### ISSUE TITLE
[android] [ios] Language names for mobile keyboards being drawn from another list

### ISSUE THREAD

**Issue by DavidLRowe** [keymanapp/keyman#1000]
This issue originally at https://github.com/keymanapp/keyboards/issues/213

@LornaSIL opened issue #213 on Keymanapp/keyboards on Mar 23

Right now when we submit a mobile keyboard, the keyboard name changes to the language name (perhaps from an Ethnologue list?).

For example, the "SIL Nubian" keyboard shows up as "Nobiin" which I believe is one of the languages it is associated with.

The "Jorai" keyboard shows up as "Jarai" which is not actually the preferred name by the people I've been working with on the keyboard.

Is there any way we could change this, either by editing the language list Keyman is using, or by putting it in the keyboard_info file to overwrite the default language name?

@mcdurdin commented on Mar 25

Right, this is a little difficult to solve at this time. I agree it is not ideal. The language names come from the Keyman API at https://api.keyman.com/cloud/4.0/languages (which themselves are drawn from ISO 639-3, Ethnologue, and BCP 47) and there are often multiple keyboards per language, which makes it hard to know which language name to pick. I think longer term we will move more to a search-based interface like we see at https://keyman.com/keyboards/ which should mitigate the issue.

For example, see the results we get for https://keyman.com/keyboards?q=jarai . Ideally, localised language names would also be brought in here.

Alternatively, we can start showing all language names including alternates in the list, but it's already a very, very long list!

Jun 18 moved to keymanapp/keyman

**Comment by darcywong00** [comment]
This might settle out in 14.0.

The language search will be driven by https://keyman.com/keyboards

and the name on the spacebar will follow the names as defined in kmp.json

**Comment by darcywong00** [comment]
Defer till later sprint when api.keyman.com rework has stabilized

**Comment by jahorton** [comment]
Did this originally address the list of keyboards to download, the name of the keyboard as shown on the picker/spacebar, or both?

**Comment by DavidLRowe** [comment]
@LornaSIL can correct me, but I think the answer is "both" (or "everywhere a language name is displayed"), even if originally the specific case was mobile keyboard name as displayed on the spacebar.

**Comment by mcdurdin** [comment]
The [online search](https://keyman-staging.com/keyboards) for 14.0 now searches against language names defined in .keyboard_info files (but will show the langtags.json primary name in some locations):

See how 'jorai' matches a language name here:
![image](https://user-images.githubusercontent.com/4498365/91795556-4ca3af80-ec61-11ea-8df0-ad8af221a0ff.png)

But when we view the details of the keyboard, it will still show the primary name from langtags.json:
![image](https://user-images.githubusercontent.com/4498365/91795582-5f1de900-ec61-11ea-9cca-ac76c21d6025.png)

**Comment by mcdurdin** [comment]
This should already be resolved for 14.0: it will show the name from kmp.json on the space bar.
