### ISSUE TITLE
bug(android): The Keyman banner flashes on the suggestion bar when selecting a keyboard from the keyboard picker menu

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#10037]
### Describe the bug

I noticed that after choosing a keyboard from the keyboard picker menu, the Keyman banner flashes on the on-screen keyboard. 

### Reproduce the bug

1. Install Keyman 17.0.214-alpha build.
2. Open the Keyman App.
3. Long press the globe key from the OSK. 
4. Select the default keyboard.

Here, I noticed that the Keyman banner flashes on the suggestion bar. 

I have attached the video file for your reference. (or Is this an expected one?)

https://github.com/keymanapp/keyman/assets/19683143/39e1b485-5552-4d18-8902-af61abdca20c

### Expected behavior

Choosing a keyboard from the menu should just show the selected keyboard without any flickering or new banner.

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.214-alpha

### Operating system

Android 12, 13

### Device

Samsung Galaxy A23 5G Mobile

**Comment by darcywong00** [comment]
@bharanidharanj can you retest on the latest alpha build and see if the issue is reproduced?

**Comment by bharanidharanj** [comment]
@darcywong00 Retested with the latest alpha (Keyman 17.0.233) build in the Android Mobile device and I was not able to reproduce it. Seems to be working fine. Thanks.
