### ISSUE TITLE
bug(mac): The Amharic keyboard is not functioning properly on the Firefox browser's Facebook search bar

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#10036]
### Describe the bug

I noticed that the Amharic keyboard failed in the Facebook Search control in the Firefox browser.

### Reproduce the bug

1. Install the latest version of Keyman 17.0.214 in macOS.
2. Download and install the gff_amharic keyboard using Keyman Configuration dialog. 
3. Log into Facebook Site. 
4. Switch to Amharic keyboard. 
5. Type tt in the search bar.  
6. Mouse-clicking between the two ታ characters. 
7. Type a. 

Here, it is showing the wrong output. 

Note: It is working as expected in Chrome and Safari browsers. 

I have attached the Screenshots for reference. 

..in Chrome browser (correct output)

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/bcfbb46d-44df-4119-a367-b330e4d1b50f">

..in Safari browser (correct output)

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/ad940495-2293-49ab-b883-1ed626fd8ab8">

..in Firefox browser (wrong output)

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/d3f0330b-d2ac-42cd-9a9e-44a461e2c1b4">

### Expected behavior

Typing tt, left-arrow, 'a' should produce ታት.

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [X] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.214-alpha

### Operating system

macOS 14 Sonoma

### Device

macMini M1 Desktop

### Keyboard name

gff_amharic

### Keyboard version

3.1.1

### Language name

Amharic

**Comment by sgschantz** [comment]
Closing, we are not receiving context from Facebook, so after moving the mouse, Keyman cannot produce the expected result.
