### ISSUE TITLE
bug(core): when calling km_core_state_get_actions, persist_options contains unexpected values

### ISSUE THREAD

**Issue by sgschantz** [keymanapp/keyman#10067]
### Describe the bug

After processing a key with Keyman Core, calling km_core_state_get_actions does not return a valid key value pair in the persist_options field as expected. 

### Reproduce the bug

1. use the Armenian Mnemonic keyboard
2. type[alt-v]
3. expected: "√"
4. type[w]
5. expected: "" -- ("√" is deleted)

This should toggle the option 'option_ligature_ew' from a value of 0 (zero) to 1 (one)

However, calling the API returns invalid values, so they will not be persisted correctly on the platform and may cause the app to crash while attempting to parse them.

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [X] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyboard name

Armenian Mnemonic

**Comment by mcdurdin** [comment]
Helps if the unit test is actually attached. Unit test, once attached, fails. So I am starting there.
