### ISSUE TITLE
chore(windows): update windows engine unit tests to match removal of engine cached context

### ISSUE THREAD

**Issue by rc-swag** [keymanapp/keyman#10071]
Work from #10065 means some the unit tests in windows engine.sln are no longer valid and need to either be updated or removed

**Comment by mcdurdin** [comment]
Should we be adding these tests to CI?

**Comment by rc-swag** [comment]
> Should we be adding these tests to CI?

Yes would be good, some of them will be removed now because the testing at the core level is sufficient for context manipulation.
