### ISSUE TITLE
bug(android): The installation of the US Basic keyboard in Keyman 17.0.217 build encountered an error

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#10084]
### Describe the bug

I observed a series of error messages while installing the US Basic Keyboard, and the installation ultimately failed.

### Reproduce the bug

1. Download and Install Keyman 17.0.217 alpha build. 
2. Open Keyman App.
3. Click Settings / Install Keyboard or Dictionary option. 
4. Click Install from keyman.com option. 
5. Type "US Basic" in the Keyboard Search bar. 
6. Install "US Basic" keyboard. 

Got "Initialization failed.." message appear on the main page followed by another error message.  Seems to be an issue. 

..Error msg1

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/690f3e19-0713-40b4-92b3-79544258f24a">

..Error msg2

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/d6c740cb-d5b0-4b02-a87f-5f37ed1d7ec0">

..Error msg3

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/22337db0-1a84-4edf-9233-bb0c46a61f7c">

### Expected behavior

Installing "US Basic" keyboard should successfully install the keyboard without showing any error message. 

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.217-alpha 

### Operating system

Android 13

### Device

Samsung Galaxy A23 5G Mobile

### Keyboard name

US Basic

### Keyboard version

1.2

### Language name

English

**Comment by darcywong00** [comment]
I've noticed several of the Keyman sites have been sluggish with network traffic lately.

I was able to install basic_kbdus on my device, but it took a while. @bharanidharanj - Maybe re-test later this week and see if the issue can be repro'd.

**Comment by bharanidharanj** [comment]
> I've noticed several of the Keyman sites have been sluggish with network traffic lately.
> 
> I was able to install basic_kbdus on my device, but it took a while. @bharanidharanj - Maybe re-test later this week and see if the issue can be repro'd.

Okay @darcywong00 . I will retest it.
