### ISSUE TITLE
bug(developer): KMD Accepts Index Out of Bounds in Large KMN Files

### ISSUE THREAD

**Issue by dyacob** [keymanapp/keyman#10083]
### Describe the bug

On line 533 of the GFF Ge'ez Manuscript Keyboard (gff_geez_emufi) the `index` has offset argument `3` which does not exist on the left-hand side of `>`:

` '።︀' + any(arabNumbersWithZero) > '.' index(arabNumbersWithZero,3)`

KMD will compile the keyboard **_without_** catching this error.  Pasting the same line into another keyboard that is less than 300 lines, the error **_is_** caught with the message:

`Error: 4032 An index() in the output does not have a corresponding any() statement`

Changing the offset value to `2` in the other keyboard,  it will compile as expected.

### Reproduce the bug

1. Open the `gff_geez_emufi.kmn` keyboad
2. `Build > Compile keyboard`
3. The keyboard will compile successfully.

The `gff_geez_emufi.kmn` keyboard is attached here as a text file.  This is from the `1.0.1` version.  The version in the main repository may update before the issue ticket is addressed.

[gff_geez_emufi.txt](https://github.com/keymanapp/keyman/files/13467269/gff_geez_emufi.txt)

### Expected behavior

Upon building the keyboard, the error message should appear:

`Error: 4032 An index() in the output does not have a corresponding any() statement`

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [X] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16.0.143

### Operating system

Windows 11 Pro (22621.1702)

### Device

Laptop

### Target application

Microsoft Word v16.77

### Keyboard name

gff_geez_emufi

### Keyboard version

1.0.1

### Language name

Ge'ez

**Comment by mcdurdin** [comment]
This puzzled me for a few minutes until I cursored through the rule and discovered an invisible character. Turns out that that rule has a variation selector in the context, so the compiler is doing the right thing. I copied and pasted the context part of the rule:

![image](https://github.com/keymanapp/keyman/assets/4498365/7625996b-ab86-4d0a-9a55-da945412ddff)

A bit of a relief because otherwise it was going to be a pretty gnarly bug!
