### ISSUE TITLE
bug(android): file association pattern is not valid -- file:*.kmp deep link

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#10095]
Per Play Store verification:

> Users will not go directly to your app from links associated with this path, but will see the app picker or be directed to the web browser. Once you have fixed these issues and published a new version, users need to update their app before the links will work.

‎file://*.*\\.kmp
com.tavultesoft.kmapro.MainActivity

Relates to https://github.com/keymanapp/keyman/blob/8d296568ce0a3d5a58660e51239f6cfef89c8e76/android/KMAPro/kMAPro/src/main/AndroidManifest.xml#L105-L134

**Comment by darcywong00** [comment]
More info from the Play Store --> Grow --> Deep Links

![image](https://github.com/keymanapp/keyman/assets/7358010/fc667074-cc5e-4b25-8fd9-9639a3be7179)
