### ISSUE TITLE
bug(core): `km_core_state_context_set_if_needed` needs more nuance for when to update cache 🌱

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#10100]
Now I am having worries about the algorithm here. There are multiple scenarios, and just want to make sure that I am covering them all.

Ignoring markers..., these are the scenarios I can see:

1. cached context identical to app context
2. cached context same length as app context but content is different
3. cached context is shorter than app context, but content is same as far as it goes
4. cached context is shorter than app context, but content is different
5. cached context is longer than app context, but content is same as far as it goes
6. cached context is longer than app context, but content is different.

I think those are the only 6 scenarios. What do we want to do for each one?

1. unchanged
2. changed, set cache to app context
3. lengthen to app context, but keep markers, consider unchanged?
4. changed, set cache to app context
5. shorten to app context, but keep markers, consider unchanged? or changed + set to app context?
6. changed, set cache to app context

We have to consider the rolling buffer that we'll have as we add new content, and that will impact whether or not the app context is longer than cache (remembering that the cached context may have markers which will shorten the overall non-marker content of it).

So number 3 and number 5 ~~6~~ need careful consideration.

Relates to #10098.

**Comment by sgschantz** [comment]
For cases 3 and 5, I would think that you would return UPDATED simply to reflect exactly what happened. Keyman for Mac is currently ignoring the result, and I don't know of anything to do with the result except log for debug purposes. I don't think the result should drive any platform logic because core is the owner of the context, and the platform needs to accept whatever the core determines.

I thought 6 was straightforward -- why does it need careful consideration?

**Comment by mcdurdin** [comment]
> For cases 3 and 5, I would think that you would return UPDATED simply to reflect exactly what happened. Keyman for Mac is currently ignoring the result, and I don't know of anything to do with the result except log for debug purposes. I don't think the result should drive any platform logic because core is the owner of the context, and the platform needs to accept whatever the core determines.

Agree that returning UPDATED makes sense for 3+5. Does the concept of keeping markers for these two scenarios make sense?

**Comment by mcdurdin** [comment]
> There is a greater chance of that happening if the app context is 1 or 2 characters long, but still seems unlikely in practice.

And I think also the downside to that happening is pretty insignificant -- keeping markers rather than clearing them -- whereas the downside to the alternative -- losing markers when we want them -- would be a real problem.

**Comment by rc-swag** [comment]
I think the most likely scenario of 5. Is cutting and pasting text to a new location in the document, cell even if in excell. Or deleting the start of a sentence. In those cases we want to keep the markers. 

For the case where they may happen to have the same context when they have just moved the cursor as @sgschantz  describes, I think it would be rare and minor annoyance if the makers resulted in unexpected behaviour.

**Comment by mcdurdin** [comment]
@ermshiperete I have assigned you per our discussion today. Please reach out if you have any questions on this.

**Comment by ermshiperete** [comment]
To sum up the results of the discussion above:

Given the test scenarios in the description, here are the expected results:

1. unchanged
2. changed, set cache to app context
3. changed, lengthen to app context, but keep markers
4. changed, set cache to app context
5. changed, shorten to app context, but keep markers
6. changed, set cache to app context

**Comment by ermshiperete** [comment]
@mcdurdin Target moved again! `km_core_state_context_set_if_needed` now sets both the internal app context as well as the cached context. This can lead to the situation that we'll update on but not the other (e.g. with the Galaxie Hebrew keyboard when typing <kbd>b</kbd>). What do we report in this case?

My suggestion would be to report the result of the cached context.

**Comment by mcdurdin** [comment]
The set_if_needed code may be simpler with the app context, because the app context should always match what the app provides. The cached context may have a different normalization form, plus includes markers, so it's not really safe to compare that.

**Comment by ermshiperete** [comment]
I know. I guess my question wasn't clear. 

In `km_core_state_context_set_if_needed` we compare the passed in new context with the app context that we have and update it if necessary.

We also compare the passed in context (after being normalized) with the cached context and update that if necessary.

`km_core_state_context_set_if_needed` returns a value whether the context got changed or remains unchanged. My question is if we return the result of the first comparison (with app context) or of the second comparison (with cached context).

**Comment by mcdurdin** [comment]
It is not terribly important because _none_ of the callers use the result except for logging. It probably makes sense to report on the app context change because that is the external surface that we are comparing against, and the cached context change really reflects internal normalization. Or we could make the return value more complicated?!

Note: whichever way you go, you may need to review unit tests because those _do_ use that status value (and perhaps that's a good argument for the additional return values?)

**Comment by ermshiperete** [comment]
I go with the cached context. For logging I think it makes more sense to report if the context changed than when it stays unchanged. The app context will not always have changed if the cached context changed, but the cached context will always have changed if the app context changed. So reporting and logging changes to the cached context will better reflect what's going on internally.

We can decide later if it would be helpful to return the status values for both contexts.

**Comment by ermshiperete** [comment]
Implemented in [epic/core/9999-normalization](https://github.com/keymanapp/keyman/tree/epic/core/9999-normalization) branch
