### ISSUE TITLE
bug(mac): amharic keyboard is not working as expected on chrome in sonoma 

### ISSUE THREAD

**Issue by Meng-Heng** [keymanapp/keyman#10116]
### Describe the bug

On Chrome search box or URL bar on Sonoma 14.0, when typing SELAMTA the actual output is ስልምት but we expect ሰላምታ.
Video of the behavior - https://drive.google.com/drive/u/1/folders/1PH0Fetyzf2Rl3L1cM3fDTeGVrp6ItCAZ

This issue does not happen on Safari v 14.0, Note, Page, Number, and Firefox v 120

### Related issues

A similar issue on Firefox - https://github.com/keymanapp/keyman/issues/10036

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [X] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16.0.141, 16.0.144 & 17.0.220

### Operating system

macOS Sonoma 14.0

### Device

Macbook Air

### Browser

Chrome 119.0.6045.199 (official build x86-64)

### Keyboard name

አማርኛ (Amharic) 

### Keyboard version

3.1.1

### Language name

Amharic

### Additional context

Keyboard link - [አማርኛ (Amharic) ](https://keyman.com/keyboards/gff_amharic)
Relevant issue - https://community.software.sil.org/t/keyman-man-not-functional-on-word/7816

**Comment by mcdurdin** [comment]
possibly related to #9506

**Comment by sgschantz** [comment]
I tested with the code from PR #10066, and this works fine. 

Note that to reproduce, we need to type the letters in lower case <kbd>s</kbd><kbd>e</kbd><kbd>l</kbd><kbd>a</kbd><kbd>m</kbd><kbd>t</kbd><kbd>a</kbd>, rather than 'SELAMTA'.

**Comment by Meng-Heng** [comment]
> Note that to reproduce, we need to type the letters in lower case <kbd>s</kbd><kbd>e</kbd><kbd>l</kbd><kbd>a</kbd><kbd>m</kbd><kbd>t</kbd><kbd>a</kbd>, rather than 'SELAMTA'.

Thank you, @sgschantz. Now both typing styles produce the same word. 
We tested 'SELAMTA' because the information they gave was written in the capital letters too. I will let them know about this on the community site.

**Comment by mcdurdin** [comment]
> Now both typing styles produce the same word.

Did you test this with latest Keyman 17?

**Comment by Meng-Heng** [comment]
Yes, I tested with this version
![image](https://github.com/keymanapp/keyman/assets/90595388/41407466-c647-47aa-9b36-f2568a53e20f)
