### ISSUE TITLE
bug(common/models): predictive-text consistency after backspaces

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#10127]
From other channels: sometimes things act... unexpectedly... in regard to predictive-text after a backspace.

From @mcdurdin's observations:  
> ...if you type "somwwhat ", press bksp, "somewhat" is not offered as an option. furthermore, any subsequent attempts to type "somwwhat" also don't offer "somewhat".
- On his device, even moving into new words doesn't fix it.

My personal attempts to repro on iOS:  I could get some approximate reproductions, though with some very fun details:
- Note:  repro is consistent when using `sil_euro_latin`, at least.  Have not vetted other English keyboards.
- Type `somwwhat`, then backspace until `somw`.  Predictions will typically fail upon typing any new character, including the original second `w`.  They _might_ appear for one character, but not after that.
- But backspace instead until `som`, deleting the earlier `w` as well.  Retyping the `w` to reach the state for the previous bullet point fails to reproduce the issue; predictions work great there and on any further typing.
- On my personal iOS device, the state reached by the first bullet point does _not_ persist after whitespace... unlike what @mcdurdin reported for his Android device.

**Comment by jahorton** [comment]
Quick note:  this issue exists both on `master` and on `feature-gestures`.

**Comment by jahorton** [comment]
Disabling the prediction-search timeout shows that the predictions would _eventually_ be generated.  The performance timeout is interfering with their generation, though.

The predictive-text engine was designed to reuse old calculations from previous suggestion requests.  After all, if adding a letter to a word, re-use of the prediction data used for that word can definitely provide a useful starting point.  The thing is... at present, when a backspace is received, that gets blocked - we have to rebuild from scratch, and layout information (including fat-finger probability data) is thrown out of the window.

So, what's the cost of rebuilding from scratch?

Using a Nexus 5 API 32 via Android Studio emulation... in one run, using a debugger on each step:

- New word: `s`:  25 'edges' evaluated; `s`-initial suggestions returned.
- New letter: `o`:  49 total 'edges' evaluated: `so`-initial suggestions returned
- New letter: `m`: 76 total 'edges' evaluated: `som`-initial suggestions returned
- New letter: `w`: 99 total 'edges' evaluated: `some`-initial suggestions returned; `w` is next to the `e`, so it's an easy correction.

If I disable the breakpoint for all but the `w`, I can get to 252 total 'edges' evaluated, with the same overall result quality.

From there...
- extra `w`: 285 total 'edges'; only two suggestions remain (`somewhere`, `somewhat`)
- backspace: hard reset; all prior edges and such are tossed out.
   - I've seen as few as only 16 (!) edges get evaluated after this hard reset.  Sometimes 41 or so, though... and that's with debugging + Android Studio emulator overhead.
    - Inspecting the state of the search...
        - `som` is considered because it matches the input.  That's all "well and good".  
        - But, `somw` isn't in the lexicon, so the engine starts attempting to typo-correct.
        - Without any layout or fat-finger data available, it doesn't know to try `e` over any other potential replacement... and picks the wrong replacement attempts, thus never reaching `some`.

For comparison, if I temporarily disable the timeout... it feels like about 0.5 sec is taken to make suggestions...
- ... with 5524 'edges' evaluated.  That's an increase of two orders of magnitude.

For contrast with the stand-alone Web test page...
- I've often seen numbers around 240 for the number of 'edges' evaluated.
    - This is enough to generate a solid set of suggestions, which is why the issue does not appear to repro from the stand-alone test page.

**Comment by jahorton** [comment]
Took a while to figure out how to find this (for WebWorkers) and extract it:

![image](https://github.com/keymanapp/keyman/assets/25213402/0c2b808f-00fb-49d0-99d0-8f5e59f88c3a)

As obtained from the standalone Web test page.  This block represents the execution time taken for processing the BKSP that would trigger the issue.

Looks like the larger portion of time is taken up by managing the search graph... and possibly by the cloning of the distance-metadata objects?  Drilling down, a lot of time is consumed within a `values` method, which is part of the downcompiled generator-function structure.

----

After a _lot_ of effort, I think we're getting significantly affected by one of the polyfills - the `Symbol.iterator` one and its cross-effects with `Array.from`.  We can actually drop the latter with just a bit of work, and locking the other one behind a check to ensure it's only applied when we _need_ the polyfill...

![image](https://github.com/keymanapp/keyman/assets/25213402/de18b3ad-36ad-4794-a4e2-8afa8526e45c)
![image](https://github.com/keymanapp/keyman/assets/25213402/8796c7e3-7b14-474f-ad23-5e4f98d35296)

That's... not a small amount of time spent just _managing_ the execution timer.  Might be worth a look at some point... but it _is_ < 10% of the runtime.  Amdahl's law says the ROI to tweak it can't be _that_ big.

**Comment by jahorton** [comment]
One thought that occurs to me - perhaps it'd be wise to create a utility to 'copy' traversed edges from the old instance, pre-backspace, over to the post-backspace graph search-tracker.  As in, rather than figuring out which edges to search... perhaps we could first pro-actively search edges that originally _were_ traversed... directly.

I'm not 100% sure this is wise, though - if backspacing toward the end of a long word, we may overrun the timer if we're not careful just by retracing prior steps.

**Comment by mcdurdin** [comment]
> For comparison, if I temporarily disable the timeout... it feels like about 0.5 sec is taken to make suggestions...
> 
> * ... with 5524 'edges' evaluated.  That's an increase of two orders of magnitude.

That seems terribly slow? That's 0.1msec/edge. Feels like we ought to be able to do much better than that?

**Comment by jahorton** [comment]
I could take some time to look into it.

My intuition tells me that it may be related to all the path-branching.  If the branching isn't terribly predictable on the assembly level, we could be hitting some notable hardware-level costs from branch-prediction failures.

For comparison, we have a heap-based priority queue.  Each pass through the system should have, at most, log(N) calls to `siftDown`, with N being the size of the heap - it's the function used to swap nodes so that heap conditions are met.

Despite that:

![image](https://github.com/keymanapp/keyman/assets/25213402/2695510c-b6b3-4e34-9175-1701825bc397)

Granted, most of the call's cost is spent computing the node probabilities involved, at multiple levels.  Interesting that it attributes 0.6ms of the runtime to the comparator's level, which is literally just a subtraction of two properties (the nested `get` entries).

As for the note evaluations...

![image](https://github.com/keymanapp/keyman/assets/25213402/a9f92941-b15f-4b8b-8a07-fe4bde8e7329)

Note how much time is spent in `step` functions - that's part of the TS generator down-compile helper stuff.  In fact, it seems like _all_ of the top-level `(anonymous)` stuff is tslib.ts helper code.

The `addMatchChar` bit?  Yeah, that's the component doing the actual computation we're focused on.  2.8 ms.  (includes 0.9 ms of GC, so 1.9ms.)  1.1 ms is spent doing search-graph chores, for a total of 3ms "core" work vs... 3.8ms on tslib code for the generator function itself.

And that's from the `buildSubstitutionEdges` level.  The `buildInsertionEdges` level puts the tslib ratio notably higher.

----

My initial take-aways from this:  
- lazy-init the 'currentCost' per node, rather than recomputing it constantly.  We're actually spending a noticeable amount of time on that, especially when a `enqueueAll` is needed, which triggers a full `heapify`, causing us to _re_compute one node's cost multiple times in some scenarios.  Between "enqueue" and "dequeue", the time cost is noticeable.
- Downcompiling generator functions to ES5 comes with a noticeable cost.

**Comment by mcdurdin** [comment]
> * Downcompiling generator functions to ES5 comes with a noticeable cost.

I think we can improve things:

1. We target ES6 (or later even?) for KeymanWeb 17. That's gonna drop the polyfills and perf cost that comes with them
2. iOS uses ES6, identical bits to KeymanWeb
3. For Android, we build two versions of KeymanWeb -- keymanweb.js (ES6, identical bits again), and keymanweb-es5.js. We dynamically choose which one to load in Android's keyboard.html based on the Chrome version found. That way, we only pay the performance cost on older devices (admittedly, we pay it twice, first by using the slower polyfills, and again by running on old CPU!)

I would like to think this is achievable with minimal pain. What do you think?

**Comment by mcdurdin** [comment]
> * lazy-init the 'currentCost' per node, rather than recomputing it constantly.  We're actually spending a noticeable amount of time on that, especially when a `enqueueAll` is needed, which triggers a full `heapify`, causing us to _re_compute one node's cost multiple times in some scenarios.  Between "enqueue" and "dequeue", the time cost is noticeable.

It'd be interesting to run this over an extended session to get more significant aggregate data -- in the range of 100x what we are seeing -- so that the differences become more marked with more significant digits in the results (or can we get results in ns?)

**Comment by jahorton** [comment]
> > * Downcompiling generator functions to ES5 comes with a noticeable cost.
> 
> I think we can improve things:
> 
> 1. We target ES6 (or later even?) for KeymanWeb 17. That's gonna drop the polyfills and perf cost that comes with them

That does come at a cost of dropping support for older Android devices for 17.  Up until now, we've been striving to maintain existing compatibility.  I'd argue less with making the call at 18 - that way, users of older devices get "one last version" - one that  supports a major new feature moving forward.  We'd probably have to do similar with the LDML / WASM stuff anyway.
 
> 3. For Android, we build two versions of KeymanWeb -- keymanweb.js (ES6, identical bits again), and keymanweb-es5.js. We dynamically choose which one to load in Android's keyboard.html based on the Chrome version found. That way, we only pay the performance cost on older devices (admittedly, we pay it twice, first by using the slower polyfills, and again by running on old CPU!)

_Oh_, you meant for standalone Web, while providing a work-around for older Android devices.  OK.  That caveat above is much less significant now, as this point would suffice for delaying in order to "make the call at [version] 18".

> I would like to think this is achievable with minimal pain. What do you think?

Uh... _that_ part is less clear - `esbuild` balks when it sees `"target": "es5"` and TS code, so the compilation linkage to do a ES6 compilation will likely take some work.  When I tried experimenting with this before, it didn't end up being super-straightforward... but I may have just been too out of energy that day to discern the right approach.  (I remember that it took me embarrassingly long that day to remember that for ES5, we `tsc` compile and then `esbuild`-bundle the `tsc` outputs, which wouldn't be needed for an ES6 compile path.)

**Comment by mcdurdin** [comment]
> That does come at a cost of dropping support for older Android devices for 17. Up until now, we've been striving to maintain existing compatibility.

Yeah ... keep reading. That was for _KeymanWeb_. For Keyman for Android, we keep the polyfilled version but with caveats as described.

**Comment by jahorton** [comment]
> > > That does come at a cost of dropping support for older Android devices for 17. Up until now, we've been striving to maintain existing compatibility.
> > 
> > Yeah ... keep reading. That was for _KeymanWeb_. For Keyman for Android, we keep the polyfilled version but with caveats as described.

> Oh, you meant for standalone Web, while providing a work-around for older Android devices. OK.

Yep.

**Comment by jahorton** [comment]
With the changes from #10274 and using its ES6 artifact, but keeping the rest of the profiling environment the same...

![image](https://github.com/keymanapp/keyman/assets/25213402/6586c39c-abd0-4a3e-9e2b-b84b766f8c8d)

That gives 11.4ms of time spent managing the timer... _way_ up from the original 3.8ms.  The backspace from `somww` to `somw` is now iterating through 500-1000 edges in 33ms.  (Variability is likely due to intermittent GC variations during the small [33ms] time window.)

With a bit more drill-down:

![image](https://github.com/keymanapp/keyman/assets/25213402/5e5ee69c-4f45-45dc-8d99-7c7dca9cced2)

+1 level...

![image](https://github.com/keymanapp/keyman/assets/25213402/832c1c42-bfb3-40fb-9dee-05fc2c07d333)

Not sure what that `set USBOutTransferResult` is, or is coming from... but the rest of it's is a _lot_ clearer.  Now we get proper functions and names that were being obscured by the downcompiled generator code... and it _also_ does seem to have taken less total runtime than its original corresponding section.

**Comment by jahorton** [comment]
That `__name` helper wraps a call to `Object.defineProperty`... and after a bit of searching... yeah, it can have performance implications:  https://humanwhocodes.com/blog/2015/11/performance-implication-object-defineproperty/

There's only one such call triggered by that constructor.  The compiled version:

```javascript
var SearchNode = class {
    constructor(rootTraversal, toKey) {
      this.toKey = /* @__PURE__ */ __name((str) => str, "toKey");
      toKey = toKey || ((x) => x);
      if (rootTraversal instanceof SearchNode) {
        let priorNode = rootTraversal;
        this.calculation = priorNode.calculation;
        this.currentTraversal = priorNode.currentTraversal;
        this.priorInput = priorNode.priorInput;
        this.toKey = priorNode.toKey;
      } else {
        this.calculation = new ClassicalDistanceCalculation();
        this.currentTraversal = rootTraversal;
        this.priorInput = [];
        this.toKey = toKey;
      }
    }
//...
```

Elsewhere...

```javascript
var __defProp = Object.defineProperty;

//...

var __name = (target, value) => __defProp(target, "name", { value, configurable: true });
```

This is being triggered once per edge / search node.  So, if we try out 500 corrections, that also means 500 `Object.defineProperty` calls.  It's also worth note that the TS code doesn't request `SearchNode` define `toKey` as a formal object property - a simple field would be fine.  But, with `keepNames` set to `true` for the `esbuild` configuration, it decides to name the passed-in function as well.

If I disable `keepNames`, that does streamline things a bit more.  Here's a profile (after that change) over the course of 10 or so keystrokes, 2 of which were backspaces:

![image](https://github.com/keymanapp/keyman/assets/25213402/45ccdc31-6ee6-4ba3-abe5-e84d70a558bb)

Interesting side bits from that:

![image](https://github.com/keymanapp/keyman/assets/25213402/a712ee71-b3ab-4d8f-9bc9-a2017800b919)

![image](https://github.com/keymanapp/keyman/assets/25213402/53b71134-e228-4e63-a292-0e7526144ef0)

This one is in regard to something previously noted:

![image](https://github.com/keymanapp/keyman/assets/25213402/3aa6a01f-be50-44eb-8c48-20aca651e4e5)

Wait a second...

![image](https://github.com/keymanapp/keyman/assets/25213402/9681b582-5a4f-47cd-8045-301dcebffce8)

(`ClassicalDistanceCalculation`)

As noted earlier, `Array.from` comes at a cost, and some new cases of said cost may be seen here.  `Array.splice` is known to be more efficient for array-cloning, so that's a quick and easy adjustment that could be made to win some gains.

And one last bit:

![image](https://github.com/keymanapp/keyman/assets/25213402/2d27d8f0-ac9b-45fa-8af6-43240f7262af)

I did think it was taking longer than expected, and I only just noticed the cause.

```typescript
```

**Comment by jahorton** [comment]
> With the changes from #10274 and using its ES6 artifact, but keeping the rest of the profiling environment the same...
> 
> ![image](https://private-user-images.githubusercontent.com/25213402/292394004-6586c39c-abd0-4a3e-9e2b-b84b766f8c8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2OTA5MDMsIm5iZiI6MTcwNDY5MDYwMywicGF0aCI6Ii8yNTIxMzQwMi8yOTIzOTQwMDQtNjU4NmMzOWMtYWJkMC00YTNlLTllMmItYjg0Yjc2NmY4YzhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA1MTAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzNGU5MWIxZmQxYmQxMjA4ZDNhZjVlZjk5OWNiMmNjZWM2ZTFkZDQzYmNmMTk4MjJiNGFiMTIyYmQ1ZjhkZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-FCV-SL0uiE3L4b7Zsl1nepiWXz_gQRTSrJtuT-eIow)
> 
> That gives 11.4ms of time spent managing the timer... _way_ up from the original 3.8ms. (Implication: the execution time of everything else has seen a dramatic improvement, so the timer code runs more often now.) The backspace from `somww` to `somw` is now iterating through 500-1000 edges in 33ms. (Variability is likely due to intermittent GC variations during the small [33ms] time window.)

After fixing the issue with the timeout loop condition, make that 1500 - 2000 edges.  That's also quite a notable improvement.

**Comment by jahorton** [comment]
After the other things already noted... the last thing I can presently see is that certain properties of search nodes that _could_ be computed based on previous nodes... aren't - they're rebuilt from scratch instead.  Yes, the arrays are typically small... but as word size grows, a word of M letters needs O(M^2) time for the properties to build across all steps taken to reach it - O(M) time to build, M times.  Dropping this to O(M) is feasible - O(1) to build, M times.  This "O(M^2)" cost likely only surfaces as a 'larger coefficient' on the true runtime complexity of each correction-search step.  Reducing this "coefficient" could still be a decent improvement, though.

The proportion of code affected is a bit hard to discern on the surface of things; the impact is somewhat scattered.  For a loose estimate, I believe that this affects no more than 1/5 of the current correction-algorithm runtime.  The 1/5 figure gives us an absolute maximum speedup of 25% if we could completely eliminate such sections (1 / 0.8, as per Amdahl's law)... and only a 11.1% speedup if we merely halve their runtime.  Quartering the runtime:  1 / .85 => 17.6% speedup, and I'd be quite surprised if we could do better than that.  It's certainly not _nothing_, but I'm pretty sure we're entering the realm of limited ROI for further optimization pursuits.

**Comment by mcdurdin** [comment]
Appreciate your analysis here @jaorton. Good work. Look forward to seeing improvements coming in based on this!

**Comment by jahorton** [comment]
We've handled a lot of this already and have decided to triage the rest of the details to 18.0, so I've spun off the extra bits to #10414 and am closing this issue for 17.0.
