### ISSUE TITLE
bug(developer): Developer does not save update to .kps when .kmn version changes

### ISSUE THREAD

**Issue by dyacob** [keymanapp/keyman#10130]
### Describe the bug

In KMD, when the version number in a KMN file is updated, _and_ the keyboard is compiled, the KPS "Source" screen will present the _updated_ keyboard version between `&lt;Keyboard&gt;&lt;Version&gt; ... &lt;/Version&gt;` tags.  However, this version number appears to be virtual and is not persisted.  No modification (the "*") is indicated on the KPS file.  Thus this KPS markup gets out of synch with the KMN file, and developers must edit the XML manually.

### Reproduce the bug

1. Open a `.kpj` file.
2. Go to the "Keyboards" tab and open the association Keyboard.
3. On the Keyboard "Details" screen, change the "Keyboard version" value.
4. On the Keyboard UI, go to: Build &gt; Compile Keyboard
5. Return to the KPJ tab, go to "Packaging" and open the associated KPS file.
6. On the KPS UI, go to "Source" and scroll to the bottom of the file.  The &lt;Version&gt; value will be identical to the new keyboard version.  Note that no modification is indicated for loaded the `.kps` file.
7. Exit KMD.
8. Open the `.kps` file viewed in KMD in a text editor, scroll to the bottom the file, the  &lt;Version&gt; value will be the previous version, or some earlier version. 

### Expected behavior

The KPS source update shown to the user should be saved on KMD exit and upon closure of the KPS window..

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [X] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16.0.143

### Operating system

Windows 11

### Device

Windows Laptop

### Keyboard name

Any

### Keyboard version

Any

### Language name

Any

**Comment by mcdurdin** [comment]
I believe this is only the case if `<FollowKeyboardVersion/>` is set, correct? If so, then the version information in the .kps is ignored by the compiler, so it is okay for it to get out of sync.

Then, this issue remains but is not really a problem because it doesn't affect the compiled output.

If what I described is not the case, let me know and I can dig deeper.

**Comment by dyacob** [comment]
@mcdurdin I'll check on the setting later today.  I later discovered that the `.kpj` file will silently update to the new keyboard version number when the `.kps` did not.

**Comment by mcdurdin** [comment]
> I later discovered that the `.kpj` file will silently update to the new keyboard version number when the `.kps` did not.

Note: the .kpj data is purely for display in the Project window so it gets refreshed automatically. Keyman Developer 17 simplifies .kpj files dramatically by not having a `<Files>` section at all -- but this is a breaking change so don't go there yet as the keyboards repo is not yet updated to work with 17.0.

**Comment by dyacob** [comment]
Just a note to confirm that the `.kps` file did not persist the version update when "Follow keyboard version" was checked in the KMD > KPS screen.

**Comment by mcdurdin** [comment]
OK, I'm going to close this as by-design. The .kps version data is irrelevant with `FollowKeyboardVersion`, as the .kmp gets its version data from the .kmn. Please reopen if you find that the .kmp has the wrong version, but I don't think this will be the case.
