### ISSUE TITLE
bug(web): The text entered is not visible in the input field after rotating the device to landscape mode on iOS

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#10139]
### Describe the bug

I observed that when switching the device from portrait to landscape orientation, the entered letters are obscured by the on-screen keyboard, and the cursor appears in front of the on-screen keyboard.

### Reproduce the bug

1. Open the [KeymanWeb Test Home](https://build.palaso.org/repository/download/Keymanweb_TestPullRequests/427855:id/index.html) link in the Safari browser. 
2. Click Example1 blue link button (from KeymanWeb Samples). 
3. Select 'Swedish' keyboard. 
4. Type 'a' into the input field. 
5. Rotate your device to a landscape (horizontal) orientation.
6. Verify that the OSK repositions itself at the bottom of the screen and occupies the full width of the device.

Here, I noticed that the typed letter 'a' is hiding behind the On-Screenkeyboard. Also, the cursor appears infront of the OSK. Seems to be an issue. 

..The text disappears when the orientation changes to landscape.

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/36403ad8-a613-42c0-bb4d-c34263529890">

### Expected behavior

The text input field should display the text clearly after transitioning the device to landscape orientation.

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [x] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.221-alpha

### Operating system

iOS 16.6

### Device

iPhone 13

### Browser

Safari 

### Keyboard name

English - EuroLatin (SIL) Keyboard

**Comment by mcdurdin** [comment]
Updated this to be under `web` because it's KeymanWeb, not Keyman for iOS.
