### ISSUE TITLE
bug(web): Output of wrong characters when typing on Armenian legacy OSK

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/keyman#10140]
When using KeymanWeb with the legacy keyboard `armenian.js`, typing on the OSK outputs the en-US characters instead of the characters on the OSK. When using the hardware keyboard with the OSK the output is correct.

Happens with stable and alpha versions of Keyman (Keyman 16 and 17)

**Comment by mcdurdin** [comment]
Are you able to test with earlier versions? Would be good to know when this broke.

**Comment by ermshiperete** [comment]
It looks like this got fixed with #10141 (alpha) and #10177 (stable).

**Comment by ermshiperete** [comment]
@bharanidharanj Did you test the stable build with the test page from #10177 (https://build.palaso.org/repository/download/Keymanweb_TestPullRequests/428624:id/testing/unminified.html)? (since we build stable only when we do a release, 16.0.144 doesn't have the fix yet)

**Comment by mcdurdin** [comment]
> @bharanidharanj Did you test the stable build with the test page from #10177 (https://build.palaso.org/repository/download/Keymanweb_TestPullRequests/428624:id/testing/unminified.html)? 

I just tested with this build and verified it works correctly.
