### ISSUE TITLE
bug(web): The connected external (USB) keyboard with the Android mobile did not produce the expected output in the text area

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#10159]
### Describe the bug

When the external (USB) keyboard was connected to the Android mobile device, the actual output did not appear in the text area.

### Reproduce the bug

1. Open [KeymanWeb Test Home](https://build.palaso.org/repository/download/Keymanweb_TestPullRequests/428269:id/index.html) page in Android mobile. 
2. Connect an external (usb) keyboard to the Android mobile device. 
3. Open Example 1 blue link button. 
4. Using the "Add a keyboard by keyboard name" section, add sil_ipa.
5. Select "sil_ipa" keyboard.
6. Type "n >" using an external keyboard in the text area.

I noticed that it shows the same letter " n >" in the text area. 

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/91c8038d-635b-4620-9ac8-152524aca842">

### Expected behavior

Typing "n >" using an external keyboard should produce ŋ in the text area. 

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Operating system

Android 13

### Device

Samsung Galaxy A23 5G Mobile, External USB Keyboard

### Keyboard name

sil_ipa

### Language name

Undetermind - IPA (SIL)

**Comment by jahorton** [comment]
Hmm... this does _not_ reproduce for me via Chrome remote-device emulation.  Testing with actual hardware may be necessary.

**Comment by mcdurdin** [comment]
> Hmm... this does _not_ reproduce for me via Chrome remote-device emulation. Testing with actual hardware may be necessary.

I would have been surprised if it did. There are a lot of variables here, and ground rule one is to test on the actual hardware.

**Comment by jahorton** [comment]
Well... this does appear to replicate in the Android app.  I guess that's both good news _and_ bad news?

**Comment by mcdurdin** [comment]
So this looks like both KeymanWeb on an Android device and Keyman for Android have the same behaviour?

Is this a regression from 16.0?

**Comment by jahorton** [comment]
Well, after a bit of digging, I think I found the logic issue behind the error, at least within the Android app:  `sil_ipa` is mnemonic, and the `<` key isn't getting mnemonic mapping.  Without the mapping, rules don't match properly.

I'd have to investigate to see if it was an issue in 16.0.

**Comment by jahorton** [comment]
... this does not reproduce on our (ancient) in-office Android test device when using an external (Bluetooth) keyboard.

Device:  SM-T350
Chrome version: 106.0.5249.126
KMW version: 17.0.241 (from #10413 - with in-app srcmaps)

**Comment by jahorton** [comment]
> So this looks like both KeymanWeb on an Android device and Keyman for Android have the same behaviour?
> 
> Is this a regression from 16.0?

I have just successfully reproduced this with Keyman for Android 16.0.144.

**Comment by jahorton** [comment]
@bharanidharanj Could you please retest this using your original repro setup outlined above with the latest 17.0 alpha build of KeymanWeb?

> ### Reproduce the bug
> 
>     1. Open [KeymanWeb Test Home](https://build.palaso.org/repository/download/Keymanweb_TestPullRequests/428269:id/index.html) page in Android mobile.
> 
>     2. Connect an external (usb) keyboard to the Android mobile device.
> 
>     3. Open Example 1 blue link button.
> 
>     4. Using the "Add a keyboard by keyboard name" section, add sil_ipa.
> 
>     5. Select "sil_ipa" keyboard.
> 
>     6. Type "n >" using an external keyboard in the text area.
> 
> 
> I noticed that it shows the same letter " n >" in the text area.

I'm wondering if something subtle might have shifted since this issue was originally made, given my most-direct repro attempt (https://github.com/keymanapp/keyman/issues/10159#issuecomment-1899523701), using an actual Android device with an actual external keyboard, failed.

**Comment by bharanidharanj** [comment]
@jahorton  Retested with the updated KeymanWeb Test page in an Android 13 Mobile device and here is my observation: 1. Connected the mobile with an externa USB keyboard. 2. Opened the Example 1 Sample page. 3. Added sil_ipa keyboard. 4. Typed "n>" and verified that it produces the correct output ŋ. Seems to be working fine. It would be better to close this issue. Thanks. 

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/e222b674-a3e4-4daf-9ab3-cf976309495d">
