### ISSUE TITLE
[KMEA] KM10 keyboard works in Keyman app, but throws "k.KFCM is not a function" in KMEA

### ISSUE THREAD

**Issue by erros84** [keymanapp/keyman#1016]
I guess I'm forging a path with end-to-end Keyman 10 keyboards. I got my KM10 Keyboards working perfectly in the Keyman Android App (keyman-10.0.403), and updated the old KM9 keyboards in my custom Android app based on the sample project. I also updated KMEA (keyman-engine-android-10.0.402) in the app.

Pressing T_XXX keys returns nothing but the error "Uncaught TypeError: k.KFCM is not a function" in the Android Studio debugger. On another Keyboard, the error thrown is "Uncaught TypeError: k.KDC is not a function"  Pressing K_XXX keys seems to only return the underlying QWERTY Key, and it's all very "freezish". Returning the kb compilation to KM9 makes things work, but I want to use KM10 features.

I tested this on emulated Android 8.1, and a physical 6.0 device. Same thing. I expect that the problem is KMEA not parsing the new formats in KM10 keyboards, and not my specific keyboard. 

Do I need to post a test case, or do you have one you can use in the harness? I would expect that the Minimal Repros you suggested in #920 would serve the purpose.

**Comment by mcdurdin** [comment]
I can't reproduce this problem here; when I build the KMSample1 app from the 403 download and plug in a Keyman 10 keyboard, everything works fine; can you attach a minimal repro to this issue?

**Comment by erros84** [comment]
I added a check to look for the version number of KMEA, and realized that the app was not grabbing 403, but an old one elsewhere. It works fine with a "real" 403. False alarm. I'm closing this issue.
