### ISSUE TITLE
feat(developer): warning/feedback about multitap + flick support limitations

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#10191]
### Is your feature request related to a problem? Please describe.

From https://community.software.sil.org/t/multi-tap-or-multitaps-not-working/8182:

> I just wanted to highlight this little fact, because today I got stuck on it. A colleague requested two keys with multi-taps, as I had provided in a previous Android system-keyboard (created without Keyman and without Keyboard App Builder).
>
> So when I found the feature in Keyman Developer, I was glad and quickly re-created our classic keyboard behaviour. And then I wasted a long time, trying to figure out why nothing is working.
>
> We are now in December 2023 and Keyman 16 (on my Android) does no longer seem to be in beta status, but I might be wrong.
> 
> Please help the developers by including a hint in the Touch Layout window, that this feature is visible but cannot be used on the user end. Thank you.

Even once #7324 lands, users of older versions of Keyman will still not be able to use the new gesture features.  This can prove extra-tricky in regard to KeymanWeb as used on websites, since that can be locally hosted by site developers in a manner that does not automatically update.

### Describe the solution you'd like

So, what I get out of this:

1.  There should be some sort of indication in the touch-layout editor about how older versions of Keyman don't actually do multitaps and such.
2.  Idea:  if a key is only reachable by multitaps and/or flicks, perhaps a warning (validation-style, but as a warning) about this may be useful.  (This also matters for accessibility, as complex gestures are less 'accessible'.)

### Related issues

#7324 
#5029

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [X] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

**Comment by mcdurdin** [comment]
This is a matter of adding a check for kmn supported version when compiling the touch layout. There is a chicken-and-egg which we have encountered previously as well -- cannot infer the kmn version when using newer features in touch layout file, because the touch layout file is compiled after the kmn.
