### ISSUE TITLE
refactor(linux): fcitx: use `km_core_state_context_set_if_needed`

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#10213]

**Comment by wengxt** [comment]
https://github.com/fcitx/fcitx5-keyman/blob/ea4a230b0dc81ab24cb07d6e1894cc7f8930e636/src/engine.cpp#L181

**Comment by ermshiperete** [comment]
https://github.com/fcitx/fcitx5-keyman/pull/5

**Comment by ermshiperete** [comment]
Updated https://github.com/fcitx/fcitx5-keyman/pull/5 with new debug method.

**Comment by ermshiperete** [comment]
Fixed in https://github.com/fcitx/fcitx5-keyman/pull/5
