### ISSUE TITLE
fix(windows): kmshell.dpr indent issue. 💽

### ISSUE THREAD

**Issue by rc-swag** [keymanapp/keyman#10235]
I solved that in Keyman Developer by moving the code into another unit and having a one line call:

https://github.com/keymanapp/keyman/blob/ff5a366c457644814385b06339ac6fb04f91ed12/developer/src/tike/tike.dpr#L309-L311

https://github.com/keymanapp/keyman/blob/3a91c7d197b99fc5bb0a82b92172fe55e1d865f7/developer/src/tike/main/Keyman.Developer.System.Main.pas

_Originally posted by @mcdurdin in https://github.com/keymanapp/keyman/pull/10156#discussion_r1423432427_

**Comment by mcdurdin** [comment]
This is also an improvement because it separates the list of units in the project from important logic. The .dpr is best when it is _just_ a list of includes with a one-line call to the implementation.
