### ISSUE TITLE
bug(android): swapping keyboards via picker in landscape results in poor kbd layout

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#10241]
From user-testing of #7324:

> * **TEST_REGRESSION_ANDROID_KBD (FAILED):** Retested with the attached PR build (Keyman 17.0.227-alpha-test-7324 in the Android Mobile device (ver 13) and here is my observation: 1. While testing  TEST_INAPP_LATIN_KEYBOARD_LANDSCAPE test in the lanscape mode the OSK shrinks it width after using the globe key. Here, What I did is :
> 1. In the Landscape mode, typed some letter using the OSK. 
> 2. Used Backspace and Enter button after typing each words. 
> 3. Clicked the globe key. 
> 4. Selected the same keyboard from the Picker menu. 
>
> Here, I noticed that the OSK shrinks its width on the Keyman home page. Seems to be an issue. 
> 
> <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/6c0eba9a-74c9-4036-9431-17126c9ebabe">

_Originally posted by @bharanidharanj in https://github.com/keymanapp/keyman/issues/7324#issuecomment-1851940191_

I have reproduced this on `master` - thus it is not a `feature-gestures` issue.  There's a chance this is related to recent ✨ Android optimizations.

Of note:  simply tapping the globe-key to swap keyboards does _not_ cause the issue.  Using the picker menu causes it.

**Comment by jahorton** [comment]
May be related to #10054.

**Comment by darcywong00** [comment]
Will re-assign when we get to that sprint

**Comment by darcywong00** [comment]
Re-opening due to @bharanidharanj 's user testing fail on
https://github.com/keymanapp/keyman/pull/10393#issuecomment-1892984859

**Comment by darcywong00** [comment]
I've debugged the issue to MainActivity.onResume()
https://github.com/keymanapp/keyman/blob/c494581117b76ac1453aa375faa9bbb99330cf86/android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java#L270-L274

Sometimes after rotating from Portrait to Landscape orientation, newOrientation incorrectly reports Portrait orientation. So the app resumes with Portrait OSK dimensions.

**Comment by mcdurdin** [comment]
Is there any public reference to this issue?

**Comment by mcdurdin** [comment]
I've found:
* https://stackoverflow.com/questions/48777084/android-activity-getresources-getconfiguration-orientation-returning-wrong
* https://issuetracker.google.com/issues/37083821?pli=1

**Comment by darcywong00** [comment]
> Is there any public reference to this issue?

Hmm, I've seen
* Issue on [Samsung devices](https://stackoverflow.com/questions/48777084/android-activity-getresources-getconfiguration-orientation-returning-wrong)
* [Issue with getResources().getConfigurtion() returns wrong value](https://issuetracker.google.com/issues/37083821) (but marked "fixed")

I haven't found recent reports.

**Comment by mcdurdin** [comment]
snap
