### ISSUE TITLE
bug(web): backspace key (special key) is different compared to return key

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#10263]
### Describe the bug

Backspace do not have confirmation on tap, similar to how it is done for Return key. Even though both are same key type, special.

https://github.com/keymanapp/keyman/assets/14062593/34268b93-157d-4e40-aa7a-f76d5e64da68

### Expected behavior

Backspace show confirmation by flashing special key active status on tap. 

### Keyman apps

- [ ] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.229

**Comment by jahorton** [comment]
Is your issue about how the BKSP key doesn't get highlighted while held?  Is that what you mean by "confirmation"?

**Comment by MayuraVerma** [comment]
> Is your issue about how the BKSP key doesn't get highlighted while held? Is that what you mean by "confirmation"?
> 
> If so, this _is_ consistent with how things worked with 16.0. Not saying that it's not something to change... just noting that it's not a regression - it "didn't break" due to the gesture rework.

Return shows confirmation of tapping by highlighting/changing the key color in blue color

backspace doesn’t have any confirmation.

**Comment by MayuraVerma** [comment]
K_LOPT, K_ENTER and K_BKSP all should have confirmation when touched.
