### ISSUE TITLE
bug(web): shift on- double tap behavior (cycling back to shift on), expected to go to "caps lock state"

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#10272]
### Describe the bug

current behavior.

**shift key from normal:**
single tap -> shift on
double tap -> caps lock

**shift key from shift on:**
_single tap -> caps state_
_double tap -> back to shift state_

Expected behavior.
**shift key from shift on:**
**_single tap -> normal_**
**_double tap -> caps lock_**

### Expected behavior

Expected behavior.
**shift key from shift on:**
**_single tap -> normal_**
**_double tap -> caps lock_**

### Keyman apps

- [X] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [X] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.231 aplha

**Comment by mcdurdin** [comment]
This is a regression I believe

**Comment by MayuraVerma** [comment]
Even the single tap behavior from "Shift on" state is wrong

Single tap from "Shift on" state should release the shift state and return to normal state.

Expected behavior.
shift key from shift on:
**_single tap -> normal
double tap -> caps lock_**

**Comment by jahorton** [comment]
> Even the single tap behavior from "Shift on" state is wrong
> 
> Single tap from "Shift on" state should release the shift state and return to normal state.
> 
> Expected behavior. shift key from shift on: **_single tap -> normal double tap -> caps lock_**

Which keyboard are you seeing this with?  I'm not currently able to reproduce some of what you're talking about here.

> Single tap from "Shift on" state should release the shift state and return to normal state.

... it does.  Unless you're doing it quickly (within half a second or so of your last tap), in which case it thinks you're still multitapping.

Also, is this within the Keyman app, or when using it as a system-wide keyboard on your device?

> Expected behavior. shift key from shift on: **_single tap -> normal double tap -> caps lock_**

Ah, okay, _that_ is a distinct point and worth considering.  It does look like that was in place during 16.0; I hadn't realized, and that _would_ be a regression.  Shouldn't be too hard to rectify with a bit of effort.

**Comment by jahorton** [comment]
In case someone beats me to it, or wants to:  

https://github.com/keymanapp/keyman/blob/a84e5202d9d9a3b2103a5a09ac868a698fdfb7cf/common/web/keyboard-processor/src/keyboards/defaultLayouts.ts#L529-L545

Add an extra "default" key spec to those.

---

https://github.com/keymanapp/keyman/blob/a84e5202d9d9a3b2103a5a09ac868a698fdfb7cf/common/web/keyboard-processor/src/keyboards/activeLayout.ts#L318C1-L337

We'd want another version for the `shift` layer in order to set shift-layer defaults.

Those two places should be the only parts in need of an update to remedy:

> Expected behavior. shift key from shift on: single tap -> normal double tap -> caps lock

**Comment by MayuraVerma** [comment]
> > Even the single tap behavior from "Shift on" state is wrong
> > Single tap from "Shift on" state should release the shift state and return to normal state.
> > Expected behavior. shift key from shift on: **_single tap -> normal double tap -> caps lock_**
> 
> Which keyboard are you seeing this with? I'm not currently able to reproduce some of what you're talking about here.
> 

iOS 17.2
Sil Eurolatin

> > Single tap from "Shift on" state should release the shift state and return to normal state.
> 
> ... it does. Unless you're doing it quickly (within half a second or so of your last tap), in which case it thinks you're still multitapping.
> 
> Also, is this within the Keyman app, or when using it as a system-wide keyboard on your device?
> 
Both Keyman and system-wide
> > Expected behavior. shift key from shift on: **_single tap -> normal double tap -> caps lock_**
> 
> Ah, okay, _that_ is a distinct point and worth considering. It does look like that was in place during 16.0; I hadn't realized, and that _would_ be a regression. Shouldn't be too hard to rectify with a bit of effort.

**Comment by MayuraVerma** [comment]
there is another small issue in the same topic

Default->Single tap->shift on->Single tap->CAPS LOCK
this happens when the time gap between two single taps are short
this Behavior is as though, after the single tap, shift key was waiting for user to complete the second tap, to accept the double tap.


it maybe timing issue

this is iOS 17.2+ Sil Eurolatin KW

**Comment by MayuraVerma** [comment]
> > this happens when the time gap between two single taps are short
> 
> Okay, sounds like that's working fine, then. Tapping a key in between would block the behavior. We do want to allow a mild delay between taps to be handled this way for accessibility reasons.

Shift on state; Single tap -> Normal 
It’s working. As along as the time gap between first and second is long enough. But this needs to be looked into. It’s timing issue.

Shift on state; double tap -> Caps lock
This needs to be resolved.  Now it’s cycling back to shift on state
