### ISSUE TITLE
bug(oem/fv): Android app keyboard-initialization error / Sentry event

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#10297]
Note:  this is only occurring within the FV app, not within the standard Keyman one.  (There _is_ a single report for the latter... over 100 builds ago, too far back to be relevant.  And for a `-local` build at that.)

Cross-reference against #10022, which added a new Java method to help smooth out the Android-engine keyboard-initialization process.  This would be called during KMW's `init` method, the one bit of stack trace showing up in the Sentry report.  

As for possible root causes... if, for some reason, the engine doesn't have keyboard info available on keyboard load when embedded within the FV app... that might cause this error event.

The PR linked above was merged in 17.0.221; related Sentry events started showing up in 17.0.222.

**Comment by jahorton** [comment]
I have noticed that there have been user tests against the FV app in the meantime, and those haven't resulted in any user test failures, it would seem.  (Example:  #10292 - no mention of a keyboard error.)  So, perhaps the error is invisible to end users?  If so, this may not be that high a priority... though it'd still be nice to clean things up.

**Comment by jahorton** [comment]
Worst-case:

https://github.com/keymanapp/keyman/blob/7c9061e869be3b52c19f1d13d82d29189b04699a/android/KMEA/app/src/main/assets/android-host.js#L36

Throwing a `try-catch` around that should be enough to silence the error... though I'd still prefer to determine the root cause and see if that exposes any other issues.

**Comment by mcdurdin** [comment]
Yes, agree, let's not paper over the root cause. Especially since it's from a recent change.
