### ISSUE TITLE
bug(windows): Images included in the "readme.htm" file are not displayed in the "Read me" tab during the installation process.

### ISSUE THREAD

**Issue by anvalon** [keymanapp/keyman#10308]
### Describe the bug

If I write the following code in the "readme.htm" file, the "flag.png" image is not displayed in the "Read me" tab during the installation process.

```
<body>
    <img src="flag.png">
</body>
```

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [x] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16.0.144

### Operating system

Windows 10

### Keyboard name

eo_plus

### Keyboard version

1.0

### Language name

espseranto

**Comment by Meng-Heng** [comment]
### Extra information

- This issue was discussed on the[ community site](https://community.software.sil.org/t/images-not-showing-in-readme-file/8238)

- Image of what the error would look like: ![image](https://github.com/keymanapp/keyman/assets/90595388/d0d33960-e4dd-4f6d-9d42-1c7d3a0a6982)

**Comment by mcdurdin** [comment]
Repro keyboard project: [readme_images_10308.zip](https://github.com/keymanapp/keyman/files/13816324/readme_images_10308.zip)

**Comment by mcdurdin** [comment]
#10312 has a fix for this issue, will be available in version 17.0. So go ahead and include the flag image in your readme and when 17.0 is released in the next couple of months it will 'just work'.
