### ISSUE TITLE
feat(developer): regex: support ranges 🙀

### ISSUE THREAD

**Issue by srl295** [keymanapp/keyman#10316]
> … If I have a transform from [\u{00E8}-\u{00EB}] (èéêë) to [\u{00EC}-\u{00EF}] (ìíîï), how will that work with decomposition? Do we need to expand ranges (beware 0020-10FFFF)?

Note that actually we don't transform TO a range.  That would be a Set which is well-defined here.

but the matching is still an issue to solve in this ticket.

This is under _core_ because it has to be handled on the core side.

Split from [#9468](https://github.com/keymanapp/keyman/issues/9468)
Supports [#9121](https://github.com/keymanapp/keyman/issues/9121)

**Comment by srl295** [comment]
- [ ] Warn on use of precomposed ranges, i.e. [é-É] could exceed limits and, might not even be intended?

**Comment by srl295** [comment]
Icu can support `\Uhhhhhhhh` escapes, so this can be a pass-through if ther'es no decomposition:   `[\U00000-\UFFFFFF]`

**Comment by mcdurdin** [comment]
Idea: we decide to not decompose any characters represented within ranges. This means that some characters will never be matched, but it's not going to break things. There will be some benefit, e.g. allowing large ranges, allowing out-of-alphabet matches (negative matches) etc.

So if we decide not to decompose characters within ranges, then we will end up with something like:
`/èéêë[^èéêë]/` ==> `/e\U00301...[^èéêë]/` or `/e\U00301...[^\U00eb...]/`

**Comment by srl295** [comment]
- HINT if the range crosses non-NFD
- WARN if the range starts or ends with non-NFD

**Comment by mcdurdin** [comment]
This should make the Core changes minimal, correct? Because we no longer need to convert to a Set.

**Comment by mcdurdin** [comment]
Changing this to be a Developer issue. We can push this one into beta if it's only hints and warnings. If there is other work to be done, can you detail that here @srl295?
