### ISSUE TITLE
chore(linux): Update sentry-python package

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/keyman#10332]
[sentry-python](https://tracker.debian.org/pkg/sentry-python) is marked for autoremoval in Debian because of Debian bug [#1058422](https://bugs.debian.org/1058422).

Because sentry-python is a dependency of Keyman this will also cause Keyman to be removed, so we should work on updating sentry-python.

**Comment by mcdurdin** [comment]
Per that link:

> We believe that the bug you reported is fixed in the latest version of sentry-python, which is due to be installed in the Debian FTP archive.

Do you propose to make it an optional dependency or what?

**Comment by ermshiperete** [comment]
sentry-python got updated by the community in the meantime, so there's no need for us to do anything at this point.
