### ISSUE TITLE
[web] KMW can't handle "default layers" other than Shift

### ISSUE THREAD

**Issue by erros84** [keymanapp/keyman#1037]
This section looks like a holdover from KM9, it disallows using layers like rightalt and rightalt_shift (and gaining from the "default layer" property). I believe it should be expanded for KM10.

To reproduce:
1. Add a layer to Touch called `rightalt`.
2. add a key to that keyboard with "default layer" as the modifier.
3. Test on web and you get this error switching to the `rightalt` layer:
 `KMW only defines default key output for the 'default' and 'shift' layers! osk.defaultKeyOutput @ kmwosk.ts:918`

https://github.com/keymanapp/keyman/blob/93a206027d6f919062459fa4edbd5d0e9d858e65/web/source/kmwosk.ts#L918

**Comment by mcdurdin** [comment]
What default output are you expecting for the `rightalt` key? KMW does not have full support for mnemonic layouts in version 10, so it expects the base layout to be US English.

**Comment by erros84** [comment]
I get it now. I set a breakpoint in Chrome and it turns out this error was related to some of my modifier keys on the rightalt-shift-nocaps layer, like K_SHIFT not having a NCAPS+RALT state, I set all of the modifier keys modifiers to default and negated the error. The letters were working fine. Closing this report.
