### ISSUE TITLE
bug(developer): special key text in key hints does not render with the OSK Symbol font

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#10372]
From #10371.

> While subkeys were already being adequately styled, I recently realized that hints were not considering such shortcuts. For the record, Developer doesn't either:

![image](https://github.com/keymanapp/keyman/assets/4498365/25f7a9af-a44f-48e1-b219-94887a7a6522)

**Comment by jahorton** [comment]
`sil_euro_latin` - % subkeys on numeric layer.
