### ISSUE TITLE
bug(windows): the installation file got corrupted

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#10412]
### Describe the bug

Original post: https://community.software.sil.org/t/kmshell-16-0-144/8300.

But report: https://keyman.sentry.io/issues/4263572464/events/7f110eec6bb94160a5a4d4623020f094/?project=5983523&referrer=issue-list&statsPeriod=7d

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [X] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16.0.144

### Operating system

Windows 10 Home 22H2

### Device

Windows machine

**Comment by mcdurdin** [comment]
@rc-swag fyi

**Comment by rc-swag** [comment]
Closing issue due to being a file corruption issue
