### ISSUE TITLE
bug(web): layout font size not being properly applied

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#10444]
When replying to https://community.software.sil.org/t/change-font-size-of-mobile-key-caps/8305/, we found that the 'proper' way to set fontsize for a layout isn't being handled properly by Keyman Engine for Web; at a minimum, it's getting overwritten whenever the OSK's layout is refreshed.

**Comment by mcdurdin** [comment]
The other way to set font size is with CSS, which some other keyboard devs have done in the past. Not recommended though, because it's hard to maintain compatibility!

**Comment by jahorton** [comment]
Very closely associated with, if not a duplicate of, #9837.
