### ISSUE TITLE
[iOS] bottom row not getting painted correctly

### ISSUE THREAD

**Issue by tombogle** [keymanapp/keyman#1045]
I'm seeing an annoying display problem on my iPad mini 4, any time I return to the main Keyman screen after going to the Keyboards screen. At first I thought it was just a Simulator problem, but I'm also seeing it on my physical device. In portrait mode, only the top 10% of the bottom row gets painted. Below that, it's just a gray bar. In landscape mode, about the top third gets painted. Switching from portrait to landscape or vice verse corrects the problem, but if I ever go back into the Keyboards screen, the problem returns.

**Comment by tombogle** [comment]
![screen shot 2018-07-02 at 3 52 56 pm](https://user-images.githubusercontent.com/4229598/42183497-0c9205ac-7e10-11e8-9045-f93813dbdbc7.png)

**Comment by tombogle** [comment]
Different problem, but at least as bad on iPad Pro 12.9 (2nd gen):
![screen shot 2018-07-02 at 3 57 03 pm](https://user-images.githubusercontent.com/4229598/42183650-ae141faa-7e10-11e8-9271-a74c05c271af.png)

**Comment by mcdurdin** [comment]
I think this relates to the constraints fixes I made recently. I saw this issue once, but only once when I was testing and I wasn't able to repro.

I think this needs to be fixed in 10.0 Stable. 

Tentative workaround: dismiss the keyboard (e.g. open the Info menu) and reopen it.

**Comment by tombogle** [comment]
In my current round of testing, it seems that switching to the Keyboards screen and then clicking Cancel is fine the first time. Doing it a second time in succession (i.e., without switching to a different keyboard) causes the parent (this is a weak reference property) to become nil, so then the code falls back to using a hard-coded 100 as the height. Since the keyboard is not visible when the Keyboards screen is, it kind of makes sense that it would be removed from the view hierarchy and lose its parent. But by that logic I'd kind of expect it to happen the first time as well. I tried changing dismissKeyboardPicker to always call reloadKeyboard, but that made it even worse - the keyboard area just paints as an empty gray rectangle. I'm pretty lost in this code.

**Comment by tombogle** [comment]
This just in: Changing the dismiss call to _not_ be animated seems to fix the problem. Not sure if it's as simple as that or what the downside is of not animating. Apparently it is sometimes throwing an exception in the code that handles the animation. Almost certainly a bug in the way we've done the plumbing in Keyman, but it could take a while to figure out what's actually wrong.

**Comment by tombogle** [comment]
Possible (vague) hypothesis: maybe the cancel button is getting hooked up each time the Keyboards screen is displayed, so the second time, it tries to dismiss the view twice. Probably not, but I'm shooting in the dark.

**Comment by tombogle** [comment]
Worth noting: on iPad 9.7 (tested in Simulator and hardware), the display problem happens over and over. On a 10.5 (tested only in Simulator), it happens only once. After that, if you click cancel again, Keyman crashes (NSException thrown).

**Comment by tombogle** [comment]
When dismiss is animated, for some reason the parent of KeymanWeb changes (during the animation). If the resize happens at a point when the parent is nil, then the default height of 100 is used. I tried putting in a flag to delay the resizing until after the dismiss completes, but then the new (apparently incorrect) parent has a height of 0, so the keyboard doesn't paint at all. I changed the height-calculation logic to use the platform defaults, and that makes it look good, but on the 10.5" iPad, it still crashes on the 3rd go-round when it performs the view hierarchy check. I have no idea why this check isn't detecting a problem on the 9.7" iPad. There's obviously some kind of plumbing problem.

**Comment by tombogle** [comment]
Potentially useful links to other people's problems:
https://stackoverflow.com/a/33174863/1532072
https://stackoverflow.com/questions/25761953/terminating-app-due-to-uncaught-exception-uiviewcontrollerhierarchyinconsistenc/25991425
https://stackoverflow.com/questions/31693133/becomefirstresponder-cause-crash-uicompatibilityinputviewcontroller
https://github.com/soffes/SAMTextView/issues/25

**Comment by tombogle** [comment]
This post looks like a _possible_ solution, but it's fairly complex: https://kerrick.wordpress.com/2017/06/29/fixing-_addchildviewcontrollerperformhierarchychecknotifywillmove/

**Comment by jahorton** [comment]
Of note is that this is likely tied to the in-app keyboard's use of the _system_ keyboard's display window.  (At minimum, affected by.)  I've seen very similar display issues result after a system-level overlay temporarily covered part of the keyboard's screen space.
