### ISSUE TITLE
Keyman Desktop failed to start

### ISSUE THREAD

**Issue by lssoffice** [keymanapp/keyman#1047]
I got this error in a Windows 7 VM today.  Any ideas what we can do to fix it?

![keyman desktop failed to start](https://user-images.githubusercontent.com/34051173/42203437-17128bdc-7ee2-11e8-9e85-bec7bc24e021.PNG)

I checked and the keyman.exe file it is referencing exists.  When I tried manually starting it, it just said, "A referral was returned from the server."

I tried to start Keyman Desktop again and it didn't work.  I didn't try restarting the computer, if that might help...

Is there a minimum .NET Framework needed?  I can't find documentation regarding that, so don't know if that is the problem.  I think they're running .NET 4.5.1 (sorry, the computer is not in front of me anymore).

Thanks,

James

**Comment by mcdurdin** [comment]
This error is a Windows error that arises when a file that requests a specific permission does not have a valid certificate. Is it possible that the root certificate store on the VM is very out of date?

You can check the certificate on the executable by right-clicking on keyman.exe and selecting Properties, Digital Signatures tab. You should see two signatures listed for SUMMER INSTITUTE OF LINGUISTICS, INC, one sha1 and one sha256. Clicking on one of the certificate entries and selecting Details will show you the certificate and whether or not it is valid.

Technical note:

The manifest file for keyman.exe requests `uiAccess='true'` which will be denied if the executable does not have a valid certificate:
```
	<trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
		<security>
			<requestedPrivileges>
				<requestedExecutionLevel level="asInvoker" uiAccess="true"/>
			</requestedPrivileges>
		</security>
	</trustInfo>
```

Without this permission, Keyman is unable to provide keyboard services to elevated applications.

**Comment by lssoffice** [comment]
It's very possible the root certificate store is out of date.  I saw a
related message on the same VM when we tried to install Keyman 9:

[image: Keyman Desktop failed to start.PNG]
​

Do you have instructions how to update the root certificate store?

**Comment by mcdurdin** [comment]
Instructions on updating the root certificate store for all operating systems is available at https://support.microsoft.com/en-us/help/2813430/an-update-is-available-that-enables-administrators-to-update-trusted-a -- download links are at the bottom of the document.
