### ISSUE TITLE
chore(ios): invalid bundle - App Store Connect notification 

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#10495]
App Store Connect
 
Dear Developer,

We identified one or more issues with a recent delivery for your app, "Keyman" 17.0.250 (1.0). Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90109: This bundle is invalid - The key UIRequiredDeviceCapabilities in the Info.plist may not contain values that would prevent this application from running on devices that were supported by previous versions. Refer to QA1623 for additional information: https://developer.apple.com/library/ios/#qa/qa1623/_index.html

After you’ve corrected the issues, you can upload a new binary to App Store Connect.

Best regards,

The App Store Team

**Comment by sgschantz** [comment]
Comparing the info.plist file for Keyman 17.0.250 to builds of different versions (16.0.144 and 17.0.255) that do not receive the error, there is not a clear explanation for the error. For the key 'Required Device Capabilities', all three versions have the same value 'arm64'.

Based on some comments I read online, it seems this may be a spurious error and there is nothing to fix. Reassigning to 18 and will close if it does not occur again.
