### ISSUE TITLE
chore(web): CI builds are currently extremely unreliable

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#10494]
Over the last month, we have had over 50 failed builds which are due to timeouts or similar and seem to be related to BrowserStack calls?

This is adding a _lot_ of noise to otherwise good pull requests. Recommendations:

1. Move /common/web modules that are KeymanWeb-exclusive into /web
2. Disable BrowserStack tests entirely unless /web files are touched.
3. Try and find out what is going wrong -- add retries/robustness etc.

**Comment by mcdurdin** [comment]
Notes:

* it seems that some BrowserStack sessions are getting a plain major.minor.patch version number and others are getting a full major.minor.patch-x-y-pr version number. Could this be related to the agent triggering it? Could multiple agents running web builds at the same time be related?

**Comment by mcdurdin** [comment]
See also:

https://github.com/keymanapp/keyman/blob/c9fac1b944e516ffdc6de6f193162e97b74d2ac7/web/test.sh#L34-L50

Why is this not working?

**Comment by mcdurdin** [comment]
The BrowserStack tests with full version information are under @jahorton's username. The ones with only major.minor.patch are under the Keyman Server username (i.e. running from CI).

So ... something is different in how they are being triggered.

**Comment by jahorton** [comment]
> The BrowserStack tests with full version information are under @jahorton's username. The ones with only major.minor.patch are under the Keyman Server username (i.e. running from CI).
> 
> So ... something is different in how they are being triggered.

In case this is something we have to triage and get back to later... I haven't directly run BrowserStack tests from my machine in months.

I remember that early on, I think my log-on details were used to set up BrowserStack CI... and then we changed the details to use Keyman Server stuff.

**Comment by mcdurdin** [comment]
> The BrowserStack tests with full version information are under @jahorton's username

JH noticed that the LMLayer test configuration has a different username

**Comment by jahorton** [comment]
Toward the bottom of the logs BrowserStack had available, we were able to determine that in stable-16.0, _both_ sources of unit tests - KMW and the LMLayer - had full version strings pass through.  (And my name, not `keyman-server`.)

We have not yet determined... where it's even getting the version string from.

**Comment by jahorton** [comment]
Thought I'd put the comment here, but I can't find it, wherever it did land.

Useful reference: https://github.com/actions/runner-images/issues/3737

A specific comment of note:  https://github.com/actions/runner-images/issues/3737#issuecomment-2037491602

There's a recent npm fix that may be notably related.  Updating to 10.5.2 or higher would give us that fix.

**Comment by mcdurdin** [comment]
> Thought I'd put the comment here, but I can't find it, wherever it did land.

#10350.

**Comment by jahorton** [comment]
With #11456 and #11451 in place, this issue is probably resolved for now.  It's also believed that #8616 was related; @mcdurdin mentioned finding something about use of `git://` entries in package.json sometimes contributing to npm instability.  (Sadly, I can't find where he posted a reference about it, but it was certainly mentioned in our discussions in other team channels.)

Granted, there may be a minor flare-up when we get to #11501... but we should be able to limit the scope of those tests and keep things stabler than before, even then.

**Comment by jahorton** [comment]
At this point, the only instabilities I'm seeing on `master`-based PRs is from the test builds for our other products, rather than from testing Keyman Engine for Web itself.  This doesn't fix `stable`, but I still consider it enough of a win to close this issue.

**Comment by mcdurdin** [comment]
> @mcdurdin mentioned finding something about use of `git://` entries in package.json sometimes contributing to npm instability. (Sadly, I can't find where he posted a reference about it, but it was certainly mentioned in our discussions in other team channels.)

I wrote on Slack:

> So removing the two git-based dependencies from package.json reduces the npm i time from 4 minutes to 13 seconds on my machine. Seems like that is a very poorly supported mechanism.

Certainly I concur that the issues appear to be pretty much resolved, hurrah (except `stable` as you note, which would be a bit hard to patch)
