### ISSUE TITLE
chore(common,developer): copy cldr license 🙀 

### ISSUE THREAD

**Issue by srl295** [keymanapp/keyman#10491]
- cldr license should be copied into the resources dir
- cldr license should be published
- icu license should go with kmcmplib and publication with kmc/etc
- both should end up in the .msi for developer see #10489

**Comment by mcdurdin** [comment]
Has to go into keymandeveloper.msi, kmcomp.zip, and kmc on npm.

**Comment by srl295** [comment]
https://[unicode.org/license.txt](https://unicode.org/license.txt)

**Comment by mcdurdin** [comment]
kmcomp.zip is still built in a CI script, so will need to be done after PR for this is merged to master, for 17.0. (TODO: move these scripts into the repo!)
