### ISSUE TITLE
bug(linux): Reordering doesn't properly work with Khmer Angkor in LO Writer on Ubuntu 23.10

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/keyman#10510]
Type <kbd>x</kbd><kbd>E</kbd><kbd>j</kbd><kbd>m</kbd><kbd>r</kbd> in LibreOffice Writer (make sure _Khmer Mondulkiri_ font is selected).

Expected output: 
        ខ្មែរ

Actual output: 
![Screenshot from 2024-01-25 15-08-30](https://github.com/keymanapp/keyman/assets/181336/5ebb0237-e3e9-42d1-bf5d-cea41225e095)

Ubuntu 23.10 Mantic
Keyman 17.0.251-1~sil1-mantic
(LO 7.6.4.1)

Works on Ubuntu 22.04 Jammy (LO 7.3.7.2)

**Comment by ermshiperete** [comment]
Same problem on Ubuntu 24.04 with LO 24.2.0.1 (both X11 and Wayland)

When using LO we get `supports_prefilter=0` and that it doesn't support surrounding text even though the patched ibus is installed. Older versions of LO support surrounding text.

**Comment by ermshiperete** [comment]
The reason is trivial: I had installed only `libreoffice-writer`. That didn't install `libreoffice-gtk{2|3|4}` which brings the necessary integration with GTK/ibus.

The solution is to either install the full `libreoffice` package, or install `libreoffice-gtk3` or `libreoffice-gtk4` together with `libreoffice-writer`. Then things work.

**Comment by mcdurdin** [comment]
Do we need to document this fix in our knowledge base? Seems like it could trip up other users

**Comment by ermshiperete** [comment]
https://github.com/keymanapp/help.keyman.com/pull/996
