### ISSUE TITLE
bug(linux): Generation of help docs keep overwriting each other

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#10551]
There's been a churn on Keyman for Linux help docs automated PRs

https://github.com/keymanapp/help.keyman.com/pulls?q=is%3Apr+is%3Aclosed+linux

where they seem to overwrite previous PRs as they go back and forth between Markdown `__optional__`  to `### options:`

From @mcdurdin 
> says this sounds like two different build agents with different versions of tools?

**Comment by ermshiperete** [comment]
The PRs get generated by the TC KeymanLinux_Master build. It seems that ba-bionic64ta and ba-jammy-64-ta produce different output.

**Comment by ermshiperete** [comment]
The reason are different Python versions. On ba-bionic64ta `km-config --help` outputs `optional arguments:`, on ba-jammy-64-ta `options:`.

Limiting the build to ba-jammy-64-ta.
