### ISSUE TITLE
test(android): Regression Test Report 17.0.238-Alpha(6 failures)

### ISSUE THREAD

**Issue by sillsdev-dondillard** [keymanapp/keyman#10598]
```
Test Report for Keyman 17.0.238 Alpha Android
Results 

 Expected Start Date 1/22/2024
 Actual Start Date 1/22/2024

 Overall Results: 98% (106/108 passed)

Regression Tests
 Android                   98% (106/108 passed)
``` 
Issues Found
* #8557 
* #7173

**Comment by jahorton** [comment]
@bharanidharanj 

We're going to need more detail on the #7173-related failure.  How consistent is the failure, and under what conditions does it happen?  I'm not getting a consistent repro on the devices I'm testing with.

**Comment by mcdurdin** [comment]
Reopening to track the #7173 failure

**Comment by mcdurdin** [comment]
OK, makes sense to track #7173 in #10608 and close this one. Please continue discussion in #10608.
