### ISSUE TITLE
docs(android): update banner documentation

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#10629]
We need to refresh any references to the banner and document the usage of it with the changes in v17.

See also #10630.

**Comment by jahorton** [comment]
Possibly relevant images - from android/help/android_images:
- [dist-install1-ap.png](https://github.com/keymanapp/keyman/blob/c56215f799e63d114258c920f2139aaeda41dc17/android/help/android_images/dist-install1-ap.png)
- [dist-install1-at.png](https://github.com/keymanapp/keyman/blob/c56215f799e63d114258c920f2139aaeda41dc17/android/help/android_images/dist-install1-at.png)
    - We now have a lexical model for this keyboard, but these images don't have an active banner.
    - ... also, the fact that there _isn't_ an active banner itself is an issue, since we always have one now.
- [dist-storage-permission-ap.png](https://github.com/keymanapp/keyman/blob/c56215f799e63d114258c920f2139aaeda41dc17/android/help/android_images/dist-storage-permission-ap.png), [dist-storage-permission-at.png](https://github.com/keymanapp/keyman/blob/c56215f799e63d114258c920f2139aaeda41dc17/android/help/android_images/dist-storage-permission-at.png)
    - bannerless EuroLatin (even if it _is_ in the background)
- [settings1-ap.png](https://github.com/keymanapp/keyman/blob/c56215f799e63d114258c920f2139aaeda41dc17/android/help/android_images/settings1-ap.png), [settings1-at.png](https://github.com/keymanapp/keyman/blob/c56215f799e63d114258c920f2139aaeda41dc17/android/help/android_images/settings1-ap.png)
    - Has an actual, active banner.
- Likewise, [settings2-ap.png](https://github.com/keymanapp/keyman/blob/c56215f799e63d114258c920f2139aaeda41dc17/android/help/android_images/settings2-ap.png), [settings2-at.png](https://github.com/keymanapp/keyman/blob/c56215f799e63d114258c920f2139aaeda41dc17/android/help/android_images/settings2-ap.png)
- [settings7-ap.png](https://github.com/keymanapp/keyman/blob/c56215f799e63d114258c920f2139aaeda41dc17/android/help/android_images/settings7-ap.png), [settings7-at.png](https://github.com/keymanapp/keyman/blob/c56215f799e63d114258c920f2139aaeda41dc17/android/help/android_images/settings7-ap.png)
    - No banner... for a keyboard that should have one.
    - settings6* is similar, but is cropped to _just_ the keyboard... so settings6* images are probably fine.
- [settings-suggestions-ap.png](https://github.com/keymanapp/keyman/blob/c56215f799e63d114258c920f2139aaeda41dc17/android/help/android_images/settings-suggestions-ap.png)
    - There is no `at` variant that I could see.

**Comment by darcywong00** [comment]
Fixed by #10691  #10726 and #10796
