### ISSUE TITLE
docs(ios): using new gestures

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#10628]
v17 includes new gestures. We should have user documentation for this.

See also #10627 for Android.

Use the keyboard sil_euro_latin.kmp located [here](https://jahorton.github.io) to document the new gesture behavior.

More technical detail is available in #5029.

**Comment by jahorton** [comment]
My current thoughts / outlines toward docs for this:

- Longpresses
    - if the key does not have an upward flick defined, you can quickly display the subkey menu with an up-flick.
* Modipresses
    - Like a longpress, but for a whole layer.
    - Once activated, the layer will be locked, unable to change, until you release the held layer-switching key.
    - Longpresses may be activated during a modipress.
    - You will always be returned to the layer that was active before the modipress began.
* On flicks:
    * Flick gestures work by...
        1. Pressing a key...
        2. ...then moving / dragging the touchpoint in the general direction of the flick.  
            - Input even 60 degrees off on either side of the "correct" direction will still work... unless there's a closer flick than the one you intend.
        3. After moving up to about half a key's width, a flick animation will start - the text for either the key or its preview will begin to "slide" in the direction of the flick that has been detected.
        4. Either return to your starting location to reset the flick and try again with a different direction...
        5. Or continue the motion, ideally in the direction of the slide animation, until the flick preview text is near the center of the key or preview, then release.
* Multitap
    - Modipress-multitap is possible - you can end a multitap by holding the last tap and use the resulting layer as a modipress if the layer changed.
    - Supports 'rota' behavior - you can continue tapping to return to the initial tap's output and continue in a cycle from there.

Anything else worth mentioning?

Also... I'm not exactly sure where this should go in the apps' help indices.  There's no good matching page - I think the "best" equivalent would be parts of the "Using the Menu" pages... which themselves could use a rework, I think.

**Comment by mcdurdin** [comment]
@jahorton your notes cover all the bases that I can think of for gestures. Good work.

I think we should give a basic, quite short, overview of gestures first, as many users may be overwhelmed by the details of each gesture. The detailed gesture reference will definitely be helpful for supporting users who have questions or for those who wish to learn all the possible methods of interaction with the keyboard.

In the overview, we need to define what each gesture is and very simply what it does (without going into the nuance) -- we are used to the terms 'longpress', 'multitap', 'modipress' etc but users may not understand those. Something like this:

> You can use gestures to interact with some keys on the keyboard. Keys which have gestures available will normally show them as a hint in the top right of the key:
> * **Longpress:** you can press and hold a key, and after a moment a submenu will appear. You can slide your finger to the submenu, and when you release it, the highlighted key from the submenu will be output.
> * **Flick:** you can hold and slide in various directions on a key to reach alternate outputs. The key will animate to show you the expected output. A common flick is to slide down to reach numerals on the top row of the keyboard.
> * **Multitap:** some keys allow you to press them repeatedly, rapidly, to reach alternate outputs. Tapping rapidly twice on <kbd>Shift</kbd> will activate <kbd>Caps Lock</kbd> on many keyboards.

My thinking is that modipress does not need to be mentioned in the overview -- it's an optimization rather than something users need to know to use the keyboard successfully (I have avoided using the term 'modipress' because it's a little more esoteric a term than either 'longpress' or 'multitap' for end user docs IMO). We may need more detail than this, but it could go in a "Gesture hints and tips" section?

> * Hold on a _layer switching key_ such as <kbd>Shift</kbd> to temporarily switch to that layer. With another finger, tap on one or more keys on that layer. When you release the layer switching key, the keyboard will return to the previous layer.

**Comment by jahorton** [comment]
> I have avoided using the term 'modipress' because it's a little more esoteric a term than either 'longpress' or 'multitap' for end user docs IMO

That's entirely fair.  I only 'coined' it for internal use, using it because I felt "modifier longpress" would be a mouthful with how often we'd refer to it and talk about it during gesture development.  Even then, "modifier longpress" itself is probably a metaphor at best, since "modifiers" aren't really a touch-OSK thing anyway.

> > * Hold on a _layer switching key_ such as Shift to temporarily switch to that layer. With another finger, tap on one or more keys on that layer. When you release the layer switching key, the keyboard will return to the previous layer.

* Hold on a _layer switching key_ such as Shift to temporarily switch to `, and "lock in",` that layer.  With another finger, tap on one or more keys on that layer.  When you release the layer switching key, the keyboard will return to the previous layer.  `While the layer-switching key is held, any other layer-switching behavior will be blocked.`

Figured I'd add a _bit_ more detail, since the whole "layer locking" thing may not be 100% intuitive to everyone.
