### ISSUE TITLE
docs(ios): update banner documentation

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#10630]
We need to refresh any references to the banner and document the usage of it with the changes in v17.

See also #10629.

**Comment by jahorton** [comment]
Possibly relevant images - from ios/help/ios_images:
- [dist-install1-i.png](https://github.com/keymanapp/keyman/blob/c56215f799e63d114258c920f2139aaeda41dc17/ios/help/ios_images/dist-install1-i.png)
    - Amharic has a lexical model now.
- [no-banner.png](https://github.com/keymanapp/keyman/blob/c56215f799e63d114258c920f2139aaeda41dc17/ios/help/ios_images/no-banner.png)
    - Should probably be eliminated now that there's always a banner.

There are a couple of other images that show the image banner in use for keyboards that actually have predictive text:
- [banner.png](https://github.com/keymanapp/keyman/blob/c56215f799e63d114258c920f2139aaeda41dc17/ios/help/ios_images/banner.png)
- [system-picker-i.png](https://github.com/keymanapp/keyman/blob/c56215f799e63d114258c920f2139aaeda41dc17/ios/help/ios_images/system-picker-i.png)

**Comment by jahorton** [comment]
My current thoughts for "things to highlight":

* The banner can slide when a touch is held down if the sum total of their width doesn't fit.
* Overly long suggestions are partially hidden, but expand when touched.
* If a suggestion is selected as a side effect of scrolling the banner, it will not be applied when scrolling is complete.
