### ISSUE TITLE
bug(android): typing rapidly can lead to stuck keys

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#10646]
Keyman 17.0.256-alpha on Android, Samsung A53/5G phone, Android 14

In this example, the <kbd>p</kbd> key gets stuck after the first one or two seconds. Note that it also does not appear to be emitted to the document. I see this quite often with spacebar, not sure if that's a useful hint?

https://github.com/keymanapp/keyman/assets/4498365/b975dd60-876c-402d-8b06-e4128b735047

No, I am not attempting to type precisely or use suggested corrections for this video. :grin:

**Comment by jahorton** [comment]
See also #10592.

**Comment by jahorton** [comment]
> I see this quite often with spacebar, not sure if that's a useful hint?

See also #10640.

**Comment by darcywong00** [comment]
Unassigning myself since @jahorton has the fix in #10873
