### ISSUE TITLE
bug(android): OSK takes several seconds to display after not being used for a while

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#10648]
Keyman 17.0.256-alpha on Android, Samsung A53/5G phone, Android 14

I have not yet managed to capture this in a video but if I open the keyboard on my phone after not using it for a while, it will display a blank black box for several seconds -- long enough that it looks like Keyman may have crashed -- before finally displaying.

**Comment by darcywong00** [comment]
I just experienced this on my Android 13 device 17.0.275-beta-local build

But I don't see anything in Sentry for Android or web. 😕

**Comment by mcdurdin** [comment]
I haven't seen this happening for a while. Since I can't repro, I will close this, and reopen if it comes back...
