### ISSUE TITLE
feat(developer): ldml - support local imports

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#10649]
only `base=cldr` is currently supported but spec allows local relative/absolute imports.

https://github.com/keymanapp/keyman/blob/5dbda001fcd8973b4922292b5c0731748380a263/common/web/types/src/ldml-keyboard/ldml-keyboard-xml-reader.ts#L187-L190

Reported by @sovichet

**Comment by srl295** [comment]
- define project-relative imports? kmc-relative?
- command line option to add additional `-I` include paths?

**Comment by srl295** [comment]
blocked by #11236

**Comment by srl295** [comment]
for now, just XML-file-relative

**Comment by srl295** [comment]
definite crowd pleaser

**Comment by srl295** [comment]
Ugh- there's a CLDR DTD bug here. https://unicode-org.atlassian.net/browse/CLDR-18138 - `base="cldr"` is implied.

I think for now I will need to *patch* the schema.
