### ISSUE TITLE
chore(developer): rename unicodeSet to uset 🙀 

### ISSUE THREAD

**Issue by srl295** [keymanapp/keyman#10657]
per https://unicode-org.atlassian.net/browse/CLDR-17366

**Comment by mcdurdin** [comment]
Moving to B17S2. If this change goes through on the spec, then we should not continue to support `unicodeSet` for the handful of early adopters -- they'll just have to deal with the shifting sands of working against non-finalized spec. Doing otherwise just leads to long term pain.
