### ISSUE TITLE
bug(developer): crash with "Test Keyboard on web"

### ISSUE THREAD

**Issue by DavidLRowe** [keymanapp/keyman#10655]
### Describe the bug

When working with the fv_denesuline keyboard (in [keyboards PR 2527](https://github.com/keymanapp/keyboards/pull/2537), I tried the "Test Keyboard on web" feature and Developer gave some unexpected messages then crashed (see details below).
The keyboard in question is defined for mobile only (mobile + tablet), but even after enabling "web" option, the test sequence still caused a crash.

### Reproduce the bug

unzip [fv_denesuline.zip](https://github.com/keymanapp/keyman/files/14185291/fv_denesuline.zip)
(NB: This is a mobile only keyboard, no desktop or web)
double-click fv_denesuline.kpj
click "Keyboards" icon at the bottom
click "fv_denesuline.kmn" link
click "Build" on the left
click "Compile Keyboard" button, observe "built successfully" message
click "Test Keyboard on web" button, observe **unexpected** dialog:
"You need to compile the keyboard before you can continue. Compile now?
click "OK" button, observe dialog: "The source file has changed. Recompile before continuing?"
click "Yes", observe crash:
Details for error report for Keyman app:
  Application Identifier: tike-17.0.253-alpha
  Error Identifier: 6C4A64D3D51A47AEF6DC1B6927E6C21E

### Expected behavior

It was not expected to receive a "You need to compile the keyboard..." message when I had just compiled the keyboard.
If this keyboard is not suitable for the "Test Keyboard on web" feature, it would be nicer to inform the user (with a hint of what is missing) rather than crash.

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [X] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.253-alpha

### Operating system

Windows 11

**Comment by mcdurdin** [comment]
> it would be nicer to inform the user (with a hint of what is missing) rather than crash.

Is this a reasonable request? I guess so 😁
