### ISSUE TITLE
bug(android):  keyboard lexical model stuck and can't change

### ISSUE THREAD

**Issue by Nnyny** [keymanapp/keyman#10673]
### Describe the bug

I download a new lexical model, Google Crawler, for Khmer Angkor keyboard. I'm testing it on Keyman 17.0.239-alpha-test-7934. I switch several times between Google Crawler and Chuon Nath Dictionary, then it stuck to Google Crawler and I can no longer switch back to Chuon Nath Dictionary . I try to uninstall and install again and again but it still stuck to Google Crawler.  

### Reproduce the bug

https://github.com/keymanapp/keyman/assets/123520338/6f579c5d-6c6f-45a6-9a26-8c054e47ef1a

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.239-alpha-test-7934

### Operating system

Android 11

### Device

OPPO F11 Pro

### Keyboard name

khmer_angkor

### Keyboard version

1.3 (unrelease) 

### Language name

Khmer

**Comment by mcdurdin** [comment]
@darcywong00 when you get a chance can you investigate?

**Comment by darcywong00** [comment]
@Nnyny - can you retest with a recent Keyman for Android beta (17.0.273-beta or newer)?

On my device, I can 
1. Install Chuon Nath dictionary
2. Uninstall the Khmer Google crawler dictionary
3. Exit the menus
4. When I go back to "Central Khmer Settings", it shows Chuon Nath dictionary

![image](https://github.com/keymanapp/keyman/assets/7358010/05046421-a836-4273-9deb-19515559740a)

**Comment by Nnyny** [comment]
I have tested it on 17.0.273-beta and it works as you mentioned. Thank you @darcywong00.

**Comment by darcywong00** [comment]
k, I'll close this and have the future feature tracked in #10679
