### ISSUE TITLE
chore(ios): upgrade iOS SDK to 17 - requires Xcode 15 - by April 29, 2024

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#10671]
Apple writes:

> We identified one or more issues with a recent delivery for your app, "Keyman" 17.0.258 (0.10662.10333). Your delivery was successful, but you may wish to correct the following issues in your next delivery:
> 
> ITMS-90725: SDK version issue - This app was built with the iOS 16.2 SDK. Starting April 29, 2024, all iOS and iPadOS apps must be built with the iOS 17 SDK or later, included in Xcode 15 or later, in order to be uploaded to App Store Connect or submitted for distribution.

**Comment by jahorton** [comment]
See #11215:  there's a task we wanted to do on it but are currently unable to.

https://github.com/keymanapp/keyman/pull/11215#issuecomment-2052605823

In particular, that `webView.isInspectable = true` would be a _very_ nice thing to have on our TestFlight builds.  Inspection of  keyboard internals within Keyman and FV apps on iOS 16.4+ and 17.0+ requires this flag to be set... but it's not even defined/declared in the SDK for our build agents' current version of Xcode.

**Comment by jahorton** [comment]
I've now spun off the iOS part of #11215 into #11229; we can revisit the latter once this issue is addressed.

**Comment by mcdurdin** [comment]
We have a working build agent and changes to the source for this are in place. I am going to go ahead and mark this as done.
