### ISSUE TITLE
chore(android): ci needs robustness on package downloads

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#10670]
```
08:27:14   Downloading sil_euro_latin.kmp from downloads.keyman.com
08:27:24   
08:27:24   [android/KMAPro] Downloading /var/lib/TeamCity/work/30ffb35c1b6c4089/keyman/android/KMAPro/kMAPro/src/main/assets/sil_euro_latin.kmp failed with error 3
```

https://build.palaso.org/buildConfiguration/KeymanAndroid_TestPullRequests/442083?buildTab=log&linesState=192&logView=flowAware&focusLine=621

**Comment by darcywong00** [comment]
Does "robustness" mean retrying the kmp download (up to 3 times?)

**Comment by mcdurdin** [comment]
> Does "robustness" mean retrying the kmp download (up to 3 times?)

Yeah probably, with a delay between retries, perhaps 5 times?
