### ISSUE TITLE
chore(ios): refresh iOS Certificates for Keyman

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#10683]
iOS certificates have expired and we need to do the needful to refresh in 16.0-stable and 17.0-alpha.

This should be done _before_ beta

**Comment by sgschantz** [comment]
@mcdurdin I don't see anything that is expired when I login to the Apple Developer site, but I'm not sure whether everything is visible to me.

**Comment by mcdurdin** [comment]
This is a little puzzling to me. It comes from a message from @chrisvire on Slack. But I don't know if we are using those certificates at present. (Side note: I think we should try and decouple the certificates from the repo entirely -- at present we still have the hash of the cert in the repo, but it'd be better as a CI variable, to try and reduce the hassle that this causes us each time.)

**Comment by mcdurdin** [comment]
Everything looks okay, so I don't know what we need to do, if anything.

**Comment by sgschantz** [comment]
Closing, no action necessary.
