### ISSUE TITLE
bug(web): Spacebar caption name of the Vedic Sanskrit keyborad was partially visible in the Portrait View

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#10699]
### Describe the bug

After installing the Vedic Sanskrit keyboard, I noticed that the space bar label name was only partly visible.

### Reproduce the bug

1. Install Keyman 17.0.265 build.
2. Open Keyman In-App. 
3. Download and Install the "Vedic Sanskrit Devanagari Phonetic (ITRANS)" keyboard. 
4. Switch to "Vedic Sanskrit.." Keyboard. 

Here, I observed that in the Portrait view, the Space bar caption name of the Vedic Sanskrit Keyboard was only partially visible. However, when I switched the orientation to Landscape, the entire spacebar caption name became visible.

Note: Able to reproduce it in both Android and iPhone mobile devices. 

..in the Portrait View

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/16940bf4-0305-47d7-b063-5eb691820c38">

..in the Landscape View

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/2f0d16ce-957e-402a-9859-9cf713620626">

..in iPhone mobile

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/ffe7cb59-aa69-41b0-8a9b-099ccc632af5">

### Expected behavior

Spacebar caption name of the Vedic Sanskrit name should be fully visible in the Portrait view. 

### Keyman apps

- [X] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.265-alpha

### Operating system

Android 5.0, 9.0, 12.0, iOS 15.5, 17.1

### Device

Samsung Galaxy A23 5G Mobile, iPhone 13 Mobile

### Keyboard name

Vedic Sanskrit Devanagari Phonetic (ITRANS)

### Keyboard version

1.22

### Language name

Sanskrit

**Comment by jahorton** [comment]
#11203 has more details and is the same underlying bug, so I'm closing this issue in favor of that one.

**Comment by mcdurdin** [comment]
process nit: when closing a duplicate, add the 'duplicate' label and close as 'not planned'. Just helps for filtering in the future.

**Comment by jahorton** [comment]
> process nit: when closing a duplicate, add the 'duplicate' label and close as 'not planned'. Just helps for filtering in the future.

One of these days, I'll remember that "not planned" exists.  Sadly, that was not today.
