### ISSUE TITLE
Solve problem with rendering diacritics on OSK key caps

### ISSUE THREAD

**Issue by tombogle** [keymanapp/keyman#1070]
Many fonts/platforms fail to render an unattached diacritic on the on-screen keyboard. The existing solutions are:
1) Use a bitmap. This scales poorly and is not supported on some platforms.
2) Create a custom font just for this purpose. This works well, but is a ton of work.
We need a good cross-platform solution that has a low enough bar that a reasonable developer can achieve it.

**Comment by erros84** [comment]
The solution I use is U+25CC (◌), the empty circle. Something like ◌́ shows up well on keys in Andika.

**Comment by glasseyes** [comment]
This works fine on the Linux OSK, showing the dotted circle with the diacritic.

**Comment by erros84** [comment]
Yes, I'm using it successfully on my OSK and Mobile/Web keyboards. If your script is RTL, you need to add U+200F before the circle and diacritic. OF course, your keyboard display font needs to include U+25CC for this method to work. The regional variants of fonts, like Andika Afr have a nice tradeoff between completeness and size.

![image](https://user-images.githubusercontent.com/986339/49391236-1e461880-f6f9-11e8-86df-ddf92645beb6.png)

**Comment by mcdurdin** [comment]
@erros84 be aware that cross-platform YMMV with use of U+25CC. Some renderers include a dotted circle automatically for unattached diacritics and don't join diacritics with U+25CC, leading to display of two dotted circles. #1407 will be the first steps to a solid generic solution so we don't need to include the U+25CC character itself in the .kvks / .keyman-touch-layout file.

**Comment by erros84** [comment]
Wow, @mcdurdin, you live in a world with many nasty dragons.
I realized that it was font-related, and this is part of why I embedded the Andika Africa font. I already know that my keyboard isn't very useful before Android 4.4.4 (the latest android release that support my base characters in native fonts).  I can't target 4.4.4 without including 4.4.0 (which doesn't fully work).
iOS 9+, Android 5.1+, Windows, and Mac all seem to work with the embedded font and no duplication. 
Are there other Dragons I haven't met yet?

**Comment by mcdurdin** [comment]
@erros84 that's why I attend St George's Church. I think the dragons are getting rarer... but we've got a good few years to go before they are completely wiped out. 

The U+25CC issue is less likely to arise with Latin script, in my experience, so you will hopefully be fine, especially because you are including a font, which reduces the variables in the experience!

I hope that we can go through and do a keyboard update after Keyman 11.0 has widespread adoption to remove U+25CC from on screen / touch keyboards.

**Comment by mcdurdin** [comment]
FWIW, this is much bigger and nastier than we had hoped. Still working on it. Hope to have better answers in 17.0.

**Comment by mcdurdin** [comment]
Resolved in #9032.
