### ISSUE TITLE
feat(developer): create a .gitignore as part of the (ldml?) template

### ISSUE THREAD

**Issue by srl295** [keymanapp/keyman#10712]
Suggestion: 

https://github.com/keyman-keyboards/ldml_test/blob/master/.gitignore#L1-L2

Could add a comment at the top of the .gitignore saying what it's for.

This is common for many cli 'generator' type things to create a .gitignore when creating a project template.

**Comment by mcdurdin** [comment]
This is also part of the conversion work for kmconvert into a kmc module (this feels like an intercontinental flight project -- got a couple of those coming up in next couple of months)

**Comment by mcdurdin** [comment]
c.f. #10509

**Comment by darcywong00** [comment]
This is blocked by single keyboard repo
