### ISSUE TITLE
[Mac] Fatal (access invalid kernel address) at line 397 of KMInputMethodEventHandler.m

### ISSUE THREAD

**Issue by tombogle** [keymanapp/keyman#1072]
```
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000018
 Raw Text
0	libobjc.A.dylib							objc_msgSend + 29
1	Keyman		KMInputMethodEventHandler.m	line 397	-[KMInputMethodEventHandler handleKeymanEngineActions:in:]
2	Keyman		KMInputMethodEventHandler.m	line 529	-[KMInputMethodEventHandler handleEvent:client:]
3	Keyman		KMInputController.m		line 53		-[KMInputController handleEvent:client:]
4	InputMethodKit							-[IMKServer handleEvent_Common:characterIndex:edge:clientWrapper:controller:] + 1427
17	AppKit								-[NSApplication run] + 764
18	Keyman		main.m				line 21		main
19	Keyman		start + 52
```

**Comment by tombogle** [comment]
After studying the code and doing a lot of searching on-line, I'm still pretty clueless. I found a similar crash in another IME [here](https://github.com/rime/home/issues/125). They determined it was likely due to an OS bug related to a specific user's font configuration, so they closed the issue without fixing it. In our case, Keyman code is the last thing at the top of the call stack, so it seems unlikely to be a font-delated delay. But there could be something that is causin

**Comment by tombogle** [comment]
In the latest version, another similar crash was reported. Different line number and call stack, but the same error. Most likely some kind of memory corruption, but not much else to go on:

# Version: Keyman 10.0 for macOS (10.0.111)
# Bundle Identifier: keyman.inputmethod.Keyman
# Issue #: 19
# Issue ID: 5b784f476007d59fcd28aed2
# Session ID: b2fdcbd6e27344e382cae9d0844eb302_DNE_0_v2
# Date: 2018-08-18T16:54:00Z
# OS Version: 10.10.5 (14F2511)
# Device: MacBook Pro Retina, 15", Mid 2015
# RAM Free: 66%
# Disk Free: 18.3%

#0. Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x7fff8a2790dd objc_msgSend + 29
1  Keyman                         0x1049dd554 -[KMInputMethodEventHandler getSelectionRangefromClient:] (KMInputMethodEventHandler.m:209)
2  Keyman                         0x1049df7a2 -[KMInputMethodEventHandler handleEvent:client:] (KMInputMethodEventHandler.m:614)
3  Keyman                         0x1049e971f -[KMInputController handleEvent:client:] (KMInputController.m:53)
4  InputMethodKit                 0x104b2fa98 -[IMKServer handleEvent_Common:characterIndex:edge:clientWrapper:controller:] + 3397
5  InputMethodKit                 0x104b24859 __63-[IMKServer handleEvent:characterIndex:edge:asyncClient:reply:]_block_invoke + 765
6  CoreFoundation                 0x7fff96a1370c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
7  CoreFoundation                 0x7fff96a05815 __CFRunLoopDoBlocks + 341
8  CoreFoundation                 0x7fff96a05356 __CFRunLoopRun + 1814
9  CoreFoundation                 0x7fff96a049f8 CFRunLoopRunSpecific + 296
10 HIToolbox                      0x7fff9190556f RunCurrentEventLoopInMode + 235
11 HIToolbox                      0x7fff919052ea ReceiveNextEventCommon + 431
12 HIToolbox                      0x7fff9190512b _BlockUntilNextEventMatchingListInModeWithFilter + 71
13 AppKit                         0x7fff9582a8ab _DPSNextEvent + 978
14 AppKit                         0x7fff95829e58 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 346
15 AppKit                         0x7fff9581faf3 -[NSApplication run] + 594
16 Keyman                         0x1049da998 main (main.m:21)
17 Keyman                         0x1049d4834 start + 52

**Comment by SabineSIL** [comment]
We decided to close this issue
