### ISSUE TITLE
bug(developer): ldml 'test keyboard area' doesn't update

### ISSUE THREAD

**Issue by srl295** [keymanapp/keyman#10732]
I made changes to the source and recompiled, but there doesn't seem to be a way to get the 'Test Keyboard' area to pickup the new changes, it doesn't have a Close button.

Update: It seems this unlabelled button actually dismisses the Test Keyboard area. 
![image](https://github.com/keymanapp/keyman/assets/855219/2af2c0cb-2e51-48b8-96f7-0f6bee43c5e7)

- Ideally, changing text should flag the user "this keyboard needs to be compiled"
- Compiling should flag "this test keyboard session is out of date"

**Comment by mcdurdin** [comment]
Dup of #10545.
