### ISSUE TITLE
bug(developer): kmc should be more verbose about xml issues

### ISSUE THREAD

**Issue by srl295** [keymanapp/keyman#10733]
in the "not so helpful messages" category

```
ldml_test.xml: Error: 0007 The source file has an invalid structure: Unable to load XML file
```

**Comment by mcdurdin** [comment]
Pretty much a dup of #10622.

**Comment by srl295** [comment]
> Pretty much a dup of #10622. 

Partially. That is a general issue of line numbers, this was to propagate the details of what's actually wrong besides "it wouldn't load". Ajv /xml2js have more details we could expose.

**Comment by mcdurdin** [comment]
Yep. I think we can cover those aspects of the problem in #10622
