### ISSUE TITLE
bug(windows): Unable to install version 15.0 keyboards due to bug in minimum Keyman ver requirement check - Keyman 17.0 beta build

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#10746]
### Describe the bug

I got an error message when attempting to install the Amharic keyboard using the Keyman Configuration dialog.

### Reproduce the bug

1. Install the latest Keyman 17.0.264-beta build.
2. Open Keyman Configuration dialog. 
3. Click the Download Keyboard button. 
4. Type 'Amharic' in the Keyboard search bar. 
5. Click the 'Install keyboard' button. 

I noticed an error message 'Sorry, this keyboard requires Keyman 15.0 or higher' appeared on the screen. Seems to be an issue. 

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/378de14f-a8b2-4c6e-aa8d-32f045251868">

### Expected behavior

Amharic Keyboard should be installed in the latest Keyman 17.0 without showing any error. 

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [X] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.264

### Operating system

Windows 10 OS, Windows 11 OS (VM)

### Keyboard name

gff_amharic

### Language name

Amharic

**Comment by rc-swag** [comment]
Euro Latin (SIL) also has the same error

**Comment by mcdurdin** [comment]
@bharanidharanj would you mind testing this issue on Windows, Linux, and macOS? v16 or v17 is fine.
