### ISSUE TITLE
chore(developer): hint, not warn, for downlevel gesture support

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#10741]
#10364 added a warning when compiling a keyboard possessing a touch-layout that aims to support versions of Keyman before 17.0.  If not making any further changes, this results in the following at present for [our prospective default-keyboard update](https://github.com/keymanapp/keyboards/pull/2520):

```
sil_euro_latin.kmn: 5002 Building sil_euro_latin.kmn
sil_euro_latin.kmn: Warning: 7005 The touch layout uses a flick or multi-tap gesture on key K_Q, which is only available on version 17.0+ of Keyman
sil_euro_latin.kmn: 5010 The build failed because option "treat warnings as errors" is enabled and there are one or more warnings.
sil_euro_latin.kmn: 5007 sil_euro_latin.kmn failed to build.
```

As we generally leave the "treat warnings as errors" option on by default within the keyboards repository, and as their presence within a touch keyboard doesn't even break anything on older versions... perhaps this should be a "hint" or "info" level message instead?

**Comment by mcdurdin** [comment]
Agree to do this. Rationale: it may be desirable to have a keyboard with graceful degradation of functionality, such as sil_euro_latin, where it still works on older versions of Keyman, albeit without gestures, without blocking builds. Thus, this can be a hint rather than a warning.
