### ISSUE TITLE
bug(core): meson build not failing when -test.json can't build

### ISSUE THREAD

**Issue by srl295** [keymanapp/keyman#10752]
Windows 11.

```shell
core/build.sh -d test:x64
```

... build logs have:

```
Configuring ldml_test-test.json with command
Running command: C:\Program Files\nodejs\node.EXE --enable-source-maps C:/projects/keyman/keyman/core/../developer/src/kmc build ldml-test-data C:\projects\keyman\keyman\core\tests\unit\ldml\keyboards\ldml_test-test.xml --out-file C:\projects\keyman\keyman\core\build\x64\debug\tests\unit\ldml\keyboards\ldml_test-test.json
--- stdout ---
error KM00007: The source file has an invalid structure: Unable to load XML file

--- stderr ---
```

but the 'console' build log showed:

```
Configuring ldml_test-test.json with command
```

and then the test runner failed because there was no .json test file.

The build should have failed when the 'command' failed.

**Comment by srl295** [comment]
looks like the _test_ path doesn't have an exitProcess(1) call in it.

But, couldn't the parent building code exit if any error messages show up in the callbacks?

**Comment by mcdurdin** [comment]
> But, couldn't the parent building code exit if any error messages show up in the callbacks?

There isn't any parent building code for `buildTestData()` -- it's essentially a top-level call in kmc:

https://github.com/keymanapp/keyman/blob/898310e6df05d07c6ddb068fdc96e5489e46b5dd/developer/src/kmc/src/commands/build.ts#L53-L56

**Comment by srl295** [comment]
fixed
