### ISSUE TITLE
bug(developer): Unable to open the debugger window in Keyman 17.0.269-beta

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#10751]
### Describe the bug

I noticed that after pressing F5 the debugger window showed a warning message and did not open the debugger window. 

### Reproduce the bug

1. Install Keyman Developer 17.0.269-beta build.
2. Open any existing keyman project. (eg., Khmer_Angkor)
3. Compile it.
4. Press F5 to start debugging. 

Here, I noticed that a warning message appeared on the screen and it did not allow debugging. FYI, 'Include debug information' option has been already checked. Seems to be an issue. 

..debug information already checked

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/26af1e37-5184-4e3c-a387-9e3ea209876f">
  

..Warning message
        
   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/0472bd4f-03be-4b54-a6ef-f0778d86511e">

### Expected behavior

Pressing F5 should open the debugger window. 

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [X] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.269-alpha

### Operating system

Windows 10 OS, Windows 11 OS (VM)

**Comment by mcdurdin** [comment]
Yes, I can repro this. Good catch @bharanidharanj, I will get onto fixing this!

**Comment by bharanidharanj** [comment]
> Yes, I can repro this. Good catch @bharanidharanj, I will get onto fixing this!

Thank you!
