### ISSUE TITLE
bug(android): tablet banner has low contrast blue-on-grey text

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#10755]
I didn't realise the banner text was such a terrible low contrast. That's a bug that we need to fix.

_Originally posted by @mcdurdin in https://github.com/keymanapp/keyman/pull/10726#discussion_r1493264954_

![image](https://github.com/keymanapp/keyman/assets/4498365/d9773873-432f-4c59-ad72-6253be53247d)

**Comment by darcywong00** [comment]
Fixed by #10760
