### ISSUE TITLE
[Web] Remove requirement of filename containing keyboard version

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#1076]
Per @mcdurdin from https://community.software.sil.org/t/custom-keyboards-not-loading-in-kmea/1100/5

> ... we should make this renaming unnecessary in future versions.

1. Update KMW so the .js keyboards don't need the keyboard version in the filename
2. Update KMEI and KMEA accordingly (also applies to default keyboard european2-1.6.js)

**Comment by darcywong00** [comment]
Removing android/ and ios/ since 14.0 now uses keyboard packages for installing keyboards (no version needed in the filename except for legacy cloud/ keyboards).

**Comment by darcywong00** [comment]
@mcdurdin can confirm, but I think keymanweb.com still relies on s.keyman.com including the file version in the keyboard file name.

For example https://keymanweb.com/#sam-syrc,Keyboard_aramaic_hebrew
pulls `aramaic_hebrew-1.2.js` from s.keyman.com

**Comment by mcdurdin** [comment]
Pretty sure that is all down to keymanweb.com and the backend APIs that return the files with version numbers. These get passed into KeymanWeb directly and KeymanWeb no longer cares about the filename structure. So the rename requirement is no longer there -- we have the build still providing versioned filenames for keymanweb.com/api.keyman.com but that's not gonna affect anything else.
