### ISSUE TITLE
test(developer): Regression Test Report 17.0.269-Beta(10failures)

### ISSUE THREAD

**Issue by sillsdev-dondillard** [keymanapp/keyman#10769]
```
Test Report for Keyman Developer Version 17.0.269-Beta
Results 

 Expected Start Date 1/15/2024
 Actual Start Date 1/15/2024

 Overall Results: 58% (14/24 passed)

Regression Tests
 Windows 10 58% (7/12 passed)
 Windows 11 58% (7/12 passed)
```
Issues
* #10751

**Comment by mcdurdin** [comment]
I'm not clear from this report what the failures were -- it'd be good to know which tests failed and correlate them to issues.

**Comment by sillsdev-dondillard** [comment]
@mcdurdin 

On Windows 10 :
TC152 - Test case for Debugger_Starts ,
TC153 - Test case for Debugger_Single_Step,
TC154 - Test case for Debugger_Pause,
TC155 - Test case for Debugger_Changes
TC156 - Test case for Debugger_Platform,

On Windows 11 :
TC152 - Test case for Debugger_Starts ,
TC153 - Test case for Debugger_Single_Step,
TC154 - Test case for Debugger_Pause,
TC155 - Test case for Debugger_Changes
TC156 - Test case for Debugger_Platform, 

The debugger will not open for any of these tests.

**Comment by mcdurdin** [comment]
Thanks Don, we've fixed the underlying issue that was blocking those tests, so next round should go better!
