### ISSUE TITLE
bug(android): backspace not working after many copies of the same character

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#10776]
### Describe the bug

If the text insertion point lies after about 18 copies of the same character in a row, the backspace key stops working.  It doesn't matter whether this is immediately after having typed the characters or after having relocated the caret; backspaces will fail either way.  Selected text is still deletable, though.

Tested with <kbd>j</kbd> and <kbd>-</kbd> repeated 18+ times (within the Keyman app) before attempting to backspace; both cases failed.  Also tested within the Memo app with Keyman as system keyboard; <kbd>-</kbd> repeated 20 times reproduces the error, albeit a bit more slowly - you can actually see the deletion for a fraction of a second _before the backspace is undone_.

This gets further complicated with deletions afterward:  typing new text, then deleting up to the border of the heavily-repeated character, will see the final backspace that works... **_replace_** the deleted text with an extra copy of the repeated character.  So far, I can only confirm +1 character when deleting a simple, single character; I haven't yet tried rigging up a case to check if it's a flat +1 or instead a +1 extra per +1 character deleted at that moment.

----

One last wrinkle here:  if the repeated text is the entirety of the context (perhaps with +1 character at the beginning), move the caret insertion point to immediately after the first (visible, user-facing) character, then press backspace.  The keyboard / Keyman app will _immediately_ crash - this is _highly_ consistent!

### Reproduce the bug

Using `sil_euro_latin`:

1. Copy, then paste (or type) the following text into the Keyman app: `--------------------` (20 hyphens in a row)
2. Hit the backspace key.
    - Error 1: the backspace won't trigger.
3. Type the following: <kbd>a</kbd>.
4. Hit the backspace key. 
    - Error 2:  the backspace should replace the <kbd>a</kbd> with another <kbd>-</kbd>.
5.  Repeat steps 3 and 4 at least 5 times.
    - "Error 2" should trigger each time, making it obvious that there are now extra <kbd>-</kbd>s due to the increased text width. 
6. Move the caret immediately after the first `-`.
7. Press backspace.
    - Error 3:  the Keyman app should immediately _**crash**_.  
    - If enabled, a Sentry error report will be logged.
    - Occurs both when in-app and when using the system keyboard

### Expected behavior

Expectation:  that backspace would work "normally" in these cases.  Here, the character immediately before the caret should always be consistently deleted, never replacing the deleted character with anything.

### Related issues

Discovered while analyzing behaviors first noted while investigating #10592.  I _strongly_ suspect that it is unrelated though; if I were a betting man, I'd wager this is actually an issue in 16.0 and before that we just never noticed.

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.271-beta

### Operating system

Android

### Device

SM-T350 (Samsung Galaxy Tab A)

### Target application

Keyman for Android, Memo

### Keyboard name

sil_euro_latin

### Keyboard version

2.0.4

### Language name

English

### Additional context

This issue does not reproduce in Keyman for iOS; I'm quite certain that it's specific to Keyman for Android, possibly due to interactions with how Android's "context window" operates.  I'm personally less well-versed in these details for Android at this time than for iOS, since the latter has historically given us more trouble.

Finally, I would not be surprised if the number of identical repeated characters in a row required to trigger this bug varies depending on the device.  I don't have any evidence to back this claim; the suspicion is entirely based on how similar behaviors have been observed for similar issues within the iOS Keyman app / keyboard.

----

I stopped investigating this after a certain point, but I do remember the following details:

1. The embedded Web engine does send correct instructions to KMEA.
    - Evidence:  Note the bit re: the system keyboard about actually seeing the backspace occur before its reversal.
2. KMEA then attempts to synchronize the resulting context with the embedded KMW.
    - For some reason, _one_ of these calls actually _undoes_ the backspace.  This appears to occur when a context reset is triggered by the process, though I'm still not exactly sure how - this implies, to me, that KMEA is sending Web the _old_ context, from _before_ the BKSP.
3. Why "one of" these calls?  This is the point where I stopped, but... for every one backspace trigger, _two_ calls to sync context from KMEA to KMW occur.  Only one of them has mismatching context with KMW, and that's the one causing the context reset.

I suspect that the Web changes included as part of #10728, along with mimicking the iOS host app's altered synchronization pattern with it, will be helpful to resolving this matter... once a better understanding of all the underlying mechanisms here has been reached.  It's hard to say for sure at this point - I'm just putting it here so I don't forget about the idea should I be the one to pick this up for full resolution.

**Comment by jahorton** [comment]
For what it's worth, the call stack for _this_ Sentry event set looks very similar... off by just one call-stack frame:

https://keyman.sentry.io/share/issue/4b9a9877cc9145a8863f53dc8d62f445/

While the previously-linked Sentry event so far appears to be 17.0-exclusive (no 16.0 events seen), _this_ one appears to be 16.0-exclusive.

15.0-exclusive:  https://keyman.sentry.io/share/issue/5059ba82088641d6b7122cd39f7dbdcf/

14.0-exclusive:  https://keyman.sentry.io/share/issue/5059ba82088641d6b7122cd39f7dbdcf/

While there are small, subtle call-stack differences... I wouldn't be surprised if they're all the same error.

**Comment by mcdurdin** [comment]
Possibly related, report from my son:

> Bug report, backspace stopped working in termux, im not sure of its keyman or termux
> ![image](https://github.com/keymanapp/keyman/assets/4498365/31212e88-2ea0-43af-b6a7-e61a74bcde44)
> Works fine with samsung

(I am not sure if there is a separate interaction with 1Password, there; enquiring further.

**Comment by rc-swag** [comment]
I have seen the same crash as described in steps 6 & 7 of the repo steps. Jahorton has confirmed it is the same and found the crash on [sentry]( https://keyman.sentry.io/share/issue/7980e86e395b4c5cbd03ba03c98cfc0d/).

My steps are type some text in my text messaging app. Using the touch screen select the cursor roughly halfway back in the text I have typed and press backspace.  Sometimes I would get a notification saying `Keyman Beta keeps stopping` other times the crash.

**Comment by darcywong00** [comment]
I've been experiencing the associated Sentry crash this morning. Mine was wresting with trying to dismiss Android's autocorrect (add to dictionary prompt). And when I kept returning to the context the keyboard would crash.

**Comment by jahorton** [comment]
> If the text insertion point lies after about 18 copies of the same character in a row, the backspace key stops working. It doesn't matter whether this is immediately after having typed the characters or after having relocated the caret; backspaces will fail either way. Selected text is still deletable, though.

So... this checks out:

https://github.com/keymanapp/keyman/blob/be867604e4b2650a60e69dc6bbe0b6115315efff/android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboardJSHandler.java#L271-L273

One backspace deletion = context length of 18.  I can certainly see where that arbitrary value came from now.

In fact... looking at the contents of the rest of the method...

https://github.com/keymanapp/keyman/blob/be867604e4b2650a60e69dc6bbe0b6115315efff/android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboardJSHandler.java#L287-L297

Wait a sec - the section from lines 291 to 296 could be responsible for the backspace-rewind!  Note:  this is the Android engine doing its own context-synchronization with the Android OS keyboard API, rather than anything that KeymanWeb touches.  (Huh... I'm not used to Web actually not being involved with one of these problems for once.)

**Comment by mcdurdin** [comment]
Note: seeing this in 18.0.235. I don't think it is 100% fixed. 

https://keyman.sentry.io/discover/results/?dataset=errors&field=title&field=release&field=environment&field=user.display&field=timestamp&interval=1d&name=StringIndexOutOfBoundsException%3A%20String%20index%20out%20of%20range%3A%20-1&project=5983520&query=issue%3AKEYMAN-ANDROID-3Z4%20release%3Arelease%4018.0.235&queryDataset=error-events&statsPeriod=90d&yAxis=count%28%29&yAxis=count_unique%28user%29
