### ISSUE TITLE
KeymanWeb initialises too quickly when using bookmarklet

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#108]
The bookmarklet typically loads KeymanWeb after page initialization is complete. This means that `kmwinit.js` calls `keymanweb.init(null);` without giving the bookmarklet a chance to set different initialisation arguments.

An appropriate fix would be to postpone initialization to happen async by wrapping the `init()` call in `kmwinit.js` with `setTimeout()`. This would mean that the bookmarklet could inject its own call to `init()` which would then take precedence over the call in `kmwinit.js`, but we wouldn't lose the initialization for other pages.

**Comment by jahorton** [comment]
Fixed with #112.
