### ISSUE TITLE
bug(android): Multiple toast notifications appearing during a (khmer_angkor)  keyboard installation

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#10812]
### Describe the bug

I noticed that several toast notifications popped up on the Keyman screen during installation. (especially the keyboard with dictionary)

### Reproduce the bug

1. Install Keyman 17.0.273 beta
2. Open Keyman In-App.
3. Open the Settings option. 
4. Click the "Install Keyboard or Dictionary" option from the Settings menu. 
5. Click the "Install from keyman.com" option from the Install Keyboard or Dictionary menu.
6. Download and Install the "Khmer_Angkor" keyboard. 

Here, I noticed multiple toast notifications appearing during the keyboard installation. I have attached the video file for reference. 

https://github.com/keymanapp/keyman/assets/19683143/dc340cc8-4c8f-4f3e-be60-ed309c3828c7

### Expected behavior

In the previous builds, I did not see multiple toast notifications during keyboard installation. It would be better If we reduce the toast notifications during installation. 

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.273 beta

### Operating system

Android 12, 13

### Device

Samsung Galaxy A23 5G Mobile

### Keyboard name

khmer_angkor

### Keyboard version

1.3

### Language name

Khmer

**Comment by darcywong00** [comment]
These are normal notifications when keyboard/dictionaries area downloaded
* Khmer Angkor keyboard installed
* Downloading dictionary started in background
* Dictionary download is finished
* Resources successfully updated

I agree the last two are "noisy" and maybe can be removed..

**Comment by darcywong00** [comment]
Fixed by #10868
