### ISSUE TITLE
bug(android): Dictionary Checking message appearing for languages that don't have a dictionary

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#10810]
### Describe the bug

I noticed that some languages that don't have dictionaries display a "checking for dictionary to download" message on the screen. 

### Reproduce the bug

1. Install Keyman 17.0.271-beta build.
2. Open Keyman In-App. 
3. Download and Install Cameroon Qwerty Keyboard. 
4. Open Settings menu. 
5. Open Installed Languages menu. 
6. Click 'Bafanji' - Cameroon Qwerty Keyboard. 
7. Click the Dictionary (Check for available dictionary) option at the bottom of the 'Bafanji' Settings menu. 

Here, I noticed that clicking on the 'Dictionary' option, opens a warning message "Checking for associated dictionary to download" and it did not open. Seems to be an issue. 

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/74f10d3c-01c2-40d3-b62e-1850bab0dcf4">

### Expected behavior

It would be more helpful if the message displayed something like "This language does not have any dictionary to download" when clicked.

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.271 beta

### Operating system

Android 5.0, 9.0, 12.0

### Device

Android 12.0 /  API 31 emulator, Redmi Note 8 Pro

### Keyboard name

sil_cameroon_qwerty

### Keyboard version

6.1.0

### Language name

Bafanji

**Comment by darcywong00** [comment]
> ## Describe the bug
>I noticed that some languages that don't have dictionaries display a "checking for dictionary to download" message on the screen.
>
> ## Expected behavior
>It would be more helpful if the message displayed something like "This language does not have any dictionary to download" when clicked.

We previously did notify if there was nothing to download. But that was removed in #7170 because it's noisy.

The current prompt "Checking for dictionary to download" is correct because Keyman doesn't know which languages have a dictionary until it queries api.keyman.com
