### ISSUE TITLE
bug(android): backspace causes Keyman to crash when cursor is moved into just-typed text

### ISSUE THREAD

**Issue by rc-swag** [keymanapp/keyman#10835]
Moving the cursor back into any just-typed characters and pressing backspace causes Keyman for Android app to crash. 

First identified as part of issue #10776. The first two errors in #10776 are an edge case as they require multiple copies of the same character the third issue can occur with any characters in the context. The discoveries already made will be moved to this issue to track. 

This is the Sentry log corresponding to the crash triggered by "Error 3" from the repro.

Sentry Issue: [KEYMAN-ANDROID-3Z4](https://keyman.sentry.io/issues/4477654819/?referrer=github_integration)

_Originally posted by @sentry-io[bot] in https://github.com/keymanapp/keyman/issues/10776#issuecomment-1953356469_

@jahorton original comments from #10776

For what it's worth, the call stack for _the next_ Sentry event set looks very similar... off by just one call-stack frame.  While the previously-linked Sentry event so far appears to be 17.0-exclusive (no 16.0 events seen), it appears to be 16.0-exclusive.

16.0-exclusive:  https://keyman.sentry.io/share/issue/4b9a9877cc9145a8863f53dc8d62f445/ (769 events, 165 users)

15.0-exclusive:  https://keyman.sentry.io/share/issue/5059ba82088641d6b7122cd39f7dbdcf/ (33 events, 4 users)

14.0-exclusive:  https://keyman.sentry.io/share/issue/c389dbc7497747c6a1f8574938458ee8/  (4 events, 1 user)

While there are small, subtle call-stack differences... I wouldn't be surprised if they're all the same error, corresponding to "Error 3" from the repro above.
https://github.com/keymanapp/keyman/issues/10776#issuecomment-1953360896

At this exact moment, our issue-listing on status.keyman.com reports 33 events, 31 issues for the 16.0 version, putting it at 25th most common under stable-16.0 among recently-occurring events.

**Comment by rc-swag** [comment]
original comment @mcdurdin  https://github.com/keymanapp/keyman/issues/10776#issuecomment-1958568458
Possibly related, report from my son:

> Bug report, backspace stopped working in termux, im not sure of its keyman or termux
> ![image](https://github.com/keymanapp/keyman/assets/4498365/31212e88-2ea0-43af-b6a7-e61a74bcde44)
> Works fine with samsung

(I am not sure if there is a separate interaction with 1Password, there; enquiring further.

**Comment by mcdurdin** [comment]
> (I am not sure if there is a separate interaction with 1Password, there; enquiring further.

1Password was not related to the issue.

**Comment by jahorton** [comment]
The errors are likely caused due to logic errors from the following method, in some fashion:

https://github.com/keymanapp/keyman/blob/be867604e4b2650a60e69dc6bbe0b6115315efff/android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboardJSHandler.java#L271

It's the last function under our control that shows up in the stack frame, and the data from the error suggests that something's off with the values we're feeding into the top-most frames.
