### ISSUE TITLE
bug(ios): sample keyboard apps do not build according to instructions

### ISSUE THREAD

**Issue by sgschantz** [keymanapp/keyman#10844]
### Describe the bug

Following the [sample keyboard app build instructions](https://help.keyman.com/developer/engine/iphone-and-ipad/current-version/guides/in-app/) results in build errors: 'There is no XCFramework found'

### Related issues

possibly related to #9674, though there are differences for Keyman 16 and 17

### Keyman apps

- [ ] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16

### Operating system

ios

**Comment by mcdurdin** [comment]
Just noting that the sample app downloadable from https://downloads.keyma.com/ios/stable does not build on its own.

**Comment by mcdurdin** [comment]
Ref https://community.software.sil.org/t/ios-kmsample-dependencies-issues/8440

**Comment by sgschantz** [comment]
The cause of the build errors is that the frameworks are in different locations when built as part of the ios project or built with the keyman-engine-ios zip file.

KeymanEngine.xcframework should be located in the same directory as the project file. For the sample zip, it is two directories above that.

All the other frameworks should be located in ../../Carthage/Build. For the sample zip, the other frameworks are not included at in the zip file at all.

**Comment by mcdurdin** [comment]
> Does this seem like a reasonable approach? I don't like duplicating keyman engine in the two sample projects, but I also don't want to move anything or change the relative paths in the main ios project.

Yes, this seems spot-on. The two copies of the framework is not quite ideal, but it's a pretty small cost and not a big deal in my view. Good stuff.
