### ISSUE TITLE
bug(android): Keyboards that were removed from an uninstalled Keyman build (17.0.273) still show up in the updated Keyman build (17.0.275) (Random)

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#10846]
### Describe the bug

I noticed that keyboards removed from an uninstalled Keyman build still show up in the updated Keyman build.

### Reproduce the bug

1. Install Keyman 17.0.273-beta
2. Open Keyman In-App. 
3. Download and Install some keyboards (sil_cameroon_qwerty (Bafanji and Baka), Tamil 99 Basic  and sil_ipa) using Settings menu. 
4. Verify all the keyboards are working as expected. 
5. Uninstall all the keyboards except the default keyboard. 
6. Close the Keyman app. 
7. Uninstall Keyman app. 
8. Install the latest Keyman 17.0.275-beta
9. Open Keyman In-App.

Here, I noticed that the removed keyboards from the uninstalled build still appear in the latest Keyman app. Seems to be an issue. 

I have attached the Video file for your reference. 

https://github.com/keymanapp/keyman/assets/19683143/924fab54-791d-4bf4-975d-c57afe3675ae

### Expected behavior

Keyboards that were removed from the previous build of Keyman should not appear in the latest version of the app.

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.275-beta

### Operating system

Android 5.0, 9.0, 12.0

### Device

Samsung Galaxy A23 5G Mobile

**Comment by bharanidharanj** [comment]
> I suspect some of the keyboard files get restored from the Play Store.
> 
> If you really want a clean installation, try clearing the app cache / app data before uninstalling and reinstalling.

@darcywong00 Retested as per your suggestion and I was not able to reproduce it after clearing the cache and app data file. It would be better to close this issue. Thanks.

**Comment by mcdurdin** [comment]
> I suspect some of the keyboard files get restored from the Play Store.
> 
> If you really want a clean installation, try clearing the app cache / app data before uninstalling and reinstalling.

Is this an issue that other users will experience? i.e. they uninstall a keyboard, then along comes a Keyman update and the keyboard reappears? If so, we need to address the core problem.

**Comment by darcywong00** [comment]
Testing on 17.0.278-beta
1. Installed khmer_angkor and rawang
2. Uninstalled Keyman
3. Re-installed 17.0.278-beta and all the previous keyboards were already installed

Note, when we "uninstall" keyboards in Keyman for Android, the extracted kmp files still persist on the device.
I don't see this in Keyman when locally built - just from Play Store

**Comment by mcdurdin** [comment]
> Uninstall all the keyboards except the default keyboard.

This is the critical point -- the upgrade is causing the uninstalled keyboards to come back, right?

So the test would be:

1. Installed khmer_angkor and rawang
2. Uninstall rawang
3. Uninstalled Keyman
4. Re-installed 17.0.278-beta 

khmer_angkor should show up but rawang not.

**Comment by darcywong00** [comment]
> khmer_angkor should show up but rawang not.

So I ran that test, and even more bizarre, it came back with eurolatin and rawang. :confused: 

Looking into https://developer.android.com/guide/topics/data/autobackup#IncludingFiles

**Comment by darcywong00** [comment]
We might have conflicting requirements here regarding Keyman backups across app installs.

When a user updates / re-installs Keyman, we want them to keep existing installed keyboards. I think this content follows the Play Store [restore schedule](https://developer.android.com/guide/topics/data/autobackup#RestoreSchedule)
> Data is restored whenever the app is installed, whether from the Play Store, during device setup (when the system installs previously installed apps), or by running adb install. The restore operation occurs after the APK is installed but before the app is available to be launched by the user.

Yet we're not wanting uninstalled keyboards to reappear.

afict, the [backup schedule](https://developer.android.com/guide/topics/data/autobackup#BackupSchedule) to the Google Drive says:
> Backups occur automatically when all of the following conditions are met:
>
> * The user has enabled backup on the device. In Android 9, this setting is in Settings > System > Backup.
> * At least 24 hours have elapsed since the last backup.
> * The device is idle.
> * The device is connected to a Wi-Fi network (if the device user hasn't opted in to mobile-data backups).

I think when the user uninstalls a keyboard, there's a 24-hour window where if they install/update Keyman, the backup restores that keyboard.

**Comment by mcdurdin** [comment]
If this is only happening in an uninstall + reinstall scenario, then we can probably ignore it. It won't impact many users. If it happens in an upgrade scenario, then that's more problematic

**Comment by darcywong00** [comment]
I could not get a repro using the steps in the issue with the downloads.keyman links for
* [17.0.273 beta](https://downloads.keyman.com/android/beta/17.0.273/keyman-17.0.273.apk)
* [17.0.275 beta](https://downloads.keyman.com/android/beta/17.0.275/keyman-17.0.275.apk)

Uninstalling 17.0.273 and immediately installing 17.0.275 resulted in just eurolatin.

**Comment by darcywong00** [comment]
> So the test would be:
>
>Installed khmer_angkor and rawang
Uninstall rawang
Uninstalled Keyman
Re-installed 17.0.278-beta
khmer_angkor should show up but rawang not.

------------
More retesting using the apk's from downloads.keyman.com

uninstall / reinstall of 17.0.273 beta resulted in just EuroLatin being installed

upgrading from 17.0.273 beta via the Play Store resulted in EuroLatin and khmer_angkor being installed

**Comment by darcywong00** [comment]
> If this is only happening in an uninstall + reinstall scenario, then we can probably ignore it. It won't impact many users. If it happens in an upgrade scenario, then that's more problematic

@bharanidharanj reported scenario was uninstall + reinstall

I think this issue can be closed then...
