### ISSUE TITLE
bug(ios): The predictive text goes beyond the border of the suggestion banner

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#10859]
### Describe the bug

I noticed that the predictive text appear on the suggestion banner is not displaying correctly.

### Reproduce the bug

1. Install Keyman 17.0.276-beta
2. Open Keyman In-app.
3. Enable "Don't show again" radio button from the Get Started menu.
4. Close the application.
5. Open Keyman In-app. 

Here, I noticed that the predictive text goes beyond the border of the suggestion banner. 

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/48f5ca53-d2e7-447a-b363-b7db07a5cc2f">

### Expected behavior

The predictive text should appear inside the suggestion banner. 

### Keyman apps

- [ ] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.276-beta

### Operating system

iOS 17.0, iOS 15.5

### Device

iPhone 13 Mobile

**Comment by jahorton** [comment]
Interestingly, the repro stated in the description appears to be almost necessary to trigger the bug.  I only get the bug to trigger on the _first_ app relaunch after disabling the Get Started menu - not on any subsequent relaunches!

It's also worth noting how the keyboard is laid out on bugged launches vs normal ones:

![image (6)](https://github.com/keymanapp/keyman/assets/25213402/ef8a1cd0-7444-47ca-8e23-72c8e1f55009)

**Comment by jahorton** [comment]
Re-enabling "Get Started" via the menu option to reach it, restarting, disabling it again, then restarting is enough to re-trigger the scenario as well.  No need to force-wipe the device or Simulator instance.

**Comment by jahorton** [comment]
I've been able to determine that the cause in height difference is due to `topBarDelta` being zero here - that is, when this bug occurs, it's because `hideBanner` below is `true`.

https://github.com/keymanapp/keyman/blob/0d2e044c5ae24d444f999a6857074c67e41181a2/ios/engine/KMEI/KeymanEngine/Classes/Keyboard/InputViewController.swift#L105

https://github.com/keymanapp/keyman/blob/0d2e044c5ae24d444f999a6857074c67e41181a2/ios/engine/KMEI/KeymanEngine/Classes/Keyboard/InputViewController.swift#L112-L122

**Comment by jahorton** [comment]
Noting that we should always be showing a banner at this point, we should probably drop the `hideBanner` logic in favor of always showing it.  Interestingly, though... that seems to present a new iteration of the problem:

![image (8)](https://github.com/keymanapp/keyman/assets/25213402/3c24f1d8-6c5d-4922-8934-5b0743fa54f8)

Note that the left-hand side seems to have extra space underneath the keyboard compared to the right-hand side; I'm pretty sure that's the whole explanation for the difference here... and looking back, that same difference is visible in the original version too.
