### ISSUE TITLE
bug(android): The On-Screen Keyboard (OSK) briefly showed a black screen, after opening Keyman app 

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#10879]
### Describe the bug

After opening the Keyman app, there was a brief moment where a black screen appeared in the On-Screen Keyboard (OSK).

### Reproduce the bug

1. Install Keyman 17.0.277- beta
2. Open Keyman In-App.

I observed that the on-screen keyboard briefly displayed a black screen before becoming visible. I have attached a video file for reference. 

https://github.com/keymanapp/keyman/assets/19683143/f21460e5-fa96-4482-8026-0ddd28143be4

### Expected behavior

Opening Keyman should immediately show the on-screen keyboard without a black screen.

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.277-beta

### Operating system

Android 12, 13

### Device

Samsung Mobile 13 AG23 device

**Comment by darcywong00** [comment]
Maybe similar to #10648

**Comment by darcywong00** [comment]
> Opening Keyman should immediately show the on-screen keyboard without a black screen.

From your video, that seems like a typical time it takes KeyamnWeb to initialize to show the OSK. 

While we don't have a consistent repro for #10648 - that one was a significant time before showing the OSK.

**Comment by darcywong00** [comment]
I'll call this a dupe of #10648
