### ISSUE TITLE
bug(android): Keyman app crashes when trying to add a space to previously typed texts

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#10870]
### Describe the bug

https://github.com/keymanapp/keyman/assets/28331388/3dc6dfe2-836a-494c-87e6-7d21c89a86cb

The same behavior happens when using Keyman as a system keyboard to type the text in Google omnibox.

### Expected behavior

A space should be added without crashing.

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.275-beta

### Operating system

Android 10

### Device

Galaxy S9+

### Target application

Keyman and Google omnibox

### Keyboard name

EuroLatin (SIL)

### Keyboard version

2.0.4

### Language name

English

**Comment by darcywong00** [comment]
See #10835 - the crash is fixed by one of the associated PRs
