### ISSUE TITLE
bug(android): move cursor to previously typed text and typing new text in causes deletion of some texts before the cursor

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#10874]
### Describe the bug

https://github.com/keymanapp/keyman/assets/28331388/79804c9a-1adf-49f9-be2d-62710677f3c2

### Expected behavior

No text should be deleted. What is typed should be added to where the cursor is placed without deleting anything before it.

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.275-beta

### Operating system

Android 10

### Device

Galaxy S9+

### Target application

Keyman and elsewhere

### Keyboard name

EuroLatin (SIL)

### Keyboard version

2.0.4

### Language name

English

**Comment by darcywong00** [comment]
See #10835 which should be fixed soon

**Comment by darcywong00** [comment]
@MakaraSok - Can you retest and see if this is still an issue in [Keyman version 17.0.278-beta](https://keyman.com/downloads/releases/beta/17.0.278)?

**Comment by MakaraSok** [comment]
Hi Darcy, I've tested with Keyman 17.0.281-beta, and the issue seems to be fixed and I can no longer reproduce the behavior.
