### ISSUE TITLE
bug(android): backspace make Keyman failed

### ISSUE THREAD

**Issue by Nnyny** [keymanapp/keyman#10912]
### Describe the bug

I was using Khmer Angkor keyboard in a dictionary app. When I tried to delete consonants that are in the middle of the word, Keyman ask to clear the history. And when I click ' clear now' , it delete Khmer Angkor keyboard. 

https://github.com/keymanapp/keyman/assets/123520338/df617539-e480-45eb-ba3a-f2e835e787d0

However, when I test this same method in Keyman app, it keeps kicking me out. Normal words are ok to delete. But words with ceong seems be the issue. 

https://github.com/keymanapp/keyman/assets/123520338/506ab85a-a850-4800-8d65-053b7cec0d4a

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.273 Beta

### Device

Oppo F11 Pro

### Target application

Khmer Dictionary

### Keyboard name

Khmer Angkor 

### Keyboard version

latest version (not available yet) 

### Language name

Khmer

**Comment by mcdurdin** [comment]
Thanks for the error report @Nnyny. I think this is the same as #10835, so can we try again next week when the fixes are all merged?

**Comment by Nnyny** [comment]
Noted, @mcdurdin.

**Comment by darcywong00** [comment]
Backspace fixes are in newer beta versions. Can you update and see if it's still an issue?

> Changes in this pull request will be available for download in [Keyman version 17.0.278-beta](https://keyman.com/downloads/releases/beta/17.0.278)

**Comment by Nnyny** [comment]
It works perfectly in KM and other apps. Thank you @darcywong00.
