### ISSUE TITLE
bug(developer): Core crash debugging sil_ipa keyboard

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#10915]
I was looking into keymanapp/keyboards#2401 on MSEA time (adding subscript numerals to sil_ipa).

I tried to type `n>` and the right-shift key (to type >) threw this exception
![image](https://github.com/keymanapp/keyman/assets/7358010/fd168d86-f22a-4c7c-bfd3-1459a993750f)
which crashed the entire keyboard project.

In further repros, I found just typing right-shift in the debugger caused the same exception

>Details for error report for Keyman app:
> Application Identifier: tike-17.0.280-beta
> Error Identifier: BE0F3BD5FF484E3C08AE2D901401CE37

## Configuration
Windows 11 Version 22H2 (OS build 22621.3155)
Keyman Developer 17.0.280-beta
Keyboard: sil_ipa (from master)

**Comment by mcdurdin** [comment]
Shouldn't press the right shift key. Golly gosh.

**Comment by mcdurdin** [comment]
:grin:

**Comment by mcdurdin** [comment]
Left shift works fine.

Right shift crashes for me too.

**Comment by darcywong00** [comment]
yep, I tried all the modifiers and only right-shift is crashing
