### ISSUE TITLE
feat: Is there a way to build iOS engine without using ngrok, computers are restricted to using ngrok

### ISSUE THREAD

**Issue by xiaoluokai** [keymanapp/keyman#10928]
### Is your feature request related to a problem? Please describe.

m ERR! command failed
npm ERR! command sh -c node ./postinstall.js
npm ERR! ngrok - downloading binary https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-darwin-arm64.zip
npm ERR! ngrok - downloading progress: 
npm ERR! ngrok - error downloading from URL RequestError: self signed certificate in certificate chain
npm ERR!     at ClientRequest.<anonymous> (/Users/gumei/Desktop/work/keyman/node_modules/got/dist/source/core/index.js:970:111)
npm ERR!     at Object.onceWrapper (node:events:510:26)
npm ERR!     at ClientRequest.emit (node:events:402:35)
npm ERR!     at ClientRequest.origin.emit (/Users/gumei/Desktop/work/keyman/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
npm ERR!     at TLSSocket.socketErrorListener (node:_http_client:447:9)
npm ERR!     at TLSSocket.emit (node:events:390:28)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:157:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:83:21)
npm ERR!     at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)
npm ERR!     at TLSSocket.emit (node:events:390:28)
npm ERR!     at TLSSocket._finishInit (node:_tls_wrap:944:8)
npm ERR!     at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12) {
npm ERR!   code: 'SELF_SIGNED_CERT_IN_CHAIN',

### Describe the solution you'd like

I only want to use iOS engine, but I have to download and compile many web-related products. In addition, the company computer also restricts the use of ngrok, so it has been unable to compile successfully. I wonder if there is a way to compile only the smallest products to support use

### Keyman apps

- [ ] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

**Comment by jahorton** [comment]
The `ngrok` errors appear to be happening from `npm` itself, not any code we directly control.

The core of our keyboarding engine for iOS is actually Web-based.  If you're not looking to edit the Web-based components, you could bypass their compilation with a bit of effort:

https://github.com/keymanapp/keyman/blob/0a40c1a4236fbf383f4526bdc2ea06a578510698/ios/engine/build.sh#L19-L21

Remove lines 20 and 21.  They're part of our custom shell-scripting setup and will trigger Web-based builds.

https://github.com/keymanapp/keyman/blob/0a40c1a4236fbf383f4526bdc2ea06a578510698/ios/engine/build.sh#L102-L116

This is the section that bundles our compiled `app/webview` Web engine into the iOS engine.  We don't directly publish this as a separate component, but the good news is that you can directly extract the results of this process - or even the individual files within - from one of our published builds.

1. Go to https://downloads.keyman.com/ios/stable or https://downloads.keyman.com/ios/beta, depending on which release tier you want.  (`/alpha` exists too, but `/beta` is our current bleeding-edge tier at the moment, as we're nearing release.)
2. Scroll all the way to the bottom to get the latest version.
3. Download `keyman-engine-ios-<version>.zip`.
4. Navigate to this level within the downloaded .zip:

    ![image (6)](https://github.com/keymanapp/keyman/assets/25213402/289a7223-a1f1-40d1-9be2-52a99b3048db)

Replace the corresponding folder in this repo with that bundle.  From our repo root, that would be at `ios/engine/KMEI/KeymanEngine/resources/Keyman.bundle`.

You may then erase all code within the previously-noted code block, leaving `updateBundle` an empty shell.

https://github.com/keymanapp/keyman/blob/0a40c1a4236fbf383f4526bdc2ea06a578510698/ios/engine/build.sh#L102-L116

**Comment by xiaoluokai** [comment]
您好，您发的邮件我已经受到了，我会尽快查看的。                                                            骆锴

**Comment by jahorton** [comment]
Additionally, we have some ongoing work to make it easier to use the iOS samples apps without needing our repository.

In the meantime, perhaps that `keyman-engine-ios-<version>.zip` I referred to above is exactly what you were looking for?  Granted, it's a manual download and not very CI-friendly at this time.  We do have APIs for requesting the latest available version of our products, though, so something CI-compatible should be possible - feel free to post an extra issue or to make a post on our [Community site](https://community.software.sil.org/c/keyman/19) for help in this regard if desired.

I'm going ahead and closing this issue for now, as its intent is technically better-suited for the Community site.  We believe the main concerns to be addressed at this time, though we are open to further discussion and/or requests for help, even if on this issue.

**Comment by xiaoluokai** [comment]
您好，您发的邮件我已经受到了，我会尽快查看的。                                                            骆锴
