### ISSUE TITLE
bug(developer): Compiler incorrectly giving an error for escaped unicode characters u\{000a} 

### ISSUE THREAD

**Issue by rc-swag** [keymanapp/keyman#10937]
The compiler is incorrectly giving an error for the following ldml transform group. Also, the error is incorrectly formatted.
reported for developer version: ver 17.0.281-beta.  It compiled ok in version 17.0.264
```    
    <transformGroup>
      <transform from="\m{hat}e" to="ê"/> 
      <transform from="a\u{000D}\u{000A}b" to="ROWb"/>
      <transform from="a\u{000A}c" to="ROWc"/>
    </transformGroup>
    ```
    This is the error 
    ```
newline.xml - info KM05002: Building newline.xml
newline.xml - error KM00030: Invalid escape "\u000d", use "\u{d}" instead.
newline.xml - error KM00030: Invalid escape "\u000a", use "\u{a}" instead.
newline.xml - fatal KM0000F: Unexpected exception: The compiler for 'tran' failed unexpectedly.
```
The message should be formatting the \u{d} code with zero prefixes \u{000d}
The exception failing I may be the same as #10894

**Comment by srl295** [comment]
could well be.

I thought there was another issue for the 'failed unexpectedly' which shouldn't happen.
