### ISSUE TITLE
feat(developer): tests CompilerMessage  matching should be loose

### ISSUE THREAD

**Issue by srl295** [keymanapp/keyman#10943]
I was concerned about this in #10689 and it's here.

- Node.js v18.19.1

```shell
$ node -p 'new RegExp("(ABC","gu")'
SyntaxError: Invalid regular expression: /(ABC/: Unterminated group
```

- node v20.11.1

```shell
$ node -p 'new RegExp("(ABC","gu")'
SyntaxError: Invalid regular expression: /(ABC/gu: Unterminated group
```

test case should allow a regex for matching messages. (Or we should somehow sanitize the regex message?)

**Comment by mcdurdin** [comment]
Happy with the solution you've come up with in #10948. That will be sufficient as it's a unit test. Wouldn't want that to go out in runtime code though, too fragile.
