### ISSUE TITLE
bug(web): The SIL Cameroon QWERTY keyboard does not show up in the keyboard list after being added through the "Add a keyboard by language name" section

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#10975]
### Describe the bug

I noticed that the SIL Cameroon QWERTY keyboard doesn't appear in the keyboard list after adding it through the "Add a keyboard by language name" section.

### Reproduce the bug

1. Open the following web link 
https://build.palaso.org/repository/download/Keymanweb_TestPullRequests/448575:id/index.html
2. Click View Keymanweb use samples link. 
3. Click Example 1 - Toggle UI, all resources in same folder as page
4. Type sil_cameroon_qwerty against the 'Add a keyboard by language name' field. 
5. Click the Add button. 
6. Click the 'Type in your language in this text area' field.
7. Click the Keyboard list that appears at the right corner of the text area field. 

Here, I noticed that the sil_cameroon_qwerty keyboard was missing in the keyboard list. Seems to be an issue. 

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/1a8836e5-1975-4bcd-919a-7cbd1fde5af1">

### Expected behavior

Adding 'sil_cameroon_qwerty' keyboard should be displayed in the Keyboard list. 

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [X] KeymanWeb
- [ ] Other - give details at bottom of form

**Comment by jahorton** [comment]
That's a keyboard id/name, not a language name.  Try the input field before that one instead.

**Comment by bharanidharanj** [comment]
@jahorton  Okay. As per your suggestion, I tried with a Keyboard name (ie., sil_cameroon_qwerty) and noticed that some other cameroon_qwerty keyboards (not sil_cameroon_qwerty) appeared in the keyboard list. So, I selected one of the keyboards for testing. But, in the regression test suite, it seems that we should choose only the sil_cameroon_qwerty keyboard. So, it seems to be an issue. 

..Baseline_Cameroon_test

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/4fca98fc-b2c4-44f4-9580-04066766c477">

..Some other keyboard appeared instead of sil_cameroon_qwerty keyboard

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/fcaab7e1-2156-42e6-8a1e-f6871e14229f">

**Comment by mcdurdin** [comment]
> But, in the regression test suite, it seems that we should choose only the sil_cameroon_qwerty keyboard. So, it seems to be an issue.
> 
> ..Baseline_Cameroon_test
> 
> ..Some other keyboard appeared instead of sil_cameroon_qwerty keyboard

I think this is okay -- what you are seeing is the first language name associated with the SIL Cameroon QWERTY keyboard.
