### ISSUE TITLE
bug(ios): The predictive text did not reappear in the suggestion bar after clearing the symbols (<>/) using Clear text option

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#10979]
### Describe the bug

After clearing the text, I observed that the predictive text was absent from the suggestion bar. This occurs only when we type symbols and then clear them using the 'clear text' option on the text screen.

### Reproduce the bug

1. Intsall Keyman 17.0.287-beta
2. Enter some text. (eg., The)
3. Verify some suggestions appeared on the suggestion bar. 
4. Click the three dots (...)button, then click the 'Clear text' button. 
5. Verify that predictive texts appeared on the bar. 
6. Long press 'd' key, hold the 'd' key, and drag it to a downward direction. 
7. Verify that '<" symbol appears then release it. 
8. Verify the "<" symbol appears on the text screen. 
9. Click the three dots(...) button, then click the 'Clear text' button. 
10. Verify that no symbol appeared on the screen. 

Here, I observed that the predictive text that usually appears on the suggestion banner was missing. I tried the same steps on an Android OS, and the predictive text appeared on the suggestion banner. This issue appears to be specific to the iOS platform.

I have attached the Video file for reference. 

https://github.com/keymanapp/keyman/assets/19683143/d0d190dc-0a3b-44e1-9d6c-d49bcbeb0e88

### Expected behavior

The predictive text should be visible in the suggestion bar after clearing the symbols using the "Clear text" option.

### Keyman apps

- [ ] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.287-beta

### Operating system

iOS 17.4

### Device

iPhone 13 Mobile

### Keyboard name

sil_euro_latin

### Keyboard version

3.0.0

### Language name

english

**Comment by jahorton** [comment]
This no longer reproduces.  I'm fairly certain this was originally due to some of the context-synchronization work that was happening at the time (such as #10728, #10869, and #10956).  #10869 is most likely to be the fix.
