### ISSUE TITLE
feat: Is there a 26-key Chinese Pinyin input method that can be used in iOS platform

### ISSUE THREAD

**Issue by xiaoluokai** [keymanapp/keyman#10972]
### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

**Comment by mcdurdin** [comment]
At this point, we don't have this, and there are some challenges around supporting it on iOS with the current toolchain. We have a feature on our roadmap to extend support for "input method extensions (IMX)" to iOS and Android, and that functionality would need to be the basis for this feature.

I'm going to go ahead and close this as an issue; please see #7928 which we will be our tracking issue for IMX support, currently on the roadmap for version 19.0.

**Comment by xiaoluokai** [comment]
Thank you for your reply. I will follow you all the time！
