### ISSUE TITLE
bug(web): Typing "qwer" on the On-Screen Keyboard (OSK) fails to display relevant words (e.g., "qwerty") on the suggestion bar.

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#11006]
### Describe the bug

When typing "qwer" in the text input field, the corresponding predictive text doesn't appear in the suggestion banner.

### Reproduce the bug

1. Install Keyman 17.0.288-beta
2. Open the Keyman In-app.
3. Type 'qwer' using the OSK.

I noticed that the suggestion bar didn't show any relevant words for "qwer," such as "qwerty." This seems to be an issue.

..in Android OS

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/69cb9f56-027e-43ce-a17a-fa32499be2ec">

..in iOS

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/71095920-06e6-4bb5-8d83-976c37a07365">

### Expected behavior

When typing "qwer" using the On-Screen Keyboard (OSK), the relevant words (e.g., "qwerty") should appear on the suggestion bar.

### Keyman apps

- [X] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.288-beta

### Operating system

Android 12, 13, iOS 17.4

### Device

API 34 emulator, iPhone 13 Mobile device

### Keyboard name

english_eurolatin_sil

### Keyboard version

3.0.1

### Language name

English

**Comment by mcdurdin** [comment]
'qwerty' is not technically a word I think :grin:

I'm going to go ahead and close this one @bharanidharanj -- we just did a round of updates to the English dictionary and so we'll pause before we do more.

**Comment by bharanidharanj** [comment]
> 'qwerty' is not technically a word I think 😁
> 
> I'm going to go ahead and close this one @bharanidharanj -- we just did a round of updates to the English dictionary and so we'll pause before we do more.

@mcdurdin Okay, Thanks for the clarification. 👍
