### ISSUE TITLE
bug(android): Keys get stuck and highlight incorrectly after holding the shift key and pressing any key rapidly in the Cameroon Qwerty Keyboard

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#11019]
### Describe the bug

I noticed that the problem occurs when I hold the shift key and then randomly press any key in the Cameroon Qwerty Keyboard.

### Reproduce the bug

1. Install Keyman 17.0.289-beta 
2. Download and Install Cameroon Qwerty - Bafanji keyboard. 
3. Switch to 'Bafanji' Keyboard. 
4. Click the Triple Colour button from the OSK. 
5. Verify that the special symbol layer is visible on the keyboard. 
6. Hold the Shift key. 
7. Rapidly press any key from the OSK. 

Here, I noticed that a key got stuck, and some keys were highlighted on the keyboard. Seems to be an issue. 

I have attached the Video file for reference. 

https://github.com/keymanapp/keyman/assets/19683143/dcc20d13-6e56-462d-aa7f-7edae1fa4c70

### Expected behavior

Keys shouldn't stick, and they should function properly.

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.289-beta

### Operating system

Android 13

### Device

Samsung Mobile 13 AG23 device

### Keyboard name

cameroon_qwerty

### Keyboard version

6.1.0

### Language name

Bafanji

**Comment by darcywong00** [comment]
@bharanidharanj - can you retest after tomorrow's beta 17.0.301+ to see if #10778 fixes this?

**Comment by darcywong00** [comment]
Assigning to @bharanidharanj to retest with the latest beta

**Comment by bharanidharanj** [comment]
> Assigning to @bharanidharanj to retest with the latest beta

@darcywong00 Retested with the latest Keyman 17.0.315-beta build on an Android 13 Mobile device and here is my observation: 1. Followed the steps as mentioned in the description. 2. I was not able to reproduce this issue with the latest build. Seems to be working fine with the latest build. It would be better to close this issue. Thanks.

**Comment by darcywong00** [comment]
Fixed by #10778
