### ISSUE TITLE
bug(oem/fv/ios): The appearance of the FirstVoices keyboard banner differs between Android and iPhone devices

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#11018]
### Describe the bug

I noticed a difference in the color of the FirstVoices banner between Android and iPhone devices.

### Reproduce the bug

1. Install FirstVoices 17.0.287-beta build on an iPhone 13 (ver iOS 17.4)  Mobile device. 
2. Install Haisla and SENCOTEN FV keyboards. 
3. Set FirstVoices Keyboard as the the system keyboard. 
4. Open a browser. 
5. Switch to FirstVoices - Haisla keyboard. 
6. Verify the FirstVoices banner appear on the OSK. 
7. Install FirstVoices 17.0 - beta build on an Android 13 Mobile device. 
8. Install FirstVoices keyboards. 
9. Set FirstVoices Keyboard as the system keyboard. 
10. Open  a browser. 
11. Switch to FirstVoices - Haisla keyboard. 

I noticed that the FirstVoices banner appears different when compared to an iPhone's FV keyboard.

I have attached the Screenshots for reference. 

..FV banner in Android Mobile

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/37d380a3-f7eb-44e0-9f0d-e161d0b620d1">

..FV banner in iPhone Mobile

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/8ca93dd6-89ae-4ebe-8553-cda9f15554d2">

### Expected behavior

The same banner design should appear on both Android and iPhone devices.

### Keyman apps

- [X] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.287-beta

### Operating system

Android 12, 13, iOS 17.4

### Device

Samsung Mobile 13 AG23 device, iPhone 13 Mobile

### Keyboard name

Haisla

### Keyboard version

1.0

### Language name

Haisla

**Comment by darcywong00** [comment]
The keyboards already have separate "themes" to match their respective devices.
Per A18S8 sprint plan, we won't fix this.
