### ISSUE TITLE
test(android): Regression Test Report 17.0.286-Beta (12failures)

### ISSUE THREAD

**Issue by sillsdev-dondillard** [keymanapp/keyman#11026]
```
Test Report for Keyman 17.0.286 Beta Android
Results 

 Expected Start Date 3/12/2024
 Actual Start Date 3/12/2024

 Overall Results: 89% (96/108 passed)

Regression Tests
 Android 5.0     89% (32/36 passed)
 Android 9.0     89% (32/36 passed)
 Android 12.0   89% (32/36 passed)
```
Issues Found
First issue :
* #8557 
Test cases failed due to this issue :
1)TC 10 - (Android 5.0) - Test case for Install Updates menu
2)TC 46 - (Android 9.0) - Test case for Install Updates menu
3)TC 82 - (Android 12.0) - Test case for Install Updates menu

Second issue : 
* #11006 
Test cases failed due to this issue :
4)TC 16 - (Android 5.0)- Test case for type on the OSK would show the expected output English (EuroLatin SIL)
5)TC 22 - (Android 5.0) - Test case for type on the System Keyboard would show the expected output English (EuroLatin SIL)
6)TC 52 - (Android 9.0)- Test case for type on the OSK would show the expected output English (EuroLatin SIL)
7)TC 58 - (Android 9.0) - Test case for type on the System Keyboard would show the expected output English (EuroLatin SIL)
8)TC 88 - (Android 12.0)- Test case for type on the OSK would show the expected output English (EuroLatin SIL)
9)TC 94 - (Android 12.0) - Test case for type on the System Keyboard would show the expected output English (EuroLatin SIL)

Third issue : 
* #10608 
Test cases failed due to this issue :
10)TC 36 - (Android 5.0) - Test case for Rapid_Typing (Rapid typing on first caps letters ometimes give TWo cap letters)
11)TC 72 - (Android 9.0) - Test case for Rapid_Typing (Rapid typing on first caps letters ometimes give TWo cap letters)
12)TC 108 - (Android 12.0) - Test case for Rapid_Typing (Rapid typing on first caps letters ometimes give TWo cap letters)

**Comment by mcdurdin** [comment]
> * 4)TC 16 - (Android 5.0)- Test case for type on the OSK would show the expected output English (EuroLatin SIL)
>   5)TC 22 - (Android 5.0) - Test case for type on the System Keyboard would show the expected output English (EuroLatin SIL)
>   6)TC 52 - (Android 9.0)- Test case for type on the OSK would show the expected output English (EuroLatin SIL)
>   7)TC 58 - (Android 9.0) - Test case for type on the System Keyboard would show the expected output English (EuroLatin SIL)
>   8)TC 88 - (Android 12.0)- Test case for type on the OSK would show the expected output English (EuroLatin SIL)
>   9)TC 94 - (Android 12.0) - Test case for type on the System Keyboard would show the expected output English (EuroLatin SIL)

These test cases need to be updated per issue #11006 resolution. 'qwerty' is not a word, so it is not in the dictionary.
