### ISSUE TITLE
bug(oem/fv/ios): FirstVoices banner disappears on the OSK when switching between keyboards

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#11025]
### Describe the bug

I noticed that the FirstVoices banner on the OSK disappears after switching to another FV keyboard. 

### Reproduce the bug

1. Install FirstVoices 17.0.291-beta
2. Install 'Haisla' and 'SENCOTEN' keyboards.
3. Set FV Keyboard as the system keyboard. 
4. Open Safari browser. 
5. Switch to FV Keyboard. 
6. Verify that the Haisla keyboard appears along with FV banner. 
7. Switch to 'SENCOTEN' keyboard. 

Here, I noticed that the FirstVoices banner was missing on the OSK. Seems to be an issue. 

I have attached the Video file for reference. 

https://github.com/keymanapp/keyman/assets/19683143/b9e50e6d-3338-4723-9315-81d8ff0ae2f7

### Expected behavior

The FirstVoices keyboard should be visible after keyboard switching. 

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [x] Other - give details at bottom of form

### Keyman version

FirstVoices 17.0.291-beta

### Operating system

iOS 17.4

### Device

Samsung Mobile 13 AG23 device

### Keyboard name

Haisla, SENCOTEN

**Comment by mcdurdin** [comment]
@sgschantz can you take a look?

**Comment by darcywong00** [comment]
Editing the title and description for FV

**Comment by jahorton** [comment]
@bharanidharanj Do you still see this in the FV apps?  I'm asking because #10929 landed since this issue was posted, and that PR fixed a fair amount of banner-related problems.

**Comment by sgschantz** [comment]
@bharanidharanj Do you still see this or has it been addressed?

**Comment by bharanidharanj** [comment]
> @bharanidharanj Do you still see this in the FV apps? I'm asking because #10929 landed since this issue was posted, and that PR fixed a fair amount of banner-related problems.

@jahorton It is still problematic in the FirstVoices 17.0.281-beta build (#10929). Anyhow, I will test with the latest one and will add my comment.

**Comment by bharanidharanj** [comment]
@sgschantz Retested this with the latest FirstVoices 17.0.305-beta build and it seems to be working fine. ie., The FirstVoices keyboard banner appears consistently during the Keyboard switching. It would be better to close this issue. Thanks.
