### ISSUE TITLE
bug(developer): An error message is displayed in the Keyman Developer window when attempting to upgrade the sil_buang project

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#11020]
### Describe the bug

After clicking the 'upgrade project' button in the keyboards tab, I observed an error message appearing in the Keyman Developer window.

### Reproduce the bug

1. Install Keyman Developer 17.0.289-beta
2. Open an existing project "sil_buang.kpj"
3. Click the Keyboards tab in the Keyman Developer window.
4. Click the "sil_buang.kmn" blue link button. 
5. Click "Upgrade Project" button. 

Here, I noticed that an error message is displayed on the screen. Also, observed that some irrelevant messages appeared on the Messages panel. FYI, I did not find the mentioned HISTORY.md file outside of the project folder.  Seems to be an issue. 
 
  <img width="600" src="https://github.com/keymanapp/keyman/assets/19683143/36db3dfb-09f6-4c7d-9065-514c91845de0">

### Expected behavior

Clicking on the 'Upgrade Project' button should upgrade the 'sil_buang' project to the Keyman Developer 17.0 project format. 

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [X] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.289-beta

### Operating system

Windows 10 OS

### Device

Desktop

### Keyboard name

sil_buang

**Comment by mcdurdin** [comment]
This looks like it is doing what we expect.

The message here identifies that you have referenced the file HISTORY.md somewhere in your project; check the Distribution tab as that is the most likely place. 

If you can't find the file referenced in the project anywhere, can you attach the .kpj to this issue?
