### ISSUE TITLE
bug(developer): escape on string substitution if syntax char

### ISSUE THREAD

**Issue by srl295** [keymanapp/keyman#11037]
```xml
		<string id="caret"  value="^" />
```

```xml
			<transform from="${caret}($[vowel])"  to="$[1:caretVowel]" />
```

This expands to basically `<transform from="^a" to="â"/>`  meaning the first `a` in the buffer gets a bonus caret

I think the solution is that when var substitution happens such as `${caret}` it should escape to `\u{005e}` thus

```xml
<transform from="\u{005e}a" to="â" />
```

which will then match correctly

**Comment by mcdurdin** [comment]
Yes, this is definitely a serious bug. It's a way to escape our regex boundaries too. Is this substitution done in the compiler or in Core (or are both potentially a problem?)

**Comment by srl295** [comment]
> Yes, this is definitely a serious bug. It's a way to escape our regex boundaries too. Is this substitution done in the compiler or in Core (or are both potentially a problem?)

Compiler only

**Comment by srl295** [comment]
Is it actually user err?

Could a string variable contain part of a regex pattern?

I think the answer is "no" to both.

**Comment by srl295** [comment]
> Yes, this is definitely a serious bug. It's a way to escape our regex boundaries too. Is this substitution done in the compiler or in Core (or are both potentially a problem?)

To be clear the issue is NOT escaping a literal when it occurs in a string. 

"^a" in a pattern will match at at begin, "\^a" would be needed to match "^a". That's to spec. 

The bug is including the variable as syntax instead of escaped.

**Comment by mcdurdin** [comment]
> Is it actually user err?
> 
> Could a string variable contain part of a regex pattern?
> 
> I think the answer is "no" to both.

no and no.

> To be clear the issue is NOT escaping a literal when it occurs in a string.
> 
> "^a" in a pattern will match at at begin, "^a" would be needed to match "^a". That's to spec.
> 
> The bug is including the variable as syntax instead of escaped.

Correct. variables must always be text, not syntax.

**Comment by srl295** [comment]
also need to escape set variables
