### ISSUE TITLE
bug(developer): IDE not capturing Alt in LDML keyboard test mode

### ISSUE THREAD

**Issue by srl295** [keymanapp/keyman#11036]
1. create a keyboard (ldml or kmn)
2. enter test mode
3. type an alt key, such as `alt-E`

The key is picked up by the test keyboard (here U+20AC in the screenshot) but the alt key is also processed by Windows 11. It will either beep or pop open a menu, or potentially perform other tasks (!)

![image](https://github.com/keymanapp/keyman/assets/855219/b402e5f6-daf5-435f-b37e-d3b1d6bca07f)

**Comment by mcdurdin** [comment]
Capture seems to be fine for .kmn?
