### ISSUE TITLE
bug(android): An error message appears on the screen when using the globe key in the Android 14.0 / API 34 emulator

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#11038]
### Describe the bug

I noticed that some error message appeared on the screen while using the globe key to change the keyboards. 

### Reproduce the bug

1. Install Keyman 17.0.291-beta
2. Open Keyman In-app. 
3. Install 'Cameroon qwerty' and 'SIL (IPA)' keyboards. 
4. Use globe to switch to some other keyboards.

Here, I noticed that some error messages appeared on the screen while clicking the globe key. Seems to be an issue in Android 14.0 OS. 

Note: Not able to reproduce in other Android versions. 

I have attached the video file for reference. 

https://github.com/keymanapp/keyman/assets/19683143/e2b2e250-21d0-440b-aa97-aaad4387f142

### Expected behavior

No error message should display when switching keyboards using the globe key.

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.291-beta

### Operating system

Android 14 OS

### Device

API 34 emulator (Android Studio - Iguana)

**Comment by mcdurdin** [comment]
Doesn't seem to have a corresponding android/web crash report?

**Comment by mcdurdin** [comment]
Assigning both @ermshiperete and @jahorton -- whoever is available to look first

**Comment by darcywong00** [comment]
Maybe this is the [Typeface error](https://keyman.sentry.io/issues/5089114809/?project=5983520&query=release%3Arelease%4017.0.291-beta&referrer=release-issue-stream) in Sentry.

**Comment by darcywong00** [comment]
I see the Sentry crash. But not sure what else Keyman for Android can do to mitigate.

https://github.com/keymanapp/keyman/blob/c5be18040885a5b217dbeb3b578872903af1a69c/android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java#L1338-L1359

In sil_ipa, the font file CharisSIL-Regular.ttf exists. 
l. 1350 runs and internally it throws IndexOutOfBoundsException which we catch in l. 1354.

**Comment by bharanidharanj** [comment]
@darcywong00 I got another error (?) message while testing PR  #11076 when I installed Cameroon Qwerty keyboard in the Keyman application. I have attached the video file for reference. Thanks. 

https://github.com/keymanapp/keyman/assets/19683143/35c14489-3cd0-4ef7-9f58-9d2c86ff98c3

**Comment by darcywong00** [comment]
It seems like your emulator is having issues downloading kmp package files intact.

In the emulator, can you try downloading from
https://downloads.keyman.com/keyboards/sil_cameroon_qwerty/6.1.0/sil_cameroon_qwerty.kmp

And then install from local file in Keyman for Android? See if that changes anything...

**Comment by darcywong00** [comment]
The failure to set the font is caught by the app and stable builds won't display the Toast error.
Closing as "Won't fix"
