### ISSUE TITLE
bug(developer): compile issue window needs horizontal scroll or wrap

### ISSUE THREAD

**Issue by srl295** [keymanapp/keyman#11042]
![image](https://github.com/keymanapp/keyman/assets/855219/4a247308-d0ff-4a88-94de-97da67512cf0)

double clicking on the long line does seem to scroll it over, but that's not exactly intuitive

**Comment by mcdurdin** [comment]
I get sourcemaps on my Keyman Developer. Can you include a full screen shot for context?

**Comment by srl295** [comment]
indeed there _is_ a scrollbar. However, the area doesn't respond to scroll wheel (two finger) events, and I didn't recognize the inactive scrollbar. 

![image](https://github.com/keymanapp/keyman/assets/855219/8dd30b0b-b6fe-4bbd-99bf-4db8c66cd621)

when moused over:
![image](https://github.com/keymanapp/keyman/assets/855219/490fd355-ad5a-4ed9-92fe-e948f7f62499)


The code area has scrollbars that fade in and out ('active') when you mouse over the code area, and it responds to scroll wheel events. So I assumed that the messages area would be similar if it had scrolling.

![image](https://github.com/keymanapp/keyman/assets/855219/80bbb3bf-9d4c-4601-adb2-46430ecfee1d)

@mcdurdin i'm moving this to v18 ?

**Comment by mcdurdin** [comment]
I think I am going to close as wontfix, given the IDE is about to undergo complete rewrite anyway.
