### ISSUE TITLE
bug(developer): U+166C not appearing correctly in mobile app or on keyboard

### ISSUE THREAD

**Issue by HopsAndHops** [keymanapp/keyman#11055]
### Describe the bug

ᙬ (U+166C, Canadian Syllabics Carrier TTSA) is not appearing correctly in the Keyman mobile app or keyboard. It instead appears as ᙠ (U+1660, Canadian Syllabics Carrier TSA). 
![SCSTestKeyman](https://github.com/keymanapp/keyman/assets/127360690/e9a04849-0c3f-4988-8295-e890906196a1)

When typed in other apps and in the test window, it looks correct.
![SCSDiscordTest](https://github.com/keymanapp/keyman/assets/127360690/8c311102-034c-4040-9f93-a6ed3a0e6694)

![Screenshot 2024-03-22 at 10 42 09 AM](https://github.com/keymanapp/keyman/assets/127360690/a359ddbf-66fe-47c9-8070-e83c3d1a722f)

The keyboard was initially using Aboriginal Sans and I switched to Gadugi, the default fallback front for Canadian Aboriginal Syllabics, but it's still displaying as U+1660.

### Keyman apps

- [X] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [x] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16.0.147 (developer and Android)

### Operating system

Android 14; Windows 11

### Device

Samsung Galaxy z Flip3; virtual Windows desktop on iMac

### Keyboard name

fv_southern_carrier

### Keyboard version

10.0

### Language name

ᑐᑊᘁᗕᑋᗸ

### Additional context

This keyboard is on a different branch from the desktop Southern Carrier keyboard I reported a bug with 2 weeks ago - I'll DM this version to @mcdurdin

**Comment by mcdurdin** [comment]
This looks like a font issue. Aboriginal Serif (and possibly some versions of Aboriginal Sans) render these two letters identically (or so near as to be identical). I wonder if the font switch to Gadugi actually worked -- how did you select the font, and did you include the gadugi ttf in the package? (I don't know what the license details are for Gadugi, is it redistributable?)

Aboriginal Sans:
![image](https://github.com/keymanapp/keyman/assets/4498365/99583a77-8fe7-4797-b525-5215090e2d5a)

Aboriginal Serif:
![image](https://github.com/keymanapp/keyman/assets/4498365/69c1dbe5-a5af-46d5-8a76-536f73ab0ef8)

Euphemia:
![image](https://github.com/keymanapp/keyman/assets/4498365/f472e77a-e73c-4bb7-849c-c958360f736a)

Gadugi:
![image](https://github.com/keymanapp/keyman/assets/4498365/59791f53-a740-4d9c-9536-6f422b9ba446)

Quivira:
![image](https://github.com/keymanapp/keyman/assets/4498365/b0748e08-53df-4a39-9ab9-bbdffa91e756)

**Comment by HopsAndHops** [comment]
Hi @mcdurdin , thanks for pointing out the issue with Aboriginal Serif, that's definitely frustrating. 

Unfortunately it looks like Gadugi cannot be packaged as per Microsoft's TOU. I'll give it another try with Aboriginal Sans and see if that goes better. 

To change the font I followed the usual route: Keyboard > Fonts... > Touch Layout - Tablet. Did I maybe miss a step there?

**Comment by mcdurdin** [comment]
The Keyboard > Fonts dialog is appropriate for testing locally. However, when you build the keyboard package for installation, you should use the Package Wizard / Keyboards tab / Fonts settings. (This is a little unintuitive and we are looking for ways to make this clearer)

**Comment by mcdurdin** [comment]
Going ahead and closing this as a font issue. Please reopen if it turns out there is more to it!
