### ISSUE TITLE
bug(ios): No space between words when replacing selected text with a letter

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#11095]
### Describe the bug

I noticed that after pressing a letter to replace selected text, there is no space between the words.

### Reproduce the bug

1. Install Keyman 17.0.295-beta
2. Open Keyman app.
3. Type two words. eg., Something Beautiful
4. Select the second word 'beautiful'.
5. Press letter 'B'. 

Here, I observed that there is no space between the word 'Something' and the replaced text 'B'. Seems to be an issue.

Note: I am not able to reproduce this issue in Android OS. 

I have attached the Video file for reference. 

..no space

https://github.com/keymanapp/keyman/assets/19683143/4f44456c-0736-4c82-bb25-f7be7cab1897

### Expected behavior

There should be a space between two words after pressing any key to the selected (second) word. 

### Keyman apps

- [ ] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.295-beta

### Operating system

iOS 17.4, iOS 15.5

### Device

iPhone 13 Mobile

**Comment by darcywong00** [comment]
I think every platform has issues related to replacing selected text (#9073)

iOS gets handled in #10107

**Comment by jahorton** [comment]
To reword what I'm seeing with that video, the issue is that deletion of the selected text is _also_ deleting the space before the text that was selected.  _That_ is certainly not something I'd expect... and it's interesting that it's iOS only.  I'll add it to my list.

**Comment by jahorton** [comment]
I suspected as much based on this:

> Note: I am not able to reproduce this issue in Android OS.

But just to double-check my assumptions:  I am not able to reproduce this with the Web pred-text test page either.
