### ISSUE TITLE
chore(core): test actions_normalize with lone trailing surrogate char

### ISSUE THREAD

**Issue by srl295** [keymanapp/keyman#11112]
Split from https://github.com/keymanapp/keyman/pull/11101#discussion_r1542195241

What about when the app context starts with a trailing surrogate or other illegal char?

I think from earlier discussion we talked about just ignoring that char, not treating it as part of the app context. At least we should make sure the normalize code doesn't fail in this situation.

**Comment by srl295** [comment]
@rc-swag @mcdurdin 

I'm getting `KM_CORE_STATUS_INVALID_UTF` from core trying to test this. which is probably good.

I'm wondering if lower-level processing should just assert that any invalid (such as lone surrogates etc) aren't in the app context.. and just skip forward ignoring such text, so that it does not interact with the keyboard's context.

**Comment by mcdurdin** [comment]
I think keyboard processors should be able to expect valid inputs - no unpaired surrogates etc. This is the responsibility of Core to filter out. But actions_normalize is part of core, not part of keyboard processors.

**Comment by srl295** [comment]
> I think keyboard processors should be able to expect valid inputs - no unpaired surrogates etc. This is the responsibility of Core to filter out. But actions_normalize is part of core, not part of keyboard processors.

sorry, by 'lower level' I meant lower level in core, not lower than core.

**Comment by rc-swag** [comment]
If we are talking about an unpaired surrogate, the furthest from the caret. I agree the core should filter this out. It could be done right at the front door with `km_core_state_context_set_if_needed`.

**Comment by srl295** [comment]
at https://github.com/keymanapp/keyman/blob/5790f634cfd765321061b37d70a134489db3a509/core/src/km_core_state_context_set_if_needed.cpp#L61

increment the app_context if it's a trailing surrogate, and continue on. 

single increment, don't try to be clever!

**Comment by srl295** [comment]
test spot:

https://github.com/keymanapp/keyman/blob/edadeb5729920c4e07fabc10ea83c48db9baee72/core/tests/unit/ldml/test_context_normalization.cpp#L114

may need adjustement

**Comment by srl295** [comment]
fixed in #11169 !
