### ISSUE TITLE
bug(android): Stuck key-highlighting and Stuck-subkey menu problems occur while testing PR build 11032 on Android OS

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#11116]
### Describe the bug

I observed that there is an issue with stuck key-highlighting and the stuck subkey menu while testing PR build 11032 on an Android mobile device.

### Reproduce the bug

1. Install Keyman 17.0.292-beta-test-11032.
2. Download and Install Khmer Angkor and SIL (IPA) keyboards. 
3. Switch to the default EuroLatin (SIL) keyboard. 
4. Type two words. 
5. Select the Second word. 
6. Hold the Shift Key. 
7. Long press some other key. 
8. Press the Number key. 
9. Press the Symbol key. 
10. Repeat steps 6 to 9. 

Here, I observed that the keyboard malfunctions and displays an error message on the screen. 

I have attached a video file for reference. 

https://github.com/keymanapp/keyman/assets/19683143/4bfe7500-f62d-40cf-8e49-6d2b3b5ad7ce

### Expected behavior

The keyboard should not malfunction if the shift key is held down and another key is rapidly long-pressed.

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.292-beta-test-11032

### Operating system

Android 13

### Device

Samsung Galaxy AG23 mobile device

### Keyboard name

EuroLatin (SIL)

### Keyboard version

3.0.1

### Language name

English

**Comment by darcywong00** [comment]
Is this related to #10646 where key previews get stuck?

**Comment by jahorton** [comment]
Probably so.  That PR's held up awaiting user re-testing, so its changes aren't merged in yet.  The issue showing up here is thus likely due to that fact.

**Comment by darcywong00** [comment]
@bharanidharanj can you update to 17.0.301 beta or later and see if you can still get a repro?

**Comment by darcywong00** [comment]
Assigning to @bharanidharanj for retesting

**Comment by bharanidharanj** [comment]
> Assigning to @bharanidharanj for retesting

@darcywong00 Retested with the latest Keyman 17.0.315-beta build and I was not able to reproduce it. It seems to be fixed and working fine with the latest build. It would be better to close this issue.  Thanks.

**Comment by darcywong00** [comment]
Fixed by #10873
