### ISSUE TITLE
[Web] Suggestion: Make "Blank" buttons "Untouchable" like spacing.

### ISSUE THREAD

**Issue by MattGyverLee** [keymanapp/keyman#1111]
I have a few touch views with only a selection of keys available. Setting inactive keys to "Blank" gives a nice look showing that they are deactivated. Setting them to "Spacing" makes them disappear completely, but gives the advantage that they are not touch target landmines (if you touch in a strange place, it will find the nearest letter).

Is it possible for "Blank" (while maintaining the same look) not to respond to touches like "Spacing" keys? I feel that blank looks more organized, especially when transitioning from related layers.

Lost in spacing:
![image](https://user-images.githubusercontent.com/986339/44294895-9d0f6680-a26c-11e8-855b-8de8980a05c7.png)

Blank landmines collecting stray touches:
![image](https://user-images.githubusercontent.com/986339/44294906-cd570500-a26c-11e8-8703-43e81aea069e.png)

---
The Previous layer (for reference)
![image](https://user-images.githubusercontent.com/986339/44294939-83225380-a26d-11e8-83d1-845c7370449d.png)

~Matthew

**Comment by MattGyverLee** [comment]
I just tested on Android (v13), and currently neither Spacer nor Blank seem to collect or respond to touches (though they do show the popup pentagon in Chrome's mobile emulation). We can probably close this if it is fixed on iOS.

**Comment by mcdurdin** [comment]
> In Chrome emulation, they do still show the popup pentagon.

Do you mean what we call the 'key preview'?

![image](https://user-images.githubusercontent.com/4498365/75101668-893b8200-5612-11ea-9179-78bd235cdb7f.png)

That shouldn't be showing if it's a blank or spacer. @jahorton can you verify?

**Comment by MattGyverLee** [comment]
> Do you mean what we call the 'key preview'?
Yes...that's a much better name...
