### ISSUE TITLE
feat(android): Standardize long-press behavior: Remove base key from popup keys

### ISSUE THREAD

**Issue by LornaSIL** [keymanapp/keyman#1113]
I was asked if Android and iOS could match the longpress key behavior.
* In Android when you longpress you see all the possibilities (including the one on the keycap).
* In iOS when you longpress you only see the possibilities that are not on the keycap.

**Comment by darcywong00** [comment]
iirc on Android,
* longpress on phone includes the base key
* longpress on tablet does not include the base key

**Comment by darcywong00** [comment]
From the [community site](https://community.software.sil.org/t/longpress-dont-display-the-main-symbol-and-popup-size/3196), @bennylin also requests that Android not include the basekey in the popup.

In addition, if the popup only has one choice, display the longpress at the basekey, so the user's finger doesn't need to move:

> Whereas in other keyboards I saw the option of longpressing only show “?”, therefore when she longpress “.”, without having to move the finger, one second longpress and release would result to the intended symbol.

**Comment by mcdurdin** [comment]
Review #3092 when implementing this.

**Comment by mcdurdin** [comment]
Let's match iOS functionality and not show the base key in the popup.

**Comment by mcdurdin** [comment]
These additional features are out of scope:

> There are a bunch of potential improvements we can make to longpress, e.g. swipe up/down, customisation of availability of symbols, etc.

> In addition, if the popup only has one choice, display the longpress at the basekey, so the user's finger doesn't need to move:

**Comment by jahorton** [comment]
So... after a bit of discussion, we're going to remove all cases for prepending the base key.  Worth note:  this _does_ happen on smaller iOS devices at present; it's not an Android-only thing, as I see prepended characters on my iPhone SE (1, the older one).  So there _are_ 'native' Web changes to be made here as well.
