### ISSUE TITLE
bug(android): Caps layer displays two different ways

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/keyman#11135]
When switching to the caps layer you can end up with the shift button displaying the caps symbol either with a dark blue or a lighter blue background.

![Screenshot_2024-04-02-08-24-05-08_e307a3f9df9f380ebaf106e1dc980bb6](https://github.com/keymanapp/keyman/assets/181336/8d4d363f-1f92-41bd-baaa-12258fd85a61) ![Screenshot_2024-04-02-08-25-43-95_e307a3f9df9f380ebaf106e1dc980bb6](https://github.com/keymanapp/keyman/assets/181336/0462d91f-e4f5-4913-8a20-fbf1799b7db9)

Similarly, if you triple tap on the shift button you can end up with the Shift symbol with either dark or lighter blue background, depending on where you start: if you start with the Shift symbol displayed and triple tap you sometimes end up with the darker blue background for the shift layer instead of the solid blue. It's also possible to get the default layer shift to display with the darker blue background.

Keyman 17.0.299-beta
Android 12

**Comment by mcdurdin** [comment]
I think this may be the same as the 'stuck key' issue #11116 -- the darker blue highlighting is the touch-down colouring.

**Comment by darcywong00** [comment]
I think this is fixed in #10778 - I can't get a repro with 17.0.301 beta.

@ermshiperete - can you update and retry?

**Comment by ermshiperete** [comment]
ok, I installed 17.0.231. We'll see if it happens again sometime.

**Comment by mcdurdin** [comment]
> ok, I installed 17.0.231. We'll see if it happens again sometime.

Do you mean 17.0.301?

**Comment by mcdurdin** [comment]
Moving assignment to Eberhard for testing.

**Comment by ermshiperete** [comment]
> > ok, I installed 17.0.231. We'll see if it happens again sometime.
> 
> Do you mean 17.0.301?

Oops, yes.

That version seems to fix it. However, it seems that some of the taps get lost sometimes: If I double tap repeatedly it should alternate between Caps and Shift layer. Sometimes however I land in the default layer. But that's not directly related, so I'm closing this issue.

**Comment by ermshiperete** [comment]
Reported #11183 for the double tap issue.
