### ISSUE TITLE
[TOUCH] UX Suggestion: Make changing keyboards quicker by provide a drag-functionality on space bar

### ISSUE THREAD

**Issue by matsbla** [keymanapp/keyman#1115]
At my samsung phone there is a push and drag function to change between languages:
![screenshot from 2018-08-20 21-46-56](https://user-images.githubusercontent.com/4965568/44362936-e35e0300-a4c2-11e8-82e6-911c858dbfbb.png)

It makes it slightly quicker to change between keyboards/languages installed. Also if we could remove the dedicated language switcher button the keyboard would be slightly less crowded:
![screenshot from 2018-08-20 21-53-35](https://user-images.githubusercontent.com/4965568/44363174-ab0af480-a4c3-11e8-881a-b619e1d9af72.png)

**Comment by mcdurdin** [comment]
Some of these interactions are under review for Keyman 12 -- they probably won't make it into Keyman 11. Thank you for the suggestion!

**Comment by ermshiperete** [comment]
Duplicates #5511

**Comment by mcdurdin** [comment]
Closing in preference for #5511, please follow there.
