### ISSUE TITLE
[TOUCH] UX Suggestion: Make keyboards appear individually in appstore (e.g. Play Store) for easier findability & installation

### ISSUE THREAD

**Issue by matsbla** [keymanapp/keyman#1116]
Maybe it would be easier for people to find and install keyboard if they could simply install them by searching and install them directly from the appstores. As example people will be able to find keyboards by searching on language names even though they don't know that there exists anything named Keyman. Also installations could be simplified for user as they can install the keyboards like they are used to install an app. In addition it could become easier to promote individual keyboards, and we would be able to to see statistics about how many users have installed the different keyboards.

**Comment by mcdurdin** [comment]
Agreed. There is a significant technical barrier with the iOS App Store -- apps which come from the same publisher that have only minimal differences (e.g. a different keyboard) are rejected. However, this would be possible with the Android Play Store and is something we are considering.

**Comment by mcdurdin** [comment]
This is now possible with [Keyboard App Builder](https://software.sil.org/keyboardappbuilder/) for Android. I believe an iOS version is coming at some point.

For customised builds, this can be done with Keyman Engine for either platform.
