### ISSUE TITLE
bug(web): An error message occurs when attempting to enter special characters using the default On-Screen Keyboard

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#11165]
### Describe the bug

I noticed that an error message appears on the screen when attempting to enter special characters using the default OSK.

### Reproduce the bug

1. Install Keyman 17.0.301-beta.
2. Open Keyman In-app.
3. Press and drag a key straight downward direction then release the key to print the special characters. 
4. Repeat step 3 several times. 

I got a keyboard error message while repeating step 4. Seems to be an issue. 

https://github.com/keymanapp/keyman/assets/19683143/80b2b8f0-cd2f-4b6d-9964-27955bc33830

### Expected behavior

The keyboard should not display any error messages when adding special characters using the On-Screen Keyboard (OSK).

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.301-beta

### Operating system

Android 12, 13

### Device

Samsung Galaxy AG23 mobile device

### Keyboard name

EuroLatin (SIL)

### Keyboard version

3.0.1

### Language name

English

**Comment by darcywong00** [comment]
I think maybe this Sentry web issue?
https://keyman.sentry.io/issues/5140089969/events/257e8524dcfa4c71aec5fd525d22bcd1/
matching 17.0.301 beta and Samsung A23 device

**Comment by jahorton** [comment]
The first of two links immediately before this appears to correspond to touch-event cases on keymanweb.com, while the latter corresponds to mouse-event cases.  (I originally made this analysis when linking the sentry issues to... #11178, the PR fixing this.)
