### ISSUE TITLE
bug(android): Clicking the globe key rapidly displays an error message on the active keyboard

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#11181]
### Describe the bug

I observed that rapidly clicking the globe key triggers an error message on the active keyboard.

### Reproduce the bug

1. Install Keyman 17.0.302-beta
2. Open the Keyman In-app.
3. Install Khmer Angkor, Balochi_Phonetic keyboards. 
4. Switch to EuroLatin (SIL) keyboard. 
5. Click rapidly the globe key several times. 

Here, I noticed that an error message appears on the active keyboard. 

I have attached the video file for reference. 

https://github.com/keymanapp/keyman/assets/19683143/df3c1e9d-9176-4fcd-a303-3e673c95ee1c

### Expected behavior

The keyboard should not generate any errors when the globe key is rapidly clicked.

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.302-beta

### Operating system

Android 13

### Device

Samsung Galaxy AG23 mobile device

**Comment by jahorton** [comment]
There is a very high chance that this has the same underlying error as #11165, which is being fixed by #11178.

**Comment by darcywong00** [comment]
I've halted on test code where the crash happens (rapidly toggling between sil_euro_latin and khmer_angkor). Both are 4-row keyboards.

![image](https://github.com/keymanapp/keyman/assets/7358010/6dc21791-3a16-4e12-a240-f16641deff94)

rowIndex = 4 which is out of bounds of layer.rows[3]

**Comment by darcywong00** [comment]
Fixed by #11178
