### ISSUE TITLE
[iOS] Install fonts bundled with keyboards as system font 

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#1118]
From community site [discussion](https://community.software.sil.org/t/unable-to-load-font/1209/7)

Keyman for iPhone and iPad 2.0 used to prompt to download and [install](https://help.keyman.com/products/iphone-and-ipad/2.0/installing-fonts.php) fonts onto the device, but that doesn't seem to be happening in Keyman 10.

Per @mcdurdin 
> iPhone font installation is a little more complex than just loading a .ttf file onto the phone. We have to host a profile file, which has the extension .mobileconfig, and wraps around the .ttf file. This is generated with an Apple configuration tool, and must be hosted on a public website. We’ll need to generate and host that .mobileconfig verison for Pawhuska.ttf on our content delivery network, and update the keyboard metadata accordingly to point to that file, in order for this font delivery to work.

**Comment by jahorton** [comment]
A side note from Nov 5, 2018:

> See https://norbertlindenberg.com/2015/06/installing-fonts-on-ios/, section “Packaging fonts in configuration profiles.” The resulting configuration profiles would need to be hosted on r.keymanweb.com for consumption by iOS Keyman.
>
> It's not actually a regression - it's actually a lack of infrastructure that's the issue.

**Comment by jahorton** [comment]
See #3445 for a _very_ nice way forward.

**Comment by jahorton** [comment]
We'll just abandon .mobileconfigs and go with the way forward mentioned in #3445.  The latter won't make it for 14.0, but oh well.
