### ISSUE TITLE
bug(developer/ide): Mobile layout switches to using surrogate pairs

### ISSUE THREAD

**Issue by LornaSIL** [keymanapp/keyman#11193]
### Describe the bug

In Keyman Developer, sometimes the `keyman-touch-layout` uses the glyph for a character and sometimes it switches to this format `"\uD801\uDDB0"`. Technically, this still works, but it's not pretty to have a surrogate pair and it does mean that almost every 3rd or 4th line is changed when the keyboard is modified.

I've finally been able to reproduce it.

If I go to the code view:
![image](https://github.com/keymanapp/keyman/assets/7071907/d5e0bd44-3c9e-4b74-8e36-6ab39ad2553b)
(we can see there is a glyph there)
Then, with code view open, I go to **Keyboard/Fonts** and click **Ok**. I don't even have to make a change to the font. I then get this:
![image](https://github.com/keymanapp/keyman/assets/7071907/f4ba3d36-654f-4973-91a4-cfbdc2671e9d)

I'm using the Vithkuqi keyboard for this report. It has not yet been approved, but probably will be by the time someone sees this report.

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [X] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.293-beta

### Operating system

Windows 11

### Device

n/a

### Keyboard name

vithkuqi

### Keyboard version

1.0

**Comment by mcdurdin** [comment]
> I've finally been able to reproduce it.

Great work! I am going to try and fix this, I can see how it is happening and it is down to issues in the legacy IDE.
