### ISSUE TITLE
chore(common): remove "is:open" from suggested search query from Bug Report template at GitHub

### ISSUE THREAD

**Issue by alex-larkin** [keymanapp/keyman#11212]
### Is your feature request related to a problem? Please describe.

Hello, 

I suggest removing "is:open" from the suggested search query from Bug Report and Feature Request templates on GitHub. The reason is that -especially in the case of bug reports- the bug may have been reported, fixed, and closed, but the patch may not yet have hit production, where other users continue to encounter the bug. 

This is what happened here:

https://github.com/keymanapp/keyman/issues/11208

I looked for other bug reports before filing my own, but missed the related bug report that had already been closed. 

### Describe the solution you'd like

The GitHub Bug Report template would suggest searching: 

https://github.com/keymanapp/keyman/issues?q=is%3Aissue+label%3Abug

That would show related closed bug reports. 

### Describe alternatives you've considered

An alternative would be to leave the templates as they are, as seeing closed issues may add too much clutter, and this may be too much of an edge case. 

Thank you for your consideration. 

### Related issues

#11208

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [X] Other - give details at bottom of form

**Comment by mcdurdin** [comment]
Thanks for the suggestion. We'll consider as we do maintenance in 18.0 cycle coming soon.
