### ISSUE TITLE
bug(web): sticky backspace button in Keyman Android 17.0.307-beta

### ISSUE THREAD

**Issue by alex-larkin** [keymanapp/keyman#11223]
### Describe the bug

Sometimes after selecting text and deleting it, the <kbd>Backspace</kbd> button remains active, continuing to quickly delete whatever text was before the selection, one character at a time. This seems to happen when pressing  <kbd>Backspace</kbd> slightly longer than a tap, but not for too long. 

The active <kbd>Backspace</kbd> button can be deactivated by touching it again (but often not before it's too late). 

See video:

https://drive.google.com/file/d/1vtxc2-0JskRnKSBC3ibM1gnq6EHm4_bL/view?usp=sharing
(Especially from 0:27 to the end.)

This is my project folder, if needed:

https://drive.google.com/file/d/1jIJqt_a1e3Gn9WS6iePrsg07xjTHE-F2/view?usp=sharing

### Reproduce the bug

1. Open a keyboard run by Keyman Beta for Android 17.0.307
2. type out a string of characters
3. Select the last bit of the characters with a long tap
4. Tap <kbd>Backspace</kbd>. (Try a slightly longer tap. But not too long of a tap.)
5. Sometimes, the <kbd>Backspace</kbd> button will remain active, deleting the selection, and then the text before it, character by character.
6. This will continue until all the text is deleted or until tapping <kbd>Backspace</kbd> again, whichever happens first. 

I was able to reproduce this behavior about 3 out of 6 times. 

### Expected behavior

Tapping <kbd>Backspace</kbd> only triggers one deleting event. The key should not remain active. 

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.307

### Operating system

Android 12

### Device

Sansung Galaxy S21

### Target application

The notepad in the Keyman Beta app

### Keyboard name

teclado_quechua

### Keyboard version

0.9

### Language name

que

**Comment by jahorton** [comment]
I'm curious if this might be related to #11221 - as if the backspace key handling is terminating too early.  I'll add a test to #11245 for this, to explore the possibility.

**Comment by alex-larkin** [comment]
Thanks!

**Comment by jahorton** [comment]
Could you try again with the latest version and let us know if the behavior is fixed now?  Thanks.

**Comment by alex-larkin** [comment]
Thanks for your work. I just tested with keyman-17.0.311.apk beta. While I did not observe the same sticky behavior, I did observe that all keyboards exhibited intermittent non-funcionality for backspace key. Tapping the backspace key would make it flash blue, but nothing would be deleted. Especially when the cursor was at or towards the end of the text. 

No issues observed with the keyboard named Winchus in the recording, which is effectively the same as "Teclado Quechua" but running on the current version 16 production release. 

See this screen recording: 

https://drive.google.com/file/d/1-Dr00-JJgVP04iZfPbXxU6gGbvBZ8Jqm/view?usp=drivesdk

Thanks so much.

**Comment by jahorton** [comment]
> Thanks for your work. I just tested with keyman-17.0.311.apk beta. While I did not observe the same sticky behavior, I did observe that all keyboards exhibited intermittent non-funcionality for backspace key. Tapping the backspace key would make it flash blue, but nothing would be deleted. Especially when the cursor was at or towards the end of the text.
> 
> No issues observed with the keyboard named Winchus in the recording, which is effectively the same as "Teclado Quechua" but running on the current version 16 production release.
> 
> See this screen recording:
> 
> https://drive.google.com/file/d/1-Dr00-JJgVP04iZfPbXxU6gGbvBZ8Jqm/view?usp=drivesdk
> 
> Thanks so much.

About this:  we've recently noticed a bug with a non-functional backspace that might be related, though it's hard to tell if this is the same thing you're experiencing without full details about your document.  I do see that it's fairly large and does seem to have been copied and pasted from a source with links, so... there's a decent chance this may be relevant.  Does #11182 seem like it could apply to your scenario?  We're working on a fix for issue that already with #11206.

**Comment by jahorton** [comment]
Either way, if it's not too much to ask, a replica of your document at the start of the video would be helpful for attempting to reproduce this ourselves.  Even if it is a match for #11182, it'd still be useful for testing our pending fix.

**Comment by jahorton** [comment]
#11206 got merged yesterday, which is the fix I referred to with the prior comment.  Could you try again with the latest beta build and see if that fixes things?  Also, it'd help to have specific data to test with if you can reliably reproduce it yourself.

**Comment by jahorton** [comment]
We believe that this has been fixed at this point, and no further reports have come in.  We'll go ahead and close this issue - we can always link it in any new bug reports in the worst-case.

**Comment by alex-larkin** [comment]
Thanks so much! I'm sorry for not having responded. I was in the most of a move and then my wife got sick. (Doing better now!) Sounds good.
