### ISSUE TITLE
bug(web): "Installing Keyboard" message displayed at the bottom of the OSK when KeymanWeb is loading

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#11226]
### Describe the bug

The message "Installing Keyboard" is displayed at the bottom of the On-Screen Keyboard (OSK) when the test keyboard is accessed in a web browser.

### Reproduce the bug

1. Install Keyman Developer 17.0.308-beta.
2. Open gff_amharic project in Keyman developer.
3. Compile the Keyboard. 
4. Click the Build tab. 
5. Click the valid web link address to open the OSK in the local browser. 
I noticed that there is a message 'Installing Keyboard' on the browser. 
6. Select 'gff_amharic' keyboard. 
Still, that message appeared at the bottom of the OSK. 

Note: I was not able to reproduce it in Windows 10 build. 

..Installing Keyboard error1

   <img width="600" src="https://github.com/keymanapp/keyman/assets/19683143/5826d124-55e8-49ac-8edc-c496c8e4c077">

..Installing Keyboard error 2

   <img width="600" src="https://github.com/keymanapp/keyman/assets/19683143/ae06ea36-5893-4088-9c02-6b4b0f7ff0d8">

### Expected behavior

The "Installing Keyboard" message should not be shown under the On-Screen Keyboard (OSK).

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [X] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.308-beta

### Operating system

Windows 11 OS (VM)

**Comment by mcdurdin** [comment]
Seeing this same issue on keymanweb.com

![image](https://github.com/keymanapp/keyman/assets/4498365/51e93203-5625-47f9-94c7-e8567e9e9a3e)

**Comment by mcdurdin** [comment]
@jahorton FYI

**Comment by jahorton** [comment]
Note:  on keymanweb.com, it is most visible when...
1. Refreshing a page
2. And the page is not focused (with focus in the Developer view).

This has been confirmed to correspond to the following:

https://github.com/keymanapp/keyman/blob/b70c7c572471b8647614ab6125d2001045b38357/web/src/resources/osk/kmwosk.css#L672

When there is no active keyboard, this is the default.  Of course, if this is showing, this implies that the OSK shouldn't be visible... and yet it is.  That said, if the page is focused, apparently that's enough to trigger the OSK to automatically hide.
