### ISSUE TITLE
bug(developer): An LDML error occurs after compiling an LDML keyboard 

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#11228]
### Describe the bug

I noticed that an error appears on the console after compiling an LDML project.

### Reproduce the bug

1. Install Keyman Developer 17.0.308-beta.
2. Open Keyman Developer. 
3. Create an LDML keyboard project. 
4. Click the Keyboards tab.
5. Click the *.xml link. 
6. Press F7 to compile the Keyboard. 

Here, I noticed that there is an error message "Error Validating LDML XML file" displayed on the console:

```
error KM01001: Error validating LDML XML file: /keyboard3/info: additionalProperties: must NOT have additional properties additionalProperty="xmlns"
```

I have attached the Screenshot for reference. 

   <img width="600" src="https://github.com/keymanapp/keyman/assets/19683143/8ec7b613-6e24-438f-bc16-da2f673c86c2">

### Expected behavior

Pressing F7 should compile the keyboard without displaying any error messages.

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [X] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.308-beta

### Operating system

Windows 11 OS (VM)

**Comment by mcdurdin** [comment]
Issue is that a blank `xmlns` property is being added to `<info>` and `<version>` keys from the template build:

```
  <info xmlns="" author="marc" name="marcamr"/>
  <version xmlns="" number="1.0.0"/>
```
