### ISSUE TITLE
feat: Add Support for Boustrophedon Writing Direction

### ISSUE THREAD

**Issue by dyacob** [keymanapp/keyman#11231]
### Is your feature request related to a problem? Please describe.

The boustrophedon writing style is used by a number of ancient scripts, Musnad is an example of one where two KM keyboards have been created (Ancient Greek is another).  Though rare, it would be beneficial to academics to be able to produce boustrophedon documents if Keyman could also support the writing direction.

### Describe the solution you'd like

`boustrophedon` should be one of the supported writing directions. The keyboard will need to recognize a key command to change the writing direction.  For example `ENTER` could be the signal to change direction, or `CTRL-/`, etc. The keyboard code would then need to be able to detect which directional "mode" it was in (ltr, or rtl) so that it can emit different glyphs accordingly.

### Describe alternatives you've considered

Two separate keyboards, one for each typing direction.

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [X] Keyman for Linux
- [X] Keyman for macOS
- [X] Keyman for Windows
- [X] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16.0.X

### Operating system

Windows 11, macOS

### Device

Windows Laptop

### Target application

Microsoft Word, LibreOffice Writer

**Comment by mcdurdin** [comment]
How would this work with line wrapping?

**Comment by dyacob** [comment]
I think it wouldn't, that would be an acceptable sacrifice. Manual line breaks are assumed.  Fortunately, the samples I've seen (stone carved) don't have a lot of words per line, so in reproducing them the user would input the manual line break anyway and the end of the line on the page is rarely reached.

**Comment by mcdurdin** [comment]
Could this be implemented without changes to Keyman with the use of keyboard options?

**Comment by mcdurdin** [comment]
You could also look at context to determine the current writing direction:

```
any(ltrletter) + any(key) > context index(ltrout, 2)
any(rtlletter) + any(key) > context index(rtlout, 2)
```

There are deeper questions on directionality which Keyman cannot answer -- is the script in Unicode, do the characters have directionality properties? Keyman cannot directly manipulate an app's paragraph directionality, although it can insert RTL or LTR embeds which have a similar effect for many cases.

I'd prefer to see this implemented in a keyboard and taken as far as possible there before we invest energy in Keyman itself. Perhaps an experimental keyboard will highlight things which Keyman could do which a keyboard wouldn't be able to?

I will go ahead and close this as an issue on this repository -- I look forward to seeing something appear in the Keyboards repo :grin:
