### ISSUE TITLE
bug(developer): transform with rule with u{002B} results in the regex processing it as `+` rule

### ISSUE THREAD

**Issue by rc-swag** [keymanapp/keyman#11233]
The transform rule `<transform from="a\u{002B}" to="plus"/>` resulted in a match any time a <kbd>a</kbd> key pressed. Any <kbd>a</kbd> produced "plus".

I have attached a test keyboard with the transform rule commented out. 
[contextreset.zip](https://github.com/keymanapp/keyman/files/15005442/contextreset.zip)

Keyman Developer Version: 17.0.308-beta

**Comment by srl295** [comment]
That's not right - thanks
