### ISSUE TITLE
bug(web): Philippines SIL keyboard not compatible with Firefox

### ISSUE THREAD

**Issue by LornaSIL** [keymanapp/keyman#1125]
There is an issue with FF (problem is on FireFox in Windows and also Linux, not tested on OSX) is demonstrated with this keyboard:
[Philippines SIL](https://keymanweb.com/?_ga=2.178222438.2116510910.1534870017-227799419.1521670190#tl,Keyboard_sil_philippines)

This keyboard has various deadkeys which all seem to work except for problems with the underscore deadkey:

In FireFox, if you use your keyboard and type "_c" you get ```_c```. If you use the osk and your mouse and select ```_``` + `c` you get `ç` (as intended). In Chrome, you always get the cedilla whichever way you type it. Other keystrokes to try would be ```_o```, ```_a```, ```_w``` and ```_1```. Also, ```&:``` is supposed to output ```÷``` and it only works if you use the osk with mouse selection of those keys in Firefox. Again they work fine in Chrome.

Help file with keystrokes is here: https://help.keyman.com/keyboard/sil_philippines

**Comment by LornaSIL** [comment]
Possibly relates to https://github.com/keymanapp/keyman/issues/1107

**Comment by mcdurdin** [comment]
I didn't realise this was KeymanWeb until I checked the link ... sorry. I have recategorised this and we'll look at it as unrelated to the TSF issues.

**Comment by jahorton** [comment]
Confirmed for OS X as well.
