### ISSUE TITLE
[Windows] Versioning should be automatic across all code

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#1126]
Currently, version 10.0 is hardcoded in a number of areas. Update this issue when new areas are found.

As far as possible, these should be sourced from the build script, perhaps via environment variable set during build.

- [x] .wxs WiX install files
- [x] Splash screens
- [x] registry settings

**Comment by darcywong00** [comment]
- [ ] .xsl help files

**Comment by mcdurdin** [comment]
.wxs, splash screens and registry settings are all now version agnostic.
