### ISSUE TITLE
bug(android): keyboard font size is affected by system font setting

### ISSUE THREAD

**Issue by Nnyny** [keymanapp/keyman#11279]
### Describe the bug

From the community site: https://community.software.sil.org/t/android-font-size-inside-of-keyboard/8689/2

> The size of the letters on the Keyman keys is affected by the system-wide Android font settings.
> 
> Other keyboards (Gboard, AOSP) don’t seem to scale the letters like this. Is this a problem with Keyman, or is there something that I (the keyboard developer for this specific language) can do to make sure this doesn’t happen on end users phone.
> 
> [By the way, I had to restart the phone after changing font settings.]

> What I would expect to happen would be for:
> 
> * Keyman to ignore the system-wide font settings, and just use the font size that I (the keyboard developer) chose to best fit the keyboard, or (maybe) for
> * Keyman to accept the system-wide font, but then automatically try to adjust the height to fit it (still allowing for that choice to be manually overridden later if desired).

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16.0.147

### Device

OnePlus 6t (a6013)

**Comment by jahorton** [comment]
Interestingly, this does _not_ appear to affect Keyman Engine for Web when _not_ embedded in the WebView.  Testing with Chrome 106, there is no visible scaling of OSK fonts.  This only appears to be an issue within the app's WebView.
