### ISSUE TITLE
bug(android): inverting text selection causes a crash

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#11344]
https://github.com/keymanapp/keyman/assets/4498365/bface0fd-d14a-4b7a-b067-6ce074bc11cd

17.0.313-beta

https://keyman.sentry.io/share/issue/e7282fd7272c47f0bff964725f48ec7f/

from #11128

**Comment by mcdurdin** [comment]
Possibly related:
* https://keyman.sentry.io/share/issue/7980e86e395b4c5cbd03ba03c98cfc0d/
* https://keyman.sentry.io/share/issue/a08bf2d9be184cc9b6de5d0ae31b5924/

**Comment by jahorton** [comment]
I just triggered an instance matching the Sentry event from the description (automatically, no merge needed).

**Comment by jahorton** [comment]
Wait a second... yeah, something's off with that code.  I'll throw something together real quick for it.  `selMin` and `selMax` are defined, but go unused?
