### ISSUE TITLE
chore(common): Document minimum emscripten version - Win, mac

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#11369]
3.1.44 or 3.1.46, but not 3.1.45...

**Comment by jahorton** [comment]
Note existing references in places like docs/build/windows.md: https://github.com/keymanapp/keyman/blob/adb27b3c564d2ce1e1a4b39a3d5568e98739884a/docs/build/windows.md?plain=1#L184

Contrast the value there with what we mentioned in a recent discussion in other channels:  [Our recent team discussion Google Doc re: dependencies and toolchain updates](https://docs.google.com/document/d/1Uy3U2YXeA4rCEbUbT7O6QzUGJDZBeViFecL8fjUOLkE/edit?usp=sharing)
