### ISSUE TITLE
chore(common): make minimum-versions.md

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#11372]
minimum-versions.md (include a link to any app-help section that’d need updating to match)

Ref to #11371.

**Comment by darcywong00** [comment]
Summarizing @mcdurdin and @ermshiperete suggestions from #11386

> I think longer term, what we could do is this:
>
>Generate min-ver.md from min-ver.inc.sh, with a script in /resources/somewhere.
In our common test build, we generate a new copy of min-ver.md and compare it to the version in-repo, and then fail the test build if they are not identical.
This would avoid us unintentionally getting the two files out of sync, allow us to track the version data easily, and avoid the complications of automatic commit etc.

@ermshiperete suggested in Slack:
>
>Another idea: we could make min-ver.md a template file min-ver.md.in or so. In the CI build we replace the variables in the .in file with the values from min-ver.inc.sh and commit/push the result.

@mcdurdin continues
>This sounds like a great idea, only challenge is making sure we pick up all the env vars in the .inc.sh so that the .md doesn't miss any. Thought: include a table at the bottom of the .md that lists all the env vars as parsed out from the file (or you could do a funky diff of before/after env, which I am doing for Windows build.sh right now so we could copy that).
