### ISSUE TITLE
chore(android): Android - checking Gradle requirements

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#11370]
Android - checking Gradle [requirements](https://developer.android.com/build/releases/gradle-plugin#compatibility)

**Comment by darcywong00** [comment]
Gradle version is tied to the [Java version](https://docs.gradle.org/current/userguide/compatibility.html#java)

Currently Java 11 goes up to Gradle 5.0

Gradle support timeline says current version 8 gets updates.
https://endoflife.date/gradle

**Comment by darcywong00** [comment]
For 18.0 we'll just do a minimal bump to Gradle.
See #11425 before updating Gradle to 8.x+
