### ISSUE TITLE
chore(core): linker warnings for keyman core when building Keyman for Mac

### ISSUE THREAD

**Issue by sgschantz** [keymanapp/keyman#11423]
### Describe the bug

Seeing dozens of these linker warnings while building Keyman for Mac:

`Object file (/Users/sgschantz/projects/keyman/core/build/mac/debug/libkeymancore.a[x86_64][26](kmx_kmx_actions.cpp.o)) was built for newer 'macOS' version (12.0) than being linked (10.13)`

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [X] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.322-beta

### Operating system

macOS 14.4.1 Sonoma

**Comment by srl295** [comment]
@sgschantz are you still seeing this?

**Comment by sgschantz** [comment]
> @sgschantz are you still seeing this?

I just built with master and saw no linker warnings. What did you change?

**Comment by srl295** [comment]
> > @sgschantz are you still seeing this?
> 
> I just built with master and saw no linker warnings. What did you change?

I didn't change anything… it does sound like out of date files. Let's close this and reopen if it comes back.

**Comment by sgschantz** [comment]
Sorry, not sure why I didn't see the warnings locally, but  I do see these on ci builds. Check the log [here](https://build.palaso.org/buildConfiguration/KeymanMac_Master/486693?buildTab=log&logView=flowAware&focusLine=0) for the latest build of 18.

There are many statements like this:
`[18:07:04] :	 [Step 5/7] ld: warning: object file (/Users/marc_durdin/buildAgent/work/fae170dc1caceadf/keyman/core/build/mac-x86_64/release/subprojects/icu/source/common/libsicuuc.a[2](stubdata.cpp.o)) was built for newer 'macOS' version (14.0) than being linked (10.13)`

**Comment by sgschantz** [comment]
@srl -- I just realized that the warnings switched from 12.0 to 14.0. Is there some way to control what version of macOS core is being built for?

Our minimum version is 10.13, and it looks like a similar issue (#9060) may be causing crashes on startup with Big Sur (11) and Catalina (10.15). I don't see any evidence that it is related to this issue, but it is interesting that it is only happening on OS versions less than 12.

**Comment by srl295** [comment]
I'm finding this also https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_DEPLOYMENT_TARGET.html

we don't set this explicitly, but:

```shell
$ strings ./core/build/mac-x86_64/release/meson-private/build.dat | fgrep MACOSX_DEPL
'--prefix=/usr/local/opt/python@3.12' '--enable-ipv6' '--datarootdir=/usr/local/opt/python@3.12/share' '--datadir=/usr/local/opt/python@3.12/share' '--without-ensurepip' '--enable-loadable-sqlite-extensions' '--with-openssl=/usr/local/opt/openssl@3' '--enable-optimizations' '--with-system-expat' '--with-system-libmpdec' '--with-readline=editline' '--with-lto' '--enable-framework=/usr/local/opt/python@3.12/Frameworks' '--with-dtrace' '--with-dbmliborder=ndbm' 'MACOSX_DEPLOYMENT_TARGET=14' 'CFLAGS=-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk' 'CFLAGS_NODIST=-I/usr/local/include' 'LDFLAGS=-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk' 'LDFLAGS_NODIST=-L/usr/local/lib -Wl,-rpath,/usr/local/lib' 'CPPFLAGS=-I/usr/local/include' 'py_cv_module__tkinter=disabled' 'PKG_CONFIG_PATH=/usr/local/opt/mpdecimal/lib/pkgconfig:/usr/local/opt/openssl@3/lib/pkgconfig:/usr/local/opt/readline/lib/pkgconfig:/usr/local/opt/sqlite/lib/pkgconfig:/usr/local/opt/xz/lib/pkgconfig' 'PKG_CONFIG_LIBDIR=/usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/14' 'CC=clang'
```

(I'm on Sonoma 14.5)

so it shows `MACOSX_DEPLOYMENT_TARGET=14` 

What we might need to do is to set this version in cmake and keep it in sync with xcode…

**Comment by srl295** [comment]
OK i was looking at the wrong build log, i see the messages now on https://build.palaso.org/buildConfiguration/KeymanMac_Master/488041?buildTab=log&focusLine=2309&logView=flowAware&expandAll=true
