### ISSUE TITLE
chore(mac): apply standard indentation of two spaces throughout Keyman for Mac source

### ISSUE THREAD

**Issue by sgschantz** [keymanapp/keyman#11427]
### Describe the bug

Throughout the Keyman for Mac source code, change all line beginnings to indent two spaces. (Most are currently four spaces.)

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [X] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

**Comment by darcywong00** [comment]
Some of the other platforms use a .editorconfig file for IDE's to standardize spacing and indents. (You can find the .editorconfig files in this repo)

Would this Xcode plugin help?

https://github.com/MarcoSero/EditorConfig-Xcode
