### ISSUE TITLE
[Mac] KERN_INVALID_ADDRESS calling [client selectedRange] at KMInputMethodEventHandler.m:209

### ISSUE THREAD

**Issue by tombogle** [keymanapp/keyman#1143]
From Crashlytics. This crash happened once to 1 user ten days ago. Most likely some kind of memory corruption, but not much else to go on:

Version: Keyman 10.0 for macOS (10.0.111)
Bundle Identifier: keyman.inputmethod.Keyman
Issue #: 19
Issue ID: 5b784f476007d59fcd28aed2
Session ID: b2fdcbd6e27344e382cae9d0844eb302_DNE_0_v2
Date: 2018-08-18T16:54:00Z
OS Version: 10.10.5 (14F2511)
Device: MacBook Pro Retina, 15", Mid 2015
RAM Free: 66%
Disk Free: 18.3%
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x00006008412cbec0
0 libobjc.A.dylib 0x7fff8a2790dd objc_msgSend + 29
1 Keyman 0x1049dd554 -[KMInputMethodEventHandler getSelectionRangefromClient:] (KMInputMethodEventHandler.m:209)
2 Keyman 0x1049df7a2 -[KMInputMethodEventHandler handleEvent:client:] (KMInputMethodEventHandler.m:614)
3 Keyman 0x1049e971f -[KMInputController handleEvent:client:] (KMInputController.m:53)
4 InputMethodKit 0x104b2fa98 -[IMKServer handleEvent_Common:characterIndex:edge:clientWrapper:controller:] + 3397
5 InputMethodKit 0x104b24859 __63-[IMKServer handleEvent:characterIndex:edge:asyncClient:reply:]_block_invoke + 765
6 CoreFoundation 0x7fff96a1370c CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK + 12
7 CoreFoundation 0x7fff96a05815 __CFRunLoopDoBlocks + 341
8 CoreFoundation 0x7fff96a05356 __CFRunLoopRun + 1814
9 CoreFoundation 0x7fff96a049f8 CFRunLoopRunSpecific + 296
10 HIToolbox 0x7fff9190556f RunCurrentEventLoopInMode + 235
11 HIToolbox 0x7fff919052ea ReceiveNextEventCommon + 431
12 HIToolbox 0x7fff9190512b _BlockUntilNextEventMatchingListInModeWithFilter + 71
13 AppKit 0x7fff9582a8ab _DPSNextEvent + 978
14 AppKit 0x7fff95829e58 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 346
15 AppKit 0x7fff9581faf3 -[NSApplication run] + 594
16 Keyman 0x1049da998 main (main.m:21)
17 Keyman 0x1049d4834 start + 52

**Comment by tombogle** [comment]
Looked into this some. Seemed vaguely similar to [this issue](https://github.com/rime/squirrel/issues/224) in Squirrel (though likely for a whole different reason), but Marc and I couldn't see any obvious way to know what happened or how to detect the problem. We decided to let it be unless/until we get more users reporting the problem.

**Comment by SabineSIL** [comment]
We decided to close this issue since it is not affecting many people
