### ISSUE TITLE
bug(android): can't install .kmp file  

### ISSUE THREAD

**Issue by Nnyny** [keymanapp/keyman#11430]
### Describe the bug

This issue is similar to https://github.com/keymanapp/keyman/issues/10659 but on Android 11. It got fixed when I used 17.0.319 beta but now it reappear again on 17.0.322 beta. 

![photo_6199675375429204137_y](https://github.com/keymanapp/keyman/assets/123520338/81233eda-ef0a-495b-9e66-f75f8ff031db)

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.322 beta

### Device

Android 11

**Comment by darcywong00** [comment]
@Nnyny - Can you see if the following steps grant permission to Keyman on your Android 11 device?

https://help.keyman.com/products/android/17.0/troubleshooting/grant-storage-permission

Do the section for Android 11 - 12L devices.

**Comment by Nnyny** [comment]
Yes it works now. Thanks @darcywong00
