### ISSUE TITLE
feat(windows): add option to use right side modifiers in hotkeys

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#11471]
### Is your feature request related to a problem? Please describe.

By default, Keyman only responds to left-side modifiers for hotkeys, so that the right-side modifiers can be used for keyboards. Some users don't need to maintain that distinction and want to be able to use right-side modifiers as keyboard switch hotkeys.

### Describe the solution you'd like

An option in Keyman Configuration to use both Left and Right modifiers for hotkeys.

### Related issues

https://community.software.sil.org/t/keyman-shortcuts-do-not-work-with-function-keys-on-the-right-side/8530/5

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [X] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.325

### Operating system

Windows

**Comment by rc-swag** [comment]
@mcdurdin 
Looking into this the place where to manage the hotkey code and seeing some two legacy feature flags I am wondering while adding it another flag if one or both are still needed. 
The two flags are 
old_hotkey_registration = UseRegisterHotkey 
old_hotkey_modifier_state = UseCachedHotkeyModifierState

I am not sure of the history of the CachedHotkeyModiferState and why the UseRegisterHotkey can only be used if it is set. 
Anyway I turned both flags on and the hotkeys behaved as this issue requests. It would be easy to add another feature flag for this, however as stated above checking about the status of the current flags.



https://github.com/keymanapp/keyman/blob/69a3fa1795a457e49608e9f80561318d6dc556b7/windows/src/engine/keyman32/k32_lowlevelkeyboardhook.cpp#L174C2-L226C4

**Comment by mcdurdin** [comment]
Those two flags should be removed -- they were there until we were confident that the new 'experimental' way (no longer experimental) of watching for hotkeys was stable.

I don't have usage data (of course), but I don't think they'd be widely used as we haven't talked about them.
