### ISSUE TITLE
bug(windows): OSK issues (blue bar and no way to reposition)

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#11487]
Report from a user via email:

> I am writing to let you know of a change that has happened with Keyman and the on screen keyboard.  There is now a blue strip at the top that covers up much of the top row of the keys unless the keyboard is expanded to be quite large on the screen.  I downloaded the new update that came today, but the blue strip is still there..
> 
>The blue strip is always there with all all the languages I use (Khmu, Lao Thai, English)
>
>Previous so this I was having the issue that when I opened Keyman and started the on-screen keyboard there was no way for me to reposition it on my screen.  In the past I could ''grab" it near the top edge of the keyboard and move it around on my screen so that it wouldn't be in the way.  More recently all I could do was drag the corner to make the keyboard larger or smaller but not move it around which was problematic. Now a couple days ago the blue strip appeared...so I can move it around my screen by grabbing the blue strip, but the strip covers up the top row of keys.

<img width="519" alt="blue strip OSK" src="https://github.com/keymanapp/keyman/assets/7358010/c2e697ea-a1ce-4fde-a04d-9546dff648a5">

## Configuration
Keyman for Windows 16.0.147

Operating System: Windows 11 Home Single Language
Version 23H2
OS build 22631.3593
Experience Windows Feature Experience Pack 1000.22700.1003.0

**Comment by mcdurdin** [comment]
I wonder if right-clicking on the OSK and toggling the 'Show Toolbar' option will help? (Perhaps doing that twice?)

![image](https://github.com/keymanapp/keyman/assets/4498365/f6af8519-ba69-4944-ac51-7de980ef7cb8)

**Comment by darcywong00** [comment]
Great suggestion @mcdurdin !

> Wow, I just double-clicked as Marc suggested and that solved the problem.  See screen shot below! 
<img width="438" alt="Onscreen keyboard restored" src="https://github.com/keymanapp/keyman/assets/7358010/f5a39073-b96c-468b-8905-64f29766a7f6">


I'll leave the issue open in case investigation can figure out how it got to this state...

**Comment by mcdurdin** [comment]
> I'll leave the issue open in case investigation can figure out how it got to this state...

I wonder if we should close this, and reopen if it is re-reported? We have a workaround, and it's a low frequency event at this point.

**Comment by darcywong00** [comment]
Closed as having a workaround
