### ISSUE TITLE
bug(android): host-page show-banner does not null-guard against uninitialized OSK

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#11507]
Pretty much the title.  I noticed this while attempting to reproduce something else; I got the following error via local simulation:

```
KMW JS Log: Line 72, file:///data/user/0/com.tavultesoft.kmapro.debug/app_data/android-host.js:Uncaught TypeError: Cannot read property 'bannerController' of undefined
```

It arose from here:

https://github.com/keymanapp/keyman/blob/53b583e009f37803f84d3aace38cd9813dafaed5/android/KMEA/app/src/main/assets/android-host.js#L72

Should the method be called before the Web engine initializes, it will fail.

**Comment by mcdurdin** [comment]
Which version of Keyman?

**Comment by jahorton** [comment]
The literal current `master` / 17.0.325 for stable.
