### ISSUE TITLE
bug(android): Shift layer key enabled in the empty space.

### ISSUE THREAD

**Issue by dinakaranr** [keymanapp/keyman#11518]
### Describe the bug

Observed the behavior about the shift layer key being enabled when clicking at the beginning of the sentence.

### Reproduce the bug

Steps to reproduce:

1. Installed the "Keyman 18.0.42.apk" file and gave all permissions to the application.
2. Checked the "Enable Keyman as system-wide keyboard" and set the keyboard as the default keyboard box on the settings page.
3. Open the Keyman text editor.
4. Enter two sentences and start with a capital letter.
5. Move the cursor to the beginning of the sentence. Here, observed that the keyboard shows the "Shift layer" key enabled state. 
6. Click at the end of the sentence.
Here, observed that the keyboard shows the "Shift layer" key in the enabled state. The "Shift layer" key needs to show in a disabled state.
Please refer to the video file.
https://github.com/keymanapp/keyman/assets/19683059/155b37bf-584a-4ced-a704-7d6abff43026

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

Keyman 18.0.42-alpha-test-11510

### Device

Andorid 14 physical device

### Keyboard name

english_eurolatin_sil

### Language name

English

**Comment by mcdurdin** [comment]
Appears to be a divergence between newContext and postKeystroke state for sil_euro_latin?

**Comment by darcywong00** [comment]
@dinakaranr - I'm not able to get a repro on the current [18.0.103 alpha](https://downloads.keyman.com/android/alpha/18.0.103/).

Can you retest on the current alpha build and see if it's still an issue?

**Comment by dinakaranr** [comment]
I tested this issue with the attached "Keyman 18.0.103-alpha" build on an Android 14 physical device. I am sharing my observation.
I could not reproduce this issue in Android 14(physical device). It works well. "Shift layer" is not enabled at the end of the sentence. shift layer enabled when starting to type a word after the dot. It works well. Thanks.

**Comment by darcywong00** [comment]
Closing this issue as it seems to be resolved.
