### ISSUE TITLE
question(windows): Does Keyman work on Win11?

### ISSUE THREAD

**Issue by kovacshviktor** [keymanapp/keyman#11516]
### Describe the bug

Today my Win10 dropped up informations about Win11.
It said - in Hungarian language "jóhírnevű programok telepítése"
It means : "Installing reputable programmes." 
Keyman will be "reputable program"? Or somebody tested it?

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

**Comment by mcdurdin** [comment]
> Keyman will be "reputable program"? Or somebody tested it?

Yes, Keyman runs just fine on Windows 11 and we test it regularly on both Windows 10 and Windows 11. I am not quite sure what they mean by 'reputable program' -- but here's what we have to say about it: https://help.keyman.com/products/windows/current-version/common/adware
