### ISSUE TITLE
refactor(web): hoist `KeyboardObject` type to common/web/types

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#11612]
So far as I can tell, yes.  I always _did_ want to write up a formal type for it, and this push gave the perfect excuse.

I'd be happy for the type to be hoisted to `common/web/types`; be my guest!

_Originally posted by @jahorton in https://github.com/keymanapp/keyman/pull/11424#discussion_r1619754605_

Currently, there is no formal definition for a KeymanWeb `Keyboard` object as emitted by the KeymanWeb compiler. This is a good starting point, so we should take this, move it to common/web/types, and add some documentation.

**Comment by mcdurdin** [comment]
Also from #11424:

> I reckon we should put `VKDictionary` and `_kmw` into a subclass, as they are internal to Keyman Engine for Web. But that can wait until we move to common/web/types.

**Comment by mcdurdin** [comment]
@ermshiperete I think this belongs in your bucket, is that okay with you?

**Comment by ermshiperete** [comment]
Hmm, this is not as straight forward as it looks. `KeyboardObject` uses `KeyEvent` in some parameters. `KeyEvent` implements `KeyEventSpec` which has a `srcKeyboard` field of type `Keyboard` which has a `scriptObject` field of type `KeyboardObject`.
