### ISSUE TITLE
[iOS] Adopt multi-tasking enhancements

### ISSUE THREAD

**Issue by tombogle** [keymanapp/keyman#1162]
Keyman currently works only as a "full screen" app. It should be able to work as a slide-over or split screen app.
https://developer.apple.com/library/archive/documentation/WindowsViews/Conceptual/AdoptingMultitaskingOniPad/

**Comment by tombogle** [comment]
Note that to do this, one thing we'll need to do is support "Upside down" orientation. Not sure why we don't support that already, but maybe there are technical reasons. On the surface, it seems like an unnecessary limitation.

**Comment by mcdurdin** [comment]
Closing as not important
