### ISSUE TITLE
mac version: Shift/Caps state

### ISSUE THREAD

**Issue by chandrab699** [keymanapp/keyman#1165]
Keyman mac version: build 10.0.111

mac OS Mojave 10.14 Beta (18A384a)

Shift state and caps lock state is not recognized at all.

**Comment by tombogle** [comment]
What Keyman keyboard are you using? Also, are you typing the on-screen keyboard, a built-in laptop keyboard, or an external keyboard? I know that the caps-lock key on the on-screen keyboard is non-functional. Otherwise, the Shift and Caps Lock keys work fine for me.

**Comment by chandrab699** [comment]
What Keyman keyboard are you using?
It is a Custom keyboard. Shift and Caps-lock keys were functioning fine before.
Also, are you typing the on-screen keyboard, a built-in laptop keyboard, or an external keyboard?
built-in laptop keyboard
I know that the caps-lock key on the on-screen keyboard is non-functional. Otherwise, the Shift and Caps Lock keys work fine for me.

**Comment by chandrab699** [comment]
I uninstalled the keyboard layout and reinstalled it.
Rebooted the system. It is working fine now.
