### ISSUE TITLE
[iOS] UIKit: -[UIEventFetcher threadMain] crash - no Keyman code on stack

### ISSUE THREAD

**Issue by tombogle** [keymanapp/keyman#1170]
![image](https://user-images.githubusercontent.com/4229598/45325215-4e2cb800-b51e-11e8-8067-81afe344e8bc.png)

**Comment by jahorton** [comment]
More `EXC_CRASH (SIGQUIT)` goodness.  Almost certainly related to #1169 - things have progressed fairly far in the initialization process, but in each of the related logs there are pthreads waits involved.  In most of them, those waits are clearly in regard to WebKit.

General interpretation:  during the initialization/load of KeymanWeb's container WKWebView, the SWKeyboard (keyboard extension) times out and is shut down by the system.

**Comment by jahorton** [comment]
Closing in favor of #1492; we've done what we can for 11.0, as further changes will require significant restructuring of the app.
