### ISSUE TITLE
[iOS] Undefined crash with no stack: SWKeyboard: NO_CRASH_STACK + 0

### ISSUE THREAD

**Issue by tombogle** [keymanapp/keyman#1172]
SWKeyboard 10.0.210 (10.0.210)
Thread 0
18 crashes in the last two weeks on phones and tablets running iOS 11.0.3-11.4.1

**Comment by tombogle** [comment]
This [page](https://lonelycoding.com/xcode-crash-log-no_crash_stack-0/) claims it could be caused by a call to exit(), but there's no such call in Keyman code.

**Comment by jahorton** [comment]
This may be an alternate form of #1169 - it's got the same `EXC_CRASH (SIGQUIT)` signal.  Many of the crash reports mention `dyld` - this is the macOS/iOS dynamic library linker.  These crashes are happening as part of the app extension load process.

I'm not clear on whether this means things progressed less or further.

**Comment by jahorton** [comment]
Closing in favor of #1492; we've done what we can for 11.0, as further changes will require significant restructuring of the app.
