### ISSUE TITLE
chore(web): remove all references to ts-node

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#11736]
* from #11723

**Comment by jahorton** [comment]
In our team meeting today, we recognized that it's still used for some gesture-recognizer tests, so we should precompile those instead.  It's a similar change to what was made with #11723.

Note that web's build.sh has a generalized build action which triggers the tests, in addition to the child-package specific test-file biulds.

**Comment by jahorton** [comment]
Another reference:

https://github.com/keymanapp/keyman/blob/6bda8556144fdf9f688d6f752a06ca9e79c89b52/developer/src/kmc-model/tools/create-override-script-regexp.ts#L1

And another:

https://github.com/keymanapp/keyman/blob/6bda8556144fdf9f688d6f752a06ca9e79c89b52/developer/src/server/package.json#L39-L42

Fortunately, the unit-tests currently specified for the latter do not appear to leverage TS in any meaningful way... so we can probably just delete that package.json entry.

In fact...

https://github.com/keymanapp/keyman/blob/6bda8556144fdf9f688d6f752a06ca9e79c89b52/developer/src/server/build.sh#L130-L135

They're already built - so why was `ts-node` referenced there in the first place?
