### ISSUE TITLE
feat(developer): Windows Installer is no longer available to use in Keyman Developer 17.0

### ISSUE THREAD

**Issue by Meng-Heng** [keymanapp/keyman#11748]
### Is your feature request related to a problem? Please describe.

Original post: https://community.software.sil.org/t/windows-installer-gone-in-kmd17/8815
> Greetings All,
> 
> 
> I’ve just started using KMD17 and found that the “Windows Installer” section of the KPS editor is no more. Is there a new approach to follow for creating installers?
> 
> Apologies if I’m overlooking available information on the topic. A note on the change would be helpful to add to the " What’s new in Keyman Developer 17.0" web page.
> 
> thanks!

I couldn't find anything related to the missing Windows Installer on the recent version of Keyman Developer; perhaps we should create one; whether or not this feature has changed, been deprecated, or has not been included yet. I will need help to get this started if we want to document it somewhere.

Please let me know. Thank you!

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [X] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.326

**Comment by darcywong00** [comment]
> Apologies if I’m overlooking available information on the topic. A note on the change would be helpful to add to the " What’s new in Keyman Developer 17.0" web page.

Maybe this issue will be used for documenting the new package installer process as detailed in #9607.
I think a more permanent location on help.keyman than whatsnew.md (like kmcomp-migration)
