### ISSUE TITLE
bug(mac): Keyman stopped unexpectedly while using Word

### ISSUE THREAD

**Issue by dyacob** [keymanapp/keyman#11774]
### Describe the bug

Using Keyman on MacOS 14.5 Keyman stopped working while in MS Word 16.84. I can change keyboards, and go into Keyman Configuration, etc and it seems fine, but with any keyboard selected the output is always the Latin keystrokes.

Going to Chrome to start this bug report, Keyman is working again in the web form, switching back to Word, the Keyman keyboards are OK again.

I do have "Use verbose Console logging" checked throughout and can attach the log file to this ticket, please let me know the location of the file and I will do so.

### Reproduce the bug

1. Open MS Word
2. Select a Keyman keyboard.
3. Type...
4. Eventually close laptop (sleep, not shutdown), reopen the next day.
5. Continue, with Keyman select output will be in Latin

### Expected behavior

Text output will be as per the selected keyboard.

### Related issues

Maybe/Maybe not related. I have noticed an issue where Keyman output does not work within a table cell in Word for Mac.  It is fine in Word for Windows.

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [X] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.325

### Operating system

macOS 14.5

### Target application

MS Word 16.84

### Keyboard name

Any

### Keyboard version

Any

### Language name

Any

**Comment by mcdurdin** [comment]
I think the verbose logging is only visible when opening the macOS Console, which has to be running at the time that the issue occurs. So we might be out of luck this time.

Is this issue reproducible?

**Comment by mcdurdin** [comment]
> Going to Chrome to start this bug report, Keyman is working again in the web form, switching back to Word, the Keyman keyboards are OK again.

So if I understand correctly, switching between Word and Chrome and back again 'reset' Keyman so that it started working again?

**Comment by mcdurdin** [comment]
> Is this issue reproducible?

I will go ahead and close this -- if you can reproduce the issue, please reopen and we will investigate. But if it's only happened once, then it's not something we can action.
