### ISSUE TITLE
[Android] 102nd (oE2) Key not responding properly in KMEA

### ISSUE THREAD

**Issue by erros84** [keymanapp/keyman#1179]
K_oE2 on the French keyboard contains '<' and '>' and my keyboard uses it. I'm noticing that even though KMWeb correctly handles the K_oE2 key (and it exists in the .js file), Android hardware treats it as a duplicate of the K_BKSLASH key and outputs the result of the K_BKSLASH Key instead. 

From the resources at:
https://source.android.com/devices/input/keyboard-devices
it looks like Android reports several "international" keys as KEYCODE_BACKSLASH, so you may not be getting enough information to solve this bug. Maybe you can ask Android to split them out in later versions? 

Secondarily, is there a plan to make all Keyman Keycodes in caps, like oE2 becoming OE2?

**Comment by mcdurdin** [comment]
Re the second question, Keyman keycodes are case-insensitive. There are no plans to change any of them.

**Comment by darcywong00** [comment]
Adding a caveat. 

The current Keyman for Android 11.0 with external keyboard behavior is:

### Keyboard has a rule for K_oE2
e.g. Cameroon AZERTY - the rules will properly process

### Keyboard doesn't define K_oE2
e.g. EuroLatin (SIL) - the key has no default output (not even `<` or `>`)

**Comment by mcdurdin** [comment]
If no rule is defined for K_oE2, then the keyboard should use the default behaviour for the key.

**Comment by darcywong00** [comment]
This is in 12.0 master from #1513
