### ISSUE TITLE
chore(developer): tweak git last commit lookup to check only HISTORY.md for keyboard-info builds

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#11793]
It should be possible to tweak the algorithm in keyboard-info-compiler and model-info-compiler to look at the last commit date for each keyboard's HISTORY.md, rather than checking the whole folder. If HISTORY.md not found, then fallback to checking the whole folder.

Ref:

https://github.com/keymanapp/keyman/blob/ccfefa279fe0fd2ad76c568bdcdd2353563f5dfd/developer/src/kmc/src/util/getLastGitCommitDate.ts#L11

This would then avoid the problem of most maintenance PRs impacting the last release date shown on keyman.com.

> But that happened last week sometime, so I think the fact it is showing yesterdays date might be a regression in what is displayed. I looked at another keyboard and see the same thing. @mcdurdin was this intentional?

This is a side-effect of every release and experimental keyboard in the repository being touched in order to move the .keyboard_info metadata into the .kps file. Avoiding reporting of this change would require a non-trivial change to the build process, as currently the build uses the data in the git repository to determine the last date of modification ([code](https://github.com/keymanapp/keyman/blob/f31b05056aea229b3f30d01577edd33251ad58d7/developer/src/kmc/src/commands/buildClasses/BuildModelInfo.ts#L65)). I opted not to try because I didn't think it was important enough, but we could give it a go if other people think it is important.

_Originally posted by @mcdurdin in https://github.com/keymanapp/keyboards/issues/2822#issuecomment-2168761936_

@LornaSIL @DavidLRowe can you see any issues with pulling the Last Update date from the date of the last HISTORY.md commit for a keyboard? Given we always want an update to HISTORY.md if a keyboard is changed, it seems to me to be the most sensible place to track this, if we don't track the whole folder.

**Comment by rowbory** [comment]
Nice move. Indeed HISTORY.md should be updated every time, and you just prompted me to notice I'd forgotten to do that.

**Comment by mcdurdin** [comment]
Hmm, we could even add a build test in the future!

**Comment by mcdurdin** [comment]
Counterpoint: https://github.com/keymanapp/keyboards/pull/2824#discussion_r1641099615

**Comment by LornaSIL** [comment]
> Counterpoint: https://github.com/keymanapp/keyboards/pull/2824#discussion_r1641099615

Hm, yeah, but that was responding to a keyboard approved just a few days earlier that David suggested I update only a few days earlier so it wouldn't be a huge deal. We'll try to do better at getting the history files correct.

**Comment by rowbory** [comment]
> It should be possible to tweak the algorithm in keyboard-info-compiler and model-info-compiler to look at the last commit date for each keyboard's HISTORY.md, rather than checking the whole folder. If HISTORY.md not found, then fallback to checking the whole folder.
> 
> Ref:
> 
> https://github.com/keymanapp/keyman/blob/ccfefa279fe0fd2ad76c568bdcdd2353563f5dfd/developer/src/kmc/src/util/getLastGitCommitDate.ts#L11

I had a quick look in there and I'm wondering whether you need possibly 2 tweaks: 
1. Specify 'master' at the end of the git log command so you get not the most recent commit but the most recently accepted/merged one.
2. Specify HISTORY.md and fall-back to the whole repo.

However, I have a concern that depending on how this function is used, we may want to maintain a distinction between the last git commit (from whatever branch) and the last accepted commit on 'master', especially if this is used to trigger maintenance after a git commit. I think the behaviour I saw was a consequence of this code using the last commit on any branch vs last commit on master, and the version number being drawn from the last commit on 'master'.

**Comment by mcdurdin** [comment]
> However, I have a concern that depending on how this function is used, we may want to maintain a distinction between the last git commit (from whatever branch) and the last accepted commit on 'master', especially if this is used to trigger maintenance after a git commit. I think the behaviour I saw was a consequence of this code using the last commit on any branch vs last commit on master, and the version number being drawn from the last commit on 'master'.

`git log` when called without a revision range uses current HEAD (not all branches). The .keyboard_info for distribution is built on the master branch, so this should not be a problem. We would not want to specify master here anyway, as for test purposes we need to test the functionality on the active branch.

**Comment by DavidLRowe** [comment]
Just a clarification: I think you're talking about the date/timestamp of the HISTORY.md file itself (rather than trying to parse the date out of the file contents, which could be problematic). 

We should probably update the online documentation to emphasize the importance of updating the HISTORY.md file when revising a keyboard.

**Comment by mcdurdin** [comment]
> I think you're talking about the date/timestamp of the HISTORY.md file itself

Pretty much -- actually the date/time of the last commit that includes changes to HISTORY.md, which is stored in the git history so we know it won't change or be unreliable.

> We should probably update the online documentation to emphasize the importance of updating the HISTORY.md file when revising a keyboard.

Yes. I am also thinking that we could add this as a hint for pull requests to the keyboards repo.
