### ISSUE TITLE
Some subkeys [of the Long Press] on the default keyboard are missing

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#118]
The screenshot shows a key with three subkeys (ឈ ្ឆ ្ឈ) when the long press functionality is triggered, but there should be four including ឆ. Thus when pressing the key for short while, four chars should popup--ឆ ឈ ្ឆ ្ឈ.

![screenshot 2017-07-11 08 47 03](https://user-images.githubusercontent.com/28331388/28047643-9ee4ec4e-6615-11e7-8bf5-7be314be72e9.png)

The issue arose in 'Khmer Angkor' keyboard. Please refer to the .ZIP file here for the source codes.

[khmer_angkor.zip](https://github.com/keymanapp/keyman/files/1137549/khmer_angkor.zip)

**Comment by mcdurdin** [comment]
Further notes: some other keys, e.g. ហ, showed the base key in the long press menu as well as the configured long press options. Thus there seems to be some inconsistency as to when the base key is shown in the long press menu.
