### ISSUE TITLE
bug(android): invalid webview height in system keyboard

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#11830]
As seen by @mcdurdin:

![Only half the keyboard is visible](https://github.com/keymanapp/keyman/assets/25213402/d30415b9-d1ad-45a4-a215-136f409a98da)

Seen with the test artifact from #11800, based upon 18.0.57.

**Comment by jahorton** [comment]
The internally-logged message about scaling:

> Height mismatch: onSizeChanged = 420, our version = 765

420 / 765 ~= .55, so the "nearly half" lines up pretty well.  It would appear that something has caused the WebView to be scaled at half the correct height in this scenario.

**Comment by jahorton** [comment]
We've now seen some matching Sentry events arise from the test build of #11826, though interestingly, no related oddities were noted during the user tests.

**Comment by mcdurdin** [comment]
See also:
* #10054
* #11604

**Comment by darcywong00** [comment]
Closing as unable to repro
