### ISSUE TITLE
bug(windows): backspace delete selected text and an extra character

### ISSUE THREAD

**Issue by Nnyny** [keymanapp/keyman#11831]
### Describe the bug

I was investigate on a community site [post](https://community.software.sil.org/t/extra-character-deleted-with-selected-text-in-microsoft-word/8846) and able to reproduce a similar behavior on my computer. Whether I selected from left or right, it will delete the extra character(or a space) at the left. 

> When I select a text in Microsoft Word, BACKSPACE deletes selected texts + an extra character (the previous or following one, depending on what direction I selected the text. 
> 
> I know that similar issues have been noted but I was wondering if any workarounds have been found, in particular through coding with Keyman coding language in Keyman Developer (although any other workaround tips are appreciated). Unfortunately, not using Word is not an option.
> 
> Thank you!

### Reproduce the bug

1. Open MS Word
2. Type 'mySchool'
3. Select 'School' and click backspace to delete it 
4. Show only the letter 'm' 

### Expected behavior

'School' got deleted and we get 'my'

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [X] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.326

### Operating system

Windows 11 Home Single Language 22H2

### Target application

Microsoft Word 2019

### Keyboard name

US Basic

### Language name

English

**Comment by rc-swag** [comment]
Thank you @Nnyny, I have captured your steps to reproduce the error and added them to an existing issue #7870 tracking this problem. Closing this as a dulpicate
