### ISSUE TITLE
[linux] keyboard information window

### ISSUE THREAD

**Issue by glasseyes** [keymanapp/keyman#1185]
The keyboard information window is incomplete

**Comment by glasseyes** [comment]
The window now has a lot more, hopefully all, information but should have a UX review

**Comment by glasseyes** [comment]
![aboutkeyboard](https://user-images.githubusercontent.com/901605/51292872-f90a3100-1a3e-11e9-89c6-04424de54ce5.png)

Current about keyboard window

**Comment by darcywong00** [comment]
Keyboard information has the info needed for Keyman 11
