### ISSUE TITLE
bug(developer): Keyman Developer needs to be restarted before Keyboard package will compile

### ISSUE THREAD

**Issue by HopsAndHops** [keymanapp/keyman#11864]
### Describe the bug

I have encountered this issue consistently since updating Keyman (17.0.326). This happens the first time I open up an existing keyboard after switching to a new branch, restart my computer, launch Developer, or create a new keyboard. 

When I attempt to compile the keyboard, I receive the below error in messages:
![Screenshot 2024-06-19 at 12 33 40 AM](https://github.com/keymanapp/keyman/assets/127360690/e9089b22-f404-492c-938a-e9d1a960c2dd)

When I close Keyman Developer after receiving this message, I get the below message. Keyman Developer does not crash on its own or freeze - I only receive this message after I close out the window.
![Screenshot 2024-06-20 at 7 33 51 PM](https://github.com/keymanapp/keyman/assets/127360690/4389f5af-23f7-4f01-97e0-bfdaec920707)

After I restart Keyman Developer, I no longer receive the first set of messages and have no issues compiling the keyboard package no matter how many changes I make. Before this, I tried removing and re-adding the files flagged in the error messages. They continued to be flagged after being added again. I've run into this issue several times a day, on 5 different branches/keyboards and this solution has worked consistently since stumbling on it.

I'm happy to provide shaky-cam if needed!

### Reproduce the bug

1. Open a new or existing Keyboard Project
2. Open up a package tab, and attempt to compile the keyboard package
3. Error messages pop-up
4. Close out Keyman Developer and crash message appears
5. Reopen Keyman Developer, and package will compile as normal

### Expected behavior

The keyboard compiles normally, without error messages

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [X] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.326

### Operating system

Windows 11 Home 22H2

### Device

2019 iMac, running virtual desktop through Parallels (19.4.0)

**Comment by HopsAndHops** [comment]
Update to this: I haven't experienced this since reporting it so I don't think I'll be able to provide shaky cam. I'll keep my eyes peeled in case this happens again though!

**Comment by mcdurdin** [comment]
Thanks for the update. I will go ahead and close this to reduce the chaos in our issue list, but please do reopen if the issue recurs. I am still tracking the crash report (#11916) as a separate task.
