### ISSUE TITLE
[linux] doc for keyman and ibus on gnome-shell

### ISSUE THREAD

**Issue by glasseyes** [keymanapp/keyman#1186]
Can't find keyman keyboard in gnome-shell

You can only select the keyboards to be used in gnome-shell after they are activated in ibus-setup

This is very user unfriendly

**Comment by glasseyes** [comment]
This looks much better now. Provided that the installation has gone smoothly - the process for installing a keyboard in keyman-config and then selecting it in gnome-shell then being available in the keyboard picker is smooth. 
https://community.software.sil.org/t/keyman-11-beta-feedback/1631/22

This issue is now for using that post as a basis for documentation

**Comment by darcywong00** [comment]
Documentation issue moved to help.keyman.com (above)
