### ISSUE TITLE
[linux] handle more than one keyboard in a kmp in inf file parsing when keyboards undefined

### ISSUE THREAD

**Issue by glasseyes** [keymanapp/keyman#1187]
Marc wrote in #893 :
> linux/keyman-config/keyman_config/install_kmp.py :69
> There may be more than one keyboard in a package.

**Comment by glasseyes** [comment]
There are probably assumptions about that in the installer so I need to check that

**Comment by glasseyes** [comment]
Looking more into this. This the generation of a keyboards dict when parsing an inf file if it doesn't have any keyboards defined. In this case the kmp should be fixed to define multiple keyboards rather than the installer making more guesses as to what they are.

**Comment by glasseyes** [comment]
Please close if that makes sense.

**Comment by mcdurdin** [comment]
I think it makes sense for us to support legacy .kmp files for Linux. A legacy .kmp file has a kmp.inf and no kmp.json, and does not have a `[Keyboards]` section in the kmp.inf. The keyboards are identified by file extension .kmx so no guessing required.

There's a bit of a larger discussion about language tagging for legacy keyboard installation that we could have but I don't know if you want to go into that at this stage.
