### ISSUE TITLE
chore(ios): CI builds for FirstVoices are down due to license agreement update

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#11883]
iOS build maintenance needed:

```
15:38:43   /opt/homebrew/Cellar/fastlane/2.220.0/libexec/gems/fastlane-2.220.0/spaceship/lib/spaceship/connect_api/api_client.rb:250:in `handle_error': [!] The request could not be completed because: (Spaceship::ProgramLicenseAgreementUpdated)
15:38:43     A required agreement is missing or has expired. - This request requires an in-effect agreement that has not been signed or has expired.
```

From https://build.palaso.org/buildConfiguration/Keyman_iOS_TestPullRequests/474686?buildTab=log&linesState=2357.2448&logView=flowAware&focusLine=2565

This also affects our 18.0.62-alpha builds for macOS and iOS.

**Comment by mcdurdin** [comment]
This only impacts FV builds, shouldn't impact macOS builds.

**Comment by mcdurdin** [comment]
I have passed this on to the FirstVoices team to action.

**Comment by mcdurdin** [comment]
I have temporarily disabled FV iOS build (RELEASE_OEM and RELEASE_OEM_FIRSTVOICES env vars in build configuration https://build.palaso.org/admin/editProject.html?projectId=Keyman_iOS&tab=projectParams) so that we can avoid build failures until FPCF have sorted out the Apple agreements

**Comment by mcdurdin** [comment]
Resolved for alpha builds. Builds re-enabled. A second agreement needs to be accepted for stable release builds, I think.

**Comment by mcdurdin** [comment]
Second agreement accepted, closing this.
