### ISSUE TITLE
bug(windows): wm_keymankeydown is supposed to be sent to IMX window, but never is

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#11919]
https://github.com/keymanapp/keyman/blob/2bc041f35324998a7570a2eb8713250561b1a700/windows/src/engine/keyman32/kmhook_getmessage.cpp#L299-L306

The `wm_keymankeydown` and `wm_keymankeyup` messages are never generated.

Is this causing problems with IMX?

See also #11917

**Comment by rc-swag** [comment]
> Is this causing problems with IMX?

Well, it does not appear to. Selection works with the Number keys 1-9 instead of the Function keys F1-F12. Even when configured to use the function keys. I'm not sure if this is related other than that it all seems to work fine.

**Comment by rc-swag** [comment]
Can remove 301 - 304 and possibly wm_keymanup/down all together.
