### ISSUE TITLE
bug (mac): Amharic keyboard ignoring context in the Google docs on Safari browser.

### ISSUE THREAD

**Issue by dinakaranr** [keymanapp/keyman#11942]
### Describe the bug

I have seen this behaviour appears on the safari browser.

### Reproduce the bug

Steps to reproduce:

1. Install the latest version of Keyman 17.0.326 stable version in macOS.
2. Download and install the gff_amharic keyboard using the Keyman Configuration dialog.
3. Open the Chrome browser.
4. Switch to the Amharic keyboard.
5. Open the Google Text Doc from Drive.
6. Type tt on the empty page.
7. Press the left-arrow and then type a.
Actual Results: Here, it is showing the wrong output. It is showing as "ትአት" but it needs to display as "ታት"
<img width="300" src="https://github.com/keymanapp/keyman/assets/19683059/d724a537-5045-4c69-bbe0-1bf4706157d3">

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [X] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.326

### Device

macOS

### Browser

safari

### Keyboard name

contextreset

### Keyboard version

1.0.0

**Comment by mcdurdin** [comment]
(you wrote Chrome in one place, but I think you mean Safari?)

This is expected behaviour because the Safari browser is not a 'compliant' app and so Keyman cannot read the context from the app when the cursor is moved.

**Comment by dinakaranr** [comment]
Yes, I have given Chrome instead of Safari browser. I am sorry. I thought the safari came under the compliant app in macOS. Thank you for the clarification.
