### ISSUE TITLE
[Windows] Adobe Indesign CC issue

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#1196]
Keyman keyboard does recognize the letter the left of the cursor, if moved to a previous typed letter.

sequence

if 'a' is present, when key '1' is pressed must output '0', if not '1'

if the 1 is typed immediately after the a, then 0 is outputted.
but if the cursor is placed next to a while edited, keyman doesn't recognize the previous character is 'a'.

This is not the case in other applications such as MS Word.

**Comment by mcdurdin** [comment]
This happens by design because Adobe Indesign does not implement Text Services Framework so we have no access to the text buffer, so we use a legacy input mode.

**Comment by MayuraVerma** [comment]
Is this reported to adobe?

www.adobeprerelease.com is best place to report it.

They are starting to work on 2020 version. Many issues I reported for language is resolved.

I don't know all the technical details. Otherwise I would report on your behalf.

After you have reported. Please let me know, I can follow up with them.

**Comment by mcdurdin** [comment]
I might leave the initial report to you for now if that's okay -- kinda busy at present! 

The thing to request is that Adobe implement full Text Services Framework support and refer them to the Microsoft documentation at https://docs.microsoft.com/en-us/windows/desktop/tsf/text-services-framework. You can refer to this issue as well if you like and note that Keyman among other input methods will benefit from TSF support.
