### ISSUE TITLE
bug(windows): keyboards stuck in Chrome 

### ISSUE THREAD

**Issue by Nnyny** [keymanapp/keyman#11964]
### Describe the bug

Keyman keyboards (and OSK) stuck in Chrome and won't output anything after I switched keyboards from English to Khmer. But it works fine when I type it on other applications. Refresh and delete the Chrome tab won't work. I have to close all tabs and restart Chrome for it to work again. This only occur when I used Chrome for a long period of time (probably more than an hour). 

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [X] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.326

### Operating system

Windows 11 Home Single Language 22H2

### Device

Laptop

### Browser

Chrome Version 126.0.6478.127 (Official Build) (64-bit)

### Keyboard name

Khmer Angkor, US Basic

**Comment by rc-swag** [comment]
@Nnyny are you still seeing this issue?

**Comment by Nnyny** [comment]
It's no longer an issue @rc-swag.
