### ISSUE TITLE
[Windows] Improvements to localization of Keyman Desktop

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#1200]
See https://community.software.sil.org/t/translation/1304/7

* Many fields such as
S_OSK_FontHelper_MatchedFonts1
S_OSK_FontHelper_NoFonts1a
S_OSK_FontHelper_PleaseWait1
S_OSK_FontHelper_PossibleFontsOnly1
S_OSK_Hint3a
S_OSK_Hint4a

are not completely internationalized. They are broken sentences with something at the end will make it complete. It would be very different to phrase a sentence with the same meaning in other language. Instead we could have add the variable %0:s similar to how it is done in other places. This way localization can be done freely and natively.

* Window size and font size is huge constraint in localization.

I can see some codes in locale_en.xml to adjust the window size. I am sure if we can use this as customization while localization.

Ability to change font size and window size is needed while localization.

* Split out deployment of localization by language so we can deploy font files with the localization file.

**Comment by MayuraVerma** [comment]
Please avoid incomplete sentence.

Also, please update these

S_LangSetup_TitleInnerPrefix
S_OSK_FontHelper_NoFonts1b
S_OSK_FontHelper_NonUnicode2

S_Help_Keyboard_Prefix and S_Help_Keyboard_Suffix should be merged with the keyboard as the variable in the middle.

**Comment by mcdurdin** [comment]
`S_LangSetup*` can be removed as the Language Setup dialog is no longer in Keyman Desktop. (Worth checking all other strings that are obsolete at the same time I think).

**Comment by mcdurdin** [comment]
Note: we currently plan to tackle all localization issues in 13.0 so this fits well into that.

**Comment by mcdurdin** [comment]
Points 1 and 2 were addressed in #3412 and #3414.

I'd like to deal with points two and three as a separate issue:

* Window size and font size is huge constraint in localization.
    I can see some codes in locale_en.xml to adjust the window size. I am sure if we can use this as customization while localization.

* Ability to change font size and window size is needed while localization.
    Split out deployment of localization by language so we can deploy font files with the localization file.
