### ISSUE TITLE
feat: improve support for bcp 47

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#12012]
BCP 47 tagging in keyboards and models is currently somewhat OS-dependent. We need to move the contact points of this issue so that we can use proper full BCP 47 tags internally in Keyman, and only reduce them to OS requirements where necessary. For example, on Windows, we don't use extension subtags (because they crash many apps and even OS components sometimes), but we should be able to have those subtags in the .kmp files.

This is a grouping issue for other issues with m:bcp47 label, currently:
* #11046
* #9693
* #9131
* #9099
* #3167
* #2237
* #164
* https://github.com/keymanapp/keyman/pull/11014#discussion_r1820032420
* https://github.com/keymanapp/keyman/issues/7548

See also:
* https://github.com/keymanapp/keyboards/pull/2988#issuecomment-2249259407

**Comment by mcdurdin** [comment]
The current limited BCP47 tag model needs to go. See https://docs.google.com/document/d/1XF7tUv5PYqlwBPbv7wUO7sgIFI7n4bp5rg03_rdb3MY/edit

We will allow any validly structured BCP 47 tag for a keyboard, canonicalize at compile time, always include script if lang does not have suppress-script so that platforms without script data can install. Installer will reduce tag as required to 'holy triplet' lang-script-region on platforms that require this.

Language models will need to have a smarter BCP 47 correspondence algorithm.

**Comment by mcdurdin** [comment]
node 20 removes script from `str` but Windows expects it. So we should make sure that Keyman for Windows makes use of suppress-script registry to put it back in? (How?)

```
> new Intl.Locale('str-latn-sencoten').minimize().toString()
'str-sencoten'
> new Intl.Locale('str-latn-sencoten').maximize().toString()
'str-Latn-CA-sencoten'
```

So, is the answer to maximize the locale in kmp.json, so that we can have a consistent minimization on each platform according to its own data?


Developer -- compiler suppots any valid tag, incl. unregistered variants. But does not provide UI to edit
  🟨 TODO: refresh package editor UI, incl. bcp47 picker
  🟨 TODO: consider if we need minimal tags in .kps and if we should stop hinting on those
  🟨 TODO: consider hinting on unregistered tags (against langtags.json? e.g. abt-Latn-PG-x-maprik, abt-Latn-PG-x-woserak vs abt-Latn-x-woserak)
  🟨 TODO: consider if we need to store maximal tags in kmp.json
  🟨 TODO: warn if a tag has unknown script (e.g. `und`)

Windows -- can do any valid tag but expects script to be there for any bcp47 not in suppress-script (apparently static)
  🟨 TODO: minimize tags accordingly, but restore script subtag if needed, use `Latn` as fallback?
  🟨 TODO: find out if region subtag is always optional, e.g. see abt-Latn-PG-x-maprik example above

Linux -- probably supports any valid tag -- but what about unregistered variants?
  ❓ TODO: verify

macOS -- supports only holy triplet
  ❌ TODO: well, currently totally unsupported ...
iOS -- supports only holy triplet
  ❌ TODO: currently totally unsupported
Android -- good question
  ❌ TODO: currently totally unsupported
web -- supports any valid tag -- incl. unregistered variants
  ❌ TODO: currently totally unsupported

**Comment by mcdurdin** [comment]
@srl295 your feedback appreciated on above comment please?

**Comment by srl295** [comment]
> node 20 minimize() removes script from `str-Latn` but Windows expects it. 

Probably it now has SIL data and can suppress it. 

> So we should make sure that Keyman for Windows makes use of suppress-script registry to put it back in? (How?)

Maximize would give a script. 

> 
> ```
> 
> > new Intl.Locale('str-latn-sencoten').minimize().toString()
> 
> 'str-sencoten'
> 
> > new Intl.Locale('str-latn-sencoten').maximize().toString()
> 
> 'str-Latn-CA-sencoten'
> 
> ```
> 


Yes. Then drop whatever we don't need there. 

> 
> 
> So, is the answer to maximize the locale in kmp.json, so that we can have a consistent minimization on each platform according to its own data?
> 
> 

I had long wondered and suggested just keeping a maximal tag at least for scripts. 

Kazakh will become multi script etc, these change over time- ριγητ?



> 
> 
> 
> Developer -- compiler suppots any valid tag, incl. unregistered variants. But does not provide UI to edit
> 
>   🟨 TODO: refresh package editor UI, incl. bcp47 picker

Yes 


>   🟨 TODO: consider if we need minimal tags in .kps and if we should stop hinting on those
> 
>   🟨 TODO: consider hinting on unregistered tags (against langtags.json? e.g. abt-Latn-PG-x-maprik, abt-Latn-PG-x-woserak vs abt-Latn-x-woserak)

Right. Good idea. 
Or unknown extensions 
> 
>   🟨 TODO: consider if we need to store maximal tags in kmp.json
> 
>   🟨 TODO: warn if a tag has unknown script (e.g. `und`)
> 
> 
> 
> Windows -- can do any valid tag but expects script to be there for any bcp47 not in suppress-script (apparently static)
> 
>   🟨 TODO: minimize tags accordingly, but restore script subtag if needed, use `Latn` as fallback?

> 
>   🟨 TODO: find out if region subtag is always optional, e.g. see abt-Latn-PG-x-maprik example above
> 
> 
> 
> Linux -- probably supports any valid tag -- but what about unregistered variants?
> 
>   ❓ TODO: verify
> 
> 
> 
> macOS -- supports only holy triplet
> 
>   ❌ TODO: well, currently totally unsupported ...
> 
> iOS -- supports only holy triplet
> 
>   ❌ TODO: currently totally unsupported
> 
> Android -- good question
> 
>   ❌ TODO: currently totally unsupported
> 
> web -- supports any valid tag -- incl. unregistered variants
> 
>   ❌ TODO: currently totally unsupported
> 
> 
> 
>

**Comment by mcdurdin** [comment]
Bbackground notes on status of custom language names (coming out of a discussion with @LornaSIL:

I just created this package for Khmer: [my_custom_language_name.zip](https://github.com/user-attachments/files/17389777/my_custom_language_name.zip)

I and used the language name and keyboard name as shown below:
![image](https://github.com/user-attachments/assets/c02660ba-061f-4dad-a258-47a2848c5a7b)

and the keyboard name is: 

![image](https://github.com/user-attachments/assets/09dfa063-3003-47df-9d86-2f018e35e893)

* **Android:** You can see from the screenshot attached that it works as expected:

  ![image](https://github.com/user-attachments/assets/bac0ce05-edff-4b7e-933f-e217762a4dcf)

* **iOS:** also works:

  ![image](https://github.com/user-attachments/assets/fa0ef543-02fe-4972-b631-afb2093451d6)

* **Windows:** YMMV -- the language picker in Windows does not allow us to override language name. The UI within Keyman Configuration shows the language name:

  ![image](https://github.com/user-attachments/assets/ba766dd5-8321-43ad-a620-f8601eb865ae)

  The Keyman menu shows "Khmer" (because it reads from Windows installed langs):

  ![image](https://github.com/user-attachments/assets/6ac6bfd4-6cfc-4dbd-a7b2-3dfef58c2eb9)

  As does the Windows language picker (as expected):

  ![image](https://github.com/user-attachments/assets/d8028695-7ba6-4554-a7d9-da7da49dbb85)

* **Linux:** I am unsure, but as most of the language picker UI is ibus, I don't think we'll see the custom language name

* **macOS:** We don't currently support languages ... at all

**Comment by darcywong00** [comment]
> * **Linux:** I am unsure....

On my Ubuntu-based distro, the keyboard picker shows
![image](https://github.com/user-attachments/assets/0d278853-7df8-4c95-b8e6-ac8513a4ea4a)
