### ISSUE TITLE
bug(linux): OSK does not support `&displayMap` fonts, e.g. with khmer_angkor 1.5 keyboard and others

### ISSUE THREAD

**Issue by dinakaranr** [keymanapp/keyman#12019]
### Describe the bug

the keys do not appear properly on the buttons. It shows the application icon on the buttons.

### Reproduce the bug

Steps to reproduce:

1. Install the latest version of the Keyman-17.0.326 stable version.
2. Downloaded and installed the "Khmer Angkor" keyboard using the Keyman Configuration dialog.
3. Select the "Khmer" keyboard on the toolbar.
4. Open the "OnBoard" app. 
5. Actual Results: Here, the "On-Screen Keyboard" window appears for the "Khmer Angkor" keyboard. but the keys do not appear properly on the buttons. It shows the application icon on the buttons.
<img width="300" src="https://github.com/user-attachments/assets/f8594c0d-54d6-4ec1-a1b8-2a6b0b117a49">

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [X] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.326 stable version

### Operating system

Ubuntu wasta 22.04 Cinnamon

### Keyboard name

khmer_angkor

### Keyboard version

1.5

### Language name

Khmer

**Comment by ermshiperete** [comment]
This also happens on other Linux distros. I wonder if it is related to the changed font for the OSK which was added in khmer_angkor 1.5.

**Comment by mcdurdin** [comment]
> I wonder if it is related to the changed font for the OSK which was added in khmer_angkor 1.5.

Yes, it is directly related. The new font uses PUA for the key caps. As onboard-keyman does not support custom fonts, this is broken.

This is a regression from v16, which I had not anticipated. I think we need to discuss mitigation strategies, because it will impact any keyboard that uses `&displayMap`. (Do we still use onboard-keyman? Could we patch that to support custom fonts?)

**Comment by mcdurdin** [comment]
Handing over to you on this @ermshiperete
