### ISSUE TITLE
[linux] keyman-config: migrate to WebKit2

### ISSUE THREAD

**Issue by nikita-moor** [keymanapp/keyman#1201]
Tools from "keyman-config" use an old WebKit1 API [deprecated since 2014](https://blogs.gnome.org/mcatanzaro/2016/02/01/on-webkit-security-updates/).

https://github.com/keymanapp/keyman/blob/3f474c64feb842cfadfd5c253516624056359adc/linux/keyman-config/keyman_config/welcome.py#L11

In the beginning of 2017, WebkitGTK+ 2.4 package with API v1 [was removed](https://www.archlinux.org/todo/phasing-out-webkitgtk2/) from Arch Linux repositories. Supporting the old release of this big library would be a laborious task, and does not seem reasonable to use it for new development.

**Comment by glasseyes** [comment]
Afair WebKit was used as in the experiments the newer WebKit couldn't do the custom keyman protocol that the embedded webpage for mac has in the link for installing the keyboard package.

Once the website is updated to support linux there will be an embedded page specifically for linux that can have links without that protocol. Then we can move to WebKit2 (API 4.0).

I don't expect this to happen until keyman on Linux uses the new (in development) keyman engine and can use the compiled keyboards in the packages.
