### ISSUE TITLE
chore(common): Update SIL logo on Keyman apps

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#12053]
See keymanapp/keyman.com#460

> https://sites.google.com/sil.org/brand-resource-center/branding/visual-brand/logos
>
> When we do so, let's make it a lot smaller than it currently is

TODO:
- [x] #12127
- [ ] #12157
- [ ] #12158
- [ ] #12159
- [x] #12160
- [x] #12161

**Comment by mcdurdin** [comment]
TODO:
- [x] Update logo on Keyman for Android @darcywong00 - #12127
- [ ] Update logo on Keyman for iOS @sgschantz 
- [ ] Update logo on Keyman for Linux @ermshiperete 
- [ ] Update logo on Keyman for macOS @sgschantz 
- [ ] Update logo on Keyman for Windows @rc-swag 
- [ ] Update logo on Keyman Developer @mcdurdin

**Comment by mcdurdin** [comment]
Closing this, tracked in separate issues.
