### ISSUE TITLE
bug: compiled LDML keyboard echos default layer outputs on other layers

### ISSUE THREAD

**Issue by DavidLRowe** [keymanapp/keyman#12057]
### Describe the bug

Pull request 2993 in keyboards repository (https://github.com/keymanapp/keyboards/pull/2993) is an LDML keyboard. When compiled (see commit [b14c6b6](https://github.com/keymanapp/keyboards/pull/2993/commits/b14c6b6c468d0304e5b7b59bd7b8ec4950a30d4f)), the keyboard produces characters for default and shift layers as expected, but the characters of the default layer are echoed on other layers. For example, Ctrl+C, Shift+Ctrl+C, RAlt+C, Shift+RAlt+C all produce the same output as "c". 

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [X] Other - give details at bottom of form

### Keyman version

17.0.326

### Operating system

Windows 11

### Device

Windows laptop

### Target application

Notepad

### Additional context

Is it possible to examine the .kmx file (in attached .zip file) [imperial_aramaic-kmx.zip](https://github.com/user-attachments/files/16419832/imperial_aramaic-kmx.zip) to see if the compiler has added the extra layers?

**Comment by DavidLRowe** [comment]
@mcdurdin Additional info: The result above was from using Keyman Developer's "Keyboard" menu, "Test keyboard" menu item.

**Comment by DavidLRowe** [comment]
When I installed the compiled and packaged keyboard on a Windows 11 computer, I found that Ctrl+a and Ctrl+Shift+a produced the same character as "a", but Alt+A brought up a menu (in Notepad).

**Comment by mcdurdin** [comment]
This is due to a bug in Core. See #12281 for fix coming shortly.
