### ISSUE TITLE
bug(developer): LDML file generates a blank .kvk file

### ISSUE THREAD

**Issue by LornaSIL** [keymanapp/keyman#12056]
### Describe the bug

It appears that an LDML keyboard generates a .kvk file, but when the keyboard is installed it is blank and doesn't show any characters. This is not helpful for users who wish to know how to type using a keyboard.

In addition, I can type using the physical keyboard and it outputs the characters, but when I press on the OSK keycaps it doesn't do anything.

### Reproduce the bug

1. Install the keyboard from this PR: https://github.com/keymanapp/keyboards/pull/2993
2. Compile the xml
3. Compile the kps
4. Install the keyboard
5. Turn on On-Screen Keyboard
7. Open LibreOffice
8. Select Imperial Aramaic.
9. Type some letters on the physical keyboard (default layer). It works.
10. See the blank OSK
![osk](https://github.com/user-attachments/assets/406fe33a-16cb-4bb4-a3f5-553c7019317c)
11. Try to type the keys on the OSK. Seems to work even though you cannot see keys.

### Expected behavior

It would be nice if it generated a .kvk file with the characters on the keycaps.

### Related issues

This is the PR: https://github.com/keymanapp/keyboards/pull/2993

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [X] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.328

### Operating system

Windows 11

### Device

Windows Dell laptop

### Target application

LibreOffice

### Keyboard name

imperial_aramaic

### Keyboard version

1.0

### Language name

arc

### Additional context

I can't even create a graphic to show the keycaps. So, I ended up implementing the keyboard in .kmn syntax so I could generate a graphic which I used in the welcome.htm file :)

**Comment by mcdurdin** [comment]
Yes, I can replicate this and see there are a few problems with the [LDML kvk compiler](https://github.com/keymanapp/keyman/blob/e67aed1606b76a5d110a94a71a1fb5cefb9682ee/developer/src/kmc-ldml/src/compiler/visual-keyboard-compiler.ts) as it stands. Will discuss internally -- I think we may need to rewrite it...

> In addition, I can type using the physical keyboard and it outputs the characters, but when I press on the OSK keycaps it doesn't do anything.

I would like to split the problem with generating the .kvk file apart from the problem of using it. Is this problem happening on Windows or another platform?

**Comment by LornaSIL** [comment]
> I would like to split the problem with generating the .kvk file apart from the problem of using it. Is this problem happening on Windows or another platform?

I'm using Win11 Pro with all current updates.
