### ISSUE TITLE
bug(linux): fix Lintian errors

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/keyman#12051]
Building the `libkeymancore` Debian package results in Lintian errors which [prevent acceptance of the 17.0.327+ package](https://lists.debian.org/debian-input-method/2024/07/msg00091.html).

```
E: libkeymancore1: symbols-file-contains-current-version-with-debian-revision on symbol
_ZNSt10_HashtableINSt7__cxx1112basic_stringIDsSt11char_traitsIDsESaIDsEEESt4pairIKS5_S5_ESaIS8_ENSt8__detail10_Select1stESt8equal_toIS5_ESt4hashIS5_ENSA_18_Mod_range_hashingENSA_20_Default_ranged_hashENSA_20_Prime_rehash_policyENSA_17_Hashtable_traitsILb1ELb0ELb1EEEE21_M_insert_unique_nodeEmmPNSA_10_Hash_nodeIS8_Lb1EEEm@Base
and 26 others (libkeymancore.so.1) [symbols]
```

The additional symbols can be seen in the [Debian build log](https://buildd.debian.org/status/fetch.php?pkg=keyman&arch=amd64&ver=17.0.326-1&stamp=1718052113&raw=0).

**Comment by ermshiperete** [comment]
The only place `Hashtable` is used is in ICU code.

I'm not sure if fixing #10882 would help.

**Comment by mcdurdin** [comment]
@srl295 thoughts?

**Comment by ermshiperete** [comment]
@mcdurdin Since I won't get to this in the current sprint  I'll move it after the scheduled web-core work.
