### ISSUE TITLE
bug(developer): An empty key appears on the "Web Keyboard"(Open in browser)

### ISSUE THREAD

**Issue by dinakaranr** [keymanapp/keyman#12099]
### Describe the bug

An empty icon appears above the input text box. If I enter some text, then an empty icon disappears. 

### Reproduce the bug

Steps to reproduce:

1. Installed the "keymandeveloper-18.0.81.exe" file.
2. Double-click on the "Keyman Developer" icon. The developer tool appeared correctly.
3. Open the Keyman keyboard project (*.kpj) file.
4. Open any keyman keyboard (*.kmn) file. (e.g., Arabic)
5. Navigate to the Debugger mode by pressing the F5 or (On build tab/Start Debugging).
6. Navigate to the Layout tab. Click on an empty text box. Type a letter. 
7. Navigate to the Build tab.  Click the "Test Keyboard on Web".
8. Select "http://localhost:8008" and then click "Open in browser". 
9. The keyboard is opened on the browser.
Actual Results: Here, an empty icon appears above the input text box. If I enter some text, then an empty icon disappears.
Please refer to the below screenshot
<img width="300" src="https://github.com/user-attachments/assets/cf8182e4-84de-49ac-87f1-a5e7e74273ca">

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [X] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

18.0.81

### Operating system

Windows 10 OS

### Browser

FireFox 128

**Comment by mcdurdin** [comment]
This is by design. The box above the text box shows the code point value of each character in the text box. If the text box contains no text, then the 'empty' message is shown -- this was clearer than just showing nothing in that box, in our testing.
