### ISSUE TITLE
chore(windows): add S_Splash_Start_2 translations once merged in to crowdin

### ISSUE THREAD

**Issue by rc-swag** [keymanapp/keyman#12219]
> This change will mean all the other languages will, until translated have the english "Start" on the splash screen. We could quite easily do the translation ourselves looking at the existing start splash screen. Should we do that in crowdin?

Maybe we tackle other translations on a separate PR. After this new string gets merged to master, I'll upload to Crowdin first.

_Originally posted by @darcywong00 in https://github.com/keymanapp/keyman/pull/12162#discussion_r1717830148_

**Comment by darcywong00** [comment]
This looks like the Crowdin cron job already synced this new string August 19.

https://crowdin.com/editor/keyman/all?view=multilingual&filter=basic&value=3#q=S_Splash_Start_2

**Comment by darcywong00** [comment]
Downloading translated strings will just happen on a per-language basis when the completion percentages are nearly done.
