### ISSUE TITLE
bug(web): documentation keyboards often have poorly-scaled keycaps

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#12231]
As seen in cases such as https://github.com/keymanapp/help.keyman.com/pull/1272#issuecomment-2270255783, our documentation keyboards often have poorly-scaled spacebar labels, with the usual "keyboard - language" label overrunning the spacebar's boundaries.

Example:

![image](https://github.com/user-attachments/assets/7842988d-94f1-42ca-a736-5026287c334e)

Affects 18.0.92.  

It would likely affect stable-17.0 if it showed spacebar text in addition to older versions of KMW.  I seem to remember it being off in the same manner in the past.

**Comment by mcdurdin** [comment]
Can you add impacted version details please?
