### ISSUE TITLE
chore(windows): Update SIL International strings to SIL Global

### ISSUE THREAD

**Issue by rc-swag** [keymanapp/keyman#12251]
These strings need to be replaced or updated to read "SIL International"
`strings.xml`
S_Support_CreatedBySIL
S_Support_Copyright

**Comment by rc-swag** [comment]
@darcywong00 
Should I add two new string IDs deprecating these IDs. Or just updated the strings and get them re-translated in Crowdin.

**Comment by darcywong00** [comment]
I've generally left old strings in crowdin (they still get used in 17.0).
Maybe create two new string IDs like S_Support_CreatedBySILGlobal and S_Support_CopyrightGlobal?

**Comment by mcdurdin** [comment]
Not sure that it makes sense to change string IDs? "SIL International" (or "SIL Global") is a name that shouldn't be localized.

**Comment by rc-swag** [comment]
> Not sure that it makes sense to change string IDs? "SIL International" (or "SIL Global") is a name that shouldn't be localized
That not the whole string though
S_Support_Copyright

- Haƙƙin mallaka © SIL International All Rights Reserved.
- የቅጂ መብት © SIL International፤ ሁሉም መብቶቹ የተጠበቁ ናቸው።

S_Support_CreatedBySIL

- Created by SIL International
- Vytvořeno SIL International

Prehaps we should do the same thing we recently did with the Start Keyman string
 
<string name="S_Support_CreatedBySILGlobal" comment="Created by {SIL Global} ">Created by %1$s</string>

**Comment by mcdurdin** [comment]
> Prehaps we should do the same thing we recently did with the Start Keyman string
> 
> `<string name="S_Support_CreatedBySILGlobal" comment="Created by {SIL Global} ">Created by %1$s</string>`

Yep
