### ISSUE TITLE
chore(android): Could not find com.stepstone.stepper:material-stepper:4.3.1 on a new development installation

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#12260]
`android/build.sh`: 

```
A problem occurred configuring root project 'KMAPro'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find com.stepstone.stepper:material-stepper:4.3.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/stepstone/stepper/material-stepper/4.3.1/material-stepper-4.3.1.pom
       - https://jcenter.bintray.com/com/stepstone/stepper/material-stepper/4.3.1/material-stepper-4.3.1.pom
       - https://repo.maven.apache.org/maven2/com/stepstone/stepper/material-stepper/4.3.1/material-stepper-4.3.1.pom
     Required by:
         project :
```

build.gradle:
```
        // From jcenter() which could be sunset in future
        // https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
        classpath 'com.stepstone.stepper:material-stepper:4.3.1'
```

So, yes, this relates to JCenter shutdown which happened last week (good timing huh?)

> UPDATE 7/2/2024: After over three years of maintaining JCenter as a read-only repository for legacy Java packages, JFrog is moving forward with an official sunset of JCenter, and, in coordination with Maven Central, will begin automatically redirecting all JCenter requests to the Maven Central Repository. The first of several service brown-outs is scheduled for July 30th and will periodically continue until the final shutdown of JCenter on August 15th. For more details, please see [JFrog’s official announcement](https://jfrog.com/blog/jcenter-sunset/).

We should either replace this component with a newer one, or bring the component into the repository.

**Comment by darcywong00** [comment]
Cursory check to see if we can use this 
https://mvnrepository.com/artifact/com.stepstone.stepper/material-stepper/4.3.0

**Comment by mcdurdin** [comment]
> Cursory check to see if we can use this
> https://mvnrepository.com/artifact/com.stepstone.stepper/material-stepper/4.3.0

No, the repositories referenced there do not appear to work (either spring-lib which requires login, or gradle).

Also tried to copy .aar from my own machine and use it locally but the problem is that local use seems to require .jar, and I don't fully understand this yet.

**Comment by darcywong00** [comment]
Now trying this guide in [setting up local maven repository](https://brightinventions.pl/blog/migrating-away-from-bintray-jcenter-when-there-is-no-alternative-repository/#setting-up-a-local-maven-repository) to check in the cached gradle dependencies for material-stepper
