### ISSUE TITLE
bug(linux): Keyboard stops working

### ISSUE THREAD

**Issue by Belu-cat** [keymanapp/keyman#12266]
### Describe the bug

I've been having an issue on Linux where, when I switch to my Keyman keyboard, it will only work for a few seconds. After these few seconds, it'll go back to working like a regular old English US keyboard. It will work as expected for a few seconds, and then stop working.

Example:
Typed: <kbd>h</kbd> <kbd>Control</kbd>+<kbd>six</kbd>
Received: h
Expected: ĥ

### Expected behavior

Be able to type the corresponding character too the key I typed

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [X] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16.0.144-1

### Operating system

Arch Linux

### Device

Dell Elitebook

**Comment by ermshiperete** [comment]
Are you using X11 or Wayland? In what application is this happening?

You might want to try with the latest Keyman version, Keyman 17, and see if that improves things.

**Comment by mcdurdin** [comment]
Closing with no response from user. Please feel free to reopen if you have further feedback.
