### ISSUE TITLE
bug(mac): crash on startup with macOS Catalina

### ISSUE THREAD

**Issue by sgschantz** [keymanapp/keyman#12295]
### Describe the bug

When running Keyman with macOS Catalina 10.15.3 the app crashes on startup.
According to the attached crash report, an error occurs when attempting to use the API CGPreflightPostEventAccess. This API is used to determine whether the user has granted Keyman Accessibility permission, which is required for Keyman to intercept key events.

[Apple's documention for the API](https://developer.apple.com/documentation/coregraphics/3656520-cgpreflightposteventaccess?language=objc) states that the CGPreflightPostEventAccess API is available with macOS 10.15+.

[catalina-crash-report.txt](https://github.com/user-attachments/files/16756241/catalina-crash-report.txt)

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [X] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17 and 18

### Operating system

macOS Catalina 10.15.3

**Comment by Meng-Heng** [comment]
Topic: https://community.software.sil.org/t/keyman-isnt-working-with-macos-catalina/9096

**Comment by sgschantz** [comment]
Reported to Apple with Feedback Assistant: FB15049573 (CGPreflightPostEventAccess API crashes when called on macOS Catalina (10.15.3))
