### ISSUE TITLE
chore(android): Separate upload to Sentry as a publish step

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#12325]
Per @mcdurdin 
> we need to make 'release' builds for android not attempt to upload sentry, instead that should be done with a 'publish' step. another chore

**Comment by darcywong00** [comment]
@mcdurdin - are you requesting for this to be in a builder publish action that would **not** cover the following?

I'm checking the CI configs and see currently there's:
* publish to downloads.keyman.com (PowerShell)
* Publish to Play Store - Keyman and FirstVoices (a separate build-publish.sh script)

**Comment by mcdurdin** [comment]
I think publish should probably be responsible for all of these. Monday Design Discussion might be good -- for all platforms?

**Comment by darcywong00** [comment]
I spun off #12373 to handle the other publish steps.

The scope of this issue will stick with the Sentry step
