### ISSUE TITLE
feat: Support for User Defined Character Aliases

### ISSUE THREAD

**Issue by dyacob** [keymanapp/keyman#12335]
### Is your feature request related to a problem? Please describe.

Often when working with a group of non-letter symbols, particularly combining marks and other marks that lose clarity within quotes, I would like to create a name alias for the symbol to then reference later in a rule.

### Describe the solution you'd like

Something like:

```
store(Z_MWIXI) U+F012D
  ⋮
any(GroupA) + '5' > context Z_MWIXI
any(GroupA) Z_MWIXI + "u" > index(GroupU,1)
```

this is _much_ nicer than having to lookup a character code over and over while writing and later maintaining the keyboard.  This is ideal, but applying brackets is also acceptable, e.g. `[Z_MWIXI]` , but would need to work on the right side of `>`

While my desire is to create human-readable names for character codes, the approach proposed lends itself to be taken further where:

```
store(Z_MyString) 'Some String'

… >  context Z_MyString
```

The door would be open to this,  although I do not have a usecase for it at the moment.  Otherwise, KMD would need to enforce that the Z_ alias is limited to a single character.

### Describe alternatives you've considered

The U+XXXX... syntax, and quoting the symbols.  They both prove to be difficult to read and tedious to work with, slowing development work.

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [X] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

N/A

### Operating system

N/A

### Device

N/A

### Target application

N/A

### Browser

N/A

### Keyboard name

Any

### Keyboard version

Any

### Language name

Any

**Comment by mcdurdin** [comment]
This is supported already with [named constants](https://help.keyman.com/developer/language/guide/constants)

**Comment by mcdurdin** [comment]
> Beautiful, this will work perfectly as desired! I'm tickled to still be learning more of the keyman language after so many years, even relearning bits and pieces that I'd forgotten is a delight 😃

Yep, that's how I feel when I discover a feature I'd forgotten too 😆
