### ISSUE TITLE
bug(web): Regression in 17.0: the online OSK files have become ugly

### ISSUE THREAD

**Issue by LornaSIL** [keymanapp/keyman#12345]
Did the CSS change make the background characters bigger? Something has gone wrong:

https://help.keyman.com/keyboard/dene/2.1/dene
![image](https://github.com/user-attachments/assets/c3682044-43f1-444c-b2a2-2b1e281b2a0f)

I checked a few other pages and they are similar.
https://help.keyman.com/keyboard/athinkra_vai/1.3/athinkra_vai
![image](https://github.com/user-attachments/assets/a212de53-d163-481f-a346-b1d662ef27e3)

https://help.keyman.com/keyboard/coptic_greek/2.3/coptic_greek

**Comment by mcdurdin** [comment]
@ermshiperete we will need to review this issue this sprint if possible. It's a change in 17.0 release, and relates to the reasons we rolled help.keyman.com back to 16.0 (keymanapp/help.keyman.com#1278).

**Comment by mcdurdin** [comment]
Issues I can see here:

1. Font size on backing text
2. Font size on key cap
3. All caps on backing text
4. centered alignment of text on key cap
5. text size on space bar
6. frame keys probably should not be using icons
7. key spacing seems unnecessarily wide compared to previous version

Perhaps we need to roll it back to 16.x again? This seems inadequately tested.

**Comment by darcywong00** [comment]
Keyboard OSK should display fine with help.keyman.com reverting to 16.0 (keymanapp/help.keyman.com#1518).

Keeping this issue open as the team investigates a fix for 17.0
(The staging site https://help.keyman-staging.com is still on 17.0 can can be used for investigation)

**Comment by ermshiperete** [comment]
https://github.com/keymanapp/help.keyman.com/pull/1530 fixes this.

With that PR the letters on the key caps are slightly bigger.
