### ISSUE TITLE
bug(android): "Always show banner" has no effect

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/keyman#12376]
With the "Always show banner" option turned off, the banner will still show (with the Keyman logo), regardless of the "Enable predictions" setting for the current language, and regardless of whether or not a dictionary for the current language is installed.

If "Always show banner" is off, we shouldn't show the banner if a) "Enable predictions" is off, or b) there are no dictionaries installed for the language.

![Screenshot_2024-09-09-08-45-18-55_958d350bfbdeb289302c75fe5c4a9384](https://github.com/user-attachments/assets/5b965026-2246-4a29-958f-e451eabe8ab3)

**Comment by darcywong00** [comment]
ah yes - this came from 17.0 where there will always either be a suggestion banner or an image banner for the top-row longpress keys.

We can clarify the strings as part of revamping that menu in #12203
