### ISSUE TITLE
chore(windows): test ldml_test on windows

### ISSUE THREAD

**Issue by srl295** [keymanapp/keyman#12450]
It seemed like this test broke in VSCode ,although the `ABC`+8 test passed.

```
    <test name="key-8-osage">
      <startContext to="𐓏" />
      <keystroke key="8" />
      <check result="8:ctxt:OK" />
    </test>
```

https://github.com/keyman-keyboards/ldml_test and also in-repo

**Comment by srl295** [comment]
I tested using `testhost` on windows 11 (x64 debug), and all passed EXCEPT:

- 8:ctxt:OK (the ABC context)
- 𐓏8:ctxt:FAIL (non-BMP context - as reported in this issue)
- 𐒻𐒷8:ctxt:FAIL (split non-BMP context)

**Comment by srl295** [comment]
I also notice in VSCode that if i click after ABC and press <kbd>8</kbd> the test fails, but if I _type_ `ABC` and then press <kbd>8</kbd> it works. 

Does that mean VSCode is 'non compliant'?

**Comment by srl295** [comment]
OK, `testhost` also fails if you click next to ABC and type <kbd>8</kbd>.

> `ABC8:ctxt:FAIL`

I'll see if I can debug it.

**Comment by mcdurdin** [comment]
> OK, `testhost` also fails if you click next to ABC and type 8.
> 
> > `ABC8:ctxt:FAIL`
> 
> I'll see if I can debug it.. no, i'll need some help..

Shall we setup a rubber ducky session? I'll ping you on Slack

**Comment by srl295** [comment]
(copyback from slack:
 - vscode is noncompliant
 - testhost is noncompliant
Maybe WAD

**Comment by rc-swag** [comment]
> * testhost is noncompliant
>   Maybe WAD

Yes correct in non-compliant app the context is going to empty as you have pasted the text and not typed it therefore is working as expected. 
Update the test markdown to specify this test requires a compliant app, then we can close this issue?

**Comment by mcdurdin** [comment]
We should add a RICHEDIT (4.0+) to testhost, so we can do both compliant and non-compliant tests

**Comment by srl295** [comment]
> Update the test to specify

OK, I'll update the test source. It's not a formal test, the only 'call to action' was this issue, when I had noticed that VSCode was being seemingly erratic

> We should add a RICHEDIT (4.0+) to testhost, so we can do both compliant and non-compliant tests

Need an issue for that?

**Comment by mcdurdin** [comment]
Issue opened

**Comment by rc-swag** [comment]
Ok issue opened by Marc I have assigned to me for 19.0 let's close this.
