### ISSUE TITLE
bug(android): OSK appears in half-size when returning from portrait to landscape.

### ISSUE THREAD

**Issue by dinakaranr** [keymanapp/keyman#12460]
### Describe the bug

The keyboard appears on the half screen of the notepad. Or an error occurs on the toast message if I change keyman keyboard to Google keyboard

### Reproduce the bug

Steps to reproduce:

1. Installed the "Keyman-18.0.116.apk" file from the PR build and gave all permissions to the application.
2. Checked the "Enable Keyman as system-wide keyboard" and set the keyboard as the default keyboard box on the settings page.
3. Open the Keyman app.
4. Navigate to the systems page. Click the "Install Keyboard or Dictionary"
5. Click the "Install from keyman.com"
6. Click in the search box.
7. Turn the mobile view from portrait to landscape.
8. Type a word in the search box and then remove it.
9. Click the globe button. observed that the Google keyboard appeared.
10. Click the back button two times on the mobile.
11. Turn the mobile view from landscape to portrait.
12. Click the back button on the mobile.
Actual Results: Here, the keyboard appears on the half screen of the notepad. Or an error occurs on the toast message. 
Please refer to the screenshot for reference
<img width="300" src="https://github.com/user-attachments/assets/ff766a6d-5a45-449c-8e75-b03a45611a68">
<img width="300" src="https://github.com/user-attachments/assets/5e4d988e-80ab-41f3-8b87-459448252250">

https://github.com/user-attachments/assets/37df2475-750e-4f5e-9b38-4bd30fd86915

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

18.0.118

### Operating system

Android 14

**Comment by darcywong00** [comment]
> Installed the "Keyman-18.0.116.apk" file from the PR build

@dinakaranr - Which PR build were you using when you saw the issue?

**Comment by dinakaranr** [comment]
I tested this issue in the "18.0.116-alpha" CI build(downloaded from Keyman's status board). I reproduced it today too. Thank you.

**Comment by darcywong00** [comment]
Haven't been able to repro the issue. Will close and can re-open if people see it again
