### ISSUE TITLE
bug(developer): kmc-ldml, marker names `\m{my-marker}` should be flagged as invalid

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#12467]
Split from #12451.

For extra credit, add a test for empty variable id in tests added in #12451.

**Comment by srl295** [comment]
By 'empty' does that mean `${}` ?

**Comment by mcdurdin** [comment]
> By 'empty' does that mean `${}` ?

Yes, but also in the `<variables>` definitions themselves.
