### ISSUE TITLE
bug(common): common-types has undeclared dependency on ldml

### ISSUE THREAD

**Issue by srl295** [keymanapp/keyman#12470]
### Describe the bug

when importing `@keymanapp/common-types` (current stable, 17.x) I get this err

```
node_modules/@keymanapp/common-types/build/src/kmx/kmx-plus.d.ts:161:22 - error TS2307: Cannot find module '@keymanapp/ldml-keyboard-constants' or its corresponding type declarations.

161     get id(): import("@keymanapp/ldml-keyboard-constants").SectionIdent;
```

### Reproduce the bug

```shell
npm i @keymanapp/common-types
```

```js
import * as kct from '@keymanapp/common-types';

console.dir(kct.Constants.CLDRScanToKeyMap);
```

### Expected behavior

successful compile

### Related issues

#12426

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [x] Other - give details at bottom of form

### Keyman version

@keymanapp/common-types@17.0.330

### Additional context

worked around by `npm i @keymanapp/ldml-keyboard-constants`

**Comment by mcdurdin** [comment]
Note: this is not a problem in 18.0 because @keymanapp/ldml-keyboard-constants has been merged into @keymanapp/common-types
