### ISSUE TITLE
feat: Register Keyman App Fonts with System

### ISSUE THREAD

**Issue by dyacob** [keymanapp/keyman#12493]
### Is your feature request related to a problem? Please describe.

The Keyman mobile app is able to display fonts that are included with a KMP file, unfortunately, as it is well known, the fonts are not available to other apps. Mobile operating systems also prevent installation of fonts into system folders.

### Describe the solution you'd like

Keyman would register its font directory with the mobile OS, or register individual fonts as the OS APIs require. Thus the keyman fonts become available system-wide for other apps to utilize.

This would be simple in X11 :-)  I've noticed Adobe and Monotype sell fonts for iPhone and Android, so I believe there must be available APIs to make fonts available to the OS.

### Keyman apps

- [X] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

Any

### Operating system

Android, iOS, iPadOS

### Device

mobile phone, tablets

### Target application

N/A

### Browser

N/A

### Keyboard name

Any

### Keyboard version

Any

### Language name

Any

**Comment by mcdurdin** [comment]
* For iOS, this is tracked at #3445. We are planning to do this in v18.
* For Android, this is not possible because Android does not allow system installation of fonts.

**Comment by mcdurdin** [comment]
Note: tracking this in a new issue now at #12658.
