### ISSUE TITLE
chore(core): Deprecate `km_core_keyboard_load`

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/keyman#12497]
#12459 added the new core API method `km_core_keyboard_load_from_blob`. Once we changed the engines to use the new method we should add the deprecated flag to `km_core_keyboard_load`.

- [x] #12498
- [x] #12499
- [x] #12500
- [x] #12690
- [ ] remove `km_core_keyboard_load` and ensure no filesystem/IO libs are linked in to kmcore

**Comment by mcdurdin** [comment]
Added WASM TODO item

**Comment by ermshiperete** [comment]
Needs to happen after the Linux/Mac/Windows subtasks are done.

**Comment by mcdurdin** [comment]
Note: once mac work is done (#12499), we can remove the filesystem code entirely from Core, rather than #ifdef or deprecation of the API. This will be much cleaner!

**Comment by mcdurdin** [comment]
As we are so close to getting this finished, brought it back to milestone 18.0.
