### ISSUE TITLE
[linux] issues with copying installed kmp directories

### ISSUE THREAD

**Issue by glasseyes** [keymanapp/keyman#1250]
afaiu the plan is to be able to copy a directory of an unpacked kmp to another users system, like via a sdcard/usbstick, and for it to just work.

(1) if it is copied to an arbitary place on the 2nd users system then we want a way in the gui to install the directory to the right place. Maybe to select the directory on the 'sdcard'

(2) even if it is put directly in /usr/local/shared/keyman or ~/.local/share/keyman the fonts that come in the kmp won't be installed. So want a way to check and fix installed kmp.

**Comment by glasseyes** [comment]
Adding alternative local install method. The file selector will be able to select a kmp.json in a directory. It will copy and process the files from that directory.

**Comment by darcywong00** [comment]
I think it's preferable to have them zip up the directory into a .kmp and pass that around.

**Comment by glasseyes** [comment]
Fine by me so this issue is irrelevant
