### ISSUE TITLE
bug(developer): wordlist pasted into Design tab doesn't display

### ISSUE THREAD

**Issue by DavidLRowe** [keymanapp/keyman#12517]
### Describe the bug

When creating a wordlist (especially after creating a new lexical model project), a person might choose to delete the sample English entries and paste in words and frequencies from the target language. If this is done in the "Design" tab, the pasted data do not display (until switching to the "Code" tab and back, or closing and reopening the project).

### Reproduce the bug

1. Create a new lexical model project
2. Click on the "wordlist.tsv" tab
3. Delete the English sample words and frequencies
4. Paste in data from another .tsv file. Observe that nothing displays until you switch to "Code" and back to "Design"

### Expected behavior

In step 4, when data is pasted into the file, the expectation is that it should display.

### Related issues

Possibly related to #6430 in that the solution (of switching to the Code tab) is similar. (Or perhaps when addressing this issue, a solution for #6430 will also be possible.)

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [X] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.330

### Operating system

Windows 11

**Comment by mcdurdin** [comment]
This is a by-product of paste not actually supporting multiple rows in the grid editor. What is happening is that the text is all being pasted into the first cell, newlines, tabs, and all. When you switch to code view, that transfers the text in all the cells into the code source, and then when you switch back, the tabs and newlines are of course parsed out correctly.

The correct fix here is probably to adapt the editor to detect tabs and newlines in the clipboard, and offer to insert the content as new records if found.
