### ISSUE TITLE
bug(windows): The "Hotkeys" pane does not display the keyboard for the installed language.

### ISSUE THREAD

**Issue by dinakaranr** [keymanapp/keyman#12549]
### Describe the bug

The Aramaic keyboard name does not appear with the installed language.

### Reproduce the bug

Steps to reproduce:

1. Installed the "keyman-17.0.330.exe" file. 
2. Keyman keyboard added in the system tray.
3. Open the keyman "Configuration" window.
4. Navigate to the "Keyboard Layouts" tab. 
5. Installed the "Aramaic" keyboard by clicking the "Download keyboard" button.
6. Click the "Add/Remove language" button to open the dialog.
7. Remove the installed language by clicking the "X" button.
8. Add another language (Syriac) by clicking the "Add language" button and then closing the dialog.
9. Navigate the "Hot Keys" pane.
Actual Results: The Aramaic keyboard name does not appear with the installed language.
https://github.com/user-attachments/assets/d0ab2c93-2e1c-4df7-aa85-939ae7ba8665

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [X] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.330 stable version from keyman website

### Operating system

Windows 10 OS

### Keyboard name

Aramaic, Imperial aramaic

**Comment by rc-swag** [comment]
@dinakaranr, as shown with the sequence in the attached video the the Aramaic keyboard name does not appear in the HotKeys tab, intially. The reason is to do with the way the Windows registry look-up is cached. Closing the configuration and opening it again, then going to the HotKey tab the Aramaic keyboard and language appear in the list.
