### ISSUE TITLE
[Windows] (Compatibility) Backspace in Edge deletes diacritics + base together

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#1254]
Edge deletes diacritics and base characters together in some scripts (tested so far with Khmer). For example, with khmer_angkor keyboard, typing xjmEr gives ខ្មែរ and five backspaces should delete it all. But in Edge, only 3 backspaces deletes it all, and not in the expected groupings either:

Start with ខ្មែរ.
Bksp: ខ្មែ
Bksp: ខ្
Bksp: empty string

See also:
* [Similar issue with Firefox](https://github.com/keymanapp/keyman/issues/889)
* [Feedback Hub report](https://aka.ms/AA2s88e)

**Comment by mcdurdin** [comment]
How to help:
* Read our blog [How to send feedback to Microsoft for issues that impact Keyman](https://blog.keyman.com/2018/10/how-to-send-feedback-to-microsoft-for-issues-that-impact-keyman/)
* Then upvote the [Feedback Hub entry](https://aka.ms/AA2s88e)

**Comment by mcdurdin** [comment]
This appears to have been resolved as of Windows 10 build 18290.rs_prerelease.181121-1501 (insider fast ring).

**Comment by mcdurdin** [comment]
New Chromium-based Edge does not have this problem. Can close this once that hits release and distribution is wide enough.

**Comment by darcywong00** [comment]
Another user reports this compatibility issue with Edge (and Windows 10 Start menu search bar)

> When I type into the Edge search bar (or the Windows 10 Start menu search bar, for that matter) using the Rvwangu7 keyboard, I see this:
![edge](https://user-images.githubusercontent.com/7358010/66821640-f5272300-ef6c-11e9-9a98-9a229f62660a.jpg)

> What I typed was "rvwàng kàí èruò we nø." Similarly, with the SIL Myanmar 3 Keyboard, I get only Roman letters. 

### Configuration
Keyman 11.0.1361.0 Desktop
Windows 10, Version 1903
Microsoft Edge (version not provided)

**Comment by mcdurdin** [comment]
@darcywong00 I wonder if that is a separate issue of Keyman not being activated for Modern UI contexts. Capturing a debug log may be sufficient to tell us if that is the issue (we'd see errors from Modern UI app in the log instead of the expected load of the keyboard). It may well be the `ALL APPLICATION PACKAGES` permission on %ProgramData%\Keyman` folder, which should be (Read & Execute, List folder contents and Read).

**Comment by mcdurdin** [comment]
@darcywong00 see also #1680 and related links.

**Comment by mcdurdin** [comment]
Closing this as new Chromium-based Edge has been released and legacy Edge will no longer receive updates.
