### ISSUE TITLE
bug(windows): extra tags associating with the Pashto (Afghanistan) Basic keyboard

### ISSUE THREAD

**Issue by Meng-Heng** [keymanapp/keyman#12547]
### Describe the bug

> This hasn’t happened before where it’s added more languages, but there may perhaps be a different related problem: I downloaded the Pashto (Afghanistan) Basic keyboard (through that same method, using the link in the “Download Keyboard” button at the bottom of the Keyman Configuration window) and it came in as a keyboard under “English” language instead of Pashto language. I just checked the windows settings and it indeed shows “Pashto (Afghanistan) Basic” as a keyboard in the English Language area. There is also a Pashto language area in windows settings (I suppose it got added when the keyboard got installed?) but no keyboard is selected there.

This was only happening as the topic and was able to produced once in the topic, but was **not** reproducible on Windows 10. Any clarification on this issue would be appreciated. Thank you!

### Expected behavior

Correctly associating the language with the keyboard.

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [X] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.330

### Operating system

Windows 11 Pro 23H2

### Keyboard name

[Pashto (Afghanistan) Basic keyboard](https://keyman.com/keyboards/basic_kbdpash)

### Keyboard version

1.1

### Language name

Pushto

### Additional context

Source: https://community.software.sil.org/t/installed-multiple-unwanted-keyboards-fixed/9193
Diagnostic report: https://community.software.sil.org/t/diagnostic-report-from-christopher-fiorello/9216

> [!Note]
> The issue is resolved by removing the unwanted tag.

**Comment by rc-swag** [comment]
Unfortunately, this is due to the transient language limit being reached, so it instead installs it with the systems default language. The reason it would not of been able to be reproduced is because the test machine most likely had not reached the transient language limit. Currently, the only option for the user is to uninstall one of the languages using a transient language ID if they no longer are using that language.

**Comment by Meng-Heng** [comment]
Thank you, @rc-swag!
