### ISSUE TITLE
bug(developer): The debugger does not stop it when using the Shift+F5.

### ISSUE THREAD

**Issue by dinakaranr** [keymanapp/keyman#12569]
### Describe the bug

Debugger mode does not stop it, and the keystroke appears in the empty text box or "keystroke log" box.

### Reproduce the bug

Steps to reproduce:

1. On Keyman Developer, navigate to the "Keyboard" tab and then click the *.kmn link button to navigate to the build tab.
2. Click the "Complie Keyboard" button.
3. Click the "Start Debugging" button or Press the F5 key.
4. Debugger mode was opened
5. Press the a,b,c, and e keys in an empty box.
6. Stop the debugger mode by pressing the SHIFT+F5.
Actual Results: Debugger mode does not stop it here, and the keystroke appears in the empty text box or "keystroke log" box.
<img width="300" src="https://github.com/user-attachments/assets/f1977fc5-3321-4e19-84a6-eb174d991145">

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [X] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.330 stable version from keyman website

### Operating system

Windows 10

**Comment by mcdurdin** [comment]
This is by design; you can press Shift+F5 while in the editor, or when the debugger is paused. Otherwise Shift+F5 is sent to the keyboard.
