### ISSUE TITLE
feat: I request to set a Chinese Character Typing system in Keyman

### ISSUE THREAD

**Issue by Cathaylaboratory** [keymanapp/keyman#12563]
### Is your feature request related to a problem? Please describe.

I request a chinese character or Kanji typing system in Keyman on all platforms and keyman developper

It will have a small window on the screen to show the candidate characters, the window can show from 0 to 9 candidates depends our setting, the window will move forward and downward along side the cursor.

When I am typing chinese characters or Japanese Kana in the Keyman, I can type the numbers or type the TAB or type page up and page down to scroll up and down and select letters. When I scroll the page down, the kana or pinyin will transfered to the selected Kanji candidate. If I type the number key which matches the mark of candidate, it will also transfer the Kana to Kanji.

On the phone and tablet, we will use the lexical model window to show those Kanji or characters.

I recommend we can have an excel file to store all those characters. For example in one row, a data can be like " Kanji TAB Kana TAB frequency (from 0 to 1000 or from 0 to 10000) "The Kanji with higher frequency will come out at first. The file can be compiled with in the KPS file.

The code can also be stored like this  "abc" = { " A "  , " B " , " C " }, and store the code directly in the KMN if you want to simplifier the coding and lexical model building process, the A B and C will come out in the ABC order.

The "abc" here is the pinyin or Kana input or conscequences, and A, B and C here is the characters which matched pinyin or Kana "abc"

I recommend you try the Rime IME keyboard at first. 

https://rime.im/download/

### Keyman apps

- [X] Keyman for Android
- [X] Keyman for iPhone and iPad
- [X] Keyman for Linux
- [X] Keyman for macOS
- [X] Keyman for Windows
- [X] Keyman Developer
- [X] KeymanWeb
- [ ] Other - give details at bottom of form

### Language name

Chinese, Japanese, Taiwanese, Cantonese, Wu, Vietnamese, Korean

**Comment by mcdurdin** [comment]
This relates to #7928. I will close this and we can track the suggestions there.
