### ISSUE TITLE
bug(mac): Configuration closes after downloading a keyboard

### ISSUE THREAD

**Issue by Meng-Heng** [keymanapp/keyman#12568]
### Describe the bug

1. Successfully downloads a keyboard.
![image](https://github.com/user-attachments/assets/43c537c0-7288-4eb2-b254-bce749c71c34)
2. The Window above disappears when clicking Done. But, the keyboard is downloaded.

### Reproduce the bug

1. Go to Configuration... 
2. Click Download keyboard... 
3. Get Cameroon Azerty or any keyboard
4. Downloads successfully
5. Click Done. 
6. The Configuration closes.

### Expected behavior

The Configuration should stay open after a keyboard download.

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [X] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.330

### Operating system

macOS Sonoma 14.6

### Device

Macbook Pro

### Additional context

Reopen Configuration... shows the Package information as well:
![image](https://github.com/user-attachments/assets/f8920a75-4f01-4e67-97c5-ed607d6bb769)
![image](https://github.com/user-attachments/assets/827924c9-ea8d-442e-8d76-9637ffa59dc1)

**Comment by sgschantz** [comment]
@Meng-Heng can you try this with 18? I believe I fixed it here: #12326 and I was not planning to cherry-pick this back to 17.

**Comment by Meng-Heng** [comment]
Is it the `Keyman version 18.0.104-alpha`? I will check it out.

**Comment by sgschantz** [comment]
@Meng-Heng To test the fix, use the build of Keyman attached to the PR or a later build after the PR has been merged. Please close this issue if you cannot reproduce with 18.

**Comment by Meng-Heng** [comment]
The bug is fixed. Thank you.
