### ISSUE TITLE
bug(linux): AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer

### ISSUE THREAD

**Issue by alkaris2** [keymanapp/keyman#12587]
### Describe the bug

When trying to access Downloads for Keyman, I get the following error on loop;

```
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
```

As as result of this you are unable to access the Downloads page for keymaps from within the app. However after a bit of digging around on the Internet this is easily fixed by setting `WEBKIT_DISABLE_DMABUF_RENDERER=1` into the environment.

If you have NVIDIA GPU this is apparently an issue. You could probably just completely disable the WebKit DMABUF Renderer from Keyman to remedy this issue completely.

See: https://github.com/SpikeHD/Dorion/issues/237 
Fix Solution: https://github.com/tauri-apps/tauri/issues/9304#issuecomment-2028409103

### Related issues

WebKit2Gtk: https://gitlab.archlinux.org/archlinux/packaging/packages/webkit2gtk/-/issues/1

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [X] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

km-config version 16.0.144-local

### Operating system

Manjaro Linux 24.1.1

**Comment by ermshiperete** [comment]
@alkaris2 Thanks for your bug report and suggested workaround! Will be available in the next version on both 18 (alpha) and 17 (stable) branch.
