### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#1260]
I have downloaded the master copy.

I am getting error with make build

Please assist

**Comment by darcywong00** [comment]
Can you verify you've done all the prerequisite steps in this [README](https://github.com/keymanapp/keyman/blob/master/windows/src/README.md)?

Note there's a section for
[Build Prerequisites](https://github.com/keymanapp/keyman/blob/master/windows/src/README.md#build-prerequisites)

and another one for
[Detailed Prequisite Notes](https://github.com/keymanapp/keyman/blob/master/windows/src/README.md#detailed-prerequisite-notes).

**Comment by MayuraVerma** [comment]
This is resolved.
Thanks to all.
