### ISSUE TITLE
[Windows] When SK_UIFontName is specified, strings come up in blue for characters missing from the font

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#1263]
If a specified font in `SK_UIFontName` does not contain characters in a given UI string (e.g. in the Keyman menu), then those strings appear in blue. This is helpful for development but not good for final end use.

![image](https://user-images.githubusercontent.com/4498365/47051973-441f6880-d1f2-11e8-807b-c1df2786d2e1.png)

**Comment by MayuraVerma** [comment]
This is resolved in this pull request -> https://github.com/keymanapp/keyman/pull/1609
