### ISSUE TITLE
bug(linux): disable constant event logging unless logging turned on

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/keyman#12661]
We shouldn't log all keystrokes unless logging is explicitly turned on, otherwise it's kind of a key-logger which isn't desirable from a security perspective.

**Comment by mcdurdin** [comment]
@ermshiperete wrote:

> That's pretty bad because it's done in Core where we enable logging if `g_debug_KeymanLog` is true, and we [initialize it with that](https://github.com/keymanapp/keyman/blob/21d8c35900990aaa595dc94b1c35a59a3f11ff2d/core/src/kmx/kmx_processevent.cpp#L15). There's no API to change that variable and can only be done in the debugger or at compile time. The issue doesn't show up on Windows because there we always log to `std::cout` regardless of the value of `g_debug_ToConsole`, but on Linux we log to syslog.
>
> I think it would be beneficial if the user could enable logging so that he can send us a log if he runs into problems, but for that I think we'd need an API that the engine could call on Core. 

Yes, that sounds appropriate. We'll address it in the 18.0 cycle. I think we should do a stop-gap of disabling the flag for release builds I think for 17.0 and 18.0 alpha.

It seems weird that we log via `std::cout` for windows anyway -- that's never helpful -- and in some cases may be seriously detrimental. How does this mesh with logging via ETL (@rc-swag)?

What are we doing on macOS (@sgschantz)?

**Comment by ermshiperete** [comment]
Closing this. Further work will be tracked in #12703 and child items.
