### ISSUE TITLE
[keyman.com] Source link on keyboard page is wrong

### ISSUE THREAD

**Issue by LornaSIL** [keymanapp/keyman#1267]
On keyboard pages, such as this one: https://keyman.com/keyboards/inuktitut_naqittaut
The source link has recently acquired the wrong url which does not take anyone to the proper place:
```https://keyman.com/keyboards/GITHUB_ROOTrelease/i/inuktitut_naqittaut```
This part is wrong ``````https://keyman.com/keyboards/GITHUB_ROOT```

It used to be:
```https://github.com/keymanapp/keyboards/tree/master/release/i/inuktitut_naqittaut```

which does work.

**Comment by mcdurdin** [comment]
@darcywong00 This looks like it happened with the recent refactor of the keyboard pages that you did? Can you look into this?

**Comment by darcywong00** [comment]
Issue moved to sillsdev/keyman-keyman.com#199
