### ISSUE TITLE
CTRL + Backspace not deleting word

### ISSUE THREAD

**Issue by Nukiver** [keymanapp/keyman#12764]
Hello, I'm trying to delete a word with CTRL + Backspace, but that doesn't seem to work. 
Skipping around words with CTRL + Left or CTRL + Right works. CTRL + DEL works aswell to delete the word in front, but CTRL + Backspace should be deleting the word that comes before. I demonstrate this here: First I try with my normal german keyboard, and then with the mnemonic one. You can see, that I am deleting letter by letter of the word "слова" even though I am pressing ctrl.
![Image](https://github.com/user-attachments/assets/9b55f54c-0ec3-4411-9519-1f12b81ee104)

**Comment by mcdurdin** [comment]
I'm going to go ahead and close this issue as we don't have enough information to replicate the problem. Please feel free to re-open if you can give us more detail on your environment as requested above.
