### ISSUE TITLE
[Windows] Unable to assign "raw" tag to Rawang Unicode 7 keyboard

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#1282]
Reported from a user trying to install and assign a legacy Rawang (BCP 47 tag "raw") desktop keyboard.

## Configuration
Windows 10
Keyman Desktop 10.0.1203
[Rawang Unicode](https://keyman.com/keyboards/rawangu7) Keyboard

The keyboard installs, but shows up in Keyman Desktop under "English"
![image](https://user-images.githubusercontent.com/7358010/47485841-35c3f300-d869-11e8-8f2c-ad126ef035a3.png)

Then from Keyman Configuration --> Add Language to Keyboard
I can't find "Rawang" or "raw" or "raw-Latn" or "raw-MM"

Also seen in Keyman Desktop 11.0.53.0

**Comment by darcywong00** [comment]
The compatibility issue is because Flex 8.3.12 didn't see the Rawang keyboard in Desktop 10 as an available keyboard.

When the user rolled back to Desktop 9, he was able to use the keyboard in Flex 8.3.12

**Comment by darcywong00** [comment]
I'll follow-up to see if this is a duplicate of #1285

**Comment by mcdurdin** [comment]
See also #1719

**Comment by mcdurdin** [comment]
See also https://github.com/keymanapp/keyman/issues/3485#issuecomment-684082010
