### ISSUE TITLE
bug(developer): why does `dpGroupArray` start at a 16-bit boundary in a KMX file?

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/keyman#12844]
Keyboard loading from blob in Keyman for Web caused test failures where tests failed with `Aborted(alignment fault)`. I tracked this down to `KMX_ProcessEvent::FixupKeyboard` where it happens when we write the pointer into `kbp->dpGroupArray`. It turns out that `kbp->dpGroupArray` starts at a 16-bit boundary, but Emscripten wants 32-bit boundaries and aborts the process if `SAFE_HEAP=1` is set. 

32-bit on Linux and Windows seem to ignore the alignment when writing to memory, although `__alignof__(uint32_t)` also returns 4, i.e. 32-bit boundary.

Looking at the data structures in `kmx_file.h` and at the documentation in [kmx-file-format.md](https://github.com/keymanapp/keyman/blob/master/docs/file-formats/kmx-file-format.md) I find it fairly surprising that the group doesn't start at a 32-bit boundary since we use 32-bit values everywhere. So I guess there is a string in between that can cause this mis-alignment.

I'm also wondering if it would be better to move the pointers to proper alignment even on 32-bit.

For Emscripten I'm working around the problem by calling `KMX_ProcessEvent::CopyKeyboard` instead of `KMX_ProcessEvent::FixupKeyboard`.

Observed with several keyboards, e.g. `common/test/keyboards/baseline/k_000___null_keyboard.kmx`.

**Comment by mcdurdin** [comment]
> Looking at the data structures in `kmx_file.h` and at the documentation in [kmx-file-format.md](https://github.com/keymanapp/keyman/blob/master/docs/file-formats/kmx-file-format.md) I find it fairly surprising that the group doesn't start at a 32-bit boundary since we use 32-bit values everywhere. So I guess there is a string in between that can cause this mis-alignment.

The file is packed data, not a memory mapped structure. On x86, alignment was pretty flexible, so the original design did not attempt to streamline this. You already discovered the fixup for 64 to allow us to drop in 64-bit pointers.

> I'm also wondering if it would be better to move the pointers to proper alignment even on 32-bit.

We will always need the ability to load older files which are not aligned, so there is no real benefit in changing the file format or compiler, IMO -- we'll still need the fixup code, as you used in #12845.

I will go ahead and close this for now as wontfix but feel free to reopen if you feel strongly about this.

**Comment by ermshiperete** [comment]
#12856 tries to improve the docs to clarify that the sections don't always start at 32-bit boundaries.
