### ISSUE TITLE
[Android] Move keyboard updates into a background async process

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#1316]
From PR #1301 @mcdurdin writes:
> Long term we need to move updates into a background async process that uses
system notifications or similar to let user accept them with minimum of
interference.

--------
Some possibilities with the Android app

* Have the app icon show a notification dot when a keyboard update is available
* In the keyboards list, have some way to notify which keyboard update is available

**Comment by darcywong00** [comment]
As of Android API 26, the use of `ProgressDialog()` is also deprecated in favor of `ProgressBar` or background notifications.

**Comment by darcywong00** [comment]
For initial task, update KMKeyboardDownloaderActivity to use one of the Download Managers from the [reference](https://developer.android.com/guide/background) on background info processing

**Comment by safolit** [comment]
Flow chart showing the processes implemented.
[keyboard_download_diagram.pdf](https://github.com/keymanapp/keyman/files/3792078/keyboard_download_diagram.pdf)
