### ISSUE TITLE
[iOS] Move keyboard updates into a background async process

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#1317]
From PR #1301 @mcdurdin writes
> Long term we need to move updates into a background async process that uses
system notifications or similar to let user accept them with minimum of
interference.

**Comment by jahorton** [comment]
This is highly related to #199 and a possible duplicate.

**Comment by mcdurdin** [comment]
> This is highly related to #199 and a possible duplicate.

Agree. Closing, we have the link now between these issues.
