### ISSUE TITLE
[common] For kpapi, `experimental/filesystem` is not supported on mac (without a lot of fudging around).

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#1341]
_Originally posted by @mcdurdin in https://github.com/keymanapp/keyman/pull/1326/comment#issuecomment-441336670_

We probably should avoid using it because we don't want to have to depend on setting up non-XCode environment for Keyman for Mac at this time. It's a shame but making this change earlier will save us cross-platform pain later.

See also alternative solutions found at https://github.com/potree/PotreeConverter/issues/260

**Comment by mcdurdin** [comment]
After discussion, have decided to use native string type (wchar_t) and pass a filename that needs no additional munging to resolve this.

**Comment by glasseyes** [comment]
is this to be closed with #1427 ?

**Comment by mcdurdin** [comment]
> is this to be closed with #1427 ?

Yes
