### ISSUE TITLE
[common] KMX processor needs to emit KM_KBP_IT_PERSIST_OPT

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#1345]
The KMX processor saves options to the KPAPI option store but does not tell the client to persist the saved option.

**Comment by keyman-server** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Common] KPAPI KMX processor does not emit KM_KBP_IT_PERSIST_OPT](https://trello.com/c/VO41ad59/1010-common-kpapi-kmx-processor-does-not-emit-kmkbpitpersistopt)

**Comment by mcdurdin** [comment]
Already resolved with options refactor
