### ISSUE TITLE
[Linux] Keyman for Linux addresses downloads.keyman.com directly rather than querying an API

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#1373]
> 
> This should be built by querying the keyboard downloads API (e.g. https://downloads.keyman.com/api/keyboard/1.0/khmer_angkor). There should be no need to construct a URL to a KMP manually.

OK, I've changed it to use that API

> > The bash completion scrapes a list of keyboards from https://downloads.keyman.com/keyboards/
> 
> The list of keyboards available can be queried from `https://api.keyman.com/search/?q=<searchstring>&platform=linux`. That's a bit of a noisier API and we don't currently support a flat list of all keyboard packages via either the downloads APIs or the api.keyman.com endpoints. We could build this if we really need it.
> 
> The main thing we need to avoid is building functionality into the apps that enforces a site structure outside what we publish as APIs.

I think that is a good idea, but there isn't an API that works for that functionality yet.
The script aborts cleanly if it can't find https://download.keyman.com/keyboards
It could get confused if that page changes.
I think this should be a separate issue with another PR so that this one can go through.

_Originally posted by @glasseyes in https://github.com/keymanapp/keyman/pull/1360#issuecomment-443598189_

**Comment by glasseyes** [comment]
`https://api.keyman.com/search?q=l:*&platform=linux` worked. PR to follow.
