### ISSUE TITLE
[Developer] Can't paste (Ctrl + V) into Developer's find/replace box

### ISSUE THREAD

**Issue by erros84** [keymanapp/keyman#1382]
For some reason, no matter what keyboard I use (Micoroft or Keyman), Ctrl C, Ctrl X, and Ctrl+V don't work in the Find dialogue Box or the Replace dialogue. I haven't noticed this in other areas.

As a workaround, right-click>paste and so on does work.

Developer 10.0.1113.0

**Comment by mcdurdin** [comment]
The Find/Replace dialogs have been replaced in Keyman Developer 11 (see latest alpha at https://keyman.com/alpha). I have tested and clipboard operations work there.

**Comment by erros84** [comment]
Thanks. Does Dev 11 have a full installer yet? Or does it require a development environment?

**Comment by mcdurdin** [comment]
Alpha installers are available at https://keyman.com/alpha
