### ISSUE TITLE
[iOS] Language duplication in keyboard download menu

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#1386]
Related to #1275, where this occurred for KeymanWeb.

Since we're now using BCP-47 codes to represent languages, it's quite possible for more than one language code to map to a single keyboard or language.  For example, `fr` vs `fr-ca`, the latter of which adds a specific locale.  The language picker menu will display a language once for each such BCP-47 code corresponding to it, with no real indication of which option corresponds to what code - not even the backing BCP-47 code.

![image](https://user-images.githubusercontent.com/25213402/49490501-eec31780-f882-11e8-9371-e9cb6ebe80b9.png)

In the example above, the first "French" option has far fewer options than the second - a little investigation reveals that the first corresponds to `fr-ca` and the second to `fr`.

Some UI improvements (at minimum) are needed to prevent this issue from impeding the user experience.

**Comment by darcywong00** [comment]
on Android too

![screenshot_20181205-125759](https://user-images.githubusercontent.com/7358010/49493197-b5dc7000-f88d-11e8-8047-5edbb796c563.png)

**Comment by mcdurdin** [comment]
This is most likely addressable on api.keyman.com. If a language has a script or region subtag, then append the `(Region)` or `(Script)`, or `(Script, Region)`. For example `French (Canada)`, `Italian (Khmer, Mexico)`

**Comment by darcywong00** [comment]
Now that api.keyman.com is updated to append (Script, Region) info, this can be closed.

Screenshot from Keyman for Android 11.0.47 alpha

![screenshot_20181221-145428](https://user-images.githubusercontent.com/7358010/50331339-e3354900-0530-11e9-8352-fb653f37875d.png)

**Comment by jahorton** [comment]
Fix confirmed on iOS.
