### ISSUE TITLE
[Developer] ethnologue directory doesn't exist when updating character database

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#1420]
While updating from Developer 11.0.64 to 11.0.76
Encountered the following prompts about "Updating Character Database".

![image](https://user-images.githubusercontent.com/7358010/49842999-36e8b980-fdf0-11e8-8a0b-48a881e48136.png)

**Comment by mcdurdin** [comment]
ethnologue.txt is missing from the distribution (note that if it isn't in the unicodedata source path -- normally the Keyman Developer program path -- then it looks in `..\ethnologue\` for the file).

However, the code that uses the ethnologue data has already been removed. So the correct fix for 11.0 is to remove the dependency on ethnologue.txt.

This needs to be resolved with 11.0.
