### ISSUE TITLE
Fill in the OSK from the layout

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#145]
![fill from layout -not working](https://user-images.githubusercontent.com/28331388/29062930-e3813e36-7c4d-11e7-8846-54d071ab25a2.PNG)

Not sure if this is just for me, but the 'fill from the layout' function keeps me waiting forever. Not sure if this is a 'bug'.

**Comment by MakaraSok** [comment]
I experience this behavior when working on [khmer_angkor.zip](https://github.com/keymanapp/keyman/files/1210741/khmer_angkor.zip). You may try it out.

**Comment by mcdurdin** [comment]
Issue occurs on Version <= 10.0.926.0. Not tested on 10.0.926.0 yet but probably not addressed.
