### ISSUE TITLE
Language chooser in Keyman doesn't jump to F.

### ISSUE THREAD

**Issue by erros84** [keymanapp/keyman#1455]
This was an odd one, and should be an easy fix but I can't find the relevant code to point to it. On the Language chooser for KM 11 (and probably 10), you can't jump to **F**. There must be an HTML anchor missing.

![image](https://user-images.githubusercontent.com/986339/50258557-3cd13280-03ce-11e9-98f1-b8d2cd41588a.png)

**Comment by darcywong00** [comment]
Thanks for reporting this. 

Curiously, "F" works from a browser
https://keyman.com/keyboards?embed=windows

This will be tracked in our websites repo as sillsdev/keyman-keyman.com#233

**Comment by erros84** [comment]
It doesn't work in Internet Explorer (but does in Chrome and Edge)...maybe that's a hint.

**Comment by erros84** [comment]
Q is also broken in Internet Explorer and Keyman.

**Comment by erros84** [comment]
@darcywong00  #F might be a reserved word in Jquery. 
https://stackoverflow.com/questions/14819910/what-doen-f-mean-in-jquery-scripts

**Comment by darcywong00** [comment]
@mcdurdin found the culprit
> There is a form named “f”. Hidden but still there. Oops :)

The fix is live, so your search in Keyman Desktop should work (and in IE)

**Comment by erros84** [comment]
Confirmed.
