### ISSUE TITLE
[Android] The 'info' window displays a NULL version number.

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#147]
![image](https://user-images.githubusercontent.com/25213402/29102573-53bc2b70-7ce4-11e7-8d61-e12575537f71.png)

When a user goes to view the app's info, it first loads this page and then loads the relevant help.keyman.com site.  However, upon hitting the 'back' button to return to the app, the user sees this page until they hit 'back' a second time.  Either this page should be automatically skipped and left unseen, or we should probably get the current version number into that location.

**Comment by darcywong00** [comment]
Adding another data point.  the current 2.7 alpha build displays the version
![keyman alpha version](https://user-images.githubusercontent.com/7358010/29155564-2e57d10c-7dc7-11e7-8542-7852bdde3df1.png)

**Comment by darcywong00** [comment]
Released builds properly set the version number.

As part of #588 , the local engineering builds now have a version `10.0.0.0`.
