### ISSUE TITLE
[iOS] Language (Keyboard) missing from spacebar for designed touch layouts.

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#1472]
We've had a long-running practice of displaying the active language and keyboard for the user in some manner on our OSKs.  Typically, with KeymanWeb and the mobile apps, we've been using the spacebar for this, as seen with the default-layout keyboard below:

![image](https://user-images.githubusercontent.com/25213402/50621652-beca6b00-0f39-11e9-81bd-d0306dd874a6.png)

However, at least within the iOS app (beta 11.0.200), this is missing - and _only_ for keyboard designer-specified touch layouts.  Auto-generated layouts based on desktop usage are not affected.

![image](https://user-images.githubusercontent.com/25213402/50621625-96db0780-0f39-11e9-99e6-f84bb74f8b61.png)

**Comment by darcywong00** [comment]
Also seen with Khmer Angkor keyboard on Keyman for Android 11.0.2050 beta
![khmer angkor](https://user-images.githubusercontent.com/7358010/50621817-11585700-0f3b-11e9-8af1-5edaabee8744.png)
