### ISSUE TITLE
[linux] Double-clicking on a .kmp file in the Files app does not open it in km-config

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#1487]
Double-clicking on a .kmp file in the Files app does not open it in km-config (and .kmp files are missing icons)

**Comment by mcdurdin** [comment]
Okay, we can leave the double-click feature for now as it is definitely lower priority than any stability or compatibility issues we may encounter.

**Comment by ermshiperete** [comment]
The icons on .kmp files already show. Double clicking them currently opens them in the unzip tool.
