### ISSUE TITLE
[Linux] Fonts do not appear to be installed with packages

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#1488]
At least, installed fonts do not appear to be visible to LibreOffice.

**Comment by glasseyes** [comment]
Unfortunately this appears to be a problem with LibreOffice. The fonts are definitely installed to ~/.local/share/fonts and fontconfig can find them e.g. `fc-match <font>`

gedit and firefox can both find the fonts ok

**Comment by glasseyes** [comment]
which fonts?

**Comment by glasseyes** [comment]
I just tested with that keyboard in the vm and newly installed LibreOffice found "Khmer Mondulkiri" just fine - it is in the font list.
What it doesn't do when you just type in the name "Mondulkiri" is find the font. LibreOffice on windows is just the same

**Comment by mcdurdin** [comment]
PEBKAC. Sorry, I don't know how I missed the font first time...
