### ISSUE TITLE
bug(linux): Backspacing and reordering is not working well in Firefox, Terminal

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#1489]
Keyman does not appear to be working correctly in Firefox, Terminal:  reordering, e.g. with Khmer Angkor, xEjmr is not​ producing ខ្មែរ (normally typed xjmEr).

**Comment by mcdurdin** [comment]
For the khmer_angkor keyboard, I'll give baseline results with gedit, then Terminal and Firefox. It's important to understand that when I type `xEjm`, the khmer_angkor keyboard reorders the output at the time the `m` key is pressed, to give the equivalent of `xjmE`. The `r` is extraneous (but forms part of the complete word)...  

* Ubuntu 18.04
* Firefox 63.0.3 64-bit

# Baseline, gedit.

This is what is expected (and what I consistently see in gedit).

| Correct order key | Correct order result | vs | Alternate keying order | Alternate order result |
| --- | --- | --- | --- | --- |
| `x` | `U+1781` | | `x` | `U+1781` |
| `xj` | `U+1781 U+17D2` | | `xE` | `U+1781 U+17C2` |
| `xjm` | `U+1781 U+17D2 U+1798` | | `xEj` | `U+1781 U+17C2 U+17D2` |
| `xjmE` | `U+1781 U+17D2 U+1798 U+17C2` | | `xEjm` | `U+1781 U+17D2 U+1798 U+17C2` |
| `xjmEr` | `U+1781 U+17D2 U+1798 U+17C2 U+179A` | | `xEjmr` | `U+1781 U+17D2 U+1798 U+17C2 U+179A` |

# Terminal

| Correct order key | Correct order result | vs | Alternate keying order | Alternate order result |
| --- | --- | --- | --- | --- |
| `x` | `U+1781` | | `x` | `U+1781` |
| `xj` | `U+1781 U+17D2` | | `xE` | `U+1781 U+17C2` |
| `xjm` | `U+1781 U+17D2 U+1798` | | `xEj` | `U+1781 U+17C2 U+17D2` |
| `xjmE` | `U+1781 U+17D2 U+1798 U+17C2` | | `xEjm` | `U+17D2 U+1798 U+17C2` * |
| `xjmEr` | `U+1781 U+17D2 U+1798 U+17C2 U+179A` | | `xEjmr` | `U+17D2 U+1798 U+17C2 U+179A` * |

# Firefox

On Firefox, the replacement sometimes works -- this looks like a race condition on backspacing. I can observe failure on my VM 4 times out of 5.

| Correct order key | Correct order result | vs | Alternate keying order | Alternate order result |
| --- | --- | --- | --- | --- |
| `x` | `U+1781` | | `x` | `U+1781` |
| `xj` | `U+1781 U+17D2` | | `xE` | `U+1781 U+17C2` |
| `xjm` | `U+1781 U+17D2 U+1798` | | `xEj` | `U+1781 U+17C2 U+17D2` |
| `xjmE` | `U+1781 U+17D2 U+1798 U+17C2` | | `xEjm` | `U+1781 U+17C2 U+17D2 U+17D2` * |
| `xjmEr` | `U+1781 U+17D2 U+1798 U+17C2 U+179A` | | `xEjmr` | `U+1781 U+17C2 U+17D2 U+17D2 U+179A` * |

\* These are incorrect results

**Comment by mcdurdin** [comment]
1. Does the same race condition problem arise with (original) KMFL? I am assuming it does?
2. I don't think timing- or delay-based solutions are going to be robust. They will fail on loaded systems, and they also cause trouble for rapid input.
3. Therefore, I suspect the solution for the race will be similar to the one we engineered for Windows (https://blog.keyman.com/2018/10/the-keyman-keyboard-input-pipeline/).
4. I am not so worried about the race condition on switching input methods at this time. That's something we can live with.

**Comment by mcdurdin** [comment]
> Can you try a virtual terminal emulator on windows and see if that is general cross-platform virtual terminal behaviour and not just a problem on linux?

Yes, this problem arises with Mintty on Windows (BKSP on U+1798 U+17D2 deletes both).

**Comment by glasseyes** [comment]
> 
> 
> > Can you try a virtual terminal emulator on windows and see if that is general cross-platform virtual terminal behaviour and not just a problem on linux?
> 
> Yes, this problem arises with Mintty on Windows (BKSP on U+1798 U+17D2 deletes both).

Good, as expected then so we can't do anything more about terminals.

**Comment by glasseyes** [comment]
>     1. Does the same race condition problem arise with (original) KMFL? I am assuming it does?

I haven't replicated it but the code path to forward the backspace is the same so I would expect it to.
 
>     2. I don't think timing- or delay-based solutions are going to be robust. They will fail on loaded systems, and they also cause trouble for rapid input.

I agree.
 
>     3. Therefore, I suspect the solution for the race will be similar to the one we engineered for Windows (https://blog.keyman.com/2018/10/the-keyman-keyboard-input-pipeline/).

Unfortunately I can't see a way to do something similar here. `SendInput` can send unicode in the generated key event but all I can do is send a virtual keycode, either forwarded back to ibus-keyman or generate a new one via the accessibility system.
ibus-keyman has no access to the Application window so it cannot send text itself, but tells ibus to send it.

>     4. I am not so worried about the race condition on switching input methods at this time. That's something we can live with.

OK

**Comment by mcdurdin** [comment]
After discussion, we will postpone this to v12 given it will require significant architectural design and perhaps upstream changes to ibus. This is not ideal but the same problems are present in KMFL and other ibus-based systems so it is a known limitation.

**Comment by nikita-moor** [comment]
A similar problem with [Anki](https://apps.ankiweb.net/) (Qt-based) and [EuroLatin (SIL)](https://keyman.com/keyboards/sil_euro_latin):

1. Start Anki
1. Press `Add` to add a new flashcard
1. Type `xxxx` in any field
1. Put the cursor in the middle of the string (`xx|xx`)
1. Start typing `-a` for "ā"

The result is `xx-xā` rather then expected `xxāxx`.

Both engines, `ibus-kmfl` and `ibus-keyman`, produce this error. However, direct typing as `xx-axx` is correct (`xxāxx`).

P.S. [Notepadqq](https://notepadqq.com/s/) is Qt-based but has no problem.

**Comment by ermshiperete** [comment]
The Khmer key sequence seems to work now in Firefox 85.0.

**Comment by ermshiperete** [comment]
To test with Qt apps, you'll have to set these environment variables ([KB101](https://help.keyman.com/knowledge-base/101)):

```
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
```

**Comment by mcdurdin** [comment]
> The Khmer key sequence seems to work now in Firefox 85.0.​

That may just be blind luck 😉 because it is a race condition that we have not resolved. Try on a slower computer, for example.

**Comment by mcdurdin** [comment]
> Neither the correct nor the alternative key order works in gnome-terminal.

Can you describe what happens in more detail?

> However, backspacing with the Khmer key sequence doesn't work, and the alternative key sequence doesn't work either.

Ditto

**Comment by ermshiperete** [comment]
Here's a little script that outputs the unicode codepoints:

```bash
#!/bin/bash
ord() {
  printf 'U+%04x ' "'$1"
}

echo -n "Input: "
while read CMD; do
	echo -n "$CMD ("
	for ((i=0; i<${#CMD}; i++)); do ord ${CMD:$i:1}; done
	echo ")"
	echo -n "Input: "
done
```

With that I get the following results:

```
Input: x
ខ (U+1781 )
Input: xj
ខ្ (U+1781 U+17d2 )
Input: xjm
ខ្ម (U+1781 U+17d2 U+1798 )
Input: xjmE
ខ្មែ (U+1781 U+17d2 U+1798 U+17c2 )
Input: xjmEr
ខ្មែរ (U+1781 U+17d2 U+1798 U+17c2 U+179a )

Input: x
ខ (U+1781 )
Input: xE
ខែ (U+1781 U+17c2 )
Input: xEj
ខែ្ (U+1781 U+17c2 U+17d2 )
Input: xEjm
ខ្មែ (U+1781 U+17d2 U+1798 U+17c2 )
Input: xEjmr
ខ្មែរ (U+1781 U+17d2 U+1798 U+17c2 U+179a )
```

Which is correct. However, the display in the terminal doesn't show up correctly:

![Screenshot from 2021-02-12 11-57-40](https://user-images.githubusercontent.com/181336/107760166-9ffa4d80-6d29-11eb-8fd3-62e73d5ef9ac.png)

**Comment by ermshiperete** [comment]
> > However, backspacing with the Khmer key sequence doesn't work, and the alternative key sequence doesn't work either.

Starting with ខ្មែរ (correct order key) and pressing backspace:
after 1 backspace: ខ្មែ
after 2-5 backspace: ខ្មែ
after 6 backspace: ខ្ម
after 7 backspace: ខ្
after 8-9 backspace: ខ្
after 10 backspace: ខ
after 11 backspace:

Entering the alternative key sequence:
```
x=ខ (U+1781 )
xE=ខែ (U+1781 U+17c2 )
xEj=ខែ្ (U+1781 U+17c2 U+17d2 )
xEjm=ខែ្្មែ (U+1781 U+17c2 U+17d2 U+17d2 U+1798 U+17c2 )
xEjmr=ខែ្្មែរ (U+1781 U+17c2 U+17d2 U+17d2 U+1798 U+17c2 U+179a )
```

**Comment by ermshiperete** [comment]
To summarize, this issue breaks down into multiple problems in different applications:

- [ ] display of Khmer text in gnome-terminal
- [ ] race condition in Firefox
- [ ] backspacing and reordering in Anki

**Comment by ermshiperete** [comment]
See also the Firefox part in #4429.

**Comment by ermshiperete** [comment]
I was able to reproduce this problem pretty consistently in a Bionic VM. A good site to test in Firefox might be https://www.editpad.org/.
