### ISSUE TITLE
[Android] In Get Started, Set Keyman as default keyboard doesn't get ticked

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#1511]
**Describe the bug**
When getting started using Keyman 11.0.2051 on Android, the last step "Set Keyman as default keyboard" is never ticked, even after completing the step.

**To Reproduce**
1. Go to "Get Started"
2. Click on "Set Keyman as default keyboard"
3. Select Keyman, click Back.

**Expected behavior**
The [3] box should be changed to a tick mark.

---
  
**iPhone/iPad/Android (please complete the following information):**
 - Device: Nokia 3 TA-1032
 - OS: Android 8.1.0
 - Keyman version: 11.0.2051
 - Target application: Keyman

**Comment by darcywong00** [comment]
This will closed when P5S2 beta gets merged back to master.

**Comment by darcywong00** [comment]
Fixed in #1564
