### ISSUE TITLE
[Android] Check for updates fails when the language menu is displayed with the system keyboard for the first time

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#1512]
**Describe the bug**
The first time you open the language menu with the Globe button in Keyman for Android, Keyman tries to check for updates. However the check fails with an error "Unable to contact Keyman server".

**To Reproduce**
1. Install Keyman and enable as system keyboard.
2. Click Globe icon.
3. Wait for "Checking for updates", then...

**Expected behavior**
No error.

---

**iPhone/iPad/Android (please complete the following information):**
 - Device: Nokia 3 TA-1032
 - OS: Android 8.1.0
 - Keyman version: 11.0.2051.0
 - Target application: Any

**Comment by darcywong00** [comment]
Fixed in #1564
