### ISSUE TITLE
[Linux] problems installing on Ubuntu 18.04

### ISSUE THREAD

**Issue by DavidLRowe** [keymanapp/keyman#1517]
With Ubuntu 18.04 running in VirtualBox (on Windows 10 host), I used
```
sudo apt-add-repository ppa:keymanapp/keyman-daily
sudo apt update
sudo apt install keyman onboard
```
to install keyman, then launched "Keyman Keyboards" and downloaded eurolatin keyboard.

This produced a "Sorry, Ubuntu 18.04 has experienced an internal error." 

One item in the error message said:
"You have some obsolete package versions installed. Please upgrade the following packages and check if the problem still occurs: nautilus, e2fsprogs, libcom-err2, libext2fs2, libnautilus-extension1a, libss2, nautilus-data, psmisc"

I used `sudo apt upgrade` (which indicated it would be upgrading 38 packages), and got error:
```
Setting up ibus-keyman (11.0.104-1~sil1~bionic) ...
sudo: david: command not found
dpkg: error processing package ibus-keyman (--configure):
 installed ibus-keyman package post-installation script subprocess returned error exit status 1

Errors were encountered while processing:
 ibus-keyman
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
I rebooted and repeated "sudo apt install keyman onboard" and got the same error messages.

Trying "sudo apt-get remove keyman onboard" gave the same error messages.

After reboot, tried "sudo apt install keyman onboard" and got:
```
dpkg: dependency problems prevent configuration of python3-keyman-config:
 python3-keyman-config depends on ibus-keyman; however:
  Package ibus-keyman is not installed.

dpkg: error processing package python3-keyman-config (--configure):
 dependency problems - leaving unconfigured
Processing triggers for libglib2.0-0:amd64 (2.56.3-0ubuntu0.18.04.1) ...
No apport report written because the error message indicates its a followup error from a previous failure.

dpkg: dependency problems prevent configuration of keyman:
 keyman depends on python3-keyman-config; however:
  Package python3-keyman-config is not configured yet.
```
"sudo apt install ibus-keyman" gives:
```
ibus-keyman is already the newest version (11.0.104-1~sil1~bionic).
```
and gives the same or similar error messages.
```
dpkg -l | grep keyman
rH  ibus-keyman                                                 11.0.104-1~sil1~bionic                              amd64        Keyman engine for IBus
iU  keyman                                                      11.0.103-1~sil2~bionic                              all          Type in your language with Keyman for Linux
ii  onboard                                                     1.4.1-4+keyman201809110810~ubuntu18.04.1            amd64        Simple On-screen Keyboard
ii  onboard-common                                              1.4.1-4+keyman201809110810~ubuntu18.04.1            all          Simple On-screen Keyboard (common files)
ii  onboard-data                                                1.4.1-4+keyman201809110810~ubuntu18.04.1            all          Language model files for the word suggestion feature of Onboard
iU  python3-keyman-config                                       11.0.103-1~sil2~bionic                              all          Keyman for Linux configuration
```
seems to indicate that ibus-keyman is indeed installed.

**Comment by glasseyes** [comment]
I'm sorry to hear of this mysterious problem. `sudo: david: command not found` being particularly mysterious.
What happens when you run `sudo -u david ibus restart` ?

Oh. Or is `david` your username or do you have one with a space in it?

**Comment by glasseyes** [comment]
I've changed the restart to use "$ibususer" so it should be more robust for unusual usernames.

ibus-keyman-1.0.104-1~2~bionic should now be available to try so we can see if that is what the problem was.

**Comment by glasseyes** [comment]
That didn't work and I've been able to replicate problems on the gnome-shell VM now. I think I've worked out how to get around that so we'll see

**Comment by glasseyes** [comment]
It now works differently on gnome-shell and should successfully run ibus exit which is needed there
`ibus-keyman-11.0.105` is currently building and should be available to install in 15 mins or so.

**Comment by DavidLRowe** [comment]
I uninstalled and reinstalled with no problem. (NB: Needed `dpkg --purge` to remove config files for `ibus-keyman` and `onboard`.) Therefore closing this issue.

**Comment by hackademix** [comment]
Actually I know exactly what was happening, and it's a bug indeed, which I bumped into some hour ago while trying to install Keyman for my wife. After some debugging I've got a patch, too.

If on the system there's more than one desktop user, both the [postinst](https://github.com/keymanapp/keyman/blob/master/linux/ibus-keyman/debian/postinst) and [postrm](https://github.com/keymanapp/keyman/blob/master/linux/ibus-keyman/debian/postrm)
scripts fail to correctly detect and handle them individually and instead feeds both (or more) to sudo: therefore the second user name is parsed as a command, making the script fail and making a mess of the whole dpkg status.

[This patch](https://github.com/keymanapp/keyman/files/3538571/ibus-keyman.postxyz.patch.txt) currently applies to each of the two scripts.

Please let me know if a pull request is actually needed.

**Comment by stefanocoretta** [comment]
I installed keyman on Ubuntu 18.04.4 LTS, but I get the errors reported above. Keyman is installed though and functioning, I just get the errors when running for example `apt update`.
