### ISSUE TITLE
QR Code for mobile APPs

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#1535]
**Is your feature request related to a problem? Please describe.**
In Desktop Apps, Windows, mac, and Linux; we need to add ability to display QR code for the mobile Apps in iOS and Android

**Describe the solution you'd like**
These QR codes with direct links to the app store will be create sense of ONE keyboard for desktop and mobile devices.

**Product context**
 - OS: Windows 7, Windows 10 1803, macOS Mojave, Ubuntu 18.04

**Comment by mcdurdin** [comment]
There are two parts to this, both of which can be handled with a single landing page, which we already have. 

For a keyboard page, the "Keyman for iPad" link should go *direct* to the App Store, and similarly for the "Keyman for Android" link, to the Play Store. That reduces the friction for installing the apps.

A QR code should be showed for each keyboard in the app which is in Keyman Cloud. For privately distributed keyboards, this is more complex and can be a separate project.

**Comment by mcdurdin** [comment]
On iPhone:

We should setup the Install Keyboard link as a Universal Link. This means that if Keyman is not installed, it will open a two-step instruction page to install the keyboard. If Keyman is installed, then 
the link will be passed to Keyman, and Keyman should recognise it as a redirect to keyman.com/keyboards/id/download. The universal link should be on its own subdomain (or potentially a path on downloads.keyman.com?)

**Comment by darcywong00** [comment]
As of now, the last 2 platforms to add this feature are iOS and Linux

**Comment by darcywong00** [comment]
All the platforms now have QR codes to share keyboards. This will be in Keyman 13.0
