### ISSUE TITLE
[iOS] iOS test flight is down

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#1541]
**Describe the bug**
iOS test flight sign up link is down
https://keyman.com/downloads/pre-release/

Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail

**Comment by mcdurdin** [comment]
Now resolved with move to Testflight hosted pages.
