### ISSUE TITLE
[Linux] Unable to Install Keyman in Ubuntu

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#1542]
**Describe the bug**
Keyman installation error

**To Reproduce**

![image](https://user-images.githubusercontent.com/14062593/51167544-7b8ec700-186c-11e9-8c24-221f5e6d1e56.png)

**Comment by glasseyes** [comment]
There is a program that automatically runs in Ubuntu called unattended-upgrade. When you don't use Ubuntu for a while, and then start it up, unattended-upgrade will automatically download and install security updates. This will take a while if there are a lot of updates. I suspect it was this program that has the lock.
Please try again.

**Comment by MayuraVerma** [comment]
I am not an expert in linux, sorry If I am asking lame questions

here is a new error
![image](https://user-images.githubusercontent.com/14062593/51298699-275e2100-19eb-11e9-9918-511a5101f8ee.png)

**Comment by glasseyes** [comment]
That's fine. Please ask questions like this on the community site so that other users can learn from them
https://community.software.sil.org/c/keyman

I don't know why this one is happening. Please try `sudo apt update` again before trying to install.

**Comment by MayuraVerma** [comment]
Great! Its installed successfully now

I have installed the keyboard, it shows in input.

but doesnt work

how do I run the keyman engine in the background?

or should i need to recompile keyboard for linux?

**Comment by glasseyes** [comment]
> Great! Its installed successfully now

:)

> I have installed the keyboard, it shows in input.
> 
> but doesnt work

Please explain what you see and are doing when it doesn't work. Add a screenshot if it helps.

> how do I run the keyman engine in the background?

It happens automatically.
 
> or should i need to recompile keyboard for linux?

You do not need to recompile for Linux. It uses exactly the same keyboard as other platforms.

**Comment by MayuraVerma** [comment]
there are no errors.
I installed a Kannada keyboard. It is listed in the available keyboards.
"show keyboard layout" shows default layout, not Kannada layout


I tried system default keyboard for Kannada. Even it is typing latin text.

There is something in the setting!

**Comment by glasseyes** [comment]
Yes, "Show keyboard layout" cannot show the Keyman keyboard layout so it
shows the default layout.

Please post this on the community support forum that I mentioned earlier.
These are useful things for other people to find. I can explain the rest
there.

**Comment by MayuraVerma** [comment]
done

https://community.software.sil.org/t/linux-keyman-keyboard/1696
