### ISSUE TITLE
[Web] Hieroglyphic keyboard is missing from keymanweb.com

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#1556]
**Describe the bug**
keymanweb.com does not list the Hieroglyphic keyboard (registered under BCP 47 code `egy-Egyp`) in the toolbar even though it is returned as an item in the array of keyboards in the API call:

```
desktopKeyboardID: 651
devices: {phone: 2, tablet: 2, desktop: 2}
filename: "hieroglyphic/1.3/hieroglyphic-1.3.js"
id: "hieroglyphic"
languages: [{id: "egy-Egyp", name: "Egyptian (Ancient)", region: 1}]
name: "Hieroglyphic"
source: "https://github.com/keymanapp/keyboards/tree/master/release/h/hieroglyphic"
version: "1.3"
```

Note that the region is `1`, which I believe is 'world', which is not listed in the available regions for the toolbar.

**To Reproduce**
1. Go to https://keymanweb.com/
2. Click on Languages, Africa.
3. Don't see "Egyptian, Ancient" in the list.

**Expected behavior**
Egyptian, Ancient should be visible either under Africa (which would require update to API data?). There should also be a 'world' catchall region in any case.

---

**KeymanWeb**:
 - OS: any
 - Browser: any
 - KeymanWeb Version: 10.0.x

---
 
**Keyboard**
 - Keyboard name: hieroglyphic
 - Keyboard version: 1.3
 - Language name: Egyptian, Ancient (egy-Egyp)

**Comment by mcdurdin** [comment]
See also https://community.software.sil.org/t/keyman-on-android-ancient-egyptian-no-longer-functions/1704/2

**Comment by jahorton** [comment]
Possible relation to #1791?

**Comment by darcywong00** [comment]
In Keyman 12, Hieroglyphic will appear under "Undetermined"

![hieroglyphic](https://user-images.githubusercontent.com/7358010/65932235-00d7fd00-e437-11e9-868f-7088cf42d0b7.png)
