### ISSUE TITLE
Tamil Character Missing 

### ISSUE THREAD

**Issue by pc8181** [keymanapp/keyman#1557]
I am using Keyman 11.0 beta with Tamil Suratha Bamini Keyboard.

but could not identified the charact 'JU' only available 'JII" 

for ex can type 
          " JULY " = ஜீலை 
         but not  = ஜூலை 

where can i type " ஜூ " in tamil suratha bamini keyboard ?

help 

Thanks

**Comment by darcywong00** [comment]
Moving this issue to the keyboards repo
keymanapp/keyboards#607

**Comment by pc8181** [comment]
Hi Sir,
     sorry for late ... is that issue fixed ?..

Thanks

**Comment by LornaSIL** [comment]
I'm sorry. We haven't fixed it in this keyboard yet. Could you try this keyboard instead and see if it works for you? https://keyman.com/keyboards/nlci_tamil_winscript or https://keyman.com/keyboards/ekwtamil99uni

**Comment by pc8181** [comment]
Thnx mam, i will try and update soon

Thanks

**Comment by LornaSIL** [comment]
@pc8181 After a very long wait I moved the bamini keyboard to our "release" version. The new keyboard is here: https://keyman.com/keyboards/thamizha_bamini

The key to produce ஜூ is `[--`. I hope this works for you.
