### ISSUE TITLE
[web] Japanese keyboard on iOS is semi-functional

### ISSUE THREAD

**Issue by rfaramir** [keymanapp/keyman#1566]
**Describe the bug**
The Japanese keyboard on iOS does not work properly. It repeats characters and has no Japanese characters on key caps.

---

(Delete the irrelevant sections)

**iPhone/iPad/Android (please complete the following information):**
 - Device: iPhone 7
 - OS: iOS 12.x
 - Keyman version 10.0
 - Target application: any 

---
 
**Keyboard**
 - Keyboard name: japanese
 - Keyboard version: 
 - Language name: Japanese

**Comment by rfaramir** [comment]
This issue is also present at keymanweb.com. Console shows error `TypeError: KeymanWeb.HideHelp is not a function. (In 'KeymanWeb.HideHelp()', 'KeymanWeb.HideHelp' is undefined)`

**Comment by darcywong00** [comment]
The keyboard is also looking for `KeymanWeb.ShowPinnedHelp`, so it sounds like we need to include uppercase methods.

**Comment by jahorton** [comment]
This sounds related to #1754.

**Comment by jahorton** [comment]
Most of the issues raised here have already been addressed.  The big remaining one is now represented by #2110; we're closing this issue in favor of that one.
