### ISSUE TITLE
[web] Shift modifier not working on Swanalekha Malayalam keyboard

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#1568]
**Describe the bug**
Reported from the [community site](https://community.software.sil.org/t/the-shift-modifier-is-not-working-in-default-and-numeric-layer-of-keyman-for-android/1709)

Shift + "-" isn't generating a fallback "_" for the keyboard rule.
KMW 10 outputs the value, but not 11.

**To Reproduce**
1. Go to KMW test page
2. Add the keyboard "swanalekha_malayalam"
3. Change the keyboard to "Malayalam"
4. Attempt to type Shift + "-"
5. No output

**Expected behavior**
It should output "_" which a keyboard rule converts to U+200C

---
Keyman Web 11.0.206 beta

--- 
**Keyboard**
 - Keyboard name: Swanalekha Malayalam
 - Keyboard version:  1.2.2

**Comment by mcdurdin** [comment]
Moved this to the wrong milestone. This is a regression that will impact multiple keyboards. We need it fixed for 11.0 stable.

**Comment by darcywong00** [comment]
I misunderstood and expected [SHIFT + K_HYPHEN] to output a character.
The user is expecting [r SHIFT + K_HYPHEN] to output `ർ` which is correctly happening in KMW and  Keyman for Android.
