### ISSUE TITLE
Further 'Mock' element unit testing

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#1587]
In #1571, support for the `Mock` "output target" type was added to KMW's 12.0 alpha branch.  While the general `OutputTarget` test cases are presently run against the `Mock`, `Mock`-specific behavior is not yet tested.

In particular - the key feature of live-mocking existing page elements, snapshotting their input-related state via deep-copy for future use without aliasing the original, needs proper unit testing.  (This is key for 'predictive text' usage.)

**Comment by mcdurdin** [comment]
@jahorton what's the state of this?

**Comment by jahorton** [comment]
Looks like I forgot to close it a while back; the unit tests requested here exist in the target_mocks.js KMW test case.  Not sure when it got added, but it's there.
