### ISSUE TITLE
[Android] Sort merged language list between kmp.json and cloud

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#1595]
Follow-up to  #1533 

When the language/keyboard info from the cloud catalog is merged with local kmp.json files, new languages from kmp.json are appended to the end.

We should sort this list.

Alternatively, revamp the keyboard search

**Comment by jahorton** [comment]
As of #1836 and/or #1842, this may now be supported already within app code.  If not, minimal extra work should be required to enable this.

**Comment by darcywong00** [comment]
This looks to be resolved now.

I installed a local keyboard package for Wyandot (language ID `wya`) and it's sorted in the "Add New Language" list.
