### ISSUE TITLE
[linux] appstream appdata files for ibus-keyman and ibus-kmfl

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#1596]
Follow-on to #361

Create appstream files for
- [x] ibus-keyman
- [x] ibus-kmfl

**Comment by ermshiperete** [comment]
Turns out that ibus-keyman and ibus-kmfl already have the appstream metadata files - albeit named `.metainfo.xml` which is the preferred naming for non-desktop apps (https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#spec-component-location).
