### ISSUE TITLE
[ios] Viewing Help for a keyboard always goes to the web instead of local

### ISSUE THREAD

**Issue by rfaramir** [keymanapp/keyman#1612]
**Describe the bug**
Viewing the Help for a keyboard always accesses the web, never the installed help. (Though it shows a plain text version of the local help once at install time.)

**To Reproduce**
1. Install a keyboard with help, e.g., Cameroon_QWERTY
2. Click on the World icon, click on the Info icon, then the "Help link"
3. It will pop up in Safari with a link to that keyboard's help file at help.keyman.com IF you have internet access. It just spins if it can't load it.

**Expected behavior**
It should show the help that was installed.
At the very least, it should show the local help as a fallback if the internet is down so the remote one cannot be loaded. Then again, if the remote one is *too* new, it might not be accurate for the version of the keyboard that is actually installed, so only showing local is probably best.

---
  
**iPhone/iPad/Android (please complete the following information):**
 - Device: any (including simulator)
 - OS: any, e.g., 12
 - Keyman version 11 (and probably earlier)
 - Target application: Keyman

**Comment by jahorton** [comment]
Delaying until all keyboards are distributed to the apps as KMPs instead of Cloud JS.

**Comment by MattGyverLee** [comment]
Thanks @rfaramir for documenting this one...it did seem strange to me.

**Comment by jahorton** [comment]
Fixed with #3622.
