### ISSUE TITLE
kmcomp creates faulty .kmp

### ISSUE THREAD

**Issue by mhosken** [keymanapp/keyman#1614]
Using a hand crafted .kps file and kmcomp.exe to create a .kmp results in a .kmp that won't install, saying that a file is missing. In this case it says that FONTLOG.txt is missing.
[khamti.zip](https://github.com/keymanapp/keyman/files/2888037/khamti.zip) is renamed from khamti.kmp to keep the issue tracker happy.
[khamti.txt](https://github.com/keymanapp/keyman/files/2888038/khamti.txt) is renamed from khamti.kps, again to keep the issue tracker happy.

Notice that this .kps uses a directory structure which is replicated within the .kmp. It is hard for me to create a flat structure here and would involve writing code just to do that.

**Comment by darcywong00** [comment]
The folder structure inside the kmp

fonts/khamti/NamKio*.ttf
fonts/*.txt
khamti_uni.kmx
kmp.inf
kmp.json

Screenshot of the error
![kmp error](https://user-images.githubusercontent.com/7358010/53150989-90394a00-35e4-11e9-9ebd-b5e4821ddceb.png)

**Comment by mcdurdin** [comment]
The .kmp format does not support folder structures.

**Comment by mcdurdin** [comment]
That was a bit hasty, sorry. The .kps file is almost okay.

* Paths can be specified in the .kps, relative to the location of the .kps file, so that should be fine.
* Paths in .kps must use backslashes (given the .kps format originated on Windows).
