### ISSUE TITLE
[Android] kmp filename used as package id

### ISSUE THREAD

**Issue by mhosken** [keymanapp/keyman#1616]
When unpacking a .kmp, the files are copied to a directory based on the .kmp filename. This means that the .kmp has to be named the same as the project id. But if someone wants to keep track, informally, of some kind of versioning, say date, of different versions of a keyboard, they can't do that using the filename. Philosophically, the filename of a package is just a filename, all information about where to store such things should come from within the package.

The good news is that you are already unpacking the package to a temporary area and reading the configuration before copying. Therefore it is a simple matter to read the id from the configuration and use that as the location to store the data rather than relying on the package filename.

This is not a problem in Windows; is a problem in Android and unknown as to whether this is a problem in iOS.

**Comment by mcdurdin** [comment]
I agree with the sentiment. However, this assumption of filename == package (or keyboard) identifier is pervasive throughout all of Keyman, and has been for many years. It's a design assumption which we could probably change given enough incentive and reason, but as there are many years of legacy dependent on it, I think it's unlikely that it will rise high enough in our priority list to fix it.

Sorry...
