### ISSUE TITLE
bug(mac): About Box shows the version where the build number should be

### ISSUE THREAD

**Issue by rfaramir** [keymanapp/keyman#1617]
**Describe the bug**
The About Box box has the version showing and right next to it, in parentheses, is something labeled 'build' but it shows the version number again.

**To Reproduce**
1. Open the About Box

**Expected behavior**
I'd expect the 'version' to be a decimal without the build number (unless 'build' means the bug fix version componenet, i.e., the third component) and the build number to be a whole number without the major and minor version numbers.

**Screenshots**
![screen shot 2019-02-22 at 3 02 14 pm](https://user-images.githubusercontent.com/45110266/53271065-ebd20900-36b2-11e9-9d77-d94a48347258.png)
"Version Keyman 11.0 for macOS" is a little awkward-sounding (maybe needs a colon after 'Version'?), but the "(build 11.0)" is both redundant and missing the actual build number.

---

**Keyman Desktop, Keyman for macOS, Keyman for Linux (please complete the following information):**
 - OS: macOS Mojave
 - Keyman version: 11.0

---

**Additional context**
I'm not actually sure where the build number comes from. I saw it on the .dmg file for v11.0 beta (the whole version looked like 11.0.200). But I don't know where the 200 comes from.

**Comment by mcdurdin** [comment]
This has been fixed some time ago:

![image](https://user-images.githubusercontent.com/4498365/202921888-0efd3531-a12c-43b9-bd6b-36f3029ca580.png)
