### ISSUE TITLE
[bookmarklet] Bookmmarklet crash due to language code issue (e.g. Osage keyboard)

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#1646]
Originally created by @LornaSIL as keymanapp/keyman#1269

> I'm told that the bookmarklet for Osage is not working. However, I can't seem to get it to work for any keyboard so I'm wondering if something is broken or I just don't know how to use it.
https://keymanweb.com/#osa-Osge,Keyboard_osage_nation

The bookmarklet gives an error
```
KeymanWeb: Invalid call to r.keymanweb.com - invalid language id
```

Also from keymanapp/keyman#747
> During a recent live demo of KMW Bookmarklets, we had a Thai keyboard crash. It is believed that the crash is due either to a not-updated BCP-47 code or due to a 2-letter code, as pre-10.0 versions of KMW required 3-letter codes.

**Comment by mcdurdin** [comment]
Fixed by https://github.com/keymanapp/r.keymanweb.com/pull/7
