### ISSUE TITLE
bug(web/bookmarklet): Nisga'a keyboard breaks bookmarklet install due to embedded quote character

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#1647]
Originally opened as KD-202, then keymanapp/keyman#319

lang portion of bookmarklet snippet that needs to be escaped

```
src='https://r.keymanweb.com/code/bml20.php?langid=ncg&keyboard=nisgaa&lang=Nisga'a Nisg̱a'a';
```

**Comment by mcdurdin** [comment]
Fixed by https://github.com/keymanapp/r.keymanweb.com/pull/7
