### ISSUE TITLE
[Linux] Icon info should be read from the .kmx instead of being included in the .kmp package

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#1649]
@mcdurdin writes:
> Information about the .ico / .bmp icon is embedded into the .kmx by the compiler. It should not be included separately in the .kmp file... Reading the icon from the .kmx is straightforward -- the header includes the offset and size of the image within the .kmx:
```
DWORD dpBitmapOffset; // 0038 offset of the bitmap in the file
DWORD dwBitmapSize;   // 003C size in bytes of the bitmap
```
> The "bitmap  image format can be either .bmp or .ico. The filename of the icon does not matter because the file data is embedded in the .kmx. .ico supports multiple resolutions; .bmp obviously does not -- it must be 16x16 pixels.

**Comment by mcdurdin** [comment]
https://github.com/keymanapp/keyman/blob/master/windows/src/global/inc/Compiler.h documents kmx file format, sorta

**Comment by mcdurdin** [comment]
https://github.com/keymanapp/keyman/blob/master/common/engine/keyboardprocessor/src/kmx/kmx_file.h is the cross-platform version.

**Comment by darcywong00** [comment]
Fixed
