### ISSUE TITLE
[windows] Font in use throws a dialog even in silent install of package from bundled exe.

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#165]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Tuesday Jun 13, 2017 at 01:42 GMT_
_Originally opened as https://github.com/sillsdev/keyman/issues/50_

----

If a font is in use when Keyman Configuration attempts to update / uninstall it (e.g. when a package is being upgraded), then a dialog box is thrown up. This must be managed silently for a silent install.

**Comment by mcdurdin** [comment]
I have tested this and found it to have been fixed already during beta.
