### ISSUE TITLE
[Web] Regression testing infrastructure

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#1652]
**Is your feature request related to a problem? Please describe.**
KeymanWeb needs to have more solid regression testing for keyboard layouts so we can refactor and update the compiler with more assurance.

**Describe the solution you'd like**
A set of regression tests based on the keymanapp/keyboards repo keyboards that can be run automatically, ideally on Node, but initially through a web driver.

**Describe alternatives you've considered**
Manual testing? Um...

**Product context**
 - OS: any (browser-based)

**Additional context**
I have some WIP code for generating test cases for keyboards (kmanalyze) -- will reference here once I create the PR. The infrastructure to run the tests needs completion. The existing Keyman Developer-based regression testing is insufficient as it is Windows-based. Anticipate being able to run tests based on both touch and hardware events in the future.

**Comment by jahorton** [comment]
Was addressed with #1697 and some further updates.  We're satisfied with the state of regression testing for KMW at this time.
