### ISSUE TITLE
[Windows] Window Close button on OSK is not visible if too many keyboards installed

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#1659]
**Describe the bug**
The X is not visible on the top right of the box. (see the screenshot below) This happens when one has considerate number of keyboards installed. 

**Screenshots**
![2019-03-08](https://user-images.githubusercontent.com/28331388/54007445-2c8c5080-4190-11e9-9c16-0ec8afa3ec76.png)

---

**Keyman Desktop, Keyman for macOS, Keyman for Linux (please complete the following information):**
 - OS: Windows 10 Pro, version 1809
 - Keyman version: 11.0.1314.0
 - Target Application: Keyman Desktop OSK
  
**Keyboard**
 - Keyboard name: any
 - Keyboard version: any
 - Language name: any

**Additional context**
One has to find an alternative to close the OSK--i.e. use the shortcut key "Shift + Alt + K" to close the OSK, or go to the Keyman icon and click on the OSK to close it.

**Comment by mcdurdin** [comment]
See also #1843.

**Comment by MakaraSok** [comment]
Tested. The dropdown arrow works as expected. One can click on it to select hidden keyboard.
