### ISSUE TITLE
Upgraded a custom keyboard and font is correct in Keyman app but not in system keyboard

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#166]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Sunday May 28, 2017 at 02:11 GMT_
_Originally opened as https://github.com/sillsdev/keyman/issues/18_

----

Upgraded a keyboard (Khmer Touch) and font is correct in Keyman app but not in system keyboard. See screenshots.

![image](https://cloud.githubusercontent.com/assets/4498365/19508471/a845d9f2-9603-11e6-983e-bc4d9a79f014.png)

![image](https://cloud.githubusercontent.com/assets/4498365/19508481/b1b7c8e2-9603-11e6-9779-86434fc29917.png)

Don't know if this is just the upgrade or happens on fresh installs as well.

**Comment by gabrielwong** [comment]
I tried reproducing but the system keyboard looked fine after the update. This may have been fixed with all the recent work. Could you take another look @mcdurdin?

**Comment by mcdurdin** [comment]
AFAICT, this issue is resolved.
