### ISSUE TITLE
[Infrastructure] Build artifacts aren't matching the build number

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#1664]
Something on the Keyman for Linux build configs is out of sync
Below are some of the tiers where the folders and build numbers don't match:

### alpha
12.0.4 -> 12.0.105
12.0.5 -> 12.0.106
12.0.6 -> 12.0.109
12.0.7 -> 12.0.111
12.0.8 -> 12.0.121
12.0.9 -> 12.0.113

### beta
11.0.112 -> 11.0.120

### stable
11.0.123 -> 11.0.122
11.0.124 -> 11.0.124 (Most of the previous stable builds were invalid, this is where it finally worked)

**Comment by mcdurdin** [comment]
The active branch determines the tier:

beta -> beta
stable-* -> stable
master -> alpha
Everything else should be a pull request where tier is not as relevant.

**Comment by glasseyes** [comment]
It turned out the simplest thing rather than detect branch was to set TIER in the TC build configs for Master, Beta and Stable.
This was in the make reconf line of the make source tarballs build step.
I've done those so the next master build should be ok, close when confirmed.

**Comment by glasseyes** [comment]
modified the build configs change to make all of them use `%env.TIER%` from the build config parameters

**Comment by glasseyes** [comment]
12.0.10 has built correctly with correct versions in the tarballs

**Comment by mcdurdin** [comment]
@darcywong00 is this issue completely resolved now?

**Comment by darcywong00** [comment]
@glasseyes fixed alpha builds in #1670 and commented
> If this works correctly I'll cherry-pick for beta and stable

The fix needs to be cherry-picked to stable (and skip beta)

**Comment by glasseyes** [comment]
I'll include that in a PR that will include the other stable changes that were for the launchpad builds hopefully Mon.

**Comment by darcywong00** [comment]
I've verified the fix from #1670 is in the current `beta` branch, so it will cover the `stable` build next week. Closing this issue.
