### ISSUE TITLE
Font size is incorrect on OSK on 12.9" iPad Pro

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#167]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Sunday May 28, 2017 at 02:11 GMT_
_Originally opened as https://github.com/sillsdev/keyman/issues/19_

----

**Comment by jahorton** [comment]
Closing this issue pending additional reports with details.
