### ISSUE TITLE
[Developer] Compile KPS files into Local Directory

### ISSUE THREAD

**Issue by dyacob** [keymanapp/keyman#1672]
Keyman Developer appears to store and reuse the location of the last .kps compilation, via a .kpj, and reuse it as the output location for later .kps files compiled without a corresponding .kpj.

Steps to reproduce:
1. Open a .kpj file and compile the corresponding .kps via the .kpj interface ("Build all" or "Build packages").
2. Exit Keyman Developer.
3. Double click a .kps file to load it into Keyman Developer.  The .kps should be in a directory different from the .kpj file in Step 1.
4. Compile the package with "Compile > Compile Package".  The .kmp output will be in the directory used by the .kpj file in Step 1, and not the enclosing directory of the .kps in Step 3.
5. Note that the .kpj file launched in Step 1 will not also be modified though it was not loaded in Step 3.

Example output that I encounter:

gff_geez.kps: Compiling package gff_geez.kps...
gff_geez.kps: 'C:\ ... \keyboards\release\gff\gff_geez\source\gff_geez.kps' compiled successfully to 'C:\ ... \keyboards\release\gff\gff_blin\build\gff_geez.kmp'.

**Comment by mcdurdin** [comment]
This is a workflow issue; it should be partially addressed by changes in Keyman Developer 12. We are moving more towards always working in a project context. The trick here is that if you load a file that is not part of the project, the project context still applies. So one appropriate fix is to determine if the file is within the current project when compiling.

The difficulty is that if the file is part of another project, but you haven't loaded that project, you are going to end up with output files potentially in multiple locations. I'm not sure how best to address this?

**Comment by mcdurdin** [comment]
I think this is really obsoleted by the use of projects in Keyman Developer 12 and later versions.
