### ISSUE TITLE
Installing a keyboard from URL should give more specific error messages when it fails

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#169]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Sunday May 28, 2017 at 02:11 GMT_
_Originally opened as https://github.com/sillsdev/keyman/issues/22_

----
JIRA:KD-112 and KMEI-64

**Comment by darcywong00** [comment]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mcdurdin](https://github.com/mcdurdin)**
_Monday Jul 10, 2017 at 05:30 GMT_

----

Another example, from https://community.software.sil.org/t/error-installing-ipad-keyboard/206

Gave unhelpful error message "Keyboard Download Error: *** -[___NSArrayM ObjectAtIndex:]: index 0 beyond bounds of empty array"


JSON captured here for posterity:



````
{
  "options" : {
    "device" : "any",
    "keyboardBaseUri" : "http://www.viduhuru.com/keyman/",
    "fontBaseUri" : "http://www.viduhuru.com/keyman/"
  },
  "keyboard" : {
    "id" : "ctb",
    "name" : "Sinhala Keyboard",
    "filename" : "ctb-1.0.js",
    "version" : "1.0",
    "lastModified" : "2017-06-09T15:16:07.600+04:00",
    "languages" : [
      ]
  }
}
````

**Comment by tombogle** [comment]
Relates to deprecated code. Won't fix.
