### ISSUE TITLE
bug(developer): Keyman Developer shows error when trying to start debugging

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#1691]
**Describe the bug**
When trying to cure my blank project windows, I decided to uninstall keyman developer and reinstall it. I uninstalled, rebooted, and reinstalled.

Now my project windows are back, but I can't do any debugging because this error pops up:
![image](https://user-images.githubusercontent.com/4498365/54862376-fe149500-4d8d-11e9-9c9a-6959bda57db0.png)

So I had to borrow someone else's computer to finish teaching.

Prior to my reinstall keyman developer was crashing over and over. and I sent you one of those crash reports, so you should have something to go on.

via @dhigby

---

**Keyman Developer**:
 - Keyman Developer version: 11.0

**Comment by darcywong00** [comment]
Closing
