### ISSUE TITLE
Keyman for Mac does not appear to work correctly with Firefox or Chrome

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#171]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Sunday May 28, 2017 at 02:12 GMT_
_Originally opened as https://github.com/sillsdev/keyman/issues/24_

----

Using the eurolatin keyboard and entering ":o", which should be transformed 
to "ö": 
In Firefox: the inputted characters are deleted, but nothing is outputted 
In Chrome: the transformed character is outputted, but the input is not 
deleted. 
(Case 72036 in CRM)

**Comment by darcywong00** [comment]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mcdurdin](https://github.com/mcdurdin)**
_Sunday May 28, 2017 at 02:12 GMT_

----

<a href="https://github.com/mcdurdin"><img src="https://avatars2.githubusercontent.com/u/4498365?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mcdurdin](https://github.com/mcdurdin)**
_Wednesday Oct 26, 2016 at 14:35 GMT_

----

I wanted to make aware that the Amharic keyboard isn't working properly. I am currently on MacOS Sierra (10.12), but even on the previous version it wasn't working properly. It works in all native programs, but for some reason not in the Messages app, where any letter typed will automatically be deleted. It all doesn't work properly in Google Chrome, inserting a space and the letter repeated with each keystroke. For example, if I wanted to type ታዲያስ, it would come up as ት ታድታዲይዲያስ.

https://secure.tavultesoft.com/forums/topic.php?ForumTopicID=417&ForumPostID=1595#ForumPost_1595

**Comment by tombogle** [comment]
Compatibility issues in Firefox are fixed. Issues in Chrome fixed also, but there are a few outstanding issues in certain sites, such as Google Docs and Word on-line.
