### ISSUE TITLE
feat(developer): Warn on unreachable code

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#1710]
**Is your feature request related to a problem? Please describe.**
If there are two identical rules, then the second rule will never be reached.  For example:

```
+ [K_A] > 'foo'
...
+ [K_A] > 'bar'  c this rule will never be matched
```

**Describe the solution you'd like**
Warn or hint on these.

**Product context**
- Keyman Developer Compiler

**Comment by darcywong00** [comment]
Like a kmn linter that grays out unreachable lines? Similar to what IDE's do

**Comment by mcdurdin** [comment]
> Like a kmn linter that grays out unreachable lines? Similar to what IDE's do

Probably just a build time warning initially.

**Comment by darcywong00** [comment]
Would the following also be considered unreachable code?
https://github.com/keymanapp/keyman/issues/6089#issuecomment-1008536489

From
```
begin Unicode > use(main)

group(main) using keys
group(main) using keys
```

to
```
begin Unicode > use(main)

group(main) using keys
c group(main) using keys)
```

I encountered this while troubleshooting one of @MakaraSok test keyboards.

**Comment by mcdurdin** [comment]
> Would the following also be considered unreachable code?

Good thinking. I think both group and store redefinition belong in the ERROR category however -- so I will turn that into a separate issue and PR.
