### ISSUE TITLE
[Windows] Keyman refuses to install some language codes (e.g. sqt-Arab)

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#1719]
**Describe the bug**
When attempting to install a keyboard with language code `sqt-Arab`, Keyman fails, and instead installs `sqt-Latn-YE`. After this it gets confused, and appears to associate the keyboard with the wrong language code.

It is possible to manually install the language code `sqt-Arab` so Keyman shouldn't be getting this wrong.

This can be reproduced with a keyboard with the code specified in the .kps, or by adding a new language for an already installed keyboard and specifying `sqt-Arab`.

**Screenshots**
![image](https://user-images.githubusercontent.com/4498365/56073671-29f5ca00-5dd2-11e9-89ce-2d3cfcaf395a.png)

![image](https://user-images.githubusercontent.com/4498365/56073673-2d895100-5dd2-11e9-9ce0-03bcba0652a7.png)

---

**Keyman Desktop, Keyman for macOS, Keyman for Linux (please complete the following information):**
 - OS: Windows 10 1809 17763
 - Keyman version: 11.0.1352.0
  
Reported at https://community.software.sil.org/t/input-method-code-in-windows-differs-from-the-code-chosen-in-the-keyboard-layout-in-keyman-developer/2053

**Comment by Shreeshrii** [comment]
As reported earlier in https://github.com/keymanapp/keyboards/pull/753 I am facing a similar issue.

>I have set the languages for the keyboard to be sa-Latn, hi-Latn etc since this is for Romanization of Indic scripts. However, when I install it, it shows up with language sa-Sinh-IN which is for Sinhala script. Why is it so? What can I do to change it?

>I also noticed that when I install a new Keyman keyboard on Windows 10, another corresponding Windows keyboard is also installed. eg. with my ITRANS Hindi keyboard, the Hindi INSCRIPT keyboard is also getting installed. With the ITRANS Roman keyboard, Sanskrit Sinhala keyboard is getting installed.
All these show up in my language choice. I would only like to keep the keyman keyboards in my list. Is there any setting I need to change for this?

>If I remove the windows keyboard,  ITRANS_ROMAN shows up with Unknown Locale (qaa-Latn)

I tried testing further using other keyboards that support transliteration and Indic languages, including ISIS. Similar problem with that. I uninstalled it using Keyman. While the keyman keyboards were deleted I now have a long list of Windows Indic keyboards that I am not able to remove. They show up in language bar but not under settings or control panel.

**Comment by Shreeshrii** [comment]
![keyman1](https://user-images.githubusercontent.com/5095331/59963009-cb07ac00-950a-11e9-916c-364ae30d9d6c.png)

**Comment by Shreeshrii** [comment]
![keyman2](https://user-images.githubusercontent.com/5095331/59963092-cabbe080-950b-11e9-8071-c02317e285f3.png)

I changed the keyboard to use `sa-Latn-IN` etc and then installed it. It only came up with one language, SA. When I used the `Add language` button, other languages show up, but they all have the wrong script in the table, including Braille.

**Comment by mcdurdin** [comment]
See also https://github.com/keymanapp/keyman/issues/3485#issuecomment-684082010
