### ISSUE TITLE
Easier method to install Keyman keyboard from local source on Android

### ISSUE THREAD

**Issue by lssoffice** [keymanapp/keyman#1722]
It is very difficult to install a Keyman keyboard (.kmp) file on Android without internet access.

A few suggested methods were as follows:

- Download a different File Manager
- Use Dropbox or Google Drive

Without Internet, Dropbox or Google Drive don’t work.

Creating an HTML file with a link also poses a challenge, because while you can download the .kmp file, when you try to open it, it doesn’t know that Keyman should be used.

People can Bluetooth/share it, but that poses the same problem (it doesn’t know Keyman should be used).

As well, many (most?) of the Android devices I have worked with in PNG have a default file manager that does not recognize that Keyman can open a .kmp file (FYI: they also didn’t recognize the Bloom Reader could open Bloom files, this is relevant later). I have found that ES File Explorer works, so can install ES File Explorer on a device that I have access to.

But then when that person shares the vernacular Keyman keyboard file with somebody else, the next phone probably does not have ES File Explorer (or another file manager that works). They don’t know that they need to get one (or which one works), or they don’t have internet so can’t get another file manager. Now they’re stuck.

The way that Bloom Reader dealt with this was to add a “Find Bloom books on this device” feature. This scans the whole device (including SD card) and automatically imports any Bloom content into Bloom Reader:

![Find Bloom books on this device](https://user-images.githubusercontent.com/34051173/56101056-a10e9800-5f63-11e9-904d-0b8553ccd1e3.jpeg)

That feature in Bloom makes it SO easy to load Books into Bloom Reader in comparison to having to get a different File Manager installed, etc. I didn't even attempt to describe the different File Manager method to a PNGan friend because it just seemed too confusing. I'm concerned the same thing will happen with Keyman.

Adding something like this to the Keyman app (that would look for .kmp files on the device and offer to install them) would be really helpful. I imagine something like a “Find keyboards on this device” option on the “add keyboard” screen. It’s possible there could be multiple .kmp files (older vs newer or different languages), so that would need to be considered too. Do you give the choice of installing the latest version of each language available?

Thanks,

James

--

Original discussion here: https://community.software.sil.org/t/install-keyman-from-local-storage/2049/3

**Comment by darcywong00** [comment]
This is fixed in #1992 

With Keyman 12.0, once the .kmp is copied/downloaded onto the device, the Keyman has a new "Settings" menu where you can "Add Keyboard from Device". This launches an internal browser which will associate the browsed .kmp file to Keyman.

See https://help.keyman.com/products/android/12.0/installing-custom-packages.php
