### ISSUE TITLE
Keyman fails to input multiple diacritics into OSX Mail with a C QWERTY keyboard

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#173]
<a href="https://github.com/mcdurdin"><img src="https://avatars2.githubusercontent.com/u/4498365?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_May 28, 2017 at 22:09 GMT_
_Originally opened as https://github.com/sillsdev/keyman/issues/26_

----

See second half of this comment [from a tavultesoft forum post]

I'm just trying out Keyman on the Mac for the very first time. Why is it that in some programs the [Country C] QWERTY keyboard gives me the dead key with the special character? 

What I want is ə ɓ ɗ ŋ etc, but it gives me ;ə ;ɓ ;ɗ ;ŋ 

It's OK in this dialogue box (I had to fake the problems above) but not with Libre Office, when it gives me as in the line above. It's OK in OSX Mail EXCEPT if you try to put two accented vowels one after the other, then it puts an extra accent on the first vowel.

**Comment by tombogle** [comment]
Tested in both OSX Mail and Libre Office using current development version (which should be functionally the same as the alpha version). Seems to work fine. I noticed that an accented upside-down e renders with the accent higher than I would have expected, but that's not likely to be a keyboard problem.
