### ISSUE TITLE
[web] Longpress and swipe over some specific subkeys can cause more than one key to stay highlighted

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#1733]
**Describe the bug**

In some specific keyboards, swiping over longpress subkeys can cause more than one key to stay highlighted. An example is available with the attached video.

Source from: https://github.com/LornaSIL/keyboards/ and commit `3b2225c5f1eceb92df4ca31dbbf570f03aa33ec9` for keyboard `release/c/coptic_qwerty`.

```
git fetch https://github.com/LornaSIL/keyboards/
git checkout 3b2225c5f1eceb92df4ca31dbbf570f03aa33ec9
```

**To Reproduce**
1. Build and test the coptic_qwerty keyboard referred above in a phone or tablet layout in KeymanWeb.
2. Long-press on full-stop.
3. Swipe over the top row, across the ['] and ["] keys. Watch more than one key stay highlighted.

**Expected behavior**
Only one key should ever be highlighted at a time.

**Screenshots**
![image](https://user-images.githubusercontent.com/4498365/56494003-19a0c600-651b-11e9-8263-a227b080d295.png)

Working hypothesis: the two keys have the same key code, and the modifier state is being ignored in the highlight code.

---

**KeymanWeb**:
 - KeymanWeb Version: 11.0.224

**Comment by mcdurdin** [comment]
Zipped video:
[2019_04_16_10_32_46.zip](https://github.com/keymanapp/keyman/files/3102893/2019_04_16_10_32_46.zip)

**Comment by DavidLRowe** [comment]
Points in support of working hypothesis:
- the keys in question both have K_QUOTE codes (one with "shift" and one without)
- the problem disappeared when K_ codes were changed to U_ codes.
