### ISSUE TITLE
[Web] Test keyboard on web not working in version 11 [Actually, web fails to read font size correctly with certain units.

### ISSUE THREAD

**Issue by DavidLRowe** [keymanapp/keyman#1746]
**Describe the bug**
Using Developer 10.0.1206.0, "Test keyboard on web" allows me to open Chrome on a mobile device (iphone, Android tablet) and test the keyboard.

When I use the same keyboard and same procedure with Developer 11.0.1352.0, the mobile device displays "Installing keyboard rac_oadki" indefinitely and never lets me test the keyboard.

**To Reproduce**
1. Open rac_oadki.kpj (keyboards PR 680)
2. Open the .kmn file, compile
3. Click "Test keyboard on web"
4. Observe on mobile device "installing keyboard" message that doesn't go away (version 11), or ability to test the keyboard (version 10).

---

(Delete the irrelevant sections)

**iPhone/iPad/Android (please complete the following information):**
 - Device: iPhone 4s
 - OS: [e.g. iOS 9.3.5]
 - Target application: [e.g. Chrome]

**Keyman Developer (please complete the following information):
 - OS: [Windows 10 1803??]
 - Keyman Developer version: [10.0.1206.0 works; 11.0.1352.0 doesn't]
 
---
 
**Keyboard**
 - Keyboard name: [e.g. rac_oadki]
 - Keyboard version: [e.g. 1.0]
 - Language name: [e.g. Oadki]

**Comment by DavidLRowe** [comment]
Same problem occurs with Developer 11.0.1350.0 and 11.0.1356.0

Problem does not occur with sil_ipa keyboard and 11.0.1350.0.

**Comment by DavidLRowe** [comment]
If I remove the `"fontsize": "16pt"` from the `rac_oadki.keyman-touch-layout` file, then the mobile device can load the keyboard.

Is this no longer allowed? If so, there should be a definite error, not an "installing keyboard" message that never finishes!

**Comment by mcdurdin** [comment]
Okay, this is an issue in KeymanWeb rather than Keyman Developer. It was addressed in #2033. It should be fixed in the latest beta.
