### ISSUE TITLE
Chinese, Japanese keyboard deprecated casing errors on KeymanWeb

### ISSUE THREAD

**Issue by jacobbowdoin** [keymanapp/keyman#1754]
Bugs related to #1742 - thanks for your quick fix on that, @jahorton! I have a few more errors from the Chinese and Japanese web keyboards which may be simply of the same manner: 

>  It's literally a matter of casing. The keyboard's an old legacy one, and while a camelCase version (showPinnedHelp) exists, the exact version shown above does not presently exist in KeymanWeb.

Bug 1. Can't click a Chinese character suggestion to insert (but pressing the corresponding number on the keyboard works)

1. On desktop, go to https://keymanweb.com/?_ga=2.108790466.192781627.1556551802-690591968.1556148767#cmn,Keyboard_chinese
2. Click on the Chinese input
3. Type "nihao" and click on the suggestion
4. Receive error:
```
Uncaught TypeError: KeymanWeb.GetLastActiveElement is not a function
    at Keyboard_chinese.ah (chinese-1.0.js:1)
    at Keyboard_chinese.aq (chinese-1.0.js:1)
    at HTMLDivElement.e.onclick [as __zone_symbol__ON_PROPERTYclick] (chinese-1.0.js:1)
```
When I click a suggestion, I expect the character(s) to be inserted into my input field.

---

Bug 2. Chinese and Japanese character suggestions don't show on mobile.

1. On Chrome's mobile emulator, go to https://keymanweb.com/?_ga=2.108790466.192781627.1556551802-690591968.1556148767#cmn,Keyboard_chinese or https://keymanweb.com/?_ga=2.130287439.192781627.1556551802-690591968.1556148767#ja,Keyboard_japanese
2. Click on the text input
3. Type anything
4. For each keystroke receive error:
```
Uncaught TypeError: Cannot set property 'innerHTML' of null
    at Keyboard_chinese.C (chinese-1.0.js:1)
    at Keyboard_chinese.show (chinese-1.0.js:1)
    at Keyboard_chinese.showCandidates (chinese-1.0.js:1)
```
When I type, I expect to receive character suggestions to click on.

---

Bug 3. Japanese character help does not show up when typing (both desktop and mobile).

1. On desktop or mobile emulator go to https://keymanweb.com/?_ga=2.172707683.192781627.1556551802-690591968.1556148767#ja,Keyboard_japanese
2. Click on the Japanese input
3. Type 'nihongo'
4. Receive errors:
```
Uncaught TypeError: KeymanWeb.ShowHelp is not a function
    at Keyboard_japanese.R (japanese-1.0.js:1)
    at Keyboard_japanese.show (japanese-1.0.js:1)
    at Keyboard_japanese.showCandidates (japanese-1.0.js:1)

ERROR TypeError: KeymanWeb.ShowHelp is not a function
    at Keyboard_japanese.aO (japanese-1.0.js:1)
    at Keyboard_japanese.gs (japanese-1.0.js:1)
    at b.processKeystroke (keymanweb.js:168)
```

Then upon clicking outside of the input to hide the keyboard:
```
ERROR TypeError: KeymanWeb.HideHelp is not a function
    at Keyboard_japanese.hide (japanese-1.0.js:1)
    at Keyboard_japanese.KNS (japanese-1.0.js:1)
    at b.notifyKeyboard (keymanweb.js:174)
```

Those stack traces are copied from my site, is the reason for seeing keymanweb.js as a reference opposed to kmwcallback.ts and kmwkeyboards.ts on keymanweb.com

My suspicions are that the Japanese keyboard may also have further deprecation errors upon fixing these first ones, similar to how the Chinese keyboard had another error as seen above.

---

KeymanWeb:
 - OS: Windows 10 1803
 - Browser: Chrome 73
 - Framework: Angular 7.2
 - KeymanWeb Version: 11.0.225
 - URL: https://keymanweb.com/?_ga=2.108790466.192781627.1556551802-690591968.1556148767#cmn,Keyboard_chinese
 - URL: https://keymanweb.com/?_ga=2.172707683.192781627.1556551802-690591968.1556148767#ja,Keyboard_japanese
 
---

 - Keyboard name: Keyboard_chinese
 - Keyboard version: 1.0
 - Language name: Chinese

 - Keyboard name: Keyboard_japanese
 - Keyboard version: 1.0
 - Language name: Japanese

**Comment by mcdurdin** [comment]
I'll add to this a race condition -- if you type a number before the suggestions have finished loading, the wrong suggestion is applied. For example, type `xue1` quickly. (after caching this behaviour may not be visible, so do this on a clean uncached load).

**Comment by jahorton** [comment]
Bug 2 (listed above) has probably always been a thing.  There's no evidence that we ever supported the picker on our mobile platforms; it seems to have always been a desktop-use only keyboard.

**Comment by jahorton** [comment]
Just in case, I spent some time seeing what it would take to make the picker work for mobile:  the branch https://github.com/keymanapp/keyman/tree/web-1754-picker-banner shows the current fruits of my labor.

<img width="1787" alt="Screen Shot 2019-09-20 at 1 32 32 PM" src="https://user-images.githubusercontent.com/25213402/65304985-374a8800-dbac-11e9-85a5-3d40952e7fd1.png">

Now that we have support for suggestion banners, I rigged up a "picker banner" to explore how the picker might operate in a mobile context.  There's a major issue though - the picker doesn't listen for touch events, so it's not interactive.  It would take significant effort at this point to read the picker's DOM mutations and jerry-rig functional handlers onto them, and then there's the matter of doing the jerry-rigged "picker banner" properly.

A more ideal scenario would be to rework it to use the new predictive-text paradigm, especially if we reach a point of having desktop platform support for predictive text available in some capacity.

**Comment by mcdurdin** [comment]
> Bug 2 (listed above) has probably always been a thing. There's no evidence that we ever supported the picker on our mobile platforms; it seems to have always been a desktop-use only keyboard.

Yes, these keyboards are pre-mobile and we never added support on mobile for them.

**Comment by jahorton** [comment]
#2109 is now in place to handle the other cases listed above.  The only issue remaining is "bug 2", which we'll have to park for now.

**Comment by mcdurdin** [comment]
@jahorton, I've moved the race condition noted [above](https://github.com/keymanapp/keyman/issues/1754#issuecomment-488880576) into #2111, and bug 2 is now reported in #2110. I think that means we can close this issue.
