### ISSUE TITLE
Errors on LMLayer CI

### ISSUE THREAD

**Issue by eddieantonio** [keymanapp/keyman#1759]
There are strange build failures that occur on LMLayer pull requests that don't _seem_ to be related to the code that is being pushed.

e.g.,
https://build.palaso.org/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=150957&_focus=1196
https://build.palaso.org/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=150940&_focus=1219

From #1755 and #1758, respectively. I cannot reproduce these errors locally, and the errors only occur on _one_ platform, **ba-win10-64-pp-602**.

**Comment by jahorton** [comment]
The second one at least - yeah, welcome to remote testing with BrowserStack.  I've tried setting up timeout variables in the past to extend how long BrowserStack waits before saying "failure", but it doesn't seem to read those variables anymore.

As for the first, that one's pretty unusual and I don't think we've seen it much.

**Comment by eddieantonio** [comment]
Ah, okay. This one might be a `wontfix`, but I'll leave it open until we see a few more LMLayer PRs.

**Comment by eddieantonio** [comment]
Marking this as `wontfix`. It might just be BrowserStack flakiness  😫
