### ISSUE TITLE
Keyman for Mac also struggles with Messages app

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#176]
<a href="https://github.com/mcdurdin"><img src="https://avatars2.githubusercontent.com/u/4498365?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_May 28, 2017 at 14:35 GMT_
_Originally opened as https://github.com/sillsdev/keyman/issues/30_

----

[tavultesoft forum post]

I wanted to make aware that the Amharic keyboard isn't working properly. I am currently on MacOS Sierra (10.12), but even on the previous version it wasn't working properly. It works in all native programs, but for some reason not in the Messages app, where any letter typed will automatically be deleted. It all doesn't work properly in Google Chrome, inserting a space and the letter repeated with each keystroke. For example, if I wanted to type ታዲያስ, it would come up as ት ታድታዲይዲያስ.

See also number 2

**Comment by tombogle** [comment]
I am able to reproduce this in Google Chrome version 61.0.3163.79 (Official Build) (64-bit). Interestingly, it seems to work fin in the URL/search bar, but if I type into a field on a page (I tried Facebook), then I get the reported incorrect behavior.

**Comment by tombogle** [comment]
Messages app works well. Chrome browser works, but there are remaining compatibility issues with some sites (e.g., Google Docs, Word on-line), as noted in the Application Compatibility Tests section of [Keyman for macOS Acceptance Test Procedures](https://github.com/keymanapp/keyman/wiki/User-testing-for-Mac)
