### ISSUE TITLE
[Web] No output for default-layout 102nd key on touch devices

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#1767]
**Describe the bug**
Keyboards with default layouts involving the 102nd key (English - United Kingdom, French-French) produce no output for said key on touch devices when interacted with via touch.  This is a regression in 11.0, as the key functioned properly in 10.0.

**To Reproduce**
1. Pick one of the keyboards above.
2. Click on the 102nd key.  (`\` for the UK keyboard example, `>` for the French keyboard example.)

**Expected behavior**
The keycap's text should be output.

**KeymanWeb (please complete the following information):
 - Occurs in KMW 11.0 stable and the current builds of `master`.

**Comment by darcywong00** [comment]
I suspect this is just the touch layout. The 102nd key on an external keyboard generates output

Tested on Keyman for Android 11.0.2107 stable with keyboards:
French-French
Cameroon AZERTY
