### ISSUE TITLE
[Mac] Keyman for Mac does not work correctly with Atom Editor

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#177]
<a href="https://github.com/mcdurdin"><img src="https://avatars2.githubusercontent.com/u/4498365?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Sunday Feb 26, 2017 at 00:44 GMT_
_Originally opened as https://github.com/sillsdev/keyman/issues/31_

----
Reported by @andjc 

(SublimeText and TextEdit are fine)

**Comment by tombogle** [comment]
I have confirmed this. It behaves like Google Docs in Safari. Neither the current beta approach nor the "legacy" approach (posting a delete-back, followed by the desired character) works. The official Apple sample approach (NumberInput) which uses a call to setMarkedText:selectionRange:replacementRange to display the composed candidate, followed by a call to insetText:replacementRange to commit it does initially display the composed text (highlighted), but as soon as the insertText call comes along, it blows it away.

**Comment by mcdurdin** [comment]
This appears to be resolved with #2588. See the test build at https://github.com/keymanapp/keyman/issues/2582#issuecomment-584900959

**Comment by mcdurdin** [comment]
Note: context is not able to be read for Atom editor but other scenarios are okay. This is acceptable.
