### ISSUE TITLE
Haíɫzaqvla Keyboard character display error on iOS

### ISSUE THREAD

**Issue by gmcauliffe** [keymanapp/keyman#1777]
**Describe the bug**
There are some errors with Haíɫzaqvla character display when typed using the FirstVoices iOS Haíɫzaqvla Keyboard:
*the high tone on ṃ́ ̣, ḷ́ and ṇ́ is not centred above the letter e.g. q̓vṃ́xsíwa 
*when ṃ́ ḷ́ or ṇ́ appears at the start or middle of a word (i.e. anywhere but the end of the word) the high tone gets bumped to the bottom of the ṇ́ (See image for examples) NB: the high tone on the “l” wasn’t consistently bumped to the bottom (see “q̓vḷ́kv” in image)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Messages'
2. Select 'Haíɫzaqvla keyboard'
3. Type words beginning with ṃ́ ḷ́ or ṇ́  (high tone) followed by any other characters 

**Expected behavior**
Expected high tone accent to be located centrally above the letter.

**Screenshots**
![image](https://user-images.githubusercontent.com/38873380/57814793-b248f100-7729-11e9-9e61-3290f33fe125.png)
--
  
**iPhone/iPad/Android:**
 - Device: iPhone 6s, Xr
 - OS: iOS 12.3
 - Keyman version: Current App Store version as of May 15, 2019
 - Target application: Messages (iOS)
 
---
 
**Keyboard**
 - Keyboard name: FirstVoices
 - Keyboard version: 1.0 (build 108)
 - Language name: Haíɫzaqvla

**Additional context**
This bug was reported by a user as occurring on multiple apps on iPhone 7 and an iPhone X. Tested in office on iPhone 6s and Xr using iOS Messages

FirstVoices Ticket reference FW-153

**Comment by mcdurdin** [comment]
This issue is also reported at: https://github.com/keymanapp/keyboards/issues/485. Will close this issue, please follow progress in the original report.
