### ISSUE TITLE
bug(developer): Regression Test Issue with Deadkey

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#1779]
**Describe the bug**
* the idea is 
    * there is need to produce the same character when pressing either [K_V] or [K_E]
    * but when another [K_E] is pressed, different characters are produced in the output.
* The issue is
    * keyman seems to mix up the two deadkey in the regression test or the speed of typing might be the issue because one can type up the sequence of VE and it should produce the desired output anyway.
    * When [K_V] is fired, "deadkey_e" is produced instead of "deadkey_v".

**To Reproduce**
1. Open "Batch regression test..." in the Debugger
2. Select the two tests, ve.xml and ee.xml
3. Click "Open"

**Expected behavior**
The expected deadkey is "deadkey_v" but the system gives "deadkey_e" instead or the other way around.

**Screenshots**
* Expected "deadkey_v", but "deadkey_e" was produced.
![image](https://user-images.githubusercontent.com/28331388/57826579-da882c80-77c9-11e9-9ab4-59780ec15a83.png)

* Expected "deadkey_e", but "deadkey_v" was produced.
![image](https://user-images.githubusercontent.com/28331388/57826753-a3664b00-77ca-11e9-9b36-2c105e4e14f0.png)

---

 
**Keyman Developer
 - OS: [Windows 10 1809]
 - Keyman Developer version: [11.0.1356.0]
 
---
 

**Additional context**
deadkey, regression tests

Source to test: 

[deadkey.zip](https://github.com/keymanapp/keyman/files/3185438/deadkey.zip)

**Comment by mcdurdin** [comment]
@MakaraSok, please re-test with Keyman Developer 15.0.

**Comment by mcdurdin** [comment]
This appears to be resolved in Keyman Developer 15.0.203.
