### ISSUE TITLE
L/R Ctrl/Alt do not appear to work on Mac

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#178]
<a href="https://github.com/mcdurdin"><img src="https://avatars2.githubusercontent.com/u/4498365?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Mar 28, 2017 at 04:50 GMT_
_Originally opened as https://github.com/sillsdev/keyman/issues/32_

----
````
store(&VERSION) '9.0'
store(&TARGETS) 'windows macosx linux'
store(&ETHNOLOGUECODE) 'ovd'
store(&LANGUAGE) 'x041D'
store(&WINDOWSLANGUAGES) 'x041D'
store(&NAME) 'Test'
begin Unicode > use(main)
group(main) using keys

+ [LALT K_A] > U+02A2
+ [RALT K_S] > U+02A2
+ [NCAPS RALT K_D] > U+02A2
+ [LCTRL RALT K_F] > U+02A2
+ [NCAPS LCTRL RALT K_F] > U+02A2
+ [LCTRL LALT K_G] > U+02A2
````
From @andjc
none of the combinations work in this instance

Two other key layouts work
````
store(&VERSION) '9.0'
store(&TARGETS) 'windows macosx linux'
store(&ETHNOLOGUECODE) 'ovd'
store(&LANGUAGE) 'x041D'
store(&WINDOWSLANGUAGES) 'x041D'
store(&NAME) 'Test3'
begin Unicode > use(main)
group(main) using keys

+ [NCAPS ALT K_A] > U+02A2
+ [NCAPS CTRL ALT K_S] > U+02A2
````
and
````
store(&VERSION) '9.0'
store(&TARGETS) 'windows macosx linux'
store(&ETHNOLOGUECODE) 'ovd'
store(&LANGUAGE) 'x041D'
store(&WINDOWSLANGUAGES) 'x041D'
store(&NAME) 'Test3'
begin Unicode > use(main)
group(main) using keys

+ [ALT K_A] > U+02A2
+ [CTRL ALT K_S] > U+02A2
````
so as soon as RALT LALT, RCTRL and LCTRL are used, virtual keys will not work on osx
at least that seems to be what's happening

**Comment by tombogle** [comment]
Note: The "bullet points" above are actually plus signs which markdown converts to bullets.

**Comment by tombogle** [comment]
FWIW, I get these two warnings when compiling:
TestMac178.kmn: Warning: line 13  warning 20A4: Left and right modifiers should not both be used in the same rule chr:3
TestMac178.kmn: Warning: line 14  warning 20A4: Left and right modifiers should not both be used in the same rule chr:3
Are those significant?

**Comment by mcdurdin** [comment]
Yes, we want to avoid L+R modifiers together in a rule. First, they are almost impossible to type. Second, there are some weirdnesses with RAlt = LCtrl+RAlt on Windows which it is just easier to avoid if we can!
