### ISSUE TITLE
[sil_ipa] Characters not properly consumed when input into chrome search bar

### ISSUE THREAD

**Issue by BRBoer** [keymanapp/keyman#1780]
I recently updated to Keyman 11 and just started having this issue after the update. When using a macro in the chrome search bar, the characters were not fully consumed.

For example, if I type 's=', I would expect it to produce ʃ. Instead 'sʃ' is produced. I've tested in other programs (VSCode) and also in <textarea> elements on various websites - these work as expected.

I can't be sure if this is due to Keyman or something Chrome has changed, but I wanted to at least bring this to your attention.

**Comment by darcywong00** [comment]
This is a compatibility issue with the Chrome autocomplete bar (See #1051)
and not isolated to the "SIL IPA" Keyman keyboard.

**Comment by BRBoer** [comment]
Interesting, thank you for the info!

**Comment by mcdurdin** [comment]
Tracking this in #1051; closing here.
