### ISSUE TITLE
[Android] Configuration menu issues

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#1782]
During #1770 some addition menu configuration items were laid out. Some parts are functional, but here's a checklist of known TODO's to resolve during 12.0 Beta

- [x] From the "Language Settings" screen, choosing to add a keyboard should show only keyboards for the currently selected language
- [x] Deleting a keyboard in the "Settings" section does not auto-update any active GUI elements for "Settings" activities". (in general all the new menu lists aren't updating). This also applies after deleting a lexical model.

--------------
Other parts of the menus to implement:
- [x] Merge lists of installed keyboards/models with what's available in the cloud
- [ ] Compare lexical model versions and automatically install latest from cloud
- [x] Implement switches (only "Get Started" from KeymanSettingsFragment is implemented so far)

**Comment by jahorton** [comment]
Additional related issues lingering from #1794:
- [ ] Lists aren't updating after install
- [ ] Lexical model isn't registered after download. Currently been toggling keyboards to get it to register
- [ ] Help links on "Model Picker" aren't implemented

**Comment by jahorton** [comment]
Noticed during development/testing:
- [ ] Uninstalling a keyboard through the Settings UI crashes the app (the view corresponding to the keyboard no longer has its matching keyboard afterward.)

**Comment by jahorton** [comment]
Thanks to the chain of PRs rooted at #1825, these issues are now resolved.
