### ISSUE TITLE
[Linux] Download Keyboard dialog shows "for macOS" not "for Linux"

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#1788]
**Describe the bug**
When downloading a keyboard in Keyman for Linux, the dialog shows "for macOS" and not "for Linux"

**Screenshots**

![image](https://user-images.githubusercontent.com/4498365/58134104-1a875d80-7c69-11e9-9363-f624c6af0a5f.png)

---

**Keyman for Linux:**
 - OS: Ubuntu 18.04
 - Keyman version: 11.0.124

**Comment by glasseyes** [comment]
I get "for Linux" with the linux icon on same OS and keyman version. Is there a rogue version of downloadkeyboard.py around there with the macos user_agent that used to be there?

**Comment by mcdurdin** [comment]
It's possible; I should try and do a clean install on my test VM ... but not tonight :(

**Comment by mcdurdin** [comment]
> I get "for Linux" with the linux icon on same OS and keyman version. Is there a rogue version of downloadkeyboard.py around there with the macos user_agent that used to be there?

Yeah, my test VM had an old version ... even after uninstalling and reinstalling via apt-get, the locally built version still took precedence. I had to do a proper cleanup to get the real deployed version.
