### ISSUE TITLE
[Linux] Downloading sil_ipa.kmp somehow retrieves sil_ipa.kmn and then fails to install it

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#1789]
**Describe the bug**
When downloading the sil_ipa keyboard in Keyman for Linux, it appears that km-config is also downloading the sil_ipa.kmn from the repository and attempting to compile it with KMFL, which fails as the keyboard uses features not supported by KMFL.

**To Reproduce**
1. Open km-config, download keyboard
2. Search for sil_ipa and click install

**Expected behavior**
The sil_ipa.kmp package should be installed. Instead, it attempts to compile sil_ipa.kmn, which is not included in the .kmp, so it must be downloading this from the source repo?

Note that downloading the file (or even installing the file that km-config downloads) via the Install Keyboard button does not attempt to compile the keyboard and hence does not fail.

**Log**

```
Download
Downloading file to /home/mcdurdin/Downloads/sil_ipa.kmp
Download URL: https://downloads.keyman.com/keyboards/sil_ipa/1.7/sil_ipa.kmp
File downloaded
kmpfile: /home/mcdurdin/Downloads/sil_ipa.kmp
installed kmp version 1.7
QUESTION dialog closed by clicking YES button
Uninstalling keyboard: sil_ipa
Removed documentation directory: /usr/local/share/doc/keyman/sil_ipa
Removed font directory: /usr/local/share/fonts/keyman/sil_ipa
Removed keyman directory: /usr/local/share/keyman/sil_ipa
Finished uninstalling keyboard: sil_ipa
Installing keyboard
created temporary directory /tmp/tmpcrwvt0vt
Installing SIL IPA
Installing sil_ipa.kmn as keyman file, minimum version: 10.0
Compiling kmn file
Could not compile /usr/local/share/keyman/sil_ipa/sil_ipa.kmn to /usr/local/share/keyman/sil_ipa/sil_ipa.kmfl so not installing keyboard.
Refreshing grid
INFO dialog closed
Closing download window
```
---

**Keyman for Linux:**
 - OS: Ubuntu 18.04
 - Keyman version: 11.0.124
  
---
 
**Keyboard**
 - Keyboard name: sil_ipa
 - Keyboard version: 1.7
 - Language name: IPA

**Comment by glasseyes** [comment]
Agreed, it should not be compiling the kmn. It looks like removing this is part of the WIP to extract the ico from the kmx in master, #1679 , so I can finish the requested changes and then backport.

**Comment by mcdurdin** [comment]
@darcywong00 does #2068 fix this completely? Please close this issue if so :)

**Comment by darcywong00** [comment]
Fixed
