### ISSUE TITLE
[Linux] Keyboard options user interface is not available

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#1790]
**Describe the bug**
First noted in https://community.software.sil.org/t/is-it-possible-to-get-an-ipa-keyboard-where-the-dead-keys-come-before-instead-of-after/1872/14

Some keyboards, such as SIL IPA, include an options dialog to control aspects of the UI. Keyman for Linux does not include a method to surface that options dialog.

According to the implementation and specification, options are supported internally, just not the UI.

**Screenshots**

![image](https://user-images.githubusercontent.com/4498365/58134521-70103a00-7c6a-11e9-93dc-0c90b5ab7fb2.png)

---

**Keyman for Linux:**
 - OS: Ubuntu 18.04
 - Keyman version: 11.0.124

**Comment by darcywong00** [comment]
Fixed by #2566
