### ISSUE TITLE
[macOS] macOS error 404 when downloading additional keyboards

### ISSUE THREAD

**Issue by gmcauliffe** [keymanapp/keyman#1806]
**Describe the bug**
When adding a new language to Keyman for macOS "error 404" returned in configuration window.

**To Reproduce**
Steps to reproduce the behaviour:
1. Choose Keyman from the Input menu in the menu bar.
2. Open Keyman Configuration, from the Configuration link under Keyman in the Input menu.
3. Select the 'Keyboard Layouts' tab
4. Click on 'Download Keyboard...'
5. See error

**Expected behavior**
Expected dropdown boxes to search for languages/keyboards to install.

**Screenshots**
![Screen Shot 2019-05-27 at 4 31 59 PM](https://user-images.githubusercontent.com/38873380/58504349-3b572380-813f-11e9-84f7-07901e8d3075.png)

---

**Keyman for macOS (please complete the following information):**
 - OS: macOS Mojave version 10.14.5
 - Keyman version: 11.0.220
 - Target Application: NA

Also tested on two client macOS devices resulting in the same error.

**Comment by rfaramir** [comment]
I get a blank page for Keyman 12.0 (just what I have currently installed), which is arguably worse,  but in my Console log I see this URL: https://keyman.com/go/macos/10.0/download-keyboards/?version=Keyman 12.0 for macOS
(the lack of percent-escaping looks wrong to me)
Trying it in Chrome yields an error page like what the user  is describing. (And the URL is percent-escaped automatically for me)

**Comment by mcdurdin** [comment]
> (it actually lacks percent-escaping, so it looks wrong to me, but it fails with it as well)

That version string is definitely wrong. It should just be `version=11.0`. I think this needs to be addressed as a separate issue; the web server issue is addressed in keymanapp/keyman.com#21.

**Comment by rfaramir** [comment]
<img width="638" alt="Screen Shot 2019-05-30 at 6 29 07 PM" src="https://user-images.githubusercontent.com/45110266/58679269-605aba80-8328-11e9-85c4-f2414911c611.png">
<img width="727" alt="Screen Shot 2019-05-30 at 11 13 44 AM" src="https://user-images.githubusercontent.com/45110266/58679270-605aba80-8328-11e9-9c6b-3ff2804820fa.png">
Here's what it looks like for me in 11.0.220 and 12.0 with my version fix.

**Comment by mcdurdin** [comment]
This issue should now be resolved.
