### ISSUE TITLE
[macOS] Keyman uses an incorrect version string in download-keyboards call

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#1808]
In my Console log I see this URL: https://keyman.com/go/macos/10.0/download-keyboards/?version=Keyman%2011.0%20for%20macOS
(it actually lacks percent-escaping, so it looks wrong to me, but it fails with it as well)

The version parameter should be just `version=11.0` or `version=12.0`.

_Originally posted by @rfaramir in https://github.com/keymanapp/keyman/issues/1806#issuecomment-496951387_

**Comment by rfaramir** [comment]
I've changed  the short bundle string (which this uses) to only be the version number. The plain bundle  string still has the long form, "Keyman 12.0 for macOS".
KMDownloadKBWindowController opening url = https://keyman.com/go/macos/10.0/download-keyboards/?version=12.0, version = '12.0'

**Comment by mcdurdin** [comment]
Fixed by #1814
