### ISSUE TITLE
[Android] Welcome Page or Help Page on Touch Devices

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#1822]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to view `welcome.html` or `help.php` on touch devices. On Windows, after a new keyboard is installed, a welcome page pops introducing the users to the keyboard and get them going. But nothing like that is available on touch devices, i.e. Android.

**Describe the solution you'd like**
It would be helpful to have a way to view `welcome.html` or `help.php` without having to go to Keyman website or Keyman Desktop.

**Describe alternatives you've considered**
Now the alternative solution is to go to Keyman Desktop to view the `help` (a.k.a. keyboard usage) page.

**Product context**
 - OS: [Android 9, Pie]

**Additional context**
N/A

**Comment by darcywong00** [comment]
On the Android app in the keyboard picker, you can click the "i" icon on the right. That usually pulls up the associated help.keyman.com page.

Note issue #1545 is still open.

**Comment by mcdurdin** [comment]
Resolved with the "i" icon in keyboard settings.
