### ISSUE TITLE
Chrome gives error "Uncaught RangeError: Maximum call stack size exceeded" loading Hieroglyphic keyboard 

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#183]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Friday Jun 16, 2017 at 06:56 GMT_
_Originally opened as https://github.com/sillsdev/keyman/issues/82_

----

https://keymanweb.com/#egy,Keyboard_hieroglyphic

However, this error does not appear in Firefox. Chrome fails to load the keyboard (in fact, it doesn't even show in the Sources tab in Developer Tools, which smells like a Chrome parser bug).

**Comment by darcywong00** [comment]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mcdurdin](https://github.com/mcdurdin)**
_Monday Jun 19, 2017 at 02:23 GMT_

----

See also https://keymanweb.com/#bod,Keyboard_tibetan_unicode_ewts

**Comment by darcywong00** [comment]
<a href="https://github.com/jahorton"><img src="https://avatars3.githubusercontent.com/u/25213402?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jahorton](https://github.com/jahorton)**
_Tuesday Jun 20, 2017 at 03:33 GMT_

----

Interestingly, the tag is successfully added to the page, but the script doesn't properly load or show up under source, despite retrieving the actual source according to the 'Network' tab.

This can be confirmed by directly linking the keyboard's source in a webpage within Chrome:  for example, adding the element `<script charset="UTF-8" src="https://s.keyman.com/keyboard/hieroglyphic/1.2/hieroglyphic-1.2.js" type="text/javascript"></script>` to samples/uncompiled.html.

Turns out that Chrome apparently hates giant if-else ladders - 'prettifying' the source shows that Chrome hits a breaking point around what becomes line 7860, or this block (useful for a Ctrl-F):

`else if (k.KKM(e, 16384, 32) && k.KDM(1, t, 147) && k.KCM(1, t, '𓈇', 1)) {`

**Comment by darcywong00** [comment]
<a href="https://github.com/jahorton"><img src="https://avatars3.githubusercontent.com/u/25213402?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jahorton](https://github.com/jahorton)**
_Tuesday Jun 20, 2017 at 03:55 GMT_

----

There is potential for a Developer-based kludge fix - each time the `if-else` ladder grows 1000 'rungs', break the ladder and do a quick check of "if not yet matched, enter new ladder".

It's definitely possible to do manually for the `hieroglyphic` keyboard, and likely possible for the other.

_Alternatively_ , I noticed that these keyboards have a _lot_ of rungs starting with the same `k.KKM` call as part of their `if`-condition.  Instead of having 20 or so of those... why not adopt a mild tree structure that makes that call once, then the subconditions within that call's branch?  That'll flatten the files enough to avoid the issue.

**Comment by darcywong00** [comment]
<a href="https://github.com/jahorton"><img src="https://avatars3.githubusercontent.com/u/25213402?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jahorton](https://github.com/jahorton)**
_Tuesday Jun 20, 2017 at 03:58 GMT_

----

Moved to https://github.com/sillsdev/keyman/issues/82.

**Comment by darcywong00** [comment]
<a href="https://github.com/jahorton"><img src="https://avatars3.githubusercontent.com/u/25213402?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jahorton](https://github.com/jahorton)**
_Tuesday Jun 20, 2017 at 05:01 GMT_

----

See also https://bugs.chromium.org/p/chromium/issues/detail?id=633189&q=call%20stack%20size%20exceeded&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified#.

**Comment by jahorton** [comment]
Now that https://github.com/keymanapp/keyman/pull/1432 exists, a number of other keyboards exhibit the same issues:

* [bod_transliterating] Bod Transliterating keyboard for Tibetan, Central
* [fv_gwichin] Gwich'in keyboard for Gwich'in
* [fv_gwichin_kmw] Gwich'in keyboard for Gwich'in
* [fv_han] Han keyboard for Han
* [fv_han_kmw] 
* [fv_northern_tutchone] Northern Tutchone keyboard for Tutchone, Northern
* [fv_northern_tutchone_kmw]
* [fv_southern_tutchone] Southern Tutchone keyboard for Tutchone, Southern
* [fv_southern_tutchone_kmw]
* [fv_tagizi_dene] Tagizi Dene keyboard for Tagish
* [fv_tagizi_dene_kmw]
* [tibetan_ewts_to_unicode] Tibetan Unicode EWTS keyboard for Adi

**Comment by mcdurdin** [comment]
See also https://community.software.sil.org/t/keyman-on-android-ancient-egyptian-no-longer-functions/1704/2

**Comment by mcdurdin** [comment]
Egyptian current link: https://keymanweb.com/#egy-Egyp,Keyboard_hieroglyphic
