### ISSUE TITLE
[Developer] Left Key Padding Value without Quotes

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#1831]
**Describe the bug**
When importing a keyboard from Windows 10, the "left padding" of the left most key on the second row has a value without a part of double quotation mark, i.e. `70` instead of the expected `"70"`. 

```
            "id": 2,
            "key": [
              {
                "id": "K_A",
                "text": "ا",
                "pad": 70
              },
```

This result in having the left most key on that row mis-align itself in the Chrome emulator. 
![image](https://user-images.githubusercontent.com/28331388/59479568-b6327500-8e87-11e9-8d7e-c3eea8d9a432.png)

Here is what it looks like when it's fixed manually by adding double quotes around the value:
![image](https://user-images.githubusercontent.com/28331388/59479610-e0843280-8e87-11e9-9b8a-af075256a60f.png)

---

**To Reproduce**
1. After importing the keyboard (Say, Central Kurdish), go to 'touch layout'
2. Click on 'Code'
3. Scroll down to or find `70` (without double quotes)
*To see how it's shown up in the emulator, go to "Build" and `Test Keyboard on web` and then `Open debugger in local browser`.

---

**Keyman Developer:**
 - OS: Windows 10 Pro 1809
 - Keyman Developer version: 11.0.1356.0

**Comment by mcdurdin** [comment]
As far as I can tell, this has already been resolved. Tested against 13.0.42
