### ISSUE TITLE
Attempting to Uninstall a keyboard from Keyman Developer can return a confusing error message

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#184]
Originally opened as sillsdev/keyman/issues/86

via @DavidLRowe in version 10.0.899.0:

At one point I clicked on the "Uninstall..." button in Keyman Developer and got a dialog box with "You do not have sufficient privileges to uninstall keyboard test_keyboard". Clicking OK brought up the dialog "Keyboard uninstalled successfully", which was actually not the case. (I eventually used Keyman Desktop to uninstall the keyboard.)

Thus, if the "You do not have sufficient privileges to uninstall keyboard test_keyboard" dialog comes up, then there should be a dialog announcing the failure (not success) of the uninstall operation.

**Comment by mcdurdin** [comment]
Fixed in 15.0 when removing strict dependencies on Keyman for Windows.
