### ISSUE TITLE
[Windows] If too many keyboards are installed, the Keyman Desktop keyboard list does not scroll 

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#1843]
**Describe the bug**
I can't see the entire list of keyboard on my machine. Probably I have too many keyboards installed.

**To Reproduce**
1. Go to 'Taskbar'
2. Click on 'Keyman Desktop' icon
3. See error

**Expected behavior**
To see the entire list of keyboard and the menu on the bottom right panel, i.e. the 'configuration' can't be accessed as it is cropped off.

**Screenshots**
![image](https://user-images.githubusercontent.com/28331388/60146790-2086d600-97f5-11e9-985a-a7f3ce826c9a.png)

---

**Keyman Desktop**
 - OS: [Windows 10 Pro 1809]
 - Keyman version: [11.0.1361.0]

**Comment by mcdurdin** [comment]
Wow, you speak a lot of languages! :)

**Comment by mcdurdin** [comment]
I think you need a bigger screen.

More useful suggestions coming soon.

**Comment by mcdurdin** [comment]
See also https://community.software.sil.org/t/keyman-desktop-display-with-many-keyboards-defined/3051

**Comment by MakaraSok** [comment]
Tested and confirmed this is fixed. 👍

**Comment by MakaraSok** [comment]
For some unknown reason, the keyboard list does not scroll any longer--as a result some keyboards are in the list. The ones missing their corresponding in the keyboard list are highlighted.

![image](https://user-images.githubusercontent.com/28331388/97141394-39a8e980-1791-11eb-993d-7a9fbca8ba7f.png)

**Comment by mcdurdin** [comment]
Can you please send a diagnostic report for this latest issue? Thanks.

**Comment by MakaraSok** [comment]
The report entitled "diag report for issue #1843" has been sent over. The case number given is #4001.

**Comment by mcdurdin** [comment]
Makara's diagnostic report:

[tkd34DD.zip](https://github.com/keymanapp/keyman/files/5437728/tkd34DD.zip)

**Comment by mcdurdin** [comment]
Okay, I see the problem here. This is a Windows limitation. I'm going to move the issue into a separate issue, because we need to give feedback when we cannot install a 5th transient language profile (first four here are Lahu, Rawang, IPA and Kayah).
