### ISSUE TITLE
[iOS] Show the readme from packages in the info menu in Settings

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#1855]
In the info display for a keyboard or model, if a readme.htm (per the kmp.json metadata) is found, present the text at the top of the menu, so that users can quickly see the basic info about the package.

**Product context**
 - OS: iOS, Android

**Comment by jahorton** [comment]
Looks related to #1822, though they are distinct.

**Comment by darcywong00** [comment]
This may need further discussion for 13.0 to be consistent with Desktop behavior where:

1. readme.htm shown before .kmp installation
2. welcome.htm displayed after .kmp installation
3. readme(?).htm displayed for keyboard help

**Comment by darcywong00** [comment]
in Keyman for Android 13.0, the implemented the Desktop behavior
