### ISSUE TITLE
[Developer] Lexical model compiler needs automated regression testing

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#1858]
From discussion on keymanapp/lexical-models#27:

> We also are lacking test for all of this code! 😱 

Now that the compilation methods are becoming large, complex, and long, it'd be wise to start implementing regression testing to assist with bug prevention as we continue enhancing them.

**Comment by eddieantonio** [comment]
Moved this issue to this repository, because the compiler code lives here now! It's also more testable here.
