### ISSUE TITLE
bug(windows): Hotkeys are lost on upgrade

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#1864]
**Describe the bug**
At least in some situations, keyboard hotkey settings are lost on upgrading from 9.0 to 11.0.

**Comment by mcdurdin** [comment]
1. Hotkeys are still not preserved in upgrades from 10.0 and older versions to 13.0.18 / 12.0.52 and later.

2. Some options may not be preserved in more recent upgrades, even though hotkeys are. For example, 'keyboard hotkeys toggle keyboard activation' option appeared to be reset after upgrading from 12.0.51 to 13.0.18. This may be because Keyman is setting default options again after install -- needs to be verified.

**Comment by mcdurdin** [comment]
Small issue: during install, Keyman Setup shows "Removing old versions" longer than it should; the message should be replaced with "Installing new version" or something like that after the removal of old versions is complete...

**Comment by MakaraSok** [comment]
Upgrading from 13.0.118 to the latest stable (14.0.283) via "Check for Update" within Keyman app or installing the latest stable on top of the 13 does prove the lost of hotkey settings.

Upgrading for 14.0.277 to the latest stable, however, doesn't rid the hotkey settings.

**Comment by rc-swag** [comment]
Doing further testing from 14.?? to 15.?? I can confirm that any `General Hotkeys` get overridden to the default values. However any values that are unset by default are retained.

**Comment by rc-swag** [comment]
This issue is fixed with PR #6491
