### ISSUE TITLE
[Android] Chat window obscured in WeChat 7.0.5 when Keyman keyboard displayed

### ISSUE THREAD

**Issue by ericjding** [keymanapp/keyman#1870]
**Describe the bug**
When writing a chat message in WeChat 7.0.5 on Android with any Keyman keyboard, the top part of the message chat window (under the title bar) is obscured by white, and the expected entry field where typed text should be displayed is also not visible. Even though the entry field is hidden, typing in the Keyman keyboard will still result in the corresponding text being input into the field (as can be seen if the keyboard is switched/hidden/turned off).

This issue does not occur on WeChat 7.0.4 or earlier versions, and it does not occur with a number of other Android keyboards that we've tested with.

**To Reproduce**
1. In WeChat 7.0.5, enter a message chat.
2. Tap on the text entry field toward the bottom to start writing a chat message.
3. If Keyman is the currently active system keyboard, then the top part of the screen under the title bar will be obscured, and the message entry field will be hidden.
4. If Keyman is not the currently active system keyboard, then switching to Keyman will result in the top part of the screen being obscured and the message entry field hidden.

**Expected behavior**
No part of the screen should be obscured by random white, and the message entry field bar should be visible as it is in WeChat 7.0.4 with Keyman.

**Screenshots**
Here is what the screen looks like in WeChat 7.0.4 with Keyman:
![Screenshot_WeChat 7 0 4](https://user-images.githubusercontent.com/10482921/61430758-99450200-a95d-11e9-8537-44179eeeb2a1.png)

Here is what the screen looks like in WeChat 7.0.5 before tapping in the entry field to write a new chat message:
![Screenshot_WeChat 7 0 5_no_keyboard](https://user-images.githubusercontent.com/10482921/61430781-afeb5900-a95d-11e9-8f7f-a094867def14.png)

Here is what the screen looks like in WeChat 7.0.5 with Keyman:
![Screenshot_WeChat 7 0 5](https://user-images.githubusercontent.com/10482921/61430791-ba0d5780-a95d-11e9-8952-1e9262726266.png)

Since it's difficult or impossible to download specific versions of WeChat from the Play Store, here are direct download links for versions 7.0.4 and 7.0.5 from WeChat (QQ) servers:
http://dldir1.qq.com/weixin/android/weixin704android1420.apk
http://dldir1.qq.com/weixin/android/weixin705android1440.apk

---

 - OS/Device: Android 8.0.0 on Sony Xperia X Compact, Android 8.1.0 (ColorOS 5.2.1) on various Oppo models
 - Keyman versions: Tested with 10.0.10000033 and 11.0.2107.
 - Target application: WeChat 7.0.5

**Comment by kienwt** [comment]
Worked around this with a Keyman Android system keyboard (modified from KMSample2) by commenting out the line starting with params.addRule in getKeyboardLayoutParams()

android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java 

This results in the WeChat chat window no longer being obscured.

WeChat 7.0.12
Keyman 13.0.6207

**Comment by ericjding** [comment]
Wow, great find, @kienwt -- so before I use this workaround on the NTL system keyboard, can you tell if this has any side effects I should be aware of?

**Comment by kienwt** [comment]
I've tested the workaround with several apps and haven't noticed any side effects.

**Comment by darcywong00** [comment]
Thanks @kienwt ! I'll give this a try in the next development Sprint. Maybe it will also resolve #2962

**Comment by mcdurdin** [comment]
@kienwt @ericjding are either of you able to test this with Keyman 14.0.53 or later (available at https://keyman.com/alpha)? None of us have a WeChat account so difficult to test from here.

**Comment by ericjding** [comment]
I just installed and tested Keyman 14.0.56 alpha on my Android 8.0 phone. The chat window is no longer obscured with this release (compare with 13.0.6060 beta, with which the bug does still occur). All hail the genius of @kienwt! :-)

BTW, for any future testing, I would mention that WeChat accounts are free to create and use, so you can actually test WeChat-related bugs in-house rather than depending on folks like us. :-)

**Comment by mcdurdin** [comment]
Fantastic news! I'l go ahead and close this issue as resolved in 14.0.53.

> BTW, for any future testing, I would mention that WeChat accounts are free to create and use, so you can actually test WeChat-related bugs in-house rather than depending on folks like us. :-)

Yeah, tried but need an existing WeChat user to validate our registration. These hurdles cost us too much time -- we are very resource constrained so really appreciate you testing!

**Comment by darcywong00** [comment]
I have some unfortunate news. The fix this introduced causes a vertical alignment issue in the system keyboard popups (See #4019).

As we're nearing 14.0 beta, I'm thinking:
* Revert most of this change for the Android app
* Copy this issue to defer to Future

As of [14.0.193](https://downloads.keyman.com/android/alpha/14.0.193/keyman-engine-android-14.0.193.zip) alpha, KMEA still has the behavior you want.

If you really need a way to keep this current behvaior in your app, I can probably make a KMManager API for your app to set.

**Comment by ericjding** [comment]
It seems to me that reverting the change basically breaks Keyman entirely in WeChat vs. a nuisance of system keyboard popups being vertically misaligned. I suspect that I would react to this differently than you are leaning toward doing, but that's your team's decision and I respect that. We've already got a working NTL OneKey keyboard "release" based on 14.0.53 and there aren't any further plans to update it at this point, unless I hear of other issues -- but again, this means that Keyman won't be of any practical use in mainland China (where WeChat is, obviously, the dominant messaging/payment app). Thanks for your due diligence and for letting me know about the issue!

**Comment by darcywong00** [comment]
I understand. 
So it turns out this was also cherry-picked into Keyman for Android 13.0.6210. 

I won't revert this change then, and will continue to resolve #4019 during Beta.

**Comment by ericjding** [comment]
Best of luck -- I've moved knee-deep into the world of Java backend development since this summer, so I'm afraid I don't have any new insight into Android UI development that could help. Thanks for your faithful and diligent efforts.
