### ISSUE TITLE
Investigate moving from keyman: to a https://local.keyman.com/ protocol for keyboard install links

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#188]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Tuesday Jun 13, 2017 at 03:11 GMT_
_Originally opened as https://github.com/sillsdev/keyman/issues/52_

----

Investigate moving from keyman: to a https://local.keyman.com/ protocol that will direct to the app if not installed, but open the app if it is installed for keyboard install links.

This link model should work for all platforms.

**Comment by mcdurdin** [comment]
`keyman:` has been deprecated with the completion of ad-hoc kmp for mobile. This feature is thus no longer directly relevant.
