### ISSUE TITLE
[LMLayer][Web] Specify "keep" suggestion display format... somewhere

### ISSUE THREAD

**Issue by eddieantonio** [keymanapp/keyman#1883]
When displaying <kbd>keep</kbd> suggestions (i.e., keep what was written verbatim, instead of taking the top ranked correction), we want quotes or some other kind of way to indicate to the user that “hey, this is what you wrote — tap here to keep it”.

Problem is, **this changes per locale**. E.g., in most Englishes, it's `“keep”`, in French and Swiss German it's `«keep»`, and in some other varieties of German, it's `„keep“`.

We need to put this SOMEWHERE — in the model? Maybe? 

Since this is presentational, I'm tempted to put this in the CSS, and make it CSS overridable via CSS. [See this Codepen for details](https://codepen.io/eddieantonio/pen/Voevze).

Problem is, _how will those quotes get there_?

It can also be specified at the lexical model definition. It could even be specified at the keyboard level! We could pull this info from the CLDR, when possible. So many possibilities!

@mcdurdin, @jahorton: ideas?

---

Discussion that started this:

>> I strongly think this is more appropriately done as close to the presentation layer as possible, and _not_ in the `displayAs` string right here.
>
>> And the quotes could be modified per language here:
>> 
>> ```css
>> [lang=en] {
>>   quotes: "“" "”";
>> }
>> 
>> [lang=fr] {
>>    quotes: "«" "»";
>> }
>> ```
>
> And that part's the reason it needs to be done in the LMLayer at present - KeymanWeb isn't given access to language modeling data; the quote style is part of that.  Which we'd then need to add as part of a model's specification, and we don't have that designed out quite yet.
>
> I suppose we could add an API to the LMLayer to request the quote types, but then there's dynamically generating the associated CSS.  KMW doesn't really have a problem with doing that - we already dynamically make and link stylesheets at times; I'd just want to make that its own issue/PR, given the extended work required to support it properly.  This one is simple enough at present to be 1 of 3 things addressed here, but such a solution should become its own PR instead.

_Originally posted by @jahorton in https://github.com/keymanapp/keyman/pull/1882_

**Comment by mcdurdin** [comment]
I see the lexical model as the most appropriate place to specify quoting style. I am not a fan of centralising it further than that. We don't know the needs of many languages and that's why we leave it as open as possible to the model/keyboard developer. Shifting language data into Keyman itself may be more optimised but it makes it difficult for those devs to do what they need to.

So per internal discussion, we are going to leave this to the LMLayer for 12.0. The rendering does seem more appropriately done in the presentation layer but the additional work to define quote characters via CSS seems unnecessary; as is adding CLDR data (which will be inadequate for our needs given it doesn't cover the languages we want) for the sake of two quote characters. Using `displayAs` works just fine and doesn't overly complicate the design.

**Comment by eddieantonio** [comment]
Alright! I'll whip up a PR soon that will allow model authors to specify:

 - quotes for the keep text
 - whether to add a space after words

Then the model compositor will be in charge of adding the configured quotes in the `keep` suggestion, and to add spaces to the `insert word` suggestions.

I think I also want somewhere to specify punctuation for double-tapping the spacebar, but that change is very non-trivial!

**Comment by jahorton** [comment]
> I think I also want somewhere to specify punctuation for double-tapping the spacebar, but that change is very non-trivial!

I think a simple API call on the LMLayer that returns a "default punctuation" Transform from the LMLayer might be 'good enough.'  KMW could ask for it on the model load and save it for use while the model's loaded.

Or is there an angle I"m not seeing immediately?

**Comment by mcdurdin** [comment]
> I think a simple API call on the LMLayer that returns a "default punctuation" Transform from the LMLayer might be 'good enough.' KMW could ask for it on the model load and save it for use while the model's loaded.
> 
> Or is there an angle I"m not seeing immediately?

Support for double-tap of spacebar (I am hesitant to add this in without thinking through the whole optimised input conceptual model -- double-tap shift, double-tap space, hold modifier + tap key, etc etc).
