### ISSUE TITLE
feat(android): The Globe key has a poor user experience

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#1887]
> Is there a reason why they can't use the Globe key to switch for quick entry?

I'd have to do some additional user testing, but I think they just don't know what the globe key _does_. Also, on my device (Android 9.0), pressing the globe key is a hinderance for a few reasons:

 1. Opening the modal dialog closes the keyboard (at least in Textra, my texting app, and a few other apps I've tested), thus meaning I have to reselect the text entry I was using whenever I switch the keyboard.
 2. The modal dialog it brings up occasionally locks up, and tries to download the keyboard index (I think), making it unresponsive to inputs for a second or two.
 3. It requires three touches to get to the Latin QWERTY keyboard: one to press the globe; one to select the alternate language. On my device, the languages are way above where my hands were resting to type in my language, so I have to readjust my grip to select either one of the two of my installed languages; finally, one more press to reselect the text area I was typing in. When I'm done writing my word or so in the Latin script, I must press the globe again, then select the language, having to readjust my grip in the process, and reselect the text input. Contrast this with one keypress to switch to Latin, I type my word, and one keypress to switch back.

A feature request to make this a quicker transition _without_ using the globe key and without adding another script to the existing keyboard is to make it so that a very deliberate swipe on the spacebar key to the left swaps to next installed keyboard. A deliberate swipe to the right swaps to the previous installed keyboard. That way, there is a very easy way to swap between installed languages to prevent breaking the flow of the typist.

_Originally posted by @eddieantonio in https://github.com/keymanapp/keyboards/pull/820#issuecomment-514381334_

**Comment by darcywong00** [comment]
Adding feedback from another user via email:

>  ... And although I think the km Khmer keyboard is designed better than Google's, I don't use it because of the slow switch between gboard and km (not between 1 km keyboard to another).

**Comment by mcdurdin** [comment]
> A feature request to make this a quicker transition _without_ using the globe key and without adding another script to the existing keyboard is to make it so that a very deliberate swipe on the spacebar key to the left swaps to next installed keyboard. A deliberate swipe to the right swaps to the previous installed keyboard. That way, there is a very easy way to swap between installed languages to prevent breaking the flow of the typist.

See also https://community.software.sil.org/t/keyboard-change-from-space-bar/3331

**Comment by mcdurdin** [comment]
From https://community.software.sil.org/t/keyman-globe-key-is-it-nessecary/3467/2:

> On the touch screen, just left of the spacebar is a little globe symbol that lets the user access keyman on android. If there is only one keyman keyboard installed, is the globe key still needed? What would the reasons be not to delete it from the keybaord if in a pinch for space?

and 

> After having tested the touch keyboard with a small group of users, it sometimes happens that people type the globe key, the screen that pops up has in english “close keyman” (not adapting to the language of the telephone, sadly) which is a problem. I would really like to remove the globe key, at least from the first layer. What if the the globe key would be just be located in the symbol layer?

**Comment by darcywong00** [comment]
Also from https://community.software.sil.org/t/solved-keyboard-package-error/4552/24

> Pls someone change the way of switching language in keyman keyboard to be better. I mean like in windows, switching language in background with key combination. Not choosing by touching screen in andriod tablet. The screen which appeared after pressing ctr+tab is annoying. Or when typing, the onscreen keyboard should disappear automatically. Thanks.

![](https://community.software.sil.org/uploads/default/original/2X/e/ef4eca6329d2f1dc42849f89613b43963c7ed79c.jpeg)

**Comment by darcywong00** [comment]
Also see related issues #4318

**Comment by mcdurdin** [comment]
See also #4937, #4515 (tangent), #4476, #4318, #4309.

**Comment by mcdurdin** [comment]
(This is probably better as a separate issue but throwing in here as a rider for now: also consider Ctrl+C, Ctrl+V on hardware keyboards)

**Comment by mcdurdin** [comment]
Per #2035, we still need to be able to customise the "Close Keyman" message for KAB users, for example. Ref: https://community.software.sil.org/t/keyman-android-feature-request-localise-close-keyman-button/4837/4

**Comment by rowbory** [comment]
Many thanks; it would be ideal to have a direct popup menu showing however many keyboards available that can fit on the screen from KAB and Keyman Android engine rather than going to a dialog and closing the keyboard after it is switched.

**Comment by darcywong00** [comment]
Reference: Team [discussion](https://docs.google.com/document/d/11CO3DdbKky5B_BbQsWwkSCkVvR1OrX_prUKK4ponaEg/edit#) on this spec

## No Changes
1. Globe key on lock screen remains the same (so user can access keyboard to unlock device)
2. External keyboard Ctrl+Tab shortcut

## Changes
1. Shortpress globe key switches to next Keyman keyboard
    * If only 1 Keyman keyboard installed, nothing happens
2.  Implement longpress globe in KeymanWeb
3. Longpress globe key opens the Keyboard Picker menu.
    * Rename “Close Keyman” button to “Next Input Method”
4. External keyboard (maybe)
    * Win+Space or Win+Shift+Space (verify not used by Android)

## Deferred Changes (Depend on KeymanWeb flick #5029)
1. Left/Right flick on spacebar switches to previous/next Keyman keyboard
2. Add a settings menu that enables/disables actions (globe keys, flicks)

**Comment by darcywong00** [comment]
The short press and long press globe key actions from #5437 should be enough to close this issue.
I'll split out the deferred changes to a separate issue.

No change with external keyboard shortcuts either.

**Comment by MayuraVerma** [comment]
My 2 cents
All users are used to GLOBE ICON behaviour

1. Tap: Next system keyboard
2. Long press: List of all system keyboards available.

When this behavior is different only while using Keyman keyboard, average users feels lost.

Globe Icon is "OS key", its behavior should not be changed

Thankfully in iPhones with face ID: X, XS, 11, 12, 13, iOS adds two globe icon. I am not sure how this works in iPads and iPhone 8, 7, 6s, SE with touch ID, which do not have second globe icon.

![IMG_94DC5D08D10C-1](https://user-images.githubusercontent.com/14062593/134718242-1629beb3-f5ba-4936-b60b-06ca3d160f23.jpeg)

In iOS with all the iPhone with face ID: globe icon in the 3rd party keyboards, single tap goes to next keyboard (basically previous system keyboard that was in use). 
large globe icon in the bottom row, cycles thru all the system keyboards and long press press shows list of all system keyboards.

So, personally it is not a challenge for me to get in and out of keyman keyboard. But I have heard from Android users, they are having HARD time using keyman, while switch back to system keyboard.

My suggestion:
Both for iOS and Android: globe icon behaves native to OS, 1. tap to next system keyboard, 2. Long press to list of system keyboards in which (Keyman as one of them).

(I understand Android and iOS do not allow one app to install multiple keyboards)

So we can over-load SPACE BAR: 1. swipe left and right to cycle thru keyman keyboards. 2. Long press space bar to keyman menu.

In the present Android UI, average users finds it hard to get out of keyman keyboards after selecting it. People use emojis often, they shouldn't feel keyman has hijacked the system keyboard layout.

It should be easy to get in, and also get out of keyman keyboard.

Please review.

Also, we need understand, how many users actually use more than one keyman keyboard. I feel it is a small number. 

My guess
1. Most people are bi-lingual, English and their Native language.
2. Please prefer English from OS, add native language from Keyman.

Or another suggestion:

Provide two Keyman apps both in android and iOS. 
1. Keyman with multiple keyboard version. User can install more than one keyboard from Keyman. Still prefer to over load Space Bar over changing the behavior of Globe Icon.
2. Keyman with one keyboard version. Keyman limited to install only one keyboard of the user choice from the app. I feel this is the most used case.

**Comment by mcdurdin** [comment]
Tracking your feedback @MayuraVerma at https://community.software.sil.org/t/feedback-on-keyman-15-0-alpha/5405/2
