### ISSUE TITLE
[Mac] Keyman on Mojave 10.14.6 emits wrong characters for SIL IPA keyboard

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#1892]
**Background Info**
The updated Keyman as described [here](https://github.com/keymanapp/keyman/issues/1877#issuecomment-514429795) has been install on macOS 10.14.6. The SIL IPA keyboard has also be uninstalled and reinstalled on the OS.

**Describe the bug**

The expected characters are not output. For instance, ɑ, æ and ɐ should be output when pressingː a=, a< and a>.

**To Reproduce**
1. Choose SIL IPA from the keyboard list
2. Go to 'Message' or 'TextEdit' or 'Notes' or 'LibreOffice'
3. Type a=, a<, a>

**Expected behavior**
a= should output ɑ
a< should output æ
a> should output ɐ 

**Screenshots**
Notesː
![image](https://user-images.githubusercontent.com/28331388/61856557-8ea1e400-aeec-11e9-997d-3406a30ae575.png)

TextEditː
![image](https://user-images.githubusercontent.com/28331388/61856464-64e8bd00-aeec-11e9-998b-563738caa95d.png)

Messagesː
![image](https://user-images.githubusercontent.com/28331388/61856629-b6914780-aeec-11e9-9d75-a77bd5a5b15c.png)

LibreOfficeː
![image](https://user-images.githubusercontent.com/28331388/61856752-f7895c00-aeec-11e9-8edc-8ae9ef3aa857.png)

---

**Keyman for macOS**
 - OS: macOS Mojave 10.14.6
 - Keyman version: [12.0 (for testing)](https://drive.google.com/file/d/1HsNAJDlsNGMlmSphVEG4OOmhlgi4NNSa/view?usp=sharing)
 - Target Application: 'Message' or 'TextEdit' or 'Notes' or 'LibreOffice'
   
**Keyboard**
 - Keyboard name: [SIL IPA](https://keyman.com/keyboards/sil_ipa)
 - Keyboard version: 1.7
 - Language name: Phonetic alphabet

**Comment by mcdurdin** [comment]
This appears to be unrelated to #1889. Watching events I see the following exception occur when I type `a=`, on the `=` key (that's as much of the stack as I have):

```
exception in IMKServer:
	NSRangeException
	*** -[__NSArrayM objectAtIndex:]: index 1 beyond bounds [0 .. 0]
	(null)
(
	0   CoreFoundation                      0x00007fff51e60cfd __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff7c50aa17 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff51e9fcf4 -[CFPrefsConfigurationFileSource initWithConfigurationPropertyList:containingPreferences:] + 0
	3   CoreFoundation                      0x00007fff51d9c47e -[CFPrefsSearchListSource addNamedVolatileSourceForIdentifier:] + 0
	4   KeymanEngine4Mac                    0x00000001089f5384 -[KMEngine processKey:event:] + 4894
	5   KeymanEngine4Mac                    0x00000001089f3db4 -[KMEngine processGroup:event:] + 4059
	6   KeymanEngine4Mac                    0x00000001089f2b7a -[KMEngine processEvent:] + 721
	7   Keyman                              0x0000000108717310 -[KMInputMethodEventHandler handleKeymanEngineActions:in:] + 642
	8   Keyman                              0x
```

**Comment by mcdurdin** [comment]
Added test case. This error relates to retrieving an `index()` value when there are `if()` statements in the context part of a rule. The rule in question in [sil_ipa.kmn](https://github.com/keymanapp/keyboards/blob/b6baec5a5822bde02655041c764584934a4f2ec1/release/sil/sil_ipa/source/sil_ipa.kmn#L373) is:

```
if(option_key = '') any(equalD) + "="  > index(equalU,2)
```

KMEngine.m:`processKey:event:`
```objc
                case CODE_INDEX: {
                    DWORD x1 = [outKey characterAtIndex:i+2];
                    DWORD x2 = [outKey characterAtIndex:i+3];
                    KMCompStore *store = [self.kmx.store objectAtIndex:x1 - 1];
>                   NSUInteger n = [[self.indexStack objectAtIndex:x2 - 1] unsignedIntegerValue];
```

This is failing because the index requested is 2, but the `if()` statement does not take a slot in the `self.indexStack` variable. The fix will be to ensure that `if()` statements take a corresponding slot.

For testing: check also `CODE_CONTEXTEX` to ensure it selects the correct character.

**Comment by mcdurdin** [comment]
Original report: https://community.software.sil.org/t/sil-ipa-ver-1-7-not-functioning-correctly-on-macos-mojave/2340/5
