### ISSUE TITLE
bug(mac): Amharic keyboard on macOS Mojave 10.14.6 in LibreOffice emits wrong characters

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#1893]
**Background Info**
The updated Keyman as described [here](https://github.com/keymanapp/keyman/issues/1877#issuecomment-514429795) has been install on macOS 10.14.6. The SIL IPA keyboard has also be uninstalled and reinstalled on the OS.

**Describe the bug**
Key sequence and the expected output
hi > ሂ
ho > ሆ
hu > ሁ
he > ሀ
ha > ሃ

But in LibreOffice, the followings are output instead:
hi > ህi
ho > ህo
hu > ህu
he > ህe
ha > ህa

**To Reproduce**
1. Go to 'LibreOffice' or 'TextEdit' or 'Notes' or 'Message' 
2. Select the 'GFF Amharic' keyboard from the Keyman menu
3. Type: hi, ho, hu, he, ha

**Screenshots**
Text typed on 'LibreOffice,' 'TextEdit,' 'Notes' and 'Message' (in this order)
![image](https://user-images.githubusercontent.com/28331388/61859495-69b06f80-aef2-11e9-99a9-5e38ae33754f.png)

---

**Keyman for macOS**
 - OS: macOS Mojave 10.14.6
 - Keyman version: [12.0 (for testing)](https://drive.google.com/file/d/1HsNAJDlsNGMlmSphVEG4OOmhlgi4NNSa/view?usp=sharing)
 - Target Application: 'LibreOffice' or 'TextEdit' or 'Notes' or 'Message' 
   
**Keyboard**
 - Keyboard name: [GFF Amharic](https://keyman.com/keyboards/gff_amharic)
 - Keyboard version: 1.8
 - Language name: Amharic

**Comment by mcdurdin** [comment]
See also #1877

**Comment by mcdurdin** [comment]
@MakaraSok Can you retest this please with latest beta?

**Comment by MakaraSok** [comment]
Tested, the keyboard is now working on TextEdit, Messages and Notes, but not on LibreOffice.

**Comment by mcdurdin** [comment]
I am testing this now with Keyman 12.0.7 beta for macOS, and LibreOffice 6.3.2.2 (x64) for macOS, and it seems to be working fine in Writer. Can you give some more detail on the LibreOffice version and test with 12.0.7 beta as well?

**Comment by mcdurdin** [comment]
(After updating Keyman, please restart the system to be sure that you are doing a clean test)

**Comment by mcdurdin** [comment]
Unable to get repro and @MakaraSok is unavailable so moving to Future release.

**Comment by mcdurdin** [comment]
This is almost certainly the same root issue with Keyman not having full access required as described in #1894.
