### ISSUE TITLE
[Mac] RightAlt and Shift RightAlt on Khmer Angkor 

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#1894]
**Describe the bug**

![image](https://user-images.githubusercontent.com/28331388/61861172-7da9a080-aef5-11e9-8338-6c9b61491587.png)

The screenshot shows all characters on the RightAlt (in this case, just Alt), however, when press unexpected character were output instead. Similar issue occurs with Shift + RightAlt too; the only different is that the OSK was not even showing the expected characters.

**To Reproduce**
1. Go to text editor or any other app which you can type text
2. Choose 'Khmer Angkor' in the keyboard menu
3. Press and hold Alt and then any key, say `b`
![image](https://user-images.githubusercontent.com/28331388/61861971-3b815e80-aef7-11e9-9ac8-2ff913d1333c.png)

The expected character is ឞ.

---

**Keyman for macOS**
 - OS: macOS Mojave 10.14.6
 - Keyman version: [12.0 (for testing)](https://drive.google.com/file/d/1HsNAJDlsNGMlmSphVEG4OOmhlgi4NNSa/view?usp=sharing)
 - Target Application: 'any text editor'
   
**Keyboard**
 - Keyboard name: [Khmer Angkor](https://keyman.com/keyboards/khmer_angkor)
 - Keyboard version: 1.0.6
 - Language name: Khmer (a.k.a. Cambodian)

**Comment by mcdurdin** [comment]
This looks like it is also related to security. Try the steps at https://community.software.sil.org/t/keyman-for-mac-and-polytonic-greek/2458/4 to resolve the issue:

1. Run the following command in Terminal:
```
  sudo tccutil reset PostEvent
```
2. Restart your Mac
3. Ensure that Keyman is enabled in Privacy/Input Monitoring and Privacy/Accessibility.

It sometimes takes a little while for Keyman to appear in those locations -- start using Keyman and check those locations after a bit.

**Comment by mcdurdin** [comment]
(Although, if this is related to clicking on the keys of the keyboard, it may be a separate, unrelated issue 😁
