### ISSUE TITLE
[Developer] The Shift Layer on Touch Layout Reappears after Getting Deleted

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#1898]
**Describe the bug**
Trying to get rid of a layer from the Touch Layout, say "Shift Layer," by using `Del` button in between `Add` and `Edit`. The Shift Layer reappears upon reopening the Developer or switching between the `Code` and `Design` view in the Touch Layout.

The Shift Layer will disappear completely when removing its code block from the Code view.
![image](https://user-images.githubusercontent.com/28331388/61923172-35d65800-af8d-11e9-8c10-994653acaee4.png)

**To Reproduce**
1. Go to 'Touch Layout' 
2. Click on 'Shift' on the dropdown menu for Layer
3. Click on 'Code' view at the bottom of the panel and then switch back to 'Design' view
4. Go the Layer dropdown menu, click on it
5. See error

**Expected behavior**
After being delete from the Layout, Shift layer should not have reappeared.

**Screenshots**
![image](https://user-images.githubusercontent.com/28331388/61922737-b005dd00-af8b-11e9-995d-978a5021fb4a.png)

---

**Keyman Developer:
 - OS: Windows 10 Pro, 1903
 - Keyman Developer version: 11.0.1356.0
 
---
 
**Keyboard**
 - Keyboard name: [Krung](https://github.com/keymanapp/keyboards/pull/804)
 - Keyboard version: 1.0
 - Language name: Krung

**Comment by mcdurdin** [comment]
Resolved in 12.0.36
