### ISSUE TITLE
[ios]  ad hoc models leave zip files around forever

### ISSUE THREAD

**Issue by rfaramir** [keymanapp/keyman#1899]
**Describe the bug**
When adding models ad hoc, upon successful installation, the zip files are not deleted.

**To Reproduce**
1. Add a model via ad hoc
2. stop it during parsing or installing to see the directories involved
3. when it's done, view the directories again
4. See error (another zip file added)

**Expected behavior**
I'd expect it to be deleted upon successful install, or at most, one new zip file per *new* model, not a zip file per download, even if same model.
---

(Delete the irrelevant sections)

**Keyman Desktop, Keyman for macOS, Keyman for Linux (please complete the following information):**
 - OS: iOS
 - Keyman v12.0
  
---
 
**Additional context**
It may be because of not using HTTPDownloader, which seems to delete the relevant files for keyboards. I may fix itself once that enhancement is in place.

**Comment by jahorton** [comment]
I think Android currently keeps these around, actually.  At a minimum, the contents of the old .kmps are actively stored so that they can be re-installed later if needed.

**Comment by jahorton** [comment]
As of #2460 and #2457, this is now handled appropriately.  While we don't delete the user's original download...

-  all temp files from installation are now handled within 'cache' directories that iOS can auto-clean (the destination of the .zip byproduct)
- we maintain a single local copy of the resource within Keyman's 'Documents' folder, which is overwritten on updates

This is sufficient to consider this issue closed.
