### ISSUE TITLE
The &targets and &keyboardversion stores cause compiler to fail if version < 9.0

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#191]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Tuesday Jun 13, 2017 at 03:53 GMT_
_Originally opened as https://github.com/sillsdev/keyman/issues/55_

----

Decide on whether the compiler should block &targets and &keyboardversion stores or ignore them for older file versions. These don't conceptually break a keyboard, so should be able to target, e.g. KM7 with these stores without trouble.

**Comment by mcdurdin** [comment]
Keyman 10 is now our minimum supported platform. Not worth doing back-compat efforts like this.
