### ISSUE TITLE
[Developer] Character Map, OSK, Character Identifier and Test Window do not recognize U+104A0..U+104A9

### ISSUE THREAD

**Issue by LornaSIL** [keymanapp/keyman#1915]
**Describe the bug**
Keyman Developer in Character Map, OSK, Character Identifier and Test Window do not correctly display the Osmanya digits. Keystrokes output the correct characters.
I'm using the Ebrima font which does have these characters in the font.

**To Reproduce**
1. Pull https://github.com/keymanapp/keyboards/tree/master/release/basic/basic_kbdosm
2. Open basic_kbdosm.kmn in Keyman Developer
3. See the square boxes

**Expected behavior**
I expect to see Osmanya digits in the OSK particularly and in the test window and other places.

**Screenshots**
Keyman Developer and installed keyboard OSK:
![image](https://user-images.githubusercontent.com/7071907/62066617-5dc8f400-b1f7-11e9-8329-38c5d87d9ecd.png)

Displays fine in Firefox:
![image](https://user-images.githubusercontent.com/7071907/62066796-c87a2f80-b1f7-11e9-995f-9545f01e16ee.png)

Displays fine in Word 2016:
![image](https://user-images.githubusercontent.com/7071907/62066807-d760e200-b1f7-11e9-9d86-7d0c158599a8.png)

---

(Delete the irrelevant sections)

**Keyman Developer (please complete the following information):
 - OS: Windows 10 1903
 - Keyman Developer version: [e.g. 11.0.1356.0]
 
---
 
**Keyboard**
 - Keyboard name: [e.g. basic_kbdosm]
 - Keyboard version: [e.g. 1.0.]
 - Language name: [e.g. Somali]

**Additional context**
This problem also existed in Andrew Cunningham's keyboard that was never accepted:
https://github.com/keymanapp/keyboards/pull/71

This problem exists in ```https://github.com/sillsdev/keyman-keyboards-internal\Osmanya (VicNet)\osmanya10.kmn```

**Comment by mcdurdin** [comment]
I am guessing this is lack of a fallback font scenario for those characters. If you select an Osmanya font in the Character Map, does it display correctly?

**Comment by LornaSIL** [comment]
This is with Ebrima font selected for both Character Map and for all the fields in the Font selector. Please notice the two squares. When there is no font fallback it is generally 1 square.
![image](https://user-images.githubusercontent.com/7071907/62137870-48fa6800-b2ac-11e9-9e2b-af603fd42a5c.png)

**Comment by darcywong00** [comment]
From Developer 12.0.40.0

Interestingly, the code tab renders the digits, but not the other places
![image](https://user-images.githubusercontent.com/7358010/65931281-409ce580-e433-11e9-9b67-007006af2d06.png)

**Comment by mcdurdin** [comment]
Note: this issue also arises in Notepad

**Comment by mcdurdin** [comment]
This appears to be a bug in Windows, given it also happens in Notepad. I am going to go ahead and close this issue, because it will be resolved in the future when we move to a web-based render for the OSK anyway (except for the debugger window, which is probably lowpri).
