### ISSUE TITLE
[Developer] Remove byte-order-mark from UTF-8 files in word list TSVs

### ISSUE THREAD

**Issue by eddieantonio** [keymanapp/keyman#1916]
In an effort to reduce end-user confusion, we can automatically remove the byte-order-mark from the very beginning of wordlist TSV files used by the developer tools.

It requires removing U+FEFF from the beginning of the code unit stream (or `EF BB BF` from the very beginning of the bytestream).

Will this lead to unintended consequences?

---

From this discussion:

> I mean, is it hard to strip out the BOM?  Seems like a big ask for those not so familiar with byte encoding particularities.

_Originally posted by @jahorton in https://github.com/keymanapp/lexical-models/pull/51_

**Comment by mcdurdin** [comment]
> Will this lead to unintended consequences?

This is unknowable.

😆

My real feeling: 👍

**Comment by eddieantonio** [comment]
Closed in #1970
