### ISSUE TITLE
[Android] Keyman for Android 12 beta adds double space

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#1929]
**Describe the bug**
Two spaces are added after tapping on one of the three suggested words on the top row.

**To Reproduce**
1. Go to 'Setting' on 'Keyman app for Android'
2. Tap on 'Installed languages' then tap on English to download the "English dictionary (MTNT)
3. Go back to the text editor area and type 'thos' then tap on "those" 

**Expected behavior**
There should be only one space after the selected word.

**Screenshots**
![double space](https://user-images.githubusercontent.com/28331388/62442501-51f2aa00-b782-11e9-863d-23671f649c6e.jpg)

---

**iAndroid:**
 - Device: [Samsung Galaxy S9+]
 - OS: [Android 9 Pie]
 - Keyman version [12.0.4074]
 - Target application: [Keyman]

---
 
**Keyboard**
 - Keyboard name: [EuroLatin (SIL) Keyboard]
 - Keyboard version: [1.8.1]
 - Language name: [English]

**Comment by jahorton** [comment]
This also occurs in base KMW on the beta branch.
