### ISSUE TITLE
[Developer] Keyman Developer debugger is still not selecting right keyboard at first load

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#193]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Tuesday Jun 13, 2017 at 03:57 GMT_
_Originally opened as https://github.com/sillsdev/keyman/issues/57_

----

**Comment by mcdurdin** [comment]
There are two scenarios where the debug host keyboard is not correctly selected:

1. When it is not installed, Keyman Developer prompts for installation. Installation takes a few seconds but before installation is complete, Keyman Developer receives focus again and thinks that the keyboard is not available. Then it prompts again to install the keyboard, which is confusing to the user. Cancelling the second prompt, waiting a second or two, and clicking into Source view and back into the Debugger selects the correct host keyboard.

2. If you press F5 in any view other than the Layout Source view, the first time the Source view loads takes a moment, which then means focus is incorrectly set and the debug host keyboard does not get activated. Clicking into the Source code and back into the Debugger selects the correct keyboard.

**Comment by mcdurdin** [comment]
Therefore, postponing this issue: #1 will be addressed with the change to KPAPI hosting in 12.0, and #2 is not a major issue; addressing it requires a redesign of the focus sequence for starting the debugger with a promise-like architecture, which is non-trivial and will likely impact a number of other areas as well.

**Comment by mcdurdin** [comment]
Resolved in 15.0 with Keyman Core Debugger integration.
