### ISSUE TITLE
bug(android): Sometimes the Delete Key is sticky and it will not stop deleting

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#1930]
**Describe the bug**
When typing in Google email app or the search bar (or on Keyman app's text editor), the delete key may get sticky and it will keep deleting everything. This behavior may pause when switching out of the app and it would resume the deletion when switch back to the app.

**To Reproduce**
1. Go to 'Keyman app for Android'
2. Start typing away several lines of text
3. Press Delete key repeatedly multiple times

**Expected behavior**
The Delete key should not be sticky. It should only delete when it's pressed, and once it's released it should stop.

**Screenshots**
https://photos.app.goo.gl/Q3WwKdd8m93Lbict5

---

**Android:**
 - Device: [Nexus 5]
 - OS: [Android 6.0.1]
 - Keyman version [12.0.40.74]
 - Target application: [Keyman for Android]

---
 
**Keyboard**
 - Keyboard name (tested): [Krung, EuroLatin (SIL) or Khmer Angkor]
 - Keyboard version: [1.0, 1.8.1, 1.0.6]
 - Language name: [Krung, English, Khmer]

**Additional context**
This does not always happen though. To reproduce, you may try it for couple of times.

**Comment by darcywong00** [comment]
I still can't get a consistent repro.
But I did experience this with Khmer Angkor clicking away on the default layer. The console halted with a message
"No base key exists for the subkey being executed: '`default-T_17D2_1787`", the keyboard fell back to SIL EuroLatin, and kept deleting the context.

**Comment by darcywong00** [comment]
I had another repro involving backspace and globe key where the globe key failed to activate the picker menu, and the backspace kept deleting the context.
It's not fully repeatable though...

**Comment by jahorton** [comment]
We've got a mitigation patch in that should help reduce the severity and frequency of the error.  It may not be a full fix though, but without a reliable repro, there's not much more we can do at this time.

I'm leaving the issue open for now, pending more details should the issue arise again.

**Comment by mcdurdin** [comment]
I am hoping that Sentry error capture will allow us to find the trigger for this because I am guessing it relates to a Javascript error that leaves things in a funny state.

**Comment by darcywong00** [comment]
More details from a community forum user who experiences this
https://community.software.sil.org/t/delete-key-is-still-sticky/5296/1

> I was typing one long paragraph and another shorter one in the local language about Gambia, in Google Notebook app. Then as I went a step back to make some corrections, the backspace key kept deleting text as I they key was pressed down.

> It doesn’t involve the suggestion banner.

### Configuration
App in use: Notebook by Google
Keyman version: 14.0.280
Android version: 8 (Oreo)

Here is the text I typed:
*** STARTS HERE ***
Gambia ìkaan̄ ìkike mfufuk mèlek owuwa ofifi ido me Afirika agan̄ Ichep-ura; mfuduk ògbaan̄ me lek inyam-ene. Mbubek ya ore achubọk inu òrọrọ ibe ebi uket-chieen̄ echili ijọn̄-mkpulu [colony] me agan̄ Okwaan̄ Gambia ya. Adasi ebi ìkakaan̄ ijọn̄-mkpulu me agan̄ ya ìre ebi Pọtugalu. Me emen mgbọ ya, ekigwen agan̄ ya ibe ìre ‘‘A Gâmbia’’. Ike mgbọ okije, me 25 Mêe 1765, Gambia onenikana ikup me irak mkpulu Ijọn̄-ubọọn̄ Biriten. Mgbọ ya si ke ebi mkpulu Biriten echubọk ibọkọ ere ya ikikpulu mè ichili . Me 1965, Gambia îkaan̄ lek me mgbọ Dawda Jawara orebe ogwu ibot mkpulu; îkoulu ido ya mege inire 1994 mgbọ Yahya Jammeh obọkọbe ido ya ikikpulu sa me mbin akọn̄ kpegwook eje geege. Me Jenuwari 2017, Adama Barrow înikana ogwu ibot mkpulu ido òso ita, me mgbọ îtimbe ikpan̄ Jammeh me orirọ igobo ebi ibot mkpulu eyi Disemba 2016. Me adasi mgbọ, Jammeh îchieek , mè iyaka inigwu ejit ikana ibe ọmọ ìkachieek; eya onenisa ufialek ògbaan̄ me lek ikpa ikan mkpulu ido itap me ido ya, mege ebi akọn̄ ECOWAS ejibibe inin̄ lek ikọ ya, mè isa me ikeya ilap ọmọ isan̄a me ido ya.

Ugwem mbubek ido ya ìchubọk ibieen̄ me lek iwop-uko, ọkọ mun̄ mè . Me acha 2015, irek akọp ini mè jeeta mè okpọkọ gweregwen me efit (48.6%) me lek ebi ìluk me ido ya eluk me ugbọọri. Me agan̄ , ugbọọri îmin ire lek akọp irek jaaba me efit (70%).
*** ENDS HERE ***

> I was in the second paragraph, and went to correct something in the first, when the issue arose.

**Comment by rc-swag** [comment]
@darcywong00  Can you write a User Test Spec format for steps reproduce then we can ask the test team to see if they can repo.
