### ISSUE TITLE
[ios] When starting Keyman for the very first time, the banner is blank

### ISSUE THREAD

**Issue by rfaramir** [keymanapp/keyman#1933]
When starting Keyman for the very first time, the banner is blank

I cannot reproduce this, yet

**Expected behavior**
Either no banner (for a language with no dictionaries downloaded) or a banner with suggestions (if there is a dictionary)

**Screenshots**
![image](https://user-images.githubusercontent.com/45110266/62580431-bb021c80-b86b-11e9-9bb1-78769d361121.png)

---
 - Device: iPhone 7
 - OS: iOS version = 12.3.1
 - Keyman version 12.0 beta (very first)
 - Target application: Keyman

**Comment by jahorton** [comment]
We haven't seen this in testing for reproduction since the initial pre-beta test; we'll assume this has been fixed by more recent work.
