### ISSUE TITLE
[ios] Switching back into Keyman led to a blank OSK

### ISSUE THREAD

**Issue by rfaramir** [keymanapp/keyman#1938]
Switching back into Keyman (from System Settings?) led to a blank OSK (the keys still appeared to work, they just didn't show):

1. I have not reproduced, yet

**Expected behavior**
The keyboard should show up.

**Screenshots**
![image](https://user-images.githubusercontent.com/45110266/62653528-5f936580-b923-11e9-9126-69da227da043.png)

---
 - Device: iPhone 7
 - OS: iOS version = 12.3.1
 - Keyman version 12.0 beta (very first)
 - Target application: Keyman

**Comment by mcdurdin** [comment]
No repro in recent builds
