### ISSUE TITLE
[ios] Switching back out and in again led to a wrongly sized OSK

### ISSUE THREAD

**Issue by rfaramir** [keymanapp/keyman#1939]
Switching back out and in again led to a wrongly sized OSK

**To Reproduce**
1. I have seen this but have not yet reproduced it consistently

**Expected behavior**
The OSK should be present with switching back in

**Screenshots**
![image](https://user-images.githubusercontent.com/45110266/62653696-ba2cc180-b923-11e9-8828-0cabf69b586c.png)

---
 - Device: iPhone 7
 - OS: iOS version = 12.3.1
 - Keyman version 12.0 beta (very first)
 - Target application: Keyman

**Comment by jahorton** [comment]
This can often still be seen when using keyboards without a predictive model.  Changing keyboards or rotating the device will immediately remedy the issue, so it's easy to work around - it's only an issue immediately when re-entering the app.
