### ISSUE TITLE
[ios] Banner is visible even for keyboards that have no dictionaries

### ISSUE THREAD

**Issue by rfaramir** [keymanapp/keyman#1940]
Banner is visible even for keyboards that have no dictionaries

**To Reproduce**
1. I used to see this, but haven't recently

**Expected behavior**
When there is no dictionary, there should be no banner shown.

**Screenshots**

---
 - Device: iPhone 7
 - OS: iOS version = 12.3.1
 - Keyman version 12.0 beta (very first)
 - Target application: Keyman

**Comment by mcdurdin** [comment]
No repro in recent builds
