### ISSUE TITLE
[iOS] Perhaps a dictionary should be pre-loaded

### ISSUE THREAD

**Issue by rfaramir** [keymanapp/keyman#1942]
It's frustrating that a new feature is present, but nothing seems different (other than Settings) until a dictionary is downloaded. English MTNT model is not installed by default. Perhaps it should be?

**Describe the solution you'd like**
Install English MTNT model by default, like the default keyboard. 

**Describe alternatives you've considered**
 - Making a 'toy' dictionary installed by default, just so people can see it in action.
 - Making a different language dictionary installed by default, so people can switch to it to see the new feature, but they won't be bothered by it being foisted upon them right away.
 - Making the words they type into an ever-expanding dictionary that is immediately used. (Future feature not doable now.)

**Product context**
 - Device: iPhone 7
 - OS: iOS version = 12.3.1
 - Keyman version 12.0 beta (very first)
 - Target application: Keyman

**Comment by darcywong00** [comment]
From the Aug 27 Predictive-text planning meeting, we'll want the mobile apps to include `nrc.en.mtnt.model.kmp` and silently install the package on launch. This also involves updating the package installer to add a mode that skips the welcome.htm page.
