### ISSUE TITLE
[ios] Can still delete a keyboard from the picker by swiping left.

### ISSUE THREAD

**Issue by rfaramir** [keymanapp/keyman#1948]
One can still delete a keyboard from the picker by swiping left.

**To Reproduce**
1. Click on the 'Globe'
2. Swipe on a keyboard
3. See error  (hmmm, actually I can't duplicate this with either real  device or simulator)

**Expected behavior**
What the Globe brings up is meant to be a Switcher ONLY. Not a place to add or delete keyboards, so deleting by swiping should not be possible.

**Screenshots**

---
 - Device: iPhone 7
 - OS: iOS version = 12.3.1
 - Keyman version 12.0 beta (very first)
 - Target application: Keyman

**Comment by jahorton** [comment]
I'm not getting this behavior either; I've tried on the Simulator and on a real device.  I think this is already fixed.

**Comment by jahorton** [comment]
Found it - this is only accessible on the version shown from the Get Started Menu - the version that should be permanently removed once we move updates properly.
