### ISSUE TITLE
[ios] Subtext on Settings shows "1 languages installed" instead of "1 language installed"

### ISSUE THREAD

**Issue by rfaramir** [keymanapp/keyman#1950]
Subtext on Settings shows "1 languages installed" instead of "1 language installed"

**To Reproduce**
1. Be sure to have only one language installed (multiple keyboards of one language is ok)
2. Click on Settings
3. See error

**Expected behavior**
The subtext on the item named "Installed Languages" should be "1 language installed".

---
 - Device: iPhone 7
 - OS: iOS version = 12.3.1
 - Keyman version 12.0 beta (very first)
 - Target application: Keyman

**Comment by jahorton** [comment]
This has already been fixed as of the current state of the Beta branch.  Granted, it says "one language" instead of "1 language," but the point stands.
