### ISSUE TITLE
[Android] Nav bar dropdown menu labels not aligned properly

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#1962]
From #1904:

> 4. [Menu] The popup menu labels are not aligned horizontally. Looks ugly.

In personal investigations, I don't see a built-in way to address this.  It may require creating a custom subclass for use by menu items that would allow us to emulate alignment.

**Comment by darcywong00** [comment]
Looking to repro.
The menu alignment in the current beta seem fine

![menu labels](https://user-images.githubusercontent.com/7358010/63253980-146f4000-c29d-11e9-8ca3-4c7be0a0ec5c.png)

**Comment by darcywong00** [comment]
On Nokia 3 device, the "i" icon (re-used from keyboards info icon) is larger than the other menu icons.

This is tied to pixel-density of the device

**Comment by darcywong00** [comment]
Fixed by #2030 in master
