### ISSUE TITLE
bug(android/browser): Embedded Browser input extremely laggy

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#1963]
From #1904:

> 8. In Keyman Browser, typing is horribly slow, seconds per keystroke.

Just load up the browser, swap to the Keyman keyboard, and note how all typing is slowed to a crawl.

---

I've done some personal investigation on this one, and it looks like a possible doozy.

You'll want to look at KMManager.java, near line 1938.  Function `insertText(final int dn, final String s, final int dr)` for `SystemKeyboard`.

The obvious point of failure:
```
ExtractedText icText = ic.getExtractedText(new ExtractedTextRequest(), 0);
```

This line is always receiving `null`; for whatever reason, the internal system calls to get context are _always_ timing out within the embedded browser for our system keyboard now.  (I stepped through some of the Android library code to verify that this is the case; it's not that the context has "become invalid.")

My gut tells me that perhaps some of the recent changes to context-handling are actually somehow used or called by the system's API, causing a deadlock leading to the forced timeouts.  (If the system needs our code to respond to get context, but our code was calling in order to manage context within `insertText`...)  If so... where to look?

**Comment by darcywong00** [comment]
I'm trying to characterize this issue:

### Configuration
Keyboard: SIL EuroLatin
Lexical model: Not installed

* From the browser omnibar, typing seems normal.

* Typing in the Google search bar (the default loaded page) is horribly slow.
* Typing in another site's text field (https://www.ironspider.ca/forms/textfields.htm) was also horribly slow.

**Comment by darcywong00** [comment]
> My gut tells me that perhaps some of the recent changes to context-handling are actually somehow used or called by the system's API, causing a deadlock leading to the forced timeouts. (

If it's any consolation, typing in the browser on the legacy Keyman for Android 2.8.300 is just as sluggish. Same for one of the Keyman 11 builds.

**Comment by darcywong00** [comment]
We took a dive into the Profiler, and there's a 2 second timeout on InputConnectionWrapper.getExtractedText.

Since users aren't reporting this, we'll defer the issue. Possibly split the browser into a separate app where it can be optimized.

**Comment by jahorton** [comment]
> We took a dive into the Profiler, and there's a 2 second timeout on InputConnectionWrapper.getExtractedText.

So nothing new, then?  Does sound like it's a rough one.

**Comment by darcywong00** [comment]
Taking a look this sprint (P8S4) to see if the performance will affect keyboard search within a WebView

**Comment by darcywong00** [comment]
Testing in Keyman 12.0.4211 stable

1. Enable Keyman as a system keyboard
2. Hit globe button and bring up EuroLatil (SIL) info page
3. The help link launches a WebView to help.keyman.com
4. Edit the URL to a page with an [input field](https://darcywong00.github.io/examples/form.html)
5. With Keyman as a system keyboard, I can type in the text field without lag

**Comment by darcywong00** [comment]
This also impacts the 14.0 keyboard search which uses an similar embedded WebView

**Comment by darcywong00** [comment]
After using the Android studio profiler, I've narrowed down the call to KMManager.insertText
```
          // Delete any existing selected text.
          ExtractedText icText = ic.getExtractedText(new ExtractedTextRequest(), 0);
          ...
```

**Comment by darcywong00** [comment]
Possible explanation from [SO](https://stackoverflow.com/questions/40650643/timed-out-waiting-on-iinputcontextcallback-with-custom-keyboard-on-android)

> So this seems to be a "bug" introduced by Android 7.0 (maybe related to the new web client). The bug simply is a custom keyboard in the same process as `WebView` will give issues with input fields. The solution is to put the activity with `WebView(s)` in a seperate process.


I tried to put the WebBrowserActivity in a separate process in AndroidManifest.xml, but Chromium gives an exception
> Caused by: java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377
        at org.chromium.android_webview.AwBrowserProcess.a(PG:40)
