### ISSUE TITLE
[Android] Versioning info on Splash

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#1964]
From #1904:

> 9. Starting Keyman, the version info scrolls into view for a moment then disappears again. Should be visible on splash always.
    See [Starting Keyman - version text shows and disappears.mp4](https://drive.google.com/a/sil.org/file/d/1k6sMQ23Pa9sogmZVS-6Hs6YJf_UmWq9x/view?usp=sharing)

**Comment by darcywong00** [comment]
The splash screen was added in #1511. 

Due to Android limitations, displaying version text on the splash screen involved adding an artificial delay in the startup activity. In the PR, it was decided to not use the delay and leave the version info out of the splash screen.

**Comment by darcywong00** [comment]
Fixed by #2030 in master
