### ISSUE TITLE
Add setting to turn off key preview / banner in Keyman for iOS

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#197]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Tuesday Jun 13, 2017 at 04:41 GMT_
_Originally opened as https://github.com/sillsdev/keyman/issues/61_

----

**Comment by jahorton** [comment]
We have plans for this space in 12.0.

**Comment by jahorton** [comment]
This has since been addressed; see #3911.
