### ISSUE TITLE
[Developer] Longpress keys stay after being triggered

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#1971]
**Describe the bug**
Keys for longpress stay after being triggered when testing a touch keyboard layout on Chrome.

**To Reproduce**
1. Go to the 'Build' tab ini 'Keyman Developer' 
2. Click on 'Test Keyboard on web' and then 'Open debugger in local browser'
3. You are now taken to Chrome where you can start testing the touch layout.
4. Press any available longpress key
5. See error

**Expected behavior**
The longpress keys should disappear after the expected character is output.

**Screenshots**
![image](https://user-images.githubusercontent.com/28331388/62909938-c80d9700-bda8-11e9-92ff-0fb1d6ee7acb.png)

---

**Keyman Developer:
 - OS: [Windows 10 Pro 1903]
 - Keyman Developer version: [12.0.10.0]
 
---
 
**Keyboard**
 - Keyboard name: [basic_kbdfar]
 - Keyboard version: [1.0]
 - Language name: [Persian (Standard) Basic]
 - In development at https://github.com/keymanapp/keyboards/pull/835

**Comment by LornaSIL** [comment]
When I test using my Android phone (not using the Chrome simulator) the longpress displays properly and behaves properly after selecting a longpress key.

**Comment by jahorton** [comment]
It turns out this was linked to the same (side) bug fixed in #2013; it no longer appears on the Developer test page.
