### ISSUE TITLE
[Developer] Support "less presumptuous" model.ts files

### ISSUE THREAD

**Issue by eddieantonio** [keymanapp/keyman#1973]
**Is your feature request related to a problem? Please describe.**

Currently, to define a lexical model, you need to define a `model.ts` file. This is the template for a `model.ts` file:

```typescript
import LexicalModelCompiler from "@keymanapp/keyman-developer-lexical-model-compiler";

(new LexicalModelCompiler).compile({
   format: "<model type goes here",
   // model arguments go here
});
```

This format is problematic for a few reasons:

 1. the `import` is based on a very particular namespace, which we will have to maintain constant.
 2. It instantiates an object, only to run a single method on that object. Calling this method results in side-effects, that are presumably desirable. Currently, it looks in the folder and reads the `.model.kps` file to eventually compile the model source code and output it to the `build/` folder. However, every model.ts file in the lexical-models repository _must_ call compile.
 3. I wrote this example from memory, and I have no idea if typed the import name correctly 😂 

Because the file is dependent on the behaviour of the import, if I just want to compile the model, without consulting the `.kps` file, I can't do that. (say I _just_ want to compile the model to JavaScript, without making a package).

**Describe the solution you'd like**

We support an additional, simpler `model.ts` file format. One that doesn't require getting an import right, one that doesn't depend on the internal API of the `LexicalModelCompiler`, one that doesn't depend on side-effects.

Here's the template I propose:

```typescript
const source: LexicalModelSource = {
  format: '<model format>',
  // parameters go here
};
export default source;
```

As a concrete example, this is a complete minimal wordlist `model.ts`:

```typescript
const source: LexicalModelSource = {
  format: 'trie-1.0',
  sources: ['wordlist.tsv']
};
export default source;
```

Note: I'm not suggesting we remove support of the `(new LexicalModelCompiler).compile()` way of doing it!

**Additional context**

This will make writing the tutorial, where we're distinguishing between developing and packaging/distribution, a lot easier! 😄 

I have a crude example working in an alternate branch:

https://github.com/keymanapp/keyman/blob/developer-alternate-model-definition/developer/js/sample-model.ts

https://github.com/keymanapp/keyman/blob/developer-alternate-model-definition/developer/js/model-compiler.ts

Run `npx ts-node model-compiler.ts sample-model.ts` to see it working!

---

@mcdurdin @jahorton do you have any opinions/concerns?

**Comment by mcdurdin** [comment]
I am not very comfortable with the current compiler design; it was a thought experiment as much as anything and I agree that the side-effects and dependencies are complicated, as well as the unnecessary linking of build and distribution. I would support splitting the build and package components as you describe.

**Comment by eddieantonio** [comment]
TODO to close this issue:

 - [ ] Implement support for this format in `developer/js` #1983 
 - [ ] Have the lexical models repo compile models in this format in addition to the old format
 - [ ] Migrate all of the old format models to the new format in lexical-models

**Comment by mcdurdin** [comment]
Suggest we stop supporting the old format as it will make our life easier going forward. No need for two ways to do it before we even release the first stable version :)
