### ISSUE TITLE
[Developer] Prepare KMLMP in same way as KMLMC

### ISSUE THREAD

**Issue by eddieantonio** [keymanapp/keyman#1998]
The package compiler in `developer/js`  should be distributed much like the lexical model compiler. @mcdurdin its input should just be the XML file, right? And it produces a `.kmp`?

**Comment by mcdurdin** [comment]
> @mcdurdin its input should just be the XML file, right? And it produces a `.kmp`?

Correct. The input is the `.model.kps` file (which will refer to other contained files) and the output is `.model.kmp` (a zip archive with `.kmp` extension). It should probably also warn in the documentation that for now it is intended for use with lexical models only (it doesn't generate the `kmp.inf` file needed for older versions of Keyman).
