### ISSUE TITLE
iPhone X and XS:  Keyboard Height too small

### ISSUE THREAD

**Issue by chandrab699** [keymanapp/keyman#2003]
**Describe the bug**
Keyman keyboard height is smaller in iOS for iPhone X and XS than the system keyboard and 3rd party keyboard

**To Reproduce**
Install Keynounce (3rd keyboard in iOS devices) and Keyman. Compare the height of the keyboards. or see the images attached to the bug report

**Expected behavior**
Keyman keyboard should be as tall as system keyboard (if allowed) or at least as tall as allowed for 3rd party keyboards.

**Screenshots**
Please see the attached screenshots, keyman, system keyboard and keynounce keyboard in iPhone XS
![IMG_2571](https://user-images.githubusercontent.com/30884806/63798401-9d0a6380-c8cf-11e9-93fd-4bd8509e2688.PNG)
![IMG_2569](https://user-images.githubusercontent.com/30884806/63798402-9d0a6380-c8cf-11e9-9858-8fa69add1a39.PNG)
![IMG_2570](https://user-images.githubusercontent.com/30884806/63798403-9da2fa00-c8cf-11e9-98f9-7b5af34f8657.PNG)

**iPhone/iPad/Android (please complete the following information):**
 - iPhone XS
 - iOS 12.4
 - Keyman version 12.0.11
 - Target application: SAFARI or any apps

**Comment by jahorton** [comment]
At present, the predictive text bar is implemented as part of the system keyboard; the combined size is the same, which required reducing the scale of the keys at this time.

It's not a simple thing to increase the keyboard's height by a constant size from the default with what iOS gives us, unfortunately, at least as far as we've been able to see at this time.  We'd love to remedy this, but for now we'll be focusing on more critical issues.

**Comment by MayuraVerma** [comment]
Between these discussions. This issue should be resolved.

With Cramped keyboard layout, keyman feels very unappealing

Please reconsider this issue as serious

https://stackoverflow.com/questions/46420488/iphonex-and-iphone-8-keyboard-height-are-different/46423340#46423340

https://craiggrummitt.com/2019/02/22/getting-the-keyboard-height/

**Comment by mcdurdin** [comment]
I agree this isn't ideal. We'll take a look.

**Comment by MayuraVerma** [comment]
@mcdurdin @jahorton 

Please look at these two references. It's full discussion on how the keyboard size is resolved. 

Please resolve this.

https://stackoverflow.com/questions/46420488/iphonex-and-iphone-8-keyboard-height-are-different/46423340#46423340

https://craiggrummitt.com/2019/02/22/getting-the-keyboard-height/

**Comment by MayuraVerma** [comment]
https://stackoverflow.com/questions/55469514/ios-custom-keyboard-increase-uiinputviewcontroller-height

Based on Developer Code Level ticket:

1. add your buttons to a UIView (say keysView)
2. add the keysView to the UIInputViewController's view.
3. Add the constraint as in the question
4. Make keysView.frame the same as self.view
5. Add at least one constant to one of the buttons to keysView

Now you should have an expanding keysView which is as high as the self.view.

Full code:
```
#import "KeyboardViewController.h"

@interface KeyboardViewController ()

@property (nonatomic, strong) UIButton *nextKeyboardButton;

@end

@implementation KeyboardViewController
- (void)viewDidLoad {
    [super viewDidLoad];
    // (1)
    UIView *keysView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 100, 100)];
    // (3)
    NSLayoutConstraint *keyboardHeightConstraint = [NSLayoutConstraint
                                                    constraintWithItem:self.view
                                                    attribute:NSLayoutAttributeHeight
                                                    relatedBy:NSLayoutRelationEqual
                                                    toItem:nil
                                                    attribute:NSLayoutAttributeNotAnAttribute
                                                    multiplier:0.0
                                                    constant:310];
    [keyboardHeightConstraint setPriority:UILayoutPriorityDefaultHigh];
    [self.view addConstraints:@[keyboardHeightConstraint]];

    self.nextKeyboardButton = [UIButton buttonWithType:UIButtonTypeSystem];

    [self.nextKeyboardButton setTitle:NSLocalizedString(@"Next Keyboard", @"Title for 'Next Keyboard' button") forState:UIControlStateNormal];
    [self.nextKeyboardButton sizeToFit];
    self.nextKeyboardButton.translatesAutoresizingMaskIntoConstraints = NO;

    [self.nextKeyboardButton addTarget:self action:@selector(advanceToNextInputMode) forControlEvents:UIControlEventTouchUpInside];

    [keysView addSubview:self.nextKeyboardButton];
    // (5)
    NSLayoutConstraint *nextKeyboardButtonLeftSideConstraint = [NSLayoutConstraint constraintWithItem:self.nextKeyboardButton attribute:NSLayoutAttributeLeft relatedBy:NSLayoutRelationEqual toItem:keysView attribute:NSLayoutAttributeLeft multiplier:1.0 constant:0.0];
    NSLayoutConstraint *nextKeyboardButtonBottomConstraint = [NSLayoutConstraint constraintWithItem:self.nextKeyboardButton attribute:NSLayoutAttributeBottom relatedBy:NSLayoutRelationEqual toItem:keysView attribute:NSLayoutAttributeBottom multiplier:1.0 constant:0.0];
    [keysView addConstraints:@[nextKeyboardButtonLeftSideConstraint, nextKeyboardButtonBottomConstraint]];
    // (4)
    keysView.frame = CGRectMake(0, 0, self.view.bounds.size.width, self.view.bounds.size.height);
    // (2)
    [self.view addSubview:keysView];
}

- (void)dealloc {
    self.nextKeyboardButton = nil;
}

@end
```

**Comment by jahorton** [comment]
Thanks for the great references; I wish I had found them when I had been working on the keyboard during development of version 12.  Never figured out the right search terms.

We'll be taking a look at this soon.

**Comment by MayuraVerma** [comment]
@jahorton OP points to iPhone X and XS, but this is an issue across all iPhones from SE, 6, 6S, 7, 8... et al

Please compare the height of the "Stock US English with prediction" and "Keyman with prediction" in any device.

I have not checked in iPad's. I am presuming it's same issue there as well.

**Comment by jahorton** [comment]
It will be.

**Comment by MayuraVerma** [comment]
Newer alpha versions are not available in the testflight app. Is it possible to try the alpha version with this fix, somehow?

**Comment by mcdurdin** [comment]
> Newer alpha versions are not available in the testflight app.

13.0.43 should now be available in testflight (we had a build agent fall over during the New Year period and had to commission new hardware, which delayed the deployment to TestFlight -- iOS has by far the most complex and fragile deployment process of any of the platforms we support...)

**Comment by MayuraVerma** [comment]
Now it is showing the newer versions.
