### ISSUE TITLE
How to develop lexical model

### ISSUE THREAD

**Issue by chandrab699** [keymanapp/keyman#2004]
How to develop lexical model?

Is it part of the keyboard or keyman web or any website of our choice?

If the lexical model is part of the website, then can it learn from the user keyboard usage on statistics of the words used?

**Comment by darcywong00** [comment]
> How to develop lexical model?

The documentation for creating lexical models is currently in-work in PR [#32](https://github.com/keymanapp/help.keyman.com/pull/32) and will be published on https://help.keyman.com

> Is it part of the keyboard or keyman web or any website of our choice?

Lexical models are created separate from keyboards and will managed in a separate GitHub repository
https://github.com/keymanapp/lexical-models
We'll eventually add more documentation on how lexical models are distributed.

>... then can it learn from the user keyboard usage on statistics of the words used?

From the Keyman [Roadmap](https://blog.keyman.com/2019/02/keyman-roadmap-february-2019) , that's planned for a future release Keyman 13

## Keyman 13.0 Oct 2019 – Feb 2020
* Predictive Text
   * Learning models
