### ISSUE TITLE
Suggestions: Keyman version 12 in Windows 10

### ISSUE THREAD

**Issue by chandrab699** [keymanapp/keyman#2005]
**Describe the bug**
Word suggestion not available in Windows 10

**To Reproduce**
Install Keyman 12 beta in Windows 10

**Expected behavior**
Keyman word suggestion is not available in Windows 10

**Keyman Desktop, Keyman for macOS, Keyman for Linux (please complete the following information):**
 - OS: Windows 10 1903
 - Keyman version: 12.0.19.0
 - Target Application: Any

**Comment by darcywong00** [comment]
In Keyman 12, the word suggestion feature is not implemented for the desktop platforms.

From the Keyman [Roadmap](https://blog.keyman.com/2019/02/keyman-roadmap-february-2019/)
## 12.0 - Mar 2019 - Sep 2019
* Predictive text
   *  Android, iOS and web platforms initially

I'm not sure which future version of Keyman will bring that to Windows 10.

**Comment by mcdurdin** [comment]
This will appear on the roadmap in a future version of Keyman but we have no current plans to implement it.
