### ISSUE TITLE
Keyman Developer - sometimes message window does not appear on compile

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#201]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Tuesday Jun 13, 2017 at 07:39 GMT_
_Originally opened as https://github.com/sillsdev/keyman/issues/71_

----

**Comment by mcdurdin** [comment]
Duplicate of #756
