### ISSUE TITLE
Keyman Developer - Update windowslanguages list to latest from MS

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#203]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Friday Jun 16, 2017 at 03:55 GMT_
_Originally opened as https://github.com/sillsdev/keyman/issues/76_

----

https://msdn.microsoft.com/en-us/library/cc233982.aspx lists latest languages. Note that any with langid 0x1000 don't need to be included, so really there are only a handful of new ones.

See `windows/src/global/delphi/general/WindowsLanguages.pas`

Reference: https://community.software.sil.org/t/keyman-developer-burmese-windows-langid/177

**Comment by mcdurdin** [comment]
Closing - as we now recommend and work with BCP 47 for all new keyboard work, this is not really very relevant.
