### ISSUE TITLE
[Android] Some keyboards emit multiple characters on 12.0 on longpress

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#2034]
**Describe the bug**
With the fv_ojibwa (v9.2) keyboard, when you longpress on `[.]` (numeric `123` layer), and select a subkey (e.g. `["]`, then `."` is emitted instead of `.`, and the following warning appears in the console:

```
keyman.js:20427 No base key exists for the subkey being executed: 'undefined-U_0022'
keymanweb.executePopupKey @ keyman.js:20427
executePopupKey @ keyboard.html:299
(anonymous) @ VM37:1
```

**To Reproduce**
1. Install fv_ojibwa 9.2 keyboard, under 'Ojibwa, Northwestern' language
2. Press `123` to activate numeric layer
3. Longpress on `.` to popup long press menu
4. Select any subkey.
5. See both `.` and selected subkey value emitted.

**Expected behavior**
Expect only the subkey value to be emitted.

**Screenshots**
![image](https://user-images.githubusercontent.com/4498365/64143459-7611db80-ce53-11e9-9701-9b6ff1012af5.png)

---

**Android:**
 - Device: Nokia 3
 - OS: Android 9
 - Keyman version 12.0 beta

---
 
**Keyboard**
 - Keyboard name: fv_ojibwa
 - Keyboard version: 9.2
 - Language name: Ojibwa, NorthWestern

**Additional context**
This issue did not arise either in KeymanWeb 12.0.78 or Keyman for iOS 12.0.27.

**Comment by mcdurdin** [comment]
(note the screen shot shows me having a second go at pressing `"` :) the results of the first go are already visible.)

**Comment by jahorton** [comment]
This sounds vaguely related to some of the work on #2013, which resolved a different issue with subkeys lacking info about a base.  It's possible that the fixes from #2013 were necessary for this issue to surface; the point of the error reported here seems different.

**Comment by darcywong00** [comment]
I'm unable to repro on my Moto device with 12.0.4082 beta

![moto](https://user-images.githubusercontent.com/7358010/64144312-2b399900-ce3e-11e9-8377-1cc59fbddad8.png)

**Comment by mcdurdin** [comment]
And ... now I can't repro either. Will reopen if I get a repro.
