### ISSUE TITLE
[Android] 'Close Keyman' button is not configurable for other apps that use Keyman Engine

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#2035]
**Describe the bug**
The `Close Keyman` button in the language switcher is not configurable or translatable, which is necessary for 3rd party apps that use this.

This is part of a larger issue of i18n and customisability of strings in Keyman Engine. I suggest we look at addressing this as part of the i18n work in 13.0 or 14.0.

**Screenshots**
![image](https://user-images.githubusercontent.com/4498365/64143864-3b10a780-ce55-11e9-8c5c-8eef5cad6ed0.png)

---

**Android:**
 - Device: Nokia 3
 - OS: Android 9
 - Keyman version 12.0.x

**Comment by darcywong00** [comment]
The string comes from /android/KMEA/app/src/main/res/values/strings.xml

```
<string name="label_close_keyman" translatable="false">Close Keyman</string>
```

Can an external app define
values-cre/strings.xml to localize the strings?

**Comment by darcywong00** [comment]
This will be done as part of #809
