### ISSUE TITLE
feat(android,ios): Firstvoices: Use the metadata in kmp.json to associate with languages and versions

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#2036]
**Is your feature request related to a problem? Please describe.**

FirstVoices Keyboards currently does not make use of the BCP 47 language tags in the kmp data included with keyboards. In the future, we'd like to make this possible, and reduce the amount of data required in the source keyboards.csv file for correct deployment of the app.

**Comment by darcywong00** [comment]
Since we haven't been updating the keyboard versions listed in keyboards.csv, it leads to confusion with users on whether the latest keyboards updates are installed.

Things to consider:
* Region isn't in kmp.json so we need somewhere to populate that
* Perhaps a TODO in keyboards repo to have more checks on the csv (e.g. missing keyboards)

**Comment by darcywong00** [comment]
From A18S2 sprint planning meeting, @mcdurdin clarified (since we can't add regions to kmp.json):
Keep only the minimal fields in keyboards.csv 
* Region
* keyboard ID (the key)
* Primary language and language name

Keyboard version info should use kmp.json.

**Comment by mcdurdin** [comment]
> * Primary language and language name

This should be sourced from kmp.json where possible? AFAIK, most of the keyboards have only one language entry; the language name should always be there too.

**Comment by darcywong00** [comment]
> This should be sourced from kmp.json where possible? AFAIK, most of the keyboards have only one language entry; the language name should always be there too.


Yeah, though there's also basic_kbdcan and sil_euro_latin...

**Comment by mcdurdin** [comment]
> Yeah, though there's also basic_kbdcan and sil_euro_latin...

So those are two examples where we need the extra metadata of default language. There may be others too, but not too many hopefully.

**Comment by darcywong00** [comment]
ok, turns out basic_kbdcan has a first language of `fr-CA`.
So maybe just sil_euro_latin needing to define default `en`. Do we want that in the keyboards.csv file or in the FV app code?

**Comment by mcdurdin** [comment]
> Do we want that in the keyboards.csv file or in the FV app code?

Per discussion on Slack, I think we put that in the FV app code. (Let's also put in a hard-coded value for basic_kbdcan, so that we don't accidentally end up with it swapping in the future.)

**Comment by darcywong00** [comment]
As of #11943, FirstVoices for Android 18.0
* Uses kmp.json for languages and versions
* USes keyboards.json for region information

Spinning a separate PR for iOS to make similar changes.
