### ISSUE TITLE
[Developer] Modals dialogs pop-under the window, which disallows interaction with Keyman Developer 12 Beta

### ISSUE THREAD

**Issue by eddieantonio** [keymanapp/keyman#2040]
**Describe the bug**
When I open a modal dialog (e.g., "Project Settings"), it pops-up, then disappears under the rest of the developer application. Because it's a _modal_ dialog, it prevents interaction with the main application, unless one fidgets around creatively with Window management.

**To Reproduce**
1. Create a new project from the default template.
2. Click on 'Project' » 'Project Settings..."
3. Modal will pop _under_ the window, making it inaccessible.

**Expected behavior**
I should see the modal _above_ the main developer window!

---

**Keyman Developer**:
 - OS: Windows 7
 - Keyman Developer version: 12.0.23.0 [beta]

Hilariously enough, this bug manifests itself when I try to access 'Help' » 'About', as that modal dialog is affected by this bug too!

**Additional context**
Note: I am using this on a three monitor setup ^.^

**Comment by mcdurdin** [comment]
This issue occurs consistently, I believe, after a tooltip is displayed in the web browser. It may related to #1693. It happens only on Windows 7 and Windows 8.

**Comment by mcdurdin** [comment]
Resolved in 12.0.36
