### ISSUE TITLE
[Developer] New project wizard incorrectly inserts region code

### ISSUE THREAD

**Issue by DavidLRowe** [keymanapp/keyman#2046]
**Describe the bug**
New project wizard incorrectly inserts region code

**To Reproduce**
1. Project, New Project, Basic, OK, to bring up New Project dialog.
2. Add... brings up Select BCP 47 Tag dialog
3. For Language tag field, enter "wwa", and program correctly assigns BCP 47 code of "wwa-Latn"
4. However, when project is created, the .keyboard_info and .kps files both have "wwa-Latn-BJ" instead of "wwa-Latn"

**Expected behavior**
The BCP 47 tag in the .keyboard_info and .kps files should be "wwa-Latn", without the region subtag.

---
**Keyman Developer (please complete the following information):
 - OS: Windows 10 1903
 - Keyman Developer version: 11.0.1356.0
 
---
 
**Additional context**
I expect that this issue was the reason that the region code was included in the keyboard PR https://github.com/keymanapp/keyboards/pull/875

**Comment by DavidLRowe** [comment]
Similar behaviour for 12.0.18.0.

**Comment by mcdurdin** [comment]
Excellent report, thank you! A partial fix is on the way; a more comprehensive fix will come with our BCP 47 language picker review in 13.0.

**Comment by DavidLRowe** [comment]
Note that this also affects lexical models as well. In Developer, Project | New Project | Wordlist Lexical Model creates a .kps file with the region code added to the BCP 47 code. The result is that the keyboard cannot connect to it.

**Comment by mcdurdin** [comment]
David noted also: I found another case, where the script changed as well. (Follow
procedure in 2046, but enter "fuv" and program suggests "fuv-Arab". If
the keyboard is for a Latin script, user changes the tag to "fuv-Latn"
in the wizard. However, the output from the wizard is: "fuv-Arab-NG".)

It's quite possible that the fix in 2060 handles this latter case as well.

**Comment by mcdurdin** [comment]
I can confirm that with the fix in #2060:

* the `fuv-Latn-NG` issue @DavidLRowe noted [above](https://github.com/keymanapp/keyman/issues/2046#issuecomment-529701200) is resolved.
* the [lexical model BCP 47 code issue](https://github.com/keymanapp/keyman/issues/2046#issuecomment-529881543) is also resolved.
