### ISSUE TITLE
[Lexical Models] Functionality requirements for custom word breaker API

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#2048]
Custom word breaker API for lexical models is not currently complete.

These items should be expanded into multiple issues against relevant repos when we start work on this:

- [x] Implement in Keyman
- [x] create a valid sample in lexical-models
- [x] document the API and how to actually implement it in help.keyman.com.

_Originally posted by @eddieantonio in https://github.com/keymanapp/lexical-models/pull/54_

**Comment by eddieantonio** [comment]
Note to future implementer: get started on this quickly by reverting #2079:

    git revert 65a0e9d

**Comment by mcdurdin** [comment]
@eddieantonio is this complete with your recent work?

**Comment by eddieantonio** [comment]
> @eddieantonio is this complete with your recent work?

This was actually _almost_ completed long before. It's been undocumented, but supported, since Keyman 12. Documentation was added in Keyman 13. We just need a full example in the lexical-models repository.

**Comment by mcdurdin** [comment]
Excellent. Do you want to throw an example in and then we can draw a line under this issue?

**Comment by eddieantonio** [comment]
> Excellent. Do you want to throw an example in and then we can draw a line under this issue?

Will do. I was thinking of doing an ambitious example, but I think just one for English ASCII will suffice.
