### ISSUE TITLE
[iOS] Share via Facebook doesn't pre-fill from the Keyman app editor

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#206]
<a href="https://github.com/jahorton"><img src="https://avatars3.githubusercontent.com/u/25213402?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jahorton](https://github.com/jahorton)**
_Monday Aug 07, 2017 at 02:27 GMT_
_Originally opened as https://github.com/sillsdev/keyman/issues/140_

----

Selecting the "post to Facebook" option does not attempt to post what has been pre-typed within the Keyman app, instead forcing the user to start from a blank slate.

Possibly relevant links:

- https://developers.facebook.com/docs/apps/review/prefill
- https://developers.facebook.com/docs/sharing/ios
- https://developers.facebook.com/docs/sharing/reference/share-dialog

**Comment by mcdurdin** [comment]
N/A
