### ISSUE TITLE
[Developer] New Project touch layout error

### ISSUE THREAD

**Issue by DavidLRowe** [keymanapp/keyman#2062]
**Describe the bug**
New Project touch layout, shift layer, incorrectly produces `>` when the `.` key is pressed.

**To Reproduce**
Project, New Project, Basic
Keyboard name: xyz
BCP 47 code: wwa-Latn
OK (taking other defaults)
Click Keyboards tab at bottom, then click xyz.kmn
Click Touch Layout on left
For both "touch" and "phone" layouts, "shift" layer, the "." (K_PERIOD) key currently has the "Modifier" set to "(current layer)", which means that the `.` on the shift layer produces `>`.

**Expected behavior**
For both "touch" and "phone" layouts, "shift" layer, the "." (K_PERIOD) key
needs to have "Modifier" set to "default", so that the `.` on the shift layer produces `.`.

---
**Keyman Developer (please complete the following information):
 - OS: Windows 10 1903
 - Keyman Developer version: 12.0.26.0

**Comment by mcdurdin** [comment]
Resolved in 12.0.36
