### ISSUE TITLE
[Windows] Keyboards missing after Keyman 11 update

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#2074]
Reported from a user via email. I'll add more configuration details as they come in to aid in reproducing the issue:

-----------------------
June 6, 2019 I re-installed Windows OS and downloaded the new version of Keyman at that time. Not sure if it was updated since then.

Today (Sept 11, 2019) I installed  the Keyman v11.0.1361.0 update and my keyboards have changed. Actually, when I noticed this, I restarted my system and the keyboards changed again! Here's what I've observed:

Before updating Keyman these are the keyboards I had installed (from what I recall):
* English
* Khmer (I think I had Khmer Angkor installed)
* Ancient Greek
* [SIL Hebrew](https://software.sil.org/ezra)

After updating to Keyman v11.0.1361.0:

* English
* Khmer NIDA
* Ancient Greek
 
After restarting once:
* English
* Ancient Greek
 
After restarting a second time (I haven't tried a third time ;-):
* English
* Khmer NIDA
* Ancient Greek
 
Also, since updating the software, whenever I open the Keyman Configuration window there are no keyboards listed in the Keyboard layouts tab (see attached screenshot and notice that the small Keyman menu does list some keyboards. I haven't tried reinstalling any keyboards yet. 

One more thing, after updating Keyman I noticed that Automatically save screen shots to OneDrive wasn't working. It still didn't work after restarting my computer once. I reapplied the setting in OneDrive settings and now it is working. Both Keyman and OneDrive are located in the System Tray…could there be some connection?

![Keyman layouts issue](https://user-images.githubusercontent.com/7358010/64661429-c1894280-d46e-11e9-9b32-4114d72998ed.jpg)

FYI, the Greek Keyman keyboard I use is called Greek Polytonic Unicode

**Comment by mcdurdin** [comment]
Can we get a reproducible process on this? If so, we can investigate further -- without it, hard to know where to go with it.

FWIW, I doubt that the OneDrive issue is in any way related.
