### ISSUE TITLE
[Developer] Include Touch Layout GUI Guide on Keyman Developer Context Help

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#2089]
Split from keymanapp/help.keyman.com/issues/26 that @lssoffice created

> I had quite a difficult time finding a guide for developing a simple Touch Layout. I was directed to this link, which makes it very clear: https://help.keyman.com/developer/11.0/guides/develop/touch-keyboard-tutorial/making-touch-keyboard. Here's the original discussion about this: https://community.software.sil.org/t/multiple-longpress-options/2048/6

> It would be helpful to have this information included in 2 places:

> (link to help.keyman.com)

> Also, in the Context Help area in Keyman Developer:
> I think that especially having it in the Context Help area in Keyman Developer would help newer people to create simple keyboards without much trouble.
![Context help - Touch Layout](https://user-images.githubusercontent.com/7358010/64833724-3b553380-d609-11e9-9fe3-031dc8c2041c.png)

**Comment by mcdurdin** [comment]
See #2130 for deeper issues with the context help. A link here won't currently help because it won't be clickable. Will reschedule this for 13.0 once we fix existing systemic issues.

**Comment by mcdurdin** [comment]
@lssoffice FYI: Resolved in 12.0.37
