### ISSUE TITLE
[Developer][LMLayer] Create a package with common LMLayer type definitions

### ISSUE THREAD

**Issue by eddieantonio** [keymanapp/keyman#2092]
## The problem

The LMLayer worker as well as the lexical model compiler depend on [keyman/common/predictive-text/worker/worker-compiler-interfaces.d.ts]. This file contains types relevant to word breakers, punctuation, and other "internal" stuff that the lexical model compiler needs to generate, and the LMLayerWorker needs to evaluate.

There are also lines in the compiler like this:

https://github.com/keymanapp/keyman/blob/d6a80e6d9dca2936e50b9f75541dcba4dd043b1b/developer/js/source/lexical-model-compiler/lexical-model.ts#L5

Yuck!

It's clear that these types need to be **shared** some better way.

## The solution

Create a package containing types common to the compiler and the internal LMLayer.

### Proposed exported types:

 - Model
   * `WorkerInternalModel` (rename to `LexicalModel`?)
   * `type LexicalModelFomat = 'trie-1.0' | 'fst-foma-1.0' | 'custom-1.0'`
   * `Suggestion`
   * `Transform`
   * `Context`
   * `type SuggestionTag = 'prediction' | 'keep' | 'correction' | 'emoji'`
 - Messaging
   * `Capabilities`
   * `Configuration`
 - Word breaking
   * `Span`
   * `WordBreakingFunction`
 - Other
   * `LexicalModelPunctuation`

I may have missed some...

### How to share this package

Using Lerna, we can create one package containing all of these types. Let's call it `@keymanapp/lexical-model-types`. Then, we can link it to the appropriate subprojects:

    lerna add @keymanapp/lexical-model-types developer/js common/predictive-text

This package's types will be exported in the package.json as:

```json
{
    "types": "index.d.ts"
}
```

[keyman/common/predictive-text/worker/worker-compiler-interfaces.d.ts]: https://github.com/keymanapp/keyman/blob/master/common/predictive-text/worker/worker-compiler-interfaces.d.ts

Blocked by #2091.

**Comment by mcdurdin** [comment]
I am wondering if this refactoring can wait for 13.0? Is there any problem with postponing it?

**Comment by eddieantonio** [comment]
I can foresee one problem: if anybody depends on the "stable" definitions within the 12.0 release — especially if they define custom models and word breakers! — they will rely on definitions that we're planning to change and clean up. It's better to refactor now, than to have to maintain ugliness later!

Because of the ugliness and ad hoc nature of the internals prior to the refactor, I don't feel comfortable allowing folks to make custom models using the interfaces defined prior to the refactor.

Regardless, the preliminary work for this is done here: #2155

**Comment by eddieantonio** [comment]
Fixed in #2155.
