### ISSUE TITLE
[Developer] Use Insert Mode -> Character when dragging character to touch layout

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#2125]
From the Character Map, right clicking can set the **Insert Mode** to:
* Code (default)
* Character
* Name

It would be nice when users drag a character to the touch layout OSK for the "Character" to get inserted instead of the default code.

**Comment by mcdurdin** [comment]
This impacts a number of areas, including layout editor, osk editor, HTML content. The design probably needs revisiting because currently the option is quite buried. This looks a little too involved (given there is a workaround) to implement for late beta.
