### ISSUE TITLE
[Web] Toolbar UI rework

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#2133]
For version 12.0, we applied #2126 to make the language selections a bit more up-to-date with our backing API/databases, but some of the changes made may have been... less than ideal.  With our upcoming language-picker redesigns planned for the next stage of our roadmap, there's a chance we may need to revert the changes from #2126 before proceeding.

In particular, if we become able to differentiate between North, Central, and South America again, one of that PR's edits (to the world.png file) would need reversion, as may the region geometry definitions in kmwuitoolbar.ts.

**Comment by mcdurdin** [comment]
Dup of #2133.
