### ISSUE TITLE
[Android] Streamlining the keyboard swap operation

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#2137]
In current beta builds of Keyman for Android (12.0.4092), **any** time the keyboard picker is used to change keyboards, there are two separate calls to the embedded page's `setKeymanLanguage` function, in rapid succession.  This results in the Android app doing significant amounts of unnecessary work.

This is also likely the cause of the, uh, less-than-smooth 'animation' that occurs when swapping keyboards.  It's always looked like the keyboards were repeatedly swapping in and out a bit before stabilizing... it turns out that this is near-exactly the case.  We swap the old keyboard for the new keyboard, throw the page away for a full reload, and then we load the new keyboard again.  This results in a lot of visual artifacting that we could somewhat simply remove.

### Recommendations

Either of the following two courses of action should remedy the issue:

1. Completely nix `KeyboardPickerActivity.switchKeyboard` in its current form.  The only important thing it accomplishes is to `saveCurrentKeyboardIndex`, so skip all the wasted JS calls and store the index separately.  Let the page reload do all the work - it's already been doing it, anyway.

2. Nix `KeyboardPickerActivity.onPause` or bypass its contents if we can tell that this was directly user-triggered.  This function does have the benefit of reducing the WebView's memory footprint, though - resetting the page means that we don't keep previously-used resources loaded.

---

## Diagnosing the issue

I first noted the core detail that lead to this diagnosis when using Chrome DevTools to debug the JS side of the 12.0 stability issues.  From there, I swapped to diagnosing the reason for the dual calls on the Java side.

Upon the app's initial load:
- passes through `KMManager.pageLoaded`, `if(!InAppKeyboard.keyboardSet)`

The initial load only calls `setKeyboard` once, which is fairly natural to expect.

Without doing anything else, a keyboard swap (ex: SIL EuroLatin -> Khmer Angkor) yields the following:
- `setKeymanLanguage` call #1:  Khmer Angkor (first call does have data for the 'target' keyboard)
    - Directly called via `KeyboardPickerActivity.switchKeyboard`.
- Call #2:  `KMManager.pageLoaded`
    - … and the `!InAppKeyboard.keyboardSet` branch of the if!?
    - At least it does (re)load Khmer.

Further examination here proves that currently, each keyboard swap has two separate phases - so let's break those phases down.

---

The first uses `KeyboardPickerActivity.switchKeyboard` on the current page.  (This also registers associated models, etc.)  This also does two important-to-note, interesting things:
- it sets `.keyboardSet` to `true` 
- it calls `saveCurrentKeyboardIndex`.

**After** this operation fully completes, the picker eventually self-dismisses, triggering `KeyboardPickerActivity.onPause`.  This then calls `KMKeyboard.loadKeyboard`, which sets `KMKeyboard.keyboardSet` to `false` and _force-resets the keyboard page_.  This near-completely invalidates the first 'set', but there's one important and necessary detail that it accomplished.  (More on that later.)

Once the triggered full-page-refresh finishes, the `InAppKeyboard.pageLoaded` event fires.  This is important because it has the critical `if (!InAppKeyboard.keyboardSet)` check - and since it is now "not set" due to having literally reloaded the base page, KMEA triggers the second `setKeyboard` call that results in the second keyboard load.

Fun fact - to perform the second keyboard load, it looks up the keyboard list index value saved by `saveCurrentKeyboardIndex` - without the first call, the second would not and could not succeed!

**Comment by darcywong00** [comment]
This kind of change will require a lot more testing than what's remaining in 12.0 Beta.
Deferring to 13.0

**Comment by darcywong00** [comment]
If @safolit runs out of issues to work on, maybe she can investigate this one?
