### ISSUE TITLE
[Developer] Package Editor script error when editing model

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#2140]
While creating a guide on making lexical model packages, I ran into this:

From the Package Editor, select the "Files" tab
![image](https://user-images.githubusercontent.com/7358010/65666363-b423a900-e067-11e9-9989-629d95eda4a6.png)

With nrc.str.sencoten.model.js selected, click "Edit" (on the right half of the panel)

![image](https://user-images.githubusercontent.com/7358010/65666263-7aeb3900-e067-11e9-8ce7-74121212b5bf.png)

Also on the tab, the package description can be changed from keyboards to lexical models
> A typical package will need keyboards, fonts, and documentation...

**Comment by mcdurdin** [comment]
Fixed in 12.0.39
