### ISSUE TITLE
[Windows] Keyman sporadically stops working with Word

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#2143]
**Describe the bug**

We have now received several reports of Keyman having trouble with Word recently. This is an issue to track and consolidate these reports and try and find commonality between them.

User 1 writes [via PM](https://community.software.sil.org/t/2603):

> My keyboards are not working properly in MS Word. Keys do not type or type sometimes and not all the time. Other, un-redifined keys, such as arrows, delete, backspace also do not work while my keyboard is active. When I toggle off the keyboard, all keys work. Toggle on the keyboard and the problem recurs. Only in MS Word. They work fine in other applications.

User 2, @MakaraSok, writes [via PM](https://community.software.sil.org/t/2568):

> Khmer Angkor keyboard on the latest version of Keyman getting slow or not responsive when a key is fired
>
> My typing is kind of out of rythm and I notice that Keyman does not respond upon my keypress. It takes more than one time to type a character. This happens to every other character if not everything single one when a key is fired.

[and](https://community.software.sil.org/t/2572):

> Keyman Deskopt slow down when typing
>
> This happened to me yesterday, and again now it’s getting slower and I have to press twice to get a character out. I have to do this for each character and it slows me down tremendously.

User 3 wrote [via PM](https://community.software.sil.org/t/2460):

> Keys very slow in MS Word
>
> While in MS Word, keystrokes are very slow, delayed, or non-existant. When I disable my Keyman (turn off keyboard) keystroke return to normal. It progressively gets worse until I do a resart of my computer (which seems to be the only way to fix it). Typing will work fine in Word then it just starts to get delayed only while the Keyman keyboard is activated in Word through HotKeys.
> Restarting Keyman or MS Word or both doesn’t have any effect on the problem. It is still present when I go back to typing. I only find the problem while in Word. All other typing seems to work fine in other programs.

[and](https://community.software.sil.org/t/2470):

> Same issue after beta install
>
> Only in MS Word, 10-30 minutes after enabling my Salish Unicode keyboad with hotkeys in MS Word my typing function starts to decay. At first its delayed keystrokes then progress to only recognizing keystrokes after multiple tries. It can get so bad that I have to hit a key 5-10 times before it will display in my document.
> When I disable the keyboard through hotkeys the typing function is restored to 90%. I still have delayed display of keystrokes in my document but usually tolerable. After time goes on it does begin to decay to where I can no longer use it.
> The only fix so far is to reboot the computer.
> I have been in contact with Makara on your team. As well I sent him the keyboard.

User 4 write via [via PM](https://community.software.sil.org/t/2384):

> I use windows 10 . Words in office 16 . I type English / manglish to gel malayalam . I use tavult keyman 10 . Mozhy .
>
> What I noticed , when I write for 1/2 n hour manglish , the letters stop impressions / doesn’t get typed , then I had to restart . Seemingly the manglish efforts get fatigued .

---

**Keyman Desktop:**
 - OS: Windows
 - Keyman version: 11?
 - Target Application: Word 2016

**Comment by mcdurdin** [comment]
[Notes](https://docs.google.com/spreadsheets/u/1/d/1jFf5IAUyyiiIjA0SEMj9miU7fO_EnefBR0mpYLfikMg/edit?usp=sheets_web)

**Comment by mcdurdin** [comment]
Some research today on a machine that was exhibiting the problem. [`ITfContext::RequestEditSession`](https://docs.microsoft.com/en-us/windows/win32/api/msctf/nf-msctf-itfcontext-requesteditsession) is sometimes returning `TF_E_SYNCHRONOUS` in `phrSession` output variable. This is not an error I have seen before -- adding some monitoring to allow for a better trace of the problem.

**Comment by mcdurdin** [comment]
Continuing to track but this won't make the initial 12.0 stable release.

**Comment by orewJ** [comment]
The FIRST bindable letter at the beginning of writing does NOT bind to the next letter in my Farsi keyboard in Word 365 for Windows (the latest version).  The exact word combination in the next word registers correctly. To illustrate this anomaly, when I start writing in Word, something like this happens: ب رای برای (in RL, the first letter has not bound to the second letter, but in the second try, it binds correctly).  This anomaly is limited to Word. I have not seen the problem in text editors.

**Comment by mcdurdin** [comment]
@orewJ  I don't think what you are experiencing is related to this issue. What you are seeing may be related to the language you have associated with your keyboard. Word requires that Arabic script keyboards are associated with an Arabic language; it's not enough to simply mark the text as right-to-left. Furthermore, you must ensure that the appropriate language support is installed in Microsoft Office Language Preferences (a separate app launchable from the Start Menu).

**Comment by MakaraSok** [comment]
@mcdurdin Headsup! I was using Khmer Angkor on MS Office for more than four hours today, and I no longer experienced the out-of-rhythm when typing. It was working as normal all through.

MS Office Pro Plus 2016 version: `1910 (Build 12130.20272 Click-to-Run)`
Keyman Desktop version: `12.0.52.0`
Khmer Angkor keyboard version:  `1.0.6`

**Comment by mcdurdin** [comment]
@MakaraSok I'm not sure whether to be happy or sad 😁 . Given we no longer have a reliable reproduction of this issue, I am going to put it on hold; if it recurs we can see if we can get a repro.

**Comment by sgschantz** [comment]
@MakaraSok @mcdurdin  Can we close this? Sounds bad, but wondering if we have seen this or had reports since 2019.

**Comment by mcdurdin** [comment]
I think this is most likely resolved with some of the work we've done around the TSF plugin, so let's go ahead and close.
