### ISSUE TITLE
[Developer] character dragged to touch layout disappears

### ISSUE THREAD

**Issue by DavidLRowe** [keymanapp/keyman#2156]
**Describe the bug**
When working with the touch layout, a character dragged to a key on the layout disappears (unless you click on the character and press Enter).

**To Reproduce**
1. Open Keyman Developer (version 12.0.41.0)
2. Select New Project, Basic, OK to bring up New Project wizard
3. Enter "xyz" as keyboard name, take other defaults
4. Click on Keyboard, xyz.kmn, then Touch Layout
5. Click on the "p" on the rightmost key in the top row and delete the "p".
6. Right-click on the "a" (U+0061) in the Character Map, select Insert Mode, then select "Character" (or make sure that "Character" is selected).
7. Drag the "a" from the Character Map to the (now blank) "p" key. The key now displays "a".
8. Click on the "o" key. The "a" on the "p" key disappears.
9. Repeat step 7.
10. Click on the "a" to position the cursor there. Press Enter.
11. Click on the "o" key. The "a" stays on the "p" key.

**Expected behavior**
When I drag a character to a key, I expect it to stay there!

---

**Keyman Developer (please complete the following information):
 - OS: Windows 10 1903 (but seen on various computers)
 - Keyman Developer version: 12.0.41.0 (and previous)
 
**Additional context**
It would be nice to get this fixed for version 12 release.

**Comment by mcdurdin** [comment]
Fixed in 12.0.44
