### ISSUE TITLE
[Web][iOS][Android] Regression: Touch layout does not switch to different layout when already in non-default layout

### ISSUE THREAD

**Issue by eddieantonio** [keymanapp/keyman#2162]
**Describe the bug**

When the touch layout is in a non-`default` layout, pressing a key should be able to switch the layout to yet another non-`default` layout. However, the observed behaviour is that a key pressed in a non-`default` layout will always switch back to the  

**To Reproduce**

Let's type a "kwV" syllabic, like "ᑵ" ("kwê"):

1. Install and enable [nrc_crk_cans.kmp](https://github.com/keymanapp/keyman/files/3683032/nrc_crk_cans.zip), the Cree syllabics keyboard (attached).

2. In the `default` layout, Type a "final" consonant, such as <kbd>ᐠ</kbd> (k).
3. The layout will switch from the default layout to the `kV` layout; the vowels (<kbd>ᐁ</kbd> <kbd>ᐃ</kbd> <kbd>ᐅ</kbd> <kbd>ᐊ</kbd>) will switch accordingly to <kbd>ᑫ</kbd> <kbd>ᑭ</kbd> <kbd>ᑯ</kbd> <kbd>ᑲ</kbd>.
4. Now type <kbd>ᐤ</kbd> (w) to switch to the `kwV` layout.
5. **unexpected behavior**: the layout will switch to the `default` layout, instead of `kwV` as intended.

**Expected behaviour**
At step 5, we should get to the `kwV` layout. This is the one where vowels, which will appear as <kbd>ᑵ</kbd> <kbd>ᑷ</kbd> <kbd>ᑻ</kbd> <kbd>ᑿ</kbd> instead of the default, <kbd>ᐁ</kbd> <kbd>ᐃ</kbd> <kbd>ᐅ</kbd> <kbd>ᐊ</kbd>.

Try this in Keyman 11.0 for Android to see the expected behaviour.

**Screenshots**

Expected behaviour (Keyman 11):
![kwe-keyman11 2019-10-02 13_33_15](https://user-images.githubusercontent.com/2294397/66075681-64d2f200-e519-11e9-970d-202b6b6733e5.gif)

Erroneous behaviour (Keyman 12):
![kwe-keyman12 2019-10-02 13_33_57](https://user-images.githubusercontent.com/2294397/66075735-75836800-e519-11e9-925e-a3259638793a.gif)

---

**iPhone/iPad/Android (please complete the following information):**
 - Device: OnePlus 3t
 - OS: Android 9
 - Keyman version 12.0.4095-beta
 - Target application: Keyman

 
---
 
**Keyboard**
 - Keyboard name: nrc_crk_cans
 - Keyboard version: 1.0.0-alpha.20190731
 - Language name: Plains Cree (Syllabics)

Please find attached .kmp file (rename to .zip -> .kmp), or [download from here](https://github.com/eddieantonio/plains-cree-touch-keyboard/releases/tag/v1.0.0-alpha.20190731)

**Additional context**

**I suspect this is an underlying issue in KeymanWeb**; I haven't tested on any other platforms.

**Comment by darcywong00** [comment]
> I suspect this is an underlying issue in KeymanWeb

I see the  same unexpected behavior on the KMW 12.0 test page with the latest beta (mobile viewport)

**Comment by darcywong00** [comment]
Looking at your keyboard file
```
                "id": "kwV",
                "row": [{
                    "id": 1,
                    "key": [{
                        "id": "U_157D",
                        "text": "\u157D",
                        "nextlayer": "default"
                    }, {
                        "id": "U_14BC",
                        "text": "\u14BC",
                        "nextlayer": "mV"
                    }, {
                        "id": "U_1423",
                        "text": "\u1423",
                        "nextlayer": "nV"
                    }, {
                        "id": "U_1540",
                        "text": "\u1540",
                        "nextlayer": "yV"
                    }, {
                        "id": "U_1424",
                        "text": "\u1424",
                        "nextlayer": "default",  <-- offending line?
                        "sp": "8"

```
Seems that character is intentionally going to "default"

**Comment by eddieantonio** [comment]
This is by design: note that that assignment occurs in the “kwV” layer, i.e., in the layer that cannot be reached by this bug. Have a look at the “kV” layer. This layout works as intended in Keyman 11. Try it!

**Comment by darcywong00** [comment]
my bad, here's the `kV` layer
```
                "id": "kV",
                "row": [{
                    "id": 1,
                    "key": [{
                        "id": "U_157D",
                        "text": "\u157D",
                        "nextlayer": "default"
                    }, {
                        "id": "U_14BC",
                        "text": "\u14BC",
                        "nextlayer": "mV"
                    }, {
                        "id": "U_1423",
                        "text": "\u1423",
                        "nextlayer": "nV"
                    }, {
                        "id": "U_1540",
                        "text": "\u1540",
                        "nextlayer": "yV"
                    }, {
                        "id": "U_1424",
                        "text": "\u1424",
                        "nextlayer": "kwV"
                    }
```

**Comment by eddieantonio** [comment]
Correct. U+1424 ᐤ goes to the `kwV` layer when pressed:

```json
{
  "id": "U_1424",
  "text": "\u1424",
   "nextlayer": "kwV"
 }
```

This is the behaviour observed in Keyman 11, and the desired behaviour for Keyman 12.

**Comment by eddieantonio** [comment]
@jahorton I'm very suspicious of `Processor#selectLayer()` and anything that calls it... 🤔🤔🤔 

https://github.com/keymanapp/keyman/blob/55f12bafe73402745a3c2c2ff6b67993781ffba1/web/source/text/processor.ts#L738

https://github.com/keymanapp/keyman/blob/55f12bafe73402745a3c2c2ff6b67993781ffba1/web/source/text/processor.ts#L738

https://github.com/keymanapp/keyman/blob/55f12bafe73402745a3c2c2ff6b67993781ffba1/web/source/text/processor.ts#L455-L458

https://github.com/keymanapp/keyman/blob/beta/web/source/kmwembedded.ts#L426-L429

https://github.com/keymanapp/keyman/blob/beta/web/source/kmwembedded.ts#L451-L453

Tomorrow, I'll prepare a keyboard that will help with a minimal repro: essentially, touch keyboards with multiple layers, but only one key per layer that cycles through them.

**Comment by jahorton** [comment]
And the winner is:  fat-finger complications!  This keyboard has rules that set the layer directly, and those aren't currently being filtered / blocked during fat-finger calculations.

<img width="1383" alt="Screen Shot 2019-10-04 at 10 58 18 AM" src="https://user-images.githubusercontent.com/25213402/66180130-e51e6200-e695-11e9-8ce5-ee77a22084a9.png">

As it turns out, the next layer _is_ being set correctly - and then the fat-finger computation overrides it.
