### ISSUE TITLE
[KeymanWeb] Entered text for input not visible

### ISSUE THREAD

**Issue by Sergey-Churilin** [keymanapp/keyman#2168]
When length of typed symbols more than width of input, other typed symbols are not visible.

This code snippet can be used to reproduce the issue:
\<html>
\<head>
<script src='https://s.keyman.com/kmw/engine/11.0.227/keymanweb.js'></script>
<script src='https://s.keyman.com/kmw/engine/11.0.227/kmwuitoggle.js'></script>
<script>
  (function(kmw) {
    kmw.init({attachType:'auto'});
    kmw.addKeyboards('@en'); // Loads default English keyboard from Keyman Cloud (CDN)
    kmw.addKeyboards('@th'); // Loads default Thai keyboard from Keyman Cloud (CDN)
  })(keyman);
</script>
\</head>
\<body>

\<input type="text">
\</body>
\</html>

**To Reproduce**
1. Type symbols untill they are visible.
2. Last typed letters are not visible.

**Expected behavior**
Last typed letters are visible. First entered letters not visible

**KeymanWeb:**
 - OS: Windows 10
 - KeymanWeb version: 11.0.227
 - Target Application: Chrome 77.0.3865.90

**Comment by jahorton** [comment]
OK, think I've got the core of it now.  It helps that it's not an issue on Firefox, though it is on the other browsers.  (Surprisingly, it's even an issue for IE!)

Examining web/source/dom/input.ts, line 78 with the developer console is enlightening.  Cross-reference this with https://stackoverflow.com/questions/1962168/scroll-to-the-very-right-of-a-long-text-input for some historical context.

On Firefox, this line will scroll the text to the right.  This does not occur in Chrome or the other browsers.  Yet, especially based on the StackOverflow link, it sounds like this once was enough to trigger the scroll in every browser.  (Though, oddly enough, not in older versions of Firefox and very old IE.)

On current versions of Firefox, `setSelectionRange` will affect the `.scrollLeft` value immediately, which maintains the desired scrolling effect.  Not so for the other browsers.  This even holds true for elements that KMW ignores; `setSelectionRange` won't trigger a scroll to the caret in Chrome, IE, Safari, or Edge.  (I'm finding the IE part especially surprising.)

It seems to be a known issue for Chrome:  https://bugs.chromium.org/p/chromium/issues/detail?id=331233.  Unfortunately, they don't seem to be in anything close to a rush to fix the issue.  So... we may need to add a workaround.

**Comment by Sergey-Churilin** [comment]
Thank you very much @jahorton for a quick response. Could you please give some approximate timeline when the fix will be available?
