### ISSUE TITLE
[Developer] Unpublish some early npm package versions with bad version data

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#2176]
**Describe the bug**

There are a few NPM packages we've published that we should just [unpublish](https://docs.npmjs.com/cli/unpublish) as they have incorrect versions or wrong name.

[`@keymanapp/lmlayer-cli`](https://www.npmjs.com/package/@keymanapp/lmlayer-cli):
* 12.0.4091 (missing -beta)
* 12.0.4092-beta.0? Why the .0
* 12.0.4093-beta.0? Again, why .0?
It looks like these are being published from Android version? Why?

[`@keymanapp/developer-lexical-model-compiler`](https://www.npmjs.com/package/@keymanapp/developer-lexical-model-compiler):
* All of them - conflicts with lexical-model-compiler.

[`@keymanapp/lexical-model-compiler`](https://www.npmjs.com/package/@keymanapp/lexical-model-compiler?activeTab=versions):
* 0.0.0

Note: It might be worthwhile updating the README.md to make it more useful to people visiting the npm entry, and moving the deployment/ci stuff into a separate .md file.

**Comment by eddieantonio** [comment]
These releases are all tests when I was trying out lerna or the ./build.sh script. I'll unpublish or deprecate them all!

**Comment by eddieantonio** [comment]
Problem:

```
npm ERR! code E400
npm ERR! 400 Bad Request - PUT https://registry.npmjs.org/@keymanapp%2flmlayer-cli/-rev/3-1e5b7111f9b9b41de9cf87a43474cc3d - You can no longer unpublish this version. Please deprecate it instead
npm ERR! npm deprecate @keymanapp/lmlayer-cli@12.0.4093-beta.0 "this version has been deprecated"

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/santoseadmin/.npm/_logs/2019-10-04T14_52_10_004Z-debug.log
```

I guess they will all be deprecated :/

**Comment by eddieantonio** [comment]
Okay! All of the incorrect versions have been deprecated! I've also spun off #2177 since I don't think we'll have time to prepare the `lmlayer-cli` for wide-release for 12.0.

I think ever since that `left-pad` debacle, they won't allow people to unpublish things. Either way, I'll make more user-friendly READMEs, then we can call this one done!

**Comment by mcdurdin** [comment]
Great, thank you! I'll go ahead and close this issue.
