### ISSUE TITLE
[iOS] System keyboard sometimes fails to load properly

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#218]
The following image is taken from a rejected TestFlight app review:

<img width="768" alt="empty-keyboard-bug" src="https://user-images.githubusercontent.com/25213402/29545816-b09d8d8a-871a-11e7-8afc-c4baf0f2f741.png">

I've also personally seen this happen when attempting to use the address/search bar in Safari on iPhone.

**Comment by jahorton** [comment]
Marc's intuitions - it may be memory-related, as it seems to be a more frequent issue on retina-display devices.

**Comment by jahorton** [comment]
Current progress of investigation - the WebView hosting the system keyboard is mysteriously having its height adjusted, forcing the keyboard's visual elements out of frame.  The issue is confirmed to be on the iOS and Obj-C side, rather than the JS components and/or KeymanWeb.

**Comment by jahorton** [comment]
It appears that recent updates to the embedded CSS file (pre move-over from the private repo) at minimum helped this to occur far more frequently.

**Comment by mcdurdin** [comment]
Am running alpha build to master that appears to resolve this with CSS fixes. There may be a secondary issue related to rotation of device which needs further investigation.

Am working on testing the CSS fix.
