### ISSUE TITLE
[Developer] when saving .kps, remove any version number if FollowKeyboardVersion is set

### ISSUE THREAD

**Issue by DavidLRowe** [keymanapp/keyman#2201]
**Is your feature request related to a problem? Please describe.**
Currently if the FollowKeyboardVersion checkbox is ticked when a version number already exists, the resulting .kps has the flag set (and does the right thing), but the old version number remains, which potentially causes confusion.

**Describe the solution you'd like**
When Developer saves the .kps, it should remove any version number if the FollowKeyboardVersion checkbox is ticked.

**Product context**
 - OS: Windows 10 1903

**Comment by mcdurdin** [comment]
Thanks David, this looks like a sensible tweak to implement; shouldn't be hard to do and will hopefully make it into v13.
