### ISSUE TITLE
[Windows] Update to 12.0.51.0 wiped installed keyboards

### ISSUE THREAD

**Issue by seumasjeltzz** [keymanapp/keyman#2207]
**Describe the bug**
Updating to 12.0.51.0 wiped my installed keyboards.

**To Reproduce**
I'm not sure I could replicate it. This happened on a fresh install of Keyman 12, on a new computer that I've had since last week. The update notice popped up automatically, I clicked it, and the next thing I know I've got the keyman start-up screen telling me I have no installed keyboards.

I'd be happy to dig for any supporting information to clarify what went wrong.

---

(Delete the irrelevant sections)

**Keyman Desktop, 
 - OS: Windows 10  1903
 - Keyman version: 12.0.51.0

**Comment by mcdurdin** [comment]
If you happen to know which version you were upgrading from, that would help!

**Comment by seumasjeltzz** [comment]
12.0.50.0 according to the install file that I'd originally had.

**Comment by mcdurdin** [comment]
Okay, I can reproduce this issue. Investigating further as a priority.

**Comment by mcdurdin** [comment]
Noting also that hotkeys and options are also not preserved.
