### ISSUE TITLE
[Web] SIL IPA Keyboard deletes multiple characters on bksp (relates to mnemonic layout)

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#2209]
There seem to be a bug in [SIL IPA keyboard](https://github.com/keymanapp/keyboards/tree/master/release/sil/sil_ipa#sil-ipa-keyboard-keyboard) on Keymanweb. The `Backspace` deletes multiple characters when it is triggered.

To test:

- https://keymanweb.com/#und-fonipa,Keyboard_sil_ipa
- https://keymanweb.com/#und-fonipa,Keyboard_ipauni11 _(deprecated?)_

**Recommended font: [Charis SIL](https://software.sil.org/charis/) or [Doulos SIL](https://software.sil.org/doulos/)**

**Comment by mcdurdin** [comment]
I can verify that this is an issue in KeymanWeb. The issue arises in `setMnemonicCode` (processor.ts) where it calls `this.defaultKeyOutput` -- this deletes the character from the context before the keyboard code is executed, and at least one other backspace is executed. Not yet clear if this is a regression?

**Comment by DavidLRowe** [comment]
One test sequenceː type `zo=i=` to produce `zɒɪ` then follow that by backspace. 

With Keyman Desktop result is (as expected) `zɒ`

With KeymanWeb result is `z`

So, does this issue really belong elsewhere?

**Comment by mcdurdin** [comment]
@DavidLRowe this is certainly a bug in KeymanWeb rather than a problem with the keyboard so the issue belongs here in the Keyman repo.

**Comment by jahorton** [comment]
> Side note: Ctrl+Shift+double click on status bar of on screen keyboard in KeymanWeb no longer pops up a version number

Ah, good ol' headspace-only documentation.  I never knew that was a thing, so I never thought to test for it.

This is likely a KeymanWeb 12-only thing; it was brought about by some of the internal restructuring that was necessary to make predictive text happen.

**Comment by mcdurdin** [comment]
> Ah, good ol' headspace-only documentation

Let's just make sure we're not continuing in that grand tradition 😉
