### ISSUE TITLE
Keyman installer fails to install when elevating to a different Administrator account

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#221]
Per Steve_White at  https://community.software.sil.org/t/keyman-install/274/3:

I did have an issue installing it though. I don’t use an administrative account on my computer, and I could not install Keyman. The installer asked me to authenticate with an admin user name and password, I did that, and then it gave an error that “setup.inf” could not be found. Running the installer as administrator also failed with the same error.

I did manage to get it installed by logging into the administrative account, then running the installer.

It is 9.0.528 that I downloaded half an hour ago.

The administrative account does have full permissions to my “Downloads” folder which is where the downloaded file was saved. I tried running the installer after the download, then I tried right clicking on the installer and saying “Run as administrator” which both failed.

I did have an earlier version of Keyman 9 desktop installed, which I did not uninstall first.

**Comment by mcdurdin** [comment]
I'm not seeing this behaviour when I test here; on a test computer I created an administrator account and a standard user account, then ran the installer from the standard user account. Windows prompted for elevation along with username and password, and then Keyman installed successfully.

**Comment by mcdurdin** [comment]
From Steve: 

This is Windows 10 Pro, version 1511. My standard user account is on the
campus domain and my admin account is on the local computer – it was set
up this way by network services. I just tried again, uninstalling
Keyman 10 and installing the latest (10.0.946). I got this error still
relating to setup.inf:

But I did try elevating to a second local computer admin account I’ve
created, and with that one the install succeeded. I suspect the difference
might be the admin account that the network team set up has no permanent
profile, when I login to it Windws says the profile is only temporary and
anything I save there will vanish when I log off.

**Comment by mcdurdin** [comment]
I'm not going to get this one resolved for the initial release. Workarounds are not ideal but will have to do for now.

**Comment by rc-swag** [comment]
This may be an issue where the default install path is incorrect. see #6221

**Comment by mcdurdin** [comment]
Believe this is resolved as @rc-swag indicates.
