### ISSUE TITLE
"displayUnderlying": false is not applied in iOS keyboard

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#2215]
**Describe the bug**
"displayUnderlying": false is not applied in iOS keyboard.
underlying key names are displayed in iOS keyman despite, this flag is set to false

**To Reproduce**
Set the keyboard flag to "displayUnderlying": false
open the keyboard in iOS app.
Visualize the keyboard.

**Expected behavior**
key caps removed, "A", "B", ...

---

**iPhone/iPad/Android (please complete the following information):**
 - Device: iPhone 11 pro max
 - OS: iOS 13.1.3
 - Keyman version 12.0.53
 - Target application: Notes and Keyman App

**Comment by mcdurdin** [comment]
Thank you for the report. Could you please upload a sample keyboard project in a zip that replicates this problem?

**Comment by MayuraVerma** [comment]
sorry, I had the settings wrong. This is not an issue.
