### ISSUE TITLE
Keyman different layout for Android and iOS

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#2219]
**Describe the solution you'd like**
Just like phone and tablet profile under platform. We need split phone platform into iPhone and andriod phone; tablet should be split into iPad and android tablet.

Keyman Application should also pick up respectively layouts during installation.

**Describe alternatives you've considered**
Create different keyboard packages for different platforms, this is not ideal.

**Additional context**
This required to make keyman layout native to the OS, iOS stock keyboard is not as a android stock keyboard.

**Comment by mcdurdin** [comment]
Thank you for the suggestion. We'll consider this in our next design round for mobile keyboards.

**Comment by MayuraVerma** [comment]
@mcdurdin Please review this.
This should be easy fix, to add additional profiles in Keyboard layout.
Read the appropriate profiles in the keyboard engine.

**Comment by mcdurdin** [comment]
It's conceptually easy but there's a lot of work involved to make it happen -- changes to development tools, changes to file formats, and small changes to the apps themselves.

**Comment by MayuraVerma** [comment]
@mcdurdin 
Please try to implement this in version 17, if possible

**Comment by mcdurdin** [comment]
@MayuraVerma we don't have capacity to do this in 17.0 -- we are aiming to land this together with LDML keyboard support for touch devices in 18.0.

**Comment by MayuraVerma** [comment]
Could we also expose device name to keyboards?

If keyboard do not create OS specific keyboard: like Android or iOS 
then keyboard can fallback to phone and tab
likewise
If keyboard do not create device specific: like iPhone 6S, iPhone XR, iPhone 13 pro, Samsung galaxy etc 
then keyboard can fallback to OS

keyboards are broadly classified desktop, mobile, web
mobile -> phone and tab
Future keyboards can be two more levels deeper.
OS -> Android and iOS
devices -> iPhone 6S, iPhone XR, iPhone 13 pro, Samsung galaxy, .... 

if device specific keyboard is not present, then the keyboard can fallback to its OS type
if OS specific keyboard is not present, then the keyboard can fallback to its device type, phone/tab

There must be active full list of mobile devices available. Either Keyman can link to the list or leave it to the keyboard developer to type the list of device names.

few list
https://developers.google.com/ar/devices#emulators
https://gist.github.com/adamawolf/3048717
https://en.wikipedia.org/wiki/List_of_Android_smartphones

**Comment by mcdurdin** [comment]
Thanks for the idea. However, we don't have the resources to maintain a list of devices which changes daily! I would ask also what the benefit is of differentiation between device type? How does language input change between devices?

We have the [`platform` statement](https://help.keyman.com/developer/language/reference/platform) which allows operating-system level differentiation, which is in my mind sufficient for most technical problems. 

(I'm going to go ahead and close this one as a won't-implement)
