### ISSUE TITLE
feat(common/models): Continuous suggestions

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#2220]
**Describe the solution you'd like**
Suggestion bar is split into three blocks, first block is the current typing text, second and third are suggestions. A lot of space is wasted in the white spaces.

An alternate way to show continuous suggestion should be made possible. To display at least three suggestions with space separated similar to Keynounce keyboard in iOS.

Also, the suggestion bar should be continuous in horizontal direction to slide left and right, as its done in Keynounce.

**Describe alternatives you've considered**
None

**Additional context**
Many non-latin languages have complex word formations. It is good to make it horizontal scroll bar to get the more suggestions to pick.

Keynounce Screenshot
![IMG_2801](https://user-images.githubusercontent.com/14062593/67177665-25b7f400-f395-11e9-8aab-984e728f3314.PNG)
![IMG_2802](https://user-images.githubusercontent.com/14062593/67177666-25b7f400-f395-11e9-8efd-71fb3233c494.PNG)

**Comment by mcdurdin** [comment]
Thank you for the feature suggestion. We will be working on additional functionality for the predictions and this fits in with those design plans.

**Comment by MayuraVerma** [comment]
![image](https://github.com/keymanapp/keyman/assets/14062593/a6552778-4f56-45c1-a57d-b6158fa00510)
![image](https://github.com/keymanapp/keyman/assets/14062593/08fd0148-6e19-4153-9f26-013bbdca09f4)

**Comment by mcdurdin** [comment]
See #7906, #7934.
