### ISSUE TITLE
[Linux] Update deployment scripts for 13.0

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#2240]
From team discussion, we'd like to have less manual steps in deploying Linux packages.
For 13.0 onward, we'll have the latest stable branch named `stable` instead of `stable-13.0`.

1. Update `master` to parse for `stable` branch names
2. Update CI to track `stable` and determine major version from version.md
3. Update CI to run launchpad.sh after tarballs sycned to downloads.keyman.com and git tagged.
4. Have packaging CI query https://downloads.keyman.com/api/version/linux to detect when to run packagers.

Once things seem to work for alpha, we can backport to stable-12.0 branch

**Comment by mcdurdin** [comment]
@darcywong00 when do you want to tackle this? Immediately, or later on in the cycle? I think in our roadmap we'd targeted quite late in alpha.

**Comment by darcywong00** [comment]
I think I'm at a point where I'm ready to look into this with @ermshiperete

**Comment by darcywong00** [comment]
Update: Feb 21, 2020
We're still using a mix of TC and Jenkins CI
TC builds off `stable-13.0` branch
Manually run launchpad.sh script to publish to Launchpad

For 14.0, the stable branch will just be `stable`

**Comment by darcywong00** [comment]
@ermshiperete  - I think between the Jenkins pipeline jobs you set up, and the TC configs, 
Keyman packaging is complete for `stable-13.0` and `master`. 

Can we close this?

**Comment by darcywong00** [comment]
I think stable-13.0 is building fine.
We can make a new issue to get 14.0 to build off the stable branch later
