### ISSUE TITLE
feat(developer): Simplify CAPS rules with &CapsLockControlledKeys store

### ISSUE THREAD

**Issue by MattGyverLee** [keymanapp/keyman#2241]
Moving this from the LTS list as suggested:

I think @mcdurdin just addressed the first issue. If mnemonic keyboards are only supported on Windows, we can't suggest it for a multi-platform keyboard yet even if we wanted to. 

French AZERTY is a different animal than, for example, a UK Keyboard. Mnemonic could work fine for letters. Only 6 unaccented letters move between AZERTY and QWERTY, but **EVERY non-letter key is different and 10 of those keys have different CAPS states than QWERTY (CAPS affects the number row)**. Thus, mnemonic gets endlessly complicated on an AZERTY trying to track down punctuation and diacritics, often doubling the necessary keystrokes, and almost always making them more awkward.

Examples:

- The apostrophe key giving the low tone on QWERTY has moved up to the 4 key. 
- The square bracket used for the high tone on QWERTY moves to the 4 and requires RALT on AZERTY. 
- The semicolon key used on QWERTY to access special characters is now hidden under the k and L keys on AZERTY, so we had to use Exclamation point on AZERTY. 
- Period requires shift on AZERTY, I have NO idea why, but that's what they expect.
- "Less than" and "greater than" are completely inaccessible on Faux-Azerty keyboards and @ requires RALT on AZERTY, so imagine trying to use a mnemonic IPA keyboard on AZERTY. It's nearly physically impossible.
- Some keys are dead-keys on AZERTY, so you can't actually access their face-value with a mnemonic keyboard.

US-bought computers are cheaper than French-bought, so to save buying a new keyboard, the vast majority of Cameroonians often choose/learn to blindly type on a physical QWERTY with the French AZERTY virtual keyboard enabled rather than using US International, typing French by muscle memory, so they already expect keyboard layouts to be strictly positional in the same way as MS keyboards. We encourage using a virtual keyboard that matches their physical layout, but the final choice is up to them.

To emulate the same expected behavior via Keyman on the Cameroon Keyboard on a physical AZERTY (and match the MSK Keyboards in use), the layout needs to be positional. This is why there are 2 versions of the Cameroon Keyboard with different placements of minor characters. A large group of Cameroonians carefully chose the fixed position of each character on the Cameroon Keyboards to put the most-needed special characters within easy reach. 

Working with a positional keyboard simply requires extra work to make it predictable. For positional not to EVER default back to English CAPS rules which will upset a francophone, I understand that it has to be hyperspecified all the way down to CAPS+SHIFT[+RALT]+Letter, because Keyman does not have an easy setting to affect whether Caps affects keys. I'm not sure any of this is a bug, but a simple MSKLC-style Caps toggle would be a feature request that would replace 4 lines of my code on every key. 

You can decide if there is anything that is actionable on the Keyman side. I'm just expressing the awkwardness of supporting AZERTY (and the joy expressed by each Francophone when a virtual keyboard's CAPS/SHIFT states actually matches the expected AZERTY Experience) and why I suggested to Laurel continuing with positional.

**Comment by mcdurdin** [comment]
The problem is determining which keys need to have the Caps Lock behaviour. One way this could be tackled is with a compile-time store that looked something like this, which references US English key codes:

```
store(&CapsLockControlledKeys) [K_A] [K_B] ... [K_Z] [K_COLON] [K_LBRKT] ...
```

Then, the compiler would add the NCAPS and CAPS variants to the rules at compile time, e.g.:

```
+ [K_COLON] > 'm'
+ [SHIFT K_COLON] > 'M'
```

would be transformed to:

```
 + [NCAPS K_COLON] > 'm'
 + [CAPS K_COLON] > 'M'
 + [NCAPS SHIFT K_COLON] > 'M'
 + [CAPS SHIFT K_COLON] > 'm'
```

Note, this may also be easier to conceptualize if we add, as I have thought about for a while, ISO-type key references:

```
+ [C10] > 'm'
+ [SHIFT C10] > 'M'
```

Again, that could be implemented as a compiler-only change.

**Comment by MattGyverLee** [comment]
I would love to see more compile-time expansion. Yes, this would definitely help, and would simplify the mental gymnastics of cross-checking all of the Caps variants. 

---
**Example:** 
**QWERTY**

- `RALT + SHIFT + CAPS + q` is equivalent to `RALT+ q` 
- **`RALT + SHIFT + CAPS + 1` is not equivalent to `RALT+ 1`, it is equivalent to `RALT + SHIFT + 1` .** 

**AZERTY**

- `RALT + SHIFT + CAPS + k_q` is equivalent to `RALT+ k_q` 
- **`RALT + SHIFT + CAPS + k_1` is equivalent to `RALT + k_1`** 
---

As-is, the compiler would allow strange combinations such as making (on a QWERTY) the asterisk available with CAPS but not SHIFT without throwing a warning. There is plenty of room for error. 

If a CapsLock (Double tapping on shift) is implemented on Keyman Mobile, I don't know what the implications of this would be for the number row. I can't find an AZERTY touch keyboard with a number row at the moment to see how it behaves.

I would assume the answer is yes, but are there any other major keyboards out there with CAPS-states different than QWERTY or AZERTY? Cameroon and Canada are the only countries that are officially Bilingual in French and English, so I feel a camaraderie with the Canadians.

**Comment by mcdurdin** [comment]
> If a CapsLock (Double tapping on shift) is implemented on Keyman Mobile, I don't know what the implications of this would be for the number row. I can't find an AZERTY touch keyboard with a number row at the moment to see how it behaves.

For touch, a double-tap on shift (when implemented) would just "lock" the shift layer until pressed again, rather than applying any other transforms.

**Comment by mcdurdin** [comment]
Okay, this functionality won't make it into the next release (13.0) but we are planning to do a big "little feature" push for the subsequent release so this would hopefully fit well there.

**Comment by MattGyverLee** [comment]
I'm glad to hear that.  Thanks!

**Comment by mcdurdin** [comment]
Note: ISO9995-style key references were implemented in #2741.

**Comment by mcdurdin** [comment]
So, I've just implemented this, plus as a bonus, added in character and virtual key ranges with the `..` operator. Hope you like it -- see the attached pull requests!

**Comment by MattGyverLee** [comment]
AWESOME!

So does this expand to ALT and CTRL (+ RALT, RCRTL, etc.)? I tried to follow the code, but I wasn't sure.

If I understand this correctly, on AZERTY, this code:

```
store(&CasedKeys) 'a'..'z' ‘0’..‘9’ 

+ [K_6] > U+002D
+ [RALT K_6] > U+007C
+ [SHIFT K_6] > U+0036
+ [SHIFT RALT K_6] > U+0308

+ [K_A] > U+0071
+ [SHIFT K_A] > U+0051
+ [RALT K_A] > U+2014
+ [SHIFT RALT K_A] > U+2013
```
will be expanded to this at compile time
```
+ [CAPS K_6] > U+0036
+ [CAPS RALT K_6] > U+0308
+ [CAPS RALT SHIFT K_6] > U+007C
+ [CAPS SHIFT K_6] > U+002D
+ [NCAPS K_6] > U+002D
+ [NCAPS RALT K_6] > U+007C
+ [NCAPS SHIFT K_6] > U+0036
+ [NCAPS SHIFT RALT K_6] > U+0308 

+ [NCAPS K_A] > U+0071
+ [CAPS SHIFT K_A] > U+0071
+ [NCAPS SHIFT K_A] > U+0051
+ [CAPS K_A] > U+0051
+ [NCAPS RALT K_A] > U+2014
+ [CAPS SHIFT RALT K_A] > U+2014
+ [NCAPS SHIFT RALT K_A] > U+2013
+ [CAPS RALT K_A] > U+2013
```
--
Oddly enough, on Windows French AZERTY, Caps is enabled on EVERY character key except:  K_BKQUOTE, K_oE2, K_SPACE, and K_NPDOT. I'm not sure I actually knew that until today.

Unless you add another shorthand range, that means that I need to add K_HYPHEN, K_EQUAL, K_LBRKT, K_RBRKT, K_BKSLASH, K_QUOTE, K_COMMA, K_PERIOD, K_SLASH; K_M (K_M is the comma key in azerty and K_COLON is the 'm' key) to my AZERTY &CasedKeys rule. Presumably K_COLON is covered by the the 'm' syntax.

So, the starting AZERTY rule would be (using the 'a' syntax you suggested)
```
store(&CasedKeys) 'a'..'z' '0'..'9' [K_HYPHEN] [K_EQUAL] [K_LBRKT] 
[K_RBRKT] [K_BKSLASH] [K_QUOTE] [K_COMMA] [K_PERIOD] [K_SLASH] 
[K_M]
```
or (using only keynames)
```
store(&CasedKeys) [K_A]..[K_Z] [K_0]..[K_9] [K_HYPHEN] [K_EQUAL] 
[K_LBRKT] [K_RBRKT] [K_BKSLASH] [K_QUOTE] [K_COMMA] [K_PERIOD] 
[K_SLASH] [K_COLON]
```
and the starting QWERTY rule would be:
```
store(&CasedKeys) 'a'..'z'
```
Even without another shorthand range, that's still way less complicated than the mental gymnastics of working the CAPS combos out per key. This is awesome news!

**Comment by MattGyverLee** [comment]
This is a handy little Creative Commons graphic by Karl432 from https://en.wikipedia.org/wiki/ISO/IEC_9995#ISO/IEC_9995-2 for the ISO codes that might be useful in the ISO documentation:
![ISOIEC-9995-2](https://user-images.githubusercontent.com/986339/109941042-00e6c700-7cd3-11eb-9b23-a7493028657c.png)

And I had this one hanging on my wall when I was working on my Linux XKB keyboard (Linux prepends A to the XKB codes).
https://web.archive.org/web/20160625084302/http://www.charvolant.org/~doug/xkb/html/node5.html#SECTION00052000000000000000
![image](https://user-images.githubusercontent.com/986339/109941404-6d61c600-7cd3-11eb-9e34-3cb485f42d38.png)

**Comment by mcdurdin** [comment]
> ```
> store(&CasedKeys) 'a'..'z' '0'..'9' [K_HYPHEN] [K_EQUAL] [K_LBRKT] 
> [K_RBRKT] [K_BKSLASH] [K_QUOTE] [K_COMMA] [K_PERIOD] [K_SLASH] 
> [K_M]
> ```

The AZERTY range could be:

```
store(&CasedKeys) 'a'..'z' '0'..'9' "-=[]\;',./"
```

Regarding `[K_M]`: remember that this is referring to US English base keys, so it's still called `K_COLON` (or `';'`) 😁

**Comment by mcdurdin** [comment]
> So does this expand to ALT and CTRL (+ RALT, RCRTL, etc.)?

Yes. It will work with all combinations.

**Comment by mcdurdin** [comment]
> This is a handy little Creative Commons graphic by Karl432 from https://en.wikipedia.org/wiki/ISO/IEC_9995#ISO/IEC_9995-2 for the ISO codes that might be useful in Keyman's ISO documentation:

It's good. But I think I'd like to make my own version which includes the Keyman key codes as well -- don't think I'll get to that today, though!
