### ISSUE TITLE
[Android] Add Keyboard activity is opening, when catalog download not finished 

### ISSUE THREAD

**Issue by safolit** [keymanapp/keyman#2265]
**Describe the bug**
If the user opens the language settings, the catalog download starts in background.
If the user opens the "Add a keyboard for your language" button before download is finished, the "please wait" comes up, but the download keyboard acitivity still starts with an empty list, which is confusing.

**To Reproduce**
1. Reinstall Keyman
2. Goto Settings / Language Settings
3. Catalog Download is started in background!
3. However, clicking the "Add a keyboard for your language" link in "Get Started" fails on first run -- it just shows a blank catalog. The catalog does not appear to start downloading, etc.
And, when the catalog is downloading, and the 'please wait' toast shows, the download keyboard activity still starts, which is confusing. 

**Expected behavior**
Ideally, it would show an interstitial activity asking the user to wait until the download completes, with a spinner, and the user can either wait, or click the Back button. Once the download completes, the interstitial should be closed automatically, and the download keyboard activity should start.

**Screenshots**

---

(Delete the irrelevant sections)

**Keyman Desktop, Keyman for macOS, Keyman for Linux (please complete the following information):**
 - OS: Android
 - Keyman version: 12
  
**iPhone/iPad/Android (please complete the following information):**
 - Device: Emulator
 - OS: Android API 28
 - Keyman version 13
 - Target application: Keyman

**Comment by darcywong00** [comment]
Originally, the Add Keyboard Activity wouldn't open if the network wasn't available.
Later on, we included keyboards available from installed kmp files, so the blank screen is a side-effect of no network and no installed kmp files.
