### ISSUE TITLE
Broken ".ICO" Link on KPJ > Keyboards Tab 

### ISSUE THREAD

**Issue by dyacob** [keymanapp/keyman#227]
When editing a .kpj file in Keyman Developer 9.0.526.0 a broken link appears when clicking the ".ICO" icon under "Source Files" of the "Keyboards" tab.  The invalid link is:

  https://help.keyman.com/developer/9.0/docs/filetype_ico.php

Further, ICO does not appear under the listing of "File Types" but perhaps should:

https://help.keyman.com/developer/9.0/reference/file-types/

**Comment by darcywong00** [comment]
The help.keyman.com reference will be updated to include the ICO filetype. In the meantime, you can refer to https://help.keyman.com/developer/language/reference/bitmap for information about how the icon is used.

**Comment by darcywong00** [comment]
Fixed in https://github.com/sillsdev/keyman-help.keyman.com/pull/91
