### ISSUE TITLE
[Developer] Full context replacement of rules with nul incorrect in web keyboards

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#2272]
**Describe the bug**
This addresses the Developer side of #2261.  Since KMW can mitigate this independently, the current plan is to fix Web before Developer, though we do wish to fix both in due time.

**To Reproduce**
Create a new keyboard with the following code:
```
store(consonants_ra_key)  [K_N] [K_B] [K_Y] 
store(consonants_ra_code) U+0CA3 U+0CAD U+0CAF 

nul U+0CB0 U+0CCD + any(consonants_ra_key) > U+0CB0 U+200D U+0CCD index(consonants_ra_code,4)
```

After compiling it, please examine the resulting JS code.  In particular, the core issue may be noted by examining the resulting keyboard-rule output code:

```
k.KDC(3, t);
k.KO(-1, t, "ರ‍್ಯ"); // Not exact, but fine for here.
```

**Expected behavior**
The rule for the context-match validly uses `3` - since it must check against `nul`.  However, we can't delete `nul` from the context - we should have `k.KDC(2, t)` instead of `(3, t)` here.

**Keyman Developer**
 - OS: Windows 10
 - Keyman Developer version: 12.0.52.0

**Comment by mcdurdin** [comment]
Note: this only impacts keyboards with `store(&VERSION) '10.0'`
