### ISSUE TITLE
Delphi 10.2

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#2280]
**Describe the bug**
make build is defaulting to Delphi 10.2, despite setting DELPHI_VERSION=20.0 in UserDefines.mak

keyman source stable-12.0

I have also set environment variable DELPHI_VERSION=20.0

**Comment by darcywong00** [comment]
The update in #2244 to use Delphi 10.3.2 was for the `master` branch (Keyman 13.0+ development)

`stable-12.0` will remain on Delphi 10.2.

**Comment by MayuraVerma** [comment]
ok thanks.
