### ISSUE TITLE
feat(android) Update to Java 11

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#2293]
in #2279 @safolit had started the process of updating the Android build to use Java 11.

Though we're staying with Java 8 for now, I'm documenting the steps for when this happens.

Note, in order to run robolectric for Android SDK 29, we'll need to update Java
(see robolectric.properties)

Java SE Development Kit 11 (Java 9 or newer)
## Install Java
It is recommended to use openJDK because of oracle license issues.
Tested with latest release for openJDK 11 from
https://github.com/ojdkbuild/ojdkbuild

1. Download and unpack the zip archive
2. On Windows: use the default java path C:\Program Files\Java to avoid error message 
> "Error 0x80010135 Path Too Long"
3. Aso set an environment variable for JAVA_HOME e.g C:\Program Files\Java\openjdk-11.0.5.10-1

**Comment by darcywong00** [comment]
Per https://android-developers.googleblog.com/2020/12/announcing-android-gradle-plugin.html

Java 11 is a pre-req for using Gradle plugin 7.0 (#4603)

**Comment by darcywong00** [comment]
We don't need Java 11 for Keyman 15.0. Deferring to Future

**Comment by rc-swag** [comment]
Or the appropriate version of Java at the time.

**Comment by darcywong00** [comment]
I've done preliminary [work](https://github.com/keymanapp/keyman/tree/chore/android/java-11) to update the Android projects to build with MS [OpenJDK 11](https://learn.microsoft.com/en-us/java/openjdk/download#openjdk-11).

One dilemma with CI is the builds depend on the environment variable `JAVA_HOME` to specify the Java version which is
currently set to Java 8 for stable-16.0

**Comment by darcywong00** [comment]
Discussing w/ @mcdurdin , instead of sdkman we can set the environment vars
JAVA_HOME_8
JAVA_HOME_11
and have the builder script export JAVA_HOME accordingly...

> But a more consolidated look at dependences will probably be needed (whole sprint effort from the team I think)
