### ISSUE TITLE
[iOS] Popup key refactor - use KMW's instead

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#2302]
**Describe the solution you'd like**
Now that we display the keyboard banner within KMW-space in the iOS app keyboard, the main reason for implementing the popup keys within iOS code is now gone.  As stated by @mcdurdin in a discussion in other channels...

> Another thing to refactor - we should now use the web popup rather than the iOS one for future versions, given it is now always entirely within the web frame!  Will both simplify the design and allow for better control of the popups, e.g. styling etc, at least on iOS.

**Product context**
 - OS: iOS

**Other notes**
Since the current behavior is part of the general "embedded" KMW package, this would likely require some tweaks to Android popup keys, too.

**Comment by mcdurdin** [comment]
> Since the current behavior is part of the general "embedded" KMW package, this would likely require some tweaks to Android popup keys, too.

Worth noting that on Android, popup keys can encroach on the app's surface area -- unlike iOS, where they have to stay within the keyboard window.

**Comment by jahorton** [comment]
Hard for web-based popup keys to display outside the WebView that hosts them, though.  Or would we keep Android's version on the Java side if we did this?

**Comment by mcdurdin** [comment]
> Or would we keep Android's version on the Java side if we did this?

Yes, I am suggesting we don't apply this change to Android, at least without serious consideration of the pros and cons. :)

**Comment by jahorton** [comment]
... looks like we forgot to close this issue off long ago.  We had to move this up when iOS 13.4 released due to a change in how `WKWebView`s interacted with longpress gestures that broke the old approach entirely.  See #2968.
