### ISSUE TITLE
[Developer] Display font on Chrome Simulator and Android

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#2310]
**Describe the bug**
The same setting for font has been applied to the touch layout, but when testing it on 
- Chrome Simulator, it looks like this:
![image](https://user-images.githubusercontent.com/28331388/68446991-f288b800-0210-11ea-9d21-f004b20f52d1.png)

- Android:
![image](https://user-images.githubusercontent.com/28331388/68447028-13510d80-0211-11ea-9a65-70f9ef86102e.png)

Why do they look different? The expected font is "Arial' on both of these.

**To Reproduce**
1. Go to 'https://github.com/keymanapp/keyboards/pull/934'
2. Test the touch layout on Chrome simulator and Android
3. See error

**Expected behavior**
The display font should look identical on both Chrome simulator and Android. The desirable one is Arial.

---

**Android:**
 - Device: Galaxy S9+
 - OS: iOS 9.0
 - Keyman version: 12.0.4206

**Chrome Simulator environment:**
 - OS: Windows 10 1903
 - Browser: Chrome 78.0.3904.87 (Official Build) (64-bit)
 
**Keyman Developer:**
 - OS: Windows 10 1903
 - Keyman Developer version: 12.0.52.0
 
---
 
**Keyboard**
 - Keyboard name: phofarsi
 - Keyboard version: 1.0
 - Language name: Farsi
 - PR: https://github.com/keymanapp/keyboards/pull/934

**Comment by mcdurdin** [comment]
This is most likely an issue in the font management in Developer.

**Comment by mcdurdin** [comment]
I'm not seeing this on my Android (Nokia 3) with the keyboard in keymanapp/keyboards#960 (replacement for 934). Can you reproduce the problem now?

**Comment by mcdurdin** [comment]
Closing as no repro. If you can reproduce the issue, please feel free to reopen.
