### ISSUE TITLE
[Web] Display underlying character on touch layouts is not working

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#2311]
**Describe the bug**

`Display underlying` is unchecked in the Developer (See the screenshot right below), but the underlying characters are shown in both Chrome simulator and Android.

![image](https://user-images.githubusercontent.com/28331388/68451748-86af4b00-0222-11ea-9d81-ea795287284e.png)

- Chrome Simulator, it looks like this:
![image](https://user-images.githubusercontent.com/28331388/68446991-f288b800-0210-11ea-9d21-f004b20f52d1.png)

- Android:
![image](https://user-images.githubusercontent.com/28331388/68447028-13510d80-0211-11ea-9a65-70f9ef86102e.png)

**Expected behavior**
When the `Display underlying` is unchecked, the underlying character shouldn't be shown on the simulator and touch devices.

---

**Android:**
 - Device: Galaxy S9+
 - OS: iOS 9.0
 - Keyman version: 12.0.4206

**Chrome Simulator environment:**
 - OS: Windows 10 1903
 - Browser: Chrome 78.0.3904.87 (Official Build) (64-bit)
 
**Keyman Developer:**
 - OS: Windows 10 1903
 - Keyman Developer version: 12.0.52.0
 
---
 
**Keyboard**
 - Keyboard name: phofarsi
 - Keyboard version: 1.0
 - Language name: Farsi
 - PR: https://github.com/keymanapp/keyboards/pull/934

**Comment by mcdurdin** [comment]
After investigation, it turns out that the change implemented in #1539 did not make its way through to Keyman 12 source due to the refactor.
