### ISSUE TITLE
[Windows] VS Code deletes whole clusters with backspace now and does not work with Keyman

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#2315]
**Describe the bug**
This issue may be present on other platforms as well. VSCode now deletes whole clusters (this may have been caused by work done in relation to https://github.com/microsoft/vscode/issues/15622, see also https://github.com/microsoft/vscode/commit/c928a447a098c54b41a2c9789727be6f4afd211f) on backspace which is (a) inconsistent with other applications, and (b) breaks Keyman's backspace support for legacy applications.

**To Reproduce**
1. Open VSCode.
2. Paste ខ្មែរ
3. Press BKSP. Note that ខ្មែ is left.
4. Press BKSP again. It should remove only the vowel but instead removes the M as well: ខ្ (leaving the coeng marker)
5. Press BKSP again. Both the coeng and the kh are removed.

**Expected behavior**
This is not specific to Keyman, but given Keyman requires single-character backspaces to work, this completely breaks Keyman for VSCode. Expecting a character-by-character deletion, which is what Notepad and Word do.

---

(Delete the irrelevant sections)

**Keyman Desktop:**
 - OS: Windows 10
 - Keyman version: 12.0.52.0
 - Target Application: VS Code 1.40.0

May also apply to other operating systems. Have not tested.

**Comment by thammarith** [comment]
See also #84897

**Comment by mcdurdin** [comment]
Fixed in VS Code by https://github.com/microsoft/vscode/commit/4560e524b8db758a0bcc0daddbac9bc1631bc7e1. Verified on VS Code Insiders build detailed below:

> Version: 1.42.0-insider (user setup)
> Commit: 235695393db763af632fab376b890d63d8a48576
> Date: 2020-01-16T18:51:39.093Z
> Electron: 7.1.7
> Chrome: 78.0.3904.130
> Node.js: 12.8.1
> V8: 7.8.279.23-electron.0
> OS: Windows_NT x64 10.0.18363
>
