### ISSUE TITLE
Kannada text not displayed

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#2333]
**Describe the bug**
Keyboard and language name with Kannada text is not displayed with "English" Locale.

**Screenshots**
![image](https://user-images.githubusercontent.com/14062593/68726720-01ac9480-0588-11ea-8ad8-9d269a5221e8.png)

**Keyman Desktop, Keyman for macOS, Keyman for Linux (please complete the following information):**
 - OS: Windows 10 1803
 - Keyman version: 12.0.52

**Comment by MayuraVerma** [comment]
also, with firstvoices oem, kannada locale doesn't load at all

**Comment by mcdurdin** [comment]
Thank you for the report. The difficulty is that we cannot load all the fonts for all possible languages in the English UX. This may be improved in a future update once we support Chromium.

**Comment by MayuraVerma** [comment]
@mcdurdin This was working just fine in version 11. I can download an older version and test.

oem/firstvoices doesn't load the Kannada font if the locale is installed and enabled.

**Comment by MayuraVerma** [comment]
Here is version 11.
I am suspecting, some old artifacts must be causing issue or something.
Could it just my machine that is acting up?
![image](https://user-images.githubusercontent.com/14062593/68730373-286fc880-0592-11ea-8d56-cdf8317c46f3.png)

**Comment by mcdurdin** [comment]
I would prefer to deal with the oem/firstvoices issue separately :)

The Kannada locale is showing fine on my computer:

![image](https://user-images.githubusercontent.com/4498365/68751396-9d580680-0655-11ea-82ef-c29fe8316db2.png)

So this looks like there is a font issue on your computer, perhaps? Two possibilities I can think of: there is a font that pretends to support the Kannada Unicode range which is taking precedence, or there is a corrupted font.

**Comment by MayuraVerma** [comment]
@mcdurdin Thank you. It was conflicting fonts that was causing the issue.
