### ISSUE TITLE
[iOS] [mac] AppleCoreText Issue with Kannada text

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#2337]
This is not an issue with Keyman keyboard, but this is an issue with iOS and MacOS, "AppleCoreText API". If you can please report it to apple at feedbackassistant.apple.com with the SIL developer account. It might traction with Apple Engineers.

Please report it to Apple.

**Describe the bug**
Kannada text is broken in Notes app in iOS and mac OS

**To Reproduce**
These text is displayed correctly in "NSTextView" field, but breaks in "NSTextField" text field.
Notes app and all forms with text editing uses "NSTextField".
Open Notes app in iOS or mac OS, type the below text.
ಕಜ್ನೋ
ಕಜ್ನ್ಕೋ
ಕಜ್ನ್ಕ್ರೋ
ಕಜ಼್ನೋ
ಕಜ಼್ನ್ಕೋ
ಕಜ್ಫ಼ೋ
ಕಜ್ನ್ಫ಼ೋ
ಕಜ್ಜ಼್ಫ಼ೋ
ಕಜ಼್ಜ಼್ಫ಼ೋ

**Expected behavior**
Expected text in email while reading. "NSTextView" 
![ExpectedTextEmailApp](https://user-images.githubusercontent.com/14062593/68792349-cace9100-0610-11ea-821c-51a3b8fad392.jpg)

**Screenshots**
Actual text in Notes App while editing. "NSTextField" 
![BrokenText](https://user-images.githubusercontent.com/14062593/68792359-d02bdb80-0610-11ea-8881-c41918b64a80.png)

---

iPhone 11 pro max
OS: iOS 13.1.2 and iOS 13.2
Keyman version 12.0.53
Target application: Notes

macbook pro
OS: mac OS 10.15.1
Keyman version 12.0.50
Target application: Notes

---
 
**Keyboard**
 - Keyboard name: ISIS (Kannada)
 - Keyboard version: 2.0.1
 - Language name: Kannada

**Additional context**
This is bug, which needs to be reported to apple 
feedbackassistant.apple.com

**Comment by mcdurdin** [comment]
I'm going to go ahead and close this issue as it isn't a Keyman bug; @MakaraSok are you able to submit a report for Mayura? You might as well go ahead and do one for the remaining issues with Khmer script as well!

**Comment by MayuraVerma** [comment]
@mcdurdin @MakaraSok Thank you very much.

**Comment by MayuraVerma** [comment]
@mcdurdin @MakaraSok just a kind reminder. Please file a bug report to Apple.
