### ISSUE TITLE
[iOS] Build not always failing when getting fastlane errors (was: Stable and Alpha update not showing up in app store)

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#2347]
iOS version stable version 12.0.54 and alpha 13.0.20 are not showing up in app store and testflight.

latest on app store is 12.0.53 and on testflight is 13.0.14.

**Comment by mcdurdin** [comment]
https://build.palaso.org/viewLog.html?buildId=167930&buildTypeId=Keyman_iOS_Stable&tab=buildLog&_focus=325#_state=325 indicates the build succeeded but errors occurred within the build. @jahorton could you investigate and address the CI skipping those errors?

**Comment by mcdurdin** [comment]
@MayuraVerma we have been updating the build infrastructure but XCode went through a series of bugs and issues and we are only just on 11.2.1 which is the first version that apparently works again. 

Apple's quality control is an unacceptable disaster.

**Comment by mcdurdin** [comment]
I've shifted the focus for this issue slightly because the builds are now running -- but there was a build that *should* have failed as I noted [above](https://github.com/keymanapp/keyman/issues/2347#issuecomment-554506789).

I still need to follow up on the 12.0 series build but will re-task this issue to be looking at that build non-fail if that's okay.

**Comment by jahorton** [comment]
My best guess is that Fastlane didn't expect a scenario where such a recently-released Xcode version got rapidly deprecated.  The rest of the console log messages match up to scenarios that have generated error codes in the past... perhaps they simply forgot to actually return an error code for that case.  I'd have to go digging through the [source](https://github.com/fastlane/fastlane) to know for sure, though./fastlane.)  I don't want to say that _has_ to be the issue, though.

Of course, the problem with more proactively debugging this is that it requires attempting to actually publish a new build... doing so would add a fair amount of 'noise.'

**Comment by mcdurdin** [comment]
This is now resolved.
