### ISSUE TITLE
[iOS] Compatibility with the Files app

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#2356]
To facilitate alternative avenues of installing KMPs on iOS devices, it's worth noting that (as of iOS 11) there's a "Files" app on iOS devices.  As an alternative language-resource installation path, we should facilitate finding KMPs and opening them by use of this app.

This would also help users to find their installed KMPs, making it comparatively easier for them to share those files with others in an ad-hoc manner if/when appropriate.

Some useful references:
- https://www.bignerdranch.com/blog/working-with-the-files-app-in-ios-11/
- https://www.appcoda.com/files-app-integration/

**Comment by orewJ** [comment]
,kmp shows up in Files and when selected, a window pops up with some info, and an option to open in Keyman. It  'opens' a blank page with a teeny menu at the bottom left with an "Open in" option. (As if the first Open was not serious enough!) and when "Open in" is chosen the same Error "Unable to copy..." appears.

**Comment by orewJ** [comment]
I am still unable to open the kmp file in iPadOS 13.3  (I had a functioning kmp on my iPad pro and I removed it to test an updated kmp) ...
Files and other file managers are unable to wed my updated kmp file into Keyman app.  
Any help's welcome.
