### ISSUE TITLE
[iOS] User-friendly notice when a language lacks lexical models

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#2357]
**Describe the bug**
If a user goes to add a "dictionary" for their language, but none is currently available from the Cloud API, the app does... nothing.  They can see that they pressed the '+', it goes active for a moment, and then everything resets.  There's no message that "sorry, we don't have a dictionary for the ____ language."

**Expected behavior**
A simple message (such as "Sorry, we don't have a dictionary for the ____ language") would be much more clear for end-users.

**Comment by mcdurdin** [comment]
Or ... could we link this to #2356 and open the File browser? :)
