### ISSUE TITLE
[kmlmi] Improve error message when author URL undefined

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#2370]
For keymanapp/lexical-models#60 I was stuck because the lexical model package compiled fine in Developer, but the build script failed with the error

```
Building model sample/example/example.ta.wordlist/
Cannot read property 'match' of undefined
Unable to merge .model_info file
Aborting with error 1
```

This was cause kmlmi was looking for an author URL in the .kps file. It would be nice to have a clearer error.

**Comment by mcdurdin** [comment]
Fix should be to allow kps without author url at all. kps spec does not require author.
