### ISSUE TITLE
[Developer] kmlmi crashes when Author email missing in .kps file

### ISSUE THREAD

**Issue by eddieantonio** [keymanapp/keyman#2373]
This prevented the build in keymanapp/lexical-models#60.

I think `kmlmi` just ignored an `undefined` check -- easy workaround.

**Comment by darcywong00** [comment]
Maybe a duplicate of #2370

**Comment by eddieantonio** [comment]
It's more of an extension of #2370. Both can be fixed in one PR. @mcdurdin Should a missing author email emit a warning, or is it no big deal?

**Comment by mcdurdin** [comment]
Missing author email is not a problem. Packages without an email address are perfectly valid.
