### ISSUE TITLE
[Developer] kmlmc generates invalid code for SMP characters

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#2374]
The ES5 engine doesn't like duplicate property names on objects, and there's a minor bug generating them within the lexical model compiler.

In particular, two SMP characters have the same leading surrogate:
- 🇸
- 🇺

It appears that when compiling SMP strings for Trie models, a node is being generated for the leading surrogate, followed by a node for the completed surrogate pair.  Unfortunately, a unique copy of the leading surrogate is generated for each surrogate pair, allowing duplicate object properties to exist if two SMP characters (like the two above) have the same leading surrogate.

_Originally posted by @jahorton in https://github.com/keymanapp/keyman/pull/2358#issuecomment-555909909_

**Comment by darcywong00** [comment]
This still might be an issue with Developer 12.0.64.0 as reported on [community site](https://community.software.sil.org/t/developer-problems-with-a-shavian-alphabet-lexical-model/2887)

When I build his lexical model project in Keyman Developer, the compiled .model.js file has split surrogate pairs.

But when I build it with lexical-models/build.sh, the model is correct.

**Comment by mcdurdin** [comment]
#2438 would need a cherry-pick to 12.0 to resolve this.
