### ISSUE TITLE
[Android] Cannot download Cree Syllabics keyboard

### ISSUE THREAD

**Issue by eddieantonio** [keymanapp/keyman#2386]
**Describe the bug**
When I try to download [nrc_crk_cans](https://help.keyman.com/keyboard/nrc_crk_cans/1.0.1/nrc_crk_cans.php) from within the Keyman app, it fails with the message "Error: Keyboard failed to download"

**To Reproduce**
1. Within the Keyman app, access the settings
2. Click  "Installed Languages"
3. Click the plus button
4. Select "ᓀᐦᐃᔭᐍᐏᐣ" (Plains Cree (Syllabics)) (it will be near the bottom of the list)
 5. Click download

**Expected behavior**
The keyboard should instal!

**Screenshots**

Here's me doing it on my phone, after a restart:
![cannot-download-cree-keyboard 2019-11-27 10_25_12](https://user-images.githubusercontent.com/2294397/69746097-cae68a80-1100-11ea-9549-3fbc9963b39a.gif)

---

**iPhone/iPad/Android (please complete the following information):**
 - Device: OnePlus 3T
 - OS: Android 9
 - Keyman version: 12.0.4210
 - Target application: Keyman

 
---
 
**Keyboard**
 - Keyboard name: nrc_crk_cans
 - Keyboard version: 1.0.1
 - Language name: ᓀᐦᐃᔭᐍᐏᐣ (Cree Syllabics)
 - BCP-47: crk-Cans

**Additional context**
I have installed development versions of this keyboard COUNTLESS times on my install of Keyman. Maybe it's a problem specific to me installing it via KMP, then trying to install it from the cloud?

**Comment by darcywong00** [comment]
#2378 has some fixes so the package ID info when installing keyboard .kmp packages gets propagated. This fixes trying to install additional languages listed in the kmp.json. And it handles your case where you uninstalled the keyboard and want to reinstall the keyboard (the extracted .kmp files are still on your device).

I've tested this with [nrc_crk_cans 1.0.1](https://downloads.keyman.com/keyboards/nrc_crk_cans/1.0.1/nrc_crk_cans.kmp) and Keyman [12.0.4211](https://downloads.keyman.com/android/stable/12.0.4211/keyman-12.0.4211.apk) which should go live on the Play Store within 1-2 days.

**Comment by eddieantonio** [comment]
It works in the latest build! Though the language appears as "Cree, Plains (Unified Canadian Aboriginal Syllabics)". Either way, :shipit:

**Comment by darcywong00** [comment]
> The the language appears as **Cree, Plains (Unified Canadian Aboriginal Syllabics)**

Yeah, that's the displayed language name when installing the keyboard from the cloud.
The **ᓀᐦᐃᔭᐍᐏᐣ (Cree Syllabics)** name in your video at the bottom of the language list is installing the keyboard from your .kmp file.
