### ISSUE TITLE
[Developer] TypeScript should be compiled with strict null/undefined checks

### ISSUE THREAD

**Issue by eddieantonio** [keymanapp/keyman#2387]
In `tsconfig.json`, we should enable `strictNullChecks` (https://www.typescriptlang.org/docs/handbook/compiler-options.html).

Bugs like #2373 could have been caught at compile time.

See this article: https://shinesolutions.com/2017/01/06/writing-safer-code-with-typescript-strict-null-checks-type-guards/

**Comment by mcdurdin** [comment]
Do you want to look at this initially for kmlm*? We'll address this separately for KeymanWeb with @jahorton
