### ISSUE TITLE
[iOS] predictive text dictionary (Salish Straits) not showing up despite "download successful"

### ISSUE THREAD

**Issue by dy2288** [keymanapp/keyman#2418]
**Describe the bug**
On an iPad, after selecting the Salish Straits keyboard and downloading the Lexical Model for Sencoten, despite getting the "download successful" message no predictive text is available, and upon going back to Dictionaries, it seems like no 

**To Reproduce**
See video here: https://drive.google.com/open?id=1kUc-tW5swYo-o1TAOS13OHImnnVoacZs

**Expected Behavior**
Expected to have predictive text working in the keyboard.

---
  
**iPhone/iPad/Android (please complete the following information):**
 - Device: iPad Gen 7
 - OS: 13.1
 - Keyman version: 12.0
 - Target application: Notes

---
 
**Keyboard**
 - Keyboard name: fv_sencoten
 - Keyboard version: 9.1
 - Language name: Salish Straits (Latin)

**Comment by mcdurdin** [comment]
Can you test with TestFlight update 13.0.27? This should be available from https://keyman.com/alpha :)

**Comment by dy2288** [comment]
This looks to have solved the download issue, however introduced a new issue with getting the prediction bar to show up.

Steps:
* Download Sencoten
* Navigate to Dictionaries. Although a dictionary is downloaded already, it does not seem to be active by default. So click on it to activate/select.
* This is the weird part: Clicking Done, despite having predictions enabled won’t show the bar. I had to toggle Enable Predictions multiple times, and hit Done, until they finally showed up.

**Comment by mcdurdin** [comment]
@jahorton Can you investigate the above issue?

**Comment by jahorton** [comment]
This has probably been addressed by #2470; could you retest with the latest alpha version?

**Comment by jahorton** [comment]
In pre-release testing, the only aspect remaining that I can find is covered by #2673.  I'm closing this issue in favor of that one.

That stated, if behaviors not covered there continue to occur, please do let us know here and we can re-open this issue.
