### ISSUE TITLE
Should not add shift keys to undefined layers

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#242]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Saturday Feb] 22, 2014 at 03:55 GMT_
_Originally opened as KD-237_

----

The default layout used for imported keyboards automatically adds Ctrl Alt CtrlAlt popup-keys to the Shift key. However, those keys should not be added unless the layer is actually valid. Validity can be determined form the Virtual Keyboard array length and content - if all keycaps (apart from special keys) for a layer are empty, the layer is not valid. 

It appears possible to delete the pop-up key entries from the Shift key object, but might be better to only add them, dynamically, if the referred layer is valid.

**Comment by jahorton** [comment]
This was implemented a while back in more recent KMW releases and is part of the final KMW 2.0 release.  Further optimizations in keeping with these ideas were added with #300.
