### ISSUE TITLE
Cannot do a search in Developer

### ISSUE THREAD

**Issue by LornaSIL** [keymanapp/keyman#2421]
**Describe the bug**
Ctrl-F for find no longer brings up the find dialog. Worked in previous version.
Also, the Edit/Find  menu does not bring up a find dialog 

**To Reproduce**
1. Go to a .kmn file and look at source
2. Click CTRL F and nothing happens
3. Click Edit / Find and nothing happens

**Expected behavior**
I would like to be able to search my keyboard source files, both the .kmn and the keyman-touch-layout

---

**Keyman Developer (please complete the following information):**
 - OS: [Windows 10]
 - Keyman version: [e.g. 12.0.61.0 stable]
 - Target Application: [Developer]
  

---
 
**Additional context**
Ctrl g in glyph window works

**Comment by mcdurdin** [comment]
Okay, I am seeing this; it might be related to focus fixes recently. Will investigate.

**Comment by mcdurdin** [comment]
Found the issue; fix on its way 😊
