### ISSUE TITLE
Cloud Services should allow user to set default keyboard and whether keyboard should be remembered

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#243]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Thursday Nov 14, 2013 at 03:55 GMT_
_Originally opened as KD-234_

----
cf case X54059

Is this a KMEW issue, or a cloud management matter?

**Comment by mcdurdin** [comment]
No longer relevant; only really for keymanweb.com and already working.
