### ISSUE TITLE
Unable to replace previously installed KMP from ad-hoc file

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#2455]
> ,kmp shows up in Files and when selected, a window pops up with some info, and an option to open in Keyman. It  'opens' a blank page with a teeny menu at the bottom left with an "Open in" option. (As if the first Open was not serious enough!) and when "Open in" is chosen the same Error "Unable to copy..." appears.
> 
> _Originally posted by @orewJ in https://github.com/keymanapp/keyman/issues/2356#issuecomment-565797339_

I was able to duplicate @orewJ's issue with the khmer_angkor keyboard, resulting in the following error logs:

```
2019-12-17 08:13:32.618 [Error] [AppDelegate.swift:33] application(_:open:options:) > Error Domain=NSCocoaErrorDomain Code=516 "“khmer_angkor.kmp” couldn’t be copied to “Documents” because an item with the same name already exists." UserInfo={NSSourceFilePathErrorKey=/Users/jahorton/Library/Developer/CoreSimulator/Devices/E65CBD87-920C-4A4F-8B58-51CB42B2DEAE/data/Containers/Data/Application/5317D0F6-F19D-48D0-97D2-BFA3480CE64C/tmp/Tavultesoft.Keyman-Inbox/khmer_angkor.kmp, NSUserStringVariant=(
    Copy
), NSDestinationFilePath=/Users/jahorton/Library/Developer/CoreSimulator/Devices/E65CBD87-920C-4A4F-8B58-51CB42B2DEAE/data/Containers/Data/Application/5317D0F6-F19D-48D0-97D2-BFA3480CE64C/Documents/khmer_angkor.kmp.zip, NSFilePath=/Users/jahorton/Library/Developer/CoreSimulator/Devices/E65CBD87-920C-4A4F-8B58-51CB42B2DEAE/data/Containers/Data/Application/5317D0F6-F19D-48D0-97D2-BFA3480CE64C/tmp/Tavultesoft.Keyman-Inbox/khmer_angkor.kmp, NSUnderlyingError=0x6000036b2f40 {Error Domain=NSPOSIXErrorDomain Code=17 "File exists"}}
```

The existing design of the iOS app currently prevents updating language resources through KMPs due to an interaction with #1899.  Even if a user de-installs the resources corresponding to the KMP, the app will block attempts to replace/overwrite the original KMP.

Basically, it's due to errors in file handling logic on our end.  We'll need to address file management shortly with #2356 anyway, so identifying this now is a good thing.

**Comment by orewJ** [comment]
Thanks for the efforts... I'll stay hopeful:)
