### ISSUE TITLE
Touch Layouts need to support permanent vs transitory layer selection

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#246]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Monday Dec 30, 2013 at 21:51 GMT_
_Originally opened as KD-223_

----

Implementing transitory vs permanent shift states:
1.	Every layer switch key has a flag determining whether it switches to the new layer for just a single keystroke (transitory) or until the user swaps to another layer (permanent).
2.	The keyboard touch layout editor will have a checkbox next to the “Next Layer” box to implement this flag.
3.	When transitory, tapping any key will swap back to the previous layer afterwards.
4.	The user can override the transitory state by double-tapping on the layer switch key: the layer switch then becomes permanent.
5.	When in permanent state, the keyboard will remain in that layer until another layer switch key (either in the layout file or in code) is tapped.
6.	When keyboard is dismissed or another field activated, then default layer is selected.
7.	When in a permanent state, any key with “Special (active)” key type may be restyled to indicate that the layer change is permanent. This is implemented by a ‘.keymanweb-permanent’ or ‘.keymanweb-transitory’ CSS class applied to the keyboard element.
8.	Holding SHIFT on the default template will show also a CAPS sub key which is a ‘permanent’ shift.

**Comment by mcdurdin** [comment]
Closing this issue; more refined discussion and spec in #3620.
