### ISSUE TITLE
[Developer] Inserting a Character from the Character Map is No Longer Possible

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#2466]
**Describe the bug**
When double clicking on a character in the Character Map, nothing happens.

**To Reproduce**
1. Go to 'Character Map'
2. Double Click on 'any character'
3. See error

**Expected behavior**
The character double-clicked on should be inserted in the text editing area.

---

**Keyman Developer:
 - OS: [Windows 10 1909]
 - Keyman Developer version: [e.g. 12.0.64.0]

**Comment by mcdurdin** [comment]
# User Testing:

Please follow the steps in the problem description :) (Specifically, I believe this was happening only with text editors?)

**Comment by MakaraSok** [comment]
@mcdurdin Fix confirmed in Desktop Layout.

Touch Layout however still can't double click to insert any character to the key cap.
