### ISSUE TITLE
[Developer] v12.0.64.0, "(Start Product)" Shortcut cannot find kmshell

### ISSUE THREAD

**Issue by dyacob** [keymanapp/keyman#2467]
**Describe the bug**
The Windows 10 shortcut to launch keyman desktop fails to find kmshell (see screenshot).  The shortcut has been added by a created installer under Keyman Developer.

**To Reproduce**
1. Create a keyboard package that includes a "Shortcuts" entry that uses the "Program" option "(Start Product"
2. Compile an installer with  Keyman Developer 12.0.64.0
3. Run the installer.
4. Go to the Windows Start Menu, locate the newly installed keyboard package entry.
5. Click on the shortcut associated with the "(Start Product)"  entry.
6. The error dialog in the attached screenshot will appear.

**Expected behavior**
The Keyman Desktop application will start.

**Screenshots**

![Keyman-Start-Problem](https://user-images.githubusercontent.com/8098333/71393981-337c3680-25dd-11ea-8da9-dae78b6d8bcb.PNG)

---

**Keyman Desktop, Keyman for macOS, Keyman for Linux (please complete the following information):**
 - OS: Windows 10 Pro 1903
 - Keyman version:  Developer  v12.0.64.0
 - Target Application: Windows Start Menu

**Comment by dyacob** [comment]
I see this issue continuing with version v12.0.66.0

**Comment by mcdurdin** [comment]
This fix is in the 13.0 release tier.
