### ISSUE TITLE
WordPress Plug-In issues

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#247]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Thursday Dec 19, 2013 at 20:11 GMT_
_Originally opened as KD-221_

----

Three immediate issues on iPad: 
(1) Field alignment sometimes still wrong, e.g. on reply page, the name and comment fields are mis-aligned.
(2) Touching enter does not generate the search action - may be a form input field issue not being handled in JS.
(3) When focus moved to non-KMW input, the KMW caret and keyboard remains visible.

Tested with uncompiled debug build, based on build 339 with corrections for menu position and other issues.

**Comment by jahorton** [comment]
At this time, we have discontinued the old WordPress plugin.
