### ISSUE TITLE
[Windows] Can't type in the Keyman Proxy Server Configuration screen

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#2471]
User reported issue from [Community Site](https://community.software.sil.org/t/cant-type-in-the-keyman-proxy-server-configuration-screen/2909)

> In the Keyman options for configuring a proxy server I can’t type in any of the four fields. I can paste into each field from the Windows clipboard so I had to put the text I wanted in Notepad, select it and copy it to the Windows clipboard and then paste it into each proxy server field.

------------
This seems to be an intermittent issue when I reopen the Proxy Server Configuration panel. 

### Steps to Replicate
1. Launch Keyman Configuration
2. Click "Keyboard Layouts" panel (default panel)
3. Click "Options" panel --> "Advanced" --> "Proxy Settings..."
4. Try to type in the panel.

![proxy server](https://user-images.githubusercontent.com/7358010/71864170-a800ba80-3131-11ea-8f22-c10a89bde4ae.png)

Possible workarounds:
1. Sometimes tabbing through the fields get it editable
2. After re-opening the panel several times, sometimes the fields become editable

### Configuration:
Keyman Desktop 12.0.64.0 stable
Windows 10 Version 1909 (OS Build 18363.535)

**Comment by mcdurdin** [comment]
This issue will be resolved with the Chromium work in #1720. This is one of the reasons we need the Chromium replacement (apart from IE being completely obsolete).
