### ISSUE TITLE
[Windows] Keyman Configuration IE Javascript is disabled

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#250]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Friday Feb 19, 2014 at 20:53 GMT_
_Originally opened as KD-2_

----

The Keyman Configuration panel is unresponsive

Had remote session for X55071 but not resolved

**Comment by mcdurdin** [comment]
Resolved with move to Chromium (#1720)
