### ISSUE TITLE
KMN file corrupted during save

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#251]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Saturday Apr 12, 2014 at 02:06 GMT_
_Originally opened as KD-7_

----

Sometimes when the file is edited and saved, the line `store(&WINDOWSLANGUAGES)` gets corrupted.
The string `x045E`, is replaced by a string with 1024 copies of that language code. It doesn't do it every time, but it happens fairly often, both when saving explicitly (Ctrl S) and when saving when prompted before a build - which then fails until the file can be successfully saved with the corrected string.

Not always `x0154` - e.g. for Tamil keyboard, `x0449` got duplicated several times, presumably by same bug.

**Comment by mcdurdin** [comment]
I believe this was fixed a long time ago. Certainly has not seen repro in recent work.
