### ISSUE TITLE
[iOS] Default resource updates

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#2512]
**Describe the bug**
Currently, KMEI packages `nrc.en.mtnt-0.1.2.model.kmp`.  We have a more up-to-date version available, so we should package that instead.

Past that, however, there's an issue with how KMEI ensures that its resources are installed.  I've yet to double-check this for keyboards (SIL EuroLatin), but I've noticed that KMEI will automatically reinstall the MTNT model every time the app restarts - possibly undoing downloaded updates to the resource!

**To Reproduce**
1. Install and open the Keyman app (Simulator use is fine, and actually recommended here)
2. Terminate the app
3. Set a breakpoint at some stage of the lexical model installation process
4. Re-run the app

The breakpoint will be reached, with the app paused during lexical model installation - despite the fact that the first installation already installed MTNT!

**Expected behavior**
I would expect KMEI to note that:

1.  MTNT has already been installed
2.  The installed version either matches or is greater than the pre-packaged version

Based on these two factors, I would then expect it to bypass installation of the model.

**iPhone/iPad/Android (please complete the following information):**
 - Keyman version: 12.0 and 13.0
- iOS version, device, etc doesn't matter - it's an app control-flow logic issue.

**Comment by darcywong00** [comment]
fwiw on the Android app

On a fresh install, after installing the default lexical model, the app saves a boolean in the shared preferences. This way if the user intentionally uninstalls the default model, the lexical model won't get reinstalled when the app restarts.
