### ISSUE TITLE
Word suggestion broken

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#2516]
**Describe the bug**
Word suggestion is provided based on the "letter" left of the cursor and not "letters/part of the word" left of the cursor

**To Reproduce**
Install keyman alpha 13.0.49 and Eurolatin keyboard
Type any text in notes, it would be obvious in the word suggestion

**Expected behavior**
Word suggestion should be based on the part of the word or letters to the left of the cursor.

**Screenshots**
![IMG_3721](https://user-images.githubusercontent.com/14062593/72915133-6d884780-3d05-11ea-988a-be996b162943.PNG)
![IMG_3722](https://user-images.githubusercontent.com/14062593/72915134-6d884780-3d05-11ea-961b-838e409d4df0.PNG)
![IMG_3723](https://user-images.githubusercontent.com/14062593/72915132-6d884780-3d05-11ea-92d8-0ea407e91982.PNG)

**Keyman Desktop, Keyman for macOS, Keyman for Linux (please complete the following information):**
**iPhone/iPad/Android (please complete the following information):**
 - Device: [e.g. iPhone 6]
 - OS: [e.g. iOS 8.1]
 - Keyman version [e.g. 10.0.111]
 - Target application: [e.g. Notes, Keyman]

**KeymanWeb (please complete the following information):
 - OS: [e.g. Windows 7, Windows 10 1803, macOS Mojave, Ubuntu 18.04, Android 8.1]
 - Browser: [e.g. Chrome, Firefox]
 - KeymanWeb Version: [e.g. 10.0.201]
 - URL: [e.g. https://example.com/web_keyboard/]
 
**Keyman Developer (please complete the following information):
 - OS: [e.g. Windows 7, Windows 10 1803]
 - Keyman Developer version: [e.g. 10.0.1206.0]
 
---
 
**Keyboard**
 - Keyboard name: EuroLatin (SIL)
 - Keyboard version: 1.8.1
 - Language name: latin

**Additional context**
I think this is related with "Word breaking" algorithm

**Comment by jahorton** [comment]
This is also happening within the app... looks like the context stopped being managed properly.  I'll be right on it.
