### ISSUE TITLE
First word suggestion from the dictionary is not displaying quotes correctly on RTL text.

### ISSUE THREAD

**Issue by rmlockwood** [keymanapp/keyman#2522]
I'm using the dictionary (word list) feature for a right-to-left language (Balochi). The keyboard is called Balochi phonetic. When I type a letter it shows the leftmost word as being in quotes. The problem is there seems to be a paragraph flow issue so that that one letter is on the left and both the opening and closing quotes are on the right. See screenshot.
![Screenshot 2020-01-23 at 10 42 05 AM](https://user-images.githubusercontent.com/7088137/72973814-329e1680-3dce-11ea-93db-c23836ea25e7.png)

**Comment by jahorton** [comment]
Note that a full fix of this issue will require resolution of #2556.  That stated, the other requirements to resolve this issue are now in place.
