### ISSUE TITLE
Blank keyboard area

### ISSUE THREAD

**Issue by rmlockwood** [keymanapp/keyman#2524]
Often when I switch back to an app where I was last using a Keyman keyboard the typing area is completely gray. It's difficult to get the gray to go away and show me the keyboard, but usually clicking on a tool bar button or something that will repaint the screen with something else and then closing the thing will show the Keyman keyboard again. I've had this happen in multiple apps, even in the Keyman app itself. It happens often so I can usually get it to happen, but I can't give steps that will cause it to happen. It seems like when the app gets taken out of resident memory or something and then has to be brought back in when the app is recalled it happens. So when I haven't used the app for a while and then go back to it, it seems to happen. It seems to happen regardless of which keyboard I'm using.

I'm using Keyman on an iPhone 7 with OS 13.3 and the Keyman app is version 12.0.62. I have the EuroLatin keyboard, Balochi phonetic, and other Balochi keyboards installed.
![Screenshot 2020-01-23 at 11 16 36 AM (002)](https://user-images.githubusercontent.com/7088137/72976589-28cae200-3dd3-11ea-95af-ecc42080c253.png)

**Comment by mcdurdin** [comment]
We're tracking this in #2259.

**Comment by mcdurdin** [comment]
Can you test beta 13.0.65 and see if that resolves this for you? (https://keyman.com/beta)

**Comment by rmlockwood** [comment]
The beta version seems to be working well. I’m not seeing the blank keyboard any more.
