### ISSUE TITLE
No output from U_xxxx keys for xxxx less than 00FF

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#253]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Saturday Mar 29, 2014 at 03:44 GMT_
_Originally opened as KD-9_

----

The convention adopted is that T_xxxx keys will only ever output a character if matched by a rule, and will never fire the nomatch rule, but U_xxxx keys should fire the nomatch rule if not matched, allowing KeymanWeb to output the character U+xxxx. However, this does not appear to be working for xxxx < 00FF, as only keys with xxxx > 00FF produce ouput if unmatched by a rule.

A workaround is to include rules for all U_xxxx keys with xxxx < 00FF.

@mcdurdin adds:
> OK, this is happening because KIK doesn’t recognise the key as it isn’t in the key dictionary, because currently the compiler only adds keys that are referenced in rules to the key dictionary. Seems to me the proper solution is for the compiler to enumerate all the keys on the touch layout as well and any relevant keys to the key dictionary.

kmwosk.js:815 says:
```javascript
// Set LisVirtualKey to false to ensure that nomatch rule does not fire for U_xxxx keys
if (keyName.substr(0,2) == 'U_') 
    Lkc.LisVirtualKey=false;
```
But should say:
```javascript
// Set LisVirtualKey to false to ensure that nomatch rule does fire for U_xxxx keys
if (keyName.substr(0,2) == 'U_') 
    Lkc.LisVirtualKey=false;
```

> Working through this a little more right now. If the keyboard is mnemonic, then it should work?
If the keyboard is positional, it uses _USKeyCodeToCharCode to validate, which seems wrong to me.

**Comment by mcdurdin** [comment]
Fixed some time ago.
