### ISSUE TITLE
[mac] Installing on macOS is such a hassle

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#2536]
See https://community.software.sil.org/t/workaround-for-installation-on-macos-catalina/2950 for a real issue.

The steps required for installation on macOS need handholding with clear instructions, and if possible, automation. At present, there are multiple hoops to jump through, and most of them are not immediately obvious. The reported issue above is a total blocker for an unwary user.

I would like to work through the steps we need to go through and provide visual pointers and interaction for those such as the Security one which must be performed by the user. If we are able to enable the Input Method ourselves, that's great; otherwise we'll need to show that step-by-step as well.

**Comment by darcywong00** [comment]
Is this resolved in #2537 ?

**Comment by mcdurdin** [comment]
It's close enough for now. We have an aspiration to build a ObjC installer. It doesn't actually do the security stuff but that's less awful than it was.
