### ISSUE TITLE
Font definitions for touch are overridden by OSK font?

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#255]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Tuesday Sept 23, 2014 at 20:57 GMT_
_Originally opened as KD-215_

----

It appears that the .kmw-key-text font definition setup in osk.addFontStyle overrides the touch layout font definitions.

**Comment by jahorton** [comment]
No longer accurate/relevant.
