### ISSUE TITLE
feat(developer): Support isRTL for lexical models

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#2556]
Per #2554, Keyman Developer lexical model editor needs UI to be able to set the lexical model property of `isRTL`. Compiler and parser need to be validated as well.

**Comment by darcywong00** [comment]
Is this separate from the Package Editor --> Lexical Models checkbox for "Is Right to left"?

**Comment by darcywong00** [comment]
RTL info (at the model or package level?) should also get propagated when the `.model_info` file is merged.
