### ISSUE TITLE
URL address not found 

### ISSUE THREAD

**Issue by Helal50** [keymanapp/keyman#2569]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

---

(Delete the irrelevant sections)

**Keyman Desktop, Keyman for macOS, Keyman for Linux:**
 - OS: [e.g. Windows 7, Windows 10 1803, macOS Mojave, Ubuntu 18.04]
 - Keyman version: [e.g. 10.0.1206.0]
 - Target Application: [e.g. Firefox 55]
  
**iPhone/iPad/Android:**
 - Device: [e.g. iPhone 6]
 - OS: [e.g. iOS 8.1]
 - Keyman version [e.g. 10.0.111]
 - Target application: [e.g. Notes, Keyman]

**KeymanWeb:**
 - OS: [e.g. Windows 7, Windows 10 1803, macOS Mojave, Ubuntu 18.04, Android 8.1]
 - Browser: [e.g. Chrome, Firefox]
 - KeymanWeb Version: [e.g. 10.0.201]
 - URL: [e.g. https://example.com/web_keyboard/]
 
**Keyman Developer:**
 - OS: [e.g. Windows 7, Windows 10 1803]
 - Keyman Developer version: [e.g. 10.0.1206.0]
 
---
 
**Keyboard**
 - Keyboard name: [e.g. khmer_angkor]
 - Keyboard version: [e.g. 1.0.1]
 - Language name: [e.g. Khmer]

**Additional context**

**Comment by mcdurdin** [comment]
Hi @Helal50, thanks for your bug report. However, we you haven't added any detail in the report so not sure what it is referring to. Can you edit your first comment at https://github.com/keymanapp/keyman/issues/2569 (click on the [...] icon next to the smiley face) and fill in the details?
