### ISSUE TITLE
[iOS] CODE_BEEP should send a vibration or sound

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#257]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Wednesday Jul 1, 2015 at 22:40 GMT_
_Originally opened as KD-91_

----
Similar to #266 

Since KMW engine handles all codes, it should send a command to vibrate or sound on `CODE_BEEP`

**Comment by jahorton** [comment]
Of note - both this issue and #266 will require changes to KeymanWeb, as it does not presently provide a separate mechanism for embedded-mode to signal a 'beep' to the embedding apps.  It'd take just a minor amount of refactoring to do, but the extra work rightly pushes this past 10.0's release.
