### ISSUE TITLE
[Linux] Rules misbehave if line length is more than 100 characters

### ISSUE THREAD

**Issue by sreerajp** [keymanapp/keyman#2575]
The issue is noticed with Malayalam keyboard we developed. I have added a rule in keyman keybaord layout file wherein after space some characters should not appear. This rule is working prefectly OK if the characters of the sentence is less than 100, but if this is greater than 100 the rule is not working.

In Windows and MAC no such issue is there.
Attached all the files

[G.zip](https://github.com/keymanapp/keyman/files/4148194/G.zip)

**Comment by darcywong00** [comment]
Sounds similar to issue #2002

**Comment by darcywong00** [comment]
Jotting some testing notes with the attached keyboard:

### Testing Configurations

Windows 10
Keyman Desktop 13.0.66.0 Beta
Application: Visual Studio Code
Rule works fine with 100+ characters

18.04 Ubuntu
Keyman for Linux 13.0.23 Beta
Application: Visual Studio Code
Rule fails

**Comment by darcywong00** [comment]
I think this is tied to a constant [MAXCONTEXT](https://github.com/keymanapp/keyman/blob/master/common/engine/keyboardprocessor/src/kmx/kmx_context.h#L10) that the keyboardprocessor Core is using for the context length. (Currently set to 64)

**Comment by sreerajp** [comment]
I have also doubted that. But the constant MAXCONTEXT is also being used in Windows and MAC, right. So there it is not showing any issue.

**Comment by darcywong00** [comment]
Currently, only Keyman for Linux uses the Keyman Core . See https://help.keyman.com/developer/core/desktop/11.0/ for more info

**Comment by sreerajp** [comment]
OK. So kmx_context.cpp won't work in Windows and MAC, right. So the following code will not work in Windows and MAC.

void KMX_Context::Add(KMX_WCHAR ch)
{
  if(pos == MAXCONTEXT - 1)
  {
    memmove(CurContext, &CurContext[1], MAXCONTEXT*2 - 2); pos--;
  }

  CurContext[pos++] = ch;
  CurContext[pos] = 0;

  DebugLog("KMX_Context: Add(%x) [%d]: %s", ch, pos, Debug_UnicodeString(CurContext));
}

**Comment by sreerajp** [comment]
Why I am asking is because when I did a debug mode run of Keyboard in Windows. I got the 'pos' variable value as 63 and after that it was not increasing. That is why I am asking. And by the way I am using Keyman 12.0.64.0

**Comment by darcywong00** [comment]
After further investigation, we determined the bug is in Keyman Core [KMX_Context::Set](https://github.com/keymanapp/keyman/blob/master/common/engine/keyboardprocessor/src/kmx/kmx_context.cpp#L81) when the context window is adjusted for full buffers.

We creating additional unit tests to go with the fix, and aim to release the fix in 13.0 Beta next week.

**Comment by mcdurdin** [comment]
This is fixed in 13.0.27 beta.
