### ISSUE TITLE
[developer] Click to insert a character to the key cap on Touch Layout

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#2577]
**Describe the bug**
"Insert Character" functionality is gray out when trying to use it with Touch Layout.

![image](https://user-images.githubusercontent.com/28331388/73708296-87c41b80-4730-11ea-97d3-6711043601ef.png)

**To Reproduce**
1. Go to 'Touch Layout'
2. Right click or double click on any character in the Character Map
3. See error

**Expected behavior**
The character double-clicked on should be inserted to where the cursor is. Also when it's right-clicked on, the "Insert Character" should be enabled and worked.

---

**Keyman Desktop:**
 - OS: Windows 10 Pro 1909
 - Keyman version: 13.0.65.0
 
**Keyman Developer:**
 - Keyman Developer version: 13.0.65.0
 
---

**Additional context**
Related **fixed** issue: https://github.com/keymanapp/keyman/issues/2466

**Comment by mcdurdin** [comment]
Testing note: if you first drag and drop onto the touch layout editor, subsequently the "Insert character" menu item is enabled and double-click works. This suggests a state issue when first opening the touch layout editor.

**Comment by mcdurdin** [comment]
Fixed in #2619 (beta 13.0.71)
