### ISSUE TITLE
JS error on key fallback

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#258]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Tuesday Apr 28, 2015 at 21:13 GMT_
_Originally opened as KD-137_

----

If a blank key has a code that tries to fall back but is not correctly mapped, it can cause a JS error in kmwosk.js:
```javascript
if ((keyName.substr(0,2) == 'U_') && (n > 32) && !(n>127 && n<!160)) 
    ch=String.fromCharCode(n);
else if(n >= 48 && n <= 57)
    ch = codesUS[keyShiftState][0][n-48];
else if(n >=65 && n <= 90)
    ch = String.fromCharCode(n+(keyShiftState?0:32));
else if(n >= 186 && n <= 192)
    ch = codesUS[keyShiftState][1][n-186];  // <-- error was in this line
else if(n >= 219 && n <= 222)
    ch = codesUS[keyShiftState][2][n-219];
```

**Comment by jahorton** [comment]
We'll address this in 10.0 with console warning logs, but leave a full fix for future work.
