### ISSUE TITLE
[mac] Shift does not work as expected

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#2582]
**Describe the bug**
Shift state output exactly the same as the Default state. Instead of a Capital version of the character, the small cap is output. 

**To Reproduce**
1. Go to 'Notes' on Mac
2. Click to choose Mongolian Cyrillic QWERTY from Keyman Keyboard list
3. Type in the Note: "ai" and "AI"

**Expected behavior**
Shift should output capital letter.

**Screenshots**
Left: Notes on mac
Right: Notepad on Windows.
![image](https://user-images.githubusercontent.com/28331388/73724684-7abe2100-475e-11ea-95c5-4cb4354171ff.png)

---

**Keyman Desktop:**
 - OS: macOS Mojave 10.14.6
 - Keyman version: 12.0.50
 - Target Application: Notes
 
---
 
**Keyboard**
 - Keyboard name: Mongolian Cyrillic QWERTY
 - Keyboard version: 2.0 (in the process of updating)
 - Language name: Mongolian
 - Source folder: [mongolian_cyrillic_qwerty.zip](https://github.com/keymanapp/keyman/files/4152023/mongolian_cyrillic_qwerty.zip)

**Additional context**
When testing in the Developer, everything configured for desktop layout is working as expected.
(Keyman Developer 13.0.65.)

**Comment by mcdurdin** [comment]
In my testing with the latest pre-beta build (#2588), this worked successfully. Please retest with build attached here:
[keyman-13.0.0.dmg.zip](https://github.com/keymanapp/keyman/files/4189027/keyman-13.0.0.dmg.zip)

**Comment by MakaraSok** [comment]
Tested and the Shift is now working as expected. Thank you, Marc.
