### ISSUE TITLE
[mac] Text-based programs vs browser based and more advanced word-processing programs

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#2586]
**Describe the bug**
Keyman for mac v. 12.0.50 behaves differently on ordinary Text-based programs (i.e. Messages, TextEdit, Notes, Safari and Stickies) and more advanced word-processing programs as well as browser-based or electron-based programs (i.e. LibreOffice)

**To Reproduce**
1. Install Sanskrit Devanāgarī (HK) (see below) on macOS Mojave 10.14.6
2. Test the three key sequences (i.e. mu, kh, ti) on LibreOffice and Notes
3. See the differences/errors

**Expected behavior**
Test 1:
- “Key Press,” m + u
- “Actual Output” म्
- “Expected/Correct Output” मु

Test 2:
- “Key Press,” k + h
- “Actual Output” क्
- “Expected/Correct Output” ख्

Test 3:
- “Key Press,” t + i
- “Actual Output” त्
- “Expected/Correct Output” ति

**Screenshots**
left: Notes v. .6
right: LibreOffice v. 6.2.5.2
![image](https://user-images.githubusercontent.com/28331388/73803307-f2d62680-47f2-11ea-9004-990cf8b34ba4.png)

---

**Keyman for macOS:**
 - OS: macOS Mojave v. 10.14.6
 - Keyman version: 12.0.50
 - Target Application: Notes v. .6 and LibreOffice v. 6.2.5.2

---
 
**Keyboard**
 - Keyboard name: Sanskrit Devanāgarī (HK)
 - Keyboard version: [testing] - derived from https://community.software.sil.org/t/problems-with-mac-os/2933?u=makara
 - Language name: Devanāgarī 
 - Keyboard file: [sanskrit_deva.zip](https://github.com/keymanapp/keyman/files/4157051/sanskrit_deva.zip)

**Additional context**
https://community.software.sil.org/t/problems-with-mac-os/2933/5

**Comment by mcdurdin** [comment]
I'm really appreciating the high quality bug reports! These are so easy for me to investigate further, with the attached keyboard file ready to try and lots of detail that helps me to reproduce the issue precisely. Well done!

(Now I'll start testing this issue!)

**Comment by mcdurdin** [comment]
Can you test this with the latest version in https://github.com/keymanapp/keyman/issues/2582#issuecomment-584900959 and latest version of LibreOffice (6.4.0.3) because in my testing with those two versions, it worked successfully.

**Comment by MakaraSok** [comment]
> Can you test this with the latest version in [#2582 (comment)](https://github.com/keymanapp/keyman/issues/2582#issuecomment-584900959) and latest version of LibreOffice (6.4.0.3) because in my testing with those two versions, it worked successfully.

Tested, but it still does not work for me on this keyboard. The latest version of LibreOffice (v 6.4.0.3) was used to test this--i.e. `mu` output `म्` not `मु`.

Also, the context dependent rules of this keyboard [Mongolian Cyrillic QWERTY](https://github.com/keymanapp/keyman/files/4152023/mongolian_cyrillic_qwerty.zip) do not work either--i.e. `ai` output `а` not `ай`; `AI` output `А` not `АЙ`.

**Comment by mcdurdin** [comment]
I wonder if it is a macOS version difference then. I tested again and both of those keyboards are working correctly on my machine with Keyman 13.0-test-2588 (that test version) and LibreOffice 6.4.0.3 and macOS Catalina 10.15.3.

I will try now in a VM with an earlier build of macOS.

**Comment by mcdurdin** [comment]
> I will try now in a VM with an earlier build of macOS.

Okay, I've tested in macOS Mojave now and it works there as well. One possibility: can you check that Keyman is allowed to control your computer in System Preferences / Security & Privacy / Privacy / Accessibility?  When I had that disabled, then integration with LibreOffice was not working correctly.

**Comment by MakaraSok** [comment]
I thought Keyman is allowed because I saw it in the list as shown below,
but actually not. It is not "ticked". Once it is ticked, the rules work.
[image: image.png]

**Comment by MakaraSok** [comment]
![image](https://user-images.githubusercontent.com/28331388/74393328-5936f680-4e3c-11ea-9173-9798b6b98aa5.png)
