### ISSUE TITLE
[Windows] Keyman 13.0.65 alters output in Firefox 72.0.2

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#2587]
**Describe the bug**
Keyman Desktop 13.0.65 behaves correctly and consistently on MS Office Pro + 2016 v. 2001, Chrome 79.0.3945.130, LibreOffice 5.3.4.2; but differently on Firefox 72.0.2.

**To Reproduce**
1. Install Sanskrit Devanāgarī (HK) (see below) on Keyman for Windows
2. Test the three key sequences (i.e. mu, kh, ti) on MS Office, Chrome and LibreOffice and Firefox.
3. See the differences/errors in Firefox.

**Expected behavior**
<table>
<thead><tr><th>Test</th><th>MS Office</th><th>Chrome</th><th>LibreOffice</th><th>Firefox</th></tr></thead><tbody>
 <tr><td>mu</td><td>मु</td><td>मु</td><td>मु</td><td style="color: red;">ु</td></tr>
 <tr><td>kh</td><td>ख्</td><td>ख्</td><td>ख्</td><td>ख्</td></tr>
 <tr><td>ti</td><td>ति</td><td>ति</td><td>ति</td><td>ि</td></tr>
</tbody></table>

---

**Keyman Desktop:**
 - OS: Windows 10 Pro 1909
 - Keyman version: 13.0.65
 - Target Application: Firefox 72.0.2

---
 
**Keyboard**
 - Keyboard name: Sanskrit Devanāgarī (HK)
 - Keyboard version: [testing] - derived from https://community.software.sil.org/t/problems-with-mac-os/2933?u=makara
 - Language name: Devanāgarī 
 - Keyboard file: [sanskrit_deva.zip](https://github.com/keymanapp/keyman/files/4157051/sanskrit_deva.zip)

**Additional context**
https://community.software.sil.org/t/problems-with-mac-os/2933/5

**Comment by mcdurdin** [comment]
See also #889 #1107 #1125 #1131

**Comment by mcdurdin** [comment]
Tracking in #3710. Potential fix in Firefox.
