### ISSUE TITLE
[Windows] Prevent Keyman from requiring admin logons when loading/setting keyboards and languages

### ISSUE THREAD

**Issue by KenZook** [keymanapp/keyman#2590]
**Is your feature request related to a problem? Please describe.**
The Dallas center, and apparently the computer world is switching users to non-administrative accounts to prevent the bad guys from getting in. So any time something requires a Windows elevation, instead of just clicking OK, you have to type in a password for an administrative account. With Keyman this gets to be very tedious. When installing and uninstalling any keyboard, it requires a password. Also, any time you add or remove a language from a keyboard requires typing a password. At times it takes numerous times adding and removing languages and/or keyboards, so you can end up typing in the password dozens of times. This gets especially tedious when working on a remote computer via Bomgar and the user needs to type this in all the time.

**Describe the solution you'd like**
From Marc: The tricky part is the delineation between logged in "current user" settings and admin "current user" settings. If you run Keyman Configuration elevated (e.g. hold Ctrl+Shift when clicking the Keyman Configuration icon in the Start Menu), it starts elevated but current user settings will be written to the Administrator's HKCU key instead of the logged-in user's HKCU key. This would require some plumbing to resolve in Keyman Configuration. Can you write this up as a feature request because I certainly think it's worth pursuing ... one day!

**Describe alternatives you've considered**
Perhaps use file(s) under user for Keyman information instead of registry.

**Product context**
Windows 10

**Additional context**

**Comment by mcdurdin** [comment]
FWIW, the LM requirement is due to Windows not supporting installation of input methods under current user.

**Comment by mcdurdin** [comment]
This will be mitigated in Keyman 14 with #3509 / #3510, whereby elevation only usually needs to be done when installing/uninstalling the keyboard. There is more work to be done to allow for current-user de-elevation during TIP installation (see #3512).

We cannot avoid the elevation requirement entirely.

**Comment by mcdurdin** [comment]
#3520 deals with the de-elevation scenario for installation of profiles from the bootstrap installer.
