### ISSUE TITLE
Keyboard Upgrade Leads to Unexpected Keyboards in Menu

### ISSUE THREAD

**Issue by dyacob** [keymanapp/keyman#2592]
Keyman Desktop 12.0.66.0 notified me of updates available for a number keyboard that I had installed, I believe the updated keyboards are a result of the https://github.com/keymanapp/keyboards/pull/1035 .

After opting to install the keyboards, the additional keyboards "Geez (gez-Ethi-ET)", "Bilin (byn-Latn-ER)", "Blin" and "Tigrinya (Ethiopia)" (with black & white icon) appeared in the "Language preference" menu (see screenshot).

These additional keyboards are probably related to a Windows language setting.  The expected behavior is that these additional keyboards would not appear.

![Keyman-Update-Issue](https://user-images.githubusercontent.com/8098333/73901103-c7d5ec00-485f-11ea-860e-484f5ff77231.PNG)

**Comment by mcdurdin** [comment]
Thank you for the report. This is an issue we are aware of and are working on resolving. It's not yet clear to us if this is a bug in Keyman or Windows, because it's certainly a behaviour change between Win 7 and Win 10.

**Comment by mcdurdin** [comment]
See additional report at https://community.software.sil.org/t/keyman-keyboard-not-staying-active-cant-get-rid-of-extra-keyboard-windows-10/3177

**Comment by mcdurdin** [comment]
This should be fixed by #3509 and related PRs
