### ISSUE TITLE
[iOS] Blank Keyboard when an input element's contents are autoselected upon focus

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#260]
## Known devices with issue:

- iPhone SE (can also be replicated in iPhone SE simulator)

## Steps to reproduce:

- Set Keyman as the system keyboard
- Open Safari and click in the address bar.
- Set a Keyman keyboard as the current keyboard.
- Open a new page in Safari
- Click in the address bar.

Result:

![image](https://user-images.githubusercontent.com/25213402/29903493-580694bc-8e2e-11e7-9537-c173c8ddc8f1.png)

## Temporary User Workaround

- After the above, click in the address bar until its contents are deselected.
  - If the address bar is empty, click a couple of times as if it *did* have contents.

The keyboard should no longer be blank and will function normally.

------

It appears that on some devices, the fact that Safari likes to automatically select the contents of the address bar is interfering with the Keyman system keyboard's OSK display, and that the problem is due to code related to text selection.

**Comment by gabrielwong** [comment]
Fixed in #434
