### ISSUE TITLE
[mac] Context-dependent rules do not work in Chrome

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#2617]
**Describe the bug**
The following context-dependent rules have been created and tested in Keyman Developer. 

```
c Context Dependent Rules
U+0430 + [K_I]          > 'ай'      c ai = ай
U+0410 + [SHIFT K_I]    > 'АЙ'      c AI = АЙ
U+043E + [K_I]          > 'ой'      c oi = ой
U+041E + [SHIFT K_I]    > 'ОЙ'      c OI = ОЙ
U+0443 + [K_I]          > 'уй'      c ui = уй
U+0423 + [SHIFT K_I]    > 'УЙ'      c UI = УЙ
U+0438 + [K_I]          > 'ий'      c ii = ий
U+0418 + [SHIFT K_I]    > 'ИЙ'      c II = ИЙ
U+044D + [K_I]          > 'эй'      c ei = эй
U+042D + [SHIFT K_I]    > 'ЭЙ'      c EI = ЭЙ
U+04AF + [K_I]          > 'үй'      c үi = үй
U+04AE + [SHIFT K_I]    > 'ҮЙ'      c YI = ҮЙ

U+0438 + [K_A]          > 'я'        c ia = я
U+0418 + [SHIFT K_A]    > 'Я'        c IA = Я
U+0438 + [K_E]          > 'е'        c ie = е
U+0418 + [SHIFT K_E]    > 'Е'        c IE = Е
U+0438 + [K_O]          > 'ё'        c io = ё
U+0418 + [SHIFT K_O]    > 'Ё'        c IO = Ё
U+0438 + [K_QUOTE]          > 'ы'        c i' = ы
U+0418 + [K_QUOTE]          > 'Ы'        c I' = Ы
U+0418 + [SHIFT K_QUOTE]    > 'Ы'        c I" = Ы (BOTH PRODUCE SAME CHARACTER. INTENTIONAL REDUNDANCY)
U+0438 + [K_U]          > 'ю'        c iu = ю
U+0418 + [SHIFT K_U]    > 'Ю'        c IU = Ю
U+0448 + [K_X]          > 'щ'       c xx = щ 
U+0428 + [SHIFT K_X]    > 'Щ'       c XX = Щ

U+002C + [K_COMMA]          > '„'   c ,, = „ (THIS IS THE COMMA KEY, INPUTTED TWICE)
U+002E + [K_PERIOD]         > '“'   c `` = “ (THIS IS PERIOD KEY, INPUTTED TWICE)
U+003C + [SHIFT K_COMMA]    > '«'   c << = « 
U+003E + [SHIFT K_PERIOD]   > '»'   c >> = »
U+201C + [K_PERIOD]         > '…'   c ... = … (THE PERIOD KEY, INPUTTED THRICE, GENERATES AN ELLIPSIS)
```

They work fine in other apps app on mac, but not in Chrome. The rules somehow get ignored and do not produce the expected output.

- Chrome - white background - product incorrect output
- TextEdit - Black background - produce correct output
- Key sequences are on the left most, i.e. "ai, AI, oi, OI"

![image](https://user-images.githubusercontent.com/28331388/74125466-f9580a00-4c07-11ea-8ae8-a8766774fe47.png)

**To Reproduce**
1. Install [Mongolian Cyrillic QWERTY](https://github.com/keymanapp/keyman/files/4152023/mongolian_cyrillic_qwerty.zip) keyboard on mac
2. Open TextEdit  and Chrome and type "ai, AI, oi, OI"
3. See error in Chrome

**Expected behavior**
Output in Chrome should be the same as that produced on TextEdit.

---

**Keyman for macOSx:**
 - OS: macOS Mojave 10.14.6
 - Keyman version: 12.0.5
 - Target Application: TextEdit and Chrome
  
---
 
**Keyboard**
 - Keyboard name: Mongolian Cyrillic QWERTY
 - Keyboard version: 2.0 (testing stage)
 - Language name: Mongolian

**Comment by mcdurdin** [comment]
I believe this is resolved in #2588 (were you testing in Google Docs?). Can you test this with the download from https://github.com/keymanapp/keyman/issues/2582#issuecomment-584900959?

**Comment by MakaraSok** [comment]
> I believe this is resolved in #2588 (were you testing in Google Docs?). Can you test this with the download from [#2582 (comment)](https://github.com/keymanapp/keyman/issues/2582#issuecomment-584900959)?

Tested, but it does not work as expected. The behavior here is similar to that of this: https://github.com/keymanapp/keyman/issues/2586. Only the first key triggers the output, then when the second key is pressed, nothing happens.

**Comment by mcdurdin** [comment]
As in #2586, can you verify the following setting: One possibility: can you check that Keyman is allowed to control your computer in System Preferences / Security & Privacy / Privacy / Accessibility?

**Comment by MakaraSok** [comment]
It's allowed:

[image: image.png]

**Comment by mcdurdin** [comment]
Sorry, that image was lost. Can you re-verify for me please?

**Comment by MakaraSok** [comment]
Shift states work on both TextEdit and Chrome now that Keyman is allowed to control the computer in the System Preference.
