### ISSUE TITLE
Import OSK to Touch layout bugs

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#263]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Friday Mar 7, 2014 at 23:35 GMT_
_Originally opened as KD-10_

----

1. Undefined (blank) OSK keys in shift layer will import corresponding default layer key.
2. Non-letter keys in shift layer not imported correctly, may get shifted original where mapping was to default (unshifted) character.

**Comment by mcdurdin** [comment]
Both of these issues appear to have been corrected a long time ago.
