### ISSUE TITLE
Create web page to generate JSON descriptions

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#264]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Tuesday Apr 1, 2014 at 20:33 GMT_
_Originally opened as KD-13_

----

1. Ask dev to enter url of keyboard.js
2. Page will load keyboard.js and parse it to get basic details
3. Form presented to fill in other details
4. Data will be validated and .json output presented.
This will be hosted on the dashboard in the future, but on tavultesoft.com/keymanweb/dev/buildjson.php for now.

**Comment by mcdurdin** [comment]
No longer relevant - this was for adhoc keyboard distribution for js keyboards, now managed through .kps.
