### ISSUE TITLE
After new installation project links don't work

### ISSUE THREAD

**Issue by rmlockwood** [keymanapp/keyman#2667]
I installed the latest beta and none of the links to my recent projects work. I click on any of the links and they don't respond.

![image](https://user-images.githubusercontent.com/7088137/74687508-de236680-51d4-11ea-90eb-273bdedc165f.png)

**Comment by rmlockwood** [comment]
There's nothing in the list for Project > Recent Projects

**Comment by mcdurdin** [comment]
Ha! Yes, I saw this and forgot about it. Thank you for reporting!
