### ISSUE TITLE
kmw-language-menu has wrong positioning, should be fixed but is absolute

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#267]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Friday Sept 26, 2014 at 01:02 GMT_
_Originally opened as KD-212_

----

This causes the menu to appear off the bottom of longer pages.

**Comment by jahorton** [comment]
Fixed by #2642.
