### ISSUE TITLE
bug(developer): New Project wizard always creates .keyman-touch-layout file

### ISSUE THREAD

**Issue by DavidLRowe** [keymanapp/keyman#2679]
**Describe the bug**
Minor annoyance: New Project wizard always creates .keyman-touch-layout file

**To Reproduce**
1. Use Project, New Project, Basic
2. Deselect 'any' and then select 'desktop' and 'web'
3. Create project
4. Note that wizard still
(a) created .keyman-touch-layout file
(b) referenced the .keyman-touch-layout file in the .kmn file
(c) included various touch device platforms in README.md

**Expected behavior**
It would be preferable if the wizard didn't create the .keyman-touch-layout file (or reference it in the .kmn file) or include touch platforms in the README.md when there is no touch platform selected in the wizard.

---

**Keyman Developer:**
 - OS: Windows 10 1903
 - Keyman Developer version: 13.0.72.0
 
---

**Additional context**
Workaround:
(a) delete .keyman-touch-layout file from source folder
(b) delete reference in .kmn file (or, alternatively, use Developer on Details tab to Remove Touch-optimised Keyboard)
(c) edit README.md file to remove unsupported platforms

**Comment by mcdurdin** [comment]
Thank you for this report -- clear as always and easy to action in a future update! It won't squeak into 13.0 though 😉
