### ISSUE TITLE
Selected Keyman keyboard not turning off for email or website inputs

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#268]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Friday Jan 24, 2014 at 03:55 GMT_
_Originally opened as KD-210_

----

If the Keymanweb keyboard is set, it will still output set language in input type of email or website, although osk and button/toolbar UI is hidden.
On mobile and tablet, keymanweb osk is replaced by system keyboard which does type correctly. Issue is only on desktop.

**Comment by darcywong00** [comment]
@mcdurdin adds
> From JMD: I ran out of time for looking a this, but in view of Marc’s comment that it is now legitimate to have (any?) Unicode characters in URL and (eventually, if not yet) email addresses, the simplest short-term fix would be to treat email and url input types as if they were text, and leave it up to the user to select the English keyboard.
For the longer term, my suggestion would be to include yet another class name that selects a particular keyboard for a particular input element, probably defaulting to English email and url input types. But this needs keyboard caching to be implemented, as discussed previously, which may or may not be simple – not sure without looking carefully at it.

**Comment by jahorton** [comment]
I agree with the assessment in the comment above - it is up to a page designer to block KMW from producing output in such controls if desired.  Of note is that with #114 (the recent Attachment API release in KMW 10.0 alpha) a number of tools addressing exactly this design has been made available.

As such, this will be considered resolved.
