### ISSUE TITLE
[Developer] version 14 alphas are not deploying

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#2687]
**Describe the bug**
https://downloads.keyman.com/developer/alpha/14.0.6/ shows keymandeveloper-14.0.6.0.exe is missing.

**Comment by darcywong00** [comment]
It looks like TC has a build number `14.0.6` but the artifact is `keymandeveloper-14.0.6.0.exe`. Somewhere, `.0` needs to be appended

**Comment by mcdurdin** [comment]
This is now resolved. It may be worth one more iteration to remove .0 from filenames and folders in build rather than appending the zero. But I will leave that for now.
