### ISSUE TITLE
API version 4.0 appears to be returning all versions of a keyboard, not just the latest, to KMW, for example with urdu

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#269]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Saturday Nov 8, 2014 at 03:55 GMT_
_Originally opened as KD-174_

----

This is causing addKeyboards to add the wrong version of keyboards to the list.

**Comment by jahorton** [comment]
This appears to have been resolved at some point since the original was posted, likely during work on the API itself.  Only the most current version of each keyboard is returned.
