### ISSUE TITLE
bug(developer): Ctrl+C doesn't work to copy from debugger text area

### ISSUE THREAD

**Issue by DavidLRowe** [keymanapp/keyman#2690]
**Describe the bug**
When trying to copy text from the Debugger's text area, the Ctrl+C shortcut doesn't work

**To Reproduce**
- Start Keyman Developer (13.0.76.0) and load release/basic/basic_kbdusx (though probably any keyboard would do)
- From Keyboard menu, click on Include Debugging Information (so that it is checked)
- On the "Build" tab, click "Compile Keyboard"
- Click "Start Debugging"
- Type "abc"
- Double-click on the "abc" text to select the characters
- Right click on the selected characters and select Copy (Observe the Ctrl+C shortcut)
- Open Notepad and type Ctrl+V and "abc" is pasted into the Notepad document.
- Back in Developer, type Backspace three times to clear the text, then type "def"
- Double-click on the "def" text to select the characters
- Type Ctrl+C
- Switch to Notepad and type Ctrl+V and "abc" (NOT "def" as expected!) is pasted in

**Expected behavior**
When Ctrl+C is listed as a shortcut on the right-click menu, I expect that typing Ctrl+C will copy the selected text!

---
**Keyman Developer:**
 - OS: Windows 10 1903]
 - Keyman Developer version: 13.0.76.0
 
---
 
**Keyboard**
 - Keyboard name: basic_kbdusx
 - Keyboard version: [e.g. 1.1]
 - Language name: US International
However, I expect any keyboard would show the same issue

**Additional context**
Either Ctrl+C should work for copying, or the right-click context menu should change.

**Comment by mcdurdin** [comment]
Thank you for the clear bug report. Will look into it for the next release!
