### ISSUE TITLE
If font source files are not defined, then KMEW delays 5 seconds on platforms without that font installed

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#270]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Sunday Oct 12, 2014 at 21:47 GMT_
_Originally opened as KD-207_

----

In a situation where a font name is defined in the keyboard metadata but no source file is listed, the KMEW engine waits 5 seconds (i.e. error condition) for the non-existent font to 'load'.
The following line of code should be added near the top of osk.waitForFonts or possibly a similar test in util.checkFontDescriptor?

```javascript
if (typeof(kfd['files']) == 'undefined' && typeof(ofd['files']) == 'undefined') 
    return true;
```

This avoids a delay for a font load where no font is actually being loaded.

**Comment by jahorton** [comment]
This appears to have been implemented at some point since the original issue was posted; the exact suggested line is part of the `osk.waitForFonts` method in kmwnative.js.
