### ISSUE TITLE
[linux] Add ibus-keyman as package dependency

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/keyman#2705]
When installing Keyman for Linux 13.0.103 one needs to have ibus-keyman installed.

Installing it separately should not be necessary, that should be part of the dependencies of the package so that it gets installed automatically.

See https://github.com/keymanapp/keyman.com/pull/85

**Comment by darcywong00** [comment]
The [ppa](https://launchpad.net/~keymanapp/+archive/ubuntu/keyman) has these packages
* ibus (@glasseyes uploaded, but we don't update)
* ibus-keyman
* ibus-kmfl
* keyman-config
* keyman-keyboardprocessor
* kmflcomp
* libkmfl
* onbard

Previous installation instruction:
`sudo apt-get install keyman onboard`

I *think* installing `keyman` added `keyman-config` and `keyman-keyboardprocessor`.

**Comment by ermshiperete** [comment]
`keyman` depends on `python3-keyman-config` and that has `ibus-keyman` as dependency, so this should already work.

**Comment by ermshiperete** [comment]
Looks like this was already added in #1391.

The official Ubuntu repo has the `keyman` package since version 19.10, but that's still at Keyman 11.
The ppa has Keyman 13. pso doesn't have keyman at all. llso-experimental has Keyman 14 for Ubuntu 16.04, 18.04 and 20.04.

**Comment by ermshiperete** [comment]
Tested this on Ubuntu 20.04 with Keyman 14 and it did install ibus-keyman.

**Comment by ermshiperete** [comment]
Keyman 13 is now available for Ubuntu 20.04 on ppa - and does install ibus-keyman as well.

**Comment by ermshiperete** [comment]
Keyman 11 (which is included in the official Ubuntu and Debian package repos) has a dependency on `ibus-kmfl`, so `ibus-keyman` won't be installed automatically if that version gets installed.
