### ISSUE TITLE
[Android] Mobile app feature request: Keyboard search

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#2708]
Android portion of #745 

> With our large catalogue of existing keyboards, it can be quite cumbersome to manually scroll through such a large list to find what a user is looking for. (It's definitely no help when doing simulation runs on debug testing, either.)
>
>Something that I'm sure users would find handy - could we include an option in our mobile apps' keyboard download screens to pull up our new keyboard search website? Said site already knows how to pass keyboards to the app, so integration should be possible.

From Keyman Team meeting discussions, we plan to revamp keyboard search so it directs the user to the keyman.com keyboard search.

TODO:
- [x] Handle deep linking to keyman.com/keyboards to download .kmp keyboard packages
- [x] Download keyboard packages with `keyman:download?` links
- [ ] Remove code involving api.keyman queries and caching keyboard catalog info
- [x] Have KMEA install sil_eurolatin.kmp as a package, not .js file
- [x] Have KMEA migrate away from `cloud/sil_eurolatin`
- [x] Have keyboard picker propagate language info (parse a dropdown)
- [x] Update cloud keyboard / lexical model updates to install into packages/ and not cloud/

- [x] Address review comment below:
> I do wonder if we need to be a little more specific on our URL parsing so that we treat keyman: and http[s]: as completely separate sources -- i.e. we never match on the query parameters for https: but we always do for keyman:. It's a little more hard nosed but means we don't accidentally end up with unexpected behaviour if we pass urls that are formatted differently in the future -- it will fail hard rather than weirdly ;-)

**Comment by sapradhan** [comment]
can we have a native search text box that filters language list in place?

**Comment by darcywong00** [comment]
> can we have a native search text box that filters language list in place?

While we do plan to localize the Keyman mobile apps in 14.0, the keyboard search will be an embedded view of https://keyman.com/keyboards

For now, the database backing the search stores all the information with English names.

**Comment by bennylin** [comment]
Could this future solution also search for:
* The script name (e.g. searching "Latin" or "Braille" would find all corresponding keyboards)
* The local name, in Latin 
* The local name, in its own script

**Comment by darcywong00** [comment]
For handling keyboard updates, try
https://api.keyman.com/keyboard/newa_traditional
https://downloads.keyman.com/api/keyboard/newa_traditional

**Comment by darcywong00** [comment]
I believe this issue is 99% complete now.
I'll split out the remaining item
> Remove code involving api.keyman queries and caching keyboard catalog info

to a separate issue for the future.
