### ISSUE TITLE
KeymanWeb.SetActiveKeyboard does not appear to update the toggle UI list setting

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#271]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Thursday Nov 14, 2013 at 03:01 GMT_
_Originally opened as KD-204_

----

V1.0 at least, is it still happening in V2.0?

JD adds:

>This has been resolved and works fine in KM2 build 355 (probably much earlier, too).

> Toggle UI is OK as are Button and Float UIs but language updating does not work for the toolbar UI.

> This is a serious issue that needs to be sorted out, as the underlying code seems to be logically incorrect. See keymanweb.line 2475ff and kmtoolbar.js line 864ff. All UIs must be checked if any change is made.

**Comment by jahorton** [comment]
I can confirm that this is still an issue as of KMW 10.0 alpha.

**Comment by jahorton** [comment]
It appears some initial work was done toward this within the toolbar code, with it expecting a 'indirect' parameter as part of the `changeKeyboard` event that was never implemented.
