### ISSUE TITLE
KMW can select the wrong keyboard at page load depending on the load order

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#272]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Thursday Nov 6, 2014 at 21:35 GMT_
_Originally opened as KD-200_

----

**Comment by jahorton** [comment]
The closest behavior I can replicate at this time is that KMW cannot initially load a keyboard that is obtained via Cloud API, as it must wait for the keyboard's stub to be retrieved.

**Comment by jahorton** [comment]
That being stated, the prior observation is likely duplicate behavior of #243.

Any other behavior I can imagine at this point was fixed with #343.
