### ISSUE TITLE
[linux] km-config to add keyboards to ibus

### ISSUE THREAD

**Issue by mhosken** [keymanapp/keyman#2728]
Currently in Linux one has to install a keyboard using km-config (a good thing) and then also add it to the ibus list using the gnome settings languages setting. This is confusing (since it isn't documented). It would be much better if adding or removing a keyboard from km-config would also do the same to the ibus keyboard list.

**Comment by darcywong00** [comment]
It is documented here
https://help.keyman.com/products/linux/13.0/guide/installing-keyboard

But yeah, that isn't obvious for users to find.

It will take some development to have km-config handle updating the ibus keyboard list.
