### ISSUE TITLE
[Developer] Editor font does not affect Debugger or Test Keyboard panels

### ISSUE THREAD

**Issue by sewhite** [keymanapp/keyman#2729]
**Describe the bug**
Setting a font for "Debugger, Editor Characters" does not affect the Debugger or the Test keyboard panel. 
**To Reproduce**
Go to Keyboard > FOnts
Select a font for Debugger, Editor characters
**Expected behavior**
Font choice to take effect for Debugger, Test keyboard. 

The font for these can be selected by right clicking, but it would be nice if the font section of the Development environment also let you select the font.

**Screenshots**

---

(Delete the irrelevant sections)

**Keyman Desktop, Keyman for macOS, Keyman for Linux:**
 - OS: [e.g. Windows 7, Windows 10 1803, macOS Mojave, Ubuntu 18.04]
 - Keyman version: [e.g. 10.0.1206.0]
 - Target Application: [e.g. Firefox 55]
  
**iPhone/iPad/Android:**
 - Device: [e.g. iPhone 6]
 - OS: [e.g. iOS 8.1]
 - Keyman version [e.g. 10.0.111]
 - Target application: [e.g. Notes, Keyman]

**KeymanWeb:**
 - OS: [e.g. Windows 7, Windows 10 1803, macOS Mojave, Ubuntu 18.04, Android 8.1]
 - Browser: [e.g. Chrome, Firefox]
 - KeymanWeb Version: [e.g. 10.0.201]
 - URL: [e.g. https://example.com/web_keyboard/]
 
**Keyman Developer:**
 - OS: [e.g. Windows 7, Windows 10 1803]
 - Keyman Developer version: [e.g. 10.0.1206.0]
 
---
 
**Keyboard**
 - Keyboard name: [e.g. khmer_angkor]
 - Keyboard version: [e.g. 1.0.1]
 - Language name: [e.g. Khmer]

**Additional context**

**Comment by mcdurdin** [comment]
Fixed by #3829.
