### ISSUE TITLE
Dynamic addition and removal of .kmw-disabled class fails to update KMW correctly

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#273]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Tuesday Nov 8, 2013 at 23:01 GMT_
_Originally opened as KD-193_

----

After dynamically adding the kmw-disabled class to an element, you will see an error when you focus the element, such as:
```
Uncaught InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable. ?domain=localhost&id=544&page=/test.htm:3179
```
in Chrome, or `NS_ERROR_FAILURE` in Firefox.

Furthermore, if .kmw-disabled is set in the page source, KMW will never attach to the control even if the class is subsequently programatically removed.

c.f. case x53728

JD adds:
> This behaviour is currently by design - addition and removal of KMW input elements is not currently supported and will require a fairly significant design change to manage, since for touch devices a lot of initialization is done when the page is first loaded.
A proposed change that uses a single input element that is moved to each mapped input element and reformatted as needed would greatly simplify management of dynamic element addition/removal, and needs to be explored.

**Comment by jahorton** [comment]
This issue will be fixed as part of the 10.0 release - it has already been addressed with #114.
