### ISSUE TITLE
ZWNJ image to put on a key

### ISSUE THREAD

**Issue by rmlockwood** [keymanapp/keyman#2738]
We need a ZWNJ to show to people on a key. It doesn't seem to be in unicode. But there is an ISO image shown here: https://en.wikipedia.org/wiki/Zero-width_non-joiner. You can see in the attached images what iOS and an Android keyboard does.
<img width="367" alt="Draft" src="https://user-images.githubusercontent.com/7088137/75338889-ca8c9580-588f-11ea-86b5-d6e7137afeb9.png">
![Persian Gboard Layout](https://user-images.githubusercontent.com/7088137/75338904-ceb8b300-588f-11ea-80bd-528f366e94b7.png)

**Comment by mcdurdin** [comment]
Thank you for the suggestion. We are planning on doing some work on the special key font included in KeymanWeb relating to #2713 (which you reported!) so this would fit in well with that.

**Comment by darcywong00** [comment]
The iOS and Android versions were added to KMW OSK in #3851
