### ISSUE TITLE
IE9 OSK scaling wrong

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#274]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Saturday May 4, 2013 at 01:54 GMT_
_Originally opened as KD-179_

----

**Comment by jahorton** [comment]
I can confirm that the scaling is off with IE 9 - the keyboard's aspect ratio is off and it is overall smaller.  It is likely a low priority issue given that it is an aesthetic issue that does not appear to impact usability.
