### ISSUE TITLE
feat(developer): Icon tool font color not intuitive

### ISSUE THREAD

**Issue by rmlockwood** [keymanapp/keyman#2748]
I was really struggling to get a colored font letter. I expected the letter to come out in the foreground color that I selected, but it always came out black. It took me a long time to figure out that I had to open the font properties dialog and then select the color of the text. Can we change it that the text will be in whatever foreground color is chosen?

**Comment by mcdurdin** [comment]
Thank you for the suggestion -- we'll aim to work on icon editor enhancements in an upcoming release.
