### ISSUE TITLE
feat(developer): Icon editor could use a clear all button

### ISSUE THREAD

**Issue by rmlockwood** [keymanapp/keyman#2749]
I've struggled with the icon editor. Even to create a simple letter on solid background is hard work. On of the issues is that it's hard to get a clean slate. Because the default text that is there is anti-aliased, there's lots of different colored pixels. So the paint bucket tool doesn't help much. One has to resort to using the pencil to change each pixel. Later I learned I could use the filled in square, but it's not obvious. 
If there was a clear all button that would be very helpful.

**Comment by mcdurdin** [comment]
Thank you for the suggestion -- we'll aim to work on icon editor enhancements in an upcoming release.

**Comment by mcdurdin** [comment]
> If there was a clear all button that would be very helpful.

Edit/Clear Selection does this. 15.0 will add a "Clear All" button also.
