### ISSUE TITLE
feat(developer): Can't find help on icon tool

### ISSUE THREAD

**Issue by rmlockwood** [keymanapp/keyman#2750]
when I search for 'icon tool' or 'icon tab' I can't find any results that will tell me how to use the Icon tool. Also, using the More help in the yellow help area of the developer tool takes me to the top of the page and I have no idea where Icon help is. I expected it to take my right to the applicable section that is way down the page.

**Comment by mcdurdin** [comment]
Thank you for the suggestion -- we'll aim to work on icon editor enhancements in an upcoming release.
