### ISSUE TITLE
bug(developer): Predictive model fails to generate the right path for a TSV file.

### ISSUE THREAD

**Issue by sewhite** [keymanapp/keyman#2752]
**Describe the bug**

**To Reproduce**
1. Attach TSV file one folder up from the default folder
2. Compile
Error caused by bad path.

![image](https://user-images.githubusercontent.com/16904461/75454880-257fc480-5944-11ea-86c1-48d865588f81.png)

**Expected behavior**

**Screenshots**

---

(Delete the irrelevant sections)

**Keyman Desktop, Keyman for macOS, Keyman for Linux:**
 - OS: [e.g. Windows 7, Windows 10 1803, macOS Mojave, Ubuntu 18.04]
 - Keyman version: [e.g. 10.0.1206.0]
 - Target Application: [e.g. Firefox 55]
  
**iPhone/iPad/Android:**
 - Device: [e.g. iPhone 6]
 - OS: [e.g. iOS 8.1]
 - Keyman version [e.g. 10.0.111]
 - Target application: [e.g. Notes, Keyman]

**KeymanWeb:**
 - OS: [e.g. Windows 7, Windows 10 1803, macOS Mojave, Ubuntu 18.04, Android 8.1]
 - Browser: [e.g. Chrome, Firefox]
 - KeymanWeb Version: [e.g. 10.0.201]
 - URL: [e.g. https://example.com/web_keyboard/]
 
**Keyman Developer:**
 - OS: [e.g. Windows 7, Windows 10 1803]
 - Keyman Developer version: [e.g. 10.0.1206.0]
 
---
 
**Keyboard**
 - Keyboard name: [e.g. khmer_angkor]
 - Keyboard version: [e.g. 1.0.1]
 - Language name: [e.g. Khmer]

**Additional context**

**Comment by mcdurdin** [comment]
Thank you for reporting this. We'll investigate shortly.

**Comment by mcdurdin** [comment]
Fixed in #4407. (A little later than I would have hoped...)
