### ISSUE TITLE
Developer: fails to compile for mobile when "return" statement in group for desktop only

### ISSUE THREAD

**Issue by sewhite** [keymanapp/keyman#2754]
Attempting to work out how to combine code for touch and code for desktop into the KMN file, using groups to apply some rules to desktop and other rules to touch.

This sample file fails to compile for mobile because of the keyword "return" near the bottom, but that is in the group for desktop so it shoudn't complain. 

(It may well be that "return" has no function in this example, this is a condensed version of a much longer file. )

c sample generated from template at 2020-02-27 11:25:37
c with name "Sample"
store(&VERSION) '10.0'
store(&NAME) 'Sample'
store(&COPYRIGHT) '©'
store(&KEYBOARDVERSION) '1.0'
store(&TARGETS) 'any'
store(&VISUALKEYBOARD) 'sample.kvks'
store(&LAYOUTFILE) 'sample.keyman-touch-layout'

begin Unicode > use(platcheck)

group(platcheck)
platform('desktop') > use(main)
platform('touch')  > use(touch)

group(main) using keys
+ 'q' > U+0257

+ "<" > U+2039  
+ ">" > U+203A   

U+2039 +"<" > U+00AB return
 

group(touch) using keys
+[T_hb] > U+0253

**Comment by mcdurdin** [comment]
Thank you for helping to improve Keyman!

The compiler does not do code path analysis so we have to be a little more direct in how we exclude code from the mobile compiler.

You can avoid this issue with the following:

```
$keymanonly: U+2039 +"<" > U+00AB return
```

I think the plan is to eventually add support for `return` so I won't suggest adding code path analysis into the compiler...

See https://help.keyman.com/developer/language/guide/compile-targets for further details.
