### ISSUE TITLE
[Developer] Touch Layout - padding on the second row

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#2755]
**Describe the bug**
When creating a keyboard project afresh by including touch support, the touch layout created by default has an issue with the left padding of the left most key on the second row which has a value of 70 did not take effect in the Chrome simulator.

Chrome simulator - iPad
![image](https://user-images.githubusercontent.com/28331388/75506517-d3f13b80-5a10-11ea-9f2d-0726c1d220d7.png)

Chrome simulator - Nexus 7
![image](https://user-images.githubusercontent.com/28331388/75506726-7d383180-5a11-11ea-81b7-aaf4e411bf26.png)

Chrome simulator - responsive
![image](https://user-images.githubusercontent.com/28331388/75506588-08fd8e00-5a11-11ea-8916-25d4ae9525c9.png)

In the Touch Layout design view, the padding looks good as expected:
![image](https://user-images.githubusercontent.com/28331388/75506907-02bbe180-5a12-11ea-922a-4142ca81b2fb.png)

**To Reproduce**
Use this project to see the error.
[test1.zip](https://github.com/keymanapp/keyman/files/4265102/test1.zip)

**Expected behavior**
The padding in the simulator should look like that in the Touch Layout in the design view.

---

**Keyman Developer:**
 - OS: Windows 10 Pro 1909
 - Keyman Developer version: 13.0.101
 

**Additional context**
This issue may be related to: https://github.com/keymanapp/keyman/issues/1831

**Comment by mcdurdin** [comment]
I believe this is working in 14.0.214-alpha. Can you verify?

**Comment by MakaraSok** [comment]
Confirmed. It has been fixed. 👍
