### ISSUE TITLE
[web] KeymanWeb (native) longpress popups do not adhere to selected modifier when firing rules

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#2756]
**Describe the bug**
KeymanWeb keyboards can have the wrong modifier selected for non-default layers.

**To Reproduce**
1. With the attached keyboard, run in keymanweb, in touch mode.
2. Long press on Shift layer C and select C with hacek.
3. No output should be expected -- this should match on `+ [SHIFT T_S_hacek_CAP] > 'С̌'` but is wrongly matching on `+ [T_S_hacek_CAP] > 'С̌'`.
4. It looks like KeymanWeb is ignoring the modifier for popups. Note that the apps get this right.

---

**KeymanWeb:**
 - OS: Windows,iOS,Android
 - Browser: any
 - KeymanWeb Version: 13.0.100
  
---

**Comment by jahorton** [comment]
Interesting... so we're talking about modifiers being applied to user-defined virtual keys, right?  I don't think KeymanWeb expects a user-defined key to be used in multiple locations, let alone across multiple layers with implied modifiers.  Modifiers were always intended for use with physical keys, right?

That said, I think there is something we can do, but we may want to discuss it first.

**Comment by mcdurdin** [comment]
> I don't think KeymanWeb expects a user-defined key to be used in multiple locations, let alone across multiple layers with implied modifiers. 

No, originally user-defined key identifiers (and any key identifiers, actually) could be used in multiple locations without trouble. I appreciate that fat finger algorithms mean this is no longer true -- for the same modifier.

> Modifiers were always intended for use with physical keys, right?

Modifiers can be applied to any key type: `K_`, `T_` or `U_`. This is not really weird for `T_` but is a bit weird for `U_` :)
