### ISSUE TITLE
bug(ios): Keyman (and possibly Developer) cache files leading to difficulty repeating test installs

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#2757]
**Describe the bug**
When installing a package from a developer web host, recompiling the package and reinstalling it should be sufficient to retrieve updates. However, the keyboard must be installed, and Keyman must be forcibly quit, before reinstalling the keyboard, in order for the updates to actually surface.

---

**iPhone/iPad/Android:**
 - Device: iPhone 7
 - OS: iOS 12
 - Keyman version 13.0.100

**Comment by jahorton** [comment]
With the recent changes to iOS package installation, I expect this to have been automatically resolved.  Of course, we should still confirm this before closing the issue.

**Comment by jahorton** [comment]
Likely related:  https://community.software.sil.org/t/ipad-needs-to-delete-keyman-in-order-to-install-a-new-version-of-keyboard/4327

> Hi,
>
> After compiling a new .kmp file, I deleted the old keyboard version on iPad and install the new version. But this newly installed keyboard is the same as the old one that I just deleted.
If I delete the Keyman app and reinstall it from the app store, and then install the new .kmp file, then the new version of the keyboard is installed.
>
> I still name the new .kmp file as version 1.0. I don’t know if this could be the issue. But my android phone does not have any issue. It will download the new .kmp file and install the new keyboard.

**Comment by jahorton** [comment]
I've gone ahead and made a custom test for this - I (locally) rewrote two pre-existing packages & keyboards to use the same name, package number, and keyboard version:

- `sil_euro_latin`
- `nrc_crk_cans`

New keyboard ID:  `test_keyboard`
New package ID: `test_package`

Both use the same language tag (`en`), just to be sure.  (The resources were chosen to highlight when a repro is successful, as the layouts are drastically different and impossible to confuse with each other.)

If I take care to ensure no automatic renaming occurs behind the scenes, this does reproduce exactly.  It gets tricky though, as various ways of importing .kmp files for testing will result in automatic `-1`, `-2`, etc renaming by iOS / Simulator / whatever.

If I slip up and let automatic renaming occur, merely swapping in and out of the keyboard is sufficient for a refresh; force-closing the app is not required.  It is still required if system-level automatic renaming is prevented.
