### ISSUE TITLE
IE9 doesn't accept .eot fonts from different domain - need to use .woff files instead

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#276]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Friday Jun 28, 2013 at 12:02 GMT_
_Originally opened as KD-175_

----

**Comment by jahorton** [comment]
Current versions of KMW prioritize .woff fonts above .eot fonts for this reason.  I'm considering this issue to have been resolved by other work since its original post.
