### ISSUE TITLE
feat(developer): Use Folders instead of Projects

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#2761]
**Is your feature request related to a problem? Please describe.**

There is very little unique content stored in a .kpj file. We encourage a directory structure already. Why not formalize this and move away from projects and instead open a 'folder'. Then populate the 'project' view with the contents of the folder.

Proposed by @MattGyverLee:
> The package (.pkg) solves a real issue of cherry-picking files/keyboards for the release. The Keyman (.kmn) file connects all the keyboard bits (OSK, Touch, Icon) to the keyboard.
>
> What does the .prj file really do for us other than duplicate data from other sources and be out-of-date when you make changes with Developer closed? It seems like we could just open the folder, let it auto-populate folder contents on open, and the contents of the .prj file could be reduced to a “.env” file. 
>
> Is there a use-case for people keeping data (keyboards) from different root directories in a project? I can, of course, see a use case for different roots in a package.

Commentary by Marc:

This is a good suggestion. The .kpj.user currently maintains state -- but it can always be thrown away and is easily transitioned to a folder concept. The .kpj served more of a purpose in the past. We've really come full-circle on how the projects interact with keyboards and packages. This seems like it would be a good future feature.

I'm not sure how we'd transition from .kpj to .env (or whatever it is called). We can't assume that existing files are structured by folder. Perhaps it could be a test when loading the project and if the project meets certain structural requirements offer to upgrade it (and offer reasons why not if it can't be upgraded).

Considerations:
* Project Options remain important: these would need to be stored in a .env?
* build Folder can be a bit confusing -- needs to be cleanly ignored in the project view (shaded down similar to .gitignored files in VS Code, perhaps).
* multi-keyboard packages (not super recommended anyway) in the existing repository reference files from outside the folder. These are the biggest use case for projects.
* This would mean two sets of 'project' style code to maintain in Developer. Some re-abstraction would be necessary to make this maintainable.

**Comment by mcdurdin** [comment]
More commentary on the issue:

Marc, I spent half an hour yesterday helping someone find the keyboard they were working on.
The *.prj was on google drive, but it was linked to a .kmn in My documents and now showing a default touch layout. Once I moved the KMN, osk and touch to the folder, I had to rename the files to match and "remove" the OSK and Touch from the kmn config and re-add them before it found and showed them. This would be very scary if i didn't know that "remove" doesn't delete.

Also, opening a keyboard while a project is open always adds it to the project, and i often find myself removing spurious keyboards from my .prj  that I only opened for comparison.  Is it possible to move to a more folder-based management system where you select a project folder and keyman finds and displays the bits inside, like Visual Studio Code. I would love to see a folder view in Developer.

**Comment by mcdurdin** [comment]
Further commentary -- this helps resolve the whole Project menu issue which also needs cleanup.

Marc wrote:
> Sounds like we need to refactor the Project menu. It's become much more important in recent versions of Keyman Developer and is not really optional any more.  (e.g. from Ken Keyes)

**Comment by MattGyverLee** [comment]
> I'm not sure how we'd transition from .kpj to .env (or whatever it is called). 

I'm not hooked on or necessarily recommending ".env". I just mentioned .env (environment) files because I've been using them in Javascript to hold build and runtime environment variables. Build configuration strings seem to be most of what is left over in the .prj file once the structural information is ignored.

Also adding the image from the Document:
![image](https://user-images.githubusercontent.com/986339/75633540-dec0f180-5c05-11ea-968e-9978c090a461.png)

**Comment by mcdurdin** [comment]
Design Documents:
* 16.0 planning: https://docs.google.com/document/d/1lKIt1VzwXxmW3P5h7jeo2egPMG559uuStlGTuo0c01E/edit
* 17.0 design meeting: https://docs.google.com/document/d/1H7BOFokQfEdm-NvKKXh8VhAvzsYePAk2ZYMkXYeaFpY/edit

**Comment by mcdurdin** [comment]
We want to completely eliminate the "untitled project" scenario -- running Keyman Developer in a non-project mode.

Scenarios for opening files and projects:

1. Asked to open v1.0 .kpj file. Load this file. Files may be anywhere on the filesystem.
   * Ask to upgrade to v2.0 project. If files are all under the folder it is in, no problem. Otherwise, need to show a message about inability to upgrade.
2. Asked to open v2.0 .kpj file. Load this file. All files will be under the folder it is in, guaranteed.
3. Asked to open a folder. If .kpj file exists in folder, load this file. See 1,2 above. Otherwise:
   * If folder contains a source/ folder, then treat this as a v2.0 folder that matches our layout expectations
   * If folder does not contain a source/ folder, then prompt user to create a new v2.0 project in the folder, with different SOURCEPATH=$PROJECTPATH (keep BUILDPATH=$PROJECTPATH/build?)
5. Asked to open an arbitrary source file, within the folder structure of the currently open project. then just open the file.
6. Asked to open an arbitrary source file, while no project is open. Use the current window and go to (3) above, and subsequently open the file. This is basically the process for a file opened from Windows Explorer also.
7. Asked to open an arbitrary source file, from another folder. Open a new window, go to (3) above, and subsequently open the file.

This means we still need to support v1.0 projects as we may not be able to automatically convert them to v2.0. But we no longer need to support the 'untitled project' pattern, which should make the IDE code more robust.

**Comment by mcdurdin** [comment]
Current challenges with folder-based projects

1. Opening a top-level folder with bajillions of files
2. Opening a .kpj file which has been dumped into a folder where it really doesn't belong (see #1)
3. Attempting to open a .kmn file which is in a high level folder with no .kpj associated

Current design has us enumerating all files in folders and subfolders at project load time (actually, multiple times, e.g. we do it again at render). This does not scale. 

* This is also a problem in kmc.

* How do we open arbitrary/keyboard.kmn files?
* What about arbitrary/othername.kpj projects?

**Proposal:** we enumerate files only in folder/ and $SOURCEPATH (which defaults to folder/source/ if no .kpj is present, or folder/ if no source/ folder is present), while we use the existing project window. The tree-based folder view will allow other patterns in future. We do not enumerate other subfolders, not even subfolders of $SOURCEPATH.

Given an arbitrary/path/to/file.kmn:

1. Look for arbitrary/path/to/to.kpj. If present, open the project
   * If file.kmn is in the project, open it, end. (note: file.kmn will always be in to.kpj for v2.0 projects)
   * Ask the user if they want to add file.kmn to the project. If they don't add file.kmn to the project, then cancel the file open, end.
   * Otherwise, open it. end.
2. Look for arbitrary/path/path.kpj. If present, open the project.
   * If file.kmn is in the project, open it, end. (note: file.kmn will be in path.kpj if $SOURCEPATH=to for v2.0 projects)
   * If v1.0 project
     * ask if they want to add file.kmn to the project. If they don't add file.kmn to the project, then cancel the file open, end.
     * Otherwise, add to project, open file, end.
   * (For v2.0 project) Close the project, go to step 3.
3. Open arbitrary/path/to as a v2.0 project folder
   * open file.kmn, because it will be in the project by default.

---------------

## Project Filenames

Subnote about project filenames: currently, these are tied to the parent folder filename. This is not ideal, because:
1. it allows for multiple .kpj files in one folder
2. it is easy to desync if either folder or .kpj are renamed
3. makes logic more complicated around testing for .kpj presence

**Proposal:** What if project filenames were fixed? We could go with `.kpj` as a fixed filename for v2.0 projects?

Then, we have a different process, which is less ambiguous, even if it is longer! Given an arbitrary/path/to/file.kmn:

1. Look for arbitrary/path/to/.kpj. If present, then:
   * This is a v2.0 project
   * open the project
   * open file.kmn
   * END.
2. Look for arbitrary/path/.kpj. If present, and its $SOURCEPATH==to/ then:
   * This is a v2.0 project
   * open the project
   * open file.kmn
   * END.
3. Look for arbitrary/path/to/to.kpj. If present, open the project
   * If file.kmn is in the project, open it, END.
   * Ask the user if they want to add file.kmn to the project:
     * Yes: add it and open it.
     * No: cancel operation.
   * END.
4. Look for arbitrary/path/path.kpj. If present, open the project.
   * If file.kmn is in the project, open it, END. 
   * Ask the user if they want to add file.kmn to the project:
     * Yes: add it and open it.
     * No: cancel operation.
   * END.
5. If to/ is called 'source', then we'll treat arbitrary/path/ as a v2.0 folder project:
   * open the project
   * open file.kmn
   * END.
6. We'll treat arbitrary/path/to/ as a v2.0 folder project:
   * open the project
   * open file.kmn
   * END.
