### ISSUE TITLE
feat(android/app): Improve UX for landscape orientation

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#2768]
From @bennylin on the [Community Site](https://community.software.sil.org/t/can-we-make-the-panorama-mode-better/3085)

> This is a screenshot from my phone, Nokia 2.2 (Android One). Maybe it’s larger in tablet, but in my phone it’s not possible to see the screen due to the keyboard taking over 70% of it.
image
> ![alt text](https://community.software.sil.org/uploads/default/optimized/2X/7/77f06f3676b0ae3e5af0ff2eaa1d179da5d17d0c_2_690x326.png "Keyman in lanscape")
>
>Can we improve the panorama-mode experience?
>
> *Make the button smaller? (shorter?)
>* Auto-disable the prediction/correction in panorama-mode
>* Other ideas?
>
> In the default keyboard that I have, the tiny text field (e.g. in WhatsApp) is transformed into one 
> big text-field.
> ![alt text](https://community.software.sil.org/uploads/default/optimized/2X/b/b941ca1cd4dfa2e13b50e2d865b78be3e05cd1a7_2_690x326.jpeg "WhatsApp in landscape")

**Comment by jahorton** [comment]
Referencing the iOS work on #2487 and #2505 may prove somewhat useful, though Android would have a much larger set of devices if an identical approach were taken.

That said, sampling scaling data for Android's default keyboard (like with #2505's tool for iOS) should give us numbers that could give useful insight to create general scaling rules.  Referencing its [readme.md](https://github.com/keymanapp/keyman/blob/master/ios/tools/KeyboardCalibrator/readme.md) may help with designing a process for data collection should we wish to take this route, though it's written more from the user perspective than the code's perspective.

**Comment by rc-swag** [comment]
Closing this issue as it addressed by adjustable height PR#5906

**Comment by mcdurdin** [comment]
I think we have to say mitigated, not completely fixed by #5906. Suggest hiding the top banner when in landscape and/or not enough space in text area.

**Comment by darcywong00** [comment]
Given this issue is mitigated, I'd like to defer control logic of the suggestion banner when in Landscape orientation to Future release.

**Comment by mcdurdin** [comment]
Sounds good to me.

**Comment by darcywong00** [comment]
> I think we have to say mitigated, not completely fixed by #5606. Suggest hiding the top banner when in landscape and/or not enough space in text area.

As of Keyman 17, the keyboard will always display a banner (either themed image or suggestions) for gesture keys on the top row.
This can be closed
