### ISSUE TITLE
Memory use changes needed

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#277]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Friday Jul 25, 2014 at 02:37 GMT_
_Originally opened as KD-176_

----

1. OSK layers should not be created if not needed for a particular keyboard.
2. Keyboards should be unloaded and memory freed when a new keyboard is loaded.
3. Why is explicit styling included in key specifications? Should not need anything except dimensional data.

**Comment by jahorton** [comment]
At this time, we have discontinued the old WordPress plugin.

**Comment by jahorton** [comment]
Did bookkeeping on the wrong issue for a moment there.  >_<

**Comment by jahorton** [comment]
1.  At present, on desktop devices we construct a layer for all potential combinations of modifiers for the keyboard's chirality preference.  It may be possible to create a general 'blank' layer for layers without valid keystrokes, but then we'd have to worry about providing proper visual feedback.  (We already discard unused layers for mobile/touch-based devices.)

2. The references maintaining each keyboard's OSK are discarded automatically once no longer the active keyboard, allowing Javascript to perform GC on the old elements.  We _could_ discard the keyboard object outright, but that would necessitate reloading the keyboard should it be desired again - possibly resulting in extra cloud calls and data usage.

    - Do we want this?

3.  If I understand the question correctly, the suggestion is to automatically detect whenever a key should receive special styling?  If all keyboards maintained the core default layouts as used within kmwlayout.js, this might be possible, but some keyboards (like EuroLatin2) create specialized modifier keys, and those need to be denoted somehow; dimensional data is not enough to detect when a key is meant for core text output vs 'modifier' usage, as text keys can have next-layer properties.
