### ISSUE TITLE
Windows Defender sees Persistence.BP!ml as  a security threat in 13.0.101.0

### ISSUE THREAD

**Issue by dyacob** [keymanapp/keyman#2772]
**Describe the bug**

A security warning appeared after the update to the latest version of Keyman Desktop.  The update required a Windows restart and after logging in the warning appeared from Windows Defender.

Behavior:Win32/Persistence.BP!ml

**To Reproduce**

Accept and apply the automatic update Keyman 13 to 13.0.101.0

**Expected behavior**

No security warnings.

**Screenshots**

![KeymanSecurityThreat](https://user-images.githubusercontent.com/8098333/75708730-5f780000-5c8f-11ea-89c1-94bd2ce2a366.png)

---

**Keyman Desktop, Keyman for macOS, Keyman for Linux:**
 - OS: Windows 10 Pro 10.0.18362 Build 18362
 - Keyman version: 13.0.101.0

**Comment by mcdurdin** [comment]
Believe this has been addressed for Windows Defender. It was a false positive.
