### ISSUE TITLE
[web] keyman.BuildVisualKeyboard in 13.0 not back compatible with 10.0

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#2784]
**Describe the bug**
`keyman.BuildVisualKeyboard` is not backwardly compatible with Keyman 10.0. You can pass the keyboard id as a parameter to this function, but Keyman 13 expects the keyboard to be selected before this anyway (and sadly, `setActiveKeyboard` is also not fully backwardly compatible).

Even after calling `setActiveKeyboard`, the keyboards are visually broken:

![image](https://user-images.githubusercontent.com/4498365/76121168-2e108300-6047-11ea-89b2-d20a97001a8e.png)

**To Reproduce**
1. On help.keyman.com, change the version of Keyman in head.php from 10.0.103 to 13.0.101.
2. Load any keyboard help page (e.g. I am testing with http://help.keyman.com.local/keyboard/newa_traditional/1.0/newa_traditional)
3. The `BuildVisualKeyboard` function (in cdn/dev/js/kbd-docs.js, around line 123) returns `null` instead of the expected element ready to append.

There is a secondary issue: the font is not loading for newa_traditional. I am not sure if this is a systemic issue or specific to this keyboard. It may be because of the way the keyboard is being loaded.

The way that help.keyman.com uses KeymanWeb is pretty out of date so refactoring of the help site may be necessary. It does bother me a little that the KMW API has changed so significantly and we don't really have good upgrade documentation between versions. We can deal with this internally but it really sucks for external developers integrating KMW. Something for us to be aware of for future versions (can we add anything for existing developers?)

---

**KeymanWeb:**
 - OS: Windows 10
 - Browser: Chrome
 - KeymanWeb Version: 13.0.101
 - URL: http://help.keyman.com.local/keyboard/newa_traditional/1.0/newa_traditional
 
---
 
**Keyboard**
 - Keyboard name: newa_traditional
 - Keyboard version: 1.0
 - Language name: Newar

**Comment by jahorton** [comment]
> (and sadly, setActiveKeyboard is also not fully backwardly compatible)

Could you detail this a bit more, please?
