### ISSUE TITLE
bug(web): bookmarklet does not work for full BCP 47 codes

### ISSUE THREAD

**Issue by sapradhan** [keymanapp/keyman#2785]
**Describe the bug**
Clicking on bookmarklet on bookmark toolbar while on https://keyman.com/bookmarklet/ produces error
![image](https://user-images.githubusercontent.com/5070211/76135404-d118cb00-604e-11ea-8882-7e06a0a9b1b6.png)
**To Reproduce**
1. Add language bookmarklet for a language as described in https://keyman.com/bookmarklet. I tried Newar(newa_traditional) and Kurumba, Kannada to see if this is specific to this particular language
2. click on a text box (I tried text box at bottom of https://keyman.com/bookmarklet)
3. Click on newly added bookmark 

4. While on gmail compose if you click on the bookmarklet, no error is seen but selected keyboard is not operational

**Expected behavior**
Keyman bookmarklet should work as described in https://keyman.com/bookmarklet

---

**KeymanWeb:**
 - OS: windows 10, Archlinux
 - Browser: Chrome 80, Firefox 73
 - KeymanWeb Version: [e.g. 10.0.201]
 - URL: https://keyman.com/bookmarklet,  gmail/compose 
---
 
**Keyboard**
 - Keyboard name: newa_traditional
 - Keyboard version: 1.1
 - Language name: Newa

**Comment by mcdurdin** [comment]
Thanks for reporting this. We'll be looking into this shortly.

**Comment by sapradhan** [comment]
hi, is this fix live ? The issue is still present.

**Comment by jahorton** [comment]
Interesting... looks like there's a new error happening behind the scenes.

KMW is properly accessing the API, but the API isn't returning all the needed metadata - no languages are being specified, so KMW isn't loading the specified keyboard correctly.

**Comment by darcywong00** [comment]
@irahopkinson reports having the same issue trying to use the bookmarklet from
https://keymanweb.com/#th,Keyboard_basic_kbdth0 

He's on Windows 10 and Chrome 87

**Comment by mcdurdin** [comment]
Apologies for the long delay on this. This issue should be resolved shortly with the pull request keymanapp/r.keymanweb.com#6.
