### ISSUE TITLE
If you try and load a second BML keyboard, the toggle menu doesn't rebuild and the second keyboard becomes active

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#279]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Friday Oct 4, 2013 at 21:10 GMT_
_Originally opened as KD-171_

----

**Comment by jahorton** [comment]
This seems to have been addressed since its original posting; I just tested this with our current Beta version of KMW and the bookmarklet, and the reported behavior is no longer the case.  The toggle menu does rebuild and does not automatically activate the second.
