### ISSUE TITLE
Some embedded fonts do not work with Android 4.2.2

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#280]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Friday Jan 3, 2014 at 00:51 GMT_
_Originally opened as KD-162_

----

The LaoWeb, MyanmarWeb, KhmerWeb, and other embedded fonts fail with Android 4.2 native browser. They were fine with Android 4.1.2, and with iOS 6 & 7. GeezWeb loads OK, so it isn't a general problem with displaying the embedded fonts.

Issue traced to a known bug in JellyBean (Issue 53479) affecting the use of complex script fonts where no font for that script has been installed natively. There does not seem to be any reliable workaround, but for KM Touch it may be possible to use a different rendering engine, if the effort is worth it.

It is likely that the issue has been resolved for Android 4.4 (KitKat) - the scripts display OK on the emulator (but not on the 4.2 emulator).

----
JD adds:

There was some confusion over font behaviour since the embedded fonts work with the non-native browsers, but Lao did not. The trouble there was with the font, not the rendering. Saysettha_web had a structural error (FontLab stores an invalid GDEF table) that caused it to be rejected by Chrome - and also by FontSquirrel's upload - and presumably by any code that uses the Google font library. Opening and resaving the font with FontForge corrects the error and then the font displays normally in Chrome on the Galaxy Tab using Android 4.2.2. However, this does not change the rendering issues, and the Native Browser on Android 4.2.2 still cannot display Lao or the several other embedded non-Latin scripts correctly.

At present the KMW embedded font code uses font-face font type order suggested by FontSquirrel (and others), referring to the woff format before ttf (if both are defined). It is not clear if this impacts download times, so, for example, if does browser that can only use the ttf format actually download the woff first or not? Probably not, but this may need further testing.

Note that Chrome on Windows desktop appears to use the first acceptable font (either woff or ttf), but Chrome on Android only uses ttf.

As are likely to have more flexibility and control in managing TTF format fonts, it is probably best if TTF format are loaded in preference.

**Comment by jahorton** [comment]
At this time, KMW gives first preference to ttf fonts.  It sounds as if this was addressed since the issue's original post.  Unfortunately, we no longer have the keyboards referenced by this issue; it is likely that they were replaced since then.

**Comment by jahorton** [comment]
We'll push full confirmation of the fix to a later point unless we receive other feedback indicating that it's a current issue.
