### ISSUE TITLE
[iOS] "display underlying text" set to false is displaying text

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#2813]
**Describe the bug**
with "display underlying text" set to false is displaying text

**Expected behavior**
Underlying text must be turned off.

This issue is observed in only 14.0.21 and 23 alpha. This is not seen in version 13 stable.

**iPhone/iPad/Android:**
 - Device: iPhone 11 pro max
 - OS: 13.3.1
 - Keyman version 14.0.21 and 23 alpha
 - Target application: Notes and Keyman

**Comment by jahorton** [comment]
I may need some more specifics / detail before I can proceed on this.  Here's what I see on an iPhone SE (iOS 13.3.1) with 14.0.21:

![No underlying text on the keycaps (khmer_angkor)](https://user-images.githubusercontent.com/25213402/76591048-b4cecf80-6521-11ea-9b82-82ea31a0e49f.png)

I see no underlying text on the keycaps for this example keyboard, and I see the `KDU` (display underlying) flag set to 0 (functionally, `false`) when I examine its compiled form.

Just in case, I updated to 14.0.24 - same thing.

What keyboard(s) are you seeing this with?

**Comment by MayuraVerma** [comment]
It was showing in 21 n 23 with KB shared offline with you. now with 24 it’s not showing the underlying text.

**Comment by jahorton** [comment]
Given how long it's been since the last report of the issue and that it notably disappeared for the user who reported it, we're going to consider this fixed and close the issue.
