### ISSUE TITLE
[iOS] [Android] [Windows] Update OEM build to use published versions of FV keyboard packages

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#2817]
Rather than linking into the source FV keyboard packages, it would be cleaner to use the existing published versions, which would reduce build time as well as complexity.

The primary concern is duplication of font resources. For the Windows version, there is a single package fv_all; is this useful for the other platforms as well?

**Comment by darcywong00** [comment]
keymanapp/keyboards#1152 added touch keyboards to fv_all, so the single fv_all.kmp should be usable by all the FV apps. 

It would be preferable to install a single package than having to extract many keyboard packages (100+?).

**Comment by darcywong00** [comment]
Windows updated in #3040
Android updated in #3045, by useing the `-download-keyboards` flag to get the latest fv_all.kmp for the build.

TODO for iOS in oem/firstvoices/common/build_keyboards.sh 
```bash
DO_JS_DOWNLOAD=false # Remove when iOS handles fv-all.kmp
```

**Comment by jahorton** [comment]
Is it safe to drop the "windows/" label from this now?
