### ISSUE TITLE
Bookmarklet is using old version of KeymanWeb

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#282]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Thursday Dec 4, 2014 at 19:30 GMT_
_Originally opened as KD-156_

----

This leads to errors such as :
14r.keymanweb.com/code/bml20.php?domain=www.google.com.au&langid=gde&keyboard…iles%22:[%22DejaVuSans.ttf%22,%22DejaVuSans.mobileconfig%22]}&page=%2F:197 Uncaught TypeError: Cannot read property 'style' of null

Mixed Content: The page at 'https://www.google.com.au/?gfe_rd=cr&ei=G3J_VI2kG8mF9AWo8ICgBQ' was loaded over HTTPS, but requested an insecure font 'http://r.keymanweb.com/20/keymanweb-osk.ttf'. This request has been blocked; the content must be served over HTTPS.
www.google.com.au/:1

Mixed Content: The page at 'https://www.google.com.au/?gfe_rd=cr&ei=G3J_VI2kG8mF9AWo8ICgBQ' was loaded over HTTPS, but requested an insecure font 'http://r.keymanweb.com/20/keymanweb-osk.woff'. This request has been blocked; the content must be served over HTTPS.

Some of these can be solved also by configuration changes

Also, the OSK is positioned slightly awkwardly on google.com and the toggle buttons are not aligned perfectly.

**Comment by jahorton** [comment]
Already addressed by https://github.com/keymanapp/keyman/pull/112 and a few PRs in our backend infrastructure.
