### ISSUE TITLE
[Developer] Issues with wordlist tabs

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#2826]
Some of the earlier lexical model projects included the wordlist as a link to edit
(e.g. nrc.en.mtnt.kpj)

Issue 1: Opening the wordlist from the project just shows a blank tab.

The wordlist opens fine from nrc.en.mtnt.model.ts, but
Issue 2: the wordlist contents are displayed in the "nrc.en.mtnt.model.ts" tab.

![tabs](https://user-images.githubusercontent.com/7358010/76610946-43584680-654c-11ea-8abb-e913b62ef3a0.png)

so the user has to close and re-open nrc.en.mtnt.model.ts to get back to the basic information.

### Configuration
Windows 10
Keyman Developer 14.0.24.0 alpha

**Comment by mcdurdin** [comment]
Issue 1: the appropriate resolution is to remove the wordlist from the project.

Issue 2: I'm not sure I understand this? Wordlists are listed in the tabs to the left of the view and you can switch between the Details and relevant wordlist tabs,

**Comment by darcywong00** [comment]
> Issue 2: Wordlists are listed in the tabs to the left of the view and you can switch between the Details and relevant wordlist tabs

Gotcha. I was expecting the wordlist to appear in the tab "mtnt.tsv".  

This can be closed with a TODO to remove the wordlists from the lexical model projects.
