### ISSUE TITLE
CKJ IMEs not fully compatible with KMW2

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#283]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Monday Nov 24, 2014 at 22:15 GMT_
_Originally opened as KD-152_

----

Must check and update IMEs for new references and/or function calls needed to work with KMW2

**Comment by jahorton** [comment]
The "Chinese, Mandarin" keyboard suffers from extremely frequent "Chinese keyboard failed to connect to database" errors.  The picker list occasionally shows, but ceases to work after one such error.

The Korean and Japanese keyboards with their picker lists seem to function flawlessly.

- [ ] Fix Chinese, Mandarin keyboard.
