### ISSUE TITLE
[iOS] Longpress causing duplicates

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#2832]
**Describe the bug**
This is the first of four issues noted with Keyman 13.0.104 on iOS.

The issue is most easily reproduced when the banner is switched off (which seems to happen by default when updating from an earlier version). When you longpress on a key, and slide up to a longpress sub key, if the position of the finger on the sub key overlaps the base key, then Keyman emits the base key's character followed by the sub key's character, rather than just the sub key.

In the video below, while you cannot see the position of my finger, the first time through I moved my finger only far enough onto the longpress menu to activate the sub key, with the result that both រ (base key) and ្រ (sub key) were emitted. The second time through, I moved my finger as far as possible up onto the longpress menu, and the correct (្រ) output was obtained.

![video-broken-longpress](https://user-images.githubusercontent.com/4498365/76807782-9cb8c200-6839-11ea-9218-96f3f6512e0b.gif)

**Expected behavior**
Only the sub key should be emitted.

**Screenshots**
![image](https://user-images.githubusercontent.com/4498365/76807385-5020b700-6838-11ea-9496-d66bc50e6c00.png)

---
 
**iPhone/iPad:**
 - Device: iPhone 7, iPhone 6
 - OS: iOS 12.4.1 (iPhone 7), iOS 12.4.5 (iPhone 6).
 - Keyman version 13.0.104 (iPhone 7), 13.0.103 (iPhone 6)
 - Target application: any (system keyboard, not tested on in-app)
 
---
 
**Keyboard**
 - Keyboard name: khmer_angkor 1.0.6 (iPhone 7), khmer10 1.2 (!!) (iPhone 6)
 - Language name: Khmer

**Comment by jahorton** [comment]
Was this noted with any subkey, or just the top row?

**Comment by mcdurdin** [comment]
> Was this noted with any subkey, or just the top row?

It's harder to repro on other rows, because the overlap is less, but I can get it to go wrong in the same way. Easiest to repro if the banner is switched off entirely.

**Comment by jahorton** [comment]
... reminder:  "switched off" isn't even a thing.

**Comment by mcdurdin** [comment]
> ... reminder: "switched off" isn't even a thing.

Okay, well here's a screenshot with it 'switched off' -- this is happening consistently on my phone:

![image](https://user-images.githubusercontent.com/4498365/76821761-fda8c000-6862-11ea-9ead-c4bc7d84cd46.png)

The setting 'Show Banner' seems to be losing state as well, because I switched it on, came back later and it was off again... not sure if that belongs separately.

**Comment by jahorton** [comment]
This issue is definitely exacerbated by #2833, but I can replicate the, uh, "edge-case" issue in stable-12.0.  (That is, hitting the edge of a popup key that aligns with the original base key.)

It's nothing new to the iOS app; we just never noticed it until it was made worse by #2833.
