### ISSUE TITLE
[iOS] Banner not displaying, or showing incorrectly

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#2834]
**Describe the bug**
The banner is not always displaying correctly in iOS for recent builds of Keyman.

**Screenshots**
iPhone 6, Keyman 13.0.103
![image](https://user-images.githubusercontent.com/4498365/76808192-06859b80-683b-11ea-9760-d86f2aecec7b.png)

iPhone 7, Keyman 13.0.104
![image](https://user-images.githubusercontent.com/4498365/76808173-fa99d980-683a-11ea-8209-9ab6b85ada40.png)

---

**iPhone/iPad:**
 - Device: iPhone 7, iPhone 6
 - OS: iOS 12.4.1 (iPhone 7), iOS 12.4.5 (iPhone 6).
 - Keyman version 13.0.104 (iPhone 7), 13.0.103 (iPhone 6)
 - Target application: any (system keyboard, not tested on in-app)

**Comment by jahorton** [comment]
Once #2840 is in place, the remaining part - the image at the top - can be resolved by noting the changes of https://github.com/keymanapp/keyman/pull/2629 - the iOS part of the CSS, in particular.

Those changes are ideal for the _suggestion banner only_ - it misaligns the image banner.  We'll need to add an extra CSS class to differentiate between the two modes.  Mr. CSS scrub here (myself) failed to realize that on the original implementation.
