### ISSUE TITLE
[iOS] Long press on globe icon does not activate keyboard menu

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#2835]
**Describe the bug**
On my iPhone 7 with Keyman 13.0.104, periodically long-press on the globe button has no effect. I have 11 keyboards installed today, so that means many touches to get to the keyboard I want 😢

**To Reproduce**
1. Go to the system keyboard
2. Longpress the globe icon
3. See nothing happen 😢

---

**iPhone/iPad:**
 - Device: iPhone 7
 - OS: iOS 12.4.1
 - Keyman version 13.0.104
 - Target application: any (system keyboard, not tested on in-app)

**Comment by jahorton** [comment]
Possibly related to #2817 - so we are seeing this behavior periodically on current devices.  Unfortunately, that repro isn't exactly consistent.

**Comment by jahorton** [comment]
Oops, wrong issue linked on that PR.

**Comment by jahorton** [comment]
It appears that #2968 has sufficiently addressed this.
