### ISSUE TITLE
[iOS] 'Keyman' Banner is showing in-app

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#2836]
**Describe the bug**
The "Keyman" banner is showing in-app, when it should only ever be on the system keyboard. The only time a banner area is shown in-app is when we are offering predictions.

**Screenshots**

![image](https://user-images.githubusercontent.com/4498365/76808349-9e838500-683b-11ea-82ca-ab609df0491a.png)

---

**iPhone/iPad:**
 - Device: iPhone 6
 - OS: iOS 12.4.5 (iPhone 6).
 - Keyman version 13.0.103 (iPhone 6)
 - Target application: Keyman in-app

**Comment by jahorton** [comment]
So, the issue is with the interpretation of "Always show banner"?  My understanding is that this is the exact implementation intended for that option.
