### ISSUE TITLE
Clicking the shift key on the OSK sometimes causes it to jump-resize

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#284]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Thursday Dec 4, 2014 at 19:31 GMT_
_Originally opened as KD-148_

----

**Comment by jahorton** [comment]
Unable to confirm/replicate, the issue is old, and there are no details on how to replicate this legacy issue.  If it occurs again, we're very much willing to revisit this, but it is likely already fixed.
