### ISSUE TITLE
Message at bottom emails and FB posts should be tweaked to include language code

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#287]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Saturday Nov 30, 2013 at 02:22 GMT_
_Originally opened as KD-123_

----

The message appended to emails and FB posts should be tweaked slightly to read, 
"Can't read this? Help at http://keyman.com/fonts?xxx"

where xxx is the language code for the currently selected keyboard.

A secondary issue is that users should be able to turn off this message via options somewhere... One day...

We can add this feature whenever we have the links working

**Comment by mcdurdin** [comment]
Unimportant.
