### ISSUE TITLE
feat(developer): Test normalization of lexical models at build

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#2880]
**Is your feature request related to a problem? Please describe.**
Lexical models should always be normalized -- either NFC or NFD. They should not normally contain a mix of normalization. Not addressing this tends to lead to repeated suggestions and broken weightings.

**Describe the solution you'd like**
The compiler should warn on mixed normalization. Even better if Keyman Developer could automatically resolve it, merging duplicate entries post-normalization and adjusting weights accordingly.

**Describe alternatives you've considered**
Doing it by hand ain't great.

**Product context**
 - OS: Windows

**Additional context**

**Comment by darcywong00** [comment]
> Doing it by hand ain't great

Below are @DavidLRowe 's notes on his manual process for keymanapp/lexical-models#80

> In the end, I was able to fix up the word list for the author using a few steps:
> * used online tool at https://dencode.com/string/unicode-normalization to convert wordlist.tsv to NFC (paste text in top box, click on "Unicode NFC" under "Encoded" and copy text to clipboard)
> * saved that new text, then opened it with LibreOffice Calc
> *used formulas in columns C and D to combine counts for duplicates
>     * column A: words, starting from cell A2 (that is, leave cell A1 blank)
>     * column B: counts, starting from cell B2 (with B1 blank)
>     * column C: Formula in cell C2, copied down to last word in column A: =IF(A2=A1,"",A2)
>     * column D: Formula in cell D2, copied down to last word in column A:  =IF(A2=A1,"",SUMIF(A$2:A$10000,"="&A2,B$2:B$10000))
> * copied columns C and D to new document, eliminated blank lines by sorting, and saved as new .tsv file
>
>I expect there are other ways to do this, but this is what occurred to me with the tools I had at hand.

**Comment by DavidLRowe** [comment]
FYI: Rather than use the website mentioned above, I now use the txtconv utility (part of TECkit package https://scripts.sil.org/TECkitDownloads) to change a file to NFC: txtconv -i infile.tsv -o outfile.tsv -nfc -nobom

**Comment by mcdurdin** [comment]
This probably won't make the cut for 14.0 but we will revisit in 15.0.

**Comment by darcywong00** [comment]
Normalization relates to #3306

**Comment by MattGyverLee** [comment]
I agree they should always be normalized one way or the other, but the user needs to be able to choose a composition to match the keyboard.  I've been having a conversation with @jahorton and @DavidLRowe today after I realized that the compiler didn't give me the option to keep my model text NFD to match the keyboard. Everything got forcefully NFC'd to my dismay.

**Comment by jahorton** [comment]
So, one fun wrinkle to consider:

Suppose the in-development lexical-model's language has two keyboards in the repository:
- `keyboard_nfc`
- `keyboard_nfd`

The implications are intended:  one keyboard is designed to emit NFC, while the other is designed to emit NFD.  Our intent for lexical models is that they should not be paired to specific keyboards; they should work with any keyboard for the language.  So... we probably need a way to determine the _keyboard's_ normalization pattern and have suggestion-text adhere to that.

That does raise concerns for languages and/or scripts that conventionally use mixed-normalization, though... we won't have knowledge of mixed-normalization patterns, so it'd be quite difficult to force suggestion text to adhere to them.

**Comment by darcywong00** [comment]
Also relates to #5809 for keyboards

**Comment by mcdurdin** [comment]
Note that per email discussion (my notes copied below), we don't need the model itself to declare an output normalization form; rather it should use the active keyboard's pref.

> Here are my thoughts.
>
> 1. Remember that NFC doesn't mean "all diacritics are combined in all circumstances" but essentially means where there exists valid combined forms, use those, then add the remaining diacritics as needed.
> 2. IMHO, NFC is the most appropriate default form for almost any language and situation, especially as vast majority of content online is NFC. Keyboards should deal with backspacing scenarios in the case that you want consistent backspacing behaviour that smooths over the normalization form peculiarities.
> 3. Vietnamese is a special case due to the Windows system Vietnamese keyboard not being able to emit fully composed characters (even though they exist), due to limitations in the Windows kernel. That's the only reason there is a bunch of messy, neither NFC nor NFD content out there in Vietnamese. Some may argue this is "linguistically appropriate" because the decomposed diacritics are tone marks (I think?) but it's a bad situation caused by tech stack limitations. For compat reasons, we may need to support this, but it should be a last resort for any other language.
> 4. Keyman _should_ be doing normalization of inputs and outputs automatically ([#3306](https://github.com/keymanapp/keyman/issues/3306)). For LDML keyboards, this will be available in the 17.0 release ([#9468](https://github.com/keymanapp/keyman/issues/9468)), and then we plan to fold that functionality back into future Keyman .kmn keyboard support as well per that issue. Keyboards that don't specify a normalization form will be "mixed" -- to preserve back compat. We'll add something like `store(&normalization) 'NFC'` and default to that for new keyboards.
> 5. Then, once we have (4) done, the model engine should inherit the normalization form of the associated keyboard -- so if the keyboard emits NFC, the model engine should normalize(nfc) its outputs. And the converse for NFD. The internals don't matter so much, but we use NFC throughout, so let's stick with that. Inputs to the model should be normalized to NFC (they probably already are?)

The lexical model compiler already does the normalization to NFC at build time, so I think we can declare this issue done. Remaining work is in referenced issues.

**Comment by mcdurdin** [comment]
> That does raise concerns for languages and/or scripts that conventionally use mixed-normalization, though... we won't have knowledge of mixed-normalization patterns, so it'd be quite difficult to force suggestion text to adhere to them.

This is almost impossible to solve consistently, and I don't think we should try. We should be aiming for NFC or NFD -- and not support mixed normalization outputs for our lexical models. The mixed normalization thing is only arising from one operating system's support for one particular language.

(missed this earlier)

**Comment by jahorton** [comment]
Point 5 raises a noteworthy point about predictive-text normalization; we don't actually normalize input text on a global level.  The _Trie-based wordlist model_ we offer does this internally, but there's no such aspect on a global level, and thus no such aspect for custom models or for any future alternative model types we may implement in the future.
