### ISSUE TITLE
KMInputViewController (KMTextView & KMTextField) sometimes deletes diacritics and letters at once

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#290]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Friday Jan 1, 2016 at 01:17 GMT_
_Originally opened as KD-83 and KD-60_

----
When deleting backward KMTextView & KMTextField delete all diacritics with the letter at once instead of deleting diacritics and letters separately.

When deleting backward close to the beginning of a text area, KMInputViewController sometimes deletes diacritics together with the letters instead of deleting them separately.

**Comment by tombogle** [comment]
This is an old issue. Probably not a real problem (anymore). It will be re-reported and can be re-opened if it is a real problem.
