### ISSUE TITLE
Position of Latin letter on OSK key

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#291]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Thursday Feb 27, 2014 at 23:56 GMT_
_Originally opened as KD-251_

----

The general layout of elements on each OSK key needs to be revisited. At present, the Latin at the top left and the popup key icon at the top right are absolute positioned within the key, which is a fixed position div. That works OK for most platforms, but for Android 4.1 the positioning is not correct, and sometimes those elements disappear altogether.

Although it seems to be OK for iOS and Android 4.2, It may be worth trying to use all fixed positioning for OSK elements, if possible, to see if that makes the element positioning reliable in all commonly used contexts.

**Comment by mcdurdin** [comment]
No longer relevant
