### ISSUE TITLE
Need easy way to test touch-screen behavior on desktop

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#292]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Tuesday Jul 25, 2014 at 02:39 GMT_
_Originally opened as KD-246_

----

It would be helpful to include an initialization member that overrides the automatic selection of device type. So setting `ui:tablet` or `ui:phone` would then emulate touch-device behaviour rather than the standard desktop.

**Comment by mcdurdin** [comment]
This was resolved with web debugger changes in #5723 and associated.
