### ISSUE TITLE
fix(common/core/web): Variable store interactions with predictive text

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#2924]
**Describe the bug**
Because of how variable stores are currently implemented in KMW keyboards, they are not currently compatible with predictive text.

**To Reproduce**
Using the `options_with_save` keyboard (023 from desktop-core unit tests) along with a predictive text model should yield unexpected behavior; fat-fingering will trigger store operations on unintended keys.

For example, typing '1' with predictive text on would likely trigger the behavior for '0', as fat-finger calculations are done after the true keystroke.  It would also automatically 'save' the store, also unintended.  The former is because the store is set directly within the keyboard, leaving KMW no way to prevent modification of the store for fat-finger cases.

**Expected behavior**
Any potential fat-finger rule evaluation should not alter the state of the keyboard.

**KeymanWeb:**
 - OS: any
 - Browser: any
 - KeymanWeb Version: 12.0 to current (14.0.41 or so)

**Additional context**
Fixing this will likely require Developer support; at minimum, we'll need one of the two following appraoches:

- a way to supply the keyboard with a flag that prevents variable store mutation
- a list of keyboard JS fields used to store values for variable stores
  - I'd suggest this approach; it requires the least breaking changes by far and would require minimal extra Developer support.  Web would need to do a bit of work, but the costs of the checks involved would be minimal.

That said, if predictive text ever _does_ need to interact with mutating system stores, things get a lot trickier and further design work will be needed.

**Comment by darcywong00** [comment]
Add a Community forum link with a sample keyboard
https://community.software.sil.org/t/lexical-models-break-variable-stores-at-least-for-mobile-keyboards/3415

**Comment by jahorton** [comment]
Note that KeymanWeb's keyboard rule processing currently produces `RuleBehavior` objects.  The definition for this type may be found at https://github.com/keymanapp/keyman/blob/master/common/core/web/keyboard-processor/src/text/ruleBehavior.ts.

For all other mutations triggered by keyboard rule within KMW, all changes are 'cached' within the `RuleBehavior` object produced by `processKeystroke` - they're only applied/persisted when the [`finalize`](https://github.com/keymanapp/keyman/blob/671509a80bd3fec402b5d81565dcafb45b522ab2/common/core/web/keyboard-processor/src/text/ruleBehavior.ts#L57) method is called.  While not strictly _necessary_, it'd be "ideal" if variable-store state could function similarly.

If taking the "a list of keyboard JS fields used to store values for variable stores" approach, I imagine this ideal could be met by taking a snapshot of those fields before the `startGroup` is run and comparing values after it completes, resetting them after storing any mutations as part of the `RuleBehavior` in some fashion.  They'd then be persisted (reapplied) by the `finalize()` method.
