### ISSUE TITLE
Add copy button if you detect the clipboard is not empty

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#293]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Thursday Nov 7, 2013 at 22:13 GMT_
_Originally opened as KD-121_

----

When copying text into Keyman from another app (for instance iMessage), currently the user needs to touch-hold in the text area to bring up the paste button.

Instead, if Keyman detects the clipboard is not empty, a 'paste text' button appears that the user can click to paste the text into the text area, it would make it clearer and simpler to use.

We will probably need a drop down menu to add copy/paste features as we have very limited space for extra navigation bar buttons. We need to discuss about it some time in future.

**Comment by mcdurdin** [comment]
This is really stale. There is a similar issue for Android in #7271, but relating to the banner for the system keyboard. This would be a good feature for iOS, but closing this particular issue as unimportant.
