### ISSUE TITLE
[Windows] Keyboard list in "Hot Key" vs "Keyman Icon"

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#2942]
**Describe the bug**
The keyboards listed in "Hot Key" tab and in the "Keyman Icon" on the task bar are not the same. On my machine, the Hot Key tab lists more keyboards than in the Keyman Icon (see the screenshot).
![image](https://user-images.githubusercontent.com/28331388/78323354-c264fb80-759b-11ea-93e7-0d04b5fe79e9.png)

"Hot Key" tab listed Korean and Japanese keyboards along with Korean - Microsoft IME and Japanese - Microsoft IME, but from the "Keyman Icon" only Korean - Microsoft IME and Japanese - Microsoft IME are shown. 

**To Reproduce**
1. Go to 'Hot Key' tab and scroll down to the Keyboard Layouts
2. Click on 'Keyman Icon' on the task bar to compare the two lists
3. See the different

**Expected behavior**
The keyboard layout list in the Hot Key tab should be identical with the list from the Keyman Icon?

---

(Delete the irrelevant sections)

**Keyman Desktop:**
 - OS: Windows 10 Pro 1909
 - Keyman version: 13.0.106
  
**Additional context**
- I also notice that once cannot set hotkey for Korean and Japan keyboards, and the likes.
- Here is the diagnostic report: https://drive.google.com/file/d/1IPTeFdX8Hwjn6jFPjEaFyLk5SORZ0myd/view?usp=sharing

**Comment by mcdurdin** [comment]
I think that with the changes recently applied in #3509 and related PRs, this should be a lot better. Are you able to re-test with a recent 14.0 alpha?

**Comment by MakaraSok** [comment]
There seem to be an issue with the keyboard list. The same keyboard is listed multiple times in different groups, i.e. Amharic got listed in once under English group, once under Khmer group, twice under Undetermined group, ...etc. The same for some other keyboards. There is a long list of keyboards, x times the actual number of keyboards in the keyboard list shown in the taskbar. 

Here is a screenshot:
![image](https://user-images.githubusercontent.com/28331388/95305722-9317aa00-08b0-11eb-99fb-7f78c2e3b9b5.png)
