### ISSUE TITLE
[Android] Use back button to minimize keyboard

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#2950]
Suggestion from the [community site](https://community.software.sil.org/t/minimize-keyboard-button-vs-back-button/3198)

@bennylin says:
> On the lower left corner, usually there’s a down arrow button, but on Keyman it behave as back button, whereas I think it should be minimize keyboard button (as in other keyboards).
>
>In some cases, the minimize keyboard is needed, for example in a form where the “OK” button is not clickable due to the keyboard, clicking the arrow would exit the form, and there’s no way to finish the form using Keyman keyboards.

**Comment by bennylin** [comment]
On the Keyman for Android app's help page, there's the "hide the keyboard" icon, which I couldn't find on the keyboards.

![image](https://user-images.githubusercontent.com/3002108/78695427-46b2d800-7928-11ea-8061-929c6af0fbce.png)
