### ISSUE TITLE
[LMLayer] Ensure that the default searchTermToKey function is consistent at build and runtime

### ISSUE THREAD

**Issue by eddieantonio** [keymanapp/keyman#2958]
**Is your feature request related to a problem? Please describe.**
Currently, there are TWO implementations of the "default" `searchTermToKey()` function in the LMLayer. There's one that's used when the Trie gets compiled, and one when the model is actually loaded within the LMLayer proper.

This has already lead to problems! (see #2954)

**Describe the solution you'd like**

Make them consistent! The easy way is to use an advanced software engineering technique called _copying-and-pasting code_. But preferably there will only be one place to store this code.

Another thing we might do is ensure that the `searchTermToKey()` function is included in the model, even when using the default function! It should be compiled as part of the model code along with the rest of the model itself. Therefore, the true implementation of the default `searchTermToKey()` will probably somewhere in the LMLayer compilation code. Note that this code needs to be IE11 compatible 😬

**Comment by mcdurdin** [comment]
> Note that this code needs to be IE11 compatible 😬

Can you elucidate? We no longer support IE11.

**Comment by eddieantonio** [comment]
> > Note that this code needs to be IE11 compatible 😬
> 
> Can you elucidate? We no longer support IE11.

Oh! Why do I still get build failures in BrowserStack when I tests for the LMLayer that use syntax that IE11 dislikes? This happened to me on #2957.
