### ISSUE TITLE
[Android] Emoji occupy the whole screen and cannot be resized/hidden

### ISSUE THREAD

**Issue by bennylin** [keymanapp/keyman#2962]
**Describe the bug**
On Telegram app, when I clicked the emoji icon, the emojis would fill the whole screen. It only happen when I'm using the Telegram app for Android. Others app are fine, and others keyboard on Telegram are fine.

**To Reproduce**
1. Go to Telegram app, open a chat or a group where you can type a message (so, not a channel that you subscribe)
2. Click on emoji icon on the 'chat box'
3. See error

**Expected behavior**
The emoji 'layer' only occupy the same size as the keyboard.

**Screenshots**
![image](https://user-images.githubusercontent.com/3002108/78695818-cf317880-7928-11ea-93dd-c1a6ffb9a80a.png)

---

**Android:**
 - Device: Nokia 2.2
 - OS: Android 9
 - Keyman version 13.0.6200
 - Target application: Telegram 6.0.1 (30 March 2020)

---
 
**Keyboard**
 - Keyboard name: SIL EuroLatin
 - Keyboard version: 1.8.1
 - Language name: English
 I also tried it with several of my keyboard that hasn't been published yet.

**Comment by mcdurdin** [comment]
Keyman doesn't have an emoji picker so I am thinking this can't be a Keyman issue?

**Comment by bennylin** [comment]
But it works on other keyboards, that's why I think this 'might be' Keyman issue, but I'm uncertain.

**Comment by mcdurdin** [comment]
@darcywong00 can you see if you can get a repro? It may be that there is some metric the Keyman app needs to report to Telegram for it to get the right keyboard area?

**Comment by darcywong00** [comment]
I can repro with my configuration
* Android: Motorola G5 S+
* OS: Android 8.1.0
* Keyman version 13.0.6207 stable
* Target application: Telegram 6.0.1 (1911)

Same default SIL Euro Latin keyboard. 

I also tried disabling predictions to see if that made any difference, but it had the same reported behavior.
