### ISSUE TITLE
feat(web): Display longpress preview on touch devices

### ISSUE THREAD

**Issue by bennylin** [keymanapp/keyman#2963]
**Is your feature request related to a problem? Please describe.**
Instead of a small dot in the top right corner of a keycap, it would be better to display the symbol in the longpress key (or one of them if there's multiple symbols)

**Describe the solution you'd like**
![preview1](https://user-images.githubusercontent.com/3002108/78699702-811f7380-792e-11ea-8fd1-9b08f358ba18.jpg)
It could be in the bottom of the keycap

![preview2](https://user-images.githubusercontent.com/3002108/78699524-3dc50500-792e-11ea-9cca-b8dc48df0d32.jpg)
Or upper right corner of it.

**Describe alternatives you've considered**
Nothing. Sometimes the dot is not really visible, and it's not really intuitive for certain people (older people, people which are not tech-savvy, first time users, etc.)

**Product context**
 - OS: Android

**Comment by mcdurdin** [comment]
Great idea :) We are looking to improve a number of things around longpress in an upcoming release and this makes a lot of sense!

**Comment by darcywong00** [comment]
This is the `hint` attribute from the [LDML keyboard spec](https://unicode.org/reports/tr35/tr35-keyboards.html#Element_map)

**Comment by mcdurdin** [comment]
We are planning to implement this in 16.0

**Comment by rc-swag** [comment]
This issue will be tracked with #5079 and #4894
