### ISSUE TITLE
[Android] Incorrect font on popup keys

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#2977]
> @darcywong00 can you test Android please (I don't have my Android phone handy).

### Android testing notes
So I ran the emulator on our minimum SDK 19, and saw the following in-app longpress issue

![SDK 19 ios popup](https://user-images.githubusercontent.com/7358010/78859031-474a8c00-7a58-11ea-8bf6-6b9825f6e40d.png)

It happens on several keys. And it's not isolated to this PR, because I get the same blanks on the current `master`. (I believe the longpress on the blank keys also output blank characters)

Longpress is fine on stable-13.0 though
![sdk 19 stable-13](https://user-images.githubusercontent.com/7358010/78859050-60ebd380-7a58-11ea-9ad8-2320907e6c29.png)

System keyboard behaved same as in-app.
Also, on Android longpress on the globe is the same has a normal press on globe.

Finally, Khmer angkor had a blank OSK. ~Retesting to see if it's the same on master~
This also occurs on `master.
![Screenshot_1586410875](https://user-images.githubusercontent.com/7358010/78866197-22aae000-7a69-11ea-9808-903771d9c31a.png)

_Originally posted by @darcywong00 in https://github.com/keymanapp/keyman/pull/2968#issuecomment-611326901_

**Comment by darcywong00** [comment]
ah, this jogged my memory. Now that the apps are installing keyboard packages, I need to check that fonts reference the packages/ folder.

**Comment by darcywong00** [comment]
For sil_euro_latin, 13.0 included DejaVuSans.ttf as an asset.
In 14.0 sil_euro_latin.kmp doesn't include the font.

----

Investigating khmer_angkor. The .kps file calls for the font
```
  <Keyboards>
    <Keyboard>
      <Name>Khmer Angkor</Name>
      <ID>khmer_angkor</ID>
      <Version></Version>
      <OSKFont>..\..\..\shared\fonts\khmer\mondulkiri\Mondulkiri-R.ttf</OSKFont>
      <DisplayFont>..\..\..\shared\fonts\khmer\mondulkiri\Mondulkiri-R.ttf</DisplayFont>
      <Languages>
        <Language ID="km">Central Khmer (Khmer, Cambodia)</Language>
      </Languages>
    </Keyboard>
  </Keyboards>
```
But the cloud download
https://api.keyman.com/cloud/4.0/languages/km/khmer_angkor?version=14.0&device=androidPhone&languageidtype=bcp47
isn't including a font. Maybe we need to update the .keyboard_info file to fix this?

**Comment by darcywong00** [comment]
Yep. again on SDK 19, I can install the khmer_angkor.kmp keyboard package. It includes the font, so the OSK and longpresses appear.

![khmer_angkor package](https://user-images.githubusercontent.com/7358010/78901645-d41a3780-7aa2-11ea-998c-fd8e2d9bbe13.png)

**Comment by mcdurdin** [comment]
> Yep. again on SDK 19, I can install the khmer_angkor.kmp keyboard package. It includes the font, so the OSK and longpresses appear.

⬆ This isn't related to that ⬇, right?

> But the cloud download
> https://api.keyman.com/cloud/4.0/languages/km/khmer_angkor?version=14.0&device=androidPhone&languageidtype=bcp47
> isn't including a font. Maybe we need to update the .keyboard_info file to fix this?

**Comment by darcywong00** [comment]
^ It was a troubleshooting step for me to confirm I needed to add Mondulkiri. khmer_angkor is resolved now.
