### ISSUE TITLE
bug(developer): `&bitmap` and `&visualkeyboard` stores are reformatted when saved

### ISSUE THREAD

**Issue by dyacob** [keymanapp/keyman#298]
Found in Keyman 10.  In the KMN Layout editor, the &bitmap and &visualkeyboard statements will be repositioned to column zero and the store names changed to uppercase upon layout save.  An example:

```
       ⋮
    store(&hotkey) '[CTRL ALT K_M]'
    store(&visualkeyboard) 'my_keyboard.kvk'
    store(&bitmap) 'my_icon.ico'
```
becomes when saved:

```
       ⋮
    store(&hotkey) '[CTRL ALT K_M]'
store(&VISUALKEYBOARD) 'my_keyboard.kvk'
store(&BITMAP) 'my_icon.ico'
```

**Comment by dyacob** [comment]
The same formatting issue occurs with the &Language and &WindowsLanguages stores.

**Comment by mcdurdin** [comment]
We should only update these lines if the values have been changed.
