### ISSUE TITLE
[Android] - Facebook Lite and "Close keyboard" error

### ISSUE THREAD

**Issue by bennylin** [keymanapp/keyman#2985]
My friend was trying the Javanese keyboard, and encountered a few errors:
* The "Close keyboard" doesn't work. I observe this in several instances (I'm in a Javanese script congress of 150 people now, where many tried the keyman keyboard) have the same problem. I estimate only 1 out of 10 keyboard can "Close keyboard" and switch back to their other default keyboard. I apologize cannot give the exact model of those phone. I think the newer model can, while the older cannot.
* In one instance, the user uses Facebook Lite, open one chat, and (1) cannot scroll up the chat ("staggering" effect?), and (2) the back button (left arrow on the bottom of keyboard) doesn't close the keyboard, but go out of the chat, which is contrary to her previous experience.

**Comment by darcywong00** [comment]
>(2) the back button (left arrow on the bottom of keyboard) doesn't close the keyboard

That will be addressed in issue #2950.
Can you provide more details about users not being able to access the "Close Keyman" button?

**Comment by bennylin** [comment]
Unfortunately I'm not with them anymore, it was some random encounters in a Javanese script seminar.

**Comment by darcywong00** [comment]
k, since we can't repro, I'll close this.

Keyman 14.0 will have the fix to dismiss the system keyboard with the back/down arrow.
And the currently released version has "Close Keyman" available from the system keyboard.
