### ISSUE TITLE
feat(developer): Feature request to define button height

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#2999]
@bennylin requests to have more control in defining button heights on layers

See original [posts](https://community.software.sil.org/t/please-enable-to-define-button-height/3160/4) in community site for screenshots

> here are 2 use cases:
>
>1. I want two layers with different number of rows to have the same button height, to maintain the look and feel (and muscle memory, among others).
>( Image 1)
> Right now the layer with four rows and five rows have different button height/size.
I wanted something like:
> (Image 2)
>
> 2. The keyboard (minus the autocomplete) occupy about 30% of the view in portrait mode (landscape-mode still have aa problem), but I saw in other keyboards go as much as 50%. For 30% keyboard height, 70% of empty space is too much, I think, and some of it could be used for keyboard instead. I want to increase the overall height a bit, probably to 40% or something.
> (Image 3)
> The letters’ size should be normal on the right, not skewed like that, of course
And numeric keyboard:
> (Image 4)
> The numbers’ size should be normal on the right, not oversized like that.
and the third one, it could also probably be the solution for the landscape-mode problem: Can we make the panorama-mode better?
>
> PS: on the 3rd and 4th image, it would be great if the suggestion bar could also be controllable, either the height adjusted (sub-request of this one), or not displayed in certain layer (a different request)
>

**Comment by mcdurdin** [comment]
Much of this is resolved with #3225, for Android. Currently, we don't have plans to support varying height of keyboard per layer.

For iOS, adjustable keyboard height is tracked in #5897.
