### ISSUE TITLE
Directionality not always set correctly for RTL input 

### ISSUE THREAD

**Issue by jmdurdin** [keymanapp/keyman#3]
KeymanWeb does not always set input element directionality correctly when changing input from LTR to RTL language.  If an element is empty, it should always change element directionality when the input language directionality changes. (If the element already contains text, the text content will have mixed directionality when new text is added, so changing element directionality automatically is not appropriate.)
In most cases, directionality will be applied correctly by going back to an LTR language then re-selecting the wanted RTL language.

**Comment by jahorton** [comment]
Attempts to replicate this bug are failing with current versions of keymanweb.com, iPhone, and Android - it appears the issue has been fixed at some point since this was reported.
