### ISSUE TITLE
[Developer] Check if Developer is creating ANSI files for .model.ts

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#3000]
From keymanapp/lexical-models#89

A lexical model had ANSI encoding causing the open/close quotes to be corrupted.

I noticed ANSI encoding for
sil.glk-arab.ptwl1.model.ts
sil.bcc-latn.upp_ptwl1.model.ts
wyc_eth.mym-latn.me_en.model.ts

Is this coming from users or Keyman Developer?

Per @mcdurdin , 
> ... it could be a bug in Developer? Default encoding **should** be UTF-8-no-bom

**Comment by darcywong00** [comment]
Encoding for the 3 lexical models fixed in keymanapp/lexical-models#90 and keymanapp/lexical-models#91

**Comment by darcywong00** [comment]
Maybe similar:
@LornaSIL used kmdecomp for keymanapp/keyboards#1163, and the .kmn file has "UCS-2 LE BOM" encoding. Shouldn't that be "UTF-8" or "UTF-8-BOM?

**Comment by mcdurdin** [comment]
> @LornaSIL used kmdecomp for [keymanapp/keyboards#1163](https://github.com/keymanapp/keyboards/pull/1163), and the .kmn file has "UCS-2 LE BOM" encoding. Shouldn't that be "UTF-8" or "UTF-8-BOM?

KMDecomp generates UTF-16 source files. It's an effectively unsupported program. You can convert them to UTF-8 within Keyman Developer or most text editors. We don't plan to fix this.
