### ISSUE TITLE
bug(common/models): Suggestion doesn't display properly for overly long words

### ISSUE THREAD

**Issue by bennylin** [keymanapp/keyman#3003]
I'm not sure if this should go here or the keyboards...

![image|50%](https://user-images.githubusercontent.com/3002108/78298192-ae99a500-755b-11ea-8be7-76060942406c.png)

So, Indonesian words are oftentimes very long, and I'm sure some other languages have long words as well. The suggestion displayed doesn't necessarily handle long-words properly, in this case, the user cannot see the full suggestions displayed on the bar.

I suggest that whenever displaying long words:
1. make the font smaller, or
2. display less than 3 suggestion (2?), or
3. make the suggestion display scrollable to the right, and display the 3 words in full

**Comment by ermshiperete** [comment]
Duplicate #5671

**Comment by mcdurdin** [comment]
See #7906, #7934.
