### ISSUE TITLE
[iOS] Current 14.0.59 alpha has kmw script error on popups

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#3038]
**Describe the bug**

Getting the following error whenever I try and open a longpress popup key:

```
[Error] TypeError: e.constructKeyEvent is not a function. (In 'e.constructKeyEvent(core.keyboardProcessor, keyman_13.dom.Utils.getOutputTarget(Lelem), keyman.util.device.coreSpec)', 'e.constructKeyEvent' is undefined)
	(_GetClickEventProperties) (preprocessor.ts:10)
	(clickKey) (preprocessor.ts:51)
	(release) (visualKeyboard.ts:1041)
	(anonymous function)
```

---

**iPhone/iPad/Android:**
 - Device: iPhone 7
 - OS: iOS 13.4.1
 - Keyman version 14.0.59-alpha-local
 - Target application: Keyman
 
---
 
**Keyboard**
 - Keyboard name: khmer_angkor
 - Keyboard version: 1.0.6
 - Language name: Khmer

**Additional context**
While testing U+25CC dotted circle alternatives

**Comment by jahorton** [comment]
I'm currently unable to reproduce this error, even when checking out the tagged release state for the version mentioned.

**Comment by mcdurdin** [comment]
Okay, well if we can't repro I'll close it.
