### ISSUE TITLE
bug(android/engine): OSK issue on 3rd party Android keyboard app

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#3042]
A 3rd party keyboard app updated to KMEA-14.0.56 alpha to test #1870
One of the users reported this OSK issue

![osk](https://user-images.githubusercontent.com/7358010/80561134-ac692000-8a0d-11ea-9ae7-ed3cd9f9603c.jpg)
### Configuration
* Phone: Oppo R11st
* OS: Android 7.1.1
* Keyboard: ntl_one_keyboard
* Keyman Engine for Android-14.0.56 alpha

> The bug doesn't show up when built against kmea 11-13
> Just on the latest release built against 14.0.56

For other users, the OSK is fine.

The keyboard does not use extra fonts.

**Comment by ericjding** [comment]
I'm the one who reported the bug to @darcywong00. I did a bisection on this bug, and found that it first crops up with KMEA 14.0.42 alpha (i.e., it doesn't show up when building against KMEA 14.0.41 alpha).

**Comment by darcywong00** [comment]
Thanks for the lead. We'll still need to find a configuration where we can reproduce the issue in an Android Studio emulator.

It will probably be about 3 weeks before I can resume looking into this.

**Comment by darcywong00** [comment]
@ericjding I set up an emulator with the Oppo R11st dimensions (6.01" screen size, 1080 x 2160 pixels), Android 7.1.1 but can't duplicate the issue with the OSK.

Can you check with your user about the **WebView implementation** on the phone?

### Unlock "Developer Options"
From Android system Settings --> About device (at the bottom) --> Build number
click "Build number" several times to unlock "Developer Options"

Then back out to system Settings --> "Developer options" --> WebView implementation (scroll about halfway down)
![Screenshot_1591863396](https://user-images.githubusercontent.com/7358010/84361933-9ea2df00-abf6-11ea-89f2-1c951cb9a355.png)

**Comment by ericjding** [comment]
Okay @darcywong00 she has since upgraded to Android 8.1.0, but the answer to your question is that her phone is currently using Android System WebView 62.0.3202.84. I’m working now on getting her a test build of the keyboard to see if the issue still occurs.

**Comment by darcywong00** [comment]
I'm going to defer this to another release, until we can get a reliably repro the issue.

**Comment by mcdurdin** [comment]
Is this still a current problem @ericjding?

**Comment by ericjding** [comment]
Unfortunately, I no longer have ready access to ask the user to test this issue, and I suspect she doesn't use the keyboard regularly anymore either. So I can't confirm or deny whether it still occurs.

**Comment by mcdurdin** [comment]
Thanks for the quick response. I'm sorry we didn't get a resolution when the issue was first reported by you. I'll get @darcywong00 to check this out once more but otherwise I think we'll go ahead and close this and focus on other current issues.

**Comment by darcywong00** [comment]
I think we can close this now. KeymanWeb 15 refactored OSK and fixes some vertical alignment issues.
