### ISSUE TITLE
change(common/lmlayer): shrink the bundle size AND make new models backwards-compatible with this one weird trick

### ISSUE THREAD

**Issue by eddieantonio** [keymanapp/keyman#3055]
> _Minifiers hate him!_

Any model that uses the join syntax, introduced in #3032/#3021 will break backward-compatibility with Keyman 12/13 because the joining is implemented in the LMLayer bundle. However, since the LMLayer supported arbitrary functions as word breakers since its initial version... **let's bundle the join decorator with each model that uses it**. Ah yes, just like my solution in #2971!

**Describe the solution you'd like**

 * The code for the joiner will migrate from `common/predictive-text/worker` to `developer/js/lexical-model-compiler`.
 * The joiner code will be compiled only into models that ask for it.
 * It will compile to something like this:

```javascript
wordBreaker: (function (wrappedWordBreaker) {
   return function (text) {
      let original = wrappedWordBreaker(text);
      let joined = /* do the joining... */;
      return joined;
  };
})(wordBreakers['default']))
```

 * ~~This also means we can compile an array of alternatives to join into a regexp, which I had in mind as an optimization!~~ Nope, that was a bad idea. See #3068

@jahorton, @mcdurdin, I'd appreciate your comments before I start on this.

**Comment by mcdurdin** [comment]
👎 on clickbait title 😛

👍 on the plan. I really like the back-compat pathway.

Re bundle size: it will increase the size of models slightly but not significantly. The models are not minified like the KeymanWeb bundle is. But the overall download size remains roughly the same for the average user.
