### ISSUE TITLE
feat(common/models): disable “keep” suggestion

### ISSUE THREAD

**Issue by eddieantonio** [keymanapp/keyman#3056]
**Is your feature request related to a problem? Please describe.**

From [Luke](https://community.software.sil.org/t/keyman-roadmap-march-2020/822/29):

> For many languages and our language it doesn’t make sense to have the option on the left side to select what you have already typed as the word. It wastes space which could have another suggestion. Spacebar should in most languages at least perform that function.

**Describe the solution you'd like**

Two options:

 * **per-model**: allow the model author to decide whether there should be a keep suggestion at all
 * **per-user**: allow the user to enable/disable the “keep” option

We could also allow for BOTH options.

**Comment by mcdurdin** [comment]
Note: as we have auto-accept of suggestions coming potentially in future versions, this could change how we view the necessity of keeping this option.
