### ISSUE TITLE
Keyboard should reset to default layer when new input field focused

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#306]
cf #288 

Keyman for iOS has the same issue where the layer isn't getting reset when switching to a new input field.
Once #288 is resolved, KeymanWeb will have the API `resetContext()`, and kmei can be updated accordingly.

**Comment by gabrielwong** [comment]
This issue appears on an iPhone 7 simulator running iOS 10.3.1 but not when running iOS 11.1.

**Comment by jacobbullock** [comment]
I don't think we can actually do anything about this for iOS 10. There is not a reliable way for us to determine that the input field has changed. The one method that gets called when the field changes is also called if you just change cursor position on the focused field and resetting the layer at that point may be frustrating.  Considering this is not an issue in iOS 11, we may have to chalk it up to an iOS bug that we can't do anything about.

**Comment by mcdurdin** [comment]
This assessment sounds fair to me. I'll mark this as wont-fix and close it out.
