### ISSUE TITLE
[Web] `initKeyEvent` function is deprecated.

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#307]
See https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/initKeyEvent - we use this function for an old bugfix/workaround in the code, but it's deprecated.  If we still need it, we should adapt the code accordingly.

**Comment by darcywong00** [comment]
Looks like it's currently used in `keymanweb._FindCaret`

**Comment by jahorton** [comment]
The responsible code (`_FindCaret`) only exists as a workaround for https://github.com/sillsdev/keyman-issues/issues/776, a bug posted back in 2007.  Investigating now to determine when the bug was fixed, as up-to-date FF does not suffer the issue when `_FindCaret` is removed.

**Comment by jahorton** [comment]
The root motivator for the code appears to be fixed as early as Firefox 4, let alone later versions.  Looks safe for removal.
