### ISSUE TITLE
[Android] Update build process to include latest default packages

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#3085]
> I can see this may be a maintenance issue for us in the future ... I wonder if we can dynamically download the latest version in the build, just as we do with FV Keyboards. This doesn't have to be fixed in this PR.

_Originally posted by @mcdurdin in https://github.com/keymanapp/keyman/pull/3079_

Investigate updating the Keyman for Android build process to download the latest versions of:
* sil_euro_latin.kmp
* nrc.en.mtnt.model.kmp

Also address how the default versions are defined in KMManager

**Comment by darcywong00** [comment]
Since MainActivity() needs keyboard info (keyboard version) at startup, do the following at **build-time**

* query and download latest kmp (see FV Android app for prior art)
* unzip and parse kmp.json (jq) to get the keyboard info
* write out to Java file

**Comment by mcdurdin** [comment]
> MainActivity() needs keyboard info (keyboard version) at startup

Is there a way to avoid this requirement? In an ideal world, keyboard version should not be needed by MainActivity as it should just be able to provide the ref to the .kmp...  That might simplify the whole story.

**Comment by darcywong00** [comment]
Fixed by #3322 in P10S10
