### ISSUE TITLE
[Android] Set Default Key Position in Long Press List

### ISSUE THREAD

**Issue by dyacob** [keymanapp/keyman#3092]
**Is your feature request related to a problem? Please describe.**
When a long press key is held down, the default mapped key will appear at the start of the list and alternatives will follow.  This can be slightly confusing when the list follows a familiar sequence that the user would be familiar with (i.e. linguistic, alphabetic, pedagogical, etc.), but prefixing the first letter breaks this familiar sequence.

**Describe the solution you'd like**
The current behavior, prefixing the base key to the start of the list, should be followed _**only**_ when the base key does _**not**_ appear in the long press list.

**Current behavior with the base key prefixed to start of list:**
![Ethiopic-Fe-Keyboard-Android-Installed](https://user-images.githubusercontent.com/8098333/81216082-531e6500-8fa8-11ea-97fe-7a34320ad948.png)

**Desired behavior where the developer sets the base key position in long press list:**
![Ethiopic-Fe-Keyboard-Android-Installed-Ordered](https://user-images.githubusercontent.com/8098333/81216094-574a8280-8fa8-11ea-8601-ef05066b98b3.png)

**Describe alternatives you've considered**
1. Not including the default key (current), can be linguistically confusing.
2. Add the default key to the desired position, these leads to a longer list with a duplication.

**Product context**
 - Mobile platforms where the keyboard is installed.

**Additional context**
This could be implement as part of the solution for #1113

**Comment by mcdurdin** [comment]
That's a good suggestion. We'll look at possibilities for this when we tackle #1113.

**Comment by mcdurdin** [comment]
It seems to me that a proper fix for this needs to give control back to the keyboard developer -- they need to be able to choose whether or not to include the base letter. If they choose to exclude automatic addition of the base letter from the popup list, they can manually add it as described by @dyacob.

This change would require design changes to Keyman Developer and the touch layout format.

**Comment by mcdurdin** [comment]
> If they choose to exclude automatic addition of the base letter from the popup list, they can manually add it as described by @dyacob.

This is sufficient. We don't need to add an option to automatically add it the key.

**Comment by darcywong00** [comment]
Since we're removing the base letter from the popup list, I believe this is only affecting Android now.
