### ISSUE TITLE
bug(web): sentry upload should happen only on CI release builds

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#3150]
**Describe the bug**
Right now, if we do `./build.sh` in web/source, then it will finish by doing an upload to sentry.keyman.com. This should not be the default behaviour.

**Expected behavior**
For test builds, and for local builds, sourcemaps should not be uploaded to sentry.keyman.com. We should control the upload of sourcemaps with a commandline parameter that we use only in the CI process.

This should be the case even if we have our local environment setup with the required sentry variables of `$SENTRY_AUTH_TOKEN`, `$SENTRY_ORG`, `$SENTRY_URL`. We still should only be uploading sourcemaps if we deliberately specify them.

---

**KeymanWeb:**
 - OS: Windows 10
 - Browser: N/A
 - KeymanWeb Version: 14.0.79

**Comment by jahorton** [comment]
I assume this would hold true for iOS as well?  iOS has the same upload pattern issue.

**Comment by mcdurdin** [comment]
> I assume this would hold true for iOS as well? iOS has the same upload pattern issue.

Definitely. I hadn't noticed it because I haven't built the iOS code for a few weeks.
