### ISSUE TITLE
fix(common,web): packages.json should use VERSION_WITH_TAG

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#3152]
Our version strings are now semver 2.0 compatible so we *should* be using them in local and test builds. This would mean that we'd update the version in all our package.json to match the global VERSION_WITH_TAG.

As a secondary benefit, we could extract the version information during a normal build because it will be available to us from the package.json environment, and we don't need to have environment.inc.ts at all.

Serious con: the horrors of embedding the version number in package.json mean that this will make all our package.json files dirty all the time. 

Second serious con: bundles package.json with our code if we replace environment.inc.ts with this.

Discuss!

**Comment by jahorton** [comment]
[From `resources/build/build_utils.sh`](https://github.com/keymanapp/keyman/blob/master/resources/build/build-utils.sh#L186-L201):

```
exportEnvironmentDefinitionTS ( ) {
    ENVIRONMENT_TS="environment.inc.ts"

    if [ -f $ENVIRONMENT_TS ];
    then
        rm $ENVIRONMENT_TS
    fi

    echo "//Autogenerated file - do not modify!
namespace com.keyman.environment {
  export var VERSION = \"$VERSION_RELEASE\";
  export var BUILD = $VERSION_PATCH;
  export var SENTRY_RELEASE = \"release-$VERSION_WITH_TAG\";
}
" >> $ENVIRONMENT_TS
}
```

---

On a side note, I'd been thinking about reworking how the web projects link with `environment.inc.ts` - it feels wrong to have each web project create its own local copy.  I'd been thinking about reworking the calls to instead create the file within `resources/build/`, much like the [Xcode-oriented `environment.sh`](https://github.com/keymanapp/keyman/blob/master/resources/build/build-utils.sh#L152-L175), which I also wrote... granted, somewhat quick and dirty itself.

**Comment by eddieantonio** [comment]
> and we don't need to have environment.inc.ts at all.

> we don't need to have environment.inc.ts at all

> #### don't need

> ### environment.inc.ts

> ## **at all**

🤯

**Comment by mcdurdin** [comment]
@eddieantonio I feel like the downside of ALWAYS DIRTY PACKAGE>JSON removes a lot of the benefit of doing away with environment.inc.ts. But environment.inc.ts *should* be its own npm package with its own build (use node to build it if you don't want to use bash!) and that would at least isolate the horrors into a single place.

> Serious con: the horrors of embedding the version number in package.json mean that this will make all our package.json files dirty all the time.

**Comment by mcdurdin** [comment]
Have a look at https://github.com/keymanapp/keyman/pull/3146#issuecomment-632939655 for additional benefit with shared tsconfig.

**Comment by mcdurdin** [comment]
This dev-side change can wait for a future version.

**Comment by mcdurdin** [comment]
I think we have the full `VERSION_WITH_TAG` in our package.jsons now. I think we also have a unified `environment.inc.ts`. So this is better than it was.

But currently we have the worst of both worlds:

* We still have (at least one) environment.inc.ts
* We have always-dirty package.json everywhere. Hundreds of them. Thousands. Crawling all over our repo. Okay, slight exaggeration. But it's awful.

No idea how to avoid the second annoying issue at this time. npm has enough bugs and issues (seriously... so many bugs) that this is probably low on their radar.
