### ISSUE TITLE
Deadkeys are not correctly mapped

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#316]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Saturday Jun 8, 2014 at 03:55 GMT_
_Originally opened as KD-85

----

(link to legacy atlassian page no longer exists)

**Comment by jahorton** [comment]
There is insufficient data for a reproduction here, and recent work on the core engine (KMW) has completely revamped how deadkeys are processed, which should address the issue fully.
