### ISSUE TITLE
feat(developer): Support commas in word count in lexical models

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#3174]
**Describe the bug**
I was playing with the language model for Khmer and the initial issue I ran into was that the word count does not show up for me in the Design view, even though they are all there in the code view.

Design View
![image](https://user-images.githubusercontent.com/28331388/82993233-76c64f80-a02a-11ea-8bfa-3dd8c11dc265.png)

Code View
![image](https://user-images.githubusercontent.com/28331388/82993297-8e053d00-a02a-11ea-9716-85340115d176.png)

After talking with @darcywong00, we found that it was because of the comma (,) in the word counts. When removing the comma in the Code View, the numbers show up in the Design View (see the screenshot below). 
![image](https://user-images.githubusercontent.com/28331388/82993525-e9372f80-a02a-11ea-95e3-c28e838b6c95.png)

NOTE: The `wordlist.tsv` were exported/downloaded from Google Sheet and of course the comma is there in the word count column.

**Expected behavior**
The word count should be shown up correctly whether or not the comma is used. :)

---

**Keyman Developer:**
 - OS: Windows 10 Pro 1909
 - Keyman Developer version: 13.0.106
 
---
 
**Keyboard**
 - Keyboard name: khmer_angkor
 - Keyboard version: 1.0.6
 - Language name: Khmer

**Comment by mcdurdin** [comment]
I'm going to classify this as a feature request -- to support formatted numbers -- rather than as a bug 😀
