### ISSUE TITLE
Handling of default keyboard

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#318]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Thursday Oct 30, 2014 at 03:55 GMT_
_Originally opened as KD-249

----

Touch devices need to be able to switch between system and mapped keyboards more smoothly, to allow tabbing between mapped and unmapped input elements. One approach would be to use a default (Latin) keyboard and switch between that and the currently active keyboard, never using the system keyboard. This would be OK as long as the switching can be smooth, and would be visually much better than switching between system and mapped keyboards. But it is inherently different from the desktop situation, so needs thinking through carefully. Possibly need a way to flag a keyboard as "install if not desktop" and modify the desktop UIs so that enable/disable is interpreted as switching to that entry. The default keyboard would be loaded as a menu entry, but when selected would disable KMW mapping (and display) entirely, allowing the physical keyboard to be used.
See KMEW-24 for more discussion.

---
JD adds:

Code has been added (for build 371) so that `setActiveKeyboard()` works a bit more smoothly, but is not reliable if called before the keyboard meta-data has been loaded.
This all needs much more careful attention. The external call should never need to specify the keyboard as `Keyboard_...`

**Comment by jahorton** [comment]
This one's dense, so I'm going to attempt to "unpack" it here.

The over-arching idea appears to be creation of a _downloadable_ default layout specification for use across the various KMW form factors within 'native' mode.  Modern KMW does provide a default layout spec used in many relevant situations, but it's not maintained separately as its own "keyboard" as the description text would suggest.

- [x] Provide a default layout specification usable for display of an OSK when no keyboard is loaded / in use
  - [ ] Make this default layout specification separately maintained and downloadable.

#### Native KMW, desktop form factor

- [x] Provide a default keyboard entry in the UI that corresponds to no actually-loaded user keyboard
  - KMW already does this for desktop by default via the 'default layout' mechanism.
  - Note that an OSK is not displayed in desktop mode when this in use.

#### Native KMW, mobile form factor

- [ ] Provide a default keyboard entry in the UI that corresponds to no actually-loaded user keyboard
- [ ] Display an OSK making this option accessible.
  - With no installed keyboards (and thus, no loaded user keyboard), KMW will not currently display the OSK, which means it also will not display any UI to show an option.  (The mobile language-picker UI currently requires the OSK.)

As swapping between 'disabled' elements (which currently use the true system keyboard) and 'enabled' elements (which use the Keyman OSK) would be kind of choppy, the idea was to provide a "disabled" OSK... which would require Keyman's touch-aliasing behavior anyway, making those elements... not so disabled.  They'd still require KMW attachment and event handling, making them disabled "in name only."

Doing this would be tricky for other reasons, too.  Displaying the Keyman OSK, unmodified, would give access to the language picker UI, which would be meaningless on 'disabled' elements.  We'd need the default layout to blot out that key when on a "disabled" input element.  Which of course means the need to track additional state, store active keyboard state when moving to a "disabled" element and restore it afterward... it'd add a lot of complexity. 

---

Note that this bit:

> to allow tabbing between mapped and unmapped input elements

was probably metaphorical, as mobile form-factor KMW doesn't actually provide tabbing.
