### ISSUE TITLE
OSK for desktop does not display Ctrl Alt (or RAlt) key text

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#321]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Thursday Aug 27, 2015 at 03:55 GMT_
_Originally opened as KD-196

----

KeymanWeb on desktop shows default and shift layers the same as Keyman Desktop OSK, but does not display keys in the Ctrl Alt (or RAlt) layers. Deciphering of the kvk needs to recognize and display keys from the CtrlAlt or RALt layer. Key output is mapped, but no key text appears.

**Comment by jahorton** [comment]
This issue no longer exists.  Further work to stablize and extend the codebase in this area was added with #300, which allows numerous other layer combinations to work and be properly displayed for desktop.
