### ISSUE TITLE
Have I done something wrong trying to install on Ubuntu 16.04?

### ISSUE THREAD

**Issue by ntzjef** [keymanapp/keyman#3217]
I'm using Ubuntu 16.04. While trying to install ibus-keyman, I continue to get this error even after following each step on the website here: https://keyman.com/linux/download

I keep getting this error:
Package ibus-keyman is not available, but is referred to by another package. This may mean that the package is missing, has been obsoleted, or is only available from another source.

E: Package 'ibus-keyman' has no installation candidate.

**Comment by darcywong00** [comment]
Hi @ntzjef 

From near the bottom of the https://keyman.com/linux page

> Q. What Linux distros will Keyman work with?
>
>A. Keyman runs on Debian, Ubuntu, Wasta Linux and can be compiled to run from source in most distributions.
>
>Note: there's currently a limitation where the Keyman packages are incomplete on the Xenial ppa

We recommend upgrading to Ubuntu 18.04 or 20.04 to install Keyman for Linux.
