### ISSUE TITLE
Embedded font test needs a different test string for each script

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#322]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Thursday Dec 12, 2013 at 03:55 GMT_
_Originally opened as KD-195

----

When testing for the existence of an embedded font, the test fails (test width always based on fall-back font) unless the test string contains characters that are contained in the embedded font. Some embedded fonts do not contain Latin script characters or contain Latin characters that have the same metrics as the default fonts (e.g. Ethiopic Wookianos=Courier), so any test for different character widths will always fail.

Solution: Include a test string with each keyboard reference that uses an embedded font. This must be handled in the keyboard database and in the KMW source code. Generally at least one wide and one narrow character should be used to reduce the risk of accidentally matching the missing character box width.

Temporary fix: Include one or two characters from the unique character set of each embedded font in the KMW code for the font test logic.

**Comment by jahorton** [comment]
No longer relevant.
