### ISSUE TITLE
Unable to position key with layout designer

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#323]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Friday Feb 14, 2014 at 03:55 GMT_
_Originally opened as KD-194

----

**Symptom:**
A key positioned at the end of a row in KMDev 9 may appear at the start of the row with incorrect width.

**Cause:**
If `"pad": ""` is an attribute of the last key in a row, the row width is incorrectly calculated and positioning is incorrect. 

**Fix:**
This is a bug in KMW Engine and will be fixed in build 344. (JD adds needs to be tested again. not sure if fix was ever implemented)

**Workaround:**
Either delete the `"pad":""` from the js or explicitly set the padding for that key to the default value of `"5"`.

Note: this only affects the last key in a row.

**Comment by jahorton** [comment]
Tests on the current builds of KMW shows that this issue was indeed resolved.
