### ISSUE TITLE
common: use labeller to automated pull request labels

### ISSUE THREAD

**Issue by eddieantonio** [keymanapp/keyman#3231]
I just stumbled across this:

https://github.com/actions/labeler#pull-request-labeler

Perhaps it can automate our pull request labels a bit?

Thoughts @mcdurdin? Feel free to close this issue if it doesn't seem applicable.

**Comment by mcdurdin** [comment]
Yes, I'd been thinking about this. I think #3233 does the job well enough -- worth 45 minutes of my time to get it going and save us all going label crazy in the future!
