### ISSUE TITLE
bug(mac): Keyman not compatible with ELAN

### ISSUE THREAD

**Issue by CelesteNgLC** [keymanapp/keyman#3243]
I have recently installed Keyman on my mac and am running the Yolŋu keyboard. I have managed to get this working for email, browser, MS office etc, however I can’t get it to work in ELAN.
The Keyman icon still appears in the top bar, but when I press a key it behaves as a standard keyboard (e.g. the shift + ‘\’ key is supposed to be ‘ŋ’, but when I hit it in ELAN it just produces ‘\’ anyway).

I really need to be able to use the Yolngu keyboard in ELAN for my work, and SIL only recommends Keyman for Mac now so it seems my only option.
Can anyone help?

**Keyman Desktop, Keyman for macOS, Keyman for Linux:**
 - OS: macOS Catalina
 - Keyman version: 13.0.101
 - Target Application: ELAN transcription software
  
**Keyboard**
 - Keyboard name: Yolngu
 - Keyboard version: ?
 - Language name: Yolngu

**Comment by MakaraSok** [comment]
Original issue has been reported on the community site: https://community.software.sil.org/t/keyman-not-working-with-elan/3495.

**Comment by MakaraSok** [comment]
> **Keyboard**
> 
> * Keyboard name: Yolngu
> * Keyboard version: ?
> * Language name: Yolngu

@CelesteNgLC Is this the keyboard you have issue with? 
https://keyman.com/keyboards/el_yolngu

**Comment by CelesteNgLC** [comment]
Yeah that's the one!

**Comment by mcdurdin** [comment]
This has the same root cause as #458 and #174. I am going to investigate whether or not we can submit a patch to Oracle to resolve this.

https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8195675.

**Comment by Salome-MAC** [comment]
Hi there, I saw the advice here to turn on legacy mode for Java apps #3944 - I'm not sure entirely what this means. I looked into Installing Java SE 6 runtime, but this appears to be incompatible with OS X Catalina which is what I'm running. Have I understood the instruction correctly? Is there anything else I can do to make Keyman Yolngu font run in Elan? Thanks heaps for any help you can offer!

**Comment by mcdurdin** [comment]
@Salome-MAC unfortunately, this is a bug in the Java platform. It has been documented for Oracle to fix for 3 years now, but they have not done anything about it. We're limited in what we can do from here. I've written up a bug report for them including how to patch -- but they have not done anything with it.

The fix I tested involved downloading the OpenJDK source code, applying the fix described in #3944 to that source, and then using that to build my own version of Java, and manually patching it into the ELAN app. That's not something that is easy to do and it's not something I can really support.

You could contact Oracle, e.g. submit a [bug report](https://bugreport.java.com/bugreport/) or a [support request](https://support.oracle.com/portal/), and chase it from there, but they are slow to respond 😢.

**Comment by Salome-MAC** [comment]
Thanks so much for your reply. I might pursue this with Keyman first, as I
have an older version of the keyboard (called Yolngu-J) on a different
computer which does work with Catalina. Strange that it was updated.

Salome Harris
Linguist

ICN: 3920
ABN: 74 197 007 196
E: ***@***.*** ***@***.***>
W: milingimbiart.com

Please note that I work mornings Monday - Thursday NT time and am not on
site at the Art Centre in Milingimbi

**Comment by mcdurdin** [comment]
Not fixed but tracking in #3935.

**Comment by darcywong00** [comment]
Another community user reported this
https://community.software.sil.org/t/on-macos-keyman-ktunaxa-works-in-notes-and-browsers-but-in-not-java-apps/11073

### Configuration
Keyman for macOS
Keyman Keyboard: Ktunaxa
Applications: ELAN 7.0, ELAN 6.8, Zotero (desktop)
