### ISSUE TITLE
Add support for universal links for keyboard downloads

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#3271]
We should setup the Install Keyboard link as a Universal Link. This means that if Keyman is not installed, it will open a two-step instruction page to install the keyboard. If Keyman is installed, then 
the link will be passed to Keyman, and Keyman should recognise it as a redirect to keyman.com/keyboards/id/download. The universal link should be on its own subdomain (or potentially a path on downloads.keyman.com?)

~~We will need to setup a new domain for the universal link endpoint. I suggest using q.keyman.com.~~ We can use specific paths on keyman.com.

I suggest we use `https://keyman.com/keyboards/install/<keyboard>[?bcp47=<bcp47tag>]`. This will be a very straightforward ~~site~~page which essentially replicates the download component of https://keyman.com/keyboards/keyboard.php, focused around a download for a specific platform and with a link to the home page.

The only supported route will be `https://keyman.com/keyboards/install/<keyboard>[?bcp47=<bcp47tag>]`. Embedding will not be supported. For example: `https://keyman.com/keyboards/install/khmer_angkor?bcp47=km`

- [ ] QRCode links will be forwarded to this page, as will keyboard shares (by a web.config rewrite rule).
- [ ] Keyboard download links on keyman.com will lead to this page.
- [ ] Probably should prevent search engines from crawling, as it will confuse ux if these end up as a landing page from a search engine (an entry in robots.txt is sufficient).

If the app is already installed, the uri will be loaded in the app, and the normal dialog for installing the keyboard will be presented.

If the app is not yet installed, the page will show a simple two step instruction:

1. Install the Keyman App [BIG FAT LINK]. This will need to be dynamically selected according to the OS. The code we have on keyman.com is reasonably reliable (perhaps we need an override though?)
2. Return here to install keyboard [SECOND LINK] (deferred deep links will make this second step unnecessary on Android).

Possible issues and questions:

* Once the app (+ keyboard) is installed, should we try to close the page to avoid repeat loads?
* Can we avoid the page being in the navigation history for similar repeat load issues?
* Should we present a "do you want to download this keyboard?" dialog before the install experience?

On Windows, step 2 may be avoidable, because we have bundled downloads (although we lose the ability to pick up the bcp47 association that the user may have already chosen).

# Background

https://css-tricks.com/hyperlinking-beyond-the-web/

# iOS "Universal Link"
iOS 9+

https://developer.apple.com/ios/universal-links/

According to this page, we can do universal links on specific paths on keyman.com, for iOS [and presumably macOS]:
https://medium.com/flawless-app-stories/bring-users-back-to-your-app-deep-linking-for-ios-5c57d8d85c2d

# macOS 

## Before Keyman has been installed

Essentially, a "deferred deep link". macOS extended attributes include the [`kMDItemWhereFroms`](https://developer.apple.com/documentation/coreservices/kmditemwherefroms) attribute, which we can use to extract parameters in the same way as we would on Windows:

![image](https://user-images.githubusercontent.com/4498365/85825197-f465b280-b7c4-11ea-9cda-bbae69f67332.png)

This requires the planned rewrite of the macOS installer (we don't yet have a specific issue for this significant functionality change) in order to be achievable. We will probably tackle this in Keyman 15.0. See #951, #952, #2490.

## With Keyman Installed

macOS 10.15+

https://stackoverflow.com/questions/40991312/universal-links-on-macos

# Android "App Link"

Android 6.0 and later

https://developer.android.com/training/app-links

This looks like potential for a single click install of Keyman + keyboard on Android:
https://css-tricks.com/hyperlinking-beyond-the-web/#instant-link-or-deferred-deep-link
https://en.wikipedia.org/wiki/Deferred_deep_linking

This suggests that we might be able to use keyman.com/some-path on Android as well: https://developer.android.com/training/app-links/verify-site-associations#multiple-apps

# Windows "App URI"

## Before Keyman has been installed

Essentially, a "deferred deep link".

This model will deprecate the bundled installer pattern, which has dramatic file storage savings for downloads.keyman.com!

We can make use of the filename of the executable downloaded from keyman.com, such as `keyman-setup.khmer_angkor.km.exe`. Details at https://docs.google.com/document/d/1rhgMeJlCdXCi6ohPb_CuyZd0PZMoSzMqGpv1A8cMFHY/edit#.

When setup.exe (which is the bootstrap for the installer) starts, it will show the welcome dialog like this:

![image](https://user-images.githubusercontent.com/4498365/85824544-65a46600-b7c3-11ea-84c9-0febc41334ad.png)

The `Install options` dialog will allow the user to change the automatically selected language:

![image](https://user-images.githubusercontent.com/4498365/85824897-33473880-b7c4-11ea-8130-9fa47f5d9c67.png)

### To finalise:
1. Format of query string.

### Questions:
1. What about multiple keyboards?
2. What about installing against multiple languages?

### Possible Downsides:
1. Requires internet access to download the keyboard file after install.

### Mitigations for downsides:
1. Check the folder where the installer is located for .kmp files and offer to install those as well.
2. Add `-keyboard-id`, `-bcp47-tag` style parameters to setup.exe as an alternate mechanism for tech staff who are deploying to users.

## With Keyman installed

~~This can be cleanly achieved on Win 10.0.19000.0 and later. Following two pages describe the method:~~

~~https://docs.microsoft.com/en-us/windows/uwp/launch-resume/web-to-app-linking~~

~~https://blogs.windows.com/windowsdeveloper/2019/10/29/identity-registration-and-activation-of-non-packaged-win32-apps/~~

~~It seems keyman.com can be achieved on Windows as well: https://docs.microsoft.com/en-us/windows/uwp/launch-resume/web-to-app-linking#associate-your-app-and-website-with-a-json-file~~

AppUriHandlers have essentially [been deprecated](https://twitter.com/ericlaw/status/1281589181387608064) on Windows. No plans to support on Chromium Edge. 

A two stage redirect pattern using protocol handlers is working well in tests. This (in JavaScript) attempts to set `window.location` to the url `keyman://download/keyboard/...` and if a focus change is detected, stops there. If no focus change is detected, then one second later it redirects to `https://downloads.keyman.com/windows/...` for the bootstrap installer as described in the Google Doc. 

# Linux

Suggest investigating protocol handlers in same pattern as Windows.

~~Not currently supported.~~ keyman.com should show the command steps for installation of Keyman for Linux and a link to the download of the .kmp, as well.

_Originally posted by @mcdurdin in https://github.com/keymanapp/keyman/issues/1535#issuecomment-562452188_

**Comment by ermshiperete** [comment]
I think something similar is possible on Linux. Zoom does something like that. If you click a link to a zoom meeting, it opens a web page that forwards to a link starting with `zoommtg://` . When Zoom gets installed it registers that URI so that it opens with `xdg-open` (which brings up a dialog asking the user for permission to open with the registered app, or allowing him to select a different app). If Zoom is not installed the web page has instructions how to install Zoom, and also a link to `zoommtg://...` in case the user has disabled automatic forwarding.

**Comment by mcdurdin** [comment]
@ermshiperete Yes, it is possible to setup custom schemes on all the platforms. Although Universal Links are a much newer and less-well-supported solution at present, I am planning to avoid using custom schemes, because they cause confusion when Keyman isn't installed. The beauty of a universal link is the fallback mechanism is completely self-explanatory 😄.

As Universal Links become better supported (after all they are now supported on all the other major platforms), I have no doubt that a solution will emerge on Linux as well. But given on Linux we have a much more complex installation story anyway, I don't think we are losing that much with the additional click for installing a keyboard -- unlike on other platforms we support which generally have more users who run into struggles installing and configuring software.

**Comment by ermshiperete** [comment]
> AppUriHandlers have essentially been deprecated on Windows. No plans to support on Chromium Edge.

The link to twitter doesn't work. The deprecation is mentioned here as well: https://textslashplain.com/2019/08/28/browser-architecture-web-to-app-communication-overview/

**Comment by mcdurdin** [comment]
> The link to twitter doesn't work.

Seems to work for me?

![image](https://user-images.githubusercontent.com/4498365/87891950-07476c00-ca7f-11ea-8369-f11121888fcc.png)

**Comment by ermshiperete** [comment]
> > The link to twitter doesn't work.
> 
> Seems to work for me?
> 

:exploding_head:  Ah, yes, it works if I enable scripts :smile:

**Comment by mcdurdin** [comment]
I believe this is essentially complete, as far as it is going to go, for all platforms except mac, which still has a two-step process. For mac, we will look at a solution similar to what we did for Windows, with a bootstrap app to install Keyman, rather than using a dmg or applescript, and rewrite the universal link pattern to use, probably, a `keyman://` approach as well.

**Comment by SabineSIL** [comment]
see #951 ,  #5318
