### ISSUE TITLE
Smart Question Mark

### ISSUE THREAD

**Issue by dyacob** [keymanapp/keyman#3285]
**Is your feature request related to a problem? Please describe.**
Accessing punctuation on a mobile keyboard often/usually requires a change of layer which leads to people omitting a punctuation at the end of a message and relying on the recipient to infer the terminal symbol.  For many common sentence structure the terminal punctuation can be predicted.

**Describe the solution you'd like**
Mobile Keyman can automatically add a final "?" to the end of a sentence when a question pattern has been detected.  The cursor will remain to the left of the "?" as the user continues to type.

An example from English.  When a sentence starts with "Who", "What", "Where", "When" and "How" the sentence is most probably a question and a closing "?" is expected.  When Keyman detects the word "Why" for example, it automatically adds the closing "?" and the user continues typing to the left.  "?" is just another symbol that the user can delete and skip past.

A configuration option could turn this predictive feature off.

This leads to the Keyman keyboard language and Keyman Developer supporting a list of simple question patterns for a language that can be tested against entered text.

**Describe alternatives you've considered**
Nothing comes to mind.

**Product context**
 - OS: iOS and Android

**Additional context**
Questions are a simple pattern to detect.  Going further, a sentiment analysis library might indicate that "!" is expected.  Regular "." could be a default terminal punctuation until either "?" or "!" is detected.  Yet another extension would be to make the terminal punctuation act like a button that when pressed the user gets a popup menu offering substitution to an alternative symbol.

**Comment by mcdurdin** [comment]
> Questions are a simple pattern to detect.

I'm going to go out on a limb here and say that this is likely only to be useful for languages where this is true! In some languages, even detecting a sentence is difficult, and I think determining end-of-sentence is a challenge even in English.

Given I don't see a generic model for this that could be applicable for any keyboard developer, at least in the foreseeable future, I'd say this feature request falls too far out of scope, sorry!
