### ISSUE TITLE
bug(web): Keyman loading time and banner splashing in iOS and Android

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#3294]
**Describe the bug**
Keyman loading is slow and banner splashes. This can be avoided.

**To Reproduce**
Switch the keyboard in iOS and android from system to Keyman.

**Expected behavior**
1. quick loading
2. No splashing of banners

**Screenshots**
Screen capture video is attached.
[ScreenCapture.zip](https://github.com/keymanapp/keyman/files/4842856/ScreenCapture.zip)

---
  
**iPhone:**
 - Device: [e.g. iPhone 11 pro max]
 - OS: [e.g. iOS 13.5.1]
 - Keyman version [e.g. 14.0.101]
 - Target application: [e.g. Notes, Mail]

**Comment by darcywong00** [comment]
> banner splashes

My understanding from your screen capture video is that you're referring to the banner on the keyboard flickering from the Keyman logo to predictive text suggestions when switching from system keyboard to Keyman keyboard.

**Comment by MayuraVerma** [comment]
Yes.

Second issue:
Also, when the keyman keyboard slides up. Keys will stretch to the full height including the predictive text field. Then predictive text field appears, while the keys re-adjusts its height.

I am trying to reproduce that issue, I will post another video with that issue by tomorrow or so.

**Comment by MayuraVerma** [comment]
@darcywong00 Please review this. In this case, the keys stretches to full height and then suggestion is added, while the keys shrinks to right size.

I think suggestion bar splashing and keys stretching are related.

Keyman is calculating the height of the keys at every launch, it might not be necessary.

[Keys_Stretch.zip](https://github.com/keymanapp/keyman/files/4855800/Keys_Stretch.zip)

**Comment by mcdurdin** [comment]
I'd like to try and take a look at this during the Keyman 14.0 beta period -- I think there are some optimisations we can do there but we are fully committed on other bug fixes and functionality up until then.

**Comment by MayuraVerma** [comment]
Thank you for reviewing this.
I should have reported this earlier. I knew issue for a long time. I should have taken time to report it, immediately.

**Comment by darcywong00** [comment]
Android app starup is tracked as #2811.

**Comment by MayuraVerma** [comment]
> @darcywong00 Please review this. In this case, the keys stretches to full height and then suggestion is added, while the keys shrinks to right size.
> 
> I think suggestion bar splashing and keys stretching are related.
> 
> Keyman is calculating the height of the keys at every launch, it might not be necessary.
> 
> [Keys_Stretch.zip](https://github.com/keymanapp/keyman/files/4855800/Keys_Stretch.zip)

@jahorton Please review this. It is not a good experience, when the key size changes everytime the keyboard is loaded.

**Comment by jahorton** [comment]
While not completely perfect - there is still some "flash of unstyled content" happening - it looks like #4279 _dramatically_ improved keyboard loading & keyboard swapping time.

**Comment by MayuraVerma** [comment]
> Keys_Stretch.zip
@jahorton yes, OSK layout flashing doesn't happen, but the keys still resize while loading the keyboard. It is a good impression. Please rectify it.
