### ISSUE TITLE
[lm-layer] Wordbreaker character specifications are incomplete

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#3318]
**Describe the bug**
For some scripts, the wordbreaker fails to recognize that letter characters... represent letters.  With the way the wordbreaker is currently written, this leads the algorithm to wordbreak after _every_ character.  This gives rise to the issue seen in https://github.com/keymanapp/lexical-models/issues/98.  (Investigation of said issue is what led to this issue's creation.)

**To Reproduce**
To reproduce this behavior, please refer to https://github.com/keymanapp/lexical-models/issues/98.

Use of the KeymanWeb testing page for predictive text UI bootstrapping (/web/testing/prediction-ui) is sufficient to reproduce this bug.  To do so:
1.  Extract both .kmps and copy their resources to the testing page's folder.
2.  At line 45 of `/web/testing/prediction-ui/index.html`, add the following:

```
kmw.addKeyboards({id:'sil_kmhmu', name:'Kmhmu', languages:{id:'kjg', name:'Kmhmu'}, filename:'./sil_kmhmu.js'});
```
- This will connect the testing page to the keyboard.
3.  At (now) line 56 or so, add the following block:

```
        var modelStub2 = {'id': 'ptwl1',
          languages: ['kjg'],
          path: (pageRef + 'sil_international.kjg-laoo.ptwl1.model.js')
        };

        kmw.modelManager.register(modelStub2);
```

- This will connect the testing page to the lexical model.

4.  Open Chrome, visit the page, and open the Developer console.  Use Toggle Device Toolbar to emulate a mobile device.

From there, test with literally any input.
- To debug, go to the Sources tab and expand the GUID-looking item; this represents the web-worker's JS context.  The item therein with the same GUID is the compiled lm-layer code.
- I suggest a CTRL+F for `function findBoundaries(text)` and placing a breakpoint early within that method to assist with tracing the issue.
    - (Current) line 2364 seems very important:

```
_a = [left, right, lookahead, wordbreakPropertyAt(lookaheadPos)], lookbehind = _a[0], left = _a[1], right = _a[2], lookahead = _a[3];
```
  - This performs character property lookup... and the properties returned for use with text output by the referenced issue's keyboard do not recognize the typed letters _as_ letters.
    - I say this based on a comparison against use of English with the MTNT model, which specified values that lead to line 2434 being `true` (involves calls to `isAHLetter()`, and the comment `W85:  Do not break between most letters`), which then triggers a `continue` to prevent said break between letters.

**Expected behavior**
Contiguous text that looks like a word should all be recognized _as_ a single word.  While Kmhmu does use a Lao-based script, it utilizes spaces for word-breaking... unlike Lao.

**Screenshots**
Note how the first character is not included in the "current word" as recognized by the wordbreaker:

![image](https://user-images.githubusercontent.com/25213402/86706373-048d5580-c041-11ea-98da-3ff5112c8696.png)

---

**KeymanWeb:**
 - KeymanWeb Version: 13.0 stable (current), 14.0 alpha (current)

Also affects Keyman for Android and Keyman for iOS, as they rely on Web internally.
 
---

**Comment by eddieantonio** [comment]
> **Describe the bug**
> For some scripts, the wordbreaker fails to recognize that letter characters... represent letters. With the way the wordbreaker is currently written, this leads the algorithm to wordbreak after _every_ character. This gives rise to the issue seen in [keymanapp/lexical-models#98](https://github.com/keymanapp/lexical-models/issues/98). (Investigation of said issue is what led to this issue's creation.)
> 
> **To Reproduce**
> To reproduce this behavior, please refer to [keymanapp/lexical-models#98](https://github.com/keymanapp/lexical-models/issues/98).
>
> [...]

Thanks for this! This is really helpful!

> * I suggest a CTRL+F for `function findBoundaries(text)` and placing a breakpoint early within that method to assist with tracing the issue.
>   
>   * (Current) line 2364 seems very important:
> 
> ```
> _a = [left, right, lookahead, wordbreakPropertyAt(lookaheadPos)], lookbehind = _a[0], left = _a[1], right = _a[2], lookahead = _a[3];
> ```

This advances the character lookups by one in the string. It cooresponds to this source code: https://github.com/keymanapp/keyman/blob/17c7868ac02b55f020cd160056cf52d3ef1b28c5/common/models/wordbreakers/src/default/index.ts#L127-L128

Only the _lookahead_ character is looked up here. In the algorithm, that's two characters after the current index.

> * This performs character property lookup... and the properties returned for use with text output by the referenced issue's keyboard do not recognize the typed letters _as_ letters.
>   
>   * I say this based on a comparison against use of English with the MTNT model, which specified values that lead to line 2434 being `true` (involves calls to `isAHLetter()`, and the comment `W85:  Do not break between most letters`), which then triggers a `continue` to prevent said break between letters.

A better place to look is at line 2543/2547 in the bundle, which actually looks up the word breaking property of the character.

https://github.com/keymanapp/keyman/blob/17c7868ac02b55f020cd160056cf52d3ef1b28c5/common/models/wordbreakers/src/default/index.ts#L313-L317

---

Given,

```typescript
text = "ະ" // U+0EB0 LAO VOWEL SIGN A
pos = 0 // get the first character
```

then `wordbreakPropertyAt(pos) == 0`.

What does 0 mean? Refer to [this enum](https://gist.github.com/eddieantonio/facb7ca78ef8d89af99b3d9c88c61a68) that gets elided out of the compiled bundle. `0 == Other`. Rules with `Other` do not have an explict rule in the Unicode Default Word Boundary specification, and "fallthrough" the rules to "break at any character" (https://unicode.org/reports/tr29/#WB999).

Looking at the data table for the word break property, I see that [some Lao characters are given the Extend property](http://www.unicode.org/Public/UCD/latest/ucd/auxiliary/WordBreakProperty.txt#:~:text=0EB1), but apart from that, characters are not given an explicity word break property.

That means that the default word boundary specification **does not consider Lao characters as ALetter** for the purpose of word breaking! 😱 

N.B., they do cop-out and say

> The following is a general specification for word boundaries—language-specific rules in [CLDR] should be used where available.  [[Source]](https://unicode.org/reports/tr29/#Word_Boundaries#:~:text=The%20following%20is%20a%20general%20specification%20for%20word%20boundaries%E2%80%94language-specific%20rules%20in%20[CLDR]%20should%20be%20used%20where%20available.)

---

So, if the default Keyman word breaker implements the Unicode default word boundary specifcation, then the current behaviour is correct. However, this is very unfortunate for Kmhmu!

I think for the original premise of this issue, this is a `wontfix`. That said, it's still concerning that the default specification does not assign properties to Lao letters.

---

I will continue to come up with a solution for Khmhu next work week!

**Comment by eddieantonio** [comment]
By the way, I checked [the CLDR](http://unicode.org/Public/cldr/37/) as Unicode says I should, and there's not much for Khmhu (ISO 639-3:`kjg`)

```
tools/java/org/unicode/cldr/util/data/language_script_raw.txt
385:kjg	Khmu	primary	Laoo	Lao
386:kjg	Khmu	secondary	Latn	Latin

tools/java/org/unicode/cldr/util/data/iso-639-3_Name_Index.tab
3191:kjg	Khmu	Khmu

tools/java/org/unicode/cldr/util/data/iso-639-3.tab
3043:kjg				I	L	Khmu

tools/java/org/unicode/cldr/util/data/languages/entityToCode.tsv
1860:http://www.wikidata.org/entity/Q33335	kjg

tools/java/org/unicode/cldr/util/data/external/2013-1_UNLOCODE_CodeListPart1.csv
5798:,"BG","KJG","Kjustendil","Kjustendil",,"--3-----","RL","0001",,,

tools/java/org/unicode/cldr/util/data/external/2013-1_UNLOCODE_CodeListPart2.csv
16209:,"JP","KJG","Kaga, Shimane","Kaga, Shimane","32","1-------","AF","9907",,,

tools/java/org/unicode/cldr/util/data/country_language_population_raw.txt
688:Laos	LA	"7,234,171"	73%	"49,340,000,000"		Khmu	kjg	5.8%			http://en.wikipedia.org/wiki/Khmu_language

tools/java/org/unicode/cldr/util/data/language-subtag-registry
17074:Subtag: kjg

common/supplemental/languageGroup.xml
66:		<languageGroup parent="mkh">bbh bgk blr caq cbn crv cwg huo jah jhi kha kjg km lbn mhe mlf mml mnw mqt mra mtq ncb oyb ply prk pry rka scb sea sii tef tnz tpu tyh uuu vi vwa wbm xao xnh zng</languageGroup>

common/supplemental/supplementalData.xml
1749:		<language type="kjg" scripts="Laoo"/>
1750:		<language type="kjg" scripts="Latn" alt="secondary"/>
3364:			<languagePopulation type="kjg" populationPercent="5.8" references="R1230"/>	<!--Khmu-->

common/supplemental/likelySubtags.xml
1195:		<likelySubtag from="kjg" to="kjg_Laoo_LA"/>
```

I couldn't find a word breaker for it :/

In fact, I can't find custom word breakers for anything except for Japanese, but it's not really a word breaker???

```xml
<segmentation type="WordBreak">
        <variables>
            <variable id="$Hiragana">\p{Hiragana}</variable>
            <variable id="$Hiragana">($Hiragana $FE*)</variable>
            <variable id="$Ideographic">[[\p{Ideographic}] [\u3005 \u3007 \u303B]]</variable>
            <variable id="$Ideographic">($Ideographic $FE*)</variable>
        </variables>
        <segmentRules>
            <rule id="13.3"> $Hiragana × $Hiragana </rule>
            <rule id="13.4"> $Ideographic × $Ideographic </rule>
        </segmentRules>
</segmentation>
```

**Comment by jahorton** [comment]
So... maybe what we need is a way for lexical models to "amend" the character spec for their language?

What I mean: they could still use the existing "default" wordbreaker if we could bake a _second_ (reduced) character-lookup table into lexical models that the wordbreaker refers to _first_.

Of course, the question is then how to generate that table.  Worst-case, users _will_ have provided a beautiful list of pre-broken words in the TSV... so maybe we could do a little compile-time AI or ML on that to determine the set of character properties that yield the best results?

**Comment by eddieantonio** [comment]
> So... maybe what we need is a way for lexical models to "amend" the character spec for their language?
> 
> What I mean: they could still use the existing "default" wordbreaker if we could bake a _second_ (reduced) character-lookup table into lexical models that the wordbreaker refers to _first_.
> 
> Of course, the question is then how to generate that table. Worst-case, users _will_ have provided a beautiful list of pre-broken words in the TSV... so maybe we could do a little compile-time AI or ML on that to determine the set of character properties that yield the best results?
> 
> Heck, the fact that we have word-broken entries would allow fairly simple logic to detect if such a table were even needed at compile time. If the word breaker is excessively breaking entries from the TSV, especially into things that aren't in said TSV, that's probably a big red flag.

Haha, yes, an easy way to extend the default. But this sounds like it'll require a LOT of design work!

I'll try to make something simpler in the meantime for Khmhu! 😅

**Comment by eddieantonio** [comment]
I'm going to makr this one as `wontfix` and continue discussion at #3347 that proposes a way to custiomize the default word breaker.
