### ISSUE TITLE
Question on BCP 47 code used in lexical model tutorial

### ISSUE THREAD

**Issue by DavidLRowe** [keymanapp/keyman#3344]
**Describe the bug**
lexical model tutorial uses BCP 47 code of str, whereas I would have expected str-Latn

**To Reproduce**
1. Go to https://help.keyman.com/developer/13.0/guides/lexical-models/tutorial/step-2
2. Scroll down to "The script subtag" heading
3. Text reads: "If your language only uses one writing system, leave this blank." But is this really correct?

**Expected behavior**
Keyman Developer checks the IANA "Suppress-Script" status and proposes a BCP 47 tag.

**Additional Notes**
If a change is made from "str" to "str-Latn" at this point, it will affect screenshots further along in the tutorial.

**Comment by mcdurdin** [comment]
This is a good question. As we are now able to, we will defer to [langtags.json](https://github.com/silnrsi/langtags/blob/master/pub/langtags.json), which shows the canonical tag as `str`. Only Windows is fussy about the script subtag, and models are not (currently) used on Windows. This goes along with how we define tags for packages and provide them to Windows and other systems, and my hope is that we can use langtags.json to provide tags that Windows is happy with, [irregardless](https://twitter.com/arielmc_g/status/1281248571858305024) of the tag that is supplied in the package.

This improvement is going to flow over into the existing bcp 47 tag use in keyboards, but I will try and make the pain minimal:

* Keyman Developer will hint when the tag is not canonical according to langtags.json
* Keyman Developer will hint when a tag is not listed in langtags.json
* Keyman Developer will offer to canonicalize according to langtags.json
* Keyman will transform to a tag that is acceptable on the system it is running on (for Windows, adding a script subtag where necessary -- probably by using the langtags.json `windows` field; on other platforms, probably just using the canonical tag).
* api.keyman.com will (already does, on staging) treat equivalent tags as identical per langtags.json.

**Comment by mcdurdin** [comment]
> * Keyman will transform to a tag that is acceptable on the system it is running on (for Windows, adding a script subtag where necessary -- probably by using the langtags.json `windows` field; on other platforms, probably just using the canonical tag).

This is implemented in Keyman for Windows in #3542, #3545.

**Comment by DavidLRowe** [comment]
I've been operating under the impression that the BCP 47 code in the keyboard and in the model need to match exactly (which has meant that a script code has been included, since that's what Keyman Developer wants for Windows). Is this no longer the case?

If so, we could end up with models named `abc.str.xyz` and `abc.str-Latn.xyz` which would presumably cause some problems somewhere. If someone revises a model and removes the script code, should we delete the old model?

**Comment by mcdurdin** [comment]
> I've been operating under the impression that the BCP 47 code in the keyboard and in the model need to match exactly (which has meant that a script code has been included, since that's what Keyman Developer wants for Windows). Is this no longer the case?

Yes, currently they need to match exactly. Keyman Developer should be slightly less strict in 14.0, allowing keyboards without a script subtag where the suppress-script property matches up for that language. That may mean some flow on issues with corresponding lexical models. Ideally we'll update to the canonical codes over time but there may be some friction in the process. We should in theory be able to match up using the knowledge in the suppress-script data but it's a fair bit of work in Keyman for iOS and Keyman for Android to get that in place, so I wouldn't want to promise it.

> If so, we could end up with models named `abc.str.xyz` and `abc.str-Latn.xyz` which would presumably cause some problems somewhere. If someone revises a model and removes the script code, should we delete the old model?

My feeling would be that we include both language tags in the model. That doesn't hurt, and it gives us backward and forward compatibility.

**Comment by DavidLRowe** [comment]
Is the BCP 47 tag matching done on the "languages" data in the .model_info file (rather than on the folder name of the project)?

IIUC you're saying that the model should have a .model_info file containing:
```
"languages": [
  "xyz",
  "xyz-Latn"
]
```

Also, I'm understanding you to say that it doesn't matter what the project folder name is (abc.xyz.def vs abc.xyz-Latn.def) because the values that matter are in the .model_info file under "languages". Is that correct?

**Comment by mcdurdin** [comment]
> Is the BCP 47 tag matching done on the "languages" data in the .model_info file (rather than on the folder name of the project)?

Yes, the folder name / file name of the model is nominal. It should be the primary BCP 47 tag that is associated with the language. We use it only for organising models in the lexical model repository. (The `.model.kmp` extension is currently a requirement, but we should really be checking the `kmp.json` data, not the presence of `.model` in the filename, for file type).

**Comment by mcdurdin** [comment]
> Also, I'm understanding you to say that it doesn't matter what the project folder name is (abc.xyz.def vs abc.xyz-Latn.def) because the values that matter are in the .model_info file under "languages". Is that correct?

The `.model_info` is used for search on the website. The languages listed in the `.model_info` are usually constructed at build time from data in the `.kps` file, as the `.kps` file is the source of truth. Normally, we should not be adding the languages into the `.model_info` file ourselves.

**Comment by mcdurdin** [comment]
Work relating to #3512 has made the Keyman for Windows changes necessary for canonicalization.

**Comment by mcdurdin** [comment]
The work referenced in this issue is all complete.
