### ISSUE TITLE
[lm-layer] easy way to say "this script uses spaces"

### ISSUE THREAD

**Issue by eddieantonio** [keymanapp/keyman#3348]
**Is your feature request related to a problem? Please describe.**

As a simpler alternative (or even complement) to #3347, say a script that typically does not use spaces (e.g., Khmer, Lao, Thai) actually _does_ use spaces for a given language (like Kmhmu written in Lao).

It would be nice to have an "override" that automatically joins words for these languages.

**Describe the solution you'd like**

In the model definition file, have a setting like `scriptUsesSpaces`. We'll need to work on the name! Here's a complete example:

```typescript
const source: LexicalModelSource = {
  format: 'trie-1.0',
  wordBreaker: {
    use: 'default',
    scriptUsesSpaces: true,
  },
  sources: ['wordlist.tsv'],
};
export default source;
```

This would customize the default word breaker to NOT break after every character in Thai, Lao, Khmer scripts! **What are other scripts that behave like this?**

**Describe alternatives you've considered**

#3347, but that one is probably too complicated for most users.

**Comment by mcdurdin** [comment]
I edited your description slightly to clarify and fix a typo :wink:

I think `spaceIsWordBreak` is better than `scriptUsesSpaces` -- even though that's a little weird, for the SEA scripts we are the looking at, the script rules are defined by the majority language that uses the script, so this is an override of the default.

So `spaceIsWordBreak` is then inherently `true` by default for all scripts except for those called out by the Unicode word break algorithm?

This seems like a good simple solution for those languages.

**Comment by eddieantonio** [comment]
> I think `spaceIsWordBreak` is better than `scriptUsesSpaces` -- even though that's a little weird, for the SEA scripts we are the looking at, the script rules are defined by the majority language that uses the script, so this is an override of the default.

What is a "SEA" script?

> So `spaceIsWordBreak` is then inherently `true` by default for all scripts except for those called out by the Unicode word break algorithm?

Those are not quite the semantics I was thinking of :/

The default word boundary specification does believe that there should be word boundaries at spaces — that's not the problem. The problem is that it breaks at EVERY CHARACTER that is not accounted for in the `WORD_BREAK` property file. That means practically all scripts whose majority language does not uses spaces, like Khmer, Lao, and Thai.

> This seems like a good simple solution for those languages.

Yes! I realize that #3347 is probably WAY too complicated, even though the Unicode spec seems to suggest it.

**Comment by mcdurdin** [comment]
> What is a "SEA" script? **EDIT**: Southeast Asian?

Yes. South-East Asian 😁 

> The problem is that it breaks at EVERY CHARACTER that is not accounted for in the `WORD_BREAK` property file.

Gotcha.

Now I am wondering if a single flag can meet our requirements. With `scriptUsesSpaces` solution, what happens with punctuation, for example, ។ in Khmer? Some of the data we could use is already in the UCD (character classes) but I don't know if it gives us what we need.

Alternatively, I don't really have a problem with asking model authors to define the codepoints used in their writing system if that is easier -- that's a fairly normal part of putting together a keyboard (but that starts to sound more like #3347).
