### ISSUE TITLE
bug(windows): Can't remove language from keyboard if text overlaps X

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/keyman#3354]
The Keyman Desktop Configuration dialog shows a X next to a language for a keyboard that allows to remove the language. However, when the window is too small the X shows up behind the text, making it impossible to click.

![image](https://user-images.githubusercontent.com/181336/87520355-21e6a300-c683-11ea-8733-bc5168ba6dda.png)

---

**Keyman Desktop**
 - OS: Windows 10
 - Keyman version: 14.0.81

**Comment by ermshiperete** [comment]
Workaround: maximize the window

**Comment by rc-swag** [comment]
This will be addressed in https://github.com/keymanapp/keyman/issues/6296
