### ISSUE TITLE
[android] Font didn't get installed consistently?

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#3366]
**Describe the bug**
Font rendering looks different when installing a keyboard from the app setting "Installed Languages" and "Add keyboard from device". It seems font only get installed when "add keyboard from device" but not when installing it from within the app.

Try install [easy_chakma](https://keyman.com/keyboards/easy_chakma) keyboard and put this text in the text editor area in Keyman for Android app.

Text: "স্তো 𑄥𑄳𑄖𑄮, স্ত্রো 𑄥𑄳𑄖𑄳𑄢𑄮, স্টো𑄥𑄳𑄑𑄮, স্ট্রো 𑄥𑄳𑄑𑄳𑄢𑄮, স্থো 𑄥𑄳𑄗 , স্থ্রো 𑄥𑄳𑄗𑄳𑄢𑄮, ন্তো 𑄚𑄳𑄖𑄮, ন্ত্রো 𑄚𑄳𑄖𑄳𑄢𑄮, ক্সো 𑄇𑄳𑄥𑄮, স্পো 𑄥𑄳𑄛𑄮, স্ফো 𑄥𑄳𑄜𑄮, স্নো 𑄥𑄳𑄚 , ল্পো 𑄣𑄳𑄛𑄮, স্মো 𑄥𑄳𑄟𑄮, ক্কো𑄇𑄳𑄇𑄮, ম্বো 𑄟𑄳𑄝𑄮, ম্ভো 𑄟𑄳𑄞 , দ্বো 𑄘𑄳𑄝𑄮, দ্ভো 𑄘𑄳𑄞𑄮, দ্ধো 𑄘𑄳𑄙𑄮, ন্ডু 𑄚𑄳𑄓𑄪, ন্ড্রু 𑄚𑄳𑄓𑄳𑄢𑄪, ন্ড্রো 𑄚𑄳𑄓𑄳𑄢𑄮, ন্দ্রো 𑄚𑄳𑄘𑄳𑄢𑄮, র্জো𑄢𑄳𑄎𑄮, ন্টো𑄚𑄳𑄑𑄮, র্বো 𑄢𑄳𑄝𑄮, র্নো 𑄢𑄳𑄚𑄮, ঙ্কো𑄋𑄳𑄇𑄮, ম্মো 𑄟𑄳𑄟𑄮, ম্বু 𑄟𑄳𑄝𑄪..."

Rendering of the text in the app when installed keyboard within the app ("Installed Languages" and then plus to add the keyboard):
![image](https://user-images.githubusercontent.com/28331388/87847276-0d174300-c901-11ea-81e4-4c1c396dd97e.png)

Rendering of the text in the app when add keyboard from device using the same .kmp:
![image](https://user-images.githubusercontent.com/28331388/87847348-ad6d6780-c901-11ea-8db8-e1ecf0d0327a.png)

**Expected behavior**
The correct rendering of the text is exactly like that of the second screenshot above.

---

**Android:**
 - Device: Xiami Mi a2 lite
 - OS: Android 10
 - Keyman version: 13.0.6216
 - Target application: Keyman for Android

---
 
**Keyboard**
 - Keyboard name: easy_chakma
 - Keyboard version: 1.20
 - Language name: Chakma

**Additional Context**
The name of the keyboard are different when installing it using different method: 
- The name is "Chakma (Chakma) (Easy Chakma)" when installing it from device and
- The name is "Chakma (Chakma, Bangadesh) (Easy Chakma)" when installing it from within the app.

**Comment by mcdurdin** [comment]
I believe this is corrected in Keyman for Android 14.0. Can you test there?

**Comment by Bivuti** [comment]
I want to try it Keyman for Android 14.0, but how can? Please help me to test it.

**Comment by mcdurdin** [comment]
We are working on a few fixes to Keyman for Android 14 and hope you can
test in a week or so.

**Comment by mcdurdin** [comment]
@darcywong00 is this ready to be tested?

**Comment by darcywong00** [comment]
I'm testing Keyman 13 in a debugger with an emulator for Android 9 and could replicate the reported issue.

I can verify Keyman 13 correctly downloaded the `RibengUni-Regular.ttf` font and sets it when switching to easy_chakma.

One possible [lead](https://stackoverflow.com/questions/57786115/why-fonts-dont-apply-if-i-create-textview-from-code-on-specific-devices) is that we might need to set the Typeface differently for Android 8.0+

**Comment by mcdurdin** [comment]
@darcywong00 that lead looks promising.

**Comment by darcywong00** [comment]
> I want to try it Keyman for Android 14.0, but how can? Please help me to test it.

Tomorrow's nightly Keyman for Android alpha build (should be 14.0.118) will have the new keyboard search for installing the easy_chakma keyboard package. (This replaces the long list of language names for installing a keyboard)

Check https://keyman.com/downloads/pre-release/#android for the latest alpha build.

Prior to Keyman 14, installing keyboards from keyman.com involved separate downloads for the keyboard and font files.

The "Settings" menu for 14.0 are a little different from before:
1. "Settings" --> "Install Keyboard or Dictionary" --> Install from keyman.com"
2. This loads the keyman.com keyboard search page where you search for "easy_chakma"
3. Click through the keyboard link and the green install button to install the keyboard package.
Since the keyboard package is installed, it should behave like "Install from device" in 13.0.

**Comment by MakaraSok** [comment]
@darcywong00 
Thank you for the updates.

@Bivuti Tested this myself with 14.0.118 alpha and it works well. The font got installed and the rendering in Keyman App looks as expected. Please test this on your side and let us know how it goes. Thanks!

**Comment by Bivuti** [comment]
@darcywong00 and @MakaraSok thanks for update keyman. I have tested the updated app it work fine now.

**Comment by MakaraSok** [comment]
So for our record, the fix in 14.0 will be live on Play Store as a Beta in early October and a Stable early next year per our project plan.
