### ISSUE TITLE
Not installed Keyboard Layouts are showing in Keyman

### ISSUE THREAD

**Issue by sreerajp** [keymanapp/keyman#3374]
**Describe the bug**
We have created a Keyman keyboard layout for Malayalam. Installed the same with Keyman Desktop. Now Keyman is showing two more layouts which are not installed in the System.

**To Reproduce**

**Expected behavior**
Keyman should only display installed Keyboard Layouts

**Screenshots**
![error1](https://user-images.githubusercontent.com/26023313/87942012-9cffed00-cab9-11ea-8073-5c802db12a83.png)

---

(Delete the irrelevant sections)

**Keyman Desktop, Keyman for macOS, Keyman for Linux:**
 - OS: Windows 10 2004
 - Keyman version: 12
   
**Keyboard**
 - Keyboard name: Malayala Manormaa Inscript
 - Keyboard version: 12
 - Language name: Malayalam

**Additional context**

**Comment by mcdurdin** [comment]
This is related to #2592 and is due to be addressed in August.
