### ISSUE TITLE
In Windows Keyman per user configuration is required

### ISSUE THREAD

**Issue by sreerajp** [keymanapp/keyman#3375]
**Describe the bug**
In windows keyman is asking for configuration in each user logging in to the machine

**To Reproduce**
1. Install Keyman by right clicking and clicking on "Run as Administrator" in Windows 10
2. After successful completion of installation in Administrator Login as a user (preferably domain user)
3. Double click on Keyman icon
4. It will again ask for configuration

**Expected behavior**
Keyman should run in all users logging into the computer once configured in Administrator. Or there should be some easy method to do that

**Screenshots**
![adminnoissue2](https://user-images.githubusercontent.com/26023313/87942714-a3db2f80-caba-11ea-938e-0685d21b21d3.png)
![usererror2](https://user-images.githubusercontent.com/26023313/87942724-a63d8980-caba-11ea-9e21-31a657993470.png)

---

**Keyman Desktop, Keyman for macOS, Keyman for Linux:**
 - OS: Windows 10 2004
 - Keyman version: 12

**Comment by mcdurdin** [comment]
The "Please wait while Windows configures Keyman Desktop 12.0" dialog is how Windows Installer configures the software for each user who logs on to the machine. It's an automatic, one-time step and does not require any user interaction.
