### ISSUE TITLE
bug(linux): Downloading/installing the euro_latin_sil keyboard for Jola-Fonyi doesn't show up in Linux keyboards list

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/keyman#3399]
**Describe the bug**
When searching for Jola-Fonyi and installing the euro_latin_sil keyboard for that language it'll install the keyboard and add an entry to the Gnome Input Sources list. However, it won't show in the keyboard selection list.

When I add the keyboard for Jola-Fonyi in the Input Sources section of the Gnome Settings dialog it will show up correctly.

**To Reproduce**
1. in km-config, click on Download and search for `l:id:dyo-latn`
2. Install the keyboard

**Actual behavior**

Keyboard shows up as `dyo:..sil_euro_latin.kmx` in Gnome Settings dialog, but doesn't show up in list of keyboards.

![Screenshot from 2020-07-23 18-57-44](https://user-images.githubusercontent.com/181336/88315362-7db1cb80-cd16-11ea-80eb-498cfb156b7f.png)

**Expected behavior**

Keyboard appears as `Other (EuroLatin (SIL) - Jola-Fonyi)` in both Gnome Settings dialog and the list of keyboards.

![Screenshot from 2020-07-23 19-00-31](https://user-images.githubusercontent.com/181336/88315693-ec8f2480-cd16-11ea-92c8-f0398983c55f.png)

This is the case if the keyboard gets added in the Gnome Settings dialog.

**Comment by ermshiperete** [comment]
The reason that it shows up when added in Gnome Settings dialog is that it gets installed as `dyo-Latn:...sil_euro_latin.kmx`.

When installing the keyboard we should compare the passed in bcp47 tag with the list of supported languages for the keyboard and use the language tag we find there. At least in the `dyo` case we would get `dyo-Latn`.

**Comment by ermshiperete** [comment]
Reimplement normalization according to langtags.json. See implementation for Windows once that is in place.

**Comment by ermshiperete** [comment]
@mcdurdin You had commented in #3408:

> This is probably a bit too straightforward. We should be normalizing according to langtags.json. I am scheduled to do that work for Windows in a couple of sprints and was hoping to define the algorithm then.

Did this got implemented on Windows in the meantime?

**Comment by mcdurdin** [comment]
> Did this got implemented on Windows in the meantime?

Yes. See `TCanonicalLanguageCodeUtils.FindBestTag`:

https://github.com/keymanapp/keyman/blob/869899fbacb425adf1e3f24411dfdbcfbb6a0504/windows/src/global/delphi/general/Keyman.System.CanonicalLanguageCodeUtils.pas#L26-L73

This has a few dependencies:

1. [`TBCP47Tag`](https://github.com/keymanapp/keyman/blob/master/windows/src/global/delphi/general/BCP47Tag.pas) validates that the tag is a valid tag and parses it
2. `TLangTagsMap` is built from langtags.json by [build_standards_data](https://github.com/keymanapp/keyman/blob/master/windows/src/buildtools/build_standards_data/Keyman.System.BuildLangTags.pas) (and hence is written at build time)
3.`TLanguageCodeUtils.TranslateISO6393ToBCP47` uses data built from http://www.iana.org/assignments/language-subtag-registry/language-subtag-registry by build_standards_data (we could use langtags.json but have not yet converted that aspect over).
