### ISSUE TITLE
bug(ios): Properly-formed KMPs do not install for language-code mismatches

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#3404]
**Describe the bug**
From #3384:

> If a language tag is specified for a resource but no match is specified by the package, installation will fail. 

It sounds as if a workaround is expected, though the ideal case would be for any of our cloud APIs providing package metadata to actually return package-supported tags.

**To Reproduce**
1. Prepare the `fv_sencoten` package, which (internally) only supports language code `str-Latn`.
2. Attempt to install it (via code edits) with language code `str`.
    - This has been returned by keyman.com's keyboard search at certain points in time.

The package installation will fail.

**Expected behavior**
This may be somewhat up for debate in and of itself.

On one hand, the fact that the query did not match the package is concerning and is rightfully seen as an error.

On the other hand... `str` is the 'root' component of `str-Latn`, so maybe a little BCP-47 language tag processing is in order.

**Comment by mcdurdin** [comment]
> * This has been returned by keyman.com's keyboard search at certain points in time.

Note that the keyboard search should no longer return BCP 47 codes that are not listed by the package. However, for robustness, the installation code should handle this situation and fall back to having either a default language selected or no language selected.
