### ISSUE TITLE
Deadkeys in iTerm2

### ISSUE THREAD

**Issue by perwigren** [keymanapp/keyman#3440]
**Describe the bug**
When using deadkeys in iTerm2, both the deadkey symbol and the combined letter is displayed.

**To Reproduce**
1. Select the "United States-International Basic" keyboard in Keyman
2. Start iTerm2
3. Type ^ (shift+6) then press a
4. It outputs ^â instead of just â

**Expected behavior**
It should output â

**Screenshots**
![Screenshot 2020-07-31 at 08 50 38](https://user-images.githubusercontent.com/48593237/89008526-1c3bbf00-d30b-11ea-9686-002fbe7ef6f6.png)

**Keyman for macOS**
 - OS: macOS Catalina 10.15.6
 - Keyman version: 13.0.101
 - Target Application: iTerm2 v3.3.12
  
**Keyboard**
 - Keyboard name: United States-International Basic
 - Keyboard version: 1.1
 - Language name: English

**Additional context**
iTerm2 has no problem with deadkeys on keyboards created with Ukelele, only Keyman.

**Comment by mcdurdin** [comment]
Thank you for this report. I have scheduled this for investigation in an upcoming sprint.

**Comment by mcdurdin** [comment]
I've finally had some time to do some investigation on this issue -- thank you for your patience -- and have found a setting in iTerm2 that resolves this deadkey issue, under Preferences/Advanced/Experimental Features/Improved support for input method editors like AquaSKK.

I note that iTerm2 struggles with some other keyboards, such as Khmer Angkor, but I think this is more of an issue with rendering than with input.
