### ISSUE TITLE
Key Type "Special" non-latin text

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#3443]
**Describe the bug**
Key Type "Special" non-latin text such as \*೧೨೩\*, will display * until \*123\*. If ೧೨೩ is used without *'s. then these keys popup.

**To Reproduce**
Change the text from \*123\* to \*೧೨೩\* Key Type "Special" in default layer of latin_euro_sil keyboard. and ೧೨೩ in place of *123* in shift layer.

1. Both will make the keys popup, unlike with it is \*123\*.
2. When it is \*೧೨೩\*, it doesn't hide *'s. Although I don't the reason for it.

**Expected behavior**
If the keyboards are to be localized in all languages, we need special keys to accept non-latin and must not popup.

**Comment by mcdurdin** [comment]
Can you include some screen shots?

Note: the `*` code indicates an alias for a symbol defined in the on screen keyboard font. You should not use `*` for anything other than the codes defined (near the end of the page) at: https://help.keyman.com/developer/engine/web/current-version/reference/layoutspec

**Comment by MayuraVerma** [comment]
![image](https://user-images.githubusercontent.com/14062593/89142802-0e09c080-d50e-11ea-86aa-699739d73925.jpeg)
![image](https://user-images.githubusercontent.com/14062593/89142818-12ce7480-d50e-11ea-9d2e-d77b6d8abba6.jpeg)

**Comment by mcdurdin** [comment]
@jahorton It looks like this is a bug with the logic around preview on 'special' keys. If the key type is 'special', it should not show a preview. Can you confirm?

**Comment by jahorton** [comment]
> @jahorton It looks like this is a bug with the logic around preview on 'special' keys. If the key type is 'special', it should not show a preview. Can you confirm?

I don't get a popup with the standard 'special keys', so that part does look like a bug, yes.

**Comment by MayuraVerma** [comment]
If you use non-text as label with special key, you should see these pop up. eg. ೧೨೩ ಅಆಇ
This is not intended behavior

**Comment by MayuraVerma** [comment]
Could we please get this resolved for v14

**Comment by MayuraVerma** [comment]
Hello @jahorton @mcdurdin 

This is resolved in version v14.0.225.

Thank you
