### ISSUE TITLE
feat(android/app): language selection during KMP installation

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#3476]
This feature request is to add a language picker during keyboard KMP installation (maybe UX similar to #3437 for iOS)
No UX change for lexical-model KMP installation.

Currently, only keyboard installs from a language search on keyman.com will install the keyboard package with a pre-selected BCP 47 language tag.

We can re-use `SelectLanguageActivity` (used to add a language to an already installed keyboard) to change the KMP installation workflow:

1. while kmp is still in a temp path (no change from current behavior)
2. Display `readme.htm` with **Cancel** and **Install** buttons
3. If kmp.json has > 1 language in the package -->
    a. `readme.htm` has **Next** button instead of **Install** which goes to language picker
    b. Display language picker (back arrow goes back to `readme.htm`)
    c. User selects n languages (click "Next" to advance)
4. PackageProcessor extracts kmp to /packages/ and installs keyboard package with the selected BCP 47 language tags
5. Display `welcome.htm` when finished

PackageProcessor still has a "silent" mode where none of the documentation is displayed. If no language is passed, it'll just install the first one.

## readme.htm
![readme](https://user-images.githubusercontent.com/7358010/90093979-fbd22280-dd56-11ea-9443-6d5ffd302ddb.png)

## language picker
![select language](https://user-images.githubusercontent.com/7358010/90094387-ffb27480-dd57-11ea-8d99-66c43f12fae7.png)

## welcome
![welcome](https://user-images.githubusercontent.com/7358010/90094230-9468a280-dd57-11ea-98d7-83c742a94984.png)

-----------------------------
## readme.htm
![readme](https://user-images.githubusercontent.com/7358010/89848932-a01a6480-dbb1-11ea-92c5-7cdb4eaea4cd.png)

## language picker
![language picker](https://user-images.githubusercontent.com/7358010/89849028-d7891100-dbb1-11ea-845d-c6e68bb06082.png)

## welcome.htm
![welcome](https://user-images.githubusercontent.com/7358010/89849038-dbb52e80-dbb1-11ea-9957-0f1d539ea045.png)

**Comment by darcywong00** [comment]
@mcdurdin What would the workflow look like for a keyboard package containing multiple keyboards 
(e.g. https://keyman-staging.com/keyboards/install/galaxie_greek_hebrew_mnemonic)?

**Comment by mcdurdin** [comment]
The process looks good. A few comments on the UI design:

* The title is a little messy and unclear. It needs to be larger, and be `Install <name> <version>` probably. See next points for layout.
* The `Next` button should be at the top, and instead of `Cancel` it should show the `<` back button on the left, which is the Android style. The title should be next to the `<` button.
* On the second page, the language picker should be a list from which you can check one or more languages. It should not have arrows on the right hand side. Furthermore, we can probably hide the BCP 47 codes here.
* On the second page, add an `Install` button at the top right to match the first page, and a `<` button at the top left.
* On the final page, the `OK` button can be at the top right, and no `<` button should be visible. The title on this page should show `Welcome to <name> <version>` or similar, not `Install Keyboard`, as the keyboard is now installed.

> What would the workflow look like for a keyboard package containing multiple keyboards
> (e.g. https://keyman-staging.com/keyboards/install/galaxie_greek_hebrew_mnemonic)?

In theory you show the second page for each keyboard (with `Next` instead of `Install` as necessary). In practice, I hope that multi-keyboard packages don't have multiple languages for each keyboard, and the second page isn't shown at all.

**Comment by darcywong00** [comment]
> *  In practice, I hope that multi-keyboard packages don't have multiple languages for each keyboard, and the second page isn't shown at all.

Of the 6 multi-keyboard packages (ignoring fv_all)
galaxie_greek_hebrew_mnemonic has 2 keyboards, each with 2 languages
galaxie_greek_hebrew_positional has 2 keyboards, each with 2 languages
syriac_aramaic has 3 keyboards, each with many languages

**Comment by darcywong00** [comment]
More from discussing with @mcdurdin 
> Keyboard Packages with multiple keyboards:
> * For multiple keyboard packages, let's just display the language picker for the first keyboard (and use the default/first language for all the other keyboards). 
> * In the future, we'll remove the "modern" languages from the galaxie_greek_hebrew keyboard packages.
>
> PackageProcessor
> * It's fine to have redundant parsing of kmp.json (before install for UI choices, and again for installation)
> * Pass in a list of language ID's to use with the first keyboard in a package
>
> SelectLanguageActivity
> * Hide the BCP 47 language codes and sort the language list by language names

**Comment by mcdurdin** [comment]
> * For multiple keyboard packages, let's just display the language picker for the first keyboard (and use the default/first language for all the other keyboards).

Sorry, I think I meant "for multiple keyboard packages, don't display the language picker at all, and just use the default/first language for all keyboards)"

**Comment by darcywong00** [comment]
> The title is a little messy and unclear. It needs to be larger, and be Install <name> <version> probably. See next points for layout.

Can I just keep the title to match the current string "Install Keyboard Package <version>"?
a. If the package contains a readme.htm, the displayed readame likely will have the name of the keyboard package in the title.
b. If the package does not contain a readme.htm we already display a template that has the package name (see screen below):

![generated readme](https://user-images.githubusercontent.com/7358010/90332576-2686da00-dfe8-11ea-9b53-167b577ab608.jpg)

**Comment by mcdurdin** [comment]
> Can I just keep the title to match the current string "Install Keyboard Package "?

How about just "Install Keyboard" (no need to say 'Package' as well here)

**Comment by darcywong00** [comment]
> How about just "Install Keyboard " (no need to say 'Package' as well here)

I didn't get the Markdown correct. There's a version at the end so it would be:
"Install Keyboard &lt;version&gt;"

**Comment by mcdurdin** [comment]
> "Install Keyboard <version>"

`"Install Keyboard (version <version>)"` and I'm okay with that 💯

**Comment by darcywong00** [comment]
As for the "back" button and "forward / next / install" UX

The Material Design spec used to have [steppers](https://material.io/archive/guidelines/components/steppers.html) but afaict it's an archived spec they haven't implemented.
The closest component now seems to be [bottom navigation](https://material.io/components/bottom-navigation) but that doesn't exactly fit us either.

I think I'll just have a button bar at the bottom with
<- BACK      NEXT -->
("NEXT" interchangeable with "INSTALL")

**Comment by mcdurdin** [comment]
> afaict it's an archived spec they haven't implemented.

Material Design is more a set of design principles and not always implementations. The following discussion is helpful: https://ux.stackexchange.com/a/130233

Implementing a Stepper design with a button bar is appropriate. Showing one, two, three dots at the bottom helps users to know how many steps they will encounter:

1 dot: package has one language, no welcome.htm.
2 dots: package has one language, has welcome.htm.
2 dots: package has multiple languages but no welcome.htm.
3 dots: package has multiple languages and welcome.htm.

When the welcome.htm page is shown, the back button is disabled but it should still be part of the same UI flow.

**Comment by darcywong00** [comment]
Fixed with #3498
