### ISSUE TITLE
Add Linux version

### ISSUE THREAD

**Issue by baimafeima** [keymanapp/keyman#348]
OS: Solus (https://solus-project.com/)
I have just read that Keyman is now free and open source here: https://blog.keyman.com/2017/08/keyman-is-now-free-and-open-source/
It would be a tremendous help to have a Linux-based version of it. Is this something you are currently pursuing or would you rather recommend to contact the 'Keyboard Mapping for Linux' project? See: http://kmfl.sourceforge.net/ and https://sourceforge.net/projects/kmfl/

**Comment by mcdurdin** [comment]
There is a long term plan to integrate the KMFL project. It is mostly compatible with Keyman already, but we don't currently have the resources to take on another platform just yet.
