### ISSUE TITLE
[android] "Resource Updates Available" Notification

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#3484]
**Describe the bug**
On Keyman for Android, the notification read "Resource Updates Available" won't go away after the download/update is completed.

![image](https://user-images.githubusercontent.com/28331388/90208970-61381900-de14-11ea-9eaa-e656623ec4ab.png)

---
  
**Android:**
 - Device: Samsung Galaxy S9+
 - OS: Android 10
 - Keyman version 13.0.6216
 - Target application: Android notification?
 
---
 
**Keyboard**
 - Keyboard name: EuroLatin (SIL)
 - Keyboard version: 1.9.2
 - Language name: English

**Comment by mcdurdin** [comment]
I note also that it is not possible to dismiss this notification, if you decide you don't want to install the update!

**Comment by mcdurdin** [comment]
This morning, I have two update notifications I can't dismiss 😢

![image](https://user-images.githubusercontent.com/4498365/90440811-32bf8400-e11b-11ea-93f7-2036a1cade80.png)

**Comment by darcywong00** [comment]
I'll have to investigate some more to find what's causing this.

One "workaround" is to reboot the device 😞

**Comment by darcywong00** [comment]
Fixed by the PRs above
