### ISSUE TITLE
[iOS] version number in settings should be updated with each release

### ISSUE THREAD

**Issue by eddieantonio** [keymanapp/keyman#3489]
**Describe the bug**

The version number in the settings on iOS is eternally fixed at version 10.0.0, build 10.0.0:

https://github.com/keymanapp/keyman/blob/83c8396b18432017dc301d8c919f8e99d10f3c9d/ios/keyman/Keyman/Settings.bundle/Root.plist#L9

**To Reproduce**
1. Go to the iOS settings
2. Select the Keyman settings
3. Look at the version number:

**Expected behavior**

It should always have the current version and build number

**Screenshots**

![IMG_0C3EC6A58202-1](https://user-images.githubusercontent.com/2294397/90527855-3eb54100-e12f-11ea-913a-9fe6563cf49b.jpeg)

---

(Delete the irrelevant sections)
  
**iPhone/iPad/Android:**
 - Device: iPad Pro 10.5" (2nd gen)
 - OS: iOS 13.6
 - Keyman version: I wish I could tell you :joy: (but the latest downloaded from the app store 2020-08-18)
 - Target application: Keyman/Settings

**Comment by mcdurdin** [comment]
I believe this has been fixed in 14.0, in #2775.
