### ISSUE TITLE
First letter in popup key is small

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#3513]
**Describe the bug**
First letter in popup key is small

**To Reproduce**
Push any popup key is small

**Expected behavior**
Same size for all keys

**Screenshots**
![IMG_5939](https://user-images.githubusercontent.com/14062593/91268033-32864080-e73a-11ea-97e4-45795dee2e7e.jpg)
![IMG_5940](https://user-images.githubusercontent.com/14062593/91268037-34e89a80-e73a-11ea-8539-871ba982bb58.jpg)
![IMG_5941](https://user-images.githubusercontent.com/14062593/91268038-35813100-e73a-11ea-80ae-7da75f459c1b.jpg)
![IMG_5942](https://user-images.githubusercontent.com/14062593/91268040-35813100-e73a-11ea-9dcc-e42293330da9.jpg)
![IMG_5943](https://user-images.githubusercontent.com/14062593/91268042-3619c780-e73a-11ea-9935-4701a9a5dabb.jpg)

---

**iPhone/iPad/Android:**
 - Device: [e.g. iPhone 11 Pro Max]
 - OS: [e.g. iOS 13.6.1]
 - Keyman version [e.g. 14.0.133]
 - Target application: Notes

---
 
**Keyboard**
 - Keyboard name: EuroLatin (SIL)
 - Keyboard version: 1.9.1
 - Language name: English

**Comment by mcdurdin** [comment]
Yes, I've seen this but always forget to document. We'll try and address this in the 14.0 timeframe.

**Comment by jahorton** [comment]
Already documented as part of #2990.

Additionally... since this issue was made, we ended up nixing the prepended base key, which is the key that was being displayed as small.  I'll need to double-check to be sure, but this has probably eliminated the issue.

**Comment by jahorton** [comment]
Now that we aren't prepending the base key, this is no longer happening.  Seems that the root cause was related to that operation.
