### ISSUE TITLE
tsysinfo.exe

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#3537]
**Describe the bug**
tsysinfo.exe determined as unsafe by Cylance protect

**To Reproduce**
Install latest version of Keyman on Windows 10 with Cylance protect

**Expected behavior**
Complete the installation

**Screenshots**
![tsysinfo exe](https://user-images.githubusercontent.com/14062593/91590466-185a8700-e921-11ea-94d2-24e4b9855fb8.png)

**Comment by mcdurdin** [comment]
Can you report this as a false positive to Cylance?

**Comment by mcdurdin** [comment]
This is not technically a bug in Keyman; it's a bug in Cylance (their heuristic picks up tsysinfo as potentially dangerous, when it isn't.)
