### ISSUE TITLE
[web] "ctrl-alt" and "shift-ctrl-alt" layers on longpress keys do not output the expected on Android 10 device

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#3569]
**Describe the bug**
Longpress keys with references to "ctrl-alt" and "shift-ctrl-alt" do not produce the expected output on Anndroid 10. The output could be a `beep` or an unexpected character.

**To Reproduce**
1. Download this [keyboard](https://community.software.sil.org/t/longpress-key-gives-invalid-key-beep-on-phones-but-works-correctly-on-test-keyboard-on-web/3823/3?u=makara)
2. Add it to Keyman for Android on Android 10 Emulator
3. Go to Numeric layer and then longpress on `[` and then pick `{`.
4. See error, a beep was output instead of {.

_You can also try other longpress on Numeric layer to see similar behavior._ 

**Expected behavior**
When given correct references on longpress keys to the existing key sequences (i.e. ctrl-alt and shift-ctrl-alt), the longpress keys should output the character being referred to.

---

(Delete the irrelevant sections)

**Android:**
 - Device: Pixel 2
 - OS: Android 10
 - Keyman version: 13.0.6218
 - Target application: Keyman for Android

**Keyman Developer:**
 - OS: Windows 10 1909
 - Keyman Developer version: 13.0.111
 
---
 
**Keyboard**
https://community.software.sil.org/t/longpress-key-gives-invalid-key-beep-on-phones-but-works-correctly-on-test-keyboard-on-web/3823/3?u=makara

**Additional context**
A work around: changing the key Modifier to "current layer" and Code to "K_4" for the longpress key fix the issue for now.

This issue may occur on iOS as well, but I do not have a device to test.

**Comment by darcywong00** [comment]
Upon investigation, this defect has existed in KMW kmwembedded.ts since at least `stable-10.0`. That's why the keyboards still work in mobile viewport of KMW.

`var t=keyName.split('-')` fails to account for layers that contain `-` (e.g. `ctrl-alt` or `shift-ctrl-alt-shift`).
