### ISSUE TITLE
[Web] Regression - Shift broken on mobile layouts

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#358]
In particular, keyboards using the default mobile layout are unable to shift correctly at present in KMW, seemingly regardless of native or embedded mode.  This does not affect EuroLatin2, which has a custom-designed OSK.

My first guess is a possible oversight with #310, though further investigation into the matter will be necessary to confirm this.

**Comment by mcdurdin** [comment]
Fixed by #359
