### ISSUE TITLE
bug(android): when downloading a package, system prompts user on which app to use to download

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#3595]
**Describe the bug**
Watch the video: https://photos.app.goo.gl/mrjsh3Dp8ok9595N7

After clicking the **Install Keyboard** button, a prompt appears:

![image](https://user-images.githubusercontent.com/4498365/93541611-48360100-f99a-11ea-89c8-28a96cb4ea01.png)

(ignore the video controls on the screenshot)

**Expected behavior**
This prompt should not appear -- instead, Keyman should always download this file.

---

**Android:**
 - Device: Samsung Galaxy A90 5G
 - OS: Android 10
 - Keyman version 14.0.144-alpha-test-3039

**Comment by darcywong00** [comment]
Our AndroidManifest.xml already has intent-filters to register for .kmp extensions.

I think the Chromium [manifest](https://chromium.googlesource.com/chromium/src/+/b71e98cdf14f18cb967a73857826f6e8c568cea0/chrome/android/java/AndroidManifest.xml) looks for any http or https, so I think that's why it also shows as an option.
ll/ 177-187
```
<!-- Matches the common case of intents with no MIME type.
  Make sure to keep in sync with the next filter.  -->
<intent-filter>
   <action android:name="android.intent.action.VIEW" />
   <category android:name="android.intent.category.DEFAULT" />
   <category android:name="android.intent.category.BROWSABLE" />
   {% if channel in ['stable', 'default'] %}<data android:scheme="googlechrome" />{% endif %}
   <data android:scheme="http" />
   <data android:scheme="https" />
   <data android:scheme="about" />
   <data android:scheme="javascript" />
</intent-filter>
```

**Comment by mcdurdin** [comment]
Yeah, but within the Keyman app, we should be able to prioritise our own handling, surely? We don't want any other app to pop up at this point, because this is part of the Keyman UX and flow.

**Comment by mcdurdin** [comment]
```
@Override
    public boolean shouldOverrideUrlLoading(WebView  view, String  url){
        return true;
    }
    @Override
    public void onLoadResource(WebView  view, String  url){
        if( url.equals("http://yoururl.com") ){
            // do something
        }
    }
}
```

Something like this?
