### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by baimafeima** [keymanapp/keyman#360]
Could you make the changelog directly visible in your GitHub releases? This would increase transparency for potential users and distribution maintainers. Something like https://skywinder.github.io/github-changelog-generator/ could be used to generate the changelog based on merged PRs and closed issues since the last release tag.

**Comment by mcdurdin** [comment]
That's a good idea for automatic logs; we also have curated logs available as history.MD files in each of the platform folders (Windows under windows/src/desktop/ and windows/src/developer/).

**Comment by mcdurdin** [comment]
This is now complete with a single consolidated [HISTORY.md](https://github.com/keymanapp/keyman/blob/master/HISTORY.md). This file is automatically updated with every release build (alpha, beta or stable), and may be manually edited for clarity over time.
