### ISSUE TITLE
[web] text goes beyond the textbox boundary

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#3600]
**Describe the bug**
When typing a number of characters consecutively with or without regular spaces between them, the text beyond the boundary is no longer visible. The character is still output at keypress, but they cannot be seen in the box.

**Expected behavior**
When a character hits the textbox boundary, it should drop to the next line.

**Screenshots**
![image](https://user-images.githubusercontent.com/28331388/93838361-92c5bf00-fcb3-11ea-9de1-a2da065d10d1.png)

---

(Delete the irrelevant sections)

**KeymanWeb:**
 - OS: Windows 10 1909
 - Browser: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
 - KeymanWeb Version: (tested from Keyman Developer 13.0.112)
 
---
 
**Keyboard**
 - Keyboard name: [sgaw_karen](https://github.com/keymanapp/keyboards/pull/1317)
 - Keyboard version: 1.0
 - Language name: Sgaw Karen

**Additional context**
This happens on Chrome Emulator after toggling the orientation to vertical.

**Comment by jahorton** [comment]
So... emulated word-wrapping.  That's likely tricky to implement.  I mean, http://unicode.org/reports/tr14/ exists for a reason.

I imagine the default word-breaker (for predictive text) would likely be a decent reference/starting point for implementation of something should we choose to pursue this.  Referring to that... this issue is definitely not low-hanging fruit.

**Comment by jahorton** [comment]
For comparison, with English:

<img width="296" alt="image" src="https://user-images.githubusercontent.com/25213402/165785470-5e6a2ec8-bed6-441a-968b-78b5ba93341c.png">

Same word; I just split the second copy with a hyphen (no space).

For comparison, if I apply the same style to a `<p>` element:

<img width="384" alt="image" src="https://user-images.githubusercontent.com/25213402/165786004-1131f564-ab09-4c39-9310-8f4b24167868.png">

The browser's built-in word-wrapping itself is at fault.  KMW's word-breaking in text boxes relies upon that.

**Comment by mcdurdin** [comment]
Fixed with removal of touch alias elements in #7343
