### ISSUE TITLE
[linux] Add an appdata file

### ISSUE THREAD

**Issue by baimafeima** [keymanapp/keyman#361]
For reference: https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps

**Comment by mcdurdin** [comment]
Is this specifically for Linux or something that is used on other platforms as well?

**Comment by baimafeima** [comment]
It was primarily designed by and for Linux-based operating systems as a "cross-distro effort for enhancing the metadata available about software components in the Linux and free-software ecosystem. One of the project's goals is to make building software-center applications possible, and make interaction with the package sources of a distribution smarter." If Linux support is on your roadmap, at least long-term, this should be too as it would make your application much more accessible and easier to maintain by distribution maintainers. 
Further info here: https://www.freedesktop.org/software/appstream/docs/

**Comment by mcdurdin** [comment]
Okay that makes sense. I think we will tackle this at the same time as
integration of KMFL.

**Comment by darcywong00** [comment]
Only keyman-config will be handled in this issue.
The other projects will be covered in #1596
