### ISSUE TITLE
Keyman stops working when switching between languages using 'Arrow key' and then 'enter'

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#362]
The popup message read, "Unfortunately, Keyman has stopped."

[Moved from keymanapp/keyboards#62]

**Comment by darcywong00** [comment]
@MakaraSok can you provide more details on how to replicate the crash?

On 10.0.10000016 alpha, I'm able to use the arrow keys to change language both in-app and as system keyboard.

**Comment by darcywong00** [comment]
Needs more info to repro

**Comment by darcywong00** [comment]
CND
