### ISSUE TITLE
feat(developer): Caps lock act as 2nd shift

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#363]
Hello,

I request we create a system state in which CAPS LOCK can act as 2nd Shift button.

While in CAPS LOCK state, if any button is pressed, CAPS LOCK would get released.

similar to 
store(&capsalwaysoff) "1"
store(&capsononly) "1"
store(&shiftfreescaps) "1"

maybe 
store(&capsanykeyrls) "1"

And also, ability to change the state of CAPS LOCK with output sequence.

**Comment by darcywong00** [comment]
Thanks for the suggestion. We plan to implement caps-lock for touch layout keyboards as part of #3620 in 16.0.

But I don't think we will support it for desktop keyboards.
