### ISSUE TITLE
[windows] Keyman Desktop 14.0.150.0 won't get installed

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#3636]
**Describe the bug**
I made an attempt to install the latest alpha version of Keyman Desktop ([keymandesktop-14.0.150.0.exe](https://downloads.keyman.com/windows/alpha/14.0.150.0/keymandesktop-14.0.150.0.exe?_ga=2.31315448.635027399.1601257698-30305726.1574652282)), but an error occurred soon after double-clicking on the EXE. A dialogue box popped up saying "Exception EInvalidCast: Invalid class typecast" (See screenshot).

![image](https://user-images.githubusercontent.com/28331388/94502264-f6a93400-022d-11eb-8e93-bac15478c643.png)

**To Reproduce**
1. Remove all keyboard packages from the current Keyman Desktop version
2. Remove all keyboards in Windows' Language Preferences except EN and your locale
3. Uninstall the current Keyman Desktop and/or Keyman Developer
4. Restart Windows
5. Download and install version 14.0.150.0.
6. See error (screenshot above)

**Expected behavior**
Smooth installation and see fixes of the following issues: 

1. https://github.com/keymanapp/keyman/issues/2942
2. https://github.com/keymanapp/keyman/issues/1843
3. https://github.com/keymanapp/keyman/pull/3627
4. https://github.com/keymanapp/keyman/issues/1659

---

(Delete the irrelevant sections)

**Keyman Desktop:**
 - OS: [Windows 10 Pro 1909, build 18363.1016]
 - Keyman version: [[14.0.150.0](https://downloads.keyman.com/windows/alpha/14.0.150.0/keymandesktop-14.0.150.0.exe?_ga=2.223264220.635027399.1601257698-30305726.1574652282)]
 - Target Application: [N/A]

  
**Additional context**
You may sometimes see the Keyman installation window, but after clicking install, the same dialogue box popped up. Click on "OK" the box disappear, but then when re-attempting it, the same thing happens.

**Comment by mcdurdin** [comment]
Okay, I am not able to reproduce this issue on my machine. We may need to test this with a debugger directly on your machine.

**Comment by MakaraSok** [comment]
2. #1843, 3. #3627 and 4. #1659 are working as expected, but 1. #2942 needs further investigation--see my comment in https://github.com/keymanapp/keyman/issues/2942.

**Comment by MakaraSok** [comment]
`14.0.169-alpha` won't get installed with the following message:
![image](https://user-images.githubusercontent.com/28331388/97264118-e4cfa680-1856-11eb-84cc-a077ffdc2348.png)

**Comment by mcdurdin** [comment]
Moved this to a new issue #3775 because it's a separate problem.
