### ISSUE TITLE
[Windows] Distinguish between RAlt and LAlt for shortcuts in Keyman

### ISSUE THREAD

**Issue by andjc** [keymanapp/keyman#364]
Distinguish between RAlt and LAlt for shortcuts in Keyman (Windows) and assign shortcuts to SHIFT + LALT sequences, making available SHIFT + RALT key sequences available for keyboard rules.

**Comment by darcywong00** [comment]
Good news. Parts of this request are already in-work as #340 and available in the 10.0 alphas

**Comment by mcdurdin** [comment]
> Good news. Parts of this request are already in-work as #340 and available in the 10.0 alphas

This is actually incorrect -- wrong platform!

However, this is an important issue. See also #1044.

**Comment by mcdurdin** [comment]
This is a little more challenging than I'd prefer. Currently we use [`RegisterHotkey`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-registerhotkey) to register a hotkey. Amazing that. However, `RegisterHotkey` does not distinguish between left and right modifiers.

This means we'd need to re-implement hotkeys in the low level keyboard hook, which raises the risk of this feature change considerably.

**Comment by mcdurdin** [comment]
Finally, a fix is on its way in #2360!
