### ISSUE TITLE
[windows] can't add a Keyman keyboard to Toolbox under Language Encoding...

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#3655]
**Describe the bug**
There seem to be no way to add a Keyman keyboard to Toolbox using the Language Encoding Properties. Any Keyman keyboard can be manually selected and used in any field [marker], but as expected the keyboard will be switched to its preset default one once jump to a new field [marker].

![image](https://user-images.githubusercontent.com/28331388/95038108-93b91080-06f7-11eb-8b6e-39ca485979d7.png)

**To Reproduce**
1. Go to Project menu in Toolbox.
2. Click on 'Language Encodings...' and add a new language
3. Under 'Options' type in the language name of the keyboard you want to use (i.e. Cheyenne)
4. In Keyboard section, click on the dropdown menu to look for the installed Keyman keyboard (Cheyenne)
5. See issue: not a single Keyman keyboard is found in the list (See the screenshot above)

**Expected behavior**
A list of all installed keyboard should have been shown in the dropdown list.

---

(Delete the irrelevant sections)

**Keyman Desktop:**
 - OS: Windows 10 1909
 - Keyman version: 13.0.112
 - Target Application: Toolbox 1.6.4
   
---
 
**Keyboard**
 - Keyboard name: Cheyenne ([link to this keyboard on Keyman.com](https://keyman.com/keyboards/sil_cheyenne))
 - Keyboard version: 1.1.1
 - Language name: chy-Latn

**Additional context**
When manually switch to the keyboard on \nt field, one can type in Cheyenne without an issue. 
![image](https://user-images.githubusercontent.com/28331388/95038917-800ea980-06f9-11eb-86ea-6e7201ae227a.png)

Related query on the community site: https://community.software.sil.org/t/keyman-13-not-working-with-cheyenne-keyboard/3907/15?u=makara

**Comment by mcdurdin** [comment]
This is a known limitation in Toolbox. The only mitigation is to use hotkeys to switch keyboards. As far as I understand, there are no plans to update Toolbox to allow switching of Windows languages.
