### ISSUE TITLE
feat(linux): Build for arm7 architecture

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#3656]
User from https://community.software.sil.org/t/keyman-launch-pad-code-not-working/3920/3 was unable to install Keyman for Linux on his configuration:

> Im using Ubuntu Mate Release 20.04.1 LTS (Focal Fossa) 32 bit
Kernel Linux 5.4.0-1015-raspi armv7l
Mate 1.24.0

Currently, we're only building for amd64 architecture.

This issue is to see how feasible it would be to build & package for arm7

**Comment by ermshiperete** [comment]
Starting with Keyman 15 the [Launchpad builds](https://launchpad.net/~keymanapp/+archive/ubuntu/keyman-alpha) are now built for additional architectures:

- ARM ARMv8 (arm64)
- ARM ARMv7 Hard Float (armhf)
- Intel x86 (i386)
- PowerPC (powerpc)
- PowerPC64 Little-Endian (ppc64el)
- IBM System z (s390x)

in addition to  AMD x86-64 (amd64).

Debian Testing has Keyman 14 for most architectures Debian supports. See e.g. https://packages.debian.org/bookworm/ibus-keyman.
