### ISSUE TITLE
[windows] Keyman keyboard is not recognized in Lexique Pro

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#3661]
**Describe the bug**
Keyman keyboards installed on Windows are not recognized in Lexique Pro under Tools > Configure > Language > Language Properties > click on a language and then Configure... to open Configure Language and then click on Keyboard tab to see the error. Some Keyman keyboards however are shown under `System language for keyboard input`.

![image](https://user-images.githubusercontent.com/28331388/95151317-8f9ef880-07b4-11eb-8f7c-f62c1263f500.png)

**To Reproduce**
Alternative Steps to reproduce the behavior:
1. Go to 'Lexique Pro'
2. Create a new project
3. Follow the screen and then at "Language Properties" select the language to configure
4. Click on Configure... > Keyboard
5. See error (screenshot above)

**Expected behavior**
All installed Keyman keyboard should be shown under `Keyman Keyboard` section.

---

(Delete the irrelevant sections)

**Keyman Desktop:**
 - OS: Windows 10 Pro 1909
 - Keyman version: 13.0.112
 - Target Application: Lexique Pro 3.6
  
---
 
**Keyboard**
 - Keyboard name: Cheyenne
 - Keyboard version: 1.1.1.
 - Language name: chy-Latn

**Additional context**
https://community.software.sil.org/t/keyman-keyboard-not-staying-active-cant-get-rid-of-extra-keyboard-windows-10/3177/25?u=makara

**Comment by mcdurdin** [comment]
This is a limitation in Lexique Pro; it does not recognise Keyman 8 or later versions (last updated in 2012). The recommended solution is to use a single Keyman keyboard with a Windows language, and then select it in the System Language list rather than the Keyman keyboard list.
