### ISSUE TITLE
Cloudflare CAPTCHA prevents keyboard download

### ISSUE THREAD

**Issue by gabrielwong** [keymanapp/keyman#367]
Occasionally on some networks, Cloudflare serves a CAPTCHA page with a 403 instead of the requested resource. This is treated by Keyman as a network error and the user is not given any indication of the specific error.

**Comment by darcywong00** [comment]
Keyman for Android treats unexpected HTTP statuses (including 403) by notifying the user with *Keyboard download failed*. At this point, I don't see a workaround for CAPTCHA in the "Add New Keyboard" dialogue.

**Comment by mcdurdin** [comment]
Closed because infrastructure changes mean captchas don't really happen on downloads.keyman.com any more.
