### ISSUE TITLE
bug(windows): error sending diagnostic report

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#3673]
**Describe the bug**
After clicking on the "Send" button, the process went through, but then this box popped up:
![image](https://user-images.githubusercontent.com/28331388/95284364-3d2f0c00-0888-11eb-9e81-459abc343402.png)

---

**Keyman Desktop:**
 - OS: Windows 10 Pro 1909 | Windows 10 Pro 2004
 - Keyman version: 13.0.112 | 14.0.154
 - Target Application: [self]
  
**Additional context**
This happens on both my main Windows and my currently installed virtual machine.

**Comment by MakaraSok** [comment]
This issue re-emerges:
![image](https://user-images.githubusercontent.com/28331388/98904018-56605380-24eb-11eb-9ae1-3e43ae24eb3e.png)

Keyman Desktop: 13.0.115.
Windows 10 Pro 1909.

**Comment by mcdurdin** [comment]
Moved new report to #3862.
