### ISSUE TITLE
[Desktop] Data1.cab error when upgrading from 13.0.111.0

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#3676]
A user reported this via email:

> The computer prompted me to update Keyman. When I did it gave me this error message. Retry gave the same result.
![gmgjflcejpbglkeo](https://user-images.githubusercontent.com/7358010/95356802-456f6180-08f1-11eb-9136-fdc80f5dbc90.png)

Windows 10 build 18363.1082
From Keyman Desktop 13.0.111.0

(update)
The user was able to uninstall Keyman, then download and successfully install Keyman 13.0.113.
Feel free to close this if  Data1.cab doesn't pertain to anything...

**Comment by mcdurdin** [comment]
This sounds like a corrupted download.
