### ISSUE TITLE
bug(windows): Can't open "Text Editor", "Configuration", "Help", or "Exit"

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#3679]
Both @MakaraSok and I have installed Keyman Desktop 14.0.154-alpha.
After Keyman is started, we click on the Keyman icon but these options don't respond upon clicking:
* Text Editor
* Configuration
* Help
* Exit

I've been using Task Manager to exit Keyman. Then I can relaunch it

**Comment by mcdurdin** [comment]
This is a regression arising from #3604, where we tried to launch processes as non-elevated. However, it fails if we are already non-elevated. Oops.

**Comment by MakaraSok** [comment]
It probably is worth noting that the configuration can be opened from the Start Menu.
