### ISSUE TITLE
[iOS] CI does not attempt to compile Keyman Engine demo and samples

### ISSUE THREAD

**Issue by gabrielwong** [keymanapp/keyman#369]
`build.sh` builds the Keyman app and Keyman Engine library. There is an additional demo app in the Keyman Engine project that is not built now that the app code is removed form the library. Also the sample apps are not built.

**Comment by jahorton** [comment]
As of #2047, the Keyman sample apps are now built by our CI.  The demo is not compiled yet, though.

**Comment by mcdurdin** [comment]
Good enough for now that the Sample apps are built. I'm not quite sure of the purpose of having a Demo as well as Samples and propose we pull that out of KMEI in the future. Turning this into a separate issue.
