### ISSUE TITLE
bug(web): desktop osk resets to original size after any key press or control focus change

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#3697]
**Describe the bug**
Any resizing of the desktop OSK is lost the first time a key is pressed or control focus changes -- it resets to the original size.

**To Reproduce**
1. Open web/testing/unminified.html in a desktop browser
2. Select Lao Basic, for instance.
3. Drag the bottom right corner of the OSK to resize
4. Click a key or change focus
5. The OSK resets to original size

**Expected behavior**
The OSK should not resize

---

**KeymanWeb:**
 - OS: Windows 10
 - Browser: Chrome
 - KeymanWeb Version: 14.0.157
 - URL: web/testing/unminified.html

**Comment by jahorton** [comment]
In my reproduction attempts, I found I had to be pretty precise in how I interacted with the page to trigger this, _but_ I was able to find one sequence that worked.

Using the listed URL:
1.  Click / focus the text area.
2. Select a keyboard that displays an OSK. 
3. Drag the bottom-right corner of the OSK to resize.
4. Either:
    - Press TAB to change focus to the input field
    - or directly click/focus that input field

If done properly, the OSK should "snap back" to its original sizing.

**However**:  if you instead drop the text area's focus by clicking on inactive parts of the page, _then_ focus on the input field, the newly-selected OSK size will remain at the dimensions selected by step 3.

It only seems to trigger when moving from one (KMW-) "attached" element to another.  There's probably some sort of sequencing issue when both `blur` and `focus` trigger at extremely close points in time, as can result in this scenario.  The actual order of 'blur' vs 'focus' may also be worth examining.
