### ISSUE TITLE
Keyman Engine for Android won't follow http->https redirects when downloading keyboard

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#370]
KMManager.java `FileDownloader` does not follow redirects that change protocol from http to https, per the design of [`HttpURLConnection`](https://developer.android.com/reference/java/net/HttpURLConnection.html).

Even worse, it silently pretends to succeed, storing a zero byte file on disk, rather than showing an error message to the user.

This is compounded then by an attempt to load this zero-byte file in the web view and select the keyboard, giving the end user a completely black keyboard view with no way to select another keyboard layout!

A fix for this wonderful little bug should address all three of these issues -- perhaps in 3 separate PRs.

**Comment by darcywong00** [comment]
TODO:
- [ ] Fix KMManager to follow redirects
- [ ] Display error if zero-byte file stored
- [ ] Prevent loading zero-byte keyboard

**Comment by darcywong00** [comment]
JSONParse.java `getJSONObjectFromUrl` also uses HttpURLConnection so it will need the same refactoring
