### ISSUE TITLE
bug(windows): Keyman deleting multiple code points on Chrome/Modern Edge in TSF mode

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#3704]
**Describe the bug**

Ref https://community.software.sil.org/t/diacritics-in-web-browsers/3949

Using SIL IPA keyboard, typing <kbd>a</kbd> <kbd>shift</kbd>+<kbd>8</kbd> <kbd>shift</kbd>+<kbd>8</kbd> should result in `a̽` (`U+0061 U+033D`) but instead results in `̽̽` (`U+033D U+033D`). This issue arises in Chrome, Modern Edge and Firefox; it does not occur in Notepad, Word or e.g. IE11.

**To Reproduce**
1. Select SIL IPA keyboard
2. In a text field in Chrome, type <kbd>a</kbd> <kbd>shift</kbd>+<kbd>8</kbd> <kbd>shift</kbd>+<kbd>8</kbd> [`a**`]
3. See error

---

**Keyman Desktop, Keyman for macOS, Keyman for Linux:**
 - OS: Windows 10
 - Keyman version: 13.0.113.0
 - Target Application: Chrome 86.0.4240.75, Firefox 81.0.1
   
---
 
**Keyboard**
 - Keyboard name: sil_ipa
 - Keyboard version: 1.7
 - Language name: Any

**Comment by mcdurdin** [comment]
Tested in Firefox 80.0.1, works correctly.
Tested in Chromium 85.0.4183.0, works correctly.
Can verify that this is a regression in Firefox 81.0 and Chromium 86.0. Interesting that they both have exactly the same symptoms. Seems like there must be a related patch to each browser?

**Comment by RebelTat** [comment]
Oop

**Comment by mcdurdin** [comment]
This may be related to #3698, given the regression appeared at the same time for Chrome.

**Comment by mcdurdin** [comment]
See bug report for Firefox at https://bugzilla.mozilla.org/show_bug.cgi?id=1670834

**Comment by mcdurdin** [comment]
See bug report for Chromium at https://bugs.chromium.org/p/chromium/issues/detail?id=1137564

**Comment by mcdurdin** [comment]
Today, I tested with Firefox 80.0.1 and it failed, so I am not sure I tested correctly. Will re-run the regression test.

**Comment by mcdurdin** [comment]
I'm going to split Firefox compatibility into a separate issue; this issue will be used to track the compatibility with Chrome, specifically with insertion of marks.

# Background on Chrome compatibility

I have isolated two separate issues here with TSF compatibility between Keyman and Chrome. Both are exposed once the `TS_SS_TRANSITORY` flag is disabled in `tsf_text_store.cc:TSFTextStore::GetStatus()`.

* Issue 1137267: Backspace stopped working with Keyman. (https://bugs.chromium.org/p/chromium/issues/detail?id=1137267) - Keyman #3698
* Issue 1137564: Certain characters are treated wrongly with TSF for elements in documents. (https://bugs.chromium.org/p/chromium/issues/detail?id=1137564) - Keyman #3704

I am currently testing the situation only without a current selection. The situation when there is a selection is slightly different, but I don't want to dig into that just yet (there is a known difference in how Keyman deals with selections which I am hoping to deal with in the future, but it shouldn't impact Chrome negatively). 

# Address bar vs in-document elements

The address bar behaves differently than elements within a document. Text insertion with Keyman appears to be working correctly (#3704), while Backspace is failing (#3698). Elements within a document have additional issues which I am recording separately.

# Setup

I'm testing on Chromium 88 commit ref 899e736f9bc1916ad2f36182c7bcf2d9f308867e with TS_SS_TRANSITORY flag manually removed in tsf_text_store.cpp (TSFTextStore::GetStatus):

```diff
--- a/ui/base/ime/win/tsf_text_store.cc
+++ b/ui/base/ime/win/tsf_text_store.cc
@@ -251,7 +251,7 @@ HRESULT TSFTextStore::GetStatus(TS_STATUS* status) {
   status->dwDynamicFlags |= TS_SD_INPUTPANEMANUALDISPLAYENABLE;
   // We don't support hidden text.
   // TODO(IME): Remove TS_SS_TRANSITORY to support Korean reconversion
-  status->dwStaticFlags = TS_SS_TRANSITORY | TS_SS_NOHIDDENTEXT;
+  status->dwStaticFlags = /*TS_SS_TRANSITORY |*/ TS_SS_NOHIDDENTEXT;

   return S_OK;
 }
```

**Comment by mcdurdin** [comment]
# Errors with input of combining marks in documents

There appears to be a bug with insertion of characters that combine, such as combining diacritics, or Indic script vowels and marks. A similar issue arises when deleting these marks. These issues arise only with elements within documents, and not the address bar.

This smells like there is some text range normalization pertaining to grapheme clusters going on when it shouldn't be.

These tests are run with a minimal test keyboard `test3704.kmx` which is available for download at _______.

To begin the test, ensure you enter at least one character into the document, e.g <kbd>a</kbd>.

Then, you can type the following keys to show results:
* FAIL: <kbd>5</kbd> emits just `U+0301` (́) but will result in `U+0301 U+0301` **that is, two** in the document.
* PASS: <kbd>6</kbd> emits `U+0061 U+0301` (á) and results in the correct `U+0061 U+0308`.
* PASS: <kbd>7</kbd> emits `U+00E1` (á) and results in the correct `U+00E1`.

I have traced the code path through to `RenderWidgetHostViewAura::InsertText()` (content\browser\renderer_host\render_widget_host_view_aura.cc) and at this point, the text to be inserted always matches what Keyman generates.

    content.dll!content::RenderWidgetHostViewAura::InsertText() Line 1174	C++
    ui_base_ime_win.dll!ui::TSFTextStore::CommitTextAndEndCompositionIfAny(unsigned int old_size, unsigned int new_size) Line 1421	C++

Also verified correct is the number of characters that Keyman asks to delete.

This issue also arises with other scripts, for example Khmer: 
* PASS: <kbd>x</kbd> generates `U+1780`.
* PASS: <kbd>m</kbd> generates `U+1798`.
* PASS: <kbd>r</kbd> generates `U+179A`.
* FAIL: <kbd>j</kbd> generates `U+17D2 U+17D2` (should be only one)
* FAIL: <kbd>E</kbd> generates `U+17C2 U+17C2` (should be only one)

## Unit tests

I added a test to tsf_text_store_unittest to insert just U+0308. This test passes, so the error lies deeper (which debugging suggested was the case):

```diff
--- a/ui/base/ime/win/tsf_text_store_unittest.cc
+++ b/ui/base/ime/win/tsf_text_store_unittest.cc
@@ -1084,6 +1084,12 @@ class InsertTextAtSelectionTestCallback : public TSFTextStoreTestCallback {
     GetSelectionTest(7, 17);
     GetTextTest(0, -1, L"abcedfg0123456789", 17);

+    const wchar_t kBufferO[] = L"̈"; // beware, there is a character lurking there.
+    SetInternalState(L"a", 0, 1, 1);
+    InsertTextAtSelectionTest(kBufferO, 1, 1, 2, 1, 1, 2);
+    GetSelectionTest(1, 2);
+    GetTextTest(0, -1, L"ä", 2);
+
     return S_OK;
   }
```

## Why not work with an empty text store?

For legacy reasons, because it is difficult to know if an app has full context support when there is empty context (although worth investigating further -- see comment in `CKMTipTextService::OnSetFocus` for pathways here), Keyman falls back to injecting characters by transient mode in an empty document, just for the first keystroke.

**Comment by mcdurdin** [comment]
(Please don't shoot me -- I put the wrong first letter in the Khmer word -- should have been U+1781, not U+1780. khmer not kmer! It doesn't change the results of the test.

**Comment by ermshiperete** [comment]
> PASS: 6 emits U+0061 U+0301 (á) and results in the correct U+0061 U+0308

@mcdurdin Is this a typo, or does emitting U+0061 U+0301 really result in U+0061 U+0308 ?

**Comment by mcdurdin** [comment]
> Is this a typo

Yes. Corrected, thanks for picking that up.

**Comment by mcdurdin** [comment]
I'm going to go ahead and close this as resolved, because Chromium team reverted the full support for TSF patch.
