### ISSUE TITLE
bug(windows): TSF integration with Firefox has a number of issues

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#3710]
This is the master tracking issue for #889, #1107, #1131, #2587. 

See also #3704, which is now only Chrome-related.

I will be consolidating all content from the above issues here and closing them as duplicates.

**Comment by mcdurdin** [comment]
Investigation today. I have been tracking the `kmtip::DeleteLeftOfSelection` function with Firefox and note that it is deleting more than is asked. Given the following:

```
TextStore: ab̈    U+0061 U+0062 U+0308
Key event: U+0308 + '3' > nul
Expected: ab   U+0061 U+0062 
Actual: a     U+0061
```

Logging has shown that `ShiftStart` is shifting a single code point, and `GetText` on the range returns just the single codepoint that is expected. Reading the text store again shows the correct content, during the edit session. At the end of the edit session, however, the text is transformed incorrectly, and the diacritic and the base are both deleted.

I need to investigate what is happening in Firefox next.

**Comment by mcdurdin** [comment]
Firefox bug ref: https://bugzilla.mozilla.org/show_bug.cgi?id=1670834#5 describes the issue and potential resolution.

**Comment by mcdurdin** [comment]
From #889:

> For example, with khmer_angkor keyboard, typing xjmEr gives ខ្មែរ and five backspaces should delete it all. But in Firefox, only 3 backspaces deletes it all, and not in the expected groupings either:
> 
> Start with ខ្មែរ.
> Bksp: ខ្មែ
> Bksp: ខ្
> Bksp: empty string
> 

Verified fixed with the Firefox patch above.

**Comment by mcdurdin** [comment]
From #1107:

> The keystrokes `amlam` results in the following
> 
> ### Chrome, Notepad (correct)
> | Keystroke    | Output character stream                                  |
> | ------------- | --------------------------------------------------|
> | a                  | U+0D05                                                            |
> | m                 | U+0D05 U+0D02                                             |
> | l                   | U+0D05 U+0D2E U+0D4D U+0D32 U+0D4D |
> | a                  | U+0D05 U+0D2E U+0D4D U+0D32                |
> | m                 | U+0D05 U+0D2E U+0D4D U+0D32 U+0D02 |
> 
> ### Firefox (incorrect)
> | Keystroke    | Output character stream                                  |
> | ------------- | --------------------------------------------------|
> | a                  | U+0D05                                                            |
> | m                 | U+0D05 U+0D02                                             |
> | l                   | U+0D2E U+0D4D U+0D32 U+0D4D               |
> | a                  | U+0D2E U+0D4D U+0D32                              |
> | m                 | U+0D2E U+0D4D U+0D32 U+0D02               |
> 

Verified fixed with the Firefox patch above.

**Comment by mcdurdin** [comment]
From #2587:
> **Expected behavior**
> <table>
> <thead><tr><th>Test</th><th>MS Office</th><th>Chrome</th><th>LibreOffice</th><th>Firefox</th></tr></thead><tbody>
>  <tr><td>mu</td><td>मु</td><td>मु</td><td>मु</td><td style="color: red;">ु</td></tr>
>  <tr><td>kh</td><td>ख्</td><td>ख्</td><td>ख्</td><td>ख्</td></tr>
>  <tr><td>ti</td><td>ति</td><td>ति</td><td>ति</td><td>ि</td></tr>
> </tbody></table>
> 

Verified fixed with the Firefox patch above.

**Comment by darcywong00** [comment]
It sounds like one of our users is experiencing this issue in FireFox 83.0 (64-bit) with Burmese keyboards
I sent him the link to [control_firefox_tsf](https://help.keyman.com/knowledge-base/100) and waiting to hear if that fixes it.

**Comment by mcdurdin** [comment]
@MakaraSok can you re-test these reports in Firefox 86.0 and Keyman 14.0 latest beta? I believe that they are all fixed now. Make sure that you have not disabled TSF integration.

**Comment by MakaraSok** [comment]
@mcdurdin Confirm that the it is fixed in Firefox 86.0 with Keyman 14.0.247-beta running on Windows 10 Pro 20H2 x64.

![image](https://user-images.githubusercontent.com/28331388/109272458-779f4280-7843-11eb-9919-a306ed3644db.png)

**Comment by MakaraSok** [comment]
TODO
Retest:
- [ ] https://github.com/keymanapp/keyman/issues/1107
- [ ] https://github.com/keymanapp/keyman/issues/889

**Comment by MakaraSok** [comment]
Mozhi Malayalam and Khmer Angkor work as expected on FirFox.

**Comment by mcdurdin** [comment]
Closing as fixed!

**Comment by mcdurdin** [comment]
Tracking a reported for integration with Bloom (uses Firefox internally). https://community.software.sil.org/t/keyman-15-0-272-and-bloom-5-x-deleting-too-much/6906

---

Workaround steps:

https://user-images.githubusercontent.com/4498365/202543310-1208beb7-0448-4821-827d-92e82c6b2c51.mp4
