### ISSUE TITLE
bug(linux): add ibus-keyman dependency (?)

### ISSUE THREAD

**Issue by rik-shaw** [keymanapp/keyman#3711]
Installing "keyman" in Ubuntu / Wasta-Linux 20.04 focal did not automatically install `ibus-keyman`, and without that, Keyman keyboards were not added to the user input method list (Ubuntu/Gnome, Cinnamon, XFCE interfaces). Either `keyman` or `python3-keyman-config` should have `ibus-keyman` listed in their `debian/control` file as a "Depends:" (?)

**Keyman for Linux:**
 - OS: Ubuntu / Wasta-Linux 20.04
 - Keyman version: 11.0.103-2

**Comment by mcdurdin** [comment]
Thanks for the report. @ermshiperete will be able to look at this when he comes back on board in about a month.

**Comment by darcywong00** [comment]
See #2705 
I believe if you add the Keyman ppa and install Keyman 13 it will work.

**Comment by mcdurdin** [comment]
> I believe if you add the Keyman ppa and install Keyman 13 it will work.

This is needed because the version distributed via Ubuntu's repos is 11.0? Is that right? We should be trying to move away from using a ppa for distribution -- it's unnecessary friction for end users.

**Comment by darcywong00** [comment]
> This is needed because the version distributed via Ubuntu's repos is 11.0? Is that right?

It's because @glasseyes as a Debian contributor could get the latest Keyman 11 (at the time) into Debian and we don't have anyone who can update it to Keyman 13.

**Comment by mcdurdin** [comment]
Yep, looking forward to signing @ermshiperete up as a Debian contributor!

**Comment by ermshiperete** [comment]
Fixed in version 14. The problem that no current version is available in the official Debian/Ubuntu repos is tracked in #3869.
