### ISSUE TITLE
bug(windows): the keyboard list disappears after installing several keyboards 

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#3725]
**Describe the bug**
Several keyboard got installed, but then when you click on the Keyman icon on the taskbar none of those are shown in the keyboard list on the left panel.

![image](https://user-images.githubusercontent.com/28331388/96537641-f77b3600-12c0-11eb-8488-9a290c9a6335.png)

**To Reproduce**
1. Download several keyboards from keyman.com
2. Install them one by one
3. Click on the Keyman icon

**Expected behavior**
All newly installed keyboards should be shown together with the existing ones.

**Keyman Desktop:**
 - OS: Windows 10 Pro 2004
 - Keyman version: 14.0.163-alpha
 - Target Application: [self]
  
---
 
**Keyboard**
 - Keyboard name: [any]
 - Keyboard version: N/A
 - Language name: N/A

**Comment by MakaraSok** [comment]
The app seems to take a while to load all those newly installed keyboard to the list. Now when I tried and uninstalled all keyboards in an attempt to uninstall Keyman Desktop, the keyboard list still shows the uninstalled keyboards.

The screenshot shows the keyboard list when clicking on the Keyman icon on taskbar and the empty keyboard list in the Keyboard Layout under Configuration.
![image](https://user-images.githubusercontent.com/28331388/96538898-e1bb4000-12c3-11eb-86e3-ee9a69fca0d4.png)

**Comment by MakaraSok** [comment]
14.0.176-alpha

![image](https://user-images.githubusercontent.com/28331388/98346456-91283e80-2048-11eb-8a53-ef6e108da35a.png)

**Comment by MakaraSok** [comment]
and the hotkey keyboard list:

![image](https://user-images.githubusercontent.com/28331388/98346734-f714c600-2048-11eb-8226-d5841667228f.png)

**Comment by mcdurdin** [comment]
I am trying to trace this. Do you think it happens because of an upgrade of Keyman? Can you find exact steps to reproduce the problem?

**Comment by MakaraSok** [comment]
The last diagnostic report I sent may have something in there. The steps
are usual. Some ten keyboards were installed and then some more ten, after
that this behavior re-surfaced.

**Comment by mcdurdin** [comment]
I'm still having trouble reproducing this issue 😢

**Comment by MakaraSok** [comment]
Tested with 14.0.224-beta. The issue is no longer there to be found.
