### ISSUE TITLE
bug(linux): keyman onboard requires old version of python?

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#3737]
per https://community.software.sil.org/t/ubuntu-groovy-support-for-keyman-particularly-onboard/3980/2

> keyman onboard requires a lower version of python hence does not work in groovy.

**Comment by darcywong00** [comment]
Also need to check if any updates are needed for
https://github.com/keymanapp/onboard-keyman

**Comment by ermshiperete** [comment]
Groovy supported was added for version 14.
