### ISSUE TITLE
Wrong Gilaki language layout

### ISSUE THREAD

**Issue by LordArma** [keymanapp/keyman#3748]
Gilaki layout in all versions are completely wrong. It should be something like this:
https://github.com/simple-keyboard/simple-keyboard-layouts/blob/master/src/lib/layouts/gilaki.js

Correct Gilaki layout is also available in Gboard.

You can test correct Gilaki keyboard here:
http://gilakikeyboard.ir/web

Please correct Gilaki in your great project so millions Gilaks in the world can use it.

Thank you 🙏🏻

**Comment by mcdurdin** [comment]
Thank you for your feedback. You can create a Gilaki keyboard layout for Keyman using Keyman Developer, downloadable from https://keyman.com/developer, and then share it with us to publish on our website.

**Comment by LordArma** [comment]
> Thank you for your feedback. You can create a Gilaki keyboard layout for Keyman using Keyman Developer, downloadable from https://keyman.com/developer, and then share it with us to publish on our website.

Hey. I did it. How can I share it with you?

**Comment by LornaSIL** [comment]
You can either go through the steps of submitting a GitHub Pull Request (directions found here: https://help.keyman.com/developer/keyboards/starter/step-5), or, if that is too daunting, we could discuss your emailing the zip to me. My preference is you try doing a GitHub Pull Request.

**Comment by LordArma** [comment]
> You can either go through the steps of submitting a GitHub Pull Request (directions found here: https://help.keyman.com/developer/keyboards/starter/step-5), or, if that is too daunting, we could discuss your emailing the zip to me. My preference is you try doing a GitHub Pull Request.

Thank you. I did it here:
https://github.com/keymanapp/keyboards/pull/1383#issuecomment-723665194
