### ISSUE TITLE
bug(windows): Config allows you to install more than 4 transient profiles, but they silently fail to install

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#3749]
**Describe the bug**
Amharic, Sgaw Karen, Hieroglypic, Tibetan and Euro-Latin do not appear in the keyboard list when the Keyman icon on the taskbar is triggered nor the Hotkeys keyboard list. They are all shown in the keyboard list in the Configuration though.

![image](https://user-images.githubusercontent.com/28331388/97128077-f8531280-176d-11eb-925c-d53b8bea663f.png)

**To Reproduce**
1. Install several keyboards and then install the following:
    - https://keyman.com/amharic/
    - https://keyman.com/keyboards/sil_sgaw_karen
    - https://keyman.com/keyboards/hieroglyphic
    - https://keyman.com/tibetan/
    - https://keyman.com/eurolatin/

2. Click on 'Keyman Icon' on the taskbar
3. See error

**Expected behavior**
All installed keyboards should be shown in the keyboard list when the Keyman icon is clicked on.

---

(Delete the irrelevant sections)

**Keyman Desktop:**
 - OS: Windows 10 Pro 2004
 - Keyman version: 14.0.168-alpha
 - Target Application: [self]

**Additional context**
Diagnostic report sent. The case # is 4000.

**Comment by MakaraSok** [comment]
These keyboards ain't visible in the language switcher either.

![image](https://user-images.githubusercontent.com/28331388/97130012-d6a85a00-1772-11eb-9b57-f64b4770758a.png)

**Comment by mcdurdin** [comment]
Possibly related to #3725.

**Comment by mcdurdin** [comment]
Makara's diagnostic report:

[tkdBE57.zip](https://github.com/keymanapp/keyman/files/5437637/tkdBE57.zip)

**Comment by mcdurdin** [comment]
This happens because there are already the maximum of 4 transient language profiles installed. We need to be checking that we haven't hit the maximum number of transient profiles before we attempt to install another profile.
