### ISSUE TITLE
bug(windows): question mark in title bar of Keyboard Search is supposed to do something

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#3755]
**Describe the bug**
There is a question mark next to the `X` on the `Download Keyboard From keyman.com`.

![image](https://user-images.githubusercontent.com/28331388/97140327-ea61b980-178e-11eb-8577-c015d2627af8.png)

**To Reproduce**
1. Go to 'Configuration'
2. Click on 'Download keyboard...'
3. Next to the `X` on the panel, click on the `?`

**Expected behavior**
The mouse pointer changes to be a pointer with a question mark when triggered using the steps above. it does not seem to do anything helpful.

---

**Keyman Desktop:**
 - OS: Windows 10 Pro 2004
 - Keyman version: 14.0.168-alpha
 - Target Application: [self]

**Comment by mcdurdin** [comment]
Suggested resolution: disable the question mark button 😉
