### ISSUE TITLE
bug(windows): unable to type into the input field for email subscription

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#3757]
**Describe the bug**
I was not able to type in the input field for `email address`.

**To Reproduce**
1. Go to 'Keep in Touch' in the 'Configuration'
2. Click in the 'input field' next to `Keyman Mailing List`
3. Start typing

**Expected behavior**
The input field should be type-able.

---

**Keyman Desktop:**
 - OS: Windows 10 Pro 1909
 - Keyman version: 13.0.114
 - Target Application: [self]

**Comment by mcdurdin** [comment]
I believe this is correct in 14.0. Can you verify?

**Comment by MakaraSok** [comment]
14.0 is OK with this.

**Comment by mcdurdin** [comment]
Okay, closing as resolved.
