### ISSUE TITLE
enhancement(windows): Warn user when attempting to install more than 4 transient profiles

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#3759]
On Windows, we are limited to 4 transient profiles (codes 2000, 2400, 2800 and 2C00). Currently, Keyman silently appears to succeed when attempting to install a fifth. This is misleading!

---

@MakaraSok's original report:

For some unknown reason on `Keyman Desktop 14.0.168-alpha`, the keyboard list does not scroll any longer--as a result some keyboards are in the list. The ones missing their corresponding in the keyboard list are highlighted. This happens after a restart.

![image](https://user-images.githubusercontent.com/28331388/97141394-39a8e980-1791-11eb-993d-7a9fbca8ba7f.png)

_Originally posted by @MakaraSok in https://github.com/keymanapp/keyman/issues/1843#issuecomment-716341461_

**Comment by darcywong00** [comment]
> On Windows, we are limited to 4 transient profiles (codes 2000, 2400, 2800 and 2C00).

Does that limit apply to all Windows versions? (e.g. 7, 8, 10)

**Comment by mcdurdin** [comment]
> Does that limit apply to all Windows versions? (e.g. 7, 8, 10)

Windows 8 and 10 as far as I know. Windows 7 does not support transient profiles.
