### ISSUE TITLE
bug(windows); 14.0.169-alpha won't install

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#3775]
`14.0.169-alpha` won't get installed with the following message:
![image](https://user-images.githubusercontent.com/28331388/97264118-e4cfa680-1856-11eb-84cc-a077ffdc2348.png)

_Originally posted by @MakaraSok in https://github.com/keymanapp/keyman/issues/3636#issuecomment-717012475_

**Comment by mcdurdin** [comment]
Can you give me some more detail on what you were installing and the steps you took to install? Can you reproduce the problem? That looks like it was more than just the Keyman installer was running, because kmp.inf will be in a package.

**Comment by MakaraSok** [comment]
I've removed `14.0.168` and once it's removed, I went ahead and installed the `14.0.169` without restarting. Only then that I restarted the machine, even so it won't install.

**Comment by mcdurdin** [comment]
This is due to a bug in reading older package files -- the kmp.inf file was being extracted to a temp folder, but wrongly. Patch on the way.
