### ISSUE TITLE
[developer] remove/replace the old .kvk with .kvks

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#3776]
**Is your feature request related to a problem? Please describe.**
An older version of Developer uses `.kvk`, while a newer one `.kvks`. When removing the `.kvk` from the keyboard project, the file itself in the directory was not removed. Would it be possible that the Developer removes the file in the directory once it is removed from the list in feature? Also, it would be helpful as well to have a warning message to let the user know what is about to happen or a reminder to prompt the user to remove the file from the directory manually.

**Describe the solution you'd like**
The file (`.kvk`) in the directory is removed once one clicks to remove it from the Developer. A warning message tells the user that "The .kvk will be removed permanently from the directory."

**Describe alternatives you've considered**
If the file cannot be removed automatically from the directory, a warning message should be given to notify the user what should be done to get rid of the `.kvk` and the `.kvks` should be used instead.

**Product context**
 - OS: Windows Pro 10 1909
 - Developer: 13.0.114

**Comment by MakaraSok** [comment]
The same practice should be applied to `.js` and `.ico`.

**Comment by mcdurdin** [comment]
I think we will leave this maintenance work to the keyboard author; it is dangerous for a tool to automatically remove files that it 'thinks' are no longer needed 😁
