### ISSUE TITLE
bug(developer): repeated `begin` or `group` lines should result in an error during compile

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#3784]
**Describe the bug**
In the code view of Layout tab, the code block below exists more than one time in different places in the layout, yet the compiler compiler compile successfully without giving a warning.

```
begin Unicode > use(main)

group(main) using keys
```

**To Reproduce**
1. Go to a keyboard project and open it in 'Keyman Developer'
2. Click on 'Layout ' tab
3. Now copy the code block above and place it in more than places in the code view
4. Compile the keyboard and test
5. See error: the keyboard would output the underlying character instead of what's being defined in the Layout.

**Expected behavior**
A warning message or error message should be given at compile time that something is off. :)

---

**Keyman Desktop:**
 - OS: Windows 10 1909
 - Keyman version: 13.0.114.0
 - Target Application: Keyman Developer 13.0.114.0
  
---
 
**Keyboard**
 - Keyboard name: WCham Unicode
 - Keyboard version: 1.1

**Comment by mcdurdin** [comment]
Duplicate `group(x)` fixed in #6463, released in Keyman version 15.0.227-beta.
