### ISSUE TITLE
The Labels of the Function Keys are partly invisible

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#382]
![screenshot 2017-10-24 11 13 30](https://user-images.githubusercontent.com/28331388/31927187-16cea426-b8bd-11e7-8124-5cd59360d883.png)

![screenshot 2017-10-24 13 18 19](https://user-images.githubusercontent.com/28331388/31927456-4e660888-b8be-11e7-99f6-b4d454fe36db.png)

As shown in the screenshots here, the labels read '១២៣' 'កខគ' and '᧠᧡᧢'​ are too big and a part of them is missing/cropped off. Also their keycap should look the same as that of the other function keys.

Note that the screenshot is taken from the emulator in Chrome (Version 62.0.3202.62).

**Comment by jahorton** [comment]
The base styling is now correct - the special keys have the correct coloration - but the key text is still an issue.

**Comment by jahorton** [comment]
Further investigation shows that the scaling issue may be harder, or at least more tedious, to correct.  Key text is set at numerous places within the OSK's code base, and to fix each case would require inclusion of style adjustment code there.

It'd definitely be simpler to implement after a proper refactor of the OSK; my investigation shows that construction of OSK keys involves a fair bit of duplicated code that should be centralized.
