### ISSUE TITLE
bug(web): Press a "blank" key causes fatal error

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#3820]
**Describe the bug**
When pressing a blank key, 

- Keyman crashes on Android: 
![image](https://user-images.githubusercontent.com/28331388/98089392-3d392080-1eb5-11eb-8395-5f9832b735ab.png)

- the next few key presses won't output anything on Chrome emulator, the keys instead got somehow highlighted as shown below.
![image](https://user-images.githubusercontent.com/28331388/98089662-a456d500-1eb5-11eb-9662-11978142976b.png)

**To Reproduce**
1. Install this keyboard
[khmer_advanced_updated1.zip](https://github.com/keymanapp/keyman/files/5486619/khmer_advanced_updated1.zip)

2. then try press the blank keyboard on Shift layer
3. See error

**Expected behavior**
The blank keys should do nothing when pressed on, shouldn't they?

---

**Android:**
 - Device: Pixel 2 API 29
 - OS: Android 10
 - Keyman version: 13.0.6220
 - Target application: [Keyman]
 
**Keyman Developer:**
 - OS: Windows 10 1909
 - Keyman Developer version: 13.0.115
 
---
 
**Keyboard**
 - Keyboard name: Khmer Advanced keyboard
 - Keyboard version: 1.0
 - Language name: Khmer

---

**Additional context**
The keyboard project: https://github.com/MakaraSok/keyboards/tree/divination_lore

**Comment by mcdurdin** [comment]
Guessing the following report is related:

https://sentry.keyman.com/organizations/keyman/issues/56/events/a3b4e22f0b01433cadc531832dcb2d3b/?project=7&query=is%3Aunresolved

```
cm_lineNumber | 230
-- | --
keyboardName | Khmer Advanced
cm_sourceID | file:///data/user/0/com.tavultesoft.kmapro/app_data/keyman.js
cm_message | Uncaught TypeError: Cannot read property 'substr' of null
keyboardType | INAPP
keyboardID | khmer_advanced
packageID | khmer_advanced
keyboardVersion | 1
```

**Comment by jahorton** [comment]
Good connection, @mcdurdin.  I get a local repro of that exact error when testing locally, although I can extract more info that than from the Chrome debugger.
