### ISSUE TITLE
[windows] Ctrl stays ON when Pressing a key with "AltGr" or "AltGr+Shift"

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#383]
When typing a character while press and hold on AltGr, the Ctrl stays ON. Without pressing any other key while press and hold on the AltGr, the Ctrl won't stay ON.
![ralt on khmer angkor](https://user-images.githubusercontent.com/28331388/31927705-672823f0-b8bf-11e7-86d2-f32cdeb1f624.PNG)
This screenshot shows up as empty when AltGr is pressed. It should show characters which are supposed to be on this layer. This happens when testing Khmer Angkor keyboard PR #94 on Keyman Desktop version 10.0.961.0.

**Comment by mcdurdin** [comment]
This issue arises when the modifier key is released before the final key, e.g. `[RAlt-Down][D-Down][RAlt-Up][D-Up]`. Repro with 10.0.1030.0.

**Comment by mcdurdin** [comment]
I cannot reproduce this issue any longer with 10.0.1081.0. Please reopen this issue if you manage to reproduce it, @MakaraSok
