### ISSUE TITLE
bug(windows): Alt+Shift+Key hotkey is triggered on Shift+Key

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#3852]
**Describe the bug**
The following issues fluctuate the natural flow of typing.
- "[left] Shift + k" behaves like "[left] Shift + [left] Alt + k" as it triggers the OSK instead of output the capital character k. To produce capital k, one has to type right Shift + k.
- "[left] Shift + m" behaves like "Shift + Alt + m" as it triggers the keyboard menu from the task bar instead of output the capital character m. To produce capital m, one has to type right Shift + m.
- "[left] Shift + o" does not output anything when Keyman is active. To produce capital o, one has to type right Shift + o.

---

**Keyman Desktop:**
 - OS: Windows 10 Pro 1909
 - Keyman version: 13.0.115
 - Target Application: [Windows wide]

---

**Additional Context:**

Diagnostic report: [hotkeys misbehave.zip](https://github.com/keymanapp/keyman/files/5529358/hotkeys.misbehave.zip)

Related bug: https://github.com/keymanapp/keyman/issues/927

**Comment by mcdurdin** [comment]
Can you capture a debug log for this issue please? Maybe press Left Shift+A, Left Shift+O, Right Shift K to show the differences.

**Comment by mcdurdin** [comment]
This will probably not be traceable without a [debug log](https://help.keyman.com/kb/40).

**Comment by mcdurdin** [comment]
Can you reproduce this? I will close this issue; please reopen if you have a repro.
