### ISSUE TITLE
chore(common): package version maintenance adjustments

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#3872]
As noted during work on #3836, the kmlmc build needed for Developer's unit tests (during a Windows/Developer build) is triggering a version change within our `node`-based packages that cause later sub-builds (which rely on the original version value) to fail.

From the TC build logs:

```
[14:39:20]
[Step 3/6] > @keymanapp/models-templates@14.0.178 build C:\BuildAgent\work\7ac43416c45637e9\keyman\common\models\templates
[14:39:20]
[Step 3/6] > tsc
[14:39:20]
[Step 3/6] 
[14:39:24]
[Step 3/6] lerna success Bootstrapped 13 packages
[14:39:25]
[Step 3/6] v14.0.178-alpha
[14:39:26]
[Step 3/6] 
[14:39:26]
[Step 3/6] > @keymanapp/lexical-model-compiler@14.0.178-alpha build C:\BuildAgent\work\7ac43416c45637e9\keyman\developer\js
[14:39:26]
[Step 3/6] > tsc
[14:39:26]
[Step 3/6] 
[14:39:32]
[Step 3/6] Typescript compilation successful.
[14:39:33]
[Step 3/6] 
[14:39:33]
[Step 3/6] > @keymanapp/lexical-model-compiler@14.0.178-alpha test C:\BuildAgent\work\7ac43416c45637e9\keyman\developer\js
[14:39:33]
[Step 3/6] > mocha
```

I've traced that section of the logs to this part of the build script:  https://github.com/keymanapp/keyman/blob/af2e4b1b6e489a14ea8baafd6bb6f2b04272d47f/developer/js/build.sh#L130-L143

So, it appears that Developer's build is setting `$publish_version`, so when running the unit-testing Makefile it's incidentally altering the package.json `version` entry that causes the break during later sub-builds.

_Originally posted by @jahorton in https://github.com/keymanapp/keyman/issues/3836#issuecomment-727803184_

As noted during team discussions, we should (ideally) rectify this detail by having the committed version of our packages always using tagged versions, instead of having the tier / environment tags only applied during builds.  Applying the tier automatically shouldn't pose any issue, though there likely would be a bit of work required to ensure local development builds aren't adversely affected or dual-tagged (like `-alpha-local`)... unless, of course, we're fine with potential dual-tagging.

**Comment by mcdurdin** [comment]
Disabling step 9 "Publish Developer NPM modules" of Keyman Desktop/Developer CI build (-publish-to-npm) until we get this resolved.

**Comment by mcdurdin** [comment]
@jahorton wrote:

> I'm just guessing here, but since we're bothering to rebuild @keymanapp/developers /lexical-model-compiler from scratch here, we could probably just git restore * at the repo root at the start of the step.
I'm pretty sure the build script is configured to automatically update the version number during that specific build when run within our CI processes.  If this assumption holds, that should be 'enough'.

**Comment by mcdurdin** [comment]
I've added a temporary patch to step 9 of the CI build script but we should presumably revisit this to clean that up.

**Comment by jahorton** [comment]
I advise cross-referencing with https://github.com/keymanapp/keyman/pull/4291, which made some changes that should simplify whatever the needed approach is.  At the very least, the original underlying issue (different versions among the npm packages during Developer builds) is no more.

**Comment by mcdurdin** [comment]
Yeah, at this point I've got no idea what we need to do here. Things seem to be working smoothly in general, so I'm hesitant to barge in and make changes!

**Comment by jahorton** [comment]
> Yeah, at this point I've got no idea what we need to do here. Things seem to be working smoothly in general, so I'm hesitant to barge in and make changes!

> Disabling step 9 "Publish Developer NPM modules" of Keyman Desktop/Developer CI build (-publish-to-npm) until we get this resolved.

> I've added a temporary patch to step 9 of the CI build script but we should presumably revisit this to clean that up.

I'd want to revisit these points and run a test build - can we re-enable and/or restore the original version of the corresponding step in our build scripts without issue?

**Comment by mcdurdin** [comment]
See also https://github.com/keymanapp/keyman/pull/6074 for other possible interactions

**Comment by darcywong00** [comment]
Package versions should be fixed by now
