### ISSUE TITLE
bug(mac): Keyman keyboards should not be kept in user's Documents folder

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#3883]
**Describe the bug**
Currently, Keyman for Mac stores keyboards in `~/Documents/Keyman-keyboards`, which is a terrible place to keep them. They should be kept in another location under `~` (please research appropriate location). The upgrade process would need to move the keyboards from the `~/Documents` location.

---

**Keyman for macOS:**
 - OS: macOS Catalina
 - Keyman version: 13.0

**Comment by SabineSIL** [comment]
We decided to close in Bug triage meeting

**Comment by mcdurdin** [comment]
Tracking in #2542.
