### ISSUE TITLE
bug(android/app): rapid UI usage can break keyboard installation

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#3895]
**Describe the bug**
The current UI flow for installing a keyboard is not fully robust.  If a user unexpectedly uses available UI before the package installer displays, package installations can break.

**To Reproduce**
1. Settings > Install Keyboard or Dictionary > Install from Keyman.com...
2. Search for a resource of your choice, but don't select the download/"Install" button.
3. Select that button, and when the UI reverts back to the main screen, **quickly** activate the globe menu on the keyboard.  (For best results, only use a single keypress attempt.)
  - In my tests while emulating via Android Studio, there's a 1 to 2 second window where this is possible; plenty of time for an impatient user (like myself) to think control has been returned to me.
4. From this point, the UX experience may diverge a bit depending on your timing.
  - With good timing, you may reach the following state:

![Screen Shot 2020-11-19 at 9 06 26 AM](https://user-images.githubusercontent.com/25213402/99611606-9624bf00-2a46-11eb-972d-a7a089bc2cde.png)

  - With less optimal timing, I've also seen the package installer exit instantly.
5. Assuming you have an active keyboard-selection menu, simply back out of it.
6. Attempt to install the resource you previously searched for.

Unfortunately, I can't get this part to reproduce consistently, but I have seen a case when doing this with `sil_cameroon_qwerty` (search string:  `Cameroon`, then selecting the language "Pinyin") where the keyboard installation completely failed... except for actually adding an entry to the keyboard menu.  Which naturally instantly fatal-errored any time you selected it, as the keyboard's files never installed.

**Expected behavior**
My personal expectation:
- I would not expect to be able to actually type or to use the globe key in this scenario; input should probably be disabled.
- I would expect better stability during the installation process.
    - In particular, if the files for a keyboard or lexical model fail to install, I do **not** expect to see a menu / settings entry for the resource!

**Screenshots**
See above.

---

**Android:**
 - Device: Nexus 10 API 27 (emulated via Android Studio)
 - Current alpha:  around 14.0.183
 - Target application: in-app

**Other notes**
There's a chance this should be two separate bugs:
1.  Ability to use keyboard during that brief moment that the UI reverts to the main screen / globe menu display over the package installer.
2.  The fact that a resource that failed to install (file-copy failed) was still given an entry in the keyboard menu.  Which naturally proceeded to cause "fatal error"s every time I attempted to select it.

**Comment by jahorton** [comment]
Did that PR fix the issue linked by @keyman-sentry later?

**Comment by darcywong00** [comment]
> Did that PR fix the issue linked by @keyman-sentry layer?

Yes, in commit https://github.com/keymanapp/keyman/pull/4088/commits/26b08bba655d897fdd3e465a89c26d0f19fd10ef on that PR
