### ISSUE TITLE
bug(linux): 'onboard' on-screen keyboard doesn't seem to work in Bionic

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/keyman#3901]

**Comment by ermshiperete** [comment]
This turns out to be a user error. The user has to install the keyman-specific `onboard` package. This will work with Keyman. If the user installs the package version from the official repos it won't work.

We have to provide keyman-specific `onboard` packages on all platforms we support.

**Comment by ermshiperete** [comment]
See also https://github.com/keymanapp/keyman/issues/3966

**Comment by mcdurdin** [comment]
Is there a discussion somewhere else where this was discovered?
