### ISSUE TITLE
bug(web): Why does dark mode only toggle on .phone.ios in kmweb.css?

### ISSUE THREAD

**Issue by MattGyverLee** [keymanapp/keyman#3928]
I have some keys with a gradient, and wanted to fade from the default key color (near-white or near-black) to green. I've always thought it was odd that .phone on iOS showed dark mode, but .tablet on iOS didn't.
https://github.com/keymanapp/keyman/blob/ad7a612b4283b3a96d4770a6eeb9ce1dcd6100c2/web/source/resources/osk/kmwosk.css#L65-L73

Unless there is a reason that iPads shouldn't support dark mode, this seems like it is over-specified, and should be simply .ios. 

FYI, if you want to test light and dark modes on iOS in Keyman Developer, Chrome and the iOS keyboard (well, iPhone only until this change is made) follow the Windows System-wide Dark or Light mode setting.

Since the default Android styling is a middle-grey and you don't have a dark-mode flag, I'm guessing that older versions  of Android didn't support the @media (prefers-color-scheme: dark) flag, though new ones do. Is this correct?

## Dark iPad keyboard (after tweaking styles)
![image](https://user-images.githubusercontent.com/986339/99962842-29385e80-2d91-11eb-956a-86e018b2fa2b.png)
## Light iPad keyboard:
![image](https://user-images.githubusercontent.com/986339/99962935-4c630e00-2d91-11eb-8020-a4a6e63c8895.png)

**Comment by jahorton** [comment]
We do have CSS for the tablet form-factor:

https://github.com/keymanapp/keyman/blob/ad7a612b4283b3a96d4770a6eeb9ce1dcd6100c2/web/source/resources/osk/kmwosk.css#L191-L199

(Same commit and file as your link in the description)

Are you saying that dark-mode styling is not being applied properly on an iOS device set to dark mode?

**Comment by jahorton** [comment]
> Since the default Android styling is a middle-grey and you don't have a dark-mode flag, I'm guessing that older versions of Android didn't support the @media (prefers-color-scheme: dark) flag, though new ones do. Is this correct?

About that CSS bit:  https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

Noting the 'supported versions' table:
- Safari 12.1 was released March 25, 2019.
- iOS 13 was released September 19, 2019.
- Chrome / Chrome for Android 76 was released July 30th, 2019.

Basically, it's relatively new, with support for this CSS marker being less than two years old.

We haven't really made any sort of pass toward supporting a dark mode on Android devices, so far as I'm aware of.  iOS nearly forced our hand, though, when we first started compiling Keyman against iOS 13 early during development of our version 13.  While it wasn't _strictly_ necessary, we were able to make dark-mode styling work for us then; I remember doing that work personally about a year ago.  (See https://github.com/keymanapp/keyman/pull/2468)

As for the Android app... as far as I can recall, it's simply always used that styling.  We could look to add support for Android dark mode as a new feature in later Keyman versions if desired, though.

**Comment by MattGyverLee** [comment]
Yes, @jahorton , you are correct, and I am mistaken. All is well. No bugs to see here. Dark and light mode might be nice on Android, but the default is dark enough for me.

**Comment by MattGyverLee** [comment]
Just for completeness, I made reference at the beginning of this issue to tablet being light mode and phone being dark, this was in fact in Android styles, not iOS, as I showed in https://github.com/keymanapp/keyman/issues/4153 .

![image](https://user-images.githubusercontent.com/986339/102277908-35937f80-3f29-11eb-821f-7e4765d6e504.png)

![image](https://user-images.githubusercontent.com/986339/102277928-3cba8d80-3f29-11eb-95dd-082d767caac1.png)
