### ISSUE TITLE
chore(web): Define `*LTREnter*` and `*LTRBkSp*`, and map `*BkSp*` and `*Enter*` for RTL

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#3934]
Oh, one more tidbit:  I believe we still need to define `*LTREnter*` and `*LTRBkSp*` within KMW; those haven't yet been added.  Even if just as aliases for the baseline `*Enter*` and `*BkSp*` with the same numerical value, they need to have a KMW-side definition.

What has been added so far: https://github.com/keymanapp/keyman/blob/0b620957262976c4b580a5cbdf0e24023648ce24/web/source/osk/visualKeyboard.ts#L541-L548

_Originally posted by @jahorton in https://github.com/keymanapp/keyman/issues/3878#issuecomment-731898129_

Also need to remap `*Enter*` and `*BkSp*` to their corresponding RTL equivalents in `renameSpecialKey()` (visualKeyboard.ts:161). Something like:

```
      if(keyboard.isRtl) {
        if(oldText == "*Enter*") oldText = "*RTLEnter*";
        else if(oldText == "*BkSp*") oldText = "*BkSp*";
      }
```

But I haven't dug in to find how we get `keyboard.isRtl` 😂

**Comment by jahorton** [comment]
So... `keyboard.isRTL`?

https://github.com/keymanapp/keyman/blob/3a90a68101cbf3df12191b957fd73ad8eec0badd/common/core/web/keyboard-processor/src/keyboards/keyboard.ts#L152-L154
