### ISSUE TITLE
bug(windows): User Account Control does not always receive focus when installing a keyboard

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#3936]
**Describe the bug**
When installing a new keyboard, the User Account Control does not pop up for the user to take action; rather the dialogue box is blinking in the taskbar while showing "Installing Keyboard" (See screenshot01). This might be confusing for the new users as they would be sitting and waiting for the installation to finish without knowing Keyman is requesting permission (See screenshot02).

Screenshot01
![image](https://user-images.githubusercontent.com/28331388/100039840-ab2f9280-2e38-11eb-8ca7-decdd39fc9dd.png)

Screenshot02
![image](https://user-images.githubusercontent.com/28331388/100040005-095c7580-2e39-11eb-8310-2d39d45dfc1d.png)

**Expected behavior**
The User Account Control should be in focus or shown to the user so that they can take action accordingly.

---

**Keyman Desktop:**
 - OS: Windows 10 Pro 20H2, build 19042.630
 - Keyman version:  14.0.187-alpha
 - Target Application: [self]

---

**Additional Context:**
The current stable version does exactly what is expected.

**Comment by mcdurdin** [comment]
I'm not getting a consistent repro on this issue. I find that it normally pops to front for me -- can you get consistent repro steps?

**Comment by MakaraSok** [comment]
This is very consistent for me on both Windows 10 Pro 1909 and 20H2. I have to click on the icon blinking on the taskbar to accept the request.

**Comment by MakaraSok** [comment]
This issue is highly visible. It may need to be fixed as it is a little inconvenient. One has to click on the blinking icon on the taskbar to proceed. 

(attested with 14.0.228-beta)

**Comment by MakaraSok** [comment]
@mcdurdin This issue seems to relapse. Keyman Desktop was being updated from 14.0.244-beta to 14.0.247-beta.

![image](https://user-images.githubusercontent.com/28331388/109270111-2b063800-7840-11eb-8832-f24ae823cfa7.png)

**Comment by mcdurdin** [comment]
@MakaraSok that's a separate issue -- that's about installing a Keyman update as opposed to installing a keyboard. It's a different code path and probably a different set of assumptions for how it should work. Can you open as a separate issue?
