### ISSUE TITLE
bug(windows): Check for Updates and then install the updates crash Keyman

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#3938]
**Describe the bug**
Click to "Check for Updates" under Useful Links on Support tab to see a list of keyboards which require updates (See screenshot 01). Click to install, but this error message occurs after the permission is granted (See screenshot 02 and the details). 

Screenshot 01
![image](https://user-images.githubusercontent.com/28331388/100042620-69a1e600-2e3e-11eb-87d1-efe447da4028.png)

Screenshot 02
![image](https://user-images.githubusercontent.com/28331388/100042354-d9fc3780-2e3d-11eb-89db-edfdbfb9a80e.png)

> Details for error report for Keyman app:
>   Application Identifier: kmshell-14.0.187-alpha
>   Error Identifier: 10336728FD4B4EAF4BC61EA1399215A1
> 

This dialogue box is shown after closing "screenshot 02".
![image](https://user-images.githubusercontent.com/28331388/100042798-cd2c1380-2e3e-11eb-9885-d45253d795a3.png)

---

**Keyman Desktop:**
 - OS: Windows 10 Pro 20H2, build 19042.630
 - Keyman version:  14.0.187-alpha
 - Target Application: [self]

**Comment by mcdurdin** [comment]
See also #4005.
