### ISSUE TITLE
bug(mac): MS Word for Mac Composition Issue with Arrow Keys & Mouse

### ISSUE THREAD

**Issue by dyacob** [keymanapp/keyman#3939]
**Describe the bug**
Microsoft Word for Mac is showing an odd behavior where composition sequences break when the cursor is repositioned either by arrow keys or mouse.  The example below uses the GFF Amharic keyboard though this is likely a general problem.

**To Reproduce**
1. Open a new document in MS Word
2. Launch the GFF Amharic keyboard
3. Type the sequence mngst (ምንግስት will appear on screen)
4. Hit the left arrow key 4 times so that the cursor is right of ም
5. Hit the "e" key.  
6. "ም" will become "ተ" (bad)

A similar issue with repositioning the cursor by mouse can be produced by repeating steps 1-3 and then:

4. Move the mouse pointer to the right of ም and click.
5. Hit the "e" key.  
6. "ም" will become "ምእ"

**Expected behavior**
In other Mac applications, and on Windows "ም" will become "መ" in both scenarios.

**Screenshots**

---
**Keyman Desktop, Keyman for macOS, Keyman for Linux:**
 - OS:  macOS Big Sur (Version 11.0.1)
 - Keyman version: 13.0.101 (Mac)
 - Target Application:  Microsoft Word for Mac Version 16.43 (20110804)
  
 
**Keyboard**
 - Keyboard name: GFF Amharic
 - Keyboard version: 1.7
 - Language name: Amharic

**Comment by mcdurdin** [comment]
I can reproduce the first scenario. This looks like we are not getting a context reset as expected, so Keyman is thinking the letter to left of the cursor is ት (generated by <kbd>t</kbd>), which would transform to ተ when <kbd>e</kbd> is pressed.

I cannot reproduce the second scenario, with the mouse; I get the following instead: መንግስት which appears to be correct.

macOS: 10.15.7 Catalina
Keyman: 14.0.187
Word: 16.43 (20110804)

**Comment by mcdurdin** [comment]
I think the mouse issue arises because of Mac security settings. You may be able to resolve it with the following:

1. Type the following command in Terminal:
```
 sudo tccutil reset PostEvent
```
2. Restart your Mac
3. Check the [Keyman privacy settings](https://help.keyman.com/products/mac/current-version/help/configure-security) -- it needs to be allowed in both Accessibility and Input Monitoring.
