### ISSUE TITLE
Navigation keys/shortcuts cause Keyman to lose its context

### ISSUE THREAD

**Issue by tombogle** [keymanapp/keyman#394]
With the exception of simple right or left arrow keys, most other keyboard navigation causes the context to change without Keyman knowing. If the previous keystroke (before navigating) was part of a multiple-key combination and the subsequent keystroke(s) comprise(s) the remainder of the combination, the replacement will happen, possibly replacing a new selection or characters at the new location. Offending keys/shortcuts include (but may not be limited to):

- ⌘-A (Select All)
- up arrow
- down arrow
- ⌘-left arrow (Jump to beginning of a line)
- ⌘-right arrow (Jump to end of a line)
- ⌘-up arrow (Jump to beginning of all text)
- ⌘-down arrow (Jump to end of all text)
- Shift-⌘-left arrow (Select text to beginning of a line)
- Shift-⌘-right arrow (Select text to end of a line)
- Shift-⌘-up arrow (Select text to beginning of all text)
- Shift-⌘-down arrow (Select text to end of all text)

**Comment by mcdurdin** [comment]
It might be good to reset context any time an unrecognised command key is pressed? We do that in Windows.
