### ISSUE TITLE
bug(android): the keyboard search box does not show any result

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#3951]
**Describe the bug**
When trying to add a keyboard from keyman.com on Android Tablet, no result is shown while there should at least few keyboard according to the same search done on Android phone emulator.

left: Android phone emulator | right: Android tablet emulator
![image](https://user-images.githubusercontent.com/28331388/100195838-887da680-2f2a-11eb-94a3-84bf06b6c1d4.png)

**To Reproduce**
1. Go to the gear icon on the top right
2. Click on 'Install Keyboard of Dictionary' or 'Installed languages'
3. Click on 'Installed from keyman.com'
4. Type a query (i.e. khmer) in the Keyboard search box
5. See error

**Expected behavior**
A list of keyboard per query should be shown.

---
  
**Android:**
 - Device: Pixel 2 | Pixel C
 - OS: Android 10 | Android 5.1.1
 - Keyman version: 14.0.188
 - Target application: Keyman for Android

**Comment by darcywong00** [comment]
Can you verify your tablet emulator has network access? On my Nexus 10 emulator, I can pull up
![Screenshot_1606290278](https://user-images.githubusercontent.com/7358010/100197355-cd0a4180-2f2c-11eb-8741-ab772ae1240c.png)

**Comment by MakaraSok** [comment]
On Nexus One emulator running Android 5.1.1, the same behavior is observed:

![image](https://user-images.githubusercontent.com/28331388/100200112-bcf46100-2f30-11eb-9584-3c09a2dcece8.png)

**Comment by mcdurdin** [comment]
This is a Javascript error in cdn/dev/keyboard-search/search.js:

```
Uncaught TypeError: undefined is not a function
https://keyman-staging.com/keyboards?q=khmer

var page = dedicatedLandingPages.find(function(p) {
```

Polyfill needed I guess.

**Comment by mcdurdin** [comment]
Fixed by keymanapp/keyman.com#204 and keymanapp/keyman.com#205
