### ISSUE TITLE
bug(web/engine): native-mode iOS key preview mispositioning

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#3953]
**Describe the bug**
If a web page has been vertically scrolled, key previews for the keyboard will not be positioned correctly.  (In particular, the y-coordinate.)

**To Reproduce**
1. Load the in-repo testing page found at `web/testing/unminified.html` on an iOS device.
2. Scroll down the page a bit.  (A smaller device, such as an iPhone SE, may facilitate this - the page may be too short on larger devices.)
2. Click and hold a key.
3. The key preview will be incorrectly positioned.

**Expected behavior**
The key preview should appear to 'pop out' of the key being pressed.  (Compare against the key preview positioning seen when no page scrolling has occurred.)

**Screenshots**

![Image from iOS (3)](https://user-images.githubusercontent.com/25213402/100206138-891d3980-2f38-11eb-84a8-9e4c27e2ca78.png)

---

**KeymanWeb:**
 - Device: any
 - OS: (probably) any
 - Keyman version: 14.0 (current alpha, _possibly_ 13.0?  I remember seeing this type of behavior before.)
 - URL:  (probably) any; `web/testing/unminified.html` will suffice.

This is easily replicated by Chrome emulation of an iOS device.

---
 
**Keyboard**
 - Any keyboard providing popup keys.

**Comment by mcdurdin** [comment]
What is the situation for longpress? If that also had a scroll issue, that would be more serious.

**Comment by jahorton** [comment]
Longpress is 100% fine, fortunately.  It's _just_ the key preview.
