### ISSUE TITLE
bug(ios): predictive text breaks in iOS 9

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#3960]
**Describe the bug**
See title.

The specific reason:
```
TypeError: wordform.normalize is not a function. (In 'wordform.normalize('NFD')', 'wordform.normalize' is undefined)
```

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize), `String.normalize` is only available as of Safari 10.  As mobile Safari's version matches the device's iOS version... the function simply isn't available on iOS 9.x.x devices.

Upon further investigation... this only appears to break predictive text in Keyman 14.  In 13.0 and before, we did a manual normalization of sorts, as `String.normalize` was also unsupported in IE and certain other legacy devices:

https://github.com/keymanapp/keyman/blob/1e844297b249313399c3d5a865e845cbf80f62a6/common/predictive-text/worker/models/trie-model.ts#L430-L456

`git blame` points to #3014 as the transition to use of `String.normalize`.

**To Reproduce**
1. Load Keyman for iPhone and iPad onto an iOS 9.3.5 (or earlier) device.
2. Launch it
3. Type literally anything

The predictive text banner will remain empty at all times.

**Expected behavior**
Predictive text suggestions should appear.

---

(Delete the irrelevant sections)

**iPhone/iPad/Android:**
 - OS: iOS 9.x.x  (anything older than this is officially unsupported)
 - Keyman version 14.0.x
 - Target application: any

**Other notes:**

Lexical models that also use this function in their code include, but are not limited to:
- `sil.glk-arab.ptwl1`
- `nrc.str.sencoten`

**Comment by mcdurdin** [comment]
I guess we could roll back that patch partially, and use it if string.normalize is not available?

**Comment by jahorton** [comment]
Given that some models wish to use the function as well, I'll probably end up writing a small, naive 'polyfill' version of it based on the pre-patch implementation.  Nothing exhaustive; I'd only do enough to prevent regressions.

**Comment by mcdurdin** [comment]
I'm not sure a polyfill is safe as a website may try to use it; give it a private name 😁

**Comment by jahorton** [comment]
> Lexical models that also use this function in their code include, but are not limited to:
> 
>     * `sil.glk-arab.ptwl1`
> 
>     * `nrc.str.sencoten`

If I don't polyfill the exact name, those models will still break.

Also, I'd be impressed if the website manages to use the naive, worker-only polyfill.
