### ISSUE TITLE
bug(mac): unused layers output something out of the rules defined in Developer

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#3965]
**Describe the bug**
Pressing a key while holding "left Ctrl" or "left Alt" output Latin characters which have not been mapped in the Keyman Developer. 

**To Reproduce**
1. Install this keyboard ([bj_naskapi_classic.zip](https://github.com/keymanapp/keyman/files/5601166/bj_naskapi_classic.zip)) on macOS 
2. Now open a text editor or office writer
3. Press and hold on "left Ctrl or left Alt" and then press any key

**Expected behavior**
Layers without any key mapping should not output anything.

---

(Delete the irrelevant sections)

**Keyman for macOS:**
 - OS: macOS Mojave 10.14.6
 - Keyman version: 13.0.101
 - Target Application: LibraOffice 6.4.0.3
 
---

**Additional context**
Related: https://github.com/keymanapp/keyman/issues/2684

**Comment by mcdurdin** [comment]
Isn't this just the same issue as #2684?

**Comment by MakaraSok** [comment]
> Isn't this just the same issue as #2684?

It depends on how it is looked at. Over there, it is about keys on the layout being partly used. Here, the layers do not even have any one key mapped to any character in the Developer, but still they output something of their own.

**Comment by mcdurdin** [comment]
Okay, it's the same underlying issue though -- so I will close this one as it is referenced by the other one when it comes to addressing it.
