### ISSUE TITLE
feat(linux): Rename `onboard` package

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/keyman#3966]
We ship a slightly modified version of `onboard` that works with Keyman. For the user it's not clear which version he installs since they have the same name, and the only difference is a slightly different package version number (which he won't necessarily see, depending on the package manager).

We should rename our `onboard` package to `onboard-keyman`. The package metadata should indicate that it replaces `onboard` and provides `onboard`. That way I think we just have to rename it. Installing it will uninstall an existing `onboard` package, but since we tell the system that we provide package `onboard` I believe it won't break any packages that depend on `onboard`.

**Comment by mcdurdin** [comment]
This sounds okay in principle, but I wonder about the possibility of adding the Keyman-specific patches upstream instead? That way we would no longer need to maintain a fork.

**Comment by ermshiperete** [comment]
I agree, having the Keyman-specific patches applied upstream should be the long-term goal. However, I have my doubts that they will be accepted because they introduce a new dependency on ibus and Keyman which Debian might be hesitant to do. And the upstream onboard repo doesn't have any commits since 2017.

**Comment by ermshiperete** [comment]
Implemented in https://github.com/keymanapp/onboard-keyman/pull/6
