### ISSUE TITLE
bug(mac): stuck in the Support page - no way to navigate

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#3979]
**Describe the bug**
In Keyman Configuration, go to Support and then click on a link on the top right corner that read "Keyman.com". Now you are in a Keyman homepage where you can find a keyboard to download/install. Try any keyboard listed by clicking on it, about now you have no where to get back to and the page does not seem to work (similar behavior: https://github.com/keymanapp/keyman/issues/3975). There seem to be no way to navigate around nor download/install a keyboard.

**Expected behavior**
One should be able to download and install a keyboard from the page that appears to be for those purposes.

**Screenshots**
![image](https://user-images.githubusercontent.com/28331388/100413484-0f0cc200-30aa-11eb-8006-b4e10f599507.png)

---

**Keyman for macOS:**
 - OS: macOS Mojave, 
 - Keyman version: 14.0.190
 - Target Application: Keyman Configuration

---

**Additional context**
Exit the configuration and reopen it does not bring you back to the Support default page either, only a restart of the machine can do that.

**Comment by mcdurdin** [comment]
I want to take this documentation page out of the Configuration app and have it launch in a web browser instead. That should fix all the problems with it. But there is a bit of work to do here.
