### ISSUE TITLE
bug(ios): issues deleting selected context-initial word via BKSP

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#3986]
**Describe the bug**
Yes, it actually seems to be _that_ specific.  It only appears to affect the first word, when selected.

![Screen Shot 2020-11-27 at 2 42 08 PM](https://user-images.githubusercontent.com/25213402/100423542-bc89d080-30be-11eb-9210-fd6da7a3414d.png)

When a backspace is entered in this state, the text remains unaltered.  _Interestingly_, the predictive text suggestions reset - and even apply correctly in this state!

![Screen Shot 2020-11-27 at 2 42 20 PM](https://user-images.githubusercontent.com/25213402/100423652-e7742480-30be-11eb-9ddf-0399ea157d21.png)

There's a strong chance this is related to that weird iOS IME API behavior we've seen affect things a few times before; emptying the context can cause unexpected side effects.  I'd have to look up the related PRs, but they're likely a solid lead.

---
  
**iPhone/iPad:**
 - Keyman version 14.0.185
 - Target application: Keyman (currently untested within other apps)

**Comment by darcywong00** [comment]
This and #3981 sure sound similar to what I experienced on Android with #3867
