### ISSUE TITLE
bug(android/app): Sentry breadcrumbs leaking too much info

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#3997]
Seen in Sentry log https://sentry.keyman.com/organizations/keyman/issues/1977

We need to filter breadcrumbs in Sentry for KMW embedded to avoid navigation that reports keystroke events.

References
https://docs.sentry.io/platforms/javascript/enriching-events/breadcrumbs/#customize-breadcrumbs

**Comment by mcdurdin** [comment]
As noted in #4025, I just tested this against 14.0.194 and I don't believe it is resolved. As Joshua noted, the mitigation was done in Android-side but the breadcrumbs are collected web-side.

I tested with the good old chrome://inspect and `window.setTimeout(() => { throw "error"}, 10);` pattern, which generated the following error:

https://sentry.keyman.com/organizations/keyman/issues/2027/events/cacf8524a976430980ff25f23755b075/

![image](https://user-images.githubusercontent.com/4498365/100937471-28e55380-3547-11eb-9644-76b58c55f134.png)

**Comment by darcywong00** [comment]
I'll close this and open a new one for `common/core/web` since that's where sentry-manager is configured

**Comment by darcywong00** [comment]
The PR for this was reverted. Since the Navigation breadcrumbs are strictly handled by embedded KMW sentry-manager, this issue is closed (no changes required)
