### ISSUE TITLE
bug(ios): cannot interact with KMP files in iOS 12 (and possibly 11)

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#4017]
**Describe the bug**
There seems to be a major difference in iOS's treatment of files between iOS 12 and 13.  Attempting to open / use a KMP file on a device in iOS 12 doesn't work in these scenarios:
- Keyman app > Settings > Install from File
- Files app > (select file, as if trying to open it)

KMP interactions are supported in these cases:
- Keyboard search works as expected
- Following a .kmp link from Safari works as expected

It seems that if the file is stored within the Keyman app's file system space, the Files app refuses any attempt to 'open' the file.

**To Reproduce**

While far from the only way to trigger this, here's one way to set up a repro:

1. Open the Keyman app
2. Navigate through menus to summon the keyboard-search UI:  `Settings` > `Installed Languages` > `+`
3. Type "Senc", then select "SENĆOŦEN".
4. When the package installer UI is displayed, select the "Cancel" option at the top-left; do not install.
    - Cancellation doesn't actually matter; this merely saves a bit of time.
5. Back out of menus until you reach `Keyman Settings`, then select `Install From File`.
6. Find the file `fv_sencoten` and attempt to open it.

As an alternative to steps 5 and 6, you can close the Keyman app, and then:
- Launch the Files app
- Navigate to the Keyman directory
- Find the file `fv_sencoten` and attempt to open it.

No matter how you attempt to open the file, iOS will not launch Keyman or attempt package installation.  Attempts to "share" (via longpress menu) will also fail.

**Expected behavior**
The UX should match that of the app when operating within iOS 13.x or 14.x; attempts to open the file should launch Keyman and present the package-installer UI.

---

**Keyman for iPhone/iPad:**
 - OS: iOS 11.x, 12.x (Does not affect any 13.x or 14.x)
 - Keyman version: 14.0.192 (it's actually been around for a long while)
 - Target application: Keyman, Files

**Comment by jahorton** [comment]
Browsing through the system console logs, I noticed this pattern on failed file-load attempts:

![Screen Shot 2020-12-09 at 8 46 49 AM](https://user-images.githubusercontent.com/25213402/101563848-9e946800-39fc-11eb-976b-5c8a98946db7.png)

Going by the text of the log messages, it's like the UIDocumentPickerViewController is being told that the picked file doesn't exist... before our callback ever even goes off.

Interestingly, I double-checked things with the actual file that should be loaded, based on the Simulator's actual path for the file on my development machine:

```
/Users/jahorton/Library/Developer/CoreSimulator/Devices/748608E9-C963-4F3C-8C34-65508657BD5D/data/Containers/Data/Application/8800E1C8-3C1A-4790-8970-34BC3951F956/Documents/jawa.kmp
```

Of interest there - the two ID numbers:
- `748608E9-C963-4F3C-8C34-65508657BD5D`
- `8800E1C8-3C1A-4790-8970-34BC3951F956`

Compare against the number from the logs above:
- `6F9A8E55-63AA-4EAF-9FC8-17D568419F22`

It's pretty clearly looking in the wrong spot... which implies this _may_ be a Simulator runtime bug for the older versions of iOS.  I'd say it may be trying to look at the 'wrong device', but there isn't even a device (or an app entry) for that unique identifier within the Simulator's designated file storage area.

At any rate, this appears to be something outside of our control.  Hopefully, the fact that we haven't received any reports of this issue in the wild means that it's Simulator only.  _Hopefully._

**Comment by jahorton** [comment]
For a little extra documentation of the evidence, here's a comparison of the filesystems:

![Screen Shot 2020-12-09 at 9 11 58 AM](https://user-images.githubusercontent.com/25213402/101564980-b0770a80-39fe-11eb-8837-c6a7a539a650.png)

<img width="603" alt="Screen Shot 2020-12-09 at 9 11 55 AM" src="https://user-images.githubusercontent.com/25213402/101564963-a94ffc80-39fe-11eb-8cce-b1a2db6413fe.png">

The `Inbox` folder may result when a file is first "imported" into an app's sandbox for file storage.

<img width="882" alt="Screen Shot 2020-12-09 at 9 14 45 AM" src="https://user-images.githubusercontent.com/25213402/101565131-0350c200-39ff-11eb-89d2-11190b0ab278.png">
 
(Note the file size + "created" timestamp.)

Removing the `Inbox` folder had no effect.

**Comment by jahorton** [comment]
Given these details, I'm not sure that it's something we _can_ fix... and there's the shot that it's not even an issue on real devices.  Of course, any device capable of running iOS 11.x or 12.x can be updated to the latest iOS version, bypassing the problem even then... so we're going to mark this low-priority for now and _maybe_ revisit this further down the line if we get more reports about this.

**Comment by jahorton** [comment]
There does appear to be a bright spot:  https://stackoverflow.com/q/62167469

> Update: I am able to import from iCloud i.e. didPickDocumentsAtURLs is called for iCloud drive files but not for local (on device) files – x64 Jun 4 '20 at 23:35

While I haven't yet confirmed it, this strongly suggests that Keyman will be able to open KMPs stored within iCloud storage.  Files under "On My Device" or its subfolders will continue to fail, but that can be circumvented by simply copying the file into iCloud storage and opening from there.

(The bug reported by that Stack Exchange issue is the exact underlying bug causing this issue.)

**Comment by eddieantonio** [comment]
I can also reproduce this on Keyman 13.0.1115 on iPad iOS 13.6 on an iPad Pro (10.5").

Steps to reproduce:

 1. download https://github.com/eddieantonio/nrc_southern_wakashan/releases/download/0.20210204/myh_makah.kmp
 2. attempt to install it;
    a. does not work from Safari downloads
    b. does not work from Settings > Install from File (File located either from Downloads or iCloud Drive)

Oof, that `low-priority` label makes me sad, because I can't test my keyboard with my community!

**Comment by jahorton** [comment]
> I can also reproduce this on Keyman 13.0.1115 on iPad iOS 13.6 on an iPad Pro (10.5").
> 
> Steps to reproduce:
> 
>     1. download https://github.com/eddieantonio/nrc_southern_wakashan/releases/download/0.20210204/myh_makah.kmp
> 
>     2. attempt to install it;
>        a. does not work from Safari downloads
>        b. does not work from Settings > Install from File (File located either from Downloads or iCloud Drive)
> 
> 
> Oof, that `low-priority` label makes me sad, because I can't test my keyboard with my community!

@eddieantonio - Does the iOS system recognize that you're trying to open it, at least?  If so... it's not this error.  (Seriously, iOS won't even try to open the file on iOS 11 or 12)

If Keyman loads (from Safari downloads) and/or reports an error message, it's probably one that we have already fixed for 14.0 with this PR:  #4327.

**Comment by eddieantonio** [comment]
> @eddieantonio - Does the iOS system recognize that you're trying to open it, at least? If so... it's not this error. (Seriously, iOS won't even try to open the file on iOS 11 or 12)
> 
> If Keyman loads (from Safari downloads) and/or reports an error message, it's probably one that we have already fixed for 14.0 with this PR: #4327.

No error message; it opens, but doesn't do anything. And using "Install From File" gives a file selection UI but, poke as hard as you like, it does not allow you to open a KMP. They _appear_ selectable, but you can't actually.... select them. So not this bug?

**Comment by jahorton** [comment]
That latter part - with "Install From File" - does sound like the bug.  The first part, not so much.  I'll aim to test that KMP out early next week and see if I can replicate it in some manner.

**Comment by jahorton** [comment]
> Oof, that `low-priority` label makes me sad, because I can't test my keyboard with my community!

Also worth note:  the 'low-priority' label was put in place largely for two reasons:

1.  Until now, I was the only person to ever report the issue.  With no one else reporting it, of course it seemed low priority.  I also wasn't making much headway after multiple attempts at resolving the issue.
2. As it appeared to be tied to use of older iOS versions, I figured a simple OS update would be enough to resolve this issue on any given device.  _Almost_ anything capable of running iOS 10 or 11 is also capable of iOS 13 or 14.
    - This holds for anything released since 2015 (save the iPod Touch [gen 6]), as well as one or two 2014 devices.
    - reference 1: https://iosref.com/ios
    - reference 2: https://everyi.com/by-capability/maximum-supported-ios-version-for-ipod-iphone-ipad.html

Unfortunately, reproduction for this issue doesn't appear to be simple.  I loaded up a Simulator mostly matching your environment (but 13.5 instead of 13.6 b/c simulator runtimes are long downloads), and...

![Screen Shot 2021-02-23 at 8 40 24 AM](https://user-images.githubusercontent.com/25213402/108792016-edd94600-75b2-11eb-90f1-07150feb5e92.png)

Granted, this is with the current `beta` version of Keyman.  Could you see if the current beta version also experiences the issue on your device?

**Comment by eddieantonio** [comment]
> Granted, this is with the current `beta` version of Keyman. Could you see if the current beta version also experiences the issue on your device?

Downloaded TestFlight and the latest Keyman 14.0 beta — I can open the .kmp just fine on my iPad! So maybe this was fixed for version 14?

**Comment by jahorton** [comment]
So it was probably that other set of bugs.  It may be possible for us to backport 'em to stable, though we do plan to release 14.0 within about a month.

Thanks for checking on that!

**Comment by eddieantonio** [comment]
I installed the stable version of Keyman 14 on my iPad and I can confirm: installing via .kmp works! 🥳 🥳 🥳  Great work! I'm not super sure if that means _this_ issue is closed though.

**Comment by mcdurdin** [comment]
I'm going to go ahead and mark this as wont-fix because it's for iOS 12 and earlier.
