### ISSUE TITLE
bug(android): link to PDF files attached and included in the package on the welcome page at installation stage NOT_FOUND

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4021]
**Describe the bug**
There are PDF files included in the keyboard package and their location is in the .\welcome folder. Hyperlinks have been used in the `welcome.htm` is not broken. It might be because of the way the package organized files and stuff included. The file path to the attached files in the `href` might have to be manipulated so that file can be viewed.

**To Reproduce**
1. Initiate keyboard installation for Khmer Angkor
2. Click on 'Install' on the bottom right corner
3. Scroll to the bottom of the "Welcome to Khmer Angkor" page 
4. Click on the link on 'here' at the end of the sentence under "Keyboard Documentations"

**Expected behavior**
The link should work? In the development processes, the link in welcome.htm is not broken. 

**Screenshots**
![Screenshot_1606717834](https://user-images.githubusercontent.com/28331388/100576803-6c567c80-3311-11eb-851f-59e85d74f58f.png)

---

  
**Android:**
 - Device: Pixel 2
 - OS: Android 10
 - Keyman version: 14.0.192
 - Target application: Keyman
 
---
 
**Keyboard**
 - Keyboard name: khmer_angkor
 - Keyboard version: 1.0.6
 - Language name: Khmer

**Comment by mcdurdin** [comment]
Happy for this to be triaged later in the process as there are other more critical issues.

**Comment by darcywong00** [comment]
Fixed in 14.0 beta by #4413
