### ISSUE TITLE
bug(windows): keyboard in Configuration is different from the one in the keyman.com

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4024]
**Describe the bug**
When install Khmer Angkor by downloading the .kmp from the keyman.com, the version of the keyboard is 1.0.7; but when installing it by downloading it within the Keyman Configuration, the version number would be 1.0.6.

I would have to verify whether or not the same behavior is observed on macOS when installing it from Download within the Configuration vs downloading it from the keyman.com

**Expected behavior**
The latest version of Keyman should be installed consistently from both keyman.com and from within the Configuration.

---

**Keyman Desktop:**
 - OS: Windows 10 Pro 1909
 - Keyman version: 14.0.192
 - Target Application: Keyman
  
---
 
**Keyboard**
 - Keyboard name: khmer_angkor
 - Keyboard version: 1.0.6 (when download from within Keyman Configuration); 1.0.7 (from keyman.com)
 - Language name: Khmer

**Comment by MakaraSok** [comment]
TODO

- [ ] Test in 13 stable and see if the same behavior happens
- [ ] Test in macOS for the same issue.

**Comment by mcdurdin** [comment]
This relates to the staging site not receiving updates as frequently as the live site.

**Comment by mcdurdin** [comment]
This has been resolved with an update to the deployment of keyboards.

**Comment by MakaraSok** [comment]
Confirmed that the two methods of keyboard installation yield the same version of the keyboard on Keyman 13.

**Comment by MakaraSok** [comment]
Confirmed this is also fixed in macOS.
