### ISSUE TITLE
test(linux): Keyman for Linux 14.0 beta acceptance test

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/keyman#4031]
# Keyman for Linux Acceptance Test Procedures #

1. These test procedures are to be run before moving from alpha to beta, or beta to stable, or before PRs are merged into stable branches.
2. Copy these checklists of tests into a new issue (for tier transitions) or a comment on the PR.
3. When annotating results, use `>` at the start of a new line under the checkbox to note the result. (For an example, see #3973).

## Visual Inspection of master/beta branches
- [x] ![Build Status](https://build.palaso.org/app/rest/builds/buildType:(id:KeymanLinux_Master)/statusIcon) Verify latest CI build of [master](https://build.palaso.org/viewType.html?buildTypeId=KeymanLinux_Master) is successful
- [ ] ![Build Status](https://build.palaso.org/app/rest/builds/buildType:(id:KeymanLinux_Beta)/statusIcon) Verify latest CI build of [beta](https://build.palaso.org/viewType.html?buildTypeId=KeymanLinux_Beta) is successful
- [x] Verify `/HISTORY.md` contains all the current changes

## Gather Assets for Testing ##
- [x] Ubuntu 18.04 Bionic or
- [ ] Ubuntu 20.04 Focal or
- [x] Ubuntu 20.10 Groovy - VMN or physical okay

## Setup Steps ##
- [x] Uninstall previous versions of Keyman for Linux on the system

# Keyman for Linux #

## Basic installation ##
- [x] Add the ppa
```
sudo add-apt-repository ppa:keymanapp/keyman-daily
sudo apt-get update
```
- [x] Install keyman and onboard
```
sudo apt-get install keyman onboard-keyman
```
- [x] From the launcher, start "Keyman Keyboard"
- [x] Verify "Keyman Configuration" panel appears
- [x] Click "Download", enter a keyboard to search for, and click the keyboard
- [x] Click "Install keyboard"
- [x] If the package includes a readme file, verify that it appears in the install window
- [x] If the package includes a welcome file, verify that it appears after installation
- [x] Verify the new keyboard appears in "Keyman Configuration"
- [x] Verify the keyboard was added to GNOME
    - [x] From Ubuntu, start "Settings" --> "Region & Language"
    - [x] Verify the keyboard appears in the "Input Sources" list
    - [x] Verify the language tag for the current keyboard appears on the top right of the screen (`"en"` for English")
          (if the keyboard indicator doesn't show, reboot)
- [x] Click Windows-spacebar to switch to the newly installed keyboard
- [x] In a text editor (gedit), verify that the newly installed keyboard can type

## Add a keyboard for an additional language

- [x] From the launcher, start "Keyman Keyboard"
- [x] Verify "Keyman Configuration" panel appears
- [x] Click "Download", search for "EuroLatin", and click the "EuroLatin (SIL)" keyboard
- [x] Click "Install keyboard"
- [x] Verify that the readme appears in the install window
- [x] Click "Install" button
- [x] Verify that the welcome file appears after installation
- [x] Verify the new keyboard appears in "Keyman Configuration"
- [x] Add the keyboard for an additional language in GNOME
    - [x] From Ubuntu, start "Settings" --> "Region & Language"
    - [x] In "Input Sources", click "+" to add input source
    - [x] Search for the language (e.g. German) and select the "EuroLatin (SIL)" keyboard for that language (e.g. "German (EuroLatin (SIL))")
    - [x] Click "Add"
    - [x] Verify the language/keyboard combination appears in the "Input Sources" list
    - [x] Verify the language tag for the current keyboard appears on the top right of the screen (`"en"` for English")
- [x] Click Windows-spacebar to switch to the newly installed keyboard
- [x] In a text editor (gedit), verify that the newly installed keyboard can type (e.g. typing `:a` should result in `ä`)
> (typing in gedit works, but typing in Gnome Shell search bar has issues, #4028, #4029, #4030)

## Install a package from disk
- [x] From the "Keyman Configuration" panel, click "Install"
- [x] Browse to a local .kmp file on disk and click "Open" to install it
- [x] If the package includes a readme file, verify that it appears in the install window
- [x] If the package includes a welcome file, verify that it appears after installation
- [x] Verify the keyboard was added to GNOME
    - [x] From Ubuntu, start "Settings" --> "Region & Language"
    - [x] Verify the keyboard appears in the "Input Sources" list
    - [x] Verify the language tag for the current keyboard appears on the top right of the screen
- [x] Click Windows-spacebar to switch to the newly installed keyboard
- [x] In a text editor, verify that the newly installed keyboard can type

## About keyboard
- [x] From the "Keyman Configuration" panel, select a keyboard and click "About"
- [x] Verify package and keyboard information is displayed
- [x] For a keyboard downloaded from keyman.com, verify a QR Code link is displayed

## Keyboard help
- [x] From the "Keyman Configuration" panel, select a keyboard and click "Help"
- [x] If the package does not include a welcome file verify that the "Help" button is disabled
- [x] If the package includes a welcome file, verify that it appears.

## Options
- [x] From the "Keyman Configuration" panel, select the "EuroLatin (SIL)" keyboard and click "Options"
- [x] Verify the Options dialog appears.
- [x] Select a different keyboard that doesn't provide options
- [x] Verify the Options button is disabled.

## On Screen Keyboard tests
- [x] From the launcher, start "onboard"
- [x] Verify the OSK for the current keyboard appears at the bottom of the screen
- [x] Verify that the default OSK (en-US) is shown if the current keyboard doesn't have one
- [x] Click Windows-spacebar to switch to another keyboard than has an OSK
- [x] Verify the OSK switches to match the current keyboard
> failed on Ubuntu 20.10 because onboard version is too old (#3966). Re-test 2020-12-04: works after installing `onboard-keyman`.
- [x] In a text editor, verify clicking on an OSK key produces expected output

## On Screen Keyboard configuration
- [x] From the launcher, start "onboard settings"
- [x] Verify the "Onboard Preferences" panel appears
> (panel appears, but choosing "Grid layout" shows empty keys, #4032)

## Uninstallation
- [x] Remove the keyman package
```
sudo apt --autoremove remove keyman
```
- [x] Verify no errors are displayed
- [x] Verify the files in `/usr/lib/python3/dist-packages/keyman_config` are gone

## What's New Tests
- [ ] Refer to the new changes in `linux/history.md` and verify functionality

**Comment by ermshiperete** [comment]
Created issues:
#4028 
#4029 
#4030 
#4032

**Comment by ermshiperete** [comment]
Ubuntu 20.10 is currently missing a keyman specific onboard version.

**Comment by mcdurdin** [comment]
Can you annotate the acceptance test text to include details on which tests failed and caused you to add those issues? (add `> failed, details, #1234` under the item which failed, then a blank line, for example:

```
- [x] Check that the flipper flips
> the flipper didn't flip, #4444

- [x] Check that the flopper flops
``
