### ISSUE TITLE
Many 'Result of call to x is unused' warnings

### ISSUE THREAD

**Issue by gabrielwong** [keymanapp/keyman#405]
Unused function results are marked as warnings in Swift. Many of these are unhandled errors. We should also consider throwing instead of returning a `Bool` that indicate success or failure.

**Comment by jacobbullock** [comment]
@gabrielwong do you want to handle this by using `_ = func()` or throwing instead of returning?  I like the idea of throwing in that case if it's a simple success boolean

**Comment by mcdurdin** [comment]
Fixed by #805
