### ISSUE TITLE
bug(windows): list of keyboards with their help page not shown when triggered from the taskbar

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4057]
**Describe the bug**
With this issue in mind (https://github.com/keymanapp/keyman/issues/4056), a new way to access the keyboard usage page was added to Keyman 14. Users can now click on "Help..." in the menu on Keyman icon of the Windows taskbar to show a list of keyboard with a link to their keyboard usage page. However, it is not so. Only one link is shown and it reads "Help Contents". When clicking on it, the link is directed to Keyman help contents.

This is shown after clicking on "Help...":
![image](https://user-images.githubusercontent.com/28331388/100850541-85e4f900-34b6-11eb-8288-72d92a2de7c9.png)

This is shown after clicking on "Help Contents":
![image](https://user-images.githubusercontent.com/28331388/100851425-c2fdbb00-34b7-11eb-912d-1663ef6d3521.png)

**To Reproduce**

With Keyman 14.0.194-alpha installed:
1. Select a keyboard to show its keyboard usage
2. Go to Windows taskbar and click on 'Help...'
3. See error

**Expected behavior**
A list of keyboards with their keyboard usage page should be shown once "Help..." is clicked.

---

**Keyman for Windows:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman version: 14.0.194-alpha
 - Target Application: (Keyman icon on Windows taskbar)

**Comment by mcdurdin** [comment]
> a new way to access the keyboard usage page was added to Keyman 14. Users can now click on "Help..." in the menu on Keyman icon of the Windows taskbar to show a list of keyboard with a link to their keyboard usage page.

This isn't actually a new feature -- however the issue described is new 😉

**Comment by mcdurdin** [comment]
@MakaraSok please re-test on build 14.0.215-beta or later.

**Comment by MakaraSok** [comment]
It looks like 14.0.2125-beta has not yet been up on our home page.

**Comment by mcdurdin** [comment]
Yeah, it should happen tonight if not earlier

**Comment by MakaraSok** [comment]
Tested with 14.0.215-beta on Windows 10 Pro 20H2 x64.  Mostly work, but not with certain keyboards.

**Comment by mcdurdin** [comment]
> Mostly work, but not with certain keyboards.

Which keyboards? Can you describe what isn't working?

**Comment by MakaraSok** [comment]
With Amharic keyboard this is shown when clicked on the help from the taskbar while the keyboard is selected:
![image](https://user-images.githubusercontent.com/28331388/104993155-05be2700-5a55-11eb-9091-2cd6c460dfab.png)

**Comment by mcdurdin** [comment]
> With Amharic keyboard this is shown when clicked on the help from the taskbar while the keyboard is selected:

See #4330.
