### ISSUE TITLE
bug(mac): install the same keyboard with different methods give two of the same keyboard on the list

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4058]
**Describe the bug**

Khmer Angkor keyboard was installed twice: (1) from the download in the configuration and (2) from the keyman.com website download.

The result of this is that two Khmer Angkor keyboards is found in the list of keyboard:
![image](https://user-images.githubusercontent.com/28331388/100854245-51c00700-34bb-11eb-92fb-c2bb46f4504f.png)

**Expected behavior**

Once an installation of an existing keyboard is installed, Keyman should notify that the keyboard being installed existing already.

---

**Keyman for macOS:**
 - OS: macOS Mojave
 - Keyman version: 14.0.195-alpha
 - Target Application: Keyman

---

**Keyboard**
 - Keyboard name: khmer_angkor
 - Keyboard version: 1.0.7
 - Language name: Khmer

**Additional context**

It is observed that the keyboard is listed only once in the Configuration:
![image](https://user-images.githubusercontent.com/28331388/100854718-f6424900-34bb-11eb-8c07-f3a3a785c361.png)

**Comment by mcdurdin** [comment]
Can you show a screenshot of your Documents/Keyman-Keyboards folders?

**Comment by MakaraSok** [comment]
![image](https://user-images.githubusercontent.com/28331388/100952776-bd4db700-3543-11eb-9b18-b79765ac1dd8.png)

**Comment by mcdurdin** [comment]
What is in the khmer_angkor folder?

**Comment by MakaraSok** [comment]
![image](https://user-images.githubusercontent.com/28331388/100974356-b7210000-356e-11eb-8454-8b984c7be697.png)

**Comment by MakaraSok** [comment]
Tested the build of the fix at #4674. The same keyboard does not get installed nor added to the menu. Confirm this issue has been resolved.

_It might be helpful to add a notification saying this same keyboard has already been installed would be nice._
