### ISSUE TITLE
bug(common/core/web) Embedded KMW Sentry breadcrumbs leaking too much info

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#4063]
As noted in #4025, I just tested this against 14.0.194 and I don't believe it is resolved. As Joshua noted, the mitigation was done in Android-side but the breadcrumbs are collected web-side.

I tested with the good old chrome://inspect and `window.setTimeout(() => { throw "error"}, 10);` pattern, which generated the following error:

https://sentry.keyman.com/organizations/keyman/issues/2027/events/cacf8524a976430980ff25f23755b075/

![image](https://user-images.githubusercontent.com/4498365/100937471-28e55380-3547-11eb-9644-76b58c55f134.png)

_Originally posted by @mcdurdin in https://github.com/keymanapp/keyman/issues/3997#issuecomment-737526428_

**Comment by darcywong00** [comment]
I can take a first swing at this since @jahorton is swamped

**Comment by jahorton** [comment]
Changes should likely happen within `common/core/web/tools/sentry-manager`.
