### ISSUE TITLE
feat(developer/ide): Should there be a way to set lexical-models to RTL?

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#4064]
I vaguely remember Developer used to have a checkbox for setting RTL for lexical-models (copied from Keyboards), but it was later removed with notion that keyboards would determine RTL.

Does it need to be put back so both lexical-models and keyboards can be set?

.model_info might need to set it too.

See keymanapp/lexical-models#106

**Comment by mcdurdin** [comment]
We'll have to tackle this in 15.0.

**Comment by darcywong00** [comment]
In the meantime, maybe we can add a note in the lexical-model creation guide

**Comment by mcdurdin** [comment]
We decided that associated keyboard will be able to spec RTL so we don't need to do it in the model as well.
