### ISSUE TITLE
bug(web): some clicks on touch keyboard cause an error

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#4065]
**Describe the bug**

When touching the keyboard rapidly, I will sometimes see an error `OSK key with ID '', keyID 'undefined' missing needed specification`. This error seems to arise when the `clickKey` function is passed a `span.kmw-key-text` element instead of a `div.kmw-key` element. I don't know how the `span.kmw-key-text` element is passed in but it relates to a function `release` which calls it with the `this.keyPending` property.

**To Reproduce**

1. On Android .194, load any keyboard and type rapidly
2. After some time, see error

**Screenshots**

![image](https://user-images.githubusercontent.com/4498365/100947693-466fe880-355a-11eb-8390-a197aa5feef2.png)

---

**KeymanWeb:**
 - OS: Android 10
 - Browser: Embedded in Keyman for Android, in-app keyboard
 - KeymanWeb Version: 14.0.194-alpha

---

**Keyboard**
 - Keyboard name: Eurolatin (or any keyboard) 
 - Keyboard version: 
 - Language name: 

**Additional context**

Noticed when testing Armenian keyboard (which has other issues) from https://github.com/keymanapp/keyboards/pull/1402

**Comment by darcywong00** [comment]
Ah, maybe that's how I generated this Sentry [issue](http://sentry.keyman.com/organizations/keyman/issues/1977), but I couldn't get a consistent repro
