### ISSUE TITLE
Keyman for iOS 10.0.72 alpha does not seem to update keyboards (+ some visual artifacts)

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#407]
I've got Khmer (NIDA) 1.1 installed. Each time I open the keyboard menu in the app, I am prompted to update. The update appears to go through. However, the version of the keyboard does not update and next time I open the menu, the prompt is there again.

Side note: there are also some visual artefacts on my phone - some text in the updating box is misaligned vertically and the menu items grow vertically after the update:

![img-3806](https://user-images.githubusercontent.com/4498365/32870366-2f9bda02-caae-11e7-8bd1-beff0898ff7e.JPG)
![img-3807](https://user-images.githubusercontent.com/4498365/32870368-2fd3f4e6-caae-11e7-92d5-4234aa99851b.JPG)
![img-3808](https://user-images.githubusercontent.com/4498365/32870369-300c8a22-caae-11e7-8707-017fcbb76c78.JPG)

**Comment by gabrielwong** [comment]
The issue was a bug in checking whether keyboards were up to date. #410 tracks the visual artifacts.
