### ISSUE TITLE
feat: Adding to the readme where the keyboard data files are :)

### ISSUE THREAD

**Issue by lancejpollard** [keymanapp/keyman#4082]
Where are the data files for the keyboards, that tell exactly how the keys map to functionality in a platform-agnostic way? I looked in the https://github.com/keymanapp/keyboards repo but I couldn't find _all_ of them, only some related to firstvoices (some JS files). Where exactly are all these 1,500 language keyboards? Or if not that many, where do the data exactly reside? Thank you.

**Comment by mcdurdin** [comment]
That's the correct repository -- look in the /release folder for the majority of the keyboards, for example https://github.com/keymanapp/keyboards/blob/master/release/k/khmer_angkor/source/khmer_angkor.kmn is the source for the Khmer Angkor keyboard.
