### ISSUE TITLE
bug(windows): error at installation

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4092]
**Describe the bug**

`14.0.200` was downloaded and installed as usual, but this message popped up right after the .exe was triggered with a double click.

![14 0 200 error at installation](https://user-images.githubusercontent.com/28331388/101429125-c0c2b300-3934-11eb-9663-8c99f820b31b.png)

**Expected behavior**

The installation should have been through without this error message.

---

**Keyman for Windows:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman version: 14.0.200-alpha
 - Target Application: Keyman executable file

**Additional context**

If "Ignore," the installation got through and Keyman was installed successfully as if nothing is wrong with it.

**Comment by mcdurdin** [comment]
This is a temporary Internet connection issue -- do you have a firewall blocking software?

**Comment by MakaraSok** [comment]
No, but this was run on a VM.

**Comment by mcdurdin** [comment]
Okay, this isn't a bug as such -- it's something in your environment which we may be able to resolve.
