### ISSUE TITLE
bug(windows): an installed keyboard cannot be used in a separate user account 

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4093]
**Describe the bug**

I have two accounts on my machine. On one account, Keyman 14.0.200-alpha was installed together with a keyboard (i.e. Khmer Angkor) and everything works fine--the keyboard can be used without an issue.

When I logged out of this current account and logged in to the other one hoping to use the same keyboard which has previously been installed, to my surprise the keyboard is not visble in the keyboard list on the Keyman icon on the windows' taskbar. It is the first time to experience this behavior. In an earlier version (Keyman 13.x), the keyboard installed in one user account can be used without any issue.

Observation: even though Khmer Angkor is not visible in the keyboard list on the Keyman icon on the windows' taskbar, it can be found in the list of the installed keyboard(s) in the Keyman Configuration > Keyboard layouts tab.

**Expected behavior**

Per earlier version of Keyman, the keyboards installed are visible and usable across existing Windows user accounts.

**Screenshots**

![keyboard not shown in a separate user account login session](https://user-images.githubusercontent.com/28331388/101430901-80fdca80-3938-11eb-8cfa-4cb3d144f148.png)

---

**Keyman for Windows:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman version: 14.0.200-alpha
 - Target Application: Keyman

---

**Keyboard**
 - Keyboard name: khmer_angkor
 - Keyboard version: 1.0.7
 - Language name: Khmer

**Additional context**

To be able to make the keyboard visible and usable on the second user account, it has to be re-installed. 
![install on a previous install of the same keyboard](https://user-images.githubusercontent.com/28331388/101432091-cfac6400-393a-11eb-8467-77a3fc95c3e5.png)
![the keyboard is visable after the installation over the existing one](https://user-images.githubusercontent.com/28331388/101432105-da66f900-393a-11eb-8416-bea095c13c9c.png)

_(Please ignore the diag report with case #4180 which has been sent over to describe an inconsistent behavior where when the same keyboard was installed successfully, but it does not show up in the keyboard list on the taskbar. The Keyman version is older, i.e. 14.0.196.)_

**Comment by MakaraSok** [comment]
I observe that Keyman 14.0.200-alpha behaves differently on Windows 10 Pro 20H2 and Windows 10 Pro 1909:

- On 10 Pro 20H2, reinstallation of the same keyboard would make it usable in both user accounts
- On 10 Pro 1909, reinstallation of the same keyboard does not make it usable in the second account. The keyboard can be seen in the Configuration but not in the keyboard list of the taskbar.

**Comment by mcdurdin** [comment]
You should be able to click `Add Language` for the keyboard in this circumstance to make the keyboard available?

**Comment by MakaraSok** [comment]
After adding the language 'km' to the keyboard, it is now working as expected.

**Comment by MakaraSok** [comment]
One weird thing though, the hotkeys of the user where the language was added to the keyboard is now empty. 

![image](https://user-images.githubusercontent.com/28331388/102731788-5c0f4b80-436b-11eb-944f-6f9fbb7ebada.png)

**Comment by mcdurdin** [comment]
I'm thinking the hotkey issue might be something separate. Can you try and get a repro in a new issue (feel free to cross-reference this one if/when you find it). Given the original issue appears to be okay, closing this.
