### ISSUE TITLE
bug(developer): error when install on Windows 10 Pro 20H2

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4096]
**Describe the bug**

An error message pops up when Installing Keyman Developer 14.0.200-alpha on Windows 10 Pro 20H2 x64. Installing it on Windows 10 Pro 1909, however, does not cause any error.
![error installing keyman dev](https://user-images.githubusercontent.com/28331388/101447341-9cc49900-3957-11eb-9d83-a073c6c7110c.png)

The error does not prevent the installation from going forward though. After clicking on OK, the installation got through and it got installed successfully.

Note also that there is no error when installing this version of Keyman Developer on Windows 10 Pro 1909 x64.

**Comment by mcdurdin** [comment]
This looks like a temporary Internet connection issue -- do you have a firewall blocking software?

**Comment by MakaraSok** [comment]
Not that I know of, but this was run on VM.

**Comment by mcdurdin** [comment]
Okay, this isn't a bug as such -- it's something in your environment which we may be able to resolve.
