### ISSUE TITLE
[iOS] Visual artifacts in keyboard picker view

### ISSUE THREAD

**Issue by gabrielwong** [keymanapp/keyman#410]
From #407:
> Side note: there are also some visual artefacts on my phone - some text in the updating box is misaligned vertically and the menu items grow vertically after the update:

The menu items also grow vertically when a menu item is selected. This can only be observed extremely briefly since the view is dismissed when an item is selected. However it may point to the underlying issue.

Screenshots from #407:
> ![img-3806](https://user-images.githubusercontent.com/4498365/32870366-2f9bda02-caae-11e7-8bd1-beff0898ff7e.JPG)
> ![img-3807](https://user-images.githubusercontent.com/4498365/32870368-2fd3f4e6-caae-11e7-92d5-4234aa99851b.JPG)
> ![img-3808](https://user-images.githubusercontent.com/4498365/32870369-300c8a22-caae-11e7-8707-017fcbb76c78.JPG)

**Comment by jahorton** [comment]
Upon re-investigation of this issue, it seems to have been automatically resolved when we refactored the keyboard picker view, splitting it from language downloads.  I can no longer observe this behavior - neither here, nor in the since-added Settings view.
