### ISSUE TITLE
bug(web): Suggestions don't honour capitalization

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#4115]
**Describe the bug**

Although we implemented suggestions following keyboard capitalization, this does not appear to be happening

**To Reproduce**

1. With sil euro latin type Th 
2. Note that suggestion offered is "the" not "The".

**Expected behavior**

Expected "The" to be offered. 

**Screenshots**

![Screenshot_20201212-155641_Keep Notes.jpg](https://user-images.githubusercontent.com/4498365/101975718-aa995780-3c92-11eb-9511-f23068ab6b97.jpg)
---

**Keyman for iPhone/iPad/Android:**
 - Device: Samsung A90
 - OS: Android 10 
 - Keyman version: 14.0.204-alpha  
 - Target application:

**Comment by jahorton** [comment]
This should be a bug on https://github.com/keymanapp/lexical-models/ against the MTNT model:

https://github.com/keymanapp/lexical-models/blob/11b70de8daab9c54466d7fac312014cfcb7bd118/release/nrc/nrc.en.mtnt/source/nrc.en.mtnt.model.ts#L1-L5

Cross-reference with https://github.com/keymanapp/keyman/pull/3824.

> The predictive engine will now detect the casing pattern used by the current context (when `languageUsesCasing == true`)...

**Comment by mcdurdin** [comment]
@jahorton Which beta will this change be available in?

**Comment by jahorton** [comment]
Uh... I'd have to do serious research.  The blocker was https://github.com/keymanapp/lexical-models/pull/109, which doesn't follow this repo's versioning scheme.  It should be supported by any beta version of the mobile Keyman apps and by some of the later alphas.

**Comment by jahorton** [comment]
Uh... I'd have to do serious research.  The blocker was https://github.com/keymanapp/lexical-models/pull/109, which doesn't follow this repo's versioning scheme.  It should be supported by **_any_** beta version of the mobile Keyman apps and by some of the later alphas.
