### ISSUE TITLE
bug(windows): set a hotkey after a fresh install

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4119]
**Describe the bug**

Setting a hotkey after a fresh install does not work as expected. The hotkey would get set for a different keyboard and not the one intended by the user.

**To Reproduce**

1. Install the Keyman 14.0.204-alpha and Go to 'Configuration'
2. Click on 'Hotkeys'
3. Scroll down to set a hotkey for a keyboard and take note of which keyboard you set the hotkey for and click "OK"

**Expected behavior**

The hotkey should be for the intended keyboard, not any other one which was not set for.

**Diag report**

@mcdurdin 
Here is the diag report: https://drive.google.com/file/d/1bYbHwbH7V3vjxuUp5YTIHmwvODZ_SirX/view?usp=sharing.

---

**Keyman for Windows:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman version: 14.0.204-alpha
 - Target Application: Keyman

**Comment by mcdurdin** [comment]
See also #4006. Same root cause I believe.
