### ISSUE TITLE
bug(linux): Problems typing IPA characters in Debian

### ISSUE THREAD

**Issue by denniz-j** [keymanapp/keyman#4122]
**Describe the bug**
Using keyman and the IPA (Sil) versionː 1.8.4 keyboard on Debian 10 Buster the first character of common two keystroke sequences is left in place and the IPA character is placed next to it, resulting in 2 characters, whereas I expect that character to be replaced by the IPA character, resulting in 1 character.

**To Reproduce**
1. After installing either `keyman 11.0.103-2` or `keyman 13.0.104-1~sil4~bionic` and associated files and configuring the IPA (Sil) versionː 1.8.4 keyboard and selecting this through the gnome settings dialogues
2. Open a text editor like gEdit or vi
3. Choose "Undetermined (IPA(SIL)) und" from the input selector in the top menu bar
4. Type in 'n>'
5. This will result in 'nŋ' instead of 'ŋ'

**Expected behavior**
Typing in n> 
should result in
ŋ 
...but what does result is
nŋ

Similarly with 
m>
I get 
mɱ
instead of
ɱ
etc.

**Screenshots**
none

---

**Keyman for Linux:**
 - OS: Debian 10 Buster `4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux`
 - Keyman version: Both `keyman 11.0.103-2` or `keyman 13.0.104-1~sil4~bionic`
 - Target Application: gEdit or vi

---

**Keyboard**
 - Package nameː IPA (SIL)
 - Package idː sil_ipa
 - Package versionː 1.8.4
 - Keyboard filename /home/user-name/.local/share/keyman/sil_ipa/sil_ipa.kmx

**Additional context**
I have tried with the default keyman packages that are in the Debian 10 Buster software repositories, and with the keyman packages from the Ubuntu PPA for the 'bionic' version of Ubuntu, see both package listings below...

Debian 10 Buster software repository:
```
dpkg-query -l   ibus-keyman ibus-kmfl keyman kmflcomp libkmfl0 libkmflcomp0 libkmnkbp0-0 python-lxml python3-keyman-config python3-lxml python3-qrcode
dpkg-query: no packages found matching python3-qrcode
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                  Version      Architecture Description
+++-=====================-============-============-==============================================================
ii  ibus-keyman           11.0.103-4   amd64        Keyman engine for IBus
ii  ibus-kmfl             11.0.101-1   amd64        Input method engine for multiple languages using KMFL for IBus
ii  keyman                11.0.103-2   all          Type in your language with Keyman for Linux
ii  kmflcomp              11.0.101-1   amd64        KMFL (Keyboard Mapping for Linux) Compiler
ii  libkmfl0:amd64        11.0.101-1   amd64        This package provides Keyman(C) services to Linux - runtime
ii  libkmflcomp0:amd64    11.0.101-1   amd64        KMFL (Keyboard Mapping for Linux) compiler library
ii  libkmnkbp0-0:amd64    11.0.101-2   amd64        Keyman keyboard processing library
un  python-lxml           <none>       <none>       (no description available)
ii  python3-keyman-config 11.0.103-2   all          Keyman for Linux configuration
ii  python3-lxml:amd64    4.3.2-1      amd64        pythonic binding for the libxml2 and libxslt libraries
```

and Ubuntu PPA for the 'bionic' version of keyman:
```
dpkg-query -l ibus-keyman ibus-kmfl keyman kmflcomp libkmfl0 libkmflcomp0 libkmnkbp0-0 python-lxml python3-keyman-config python3-lxml python3-qrcode
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                  Version                Architecture Description
+++-=====================-======================-============-===========================================================
ii  ibus-keyman           13.0.104-1~sil2~bionic amd64        Keyman engine for IBus
ii  ibus-kmfl             13.0.104-1~sil2~bionic amd64        kmfl engine for IBus
ii  keyman                13.0.104-1~sil4~bionic all          Type in your language with Keyman for Linux
ii  kmflcomp              13.0.104-1~sil2~bionic amd64        KMFL (Keyboard Mapping for Linux) Compiler
ii  libkmfl0              13.0.104-1~sil2~bionic amd64        This package provides Keyman(C) services to Linux - runtime
ii  libkmflcomp0          13.0.104-1~sil2~bionic amd64        KMFL (Keyboard Mapping for Linux) compiler library
ii  libkmnkbp0-0:amd64    13.0.104-1~sil2~bionic amd64        Keyman keyboard processing library
ii  python-lxml:amd64     4.3.2-1+deb10u1        amd64        pythonic binding for the libxml2 and libxslt libraries
ii  python3-keyman-config 13.0.104-1~sil4~bionic all          Keyman for Linux configuration
ii  python3-lxml:amd64    4.3.2-1+deb10u1        amd64        pythonic binding for the libxml2 and libxslt libraries
ii  python3-qrcode        6.1-1                  all          QR Code image generator library - Python 3.x
```
The web based version of the keyboard works as expected, so I can use that, therefore, from my point of view, this issue is not urgent.
Thanks.

**Comment by mcdurdin** [comment]
Thank you for the report. We'll do some investigation here in upcoming sprints.

**Comment by ermshiperete** [comment]
This happens when Wayland is used. Try with X11 (in the options of the login screen select "System X11 Default").

**Comment by denniz-j** [comment]
Thanks ermshiperete, your suggestion worked.

**Comment by mcdurdin** [comment]
> This happens when Wayland is used. Try with X11 (in the options of the login screen select "System X11 Default").

Do we have this documented as a known compat issue somewhere? Perhaps a KB article would be good?

**Comment by ermshiperete** [comment]
This got added to the Linux Q&A (https://keyman-staging.com/linux/).
