### ISSUE TITLE
bug(ios): changes to error reporting flag require app restart

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#4126]
https://github.com/keymanapp/keyman/blob/58f79e48cf12934734d37c88e987a0396801dc40/ios/engine/KMEI/KeymanEngine/Classes/Errors/SentryManager.swift#L81-L90

If the app is loaded while the toggle set to enable error reporting, any Swift-side errors will always be reported while the app is loaded.  Even if the toggle's value is changed to disable reporting.  (Keyboard errors will be disabled immediately, though.)

Of course, if the app is closed and then reloaded after being toggled to disable errors, this also holds; as the toggle is disabled on the new app load, no Swift-side errors will be reported for the app's lifetime in this case, even if the toggle is then enabled.  (Keyboard errors, on the other hand, will be instantly enabled.)

It's almost like Sentry produces some sort of 'closure' during the app's init and refuses to accept changes to the enablement state within the function.  There's no clear reason _why_ it's ignoring the change in value... but it's ignoring that change all the same.

_Originally posted by @jahorton in https://github.com/keymanapp/keyman/pull/4106#r542051328_

**Comment by jahorton** [comment]
Important detail for testing... and possibly relevant for the issue at large:  when the app completely crashes (like via the DEBUG+SENTRY mode's "Force a crash" option), you actually _have to launch the app again_ for it to have a chance to send the error report.

It does seem to respect the last known setting for "Allow Error Reporting" this way.  The crash is only send during load if the toggle is on.

So... I probably just didn't understand this when I was testing before, expecting the result to be immediate with the crash.  We're probably fine, actually!
