### ISSUE TITLE
bug(web): kmwosk.css color inconsistency

### ISSUE THREAD

**Issue by MattGyverLee** [keymanapp/keyman#4153]
@jahorton pointed out some CSS inconsistency on my Cameroon Keyboard in https://github.com/keymanapp/keyboards/issues/1396
I realized that such inconsistency came from the master kmwosk.css file, and will be suggesting some changes in an upcoming pull request.

When I use the following options in the touch layout, I would expect the different classes of keys to show up differently. Across mobile platforms, coloration and contrast are not consistent.

![image](https://user-images.githubusercontent.com/986339/102239012-b38a6300-3ef6-11eb-9d28-f7ede5cddcdd.png)

Today, I worked through and made an inventory of the color changes, and will be submitting a pull request with fixes. While I worked through the Android, iOS dark, and iOS Light, I'm not addressing the lack of dark mode on Android (I like the Android Phone's mid-gray, and I understand that support for light/dark on android is patchy).

I've aimed for the minimum number of changes to fix the problems I see, but I don't know what kind of regression testing you will need to do. I'd like to see the regression testing you do.

**Note: You need to refresh after changing the chrome-debug device, and you can test iOS dark and light modes in Chrome by toggling your system-wide windows Color setting.**

![image](https://user-images.githubusercontent.com/986339/102240209-e3863600-3ef7-11eb-8112-08afe860a2e0.png)

### Tablet vs phone
I fully understand wanting possible spacing, size, and border changes between phone and tablet, but I don't understand why the colors need to be doubly specified for phone and tablet. Nevertheless, I'm following your lead believing that the extra specification is necessary for compatibility.

### Android:
**Android-Phone-Before:**
![android-phone-before](https://user-images.githubusercontent.com/986339/102236254-92744300-3ef3-11eb-81ac-bae901ef6ea5.png)

- Deadkey falls back to a light grey
- shift-on and special-on not contrastive
- spacebar doesn't match keys

**Android Tablet Before**

![Android Tablet before](https://user-images.githubusercontent.com/986339/102242432-5690ac00-3efa-11eb-9d02-0339c3507983.png)

There are so many issues in the tablet style, but I don't think Keyman is still correctly recognizing tablets in debug mode. I have to debug-tweak the code to make the Tablet styles show up at all, even if I Chrome-debug on a Nexus 7 Tablet (I found it in the list).

![image](https://user-images.githubusercontent.com/986339/102238196-c5b7d180-3ef5-11eb-84af-2f016f52fa4a.png)

**Android-Both After**

![android](https://user-images.githubusercontent.com/986339/102237041-7f15a780-3ef4-11eb-83bb-cc6c04da5b83.png)

Of course, I left the margin tweaks in the old code that differed between tablet and phone.

If you like my work, and want me to propose a separate dark and light Android theme, let me know.

### iOS LIGHT

**iOS Light - Before**
![ios-light-before](https://user-images.githubusercontent.com/986339/102237155-a1a7c080-3ef4-11eb-8089-6efc48964cdd.png)

- Deadkey falls back to a light grey
- shift-on and special-on not contrastive

**iOS Light After**
![ios-light](https://user-images.githubusercontent.com/986339/102237299-d3b92280-3ef4-11eb-8a80-2557fa4e03e7.png)

### iOS Dark

**ios DARK before:**
![ios-dark-before](https://user-images.githubusercontent.com/986339/102237422-f21f1e00-3ef4-11eb-8859-79c05e84d446.png)

- Deadkey falls back to a light grey
- shift-on and special-on not contrastive

**iOS Dark After**

![ios-dark](https://user-images.githubusercontent.com/986339/102237592-1a0e8180-3ef5-11eb-9958-b0d95020d92f.png)

~Matthew

**Comment by jahorton** [comment]
Now that #4154 has been merged, is there anything else that needs to be addressed before we close this issue?  Or did #4154 cover it?

**Comment by MattGyverLee** [comment]
Unless you want to pursue dark and light modes for Android and Web, I'm fine closing this one.
