### ISSUE TITLE
bug(windows): unchecked but the effect stays for OSK

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4188]
**Describe the bug**

When "Simulate AltGr with Ctrl+Alt" is checked, both shortcut key combos can be used for the same purpose. The OSK would also trigger the appropriate layout. It makes sense to show the appropriate OSK when pressing "Ctrl+Alt" while the option is still in check; however, when the option is unchecked, the OSK of the AltGr should not be shown. This is now not the case. See the screenshot below:

![image](https://user-images.githubusercontent.com/28331388/102736652-fffef400-4377-11eb-8f94-5e1c27d08fc6.png)

**To Reproduce**

1. Go to 'Options' tab of the Configuration
2. Click to check 'Simulate AltGr with Ctrl+Alt'
3. Press 'Ctrl+Alt+A/S/D' and see +-× in the output while having OSK on (you should see the expected layout for Altgr)
4. Now click to uncheck 'Simulate AltGr with Ctrl+Alt' and do step 3

**Expected behavior**

The OSK of AltGr should not be shown when pressing 'Ctrl+Alt' while the simulation is off.

---

**Keyman for Windows:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman version: 14.0.214-beta
 - Target Application: Keyman, OSK

---

**Related** https://github.com/keymanapp/keyman/pull/4164

**Comment by mcdurdin** [comment]
When testing with beta 14.0.229, I cannot reproduce this. The Ctrl+Alt and AltGr OSK views are correct according to the state of the Simulate AltGr with Ctrl+Alt setting.

# Simulate AltGr with Ctrl+Alt OFF

![image](https://user-images.githubusercontent.com/4498365/105943842-4271ca00-60b6-11eb-8849-13f0c13cb04b.png)

![image](https://user-images.githubusercontent.com/4498365/105943853-4867ab00-60b6-11eb-8a6c-ec58d5604139.png)

# Simulate AltGr with Ctrl+Alt ON

![image](https://user-images.githubusercontent.com/4498365/105943899-5ddcd500-60b6-11eb-8af5-0aaaf46ed09b.png)

![image](https://user-images.githubusercontent.com/4498365/105943853-4867ab00-60b6-11eb-8a6c-ec58d5604139.png)

**Comment by MakaraSok** [comment]
The same expected behavior is also attested in 14.0.224-beta. Let's close this bug.
