### ISSUE TITLE
bug(windows):  Microsoft word inserts invalid characters with sequences with SMP context

### ISSUE THREAD

**Issue by virtualvinodh** [keymanapp/keyman#4196]
**Describe the bug**
Microsoft Word 365 inserts an invalid character with sequences that have SMP characters as the immediate previous context.

For instance, sequences such as the below result in such behavior.

'𑌇' + "i" > '𑌈'
'𑍍' + "i" > '𑌿' 
'𑍍' + "o" > '𑍋' 

They work perfectly in other apps but for some reason, they do not work with MS Word.

However, sequences without any context seem to work fine.

+ "p" > '𑌪' '𑍍'
+ "i" > '𑌇'

**To Reproduce**
Install the Keyman keyboard from the zip file and compose text in MS Word 365. The zip file includes both the source and the compiled keyboard.

[grantha_unicode_phonetic.zip](https://github.com/keymanapp/keyman/files/5726860/grantha_unicode_phonetic.zip)

If it helps, you can download the relevant font from here:

https://github.com/googlefonts/noto-fonts/tree/master/unhinted/otf/NotoSansGrantha

**Expected behavior**
Invalid characters should not appear

**Screenshots**

![image](https://user-images.githubusercontent.com/1050975/102828386-82210400-43dc-11eb-87ca-7bf532dc072c.png)

The sequences to type are:

p pa pi po i ii

---

**Keyman for Windows:**
 - OS:  Windows 10
 - Keyman version: Version 14.0.214-beta
 - Target Application: Microsoft Word 365

**Keyman Developer:**
 - OS: Windows 10
 - Keyman Developer version: Version 14.0.214.0

---

**Comment by mcdurdin** [comment]
Thank you for this report. I will investigate and let you know what I find. At this stage, it probably won't happen before January as I go on holidays shortly.

**Comment by mcdurdin** [comment]
Fixed in #4360.

**Comment by ermshiperete** [comment]
Key sequences for typing the problematic characters: 

i + i
p + i
p + o
