### ISSUE TITLE
Firing "onChange" when the input value changes via a click (desktop)

### ISSUE THREAD

**Issue by dy2288** [keymanapp/keyman#42]
Hi,

Thanks for the great library!

We're using Version 1.0 and are considering moving to version 2.0 (which I'm currently testing), however we're facing an issue with using the keyboard in an application that relies on onChange events firing (for example - in a 3rd party library like this https://github.com/gcanti/tcomb-form).

As you probably know, onChange events only fire when an input is manipulated via a user action, however we need these to fire when someone clicks one of the keys in the virtual keyboard.

While I can track typed-values using code like this:

{code}
  myInput.addEventListener(
    'keyup', 
    function() { console.log('test') }, 
    false);
{code}

I can't seem to figure out how to listen to the event that corresponds to someone clicking a key via the moust (or for the matter, can't find a way to manually trigger an onChange event via KeyManWeb). Tried adding event listeners via kmw.addEventListener and kmw.osk.addEventListener, and had a through read of the documentation. 

Any help would be appreciated.

**Comment by mcdurdin** [comment]
Thanks for using KeymanWeb :)

I think this change would need to be added to the KeymanWeb code, but I am
going to be stuck for time in the next couple of months to investigate.  It
is possible to synthesize OnChange events, e.g. see
http://stackoverflow.com/questions/2490825/how-to-trigger-event-in-javascript
(that result is a little dated; you don't need to worry about the
IE-specific solution any more). I would be willing to review a pull request
that makes this change to the on screen keyboard if you are up for that.

**Comment by dy2288** [comment]
Thanks for the reply. We're looking at a few workarounds, but I'd love to make a pull request once things settle here. Time is of course a factor as well.
