### ISSUE TITLE
feat: add a bot to annotate PRs and Issues with build links

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#4201]
**Is your feature request related to a problem? Please describe.**

It can be a hassle to determine which version a particular issue was resolved in. You can drill into the PR's merge commit to find the earliest release tag and determine the version there, but that's pretty buried.

**Describe the solution you'd like**

It would be awesome to have a bot run which annotates a PR and any linked issues with a "Probably fixed in build x.y.z, download here" comment after a release build is completed.

**Comment by mcdurdin** [comment]
Yep, I went ahead and did this. Call it a pre-Christmas present. It only took about 90 minutes to implement so I think that's a worthwhile addition 😁

**Comment by MattGyverLee** [comment]
I'm a fan of this new feature...now I can stop asking when each fix will be available!

**Comment by mcdurdin** [comment]
@MattGyverLee I like it too although it triggered an internal GitHub rate limit and broke our build when we merged 14.0 beta fixes into the 15.0 alpha: "You have triggered an abuse detection mechanism and have been temporarily blocked from content creation. Please retry your request again later."
