### ISSUE TITLE
bug(developer/compilers): lexical-model compiler bad formatting in duplicate words warnings

### ISSUE THREAD

**Issue by DavidLRowe** [keymanapp/keyman#4221]
**Describe the bug**
When compiling a lexical model that has duplicate words in the wordlist, the warnings that are issued are badly formatted.

**To Reproduce**

1. Load lexical-models PR#107 (https://github.com/keymanapp/lexical-models/pull/107)
2. Compile
3. When I compile the model, there are some duplicated words in the wordlist and these produce warnings, but the output is hard to read since there's a "â€œ" before and "â€" after each word. The first word in the list, for example, is "ala".

**Expected behavior**
Legible output: "ala" instead of "â€œalaâ€"

**Screenshots**
![image](https://user-images.githubusercontent.com/8562172/103718806-79076980-4f7c-11eb-9aec-e26ba96bf070.png)

---

**Keyman Developer:**
 - OS: Windows 10 2004 x64
 - Keyman Developer version: 14.0.216.0 beta

**Lexical Model**
 - see information above

**Comment by mcdurdin** [comment]
Note: UTF-8 output from the compiler but Keyman treating it as Windows-1252.

**Comment by jahorton** [comment]
This issue does not seem to appear on macOS.

The closest thing is this:

<img width="653" alt="Screen Shot 2021-02-26 at 8 48 44 AM" src="https://user-images.githubusercontent.com/25213402/109243409-76ecb900-780f-11eb-80ac-75ef49a654c8.png">

But that's due to the script's characters being unsupported by the terminal's font.

**Comment by mcdurdin** [comment]
> This issue does not seem to appear on macOS.

Well, given this is an issue in the IDE which runs only on Windows, I'm not surprised 😁
