### ISSUE TITLE
bug(windows): uncheck the keyboard after a restart doesn't get updated the keyboard menu automatically

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4222]
**Describe the bug**

The keyboard menu from the taskbar does not get updated automatically and/or immediately when the keyboard is unchecked from the Configuration.

Do a refresh install of Keyman for Windows (v14.0.217-beta) and install Hebrew Basic and Lao Basic keyboards. Restart the machine and from the Configuration check Hebrew Basic keyboard to see the error.

![image](https://user-images.githubusercontent.com/28331388/103740325-9a725f00-5029-11eb-8ada-113c54ae70bf.png)

**Expected behavior**

The update should take effect immediately.

---

**Keyman for Windows:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman version: 14.0.217-beta
 - Target Application: self

---

**Keyboard**
 - Keyboard name: Hebrew Basic, Lao Basic
 - Keyboard version: 1.1
 - Language name: Hebrew, Lao

---

**Additional Context**
Uncheck and recheck the keyboard again may trigger expected behavior.

**Comment by mcdurdin** [comment]
Can you re-test this? I cannot reproduce this with the latest beta.

**Comment by MakaraSok** [comment]
Following the repro steps, the same behavior was experienced in the latest beta, 14.0.230.

![image](https://user-images.githubusercontent.com/28331388/106098576-d6ea3400-616b-11eb-913d-3811862fccff.png)

**Comment by mcdurdin** [comment]
I still cannot reproduce this on my machine. We might need to do a screenshare?

**Comment by mcdurdin** [comment]
Still cannot reproduce this one either :(

**Comment by mcdurdin** [comment]
I believe this has the same root cause as #4447 -- the restart is what is triggering the problem.

**Comment by MakaraSok** [comment]
"Uncheck" the keyboard from the Configuration does hide the keyboard from the keyboard menu.

"Recheck" does reshow the keyboard.
