### ISSUE TITLE
bug(windows): unwanted keyboard got installed along with the expected keyboard 

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4227]
**Describe the bug**

In Keyman stable version (13.0.115), when install Swampy Cree keyboard package, `Inuktitut - Naqittaut` got installed as well. This keyboard comes into being without any trace in Windows Language Preferences nor Keyman Configuration, hence there is no way to uninstall it.

**To Reproduce**

1. Fresh install Keyman 13.0.115 and then the Swampy Cree keyboard
[bj_mista_wasaha_cree - Jan08 new.zip](https://github.com/keymanapp/keyman/files/5785126/bj_mista_wasaha_cree.-.Jan08.new.zip)

2. Click on Keyman icon on the Windows taskbar
3. See error

![image](https://user-images.githubusercontent.com/28331388/103972810-5eadd580-51a0-11eb-89b4-0bcfaaf880c4.png)

**Expected behavior**

Only Swampy Cree keyboard should be installed as it's the only keyboard in the package.

---

**Keyman for Windows:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman version: 13.0.115
 - Target Application: self

---

**Keyboard**
 - Keyboard name: [Swampy Cree](https://github.com/keymanapp/keyboards/pull/1412)
 - Keyboard version: 1.2
 - Language name: csw-Cans

**Additional context**

This behavior does not happen in 14.0.216-beta. When installed the package, only Swampy Cree is shown in the keyboard menu.

![image](https://user-images.githubusercontent.com/28331388/103973097-396d9700-51a1-11eb-9b8c-9ba0957a9530.png)

**Comment by mcdurdin** [comment]
Yes, I believe this issue is resolved in 14.0. Can we mark this issue as resolved?

**Comment by MakaraSok** [comment]
Yes, we can mark it so; however it might be bothering the users who are currently using v13.0.115.

**Comment by mcdurdin** [comment]
> however it might be bothering the users who are currently using v13.0.115.

Which is why I invested more than two weeks into fixing it in 14.0 -- it's not a simple issue to resolve which is why it is fixed with 14.0. 😀
