### ISSUE TITLE
feat(android/app): add support l10n languages not supported by device

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#4236]
Also note, (at least for Android), while we later on will have translations available from translate.keyman.com, we may be limited to the list of languages provided by the ROM on the device.

For example, I can find "amharic", but not "nko" or "obolo" 😞

_Originally posted by @darcywong00 in https://github.com/keymanapp/keyman/issues/4228#issuecomment-756622913_

This is an issue that we need to find a solution for as it's a serious limitation for our primary target userbase, given they are using less supported languages.

**Comment by darcywong00** [comment]
Possible workaround ?
https://lokalise.com/blog/android-app-localization/#Change_Application_Locale_Programmatically

**Comment by darcywong00** [comment]
UX Question: Should there be a Localization settings menu, similar to Keyman Configuration?

![desktop l10n](https://user-images.githubusercontent.com/7358010/104413151-5e4a7b80-55a0-11eb-8c72-4af2a3fb0ae0.png)

Would it also involve multiple fonts to render localized language names? Or  just display language names in English?

**Comment by darcywong00** [comment]
Notes from discussion with @mcdurdin 

1. Yes, add a menu option to the Keyman Settings menu.
2. Display the language names in English (match the names per translate.keyman.com)
3. Edit crowdin.yml as needed to do the locale mapping

**Comment by darcywong00** [comment]
Fixed in 14.0 beta by #4261
