### ISSUE TITLE
bug: developer 14 launch fail

### ISSUE THREAD

**Issue by jolene-s** [keymanapp/keyman#4244]
**Describe the bug**
Immediately after installation of Keyman Developer 14 beta if fails to launch with Error code : 0x0000007E  (Error loading libcef.dll)

**To Reproduce**
1. Install latest beta version of Keyman Developer 14.0.216 with Default settings
2. Launch the app
3. App doesn't launch

**Expected behavior**
App launches successfully and runs

---

**Keyman Developer:**
 - OS: <Windows 7 Enterprise SP1 x64>
 - Keyman Developer version: <14.0.216>

The file is present; however, it can't load for some unknown reason that is not explained.

**Comment by mcdurdin** [comment]
Thank you for the bug report; the team is just getting back up to speed after New Year break so will triage as soon as we can.

**Comment by mcdurdin** [comment]
This may be related to #4278. Can you try installing Keyman Desktop and see if that resolves the problem?

**Comment by jolene-s** [comment]
Sorry for my delayed response!  Very tumultuous & trying times!

Installing the same version of the Desktop App has resolved the problem!  Thank you!
