### ISSUE TITLE
bug(android/app): Install link does not work on keyman.com/amharic

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#4247]
**Describe the bug**

Attempting to install the Keyman Amharic keyboard does not work from https://keyman.com/amharic or https://keyman-staging.com/amharic

**To Reproduce**

1. Go to either url above
2. Click on 'Download for Android'
3. Select 'Yes - Install Keyboard'
4. Keyman for Android opens, but no other action is performed

**Expected behavior**

Keyman for Android should start downloading the keyboard immediately.

I have not assessed whether this is an issue with the app or with the website. When resolving this, we should consider backwards compatibility with Keyman 10-13 as well.

---

**Keyman for iPhone/iPad/Android:**
 - Device: Galaxy A90 5G 
 - OS: Android 10
 - Keyman version: 14.0.219-beta

**Comment by darcywong00** [comment]
The external browser is downloading a link
`keyman://localhost/open?keyboard=gff_amharic&language=am`

From https://github.com/keymanapp/keyman/pull/2953#discussion_r405138692
> We should never see keyman:download links in external browsers. So I'd be kinda keen to actually disable this so we don't end up doing things which break for people who haven't yet installed the app. Universal links are a much better long term solution.

Granted universal links aren't working. That PR disabled the keyman:// link from external browsers.

I could revert that... ❓

**Comment by darcywong00** [comment]
Recap from team discussion

Since the universal links didn't get fully implemented, we'll revert part of a0d1cb0307891fa469064a62228f6450773263c0
so that `keyman://` links can be handled by external browsers too.

**Comment by darcywong00** [comment]
Fixed in 14.0 beta by #4292
