### ISSUE TITLE
chore(ios): save .xcarchive as build artifact

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#4248]
Hmm... as best as I can tell, in order to symbolicate this crash report, I'll need access to the *.xcarchive we would have uploaded.  There's no way to download it from Apple's servers after an upload; we'd have to hope the file still exists and is accessible by the build agent's Xcode.  From there, if accessible, it could then be used to download the corresponding *.dSYM files needed to do the actual symbolication.

As a related note... we should probably consider saving that *.xcarchive as a build artifact, even if we can't use it for app distribution.

_Originally posted by @jahorton in https://github.com/keymanapp/keyman/issues/4051#issuecomment-749945749_

**Comment by jahorton** [comment]
So, after some investigation, it seems that the distinction between .xcarchive and .ipa for apps is largely around code-signing: https://stackoverflow.com/a/66823460

So, we should be able to use _either_ a .ipa _or_ an .xcarchive for symbolification.  (https://www.skoumal.com/en/how-to-manually-symbolicate-crash-on-apple-platforms/)  I guess I just didn't find good search results when I'd looked previously.  Both contain the relevant .dSYM files when you crack 'em open far enough.  For IPA files, you need to drill within its `.app` - so to be fair, it _is_ a bit simpler with the .xcarchive, even if just by one or two steps.
