### ISSUE TITLE
bug(developer): include debug information can break identifiers with non-ansi names in the web compiler

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#4250]
**Describe the bug**

From https://community.software.sil.org/t/touch-layout-debugging-with-keyman-developer/4236. A sample keyboard can be found at https://drive.google.com/drive/u/1/folders/1C1EOhWTGXvZlBEmvW8Y4o1QArEyI4-th

If a keyboard includes identifiers (stores or groups) that include characters outside the `a-z A-Z 0-9 _` range, these characters are replaced by `_` by the compiler when Include Debug Information is set to avoid potential issues with invalid characters in identifiers.

When no debug information is included, the store names are replaced with integer identifiers so this problem does not arise.

For example, given the following Keyman source:

```keyman
c ---------------------Maps of Syllabic Forms---------------------------------------------------
c the following is universal (language neutral) these mappings can be overridden by
c language specific mappings
  store(ግዕዝ)  'ሀለሐመሠረሰሸቀበቨተቸኀነኘከኸወዐዘዠየደጀገጠጨጰጸፀፈፐ'
  store(ካዕብ)  'ሁሉሑሙሡሩሱሹቁቡቩቱቹኁኑኙኩኹዉዑዙዡዩዱጁጉጡጩጱጹፁፉፑ'
  store(ሣልስ)  'ሂሊሒሚሢሪሲሺቂቢቪቲቺኂኒኚኪኺዊዒዚዢዪዲጂጊጢጪጲጺፂፊፒ'
  store(ራብዕ)  'ሃላሓማሣራሳሻቃባቫታቻኃናኛካኻዋዓዛዣያዳጃጋጣጫጳጻፃፋፓ'
  store(ኃምስ)  'ሄሌሔሜሤሬሴሼቄቤቬቴቼኄኔኜኬኼዌዔዜዤዬዴጄጌጤጬጴጼፄፌፔ'
  store(ሳድስ)  'ህልሕምሥርስሽቅብቭትችኅንኝክኽውዐዝዥይድጅግጥጭጵጽፅፍፕ'
  store(ሳብዕ)  'ሆሎሖሞሦሮሶሾቆቦቮቶቾኆኖኞኮኾዎዖዞዦዮዶጆጎጦጮጶጾፆፎፖ'

c QWERTY keymappings
  store(keys)  'hlHm_rsxqbvtc_nNkKw_zZydjgTCPS_fp'
```

The compiler produces:

```
  this.s____="ሀለሐመሠረሰሸቀበቨተቸኀነኘከኸወዐዘዠየደጀገጠጨጰጸፀፈፐ";
  this.s____="ሁሉሑሙሡሩሱሹቁቡቩቱቹኁኑኙኩኹዉዑዙዡዩዱጁጉጡጩጱጹፁፉፑ";
  this.s____="ሂሊሒሚሢሪሲሺቂቢቪቲቺኂኒኚኪኺዊዒዚዢዪዲጂጊጢጪጲጺፂፊፒ";
  this.s____="ሃላሓማሣራሳሻቃባቫታቻኃናኛካኻዋዓዛዣያዳጃጋጣጫጳጻፃፋፓ";
  this.s____="ሄሌሔሜሤሬሴሼቄቤቬቴቼኄኔኜኬኼዌዔዜዤዬዴጄጌጤጬጴጼፄፌፔ";
  this.s____="ህልሕምሥርስሽቅብቭትችኅንኝክኽውዐዝዥይድጅግጥጭጵጽፅፍፕ";
  this.s____="ሆሎሖሞሦሮሶሾቆቦቮቶቾኆኖኞኮኾዎዖዞዦዮዶጆጎጦጮጶጾፆፎፖ";
  this.s_keys="hlHm_rsxqbvtc_nNkKw_zZydjgTCPS_fp";
```

Thus, later stores clobber earlier ones, breaking future rules.

**Expected behavior**

Each store should be unique. The easiest way to resolve this may be to include the integer identifier for each store as well as its name. Also for groups.

---

**Keyman Developer:**
 - OS: Windows 10 20H2 x64 
 - Keyman Developer version: 14.0.220-beta

**Comment by jahorton** [comment]
Could always sneak the original name in as an in-lined "multiline" comment.
