### ISSUE TITLE
bug(android): some strings in settings are too long (e.g. Enable Keyman as system-wid..)

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#4260]
**Describe the bug**

Presumably this is a limitation of the checkboxes but some strings are cropped which makes them hard to understand. This will potentially be exacerbated with other localizations.

![image](https://user-images.githubusercontent.com/4498365/104653085-2d885480-570e-11eb-9b85-b063d5e7ed1d.png)

---

**Keyman for iPhone/iPad/Android:**
 - Device: Samsung Galaxy A90 5G 
 - OS: Android 10 
 - Keyman version: 14.0.222-beta

**Comment by darcywong00** [comment]
Fixed in 14.0 beta by #4326
