### ISSUE TITLE
bug(windows): Two Englishes in the UI language menu

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4262]
**Describe the bug**

Click on "English" to the right of "Display in:" to see a list of languages to pick for the UI to show in. You may see two versions of English, (1) "English" and (2) អង់គ្លេស among others. 

![image](https://user-images.githubusercontent.com/28331388/104670894-48a79400-570f-11eb-891f-5e41dc889c3f.png)

**Expected behavior**

"ខ្មែរ (Khmer)" should be shown on the list instead of អង់គ្លេស.

---

**Keyman for Windows:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman version: 14.0.222-beta
 - Target Application: self

**Comment by MakaraSok** [comment]
https://crowdin.com/translate/keyman/all/en-km?filter=basic&value=3#q=english

Is this the one which should be localized as the "target language name"?
![image](https://user-images.githubusercontent.com/28331388/104703484-f768c600-5749-11eb-99f0-e16dc5cae54a.png)

**Comment by darcywong00** [comment]
I think that's where you put "ខ្មែរ (Khmer)"

**Comment by mcdurdin** [comment]
Correct.
