### ISSUE TITLE
feat(windows): Khmer UI is the default font. Can it be changed?

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4263]
**Is your feature request related to a problem? Please describe.**

Khmer UI is not preferred by most users. There was a [petition on change.org](https://www.change.org/p/microsoft-please-change-the-default-khmer-font-in-microsoft-windows?redirect=false) requesting Microsoft to switch its Khmer UI font to Hanuman UI by Danh Hong.

**Describe the solution you'd like**

For Keyman, "Khmer Mondulkiri" may be the one to try on as its our font. 

**Describe alternatives you've considered**

If Khmer Mondulkiri font is not working well on the screen, we may resort to Hanuman UI.

![VirtualBox_Windows 10_15_01_2021_09_04_44](https://user-images.githubusercontent.com/28331388/104673059-945c3c80-5713-11eb-8da8-100acee47dd8.png)

---

**Keyman for Windows:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman version: 14.0.222-beta
 - Target Application: self

**Comment by mcdurdin** [comment]
You can set the `SK_UIFontName` string to `Khmer Mondulkiri` and if it is present, Keyman will use it.
