### ISSUE TITLE
feat(linux): Add support for Wayland

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/keyman#4273]
Currently Keyman doesn't work properly when Wayland instead of X11 is used (see #4122).

**Comment by ermshiperete** [comment]
This happens on Debian Buster 10.7. On Ubuntu 20.04 things work in gedit, but not in gnome-terminal.

To see whether Wayland or X11 is used, run: 

```
loginctl show-session $(awk '/tty/ {print $1}' <(loginctl)) -p Type | awk -F= '{print $2}'
```

To allow Wayland login on Ubuntu 20.04, edit `/etc/gdm3/custom.conf` and set `WaylandEnable` to true (or comment the line). Then restart gdm3: `sudo systemctl restart gdm3`.

**Comment by ermshiperete** [comment]
A little more research shows that Keyman 14.0 kind of works with Wayland: it doesn't survive an ibus restart, which means after installing it's necessary to reboot (or maybe logout/login would be sufficient). 

But even then things don't work properly: With Eurolatin, typing `n` + `>` produces `nŋ`, and with Khmer Angkor typing xEjmr doesn't produce the desired results.

I was testing this in a VM, and I just noticed that my host machine behaves strangely, so that might have an impact...

Note that Debian Buster doesn't have neither `python3-raven` nor `python3-sentry-sdk`, so this will have to be manually downloaded and installed from https://packages.debian.org/bullseye/all/python3-sentry-sdk.

**Comment by darcywong00** [comment]
Is this a pre-requisite for releasing packages on 21.04?  See https://community.software.sil.org/t/how-does-one-go-about-installing-keyman-14-on-ubuntu-21-04/4728

**Comment by bizulk** [comment]
Hello /

Is there a the roadmap for wayland integration ?
By default Ubuntu Linux 20 is using wayland and many embedded Linux devices.
Thanks for answer.

**Comment by ermshiperete** [comment]
> Is there a the roadmap for wayland integration ?

Yes, if everything goes as planned Keyman will work with Wayland in the upcoming version 15. We're currently working on it. In fact, most things already seem to work when using Wayland, but there seems to be a bug in ibus that prevents surrounding text from working properly which results in characters not being replaced.

**Comment by ermshiperete** [comment]
On Ubuntu 21.10 Impish `ibus-keyman` crashes when running under Wayland when trying to switch to a Keyman keyboard.

**Comment by ermshiperete** [comment]
See also #6172.

Additionally, typing with "Korean KORDA Jamo (SIL)" keyboard doesn't work properly in LibreOffice Writer.

Type han<space>geul<space>. This should result in "한글", but after typing `g` no further input is possible until another space is pressed. Then it's possible to type geul, but this results in 한ᄀ글.

See [acceptance tests for v15](https://github.com/keymanapp/keyman/issues/6200#issuecomment-1036316589).

**Comment by ermshiperete** [comment]
It seems support for Wayland in ibus is incomplete (see [here](https://github.com/ibus/ibus/issues/2182)) and only properly works in XWayland.

**Comment by ermshiperete** [comment]
See TEST_KO_WRITER and TEST_KM_WRITER tests in regression test suite (with "Khmer Angkor" keyboard, type `xEjmr`; with "Korean KORDA Jamo (SIL)" keyboard, type `han<space>geul<space>`).

**Comment by ermshiperete** [comment]
While testing typing `shrI` with the _Vedic Sanskrit Devanagari Phonetic (ITRANS)_ keyboard (which should output श्री) I made some interesting discoveries with Wayland:
With the ordered output changes (#7079) things work in Chromium (which doesn't support surrounding text). With apps that support surrounding text, after typing `sh` Core gives us two BACK actions which result in `ibus_engine_delete_surrounding_text` calls. Things seem to work if I put a `sleep(2)` after the `ibus_engine_delete_surrounding_text` call.
Another oddity I noticed with Wayland: When used with Chromium, ibus-engine-keyman reports that prefilter is supported, but for apps that support surrounding text that flag is cleared, i.e. they report not to support prefilter :confused:.

**Comment by ermshiperete** [comment]
I found two workarounds:
- on the user's machine: set the `GTK_IM_MODULE` environment variable before starting the app:
  ```bash
  export GTK_IM_MODULE=ibus
  ```
- in code: set `usleep(50);` after calling `ibus_engine_delete_surrounding_text()`

**Comment by ermshiperete** [comment]
Another problem with the Eurolatin(SIL) keyboard is that the context is wrong:
Type `:ab left =s`. Expected output: `äßb`, but instead we get `ä=sb`.
