### ISSUE TITLE
bug(windows): context() and context do not work correctly with if() or deadkey()

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#4275]
**Describe the bug**

The `context()` and `context` statements do not correctly reproduce the context when `if()` or `deadkey()` statements are used. The results are slightly different in each case:

1. With each `if()` statement, subsequent characters are offset by 1 for `context()` indices.
2. Deadkeys are elided for `context` statements 
3. `context()` statements that refer to deadkeys emit garbage (`U+FFFF`)

These issues arise because of poor use of `miniContext` [in Keyman Engine](https://github.com/keymanapp/keyman/blob/f7e23ba0c5a9430049d1281e228ee8f9c53d0843/windows/src/engine/keyman32/kmprocess.cpp#L551-L565), which does not account for `if()` or other zero-width statements, and is emitted character-by-character rather than emitting the actual code element (using `PostString` such as is done with the [`CODE_INDEX` path](https://github.com/keymanapp/keyman/blob/f7e23ba0c5a9430049d1281e228ee8f9c53d0843/windows/src/engine/keyman32/kmprocess.cpp#L586-L594)).

* Keyman Engine for Web: not affected.
* Keyman Engine for macOS: affected, will not fix, wait for Keyman Core on macOS.
* Keyman Core (Linux): also affected.

**Backward compatibility report**

1. It is possible that there are keyboards that are using the `context()` and `if()` statements that have hacked workarounds but a search shows that only el_dinka and el_nuer in the keyboards repository are using this construct, and only in commented out rules (perhaps because of this bug).

2. The fixes for deadkeys should be reasonably straightforward because they would never have been correct in earlier versions. A search in the keyboards repository (regex `(deadkey|dk)\(.+context`) reveals the following keyboards:

  * bj_naskapi_common uses this construct in [3 rules](https://github.com/keymanapp/keyboards/blob/11dcc04b90d6d58f67c563980fb5a60144cf1ae4/release/bj/bj_naskapi_common/source/bj_naskapi_common.kmn#L233-L235)
  * korean_rr.kmn uses this in [4 rules](https://github.com/keymanapp/keyboards/blob/11dcc04b90d6d58f67c563980fb5a60144cf1ae4/release/k/korean_rr/source/korean_rr.kmn#L111-L114). Fixing this issue will improve this keyboard.
  * lao_phonetic.kmn uses this in [1 rule](https://github.com/keymanapp/keyboards/blob/11dcc04b90d6d58f67c563980fb5a60144cf1ae4/release/l/lao_phonetic/source/lao_phonetic.kmn#L146)
  * sil_korda_jamo.kmn uses this in [2 rules](https://github.com/keymanapp/keyboards/blob/11dcc04b90d6d58f67c563980fb5a60144cf1ae4/release/sil/sil_korda_jamo/source/sil_korda_jamo.kmn#L88-L89)
  * sil_korda_latin.kmn uses this in [1 rule](https://github.com/keymanapp/keyboards/blob/11dcc04b90d6d58f67c563980fb5a60144cf1ae4/release/sil/sil_korda_latin/source/sil_korda_latin.kmn#L138)

**To Reproduce**

Keyboard context_mismatchwith_if:

```
c Tests context(n) together with if() and BKSP, as reported by 
c Andrew Cunningham.

c
c Tests:
c
c 1. [x][BKSP] should result in "a" U+0308
c    -> 14.0.223 gives U+0308 "e"
c 2. [y][z] should result in '<' dk(1) 'a' dk(2) 'b' dk(3) '>'
c    -> 14.0.223 gives 'ab>' (note the missing initial '<'!)
c 3. [y][M] should result in '<' dk(1) '>'
c    -> 14.0.223 gives '<' U+FFFF '>'
c    (to test on web, type [y][M][?], which should result in 'correct', as it is
c     difficult to observe deadkeys)
c
c Note: all these tests pass on web.
c


store(&VERSION) '10.0'
store(&NAME) 'context_mismatch_with_if'
store(&COPYRIGHT) '© 2021 Andrew Cunningham / Marc Durdin'
store(&TARGETS) 'any'

begin Unicode > use(constraints)

store(nfc) '0'    c 1 (default) = Normalisation Form C, 0 = Normalisation Form D
store(diaeresisBase) U+0061 U+0041 U+0065 U+0045 U+0069 U+0049 U+006F U+004F                   c a A e E i I o O

group(constraints) using keys

c ########################
c character position tests
c ########################

c Setup

+ 'x' > 'a' U+0308 'e' U+0308

c Test #1 for if() with context(n)

if(nfc = "0") any(diaeresisBase) U+0308 any(diaeresisBase) U+0308 + [K_BKSP] > context(2) context(3)

c ##########################
c deadkeys and context tests
c ##########################

c Setup

+ 'y' > dk(1) 'a' dk(2) 'b' dk(3)

c Test #2 for dk(d) and context

dk(1) 'a' dk(2) 'b' dk(3) + 'z' > '<' context '>'
'<' dk(1) 'a' dk(2) 'b' dk(3) '>' + '?' > 'correct'

c Test #3 for dk(d) and context(n)

dk(1) 'a' dk(2) 'b' dk(3) + 'M' > '<' context(1) '>'
'<' dk(1) '>' + '?' > 'correct'
```

Using keyboard context_mismatch_with_if, type the following sequences:

1. <kbd>x</kbd><kbd>BKSP</kbd> should result in `"a" U+0308` but 14.0.223 gives `U+0308 "e"`
2. <kbd>y</kbd><kbd>z</kbd> should result in `'<' dk(1) 'a' dk(2) 'b' dk(3) '>'` but 14.0.223 gives `"ab>"` (note the missing initial `"<"`!)
3. <kbd>y</kbd><kbd>M</kbd> should result in `"<" dk(1) ">"` but 14.0.223 gives `'<' U+FFFF '>'`

---

**Keyman for Windows/macOS/Linux:**
 - OS: Windows 10, Linux 
 - Keyman version: 14.0.223-beta

**Comment by mcdurdin** [comment]
Note: Keyman for macOS has a number of other limitations in its engine. Given we are replacing this part of the engine with Keyman Core shortly, it is probably not worth chasing this issue on macOS.

**Comment by mcdurdin** [comment]
@andjc This issue is now resolved and will be published in an upcoming 14.0 beta build. Would it be valuable to you for us to backport to 13.0?

**Comment by andjc** [comment]
@mcdurdin at the moment I have removed the if statements, so no need to back port. If I reapply the if statements I assume I should specify the keyboard for version 14 onwards?

**Comment by mcdurdin** [comment]
> If I reapply the if statements I assume I should specify the keyboard for version 14 onwards?

Yes, that would be correct. Downside is then it doesn't work on earlier versions...  So I would consider doing this in a year once 14.0+ has sufficient uptake.

**Comment by andjc** [comment]
Ok. Currently not critical so a years wait should be fine
