### ISSUE TITLE
change(developer/compilers): Flag package compilation if language not set for touch keyboard

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#4277]
There's been a few occasions on the community forum where a keyboard developer forgets to assign a language to a touch layout keyboard in Keyman Developer package editor. The package compiles fine, but the mobile apps won't be able to install the keyboard package.

Latest occurrence:
https://community.software.sil.org/t/android-phone-no-keyboard-found/4286

It would be nice if Keyman Developer could flag that as a warning/error.

**Comment by mcdurdin** [comment]
Duplicate of #2998.
