### ISSUE TITLE
bug(windows): Simulate AltGr with Ctrl+Alt - checked, but no output when triggered

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4289]
**Describe the bug**

The expected character is not produced when Ctrl+Alt+(anyKey) is triggered while the "Simulate AltGr with Ctrl+Alt" is checked.

**To Reproduce**

1. Install Khmer Angkor keyboard
2. Press AltGr+`K_A` and confirm that a plus sign is output
3. Now, go to the Option tab in the Configuration and check 'Simulate AltGr with Ctrl+Alt'
4. Press 'Ctrl+Alt+`K_A`' and see error (OSK does show the appropriate layout, but nothing is output as expected)

**Expected behavior**

The expected character should be output. In this case, when the option is checked, a plus sign should be produced.

---

**Keyman for Windows:**
 - OS: Windows 10 Pro 1909 x64
 - Keyman version: 14.0.221-beta
 - Target Application: self

---

**Keyboard**
 - Keyboard name: khmer_angkor
 - Keyboard version: e.g. 1.0.7
 - Language name: Khmer

**Additional context**

https://github.com/keymanapp/keyman/issues/4188

**Comment by mcdurdin** [comment]
Investigation:

1. Can repro this.
2. Only an issue with 64-bit apps.
3. So the problem lies in the refresh notification for keyman64.

**Comment by MakaraSok** [comment]
1. This issue is consistent on 64-bit.
2. I am making an attempt to test 32-bit.
3. Probably, the only thing I can confirm is that it does not output anything.

**Comment by mcdurdin** [comment]
@MakaraSok the issue occurs in 64 bit apps on a 64 bit system. If you run a 32 bit app, e.g. c:\windows\syswow64\notepad.exe, you'll see that the settings change is reflected in that app immediately. 

The test build with #4378 should show it working with both 32 and 64 bit apps.

**Comment by MakaraSok** [comment]
> 3\. Probably, the only thing I can confirm is that it does not output anything.

The same happens in LibreOffice, Notepad, Microsoft Edge and Chrome, unless the machine is restarted.

Tested with Keyman 14.0.236-beta on Windows 10 Pro x64.

**Comment by mcdurdin** [comment]
Please retest on the next beta release (just merged the fix). I am not sure it's 100% correct yet (but it should be a lot better than previously). If not 100%, I'll have another go.

**Comment by mcdurdin** [comment]
Following on in #4557 for one last sync issue.
