### ISSUE TITLE
feat(developer/ide): Can "Open Containing Folder" open package build folder?

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#4314]
I'm in the middle updating the KMEA in-app keyboard guide
http://help.keyman-staging.com/developer/engine/android/14.0/guides/in-app/

where I'm planning to modify it to have the package editor --> Open Containing Folder to get the .kmp file.

![open-containing-folder](https://user-images.githubusercontent.com/7358010/105434485-3b9a2000-5c8e-11eb-86df-17bfdd005974.png)

Currently, the package editor "Open Containing Folder" button seems to open the keyboard source folder.

For keyboard projects (like in the keyboards repo) that put build artifacts in a `build` folder, can "Open Containing Folder" open that folder?

**Comment by mcdurdin** [comment]
Right now, "Open Containing Folder" opens Explorer up with the .kps file selected. Changing this would break that behaviour; we'd need to have separate "Open Target in Explorer" and "Open Source in Explorer" actions. Those would need to be replicated in the keyboard editor and the project view as well.

Is it worth the effort?

**Comment by darcywong00** [comment]
> Is it worth the effort?

It would be a nice bell & whistle, but I'm OK if you end up closing this "won't fix"
