### ISSUE TITLE
bug(developer/compilers): lexical model package build warnings during CI don't cause build failures

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#4324]
**Describe the bug**
From https://github.com/keymanapp/lexical-models/pull/109#issuecomment-766495904:

> ![image](https://user-images.githubusercontent.com/25213402/105653175-b1e88d80-5eed-11eb-9dca-078c0340332a.png)
> 
> It may be that I was using a slightly older (`14.0.180`) version of Developer, but it treated the build warning as an error and failed the build!  Removing the cause of the warning allowed the build to then pass.

The build **warning** about a non-canonical BCP-47 tag acted as if it were a build **error**, triggering the package build to fail.  The lexical model (.js) itself compiles fine either way; it's just the package that's affected.  Removing the non-canonical tag (as for the original case, `en` was also a specified tag) resulted in the package build passing.

**To Reproduce**
1. Fetch the https://github.com/keymanapp/lexical-models repo.
2. Checkout commit [11b70de8daab9c54466d7fac312014cfcb7bd118](https://github.com/keymanapp/lexical-models/tree/11b70de8daab9c54466d7fac312014cfcb7bd118).
     - There's a strong chance that https://github.com/keymanapp/lexical-models/pull/109 will work around this issue shortly.
     - Reflects the current state of `master` at the time this issue was created.
3. Launch a console / terminal at the root of your locally-cloned version of that repo, if not already opened.
4. From said root directory, run `./build.sh release/nrc/nrc.en.mtnt` to build its packages.
     - See successful build.  (Actually, there's not even a warning for the package build from the command-line!)
5. Open the project in Keyman Developer
6. Attempt to build the package.
     - See build failure.

**Expected behavior**
As "build warning" usually means an issue with the build that shouldn't result in failure, I'd expect the build to succeed despite the warning.

**Keyman Developer:**
 - OS: Win 10
 - Keyman Developer version: 14.0.180

**Comment by darcywong00** [comment]
Note: the lexical model and keyboards repos have the Keyman Developer project setting to treat compiler hints and warnings as errors

![image](https://user-images.githubusercontent.com/7358010/105657469-03e1e100-5ef7-11eb-89f3-52a16a39a4fd.png)

**Comment by jahorton** [comment]
Ah.  Though, this does still raise one issue we may want to consider:  the build still only fails if run from Developer.  It will succeed during CI builds, meaning someone _could_ disable the warnings locally and push a sub-optimal build if they wanted.

Though, if we're fine with that... I guess it wouldn't be an issue.

**Comment by mcdurdin** [comment]
I've improved the warnings in the .model.ts with #7372 when building through kmcomp or tike. However, the CI build does not use kmcomp for models; rather it calls kmlmc directly, and never even looks at the settings in the .kpj. This means that we'd need to do considerably more work to determine whether or not warnings should fail the build, because we'd need to parse the .kpj to understand the option.

I propose we tag that fix along with the kmc reorg in the future (#5283), when we will need to be able to parse kpj in order to support all the keyboard compilation goodness.

**Comment by mcdurdin** [comment]
This is now complete with the work done on kmc in #9237.
