### ISSUE TITLE
bug(developer): update check failure

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#4325]
**Describe the bug**

In Keyman Developer 14.0.180.0 (alpha), I used `Help` > `Check for Updates...` and was greeted with the following:

![image](https://user-images.githubusercontent.com/25213402/105655954-c039a800-5ef3-11eb-88ed-af66483932b8.png)

The latest version of 14.0 at the time of writing this issue:  14.0.228 (beta).

While by no means a certain thing... perhaps something's amiss with the alpha -> beta upgrade logic?

----

On a side note, I only 'checked for updates' because I noticed that my local Developer installation hadn't prompted me with any updates for quite a while despite being an in-development installation.  The automated, at-launch update check is probably silently failing.

**Expected behavior**

I expected to be updated to 14.0.228-beta.  Failing that... something a _little_ more informative than "Error 401" would also be nice.

**Keyman Developer:**
 - OS: Win 10
 - Keyman Developer version: 14.0.180.0 (alpha)

**Comment by mcdurdin** [comment]
I think this has already been resolved; I am seeing a correct update message with 14.0.248-beta.

![image](https://user-images.githubusercontent.com/4498365/109606228-75f2b900-7b7a-11eb-956e-38b40eea4f1f.png)

Please re-open if this issue still arises with latest beta 😁

**Comment by jahorton** [comment]
I just did some extra testing on this to make sure everything's squared away as we'd expect.

Version 14.0.180-alpha still experiences the same errors; its update check outright fails.

That said, version 14.0.209-beta (the first `beta` build available) updates without issue:

![image](https://user-images.githubusercontent.com/25213402/109738029-aded1100-7bf9-11eb-858d-3cd00209643d.png)

Just to be sure it isn't an issue caused by tier differences, I also tried version 14.0.205-alpha, the last available 14.0 `alpha`:

![image](https://user-images.githubusercontent.com/25213402/109738096-c78e5880-7bf9-11eb-8d01-496792f85bca.png)

... not the error I was expecting, but given the structure of our development cycles... that's still an error, isn't it?  Shouldn't 14.0 alpha upgrade into 14.0 beta... at least while beta is the most current tier?

**Comment by mcdurdin** [comment]
> Shouldn't 14.0 alpha upgrade into 14.0 beta... at least while beta is the most current tier?

At this stage, we always stay in the same tier -- in the same way as if you install an alpha version on Android, you'll stay on the Alpha version even when stable versions are released. The changes in beta do end up in the alpha version, just a few days later (in the future we could actually automate this, and probably should).
