### ISSUE TITLE
feat(mac): Improve behavior of "Always show on-screen keyboard" option

### ISSUE THREAD

**Issue by tombogle** [keymanapp/keyman#433]
When this option is selected, if the OSK is not already visible, it should appear immediately (or perhaps when the Configuration window closes?) (By contrast, I'm not sure we should hide it immediately when the user clears this checkbox - might need some UX testing to know what users would expect.)

**Comment by tombogle** [comment]
This behavior is same as on Windows.

**Comment by SabineSIL** [comment]
see #5859

**Comment by sgschantz** [comment]
Fixed by #12355. The state of the OSK is preserved automatically wherever the user left it, and there is no need for a special option to manage this.
