### ISSUE TITLE
bug(windows): which version will be installed?

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4409]
**Describe the bug**

I made an attempt to install an older version with a fix (i.e. v14.0.233-4386), but in the installation process the versions shown are somehow confusing as to which version will get installed?

![image](https://user-images.githubusercontent.com/28331388/106697987-76973e80-6612-11eb-82f1-d59f6ca8cbca.png)

Download and install this version to see the error above: https://build.palaso.org/repository/download/KeymanDesktop_TestPullRequests/250330:id/release/14.0.233/keyman-14.0.233.exe.

**Expected behavior**

Is there a way to install "just" the version being installed?

---

**Keyman for Windows:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman version: 14.0.233-4386
 - Target Application: self

**Comment by mcdurdin** [comment]
Resolved in #4623.
