### ISSUE TITLE
bug(windows): added languages shown as "English (United States)" instead of their actual name

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4435]
**Describe the bug**

Two languages were added to the "Cameroon QWERTY" keyboard, iė. Bati and Bana. The respective languages were shown in the keyboard menu on the taskbar, but after restarting Windows the languages were changed to "English (United States)".

![image](https://user-images.githubusercontent.com/28331388/107188909-11c95300-6a1b-11eb-85a9-ca636c779709.png)

**Expected behavior**

The respective languages should have been shown instead of "English (United States)" on all three.

---

**Keyman for Windows:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman version: 14.0.237-beta
 - Target Application: self

---

**Keyboard**
 - Keyboard name: sil_cameroon_qwerty
 - Keyboard version: 6.0.4
 - Language name: Afade, Bana, Bati

**Comment by mcdurdin** [comment]
Can you attach a diagnostic report for this issue?

**Comment by MakaraSok** [comment]
Reproed (+ an issue with Amharic not visible in the keyboard menu): 
![image](https://user-images.githubusercontent.com/28331388/107451930-e0679900-6b7a-11eb-8a4c-404d6425d9d1.png)

![image](https://user-images.githubusercontent.com/28331388/107452042-1b69cc80-6b7b-11eb-9fca-42c3b8e0d8b6.png)

Diag report: https://drive.google.com/file/d/1kjkV7qCxdKXTVLdqH7Q71Upyp8pNXQfX/view?usp=sharing

**Comment by mcdurdin** [comment]
I am wondering if this issue is resolved now; can you reproduce with the latest version of the beta? I cannot reproduce it here.

**Comment by MakaraSok** [comment]
No.

After the keyboard was installed and the two languages were added, everything looks good:
![image](https://user-images.githubusercontent.com/28331388/111103941-1e911780-8582-11eb-94ba-3b1e09190eb1.png)

After restarting, the three are now shown as "unknown locale":
![image](https://user-images.githubusercontent.com/28331388/111104021-4bddc580-8582-11eb-83b9-8c1fda002020.png)

When unchecked and rechecked the keyboard, the three reappear. :(

**Comment by mcdurdin** [comment]
The restart will be causing the loss of language identifiers. Can you test this issue also with the build from #4663? It may be that we need both fixes for 100% reliability -- which won't happen yet, although I can rebase the #4663 build and get a rebuild for you that has both fixes in it if you want.

**Comment by MakaraSok** [comment]
With the new build tested on Windows 10 Pro x64, affirmative that the languages are no longer labeled as "Unknown Locale" after the restart.

![image](https://user-images.githubusercontent.com/28331388/111116775-12648480-8599-11eb-8565-1024b6fc4b72.png)
