### ISSUE TITLE
The mobile keyboard layouts shown on the help page are cropped off

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4436]
The mobile keyboard layouts shown on the help page are cropped off when viewing them on mobile devices.

Vertical orientation:
![image](https://user-images.githubusercontent.com/28331388/107164998-eb3bf580-69e3-11eb-8e36-5a7835d96581.png)

Horizontal orientation:
![image](https://user-images.githubusercontent.com/28331388/107165027-0b6bb480-69e4-11eb-8224-45f71fc9155b.png)

While the user can swipe to view the whole keyboard layout, it would be better to ensure that the layouts are completely visible by default.

References:
1. [Original report](https://community.software.sil.org/t/tawallamat-help-images-for-mobile-not-formatted/4396/3)
2. [Sample page with issue](https://help.keyman.com/keyboard/tawallammat_latin/1.2/tawallammat_latin)

**Comment by jahorton** [comment]
There are CSS width values being set on each `kmw-key-square`, which is what causes the excessive width.  It's thus a matter of determining what's causing that... and figuring out where it was introduced.

I have suspicions that #4255 and/or #4270 may be related - those are when I (believe that I) last touched related code - but a deeper investigation will be necessary.

**Comment by jahorton** [comment]
Though... help.keyman.com (not staging) is on KMW 13.0, not 14.0.  So those PRs couldn't have been it.
