### ISSUE TITLE
[iOS] Landscape keyboard sized incorrectly on iPhone X

### ISSUE THREAD

**Issue by gabrielwong** [keymanapp/keyman#444]
KeymanEngine sets the width of keyboard views to the screen width. But on iPhone X, the keyboard is not given full width in landscape.

Landscape system keyboard:
<img width="836" alt="screen shot 2017-11-24 at 12 28 41 pm" src="https://user-images.githubusercontent.com/3857617/33196694-78509b28-d113-11e7-8c6d-0e8d3c6831d6.png">

Landscape in-app keyboard:
<img width="836" alt="screen shot 2017-11-24 at 12 30 12 pm" src="https://user-images.githubusercontent.com/3857617/33196712-93e5e5dc-d113-11e7-91f7-de2043601de3.png">

Portrait system keyboard (correct but just for reference):
<img width="446" alt="screen shot 2017-11-24 at 12 29 38 pm" src="https://user-images.githubusercontent.com/3857617/33196705-872deca4-d113-11e7-9b29-3ba10b4b438e.png">

**Comment by jahorton** [comment]
Returning from landscape on the iPhone SE also results in display errors, leaving a gap beneath the final row of keys, much like happens with my experiments with the iPhone X simulator.

I can't help but notice that said gap when returning to portrait mode is almost exactly as tall as the in-app banner.  Furthermore, the iPhoneX supports an extended display area toward the top, and the dimensions remind me of the newly unusable space we're noting within landscape...

**Comment by mcdurdin** [comment]
This is potentially partially fixed with #981. Now testing.

**Comment by mcdurdin** [comment]
Rotation issues resolved with #981 but sizing is still inaccurate.

**Comment by mcdurdin** [comment]
Current status is that sizing is still incorrect. It is best in system keyboard portrait mode, which is probably the most common size. So may postpone this to after release?

in-app keyboard portrait:
![image](https://user-images.githubusercontent.com/4498365/41329868-62995b96-6efa-11e8-8c78-7a6ea5cc383e.png)

in-app keyboard landscape right:
![image](https://user-images.githubusercontent.com/4498365/41329791-d95db570-6ef9-11e8-9f05-2ca4eb57d5c9.png)

in-app keyboard landscape left:
![image](https://user-images.githubusercontent.com/4498365/41329800-e810bf40-6ef9-11e8-92ce-9dc9122b5bfe.png)

system keyboard portrait:
![image](https://user-images.githubusercontent.com/4498365/41329883-81da181a-6efa-11e8-903a-40604382e210.png)

system keyboard landscape right:
![image](https://user-images.githubusercontent.com/4498365/41329912-9d86fdc6-6efa-11e8-81ac-4b40070e391e.png)

system keyboard landscape left:
![image](https://user-images.githubusercontent.com/4498365/41329894-93b14d06-6efa-11e8-91d4-b148bc124584.png)
