### ISSUE TITLE
bug(windows): update Keyman and all languages related to EuroLatin keyboard got added without user's knowledge

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4445]
**Describe the bug**

Keyboard menu from the Windows' taskbar:
![image](https://user-images.githubusercontent.com/28331388/107314500-514d7900-6ac7-11eb-80b3-68e3642de873.png)

Keyboard menu on the Keyboard Layouts of the Configuration:
![image](https://user-images.githubusercontent.com/28331388/107314564-7641ec00-6ac7-11eb-9eef-e82017ccecd8.png)

Update from any older version of 14 beta to 14.0.239 to see the error. Ensure that you have EuroLatin keyboard installed before updating Keyman.

**Expected behavior**

All languages related to the keyboard should not be automatically added without user's knowledge.

---

**Keyman for Windows:**
 - OS: Windows 10 Pro 20H2 x64/x86
 - Keyman version: 14.0.239-beta
 - Target Application: self

---

**Keyboard**
 - Keyboard name: EuroLatin (SIL)
 - Keyboard version: 1.9.3
 - Language name: ??

**Comment by MakaraSok** [comment]
diag report for @mcdurdin: https://drive.google.com/file/d/104ewRCuHQenu1LSiT2gmzTtPxfhF_zUO/view?usp=sharing

**Comment by mcdurdin** [comment]
Temporary workaround until we resolve this issue: uninstall and reinstall the EuroLatin keyboard.
