### ISSUE TITLE
bug(windows): OSK, keyboard menu on taskbar and Configuration do not get sync immediately

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4447]
**Describe the bug**

Swampy Cree (Tataskweyak) was unchecked, rechecked and then unchecked again. Now the keyboard is still shown in the keyboard menu and the OSK toolbar.

![image](https://user-images.githubusercontent.com/28331388/107334086-de54fa00-6ae8-11eb-80b0-54c11231cfd9.png)

**Expected behavior**

Unchecked keyboard should not be visible in the keyboard menu.

---

**Keyman for Windows:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman version: 14.0.239-beta
 - Target Application: Configuration, OSK toolbar and keyboard menu

---

**Keyboard**
 - Keyboard name: Swampy Cree (Tataskweyak)
 - Keyboard version: 1.1
 - Language name: Cree

**Comment by mcdurdin** [comment]
I also cannot reproduce this problem :) Can you reproduce with the latest beta?

**Comment by MakaraSok** [comment]
Tested with Keyman 14.0.258-beta on Windows 10 Pro 20H2 x64.

This is a little more than just uncheck, recheck and uncheck the keyboard. After installing the Cree keyboard, I've installed a few more keyboards and then restart the machine to experience the issue -- uncheck the Cree keyboard and it stays in the keyboard menu and the OSK tool bar.

![image](https://user-images.githubusercontent.com/28331388/110910205-9a515100-8343-11eb-9634-f1d4643777d8.png)

**Comment by MakaraSok** [comment]
This issue is now more like this one https://github.com/keymanapp/keyman/issues/4222.

**Comment by mcdurdin** [comment]
Thank you for the additional repro steps. The reboot was the key.

Our transient language installs are being deleted when Windows restarts.

For example, we can reproduce this with the `csw-Cans-CA` locale on Windows 10 Pro 20H2 x64. 
In my repro, I am using a classic Windows account without an online Microsoft account associated.
`Get-WinUserLanguageList` shows the following before restart:

```
PS C:\Users\mcdurdin> Get-WinUserLanguageList


LanguageTag     : en-AU
Autonym         : English (Australia)
EnglishName     : English
LocalizedName   : English (Australia)
ScriptName      : Latin
InputMethodTips : {0C09:00000409}
Spellchecking   : True
Handwriting     : False

LanguageTag     : km
Autonym         : ភាសាខ្មែរ
EnglishName     : Khmer
LocalizedName   : Khmer
ScriptName      : Khmer
InputMethodTips : {0453:{FE0420F1-38D1-4B4C-96BF-E7E20A74CFB7}{97899144-A578-41B2-838B-D2DAB4161A5C}}
Spellchecking   : True
Handwriting     : False

LanguageTag     : csw-Cans-CA
Autonym         :
EnglishName     : Swampy Cree (csw-Cans-CA)
LocalizedName   :
ScriptName      : Unified Canadian Aboriginal Syllabics
InputMethodTips : {2000:{FE0420F1-38D1-4B4C-96BF-E7E20A74CFB7}{2A8A8F0E-0B49-4943-89B8-45CD6DE2DDCF}}
Spellchecking   : True
Handwriting     : False
```

I ran a procmon trace and found that process `taskhostw.exe SyncFromCloud` was doing this. Looking at the stack which deletes the `HKCU\Control Panel\International\User Profile\csw-Cans-CA` key, it looks like it is `coreglobconfig.dll!SyncLanguageDataFromCloud` that is making the change.

After this task runs, a few seconds after Windows finishes booting, the keyboard appears to still be loaded but `Get-WinUserLanguageList` no longer shows it:
 
![image](https://user-images.githubusercontent.com/4498365/110994783-6fabda80-83cd-11eb-810d-90a69b7a25a5.png)

**Comment by mcdurdin** [comment]
I can see that the Language Preferences app does trigger an update of the sync settings (in ProcMon seeing a write to `HKCU\Software\Microsoft\Windows\CurrentVersion\CloudStore\Store\DefaultAccount\Current\default$windows.data.globalization.culture.culturesettings\windows.data.globalization.culture.culturesettings\Data`) but I don't think there is a public API we can use to be able to do the same when we add an input method from Keyman.

Also, `Set-WinUserLanguageList` has exactly the same problem -- the sync overwrites any changes added, shortly after a reboot. So looks like I can isolate this completely away from Keyman.

Keys referenced by language sync recording for reference:

```
HKCR\CLSID\{10d62541-90d0-42fe-848c-0dbc1ac42eda}\(Default)
HKCU\Software\Microsoft\Windows\CurrentVersion\CloudStore\Store\DefaultAccount\Current\default$windows.data.globalization.culture.culturesettings\windows.data.globalization.culture.culturesettings\Data
```

**Comment by mcdurdin** [comment]
Note: language sync is disabled:

![image](https://user-images.githubusercontent.com/4498365/111009018-96c2d600-83e6-11eb-86d3-d14f48937aa0.png)

**Comment by mcdurdin** [comment]
This is running with the scheduled task Microsoft\Windows\International\Synchronize Language Settings.

It is possible to disable this task. Disabling the task is a workaround that avoids the problem.

Out-of-the-box mitigation ideas:
* Disable the task when Keyman installs I don't know if Windows will re-enable it at any point (e.g. after a Windows Update, etc).
* Always re-install our language profiles on every Keyman startup. And then again if any discrepancy is detected. Question: do we get a `WM_SETTINGSCHANGE` notification after the sync runs -- in which case we could trigger it again?
* Find a way to trigger the "SyncToCloud" that is done from the Language Preferences settings app.

**Comment by mcdurdin** [comment]
Testing Notes: 
* Win 8.1 does not have coreglobconfig.dll but has some lang sync infrastructure included with OneDrive/SkyDrive: https://kb.parallels.com/123822
* Win 10 RTM does not have coreglobconfig.dll but does have some lang sync infrastructure included. 

Thus, this fix may work only with more recent builds of Windows 10.

**Comment by MakaraSok** [comment]
The OSK toolbar does behave in sync with what is checked/unchecked: https://github.com/keymanapp/keyman/issues/4222#issuecomment-801729911.

**Comment by mcdurdin** [comment]
Note: Microsoft have let me know via email that they are investigating a fix, although I am not clear if that fix will encompass only PowerShell or will also handle changes via other APIs at this point.
