### ISSUE TITLE
System keyboard does not resize when rotated on iPhone X

### ISSUE THREAD

**Issue by gabrielwong** [keymanapp/keyman#445]
The system keyboard does not resize when rotated on iPhone X. However, the in-app keyboard resizes. I have not been able to reproduce on other devices I've tried (iPhone 7 running iOS 11.1 and iPhone 5s running iOS 8.4).

<img width="836" alt="screen shot 2017-11-24 at 12 29 46 pm" src="https://user-images.githubusercontent.com/3857617/33196759-e0f64b96-d113-11e7-9878-6c32d6aa0033.png">

<img width="446" alt="screen shot 2017-11-24 at 12 29 56 pm" src="https://user-images.githubusercontent.com/3857617/33196764-eb531a24-d113-11e7-893d-d90342cf53cf.png">

**Comment by jacobbullock** [comment]
@jahorton @mcdurdin I am not seeing this specific issue on iPhoneX.  We still have the layout issues with changing orientation across other devices, but we may be able to close this one.

**Comment by mcdurdin** [comment]
Okay, I'll go ahead and close given the work you and @jahorton have done on orientation changes for iOS recently.
