### ISSUE TITLE
bug(windows): Hotkeys do not work in 32-bit OS

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4450]
**Describe the bug**

The hotkeys are not working in the 32-bit OS:
1. "Shift+Alt" does not open Language Switcher
2. "Shift+Alt+K" does not open OSK window
3. "Shift+Alt+M" does not open Keyboard Menu

**Expected behavior**

All hotkeys should work as expected.

---

**Keyman for Windows:**
 - OS: Windows 10 Pro 20H2 x86
 - Keyman version: 14.0.239-beta
 - Target Application: LibreOffice 7.0.4.2 (x86)

**Comment by mcdurdin** [comment]
Already resolved?

**Comment by mcdurdin** [comment]
Tested fixed in 14.0.259-beta
