### ISSUE TITLE
bug(windows): hotkey set for a specific keyboard does not work on 32-bit OS

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4452]
**Describe the bug**

Hotkey set for Khmer Angkor (Shift+Ctrl+K) does not work in the 32-bit OS.

---

**Keyman for Windows/macOS/Linux:**
 - OS: Windows 10 Pro 20H2 x86
 - Keyman version: 14.0.239-beta
 - Target Application: n/a

---

**Keyboard**
 - Keyboard name: khmer_angkor
 - Keyboard version: 1.0.7
 - Language name: Khmer

**Additional context**

https://github.com/keymanapp/keyman/issues/4450

**Comment by mcdurdin** [comment]
Already resolved?

**Comment by mcdurdin** [comment]
Tested fixed in 14.0.259-beta

**Comment by MakaraSok** [comment]
Tested with 14.0.262-beta on Windows 10 Pro 20H2 x86. This bug has been fixed.
