### ISSUE TITLE
bug(windows): On 32-bit OS, AltGr does not output anything when "Simulate AltGr with Ctrl+Alt" is checked

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4453]
**Describe the bug**

On 32-bit OS, when "Simulate AltGr with Ctrl+Alt" is checked, nothing is output when AltGr+key is triggered on LibreOffice, Notepad, Windows' Sticky Note, Keyman Text Editor.

It does output the expected character on Microsoft Edge though.

**Expected behavior**

On 64-bit OS, AltGr+key does output an expected character. It should too on 32-bit.

---

**Keyman for Windows:**
 - OS: Windows 10 Pro 20H2 x86
 - Keyman version: 14.0.239-beta
 - Target Application: n/a

---

**Keyboard**
 - Keyboard name: khmer_angkor
 - Keyboard version: 1.0.7
 - Language name: Khmer

**Comment by mcdurdin** [comment]
Resolved in #4622.
