### ISSUE TITLE
bug(windows): compatibility issues with text suggestions in Windows

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#4457]
**Describe the bug**

If you enable the Windows setting "Hardware keyboard" -> "Show text suggestions as I type", then Keyman keyboards no longer function.

**To Reproduce**

1. Start, search for "Hardware Keyboard Settings"
2. Under "Hardware keyboard", enable "Show text suggestions as I type"
3. Start Notepad and select a Keyman keyboard
4. Observe that the keyboard appears to be active but no mapping is performed.

Note that apps such as Editpad Pro continue to work, possibly as they are not using any TSF interfaces?

**Expected behavior**

It should still work...

---

**Keyman for Windows/macOS/Linux:**
 - OS: Windows 10 20H2 
 - Keyman version: 14.0.239-beta

**Comment by mcdurdin** [comment]
This may be related to #4965?

**Comment by rc-swag** [comment]
Re-tested against 16.0.47-alpha and confirmed it is still a problem. I noted that it doesn't interfere for languages that it doesn't have suggestions for. So Khmer_Angkor worked fine. IPA did not work in both TSF and non TSF applications.

**Comment by mcdurdin** [comment]
Duplicated in #6933.
