### ISSUE TITLE
bug(android): there is no English on the language list for UI

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4461]
**Describe the bug**

When the Android UI is set to "Khmer", Keyman picks it up seamlessly and uses it by default. However, the user has no choice to change the UI language to English. Two options are there for the user to switch the language to Khmer, i.e. Default Locale and Khmer.

![image](https://user-images.githubusercontent.com/28331388/107462783-6ab9f800-6b8f-11eb-8a3a-783faa0ef2bb.png)

**Expected behavior**

One of the option on the list should be "English".

---

**Keyman for Android:**
 - Device: Pixel 2 API 29 (Emulator)
 - OS: Android 10
 - Keyman version: 14.0.240-beta
 - Target application: self

**Comment by darcywong00** [comment]
Fixed in 14.0.241 beta
