### ISSUE TITLE
bug(common/models): delete the left most word would give a duplicate of the whole phrase

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4463]
**Describe the bug**

Type this (the quick brown fox) out in the Keyman for Android using EuroLatin (SIL) keyboard with the predictive text enabled. Now, please the cursor after "the" and choose "they" from the suggestion on the banner, and then delete it by pressing the backspace five times. On the fifth press of the backspace, a duplicate of the phrase should appear. The cursor is seen in between the duplicated phrases.

![Screenshot_1612947496](https://user-images.githubusercontent.com/28331388/107488415-e761cc00-6bb9-11eb-8f80-fc517fc51a16.png)

**Expected behavior**

The fifth backspace should not generate a duplicate of the phrase. 

---

**Keyman for Android:**
 - Device: Pixel 2 API 29 (emulator)
 - OS: Android 10
 - Keyman version 14.0.235-beta-test-4427
 - Target application: Keyman

---

**Keyboard**
 - Keyboard name: EuroLatin (SIL)
 - Keyboard version: 1.9.3 (with MTNT)
 - Language name: English

**Additional context**

https://github.com/keymanapp/keyman/pull/4427

**Comment by jahorton** [comment]
... probably should have put this on the PR's thread, as it's not merged yet.  But oh well.

Sounds like a classic context-desynchronization situation.

Also... I see that suggestions at the left-most end of the context are drawn from and act as if the caret were at the right-most end of the context, which definitely _is_ an issue.
