### ISSUE TITLE
feat(linux): Improve output of km-package-list-installed

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/keyman#4465]
The output of `km-package-list-installed` is confusing. I've installed three Keyman keyboards and one system keyboard, yet that doesn't show because all three sections the command outputs refer to Keyman keybords:

```bash
$ km-package-list-installed 
--- Installed user keyboards ---
GFF Amharic Keyboard, version: 1.9.2, id: gff_amharic
Khmer Angkor, version: 1.0.6, id: khmer_angkor
EuroLatin (SIL), version: 1.9.2, id: sil_euro_latin
--- Installed shared keyboards ---
--- Installed OS keyboards ---
```

I think it would be better to explicitly state that it's Keyman keyboards ("Installed user Keyman keyboards"), or maybe even better add the location where it looks for the keyboards ("Installed user keyboards (~/.local/share/keyman)").

**Comment by mcdurdin** [comment]
I would assume that this lists Keyman packages and not system keyboards. The thing that I would agree isn't clear is the delineation between, user, shared and os keyboards. I'm not sure if showing the path is useful for the average user but it could be helpful with a `-v` (`--verbose`) mode.

It would be fine to add `Keyman` to each of the titles to reduce confusion. I think it's appropriate that it doesn't attempt to list non-Keyman keyboards/packages.

The other thing that is conflated here: are we listing packages, or keyboards? They are not the same thing -- a package can have multiple keyboards, e.g. [Galaxie Greek and Hebrew Positional](https://keyman.com/keyboards/galaxie_greek_hebrew_positional)

**Comment by ermshiperete** [comment]
> The other thing that is conflated here: are we listing packages, or keyboards? They are not the same thing -- a package can have multiple keyboards, e.g. Galaxie Greek and Hebrew Positional

Good point. We're listing packages.
