### ISSUE TITLE
bug(android): Khmer string found when English is chosen as the UI language

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4475]
**Describe the bug**

While testing ML, I got to install, uninstall and reinstall the dictionary of a keyboard manually. In this case, when trying to "Check for a available dictionary," a notification in Khmer appears even though the UI language is set to English.

![Screenshot_1613013601](https://user-images.githubusercontent.com/28331388/107606709-8bef1700-6c69-11eb-8d64-c12dfbf06c48.png)

**To Reproduce**

1. Go to 'Settings' > 'Installed Languages'
2. Click on 'Central Khmer'
3. Scroll down to the bottom and click on 'Dictionary' to check for associate dictionary to download

**Expected behavior**

The message should be in English -- 'No dictionary to download'.

---

**Keyman for Android:**
 - Device: Pixel 2 API 29
 - OS: Android 10
 - Keyman version 14.0.241-beta
 - Target application: Keyman

---

**Keyboard**
 - Keyboard name: khmer_angkor
 - Keyboard version: 1.0.7
 - Language name: Khmer

**Additional Context**
This behavior can also be experienced when a keyboard without a dictionary is completing the installation. Try and install "Mongolian Cyrillic Basic" keyboard and observe this behavior when the installation is looking for available dictionary to download, but fail.

![Screenshot_1613026925](https://user-images.githubusercontent.com/28331388/107609644-26535880-6c72-11eb-87fe-23732c57208f.png)

**Comment by MakaraSok** [comment]
Another string is found: "Downloading dictionary started in Background".

![Screenshot_1613026152](https://user-images.githubusercontent.com/28331388/107608938-0753c700-6c70-11eb-9cc2-e6c2dd78ccc4.png)

**Comment by MakaraSok** [comment]
These behavior also happen when a language other than English is chosen as the UI language.

i.e. Frech is the UI language:
![Screenshot_1613027618](https://user-images.githubusercontent.com/28331388/107610115-6f57dc80-6c73-11eb-9df8-1a50ad4af560.png)

**Comment by darcywong00** [comment]
Noting in all your examples, the device has a system locale of "Khmer", while Keyman for Android is set to display language "English".

**Comment by darcywong00** [comment]
Fixed by the linked issue
