### ISSUE TITLE
bug(common): history collater not taking base branch into account on PR merges

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#4483]
**Describe the bug**

See https://github.com/keymanapp/keyman/pull/4427#issuecomment-777681199 for example. At time that comment was added to the PR, the PR had not yet been merged. However, another PR that it was based on had been merged?

The history collater should only reference PRs that are merged into alpha,beta or stable.

See also #5348 which is repeated in history for several versions.

**Comment by jahorton** [comment]
It seems to have been right after I'd merged `beta` into the PR's branch.  At least, according to the page's timing.

I think that only got uploaded along with the two commits afterward though, so take this with a grain of salt.

**Comment by mcdurdin** [comment]
Fixed by #5527 in A15S12.
