### ISSUE TITLE
bug(common/model): long words get truncated on the banner

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4495]
**Is your feature request related to a problem? Please describe.**

Original post from the community site:

> The font size used seems to be too large, and as a result long words don’t feet. As a result it’s hard to pick the right word form, which makes it almost useless exactly when it would be most useful: to tap in long words. 

**Describe the solution you'd like**

Can’t the font size be defined or adjusted based on word length?

**Describe alternatives you've considered**

n/a

---

**Keyman for iPhone:**
 - Device: iPhone Xs Max
 - OS: iOS?
 - Keyman version 14.0.243-beta
 - Target application: any

---

**Keyboard**
 - Keyboard name:  (custom-made)
 - Keyboard version: 
 - Language name: 

**Additional context**

**Comment by jahorton** [comment]
Compare against #1980, which is when we settled on making suggestions scrollable.  Also #2220.

**Comment by mcdurdin** [comment]
@MakaraSok Can you link to the original post from community site?

**Comment by MakaraSok** [comment]
cf: https://community.software.sil.org/t/suggestions-bar-questions/4420

**Comment by jahorton** [comment]
Highly related to #3003.
