### ISSUE TITLE
kmw.addKeyboards uses 'language' instead of 'languages'

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#45]
When registering a keyboard in KMW, the developer must include a 'language' member in the object with an array of language objects. However, the name of this member in the cloud API is 'languages'.

See http://help.keyman.com/developer/engine/web/2.0/webapi.php vs http://help.keyman.com/developer/engine/web/2.0/reference_kmw20_core_addKeyboards.php (recently updated to match implementation)

**Comment by jahorton** [comment]
Updated links: 

* Cloud API:  https://help.keyman.com/developer/cloud/4.0/
* KMW API:  https://help.keyman.com/DEVELOPER/engine/web/10.0/reference/core/addKeyboards
