### ISSUE TITLE
bug(android): the welcome page does not go away when tapping on "OK"

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4511]
**Describe the bug**

In the installation process of a keyboard (either from device or keyman.com), the welcome page does not go away after clicking on "OK" button on the bottom right corner.

**To Reproduce**

1. Go to 'Settings'
2. Click on 'Install a Keyboard or a Dictionary'
3. Choose a keyboard to install either from keyman.com or device
4. Tap on "Install" 
5. Tap on "OK" 
6. See error - nothing happens even after tapping on the "OK" button multiple times

**Expected behavior**

The welcome page should go away after clicking on "OK".

**Screenshots**

![Screenshot_1614141277](https://user-images.githubusercontent.com/28331388/108948073-54826080-7694-11eb-96c4-03655b20af29.png)

---

**Keyman for Android:**
 - Device: Pixel 2 API 29
 - OS: Android 10 - emulator
 - Keyman version 14.0.244-beta
 - Target application: Keyman

**Comment by MakaraSok** [comment]
The back button at the bottom of the screen does not make the welcome page go away either, unless tapping it at least 8 times.

Eight times of taps on the "OK" button would also make it go away too.

**Comment by darcywong00** [comment]
I wonder if a recent Chrome webView update is causing this to hang (multiple processes using WebView within the same app).

I can repro with Keyman for Android 13.0.6220 stable

My Android 8.1 device currently has Chrome 88.0.4324.181

**Comment by darcywong00** [comment]
More investigation with my Android 8.1 device and Chrome 88: 

When I installed the build prior to #4477 (14.0.242 beta) where the welcome.htm page is picked out to the `ACTION_VIEW` intent for Chrome, Chrome is also unresponsive when rendering sil_cameroon_qwerty welcome.htm page.

**Comment by MakaraSok** [comment]
Chrome version on the Android 10 emulator:
![image](https://user-images.githubusercontent.com/28331388/109749577-856f1200-7c0d-11eb-8a20-8f2415bd0257.png)

**Comment by MakaraSok** [comment]
I can confirm that this behavior does not happen in my physical device running Android 10, Chrome 88.0.4324.141 and Keyman 14.0.248-beta.

The welcome page stays though when testing on Android 10 emulator running Keyman 14.0.248-beta and Chrome 74.0.3729.185. To make the welcome page to away, the OK button has to be pressed on multiple times - 4 times to be specific.

**Comment by darcywong00** [comment]
Fixed in #4531
