### ISSUE TITLE
bug(windows): Caps Lock not working as expected

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4525]
**Describe the bug**

Caps Lock key does not do anything when a Keyboard keyboard is used (say, `EuroLatin (SIL)`). In order for the Caps Lock to work, one has to leave the Caps Lock on and switch to a different app, and then switch back to where you want to type with the Caps Lock on.

**To Reproduce**

1. Install the current latest beta version of Keyman 14.0.244 and EuroLatin (SIL) keyboard
2. Go to the comment section below.
3. Try and type using the keyboard with  and without the Caps Lock on

**Expected behavior**

For other non-Latin keyboards, it may not be important to have the Caps Lock working. The Latin based ones may find it helpful to have the Caps Lock working as expected.

---

**Keyman for Windows:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman version: 14.0.244-beta
 - Target Application: Chrome v88.0.4324.190 (Official Build) (64-bit)

---

**Keyboard**
 - Keyboard name: EuroLatin (SIL)
 - Keyboard version: 1.9.3
 - Language name: English

---

**Additional context**
This issue does not happen in macOS when testing it with Keyman for mac v14.0.243-beta.

Original report on the community site: https://community.software.sil.org/t/keyman-14-beta-does-not-recognize-the-caps-lock-key/4452

**Comment by MakaraSok** [comment]
This behavior is also experienced in Linux (`20.04.2 LTS`) and Keyman `15.0.17-alpha-local`.

**Comment by mcdurdin** [comment]
> This behavior is also experienced in Linux (`20.04.2 LTS`) and Keyman `15.0.17-alpha-local`.

Can you report the Linux behaviour as a separate issue?

**Comment by MakaraSok** [comment]
This is proved to be fixed for EuroLatin (SIL) keyboard, but not this particular keyboard [sil_madi.zip](https://github.com/keymanapp/keyman/files/6127445/sil_madi.zip). Probably because the `.kmn` explicitly define Shift + 'key' comparing with the EuroLatin keyboard.

**Comment by mcdurdin** [comment]
> but not this particular keyboard [sil_madi.zip](https://github.com/keymanapp/keyman/files/6127445/sil_madi.zip). Probably because the .kmn explicitly define Shift + 'key' comparing with the EuroLatin keyboard.

Yes, the keyboard does not define rules for how Caps Lock should be treated, so it ignores Caps Lock. This is not a bug in Keyman, this time 😁.

This keyboard is definitely a good candidate for the brand new 14.0 language feature [`&CasedKeys`](https://help.keyman.com/developer/language/reference/casedkeys). This  feature would add Caps Lock support to the keyboard with a single statement! Note that it requires the 14.0 compiler, but not 14.0 of Keyman.
