### ISSUE TITLE
bug(mac): another Configuration window get opened behind the current Configuration window

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4526]
**Describe the bug**

After finishing the installation of Sgaw Karen keyboard, a window of Configuration appears behind the current Configuration window showing Sgaw Karen keyboard in the keyboard menu.

![image](https://user-images.githubusercontent.com/28331388/109102793-31bb7f00-775c-11eb-9de5-c0c06389fe13.png)

**To Reproduce**

1. Go to 'Configuration > Download keyboard...'
2.Search for "Sgaw Karen" and click on it
3. Click "Install keyboard" and finish the installation

**Expected behavior**

Another Configuration window should not be appear behind the current one.

---

**Keyman for macOS:**
 - OS: macOS Mojave 10.14.4
 - Keyman version: 14.0.243-beta
 - Target Application: Configuration

---

**Keyboard**
 - Keyboard name: Sgaw Karen
 - Keyboard version: 1.0.1
 - Language name: Sgaw Karen

**Comment by mcdurdin** [comment]
Fixed

**Comment by MakaraSok** [comment]
Tested with 14.0.262-beta on macOS Mojave 10.14.6. This issue has been fixed.
