### ISSUE TITLE
chore(web): change insertText method parameter ordering

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#4529]
> I'd have kinda liked this to have a different parameter order:
> 
> ```suggestion
>   func insertText(_ keymanWeb: KeymanWebViewController, numCharsToLeftDelete: Int, numCharsToRightDelete: Int, newText: String)
> ```
> 
_Originally posted by @mcdurdin in https://github.com/keymanapp/keyman/pull/4427#discussion_r572418758_

> From Web:
>
> https://github.com/keymanapp/keyman/blob/58a2bda5344a4fa153f772614d644f30b919ec46/web/source/kmwbase.ts#L633-L638
> 
> https://github.com/keymanapp/keyman/blob/58a2bda5344a4fa153f772614d644f30b919ec46/web/source/dom/domOverrides.ts#L36-L38
> 
> From Android:
> 
> https://github.com/keymanapp/keyman/blob/58a2bda5344a4fa153f772614d644f30b919ec46/android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java#L2351-L2353
> 
> That said, both of these arose during 14.0 - there's no evidence of them in 13.0.  In their original versions, they closely matched the iOS function above:  `deleteLeft`, then `newText`.
> 
> Admittedly, the order was chosen b/c it's a new parameter, and new things - especially potentially-undefined parameters (b/c JS/TS) - go on the right-hand side.  That said, there _is_ a beauty to the order:
> 
> abc _de_ | _fg_ hij
> 
> With respect to the caret, we first delete-left, then insert the text at the caret's position, then delete-right if needed after the caret.  Though, I suppose that temporal order doesn't particularly matter - it's largely transitive as long as delete-lefts come before text insertion.  It does make sense with spatial order, though.
> 
> That said... I don't mind changing it... but only if we also change the parameter order in those locations.  And I think that's best left to a separate PR.

_Originally posted by @jahorton in https://github.com/keymanapp/keyman/pull/4427#discussion_r572505123_

**Comment by jahorton** [comment]
I'm still a bit wary about doing this, partly because of this block:

https://github.com/keymanapp/keyman/blob/58a2bda5344a4fa153f772614d644f30b919ec46/web/source/kmwbase.ts#L633-L638

While not actually documented on help.keyman.com, it is technically part of KMW's publicly-accessible API - we've made sure it has a stable name.  So, if someone happened to wire up KMW for their own ends and wanted to use this method... it'll change the signature on them.

This signature harkens back to https://github.com/keymanapp/keyman/pull/1732/, which was part of the 12.0 development cycle.

**Comment by mcdurdin** [comment]
Okay, given that discussion, let's close this one then. It's not terribly important 😄
