### ISSUE TITLE
bug(linux): install beta, but get alpha 

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4532]
**Describe the bug**

```
sudo add-apt-repository ppa:keymanapp/keyman-beta
sudo apt upgrade
sudo apt install keyman onboard-keyman
```
Run the above lines to get the alpha version of Keyman instead of the expected beta.

**To Reproduce**

1. Go to 'Terminal'
2. Remove the existing Keyman if there is one installed
3. Run the above three lines one by one
4. check Keyman version using `km-config --version`
5. See error - the alpha version is `15.0.17-alpha-local`

**Expected behavior**

The beta version should get installed instead of the alpha.

---

**Keyman for Linux:**
 - OS: Ubuntu 20.04.2 LTS
 - Keyman version: N/A
 - Target Application: N/A

**Comment by ermshiperete** [comment]
This will happen if you also have a repo with the alpha version enabled - the system will always install the highest version. Check `/etc/apt/sources.list` and the files in `/etc/apt/sources.list.d` for `keyman-alpha` and `linux.lsdev.sil.org` and comment those lines by putting `#` in front (e.g. `# deb http://linux.lsdev.sil.org/ubuntu focal-proposed main`).

Alternatively you can force the installation of a specific version. However, unless you take additional precautions the next system update will upgrade to the alpha version if that is enabled in the system. And, I think you need to explicitly specify the version for each (Keyman) dependency.

Installation would be something like:

```
sudo apt install keyman=14.0.247-1~sil1~focal ibus-keyman=14.0.247-1~sil1~focal  \
    python3-keyman-config=14.0.247-1~sil1~focal libkmnkbp0-0=14.0.247-1~sil1~focal 
```

**Comment by MakaraSok** [comment]
> This will happen if you also have a repo with the alpha version enabled - the system will always install the highest version. 

I was expecting the latest beta version. The highest beta version should have been installed instead of alpha.

I have commented out `deb http://linux.lsdev.sil.org/ubuntu focal-experimental main` in `/etc/apt/sources.list`, but I was not able to find `keyman-alpha` and `linux.lsdev.sil.org` in `/etc/apt/sources.list.d` -- here are all files in the directory:

![image](https://user-images.githubusercontent.com/28331388/109268356-897de700-783d-11eb-9c1e-ef8ca3bab194.png)


I haven't tried the alternative solution yet.

**Comment by MakaraSok** [comment]
Files for @ermshiperete 

https://drive.google.com/drive/folders/1-NPXal3b5bEGhA6GVqFx2M017IYptDl4?usp=sharing, https://drive.google.com/file/d/1odvt7XyW2EKEZO5l2W73ZIAVeMzfUxVQ/view?usp=sharing

**Comment by ermshiperete** [comment]
Thanks @MakaraSok !

There's a linux.lsdev.sil.org line in `sources.list` that slipped through. You can fix it by running this command in a terminal:

```
sudo sed -i 's@deb http://linux.lsdev.sil.org/ubuntu@# deb http://linux.lsdev.sil.org/ubuntu@' /etc/apt/sources.list
```

Also, to reduce future confusion, please remove the `keymanapp-ubuntu-keyman-daily-focal.list*` files - we renamed the keyman-daily repo, so these are no longer needed:

```
sudo rm /etc/apt/sources.list.d/keymanapp-ubuntu-keyman-daily-focal.list*
```

**Comment by MakaraSok** [comment]
Thank you for the instructions. The two commands were run and then uninstalled the current alpha version of Keyman.

After restarting the machine, the following commands were run to install the beta:

```
sudo add-apt-repository ppa:keymanapp/keyman-beta
sudo apt upgrade
sudo apt install keyman onboard-keyman
```

But the version of Keyman installed is still alpha: `15.0.18-alpha-local`.

**Comment by ermshiperete** [comment]
> But the version of Keyman installed is still alpha: 15.0.18-alpha-local.

Strange. `15.0.18-alpha-local` is not an official version. I don't know where that comes from. The official version in the alpha-channel ppa is `15.0.18-1~sil1~focal`, on llso `15.0.18-1+focal1`.

Please run `apt policy keyman` in a terminal window and post the output.

**Comment by MakaraSok** [comment]
Here is the output of `apt policy keyman`:
```
ubuntu@ubuntu:~$ apt policy keyman
keyman:
  Installed: 14.0.248-1~sil1~focal
  Candidate: 14.0.248-1~sil1~focal
  Version table:
 *** 14.0.248-1~sil1~focal 500
        500 http://ppa.launchpad.net/keymanapp/keyman-beta/ubuntu focal/main amd64 Packages
        500 http://ppa.launchpad.net/keymanapp/keyman-beta/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
     13.0.104-1~sil4~focal 500
        500 http://ppa.launchpad.net/keymanapp/keyman/ubuntu focal/main amd64 Packages
        500 http://ppa.launchpad.net/keymanapp/keyman/ubuntu focal/main i386 Packages
     11.0.103-2 500
        500 http://kh.archive.ubuntu.com/ubuntu focal/universe amd64 Packages
        500 http://kh.archive.ubuntu.com/ubuntu focal/universe i386 Packages
```

**Comment by ermshiperete** [comment]
That says that version 14.0.248 is installed. Where do you see version `15.0.18-alpha-local`?

**Comment by MakaraSok** [comment]
```
ubuntu@ubuntu:~$ km-config --version
km-config version 15.0.18-alpha-local
```

**Comment by ermshiperete** [comment]
What does `which km-config` give?

**Comment by ermshiperete** [comment]
I guess it gives `/usr/bin/km-config`.

I think I found the problem: you'll have to explicitly uninstall all keyman related packages. I think on your system `python3-keyman-config` is probably still at 15.0.18.

Please try and run `apt remove keyman ibus-keyman python3-keyman-config`, then try the installation again.

**Comment by MakaraSok** [comment]
Done and now the return of `km-config --version` is `14.0.251-beta`.
