### ISSUE TITLE
chore(ios): update default resources

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#4545]
The MTNT model for English has had a couple of updates since the release of 13.0.  We should bundle those in for 14.0.

**Comment by jahorton** [comment]
Note:  depends upon https://github.com/keymanapp/lexical-models/pull/121.

**Comment by darcywong00** [comment]
Could you have the ios build script get the latest version of sil_euro_latin and MTNT model?

See #3085

**Comment by jahorton** [comment]
> Could you have the ios build script get the latest version of sil_euro_latin and MTNT model?
> 
> See #3085

It's not that simple.  See this section:

https://github.com/keymanapp/keyman/blob/81d7722bf4840d43589de4bc8a3f632c34ed2574/ios/engine/KMEI/KeymanEngine/Classes/Migrations.swift#L28-L99

The iOS resource-update strategy kind of relies upon this area at present; it'd take some time and effort to rework.  Said area allows the app, upon update, to determine whether or not the user had removed our default resources in the past.  If the "migrations" area determines that they had deliberately nixed use of the default English keyboard, it'll avoid auto-installing the current default English keyboard - stuff like that.

**Comment by jahorton** [comment]
So... gave it some thought, and I think I've found a way forward that'll _make_ it that simple.  (See mention from PR above.)

I still need to implement the actual build-script update and related bits needed for the engine to adapt to the bundled version automatically, but that'll knock out the big roadblock, at least.
