### ISSUE TITLE
bug(windows): the welcome page gets hidden being the Configuration after the installation is done

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4549]
**Describe the bug**

After completing the installation of the keyboard, a welcome page is not shown. It seems like it gets buried under the Configuration window.

**To Reproduce**

1. Go to 'Configuration'
2. Click on 'Download keyboard...'
3. Choose a keyboard to install and finish the process

**Expected behavior**

The welcome page has usually been shown on top of the Configuration. 

**Screenshots**

![image](https://user-images.githubusercontent.com/28331388/109444442-d3e6aa00-7a6f-11eb-86be-8b7388f57bd7.png)

---

**Keyman for Windows:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman version: 14.0.248-beta
 - Target Application: Configuration

**Comment by mcdurdin** [comment]
I can't reproduce this error. Can you reproduce it with the latest beta?

**Comment by MakaraSok** [comment]
Tested with the latest beta of Keyman 14.0.258 on Windows 10 Pro 20H2 when installing a keyboard using "Install keyboard...". This does not happen when installing using "Download keyboard...".

IPA keyboard installed from a downloaded file on disk:
![image](https://user-images.githubusercontent.com/28331388/110887456-f0f76480-831c-11eb-964f-ae323111a6a8.png)

Acoli keyboard installed from keyman.com via the  "Download keyboard...":
![image](https://user-images.githubusercontent.com/28331388/110887744-65320800-831d-11eb-8424-48962dccb32f.png)
