### ISSUE TITLE
bug(windows): update 11 beta to 14 beta 

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4551]
**Describe the bug**

It seems impossible to upgrade from the latest 11-beta to the latest 14-beta. After clicking on the `Check for Updates`, the screen shows it updates to the latest stable instead of the expected latest 14-beta.

**To Reproduce**

1. Do a fresh install of `11.0.1314` 
2. Go to Support tab and click on 'Check for Updates'
3. See error

**Expected behavior**

When check for update on the beta version, the latest beta should be picked and upgraded to.

**Screenshots**

![image](https://user-images.githubusercontent.com/28331388/109452236-e79b0c00-7a81-11eb-9b4c-15ea6e87639e.png)

---

**Keyman for Windows:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman version: 11.0.1314-beta
 - Target Application: Configuration

**Comment by MakaraSok** [comment]
related: https://github.com/keymanapp/keyman/pull/4535#issuecomment-787627913

**Comment by mcdurdin** [comment]
Upgrading from 10, 11, 12 beta to 14 beta is not supported :) Future version beta upgrades should be supported (e.g 14.0 beta to 15.0 beta)

**Comment by MakaraSok** [comment]
> Upgrading from 10, 11, 12 beta to 14 beta is not supported :) Future version beta upgrades should be supported (e.g 14.0 beta to 15.0 beta)

Guide me how to test this then: https://github.com/keymanapp/keyman/pull/4535#issuecomment-786298511.

**Comment by mcdurdin** [comment]
> Guide me how to test this then: [#4535 (comment)](https://github.com/keymanapp/keyman/pull/4535#issuecomment-786298511).

Are the instructions I left on that PR sufficient now? If not perhaps we can discuss at standup. 😁
