### ISSUE TITLE
bug(windows): Simulate AltGr with Ctrl+Alt - checked, but no output when triggered in Windows' Notepad

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4557]
**Describe the bug**

The expected character is not produced in Windows' Notepad when Ctrl+Alt+(anyKey) is triggered while the "Simulate AltGr with Ctrl+Alt" is checked. Elsewhere (i.e. LibreOffice, MS Office, Chrome, FireFox and MS Mail etc), the expected character is output.

**To Reproduce**

1. Install Khmer Angkor keyboard
2. Press AltGr+`K_A` and confirm that a plus sign is output
3. Now, go to the Option tab in the Configuration and check 'Simulate AltGr with Ctrl+Alt'
4. Press 'Ctrl+Alt+`K_A`' and see error (OSK does show the appropriate layout, but nothing is output as expected)

**Expected behavior**

In Notepad, the expected character should be output. In this case, when the option is checked, a plus sign should be produced.

---

**Keyman for Windowsx:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman version: 14.0.248-beta
 - Target Application: Notepad

---

**Additional context**

cf: https://github.com/keymanapp/keyman/issues/4289#issuecomment-786506389

**Comment by mcdurdin** [comment]
Resolved in #4622.
