### ISSUE TITLE
feat(developer/compilers) Propagate isRTL to .model_info

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#4567]
Related to #2556 and follow-on to #4559 where Developer adds support for `isRTL`.

> Does this also update .model_info?

No, that's entirely separate -- can you open an issue on that?

_Originally posted by @mcdurdin in https://github.com/keymanapp/keyman/issues/4559#issuecomment-788523946_

**Comment by mcdurdin** [comment]
This is not currently easy to pull out of the model (requires compiling it and loading it to evaluate) so I will put it as low priority.

**Comment by mcdurdin** [comment]
not needed, see discussion in #4064.
