### ISSUE TITLE
bug(android/app): backspace does not work after suggestions

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4575]
**Describe the bug**

With the predictive text enabled on either EuroLatin (SIL) or Khmer Angkor, tap to choose three words in a row from the banner and then move the cursor back to the end of the first word to delete it and then move the cursor to the end of the last word to delete all only to find that the backspace stop responding. Moving the cursor around does not help either.

**Expected behavior**

The backspace should function as expected regardless of where it's placed in the text editor

**Screenshots**

EuroLatin (SIL)
https://youtu.be/TX4jN1fIBgE

Khmer Angkor
https://youtu.be/QBQ71ev2L0g

---

**Keyman for Android:**
 - Device: Pixel 2 API 29 - emulator (also on physical device Galaxy S9+)
 - OS: Android 10
 - Keyman version: 14.0.248-beta
 - Target application: Keyman

**Comment by MakaraSok** [comment]
This only happens within Keyman app.

**Comment by jahorton** [comment]
It's hard to say without a more thorough investigation, but this "smells" somewhat like a context desync - where the embedded KMW thinks the current context is different from what the Java-side code has.

**Comment by darcywong00** [comment]
Does this work fine on iOS?

**Comment by jahorton** [comment]
This works fine on iOS (at least in-app).

Also of note:  the fact that this is only occurring within the Android app.  That makes me more suspicious of our Android context-management code; I know that the iOS app has had context-resetting issues arise from its extra in-app context-management code before.

**Comment by darcywong00** [comment]
This may be just the Keyman for Android in-app text field. When I reproduce the steps on the Chrome omnibar, the backspace works.

**Comment by darcywong00** [comment]
Fixed in #4636
