### ISSUE TITLE
feat(developer): support resizing of edit boxes on touch with the resizing handle

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4616]
**Describe the bug**

Test keyboard on web using Chrome shows double text layout when dragging the bottom right corner to expand the text box.

**To Reproduce**

1. Go to 'https://github.com/keymanapp/keyboards/pull/1477'
2. Open the keyboard project
3. Try and open Test Keyboard on web
4. Type at a least three lines and then expand the text box by dragging the bottom right corner of the box
5. See error

**Expected behavior**

There should only be one text box.

**Screenshots**

![image](https://user-images.githubusercontent.com/28331388/110081325-5a77f000-7dbe-11eb-80c4-1ccbcbbd7ac9.png)

---

**Keyman for Windows/macOS/Linux:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman version: 14.0.252-beta
 - Target Application: Chrome Version 89.0.4389.72 (Official Build) (64-bit)

---

**Keyboard**
 - Keyboard name: Brao (SIL)
 - Keyboard version: 1.0 (in development)
 - Language name: Lave (Brao)

**Additional context**

https://github.com/keymanapp/keyboards/pull/1477

**Comment by mcdurdin** [comment]
> * Type at a least three lines and then expand the text box by dragging the bottom right corner of the box

This is not currently supported in KeymanWeb. We should support it, of course... In this situation, KeymanWeb simulates the normal edit box because it needs to pretend that the keyboard is active without actually focusing the edit box.

**Comment by mcdurdin** [comment]
Fixed by #7343 (by removing the touch alias elements and working with native elements)
