### ISSUE TITLE
bug(web): key-id aliasing results in issues for predictive text, recorder module

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4617]
**Describe the bug**

The suggestion on the banner does not match the character directly to the left of the cursor. Three words begins with a different character.

![Screenshot_1614931057](https://user-images.githubusercontent.com/28331388/110085016-2bb04880-7dc3-11eb-8a93-d3068d2dc726.png)

**To Reproduce**

1. Install this keyboard and the its lm ([brao_keyboard_and_lm.zip](https://github.com/keymanapp/keyman/files/6088954/brao_keyboard_and_lm.zip))
2. In the Keyman text editor area, press the key on the top left -- output ក
3. See error

**Expected behavior**

When ក is pressed, words beginning with ក should be shown on the suggestion, not those beginning with គ.

---

**Keyman for Windows:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman version: 14.0.252-beta
 - Target Application: Chrome Version 89.0.4389.72 (Official Build) (64-bit) and Keyman app for Android

**Keyman for Android:**
 - Device: Pixel 2 API 29 - emulator
 - OS: Android 10
 - Keyman version 14.0.252-beta
 - Target application: Keyman 

---

**Keyboard**
 - Keyboard name: Brao (SIL)
 - Keyboard version: 1.0
 - Language name: Lave (Brao)

**Additional context**

When click away and click back to the right of the character (say, ក), then the expected words are shown in the banner.

**Comment by jahorton** [comment]
I expect this to be related to the underlying problems we saw with some of the tests on #4647, though the suggestions shouldn't be butting up against the iOS caret-management issues.  Unless it's due to the overly-eager in-app context refreshes...

Will require some more investigation.

**Comment by jahorton** [comment]
Nope.  Something _really_ weird's going on here - KMW's not getting the touch distributions right!

Pressing the top-left key on the keyboard, as seen below...

![Screen Shot 2021-03-16 at 9 27 54 AM](https://user-images.githubusercontent.com/25213402/111247291-4e9bf180-863a-11eb-8461-b375c3917af1.png)

Gives this internally:

<img width="1424" alt="Screen Shot 2021-03-16 at 9 27 47 AM" src="https://user-images.githubusercontent.com/25213402/111247327-607d9480-863a-11eb-8a65-92d75ddf5773.png">

So, it's not the lm-layer's fault - it's Web's.

**Comment by jahorton** [comment]
... I see what it is now.  Web's not properly handling the key names b/c it's really not expecting the sort of key definitions being used by this keyboard.

Both ក and គ use the same key name:  `K_K`, with the latter also applying a `shift` modifier.  Unfortunately, the key-distribution algorithm currently... uh... _doesn't look at the modifiers_.  So, the two keys get conflated.

Kinda surprising we never caught this until now!

**Comment by jahorton** [comment]
For more reference:

<img width="1424" alt="Screen Shot 2021-03-16 at 9 46 01 AM" src="https://user-images.githubusercontent.com/25213402/111248425-7429fa80-863c-11eb-9277-4ff7e2d1e2b9.png">

So yeah, the two keys look exactly the same.  In fact, I'm pretty sure the KMW recorder system would be broken against this keyboard as well, as in HTML land, the two keys' elements' IDs are also completely equal.  The reason for _this tidbit_ goes back earlier than KMW 10, not that it mattered then - we didn't have either the 'recorder' system to facilitate testing or predictive text at that time.

Of course... it very much matters now.

**Comment by mcdurdin** [comment]
> the two keys' elements' IDs are also completely equal

eep. Seems like the key id should be modified, shouldn't it, if we use a non-default modifier?

`default+shift-K_K` or something like that?

**Comment by mcdurdin** [comment]
FWIW, the key ids are a problem anyway, because they are a little too generic; they should have been prefixed with `kmw-<keyboard_id>-` to prevent stomping on other names used by a site. But that may be a big problem to fix.

**Comment by jahorton** [comment]
> > the two keys' elements' IDs are also completely equal
> 
> eep. Seems like the key id should be modified, shouldn't it, if we use a non-default modifier?
> 
> `default+shift-K_K` or something like that?

I'd go with `default-K_K+shift`:  we use the `-` to split the key's OSK layer from the key ID.

My initial thought was in this direction as well - both for the element and in the key-distribution map.

... this may cause issues for the Recorder though, as there's a chance some of our 'recorded' test sequences will be affected.  If so, that'll cascade into some fun maintenance for our unit tests.  I can probably write in a decent enough hack-workaround.  Probably.

------

Now, about when to append vs not append:

I'd say that it's probably simplest if we don't append the modifier if the modifier matches the current layer.

- default layer:
    - ក uses no modifiers, so should be "default".  No modifier `+`-suffix.
    - គ uses a modifier, so it would use `+shift` as an ID 'suffix'.
- shift layer:
    - ុ does not use a modifier, acting as a 'desktop' layout `K_U`.  This does *not* match the current layer, so it receives a `+default` suffix.
    - ូ does use a modifier, which matches the current layer of `shift`.  As it matches, no ID suffix is applied.

That sound reasonable?

**Comment by mcdurdin** [comment]
Yes that sounds reasonable. This could be a breaking change for custom CSS or apps that do funky things with keys (e.g. learnthaiping.com) but it is fixing a bug so worth doing. Just needs to be documented as a breaking change.

The whole kmw-keyboardid- prefix thing should be left until the future.

**Comment by MakaraSok** [comment]
Tested with 14.0.266-beta on Android 10 API 29 emulator. The prediction works as expected when there is only one character to the left the caret.
![Screenshot_1616396873](https://user-images.githubusercontent.com/28331388/111952764-32a3be80-8b18-11eb-827c-d5e597470843.png)
