### ISSUE TITLE
bug(android/engine): Support emitting carriage return as last character after text

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#4645]
Issue found while testing #4636

>Technically, we don't support emitting text after the carriage return; we support emitting the carriage return as the last character after other text though.
>
>* `+ 'a' > [K_ENTER] 'foo'` should never happen.
>
>But:
>
>* `'bar' + [K_ENTER] > 'foo' [K_ENTER]` could happen (although it will be more [verbose than that in code]
>(https://help.keyman.com/developer/language/guide/groups#:~:text=If%20the%20final%20group%20processed%20is%20a%20context%20and%20keystroke%20group)).
>
>Will that work at present? Do we need to open a separate issue on that?

_Originally posted by @mcdurdin in https://github.com/keymanapp/keyman/pull/4636#discussion_r591818714_

----

I implemented the keyboard from keymanapp/help.keyman.com#346 and found:
| Keystroke: <kbd>s</kbd><kbd>Enter</kbd> | result |
|----------|-------|
| Expected Result | `ς\n` |
| unminified KMW test page | `ς\n` |
| Keyman for Android in-app | `σ\n` |
| Keyman for Android system keyboard (Keep app) | `σ\n` |

**Comment by darcywong00** [comment]
The .kmn from help.keyman

```
begin Unicode > use(main)

group(main) using keys

+ 's' > 'σ'
'σ' + [K_ENTER] > 'ς' use(final)

group(final) using keys
c Empty final group causes keystroke to be emitted
```

**Comment by jahorton** [comment]
This will be highly related to https://github.com/keymanapp/keyman/issues/4498 and should probably be delayed until 15.0 as a result.

**Comment by jahorton** [comment]
iOS gives the same incorrect output, as the embedded "text changed!" notifier requires that KMW be aware that **_a_** rule (not necessarily the final one!) was applied; that's #4498's primary concern.

**Comment by mcdurdin** [comment]
Yes, we'll delay to 15.0, but let's see if we can tackle it early in 15.0 and back-port. This is a longstanding bug which breaks many keyboards handling of Enter. The example given of final sigma is a common one.

**Comment by jahorton** [comment]
> Yes, we'll delay to 15.0, but let's see if we can tackle it early in 15.0 and back-port. This is a longstanding bug which breaks many keyboards handling of Enter. The example given of final sigma is a common one.

Keep in mind that #4498 is also entangled with #4499, so we _will_ need some design work & planning for that.  That said... I do like the idea of backporting it.  For reference, #4350 (the draft PR that got delayed for these issues) on iOS gives **_the right output_**, `ς\n`.
