### ISSUE TITLE
Regression: Keyman 10.0.98 shows a blank keyboard after install

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#467]
This is on an iPhone 7 both with an upgrade install and a clean install:

![image](https://user-images.githubusercontent.com/4498365/33522776-2b7ab458-d827-11e7-9384-7385f6556b5a.png)

10.0.95 appears to function correctly.

**Comment by gabrielwong** [comment]
Ran both a debug and release build of the 10.0.98 tag on the original device with this bug and could not reproduce. Also unable to reproduce on simulator.

**Comment by mcdurdin** [comment]
Let's run another TestFlight build and if that works we'll close this as no-repro ... I guess.

**Comment by gabrielwong** [comment]
Problem is that #456 breaks iOS since the directory structure has not yet been migrated.
