### ISSUE TITLE
bug(linux): EuroLatin keyboard only works at beginning of line in gedit

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/keyman#4678]
After installing the EuroLatin keyboard and assigning it to a language I can switch to that language and typing the key combinations works (e.g. `:a` to get `ä`) in gedit. If I then switch to English and back to EuroLatin, the key combinations no longer work in gedit if I try to continue on an existing line.

Things still work in Firefox, or after restarting gedit. Things work on a new line.

**Comment by ermshiperete** [comment]
Things don't always work. Sometimes typing `%a` results in `%`, with the `ǎ` quickly disappearing and then being deleted again. This is probably caused by the race condition (#1489)

**Comment by ermshiperete** [comment]
@MakaraSok Can you please test my fix once it's available in the package? Should also be tested with some other keyboards.

**Comment by mcdurdin** [comment]
Closing as fixed but @MakaraSok can still test :)

**Comment by MakaraSok** [comment]
Tested with 14.0.266-beta on Ubuntu 20.04.2 LTS. The EuroLatin (SIL) keyboard works as expected in FireFox, LibraOffice and TextEditor when typing <kbd>:</kbd> <kbd>a</kbd> -- the result is always the desirable one (ä).
