### ISSUE TITLE
bug(ios): the active lexical model doesn't automatically refresh when updated.

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#4685]
**Describe the bug**
See:  title.  We only noticed this one because it looked like case-sensitivity was broken with the MTNT model via the repro steps below.

**To Reproduce**

While this isn't the only way to reproduce the underlying behavior, it's certainly the most _visually-distinct_ yet common-case way to reproduce it.

1. Install Keyman for iPhone and iPad 14.0.258-beta or 14.0.259-beta on a fresh device (or within the Simulator)
    - Do NOT install a more recent version - those are the cutoff!  (Refer to https://github.com/keymanapp/keyman/pull/4656#issuecomment-799629509)
2. Verify that case sensitivity is missing (as expected):  With `sil_euro_latin` active for the English language, attempt to type a capitalized word.
    - If the suggestions are all capitalized, return to step 1 - that setup is fairly critical!
    - Aside from the quoted suggestion that matches the current input, the other suggestions should be lowercase - MTNT 0.1.4 is the default lexical model for that Keyman version.
3. Via menus, navigate to Settings > Installed Languages.
4. You should be notified that resource updates are available.  Choose to update resources and wait for completion of the process.
    - Optional:  you should be able to navigate to the "English" submenu of that screen and drill down for info on the MTNT model, verifying it is at least version 0.1.6 as a result.
5. Exit Settings and return to the main screen.
6. Repeat step 2.

The behavior seen in step 6 will match the behavior seen in step 2.

**Expected behavior**
After step 5, step 6 should display case-sensitive suggestions:  MTNT 0.1.6 has case-sensitivity enabled.

The problem:  internally, iOS hasn't refreshed the model, so 0.1.4 is still active.

**Workaround**
After step 5, you have two options:

- Kill and restart the app
- Temporarily change keyboards and return.
  - If following the repro above, this will require installing a new keyboard, since you can't "swap" with just one keyboard.

Either approach will force-refresh the app's keyboard, allowing MTNT 0.1.6 to load.

---

**Keyman for iPhone/iPad:**
 - Device: any
 - OS: any
 - Keyman version:  14.0.
 - Target application: 

Note: the repro will only work for 14.0.x-beta **up to 14.0.259**, as https://github.com/keymanapp/keyman/pull/4656 updates the default resource set to MTNT 0.1.6 for subsequent builds.

**Comment by mcdurdin** [comment]
Closing as fixed
