### ISSUE TITLE
bug(windows/developer): attempt to upgrade Developer after upgrading the Desktop to 14.0.262-beta

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4700]
**Describe the bug**

An error after an attempt to check and install an upgrade of Developer to 14.0.262-beta.

Details for error report for Keyman app:
  Application Identifier: tike-14.0.259-beta
  Error Identifier: 922EF46AE9B045C2F6AF7E27739D9E55

**Expected behavior**

The upgrade of Developer following the upgrade of Desktop should get through without crashing.

---

**Keyman for Windows:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman version: 14.0.258-beta upgrading to .262-beta
 - Target Application: Keyman Developer

**Comment by mcdurdin** [comment]
See also #5001.

**Comment by mcdurdin** [comment]
Review in 15.0 beta cycle. Probably fixed.

**Comment by mcdurdin** [comment]
There are now no dependencies between Developer and Keyman for Windows. Fixed.
