### ISSUE TITLE
bug(developer/compilers): lexical model compiler does not properly store version in compiled models 

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#4705]
**Describe the bug**
As part of the new model-definitions object baked into lexical models with 14.0, the compiler is supposed to store its version within the model.  This isn't properly working.

Block that should be storing the version:
https://github.com/keymanapp/keyman/blob/ae6068557eefed62e9fb87ea07787744ec583e70/developer/js/source/lexical-model-compiler/model-definitions.ts#L48-L53

That defines a basic structure and inline-initializes its default value, the version string.  Or, well... it _should_.

Resulting code (from compiled MTNT 0.1.6):
```
(function() {
'use strict';
let definitions = {
  defaults: {
    version: "undefined",
    applyCasing: function defaultApplyCasing(casing, text) {
      // ...
```

Fortunately, this doesn't actually break anything right now.  It should probably be fixed at some point, though.

**Expected behavior**
I'd expect to see the version of the lexical-model compiler that was used to compile the model.  It should serve a role similar to the `KVER` field used in compiled JS keyboards.

Current as of 14.0.262-beta.

**Comment by mcdurdin** [comment]
Fixed in #6539, released in #6525, 16.0.12-alpha.
