### ISSUE TITLE
bug(windows): setup can cause an error in keymanx64 when it continues after Windows restart

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#4724]
**Describe the bug**

If Keyman Setup needs to restart Windows to complete setup, Keyman can startup (with its 'start with Windows' setting) while Setup is doing its final tasks. This can cause keymanx64 to try to start twice or similar.

This was discovered while testing #4649.

![image](https://user-images.githubusercontent.com/28331388/111593762-e21d2000-87fc-11eb-9ae9-81149608654e.png)

---

**Keyman for Windows/macOS/Linux:**
 - OS: Windows 10 20H2 
 - Keyman version: 14.0.264-beta

**Comment by MakaraSok** [comment]
This issue has been fixed at https://github.com/keymanapp/keyman/pull/4726#issuecomment-802609471.
