### ISSUE TITLE
docs(android): help-docs polish needed

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#4733]
General:

- [ ] Is there a page for "sharing keyboard / dictionary packages"?
    - Refer to the latter half of https://help.keyman-staging.com/products/iphone-and-ipad/current-version/basic/sharing-keyboards. 

https://help.keyman-staging.com/products/android/current-version/start/installing-keyboards

Starting at step 5:

> Once the download is complete...

- [x] Everything after that within the same sentence is very awkwardly worded.
    - I could _almost_ go with "you'll see [a] 2 or 3"... but then you don't really "see" a "process".
    - Maybe "installation wizard"?
- [x] `a)` - ... so the _user_ needs to display the readme.htm documentation?  Or they'll be _presented with it_?
    - The shift in perspective here is quite jarring.
- [x] `c)` - same as with `a)`.

----

Minor nit:

https://help.keyman-staging.com/products/android/current-version/start/enabling-system-keyboard

CTRL+F:  "you'll see a keyboard icon at the bottom right"

- [x] A small bit of MS Paint / other image editor work to highlight that icon would go a long way.
    - A few ideas:  
        - Circle it.
        - Copy the image, then crop it down to just the icon, and inline that.

**Comment by bravogeorge** [comment]
Hello! I'm an aspiring technical writer, and I would love to offer my assistance if you still need help with this.

**Comment by jahorton** [comment]
> Hello! I'm an aspiring technical writer, and I would love to offer my assistance if you still need help with this.

Sure!  Android's help documentation is managed within https://github.com/keymanapp/keyman/tree/master/android/help and uses Markdown formatting, so it should be pretty simple to edit.

**Comment by bravogeorge** [comment]
Great! i made commits created pull request for both items you requested. Hope you like them. 

Please note. I have watched tutorials, read help articles but I am still very new to contributing/collaborating on github and I'm doing my best. So hopefully all my commits/pull requests went through properly. Thank you so much!

**Comment by darcywong00** [comment]
Thanks again @bravogeorge for tackling this issue. Now we can close it 👍

**Comment by bravogeorge** [comment]
No problem! Thanks for the opportunity. Keep me in mind if you need any more contributions in the future!
