### ISSUE TITLE
bug(windows): the message after updating a keyboard from the Configuration

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4746]
**Describe the bug**

This message pops up after a keyboard completes its update from older version to a newer version available on the server.
![image](https://user-images.githubusercontent.com/28331388/111962535-fdea3400-8b24-11eb-925e-16ba348353cb.png)

From the user point of view, this message is confusing because the expected message would something along the line that "this keyboard has been updated to the latest version successfully."

**To Reproduce**

1. Download and install this '[Khmer Angkor v1.0.6](https://drive.google.com/file/d/1xxwhji-x16n-7OiRyg-RVV1_GxA-kWtP/view?usp=sharing)'
2. Go to Configuration > Support and click on 'Check for Updates'
3. Follow the screen to finish the installation

**Expected behavior**

The message should confirm that the keyboard has been updated successfully.

---

**Keyman for Windows:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman version: 14.0.266-beta
 - Target Application: Keyman Configuration

---

**Keyboard**
 - Keyboard name: khmer_angkor
 - Keyboard version: 1.0.6 --> 1.0.7
 - Language name: Khmer

**Comment by mcdurdin** [comment]
This message is no longer shown.
