### ISSUE TITLE
bug(windows): Error when clicked on "Download keyboard..." in Keyman 11

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4747]
**Describe the bug**

![image](https://user-images.githubusercontent.com/28331388/111966031-07759b00-8b29-11eb-9b86-f2dbf1b0bc17.png)

This error pops up when trying to install a keyboard from within the Configuration using "Download keyboard..." button.

**To Reproduce**

1. Install Keyman 11 Stable and then open Configuration
2. Click on 'Download keyboard...'
3. See error

Diag [report](https://drive.google.com/file/d/1QXh3XvDrB2lCHtNfTmC-OU8LuD0qdlK_/view?usp=sharing) for Marc.

**Expected behavior**

A list of keyboards should be shown up.

---

**Keyman for Windows:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman version: 11.0.1361 stable
 - Target Application: Keyman Configuration

**Comment by MakaraSok** [comment]
Additional Context: When clicking on "Exit Application", the application does not close. Keyman is still running even after then.

**Comment by mcdurdin** [comment]
Resolved; the new web server for keyman.com needed its cdn cache refreshed (now configured in the post deployment actions).
