### ISSUE TITLE
bug(windows): upgrade to .266 beta via .265-beta from 11.0.1361 gives an error

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4748]
**Describe the bug**

When making an attempt to upgrade to 14.0.266-beta by installing 14.0.265-beta on 11.0.1361 stable, this error occurs.

![image](https://user-images.githubusercontent.com/28331388/111969450-d26b4780-8b2c-11eb-950f-5d2a35703d08.png)

Keyman 14.0.266-beta is running as usual despites this error.

**To Reproduce**

1. Download and install 14.0.265-beta on top of 11.0.1631 stable 
2. Click to get the latest update of the beta -- 14.0.266-beta
3. Restart the machine

**Expected behavior**

No error message should be shown.

---

**Keyman for Windows:**
 - OS: Windows 10 20H2 x64
 - Keyman version: 11.0.1361 > 14.0.265-beta > 14.0.266-beta
 - Target Application: Keyman

**Additional context**

It looks like a copy of Keyman has already been running before it triggered once again.

**Comment by mcdurdin** [comment]
We haven't seen this reproducing, so closing. Please re-open if you have a repro.
