### ISSUE TITLE
bug(developer): test a keyboard in Developer even when Keyman Desktop is a different version

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4756]
**Describe the bug**

![image](https://user-images.githubusercontent.com/28331388/112089671-b4512600-8bc4-11eb-88b5-c2f1eef776f9.png)

It seems weird, but it does happen. Keyman Developer is running testing/debugging without crashing even when the versions of itself and Keyman Desktop are different.

**Expected behavior**

Usually, Developer would notify that the Desktop version is different from the Developer and it has to be updated to a consistent version.

**Question**
Is it now possible to have different versions of Developer and Desktop and able to run keyboard debugging and testing?

---

**Keyman for Windows:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman version: 14.0.235-beta
 - Target Application: N/A

**Keyman Developer:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman Developer version: 14.0.267-beta

---

**Additional context**

This was encountered when trying to repro an error when updating Keyman Developer before Keyman Deskop from 14.0.235-beta to the latest beta (.267-beta).

**Comment by mcdurdin** [comment]
You can get away with mixing 14.0.x with 14.0.x, but nothing is guaranteed when using alpha or beta versions (due to bug fixes and changes in interfaces). 

When using stable versions, 14.0.x with a different 14.0.x will normally be fine.
