### ISSUE TITLE
bug(developer): update Developer crash

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4757]
**Describe the bug**

When making an attempt to update Keyman Developer from 14.0.65-beta to the latest version, a crash occurs.

Details for error report for Keyman app:
  Application Identifier: tike-14.0.262-beta
  Error Identifier: E34BB96AAA474D74364FB2025D622C2C

But after closing the error box, it looks like the Developer has been updated to 14.0.267-beta successfully.

**To Reproduce**

1. Install Keyman Desktop and Developer 14.0.265-beta
2. In Keyman Developer go to 'Check for update...' on Help menu
3. Click on "Install" to update
4. Restart and Open Developer
5. See error

**Expected behavior**

The Developer should not crash after being updated.

---

**Keyman Developer:**
 - OS: Windows 10 20H2 x64
 - Keyman Developer version: 14.0.265 > 14.0.267-beta
 - Target Application: Keyman Developer

---

**Additional context**

This error occurs when updating Developer before the Keyman Desktop.

**Comment by mcdurdin** [comment]
This looks like it is happening on shutdown of TIKE.exe, and perhaps is due to a disorderly shutdown due to the upgrade trigger.

**Comment by MakaraSok** [comment]
While working on Developer, notice a new update on the web then trigger update on the Developer 14.0.267, but then again crash occurs:

Details for error report for Keyman app:
  Application Identifier: tike-14.0.267-beta
  Error Identifier: 49F0AF317D9C46B0C329EF4F97DB1971

**Comment by MakaraSok** [comment]
Updating Developer from 14.0.268 to 14.0.270 crashes:

![image](https://user-images.githubusercontent.com/28331388/112244967-a4981700-8c82-11eb-95eb-b18c178117dd.png)

Details for error report for Keyman app:
  Application Identifier: tike-14.0.268-beta
  Error Identifier: 57464305673049BF5DC9DA2D2E151D8E
