### ISSUE TITLE
bug(web): CapsLock issues when using "Test Keyboard on web" from Keyman Developer

### ISSUE THREAD

**Issue by DavidLRowe** [keymanapp/keyman#4766]
**Describe the bug**
When using the "Test Keyboard on web" option from Keyman Developer, the CapsLock button on the OSK doesn't always reflect the physical keyboard's CapsLock state.

**To Reproduce**
For this sequence, use the "engram" keyboard, version 1.3 (release/e/engram)
The engram.kmn file includes these rules:
```
+ [NCAPS K_A] > 'h'
+ [NCAPS SHIFT K_A] > 'H'
+ [CAPS K_A] > 'H'
+ [CAPS SHIFT K_A] > 'h'
```

With Keyman Developer (version 14.0.233.0 was used here), open engram.kpj, then engram.kmn
select Build tab, Compile Keyboard button, Test Keyboard on web button, Open debugger in local browser
In browser (Chrome version 88.0.4324.182 (64-bit) was used here):

Action 1: type 'a'
Result: h
Comments: as expected

Action 2: type Shift+'a'
Result: H (Shift buttons on OSK are highlighted when Shift key depressed)
Comments: as expected

Action 3: press and release CapsLock
Result: CapsLock light on keyboard illuminates (Caps button on OSK is not highlighted)
Comments: would expect highlight of OSK Caps button

Action 4: type 'a' (with CapsLock on)
Result: H (Caps button on OSK remains unhighlighted)
Comments: as expected (except that OSK Caps button not highlighted)

Action 5: type Shift+'a' (with CapsLock on)
Result: h (when Shift key depressed, Shift buttons and Caps button on OSK are highlighted; when Shift key released, Caps button remains highlighted)
Comments: as expected

Action 6: press and release CapsLock
Result: CapsLock light on keyboard goes out (Caps button on OSK still highlighted)
Comments: would expect OSK Caps button to be unhighlighted

Action 7: on OSK click 'a' key (labeled 'h')
Result: H (with Caps button highlighted)
Comments: would expect 'h' since keyboard CapsLock is off

Action 8: press and release Shift on keyboard
Result: nothing: Shift buttons on OSK do not highlight when Shift key depressed
Comments: would expect Shift buttons on OSK to highlight

Action 9: on OSK click Shift button
Result: both Shift buttons and Caps button are highlighted
Comments: sort of as expected!

Action 10: on OSK click 'a' key (now showing 'H')
Result: H (Caps button remains highlighted, but both Shift buttons now unhighlighted
Comments: might expect 'h' rather than 'H' since OSK has both Caps and Shift highlighted

Action 11: on OSK click Caps button
Result: nothing: Caps button remains highlighted
Comments: not sure what to expect! Would the OSK turn the actual keyboard CapsLock on?

---

**Keyman Developer:**
 - OS: Windows 10 20H2 x64
 - Keyman Developer version: 14.0.233.0

---

**Keyboard**
 - Keyboard name: engram
 - Keyboard version: 1.3
 - Language name: English

**Comment by mcdurdin** [comment]
I believe that all of these are addressed in Keyman 15, except for Action 11 -- where we do not have the system capability to turn off Caps Lock. Given this I will go ahead and close this as fixed by #5456.
