### ISSUE TITLE
bug(linux): html tags in package description in keyboard's About page

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4769]
**Describe the bug**

![image](https://user-images.githubusercontent.com/28331388/112242658-e1620f00-8c7e-11eb-9a76-bebaf12b471e.png)

The description is shown with these html tags `<p>...</p>` when triggered it from the <kbd>About</kbd> button on the Keyman Configuration.

**Expected behavior**

The tags should not be shown explicitly.

---

**Keyman for Linux:**
 - OS: Ubuntu 20.04.2 LTS -->
 - Keyman version: 14.0.270
 - Target Application: Keyman

---

**Keyboard**
 - Keyboard name: khmer_angkor
 - Keyboard version: 1.0.7
 - Language name: Khmer

**Comment by darcywong00** [comment]
I wonder if that comes from https://api.keyman.com/keyboard/khmer_angkor

which looks like https://github.com/keymanapp/keyboards/blob/master/release/k/khmer_angkor/khmer_angkor.keyboard_info#L13

**Comment by ermshiperete** [comment]
See discussion in https://github.com/keymanapp/keyman/pull/8057#issuecomment-1401469104
