### ISSUE TITLE
bug(web/bookmarklet): OSK does not show when multiple bookmarklets are used on the same page

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#4785]
**Describe the bug**
OSK does not show when multiple bookmarklets are used on the same page.

**To Reproduce**
1. Go to keymanweb.com
2. Select two or more languages, ideally with different scripts.  For each one, save its bookmarklet.
3. Go to google.com
4. Use **one** bookmarklet.
5. Defocus the search element, then click it.
    - The OSK should then appear.
6. Without refreshing, use another bookmarklet.
7. Repeat step 5.
    - No matter what you try, the OSK will not appear.
        - Like, I've even tried manually calling the OSK-display functions via console - _still_ no effect.
        - The hide/show OSK button?  Yeah, no dice.
    - I've noted via Inspector that the OSK may even have its `display` property change as usual... but it still won't appear!

**Expected behavior**
Extra bookmarklets should "combine" in a way that lets the OSK continue operating.  Note:  the Toggle UI _does_ combine the bookmarklets.  Each keyboard, when selected, _actually works_.  It appears to be just an OSK issue.
- That said... I'm actually surprised that it works as well as it does.
    - KeymanWeb's init process isn't exactly designed to load multiple copies of the script on the same page without issues.

**KeymanWeb:**
 - OS: macOS X 10.15.7
 - Browser: Firefox (others untested)
 - KeymanWeb Version: 14.0.270

**Comment by jahorton** [comment]
I think the best way forward here is to simply have the bookmarklet check to see if KMW is already active on a page.  If it is... just bypass reloading KMW entirely.

For that, we'll need to change the code that's used to generate bookmarklets.  A simple little 'if-else' check that sees if KMW is already active.

Granted, that won't retroactively fix old bookmarklets that people have stored.  On the plus side, they won't be redownloading KMW multiple times on the same page - only the first bookmarklet would be needed to initialize KMW.

If done with care, there's a decent chance we could even set things up to allow a bit of async.  Like...

```
let kbdLoader = function(kmw) {
  kmw.addKeyboards(<!-- spec goes here -->);
}

if(window['keyman'] instanceof Promise) {
  window['keyman'].then(function(kmw) {
    kbdLoader(kmn);
  });
} else if(<!-- keymanweb is already loaded --> {
  kbdLoader(window['keyman']);
} else {
  <!-- build script tag to load keyman -->
  <!-- construct Promise that resolves on script-tag load -->
  window['keyman'] = <!-- constructed Promise -->
  window['keyman'].then(function(kmw) {
    kbdLoader(kmn);
  });
}
```

**Comment by jahorton** [comment]
Notes for if we do decide to take this approach:

https://github.com/keymanapp/keyman.com/blob/fc79e24c5b798b92c11170cd1aada8049181e02a/bookmarklet/install-bookmarklet.js#L3-L11

https://github.com/keymanapp/keymanweb.com/blob/a73bcfff201e44093f628e46fd47d3687266c7fa/cdn/dev/js/kmwlive.js#L442-L466

Looks like that fellow's a bit WET there across the sites.

**Comment by mcdurdin** [comment]
Agreed. I think we DRY first and then fixup this issue. Make the bookmarklet generator into shared code (although our shared code across sites is currently still not really great, perhaps we can share it on s.keyman.com?)

Even if we can't fix for existing bookmarklets, we should certainly try and fix going forward. The suggested way forward looks good but wonder if we can DRY it a bit more by moving the tri-load pattern into a script on s.keyman.com rather than embedding it into the bookmarklet?

**Comment by jahorton** [comment]
> Even if we can't fix for existing bookmarklets, we should certainly try and fix going forward. The suggested way forward looks good but wonder if we can DRY it a bit more by moving the tri-load pattern into a script on s.keyman.com rather than embedding it into the bookmarklet?

It's not like the bookmarklet is usable offline, so that sounds perfectly viable.

**Comment by jahorton** [comment]
Huh.  At some point since the last assessment, this bug seems to have been fixed.

That said, the OSK's _positioning_ is off; it appears to lock to a web page's left-hand side and previous y-position once a second bookmarklet is loaded, with the position refusing to update unless manually dragged by the user.

**Comment by jahorton** [comment]
> Agreed. I think we DRY first and then fixup this issue. Make the bookmarklet generator into shared code (although our shared code across sites is currently still not really great, perhaps we can share it on s.keyman.com?)
> 
> Even if we can't fix for existing bookmarklets, we should certainly try and fix going forward. The suggested way forward looks good but wonder if we can DRY it a bit more by moving the tri-load pattern into a script on s.keyman.com rather than embedding it into the bookmarklet?

I think I've figured out how to set up lthe "tri-load" pattern.  I'm not entirely sure how best to implement the DRY version in a way that the different use cases can access easily, though.

**Comment by jahorton** [comment]
When the three PRs linked above are all merged, we may consider this issue resolved.
