### ISSUE TITLE
feat(web): addKeyboards should return a Promise

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#4788]
**Is your feature request related to a problem? Please describe.**
Because `addKeyboards` is async, loading scripts in background, it should return a Promise so API consumers can use it effectively.

This is probably not the only API endpoint that should be doing that kinda thing.

The good news is that we can improve the existing API endpoint here because currently its return value is undefined.

---

**KeymanWeb:**
 - OS: any 
 - Browser: any 
 - KeymanWeb Version: 14.0.270

**Comment by mcdurdin** [comment]
Promise should return an array of the new keyboards added.

**Comment by mcdurdin** [comment]
Per 15.0 planning, we should spec this out for any of the APIs in KMW before we attempt implementation.

**Comment by jahorton** [comment]
Should we consider this subsumed by #5044?  This thread now feels like a duplicate, with the spec thread being the more complete version.

**Comment by mcdurdin** [comment]
> Should we consider this subsumed by #5044?  

Yes
