### ISSUE TITLE
bug(developer): Font with quote in name breaks compiler

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4810]
**Describe the bug**

sil_nko keyboard was updated and compiled with an error except a warning of having non canonical tag, i.e. 

```
sil_nko.kps: Keyboard with ID 'sil_nko' has a BCP 47 warning: 'emk-Nkoo' is a valid tag but is not canonical: it should be 'man-GN'.
sil_nko.kps: Keyboard with ID 'sil_nko' has a BCP 47 warning: 'man-Nkoo' is a valid tag but is not canonical: it should be 'man-GN'.
```

Now, when testing this keyboard on Chrome emulator, an error occurs "Error registering the sil_kno keyboard for sil_nko."
![image](https://user-images.githubusercontent.com/28331388/112786423-6e8ed480-9080-11eb-8f12-e01662a1099e.png)

The same kind of error is experienced on mobile emulator as well:

First this message:
![Screenshot_1616989911](https://user-images.githubusercontent.com/28331388/112786475-85cdc200-9080-11eb-9483-42ff9571ee54.png)

Then this:
![Screenshot_1616989914](https://user-images.githubusercontent.com/28331388/112786495-92521a80-9080-11eb-9c3b-7a93590e319d.png)

The keyboard seems to be installed, but when switching over it, the same error messages occur.

**To Reproduce**

**Expected behavior**

**Screenshots**

---

**Keyman for Android:**
 - OS: Android 10 API 29
 - Keyman for Android: 14.0.270 stable

**Keyman Developer:**
 - OS: Windows Pro 10 2004 x64
 - Keyman Developer version: 14.0.270 stable

---

**Keyboard**
 - Keyboard name: [sil_nko](https://github.com/keymanapp/keyboards/pull/1501)
 - Keyboard version: 1.1
 - Language name: N'Ko

**Comment by mcdurdin** [comment]
The problem here is that the `Noto Sans N'Ko` font has a quote in the name but we've failed to escape quotes for font names.

```js
this.KV={F:' 1em "Noto Sans N'Ko"',K102:0};
```

This will be fixed in a compiler update.
