### ISSUE TITLE
bug(android): blank (black) keyboard when opening an app

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#4819]
**Describe the bug**

![image](https://user-images.githubusercontent.com/4498365/112917728-05c25d80-914f-11eb-89f1-969792dd4fda.png)

The keyboard was completely blank and black. I attached chrome web inspector and was able to see that the keyboard was loaded and KeymanWeb was initialised. There were no errors (apart from the usual 'No keyboard stubs exist'). This suggests we are getting a race sometimes where Keyman for Android never gets fully initialised on load and never gets the opportunity to pop a keyboard?

Difficult to reproduce; have noted a couple of times when opening search after not using my phone for a while.

---

**Keyman for iPhone/iPad/Android:**
 - Device: Samsung A90 5G 
 - OS: Android 10 
 - Keyman version: 14.0.270

**Comment by darcywong00** [comment]
> This suggestions we are getting a race sometimes where Keyman for Android never gets fully initialised on load and never gets the opportunity to pop a keyboard?

That sounds similar to what I saw while investigating
https://github.com/keymanapp/keyman/issues/4753#issuecomment-804606899
> Binary search through the alpha builds and the backspace results:
>
>14.0.32 - pass
>14.0.33 - sil_euro_latin keyboard fails to load
>14.0.34 - fail
>14.0.35 - fail


It'll take some 🦆 to troubleshoot the loading issue...

**Comment by mcdurdin** [comment]
user report now: https://community.software.sil.org/t/keyman-nuer-keyboard/4596/1

**Comment by mcdurdin** [comment]
I've been spelunking this code and I think that the issue may be related to line 2081 in `KMManager.java:pageLoaded`:

```
if (!SystemKeyboard.keyboardSet)
```

The circumstances in which I am seeing this are after not using the keyboard for a while, I select a text field, and the keyboard pops up. It looks like the page reloads, but on the KMManager side, it sees that `keyboardSet` is already true (because KMManager has not reloaded, just the web page). This means that the keyboard is never set after the reload.

I can trivially reproduce this by attaching the Chrome remote web inspector to keyboard.html and reloading the page from there.

I think we always want to be setting the keyboard after a page reload.
