### ISSUE TITLE
chore(android): Save image locally

### ISSUE THREAD

**Issue by bravogeorge** [keymanapp/keyman#4838]
![Screen Shot 2021-03-30 at 8 47 51 PM](https://user-images.githubusercontent.com/19643078/113205635-5d31fd80-9223-11eb-9782-24579a0883bc.png)

Prosing image update from suggestion of @jahorton of keyboard icon the image of help article should pop more.

https://help.keyman-staging.com/products/android/current-version/start/enabling-system-keyboard

CTRL+F: "you'll see a keyboard icon at the bottom right"

**Comment by darcywong00** [comment]
Fixed in #4844

Thanks!
