### ISSUE TITLE
feat(developer): insert code to the key code & character to the key cap

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4854]
**Is your feature request related to a problem? Please describe.**

Currently, Keyman Developer would only allow insert character to the Touch layout.

**Describe the solution you'd like**

A proposed solution from [Ibrahima](https://community.software.sil.org/t/feature-request-on-keyman-developer/4606):
> Dragging or double-clicking on character on Unicode Map should populate both key and key code fields respectively with character and character code. Right now, only character is transferred to those if we drag or double-click the character, no matter what mode we select (character/Code/Name).
> 
> I find it easier and we can avoid errors while typing codes like U_1FB4.
> But, we have to make sure that the U_ is included instead of the U+ (which I understood was not supported. If I remember)
> 
> Here’s a summary:
![image](https://user-images.githubusercontent.com/28331388/113369877-a0f44680-938c-11eb-8818-4057ffb20f4d.png)

**Describe alternatives you've considered**

N/A

**Comment by mcdurdin** [comment]
There are a few nuances to this. I think I would implement like this for the Touch Layout Editor design view:

* Double-clicking should always insert into the key cap of the currently active key (longpress key takes precedence if it is active).
* Drag+drop should allow you to drop onto any key (long-hold over a target key should also make its longpress keys available so you can then drag onto those).
* If the id of the target key is currently `T_new_...` then replace it with `U_xxxx` when you either double-click or drop onto the key cap.
* If the id is anything else, only replace if you drop directly on to the id field, or if you hold <kbd>Shift</kbd> while double-clicking or dropping onto the key cap.

As far as I can tell, there is never really any reason to have Character Map interact with any other fields, so these optimisations should make the interactions a whole lot more pleasant. The "Insert Mode" would have no meaning here -- it would always drop characters onto the key cap, and codes onto the id.

**Comment by mcdurdin** [comment]
Same issue also reported via email by Doug Higby.
