### ISSUE TITLE
bug(windows): the keyboard is not working even though activated

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4856]
**Describe the bug**

On a particular user's machine, a custom keyboard does not work as expected even though it was correctly set as default input method. Here is the whole account of the [issue ](https://community.software.sil.org/t/keyboard-shows-as-on-but-doesnt-work-until-it-is-turned-off-and-on-again/4336/15) from the community site:

> The issue persists even when having the right language tag set to “qu-PE”. Despite the fact that the keyboard works for me, the keyboard keeps misbehaving. ;a output ;a instead of ä in Microsoft Office Word 365 (including even Notepad) on Diane’s machine.
> 
> What I do that works for me but not for her
> 
> Install the keyboard [quechua_unicode2.1.kmp](https://community.software.sil.org/uploads/short-url/80Iqy8CCFO0IajYwJJZw1JgI7Mg.kmp) (1.6 KB)
> Go to the Language Preferences and move Quechua keyboard to the top of list of “Preferred Language” so the keyboard will be used for any apps.
> Go to “Keyboard” and choose “Quechua Unicode” to Override for default input method.
> Doing these proves to work on my Machine. Open LibreOffice, Notepad or Chrome to type away in Quechua without any issue nor having to switch the keyboard on and off.
> 
> As you have mentioned earlier, there might be something getting in the way before Keyman gets to work in per particular machine. I would suggest that you look into it when time allows.

**Expected behavior**

The keyboard should work (i.e. `;a` output ä) at any given application on startup without having to switch to an different keyboard and back to it to activate the keyboad.

---

**Keyman for Windows/macOS/Linux:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman version: 14.0.270
 - Target Application: MS Office 365, Notepad, Chrome (any at all)

---

**Keyboard**
 - Keyboard name: quechua_unicode
 - Keyboard version: 2.1
 - Language name: Quechua

**Comment by mcdurdin** [comment]
This is the same issue as #4965.
