### ISSUE TITLE
bug(developer): model won't build in Developer

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4862]
**Describe the bug**

The `sil.brb.brao` still cannot be build in Developer, even though it is built successfully on command line. Confirm that the Developer used is the latest stable, 14.0.271.

Error message in the developer:
```
sil.brb.brao.model.ts: Compiling 'C:\keyman\lexical-models\release\sil\sil.brb.brao\source\sil.brb.brao.model.ts'...
sil.brb.brao.model.ts: Success: 'C:\keyman\lexical-models\release\sil\sil.brb.brao\source\sil.brb.brao.model.ts' was compiled successfully  to 'C:\keyman\lexical-models\release\sil\sil.brb.brao\build\sil.brb.brao.model.js'.
sil.brb.brao.model.kps: Compiling package sil.brb.brao.model.kps...
sil.brb.brao.model.kps: Warning: Lexical model with ID 'sil.brb.brao' has a BCP 47 warning: 'brb-Khmr' is a valid tag but is not canonical: it should be 'brb'.
sil.brb.brao.model.kps: Failure: 'C:\keyman\lexical-models\release\sil\sil.brb.brao\source\sil.brb.brao.model.kps' was not compiled successfully.
```

lm pr: https://github.com/keymanapp/lexical-models/pull/122

**To Reproduce**

1. Load the lm
2. Click to open it in 'Developer'
3. Build the package

---

**Keyman Developer:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman version: 14.0.271

**Additional context**

This was not working in the previous version either.

**Comment by darcywong00** [comment]
Does the lexical model compiler need its corresponding update to #4689 and #4699?
