### ISSUE TITLE
bug(android): Typing Emoji in Messaging app causes bug when tried to backspace.

### ISSUE THREAD

**Issue by bennylin** [keymanapp/keyman#4868]
**Describe the bug**

https://community.software.sil.org/t/emoji-delete-bug/4610

I'm typing a post in WhatsApp (also Telegram) using my keyboard Jawa_Latin (https://github.com/keymanapp/keyboards/pull/1495). Use Messaging app's emoji button, input an emoji. Go back to my keyboard, try to delete (backspace) the emoji, results in three tofus (���). Backspace again clear the tofus.

Try to add letters after emoji, then pressing backspace would result in nasty bug, the number of characters in the text field won't reduce, but pressing backspace resulted in a random character to pop up, essentially rendering backspace useless. I can only select all text and backspace to clear it, or post the buggy message, and delete it.

Edit 1: Confirming the bug exist in my WhatsApp, Telegram, and Keyman for Android (if I copy paste an emoji from somewhere else)

Edit 2: Confirming the bug exist in other keyboards, such as default EuroLatin SIL keyboard

Super nasty bug!

**To Reproduce**

1. Go to WhatsApp or Telegram, right now I'm using my keyboard, https://github.com/keymanapp/keyboards/pull/1495, but will try other keyboards after I submit this.
2. Compose any message, start with an emoji, using emoji provided by WhatsApp. Then exit the emoji screen, try backspace, you'll see ���; if you add some text after the emoji, more chaos ensued.
3. See error

**Expected behavior**

Emoji should be deleted with no tofus.

**Screenshots**

If the repro steps doesn't work, I'll post a video. Screenshots cannot describe the effect.

---

**Keyman for iPhone/iPad/Android:**
 - Device: Nokia 2.2
 - OS: Android 10, 5 March 2021
 - Keyman version 14.0.270
 - Target application: WhatsApp 2.20.201.23 or Telegram 7.6.0
 - 
---

**Keyboard**
 - Keyboard name: Latin Jawa https://github.com/keymanapp/keyboards/pull/1495
 - Keyboard version: 1.0
 - Language name: Basa Jawa (Javanese)

**Additional context**

The bug appear whenever there's at least 1 emoji on the text. It doesn't matter where: on the same line, same sentence, different lines/paragraph. As long as there's 1 emoji while typing, and I press backspace (on any character, any language/script, selecting random part of the sentence, i.e. not a sequence bug), the bug happens.

If the emoji is deleted by any mean (usually by select part of text and press backspace), then the rest of the text resumes to normal. 

As long as the backspace is not pressed, I can still compose the text normally, no problem.

**Comment by darcywong00** [comment]
> If the repro steps doesn't work, I'll post a video. Screenshots cannot describe the effect.

Thanks for the thorough report. No video necessary as I can repro 

WhatsApp 2.21.6.17
Keyman 14.0.271
Keyboard: SIL Euro Latin
Android 8.1

**Comment by jahorton** [comment]
I can get similar effects on iOS with its emojis, too.

**Comment by jahorton** [comment]
Diagnosis:  this appears to be an issue in the `OutputTarget` subclasses for `Input` and `TextArea`.

Both classes contain a `getCaret()` function marking the current location... well, of the caret.  This is supposed to be the SMP-aware index, but as that's a fairly costly operation, we compute the index once and cache it, detecting whenever the index changes.

That value is then being used within the `deleteCharsBeforeCaret()` function, which is responsible for backspaces, as follows:

https://github.com/keymanapp/keyman/blob/7bdf03e481b747c1e96e5842b27bdf6134369202/web/source/dom/targets/textarea.ts#L124-L137

(This is the function triggered by BKSP use within the mobile apps; embedded mode uses the underlying element, not the touch alias here.  The mobile apps do use a TEXTAREA element.)

The problem:  for whatever reason, with (at least) some emojis at the end of the context, the SMP-index calculations... aren't operating correctly.  They're returning the non-SMP-aware index, which is markedly _after_ the SMP-aware index, so BKSP operations don't result in a change to KMW's internal context, as the substring is accidentally told to preserve the whole string.  However, the app (naturally) processes that differently, resulting in a context desync.

Note:  the easiest repro I can find is to use a skin-tone based emoji, though the skin-tone element isn't necessary.

----

Attempting to narrow this down further:

```
"👍".length == 2;
"👍🏻".length == 4;
```

KMW's design, and SMP-extension functions, are designed on the assumption that code points involve either 1 or 2 code units, but as denoted here, the white skin-tone thumbs-up emoji results from combining "thumbs-up" + "white skintone".

Interestingly,

```
"👍".kmwLength == 1;
"👍🏻".kmwLength == 2;
```

If using an emoji keyboard, then swapping to English: as our default English keyboard for the app (properly) notes that English text doesn't need any SMP-handling, our SMP-aware functionality is disabled when said keyboard is loaded.  As a result, it's not available when backspacing into pre-existing emoji context, which _does_ need SMP handling.

The simplest solution is likely to permanently enable SMP handling, at least when embedded in the mobile apps.

**Comment by jahorton** [comment]
On iOS, that "simplest solution" (from the end of my last comment) generally appears to work _so long as_ skin-tone variants aren't used.  iOS will auto-backspace the full emoji all at once, while KMW will only backspace one of the code unit pairs at a time - this does lead to a context desync.

Even then, this at least stops the "tofu" from appearing.
