### ISSUE TITLE
bug(android): Loading keyboard "indonesia" in Keyman for Android 14 causes fatal error

### ISSUE THREAD

**Issue by bennylin** [keymanapp/keyman#4869]
**Describe the bug**

`Fatal keyboard error with indonesia:indonesia for keyboard. Loading default keyboard`

I've had this bug for quite some time, today I'm trying to repro it for bug report.

**To Reproduce**

1. Go to Keyman for Android
2. Click on language selector, choose keyboad (Bahasa Indonesia: Indonesia)
3. Wait a couple of second

**Expected behavior**

I can use my keyboard 😂

**Screenshots**

---

**Keyman for iPhone/iPad/Android:**
 - Device: Nokia 2.2
 - OS: Android 10, 5 March 2021
 - Keyman version 14.0.270
 - Target application: Keyman 14.0.270, or WhatsApp 2.20.201.23, or Telegram 7.6.0
 - 
---

**Keyboard**
 - Keyboard name: Bahasa Indonesia https://keyman.com/keyboards/indonesia
 - Keyboard version: 1.0
 - Language name: Bahasa Indonesia (Indonesia)

**Additional context**

It worked fine in previous keyman that I had. The bug only occur after I updated it to version 14.0

**Comment by darcywong00** [comment]
Sorry for the trouble. I've been monitoring what could be a related issue in #4794 

Can you update Keyman for Android to 14.0.271 and see if that helps?

**Comment by darcywong00** [comment]
I think this will also be fixed by #4961
