### ISSUE TITLE
bug(developer): the keyboard can be compiled within Developer, but it crashes when compiling from the command line

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4871]
**Describe the bug**

This [keyboard](https://github.com/keymanapp/keyboards/pull/1477) is proved to be compiled without error within Keyman Developer, but when running `$ ./build.sh release/sil/sil_brao/`, this occurs:

```
--- Only building release release/sil/sil_brao/ ---
Building sil_brao
sil_brao.keyboard_info: Failure: File sil_brao.keyboard_info has errors.
Failed to validate sil_brao.keyboard_info in release/sil/sil_brao/
Aborting with error 1


```

There is also a crash in TC.

**To Reproduce**

1. Get the keyboard and run the build command 
2. See error

**Expected behavior**

The keyboard should be compiled without any error, just like when it is compiled within Developer.

---

**Keyman Developer:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman Developer version: 14.0.271

---

**Keyboard**
 - Keyboard name: sil_brao
 - Keyboard version: 1.0
 - Language name: Bral Lave

**Comment by mcdurdin** [comment]
Is this related to https://github.com/keymanapp/keyboards/pull/1477?

**Comment by MakaraSok** [comment]
Yes and it turns out that something is wrong with the keyman_info file even though it was a valid json. The brackets used were different. Lorna's solution works.
