### ISSUE TITLE
bug(windows): Character Map always stays atop?

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4873]
**Describe the bug**

While on Character Map, click to "Open Keyman Configuration" to see the Configuration window behind the Character Map window. The same happens when click to "Open Help".

**Expected behavior**

The Configuration window should be shown above the Character Map window.

**Screenshots**

![image](https://user-images.githubusercontent.com/28331388/114119690-58510600-9915-11eb-942e-4fc5b17c6fc6.png)

---

**Keyman for Windows:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman version: 14.0.271
 - Target Application: Keyman

**Comment by mcdurdin** [comment]
This is by design -- the on screen keyboard panel is always on top no matter what 😁
