### ISSUE TITLE
bug(android): a string in English when UI language is set to Khmer

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4875]
**Describe the bug**

When deleting a keyboard either by pressing and holding on the keyboard list or "Settings > Installed Languages > Tap on any keyboard > Uninstall keyboard > Tap "Delete" to get rid of the keyboard and see error as shown below:
![Screenshot_1617947545](https://user-images.githubusercontent.com/28331388/114135145-061edd80-9933-11eb-96d0-d8c2c6034c67.png)

**Expected behavior**

The message should be in Khmer because that is what was set for the UI.

---

**Keyman for Android:**
 - Device: Android 10 emulator
 - Keyman version 14.0.271
 - Target application: Keyman

---

**Additional context**

- Delete a keyboard from the globe key would also show the error. 
- When looking into the source strings, no message with "Keyboard deleted" is found.

**Comment by darcywong00** [comment]
I'm inclined to push this to 15.0 since it's not a crash-inducing issue...

**Comment by darcywong00** [comment]
Fixed by #6561
