### ISSUE TITLE
feat(developer): underlying character customizable?

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4879]
**Is your feature request related to a problem? Please describe.**

A user asked whether or not the underlying characters on touch layout and OSK be modified. If possible, the intention is to use IPA characters instead of the English characters because it may be useful to users to learn to type.

**Comment by jahorton** [comment]
Loosely related to #4894.  I'd advise tackling both within the same release.

**Comment by mcdurdin** [comment]
The underlying characters on desktop platforms are correlated to the hardware keyboard. On touch, this is a loose correlation. However, unless I am misunderstanding something, I don't really see a solid reason to support doing this -- the underlying layout characters are supposed to help users correlate to the base keyboard (this is also why we don't encourage showing them as much on touch layouts).

**Comment by MakaraSok** [comment]
> However, unless I am misunderstanding something, I don't really see a solid reason to support doing this -- the underlying layout characters are supposed to help users correlate to the base keyboard (this is also why we don't encourage showing them as much on touch layouts).

Might be true for the OSK, but for touch layout is rather helpful for a keyboard (customized for non-native speakers) like Thai to have IPA characters as the underlying characters, i.e. having "ŋ" as the underlying character for a keycap labeled as "ง". This was requested by a keyboard developer who looks into creating a new Thai keyboard.

**Comment by mcdurdin** [comment]
Okay, file this under future feature 😁 Don't think we can implement this one today!

**Comment by mcdurdin** [comment]
> Loosely related to #4894. I'd advise tackling both within the same release.

Very loosely. One is a user option, the other is a keyboard development side change. I'm not sure they need to be implemented together...

**Comment by MakaraSok** [comment]
> Okay, file this under future feature 😁 Don't think we can implement this one today!

Totally understood. 👍

**Comment by MakaraSok** [comment]
A new request of this feature: https://community.software.sil.org/t/custom-display-underlying/5618.

**Comment by maxipombo** [comment]
Hi! I think that it would be helpfull on touch layout for show a hint with the most common long press keys. This is something that my users ask me if was possible because it would help them to know where the hidden keys (on long press) are.

**Comment by mcdurdin** [comment]
This feature is scheduled to be implemented in 16.0 and will be tracked in #5079.
