### ISSUE TITLE
bug(ios): long press on the top right

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4880]
**Describe the bug**

When long press on the top row character, the popup key overlaps the key it is based on (see screenshots below).

As default:
![image](https://user-images.githubusercontent.com/28331388/114488069-e0e3e500-9c3a-11eb-969c-4d1e372f5c34.png)

In app:
![image](https://user-images.githubusercontent.com/28331388/114488041-d4f82300-9c3a-11eb-9c20-d31900a40729.png)

**To Reproduce**

1. install this [keyboard](https://community.software.sil.org/uploads/short-url/tIpRwzZH6nwJvxr4gHIFsxA0Fnz.kmp) on your iOS device
2. Open Keyman app, select the keyboard and then long press on "U" key on default layer
3. See error

**Expected behavior**

The popup key should be shown up like this on Android:
![image](https://user-images.githubusercontent.com/28331388/114490249-b3009f80-9c3e-11eb-8ff4-658ead3e7a7f.png)

---

**Keyman for iPhone/iPad:**
 - Device: iPad mini (5th gen)
 - OS: iOS 14.4.2
 - Keyman version 14.0.271
 - Target application: Keyman and when used as a system keyboard

---

**Keyboard**
 - Keyboard name: [thai_QWERTY](https://community.software.sil.org/uploads/short-url/b6xMdpWCTuWC9EjcYMfbBVwFntl.zip)
 - Keyboard version: 1.0
 - Language name: Thai

**Additional context**

When test on Chrome emulator - iPad, the long press characters on the key on the top right corner of the "0" key on numeric layer, pop way to far from the key it's based on:
![image](https://user-images.githubusercontent.com/28331388/114490723-88631680-9c3f-11eb-9e3b-d5ed3e77a50f.png)

**Comment by mcdurdin** [comment]
Can you log the "Additional context" as a separate issue please?

The base issue here is a limitation of iOS. We cannot draw the popup key outside the boundaries of the keyboard. So we recommend turning on the banner, which gives space for the popup to appear.

**Comment by MakaraSok** [comment]
The new issue can be found at: https://github.com/keymanapp/keyman/issues/4930
