### ISSUE TITLE
bug(windows): keyboard installation prompt lacks wordwrap / scrolling

### ISSUE THREAD

**Issue by DavidLRowe** [keymanapp/keyman#4883]
**Describe the bug**
When installing a keyboard, the Message doesn't wrap, so the end is clipped off.

**To Reproduce**
1. Install the keyboard from https://github.com/keymanapp/keyboards/pull/1519 (I had the keyboard loaded in Keyman Developer, built it, then used the Install button to install it.)
2. Observe that the Message is clipped. It doesn't wrap to display the entire text. (I can select the Message line, copy and paste it into Notepad to see that all that's missing is the end of "Nigeria." So, in this case, I'm not missing much.
3. Click Cancel avoid installing the keyboard.

**Expected behavior**
The Message should wrap to the following line(s). Alternatively, the Message area could be scrollable.

Has this always been the behaviour? Or has something changed recently. 

**Screenshots**
![image](https://user-images.githubusercontent.com/8562172/114923674-f6474380-9de1-11eb-9e21-e4ffa662d0fa.png)

---

Keyman for Windows:
    OS: Windows 10 20H2 x64
    Keyman version: 14.0.271

Keyman Developer: (since I launched the install from Developer)
    OS: Windows 10 20H2 x64
    Keyman Developer version: 14.0.271.0

---

**Keyboard**
 - Keyboard name: Obolo Chwerty
 - Keyboard version: v1.1.2 (PR https://github.com/keymanapp/keyboards/pull/1519 as of 2021-04-15)

**Comment by mcdurdin** [comment]
This impacts only installing the .kmx directly; .kmp files do not include a Message but rather that content would belong in the Readme, which is a normal HTML file. Thus, I will consider this low priority as we do not normally install .kmx outside of a package except in development.

**Comment by mcdurdin** [comment]
The problem can be tested with the attached .kmx file: [obolo_chwerty.zip](https://github.com/keymanapp/keyman/files/6587415/obolo_chwerty.zip)

**Comment by mcdurdin** [comment]
Many thanks to @SabineSIL for her first pull request fixing this!
