### ISSUE TITLE
bug(windows): modifier keys sometimes get stuck

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#4884]
**Describe the bug**

https://community.software.sil.org/t/problems-with-keyman-windows-popping-up/4668

In some situations Keyman thinks that modifier keys are down for hotkeys when in fact they are not. This modifier state does not impact other input, just hotkeys within Keyman such as open osk.

Workaround: press and release each modifier to reset the hotkey modifier state.

---

**Keyman for Windows/macOS/Linux:**
 - OS: Windows 10 
 - Keyman version: 14.0.271 
 - Target Application:

**Comment by MakaraSok** [comment]
The behavior experienced by the user is with Keyman 13.

https://community.software.sil.org/t/problems-with-keyman-windows-popping-up/4668/6
