### ISSUE TITLE
Question:  testing Crowdin language translations in-app

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#4885]
How can we test the language translation from Crowdin in Windows, iOS, mac?

Can we download the files from Crowdin and copy to local installation?

**Comment by jahorton** [comment]
I _believe_ that (currently) there's no easy way to test it before it's compiled into Keyman.

We've done a bit of research into support for loading 'custom' localizations within some of our platforms, but we were unable to implement that for 14.0.

Example leads we've investigated:
- #4864
- #4598

**Comment by darcywong00** [comment]
Our workflow at the moment is to pull completed translations into the master branch (currently 15.0 alpha) and also to the latest stable release.

Once you've completed a translation, we can just pull them into master for you to test (15.0 builds). When you think it's ready, we can then incorporate them into stable-14.0.

**Comment by mcdurdin** [comment]
Yes. We hope to do this in a future version but it's non-trivial for mobile platforms at least. Ideally the translation will be distributed as a .kmp and installable in the same way as a keyboard or lexical model. Perhaps we'll use the file extension `.l10n.kmp` 😉?

**Comment by mcdurdin** [comment]
Current workflow is for the files to be integrated into an alpha release and tested there. It would be difficult to make this dynamic without a _lot_ of work, so will close this issue.
