### ISSUE TITLE
feat(linux): Integrate with fcitx5

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/keyman#4910]
Detect when fcitx is running (fcitx appears on dbus - cf https://github.com/fcitx/fcitx5/blob/master/src/modules/dbus/org.fcitx.Fcitx5.service.in). If it is running we shouldn't try to add the keyboard automatically but instead display a message box telling the user to use fcitx5-configtool for adding it to the list of keyboards. 

See https://github.com/keymanapp/keyman/pull/4806#issuecomment-812006448

**Comment by mcdurdin** [comment]
Don't forget to fix the 10000 loop!
