### ISSUE TITLE
bug(web): popup key is not shown right on the base

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4930]
**Describe the bug**

**Additional context**

When test on Chrome emulator - iPad, the long press characters on the key on the top right corner of the "0" key on numeric layer, pop way too far from the key it's based on:

![image](https://user-images.githubusercontent.com/28331388/114490723-88631680-9c3f-11eb-9e3b-d5ed3e77a50f.png)

**Expected behavior**

The popup key should be on the key it's based on.

---

**KeymanWeb:**
 - OS: Windows 10 Pro 20H2 x64
 - Browser: Chrome Version 89.0.4389.128 (Official Build) (64-bit)
 - KeymanWeb Version: ??

**Keyman Developer:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman Developer version: 14.0.271

---

**Keyboard**
 - Keyboard name: thai_qwerty
 - Keyboard version: 1.0 (under development)
 - Language name: Thai

**Comment by mcdurdin** [comment]
Can you give a set of steps to reproduce this issue please?

**Comment by jahorton** [comment]
Looks like I will need additional detail.  I pulled your branch for the linked keyboard and set up a test page; I cannot currently replicate the effect you're reporting here.  The long pressable key at the top-right displays its subkeys in the correct location for me.

**Comment by MakaraSok** [comment]
> Looks like I will need additional detail.

Have you tried landscape mode? This happens to me when it's on landscape.

![image](https://user-images.githubusercontent.com/28331388/117946221-4cec6280-b339-11eb-87b1-495680f193f2.png)

**Comment by jahorton** [comment]
That's a pretty important detail; didn't think about that, despite all the screenshots being in landscape.  I get a successful repro in landscape mode.

Quick notes:
- Initial orientation does not appear to matter.
- The position of the subkey array for '8', '9', and '0' are all _identically positioned_.
- The landscape 'bound' appears to be using portrait width, not landscape width.

Compare the highlighted element between these two screenshots:

<img width="1440" alt="Screen Shot 2021-05-12 at 3 54 42 PM" src="https://user-images.githubusercontent.com/25213402/117947592-8a052480-b33a-11eb-8d33-22dcc0f735a0.png">

<img width="1440" alt="Screen Shot 2021-05-12 at 3 54 13 PM" src="https://user-images.githubusercontent.com/25213402/117947577-86719d80-b33a-11eb-9b0b-5781984cbab5.png">

Please ignore how the wrong layer is shown behind the subkeys - that's an artifact of forcing a breakpoint during a debugging session.

The critical bit:  note the `left` attribute.  While not the _same_ value, it's quite, quite close.

**Comment by jahorton** [comment]
Found the culprit:

https://github.com/keymanapp/keyman/blob/9d7a8d649f27952ba9c482a670e0d835c83a101c/web/source/osk/visualKeyboard.ts#L1790-L1793

Note the final line.  It appears that at some point in KMW's history, `screen.width` and `screen.height` did not swap places when a device was put into landscape mode.  But... now it _does_ swap:

<img width="648" alt="Screen Shot 2021-05-12 at 4 05 37 PM" src="https://user-images.githubusercontent.com/25213402/117949044-ed438680-b33b-11eb-9273-624461cf4e35.png">

This has the net effect of putting subkey positioning calculations back into "portrait" mode, causing the erroneous position.

So... now to figure out what cases do and don't auto-swap `screen.height` and `screen.width`.  Perhaps even which devices this was originally written to correct... as its presence indicates that a naive "fix" would break behavior on other devices.

**Comment by jahorton** [comment]
And, for what it's worth... apparently it ought to be a pretty old error:

<img width="1440" alt="Screen Shot 2021-05-12 at 4 15 33 PM" src="https://user-images.githubusercontent.com/25213402/117950466-68f20300-b33d-11eb-8a51-22ed476b5bd6.png">

That said... on a _**real**_ iPhone SE (2nd gen, granted), using Safari:

![Image from iOS](https://user-images.githubusercontent.com/25213402/117951372-4e6c5980-b33e-11eb-9f56-b6115cab4d99.png)

... maybe ignore the whole 'missing spacebar' thing in that image.  At least here.  For _this_ issue, the important thing is that the subkeys actually _are_ correctly positioned.  Especially because we get the same (subkey display) behavior in the Keyman app & its keyboard.  (Sidenote:  no weird 'spacebar' glitch there, at least.)

In fact, using Chrome on the same (real) device:
![Image from iOS (1)](https://user-images.githubusercontent.com/25213402/117953114-0817fa00-b340-11eb-98ef-350d82634317.png)

So... this might be a glitch in Chrome's mobile-device emulation.

**Comment by jahorton** [comment]
Based on my test with an emulated Android device (via Android Studio), this _is_ a bug for non-embedded Web on Android devices.  It would be helpful if someone could test with a real Android device to be sure, though.

**Comment by darcywong00** [comment]
> It would be helpful if someone could test with a real Android device to be sure, though.

Aside from the known issue of the OSK filling up the entire screen, the popup seems to be in the correct location

![qwerty_farang android landscape](https://user-images.githubusercontent.com/7358010/117956650-73af9680-b343-11eb-8884-00f88efe9bc5.jpg)

**Comment by mcdurdin** [comment]
Same osk size issue but I can replicate on chrome 90 in Android 10.

Long press on rightmost key with a popup on top row here:

![Screenshot_20210512-200903_Chrome.jpg](https://user-images.githubusercontent.com/4498365/117958123-0fe69700-b35e-11eb-84ad-38f1acedbd5d.jpg)

**Comment by jahorton** [comment]
I'm assuming that @darcywong00's screenshot is from within the Keyman app?  That yellow for the text area is pretty telling.

**Comment by mcdurdin** [comment]
https://user-images.githubusercontent.com/4498365/118062734-f46da180-b3da-11eb-85df-8417262a26b8.mp4

This shows interaction within the Keyman app on my phone. It is not always consistent. This time when I used the system keyboard I had the correct positioning (within GitHub app)

**Comment by darcywong00** [comment]
> screenshot is from within the Keyman app? 

Yes, my screenshot is within the Keyman app.

**Comment by jahorton** [comment]
Since the Keyman for Android app manages popup keys separately, seems like the rule of thumb for non-embedded Web may be "if Android, don't swap; if iOS, do swap."

**Comment by mcdurdin** [comment]
I should note that the App photos and screenshots (https://github.com/keymanapp/keyman/issues/4930#issuecomment-839642982) and (https://github.com/keymanapp/keyman/issues/4930#issuecomment-840209113) are confusing the issue here!

**Comment by MakaraSok** [comment]
> It would be helpful if someone could test with a real Android device to be sure, though.

On my Android physical device, the popped up key on the top right most does stay on the key and that works as expected.

It would be better to confirm this behavior on a physical iPad device because the issue arises from the Chrome emulator when iPad is chosen.

**Comment by jahorton** [comment]
> On my Android physical device, the popped up key on the top right most does stay on the key and that works as expected.

When using the system keyboard, which is from the Keyman app, right?  That doesn't apply here - the Android app has separate handling for this scenario.

**Comment by MakaraSok** [comment]
> When using the system keyboard, which is from the Keyman app, right?

When using the keyboard mentioned above within Keyman app.

**Comment by darcywong00** [comment]
ok, here's system keyboard typing in Chrome.
popup on 0 lines up fine.

![landscape popup](https://user-images.githubusercontent.com/7358010/118067648-2ecf4280-b3cb-11eb-9e00-4ece6ad7ba2f.jpg)

**Comment by mcdurdin** [comment]
@darcywong00 note that this issue is about keymanweb native -- not in embedded mode
