### ISSUE TITLE
bug(web): iPad emulator has the banner narrowed and not output the suggested word

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4943]
**Describe the bug**

iPad emulator has the banner narrowed and not output the suggested word when pressing the lower half of the banner.

**Expected behavior**

The banner should be shown in full for Khmer text to be readable.

**Screenshots**

The subscript and parts below the base are cropped off.
![image](https://user-images.githubusercontent.com/28331388/115518514-7114d080-a2b2-11eb-9c6c-685f9cb8a253.png)

---

**KeymanWeb:**
 - OS: Windows 10 Pro 20H2 x64
 - Browser: Chrome Version 90.0.4430.72 (Official Build) (64-bit)
 - KeymanWeb Version: 14.0.271
 - URL: n/a

---

**Keyboard and model**
 - Keyboard name: khmer_angkor
 - Keyboard version: 1.0.9
 - Language name: Khmer
 - LM: https://github.com/keymanapp/lexical-models/pull/131

**Comment by mcdurdin** [comment]
Is the word suggestion issue related to #4953? If so, let's make this only about the banner height. Does the banner height issue arise for native iPad devices?

**Comment by jahorton** [comment]
If you press the lower half of the banner, often KMW thinks you're pressing a key on the first row instead.

No iPad within reach here, sorry.  Only Simulated, but that requires being in macOS, which then precludes running the Developer test host.

**Comment by mcdurdin** [comment]
In the latest build (using artifacts from #5923), I found that the predictive text banner was no longer cropped:

![image](https://user-images.githubusercontent.com/4498365/142140645-8a0576f0-03a9-4ea1-b6e1-a27c1dec0f71.png)

I also found that it emitted the word as expected in all cases.

Can you repro this with that version from #5923, @MakaraSok?

**Comment by mcdurdin** [comment]
Assuming this is fixed, @MakaraSok.
