### ISSUE TITLE
bug(web): `setRect()` sets `dlftX` and `dfltY` but no way to reset these via API

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#4948]
Once `setRect({left:x, top:y})` has been called, `restorePosition()` no longer resets the position to pin to the active text field. Internally, this is because once `keyman.osk.dfltX` and `keyman.osk.dfltY` are set, there is no API to reset them. `restorePosition()` should probably be clearing those values (or there should be another API to do that).

Furthermore, `dfltX` and `dfltY` are not persisted to KMW's cookies.  This is likely due to the assumption that they'd be automatically re-established during a page's initiation on future visits / refreshes.

_Originally posted in https://github.com/keymanapp/help.keyman.com/issues/379_

---

**KeymanWeb:**
 - OS: any 
 - Browser: any 
 - KeymanWeb Version: 14.0.271

**Comment by jahorton** [comment]
I like the `restorePosition()` solution idea.

**Comment by mcdurdin** [comment]
> I like the `restorePosition()` solution idea.

I will draft a PR. We'll need to test this one a bit more thoroughly before back-porting though -- there are more interactions with the pin control and want to make sure that that doesn't break the user experience with that.

**Comment by mcdurdin** [comment]
FWIW, I think we should consider breaking `restorePosition()` into two functions: a wrapper for the event handlers for the pin, and a public function -- so that we don't do the grungy event fiddling within `restorePosition()` but only when we are responding to direct interaction with the pin div:

https://github.com/keymanapp/keyman/blob/c7adfd116d96cf290d0ffbb4d36fa525f6dd53bc/web/source/osk/oskManager.ts#L499-L501
