### ISSUE TITLE
Not able to install a keyboard from Keyboard Test Host on Android

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#499]
I was trying to install a keyboard, namely rac_kalasha, on my android using the Keyboard Test Host running. The host doesn't allow me to do anything, but showing this popup message: 
![screenshot 18 2017 8_26_00](https://user-images.githubusercontent.com/28331388/34086275-35ad3372-e3cd-11e7-89cb-9d76bd390373.png)

Thus, I was not able to install it.

**Comment by jahorton** [comment]
This affects KeymanWeb on Android devices as well as the Keyman app when attempting to install in-development keyboards for testing from Keyman Developer.

**Comment by darcywong00** [comment]
This seems to be related to Developer no longer appending keyboard version number to the .js filename. If you rename the js file, the Keyboard Test Host should be able to find and install the keyboard.
