### ISSUE TITLE
Exception when selecting subkey of Shift

### ISSUE THREAD

**Issue by gabrielwong** [keymanapp/keyman#501]
To reproduce:
1. Switch to the French keyboard and select the shift layer
2. Longpress shift and select one of the subkeys

The following error is thrown from `kmwosk.js` in `osk.release`.
```
Exception with thrown value: TypeError: null is not an object (evaluating 'osk.popupBaseKey.id')
```

**Comment by jahorton** [comment]
We are unable to reproduce this error, and there has been recent significant work addressing highly related code.  We're marking this as fixed for now, though we are willing to re-address it if additional details can be provided to help replicate it.
