### ISSUE TITLE
regression: Links to Keyboard Docs missing.

### ISSUE THREAD

**Issue by MattGyverLee** [keymanapp/keyman#5010]
**Describe the regression**
In previous versions of Keyman, one could access the Keyboard's local documentation by opening on the OSK, and clicking on the "i" button as shown in this screenshot from Help (Help says the screenshot is from v10).
![image](https://user-images.githubusercontent.com/986339/116859686-4a329480-abf8-11eb-87ce-c24c58a45cf2.png)
or clicking on the icon by the clock and clicking the "i". (For some reason, I can't screenshot this popup window, but the "i" is missing.) 

That "i" button is missing in current versions of Keyman (I'm in 14).
![image](https://user-images.githubusercontent.com/986339/116859913-a1d10000-abf8-11eb-8ce8-0d1e7e7097f0.png)

It seems that the only way to open the docs is to set a keyboard shortcut, but even that fails to work.  

**To Reproduce**

1. Install a keyboard with documentation.
2. Open OSK or the taskbar menu.
3. Try to find and click the "i".
4. [Don't] See Keyboard specific docs.

**Expected behavior**
I expect to find and click the "i" and see the keyboard docs.

**Keyman for Windows/macOS/Linux:**
 - OS: Win 10 20h2
 - Keyman version: 14.0.192-alpha
 - Target Application: Keyman

**Keyboard**
 - Keyboard name: Cameroon QWERTY, IPA, TChad

**Comment by mcdurdin** [comment]
Yeah, unfortunately we had to remove the info page as it was hosted as a HTML file -- and that opened up a number of security issues. Still hoping we can find a way forward on that in the future.

But, you can still access the keyboard help by clicking the `?` icon in the toolbar of the OSK or by clicking Help in the Keyman menu while the keyboard is active.
