### ISSUE TITLE
feat(web): Core OSK module

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#5023]
This is a holding issue for the Keyman Core integration for Web required to support LDML keyboards. We'll be filling this in as we complete planning and design.

**Objective:** Rework the Core OSK into a separate module that removes spaghetti integration with element activation.

* LDML has its own layout definition spec, which all of our platforms will need to support in some fashion.
* Of course, this affects Web-based platforms more strongly b/c touch layouts, predictive text, etc.
* May be worth considering touch-testing on desktop as a part of this (https://github.com/keymanapp/keyman/issues/292)
* Decoupling the OSK code as much as possible may greatly facilitate the ability to do this, especially in an easy-to-maintain way.
May also assist https://github.com/keymanapp/keyman/issues/61.  (Touchscreen desktop support) 

---

**KeymanWeb:**
 - Keyman version: target 15.0

**Comment by jahorton** [comment]
While not quite a standalone module yet, the OSK classes are now far, FAR closer to that end goal.  The classes are much more highly modularized as well.

At this stage, I don't think there's a need to make it fully standalone, though this idea _may_ make a nice goal for some point later in the roadmap if desired.  My recommendation would be to shift this to the Future milestone for now.

**Comment by jahorton** [comment]
Now that #8560 has merged, we're even closer to this goal.

During the namespace -> module conversion work, I took care to further modularize KMW's OSK.  It now has a test page where it is fully operational for user-interaction - though not text output - independently of Keyman Engine for Web.

There are still lingering hooks for predictive-text (thus, Web's `input-processor`) - but even that's been centralized and should be possible to mask for other platforms when we make the final push toward cross-platform use of the OSK module.

**Comment by srl295** [comment]
will there be any new requirements on the ldml side?

**Comment by jahorton** [comment]
> will there be any new requirements on the ldml side?

I doubt it.  If memory serves, the plan is to compile the LDML layout specs into standard Keyman touch layouts and the like... so it'd only be the same requirements we're already going to have to deal.

**Comment by mcdurdin** [comment]
Modularisation is done, LDML reqs probably not all met but that can be a separate task.
