### ISSUE TITLE
feat(web): move from namespaces to modules

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#5024]
This is a holding issue for the Keyman Core integration for Web required to support LDML keyboards. We'll be filling this in as we complete planning and design.

**Objective:** move from using namespaces in KeymanWeb to modules, in order to support WASM integration.

We'll do this only if we determine it is required for WASM support, and possibly only at a minimal level.

---

**KeymanWeb:**
 - Keyman version: target 15.0

**Comment by jahorton** [comment]
This was determined to be unnecessary at this time.
