### ISSUE TITLE
spec(web): Async API methods should return Promise (except Events)

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#5044]
KeymanWeb async API methods should return a Promise (except for existing Events).
An example of usage is websites that use KeymanWeb to addKeyboard (which can internally do a cloud query)

Preliminary discussion on [Google Doc](https://docs.google.com/document/d/1INxymfrj4GKkQBZnEAH9yVxPYadDRWAaF2FP0K7uWuM/edit#)

## Related Issue
Originally from #4788
> Per 15.0 planning, we should spec this out for any of the APIs in KMW before we attempt implementation.

## Existing KeymanWeb APIs with Promise
Per @jahorton 
> KMW already has one API with Promise support, though it could probably use a bit of optimization - the `.init()` function defined here:
https://github.com/keymanapp/keyman/blob/bf03c89a6be01a3dad93a410bdd65c931b46f677/web/source/dom/domManager.ts#L1480

> `setActiveKeyboard` also has a bit of Promise support. I'm not convinced that the `void` return is optimal, but at least it's there.
https://github.com/keymanapp/keyman/blob/bf03c89a6be01a3dad93a410bdd65c931b46f677/web/source/keyboards/kmwkeyboards.ts#L412

### C5044.1.1 Core Module
kmwbase.ts

#### C5044.1.1.1 Changes to addKeyboards and addKeyboardsForLanguage
1. Return a Promise of an Array of the new added keyboards (from )
    - Probably means the keyboard **stubs**
        * At its core, the stub is a keyboard metadata + language code pairing
       Refer to addKeyboard when spec is an [object](https://help.keyman.com/developer/engine/web/14.0/reference/core/addKeyboards)
        * May have multiple stubs per keyboard if the same keyboard is requested for multiple languages.       
    - If error, construct a JS error including the string (maybe keyboard info on the failing one)
        * See if we can put the error in fulfilled. And keep the array of successful keyboards
        * rejected state, returns array, `[ { InternalName: 'gff_mahric', error: 'could not load this keyboard because you can\'t spell'}, { InternalName: 'gff_amharic', lang: 'x', … } ]`
        * Add error to the keyboard [metadata object]
    - Special case: when addKeyboards is called with a **pre-built stub**
        * [Example case 1]( https://github.com/keymanapp/keyman/blob/bf03c89a6be01a3dad93a410bdd65c931b46f677/web/testing/commonHeader.js#L57-L61)
        * Just a bit later within the same [file]( https://github.com/keymanapp/keyman/blob/bf03c89a6be01a3dad93a410bdd65c931b46f677/web/testing/commonHeader.js#L74-L80)
        * For these two, those are the same stubs that an API call would return (aside from the file paths).
        * Here, because there’s no need to asynchronously request the stub, we could skip the Promise.  But it’s probably best to maintain consistency, noting that in such cases, the Promise will [instantly resolve](https://www.google.com/url?q=https://gist.github.com/brennanMKE/9310805&sa=D&source=editors&ust=1623124386272000&usg=AOvVaw0JtpIEiix75A4Z9OwPVpHG).
        * Add addKeyboardsForLanguage to help.keyman. It’s already mentioned in addKeyboard

#### C5044.1.1.2 Changes to setActiveKeyboard
```javascript
     * @param       {string}    PInternalName   Internal name
     * @param       {string}    PLgCode         Language code
     * @param       {boolean=}   saveCookie
```
This already returns Promise<void> which we can keep.
1. While `success` states are properly supported, the Promise is not rejected during error states.
    - [loadingStub.asyncLoader.callback](https://github.com/keymanapp/keyman/blob/bf03c89a6be01a3dad93a410bdd65c931b46f677/web/source/keyboards/kmwkeyboards.ts#L538-L564) should 'reject' the Promise at the functions' end, before returning.
        * It's the current way feedback about errors within `setActiveKeyboard` occurs
        * Cross-reference with [this line](https://github.com/keymanapp/keyman/blob/bf03c89a6be01a3dad93a410bdd65c931b46f677/web/source/keyboards/kmwkeyboards.ts#L578).
 
#### C5044.1.1.3 Changes to init
Init needs to add a flag `useAlerts` (default `true`) to determine whether or not KeymanWeb should display its own alert messages if a keyboard fails to download or run. Modern consumers of the API will probably prefer to implement their own reject promise handler for `addKeyboards`, and we may also need to add an `onalert` callback event for other async errors  

Also document on help.keyman.com
-----

### C5044.1.2 Utility Module
kmwutils.ts

#### C5044.1.2.1 Changes to alert (low priority)
1. Return a Promise to void.
  * Used by setKeyboard so when it fails, keyboard fails to load and alert displays.
2. If `useAlerts` == false, then do not show the alert, as the host is intending to handle failure cases in loadKeyboard, setKeyboard, etc.   Instead call the onalert handler. We need to consider situations where promise reject happens and avoid multiple failure pathways (i.e. don't have both promise.reject and alert). One to solve this may be to improve the KeymanWeb UI to use the new promise functionality as well and make *it* responsible for the alert calls?
 

## References 
Documented KMW API
https://help.keyman.com/developer/engine/web/14.0/reference/

**Comment by darcywong00** [comment]
Going through the Reference docs and compiling a list of methods to update:

## Core Module
* addHotKey
* addKeyboards
* addKeyboardsForLanguage (not listed, but referenced in [AddingKeyboards](https://help.keyman.com/developer/engine/web/14.0/guide/adding-keyboards.php)
* register
* ~setActiveKeyboard~ - already implemented
* ~init~ - already implemented
* enableControl?
* setKeyboardForControl?
* focusLastActiveElement?
* setActiveElement?
* moveToElement?

**Comment by jahorton** [comment]
#5121 and #535 are noteworthy here.

**Comment by darcywong00** [comment]
The changes in this spec have been implemented by the PRs above.
