### ISSUE TITLE
When signing up to the Keyman iOS alpha, an error message is received

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#506]
Through the keyman-ios-alpha.herokuapp.com website, an error message is received during the signup process:

`Something went wrong, please contact the application owner: uninitialized constant Spaceship::Tunes::Tester`

However, the signup appears to work despite this message.

**Comment by darcywong00** [comment]
This issue was reported on [FastLane](https://github.com/fastlane/fastlane/issues/10930) and they said it's been fixed in a newer version than what we're on.

**Comment by mcdurdin** [comment]
Resolved with update to the sites.
