### ISSUE TITLE
KeymanWeb 2.x problem with backspace and SMP characters

### ISSUE THREAD

**Issue by andjc** [keymanapp/keyman#509]
I am currently working on an Adlam layout and testing with the latest version of KeymanWeb 2.x.

The when the OSK delete/backspace key is used on the OSK, it appears to delete a single surrogate codepoint, leaving an unpaired surrogate codepoint. To delete a character requires two keypresses.

This does not occur when using a desktop and physical keyboard but does occur on a desktop when using a mouse with the OSK, also occurs on mobile devices, observed on Android 6.0.1. Currently untested on iOS.

Example page: https://enabling-languages.github.io/adlam/adlam-input-test.html

Have not tested with KMW 10 yet.

(DW edit: "to" -> "two" keypresses)

**Comment by darcywong00** [comment]
This is still an issue in KMW10 as seen in the following (mobile viewport for touch layout)

https://keymanweb.com/?tier=alpha#so,Keyboard_osmanya10

**Comment by jahorton** [comment]
It turns out that said Osmanya keyboard isn't requesting use of the SMP functionality needed to handle backspace properly.  Other recent work has already fixed the issue for KMW 10; so long as the compiled keyboard sets `this.KS=1;`, it will utilize the correct backspace behavior.
