### ISSUE TITLE
bug(windows): Crash when keyboard has no language defined and system has non-minimal BCP47 tag for default language

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#5091]
I got this support email below involving crashes with the latest Keyman for Windows 14.0.274 stable. 
The user was attempting to install the attached kmx files, but the crash reports say
> EOleExceptions: "Profile for language code zh-Hans-CN was not found when attempting to install TIP for [keyboard....]"

The keyboards are intended to install with `hmd`, but since they're not in a keyboard package, user doesn't get to assign a language.

Uni.kmx
http://sentry.keyman.com/organizations/keyman/issues/6050/?project=5
http://sentry.keyman.com/organizations/keyman/issues/6051/?project=5
http://sentry.keyman.com/organizations/keyman/issues/6052/?project=5

Miao1_.kmx
http://sentry.keyman.com/organizations/keyman/issues/6394/?project=5
http://sentry.keyman.com/organizations/keyman/issues/6393/?project=5

Configuration
Keyman for Windows 14.0.274 stable
Windows 10 Home (Chinese locale)
[hmd.zip](https://github.com/keymanapp/keyman/files/6490913/hmd.zip)

**Comment by mcdurdin** [comment]
Are you sure this is happening when transient languages are full?

**Comment by darcywong00** [comment]
> Are you sure this is happening when transient languages are full?

The user reported after dismissing crash dialogs, they got this
![transient-full](https://user-images.githubusercontent.com/7358010/118438026-dc18c200-b70d-11eb-9282-a6b88af68284.png)

**Comment by mcdurdin** [comment]
Okay, that message may be misleading in this context because it is coming up after an error. I don't think it actually applies :)
