### ISSUE TITLE
bug(developer): longpress keys on the right side popped off further away their based

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#5103]
**Describe the bug**

Longpress on the key on the right side of the keyboard on any layer in horizontal mode shows way off to left of the base.

Chrome Emulator:
* iPhone X  ![image](https://user-images.githubusercontent.com/28331388/118752436-47d56900-b88d-11eb-9bc4-b7ada33f9c7f.png)

* Pixel 2 ![image](https://user-images.githubusercontent.com/28331388/118752506-6b001880-b88d-11eb-9dfd-b5e02299608b.png)

_**Test on iPad simulator on macOS pending...**_

**To Reproduce**

1. Go to https://github.com/keymanapp/keyboards/pull/1472 to get the keyboard source
2. In Developer, build and initiate 'Test Keyboard on web'
3. Chose the device type 'iPhone/Pixel 2' and flip it to horizontal
4. Longpress any key on the default or shift layer
5. See error

**Expected behavior**

The popped up keys should be shown right on the key they are based on.

---

**KeymanWeb:**
 - OS: Windows 10 Pro 20H2 x64
 - Browser: Chrome
 - KeymanWeb Version: 14.0.274?
 - URL: n/a

---

**Keyboard**
 - Keyboard name: [sil_madi](https://github.com/keymanapp/keyboards/pull/1472)
 - Keyboard version:1.0
 - Language name: Ma'di

**Additional context**

Related closed issue: https://github.com/keymanapp/keyman/issues/4930

**Comment by MakaraSok** [comment]
This issue is seen as fixed when built from Keyman Developer stable version (14.0.280) with Chrome version `92.0.4515.131 (Official Build) (64-bit)` on Windows 10 Pro 21H1.

Pixel 2:
![image](https://user-images.githubusercontent.com/28331388/128826036-a2a2ff4b-7b0a-4651-9b15-516bc2adce21.png)


iPhone X:
![image](https://user-images.githubusercontent.com/28331388/128825947-170e0d3f-f1b6-4ae0-8287-bcef12bce0c1.png)

Please confirm whether the same effect is seen on your side.

**Comment by mcdurdin** [comment]
Confirm fixed, tested on 14.0.282.
