### ISSUE TITLE
bug(android): system font size negatively affects the letter on the key caps

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#5104]
**Describe the bug**

On Android tablet device, the system font size has been set to the maximum under `Settings/Display/Font size and style`. Now the characters on the keycaps of Keyman keyboards are too large that they look awfully ugly.

In Keyman app:
![image](https://user-images.githubusercontent.com/28331388/118757001-570ce480-b896-11eb-9e6d-3add3fca1438.png)

As system keyboard:
![image](https://user-images.githubusercontent.com/28331388/118756107-6723c480-b894-11eb-85a8-118c5bcd591f.png)

When the system font size is set to the minimum, the keyboards look OK.

**To Reproduce**

On an Android tablet:
1. Go to ' `Settings/Display/Font size and style`.'
2. Set the font size to the max
3. Go to Keyman app or Keyman keyboard set as a system keyboard

**Expected behavior**

Letters on Keyman keyboard should not be affected by the system font-size settings.

---

**Keyman for Android:**
 - Device: Samsung Galaxy Tab A7
 - OS: Anroid 10
 - Keyman version. 14.0.274
 - Target application: Keyman app and else where

---

**Keyboard**
 - Keyboard name: default - EuroLatin

**Comment by darcywong00** [comment]
I cannot repro this with the latest 15.0 Beta. Changing the system font-size doesn't impact the OSK keys

Likely, the KeymanWeb OSK refactor and vertical alignment fixed this.
