### ISSUE TITLE
bug(windows): dllhost.exe - Application Error - when install Keyman Developer on Windows on Boot Camp 

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#5130]
**Describe the bug**

Download this [version](https://build.palaso.org/buildConfiguration/KeymanDesktop_TestPullRequests/269472?buildTab=artifacts) of KD on to the Windows running on macOS Boot Camp.

Now initiate the installation, uncheck for update to just install the version (not the latest version). Follow the screen and then allow Windows to restart if required. At some point, the follow would pop up. Clicking OK won't stop it from re-appearing. Closing it a few times doesn't closes it either. Leaving it for a bit and then closing it again closes it. 

![image](https://user-images.githubusercontent.com/28331388/119246515-66e53b00-bbac-11eb-81ad-01c37a92dee2.png)

(For some reason, the Snipping Tool does not open itself on this Windows).

**Expected behavior**

The installation should get through without any hiccup. When installing the same version on my main Windows, no error occured.

---

**Keyman Developer:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman version: 14.0.274-stable > 15.0.49-alpha

---

**Additional context**

Once the error dialogue box is gone, the installation would carry on as normal and the KD got installed successfully upon a restart.

**Comment by mcdurdin** [comment]
dllhost is not related to Keyman Developer; this error is another process struggling to close down after Windows Installer initiated a restart.
