### ISSUE TITLE
bug: Selecting non-default modifier for touch key includes "+" in key ID. 

### ISSUE THREAD

**Issue by MattGyverLee** [keymanapp/keyman#5137]
**Describe the bug**
Selecting a "Modifier" on a touch key creates an element ID with a plus sign.

**To Reproduce**
1. Add a touch key on any layer but normal (ex. shift).
2. Choose a "Modifier" other than "current layer".
![image](https://user-images.githubusercontent.com/986339/119374513-90d45580-bcb1-11eb-8e23-c970d04e8243.png)
3. Build and test the KB in Chrome.
4. Inspect the key you just added.  The identifier will be "[active-layer]-[key-name]+[modifier].
![image](https://user-images.githubusercontent.com/986339/119373505-646c0980-bcb0-11eb-885c-36bccaff31a0.png)

**Expected behavior**
I expected [modifier]-[key-name] (I thought this was how it was before). I did not expect "+" which is a reserved character in CSS. This causes problems if you want to restyle that key. I've worked around it by setting the keys to layer default and editing my layout code to add SHIFT. I could have added /# to my code, but that is klugey. The css selector problem exists in native Android an iOS as well as touch emulation. It does not affect web, which uses different configuration.

Details
---

**Keyman Developer 15.0.35:**
 - OS: Windows 10 20h2
 - Target Application: Chrome
 - Emulating iOS and Android

**Additional context**
I'm a CSS nerd.

**Comment by mcdurdin** [comment]
The `+` was chosen to avoid potential conflict with identifiers which may use `-`. You can escape the `+` character in CSS:

```css
#shift-T_003A\+default { 
  color: green;
}
```

**Comment by MattGyverLee** [comment]
Thanks @mcdurdin, understood. Is it my imagination, or is this a new change (since KM11)?

**Comment by mcdurdin** [comment]
I don't remember when it came in, sorry. Would have to review history!
