### ISSUE TITLE
bug(linux): LibreOffice draw does not backspace for contextual replacement

### ISSUE THREAD

**Issue by mhosken** [keymanapp/keyman#5154]
Keyman 14 on Linux Ubuntu 20.04. When using a contextual keyboard (Boonkit) in LibreOffice Draw (6.4.7.2) the contextual backspaces are ignored and so nothing gets deleted. This is not a problem in LibreOffice Writer.

This is probably a bug in LibreOffice more than in Keyman, but I thought I would capture it here to start with.

**Comment by mhosken** [comment]
Further testing. This doesn't seem to be a problem with Liberation Sans and SIL IPA keyboard. So perhaps it's a Graphite thing.

**Comment by darcywong00** [comment]
In Libre Draw or Writer with sil_boonkit keyboard:
<kbd>d</kbd><kbd>d</kbd><kbd>`</kbd> should yield two stacked curly "m" characters

Works on Windows 10 with Libre Office 6.3.0.4 (x64)

**Comment by ermshiperete** [comment]
Works for me on Ubuntu 20.04 (Gnome with X11) with Libre Office 7.1.3.2, sil_boonkit keyboard, Doulos SIL font, Keyman 15.0.47

**Comment by ermshiperete** [comment]
@mhosken Are you using X11 or Wayland? There's an open issue with Wayland support (#4273).

**Comment by mhosken** [comment]
X11 but Keyman 14. Do you think you did anything in 15 that would fix this? The fault is in Libo Draw, not in Writer. Writer is fine for me and maybe a newer Libo fixes it too. All very confusing. Anyway I'm happy it's just me :)

**Comment by ermshiperete** [comment]
> X11 but Keyman 14. Do you think you did anything in 15 that would fix this? 

No, the changes between 14 and 15 are minimal (to non-existent) at this point.

**Comment by ermshiperete** [comment]
From slack:

Martin Hosken: I suspect graphite in libo

**Comment by mcdurdin** [comment]
@mhosken, does #7079 fix this for you? (requires updated ibus, @ermshiperete can guide you through setup if necessary)

**Comment by ermshiperete** [comment]
Closing since this seems to work.
