### ISSUE TITLE
bug(common): some entries appear to be missing from history

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#5172]
For example #4300 should have appeared in 14.0.227, from what I can see on dates.

Logs: https://build.palaso.org/viewLog.html?buildId=248326&buildTypeId=Keyman_TriggerReleaseBuildsBeta&tab=buildLog&branch_Keyman=5054&_focus=484#_state=484

Note that 14.0.229 failed due to external reasons but that does not appear to be connected to this.

#4300 does appear in 15.0.9, as part of a bulk merge at end of sprint to master, but that would be expected.

Ref: https://community.software.sil.org/t/google-play-warning-zip-path-traversal/4853/3

**Comment by mcdurdin** [comment]
Also #5119 shows up in 3 [history](https://help.keyman.com/products/windows/version-history/) notes:

![image](https://user-images.githubusercontent.com/4498365/120121602-ada7e600-c1e7-11eb-8a76-0dfecf2c1a21.png)

And is correspondingly reported on 3 [times](https://github.com/keymanapp/keyman/pull/5119):

![image](https://user-images.githubusercontent.com/4498365/120121587-9537cb80-c1e7-11eb-987d-5d5629fe6830.png)

**Comment by mcdurdin** [comment]
Weirdness continues:

#5534 not listed in 14.0.280 but #5487 *is* (despite not being merged at time of build!)

(note: we may need to back-port some of the history stuff to stable-14.0 to resolve?)

**Comment by darcywong00** [comment]
Is the merge commit https://github.com/keymanapp/keyman/pull/5487/commits/5b21ac69622119a53c13208e03f6365e4470482b of stable-14.0 on #5487 potentially causing some issue?

**Comment by mcdurdin** [comment]
Yes, it looks like it's picking up merges going either way rather than just _into_ `master`. That gives me a good hint on what to fix, thanks.

**Comment by mcdurdin** [comment]
Work arising from #5527:

>>I'm unclear how `-b <BASE>` works.
> Yeah, you have to have that branch checked out in your repo as well. This script needs more polish, this is just getting it started.

**Comment by mcdurdin** [comment]
Resolved by #5603, #5527, #5678
