### ISSUE TITLE
docs(iOS): build Keyman for iOS on macOS

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#5191]
**Describe the bug**

One thing is missing in the prerequisites for building Keyman for iOS at https://github.com/keymanapp/keyman/blob/master/ios/README.md, Java is needed to build successfully. What works for me is to download and install OpenJDK from here: https://adoptopenjdk.net/releases.html.

---

**Keyman for macOS:**
 - OS: macOS Big Sur

---

Also, consistency purposes, `Xcode 11` on the top of the list to be updated `Xcode 11+` to indicate that it's not only for `Xcode 11`; but 11 and later.

**Comment by darcywong00** [comment]
Technically, Java is listed in the prerequisite of building Keyman Web:
> Building Keyman Web is a precursor for compiling KMEI, so verify your system has all the Minimum Web Compilation Requirements

https://github.com/keymanapp/keyman/blob/master/ios/README.md#building
