### ISSUE TITLE
bug(android): the Krung keyboard installation stuck at the PDF page

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#5208]
**Describe the bug**

The installation got stuck at the welcome page where PDF viewer is present. The PDF file keep loading when an attempt was made to get back or get out of the PDF.

**To Reproduce**

On Android:
1. Go to install Krung keyboard from keyman.com
2. Follow the screen to install the keyboard
3. Tap on 'Install' at the bottom right of the screen
4. The PDF got loaded and one or two tap on the back button won't take the user away from the page
5. See error

**Expected behavior**

One tap on the back key should bring the user back to wherever s/he supposed to be, not reloading the PDF.

**Screenshots**

Stuck here:
![image](https://user-images.githubusercontent.com/28331388/120265002-3d719100-c2c9-11eb-9a41-d09661600a8b.png)

---

**Keyman for Android:**
 - Device: Pixel 2 API 29
 - OS: Android 10
 - Keyman version 14.0.274
 - Target application: Keyman

---

**Keyboard**
 - Keyboard name: krung
 - Keyboard version: 1.0.1
 - Language name: Krung

**Comment by MakaraSok** [comment]
@darcywong00 Is this issue caused by the way the PDF is embedded and not because of Keyman itself. If so, I'll try and fix the keyboard help page by removing the embedded PDF and including a link to the PDF instead.

**Comment by darcywong00** [comment]
Maybe. 
Can you convert this
https://github.com/keymanapp/keyboards/blob/b95fb24d3d95a303e9fa6567d63be10e0fae7f8d/release/k/krung/source/welcome/welcome.htm#L1665-L1666

to an HTML link to the PDF and see if that works when you're installing the package?

**Comment by MakaraSok** [comment]
fixed: https://github.com/keymanapp/keyboards/pull/1562
