### ISSUE TITLE
bug(developer): Redist path not specified

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#5212]
**Describe the bug**

When "Compile Installer", an error occurs even though .kmp is compiled successfully.

```
khmer_angkor.kps: Compiling package khmer_angkor.kps...
khmer_angkor.kps: Redist path not specified, loading default (C:\Program Files (x86)\Keyman\Keyman Developer\redist\setup\)
khmer_angkor.kps: Compiling package khmer_angkor.kps...
khmer_angkor.kps: Success: 'C:\keyman\keyboards\keyboards\release\k\khmer_angkor\source\khmer_angkor.kps' compiled successfully.
```

When going to the build folder, the .exe is found and that's the expected bundle.
![image](https://user-images.githubusercontent.com/28331388/120418072-16c75f00-c38a-11eb-97fb-b1d31f3452c6.png)

**To Reproduce**

1. Go to 'khmer_angkor' keyboard folder
2. Click to open '.kpj' and configure the "Compile Installer"
3. Compile Installer

**Expected behavior**

Since the `setup.exe` is in `C:\Program Files (x86)\Keyman\Keyman Developer\Redist\Setup`, the compile should not say the path doesn't exist.

---

**Keyman Developer:**
 - OS: Windows 10 221H1 x64
 - Keyman Developer version: 14.0.274 

---

**Keyboard**
 - Keyboard name: khmer_angkor
 - Keyboard version: 1.0.9
 - Language name: Khmer

**Additional context**

cf: https://github.com/keymanapp/keyman/issues/4354

**Comment by mcdurdin** [comment]
Yeah, that's not an error, just information -- so I think we can leave it as is.

**Comment by MakaraSok** [comment]
> Yeah, that's not an error, just information -- so I think we can leave it as is.

Why was the info given? Why the path was not specified? Should the path be specified manually? If so, how?

**Comment by mcdurdin** [comment]
This is all very old UX -- it hasn't been updated for possibly 10 years. So ... 

> Why was the info given?

Just telling the keyboard dev that the default redistributable is in use.

> Should the path be specified manually?

Not normally, no.

> If so, how?

I think it can be set in the last page of the Package Editor.
