### ISSUE TITLE
bug(ios): advertising identifier flag needs to be set for release build

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#5226]
**Describe the bug**

```
[Step 6/9] /Library/Ruby/Gems/2.6.0/gems/fastlane-2.182.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [!] Use of Advertising Identifier (IDFA) is required to submit (FastlaneCore::Interface::FastlaneError)
```

https://build.palaso.org/viewLog.html?buildId=272460&buildTypeId=Keyman_iOS_Master&tab=buildLog&_focus=2486#_state=786

This needs to be checked in the FV Keyboards build as well.

---

**Keyman for iPhone/iPad/Android:**
 - Device: 
 - OS: iOS 
 - Keyman version: 14.0.275-stable

**Comment by jahorton** [comment]
FV builds already has it in its build configuration, actually.  It's the Keyman app that didn't.  I've updated the configuration accordingly.  There are no major changes there, so I'll leave the script where it is for now.
