### ISSUE TITLE
bug(ios): FV Keyboards 'what's changed' is for US English instead of Canada English

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#5227]
**Describe the bug**

FV Keyboards primary language is English (Canada) but we still populate the What's Changed data into English (US). In order to automate, we need to populate the English (Canada) field instead.

https://build.palaso.org/viewLog.html?buildId=272460&buildTypeId=Keyman_iOS_Master&tab=buildResultsDiv

---

**Keyman for iPhone/iPad/Android:**
 - Device: 
 - OS: iOS 
 - Keyman version: 14.0.2745-stable

**Comment by jahorton** [comment]
I've gone ahead and added a duplicate entry for `en-CA` in the TeamCity build config script that publishes to the App Store.  Hopefully I got it right; we'll see come next `stable` release.

**Comment by mcdurdin** [comment]
I've checked this in 14.0.288-stable and it looks fine: content in both en-US and en-CA.
