### ISSUE TITLE
bug(ios): FV Keyboards needs encryption export compliance details set

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#5228]
**Describe the bug**

App Store Connect requires us to set the encryption export compliance for FV Keyboards.

https://stackoverflow.com/a/46691541/1836776

https://build.palaso.org/viewLog.html?buildId=272460&buildTypeId=Keyman_iOS_Master&tab=buildResultsDiv

---

**Keyman for iPhone/iPad/Android:**
 - Device: 
 - OS: iOS 
 - Keyman version: 14.0.275-stable 
 - Target application:

**Comment by mcdurdin** [comment]
Dup of #5225

**Comment by jahorton** [comment]
... this is the more informative version, actually.  Oh well.
