### ISSUE TITLE
feat(android): uncheck 'show on startup' automatically in Get Started once all steps complete

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#5229]
**Is your feature request related to a problem? Please describe.**

Once all three steps have been completed in the Get Started activity, the "Show 'Get Started' on startup" check box should be cleared automatically. The user could turn it back on again if they wanted.

Consider whether we want to close the activity automatically altogether at this point.

---

**Keyman for iPhone/iPad/Android:**
 - Device: Android 
 - OS: Android 11 
 - Keyman version: 14.0.275

**Comment by darcywong00** [comment]
We'll uncheck if just steps 2-3 are completed
1. Add a keyboard for your language
2. Enable Keyman as a system-wide keyboard
3. Set Keyman as default keyboard

**Comment by darcywong00** [comment]
Fixed in 16.0 beta by #7587
