### ISSUE TITLE
bug(android): going back while `progressDialog` is visible does not destroy the activity

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#5242]
**Describe the bug**

If `progressDialog` has been created (e.g. from `downloadKmp`), if you touch the back button, it dismisses the progress dialog but does not destroy it, which makes it impossible to re-enter and start another download.

**To Reproduce**

1. Start to download a keyboard.
2. As soon as the down progress dialog is shown, click Back `<`.
3. Try again.
4. See that nothing happens.

---

**Keyman for iPhone/iPad/Android:**
 - Device: Android 
 - OS: Android 11 
 - Keyman version: 14.0.275-stable

**Comment by darcywong00** [comment]
I'm having difficulty with repro.
Granted, when I cancel the progress dialog, it doesn't stop the background download from completing and launching the kmp installer wizard.
When I back out of the wizard, I could restart a keyboard search for a different keyboard and that one would download and install.
