### ISSUE TITLE
bug(windows): clicking the (none) link in Hotkeys can crash

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#5245]
**Describe the bug**

@MakaraSok experienced a crash on his computer when trying to change a hotkey. This happens consistently. Dump attached.

---

**Keyman for Windows/macOS/Linux:**
 - OS: Windows 10 
 - Keyman version: 14.0.275 

**Additional context**

[kmshell.zip](https://github.com/keymanapp/keyman/files/6620944/kmshell.zip)

**Comment by MakaraSok** [comment]
To repro, fresh install the latest stable (14.0.275). Install a few keyboard and now try to set hotkeys for them. Once `none` is clicked on to set a hotkey for a given keyboard, the Configuration crashes a little while after.

**Comment by mcdurdin** [comment]
Problem is mismatched kmcomapi.dll: #5222 was previously installed which left kmcomapi.dll with different interfaces. The interfaces should not remove old methods but just no-op them. This needs to be fixed in #5222 and also in 15.0.
