### ISSUE TITLE
bug(web): OutputTarget.buildTransformFrom (String.kmwCharAt) is hideously slow

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#5246]
**Describe the bug**

Ref: https://community.software.sil.org/t/the-more-i-type-the-slower-the-prediction-speed/3552/9

When using Keyman on a mobile device, after typing a few lines (in my case 12 lines on my Android phone), the input becomes visibly slower.

I attached a sampling profiler and typed "test", with the following outcomes:

1. It took roughly 480ms of script time for each keystroke.
2. 94% of that time was spent in `String.kmwCharAt` and its descendents
3. Its primary use was in `OutputTarget.buildTransformFrom` (also 94% of total time), which was called over 30 times per keystroke.

The use in `buildTransformFrom` is exponential -- kmwCharAt itself scans from start of string, so this is super expensive!

Chrome DevTools Profile is attached. 

Ways forward:
1. Optimise kmwString internals. It's pretty rudimentary at present.
2. Try swapping out the kmwString module for an alternative that may be more performant (#2492)? Even just in this one place as an initial test?
3. Do we need to use kmwString in `buildTransformFrom` or can we just use standard String functions?
4. It would also be good to look at `buildTransformFrom` and see if its usage can be made more performant - either by implementation or reducing number of calls to it.

**Screenshots**

![image](https://user-images.githubusercontent.com/4498365/121291933-6c70ae00-c92c-11eb-930a-257297169535.png)
[Profile-20210609T141024.zip](https://github.com/keymanapp/keyman/files/6621034/Profile-20210609T141024.zip)

---

**KeymanWeb:**
 - OS: Android 11 
 - Browser: Chrome webview 
 - KeymanWeb Version: 14.0.275 

---

**Keyboard**
 - Keyboard name: sil_euro_latin 
 - Keyboard version: 1.9.3 
 - Language name: English 
 - Model: mtnt 0.1.6

**Comment by jahorton** [comment]
Future work in this direction has been documented as #5258.

#5248's improvement to the algorithm has resolved the issues and questions raised by the analysis seen here.
