### ISSUE TITLE
bug(android): Inconsistent OSK dimensions on rotation - in-app

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#5252]
**Describe the bug**

Split out from #5211.

@darcywong00 writes:

During testing of #5201, I noticed the OSK height doesn't reliably resize to the correct height when toggling between portrait and landscape orientation. (landscape usually ends up "taller" than what the default dimension specifies)

Going into the globe button menu and existing seems to refresh OSK to the correct dimensions.
This affects both in-app and system keyboard; this issue is about the in-app glitches.

Keyman 15

---

**Keyman for iPhone/iPad/Android:**
 - Device: Samsung Galaxy A90 (@mcdurdin test) 
 - OS: Android 11 
 - Keyman version: 15.0.65-alpha 
 - Target application: Keyman

**Comment by MakaraSok** [comment]
FYI, while testing https://github.com/keymanapp/keyman/pull/5247, these were noticed:

_The in-app test shows that the black banner issue persists on the virtual device, but not the physical one._
![Screenshot_1622704411](https://user-images.githubusercontent.com/28331388/121458097-f4a98e80-c9d2-11eb-97fb-9140977f04ae.png)

![Screenshot_1623290287](https://user-images.githubusercontent.com/28331388/121457658-3980f580-c9d2-11eb-9c46-ca584358f43e.png)

_If refresh while (by pressing on the globe key) on horizontal mode, the keyboard would be cropped off when switch back to vertical._
![Screenshot_1623290337](https://user-images.githubusercontent.com/28331388/121457758-62a18600-c9d2-11eb-817a-8a716d7f6f35.png)
