### ISSUE TITLE
chore(android): cleanup error case for PackageActivity

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#5264]
yeah, kmpFile in the bundle is required.
Maybe we just exit if bundle is null?

_Originally posted by @darcywong00 in https://github.com/keymanapp/keyman/pull/5240#discussion_r647884339_

**Comment by darcywong00** [comment]
Possibly related to #6862

**Comment by darcywong00** [comment]
Fixed in 16.0 beta by #7603
