### ISSUE TITLE
bug(android): Keyman for Android disappears on Twitter post after rotating and can't get it back on 

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#5277]
**Describe the bug**

Keyman works OK in vertical mode on Twitter, but when switch to the horizontal mode it disappears. Tapping in the text area again does not bring it back on either.

**To Reproduce**

1. Go to 'Twitter' and tap to start writing a tweet using the default Keyman keyboard (EuroLatin)
2. Tilt the keyboard to horizontal to continue typing
3. The keyboard disappears and now tap in the text area on the tweet 

**Expected behavior**

The keyboard should appear and work as normal in the horizontal mode.

---

**Keyman for Android:**
 - Device: Samsung Galaxy S9+
 - OS: Android 10
 - Keyman version 
https://github.com/keymanapp/keyman/pull/5247

**Comment by darcywong00** [comment]
Observing Twitter behavior with landscape OSK

On GBoard, starting a message begins in this main composition view
![twitter main](https://user-images.githubusercontent.com/7358010/122008080-d08aea80-cde2-11eb-9135-310a0ccecaa0.jpg)

and then immediately pulls up a separate text area with the keyboard.
![twitter text area](https://user-images.githubusercontent.com/7358010/122008053-ca950980-cde2-11eb-986c-9ce11c890ecb.jpg)


When the Keyman  for Android keyboard is loaded, it seems like Twitter is trying to switch to this separate text area, but keeps dismissing to the main composition view.

**Comment by darcywong00** [comment]
I cannot repro with this configuration:

## Configuration
Keyman for Android 15.0.200 alpha
Wancho system Keyman keyboard
Twitter
Android 11 device.

![twitter landscape](https://user-images.githubusercontent.com/7358010/155086393-193b1b57-dabf-42b0-9161-0a2f9c527055.jpg)

**Comment by darcywong00** [comment]
@MakaraSok can you try to repro with the latest 15.0 beta?

**Comment by darcywong00** [comment]
Fixed by #6498
