### ISSUE TITLE
feat(developer): modernise command line tooling

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#5283]
streamlining the use of the Keyman Developer tooling:

1. Native command-line Keyman development tools for Linux, macOS and Windows.
2. `apt install keyman-compiler` (or something like that)
3. A good set of documentation on 'getting started' (or refreshing knowledge) with the command line tools.
4. Update kmcomp and kmconvert to use the "generate" paradigm common to development tools these days (it's all there, just needs rewording and organising):
       kmdev generate project foo  # generates a new keyboard project from a template, supporting all platforms by default
       kmdev duplicate project foo bar  # copies the foo project, renaming files to bar as needed

Something like that is my long-term goal for the development tools. Then, a simple `kmdev build [foo]` will build the target package which can be distributed either directly to users or uploaded to Keyman Cloud for wider distribution.

**Update:** Design doc: https://docs.google.com/document/d/1ra7jQgg0ZDC8QcVIFRyA_Xw0kya3HS5ITSjJBsSNTtQ/edit#heading=h.me4lkdiw0zz5

---

**Keyman Developer:**
 - OS: any 
 - Keyman Developer version: 15.0

**Comment by mcdurdin** [comment]
Intention:

Design: 16.0.
Implementation: Future.

**Comment by darcywong00** [comment]
@mhosken has some thoughts on what he'd find convenient:

>ideally having kmcomp do .kmn->.kmp with a minimal package would be nice (as well as all the rest)
>
> so I would just type `kmcomp -o xyz.kmp xyz.kmn` would be wonderful
> if I want more, then I would have to create a .kps
> 
> also kmcomp -o xyz.kps xyz.kmn generating a template .kps (as would be used in the previous command) so that I can add whatever, would be nice too

**Comment by mcdurdin** [comment]
> ideally having kmcomp do .kmn->.kmp with a minimal package would be nice (as well as all the rest)

[kmconvert](https://help.keyman.com/developer/current-version/context/kmconvert) generates a minimal project .kpj and .kps with the `template` parameter. Does this do what you need @mhosken?

**Comment by mcdurdin** [comment]
> so I would just type `kmcomp -o xyz.kmp xyz.kmn` would be wonderful

I don't really want to support this. There is additional metadata that we need for a .kmp which is not in the .kmn (e.g. fonts, docs, language metadata, license information). This is the kind of thing that you could do with a very simple script to meet your own needs, but it is not generically applicable, so would create more problems that it solves for a general use case.

**Comment by mcdurdin** [comment]
Given everything that has been happening, postponing this change to 17.0.

**Comment by mcdurdin** [comment]
See https://docs.google.com/document/d/1ra7jQgg0ZDC8QcVIFRyA_Xw0kya3HS5ITSjJBsSNTtQ/edit#heading=h.me4lkdiw0zz5 for design doc

**Comment by mcdurdin** [comment]
Note: error message cleanup is in scope for this issue, as well as exit codes. See #8580.

**Comment by mcdurdin** [comment]
Marking this as complete for A17S14. Infrastructure is in place and additional work can be done without reference to this.
