### ISSUE TITLE
KMSample1 still input is English no tamil

### ISSUE THREAD

**Issue by naguchennai** [keymanapp/keyman#529]
How can i get tamil? i try KMSample1 its still input is english only? why?
KMManager.KMKey_PackageID not import

**Comment by darcywong00** [comment]
Hi there,

We've been working on a new feature that makes use of a package ID field. Some of the Sample projects may not be completely updated yet.

Can you provide some more details like
1. Which platform are you trying to run? iOS? Android?
2. Which link did you use to get the KMSample1 project? (so we'll know what version of the code you're using)

I've pulled the current `master` branch and can get KMSample1 to type Tamil on Android with these steps
```
cd android/KMEA
./build.sh
cd ../Samples/KMSample1
./build.sh
```

In Android Studio, I then run the app and get this

![kmsample1 android tamil](https://user-images.githubusercontent.com/7358010/35103806-9173c1aa-fc99-11e7-8b40-286015c4b511.png)

**Comment by naguchennai** [comment]
ok i tested it for andtoid. i will check again. can you pls make Tamil keybord from english input to tamil language? google indic keyboard can work like that.

**Comment by darcywong00** [comment]
I installed the Google Indic keyboard on my device and it has 3 options:
1. English keys typing English text
2. English keys typing Tamil text
3. Tamil keys typing Tamil text.

It sounds like you would like the second one where the labels on the keys are English (Latin) letters, and when you type them, you get Tamil text. Is that correct?

If you download the Keyman for Android app, you'll have access to about 11 Tamil keyboards.

![keyman tamil keyboards](https://user-images.githubusercontent.com/7358010/35132999-8beedbcc-fd00-11e7-8d6d-1386ae0a3365.png)

Once you find one with a layout you want, you can use Keyman Developer to create a keyboard so that it has English keys and outputs Tamil text.

**Comment by naguchennai** [comment]
Yes we need "English keys typing Tamil text" you are right .. but there is no in your 11 Tamil keyboard.. All 11 keyboard layout are in tamil we need layout in english when type tamil need display

Pls develop Keyboard the labels on the keys are English (Latin) letters, and when you type them, you get Tamil text. thank you . Can we wait.. how many days it take?

**Comment by mcdurdin** [comment]
ISIS-Tamil uses an English layout and generates Tamil output, as does அஞ்சல் பாங்கு | Anjal Paangu.

**Comment by naguchennai** [comment]
you closed this post with wrong info. isistamil layout not in english its also tamil layout. there is no layout you have with eng. before close post just check

**Comment by mcdurdin** [comment]
Okay, then I don’t know what you mean by an “English” layout. Perhaps you could create one with Keyman Developer and share it with us?

**Comment by naguchennai** [comment]
So you closed this for you don’t know what i am telling? its ok English Layout means. like a, b c, d etc when keyboard is open.. when tamil user type "amma" using english input ... result must be "அம்மா " check this google keyboard 
https://www.google.com/intl/ta/inputtools/try/

Where i can find Keyman Developer?????? you can find one and possible create?

just tell me yes or no?

if not possible  just tell me **" it is not possible in keyman  So i closed this Issue"** after that you can close this.. not close with wrong info and act like your code is good one.. you need accept if not possible you need tell its not possible .. any way sorry i am just hard and bold type

**Comment by darcywong00** [comment]
Keyman Developer is the free Windows program you can use to create the Tamil keyboard you want
(English labels on the keys outputting Tamil text). 

You can get installer to Keyman Developer 9.0 [here](https://keyman.com/developer/download.php)

@mcdurdin has written a lot of guides on how to use Keyman Developer to create your keyboard.

If you're looking to use your keyboard on a desktop (Windows PC, Mac), here is a good [tutorial](https://help.keyman.com/DEVELOPER/9.0/guides/develop/tutorial/)
to start with.

If you're looking to create a touch layout keyboard to use on mobile devices (Android, iOS), use this [tutorial](https://help.keyman.com/developer/9.0/guides/develop/creating-a-touch-keyboard-layout-for-amharic-with-keyman-developer-9)

**Comment by mcdurdin** [comment]
Those two keyboards I mentioned work precisely like that. They also show Tamil letters on the key cap for reference purposes, but they are phonetic-style input methods.

**Comment by naguchennai** [comment]
@mcdurdin  thankyou i got your point .. thank you again .. Can you explain How can i Change This keyboard layout? i need eng only

**Comment by mcdurdin** [comment]
Which platform do you want to use the keyboard on? Android, Windows? Something else?

**Comment by naguchennai** [comment]
Android sir

**Comment by mcdurdin** [comment]
Right now, the source for those keyboards is not yet published -- we are working through these but it takes time.

Currently, the ISIS keyboard is not open source; this is a dialog we need to open with the author. The Anjal Paangu keyboard is open source but we don't currently maintain the source, and the maintainers of the source for that keyboard are not currently maintaining it. So it's not easy for you to modify these existing keyboards, until we have the time available to publish the source.

But you can certainly create a new one following the pointers that @darcywong00 provided.

**Comment by naguchennai** [comment]
O ok  nothing in your hand? ok thank you . so its not possible .. close this thread. i will try some other library thank u

**Comment by mcdurdin** [comment]
It's certainly possible, but you are right we don't have anything ready for you to pick up and use. Good luck!
