### ISSUE TITLE
bug(web): resizing desktop OSK sometimes causes it to "pop" to a fixed width

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#5296]
**Describe the bug**

When you resize the desktop OSK, when you get larger than a certain size, it "pops" into a fixed, narrow width which is definitely incorrect.

![image](https://user-images.githubusercontent.com/4498365/122194477-d3680700-ced8-11eb-9e67-ff5749824b95.png)

See the screen capture for a live example: 

https://user-images.githubusercontent.com/4498365/122194512-db27ab80-ced8-11eb-991b-e76078d75ff2.mp4

**To Reproduce**

1. Go to https://keymanweb.com/#jv-java,Keyboard_jawa
2. Click in the text field and drag the corner of the OSK to resize it
3. See error

This may be related to the OSK sometimes loading at the same fixed width when loading a KeymanWeb page?

---

**KeymanWeb:**
 - OS: Windows 10 
 - Browser: Chrome 91 
 - KeymanWeb Version: 14.0.276

**Comment by jahorton** [comment]
Should be fixed already as part of #5428.

**Comment by mcdurdin** [comment]
Tested fixed with 14.0.278 on keymanweb.com.
