### ISSUE TITLE
bug(android): longpress doesn't reveal the popped up keys all the time

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#5301]
**Describe the bug**

Usually, press and hold on a longpress key reveals more keys in the popped up keys, but sometimes somehow this mechanism does not work as expected.

**Expected behavior**

**Screenshots**

keys which does not reveal popped up keys (not always these though): "q, t, u, o, i, j, g, d and a"
https://youtu.be/wRRU32cFYIg

---

**Keyman for Android:**
 - Device: Samsung Galaxy
 - OS: Android 10
 - Keyman version: 14.0.276
 - Target application: Keyman

---

**Keyboard**
 - Keyboard name: EuroLatin (SIL)
 - Keyboard version: 1.9.4
 - Language name: English

**Comment by darcywong00** [comment]
I was able to eventually repro, but haven't found consistent steps...

It's acting like sometimes the longpress isn't detected

![longpress](https://user-images.githubusercontent.com/7358010/122522292-fc56dc00-d03f-11eb-95b4-46bf0e71ac28.jpg)


## Configuration
Keyman for Android 14.0.276
OS: Android 8.1
Target application: Keyman

Keyboard
EuroLatin (SIL) version 1.9.4
Language: English

**Comment by rowbory** [comment]
I wondered whether alignment of the tap/press position and margins/padding might be causing issues. I've noticed it here and there but found it difficult to reproduce reliably. Is it possible to press on the edge of a key so that it shows the main key but doesn't show a longpress popup? I'll let you know if I get any clearer insight into what's going on.

**Comment by mcdurdin** [comment]
The issue appears to be if the user makes a micro-movement when they start the longpress. This movement is not enough to move off the key but is enough to cancel the longpress logic.

This appears to be a problem only for Keyman for Android -- KeymanWeb works fine.

**Comment by darcywong00** [comment]
Yeah, if the user moves while starting the longpress, it will trigger popup on other keys, but never detect a longpress.

**Comment by darcywong00** [comment]
Fixed by #6138
