### ISSUE TITLE
bug(linux): Keyman does not appear to work with VS Code

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#5307]
**Describe the bug**

I am unable to type with a Keyman keyboard in Visual Studio Code: I simply get the base keyboard output. This is true for the editor windows, terminal, even the File Open, search box.

---

**Keyman for Windows/macOS/Linux:**
 - OS: Ubuntu 20.04 
 - Keyman version: 14.0.276 
 - Target Application: VS Code 1.57.0

**Comment by ermshiperete** [comment]
It works for me. 

How did you install vscode? Did you install it as a snap or flatpak package, or the downloaded .deb file, or the package from https://packages.microsoft.com/repos/code? 

I assume Keyman works in other apps like gedit?

**Comment by mcdurdin** [comment]
* Looks like I installed with snap.
* Keyman is working in other apps (gedit, firefox, terminal, etc).

VS Code environment:

Version: 1.57.0
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T17:18:42.895Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.8.0-55-generic snap

Are there logs I can capture?

**Comment by ermshiperete** [comment]
It looks like this might be a general problem in the vscode snap package: https://github.com/microsoft/vscode/issues/96041

**Comment by ermshiperete** [comment]
Needs to be solved in vscode snap package.
