### ISSUE TITLE
bug(linux): packages installed shared do not appear in ibus

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#5311]
**Describe the bug**

A package installed to shared with does not appear in ibus, even after restarting.

```shell
km-package-install -s -f sample.kmp
```

---

**Keyman for Windows/macOS/Linux:**
 - OS: Ubuntu 20.04 
 - Keyman version: 14.02.76

**Comment by ermshiperete** [comment]
What do you mean "does not appear in ibus"? You should be able to add it to the list of Input Sources.

**Comment by mcdurdin** [comment]
> What do you mean "does not appear in ibus"? You should be able to add it to the list of Input Sources.

Per discussion, pretty sure the issue was that it was not automatically added. Will re-test with the updated PRs #5371, #5372, #5373.

**Comment by mcdurdin** [comment]
I found I need to exit the Language and Region Settings app and restart it before the newly installed package will be available.

It would be good to have a method of adding the keyboard for the logged in user as well (with an additional parameter for `km-package-install`)
