### ISSUE TITLE
bug: warnings when installing lexical model compiler

### ISSUE THREAD

**Issue by rc-swag** [keymanapp/keyman#5320]
**Describe the bug**

when running "npm install @keymanapp/lexical-model-compiler" 
I received some warnings about no such file or directory.
Note: I did this on Win10 machine in a git-bash shell

**To Reproduce**

1. Go to 'https://help.keyman.com/developer/14.0/guides/command-line' 
2. Follow the instructions under Linux and Macos installation
3. at step "npm install @keymanapp/lexical-model-compiler" 
4. See the warning 
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\ross_\DeleteMe\kmcomp\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\ross_\DeleteMe\kmcomp\package.json'
npm WARN kmcomp No description
npm WARN kmcomp No repository field.
npm WARN kmcomp No README data
npm WARN kmcomp No license field.
**Expected behavior**

No warnings about such file or directory.

**Keyman for Windows:**
 - OS: 
 - Keyman version:

**Comment by mcdurdin** [comment]
OK, this should probably be `npm install --global @keymanapp/lexical-model-compiler`

**Comment by rc-swag** [comment]
> OK, this should probably be `npm install --global @keymanapp/lexical-model-compiler`

Yes this worked with out warnings the output is:
``
$ npm install --global @keymanapp/lexical-model-compiler
C:\Users\ross_\AppData\Roaming\npm\kmlmp -> C:\Users\ross_\AppData\Roaming\npm\node_modules\@keymanapp\lexical-model-compiler\dist\kmlmp.js
C:\Users\ross_\AppData\Roaming\npm\kmlmi -> C:\Users\ross_\AppData\Roaming\npm\node_modules\@keymanapp\lexical-model-compiler\dist\kmlmi.js
C:\Users\ross_\AppData\Roaming\npm\kmlmc -> C:\Users\ross_\AppData\Roaming\npm\node_modules\@keymanapp\lexical-model-compiler\dist\kmlmc.js
+ @keymanapp/lexical-model-compiler@14.0.276
updated 1 package in 0.982s
``

**Comment by mcdurdin** [comment]
Updated documentation to use `--global`.
