### ISSUE TITLE
feat(linux): Allow to specify language in command line tools

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/keyman#5361]
Add a `-l`/`--language` parameter to `km-config` and `km-package-install` command line tools that allows to pass a BCP47 language. The keyboard would then be added for that language.

Optional would could allow this parameter to occur multiple times - we then would add the keyboard for each specified language.

Can we add something to tab-completion to support this feature?

**Comment by darcywong00** [comment]
Low-hanging fruit to tackle in 17.0

**Comment by ermshiperete** [comment]
This was partially implemented by #7731/#7725 (implemented for `km-package-install`).

We should still consider adding tab-completion support.
