### ISSUE TITLE
bug(windows): the first sequence not rendered correctly

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#5394]
**Describe the bug**

When using Bunong (SIL) keyboard in MS Office Word, the first two character sequence does not render correctly. The consonant and the vowel does not combine as expected. The consonant and vowel sequences after that are rendered correctly though (see the screenshot below).

![image](https://user-images.githubusercontent.com/28331388/123768095-3b174c80-d8f2-11eb-86c3-91cedcf7ec28.png)

Note that this doesn't happen in Google Docs nor Notepad. This issue seems to be app and keyboard specific.

**Expected behavior**

The first sequence on the very first line in MS Office Word should be rendered correctly. 

---

**Keyman for Windows:**
 - OS: Windows 10 Pro 21H1 x64
 - Keyman version: 14.0.277
 - Target Application: MS Office Professional Plus 2016, version 2105

---

**Keyboard**
 - Keyboard name: [sil_bunong](https://keyman.com/keyboards/sil_bunong?bcp47=cmo-khmr)
 - Keyboard version: 1.0
 - Language name: Bunong

**Comment by MakaraSok** [comment]
This behavior does not happen when using Khmer Angkor keyboard though.

**Comment by mcdurdin** [comment]
Believe this issue is related to the language tagged in Office. If you tag with Khmer, then it should work correctly. This really should be raised as an issue with Microsoft.
