### ISSUE TITLE
feat(android): move all network and sd file access out of Keyman Engine into Keyman

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#5396]
**Is your feature request related to a problem? Please describe.**

Keyman Engine should not make network connections, nor should it access user files. The host app should provide access to resources as required.

There are two current points where Keyman Engine accesses network:

* Sentry error reporting
* Checking for resource updates / downloading resources

**Describe the solution you'd like**

1. Error reporting should be delegated to the host app (if necessary, provide a callback).
2. Checking for resource updates and downloading resources should be done in the host app also.

---

**Keyman for iPhone/iPad/Android:**
 - Device: Android 
 - Keyman version: 14.0 

---

Emerging from discussions at https://community.software.sil.org/t/kab-support-for-keyman-14-or-15/4857

**Comment by darcywong00** [comment]
This also ties to some Keyboard App Builder users who would like the network permission removed from the Keyman Engine AndroidManifest.xml file.

Network access is also used to display keyboard help page (help.keyman) on the Keyboard Info pages.

**Comment by mcdurdin** [comment]
> Network access is also used to display keyboard help page (help.keyman) on the Keyboard Info pages.

This should definitely be in Keyman, not Keyman Engine.

**Comment by chrisvire** [comment]
I believe this covers our needs in Keyboard App Builder.  Thanks!

**Comment by mcdurdin** [comment]
All PRs relating to this issue should be run past the KAB team before merge.

**Comment by mcdurdin** [comment]
Per @chrisvire:

Main issues:
* sentry.io
* AndroidManifest.xml : READ_EXTERNAL_STORAGE, INTERNET, ACCCESS_NETWORK_STATE permissions
* `getUpdateTool().checkForResourceUpdates()`

**Comment by darcywong00** [comment]
This will deprecate some of the KMManager [APIs](https://help.keyman.com/developer/engine/android/15.0/KMManager/):

* [addKeyboardDownloadEventListener](https://help.keyman.com/developer/engine/android/15.0/KMManager/addKeyboardDownloadEventListener)
* [getMaySendCrashReport](https://help.keyman.com/developer/engine/android/15.0/KMManager/getMaySendCrashReport)
* [hasConnection](https://help.keyman.com/developer/engine/android/15.0/KMManager/hasConnection.php)?
* [setMaySendCrashReport](https://help.keyman.com/developer/engine/android/15.0/KMManager/setMaySendCrashReport)
* [setShouldCheckKeyboardUpdates](https://help.keyman.com/developer/engine/android/15.0/KMManager/setShouldCheckKeyboardUpdates.php)

**Comment by mcdurdin** [comment]
Does #5752 cover off everything we need here?
