### ISSUE TITLE
bug(mac): Issues with GFF Gurage Letter Composition (Unicode  14)  on MacOS

### ISSUE THREAD

**Issue by dyacob** [keymanapp/keyman#5398]
**Describe the bug**

@mcdurdin  , thanks for the previous fixes and back-porting the fix into 14.0.277 .  The issue with the missing data in the dialogs is resolved.  There remains an issue with letter composition that has been there throughout for MacOS.  

The issue is with letters that are new in Unicode version 14.0 which is itself in Beta presently.  This may be the underlying problem if the OS is validating characters.  The new address range is Ethiopic Extended-B that begins at `U+1E7E0` .  As a point of comparison, Keyman for Mac has worked fine outside of the Unicode BMP, the GFF Musnad keyboard uses letters in the range  U+10A60 (but has been in Unicode for over a decade).

**To Reproduce**
Install version 2.1 of the Abyssinica SIL font which is required for the new Gurage letters (https://software.sil.org/downloads/r/abyssinica/AbyssinicaSIL-2.100.zip)

1. Start the GFF Gurage Keyboard
2. Go to an editor app.
3. Type: h + y + e
4. The glyph for U+1E7E0 should appear on the screen at the end of the composition.

**Expected behavior**
1. Upon hitting 'h', U+1215 (ሕ) appears correctly.
2. Upon hitting 'y', U+1E7E6  should appear, however, no character will be seen on the screen.
3. Upon hitting 'e', U+1E7E0 should appear, instead U+12A5 (እ) appears.

**Screenshots**

Related, upon installing the .kmp file at the URL below, Keyman 15.0.77-alpha goes into this grayed-out disabled state.  I had to restart my MacBook to Keyman to recover.

<img width="576" alt="Screen Shot 2021-06-30 at 11 11 22 AM" src="https://user-images.githubusercontent.com/8098333/123989188-a7e42280-d996-11eb-938e-88b7dee012f7.png">sss

---

**Keyman for macOS**
 - OS: Big Sur Version 11.4
 - Keyman version: 14.0.276, 14.0.277 , 15.0.77-alpha
 - Target Application: Microsoft Word, Sublime

---

**Keyboard**
 - Keyboard name: GFF Gurage
 - Keyboard version: 0.8.x
 - Language name: Gurage (sgw)
 
Note that keyboard version 0.8.0 set the keyman &Version to 14.0 , 
version 0.8.1 set the &Version to 10.0 .

I've made a special version of 0.8.1 with the &Versio returned to 14.0 here:

https://drive.google.com/file/d/11RMPSdoUDj27SU4NFFlAlBQGZ9odQTzz/view?usp=sharing

I'm not recalling why I set the Keyman version to 14.0, I vaguely remember some fix made in version 14 that was important here.

**Comment by mcdurdin** [comment]
This is a known issue (#1643) in Keyman for macOS that we are aiming to address in 15.0 when we replace the Keyman Engine for macOS core keyboard processor with a common one used already in Keyman for Linux.

**Comment by dyacob** [comment]
i see, i'm relieved to know that it's not something odd in the .kmn file.  The other GFF keyboards seem fine, it's just the Gurage one that has had trouble so far, the pre-final Unicode additions was the only difference that stood out to me.

**Comment by mcdurdin** [comment]
Yes, it's an issue with SMP in the context. I will go ahead and close this issue if that's okay, as we can track in #1643, and that issue will now have a link to this one.
