### ISSUE TITLE
bug(android): initial keyboard load improperly links custom fonts

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#5418]
**Describe the bug**
If the last keyboard used within the Android app has a custom font set, when the app launches, the keyboard will load without that font.

Example using `sil_cameroon_qwerty`:

![Screen Shot 2021-07-02 at 12 57 35 PM](https://user-images.githubusercontent.com/25213402/124227872-879e9a00-db35-11eb-810a-a67bc906a5ae.png)

Any later reload shows up as normal:

![Screen Shot 2021-07-02 at 12 59 08 PM](https://user-images.githubusercontent.com/25213402/124227917-984f1000-db35-11eb-906e-93405deaeda2.png)

After some investigation, I found the following noteworthy bits in KMW after adding a temporary logging statement:

While loading the first keyboard:

![Screen Shot 2021-07-02 at 12 48 08 PM](https://user-images.githubusercontent.com/25213402/124227966-ab61e000-db35-11eb-9c05-da31f3560626.png)

Any later loads:

![Screen Shot 2021-07-02 at 12 49 23 PM](https://user-images.githubusercontent.com/25213402/124228040-c7fe1800-db35-11eb-8956-4105a2957841.png)

Since the link isn't being set correctly on that initial load, the font fails to load.  Now, as to _why_ it's being linked incorrectly... that'll take more time to discern.

**To Reproduce**
1. Launch the Android app
2. If not already installed, install `sil_cameroon_qwerty`.
3. Set `sil_cameroon_qwerty` as your active keyboard.
4. Wait a couple of seconds, then force-close the app
5. Relaunch the app

Assuming all goes well (`sil_cameroon_qwerty` is automatically loaded when the app launches), you'll see the error.   It's most notable with the diacritic keys, but also note the differences between the 'a' keys' caps.

**Expected behavior**
The font should load correctly in every case (the second image of each pair).

**Keyman for Android:**
 - Keyman version: 15.0.79
 - Target application: Keyman

**Comment by mcdurdin** [comment]
Does this repro in 14.0?

**Comment by jahorton** [comment]
This does not repro on 15.0.74 (the last release before #5260).  I haven't yet confirmed the first release where it does occur.

**Comment by darcywong00** [comment]
I don't get a repro in 14.0
Wonder if it's due to #5338 where the 🍒 pick in #5407 hasn't landed on stable.14.0 yet.

In stable.14.0 when I halt the debugger in KMManager
```java
 if (oFont.equals("''")) {
      oFont = fontUndefined;
    }
```

oFont has full Font paths as in 
```
{"family":"font_family_AndikaAfr-R",
 "files":  ["
    /data/user/0/com.tavultesoft.kmapro.debug/app_data/packages/sil_cameroon_qwerty/AndikaAfr-R.ttf"
  ]
}
```

I believe in 15.0, the "files" paths just have "AndikaAfr-R.ttf"
