### ISSUE TITLE
bug(model): "see" should be listed as one of the suggestion when the input is "ŝee"

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#5429]
**Describe the bug**

Key in <kbd>ŝ</kbd><kbd>e</kbd><kbd>e</kbd> using EuroLatin (SIL) keyboard with the predictive text on to see three options on the suggestion banner -- "ŝee, seems, seen". One of the suggestions of ŝee should be "see" because it is most likely to be the case that it's expected.

![image](https://user-images.githubusercontent.com/28331388/124572955-4844b600-de73-11eb-984c-6066e44c194a.png)

---

**Keyman for iPhone:**
 - Device: S9+
 - OS: Android 10
 - Keyman version 14.0.277
 - Target application: Keyman

---

**Keyboard**
 - Keyboard name: sil_euro_latin
 - Keyboard version: 1.9.4
 - Language name: English

**Additional context**

cf. https://github.com/keymanapp/keyman/pull/5387

**Comment by jahorton** [comment]
While discovered while debugging #5387, I can confirm that this also occurs on `master`.

<img width="291" alt="image" src="https://user-images.githubusercontent.com/25213402/124575126-53004a80-de75-11eb-831b-901dd0eacd6d.png">

_**And**_ on `stable-14.0`:

![Image from iOS (3)](https://user-images.githubusercontent.com/25213402/124575272-75926380-de75-11eb-9473-58fc1cb5e015.png)

**Comment by jahorton** [comment]
Looks like this does not happen in reverse:

<img width="293" alt="image" src="https://user-images.githubusercontent.com/25213402/124575752-dc178180-de75-11eb-8ff6-bc31ed49055a.png">
