### ISSUE TITLE
[Developer] Feature proposal: enhance visual editor to support more complex keyboards

### ISSUE THREAD

**Issue by auralarch** [keymanapp/keyman#546]
Wonderful, powerful software!

It needs a GUI to handle many of the advanced features (deadkeys, modifier key layers, contextual substitutions, etc.) if it is going to be truly helpful and useful to those who probably need it the most—individuals seeking to bring their own minority languages into the digital age who have limited resources and knowledge aside from that of their own language; the one thing that others don't have!

The Keyman Keyboard Language is quite extensive and robust, allowing for the creation of complex and specialized language/text input schemes; but it can be tedious to use.  Especially for someone who is not already somewhat proficient in some form of coding or scripting; which is very often the case for native speakers of minority languages seeking to create resources for their community.
The documentation for the Keyman Keyboard Language online seems to be complete; but it can be a bit difficult to understand.  Many passages are somewhat ambiguous and vague, and seem to be incomplete to even many savvy, power users because of the style of writing used and because many details are implied or assumed to be known or understood.   Many of the existing examples are very short and not fully explained for the layman, and end up being insufficient or even generating more questions.
However, ultimately what is really needed is some form of graphic interface through which most if not all of the source coding is generated automatically!

A good example of how some of the advanced features could be implemented with a GUI is "Ukelele" for Mac—an excellent piece of SIL software (by the very helpful and knowledgeable: John Brownie).  Ukelele is a fantastic app with a very intuitive interface that is able to facilitate the creation of extensive and complex keyboards quite easily  Ukelele certainly has the most intuitive process for creating deadkeys that I've encountered.  A look at a font designer like HighLogic FontCreator could provide ideas for how to create contextual substitution rules; Microsoft VOLT is another (although less intuitive).   KbdEdit is very powerful & flexible tool for windows with an intuitive interface that takes a slightly different approach.  KbdEdit allows for very extensive and customized control and reprogramming of almost the entire keyboard with seemingly endless options.  ControllerMate for Mac is another exceptionally versatile and expansive package used to "reprogram" nearly any USB input device; although its scope is different it might provide some inspiration or ideas on how an interface might be implemented.

I realize this would be quite an undertaking;  if I had the knowledge and skills I would certainly already be working on this!  But my brain just doesn't seem to be configured to learn to write code...

**Comment by tombogle** [comment]
If we deem this worth pursuing, this could be a good project to farm out to a college for a senior project. I also find the UI in Developer a bit hard to comprehend, but with an existing implementation already available, it's the kind of project a student team could probably take on without a ton of hand holding. We could maybe even consider a browser-based front end to result in a multi-platform tool for creating keyboards.

**Comment by auralarch** [comment]
Thank you for your consideration and response!

I hope that while deciding the fate of this potential upgrade it will be taken into consideration that it would almost certainly bring a significant boost to the number of users working on development!
The Keyman system and suite is a unique product in the sense that (as far as I know) it is the only tool/system available which is capable of producing complex input methods for any unicode supported writing system which are compatible with the major platforms which are also basically the same on all platforms!  That is really huge!   Anyone who is a regular or even occasional user of both Windows and Mac computers is often deeply frustrated by the differences—especially for languages other than English—in the layout and functioning of their keyboards;  I have encountered numerous comments and complaints, and people looking for some solution to help bridge the gap on blogs and forums throughout cyberspace.
I believe that if it were simpler to create keyboards in Keyman with dead keys and some of the other more advanced features, especially using an intuitive GUI, the user base of this product would increase as people learn of it.   The need certainly exists for a tool capable of generating keyboards for multiple platforms from the same source files!  But in its current form Keyman's use is beyond the skills of most of those who would use it.

I feel that it should also be kept in mind that not all minority languages have the benefit of a professional linguist or field worker to assist them in bringing their language into the digital age.  Or it is quite possible their representative may have multiple projects leaving them short on time and resources...  And if the UI of Keyman Developer were more graphically oriented it would facilitate the possibility for more less experienced and casual users of minority languages world-wide to create more than the just the simple 1-1 layouts which can often be required.

The browser-based front end is quite a good and promising  idea, which could quite likely simplify the project, or at least put its development within the scope of more developers.  I do feel that if this route is chosen, it should be implemented with the possibility to be downloaded to the local machine and be able to run and fully function in offline mode, or when there is no network/internet access available.

The idea of such an endeavor being adopted by a student is absolutely fantastic!   Considering what this software has the potential to become, I would imagine that it shouldn't be too hard finding interested candidates...

Also, as I mentioned before, the Ukelele app which is also a SIL product is very similar in its scope to the Keyman suite—although it is exclusively for the Mac platform...  Ukelele is a robust and mature app which I have used fairly extensively for a number of years.  I have always found its developer to be exceptionally helpful  with any questions or issues I have encountered.
While the native Mac keyboard layout protocols do not support all of the features of Keyman keyboards, it does provide  more features than Windows with superior implementation, and it does support a number of Keyman's advanced features such as chained dead keys.  Ukelele has quite a simple and easy to use GUI for creating chained dead keys.  Its techniques and UI could provide inspiration for a good and solid basis and starting point for Keyman Developer—especially since both products are owned by SIL.
I would imagine that Ukelele's developer would be willing to discuss the idea and to provide some helpful thoughts and ideas to anyone working on developing a graphic  interface for Keyman.


Thank you to all who have taken the time to read and consider my thoughts and proposal!   And if by chance you are someone with an interest and the skills needed to tackle something like this,  or if you have any thoughts or ideas which may be helpful or improve/refine these ideas,  I hope you will share and add to this conversation.

**Comment by mcdurdin** [comment]
As we have had no movement on this and no one has had the capacity to start tackling this, I think we're going to close this issue. There will be a lot of functionality in a new LDML Keyboard Editor coming in version 18.0, and that's where we'd like to focus our energy for now. 😄

**Comment by auralarch** [comment]
I'm looking forward to the LDML editor when that is available!
