### ISSUE TITLE
bug(common/core): unicode32 char is cast to 16 bit char losing surrogate info

### ISSUE THREAD

**Issue by rc-swag** [keymanapp/keyman#5465]
**Describe the bug**

KMX_ProcessEvent::PostString  converts(incorrectly) a surrogate pair unicode-16 to a UTF-32. Which then gets cast away again.

**To Reproduce**
kmx_processevent.cpp
`KMX_ProcessEvent::PostString  line  m_actions.QueueAction(QIT_CHAR, Uni_SurrogateToUTF32(*p, *(p+1)));`

kmx_actions.cpp 
`KMX_Actions::QueueAction
case QIT_CHAR:
    m_context->Add((KMX_WORD) dwData);`

**Expected behavior**

I think just consective calls to QueueAction should fix this as long as *(p+1) is not null
`m_actions.QueueAction(QIT_CHAR, *p);`
`m_actions.QueueAction(QIT_CHAR, *(p+1));`

**Comment by mcdurdin** [comment]
Keyman Core treats each character as UTF-32, but the KMX Processor is UTF-16 internally. So we do need `KMX_ProcessEvent::PostString` to continue to push the UTF-32 char, and perhaps `KMX_Actions::QueueAction` can check for a surrogate pair and expand it out for its internal context here.

See also `kmx_processor::process_event` :grin:

**Comment by rc-swag** [comment]
> Keyman Core treats each character as UTF-32, but the KMX Processor is UTF-16 internally. So we do need `KMX_ProcessEvent::PostString` to continue to push the UTF-32 char, and perhaps `KMX_Actions::QueueAction` can check for a surrogate pair and expand it out for its internal context here.
> 
> See also `kmx_processor::process_event` 😁
> 
> Let's start by creating a unit test that demonstrates this bug.

All the other `KMX_ProcessEvent::PostString is pushing UTF-16 for all the other cases just this case it pushes utf-32.  `KMX_Actions::QueueAction`  - does not cast away the info when it adds the action to the queue only when it adds it to the KMX_ processors internal context. As it is the action that is replayed to modify the Core Context this bug has not been exercised. The fact it the KMX_Context is getting corrupted is also not causing a problem as it will be reset with the Core Context the next process event.  
The unit test first is a good idea.

**Comment by mcdurdin** [comment]
A fix is on its way.
