### ISSUE TITLE
bug(core): deleting markers leads to divergence in text store and context

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#5488]
**Describe the bug**

The `KM_KBP_IT_BACK` action currently does not apply to markers (aka deadkeys in .kmn). This means that Engine is unable to know if markers should be deleted or not when updating the text store (markers should be tracked by Engine, which we currently do maintaining a cached copy of the context generated by Core). This can also lead to the text store and the cached context diverging, as the internally maintained cached context correctly tracks markers, while the text store is updated by the actions, and does not track markers. Our current `kmx` unit tests happened not to validate this scenario because they never tested markers in final outputs.

For example, with the following hypothetical keyboard, the processor is unable to determine if `dk(1)` should be deleted or not, when <kbd>a</kbd><kbd>b</kbd> is typed:

```
+ 'a' > 'b' dk(1) dk(2) 'c'
dk(2) 'c' + 'b' > 'xxx'
```

**Expected behavior**

The `dk(1)` value should not be deleted. In that example, the final output should be: `'b' dk(1) 'xxx'`.

I can see two options:

1. We add an action to delete a marker, either by a flag on `KM_KBP_IT_BACK` or a new action type. We could enhance this for unit tests by passing the value we are expecting to delete as a parameter for the action, whether it be a character or a marker.
2. We refactor text output to a single action which includes interleaved markers in the output and number of characters to delete from context, and eliminate multiple `KM_KBP_IT_BACK`, `KM_KBP_IT_CHAR` and `KM_KBP_IT_MARKER` actions.

Option 1 is certainly easier to implement. Option 2 is possibly better architecturally, but I am concerned that it is going to blow out our development time in its impact on Core consumers; it will also break the interactive debugger as we would no longer be able to step through the transform rules. Given this, I am leaning towards Option 1.

In either case, this is a breaking change for Core, and will impact Linux, Windows, and Developer.

Related: https://docs.google.com/document/d/11O7jrPxnf-M_Iyu0ef4TWLmrMu4N-6QC47Z6tHT-89U/edit

---

**Keyman Core:**
 - OS: all
 - Keyman version: 14.0

**Comment by jahorton** [comment]
FWIW, the corresponding behavior for Web:

https://github.com/keymanapp/keyman/blob/f64f34b0ec32fe07c397b3f1dae7c4a9e39e5ee5/common/core/web/keyboard-processor/src/text/kbdInterface.ts#L785-L798

If the rule can be written compactly by a single `KO` (output) statement, only the _matched_ deadkeys will be deleted.  Thus, `dk(1)` will remain, as the 'b' key's rule doesn't attempt to match it.  This was per @mcdurdin's guidance at the time.

A `KDC` ('delete context') keyboard API call can also delete deadkeys, though its mechanisms leave the responsibility in the hands of the Developer compiler in that case.  There, Developer tells KMW how much context to delete in terms of 'units', with a single deadkey and a single Unicode char both counting as a single unit.

**Comment by mcdurdin** [comment]
Yes, that deadkey behaviour in Web seems correct.

**Comment by jahorton** [comment]
In that case, just going to point out that in the description above...

> For example, with the following hypothetical keyboard, the processor is unable to determine if `dk(1)` should be deleted or not, when <kbd>a</kbd><kbd>b</kbd> is typed:
>
> ```
> + 'a' > 'b' dk(1) dk(2) 'c'
> dk(2) 'c' + 'b' > 'xxx'
> ```

it's never made clear what the correct solution actually is - that `dk(1)` should not be deleted.  Just that the desktop-core's `KeyboardProcessor` doesn't know.  Might help the others to know that for the upcoming discussion(s).
