### ISSUE TITLE
bug(ios): Some UI still in English

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#5531]
While testing updated crowding strings for Azerbaijani, @makarasok noted the following UI is still in English
* "Get Started" is still in English. 
   <img width="139" alt="image" src="https://user-images.githubusercontent.com/28331388/127457323-3da4bdae-02ee-4575-9ae6-d4df688448c7.png">
Note, the crowding string exists for "Get Started" as a menu string

* "Spacebar Caption" is shown up as something else.
   <img width="139" alt="image" src="https://user-images.githubusercontent.com/28331388/127458346-c3dfe5e3-c611-4904-8591-36c92b902c00.png">

* Other things under "Spacebar Caption" are also shown up something else.
   <img width="139" alt="image" src="https://user-images.githubusercontent.com/28331388/127458693-50bddf33-682f-487c-b016-7cb72df4e40f.png">

_These are also observed when choosing Khmer as the UI language._

_Originally posted by @MakaraSok in https://github.com/keymanapp/keyman/issues/5486#issuecomment-888952143_

**Comment by darcywong00** [comment]
The "Get Started" string is fixed in #5486

**Comment by darcywong00** [comment]
You can check crowdin to see if they've been translated (these seem to have been)

Khmer for "menu-settings-spacebar"
https://translate.keyman.com/proofread/keyman/414/en-km?filter=basic&value=3#q=menu-settings-spacebar

The strings are proofread and validated.
After that, I run the crowdin-cli to download a language
I'll update the KM ones in a PR

**Comment by darcywong00** [comment]
@MakaraSok can you take another pass through the Khmer strings on crowdin (for macOS) and fill in the missing ones?
https://translate.keyman.com/translate/keyman/575/en-km?filter=basic&value=0

Start with the untranslated or unvalidated strings

**Comment by MakaraSok** [comment]
Everything has been completed on the link above.

**Comment by darcywong00** [comment]
Fixed in #6501 and #6508
