### ISSUE TITLE
bug(android/engine): UX of shortpress on globe key when 1 keyboard installed 

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#5545]
#5437 separated the globe key so:
* short press would switch to next keyboard
* long press would bring up the Keyman keyboard picker menu

This creates some UX weirdness of the short press globe key when only 1 Keyman keyboard is installed
* The OSK "switches" to itself (suggestion banner can toggle off and back on during the transition for sil_euro_latin)
* As a system keyboard, it never switches to the next IME

We should clarify the expected behavior for this

**Comment by darcywong00** [comment]
In standup, @mcdurdin recommends the short press globe key  not doing anything in this scenario.

Will this confuse users who are previously expecting a keyboard picker menu to appear?

**Comment by mcdurdin** [comment]
> Will this confuse users who are previously expecting a keyboard picker menu to appear?

Good question! If there is only one keyboard, short press could bring up the language switch dialog, no harm in that -- why force a longpress. Then if multiple keyboards, short press switches and long press does the dialog. That is a common UI pattern so I think it won't be painful for users to come to grips with.
