### ISSUE TITLE
test(iOS): acceptance test for 14.0.280

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#5547]
# Keyman for iPhone and iPad Acceptance Test Procedures #

| Notes |
| ------- | 
| - _Uncheck boxes are either failed, n/a or need further clarification on what it is and where to look for._ |
| - _Instructed steps taken checklist do not have **PASSED/FAILED** tag result, only verified results do._ |
| - _Instructed steps are checked to indicate that they have indeed be done as instructed._ |

> ## Steps taken in prepping for the test:
> - Test build: [`#14.0.280-test at 2 Aug 01:52`](https://build.palaso.org/buildConfiguration/Keyman_iOS_TestPullRequests/283155?buildTab=overview)
> - From the terminal on `macOS 11.5.1`, navigated to `~/keyman/ios`
> - Successfully built from terminal: 
(1) switched to branch `stable-14.0`, 
(2) ran `git clean -fdx` and then 
(3) `./build.sh -no-codesign`
> - In Xcode, (1) choose iPhone 12 Pro and iPad Pro and (2)Product>Clean Build Folder
> - Began testing...

## Visual Inspection of master branch
- [x] ![Build Status](https://build.palaso.org/app/rest/builds/buildType:(id:Keyman_iOS_Master)/statusIcon) Verify latest CI build of [master](https://build.palaso.org/viewType.html?buildTypeId=Keyman_iOS_Master) is successful
- [ ] Verify `history.md` contains all the current changes
- [ ] Verify that all unit tests for iOS are currently passing.
    - May be integrated with the first step above once our usual CI processes include the iOS unit tests.

## Gather Assets for Testing ##
- [ ] Record device's iOS version 
- [ ] Ensure the device is properly configured for testing and is registered with TestFlight.

At this time, Keyman for iOS does not support external keyboard input.

## Setup Steps ##
- [x] Uninstall previous version of Keyman on the device
> No uninstallation needed, but the `Build Folder` has indeed been cleaned for good measure.
- [x] Install test build IPA
> Build from within Xcode using iPhone 12 Pro
- [x] On device, disable internet connectivity
> Internet connection from the host machine was disable to comply with this
- [x] Start Keyman and select **Add a keyboard for your language**
- [x] **FAILED** Verify error message "Could not reach Keyman server!" is displayed
> The message instead says "The Internet connection appears to be offline."
<img width="70" alt="image" src="https://user-images.githubusercontent.com/28331388/128117803-662a30e0-5da4-45d2-b0c8-0a5a085df6f8.png">

- [x] Click OK to dismiss.  Close Keyman app
- [x] On device, enable internet connectivity
- [x] Start Keyman
- [x] On initial **Get Started** menu, select "Enable Keyman as system-wide keyboard" and do any necessary system steps to enable Keyman
> The message actually says "Set up Keyman as system-wide keyboard"
<img width="70" alt="image" src="https://user-images.githubusercontent.com/28331388/128118648-fe1afb1f-72e7-4763-81ab-5df54102f51b.png">

### Get Started ###
- [x] **PASSED** Verify touching **Add a keyboard for your language** pulls up the **keyboard search**
    - [x] **PASSED** This should also be accessible as **Settings** > **Installed Languages** > **`+`**.
- [x] **PASSED** Verify touching **Enable Keyman as system-wide keyboard** pulls up Keyman's menu within iOS settings.  (11.0+ devices)
    - [ ] If older versions of iOS are supported, ensure that the help page for doing it manually is properly linked.
- [x] **PASSED** Verify touching **More info** brings up an accurate version and the main table-of-contents help page.
    - [x] This should also be accessible as **Info** from the main menu dropdown (on phones) or as the circled-i button (on tablets).
    <img width="70" alt="image" src="https://user-images.githubusercontent.com/28331388/128119144-4d6d232d-aca0-4b9f-94b4-1cacdd36b9ff.png">

- [x] **PASSED** Set **Don't show again** to checked, close and re-open Keyman, and verify **Get Started** menu does not appear

### Add New Keyboard ###
This menu is accessed via **Get Started** menu or **Settings** menu
- [x] On the device, enable internet connectivity
- [x] **PASSED** Verify a new keyboard can be downloaded and selected
- [x] **PASSED** Return to the text input screen and confirm that it operates correctly.
- [x] **PASSED** Without changing selected language, confirm that it can be cleanly deleted via the Settings menu.
- [x] **PASSED** Confirm that another keyboard is correctly selected afterward.
> The default keyboard (i.e. EuroLatin (SIL)) was selected after removing the aforementioned keyboard.

### Share ###
- [x] **PASSED** Type and verify text can be copied and shared to external app

### Keyman Browser ###
- [x] On default page, click on text field and set system keyboard to Keyman
- [x] **PASSED** Verify can type with Keyman as system keyboard
- [x] **PASSED** Verify that predictive suggestions are properly applied when selected (using `sil_euro_latin` + English)
- [x] Close and reopen Keyman app

### Text Size ###
- [x] **PASSED** Verify text can be rescaled from Text Size 9 to 72

### Clear Text ###
- [x] **PASSED** Verify text can be cleared

### Info ###
- [x] **PASSED** Verify that the Keyman iOS version is displayed; record the version
- [x] **PASSED** Verify that the Info menu options matches that of the **More Info...** option from the **Get Started** menu option.
> If this means the pages loaded when triggered from these two processes are identical, then this is PASSED, otherwise FAILED.
- [x] **PASSED** Verify that the Keyman iOS version matches the version string seen at (Home Screen) > [iOS] Settings > Keyman.

### Settings ###
- [x] Installed Languages ... Add Language
- [x] Select an installed language ... Add (another) Keyboard
    - [x] Should automatically perform a filtered search based upon that language's BCP-47 code
    > _Please clarify what this means_
- [x] Select an installed language ... Dictionary
- [x] **FIXED at https://github.com/keymanapp/keyman/pull/5548** Turn on/off 'Enable Predictions' and validate each
> The toggle button doesn't respond to the touch. It flashes a bit and then didn't turn off as intended.
- [x] **FIXED at https://github.com/keymanapp/keyman/pull/5548** Turn on/off 'Enable Corrections' and validate each
> The toggle button doesn't respond to the touch. It flashes a bit and then didn't turn off as intended.
- [x] **FIXED at https://github.com/keymanapp/keyman/pull/5548** Validate that when both predictions and corrections are off, banner is not visible
- [ ] **FAILED** Add/Remove dictionaries - validate
> Tapping on the dictionary name or the arrow to the right of the dictionary would take one to the text input; unless tap right on the info icon (i.e. the i with a blue circle) that one is taken to where the dictionary can be uninstalled. It is a pain to be that precise for one with a fat finger. :) This is marked as failed for now so that we can get a discussion going.
<img width="70" alt="image" src="https://user-images.githubusercontent.com/28331388/128122263-b770222c-5bde-4959-8d2b-3301e361ddcf.png">

- [ ] **PASSED/FAILED** If multiple dictionaries are available, test swapping between them

---

<details>

<summary><b>The remaining...</b></summary>

## Keyboard Tests

- [x] Confirm all keyboard tests below have been performed in both **portrait** mode.
> Unless indicated otherwise in the inline instructions.

### **English (Eurolatin2)** in-app
> Eurolatin2 keyboard could not be found in the keyboard library to test; EuroLatin (SIL) was used instead.

- [x] **PASSED** In portrait orientation, verify that the OSK appears and fills the width the bottom of the screen
- [x] **PASSED** Verify long-press `q` key works
- [x] **PASSED** Verify long-press `k` key works
    - [x] **PASSED** Verify that any predictive suggestions generated feel 'reasonable' (based upon 'k', the selected subkey, or one of its neighbors)
    > The prediction is randomized and depends on the location of the the longpress key, i.e. when press <kbd>ǩ</kbd> the suggestions are "you, know, your" (see the screenshot below);
   <img width="70" alt="image" src="https://user-images.githubusercontent.com/28331388/128134552-8c505386-979a-4608-b043-aa15ef32cfcb.png">

    > when press <kbd>ķ</kbd>, the suggestions are "of, on, know" (see the screenshot below).
    <img width="70" alt="image" src="https://user-images.githubusercontent.com/28331388/128134854-85993fba-6b1e-4915-a6a0-68222d5074bf.png">

    > It looks like the location of where the long press is released determines the suggestions. The result is PASSED as this behavior is not detrimental.

- [x] **PASSED** Verify uppercase layer can be selected via `SHIFT`
- [x] **PASSED** Verify number layer can be selected via `123`
- [x] **PASSED** Verify long-press `1` key works
- [x] **PASSED** Verify long-press `0` key works
- [x] **PASSED** Verify backspace, space, and enter keys work

Note that the shown EuroLatin2 is a highly customized keyboard explicitly designed for mobile.

### English: **US Basic** in-app
- [x] **PASSED** Verify that the **US Basic** keyboard can be downloaded through Settings > Installed Languages > English > `+`
  - [x] This should automatically bring up search results for **English** keyboards.
  - [x] When the package-installer launches, English should be the one pre-selected language.
- [x] Install the package for both English and Tagalog.
- [x] Set **English: US Basic** as the active in-app keyboard.
- [x] **PASSED** Verify that predictive text suggestions appear.
- [x] Set **Tagalog: US Basic** as the active in-app keyboard.
- [x] **PASSED** Verify that predictive text suggestions do _not_ appear.
- [x] **PASSED** Verify that long-press `123` key works, presenting options for a currency layer and a symbol layer.
- [x] Select the currency layer, then press the `£` key.
- [ ] **FAILED** Verify that the keyboard outputs correctly and returns to the default layer.
> It actually switches to the numeric layer (see the screenshot below).
<img width="70" alt="image" src="https://user-images.githubusercontent.com/28331388/128138496-9fdb13d9-5181-4e32-8f38-4f7b3fce9812.png">

- [x] Go to the symbol layer and press the `©` key.
- [x] **PASSED** Verify that the keyboard outputs correctly and remains on the symbol layer.
- [x] Revert to the default layer and ensure basic key inputs work.
- [x] Long-press `e` on the default layer and select a subkey.
- [x] **PASSED** Verify that the selected key produces the correct output.
- [x] From the `Settings > *Installed* Languages > English > US Basic` menu, follow the "Help link" and ensure it displays appropriate help.
  - (Should work both online and offline)
- [x] **PASSED** From the `Settings > Languages > English > US Basic` menu, scan the QR code with a phone and test that it links to the current version of that keyboard's public download page on keyman.com.
- [x] Returning to the app, delete the **US Basic** keyboard via Settings for Tagalog.
- [x] Set **English: US Basic** as the active in-app keyboard.
- [x] **PASSED** Verify that the keyboard appears correctly and ensure basic key inputs work.
  - This is to ensure that uninstalling for one language doesn't adversely affect installations of the same resource for another language.
- [x] Delete the **US Basic** keyboard via Settings for English.

---

- [ ] Confirm all keyboard tests below have been performed in **landscape** mode.
> Unless indicated otherwise in the inline instructions.

### **English (Eurolatin2)** in-app
> Eurolatin2 keyboard could not be found in the keyboard library to test; EuroLatin (SIL) was used instead.

- [x] **PASSED** ~~In portrait orientation~~, verify that the OSK appears and fills the width the bottom of the screen
- [x] **PASSED** Verify long-press `q` key works
- [x] **PASSED** Verify long-press `k` key works
    - [x] Verify that any predictive suggestions generated feel 'reasonable' (based upon 'k', the selected subkey, or one of its neighbors)
- [x] **PASSED** Verify uppercase layer can be selected via `SHIFT`
- [x] **PASSED** Verify number layer can be selected via `123`
- [x] **PASSED** Verify long-press `1` key works
- [x] **PASSED** Verify long-press `0` key works
- [x] **PASSED** Verify backspace, space, and enter keys work

Note that the shown EuroLatin2 is a highly customized keyboard explicitly designed for mobile.

### English: **US Basic** in-app
- [x] **PASSED** Verify that the **US Basic** keyboard can be downloaded through Settings > Installed Languages > English > `+`
  - [x] This should automatically bring up search results for **English** keyboards.
  - [x] When the package-installer launches, English should be the one pre-selected language.
- [x] Install the package for both English and Tagalog.
- [x] Set **English: US Basic** as the active in-app keyboard.
- [x] **PASSED** Verify that predictive text suggestions appear.
- [x] Set **Tagalog: US Basic** as the active in-app keyboard.
- [x] **PASSED** Verify that predictive text suggestions do _not_ appear.
- [x] **PASSED** Verify that long-press `123` key works, presenting options for a currency layer and a symbol layer.
- [x] Select the currency layer, then press the `£` key.
- [x] **FAILED** Verify that the keyboard outputs correctly and returns to the default layer.
> Unlike in portrait mode, the keyboard does switch to default layer after the pound sign is pressed in the first attempt. Repeat the steps to output the pound sign again to see that it switches to the numeric layer.
<img width="139" alt="image" src="https://user-images.githubusercontent.com/28331388/128141543-e24d0ebc-b966-4c7a-aa35-b6fbd7e24994.png">

- [x] Go to the symbol layer and press the `©` key.
- [x] **PASSED** Verify that the keyboard outputs correctly and remains on the symbol layer.
- [x] **PASSED** Revert to the default layer and ensure basic key inputs work.
- [x] Long-press `e` on the default layer and select a subkey.
- [x] **PASSED** Verify that the selected key produces the correct output.
- [x] From the `Settings > Languages > English > US Basic` menu, follow the "Help link" and ensure it displays appropriate help.
  - (Should work both online and offline)
- [x] From the `Settings > Languages > English > US Basic` menu, scan the QR code with a phone and test that it links to the current version of that keyboard's public download page on keyman.com.
- [x] Returning to the app, delete the **US Basic** keyboard via Settings for Tagalog.
- [x] Set **English: US Basic** as the active in-app keyboard.
- [x] **PASSED** Verify that the keyboard appears correctly and ensure basic key inputs work.
  - This is to ensure that uninstalling for one language doesn't adversely affect installations of the same resource for another language.
- [x] Delete the **US Basic** keyboard via Settings for English.

### Predictive Text
- [ ] **TODO**

## What's New Tests
- [ ] Refer to the new changes in `history.md` and verify functionality

</details>

**Comment by jahorton** [comment]
Right, the menu toggles.  I was wondering if that was some oddity local to my machine or not.

I thought it was be a Simulator bug when using one of the latest available iOS simulator runtimes, as when I first started noticing it, I could just hop back one iOS version and it'd work fine... but now that I check it on an actual device, my personal iPhone on 14.6 also can't use the toggles.  So... now to figure out what Apple did to break things _this_ time.  

Without changing a single line of code, only the device running the Keyman app:
- When simulating 13.5, the toggles work.
- When simulating 14.4, they don't.
- On an actual 14.6 device, they don't.  But, at some previous point in time on the same device (older iOS version), they did.

Either way, that toggling issue already exists, thus is not caused by the 🍒-pick changes.  That said... this is very much worth making its own issue.

------

> Add / Remove dictionaries

You should also be able to press and slide the dictionary toward the left as a touch-gesture in order to delete keyboards and models.

**Comment by jahorton** [comment]
Huh.  Fortunately, that does look simple to resolve.

https://developer.apple.com/forums/thread/660915

Just tried it out, and that seems to do the trick.  Now just to apply it where needed.

**Comment by MakaraSok** [comment]
Please click on the collapsible "The remaining..." in the comment above to see the rest of the test results. :)

**Comment by jahorton** [comment]
Ah, so in regard to the next layer tests:  seems like it _should_ be swapping to "numeric" - the original spec is wrong.

```
                    }, {
                        "nextlayer": "numeric",
                        "id": "U_20A4",
                        "text": "\u20A4"
                    }, {
```

https://www.fileformat.info/info/unicode/char/20a4/index.htm

While attempting to repro your report, I noticed that the layer seems to auto-reset if the OSK is in a non-default layer when it is rotated, but without _internally_ resetting, which can present an issue.  (I was unable to enter the numeric layer directly... because KMW thought it already was in it, despite _showing_ the default.  The 'reset' was only partial.)

I couldn't repro the exact scenario where pressing that specific key actually returned to the default layer, though.
