### ISSUE TITLE
bug(mac): Unable to Install - M1/macOS 12 beta

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#5573]
**Describe the bug**
Keyman is not fails to install in macOS 12 with m1 cpu

**To Reproduce**
Install Keyman in macOS12 with m1 cpu

**Screenshots**
<img width="702" alt="image" src="https://user-images.githubusercontent.com/14062593/128771760-be0ff7c5-489e-433b-b8db-6d0b94d738ad.png">

**Keyman for Windows/macOS/Linux:**
 - OS: 12.0 Beta (21A5294g)
 - Keyman version: keyman-15.0.95.dmg alpha (released 2021-08-07, 4.65 MB)
 -  Keyman version: keyman-14.0.280.dmg

**Comment by mcdurdin** [comment]
Is this a macOS 12 issue or M1 issue?

**Comment by MayuraVerma** [comment]
I am not sure. I have tested on macOS 12 and m1 cpu.

I have an old Intel mac with Catalina (mac OS 10), I can't upgrade to macOS 12, it's not eligible!

I suspect it's with mac OS 12 should be independent of cpu architecture for simple apps. It is complaining about app signing.

**Comment by MayuraVerma** [comment]
`xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/_CodeSignature'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/MacOS'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Resources/en.lproj'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Resources/Help/basic/config'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Resources/Help/basic'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Resources/Help/start'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Resources/Help/mac_images'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Resources/Help/about'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Resources/Help/troubleshooting'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Resources/Help/common'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Resources/Help'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Resources'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Frameworks/Sentry.framework/Resources'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Frameworks/Sentry.framework/Versions/A/_CodeSignature'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Frameworks/Sentry.framework/Versions/A/Resources'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Frameworks/Sentry.framework/Versions/A'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Frameworks/Sentry.framework/Versions/Current/_CodeSignature'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Frameworks/Sentry.framework/Versions/Current/Resources'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Frameworks/Sentry.framework/Versions/Current'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Frameworks/Sentry.framework/Versions'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Frameworks/Sentry.framework'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Frameworks/KeymanEngine4Mac.framework/Resources'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Frameworks/KeymanEngine4Mac.framework/Versions/A/_CodeSignature'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Frameworks/KeymanEngine4Mac.framework/Versions/A/Resources'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Frameworks/KeymanEngine4Mac.framework/Versions/A'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Frameworks/KeymanEngine4Mac.framework/Versions/Current/_CodeSignature'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Frameworks/KeymanEngine4Mac.framework/Versions/Current/Resources'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Frameworks/KeymanEngine4Mac.framework/Versions/Current'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Frameworks/KeymanEngine4Mac.framework/Versions'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Frameworks/KeymanEngine4Mac.framework'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Frameworks'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app'`
`xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/_CodeSignature'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/MacOS'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Resources/en.lproj'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Resources/Help/basic/config'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Resources/Help/basic'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Resources/Help/start'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Resources/Help/mac_images'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Resources/Help/about'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Resources/Help/troubleshooting'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Resources/Help/common'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Resources/Help'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Resources'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Frameworks/Sentry.framework/Resources'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Frameworks/Sentry.framework/Versions/A/_CodeSignature'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Frameworks/Sentry.framework/Versions/A/Resources'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Frameworks/Sentry.framework/Versions/A'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Frameworks/Sentry.framework/Versions/Current/_CodeSignature'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Frameworks/Sentry.framework/Versions/Current/Resources'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Frameworks/Sentry.framework/Versions/Current'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Frameworks/Sentry.framework/Versions'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Frameworks/Sentry.framework'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Frameworks/KeymanEngine4Mac.framework/Resources'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Frameworks/KeymanEngine4Mac.framework/Versions/A/_CodeSignature'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Frameworks/KeymanEngine4Mac.framework/Versions/A/Resources'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Frameworks/KeymanEngine4Mac.framework/Versions/A'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Frameworks/KeymanEngine4Mac.framework/Versions/Current/_CodeSignature'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Frameworks/KeymanEngine4Mac.framework/Versions/Current/Resources'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Frameworks/KeymanEngine4Mac.framework/Versions/Current'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Frameworks/KeymanEngine4Mac.framework/Versions'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Frameworks/KeymanEngine4Mac.framework'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents/Frameworks'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app/Contents'
xattr: [Errno 9] Bad file descriptor: '/Users/test/Library/Input Methods/Keyman.app' (1)`

**Comment by MayuraVerma** [comment]
Above error is with keyman-14.0.280.dmg

**Comment by mcdurdin** [comment]
OK. I will try to investigate this in a few weeks; it really takes a full day to go and install the macOS beta so I'm am not excited about that!

**Comment by mcdurdin** [comment]
I note that `textinputsource` is intel-only. See https://community.software.sil.org/t/does-keyman-support-m1-mac/5213/8

**Comment by mcdurdin** [comment]
@MayuraVerma can you test now with 14.0.282? I believe it should install on M1 and macOS beta 12.

**Comment by MayuraVerma** [comment]
I am able to install in Mac OS 11.6 (20G165) with M1 silicon.

I think It will work on mac os monterey.
