### ISSUE TITLE
bug(android): the backspace button is not responsive on Android 5.0

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#5576]
**Describe the bug**

The backspace button is not responsive on Keyman 14.0.280 in Android 5.0 emulator. This doesn't work on any installed keyboard, not anyone in particular.

**Expected behavior**

The backspace button should delete the character to the left of the caret.

**Screenshots**

https://youtu.be/hgT6GY9GRYU

---

**Keyman for Android:**
 - Device: Pixel API 21
 - OS: Android 5.0
 - Keyman version: 14.0.280 stable
 - Target application: Keyman

**Comment by darcywong00** [comment]
I wonder if KeymanWeb is not registering the backspace key.
On Android 5.0 emulator, the backspace key is generating
```
insertText(0, , 0); 
```

I would have expected `insertText(1, , 0);` to delete a character

**Comment by darcywong00** [comment]
notes on debugging outputTarget.ts in `deleteCharsBeforeCaret()`

In the Keyman Android text area, I have context `po` and hit backspace.
At the breakpoint, KMW has `this.text` is `op`

**Comment by jahorton** [comment]
In separate channels, @darcywong00 has mentioned that this seems to have occurred in 14.0.277; it was fine in 14.0.276.

So, it's likely due to a change in one of the PRs listed under https://github.com/keymanapp/keyman/blob/stable-14.0/HISTORY.md#140277-stable-2021-06-29.

**Comment by jahorton** [comment]
If I had to guess, it's probably something in https://github.com/keymanapp/keyman/pull/5352 - I remember there being some iteration on certain lines due to Web feature support.  We may have missed something that an older WebView is being affected by.

**Comment by jahorton** [comment]
> notes on debugging outputTarget.ts in `deleteCharsBeforeCaret()`
> 
> In the Keyman Android text area, I have context `po` and hit backspace.
> At the breakpoint, KMW has `this.text` is `op`

Though... this part is indicative of a context desync, which is more likely due to something in Android changes rather than #5352.

**Comment by darcywong00** [comment]
I wonder if this comes out of #5376 where the backing TextArea is set to `display: none`

In an Android 5 emulator, when I debug in KeymanWeb textarea, `this.root.selectionStart` and `this.root.selectionEnd` are always 0 and never update, even after inserting text.

Also in the same Android 5 emulator, I installed
14.0.276 stable -  backspace works
14.0.277 stable -  backspace stops working (which includes the 🍒 pick #5377)

**Comment by darcywong00** [comment]
Android 5.1 (SDK 22) works with existing `display: none`.
