### ISSUE TITLE
bug(android): the keyboard search is blank in Android 5.0.2 

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#5598]
**Describe the bug**

While testing this PR (https://github.com/keymanapp/keyman/pull/5570), a weird issue arises where the keyboard search page doesn't seem to load at all. A blank page is shown as opposed to its normal behavior when accessing from within Windows/macOS/keyman.com.

<img width="70" alt="image" src="https://user-images.githubusercontent.com/28331388/129881912-afe8716d-1220-4ff1-beb3-3c664b8c04f1.png">

**Expected behavior**

The page should be shown like that of the what is on Keyman.com keyboard search page.

---

**Keyman for Android:**
 - Device: Pixel
 - OS: 5.0.2
 - Keyman version: 15.0.96-alpha-test-5570
 - Target application: Keyman
 - Android System Webview version: 37

**Comment by darcywong00** [comment]
Cannot repro.  But likely duplicate to #5599
