### ISSUE TITLE
feat(mac): Make Hebrew Consonants and Vowels Show Bigger in On-Screen Keyboard

### ISSUE THREAD

**Issue by martinmts** [keymanapp/keyman#5600]
**Is your feature request related to a problem? Please describe.**

The Hebrew consonants and the vowels in the On-Screen keyboard are too small, the vowels especially. Screenshot:
![image](https://user-images.githubusercontent.com/32575091/129925923-131b4497-222c-4ebe-9172-bf11d4473376.png)

**Describe the solution you'd like**

Please make them bigger if possible.

**Describe alternatives you've considered**

Well, because it is almost unusable, I had to ask the students to print the mapping out.

---

**Keyman for macOS:**
 - OS:  macOS Big Sur
 - Keyman version:  13.0.101
 - Target Application:  Keyman OSK

---

**Keyboard**
 - Keyboard name:  sil_hebrew
 - Keyboard version:  1.8.1
 - Language name: Hebrew (SIL)

**Comment by mcdurdin** [comment]
Thank you for creating this issue. I certainly agree -- the macOS version of Keyman has a more constrained on screen keyboard experience than Windows (where you can resize the keyboard), and the font scale is not great -- we could generally make the letters much larger.

Original ref: https://community.software.sil.org/t/on-screen-keyboard-too-small-for-hebrew-vowels/5209
