### ISSUE TITLE
bug(android): longpress keys on shift layer aren't applying specified layer

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#5610]
**Describe the bug**

All long press keys on the Shift layer of [sil_madi](https://keyman.com/keyboards/sil_madi?bcp47=mhi) keyboard do not work as expected. They do not output the character shown on the keycap on Android physical device.

**Screenshots**

Chrome emulator using the build off of my computer: 
<img width="139" src="https://user-images.githubusercontent.com/28331388/130169557-8ea7f9ee-fc8b-4b82-a780-d64ef36cc601.png">

Chrome emulator using the keymanweb version:
<img width="139" src="https://user-images.githubusercontent.com/28331388/130169578-e5d9ea72-7bc6-4008-9081-0ce2f4709329.png">

---

**Keyman for Android:**
 - Device: Samsung Galaxy S9+
 - OS: Android 10
 - Keyman version: 14.0.280
 - Target application: Keyman app

**KeymanWeb:**
 - OS: Windows 10 Pro
 - Browser: Chrome
 - KeymanWeb Version: ?
 - URL: https://keymanweb.com/?_ga=2.74887638.575662518.1629422514-576725948.1623116260#mhi,Keyboard_sil_madi

---

**Keyboard**
 - Keyboard name: sil_madi
 - Keyboard version: 1.0
 - Language name: Madi

**Comment by MakaraSok** [comment]
When will this fix go live? @darcywong00 @mcdurdin

**Comment by darcywong00** [comment]
This will appear in the next stable-14.0 release (eta middle of Sept)
