### ISSUE TITLE
bug(linux): Investigate use of surrogate pairs in ibus-keyman 

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/keyman#5615]
From [Slack](https://keymanapp.slack.com/archives/C6Q9WS09G/p1629406787122100?thread_ts=1629390731.121900&cid=C6Q9WS09G):

Weird that we are considering surrogate pairs in `KM_KBP_IT_CHAR` given it should be providing UTF-32 Unicode scalar value?!? -- something else to investigate.

**Comment by darcywong00** [comment]
Will try to investigate during 15.0 beta. Then we can determine the scope for a future milestone

**Comment by ermshiperete** [comment]
[`engine.c`](https://github.com/keymanapp/keyman/blob/93af2a3d84489e15f514c553546805c2fe90fd5e/linux/ibus-keyman/src/engine.c#L524) checks for `action_item->character` being a surrogate. This should never happen because `action_item->character` is a 32-bit character. We should verify that we don't hit this block in any test, and then remove this code block and remove the `keyman->firstsurrogate` field.
I suggest doing that in Keyman 16.
