### ISSUE TITLE
bug(windows): keyboard switcher missing on second (non-admin) user account after single Keyman install on admin user account

### ISSUE THREAD

**Issue by megahirt** [keymanapp/keyman#5634]
**Describe the bug**
Lahu keyboard (the only installed Keyman keyboard) is missing from Windows keyboard switcher.  In fact, the keyboard switcher is not present on the Windows toolbar even though Keyman is loaded with the one keyboard.  Adding a second Keyman keyboard causes the Windows Keyboard Switcher to appear, but the original Lahu keyboard is not present in the switcher.

**To Reproduce**
1. Install Keyman under first user account (with admin privileges).  Installed with single language keyboard Lahu initially.  All is well.
2. Create second windows user account (standard user)
3. Change to second user.  Keyman is not running, however there is a desktop icon for Keyman.  Click on the Keyman desktop.  Keyman runs up with a brief "install" dialog.
4. Keyman is running however, the windows 10 keyboard switcher is missing and seems unaware of the existence of the Lahu keyboard installed initially
5. As an additional debug step, I thought I would install a second Keyman keyboard to see if I could "kick" Keyman into adding the original Lahu keyboard to the windows keyboard switcher, however it did not work as I had hoped.  After installing the second keyboard "EuroLatin (SIL)", Keyman was in a state where Lahu was installed but not able to switch to in the windows switcher or the Keyman keyboard switcher (Keyman icon).

**Expected behavior**
Installed Keyman keyboards should be represented in the Windows keyboard switcher, even if they were installed by another user on the system.  The assumption is that Keyman keyboards are installed system-wide for all users.

**User workaround**
I was able to work around the issue by uninstalling the Lahu Keyboard (requires admin permission) and then download/reinstall the Lahu Keyboard from within Keyman (also requires admin permission).  After this, the Lahu keyboard was present in the Windows keyboard switcher.

**Screenshots**
![image (1)](https://user-images.githubusercontent.com/3444521/130754570-88ebe161-ed79-42e6-b1bf-9c3f4b1b5599.png)

![image](https://user-images.githubusercontent.com/3444521/130752001-0a72c7c6-0273-484a-9ebe-e64a3250c307.png)

---

 - Windows 10 Home 32-bit 21H1 19043.1165
 - Keyman version: 14.0.280

**Keyboard**
 - Keyboard name: Lahu (ID = lahu) 
 - Keyboard version: 1.1.1
 - Language name: 

**Additional context**
Possible duplicate of #760

**Comment by mcdurdin** [comment]
Here is the best workaround:

1. In the standard user account, open Keyman Configuration.
2. Select the keyboard, expand the details.
3. Click Add Language, add the language association, click OK.
4. At this point, the language and keyboard should appear in the Windows language list.

Closing with this workaround.
