### ISSUE TITLE
feat(mac): Would you mind if I submit this app to Homebrew Casks

### ISSUE THREAD

**Issue by myzhang1029** [keymanapp/keyman#5663]
**Is your feature request related to a problem? Please describe.**

A lot of macOS users use Hoembrew to manage their packages, but Keyman as a great package is not in the registry itself.

**Describe the solution you'd like**

Add this awesome app to Homebrew for easier installation!

**Describe alternatives you've considered**

It is true that people can still install Keyman without submitting it, but it will make it easier to discover and install.

**Additional context**

The new formula file is in this repo and waiting to be reviewed: [myzhang1029/homebrew-cask](https://github.com/myzhang1029/homebrew-cask/tree/add-keyman) and Homebrew/homebrew-cask#110863

**Comment by darcywong00** [comment]
Thanks for the suggestion. That does sound useful for easier installation.

We currently don't have a developer available that can review your PR. Our small development team will be shuffling responsibilities in a few weeks though. I'll keep you posted next week.

**Comment by darcywong00** [comment]
Looks like this is taken care of now that your Homebrew PR got merged.

Thanks for doing this!
