### ISSUE TITLE
bug(mac): OSKs of Alt and Alt+Shift on macOS are not consistent with those on Windows

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#5721]
**Describe the bug**

On behalf of user:

> I built a simple keyboard using Keyman Developer on Windows 10. I installed the keyboard on a MacOS system.
> 
> The OSK on Windows displays all the layers correctly.
> 
> On MacOS, the main layer and Shift layer display correctly, but the Alt and Alt+Shift layers are blank. No characters are displayed in these layers.
> 
> But, I am able to type the characters correctly! I just can’t see them on the OSK.
> 
> I also installed one of the keyboards from the Keyman website and that keyboard has all the layers displayed correctly (including Alt and Alt+Shift) on MacOS, so I don’t think it’s a settings issue.
> 
> Has anyone seen this problem before?

**To Reproduce**

1. Install [this keyboard](https://drive.google.com/file/d/1hkVbdbBMOSBGuYSJYdxuW1ELOBCQ6uWh/view?usp=sharing) on Keyman for macOS and Keyman for Windows
2. Open the OSK of each
3. Compare the OSK of Alt and AltShift layers
4. See error: OSKs on macOS are empty unlike those of Windows.

**Expected behavior**

OSK of Alt layer on Windows:
<img width="139" src="https://user-images.githubusercontent.com/28331388/133948443-a00d1165-2581-433a-99ad-c8d6367ed699.png">

OSK of Alt on Mac:
<img width="139" src="https://user-images.githubusercontent.com/28331388/133948478-543e0334-209f-4796-909f-ead828c8502e.png">

---

**Keyman for Windows/macOS:**
 - OS: Windows 10 Pro 21H1 x64 / macOS Big Sur
 - Keyman version: 14.0.281
 - Target Application: Keyman OSK

---

**Additional context**

https://community.software.sil.org/t/osk-not-displaying-characters-on-macos/5349

**Comment by shrutirij** [comment]
Hi! 

I'm the user that originally posted on the help forum. I did some more debugging and it seems like the Mac OSK only displays the RightAlt layer. 

If the keyboard does not distinguish left and right Alt, then the OSK does not display the Alt layer as explained in the previous post.

**Comment by MakaraSok** [comment]
Have you tried and enabled this option `Distinguish between left and right Ctrl/Alt` on the On-Screen tap in Keyman Developer?
![image](https://user-images.githubusercontent.com/28331388/134101915-9f8af94a-ed3d-4ff6-80fa-22c0a699a36d.png)

**Comment by MakaraSok** [comment]
related: https://github.com/keymanapp/keyman/issues/734.

**Comment by shrutirij** [comment]
Thanks! I'll try that.

**Comment by mcdurdin** [comment]
Yes, this is something we are investigating further for cross-platform compatibility. On macOS, the left and right Option (Alt) keys are not normally treated independently, unlike Windows. By default, we map RAlt to either Option key; if a keyboard does not include RAlt but rather includes Alt, we should probably display that accordingly.

FWIW, RAlt is recommended over Alt, because Alt conflicts with keyboard shortcuts such as Alt+F to open the File menu.
