### ISSUE TITLE
bug(mac): after installing a keyboard from file by double clicking on .kmp, the Configuration shown is blank 

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#5733]
**Describe the bug**

Installing any keyboard using a downloaded .kmp file by double clicking on it would result in a blank window of Keyman Configuration. Welcome page doesn't show up either after the installation was completed.

<img width="846" alt="image" src="https://user-images.githubusercontent.com/28331388/134103398-aab912aa-db69-443e-886e-09888a9ccbac.png">

However, the keyboard got installed and shown `untick` in the Configuration.

<img width="846" alt="image" src="https://user-images.githubusercontent.com/28331388/134104895-70f0683e-1cbd-4aba-9525-bebd41501d78.png">

**Expected behavior**

A list of installed keyboard should be shown.

---

**Keyman formacOS:**
 - OS: macOS Big Sur 11.6
 - Keyman version: 14.0.281
 - Target Application: Keyman Configuration

Keyboard for testing: 
[xyz.kmp.zip](https://github.com/keymanapp/keyman/files/7199920/xyz.kmp.zip)

**Comment by sgschantz** [comment]
I can't reproduce this. Are there any other necessary steps or conditions? I always see the fully populated Configuration window. It appears in the background immediately behind the alert confirming that I want to install xyz.kmp.

After installation, I see only the Configuration window with the new keyboard included in the list and checked. There is no welcome page -- by 'welcome page', do you mean the Keyboard Information window? I do see that when I install a keyboard from within the app.

**Comment by MakaraSok** [comment]
It looks like this issue has somehow be fixed. You are right that the keyboard installed is populated right after the installation complete.
