### ISSUE TITLE
Keyman for Android should increase network timeout from 10sec for slow networks

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#575]
Currently the load of keyboard data from api times out after 10sec. On slow networks this may not be enough time. Consider extending to 20 sec (or some other timeframe, any best practices?) See #569

**Comment by darcywong00** [comment]
Per the [Nielson Norman Group](https://www.nngroup.com/articles/website-response-times/), 10 seconds is the limit before users will bail on a website.

Maybe after 10 seconds, we present a Dialog that conveys "Network connection seems to be slow. Want to keep waiting?" and give them the option to continue or cancel.

**Comment by mcdurdin** [comment]
Fair enough, but in my experience, users in remote communities that live with poor quality network connections tend to be far more patient. These are the users we don't want to cut off with a hard fail on downloading keyboards :)  I don't know how much extra engineering is required to add the dialog, and if it is worth the effort. Can you estimate?

**Comment by darcywong00** [comment]
Since 10 sec may not be enough, then let's go ahead and change it to 20 with a simple "Cancel" button.

It'll prob take me a day or two to make sure the app gracefully handles the "Cancel".

**Comment by darcywong00** [comment]
"Cancel" button cherry-picked to 12.0 master in #1513
