### ISSUE TITLE
bug(web): some keys are not fully visible when testing OSK in Chrome emulator

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#5779]
**Describe the bug**

When tested `khmer_angkor` keyboard on Chrome emulator, some keys on the Shift layer are cropped off.

Windows/macOS/Linux desktop
<img width="139" src="https://user-images.githubusercontent.com/28331388/135403152-3530084d-1e1f-479d-92fe-a8916b02af75.png">

No touch device has this issue.

**Expected behavior**

The character on each cap should be readability, nothing is cropped off.

---

**Keyman Developer:**
 - OS: Windows 10 Pro 21H1 x64
 - Keyman Developer version: 15.0.113.0 from the build of this PR https://github.com/keymanapp/keyman/pull/5723

---

**Keyboard**
 - Keyboard name: khmer_angkor
 - Keyboard version: 1.0.9
 - Language name: Khmer

**Comment by mcdurdin** [comment]
I wonder if this is a font issue? In any case, it's not specific to Keyman Developer -- it's to do with rendering in KeymanWeb.
