### ISSUE TITLE
bug(developer): the subkeys are shown off to the right of their base key 

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#5780]
**Describe the bug**

The subkeys are not shown directly above their base key, but further away to the right of the screen.

iPhone view:

<img width="139" src="https://user-images.githubusercontent.com/28331388/135406910-453491b5-2696-4f81-8c0e-79b61ca5df6c.png">

<img width="139" src="https://user-images.githubusercontent.com/28331388/135406921-44bec163-dfb5-4023-a611-682e672b94b9.png">

**Expected behavior**

The subkeys should be shown right above their base key.

---

**Keyman Developer:**
 - OS: Windows 10 Pro 21H1 x64
 - Keyman Developer version: 15.0.113.0 from the build of this PR https://github.com/keymanapp/keyman/pull/5723

---

**Keyboard**
 - Keyboard name: khmer_angkor
 - Keyboard version: 1.0.9
 - Language name: Khmer

**Comment by mcdurdin** [comment]
Is this fixed by #5742?

**Comment by mcdurdin** [comment]
Pinging @MakaraSok:

> Is this fixed by #5742?

**Comment by mcdurdin** [comment]
@MakaraSok am assuming this is fixed because I cannot repro and no response from you 😁
