### ISSUE TITLE
feat(android): vibration while typing

### ISSUE THREAD

**Issue by rmlockwood** [keymanapp/keyman#5792]
I support a user that would like the option of having the device vibrate when typing on the screen. This haptic feedback would be helpful.

**Comment by mcdurdin** [comment]
This is a good feature request. We would need to implement the haptic feedback along with user interface to allow the user to turn it on and off.

I am listing this under Android for now; presumably we will want to synchronize the implementation with iOS.

This should be a fairly straightforward feature to implement. We'll aim for 16.0.

**Comment by darcywong00** [comment]
Fixed by #6626 and will be available in 15.0.250 beta
