### ISSUE TITLE
bug(web): test 'RegisterStub on same keyboard twice' sporadically fails

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#5799]
**Describe the bug**

We are finding that the engine test 'RegisterStub on same keyboard twice' sporadically fails during builds. Have not been able to trace the reason at this point. The issue appears to be new in 15.0.

Example failure: https://build.palaso.org/viewLog.html?buildId=292538&tab=buildResultsDiv&buildTypeId=Keymanweb_TestPullRequests#testNameId6336149092226859392

Note that it shows the subsequent test as failing. This is a reporting issue somewhere between Karma and TeamCity.

I have disabled the test for now.

---

**KeymanWeb:**
 - OS: any 
 - Browser: especially Firefox 
 - KeymanWeb Version: 15.0.124

**Comment by jahorton** [comment]
While working on #7024, I ran into a highly related issue with the most closely-related unit test.  It appears that both were conflating two different features that should be tested, so I split the unskipped one in twain, skipped the half for the feature that's being problematic, and removed its aspect from the previously-skipped test.

So, the part that's _now_ being skipped has to do with KMW's auto-activation of the first keyboard added to it.  That's the part that's been flaking.  The exact unit test mentioned above should now be fine, as it's no longer mixing this in with the rest of its test code.
