### ISSUE TITLE
chore(common): centralize test keyboards and build them as artifacts

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/keyman#5815]
Currently test keyboards are scattered all over the keyman repo as well as in https://github.com/ermshiperete/TestKeyboards.

@mcdurdin wrote on Slack:

>  I think I'd prefer to add test keyboards into the main repo and have a process to build them all as artifacts, perhaps along with the Keyman Developer build. That way we always get current versions to play with and have the ability to contrast with older builds also as required.
But I am not quite ready to do the path factoring required on the repository because right now we have keyboards scattered all over the place for tests in various platforms.

**Comment by ermshiperete** [comment]
Part of that was done as part of #5613, at least for the `common/core/desktop/tests/unit/kmx` tests.

**Comment by mcdurdin** [comment]
Postponing this for now -- we have the `common/test/keyboards` path for any new test keyboards. These deploy for test and release for all platforms except web, which probably needs to keep its test keyboards within the `web/testing/` path for ease of access.

**Comment by mcdurdin** [comment]
Closing as we have done a lot of consolidation. Any more work on this should have specific keyboards referenced as well as some justification for why we need to do it.
