### ISSUE TITLE
bug(android): no source mapping for crash reports on sentry

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#5818]
**Describe the bug**

Android reports do not appear to have source mapped in for crash reports, which is a shame. Other projects, e.g. keyman-windows, do have source mapped in; see screenshot below.

Compare: 
https://sentry.io/organizations/keyman/issues/2699454938/?project=5983520&query=is%3Aunresolved vs
https://sentry.io/organizations/keyman/issues/2700324563/?project=5983518&query=is%3Aunresolved

**Screenshots**

Android:
![image](https://user-images.githubusercontent.com/4498365/136454993-c84c75cf-b8c3-49ab-a189-06e23b8c03c8.png)

vs What we want (Windows):
![image](https://user-images.githubusercontent.com/4498365/136454730-f77bdab1-28ba-4aad-ac30-8cf0ccb4ebd3.png)

---

**Keyman for iPhone/iPad/Android:**
 - OS: Android 
 - Keyman version: 14.0, 15.0

**Comment by darcywong00** [comment]
I'll try to tackle this in Beta

**Comment by mcdurdin** [comment]
I've investigated this a little. No obvious reasons I can see at this point. Opened a case with Sentry but guessing they're gonna want us to upgrade the SDK version before talking to us (which is frustrating because this was an issue when the version we were on was current.)

**Comment by mcdurdin** [comment]
Per Sentry support (eventually), they discovered that:

> I heard back from my team and they said for Android, we do not support source maps.

Big sigh.
