### ISSUE TITLE
bug(oem/fv/ios): 2 FV keyboards disappear on iOS 15

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#5831]
@madebybridget reports

>  Hey team! Got a report that touch layouts for Tuscarora and Sm’algyax keyboards on the FV Keyboards App are no longer working after 2 users updated to iOS 15. "When I change to the FV Sm’algyax keyboard and go to press a letter, the whole keyboard flashes and doesn’t type the letter and after pressing three times or so, the entire keyboard disappears."

> Same sort of issue for Tuscarora: "Basically what happens is the keyboard shows up but I am unable to press any of the characters. It comes to a point where the keyboard characters disappear from the keyboard."

![image0](https://user-images.githubusercontent.com/7358010/137408812-37f75e49-60ea-4ae8-af71-c29afc65746f.png)

**Comment by sgschantz** [comment]
I was able to reproduce on my iPhone running iOS 15.0.2 and the Sm’algyax keyboard. I don't see a Tuscarora keyboard, but I could also reproduce with the Skarù-re keybaord which has an alternate name of Tuscarora and with Onödowága.

**Comment by darcywong00** [comment]
A Keyman user reports on the community site this was impacting him in the Keyman app too
https://community.software.sil.org/t/i-phone-13-pro-max/5500

@Shavian-info mentions a possible fix involves enabling Keyman to "Allow full access"?
https://community.software.sil.org/t/i-phone-13-pro-max/5500/4

If that's the case, maybe we add a step to "Get Started" to direct users to that setting?

**Comment by sgschantz** [comment]
In Keyman, I can reproduce with iOS 15 on my iPhone 11 Pro if both
1) In Settings -> General -> Keyboard -> Keyboards -> Keyman, Allow Full Access is switch is disabled
2) I type in a different app outside of Keyman with a Keyman keyboard selected in the OSK. Typing inside of Keyman config is fine, but typing in Pages, Notes, Contacts or the homescreen Search box all cause the OSK to disappear on the second keystroke.

I am unable to reproduce on any simulator with either FV or Keyman.

Text copies of the console logs are attached. One with errors only and one also with all messages for the same duration. I noticed that the first errors appeared in the log when I disabled Allow Full Access -- before even switching to the Keyman keyboard.

[disappearing kb ios errors log](https://github.com/keymanapp/keyman/files/7465660/disappearing.kb.ios.errors.log)
[disappearing kb ios messages log](https://github.com/keymanapp/keyman/files/7465661/disappearing.kb.ios.messages.log)

**Comment by mcdurdin** [comment]
The following crash report in the log may be relevant?

```
error	12:55:15.134814+0700	SWKeyboard	networkd_settings_setup_notify_watch notify_register_dispatch(com.apple.system.networkd.settings) [status 9] failed, dumping backtrace:
        [arm64] libnetcore-2736.12.1
    0   libnetwork.dylib                    0x0000000182da99c0 __nw_create_backtrace_string + 120
    1   libnetwork.dylib                    0x000000018257a7d8 D810C689-1339-3FC6-96E8-196B9901E4DC + 858072
    2   libnetwork.dylib                    0x00000001825429ec D810C689-1339-3FC6-96E8-196B9901E4DC + 629228
    3   libnetwork.dylib                    0x0000000182564810 networkd_settings_get_int64_with_default + 32
    4   libnetwork.dylib                    0x0000000182576a50 D810C689-1339-3FC6-96E8-196B9901E4DC + 842320
    5   libnetwork.dylib                    0x00000001825914a4 D810C689-1339-3FC6-96E8-196B9901E4DC + 951460
    6   libdispatch.dylib                   0x00000001814d9950 959CD6E4-0CE7-3022-B73C-8B36F79F4745 + 14672
    7   libdispatch.dylib                   0x00000001814db1d8 959CD6E4-0CE7-3022-B73C-8B36F79F4745 + 20952
    8   libnetwork.dy<…>
fault	12:55:15.130665+0700	SWKeyboard	networkd_settings_setup_notify_watch notify_register_dispatch(com.apple.system.networkd.settings) [status 9] failed
error	12:55:15.134979+0700	SWKeyboard	networkd_settings_read_from_file Sandbox is preventing this process from reading networkd settings file at "/Library/Preferences/com.apple.networkd.plist", please add an exception.
error	12:55:15.135015+0700	SWKeyboard	networkd_settings_read_from_file Sandbox is preventing this process from reading networkd settings file at "/Library/Preferences/com.apple.networkd.plist", please add an exception.
error	12:55:15.135248+0700	SWKeyboard	networkd_settings_init notify_register_check(com.apple.system.networkd.settings) status 9 token -1
```
