### ISSUE TITLE
feat(android):  Improved globe key experience (Part 2)

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#5834]
Follow-on to #1887

@MayuraVerma requested on the [community site](https://community.software.sil.org/t/feedback-on-keyman-15-0-alpha/5405/12) to tweak to the globe key experience

> Preferred method for Keyman:
Press and hold Globe Icon
Get list of all keyboards, in which “Keyman” is one them. Similar to how the list is generated by all the above layouts.

> Tap Globe Icon
Toggle to next Keyman Keyboard layout.
If only one Keyboard is installed in Keyman, then use “Next Keyboard” method to switch to next system keyboard layout. Otherwise, “Tap Globe Icon” will not yield anything, when only one keyboard is installed.

There's more UX discussion in that thread...

**Comment by mcdurdin** [comment]
> In fact space bar long press, is a good place for list of keyman keyboards. Since it displays keyboard name in Keyman.

Some keyboards have a spacebar longpress menu already (e.g. Khmer)

**Comment by mcdurdin** [comment]
> The key issue is what order to list the Keyman keyboards in, and by extension what order to cycle through them. The Gboard implementation is far from ideal in this respect.

I agree that this is important; see #5835 for this. We'll keep the issue of keyboard order separate from the function of the picker itself.

**Comment by mcdurdin** [comment]
I can see two things we should do for version 15:

1. Long press should trigger the keyboard menu -- right now it only triggers on the release of the key, which is not ideal
2. Find a way to list the other keyboard apps in the Keyman keyboard picker menu.

**Comment by mcdurdin** [comment]
Listing other keyboard apps. First:

1. Use [`getInputMethodList()`](https://developer.android.com/reference/android/view/inputmethod/InputMethodManager.html#getInputMethodList()) to get the list of input method apps.
2. Use [`switchInputMethod()`](https://developer.android.com/reference/android/inputmethodservice/InputMethodService#switchInputMethod(java.lang.String)) to switch to the alternative input method.

**Comment by mcdurdin** [comment]
Also potentially relevant in the future is [`InputMethodSubtype`](https://developer.android.com/reference/android/view/inputmethod/InputMethodSubtype.InputMethodSubtypeBuilder)

**Comment by darcywong00** [comment]
The scope of this will also only apply to the Keyman system keyboard's "Keyboard picker" menu.
Will remove the existing "CLOSE KEYMAN" button because we will list other IME's.

**Comment by MayuraVerma** [comment]
@darcywong00 
Keyman 15.0.186-alpha, 
Android 11

Still showing only keyman keyboards
