### ISSUE TITLE
bug(developer): when Keyman for Windows is not installed, Keyman Developer crashes after initiating Debugger 

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#5845]
**Describe the bug**

Keyman Developer crashes when attempting to start the Debugger without having Keyman for Windows installed.
> Details for error report for Keyman app:
>   Application Identifier: keyman-14.0.282
>   Error Identifier: 8F20D1BB24F64DEA871454DE4A3C85CE

**Expected behavior**

A prompt saying that Keyman for Windows is required to start the Debugger.

---

**Keyman for Windows:**
 - OS: Windows 10 21H1 x64
 - Keyman version: 14.0.282
 - Target Application: Keyman Developer

**Comment by mcdurdin** [comment]
Closing as fixed in 15.0
