### ISSUE TITLE
bug(developer): “Unable to start debugging – failed to switch to language with error 80004005” 

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#5846]
**Describe the bug**

At one point, I got the error:

![image](https://user-images.githubusercontent.com/28331388/138205178-d35ebab4-456d-4843-aeb3-254b07562803.png)

when:

1. Keyman Developer was installed and used to successfully compile a keyboard
2. start the debugger without having Keyman for Windows installed to see a dialogue notify that there is no Keyman installed follow by a separate error "The keyboard failed to unload with the error 0000007E."
3. Click "OK" and then install Keyman for Windows
4. Restart the machine and run Keyman Developer Debugger to see the error as shown in the screenshot above after starting Debugger.

**Expected behavior**

No error should be experienced just because of Keyman Developer is installed before Keyman for Windows.

---

**Keyman for Window:**
 - OS: Windows 10 21H2 x64
 - Keyman version: 14.0.282
 - Target Application: Keyman Developer

**Comment by mcdurdin** [comment]
Closing as fixed in 15.0
