### ISSUE TITLE
bug(web): Highlight and replace/delete is not working

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#5853]
@katelem24 reports on [community site](https://community.software.sil.org/t/feedback-on-keyman-15-0-alpha/5405/24)

> Highlight and replace/delete is not working.
When text is highlighted, whatever action is applied to the highlighted text affects only the last letter in the highlight. So, to delete a paragraph, you have to delete it one letter at a time or switch to another keyboard that can highlight and delete all at once.

## Configuration
> Android, version: 15.0.135-alpha
>
>Keyman web, version 14.0.268
For Keyman web, any action taken only affects the character at where the insertion point was before the selection/highlight.
>
>I think it also affects the current released version on Android (I can’t tell, I’ve since been using the 15-alpha versions).

**Comment by darcywong00** [comment]
per @mcdurdin 

> Keyman Engine for Android should pass selected text as null context to KeymanWeb engine.

**Comment by darcywong00** [comment]
> > > Keyman Engine for Android should pass selected text as null context to KeymanWeb engine
> > 
> > 
> > Should that still be implemented on a separate PR?
> 
> Yes, but let's review what the status is for all apps on this:
> 
- [ ] Keyman for Android
- [ ] Keyman for iOS
- [ ] KeymanWeb (non-touch mode)
- [ ] Keyman for Windows
- [ ] Keyman for Linux
- [ ] Keyman for macOS
 
> We may need to check multiple modes in Windows, macOS as well.

Keyman for Android re-inserts selected text
KeymanWeb (non-touch mode) correctly replaces selected text

**Comment by mcdurdin** [comment]
I noted also we should look at backspace behaviour when text is selected -- it should just delete the selection but on KMW at least it also deletes one char to left of selection (oops!)

**Comment by darcywong00** [comment]
More notes. We'll want to check all Keyman platforms to verify these 3 scenarios:

1. When text is selected, an inserted character should replace the selection
2. When text is selected, backspace should only delete the selection
3. When text is selected, treat context as empty for keyboard rules (intentionally ignore text before selection too, since that might be pretty far and confusing to consider)

**Comment by mcdurdin** [comment]
Fixed in #6272
