### ISSUE TITLE
bug(mac): When using Farsiman keyboard, the cursor stays on the far right of the text at times even though it's for RTL language

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#5855]
**Describe the bug**

macOS Catalina/BigSur - Notes - the cursor is shown on the left at first, but upon pressing the spacebar it jumps to the far right.

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/28331388/138797818-e01508a1-4a75-47ba-9c2c-02d87e877482.png">

macOS BigSur - LibreOffice - the cursor is always shown on the far right while the texts output on the far left.

<img width="1508" alt="image" src="https://user-images.githubusercontent.com/28331388/138798202-7b7c8b2b-f404-416c-aa67-bf39804b5285.png">

The above behavior doesn't show when testing with TextEdit on macOS BigSur. The cursor always stays on the far left as expected.

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/28331388/138798483-420c5b8c-5a72-4489-9564-3a4429227914.png">

**Expected behavior**

The cursor should always be shown on the far left as Farsiman keyboard is RTL.

---

**Keyman for macOS:**
 - OS: macOS Catalina 10.15.5 | macOS Big Sur 11.6
 - Keyman version: 14.0.282
 - Target Application: Notes, LibreOffice, TextEdit

**Additional context**

https://community.software.sil.org/t/fixing-issues-with-keyman-and-macos-catalina/2745/30

**Comment by mcdurdin** [comment]
This relates to #170 and #2237. I will close it as a duplicate
