### ISSUE TITLE
bug(mac): OSK popups randomly system-wide

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#5856]
**Describe the bug**
OSK popups randomly system-wide

**To Reproduce**
OSK popups randomly system-wide, it can happen anywhere. It is hard to reproduce.
But it is frequent

**Expected behavior**
OSK should not popup

**Keyman for Windows/macOS/Linux:**
 - OS: macOS Monterey
 - Keyman version: 15.0.136-alpha
 - Target Application: system-wide

**Comment by MayuraVerma** [comment]
Random, I am trying to edit playlist in music app.
OSK popups.

<img width="963" alt="image" src="https://user-images.githubusercontent.com/14062593/140546726-b2e0605f-1171-4431-85d5-bb8f84934946.png">

**Comment by mcdurdin** [comment]
Yes, I have observed this; we probably won't be able to address this in 15.0 but will be spending some effort I hope on OSK behaviour, theming and consistency in 16.0.

**Comment by SabineSIL** [comment]
see #1523

**Comment by SabineSIL** [comment]
see #433
