### ISSUE TITLE
bug(windows): A crash occurs when update Keyman Developer 14.0.280 to xx.x.282 

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#5868]
**Describe the bug**

Details for error report for Keyman app:
  Application Identifier: tike-14.0.280
  Error Identifier: 4BFFD83AF7114BA92D13E256D7590A85

---

**Keyman for Windows:**
 - OS: Windows 10 21H1x64
 - Keyman version: 14.0.282

**Keyman Developer:**
 - Keyman Developer version: 14.0.280 > .282

**Comment by mcdurdin** [comment]
I cannot find this error report in Sentry, so will have to close this. It does not look like it is a consistent issue?
