### ISSUE TITLE
bug(developer): regression batch testing is running surprisingly slow

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#5870]
**Describe the bug**

Go to Khmer Angkor keyboard source and then open the keyboard project using Keyman Developer 14.0.282. Now, start debugger. Under regression testing, click on "Options" button > "Batch regression testing...". Navigate to the regression test set (khmer_angkor\extras\regression_tests) and start the test to see how slow the test runs.

**Expected behavior**

The test running speed should not be that sluggish. The debugger on Keyman Developer 15.0.135 is running as fast as expected.

---

**Keyman for Windows and Keyman Developer:**
 - OS: Windows 10 21H1 x64
 - Keyman version: 14.0.282
 - Target Application: Keyman Developer

---

**Keyboard**
 - Keyboard name: khmer_angkor
 - Keyboard version: 1.0.9
 - Language name: Khmer

**Comment by mcdurdin** [comment]
This is fixed in 15.0, yeah?
