### ISSUE TITLE
bug: EuroLatin KB (iOS) blanks out when used as system KB 

### ISSUE THREAD

**Issue by eb1** [keymanapp/keyman#5871]
**Describe the bug**
When using Keyman as the system keyboard outside of the app (e.g., in the iOS Notes program), the on-screen keyboard does not respond to tap events; instead, the entire keyboard area does blank. I'm not sure if this is an issue with the EuroLatin keyboard or the Keyman software when used as a system keyboard. This does not happen when inputting data in the Keyman app.

**To Reproduce**

1. Open an iOS app that allows for on-screen keyboard input (iOS Notes, for example), and navigate to / select an area that brings up the on-screen keyboard.
2. Click on the Globe icon to switch between keyboards, until Keyman is the selected keyboard. I'm currently using the EuroLatin keyboard.
3. Tap on a letter in the keyboard. You'll see the keyboard screen area blank out. No letter will be added to the input.

**Expected behavior**
Keyboard input.

**Screenshots**
![blank keyboard screen](https://user-images.githubusercontent.com/1458944/139738319-58e1c48b-a092-4e83-b45d-8acaa4a9e8bc.PNG)

**Keyman for iPhone/iPad/Android:**
 - Device: iPhone XR
 - OS: 15.0.2
 - Keyman version 14.0.282
 - Target application: Notes, Adapt It Mobile, Key It

**Keyboard**
 - Keyboard name: EuroLatin (SIL)
 - Keyboard version: ? Not sure (downloaded 1 Nov 2021)
 - Language name: English, Spanish

**Additional context**
Appears that the keys are working properly within Keyman, just not outside of the program.

**Comment by mcdurdin** [comment]
Thanks for this report. We have been investigating this issue, also reported in #5831. A temporary workaround is to enable 'Allow full access' for Keyman.

I'll close this report; please follow #58431 for further progress.
