### ISSUE TITLE
bug(windows): Opening crash kmshell

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#5882]
**Describe the bug**

On behalf of user reported at https://community.software.sil.org/t/opening-crash-kmshell/5526:
> I installed the Keyman 15 alpha, then uninstalled Keyman 15 alpha and tried to re-install Keyman 14.0.282 again.
> 
> After installation and now every time I try to open Keyman, I get this error report. I have tried restarting and re-installing several times.
> 
> Details for error report for Keyman app:
> Application Identifier: kmshell-14.0.282
> Error Identifier: 2C1E94DE94F947BB18B90FB3DC02013A

**Keyman for Windows:**
 - OS: 
 - Keyman version: after uninstalling 15 alpha and reinstalling 14 stable
 - Target Application: Keyman

**Comment by mcdurdin** [comment]
I am thinking this is related to shared components and the need to uninstall both Keyman and Keyman Developer before downgrading. I will go ahead and close this because uninstalling both is the solution.
