### ISSUE TITLE
feat(ios): Touch keyboard height adjustability

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#5897]
Described for Android in #3225. We need a similar fix for iOS.

---

**Keyman for iPhone/iPad/Android:**
 - Device: iPhone/iPad 
 - OS: iOS 
 - Keyman version: 15.0

**Comment by MakaraSok** [comment]
A recent request at https://community.software.sil.org/t/feature-request/7347.

**Comment by sgschantz** [comment]
Moving to sprint focusing on ios work
