### ISSUE TITLE
CTRL+ALT Characters not displaying in KMW's OSK

### ISSUE THREAD

**Issue by andjc** [keymanapp/keyman#59]
Ctrl+Alt key sequences not displaying in onscreen keyboard although we can successfully input characters.

keyboard layout: el_togo
repo: https://bitbucket.org/enablinglanguages/globalbility_project/src/35654d99094891366f20c8bb9c32caf30a1e3cdf/el_togo/?at=master

**Comment by mcdurdin** [comment]
This appears to happen when a single keyboard uses both differentiated left/right modifiers (i.e. LALT/RALT/LCTRL/RCTRL) and merged modifiers (CTRL/ALT).

**Comment by jahorton** [comment]
With #300's upcoming approval, differentiated (chiral) modifiers will be supported in KeymanWeb, which should address this issue.

Developer support for this upcoming KMW feature is still pending but is planned to occur within our next sprint.

Note that this feature (with the rest of our 10.0 features) is scheduled for official release toward the end of this year.

**Comment by jahorton** [comment]
At this time, we've been unable to replicate the issue.  We'll go ahead and mark this closed for now, but if this is still an issue for you with the alpha, please let us know and we'd be glad to reopen it.
