### ISSUE TITLE
Inconsistent longpress of keys involving shift

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#590]
This was found during review of keyboards [PR 166](https://github.com/keymanapp/keyboards/pull/166)
(User is going to change his keys to U_XXXX to workaround this bug)

On the numeric layer, row 3 has a `(` key with this code
```
           {
             "id": "K_9",
             "text": "(",
             "layer": "shift",
             "sk": [
               {
                 "text": "[",
                 "id": "K_LBRKT"
               },
               {
                 "text": "{",
                 "id": "K_LBRKT",
                 "layer": "shift"
               }
             ]
           },
```

Tapping on `(` correctly outputs `(`,
but a longpress on `(` and selecting `(` is outputting `9` instead.

This issue exists in 10.x alpha and also on 2.8.300 stable.

**Comment by mcdurdin** [comment]
This likely relates to a similar bug reported with Khmer Angkor keyboard:

>long press of K_J outputs Coeng, while it should be ញ

**Comment by darcywong00** [comment]
Duplicated on https://keymanweb.com/?tier=alpha#km,Keyboard_khmer_angkor
