### ISSUE TITLE
bug(web): keyboard loads with different font

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#5918]
**Describe the bug**
keyboard key label font loads with different weight or different typeface. 

**To Reproduce**
Launch the keyman keyboard and change to another Keyman keyboard layout, you will see light weight text. If you change it to system keyboard and back to keyman, then it loads normal font weight

**Expected behavior**
Key label font must not change

**Screenshots**
https://user-images.githubusercontent.com/14062593/142057074-2a71605d-7d47-472a-814b-c9ee15d841e3.MOV
---

**Keyman for iPhone/iPad/Android:**
 - Device: iPhone 12 pro max
 - OS: iOS 15.1
 - Keyman version 15.0.148-alpha
 - Target application: system wide

**Comment by MayuraVerma** [comment]
Keyman switched from other keyman keyboards: font weight is light/thin
![image](https://user-images.githubusercontent.com/14062593/142157382-60535da0-689e-4022-aced-a56bf6d685de.jpeg)

Keyman switched from system keyboard: font weight is normal
![image](https://user-images.githubusercontent.com/14062593/142157546-bd23b2ad-f86b-4982-9a1a-d758e4324963.jpeg)

**Comment by mcdurdin** [comment]
I'm no longer able to reproduce this in 15.0.222-beta. Please reopen if you see any further issues.
