### ISSUE TITLE
feat: Keyboard learning language

### ISSUE THREAD

**Issue by Pantyhose-X** [keymanapp/keyman#5921]
**Is your feature request related to a problem? Please describe.**
TTS Keyboard learning language

**Describe the solution you'd like**
Hope to support
Text-to-Speech Always speak typed keys Speak phonetic letters Phonetic letters are spoken when long pressing on keyboard keys and navigating by character.
Applied to language learning. Pronunciation correction

* example，

https://user-images.githubusercontent.com/42504385/132130706-a1a8ec10-416a-4711-b5d3-c91086e9710f.mp4

https://user-images.githubusercontent.com/42504385/127757873-c3c076d3-ce73-40b1-8f57-423459fc0c2f.MP4

The mother tongue is not English. Need to learn English, the market is very large

**Describe alternatives you've considered**
l considered [sinstar3](https://github.com/soui3-demo/sinstar3) Developers are reluctant to include other languages for reading aloud.[TTS Read aloud keyboard](https://soime.cn/) Only Chinese is supported for reading aloud

**Keyman for Windows/macOS/Linux:**
 - OS: Windows 10 1809 x64, opensuse 15.3 x64

**Additional context**

[Mozilla's Text-to-Speech](https://github.com/mozilla/TTS)  
[coqui-ai TTS](https://github.com/coqui-ai/TTS) 
[Google Text-to-Speech apk](https://play.google.com/store/apps/details?id=com.google.android.tts&hl=en_US&gl=US)

**Comment by mcdurdin** [comment]
Thank you for your contribution and feature request. At this time, adding text-to-speech is not in scope for Keyman; this may be something we consider one day in the future, but we currently have many other keyboard-specific functions that we need to work on.

You are welcome to fork the Keyman project and make your own implementation of course!

**Comment by Pantyhose-X** [comment]
@mcdurdin No sound, you are a dumb. I know that Keyman and [SIL](https://www.sil.org/) are partners to protect EndanGred Language. TTS function is very important to language learners
