### ISSUE TITLE
chore(web): remove remaining IE references

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#5943]
**Describe the bug**

There are still a number of references to IE11 and older versions, e.g. mspointerevents, promise polyfill, _IE variable, IEVersion, document.createEvent, etc. These should be removed.

---

**KeymanWeb:**
 - KeymanWeb Version: 15.0

**Comment by mcdurdin** [comment]
This needs to be done on the alpha (master) branch.

**Comment by jahorton** [comment]
Post-discussion note:  where before, we were fine leaving in old IE support 'cause there was no need to break it... now we're going in and fully ripping it out.  There's been enough time since.

**Comment by jahorton** [comment]
Self note:

<img width="1185" alt="image" src="https://user-images.githubusercontent.com/25213402/164260581-956a9fb8-ca58-46d2-9d55-5bda763d3215.png">

Therefore, the `Promise` polyfill should indeed be safe to rip out when dropping IE support.

**Comment by jahorton** [comment]
Of course there did have to be one major complication:

https://github.com/keymanapp/keyman/blob/bb4887387729a2ea5761e4e0d7d19c118eac6d9f/common/predictive-text/promise-store.ts#L44-L51

The `Map` built-in type seen there... requires Chrome for Android **38**.  One version off from the minimum we need to support for Web to work on non-updated API 21 devices.  `es6-shim` has been providing that for us.

**Comment by mcdurdin** [comment]
> The `Map` built-in type seen there... [requires Chrome for Android **38**](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map#browser_compatibility). One version off from the minimum we need to support for Web to work on non-updated API 21 devices. `es6-shim` has been providing that for us.

We should solve this by moving the shim into the Keyman for Android host page rather than keeping it in KMW.

**Comment by jahorton** [comment]
> > The `Map` built-in type seen there... [requires Chrome for Android **38**](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map#browser_compatibility). One version off from the minimum we need to support for Web to work on non-updated API 21 devices. `es6-shim` has been providing that for us.
> 
> We should solve this by moving the shim into the Keyman for Android host page rather than keeping it in KMW.

I presume we may wish to do this only on devices that need it?  I think logic for this should be possible.

After a bit of investigation into Android code:

https://github.com/keymanapp/keyman/blob/bb4887387729a2ea5761e4e0d7d19c118eac6d9f/android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/WebViewUtils.java#L28-L52

Though that doesn't actually include a step - yet - for versions that can only support touch keyboards when es6-shim is included.  I could add one, or...

https://github.com/keymanapp/keyman/blob/bb4887387729a2ea5761e4e0d7d19c118eac6d9f/android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/WebViewUtils.java#L85-L91

Change a little `private` to `public` and we're in business.  I mean, it's a stateless, `static` function; it's not gonna break anything if we let the engine library's keyboard WebView access it during setup.

Again, of course, there's always the lazy approach of "just link it in all the time."  Either way ought work.

**Comment by mcdurdin** [comment]
> Again, of course, there's always the lazy approach of "just link it in all the time." Either way ought work.

This is fine for the Android app. We include the ref in the android host web page (before kmw).

We can even document that as an alternative for web hosts that want to support older browsers with KMW -- we could do it on keymanweb.com if we wanted.
