### ISSUE TITLE
bug: EAccessViolation in module sentry.dll at 0000CB15

### ISSUE THREAD

**Issue by nike4613** [keymanapp/keyman#5945]
When attempting to install Keyman (but only on this one machine!), the application successfully installs, but any time any application is started, that application gives the following (more or less):
```
EAccessViolation in module sentry.dll at 0000CB15.
Access fiolation at address 6628CB15 in module 'sentry.dll'.
Read of address 00000010.
```

I have tested each executable in the installation directories, and they all give this error. Removing `sentry.dll` and `sentry.x64.dll` only cause the application to not load at all.

**To Reproduce**
1. Perform a fresh installation of Keyman.
2. Attempt to launch any application.
3. See error.

**Expected behavior**
A running and functional application.

---

**Keyman for Windows:**
 - OS: Windows 10 Pro x64 20H2 (build 19042.1288)
 - Keyman version: 14.0.283

**Additional context**
I have successfully installed this version of Keyman on my laptop running Windows 10 Pro 2004 (build 19041.1348) with no issues.

**Comment by mcdurdin** [comment]
I'm not immediately sure what the issue is...

* Have you installed other versions of Keyman or Keyman Developer on this machine in the past?

* Can you try deleting the folder %localappdata%\keyman\diag, in case Sentry has a corrupt backing database? This folder is safe to delete any time Keyman and Keyman Developer are not running.

**Comment by nike4613** [comment]
I have never installed any other version of Keyman to this machine. I have also, in trying to resolve this myself, done as thorough of a purge of Keyman as I could before attempting a reinstall. This meant
- Deleting all Keyman files on the system (appdata, program files, etc)
- Deleting all registry entries that were associated with Keyman
As such, `%localappdata%\keyman\diag` is completely empty, and the issue remains.

**Comment by mcdurdin** [comment]
We have an updated version of Sentry in Keyman 15 alpha. Could you try installing that version, before we dig any further into the issue with the 14.0.283 version? https://keyman.com/alpha

**Comment by nike4613** [comment]
The alpha seems to work fine. Give me a second to actually install a keyboard with it.

**Comment by nike4613** [comment]
The keyboard I want to use doesn't seem to be behaving, though Keyman itself is.

**Comment by mcdurdin** [comment]
Great, glad to hear the updated Sentry resolves the issue. If you have any further trouble with the keyboard, let us know :grin:
