### ISSUE TITLE
bug(windows): SIL IPA Keyboard causes catastrophic crashing on 15 alpha

### ISSUE THREAD

**Issue by nike4613** [keymanapp/keyman#5951]
When using Keyman 15 alpha (which unfortunately for me is the only version that works on this machine), the SIL IPA keyboard, whenever it is used, causes the following applications to crash:
- My test text editor (Notepad++)
- My Discord client
- My web browser (Vivaldi 4.3.2439.56 64 bit)
- `explorer.exe`

**To Reproduce**
1. Select the IPA keyboard
2. Select an empty file in Notepad++
3. Press any key
4. Watch as your system implodes

**Expected behavior**
The IPA keyboard is usable, or at the very least not actively destructive.

**Keyman for Windows/macOS/Linux:**
 - OS: Windows 10 Pro x64 20H2 (build 19042.1288)
 - Keyman version: 15.0.151-alpha
 - Target Application: Notepad++, Vivaldi, explorer.exe

---

**Keyboard**
 - Keyboard name: IPA (SIL)
 - Keyboard version: 1.8.6
 - Language name: und-Latn

**Additional context**
I have *attempted* to turn off the Keyman Core engine, however it seems as though that setting is not being respected.
![image](https://user-images.githubusercontent.com/10411129/142566036-2d5036b9-3da2-4792-a4e3-9f353e35617b.png)
![image](https://user-images.githubusercontent.com/10411129/142566068-ef32c04d-70b9-4172-8eec-4114bf606264.png)

I have also not actually tried any other Keyman keyboards, but standard Windows keyboards work fine even when Keyman is running.

**Comment by nike4613** [comment]
I should probably also note that I am pretty much at the point where I am considering this as "something which was simply not meant to be."

**Comment by mcdurdin** [comment]
After changing the keyman core setting, you will need to exit and restart Keyman. Does that make any difference? @rc-swag can you replicate this?

**Comment by nike4613** [comment]
After a full Keyman restart, the setting stays changed, and yet it continues to use Keyman Core.

**Comment by mcdurdin** [comment]
FWIW, [Keyman 13](https://downloads.keyman.com/windows/stable/13.0.118.0/keymandesktop-13.0.118.0.exe) does not use Sentry, so you may have more luck with that... I'm sorry you are not having a great time on this particular computer. (I just tested on my machine and sil_ipa seems to be working here on 15.0.146-alpha which I installed a couple of days ago.)

We can also look into a diagnostic report if you send one through, following steps shown at: https://help.keyman.com/kb/40

**Comment by nike4613** [comment]
Just submitted, case number 5594.

**Comment by mcdurdin** [comment]
The diagnostic report looks pretty straightforward; I can't see any obvious issues there. The crashes you are experiencing are pretty unusual though so there must be something going on... At this point, about the only thing we can try is capturing crash dumps and then analyzing those.

If you are comfortable with doing that (either using [ProcDump](https://docs.microsoft.com/en-us/sysinternals/downloads/procdump) or by setting up [Windows Crash Reporting](https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps)), and uploading any dumps you get to this issue, I can dig into them to see what I can see.

**Comment by nike4613** [comment]
I'll get a dump tomorrow, probably. I've already had to move my browser windows back to their correct desktops enough times today.

**Comment by nike4613** [comment]
Some new insight into this: it only seems to cause problem when I have Vivaldi running. If it isn't then the keyboard works just fine.

Interestingly, I have Vivaldi *also* installed on my laptop, where it *does* work, even when running.

**Comment by nike4613** [comment]
I'm going to try to update Vivaldi, see if that resolves the issue.

**Comment by nike4613** [comment]
Scratch that earlier message. It doesn't work even with Vivaldi completely closed. I don't know why it worked that once.

**Comment by nike4613** [comment]
Alright, well  I managed to get a dump of Explorer crashing. Wasn't able to record Notepad++ crashing though, and am rather hesitant to attempt to procdump my browser.
[explorer.exe_211119_181822.zip](https://github.com/keymanapp/keyman/files/7573522/explorer.exe_211119_181822.zip)

**Comment by rc-swag** [comment]
> After changing the keyman core setting, you will need to exit and restart Keyman. Does that make any difference? @rc-swag can you replicate this?

I installed the same alpha version and keyboard I could not replicate the crash. I tested it with both keyman core engine enabled and disabled. I can look into it further in the next few days.

**Comment by mcdurdin** [comment]
I've extracted a callstack from the dump file, thank you @nike4613.

```
...
00 00000000`02b2dc10 00007ff8`5ef0f163     ntdll!RtlReportFatalFailure+0x9
01 00000000`02b2dc60 00007ff8`5ef17ee2     ntdll!RtlReportCriticalFailure+0x97
02 00000000`02b2dd50 00007ff8`5ef181ca     ntdll!RtlpHeapHandleError+0x12
03 00000000`02b2dd80 00007ff8`5ef1de51     ntdll!RtlpHpHeapHandleError+0x7a
04 00000000`02b2ddb0 00007ff8`5ee35b43     ntdll!RtlpLogHeapFailure+0x45
05 00000000`02b2dde0 00007ff8`5ee347b1     ntdll!RtlpFreeHeapInternal+0x433
06 00000000`02b2dea0 00000000`5ef7e0e0     ntdll!RtlFreeHeap+0x51
07 00000000`02b2dee0 00000000`5eed8278     keyman64!_free_base+0x1c [minkernel\crts\ucrt\src\appcrt\heap\free_base.cpp @ 105] 
08 00000000`02b2df10 00000000`5eed74b8     keyman64!IntLoadKeyboardOptionsCore+0x338 [C:\BuildAgent\work\82cac59564031c74\keyman\windows\src\engine\keyman32\keyboardoptions.cpp @ 284] 
09 00000000`02b2e3e0 00000000`5eed71ae     keyman64!LoadlpKeyboardCore+0x258 [C:\BuildAgent\work\82cac59564031c74\keyman\windows\src\engine\keyman32\K32_load.cpp @ 123] 
0a 00000000`02b2e560 00000000`5eedc761     keyman64!LoadlpKeyboard+0x2e [C:\BuildAgent\work\82cac59564031c74\keyman\windows\src\engine\keyman32\K32_load.cpp @ 130] 
0b 00000000`02b2e6a0 00000000`5eedc20e     keyman64!SelectKeyboardCore+0x1b1 [C:\BuildAgent\work\82cac59564031c74\keyman\windows\src\engine\keyman32\selectkeyboard.cpp @ 92] 
0c 00000000`02b2e740 00000000`5eed3090     keyman64!SelectKeyboard+0x2e [C:\BuildAgent\work\82cac59564031c74\keyman\windows\src\engine\keyman32\selectkeyboard.cpp @ 212] 
0d 00000000`02b2e7d0 00000000`5ee52006     keyman64!TIPActivateKeyboard+0x100 [C:\BuildAgent\work\82cac59564031c74\keyman\windows\src\engine\keyman32\appint\aiTIP.cpp @ 75] 
0e 00000000`02b2e810 00000000`5ee53acc     kmtip64!CKMTipTextService::TIPNotifyActivate+0x46 [C:\BuildAgent\work\82cac59564031c74\keyman\windows\src\engine\kmtip\kmkey.cpp @ 263] 
0f 00000000`02b2e840 00007ff8`5d9094f2     kmtip64!CKMTipTextService::OnActivated+0x2bc [C:\BuildAgent\work\82cac59564031c74\keyman\windows\src\engine\kmtip\tmgrsink.cpp @ 202] 
...
```

The code in question (crash on line 284 freeing data):

https://github.com/keymanapp/keyman/commit/09611b600dbc967b74af8302f34d78db81ee2d52

I can see the issue. We can free memory that we never allocated, for example, on first use of a keyboard when there are no registry entries corresponding to the keyboard option data, because we have uninitialized pointers in the `keyboardOpts` memory. To fix this we make the `for` loop in line 282 `for (int i = 0; i < n; i++)` -- because we know that those entries were valid.

For added robustness, I would also zero out the newly allocated `keyboardOpts` memory so that the `delete[]` is a no-op.

Finally, we should consider splitting the registry index variable from the memory index variable (both currently `n`) because otherwise if the `if()` on line 259 fails, we can be left with an invalid entry in the middle of the `keyboardOpts` array.

I am guessing we have not seen this elsewhere because the registry values in question were already present.

**Comment by rc-swag** [comment]
I have created a PR for this [5959](https://github.com/keymanapp/keyman/pull/5959). I was able to work out how to replicate the crash. I need to change a keyboard option, I change it to use the `Before` option.

**Comment by rc-swag** [comment]
@nike4613  version [15.0.156](https://keyman.com/downloads/releases/alpha/15.0.156) has the fix for this issue.
