### ISSUE TITLE
bug(windows): Haroi keyboard works with bundled installer, but not with separate kmp

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#5962]
I don't really understand this one, but I experienced it after fielding a tech support request for Haroi keyboard.

On Windows 10
They had Keyman 14.0.282 installed, along with the Haroi keyboard (1.2.1) but the Haroi keyboard didn't work (installed with `hro-Latn-VN`).

### Steps to repro:
1. Install Keyman for Windows 14 or 15
2. From Keyman, download and install Haroi for `hro-Latn-VN`.
3. With Haroi selected, type a vowel + tone combo <https://help.keyman.com/keyboard/haroi/1.2.1/haroi>
4. See the tone isn't inserted

### Workaround
1. Uninstall Keyman 14
2. Download bundled installer:
https://downloads.keyman.com/windows/stable/14.0.283/keyman-setup.haroi.exe
3. The Haroi keyboard installs with "Vietnamese" language. Add `hro-Latn-VN` and remove "Vietnamese" 
4. With Haroi selected, type a vowel + tone combo
5. See the tone inserted

@MakaraSok notes the keyboard also works fine on Keyman for macOS 14.0.282.

**Comment by rc-swag** [comment]
@marc and @darcywong00  I propose closing this Issue as working now.

I have tried the following steps with both the `15-beta` build and the latest version  `14.0.287`. Each time it works correctly.
I even tried on windows 7 and it worked.

**Comment by darcywong00** [comment]
I just installed the latest version 14.0.287 and the Haroi keyboard worked on my Win 10 machine. Can close
