### ISSUE TITLE
bug(web): subkeys highlighting wrong position when scrollTop is not zero

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#5964]
**Describe the bug**

Load this [build](https://build.palaso.org/repository/download/Keymanweb_TestPullRequests/297860:id/samples/unminified.html) on an android device and turn the phone side way to enter horizontal mode, now try and use a EuroLatin keyboard to trigger a subkey. Notice the selected key is not on where is being touched/pressed. It seems to be a row above where is being touched/pressed.

<img width="869" alt="image" src="https://user-images.githubusercontent.com/28331388/143204252-2743bdc2-72b8-47bc-ac9a-b7a3878ae746.png">

Video:

https://user-images.githubusercontent.com/28331388/144836458-5898f3ac-e754-49a5-88a5-cba5d00aa6ec.mov

**Expected behavior**

The subkey selected should be right on where is being touched/pressed.

---

**KeymanWeb:**
 - OS: Android 10
 - Browser: Chrome Version 74.0.03729.185
 - KeymanWeb Version: pr [5958](https://build.palaso.org/repository/download/Keymanweb_TestPullRequests/297860:id/samples/unminified.html) (#5958)

---

**Keyboard**
 - Keyboard name: EuroLatin (SIL)

**Comment by darcywong00** [comment]
This is what I can repro on: 
Pixel 2 emulator, Android 5.0 (API 21)
keymanweb.com using English - sil_euro_latin

1. Long-press on <kbd>g</kbd>
2. Keep pressing down, and move a little around the base <kbd>g</kbd> key.
3. Observe the first item in the popups is highlighted `ǵ`

**Comment by darcywong00** [comment]
At this point since 15.0 is fine, I don't think we'll be spending the time to investigate why the popup in 14.0 isn't working.

**Comment by mcdurdin** [comment]
> At this point since 15.0 is fine, I don't think we'll be spending the time to investigate why the popup in 14.0 isn't working.

It appears this is also an issue in 15.0. See https://github.com/keymanapp/keyman/pull/5963#issuecomment-987712479

**Comment by mcdurdin** [comment]
I have reproduced this issue. It occurs when the `scrollTop` of the document is not 0, and gets worse the further you scroll. So we are missing a scrolling offset adjustment on the longpress calculations -- this does not appear to be a problem on the main keyboard.

**Comment by mcdurdin** [comment]
This beautiful little comment in [subkeyPopup.ts](https://github.com/keymanapp/keyman/blob/93af2a3d84489e15f514c553546805c2fe90fd5e/web/source/osk/browser/subkeyPopup.ts#L55-L57) hints at the root of the problem:

```
      // The holder is position:fixed, but the keys do not need to be, as no scrolling
      // is possible while the array is visible.  So it is simplest to let the keys have
      // position:static and display:inline-block
```
