### ISSUE TITLE
bug(android): Shift state becomes inactive after rotation while it's on

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#5965]
**Describe the bug**

While Shift state is active, try and rotate the phone and then try and press on the shift key to see that it doesn't switch to the shift layer at all. The key become inactive.

https://user-images.githubusercontent.com/28331388/143209847-b550dbfc-a490-4af4-a99e-fd0dd1053268.mov

**Expected behavior**

The shift key should not become inactive because of leaving it on prior to the rotation.

---

**Keyman for Android:**
 - Device: Pixel 2 emulator
 - OS: Android 10
 - Keyman version 15.0.154-alpha-est-5958
 - Target application: Keyman

---

**Keyboard**
 - Keyboard name: EuroLatin (SIL)
 - Keyboard version: 1.9.5
 - Language name: English

**Additional context**

cf. https://github.com/keymanapp/keyman/pull/5958

**Comment by MakaraSok** [comment]
The same issue is experienced in iOS 14.5.


https://user-images.githubusercontent.com/28331388/143215270-a0e4b638-2955-4d18-95ea-a1c0973a8a53.mov

**Comment by darcywong00** [comment]
I can also repro on Keyman for Android 14.0.283 stable
Android 11

**Comment by darcywong00** [comment]
Shift button does work after rotation on Keyman for Android 13.0.6222 stable
Android 11

**Comment by darcywong00** [comment]
Fixed by #6498
