### ISSUE TITLE
bug(web/developer): different rendered texts on the keycaps of OSKs on KeymanWeb test page and web debugger in Developer

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#5983]
**Describe the bug**

Keyman web - Unminified test page (on Chrome in Windows 10):
![image](https://user-images.githubusercontent.com/28331388/143978246-4e018650-1c59-409b-b162-6361847f5983.png)

Web Debugger in Keyman Developer (on Chrome in Windows 10):
![image](https://user-images.githubusercontent.com/28331388/143979572-a7a32fa0-cd54-4c36-b7fe-b8c498a722b5.png)

The four highlighted keys are rendered differently. The ones on KeymanWeb is well rendered -- only on dotted circle shown. The ones on web debugger in Keyman Developer show two dotted circles instead of one which is expected.

Tested off of the build of this PR: https://github.com/keymanapp/keyman/pull/5906

---

**Keyman for Windows:**
 - OS: Windows 10 Pro 21H1
 - Keyman version: 15.0.157
 - Target Application: Chrome Version 96.0.4664.45 (Official Build) (64-bit)

**KeymanWeb:**
 - KeymanWeb Version: 
 - URL: https://build.palaso.org/repository/download/Keymanweb_TestPullRequests/298716:id/samples/unminified.html

---

**Keyboard**
 - Keyboard name: khmer_angkor
 - Keyboard version: 1.1
 - Language name: Khmer

**Comment by mcdurdin** [comment]
This will be due to the fonts specified in both cases. The test in Keyman Developer uses only the font specified in the Fonts dialog. I don't think this is a bug.
