### ISSUE TITLE
bug(android): the base keys and the subkeys are in different font face

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#5985]
**Describe the bug**

<img width="278" alt="image" src="https://user-images.githubusercontent.com/28331388/144007078-995bacfc-99a5-42c3-a2d7-f44af31a828a.png">

When testing https://github.com/keymanapp/keyman/pull/5906, it's noticed that the font face of the base keys and the subkeys are not consistent. The base keys are in Mondulkiri font (chosen for this keyboard), but the subkeys are in the Android default font (Noto Sans Khmer).

The font should have been consistent. If not, they looks kind of odd.

---

**Keyman for Android:**
 - Device: Pixel 4
 - OS: Android 10 - API 29
 - Keyman version 15.0.157-alpha-test-5906
 - Target application: Keyman

---

**Keyboard**
 - Keyboard name: khmer_angkor
 - Keyboard version: 1.1
 - Language name: Khmer

**Comment by darcywong00** [comment]
Likely related to #5914

**Comment by darcywong00** [comment]
Will resolve with that issue
