### ISSUE TITLE
bug(android): three Khmer characters are not shown correctly on their keycaps 

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#5986]
**Describe the bug**

<img width="500" src="https://user-images.githubusercontent.com/28331388/144009648-21952ff6-d2fe-40fe-b53d-969d71824c85.png">

On Android 10 API 29, ៊ ៉ and ្ are not rendered correctly. They expected to have dotted circle.

---

**Keyman for Android:**
 - Device: Pixel C
 - OS: Android 10 - API 29
 - Keyman version 15.0.157-alpha-test-5906
 - Target application: Keyman

---

**Keyboard**
 - Keyboard name: khmer_angkor
 - Keyboard version: 1.1
 - Language name: Khmer

**Comment by darcywong00** [comment]
Dotted-circles were removed from KMW rendering in #3039

There's also the separate issue of the Android keyboard not using the right font path (ref #5914)

**Comment by mcdurdin** [comment]
> Dotted-circles were removed from KMW rendering in #3039

I'm not sure that this answers the question though -- do we need dotted circles as a base for those three characters? Should we find a way to include them in the keyboard?

**Comment by darcywong00** [comment]
>  do we need dotted circles as a base for those three characters? Should we find a way to include them in the keyboard?

I thought if we update the OSK to use dotted circles, we end up with inconsistent rendering across the platforms. Some will show dotted circle, some will show two dotted circles...

**Comment by mcdurdin** [comment]
> I thought if we update the OSK to use dotted circles, we end up with inconsistent rendering across the platforms. Some will show dotted circle, some will show two dotted circles...

Yes, this is the problem. The only real solutions AFAIK are:

1. Allow dev to specify font and even string per platform and add ability to preview in the process (wow big job!), or
2. Create a specific font for the Khmer OSK that has special characters just for this purpose.

I think (2) is probably a better answer for the Khmer rendering problem here -- I wonder if Didi would be willing to make a custom version of Khmer Mondulkiri for this purpose?

**Comment by mcdurdin** [comment]
See also https://github.com/keymanapp/keyman/pull/6006#issuecomment-989489983 for related Khmer Angkor OSK render issues. Am working via email on a potential solution.

**Comment by darcywong00** [comment]
Triage to 15.0 beta. This issue depends on keymanapp/keyboards#1710

**Comment by mcdurdin** [comment]
Tracking in keymanapp/keyboards#1710 - this is not an Android-specific bug. Closing here.
