### ISSUE TITLE
bug(windows): emoji input panel in Windows 11 does not respond to keystrokes if Keyman is running

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#5996]
**Describe the bug**

If Keyman is running, even if a Keyman keyboard is not selected, it does not appear to be possible to use the keyboard in the emoji input panel.

Ref: https://community.software.sil.org/t/cant-search-for-emojis-or-gifs-in-the-windows-emoji-panel-if-keyman-is-running/5559

Note: this appears to be an issue only with the Windows 11 emoji input panel; Windows 10 appears to work fine.

I have reproduced this issue in Windows 11 Insider Preview on a VM.

**Workaround**

Disable Keyman's serialized input:

1. Open Keyman Configuration
2. Select Options / Keyman System Settings
3. For `engine.compatibility.serialize_input`, enter the value `0`.
4. Restart Keyman

---

**Keyman for Windows/macOS/Linux:**
 - OS: Windows 11 
 - Keyman version: 14.0.283 
 - Target Application: emoji input panel

**Comment by rc-swag** [comment]
@marc can you post a few notes for  where to start the investigation for this please.

**Comment by mcdurdin** [comment]
Ah yes. The correct initial workaround I think is to switch off the pipeline altogether if a Keyman keyboard is not active. That doesn't allow us to use the emoji picker while a Keyman keyboard is active, but it is a good first step.

The area we probably should start in is here:

https://github.com/keymanapp/keyman/blob/733d112d055742a7d80576c46b54abc674b9f48a/windows/src/engine/keyman32/k32_lowlevelkeyboardhook.cpp#L225-L256

And we need to find out if a Keyman keyboard is active. Now this is the tricky bit -- this is currently only visible in the active thread (the app that has input focus), not in the thread which does the serialiazed input, which is usually in another process (the keyman.exe process).

The good news is that switching keyboards and/or processes causes a `wm_keyman_control` `KMC_PROFILECHANGED` to be posted to the 'master controller' which is in the same process as the serialized input controller.

So we can watch for that in the `_kmnGetMessageProc` (e.g. around line 229 where we currently test for `wm_keyman_control_internal`, add another test for `wm_keyman_control`) and update a process-local variable to determine if a Keyman keyboard is active or not (we *could* track the specific keyboard that is active, similar to how `KeymanID` is used, but we don't need to). We can test whether it's a Keyman keyboard by peeking at the string that is passed in via the atom value:

https://github.com/keymanapp/keyman/blob/ee87f0a33ea2a47978347eb992e84500e865fcfc/windows/src/engine/keyman32/selectkeyboard.cpp#L295-L312

The atom string would be either `threadid|langid|hkl` or `threadid|langid|clsid|guidprofile`, defined in [PrepareLanguageSwitchString](https://github.com/keymanapp/keyman/blob/ee87f0a33ea2a47978347eb992e84500e865fcfc/windows/src/engine/keyman32/selectkeyboard.cpp#L270-L279). So we can test for the presence of Keyman's CLSID in the atom string, using [`GetAtomName`](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getatomnamea) to retrieve the string from the `HIWORD(mp->lParam)`:

https://github.com/keymanapp/keyman/blob/8853155203dda5b554d2e0610caab4882ca3d05e/windows/src/engine/kmtip/globals.cpp#L36-L37

And that should be enough to tell us if a Keyman keyboard is active. HTH!
