### ISSUE TITLE
bug(windows): crashed when install the latest stable from 14.0.282

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#5997]
**Describe the bug**

I had a version older Keyman on Windows (14.0.282). Click and install it. Keyman then prompts me to install the latest version (14.0.283). I did just that. The version was downloaded and installed, but then this happened.

![image](https://user-images.githubusercontent.com/28331388/144346299-dd9bba2c-e07e-4c2b-bd1a-42f2b410b68a.png)

Details for error report for Keyman app:
  Application Identifier: kmshell-14.0.283
  Error Identifier: 66CE03E4B85548A550B1FA1256A715D1

**Expected behavior**

Keyman should be installed without any issue.

---

**Keyman for Windows:**
 - OS: Windows 10 Pro 21H1 x64
 - Keyman version: 14.0.282 > 14.0.283
 - Target Application: Keyman

**Comment by MakaraSok** [comment]
Looking into the app installed. I saw that Keyman Developer 15 was installed. This might be the culprit of the crash, but should Keyman says something about the conflict?

**Comment by MakaraSok** [comment]
Uninstall the existing versions of Keyman. Reinstall using the same method. Everything went through without an issue.

**Comment by mcdurdin** [comment]
This looks like it was because part of a test version of Keyman was installed (kmcomapi.dll was a private build, not an official build). Not clear where the version mismatch was. As you have now uninstalled and reinstalled, we cannot diagnose any further, so going ahead and closing this.
