### ISSUE TITLE
bug(model): the prediction picked omits the opening single and double quote

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#6024]
**Describe the bug**

In any version of Keyman, make sure the prediction is on. Press an opening single or double quote and then select a word from the suggestion to see the error. The quote shouldn't have been omitted and replaced with the suggestion picked. This is observed in both iOS and Android.

https://user-images.githubusercontent.com/28331388/145174163-abcf8534-5916-484f-9c23-c01515cba566.mov

**Comment by jahorton** [comment]
#7205 may address the bug mentioned here.
