### ISSUE TITLE
feat: osk should translate invisible controls to images

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#6031]
**Is your feature request related to a problem? Please describe.**

For example, with the Gilaki keyboard, there are a number of keys that emit ZWJ and other invisible control characters. Keyman should detect the presence of one of these characters on the key cap and automatically use a visible control symbol in its place (and perhaps give the option to use an alternate char if preferred, such as the ZWNJ chars from the touch keyboard). This should also be possible with the touch keyboard.

Note: it may be safer to make this a function of the visual keyboard editor rather than making it automatic at runtime.

Note: the Gilaki keyboard uses bitmaps currently to display these keys. However, bitmaps are not supported in KeymanWeb, and are also not scalable.

---

**Keyman for Windows/macOS/Linux:**
 - OS: any 
 - Keyman version: 14.0

**Comment by mcdurdin** [comment]
Note: this should be accomplished with the KeymanWebOsk font and be up to the keyboard developer to select the image they want from that (e.g. *ZWNJ*).

**Comment by darcywong00** [comment]
Involves WS Tech to update our internal font

**Comment by mcdurdin** [comment]
Completed with #9846.
