### ISSUE TITLE
feat(android): Quickly install Android apk via usb cable

### ISSUE THREAD

**Issue by mnjames** [keymanapp/keyman#6032]
**Is your feature request related to a problem? Please describe.**
The current process of moving an Android test build to a phone can be complicated, involving copying an apk via a file explorer or sending it to the phone in some other way.

**Describe the solution you'd like**
I believe using adb to push the apk to the phone via a usb cable (and automatically open the app) would speed things up. For an example of how this might work, see [Scripture App Builder](https://software.sil.org/scriptureappbuilder/download/) and they way they do this.

POTENTIAL ISSUES
This would require bundling a small number of new files, including adb, with Keyman Developer. I don't think the overhead would be very significant and shouldn't cause any performance issues.
If Keyman is already installed and you are simply trying to test a new project, I assume this will still work but I'm less clear on the specifics. adb can also push regular files (like a .kmp file), so I think this should be possible.

**Comment by mcdurdin** [comment]
Just trying to get my head around this -- are you looking at deploying Keyman itself to the Android device, or a keyboard that you are testing, or both?

Re Keyman APK: We don't bundle the Keyman for Android apk with Keyman Developer, so it would need to be downloaded as part of the deployment in that case (it would be a hassle for us to bundle the apk as the Android and Developer builds processes are currently completely isolated, and we'd like to maintain that).

**Comment by mnjames** [comment]
In listening to presentations regarding Keyman, it sounded like a few people said it took a bit of extra work to test keyboards on a phone (not just in a browser on the phone). This report was a suggestion to try to speed up that process, but it's something I haven't personally done in a couple of years, so maybe I'm trying to solve a problem that doesn't exist. Feel free to close this if that's true.

I guess I'm looking to quickly deploy the keyboard for testing within Keyman for Android, but it's not necessary that you push the apk. I think it's reasonable to tell the developer to install Keyman for Android themselves (since it's a one-time process) and then just push the .kmp file. I still think that adb might be a possible way to push the .kmp file to the correct location on the Android phone.

I think adb could also be used to automatically open Keyman for Android on the phone after the keyboard is sent over.

**Comment by mcdurdin** [comment]
I'd like to suggest an alternative approach to solving this: use the upcoming Keyman Developer Server, which can host a public URL with using a tool called ngrok. Then if your dev computer and the target device are online, they will be able to connect (no need to get them on the same network any more). The test host page includes a link to install the latest stable Keyman version as well!

Keyman Developer will make it easy to configure ngrok. The two big advantages to using ngrok, as opposed to a cable, are:

1. It works with all platforms, not just Android
2. You can share the keyboard you are testing in real time with a remote colleague

You can see the pull request implementing this at https://github.com/keymanapp/keyman/pull/6073.

Do you think that functionality will address this sufficiently?

**Comment by mnjames** [comment]
Yes, I think that would have the same functionality, so this idea probably isn't necessary and could be closed.

**Comment by mcdurdin** [comment]
Great! Going ahead and closing this. Thank you for your feature suggestion and keep them coming 😁
