### ISSUE TITLE
bug(iOS): Keyman in-app crashes on backspace

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#6041]
**Describe the bug**

Using the build of this PR https://github.com/keymanapp/keyman/pull/5963. 

Keyman crashes when trying to backspace on multiple line breaks. The crash occurs on the second to last line break.

https://user-images.githubusercontent.com/28331388/145766286-ce22895a-e8c5-454c-8566-75983060d484.mov

**Expected behavior**

No crash should occur when backspace on a line break.

---

**Keyman for iPhone:**
 - Device: iPhone 13 (Simulator)
 - OS: iOS 15.0
 - Keyman version 15.0.157
 - Target application: Keyman

---

**Keyboard**
[start_of_sentence_3621.kmp](https://drive.google.com/uc?id=1WbiesUOgI5Nby8xJM_vSy-Ip_-98nLCf&export=download)

**Comment by MakaraSok** [comment]
This issue also experienced when Keyman is using as a system keyboard.

https://user-images.githubusercontent.com/28331388/145775637-76590368-f815-442e-a9a7-4ed4b86626c4.mov

**Comment by sgschantz** [comment]
@MakaraSok The in-app backspace problem that causes the app to crash appears to be unrelated to the other issue described using the system keyboard. The system keyboard issue should be documented as a separate issue. In that case, the keyboard does not crash but is unable to backspace more than two lines previous to the current one.

**Comment by sgschantz** [comment]
Fixed by PR #6371
