### ISSUE TITLE
bug(win): Pyidaungsu MM keyboard's associated language is not Burmese on Win7 

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#6043]
**Describe the bug**

With the current latest stable (Keyman 14.0.283) on Windows 7, install [Pyidaungsu MM](https://www.myanmar.gov.mm/documents/20143/17963807/PyidaungsuMM-2.1.kmp.zip/e7c756e5-264f-4e9d-ea62-823ca22c547a?t=1556094619996) keyboard. The keyboard got installed successfully, but then the associate language is 'en-US' instead of the expected Burmese language.

Diagnostic [report](https://drive.google.com/file/d/1dU_lrpUPT1V2G7QV3i_yTECzrocGq2yy/view?usp=sharing)

I was for a moment thought that this might because of the keyboard, but when tested with "Myanmar3 (SIL)" keyboard. This same behavior occurs.

![image](https://user-images.githubusercontent.com/28331388/145925670-07afc394-8e9a-4e7a-b47a-e44f45a3ae92.png)

It looks more like it's because of Windows 7.

---

**Keyman for Windows:**
 - OS: Windows 7 Pro x64, Service Pack 1
 - Keyman version: 14.0.283
 - Target Application: Keyman

---

**Keyboard**
 - Keyboard name: (see the screenshot of the two keyboards above)

**Additional context**

Original report: https://community.software.sil.org/t/diagnostic-report-from-aung122-gmail-com/5674

**Comment by mcdurdin** [comment]
This is because Windows 7 did not include the Myanmar language.
