### ISSUE TITLE
bug: Ipad with Smart Connector

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#6071]
**Describe the bug**
Keyman with non-latin keyboards do not work with iPad with external keyboards with smart connector

**To Reproduce**
1. Install Keyman with any non-latin keyboard
2. Connect iPad with external keyboard via smart connector
3. Enable keyman keyboard, start typing
4. Keyman will switch to system default keyboard of that language
5. Surprising, iOS installed a system keyboard of the language, Kannada in this case.
This is not an issue, if Keyman has enable latin keyboard, Euro-SIL2. External keyboard will map the keys correctly.
Also, iPad connector to bluetooth keyboards, such Apple Magic Keyboard, Keyman works perfectly.

**Expected behavior**
Keyman non-latin keyboard should work with iPad and extenal keyboard

**Keyman for iPhone/iPad/Android:**
 - Device: iPad 9th gen, iPad Pro 12.9inch
 - OS: iPad OS 15.2
 - Keyman version 15.0.171-alpha -->
 - Target application: Any application, notes, keyman, etc

**Comment by mcdurdin** [comment]
This is an iOS limitation. See #1018.
