### ISSUE TITLE
chore(android): disable linting for kmsample2

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#6075]
The lint tool is crashing but only on kmsample2, so let's just disable it there for now?

For example: https://build.palaso.org/viewLog.html?buildId=301805&buildTypeId=KeymanAndroid_TestSamplesAndTestProjects&tab=buildLog

**Comment by darcywong00** [comment]
Ah, comparing the KMSample1 and KMSample2 build.sh scripts, I notice KMSample2 doesn't have the bits for NO_DAEMON.
```bash
#!/bin/sh
# Build KMSample2

#
# Prevents 'clear' on exit of mingw64 bash shell
#
SHLVL=0

echo Build KMSample2
./gradlew clean build
```

**Comment by mcdurdin** [comment]
And ... that's why it also leaves a mess after it fails... thank you Darcy!
