### ISSUE TITLE
bug(web): font size is still wrong after #5906

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#6076]
The font size fix in #5906 does not appear to have worked consistently on Android, at least. More testing and validation is certainly required.

Per https://community.software.sil.org/t/feedback-on-keyman-15-0-alpha/5405/34:
* I’m using the keyboard in the app.
* Tecno POP3, Android 8.1
* The keyboard in the 1st image (top) is the published version, while that in the 2nd image is not yet published. Both versions used to display with those small fonts until 15.165 and 15.169. I can’t tell the behaviour in 15.166-8; I haven’t tested those.
* I’ve specified a font but not size. The keyboard font is NotoSans Regular. I’m not aware font size could be specified.

_Originally posted by @mcdurdin in https://github.com/keymanapp/keyman/issues/5906#issuecomment-999929340_

> 15.164-alpha (normal font size, I like this)
![](https://community.software.sil.org/uploads/default/original/2X/7/77c6e3edaade7a3a592288d21f2a3fe40fee77da.png)

> 15.169-alpha (large font, I don't really...)
![](https://community.software.sil.org/uploads/default/original/2X/a/a293cd30eab332a7dfeeaee7e96a740006e57993.png)

**Comment by darcywong00** [comment]
I've created an emulator for Tecno Pop 3, Android 8.1 (5.7" screen, 480 x 960 pixels).

![Screenshot_1641444930](https://user-images.githubusercontent.com/7358010/148330468-613e7596-ffe5-4eef-bda9-c336a5e8a97d.png)

15.0.169 also includes the Android fix for the keyboard font paths (#5987). Could that be a factor in the OSK change?

**Comment by darcywong00** [comment]
I suspect prior to 15.0.164, the Tecno Pop 3 was getting treated as "tablet" in some of the KeymanWeb paths, resulting in a font scaling of 1.2
https://github.com/keymanapp/keyman/pull/5906/files#diff-174fda0a428ca733bb60b62848e3b9799bcc73fc5d1804b2e2b3e61982b1d981L389

After #5906, Tecno Pop 3 is treated as a phone and the font scaling is 
```
const fontScale = device.formFactor == 'phone'
          ? 1.6 * (isEmbedded ? 0.65 : 0.6) * 1.2  // Combines original scaling factor with one previously applied to the layer group.
          : 2; // iPad or Android tablet
```

e.g. 1.6 * 0.64 * 1.2 = 1.248

**Comment by darcywong00** [comment]
The reason 15.0.164 was treating the Tecno Pop 3 as tablet is this calculation
```
 device.formFactor=((screen.height < 4.0 * dpi) || (screen.width < 4.0 * dpi)) ? 'phone' : 'tablet';
      }
```
screen.height = 960
screen.width = 480
4.0 * dpi = 384

**Comment by mcdurdin** [comment]
I am somewhat confused by this now -- @darcywong00, it looks like you haven't been able to reproduce the original report as all of your screen images are showing good font scales?

**Comment by darcywong00** [comment]
I think the original report was wanting the smaller font scale
like what was in 15.0.164 alpha (note the space bar label size among the Keyman versions).

The tricky part is that the "smaller" font scale was actually intended for tablets, not phones.

**Comment by mcdurdin** [comment]
The issue I think is more the key caps than the spacebar text:

![image](https://user-images.githubusercontent.com/4498365/151277722-8e05b688-8877-4785-80eb-4b1fa8173f6f.png)

I've screensnapped the <kbd>ch</kbd> key, and the 15.0.169 reported by end user is the only one which is problematic, as far as I can tell. I adjusted the keyboard height to make sure that wasn't causing the problem. I cannot repro the original report, and it looks like your screenshots are also okay for the key cap font size.

**Comment by mcdurdin** [comment]
For now, I would like to abandon this. The font size is actually 'correct' -- as in it matches other phone devices. In 14.0, this particular device was being treated as a tablet, which made the font size slightly smaller. We can revisit in 16.0 if we end up doing OSK theming.
