### ISSUE TITLE
bug(android): longpress with Shift+RightAlt not working on touch

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#6089]
**Describe the bug**

A longpress key with reference to a key with Shift+RightAlt in the computer layout does not output anything. 
It works just fine though when testing on Chrome emulator.

This was encountered when testing [Ukwuani keyboard](https://drive.google.com/drive/folders/1M-HUkJhfvLgb9_G4d-WVuo2tMlqRNl-7).

**To Reproduce**

1. On the current stable version of Keyman (14.0.283) install the keyboard above.
2. Go the Shift layer and then press and hold on key <kbd>E</kbd> to output the capital E with a dot below
3. See error - nothing is output.

**Expected behavior**

The longpress with such reference should work as normal, just like how it works in Chrome emulator.

---

**Keyman for Android:**
 - Device: Pixel XL
 - OS: Android 10.0
 - Keyman version: 14.0.283-stable
 - Target application: Keyman

**KeymanWeb:**
 - OS: Windows 10
 - Browser: Chrome
 - KeymanWeb Version: ?
 - URL: N/A (test it locally using the Ukwuani keyboard project above.

---

**Additional context**

This works OK in iOS when testing with Keyman 14.0.284.

**Comment by darcywong00** [comment]
I'm not seeing Shift+RightAlt in the keyboard source

With Keyman Developer 15.0.172 alpha, I was able to get the keyboard working after modifying the beginning part of the .kmn
```
begin Unicode > use(Unicode)

group(Unicode) using keys
```

**Comment by MakaraSok** [comment]
[ukwuani.zip](https://github.com/keymanapp/keyman/files/7845806/ukwuani.zip)
