### ISSUE TITLE
chore: update github auto merge PR to only merge on 'auto' label

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#6117]
Currently, the .github\workflows\auto-merge-keyman-server-pr.yml workflow approves and merges any PRs from keyman-server. However, we should only do that if the appropriate label `auto` is also set (or if `auto:` is at the start of the title, perhaps). Arising from #6114.

From slack, by myself:
>Well that was fun. https://github.com/keymanapp/keyman/pull/6114 was approved and merged by some 'helpful' bots because the PR was created by keyman-server... argh. Looks like we need to watch out for the 'auto' label!

**Comment by darcywong00** [comment]
Would the condition be something like this?
```
if: github.actor == 'keyman-server' && startsWith(${{github.event.pull_request.title}}, 'auto:')
```

**Comment by mcdurdin** [comment]
From the [expression syntax docs](https://docs.github.com/en/actions/learn-github-actions/expressions), I think it should be:

```yaml
  if: ${{ github.actor == 'keyman-server' && startsWith(github.event.pull_request.title, 'auto:') }}
```

The `${{}}` is optional for `if` but doesn't hurt.
