### ISSUE TITLE
bug(web): AltGr, "Ctrl + Alt" functionality doesn't work

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#6140]
@MakaraSok writes:
> * **TEST BASIC_KEYBOARD: FAILED** For Desktop version, AltGr functionality doesn't work. Nothing appears when it's pressed. "Ctrl + Alt" doesn't work either. For mobile, the normal space set to ZWSP doesn't output the ZWSP character at all.

I think this may be a separate issue to address, as I don't think it is new, nor is it directly related to the Keyman Developer Server, rather being something to do with KeymanWeb. I assume you are testing the Khmer Angkor keyboard? 

_Originally posted by @mcdurdin in https://github.com/keymanapp/keyman/issues/6073#issuecomment-1019554490_

**Comment by MakaraSok** [comment]
> I assume you are testing the Khmer Angkor keyboard?

Any keyboard with the layers in use doesn't have them working.

**Comment by mcdurdin** [comment]
So we can easily repro, can you please document:

* The name of one published keyboard with the issue and a version
* Example key sequences and expected output
* Affected operating systems and versions
* Affected browsers and versions
* Base keyboard layout in the operating system(s)

**Comment by MakaraSok** [comment]
- Keyman Developer beta 15.0.209
- keyboard [ukwuani.zip](https://github.com/keymanapp/keyman/files/8211675/ukwuani.zip)
- click on the Alt key on the OSK present to test on Chrome, the Alt key works as expected when testing within Keyman Developer debugger, <kbd>Alt</kbd><kbd>n</kbd> > `ṅ`

https://user-images.githubusercontent.com/28331388/157373657-e11088d1-f741-4ed7-b08b-b972df9aad99.mov


- Windows 10 Pro 2H21
- Chrome 99.0.4844.51
- US - English

**Comment by mcdurdin** [comment]
I think this is fixed with #6357. Can you retest on that build?

**Comment by MakaraSok** [comment]
The issue has been fixed. See the screen recording below for your reference.

https://user-images.githubusercontent.com/28331388/159624810-72ff97b4-0338-4e6c-9cef-36593c691267.mov

**Comment by mcdurdin** [comment]
Excellent!
