### ISSUE TITLE
bug(developer): crash after clicking on Test Keyboard on web without compiling 

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#6149]
**Describe the bug**

https://user-images.githubusercontent.com/28331388/150713479-f98b3b7c-9b0c-4d17-8e97-2193f29a11dc.mov

> Details for error report for Keyman app:
>>   Application Identifier: tike-15.0.182-alpha-test-6073
>>   Error Identifier: 2D624F0A69714ADEF61F5CE503DE187A

**To Reproduce**

1. Go to a keyboard project
2. Click to open the .kmn
3. Go to Build tab and then click to Test Keyman on web without compiling

**Expected behavior**

After clicking on the "OK" button of the warning message, the keyboard should have been built and one can go ahead and test the keyboard.

---

**Keyman Developer:**
 - OS: Windows 10 21H1 x64
 - Keyman Developer version: 15.0.182 alpha of this pr https://github.com/keymanapp/keyman/pull/6073.

**Comment by mcdurdin** [comment]
Is it possible to reproduce this on an alpha release build?
