### ISSUE TITLE
chore(linux): stop releasing KMFL together with Keyman

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#6163]
From @ermshiperete:

Currently we release KMFL in sync with Keyman although we longer actively develop it. There have been no changes since v14 other than packaging related commits.

This raises the question if we should stop releasing KMFL. The Linux users who still need it would still have access to it since the v14 packages won’t go away.

Not releasing it with v15 would save time with packaging, especially when uploading to Debian since there are 3 less packages that would need to be reviewed each time we upload a new version to Debian.

KMFL is self-contained, so any changes to Keyman won’t affect it. This means we don’t gain anything from regularly building packages for KMFL, and there are no benefits to the user. In the unlikely event that we’d have to fix a bug in KMFL we’d still be able to do that and manually release packages.

**Comment by mcdurdin** [comment]
From my perspective, this makes sense. The number of users depending on KMFL should be minimal now, and it should be well understood that KMFL is EOL.

One question: how do upgrades work for Keyman in the various packaging scenarios? Would upgrading from Keyman 14 to 15 cause KMFL to be uninstalled?

**Comment by ermshiperete** [comment]
> One question: how do upgrades work for Keyman in the various packaging scenarios? Would upgrading from Keyman 14 to 15 cause KMFL to be uninstalled?

No. KMFL is totally separate from Keyman, there are no dependencies in either direction, so they can be upgraded independently.

**Comment by ermshiperete** [comment]
This also requires updating the FAQ and help.keyman.com.
