### ISSUE TITLE
chore: add other non-printing characters to OSK font

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#6167]
> **Is there any way to mark special characters, such as: ZWSP, ZWNJ, ZWJ visually on the OSK?**

See https://github.com/silnrsi/font-keymanweb-osk/issues/3

_Originally posted by @mcdurdin in https://github.com/keymanapp/keyboards/issues/1710#issuecomment-1022704548_

**Comment by darcywong00** [comment]
KMW OSK font updated in #9469 so remaining work is to use the lebels (*ZWSP* etc)

**Comment by mcdurdin** [comment]
Calling this done, enough for now.
