### ISSUE TITLE
bug(linux): Reordering of characters doesn't work with Wayland

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/keyman#6172]
From testing https://github.com/keymanapp/keyman/pull/6135:

@MakaraSok reported when testing Ubuntu 21.10 Impish with Wayland: 

> in Khmer Angkor, when type kEjmr, the output should be ខ្មែរ​. The reordering rule should have been kicked in, but it doesn't seem to be so. This might be a bug in the system itself. This issue is not experienced in Ubuntu 20.04 LTS though when Khmer Mondulkiri is selected instead of the default font.

**Comment by ermshiperete** [comment]
I can confirm that it works in Ubuntu 20.04 with Wayland.

**Comment by ermshiperete** [comment]
Comparing the debug output of `ibus-engine-keyman` produced in libreoffice and gedit I notice that gedit has more `ibus_keyman_engine_set_surrounding_text` calls, whereas LO only gets it for the final keystroke, at which point the context no longer matches the expected.

**Comment by ermshiperete** [comment]
This seems to be the same problem as #6193. Tested in Ubuntu 22.04 with Wayland (which uses XWayland). With the settings from #6193 things work in LibreOffice.

**Comment by ermshiperete** [comment]
# User Testing

## Preparations

- The tests should be run on this Linux platform:
  - **GROUP_JAMMY_WAYLAND**: Ubuntu 22.04 Jammy with Gnome Shell and Wayland

- Install current beta version of Keyman

- Install Khmer Angkor keyboard in Keyman Configuration

- Open LibreOffice Writer, go to Tools/Options, Language Settings/Languages tab. Under "Default Languages for Documents" check the box for Complex text layout and select Khmer as language.

![Screenshot from 2022-02-18 12-01-23](https://user-images.githubusercontent.com/181336/154620732-ed19b43c-a792-4267-9fde-fe6e5a86db61.png)

- Also change the default style: go to Styles/Manage Styles, right-click on "Default Paragraph Style" and select Modify. Go to the Font tab. For CTL Font, select Family "Khmer Mondulkiri" and Language "Khmer".

![Screenshot from 2022-02-18 12-04-15](https://user-images.githubusercontent.com/181336/154621010-47305ccd-3c6d-4079-a12f-c4bc1c186ca9.png)

- Close LibreOffice Writer

- Reboot

## Tests

**TEST_LO**: Reordering of characters work correctly

- Open LibreOffice Writer, switch to Khmer keyboard, and type `xjmEr`
- The result should be `ខ្មែរ`.

**Comment by bharanidharanj** [comment]
### GROUP_JAMMY_WAYLAND: Ubuntu 22.04 Jammy with Gnome Shell and Wayland

* **TEST_LO (PASSED):** Followed the Steps as it mentioned in the Test instructions, with Keyman 15.0.232-beta build in Ubuntu 22.04 Jammy Jellyfish linux (Ubuntu on Xorg) and it is working as expected. 

<img width="300" src="https://user-images.githubusercontent.com/19683143/164434652-648c367a-039c-405c-b136-6153c5ea470a.PNG">
