### ISSUE TITLE
feat(android): Android Globe icon: single tap behavior with only one Keyman Keyboard

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#6175]
**Is your feature request related to a problem? Please describe.**
Android Globe icon "single tap behavior" with only one Keyman Keyboard installed, needs to be relooked into

Current scenario, with only one Keyman Keyboard installed, single tap on globe icon presents list of all system keyboards along with Keyman similar to long press on Globe Icon.

with more than one Keyman Keyboard installed, single tap on globe icon presents toggles between keyman keyboards

**Describe the solution you'd like**
with only one Keyman Keyboard installed, single tap on globe icon can switch to previously used system keyboard.

![image](https://user-images.githubusercontent.com/14062593/151436199-d4993911-1c60-42eb-bea2-9c2be6c356a2.png)

**Keyman for Android:**
 - Device: Samsung
 - OS: Andriod 11
 - Keyman version: 15.0.186-alpha
 - Target application: Notes, Keyman

**Comment by mcdurdin** [comment]
Thank you for the suggestion. We will review this as I think it makes sense, and may be able to fold it into the 15.0 release if implementation is straightforward (I am not sure if the 'previously used system keyboard' information is available to us).

**Comment by MayuraVerma** [comment]
> Thank you for the suggestion. We will review this as I think it makes sense, and may be able to fold it into the 15.0 release if implementation is straightforward (I am not sure if the 'previously used system keyboard' information is available to us).

Yes, It is available with switchToPreviousInputMethod()

Also, we are using if condition already for one keyboard scenario which is pulling the other keyboard list, instead we need to pull this method.

**Comment by darcywong00** [comment]
> Yes, It is available with switchToPreviousInputMethod()

@MayuraVerma - how about if we use [switchToNextInputMethod()](https://developer.android.com/reference/android/inputmethodservice/InputMethodService#switchToNextInputMethod(boolean)) instead of previous? This way the user could cycle through

* Gboard
* Keyman (with 1 keyboard)
* another keyboard (e.g. Swype or Samsung)

**Comment by mcdurdin** [comment]
> This way the user could cycle through

I think the idea is that tapping swaps between two most recent, and longpress allows you to switch to any. This is a common pattern for switching languages, apps, etc across various operating systems -- e.g. think Alt+Tab in Windows, Ctrl+Tab in many editors.

**Comment by MayuraVerma** [comment]
> > Yes, It is available with switchToPreviousInputMethod()
> 
> 
> 
> @MayuraVerma - how about if we use [switchToNextInputMethod()](https://developer.android.com/reference/android/inputmethodservice/InputMethodService#switchToNextInputMethod(boolean)) instead of previous? This way the user could cycle through
> 
> 
> 
> * Gboard
> 
> * Keyman (with 1 keyboard)
> 
> * another keyboard (e.g. Swype or Samsung)

With SwitchtoNextInputMethod, single tap will always to a keyboard which is the first in the ordered list of other keyboards, let's say it happens to be gBoard, then single tap from Keyman will always yield gBoard

With SwitchToPreviousInputMethod, single tap would go to previously used keyboard, let's say it was emoji or Swype, which was used just before.
For user, this would be dynamic response and perhaps yield a keyboard he/she has used in the same context, if it was a bilingual text.

My 2 cents

Apple implementation is very intuitive, Human friendly. For single tap in iOS and command+spaceBar in macOS is previous keyboard used. In fact, in mac, the list of keyboards while holding command + spaceBar, is in the order of usage, 1. current, 2. previous, 3. Previous to it,....

**Comment by MayuraVerma** [comment]
On a separate note.

For Single tap in Keyman with multiple Keyman Keyboards, we should consider the cycling of Keyman Keyboards followed by SwitchtoPreviousInputMethod, if it possible

This would be intuitive. Single tap and long press would have same logic

Otherwise single tap and long press would be zoned

It's like single tap is taking stairs
Long press is taking elevator

If we restrict single to only first five floors (Keyman with 5 keyboards)

And 6-10 floors you have to take only elevator (other 5 system keyboards)

Instead we can build the stairs to climb past fifth floor

Before globe icon is one button we are implementing two gestures, one is faster (long press) and other is ordered (single press), both gestures should have same playing field

**Comment by darcywong00** [comment]
I initially was planning to resolve this later after Beta release.
But since it involves a Keyman Engine for Android API change in `GlobeKeyAction`, I'll address it now.

```java
  // Globe key actions
  public enum GlobeKeyAction {
    GLOBE_KEY_ACTION_SHOW_MENU,
    // GLOBE_KEY_ACTION_SWITCH_TO_PREVIOUS_KEYBOARD,      // Switch to previous Keyman keyboard (reserved for flick)
    GLOBE_KEY_ACTION_SWITCH_TO_NEXT_KEYBOARD,             // Switch to next Keyman keyboard
    GLOBE_KEY_ACTION_ADVANCE_TO_PREVIOUS_SYSTEM_KEYBOARD, // Advance to previous system keyboard (this is the new one)
    GLOBE_KEY_ACTION_ADVANCE_TO_NEXT_SYSTEM_KEYBOARD,     // Advance to next system keyboard
    GLOBE_KEY_ACTION_SHOW_SYSTEM_KEYBOARDS,
    GLOBE_KEY_ACTION_DO_NOTHING,
  }
```
