### ISSUE TITLE
bug: iOS and Android Text Select weird behavior

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#6177]
**Describe the bug**
Selecting text in iOS and Android with Keyman keyboard is resulting in weird results
in Android, selecting text will copy and paste text
in iOS, text is deleted

**To Reproduce**
1. with Keyman keyboard, highlight any text in notes app or whatsapp
2. Text will be copied and pasted in Android, Text will be deleted in iOS

**Expected behavior**
Show context menu

**Keyman for iPhone:**
 - Device: iPhone 13 Pro Max
 - OS: iOS 15.2.1
 - Keyman version 15.0.186-alpha
 - Target application: Notes, Whatsapp

**Keyboard**
 - Keyboard name: EuroSil

**Comment by darcywong00** [comment]
We're already chasing down this issue in #5853.

Hopefully will be solved before 15.0 goes to Beta

**Comment by mcdurdin** [comment]
Fixed in #6274 and #6280.
