### ISSUE TITLE
feat: additional letters on on-screen keyboard key caps

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#6185]
**Is your feature request related to a problem? Please describe.**
Keyboard display layer can only display the current layer and underlying key labels (English).

We need a way to display text at least the shift layer on selected keys and tertiary text. Keyboard developer be able to display key labels more than current layer. 

Most importantly it should be to each key. If the text is entered in the key, should display the secondary and tertiary labels, if not, standard label

Please review the below link, which is a Keyboard Layout Editor. We need something similar with at least three labels on each keys.

Also, the standard way of displaying a dot for popup menu can be made optional. If the developers doesn’t want to display the dot, it can be removed. Most system keyboards do not have the dots.

**Describe the solution you'd like**

http://www.keyboard-layout-editor.com/#/

![image](https://user-images.githubusercontent.com/14062593/151857006-1a933d8e-5a99-46ba-a506-3c45f00747c3.png)

![image](https://user-images.githubusercontent.com/14062593/151858167-15de2da4-924f-4f2c-9251-2cea650c5e81.png)

**Keyman for All platform:**

**Comment by mcdurdin** [comment]
Thank you for this feature request. We are reviewing the OSK design in 16.0 and I am hopeful that some of these ideas can be incorporated into the new design.

**Comment by mcdurdin** [comment]
See also #2963
