### ISSUE TITLE
test(windows): Keyman for Windows 15.0 beta acceptance test

### ISSUE THREAD

**Issue by rc-swag** [keymanapp/keyman#6192]
# Keyman for Windows Acceptance Test Procedures #

1. These test procedures are to be run before moving from alpha to beta, or beta to stable, or before PRs are merged into stable branches.

2. Results are annotated with results, use `>` at the start of a new line under the checkbox/Test to note the result. 

# User Testing

## Gather Assets for Testing ##
- [x] Windows 7 (x86) - VM or physical okay
- [x] Windows 7 (x64) - VM or physical okay
- [x] Windows 8.1 (x64) - VM or physical okay
- [x] Windows 10 (x64) - VM or physical okay

## Setup Steps ##
- [x] Uninstall previous versions of Keyman Desktop and Keyman Developer on the system
- [x] Restart system, install updates
- [x] Make sure all additional Windows languages are removed
- [x] Make sure no debug flags are set in HKCU/Software/Keyman/Debug

## SUITE_INSPECT: Visual Inspection of master/beta branch
- TEST_CI_MASTER:  Verify latest CI build of master is successful 
- TEST_CI_BETA:  Verify latest CI build of beta is successful 
- TEST_VERIFY_HISTORY: Verify `/HISTORY.md` contains all the current changes

## TEST_INSTALL: 
- Install test build keyman-15.0.21?.exe
-  Make sure Keyman is started and visible in the Notification area

## TEST_KEYBOARD_INSTALLATION_REMOTE: 
- Start Keyman Configuration
- Click Download Keyboard, select a keyboard from the download dialogue and install it
- If the package includes a readme file, verify that it appears in the install window.
- If the package includes a welcome file, verify that it appears after installation.
- Click OK to close Keyman Configuration
- Start Notepad
- Verify that the newly installed keyboard appears in the Keyman menu and can be selected

## TEST_INSTALL_PKG_DISK: 
- Install a package from disk ##
- Locate a .kmp file on disk and double-click to install it
- If the package includes a readme file, verify that it appears in the install window.
- If the package includes a welcome file, verify that it appears after installation.
- Start Notepad
- Verify that the keyboard appears in the Keyman menu

## TEST_KEYBOARD_OUTPUT: 
- Start Notepad and select a Keyman keyboard (testing Legacy integration)
- Verify that various test sequences are output correctly
- Start Word or FiledWorks and select a Keyman keyboard (testing TSF integration)
- Verify that various test sequences are output correctly

## TEST_ON_SCREEN_KEYBOARD:
- Click Keyman icon in Notification area, select On Screen Keyboard
- Verify that OSK displays correctly for selected Keyman keyboard
- Verify that typing characters by clicking on OSK produces expected output

## TEST_WHATS_NEW:
- Refer to the new changes in `/HISTORY.md` and verify functionality

---
## TEST_CAPS_STORES 
- Run the tests found in [5803](https://github.com/keymanapp/keyman/pull/5803) also see [TestReame.md](https://github.com/keymanapp/keyman/blob/master/windows/src/test/manual-tests/caps-lock-stores/TestReadme.md)

`>` It Failed the `CapsLock` suite and the `CapsAlwaysOff` suite. Issue #6204 was raised and PR to fix it.

## TEST_TSF_APP
Type in-app that uses the windows TSF (MS Word, Fieldworks windows search field on the taskbar).

`>` This test failed initially with characters being output twice.   Issue #6205 was raised to address this.

## TEST_IMX_KEYBOARDS
 - Test IMX keyboards still work after core integration. see tests suite on #5936 and also #6187

**Comment by rc-swag** [comment]
## SUITE_INSPECT: Visual Inspection of master/beta branch
- TEST_CI_MASTER: pass
- TEST_CI_BETA: open
- TEST_VERIFY_HISTORY: open

## SUITE_BASELINE: Keyman for Windows Base Line Tests

### GROUP_WIN7_x86

## TEST_INSTALL: pass
## TEST_KEYBOARD_INSTALLATION_REMOTE: pass
## TEST_INSTALL_PKG_DISK: pass
## TEST_KEYBOARD_OUTPUT: pass
## TEST_ON_SCREEN_KEYBOARD: pass
## TEST_WHATS_NEW: open

### GROUP_WIN7_x64
## TEST_INSTALL: pass
## TEST_KEYBOARD_INSTALLATION_REMOTE: pass
## TEST_INSTALL_PKG_DISK: pass
## TEST_KEYBOARD_OUTPUT: pass
## TEST_ON_SCREEN_KEYBOARD: pass
## TEST_WHATS_NEW: open

### GROUP_WIN8_1
## TEST_INSTALL: pass
## TEST_KEYBOARD_INSTALLATION_REMOTE: pass
## TEST_INSTALL_PKG_DISK: pass
## TEST_KEYBOARD_OUTPUT: pass
## TEST_ON_SCREEN_KEYBOARD: pass
## TEST_WHATS_NEW: open

### GROUP_WIN10
## TEST_INSTALL: pass
## TEST_KEYBOARD_INSTALLATION_REMOTE: pass
## TEST_INSTALL_PKG_DISK: pass
## TEST_KEYBOARD_OUTPUT: pass
## TEST_ON_SCREEN_KEYBOARD: pass
## TEST_WHATS_NEW: open

**Comment by rc-swag** [comment]
*  GROUP_WIN10: 

  - **TEST_WHATS_NEW PASS**
  - **TEST_CAPS_STORES PASS**
  - **TEST_TSF_APP PASS**
  - **TEST_IMX_KEYBOARDS PASS**

**Comment by mcdurdin** [comment]
# Test Results

## SUITE_INSPECT: Visual Inspection of master/beta branch

* **TEST_CI_BETA (PASSED):** THis is Mchu much EASier than befoere

**Comment by rc-swag** [comment]
# Test Results

## SUITE_INSPECT: Visual Inspection of master/beta branch

* **TEST_CI_BETA: ** PASS

## SUITE_BASELINE: Keyman for Windows Base Line Tests

### GROUP_WIN7_x86: 

* **TEST_WHATS_NEW:** PASS
* **TEST_CAPS_STORES):** PASS
* **TEST_TSF_APP:** PASS


### GROUP_WIN7_x64: 

* **TEST_WHATS_NEW:** PASS
* **TEST_CAPS_STORES:** PASS
* **TEST_TSF_APP:** PASS


### GROUP_WIN8_1: 

* **TEST_WHATS_NEW:** PASS
* **TEST_CAPS_STORES:** PASS
* **TEST_TSF_APP:** PASS


### GROUP_WIN10: 

* **TEST_WHATS_NEW:** PASS
* **TEST_CAPS_STORES:** PASS
* **TEST_TSF_APP:** PASS

**Comment by rc-swag** [comment]
All acceptance tests have now passed
