### ISSUE TITLE
bug(linux): problems typing Khmer in LibreOffice Writer

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/keyman#6193]
With the Khmer Angkor keyboard, typing `xEjmr` should result in ខ្មែរ​. However, when typing this sequence in LibreOffice Writer 6.4 with Keyman 15, the result is ខ្មែរ, displayed in Writer is 

![Screenshot from 2022-02-22 19-07-31](https://user-images.githubusercontent.com/181336/155192805-09ba3d9e-db00-44e0-b664-776c30843293.png)

With Khmer Mondulkiri selected instead of the default font the display is correct:

![Screenshot from 2022-02-22 19-09-50](https://user-images.githubusercontent.com/181336/155193129-32aa4ba2-b44c-4580-9b99-804247a15f60.png)

**Keyman for Linux:**
 - OS: Ubuntu 20.04 Focal with X11
 - Keyman version: 15.0.186-alpha
 - Target Application: LibreOffice 6.4.7.2

**Keyboard**
 - Keyboard name: khmer_angkor
 - Keyboard version: 1.1
 - Language name: Khmer

**EDIT:** I initially typed the wrong characters (`kEjmr`) which showed wrong both with the correct and default fonts. After noticing this I updated this issue with the right characters. The settings mentioned in the comment below might still be helpful.

**Comment by rc-swag** [comment]
The changes to the Libre Office settings does not work for Windows 10. 
Windows 10 
LO version: 7.0.6.2 
However, it doesn't work in Notepad or Google Docs either.
kEjmr =>  ក្មែរ​
However 
xEjmr => ខ្មែរ 
which to me looks like the expected result detailed above.

**Comment by ermshiperete** [comment]
Thanks @rc-swag! Looks like I mixed up the characters to type :smile:
