### ISSUE TITLE
Unable to Add New Touch Inputs After Initialization

### ISSUE THREAD

**Issue by Sethyboy0** [keymanapp/keyman#62]
When using KeymanWeb on a touchscreen device, the keyboard will not work with inputs added to the page after KeymanWeb has initialized. Specifically, new inputs do not get the blocking element added to them that captures the touch event to open the keyboard.

My limited knowledge of web development tells me that automatically setting up the touch stuff on new inputs would not really be a feasible addition, but it would be useful to at least move the touch input initialization into functions that developers can call to add inputs on their own.

At my company I've had to work around this issue by adding the kmwInput property to my new inputs and rerunning the setupTouchDevice function.

Putting the existing touch input setup code blocks into functions doesn't seem too difficult and I may try to fix it myself if I find the time.

**Comment by jahorton** [comment]
Fixed with PR #77.
