### ISSUE TITLE
bug(android): Popup key is truncated in landscape orientation

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#6232]
Found during Acceptance Testing of 15.0.195-alpha

The default EuroLatin SIL keyboard popup key is truncated in landscape orientation.
(Note the popup looks like "v" when it should be "y")

![land osk](https://user-images.githubusercontent.com/7358010/153336508-3e2b5f55-a91f-43d8-9647-88514aaeeca3.jpg)

It seems to affect keys like "q", "y", "p"

Is this web or Android issue?

Workaround: Use the Settings -> Adjust Keyboard Height menu in landscape orientation to make the keyboard taller

**Comment by mcdurdin** [comment]
> Is this web or Android issue?

This would be an Android issue, but impacted by the thin keys in landscape mode.

**Comment by darcywong00** [comment]
For comparison on 15.0 Beta

| Popup                | US Basic | EuroLatin |
|-------------------|--------------|----------|
| <kbd>q</kbd> | ![q US Basic](https://user-images.githubusercontent.com/7358010/160527600-a7c7c169-43ae-423e-bac5-2b663ef459e0.png) | ![q EuroLatin](https://user-images.githubusercontent.com/7358010/160527612-dc18bc58-e142-4e9b-971f-187f4fb4d819.png) |

**Comment by darcywong00** [comment]
I wonder if the Typeface font is affect popup key scaling.

If I override EuroLatin to use SANS_SERIF (the fallback font applied to US Basic) 
```java
textView.setTypeface(Typeface.SANS_SERIF);
````

I get the following
![q EuroLatin SanSerif](https://user-images.githubusercontent.com/7358010/160557711-59b365fe-ed47-419b-816a-62c9920a584a.png)

**Comment by darcywong00** [comment]
I tried to bisect when this issue started happening
15.0.158-alpha the popup in landscape orientation was good
15.0.159-alpha that popup in landscape orientation gets clipped.

Alas, this is due to #5987 which fixes the KMEA font paths so that associated fonts are applied.

**Comment by darcywong00** [comment]
And it's not limited to popup keys. When I adjust the landscape OSK to the minimum height, I get this
![min landscape height](https://user-images.githubusercontent.com/7358010/160741213-17ca79fd-4794-4165-98a0-137a2ae7a79e.png)

**Comment by mcdurdin** [comment]
> And it's not limited to popup keys. When I adjust the landscape OSK to the minimum height, I get this

That's an unrelated issue.

**Comment by darcywong00** [comment]
Fixed by #6447
