### ISSUE TITLE
test(web): Web Acceptance Tests for 15.0 Beta

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#6235]
# Keyman for Web Acceptance Test Procedures #

1. These test procedures are to be run before moving from alpha to beta, or beta to stable, or before PRs are merged into stable branches.
2. Copy these lists of tests into a new issue (for tier transitions) or a comment on the PR.
3. Use User Testing format for documenting tests.

Remember that KeymanWeb is embedded into the iOS and Android apps, thus we need to ensure that those work properly with a KeymanWeb release as well.  See the Android and iOS instructions for details.

# User Testing

## SUITE_INSPECT: Visual Inspection of master branch

- **TEST_CI_WEB_MASTER:** ![Build Status](https://build.palaso.org/app/rest/builds/buildType:(id:Keymanweb_Build)/statusIcon) Verify latest CI build of [the KeymanWeb master](https://build.palaso.org/viewType.html?buildTypeId=Keymanweb_Build) is successful
- **TEST_CI_ANDROID_MASTER:** ![Build Status](https://build.palaso.org/app/rest/builds/buildType:(id:KeymanAndroid_Build)/statusIcon) Verify latest CI build of [the Android master](https://build.palaso.org/viewType.html?buildTypeId=KeymanAndroid_Build) is successful
- **TEST_CI_IOS_MASTER:** ![Build Status](https://build.palaso.org/app/rest/builds/buildType:(id:Keyman_iOS_Master)/statusIcon) Verify latest CI build of [the iOS master](https://build.palaso.org/viewType.html?buildTypeId=Keyman_iOS_Master) is successful
- **TEST_VERIFY_HISTORY:** Verify `web/history.md` contains information on all the current changes.

## SUITE_DESKTOP: Desktop Platforms

Ensure that all tests in the selections below are run on a representative set of the following browsers and setups:

* GROUP_WINDOWS_FIREFOX
* GROUP_WINDOWS_CHROME
* GROUP_MACOS_SAFARI
* GROUP_MACOS_CHROME
* GROUP_MACOS_FIREFOX
* GROUP_LINUX_FIREFOX

### Baseline Tests 

Use the `web/samples/minified.html` sample page for the following tests.

* **TEST_BASELINE_ADD_SIL_IPA:** Using the "Add a keyboard by keyboard name" section, add `sil_ipa`.
  - Ensure the key sequence <kbd>n</kbd><kbd>></kbd> produces `ŋ`.

* **TEST_BASELINE_ADD_KM:** Using the "Add a keyboard by BCP-47 language code" section, add `km`. A Khmer keyboard should be added (perhaps khmer_basic, but not necessarily).

* **TEST_BASELINE_ADD_KHMER_ANGKOR:** Using the "Add a keyboard by keyboard name" section, add `khmer_angkor`.
  - Ensure the key combination <kbd>Ctrl</kbd>+<kbd>Alt</kbd><kbd>B</kbd> produces `ឞ`. Delete the character again.
  - Type the following (US) keys in sequence: <kbd>s</kbd> <kbd>u</kbd> <kbd>j</kbd> <kbd>r</kbd> <kbd>k</kbd>. You should see `ស្រុក`.
  - Continuing from the last test, hit <kbd>Backspace</kbd>, checking each time to ensure the output is as expected.  As this is a reorder (keyboard) rule test, you should see:
    - `ស្រុ`
    - `ស្រ`
    - `ស្`
    - `ស`
    - empty text area.

* **TEST_BASELINE_ADD_SPANISH:** Using the "Add a keyboard by language name(s) section", add `spanish`. Verify that a Spanish keyboard is added to the list.

* **TEST_BASELINE_SWEDISH:** Swap to the Swedish keyboard.
  - Ensure the key sequence <kbd>'</kbd> <kbd>e</kbd> produces `é` and that <kbd>o</kbd> <kbd>\\</kbd> <kbd>e</kbd> produces `œ`.

### Text Selection Tests

These tests are all run with the **web_context_tests** keyboard, in the Unminified Test Page. They should be run on both INPUT and TEXTAREA elements. Press Ctrl+F5 to reload the page between tests.

* **TEST_SELECTION:** Type <kbd>a</kbd><kbd>b</kbd><kbd>c</kbd><kbd>x</kbd>. Select `bc` and type <kbd>q</kbd>. The output after the final key should be `aqx`. (This is testing selection replacement with no matching keyboard rule.)

* **TEST_SELECTION_2:** Type <kbd>a</kbd><kbd>b</kbd><kbd>c</kbd><kbd>x</kbd>. Select `bc` and type <kbd>p</kbd>. The output after the final key should be `aqx`. (This is testing selection replacement with a matching keyboard rule.)

* **TEST_CONTEXT_BASE:** Type <kbd>a</kbd><kbd>b</kbd><kbd>c</kbd><kbd>d</kbd>. The output after the final key should be `!`.

* **TEST_CONTEXT_SELECTION:** Type <kbd>a</kbd><kbd>b</kbd><kbd>c</kbd><kbd>x</kbd>. Select the `x` character, and type <kbd>d</kbd>. The output after the final key should be `abcd`.

* **TEST_CONTEXT_SELECTION_2:** Type <kbd>a</kbd><kbd>b</kbd><kbd>c</kbd><kbd>x</kbd>. Select the `x` character, and delete it with <kbd>Backspace</kbd>. Type <kbd>d</kbd>. The output after the final key should be `!`.

* **TEST_CONTEXT_SELECTION_3:** Type <kbd>a</kbd><kbd>b</kbd><kbd>c</kbd><kbd>x</kbd>. Select the `x` character, and type <kbd>y</kbd>. Press <kbd>Backspace</kbd>, and type <kbd>d</kbd>. The output after the final key should be `!`.

* **TEST_CONTEXT_SELECTION_4:** Type <kbd>x</kbd><kbd>a</kbd><kbd>b</kbd><kbd>c</kbd><kbd>x</kbd>. Select the `abc` characters, and type <kbd>d</kbd>. The output after the final key should be `xdx`.

### Element Attachment Tests

* **disabled_TEST_ATTACHMENT_API:** Utilize the `web/testing/attachment-api` samples page to ensure the following:
  - `'auto'` attachment mode properly and automatically attaches to each dynamically-added control.
  - `'manual'` attachment mode results in a page with no KMW-activated controls.
  - Each 'attached' control functions as expected for the keyboard(s) selected.
  - KeymanWeb properly attaches to and detaches from each relevant type of control with the page's API-interface controls.
  - Confirm that the independent-keyboard management API functions correctly.

## SUITE_TOUCH: Touch platform tests

Ensure that all tests in the selections below are run on a representative set of the following browsers and setups:

* GROUP_ANDROID_CHROME_TOUCH
* GROUP_ANDROID_CHROME_HARDWARE
* GROUP_IPHONE_SAFARI_TOUCH
* GROUP_IPHONE_SAFARI_HARDWARE
* GROUP_IPAD_SAFARI_TOUCH
* GROUP_IPAD_SAFARI_HARDWARE

### Baseline Tests 

Use the `web/samples/minified.html` sample page for the following tests.

* **TEST_BASELINE_ADD_SIL_IPA:** Using the "Add a keyboard by keyboard name" section, add `sil_ipa`.
  - For physical devices, ensure the key sequence <kbd>n</kbd><kbd>></kbd> produces `ŋ`.
  - For touch devices, <kbd>ŋ</kbd> should be a subkey of <kbd>n</kbd> - ensure it works.

* **TEST_BASELINE_ADD_KM:** Using the "Add a keyboard by BCP-47 language code" section, add `km`. A Khmer keyboard should be added (perhaps khmer_basic, but not necessarily).

* **TEST_BASELINE_ADD_KHMER_ANGKOR:** Using the "Add a keyboard by keyboard name" section, add `khmer_angkor`.
  - If using a physical keyboard, ensure the key combination <kbd>Ctrl</kbd>+<kbd>Alt</kbd><kbd>B</kbd> produces `ឞ`. Delete the character again.
  - Type in the following sequence on touch:  <kbd>ស</kbd> <kbd> ុ</kbd> <kbd> ្រ</kbd> (subkey of <kbd>រ</kbd>) <kbd>ក</kbd>.  You should see `ស្រុក`.
  - For physical devices, typing the following (US) keys in sequence: <kbd>s</kbd> <kbd>u</kbd> <kbd>j</kbd> <kbd>r</kbd> <kbd>k</kbd>. You should see `ស្រុក`.
  - Continuing from the last test, hit <kbd>Backspace</kbd>, checking each time to ensure the output is as expected.  As this is a reorder (keyboard) rule test, you should see:
    - `ស្រុ`
    - `ស្រ`
    - `ស`
    - empty text area.

* **TEST_BASELINE_ADD_SPANISH:** Using the "Add a keyboard by language name(s) section", add `spanish`. Verify that a Spanish keyboard is added to the list.

* **TEST_BASELINE_SWEDISH:** Swap to the Swedish keyboard.
  - If using a physical keyboard, ensure the key sequence <kbd>'</kbd> <kbd>e</kbd> produces `é` and that <kbd>o</kbd> <kbd>\\</kbd> <kbd>e</kbd> produces `œ`.
  - If using a touch-based keyboard, use long-press <kbd>.</kbd> to output <kbd>'</kbd> and then press <kbd>e</kbd>.  The two characters should not combine.
  - If using a touch-based keyboard, ensure that long-press <kbd>p</kbd> and long-press <kbd>G</kbd> displays properly and that the subkeys produce the expected output.

* **TEST_BASELINE_CAMEROON:** If using a touch-based keyboard, add the following keyboard by name:  "sil_cameroon_qwerty"
  - Ensure the top two rows of the symbol layer work correctly.  (These have unusual 'layer' settings.)
  - Ensure that the tri-color key (on both 'default' and 'shift' layers) changes layer appropriately and that keys pressed automatically transition back to the default layer.  (The 'default' layer's variant is very unusual, as it matches a keyboard rule and changes layer, but doesn't generate direct output!)
  - Test that a subkey on the 'default' and on the 'shift' layers output the expected character.

### Element Attachment Tests

* **disabled_TEST_ATTACHMENT_API:** Utilize the `web/testing/attachment-api` samples page to ensure the following:
  - `'auto'` attachment mode properly and automatically attaches to each dynamically-added control.
  - `'manual'` attachment mode results in a page with no KMW-activated controls.
  - Each 'attached' control functions as expected for the keyboard(s) selected.
  - KeymanWeb properly attaches to and detaches from each relevant type of control with the page's API-interface controls.
  - Confirm that the independent-keyboard management API functions correctly.

**Comment by mcdurdin** [comment]
# Test Results

## SUITE_INSPECT: Visual Inspection of master branch

* **TEST_CI_WEB_MASTER (PASSED)** 
* **TEST_CI_ANDROID_MASTER (PASSED)** 
* **TEST_CI_IOS_MASTER (PASSED)** 
* **TEST_VERIFY_HISTORY (PASSED)**

## SUITE_DESKTOP: Desktop Platforms

### GROUP_WINDOWS_FIREFOX: 

* **TEST_BASELINE_ADD_SIL_IPA (PASSED)** 
* **TEST_BASELINE_ADD_KM (PASSED)**
* **TEST_BASELINE_ADD_KHMER_ANGKOR (PASSED)**
* **TEST_BASELINE_ADD_SPANISH (PASSED)**
* **TEST_BASELINE_SWEDISH (PASSED)**
* **TEST_SELECTION (PASSED)**
* **TEST_SELECTION_2 (PASSED)**
* **TEST_CONTEXT_BASE (PASSED)**
* **TEST_CONTEXT_SELECTION (PASSED)**
* **TEST_CONTEXT_SELECTION_2 (PASSED)**
* **TEST_CONTEXT_SELECTION_3 (PASSED)**
* **TEST_CONTEXT_SELECTION_4 (PASSED)**

### GROUP_WINDOWS_CHROME: 

* **TEST_BASELINE_ADD_SIL_IPA (PASSED)** 
* **TEST_BASELINE_ADD_KM (PASSED)**
* **TEST_BASELINE_ADD_KHMER_ANGKOR (PASSED)**
* **TEST_BASELINE_ADD_SPANISH (PASSED)**
* **TEST_BASELINE_SWEDISH (PASSED)**
* **TEST_SELECTION (PASSED)**
* **TEST_SELECTION_2 (PASSED)**
* **TEST_CONTEXT_BASE (PASSED)**
* **TEST_CONTEXT_SELECTION (PASSED)**
* **TEST_CONTEXT_SELECTION_2 (PASSED)**
* **TEST_CONTEXT_SELECTION_3 (PASSED)**
* **TEST_CONTEXT_SELECTION_4 (PASSED)**

**Comment by mcdurdin** [comment]
# Test Results

## SUITE_DESKTOP: Desktop Platforms

### GROUP_MACOS_SAFARI: 

Safari 14.1.2 on macOS Big Sur 11.6 (M1)

* **TEST_BASELINE_ADD_SIL_IPA (PASSED)**
* **TEST_BASELINE_ADD_KM (PASSED)**
* **TEST_BASELINE_ADD_KHMER_ANGKOR (PASSED)**
* **TEST_BASELINE_ADD_SPANISH (PASSED)**
* **TEST_BASELINE_SWEDISH (PASSED)**
* **TEST_SELECTION (PASSED)**
* **TEST_SELECTION_2 (PASSED)**
* **TEST_CONTEXT_BASE (PASSED)**
* **TEST_CONTEXT_SELECTION (PASSED)**
* **TEST_CONTEXT_SELECTION_2 (PASSED)**
* **TEST_CONTEXT_SELECTION_3 (PASSED)**
* **TEST_CONTEXT_SELECTION_4 (PASSED)**

### GROUP_MACOS_CHROME: 

Chrome 99.0.4844.51 (arm64) on macOS Big Sur 11.6 (M1)

* **TEST_BASELINE_ADD_SIL_IPA (PASSED)**
* **TEST_BASELINE_ADD_KM (PASSED)**
* **TEST_BASELINE_ADD_KHMER_ANGKOR (PASSED)**
* **TEST_BASELINE_ADD_SPANISH (PASSED)**
* **TEST_BASELINE_SWEDISH (PASSED)**
* **TEST_SELECTION (PASSED)**
* **TEST_SELECTION_2 (PASSED)**
* **TEST_CONTEXT_BASE (PASSED)**
* **TEST_CONTEXT_SELECTION (PASSED)**
* **TEST_CONTEXT_SELECTION_2 (PASSED)**
* **TEST_CONTEXT_SELECTION_3 (PASSED)**
* **TEST_CONTEXT_SELECTION_4 (PASSED)**

### GROUP_MACOS_FIREFOX: 

Firefox 97.0.2 (64-bit) on macOS Big Sur 11.6 (M1)

* **TEST_BASELINE_ADD_SIL_IPA (PASSED)**
* **TEST_BASELINE_ADD_KM (PASSED)**
* **TEST_BASELINE_ADD_KHMER_ANGKOR (PASSED)**
* **TEST_BASELINE_ADD_SPANISH (PASSED)**
* **TEST_BASELINE_SWEDISH (PASSED)**
* **TEST_SELECTION (PASSED)**
* **TEST_SELECTION_2 (PASSED)**
* **TEST_CONTEXT_BASE (PASSED)**
* **TEST_CONTEXT_SELECTION (PASSED)**
* **TEST_CONTEXT_SELECTION_2 (PASSED)**
* **TEST_CONTEXT_SELECTION_3 (PASSED)**
* **TEST_CONTEXT_SELECTION_4 (PASSED)**

**Comment by mcdurdin** [comment]
# Test Results

## SUITE_DESKTOP: Desktop Platforms

Firefox 95.0.1 (64-bit) on Ubuntu 20.04 x64

### GROUP_LINUX_FIREFOX: 

* **TEST_BASELINE_ADD_SIL_IPA (PASSED)**
* **TEST_BASELINE_ADD_KM (PASSED)**
* **TEST_BASELINE_ADD_KHMER_ANGKOR (PASSED)**
* **TEST_BASELINE_ADD_SPANISH (PASSED)**
* **TEST_BASELINE_SWEDISH (PASSED)**
* **TEST_SELECTION (PASSED)**
* **TEST_SELECTION_2 (PASSED)**
* **TEST_CONTEXT_BASE (PASSED)**
* **TEST_CONTEXT_SELECTION (PASSED)**
* **TEST_CONTEXT_SELECTION_2 (PASSED)**
* **TEST_CONTEXT_SELECTION_3 (PASSED)**
* **TEST_CONTEXT_SELECTION_4 (PASSED)**

**Comment by bharanidharanj** [comment]
## SUITE_TOUCH: Touch platform tests

### GROUP_ANDROID_CHROME_TOUCH: 

* **TEST_BASELINE_ADD_SIL_IPA (PASSED):** Tested this in Android API 29 and it is working as expected. 
* **TEST_BASELINE_ADD_KM (PASSED):** Tested this in Android API 29 and it is working as expected.
* **TEST_BASELINE_ADD_KHMER_ANGKOR (PASSED):** Tested this in Android API 29 and it is working as expected.
* **TEST_BASELINE_ADD_SPANISH (PASSED):** Tested this in Android API 29 and it is working as expected.
* **TEST_BASELINE_SWEDISH (PASSED):** Tested this in Android API 29 and it is working as expected.
* **TEST_BASELINE_CAMEROON (PASSED):** Tested this in Android API 29 and it is working as expected.

**Comment by bharanidharanj** [comment]
## SUITE_TOUCH: Touch platform tests

### GROUP_ANDROID_CHROME_HARDWARE: 

* **TEST_BASELINE_ADD_SIL_IPA (PASSED):** Tested this in Android Phone Version 11.0 and it is working as expected. 
* **TEST_BASELINE_ADD_KM (PASSED):** Tested this in Android Phone Version 11.0 and it is working as expected. 
* **TEST_BASELINE_ADD_KHMER_ANGKOR (PASSED):** Tested this in Android Phone Version 11.0 and it is working as expected. 
* **TEST_BASELINE_ADD_SPANISH (PASSED):** Tested this in Android Phone Version 11.0 and it is working as expected. 
* **TEST_BASELINE_SWEDISH (PASSED):** Tested this in Android Phone Version 11.0 and it is working as expected. 
* **TEST_BASELINE_CAMEROON (PASSED):** Tested this in Android Phone Version 11.0 and it is working as expected.

**Comment by MakaraSok** [comment]
SUITE_TOUCH: Touch platform tests
TEST_BASELINE_ADD_KHMER_ANGKOR: (FAILED) Something is weird with the longpress which overlaps another key, the output would be the character for the subkey and the character of the basekey on which the subkey is shown above.


https://user-images.githubusercontent.com/28331388/157393968-d55aed7b-13b8-4fdf-8fc3-bdf7c0b7918d.mov

**Comment by MakaraSok** [comment]
# Test Results

## SUITE_TOUCH: Touch platform tests

### GROUP_IPHONE_SAFARI_HARDWARE: 

All tests done using `https://build.palaso.org/repository/download/Keymanweb_TestPullRequests/309863:id/samples/minified.html` on Safari on iPod touch (7th gen.).

* **TEST_BASELINE_ADD_SIL_IPA (PASSED):** `ŋ` is on the subkey of `n` and it indeed outputs the expected character.
* **TEST_BASELINE_ADD_KM (PASSED):** "khmer_basic" got installed as expected.
* **TEST_BASELINE_ADD_KHMER_ANGKOR (FAILED):** The longpress doesn't output the expected character. There is no highlighted selection when rolling the finger over to the subkey.
* **TEST_BASELINE_ADD_SPANISH (PASSED):** The `spanish` keyboard does get added.
* **TEST_BASELINE_SWEDISH (FAILED):** The longpress doesn't output the expected character. There is no highlighted selection when rolling the finger over to the subkey.
* **TEST_BASELINE_CAMEROON (FAILED):** The longpress doesn't output the expected character. There is no highlighted selection when rolling the finger over to the subkey.

### GROUP_IPAD_SAFARI_HARDWARE: 

All tests done using `https://build.palaso.org/repository/download/Keymanweb_TestPullRequests/309863:id/samples/minified.html` on Safari on iPad 6 mini.

* **TEST_BASELINE_ADD_SIL_IPA (PASSED):** `ŋ` is on the subkey of `n` and it indeed outputs the expected character.
* **TEST_BASELINE_ADD_KM (PASSED):** "khmer_basic" got installed as expected.
* **TEST_BASELINE_ADD_KHMER_ANGKOR (PASSED):** Everything works as expected.
* **TEST_BASELINE_ADD_SPANISH (PASSED):** The `spanish` keyboard does get added.
* **TEST_BASELINE_SWEDISH (PASSED):** Everything works as expected.
* **TEST_BASELINE_CAMEROON (PASSED):** Everything works as expected.

**Comment by bharanidharanj** [comment]
## SUITE_TOUCH: Touch platform tests

### GROUP_IPHONE_SAFARI_TOUCH: 

* **TEST_BASELINE_ADD_SIL_IPA (PASSED):** Tested this in iphone 13 Pro emulator and it is showing the expected character ŋ.
* **TEST_BASELINE_ADD_KM (PASSED):** Tested this in iPhone 13 Pro emulator and it is working as expected.
* **TEST_BASELINE_ADD_KHMER_ANGKOR (FAILED):** The Output Character has been changed for the 3rd time, when I hit enter. I need to give two more hits to empty the text area. Seems to be an issue in iPhone 13 Pro Emulator. Attached the Screenshot for reference.

<img width="300" src="https://user-images.githubusercontent.com/19683143/157453268-6d242e97-8f1a-40c0-8c1e-6b9f63cc9623.png"> 

* **TEST_BASELINE_ADD_SPANISH (PASSED):** Tested this in iPhone 13 Pro emulator and it is working as expected.
* **TEST_BASELINE_SWEDISH (PASSED):** Tested this in iPhone 13 Pro emulator and it is working as expected.
* **TEST_BASELINE_CAMEROON (PASSED):** Tested this in iPhone 13 Pro emulator and it is working as expected.

**Comment by mcdurdin** [comment]
> * **TEST_BASELINE_SWEDISH (FAILED):** The longpress doesn't output the expected character. There is no highlighted selection when rolling the finger over to the subkey.
> * **TEST_BASELINE_CAMEROON (FAILED):** The longpress doesn't output the expected character. There is no highlighted selection when rolling the finger over to the subkey.

@MakaraSok Are these related to #6340?

**Comment by MakaraSok** [comment]
> > * **TEST_BASELINE_SWEDISH (FAILED):** The longpress doesn't output the expected character. There is no highlighted selection when rolling the finger over to the subkey.
> > * **TEST_BASELINE_CAMEROON (FAILED):** The longpress doesn't output the expected character. There is no highlighted selection when rolling the finger over to the subkey.
> 
> @MakaraSok Are these related to #6340?

The behavior seems similar, but not the same. No matter where the thump roll, the subkey doesn't get selected/highlighted at all. Nothing is output either.

https://user-images.githubusercontent.com/28331388/157585020-086a1271-b116-4f84-b6fd-c42f7b50e586.mov

**Comment by MakaraSok** [comment]
# Test Results

## SUITE_TOUCH: Touch platform tests

### GROUP_IPAD_SAFARI_TOUCH: 

* **TEST_BASELINE_ADD_SIL_IPA (PASSED):**
* **TEST_BASELINE_ADD_KM (PASSED):**
* **TEST_BASELINE_ADD_KHMER_ANGKOR (PASSED):**
* **TEST_BASELINE_ADD_SPANISH (PASSED):**
* **TEST_BASELINE_SWEDISH (PASSED):**
* **TEST_BASELINE_CAMEROON (PASSED):**

**Comment by mcdurdin** [comment]
> The behavior seems similar, but not the same. No matter where the thump roll, the subkey doesn't get selected/highlighted at all. Nothing is output either.

Are you able to re-test with KeymanWeb from https://github.com/keymanapp/keyman/pull/6357?

@keymanapp-test-bot retest SUITE_TOUCH GROUP_IPHONE_SAFARI_HARDWARE TEST_BASELINE_SWEDISH TEST_BASELINE_CAMEROON

**Comment by mcdurdin** [comment]
> ### GROUP_ANDROID_CHROME_TOUCH
> * TEST_BASELINE_ADD_KHMER_ANGKOR: (FAILED) Something is weird with the longpress which overlaps another key, the output would be the character for the subkey and the character of the basekey on which the subkey is shown above. (tested on Pixel 4, API 30, Chrome 98.0.4758.101)

I am unable to reproduce this. Can you retest this one with the latest KeymanWeb?

@keymanapp-test-bot retest SUITE_TOUCH GROUP_ANDROID_CHROME_TOUCH TEST_BASELINE_ADD_KHMER_ANGKOR

**Comment by mcdurdin** [comment]
> GROUP_IPHONE_SAFARI_TOUCH:
> TEST_BASELINE_ADD_KHMER_ANGKOR (FAILED): The Output Character has been changed for the 3rd time, when I hit Backspace Key. I need to give two more hits to empty the text area. Seems to be an issue in iPhone 13 Pro Emulator. Attached the Screenshot for reference.

@bharanidharanj: This looks like you might have pressed the backspace key on the hardware keyboard, rather than the backspace key on the touch keyboard. The backspace key on the hardware keyboard will have slightly different behaviour (by design) with the Khmer Angkor keyboard when deleting subconsonant marks such as ្រ:

* Hardware keyboard will require two backspaces, because input is <kbd>j</kbd><kbd>r</kbd> (two keystrokes).
* Touch keyboard will require one backspace, because input is via longpress on <kbd>រ</kbd> (one keystroke).

@keymanapp-test-bot retest SUITE_TOUCH GROUP_IPHONE_SAFARI_TOUCH TEST_BASELINE_ADD_KHMER_ANGKOR

**Comment by bharanidharanj** [comment]
## SUITE_TOUCH: Touch platform tests

### GROUP_ANDROID_CHROME_TOUCH: 

* **TEST_BASELINE_ADD_KHMER_ANGKOR (PASSED):** Tested this issue 

> > GROUP_IPHONE_SAFARI_TOUCH:
> > TEST_BASELINE_ADD_KHMER_ANGKOR (FAILED): The Output Character has been changed for the 3rd time, when I hit Backspace Key. I need to give two more hits to empty the text area. Seems to be an issue in iPhone 13 Pro Emulator. Attached the Screenshot for reference.
> 
> @bharanidharanj: This looks like you might have pressed the backspace key on the hardware keyboard, rather than the backspace key on the touch keyboard. The backspace key on the hardware keyboard will have slightly different behaviour (by design) with the Khmer Angkor keyboard when deleting subconsonant marks such as ្រ:
> 
>     * Hardware keyboard will require two backspaces, because input is jr (two keystrokes).
> 
>     * Touch keyboard will require one backspace, because input is via longpress on រ (one keystroke).
> 
> 
> @keymanapp-test-bot retest SUITE_TOUCH GROUP_IPHONE_SAFARI_TOUCH TEST_BASELINE_ADD_KHMER_ANGKOR

@mcdurdin Okay, Thanks for the Clarification.

**Comment by bharanidharanj** [comment]
> ## SUITE_TOUCH: Touch platform tests
> ### GROUP_ANDROID_CHROME_TOUCH:
> 
>     * **TEST_BASELINE_ADD_KHMER_ANGKOR (PASSED):** Tested this issue
> 
> 
> > > GROUP_IPHONE_SAFARI_TOUCH:
> > > TEST_BASELINE_ADD_KHMER_ANGKOR (FAILED): The Output Character has been changed for the 3rd time, when I hit Backspace Key. I need to give two more hits to empty the text area. Seems to be an issue in iPhone 13 Pro Emulator. Attached the Screenshot for reference.
> > 
> > 
> > @bharanidharanj: This looks like you might have pressed the backspace key on the hardware keyboard, rather than the backspace key on the touch keyboard. The backspace key on the hardware keyboard will have slightly different behaviour (by design) with the Khmer Angkor keyboard when deleting subconsonant marks such as ្រ:
> > ```
> > * Hardware keyboard will require two backspaces, because input is jr (two keystrokes).
> > 
> > * Touch keyboard will require one backspace, because input is via longpress on រ (one keystroke).
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @keymanapp-test-bot retest SUITE_TOUCH GROUP_IPHONE_SAFARI_TOUCH TEST_BASELINE_ADD_KHMER_ANGKOR
> 
> @mcdurdin Okay, Thanks for the Clarification.



> > GROUP_IPHONE_SAFARI_TOUCH:
> > TEST_BASELINE_ADD_KHMER_ANGKOR (FAILED): The Output Character has been changed for the 3rd time, when I hit Backspace Key. I need to give two more hits to empty the text area. Seems to be an issue in iPhone 13 Pro Emulator. Attached the Screenshot for reference.
> 
> @bharanidharanj: This looks like you might have pressed the backspace key on the hardware keyboard, rather than the backspace key on the touch keyboard. The backspace key on the hardware keyboard will have slightly different behaviour (by design) with the Khmer Angkor keyboard when deleting subconsonant marks such as ្រ:
> 
>     * Hardware keyboard will require two backspaces, because input is jr (two keystrokes).
> 
>     * Touch keyboard will require one backspace, because input is via longpress on រ (one keystroke).
> 
> 
> @keymanapp-test-bot retest SUITE_TOUCH GROUP_IPHONE_SAFARI_TOUCH TEST_BASELINE_ADD_KHMER_ANGKOR

@mcdurdin Okay, Thanks for the Clarification.

**Comment by bharanidharanj** [comment]
> > GROUP_IPHONE_SAFARI_TOUCH:
> > TEST_BASELINE_ADD_KHMER_ANGKOR (FAILED): The Output Character has been changed for the 3rd time, when I hit Backspace Key. I need to give two more hits to empty the text area. Seems to be an issue in iPhone 13 Pro Emulator. Attached the Screenshot for reference.
> 
> @bharanidharanj: This looks like you might have pressed the backspace key on the hardware keyboard, rather than the backspace key on the touch keyboard. The backspace key on the hardware keyboard will have slightly different behaviour (by design) with the Khmer Angkor keyboard when deleting subconsonant marks such as ្រ:
> 
>     * Hardware keyboard will require two backspaces, because input is jr (two keystrokes).
> 
>     * Touch keyboard will require one backspace, because input is via longpress on រ (one keystroke).
> 
> 
> @keymanapp-test-bot retest SUITE_TOUCH GROUP_IPHONE_SAFARI_TOUCH TEST_BASELINE_ADD_KHMER_ANGKOR

@mcdurdin Okay, Thanks for the Clarification.

**Comment by bharanidharanj** [comment]
## SUITE_TOUCH: Touch platform tests

### GROUP_ANDROID_CHROME_TOUCH: 

* **TEST_BASELINE_ADD_KHMER_ANGKOR (PASSED):** Tested this in both Android emulator (API 29) and the Mobile device and it is working as expected. 

In Android API 29 Emulator:
<img width="300" src="https://user-images.githubusercontent.com/19683143/159669886-d77ee497-18af-4988-ab4f-92e955c80513.PNG">

In Android Mobile (Version 11):
<img width="300" src="https://user-images.githubusercontent.com/19683143/159669928-f367b8b9-38a0-437d-8d0e-2e07628a8e9e.jpg">

**Comment by bharanidharanj** [comment]
## SUITE_TOUCH: Touch platform tests

### GROUP_IPHONE_SAFARI_TOUCH: 

* **TEST_BASELINE_ADD_KHMER_ANGKOR (PASSED):** Tested this on iPhone 13 Pro Simulator in Minified Source view and it seems to be working fine. 

Minified Page:
<img width="300" src="https://user-images.githubusercontent.com/19683143/159676590-16e59e9a-7361-42a6-855d-de4a26195fa8.png">

**Comment by MakaraSok** [comment]
# Test Results

## SUITE_TOUCH: Touch platform tests

### GROUP_IPHONE_SAFARI_HARDWARE: 

Tested at https://downloads.keyman.com/web/beta/15.0.220/static/samples/ on iPod Touch 7th gen. running iOS 15.3.1

* **TEST_BASELINE_ADD_KHMER_ANGKOR (PASSED):** The OSK behaves as expected when the address bar shown at the bottom is hidden, otherwise the page would roll down making it impossible to type the subkeys.

address bar shown - subkeys not working
<img width="150" src="https://user-images.githubusercontent.com/28331388/159866119-672494a5-17dd-42ce-9aa4-30e7552b7ca7.png">


address bar hidden - subkeys working
<img width="150" src="https://user-images.githubusercontent.com/28331388/159866640-343471b9-360f-468a-a872-1188806225cd.png">


* **TEST_BASELINE_SWEDISH (FAILED):** the key sequences don't output the expected characters.
* **TEST_BASELINE_CAMEROON (PASSED):** Things work as expected including the weirdness on the tri-color button layers on the Default and Shift layers.

**Comment by mcdurdin** [comment]
# Test Results

## SUITE_TOUCH: Touch platform tests

### GROUP_IPHONE_SAFARI_HARDWARE: 

* **TEST_BASELINE_SWEDISH (PASSED):** I tested against 15.0.223-beta and the hardware key sequences `'e` and `o\\e` worked fine. Did you check the right sequences?
