### ISSUE TITLE
bug(android/engine): OSK not rendering on Gondi keyboard 

### ISSUE THREAD

**Issue by hinditutorpoint** [keymanapp/keyman#6252]
Hi there
i have an issue with android library on keyboard button did not show font on key
![Screenshot_20220213-022128_Gondi Darshan Lite](https://user-images.githubusercontent.com/42866845/153728123-93617e99-bc93-4af0-af40-bbd5f78a9904.jpg)

android os 8.0 oreo

**Comment by mcdurdin** [comment]
@darcywong00 can you assist?

**Comment by darcywong00** [comment]
Hello @hinditutorpoint - Are you using the Keyman Engine for Android library in your own keyboard app, or is that what you're experiencing in the Keyman for Android app after installing Masaram Gondi keyboard?

This is what I get in an Android 8.1 emulator with the latest Keyman for Android (14.0.286 stable)
![Screenshot_20220213_153319](https://user-images.githubusercontent.com/7358010/153745530-d151e403-8d69-4532-ab30-7881c1fec5c8.png)

**Comment by hinditutorpoint** [comment]
hi team my problem not solve please guide how fixed this issue

**Comment by darcywong00** [comment]
Hi
Can you tell me what version of Keyman Engine for Android (keyman-engine.aar) you're using in your app?
We recommend the latest build:
https://downloads.keyman.com/android/stable/14.0.286/keyman-engine-android-14.0.286.zip

because it includes a fix to the font paths in pull request #5990

**Comment by hinditutorpoint** [comment]
@darcywong00 thanks for reply
I tested alpha and stable version both of these but didn't not work if you see my code I will do commit GitHub

**Comment by hinditutorpoint** [comment]
Latest stable 14.0.286

**Comment by darcywong00** [comment]
> if you see my code I will do commit GitHub

Can you tell us the link to your GitHub project that's using Keyman Engine for Android and the masaram_gondi keyboard?

**Comment by hinditutorpoint** [comment]
hi @darcywong00 thanks for replying
just see my code copy paste from demo app with our requirement modification
https://github.com/hinditutorpoint/masaramgondiandroidkeyboard/blob/main/SystemKeyboard.java

**Comment by darcywong00** [comment]
The font file included in the masaram_gondi.kmp keyboard package is named
`NotoSansMasaramGondi-Regular.ttf` (note the capitals letters and the hyphen in the name). Keyman Engine for Android needs to find the matching font file in order to apply it.

If your update the font names in your SystemKeyboard.java files, it should work.
https://github.com/hinditutorpoint/masaramgondiandroidkeyboard/blob/badc4c9d66c6971426f225aaf5e0e8d654ddb19d/SystemKeyboard.java#L53-L54

**Comment by darcywong00** [comment]
@hinditutorpoint - Is this still an issue for you after updating the font name?

**Comment by hinditutorpoint** [comment]
@darcywong00 many many thank now work perfect 
have another question how to add multiple keyboard

**Comment by darcywong00** [comment]
Does your keyboard package already have multiple keyboards in it?
Here's the guide for creating a keyboard package
https://help.keyman.com/developer/14.0/guides/distribute/tutorial/

In "Step 3", you'll add the multiple keyboards to the package. Make sure to also assign languages for each keyboard you add (along with associated font info).

Then in your app, you can update `kbInfo` for each keyboard and then ` KMManager.addKeyboard(this, kbInfo);`

I'll go ahead and close this issue. If you have additional questions, post them on the community forum
https://community.software.sil.org/c/keyman/19
