### ISSUE TITLE
chore(android): jcenter removal

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#6265]
Per build:

```
WARNING:: Please remove usages of `jcenter()` Maven repository from your build scripts and migrate your build to other Maven repositories.
This repository is deprecated and it will be shut down in the future.
See http://developer.android.com/r/tools/jcenter-end-of-service for more information.
Currently detected usages in: root project 'KMAPro', project ':kMAPro'
```

**Comment by darcywong00** [comment]
We're using an unmaintained dependency material-stepper (UI to step the user through package installation). It's only hosted on jcenter. 

The blog post says jcenter will be kept as a read-only repository indefinitely
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
