### ISSUE TITLE
bug(linux): Keyman Keyboard does not show up on the Taskbar after successfully installed in a Clean machine

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#6277]
**Description**
Keyman Keyboard does not show up on the Task bar after installing it

**Expected behavior**
The Keyman Keyboard should appears on the Taskbar after installing it.

**Screenshots**

 <img width="300" src="https://user-images.githubusercontent.com/19683143/155130462-d9fb1141-9b99-462a-8349-a4c7acc8e104.PNG"> 

<img width="300" src="https://user-images.githubusercontent.com/19683143/155130608-a165ee13-86e4-49d2-8ae5-6c9d08393bfc.PNG"> 

**Keyman for Linux:**
 - OS: Ubuntu 20.04 Focal Linux
 - Keyman version: Keyman 14.0.286
 - Target Application: Taskbar

**Note**
This happens when I install Keyman for the first time in a Clean machine.

**Comment by ermshiperete** [comment]
Yes, this is a known bug in v14 which is fixed in Keyman 15 (see #6109).

**Comment by bharanidharanj** [comment]
> Yes, this is a known bug in v14 which is fixed in Keyman 15 (see #6109).

@ermshiperete Oh Okay. Thanks.
