### ISSUE TITLE
feat(linux): Display error messages in the UI

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/keyman#6288]
Currently when we encounter an error when installing a keyboard, we use `logging.error` to output a message to the command line. Depending on how the user started `km-config` he might not be able to see these errors.

We should implement a way to display these errors in a message box.

**Comment by darcywong00** [comment]
We'd also want these error strings localizable in the .po files

**Comment by ermshiperete** [comment]
We already display a message box in `install_window.py`, but need to do it in other places as well.
