### ISSUE TITLE
[Android] KMP not installing with Samsung "My Files" browser

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#629]
User reports during a demo that the intent for KMP wasn't triggering Keyman to install the keyboard.

From logcat, the system intent can't find an activity to handle Intent ` {
act=android.intent.action.VIEW dat=content://0@media/external/file/XYZ }`

Configuration: Keyman Android 10.0.10000058
Android 6.x
Filebrowser: My Files

Issue also on Android 7.0 with "My Files" browser. The KMP does install via  another file browser (Amaze)

**Comment by darcywong00** [comment]
The KMP can be installed from Chrome Downloads. Just not the default "My Files" browser

**Comment by darcywong00** [comment]
Found 1 configuration that worked

### Configuration
Keyman 10.0.383 Beta
Samsung Galaxy J1
Android: 4.4.4
My Files: 1.0

**Comment by darcywong00** [comment]
See about posting feature request/feedback to Samsung

**Comment by mcdurdin** [comment]
See also #1722

**Comment by darcywong00** [comment]
Fixed by #2030 in master
