### ISSUE TITLE
bug(android): installing a package may not overwrite existing package

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#6292]
**Describe the bug**

If you make a change to a package, but don't change its version number, it can fail to install the newer version.

**To Reproduce**

1. Create a keyboard + package in Keyman Developer.
2. Install the package on Keyman for Android, test it.
3. Make a change to the keyboard and rebuild it in Developer.
4. Uninstall the package on Keyman for Android.
5. Install the updated package on Keyman for Android.
6. Observe that the new keyboard rules are not available.

---

**Keyman for iPhone/iPad/Android:**
 - Device: Android 
 - Keyman version: 15.0-alpha

**Comment by darcywong00** [comment]
I think this is due to some of the design decisions we had in kmp package installation and "uninstalling" a keyboard.

1. When a keyboard is "uninstalled", the extracted package files are left behind in the filesystem
2. When installing a kmp package, the versions of the "new" package are compared to what's already on the filesystem, and it needs to be newer to install.

**Comment by rc-swag** [comment]
I observed this but at step 5 ^^. I changed the system board back to gboard then back to keyman again. After this it observed the new keybaord rules. So yes prehaps it needs to some how refresh a cache somewhere.

**Comment by mcdurdin** [comment]
Righto. That reduces the scope. Sounds like just need to trigger a reload of the WebView to cleanse its keyboard list. It may be even that switching to another Keyman keyboard and back is enough to resolve things?

**Comment by mcdurdin** [comment]
I'm suggesting we triage this to Future given it is of limited severity at present? Although I guess it may impact keyboard developers in an unfriendly way... What do you think @darcywong00?

**Comment by darcywong00** [comment]
I can try B16S6 - I don't think the KMP fileversion check will take a whole week

**Comment by darcywong00** [comment]
Fixed by #6438
