### ISSUE TITLE
moveToNext Function Does Not Check For Existence of Next Input

### ISSUE THREAD

**Issue by Sethyboy0** [keymanapp/keyman#63]
The moveToNext function in keymanweb.js never actually checks if the target it wants to focus on exists or not, causing errors when it doesn't. I've seen this come up in my implementation for my employer where moveToNext is called and no other inputs exist on the page.

**Comment by jahorton** [comment]
Could you give some example code where this is the case?

Also, in the above-mentioned implementation for your employer, does the number of inputs change over the lifetime of your page?  If so, I suspect that's highly related.

**Comment by Sethyboy0** [comment]
In the employer's implementation, the only input on the page that is
enabled for KeymanWeb is frequently deleted from and re-added to the page.
There should only be one input at time, and the deletion and addition are
spaced out enough that they shouldn't cause any overlap.

Unfortunately I've finished my co-op term and am back on a new school term,
making it more difficult to get some example code made. I'll see if I can
find some time.

**Comment by jahorton** [comment]
Fixed with PR #80, as the issue was highly related to dynamic element removal.
