### ISSUE TITLE
bug(macos): configuration doesn't open in the latest beta

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#6328]
**Describe the bug**

https://user-images.githubusercontent.com/28331388/156489169-ddb2cb1e-83e3-4b9d-b067-62df5dae2660.mov

**Expected behavior**

The configuration should be opened when summoned via the dropdown menu and the about window.

---

**Keyman for macOS:**
 - OS: macOS Monterey 12.2.1
 - Keyman version: 15.0.206-beta
 - Target Application: Keyman

**Comment by MakaraSok** [comment]
> [Makara Sok](https://app.slack.com/team/U6Q7Y6XTM) i installed the beta on top of the current stable and no restart

**Comment by MakaraSok** [comment]
Repro steps taken:
1. the existing version of Keyman was uninstalled following the instructions at https://help.keyman.com/products/mac/1.0/docs/help_uninstall_keyman.
2. the machine was restarted
3. the latest beta ([15.0.219](https://build.palaso.org/viewLog.html?buildId=312169&buildTypeId=KeymanMac_Master)) build was installed
4. this error occurs https://github.com/keymanapp/keyman/issues/5578 here is the [log](https://drive.google.com/file/d/1FIyQkcbOZOEDHmtACnJqi5OzODi7Eq4k/view?usp=sharing) of when the error occurs.
5. steps in the [knowledge base](https://help.keyman.com/knowledge-base/108) relevant with the error mentioned right above were taken​ - Safe Boot was done following the instructions [here](https://support.apple.com/en-gb/HT201262)
6. in Safe Boot, Keyman was installed successfully and the `Configuration...` window shows up.
7. the machine was restarted and log in as usual, Keyman configuration was opened and the configuration window does show up.

<img width="496" alt="image" src="https://user-images.githubusercontent.com/28331388/159651583-1d2bd421-9cd3-44a9-95c7-e2ff7795fa4f.png">

<img width="846" alt="image" src="https://user-images.githubusercontent.com/28331388/159651614-82faa3a8-0703-4a08-ac4c-51a5616bfc73.png">

**Comment by mcdurdin** [comment]
Okay, thank you, going ahead and closing this as resolved!
