### ISSUE TITLE
bug(developer): Developer seems to be frozen without any obvious reason

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#6329]
**Describe the bug**

A keyboard project was loaded and a build was about to be triggered from the keyboard menu (via Compile Keyboard), but then this happened.

![image](https://user-images.githubusercontent.com/28331388/156526278-a6369364-e997-46d0-9796-95faf2ec390f.png)

Nothing responds to the click. See the video clip below:

https://user-images.githubusercontent.com/28331388/156527149-93069f5b-8cbc-4607-8214-bdad75e2e7b8.mov

---

**Keyman Developer:**
 - OS: Windows 10 Pro 21H2 x64
 - Keyman Developer version: 15.0.206-beta

**Comment by mcdurdin** [comment]
Did minimizing and restoring the app resolve the issue?

**Comment by MakaraSok** [comment]
Yes, minimize and then maximize to get it to be responsive again.

**Comment by mcdurdin** [comment]
OK, I am going to go ahead and close this for now -- it seems to me to be hard to reproduce. If we get a solid repro, we can reopen and chase this.
