### ISSUE TITLE
test(android): Regression Test B15S4

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#6336]
# Keyman for Android Regression Test Procedures #

* These test procedures are to be run each sprint, also before moving from alpha to beta, or beta to stable, and ideally before PRs are merged into stable branches.

* Copy these checklists of tests into a new issue and title/tag as required.

## Gather Assets for Testing ##
- [ ] Physical Android phone (record device's Android -- version 5.0 Lollipop or later)
- [ ] External Bluetooth or USB QWERTY keyboard
- [ ] External Bluetooth or USB AZERTY keyboard (European AZERTY layout with 102nd key)

## Setup Steps ##
  1. Uninstall previous version of Keyman on the device (don't forget to reset user settings for the app; in Android Pie: Settings>Storage>Other apps>Keyman>Clear Data)
  2. Install test build APK
  3. Accept all the Android permission requests for storage (applies to Android 6.0 Marshmallow onward) 
  
# User Testing
## SUITE_INSPECT: Visual Inspection of master branch
- **TEST_CI_WEB_MASTER**: Verify latest CI Android build of master is successful on https://status.keyman.com/
- **TEST_VERIFY_HISTORY**: Verify `/history.md` contains all the current changes

## SUITE_MENU_FUNCTIONALITY: Menu Functionality Tests ##
<details>
<summary>click to expand</summary>

## Various versions of Androids
  UI for these tests assume default English locale
  * GROUP_ANDROID_5
  * GROUP_ANDROID_8
  * GROUP_ANDROID_11

- **TEST_GET_STARTED:** This tests the "Get Started" menu from a fresh installation
  <details>
  <summary>Expand to see how to do and verify this</summary>

  1. When the app loads, verify the "Get Started" menu is visible
  2. From the "Get Started" menu, touch "Add a keyboard for your language"
  3. Verify "Install Keyboard or Dictionary" menu appears
  4. From the "Install Keyboard or Dictionary" menu, click the back arrow to return to "Get Started"
  5. From the "Get Started" menu, touch "Enable Keyman as system-wide keyboard"
  6. Verify Android system menus appear for controlling virtual keyboard
  7. Scroll down and enable Keyman as a system keyboard.
  8. On the "Attention" dialog, read and hit "OK" to dismiss the dialogs.
  9. Touch the back button to return to "Get Started"
  10. Verify "Enable Keyman as system-wide keyboard" now has a ticked checkbox.
  11. From the "Get Started" menu,  touch "Set Keyman as default keyboard"
  12. On the "Change keyboard" dialog, select Keyman
  13. Verify on the "Get Started" menu that "Set Keyman as default keyboard" now has a ticked checkbox.
  14. From the "Get Started" menu,  touch "More info"
  15. Verify the Info page appears with a version string at the bottom of the page
  16. Touch the back button (arrow) to return to "Get Started"
  17. From the "Get Started" menu, untick the last option 'Show "Get Started" on startup'
  18. Close the "Get Started" menu and exit the app.
  19. From the Android device, start Keyman for Android
  20. Verify the "Get Started" menu does not appear.
  </details>

- **TEST_INSTALL_KD:** This menu is accessed via **Get Started** menu or the Settings button-->"Install Keyboard or Dictionary"
  <details>
  <summary>Expand to see how to do and verify this</summary>
  
  1. On the device, enable internet connectivity
  2. Touch "Install from keyman.com"
  3. Verify a new keyboard can be downloaded and selected
  4. On the device, disable internet connectivity
  5. From "Install Keyboard or Dictionary", touch "Install from keyman.com"
  6. Verify device displays a message "Cannot connect to Keyman server!"
  7. On the device, re-enable internet connectivity
  </details>

- **TEST_KEYMAN_SETTTINGS:**
  <details>
  <summary>Expand to see how to do and verify this</summary>
  
  1. From "Settings" --> "Installed Languages"
  2. Select "English" --> English Settings
  3. Select keyboard settings menu
  4. Verify Info appears with keyboard version, help link, and QR code
  5. If keyboard update is available, click on version and verify update
  6. If help link is available, click on link
  7. Verify keyboard help documentation appears
  8. Return to English Settings menu
  9. Select Dictionary --> English dictionary (MTNT)
  10. Verify the Dictionary info appears
  11. Return to English Settings menu
  12. Turn on/off 'Enable Predictions' and validate each
  13. Turn on/off 'Enable Corrections' and validate each. For example, when Corrections are enabled and context "tooo" should still suggest "too"
  14. Validate that when both predictions and corrections are off, banner is not visible
  15. Add/Remove dictionaries - validate
  16. If multiple dictionaries are available, test swapping between them
  </details>
  
- **TEST_SHARE:** Type and verify text can be shared to external app 

- **TEST_KEYMAN_BROWSER:** Keyman Browser ###
  <details>
  <summary>Expand to see how to do and verify this</summary>

  1. On default page, click on text field and set system keyboard to Keyman
  2. Verify can type with Keyman as system keyboard
  3. Close and reopen Keyman app
  </details>

- **TEST_TEXT_SIZE:** Verify text can be rescaled from Text Size 16 to 72
  
- **TEST_CLEAR_TEXT:** Verify text can be cleared
  
- **TEST_INFO:**
  <details>
  <summary>Expand to see how to do and verify this</summary>
  
  1. From the device, disable internet access
  2. From the Keyman app menu, select "Info"
  3. Verify Keyman for Android version appears at the bottom of the screen
  4. Verify Keyman for Android help documentation is displayed.
  5. From the device, enable internet access
  </details>

- **TEST_INSTALL_UPDATES:** This menu option only appears when a language resource (keyboard or lexical-model) update is available
  <details>
  <summary>Expand to see how to do and verify this</summary>
  
  1. Click on "Install Updates"
  2. Accept "Download" on the dialogue
  3. Verify resource is updated after background download complete
  </details>
  
- **TEST_CHANGE_DISPLAY_LANG:** This tests changing the display language for the App and assumes starting with English locale
  <details>
  <summary>Expand to see how to do and verify this</summary>
  
  1. From "Settings" --> "Display Language"
  2. Select "Khmer"
  3. From "Settings" --> Verify menu selections in Khmer
  4. From the overflow menu --> clear text
  5. Verify Keyman text field has Khmer prompt (for "Start typing here")
  6. From "Settings" --> "Change Display Language"
  7. If the string is translated, the first row should be "Default Locale" in Khmer
  8. Select "English"
  9. Verify the app reloads in English
  </details>

- **TEST_ADJUST_K_HEIGHT:** This menu option allows the user to adjust the OSK height for the current orientation (portrait or landscape). The customized height is saved as a preference
  <details>
  <summary>Expand to see how to do and verify this</summary>
  
  1. Have the device in portrait orientation
  2. From "Settings" --> "Adjust keyboard height"
  3. On the menu, drag the OSK height to change the keyboard height
  4. Click back
  5. Verify the OSK is refreshed to the selected height
  6. From "Settings" --> "Adjust keyboard height"
  7. Click the "reset to defaults" button and then click back
  8. Verify the OSK reverts to the original height
  9. Rotate the device to landscape orientation
  10. From "Settings" --> "Adjust keyboard height"
  11. On the menu, drag the OSK height to change the keyboard height
  12. Click back
  13. Verify the OSK is refreshed to the selected height
  14. From "Settings" --> "Adjust keyboard height"
  15. Click the "reset to defaults" button and then click back
  16. Verify the OSK reverts to the original height
  17. Rotate the device back to portrait orientation
  </details>

- **TEST_SPACEBAR_CAPTION:** This menu option allows the user to adjust the label displayed on the keyboard spacebar
  <details>
  <summary>Expand to see how to do and verify this</summary>
  
  1. Select the default SIL EuroLatin keyboard
  2. From "Settings" --> Spacebar caption
  3. On the menu, select "Language"
  4. Click back until the OSK is displayed
  5. Verify the spacebar label is "English"
  6. From "Settings" --> Spacebar caption
  7. On the menu, select "Keyboard"
  8. Click back until the OSK is displayed
  9. Verify the spacebar label is "EuroLatin (SIL)"
  10. From "Settings" --> Spacebar caption
  11. On the menu, select "Blank"
  12. Click back until the OSK is displayed
  13. Verify the spacebar label is blank
  14. From "Settings" --> Spacebar caption
  15. On the menu, select "Language+Keyboard"
  16. Click back until the OSK is displayed
  17. Verify the spacebar label is "English - EuroLatin (SIL)"
  </details>
</details>

----

## SUITE_KEYBOARD_FUNCTIONALITY: Keyboard Tests

<details>
<summary>click to expand</summary>

## Various versions of Androids
  UI for these tests assume default English locale
  * GROUP_ANDROID_5
  * GROUP_ANDROID_8
  * GROUP_ANDROID_11

### In-app Keyboards
These tests are run in the context of typing in the Keyman app

- **TEST_INAPP_LATIN_KEYBOARD:** English(EuroLatin SIL)
  In portrait orientation, verify OSK is visible and fills the width the bottom of the screen
  <details>
  <summary>Expand to see how to do and verify this</summary>
  
  1. Verify long-press `q` key works
  2. Verify long-press `p` key works
  3. Verify uppercase layer can be selected via `SHIFT`
  4. Verify number layer can be selected via `123`
  5. Verify long-press `1` key works
  6. Verify long-press `0` key works
  7. Verify backspace, space, and enter keys work
  8. Verify *Khmer* -> *Khmer Angkor* keyboard can be added via Settings menu
  9.  Repeat in landscape orientation
  </details>

- **TEST_INAPP_NON_LATIN_KEYBOARD:** Non-Latin script Keyboard
  <details>
  <summary>Expand to see how to do and verify this</summary>

  1. In the app, add/select a random non-Latin script keyboard
  2. Verify OSK is visible
  3. Test several keys and modifiers and verify Latin characters are not appearing.
  </details>

### System Keyboards
These tests are run with Keyman selected as a system keyboard, and in the context of typing in an external app (like Google Keep)

- **TEST_SYSTEM_LATIN_KEYBOARD:** English (EuroLatin SIL)
 In portrait orientation, verify OSK is visible and fills the width the bottom of the screen
  <details>
  <summary>Expand to see how to do and verify this</summary>
 
  1. Verify long-press `q` key works
  2. Verify long-press `p` key works
  3. Verify uppercase layer can be selected via `SHIFT`
  4. Verify number layer can be selected via `123`
  5. Verify long-press `1` key works
  6. Verify long-press `0` key works
  7. Verify backspace, space, and enter keys work
  8. Verify can change to random non-Latin script keyboard via globe button
  9. Repeat in landscape orientation
  </details>
  
- **TEST_KEYBOARD_PICKER:** Keyboard Picker menu to switch input method
This tests the Keyboard Picker menu which lists other system input methods at the bottom of the menu. These appear only in Keyman system keyboard
  <details>
  <summary>Expand to see how to do and verify this</summary>
  
  1. With only 1 Keyman keyboard installed and selected as a system keyboard, long-press and release the the globe button
  2. Verify the bottom of the Keyboards picker menu lists other available input methods
  3. Click on one of the other input methods
  4. Verify the Keyman system keyboard switches to the selected input method
  5. On the device's Settings, select Keyman as the input method
  6. On the Keyman keyboard, short-press and release the globe button
  7. Verify the previous input method is selected
  </details>

- **TEST_EXT_BLUETOOTH_KEYBOARD:** External (Bluetooth) keyboard
This test is run with an external keyboard (USB or bluetooth) connected to the device
  <details>
  <summary>Expand to see how to do and verify this</summary>
  
  1. Start with English(EuroLatin SIL) as the selected keyboard
  2. On the device's Settings, show the input method (OSK)
  3. Verify can type with numbers, letters, and punctuation
  4. Verify `caps lock` has no effect when typing
  5. Verify long-press on a character repeats that character
  6. Verify `tab` toggles to next field
  7. Verify `enter` adds a newline
  8. Verify `backspace` removes a character
  9. Verify <kbd>ctrl</kbd>+<kbd>tab</kbd> brings up the keyboard picker menu
  10. Use <kbd>tab</kbd> or arrow keys to navigate the keyboard picker menu
  11. Select a non-Latin keyboard
  12. Resume typing and verify new script appears
  </details>

- **TEST_EXT_AZERTY_KEYBOARD:** External European AZERTY keyboard
This test is run with an external European AZERTY keyboard paired to the device. It should contain the 102nd key `<>` on the bottom row next to the left-shift.
  <details>
  <summary>Expand to see how to do and verify this</summary>
  
  1. Start Keyman and install the French Basic keyboard
  2. From the physical keyboard, type on the top letter row (azerty)
  3. Verify `azerty` appears
  4. Type on the 102nd key
  5. Verify `<` appears
  6. Type shift-102nd key
  7. Verify `>` appears
  </details>
  
</details>

----

## SUITE_KB_DISTRIBUTION: Ad-hoc Keyboard Distribution Tests
<details>
<summary>Expand to see how to do and verify this</summary>

## Various versions of Androids
  UI for these tests assume default English locale
  * GROUP_ANDROID_5
  * GROUP_ANDROID_8
  * GROUP_ANDROID_11

- **TEST_KMP_DISTRIBUTION** KMP distribution
  <details>
  <summary>Expand to see how to do and verify this</summary>
  
  1. Reset app settings (in Android Pie: Settings>Storage>Other apps>Keyman>Clear Storage)
  2. Verify kmp [distribution](https://help.keyman.com/developer/current-version/guides/distribute/) successfully installs<br/>
   Example: [Khmer Angkor](https://downloads.keyman.com/keyboards/khmer_angkor/1.0.2/khmer_angkor.kmp)
  3. Verify kmp successfully installs from Settings --> Install Keyboard or Dictionary --> Install from local file
  </details>
</details>

**Comment by bharanidharanj** [comment]
## SUITE_INSPECT: Visual Inspection of master branch

* **TEST_CI_WEB_MASTER (PASSED):** Able to see the Successful Beta build 15.0.218 in status.keyman.com website. 
Successful Beta build for Android:
<img width="300" src="https://user-images.githubusercontent.com/19683143/159472175-65488b3b-c8b6-49cd-b433-da867266eefd.PNG">

History File for the Beta build 15.0.218:
* **TEST_VERIFY_HISTORY (FAILED):** History File need to be updated.
<img width="300" src="https://user-images.githubusercontent.com/19683143/159472516-c9eb6731-a591-41c1-b7f1-0975c2258c78.PNG">

**Comment by bharanidharanj** [comment]
### GROUP_ANDROID_8: 

* **TEST_GET_STARTED (PASSED):** Tested this on Android emulator API 26 and it is working as expected. However, I noticed that running step viii, I got another Warning box. Clicking on the OK button would close the dialog. 

Warning box appears after closing the first (Attention) dialog box:
<img width="300" src="https://user-images.githubusercontent.com/19683143/159479430-59cd219e-a55b-407d-bab9-8e3fb34da551.PNG">


Version number appears at the bottom of the page:
<img width="300" src="https://user-images.githubusercontent.com/19683143/159479548-d2ae2d52-61a6-4e02-a138-9c9705d80356.PNG">

**Comment by bharanidharanj** [comment]
* **TEST_INSTALL_KD (PASSED):** Tested this on Android API 26 emulator and it is working as expected. 

Install Keyboard (with Internet):
<img width="300" src="https://user-images.githubusercontent.com/19683143/159483734-49464ab6-6d3a-4553-86f2-99caf3c54834.PNG">

Install Keyboard (without Internet):
<img width="300" src="https://user-images.githubusercontent.com/19683143/159483765-fffae2d4-c6fe-4628-8b86-0c80291cbaea.PNG">

**Comment by bharanidharanj** [comment]
## SUITE_MENU_FUNCTIONALITY: Menu Functionality Tests ##

### GROUP_ANDROID_8: 

* **TEST_KEYMAN_SETTTINGS (PASSED):** Tested this on Android emulator API 26 and it is working as expected.
* **TEST_SHARE (PASSED):** Tested this on Android emulator API 26 and it is working as expected.
* **TEST_KEYMAN_BROWSER (PASSED):** Tested this on Android emulator API 26 and it is working as expected.
* **TEST_TEXT_SIZE (PASSED):** Tested this on Android emulator API 26 and it is working as expected.
* **TEST_CLEAR_TEXT (PASSED):** Tested this on Android emulator API 26 and it is working as expected.
* **TEST_INFO (PASSED):** Tested this on Android emulator API 26 and it is working as expected.
<img width="300" src="https://user-images.githubusercontent.com/19683143/159496183-dee44ab2-9903-46f2-b7e2-78b121770fa7.PNG"> 


* **TEST_INSTALL_UPDATES (SKIPPED):** Not able to see the Update option. Seems to options. Hence, I skipped this one. 
* **TEST_CHANGE_DISPLAY_LANG (PASSED):** Tested this on Android emulator API 26 and it is working as expected.
<img width="300" src="https://user-images.githubusercontent.com/19683143/159496370-178e6486-db01-411b-a251-db711c3fe232.PNG"> 


* **TEST_ADJUST_K_HEIGHT (PASSED):** Tested this on Android emulator API 26 and it is working as expected.
* **TEST_SPACEBAR_CAPTION (FAILED):** Tested this on Android emulator API 26 and it seems that changing any options does not work. Seems to be an issue. 
<img width="300" src="https://user-images.githubusercontent.com/19683143/159498138-720c2565-8702-4adc-94f9-2db6512b13df.PNG"> 

<img width="300" src="https://user-images.githubusercontent.com/19683143/159497201-1584d0ec-cb26-485a-bb7e-51c444e0c0f7.PNG">

**Comment by bharanidharanj** [comment]
## SUITE_KEYBOARD_FUNCTIONALITY: Keyboard Tests

### GROUP_ANDROID_8: 

* **TEST_INAPP_LATIN_KEYBOARD (PASSED):** Tested this with the latest Keyman 15.0.221 beta build in Android 8 API 26 emulator and it is working as expected.
* **TEST_INAPP_NON_LATIN_KEYBOARD (PASSED):** Tested this with the latest Keyman 15.0.221 beta build in Android 8 API 26 emulator and it is working as expected.
* **TEST_SYSTEM_LATIN_KEYBOARD (PASSED):** Tested this with the latest Keyman 15.0.221 beta build in Android 8 API 26 emulator and it is working as expected.
* **TEST_KEYBOARD_PICKER (PASSED):** Tested this with the latest Keyman 15.0.221 beta build in Android 8 API 26 emulator and it is working as expected.
<img width="300" src="https://user-images.githubusercontent.com/19683143/160119854-87ed8864-f99e-4771-953b-fe7cb478a47b.PNG"> 

* **TEST_EXT_BLUETOOTH_KEYBOARD (SKIPPED):** Skipped this test since I don't have Bluetooth Keyboard for testing. 
* **TEST_EXT_AZERTY_KEYBOARD (SKIPPED):** Skipped this test since I don't have AZERTY Keyboard for testing.

**Comment by bharanidharanj** [comment]
### GROUP_ANDROID_11: 

* **TEST_INAPP_LATIN_KEYBOARD (PASSED):** Tested this with the latest Keyman 15.0.221 Beta build in Android 11 API 30 and it is working as expected.
* **TEST_INAPP_NON_LATIN_KEYBOARD (PASSED):** Tested this with the latest Keyman 15.0.221 Beta build in Android 11 API 30 and it is working as expected.
* **TEST_SYSTEM_LATIN_KEYBOARD (PASSED):** Tested this with the latest Keyman 15.0.221 Beta build in Android 11 API 30 and it is working as expected.
* **TEST_KEYBOARD_PICKER (PASSED):** Tested this with the latest Keyman 15.0.221 Beta build in Android 11 API 30 and it is working as expected.
<img width="300" src="https://user-images.githubusercontent.com/19683143/160132390-1274ad25-087a-46c7-b694-2e74e8854bc2.PNG"> 

* **TEST_EXT_BLUETOOTH_KEYBOARD (SKIPPED):** Skipped this test since I don't have Bluetooth Keyboard for testing.
* **TEST_EXT_AZERTY_KEYBOARD (SKIPPED):** Skipped this test since I don't have Bluetooth Keyboard for testing.

**Comment by bharanidharanj** [comment]
### GROUP_ANDROID_5: 

* **TEST_INAPP_LATIN_KEYBOARD (BLOCKED):** Tested this in Android 5.0 API 21 emulator and it showing Chrome update (even though installed the latest chrome version) error message after installing the Keyman 15.0 Beta build. 
* **TEST_INAPP_NON_LATIN_KEYBOARD (BLOCKED):** Tested this in Android 5.0 API 21 emulator and it showing Chrome update (even though installed the latest chrome version) error message after installing the Keyman 15.0 Beta build. 
* **TEST_SYSTEM_LATIN_KEYBOARD (BLOCKED):** Tested this in Android 5.0 API 21 emulator and it showing Chrome update (even though installed the latest chrome version) error message after installing the Keyman 15.0 Beta build. 
* **TEST_KEYBOARD_PICKER (BLOCKED):** Tested this in Android 5.0 API 21 emulator and it showing Chrome update (even though installed the latest chrome version) error message after installing the Keyman 15.0 Beta build. 
* **TEST_EXT_BLUETOOTH_KEYBOARD (BLOCKED):** Tested this in Android 5.0 API 21 emulator and it showing Chrome update (even though installed the latest chrome version) error message after installing the Keyman 15.0 Beta build. 
* **TEST_EXT_AZERTY_KEYBOARD (BLOCKED):** Tested this in Android 5.0 API 21 emulator and it showing Chrome update (even though installed the latest chrome version) error message after installing the Keyman 15.0 Beta build.

**Comment by bharanidharanj** [comment]
## SUITE_KB_DISTRIBUTION: Ad-hoc Keyboard Distribution Tests

### GROUP_ANDROID_5: 

* **TEST_KMP_DISTRIBUTION (BLOCKED):** Tested this on Android 5.0 API 21 emulator and Keyman shows an error message (Chrome update) in the Keyman 15.0 Beta build. 
<img width="300" src="https://user-images.githubusercontent.com/19683143/160385495-8d2103ff-f154-457b-8fdc-623e842a9de5.PNG"> 


### GROUP_ANDROID_11: 

* **TEST_KMP_DISTRIBUTION (FAILED):** Tested this on Android 11.0 API 30 emulator and it is failed in the 3rd step ie., Keyman KMP files can install from Local File folder. 
<img width="300" src="https://user-images.githubusercontent.com/19683143/160385450-9c7cbce0-a5a4-4e96-a394-d2a72a773e08.png">

**Comment by MakaraSok** [comment]
I don't see the notification on updating Chrome in Android 5 as a blocking issue for any of the tests. All tests could be done without any issue, couldn't they?

@keymanapp-test-bot retest GROUP_ANDROID_5

**Comment by MakaraSok** [comment]
@keymanapp-test-bot retest SUITE_KB_DISTRIBUTION GROUP_ANDROID_8 all, SUITE_KB_DISTRIBUTION GROUP_ANDROID_11 all

I can install the .kmp file as usual on both Android versions. Can you double check them?

**Comment by MakaraSok** [comment]
@bharanidharanj

**Comment by bharanidharanj** [comment]
## SUITE_MENU_FUNCTIONALITY: Menu Functionality Tests ##

### GROUP_ANDROID_5: 

* **TEST_GET_STARTED (PASSED):** Tested this with the latest Keyman 15.0.246-beta build in Android 5.0 API 21 emulator and it is working as expected. 
* **TEST_INSTALL_KD (PASSED):** Tested this with the latest Keyman 15.0.246-beta build in Android 5.0 API 21 emulator and it is working as expected. 
* **TEST_KEYMAN_SETTTINGS (PASSED):** Tested this with the latest Keyman 15.0.246-beta build in Android 5.0 API 21 emulator and it is working as expected. 
* **TEST_SHARE (PASSED):** Tested this with the latest Keyman 15.0.246-beta build in Android 5.0 API 21 emulator and it is working as expected. 
* **TEST_KEYMAN_BROWSER (PASSED):** Tested this with the latest Keyman 15.0.246-beta build in Android 5.0 API 21 emulator and it is working as expected. 
* **TEST_TEXT_SIZE (PASSED):** Tested this with the latest Keyman 15.0.246-beta build in Android 5.0 API 21 emulator and it is working as expected. 
* **TEST_CLEAR_TEXT (PASSED):** Tested this with the latest Keyman 15.0.246-beta build in Android 5.0 API 21 emulator and it is working as expected. 
* **TEST_INFO (PASSED):** Tested this with the latest Keyman 15.0.246-beta build in Android 5.0 API 21 emulator and it is working as expected. 
* **TEST_INSTALL_UPDATES (SKIPPED):** Tested this with the latest Keyman 15.0.246-beta build in Android 5.0 API 21 emulator and this functionality is optional. Hence, I Skipped. 
* **TEST_CHANGE_DISPLAY_LANG (PASSED):** Tested this with the latest Keyman 15.0.246-beta build in Android 5.0 API 21 emulator and it is working as expected. 
* **TEST_ADJUST_K_HEIGHT (PASSED):** Tested this with the latest Keyman 15.0.246-beta build in Android 5.0 API 21 emulator and it is working as expected. 
* **TEST_SPACEBAR_CAPTION (FAILED):** Tested this with the latest Keyman 15.0.246-beta build in Android 5.0 API 21 emulator and I noticed that Spacebar Caption is not changed when I set to any options like Language, Keyboard, Blank etc., 

<img width="300" src="https://user-images.githubusercontent.com/19683143/168280773-598cff0d-05fb-4c96-8b83-878e0965b092.PNG">

**Comment by bharanidharanj** [comment]
## SUITE_KEYBOARD_FUNCTIONALITY: Keyboard Tests

### GROUP_ANDROID_5: 

* **TEST_INAPP_LATIN_KEYBOARD (PASSED):** Tested this with the latest Keyman 15.0.246-beta build in Android 5.0 API 21 emulator and it is working as expected.
* **TEST_INAPP_NON_LATIN_KEYBOARD (PASSED):** Tested this with the latest Keyman 15.0.246-beta build in Android 5.0 API 21 emulator and it is working as expected.
* **TEST_SYSTEM_LATIN_KEYBOARD (PASSED):**  Tested this with the latest Keyman 15.0.246-beta build in Android 5.0 API 21 emulator and it is working as expected.
* **TEST_KEYBOARD_PICKER (FAILED):**  Tested this with the latest Keyman 15.0.246-beta build in Android 5.0 API 21 emulator and it is flashing some other dialog instead of Keyboard Picker menu.

<img width="300" src="https://user-images.githubusercontent.com/19683143/168298566-ce5daa70-dcd2-4f29-94ed-f708a158c1b0.png"> 

* **TEST_EXT_BLUETOOTH_KEYBOARD (PASSED):**  Tested this with the latest Keyman 15.0.246-beta build in Android 5.0 API 21 emulator and it is working as expected.
* **TEST_EXT_AZERTY_KEYBOARD (SKIPPED):** This test needs AZERTY KEYBOARD. Hence, I Skipped.

**Comment by bharanidharanj** [comment]
## SUITE_KB_DISTRIBUTION: Ad-hoc Keyboard Distribution Tests

### GROUP_ANDROID_5: 

* **TEST_KMP_DISTRIBUTION (FAILED):**  Tested this with the latest Keyman 15.0.246-beta build in Android 5.0 API 21 emulator and it is not working as expected. ie., It is showing error message while trying to install the .kmp file. 
<img width="300" src="https://user-images.githubusercontent.com/19683143/168308354-a8477be2-7fe2-4d64-8ec9-538e3502dbba.png"> 


### GROUP_ANDROID_8: 

* **TEST_KMP_DISTRIBUTION (FAILED):** Tested this with the latest Keyman 15.0.246-beta build in Android 5.0 API 26 emulator and it is not working as expected. ie., It is showing error message while trying to install the .kmp file.

### GROUP_ANDROID_11: 

* **TEST_KMP_DISTRIBUTION (FAILED):** Tested this with the latest Keyman 15.0.246-beta build in Android 5.0 API 30 emulator and it is not working as expected. ie., It is showing error message while trying to install the .kmp file.

**Comment by MakaraSok** [comment]
Some devices are needed to perform these tests: (1) a bluetooth keyboard or a USB keyboard which can be attached to the USB-C port of the physical Android phone

@keymanapp-test-bot retest SUITE_KEYBOARD_FUNCTIONALITY GROUP_ANDROID_5 TEST_KEYBOARD_PICKER TEST_EXT_BLUETOOTH_KEYBOARD TEST_EXT_AZERTY_KEYBOARD, SUITE_KEYBOARD_FUNCTIONALITY GROUP_ANDROID_8 TEST_KEYBOARD_PICKER TEST_EXT_BLUETOOTH_KEYBOARD TEST_EXT_AZERTY_KEYBOARD, SUITE_KEYBOARD_FUNCTIONALITY GROUP_ANDROID_11 TEST_KEYBOARD_PICKER TEST_EXT_BLUETOOTH_KEYBOARD TEST_EXT_AZERTY_KEYBOARD, SUITE_KB_DISTRIBUTION GROUP_ANDROID_5 GROUP_ANDROID_8 GROUP_ANDROID_11

**Comment by MakaraSok** [comment]
@keymanapp-test-bot retest SUITE_KB_DISTRIBUTION GROUP_ANDROID_5 TEST_KMP_DISTRIBUTION, SUITE_KB_DISTRIBUTION GROUP_ANDROID_8 TEST_KMP_DISTRIBUTION, SUITE_KB_DISTRIBUTION GROUP_ANDROID_11 TEST_KMP_DISTRIBUTION

**Comment by bharanidharanj** [comment]
### GROUP_ANDROID_5: 

* **TEST_KEYBOARD_PICKER (PASSED):** As per Makara's suggestion I have retested this with the Keyman 15.0.246-beta build and this time it is working as expected. 

### GROUP_ANDROID_8: 

* **TEST_KEYBOARD_PICKER (PASSED):** As per Makara's suggestion I have retested this with the Keyman 15.0.246-beta build and this time it is working as expected. 

### GROUP_ANDROID_11: 

* **TEST_KEYBOARD_PICKER (PASSED):** As per Makara's suggestion I have retested this with the Keyman 15.0.246-beta build and this time it is working as expected.

**Comment by bharanidharanj** [comment]
## SUITE_MENU_FUNCTIONALITY: Menu Functionality Tests ##

### GROUP_ANDROID_5: 

* **TEST_INSTALL_UPDATES (PASSED):** Tried with Darcy's new steps (suggested by Makara) in Android 5 API 21 emulator and this is working as expected. (Able to upgrade Cameroon qwerty keyboard from 6.0.4 to 6.0.6)
<img width="300" src="https://user-images.githubusercontent.com/19683143/169308744-fd4cf323-3e70-417e-9b5a-bc61b635aece.PNG"> 


### GROUP_ANDROID_8: 

* **TEST_INSTALL_UPDATES (PASSED):** Tried with Darcy's new steps (suggested by Makara) in Android 8 API 26 emulator and this is working as expected. (Able to upgrade Cameroon qwerty keyboard from 6.0.4 to 6.0.6)


### GROUP_ANDROID_11: 

* **TEST_INSTALL_UPDATES (PASSED):** Tried with Darcy's new steps (suggested by Makara) in Android 8 API 26 emulator and this is working as expected. (Able to upgrade Cameroon qwerty keyboard from 6.0.4 to 6.0.6)

**Comment by bharanidharanj** [comment]
## SUITE_KEYBOARD_FUNCTIONALITY: Keyboard Tests

### GROUP_ANDROID_5: 

* **TEST_EXT_BLUETOOTH_KEYBOARD (PASSED):** Tested Keyman 15.0.528 beta build in Android 5.0 emulator along with USB Keyboard and it is working as expected. 
* **TEST_EXT_AZERTY_KEYBOARD (SKIPPED):** Waiting for Azerty Keyboard to test.

### GROUP_ANDROID_8: 

* **TEST_EXT_BLUETOOTH_KEYBOARD (PASSED):** Tested Keyman 15.0.528 beta build in Android 8.0 emulator along with USB Keyboard and it is working as expected. 
* **TEST_EXT_AZERTY_KEYBOARD (SKIPPED):** Waiting for Azerty Keyboard to test.

### GROUP_ANDROID_11: 

* **TEST_EXT_BLUETOOTH_KEYBOARD (PASSED):** Tested Keyman 15.0.528 beta build in my Android Mobile 11.0 along with USB Keyboard and it is working as expected. 
* **TEST_EXT_AZERTY_KEYBOARD (SKIPPED):** Waiting for Azerty Keyboard to test.

**Comment by bharanidharanj** [comment]
## SUITE_KEYBOARD_FUNCTIONALITY: Keyboard Tests

### GROUP_ANDROID_8: 

* **TEST_EXT_BLUETOOTH_KEYBOARD (PASSED):** Tested Keyman 15.0.528 beta build in Android 8.0 emulator along with USB Keyboard and it is working as expected. 
* **TEST_EXT_AZERTY_KEYBOARD (SKIPPED):** Waiting for Azerty Keyboard to test.

**Comment by bharanidharanj** [comment]
## SUITE_KEYBOARD_FUNCTIONALITY: Keyboard Tests

### GROUP_ANDROID_11: 

* **TEST_EXT_BLUETOOTH_KEYBOARD (PASSED):** Tested Keyman 15.0.528 beta build in my Android Mobile 11.0 along with USB Keyboard and it is working as expected. 
* **TEST_EXT_AZERTY_KEYBOARD (SKIPPED):** Waiting for Azerty Keyboard to test.

**Comment by MakaraSok** [comment]
@keymanapp-test-bot retest SUITE_KEYBOARD_FUNCTIONALITY GROUP_ANDROID_5 TEST_KEYBOARD_PICKER TEST_EXT_AZERTY_KEYBOARD, SUITE_KEYBOARD_FUNCTIONALITY GROUP_ANDROID_8 TEST_KEYBOARD_PICKER TEST_EXT_AZERTY_KEYBOARD, SUITE_KEYBOARD_FUNCTIONALITY GROUP_ANDROID_11 TEST_KEYBOARD_PICKER TEST_EXT_AZERTY_KEYBOARD

**Comment by MakaraSok** [comment]
## SUITE_INSPECT: Visual Inspection of master branch

* **TEST_VERIFY_HISTORY (SKIPPED):** TBU
