### ISSUE TITLE
bug(developer): script error after updating from beta 15.0.206 to 15.0.209

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#6349]
**Describe the bug**

![image](https://user-images.githubusercontent.com/28331388/157368335-bfc09cfd-4b24-4985-836a-2b1efbfc1976.png)

This error occurs after/during updating from 15.0.206 to 15.0.209. Closing the box using the X box and it reappears. Click again on the X to close and it's gone.

However, this doesn't stop Keyman Developer from running. Is this a legit Windows' error, Keymans' or VM's?

---

**Keyman Developer:**
 - OS: Windows 10 Pro 21H2 x64 (VM)
 - Keyman Developer version: Beta 15.0.206 > 15.0.209

**Comment by mcdurdin** [comment]
This appears to be a OneDrive issue - see https://answers.microsoft.com/en-us/msoffice/forum/all/onedrive-login-javascript-error/1f76da13-442d-4da7-b1a8-3c6f3c1f7c92?auth=1
