### ISSUE TITLE
bug: windows backspace adding a character 

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#6362]
**Describe the bug**

**To Reproduce**
Same behavior is seen in android and iOS

**Expected behavior**
Delete character with backspace

**Keyman for Windows/macOS/Linux:**
 - OS:  Windows 10 2004 x64
 - Keyman version: 15.0.211-beta
 - Target Application: chrome

**Comment by mcdurdin** [comment]
Can you give a little more detail, including precise steps to reproduce, and whether or not this issue is present in earlier versions of Keyman?

**Comment by mcdurdin** [comment]
Hi @MayuraVerma, we can't reproduce this here; I'm going to go ahead and close this. If you have any additional detail or repro steps, please feel free to reopen this issue 😀
