### ISSUE TITLE
bug(developer): insert character code, but output the character itself in the key ID field

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#6384]
**Describe the bug**

https://user-images.githubusercontent.com/28331388/158512020-1d81a90c-d10c-4c91-b762-c52e5f497e53.mov

**Expected behavior**

The output should be character code per selected option.

---

**Keyman Developer:**
 - OS: Windows 10 Pro 21H2
 - Keyman Developer version: 15.0.211

**Comment by mcdurdin** [comment]
See also #4854

**Comment by mcdurdin** [comment]
This will be resolved in #4854 by tightening up the integration of the Character Map with the Touch Layout Editor.
