### ISSUE TITLE
bug(ios): transparent navigation bars

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#6413]
**Describe the bug**

Two issues: (1) the top part is transparent making the heading texts hard to read and (2) the bottom part has a keyboard popped up unexpectedly.

<img width="497" alt="image" src="https://user-images.githubusercontent.com/28331388/159605217-8d697805-32d6-4f09-8e67-dc8e2ca05ab1.png">

build: 
[Keyman-4.app.zip](https://github.com/keymanapp/keyman/files/8328962/Keyman-4.app.zip)

keyboard (if needed): 
[obolo_chwerty_6351.kmp.zip](https://github.com/keymanapp/keyman/files/8328980/obolo_chwerty_6351.kmp.zip)

**Expected behavior**

The screen shown after dropping the .kmp file in the iOS simulator could be improved, esp. the two things noted above.

---

**Keyman for iPhone:**
 - Device: iPhone 13
 - OS: iOS 15.4
 - Keyman version: 15.0.214-beta-test-6366
 - Target application: Keyman

---

**Additional context**

related: https://github.com/keymanapp/keyman/pull/6366, https://github.com/keymanapp/keyman/issues/6387

**Comment by MakaraSok** [comment]
This behavior is also observed in `15.0.220-beta-test`.

**Comment by MakaraSok** [comment]
The same for landscape mode with Keyman 15.0.241-beta on iOS 15.4 on iPhone 8 simulator. Buttons at the top are not clearly visible and seem to overlap with icons/logos in the background.
<img width="905" alt="image" src="https://user-images.githubusercontent.com/28331388/167365459-03ae820a-eb23-4ada-b2ec-6ae8adc22053.png">

**Comment by jahorton** [comment]
This sounds possibly related: https://stackoverflow.com/questions/69111478/ios-15-navigation-bar-transparent

> In the apple developer forum at https://developer.apple.com/forums/thread/682420 it states that "In iOS 15, UIKit has extended the usage of the scrollEdgeAppearance, which by default produces a transparent background, to all navigation bars." To restore the old look, you must adopt the new UINavigationBar appearance APIs
