### ISSUE TITLE
bug(ios): the three dot menu icon has white background against the yellow background of the app itself

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#6414]
**Describe the bug**

<img width="150" src="https://user-images.githubusercontent.com/28331388/159612088-1a5472a7-90a5-4df5-ae2b-2ba133fcd524.png">

**Expected behavior**

The icon's background should have been transparent, not white as it is now.

---

**Keyman for iPhone:**
 - Device: iPhone 11 simulator
 - OS: iOS 15.4
 - Keyman version 15.0.220-beta-test
 - Target application: Keyman

**Comment by darcywong00** [comment]
Fixed by #6598
