### ISSUE TITLE
bug(developer): node.js shows up each time Keyman Developer is opened

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#6427]
**Describe the bug**

![image](https://user-images.githubusercontent.com/28331388/160045652-909b0524-7613-4a9a-bcf7-e4e6cecc3b07.png)

Here what it says in the node.js window:
![image](https://user-images.githubusercontent.com/28331388/160045720-0cb4358b-c131-452b-ac2a-23eeb16ee385.png)

**Expected behavior**

This just bothers me a bit, but not stopping me from using Keyman Developer though.

---

**Keyman for Windows**
 - OS: Windows 10 Pro 21H2 x64
 - Keyman version: 15.0.221.0
 - Target Application: n/a

**Comment by mcdurdin** [comment]
This isn't a bug -- it's by design. You have turned on the option "Show Server console window on start" in Tools/Options/Server Options I believe!
