### ISSUE TITLE
bug(windows): different output on backquote key of Bunong keyboard

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#6448]
**Describe the bug**

https://user-images.githubusercontent.com/28331388/160789229-c27735d7-8fc7-405b-b3a7-eeb759e60342.mov

**Expected behavior**

The output in Notepad should be like that of LibreOffice, i.e. «, when the backquote is pressed once.

---

**Keyman for Windows:**
 - OS: Windows 10 Pro 21H2 x64
 - Keyman version: 15.0.224-beta
 - Target Application: Notepad

**Comment by mcdurdin** [comment]
I *think* this may be due to the Windows system keyboard you have installed -- are you testing within Parallels/VMWare or Bootcamp on a Mac? The Apple/Parallels keyboard driver has some mismatched scan codes. Can you check which Windows keyboards are installed?

Ref #3017.

**Comment by MakaraSok** [comment]
Virtual Box 6.1.32 r149290 (Qt5.6.3)
[Bunong keyboard](https://keyman.com/keyboards/sil_bunong)

**Comment by mcdurdin** [comment]
Can you run the Virtual Key Identifier on that VM and show the output for the backquote key?

Here's what I get:

![image](https://user-images.githubusercontent.com/4498365/161693876-7810eb8e-4615-4943-9b9e-6dc8a4cef0bf.png)

**Comment by MakaraSok** [comment]
<img width="304" alt="image" src="https://user-images.githubusercontent.com/28331388/161717792-42543c43-5c5d-494a-a3e8-802863911985.png">

**Comment by mcdurdin** [comment]
I'm still not seeing the same behaviour that you are on my system. Can you attach a diagnostic report?

**Comment by MakaraSok** [comment]
![image](https://user-images.githubusercontent.com/28331388/162666389-2c4bd905-25b6-4ddf-9a66-ee5ed58dd9eb.png)
[system0.zip](https://github.com/keymanapp/keyman/files/8461082/system0.zip)

**Comment by mcdurdin** [comment]
system0.zip: typed <kbd>`</kbd> in Notepad, then twice in Wordpad separated by <kbd>Enter</kbd> (first time did a rota).

**Comment by mcdurdin** [comment]
I've had a look at that log; unfortunately it does not capture either Notepad or Wordpad because they were started before the trace. Can you recapture the trace in the same way, but make sure you start Notepad and Wordpad *after* turning on Debugging?

**Comment by mcdurdin** [comment]
@MakaraSok can you redo this test following instructions above please?

**Comment by rc-swag** [comment]
> @MakaraSok can you redo this test following instructions above please?

Bump @MakaraSok

**Comment by MakaraSok** [comment]
What version of Keyman should this test be done against? The current stable?

**Comment by rc-swag** [comment]
> What version of Keyman should this test be done against? The current stable?

Latest 16 build or current stable which ever you have already to go.

**Comment by MakaraSok** [comment]
I've tested this with the current stable/alpha `15.0.268`/`16.0.57` and  it works as expected in Notepad.

**Comment by rc-swag** [comment]
Based on Makara's final test I am closing this issue.
