### ISSUE TITLE
KMW console error: Cannot read property 'wholeText' of null

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#646]
On the "SIL IPA" keyboard, toggling the layer from default to shift and back to default causes a console error
```
Uncaught TypeError: Cannot read property 'wholeText' of null
```
It corresponds to kmwosk.ts at `var keyText=e.firstChild.firstChilr.wholeText;`

Configuration:
KMW 10.0.68
Use mobile viewport to
http://localhost/keymanweb/samples/unminified.html

and add the BCP 47 tag "qab" for "SIL IPA" keyboard.
Select qab
Click the shift button to get to shift layer
Click shift button again to revert to default. (This gets stuck w/ the console error)

**Comment by jahorton** [comment]
This has been fixed in more recent versions and is not reproduced from the current edition of KeymanWeb.
