### ISSUE TITLE
Issue with Masaram Gondi model

### ISSUE THREAD

**Issue by hinditutorpoint** [keymanapp/keyman#6503]
hi team there was an issue with Masaram Gondi model
i have created wordlist for Masaram Gondi but could not render Noto Sans Masaram Gondi font in primer and model editor also
in Android library

**Comment by mcdurdin** [comment]
Hi, this sounds like three separate issues -- but can you give us some more detail, e.g. screenshots and exact areas where you are having trouble with fonts?

**Comment by hinditutorpoint** [comment]
sorry team I have fixed issue my mistake was capitalize latter
