### ISSUE TITLE
feat: keyboard background color

### ISSUE THREAD

**Issue by hinditutorpoint** [keymanapp/keyman#6513]
hi team how can I change android keyboard background color and keys styling.

**Comment by mcdurdin** [comment]
Background color and full theming support is coming in [version 17.0](https://blog.keyman.com/2022/03/keyman-roadmap-march-2022/). You can make minor changes to theming with the CSS with [`&kmw_embedcss`](https://help.keyman.com/developer/language/reference/kmw_embedcss).

* Reference: https://help.keyman.com/DEVELOPER/engine/web/14.0/reference/osk/classes
* Examples: https://community.software.sil.org/t/css-does-not-work-on-custom-layer/4557/7
