### ISSUE TITLE
bug(iOS): stray characters in the Installed Languages page

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#6520]
**Describe the bug**

<img width="150" src="https://user-images.githubusercontent.com/28331388/162696958-21b27070-eb10-428e-95f0-3f920266cd70.png">

In the beta version of Keyman for iOS 15.0.231-beta, go to Settings and then Installed Languages to see the error.

---

**Keyman for iPhone:**
 - Device: iPhone 13 simulator
 - OS: iOS 15.4
 - Keyman version: 15.0.231-beta
 - Target application: Keyman

**Comment by mcdurdin** [comment]
That's the index feature of the list -- touch the letter to go to that part of the list. On a very short list it's not helpful, but not a bug :grin:
