### ISSUE TITLE
Keyman for iPhone and iPad - Regression Tests

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#6521]
# Keyman for iPhone and iPad Acceptance Test Procedures #

1. These test procedures are to be run before moving from alpha to beta, or beta to stable, or before PRs are merged into stable branches.
2. Copy these tests into a new issue (for tier transitions) or a comment on the PR.
3. When annotating results, use `>` at the start of a new line under the checkbox to note the result. (For an example, see #3973).

---

# User Testing
## Gather Assets for Testing ##
- [ ] Record device's iOS version
- [ ] Ensure the device is properly configured for testing and is registered with TestFlight.

At this time, Keyman for iOS does not support external keyboard input.

## Setup Steps ##
1.  Uninstall previous version of Keyman on the device (on a simulator, "Erase All Content and Settings..." under Device menu)
2. Install test build IPA (on a simulator, "iOS Simulator Image")
3. Disable internet connectivity of the device
4. Start Keyman and select **Add a keyboard for your language**
5. Verify error message "Could not reach Keyman server!" or "The Internet connection appears to be offline." is displayed
6. Click OK to dismiss.  Close Keyman app
7. On device, enable internet connectivity
8. Start Keyman
9. On initial **Get Started** menu, select "Enable Keyman as system-wide keyboard" and do any necessary system steps to enable Keyman

---

## SUITE_INSPECT: Visual Inspection of master branch
- TEST_BUILD_STATUS: ![Build Status](https://build.palaso.org/app/rest/builds/buildType:(id:Keyman_iOS_Master)/statusIcon) Verify latest CI build of [master](https://build.palaso.org/viewType.html?buildTypeId=Keyman_iOS_Master) is successful
- TEST_VERIFY_HISTORY: Verify `history.md` contains all the current changes
- TEST_VERIFY_UNIT_TESTS: Verify that all unit tests for iOS are currently passing.
    - May be integrated with the first step above once our usual CI processes include the iOS unit tests.

---

## SUITE_MENU_FUNCTIONALITY: Menu Functionality Tests, in-app##
- GROUP_IPHONE_PORTRAIT: portrait mode in iPhone
- GROUP_IPHONE_LANDSCAPE: landscape mode in iPhone
- GROUP_IPAD_PORTRAIT: portrait mode in iPad
- GROUP_IPAD_LANDSCAPE: landscape mode in iPad

### Test Cases
- **TEST_GET_STARTED**: Get Started
  - Verify touching **Add a keyboard for your language** pulls up the **keyboard search**
      - This should also be accessible as **Settings** > **Installed Languages** > **`+`**.
  - Verify touching **Enable Keyman as system-wide keyboard** pulls up Keyman's menu within iOS settings.  (11.0+ devices)
      - If older versions of iOS are supported, ensure that the help page for doing it manually is properly linked.
  - Verify touching **More info** brings up an accurate version and the main table-of-contents help page.
      - This should also be accessible as **Info** from the main menu dropdown (on phones) or as the circled-i button (on tablets).
  - Set **Don't show again** to checked, close and re-open Keyman, and verify **Get Started** menu does not appear

- **TEST_ADD_NEW_KEYBOARD**: Add New Keyboard
This menu is accessed via **Get Started** menu or **Settings** menu
  - On the device, enable internet connectivity
  - Verify a new keyboard can be downloaded and selected, say "US Basic"
  - Return to the text input screen and confirm that it operates correctly.
  - Without changing selected language, confirm that it can be cleanly deleted via the Settings menu.
  - Confirm that another keyboard is correctly selected afterward.

- **TEST_ADD_NEW_KEYBOARD_FROM_FILE**:
  - On the device, go to keyman.com on Safari
  - Search for "US Basic"
  - scroll down to keyboard details and tap to download the keyboard package (i.e. `.kmp` file)
  - open Files app and navigate to Download folder to find "basic_kbdus.kmp" and tap on it to start the installation processes
  - Keyman app should be pulled up
  - follow the screen to finish the keyboard installation
  - verity that the keyboard is correctly installed and working as expected

- **TEST_SWITCH_KEYBOARD**
  - press on the globe key
  - the keyboard menu should be shown
  - press on a keyboard to switch to, say "EuroLatin (SIL)"
  - confirm that "EuroLatin (SIL)" is now selected and ready to be used
  - swich back to "US Basic" and confirm it does as expected

- **TEST_SHARE**: Share
  - Type and verify text can be copied and shared to external app

- **TEST_KEYMAN_BROWSER**: Keyman Browser ###
  - On default page, click on text field and set system keyboard to Keyman
  - Verify can type with Keyman as system keyboard
  - Verify that predictive suggestions are properly applied when selected (using `sil_euro_latin` + English)
  - Close and reopen Keyman app

- **TEST_TEXT_SIZE**: Text Size
  - Verify text can be rescaled from Text Size 9 to 72

- **TEST_CLEAR_TEXT**: Clear Text
  - Verify text can be cleared

- **TEST_INFO**: Info
  - Verify that the Keyman iOS version is displayed; record the version
  - Verify that the Info menu options matches that of the **More Info...** option from the **Get Started** menu option.
  - Verify that the Keyman iOS version matches the version string seen at (Home Screen) > [iOS] Settings > Keyman.

- **TEST_SETTINGS**: Settings
  - Installed Languages ... Add Language
  - Select an installed language ... Add (another) Keyboard
    - Should automatically perform a filtered search based upon that language's BCP-47 code, i.e. for "English" it should be seen as shown in the screenshot below.
    <img width="150" src="https://user-images.githubusercontent.com/28331388/163088289-b467eabb-01a6-468e-81f9-2cfad38584bd.png">

  - Select an installed language ... Dictionary
    - Turn on/off 'Enable Predictions' and validate each
    - Turn on/off 'Enable Corrections' and validate each
  - Validate that when both predictions and corrections are off, banner is not visible
  - Add/Remove dictionaries - validate
  - If multiple dictionaries are available, test swapping between them

- **TEST_EUROLATIN**: `English (Eurolatin)` in-app
  - Verify that the OSK appears and fills the width the bottom of the screen
  - Verify long-press `q` key works
  - Verify long-press `k` key works
      - Verify that any predictive suggestions generated feel 'reasonable' (based upon 'k', the selected subkey, or one of its neighbors)
  - Verify uppercase layer can be selected via `SHIFT`
  - Verify number layer can be selected via `123`
  - Verify long-press `1` key works
  - Verify long-press `0` key works
  - Verify backspace, space, and enter keys work

Note that EuroLatin2, a highly customized keyboard explicitly designed for mobile, is not found; hence EuroLatin (SIL) is used for testing this instead.

- **TEST_US_BASIC**: English: `US Basic` in-app
  - Verify that the **US Basic** keyboard can be downloaded through Settings > Installed Languages > English > `+`
    - This should automatically bring up search results for **English** keyboards.
    - When the package-installer launches, English should be the one pre-selected language.
  - Install the package for both English and Tagalog by selecting both of them in the installation processes.
  - Set **English: US Basic** as the active in-app keyboard.
  - Verify that predictive text suggestions appear.
  - Set **Tagalog: US Basic** as the active in-app keyboard.
  - Verify that predictive text suggestions do _not_ appear.
  - Verify that long-press `123` key works, presenting options for a currency layer and a symbol layer.
  - Select the currency layer, then press the `£` key.
  - Verify that the keyboard outputs correctly and returns to the default layer.
  - Go to the symbol layer and press the `©` key.
  - Verify that the keyboard outputs correctly and remains on the symbol layer.
  - Revert to the default layer and ensure basic key inputs work.
  - Long-press `e` on the default layer and select a subkey.
  - Verify that the selected key produces the correct output.
  - From the `Settings > Languages > English > US Basic` menu, follow the "Help link" and ensure it displays appropriate help.
    - (Should work both online and offline)
  - From the `Settings > Languages > English > US Basic` menu, scan the QR code with a phone and test that it links to the current version of that keyboard's public download page on keyman.com.
  - Returning to the app, uninstall the **US Basic** keyboard via Settings for Tagalog.
  - Set **English: US Basic** as the active in-app keyboard.
  - Verify that the keyboard appears correctly and ensure basic key inputs work.
    - This is to ensure that uninstalling for one language doesn't adversely affect installations of the same resource for another language.
  - Uninstall the **US Basic** keyboard via Settings for English.

---

## SUITE_SYSTEM_KEYBOARD:
- GROUP_IPHONE_PORTRAIT: portrait mode in iPhone
- GROUP_IPHONE_LANDSCAPE: landscape mode in iPhone
- GROUP_IPAD_PORTRAIT: portrait mode in iPad
- GROUP_IPAD_LANDSCAPE: landscape mode in iPad

Test the following after setting Keyman as a system keyboard.

Test Cases
- **TEST_BASIC_USAGE**: ensure that the keyboards functions as expected on all layers. Please test on multiple keyboards, i.e. EuroLatin (SIL), Cameroon QWERTY keyboard and Khmer Angkor.
- **TEST_LONG_PRESS**: ensure that longpress on all applicable layers are working as intended
- **TEST_GLOBE_KEY**: ensure that a short press on the globe key switch to the next keyboard and a longpress on it open the keyboard menu where you can select a keyboard of your choice

## SUITE_SWITCH_LOCALE
- GROUP_IPHONE_PORTRAIT: portrait mode in iPhone
- GROUP_IPHONE_LANDSCAPE: landscape mode in iPhone
- GROUP_IPAD_PORTRAIT: portrait mode in iPad
- GROUP_IPAD_LANDSCAPE: landscape mode in iPad

### Test Cases
- **TEST_KM_LOCALE** 
  - from System Preferences, switch the UI language to Khmer by adding it in `Language & Region` using `+`
  - drag Khmer to the top of the list to set it as a primary UI language
  - check the dropdown menu to see it in Khmer (there is a known issue on this though, cf. https://github.com/keymanapp/keyman/issues/6527)
  - verify the UI language switch to Khmer
- **TEST_AM_LOCALE**
  - from System Preferences, switch the UI language to Amharic by adding it in `Language & Region` using `+`
  - drag Amharic to the top of the list to set it as a primary UI language
  - check the dropdown menu to see it in Amharic (there is a known issue on this though, cf. https://github.com/keymanapp/keyman/issues/6527)
  - verify the UI language switch to Amharic

---

## [TODO] SUITE_PREDICTIVE_TEXT: Predictive Text

**Comment by MakaraSok** [comment]
@keymanapp-test-bot retest all

**Comment by MakaraSok** [comment]
@bharanidharanj please don't test this now.

**Comment by bharanidharanj** [comment]
@MakaraSok  After changing UI locale to Khmer or Amharic, the corresponding UI appears correctly in the Keyman Keyboard Menu list. However, I noticed that the top row keys of Khmer Keyboard are partially appears in the In-App.

<img width="300" src="https://user-images.githubusercontent.com/19683143/163197471-0dee04a1-013b-4025-ae84-7ec9a6d320bd.png">

**Comment by bharanidharanj** [comment]
@MakaraSok Tested Keyman 15.0.232 beta build in Landscape mode in iPhone 13 Pro Simulator and here are my observations:
1. I noticed that the Predictive Text / Suggestions appears partially on the top of the banner. 
<img width="300" src="https://user-images.githubusercontent.com/19683143/163207600-f5044e2a-15fc-40f4-bd26-48ebaaf14781.png"> 

2. While using Physical Keyboard device, the texts appears only in english and not changing to the corresponding Keyboard.  
<img width="300" src="https://user-images.githubusercontent.com/19683143/163207774-15597fca-45bf-4ba1-bdeb-103b4958bf79.png">


3. Keyman Logo appears in the Keyboard banner while using Keyman as System Keyboard. 
<img width="300" src="https://user-images.githubusercontent.com/19683143/163207795-769629e5-1ad1-4e02-9d44-147a117b96c8.png">


4. QR Code is missing for the Tagalog (US Basic) Keyboard. 
<img width="300" src="https://user-images.githubusercontent.com/19683143/163207820-2d0bf456-e5d9-4c44-aa4c-73d2c1fb4556.png">

**Comment by bharanidharanj** [comment]
## SUITE_MENU_FUNCTIONALITY: Menu Functionality Tests, in-app##

### GROUP_IPHONE_PORTRAIT: portrait mode in iPhone

* **TEST_GET_STARTED (FAILED):** Tested this with the latest Keyman 15.0.235-beta build and I noticed that If I  disable 'Don't show again' option, then restarting Keyman, the 'Get Started' dialog does not appear on the Screen.
<img width="300" src="https://user-images.githubusercontent.com/19683143/163971810-347522b7-84fa-4d01-89df-b689f1827148.png">

* **TEST_ADD_NEW_KEYBOARD (PASSED):** Able to add a new Keyboard and also able to delete it using Settings Option. 
* **TEST_ADD_NEW_KEYBOARD_FROM_FILE (PASSED):** Able to install a keyboard using .kmp file. 
* **TEST_SWITCH_KEYBOARD (PASSED):** Switching from one Keyboard to other using globe key is working as expected. 
* **TEST_SHARE (PASSED):** Able to share the text to some other app line Notepad. 
* **TEST_KEYMAN_BROWSER (PASSED):** Able to use the Keyman Keyboard in Keyman Browser. 
* **TEST_TEXT_SIZE (PASSED):** Able to change the Text size from 9 to 72. 
* **TEST_CLEAR_TEXT (PASSED):** Clear Text functionality is working as expected. 
* **TEST_INFO (PASSED):** Able to to see the installed Keyman Version in the Info page and it is also reflected in More Info page too. 

Keyman Info:
<img width="300" src="https://user-images.githubusercontent.com/19683143/163972715-2f389757-7d07-4d54-bda5-91530f25d288.png">

* **TEST_SETTINGS (PASSED):** Able to install or add a Language. Banner is visible If the Predictions / Corrections are enabled. And it is not visible if they are disabled. Able to add or remove dictionaries. 
* **TEST_EUROLATIN (PASSED):** Tested this with English-EuroLatin (SIL) Keyboard and it is working as expected. 
* **TEST_US_BASIC (PASSED):** Tested this with US_BASIC (English and Tagalok) Keyboard and I noticed that everything is working fine except the QR code functionality. ie., In US Basic menu, the QR code was missing. 

<img width="300" src="https://user-images.githubusercontent.com/19683143/163971367-9ee99481-c72f-4e7f-93da-a5f44a76a4d6.png">

**Comment by bharanidharanj** [comment]
## SUITE_MENU_FUNCTIONALITY: Menu Functionality Tests, in-app##

### GROUP_IPHONE_LANDSCAPE: landscape mode in iPhone

* **TEST_GET_STARTED (FAILED):** Tested this with the latest Keyman 15.0.235-beta build and I noticed that If I disable 'Don't show again' option, then restarting Keyman, the 'Get Started' dialog does not appear on the Screen.
* **TEST_ADD_NEW_KEYBOARD (PASSED):** Able to add a new Keyboard and also able to delete it using Settings Option.
* **TEST_ADD_NEW_KEYBOARD_FROM_FILE (PASSED):**  Able to install a keyboard using .kmp file.
* **TEST_SWITCH_KEYBOARD (PASSED):** Switching from one Keyboard to other using globe key is working as expected.
* **TEST_SHARE (PASSED):** Able to share the text to some other app line Notepad.
* **TEST_KEYMAN_BROWSER (PASSED):** Able to use the Keyman Keyboard in Keyman Browser.
* **TEST_TEXT_SIZE (PASSED):** Able to change the Text size from 9 to 72.
* **TEST_CLEAR_TEXT (PASSED):** Clear Text functionality is working as expected.
* **TEST_INFO (PASSED):** Able to to see the installed Keyman Version in the Info page and it is also reflected in More Info page too.
* **TEST_SETTINGS (PASSED):** Able to install or add a Language. Banner is visible If the Predictions / Corrections are enabled. And it is not visible if they are disabled. Able to add or remove dictionaries.
* **TEST_EUROLATIN (PASSED):** Tested this with English-EuroLatin (SIL) Keyboard and it is working as expected.
* **TEST_US_BASIC (FAILED):** Tested this with US_BASIC (English and Tagalok) Keyboard and I noticed that everything is working fine except the QR code functionality. ie., In US Basic menu, the QR code was missing.

<img width="300" src="https://user-images.githubusercontent.com/19683143/163992583-50ca1993-946b-41bb-8ebc-1e8b768a84c5.png">

**Comment by bharanidharanj** [comment]
## SUITE_SWITCH_LOCALE: 

### GROUP_IPHONE_PORTRAIT: portrait mode in iPhone

* **TEST_KM_LOCALE (PASSED):** Tested this with the recent Keyman 15.0.235-beta build and it seems to be working as expected.
<img width="300" src="https://user-images.githubusercontent.com/19683143/164218593-47ac3990-fc9e-4472-b1aa-238bfd49d6da.png"> 


* **TEST_AM_LOCALE (PASSED):** Tested this with the recent Keyman 15.0.235-beta build and it seems to be working as expected.
<img width="300" src="https://user-images.githubusercontent.com/19683143/164218652-ad8235ab-7169-4ce0-854f-f7c915bc4e0c.png"> 



### GROUP_IPHONE_LANDSCAPE: landscape mode in iPhone

* **TEST_KM_LOCALE (PASSED):** Tested this with the recent Keyman 15.0.235-beta build and it seems to be working as expected.
<img width="300" src="https://user-images.githubusercontent.com/19683143/164218685-06c9bf01-48f6-4051-aea6-bf841f5c8ea6.png"> 

* **TEST_AM_LOCALE (PASSED):** Tested this with the recent Keyman 15.0.235-beta build and it seems to be working as expected.
<img width="300" src="https://user-images.githubusercontent.com/19683143/164218706-bca1d796-988d-4902-a0d8-4a9d5577cea2.png">

**Comment by bharanidharanj** [comment]
## SUITE_SYSTEM_KEYBOARD: 

### GROUP_IPAD_PORTRAIT: portrait mode in iPad

* **TEST_BASIC_USAGE (PASSED):** Tested this with the recent Keyman 15.0.235-beta build and it seems to be working as expected.
* **TEST_LONG_PRESS (PASSED):** Tested this with the recent Keyman 15.0.235-beta build and it seems to be working as expected.
* **TEST_GLOBE_KEY (PASSED):** Tested this with the recent Keyman 15.0.235-beta build and it seems to be working as expected.

### GROUP_IPAD_LANDSCAPE: landscape mode in iPad

* **TEST_BASIC_USAGE (PASSED):** Tested this with the recent Keyman 15.0.235-beta build and it seems to be working as expected.
* **TEST_LONG_PRESS (PASSED):** Tested this with the recent Keyman 15.0.235-beta build and it seems to be working as expected.
* **TEST_GLOBE_KEY (PASSED):** Tested this with the recent Keyman 15.0.235-beta build and it seems to be working as expected.

## SUITE_SWITCH_LOCALE: 

### GROUP_IPAD_PORTRAIT: portrait mode in iPad

* **TEST_KM_LOCALE (PASSED):** Tested this with the recent Keyman 15.0.235-beta build and it seems to be working as expected.
<img width="300" src="https://user-images.githubusercontent.com/19683143/164225611-22a9a43c-d697-47c9-89b6-eeeb351e1cff.png"> 


* **TEST_AM_LOCALE (PASSED):** Tested this with the recent Keyman 15.0.235-beta build and it seems to be working as expected.

### GROUP_IPAD_LANDSCAPE: landscape mode in iPad

* **TEST_KM_LOCALE (PASSED):** Tested this with the recent Keyman 15.0.235-beta build and it seems to be working as expected.

<img width="300" src="https://user-images.githubusercontent.com/19683143/164225513-318963dd-42e2-4d43-8b71-b88af8069961.png">


* **TEST_AM_LOCALE (PASSED):** Tested this with the recent Keyman 15.0.235-beta build and it seems to be working as expected.

<img width="300" src="https://user-images.githubusercontent.com/19683143/164225560-9caa0920-2d73-4a07-8854-13ee9f264e8d.png">

**Comment by MakaraSok** [comment]
@keymanapp-test-bot retest SUITE_MENU_FUNCTIONALITY GROUP_IPHONE_PORTRAIT TEST_GET_STARTED TEST_US_BASIC, SUITE_MENU_FUNCTIONALITY GROUP_IPHONE_LANDSCAPE TEST_GET_STARTED TEST_US_BASIC

**Comment by MakaraSok** [comment]
@keymanapp-test-bot retest SUITE_MENU_FUNCTIONALITY GROUP_IPAD_PORTRAIT TEST_GET_STARTED TEST_US_BASIC, SUITE_MENU_FUNCTIONALITY GROUP_IPAD_LANDSCAPE TEST_GET_STARTED TEST_US_BASIC

**Comment by MakaraSok** [comment]
Please retest all with the build from https://github.com/keymanapp/keyman/pull/6552.

@keyman-test-bot retest all

**Comment by MakaraSok** [comment]
@bharanidharanj This is to remind us that the build to use for retesting is from this PR https://github.com/keymanapp/keyman/pull/6552.

The version number of Keyman for iOS installed has to be `15.0.238-beta` or later. Please don't go for alpha just yet.

**Comment by bharanidharanj** [comment]
> @bharanidharanj This is to remind us that the build to use for retesting is from this PR #6552.
> 
> The version number of Keyman for iOS installed has to be `15.0.238-beta` or later. Please don't go for alpha just yet.

@MakaraSok Okay.

**Comment by bharanidharanj** [comment]
## SUITE_SWITCH_LOCALE: 

### GROUP_IPHONE_PORTRAIT: portrait mode in iPhone

* **TEST_KM_LOCALE (PASSED):** Tested this with Keyman 15.0.238-beta build as per the instructions in iPhone 13 Pro Simulator and it is working as expected.
* **TEST_AM_LOCALE (PASSED):** Tested this with Keyman 15.0.238-beta build as per the instructions in iPhone 13 Pro Simulator and it is working as expected.

<img width="300" src="https://user-images.githubusercontent.com/19683143/167887219-8beb61f6-651c-4fdb-b736-4fc32d22726a.png"> 



### GROUP_IPHONE_LANDSCAPE: landscape mode in iPhone

* **TEST_KM_LOCALE (PASSED):** Tested this with Keyman 15.0.238-beta build as per the instructions in iPhone 13 Pro Simulator and it is working as expected.

<img width="300" src="https://user-images.githubusercontent.com/19683143/167887294-87be558c-938d-4368-b2b0-990a2123a988.png"> 

* **TEST_AM_LOCALE (PASSED):** Tested this with Keyman 15.0.238-beta build as per the instructions in iPhone 13 Pro Simulator and it is working as expected.

**Comment by bharanidharanj** [comment]
## SUITE_SYSTEM_KEYBOARD: 

### GROUP_IPHONE_PORTRAIT: portrait mode in iPhone

* **TEST_BASIC_USAGE (PASSED):** Tested this with Keyman 15.0.238-beta build as per the instructions in iPhone 13 Pro Simulator and it is working as expected.
* **TEST_LONG_PRESS (PASSED):** Tested this with Keyman 15.0.238-beta build as per the instructions in iPhone 13 Pro Simulator and it is working as expected.
* **TEST_GLOBE_KEY (PASSED):** Tested this with Keyman 15.0.238-beta build as per the instructions in iPhone 13 Pro Simulator and it is working as expected.

### GROUP_IPHONE_LANDSCAPE: landscape mode in iPhone

* **TEST_BASIC_USAGE (PASSED):** Tested this with Keyman 15.0.238-beta build as per the instructions in iPhone 13 Pro Simulator and it is working as expected.
* **TEST_LONG_PRESS (PASSED):** Tested this with Keyman 15.0.238-beta build as per the instructions in iPhone 13 Pro Simulator and it is working as expected.
* **TEST_GLOBE_KEY (PASSED):** Tested this with Keyman 15.0.238-beta build as per the instructions in iPhone 13 Pro Simulator and it is working as expected.

**Comment by bharanidharanj** [comment]
## SUITE_SYSTEM_KEYBOARD: 

### GROUP_IPAD_PORTRAIT: portrait mode in iPad

* **TEST_BASIC_USAGE (PASSED):** Tested this with Keyman 15.0.238-beta build as per the instructions in iPad Air (5th generation) Pro Simulator and it is working as expected.
* **TEST_LONG_PRESS (PASSED):** Tested this with Keyman 15.0.238-beta build as per the instructions in iPad Air (5th generation) Pro Simulator and it is working as expected.
* **TEST_GLOBE_KEY (PASSED):** Tested this with Keyman 15.0.238-beta build as per the instructions in iPad Air (5th generation) Pro Simulator and it is working as expected.

### GROUP_IPAD_LANDSCAPE: landscape mode in iPad

* **TEST_BASIC_USAGE (PASSED):** Tested this with Keyman 15.0.238-beta build as per the instructions in iPad Air (5th generation) Pro Simulator and it is working as expected.
* **TEST_LONG_PRESS (PASSED):** Tested this with Keyman 15.0.238-beta build as per the instructions in iPad Air (5th generation) Pro Simulator and it is working as expected.
* **TEST_GLOBE_KEY (PASSED):** Tested this with Keyman 15.0.238-beta build as per the instructions in iPad Air (5th generation) Pro Simulator and it is working as expected.

## SUITE_SWITCH_LOCALE: 

### GROUP_IPAD_PORTRAIT: portrait mode in iPad

* **TEST_KM_LOCALE (PASSED):** Tested this with Keyman 15.0.238-beta build as per the instructions in iPad Air (5th generation) Pro Simulator and it is working as expected.
* **TEST_AM_LOCALE (PASSED):** Tested this with Keyman 15.0.238-beta build as per the instructions in iPad Air (5th generation) Pro Simulator and it is working as expected.

### GROUP_IPAD_LANDSCAPE: landscape mode in iPad

* **TEST_KM_LOCALE (PASSED):** Tested this with Keyman 15.0.238-beta build as per the instructions in iPad Air (5th generation) Pro Simulator and it is working as expected.
* **TEST_AM_LOCALE (PASSED):** Tested this with Keyman 15.0.238-beta build as per the instructions in iPad Air (5th generation) Pro Simulator and it is working as expected.

**Comment by MakaraSok** [comment]
## SUITE_INSPECT 
* **TEST_VERIFY_HISTORY (PASSED):** `history` to be checked live at the root of the branch being tested - `keyman/HISTORY.md`.

## SUITE_MENU_FUNCTIONALITY 
### GROUP_IPHONE_PORTRAIT 
* **TEST_US_BASIC (PASSED):** The keyboard was examined and the next layer for the currency key <kbd>£</kbd> is numeric layer, not default layer.

## SUITE_MENU_FUNCTIONALITY 
### GROUP_IPHONE_LANDSCAPE 
* **TEST_US_BASIC (PASSED):** The keyboard was examined and the next layer for the currency key <kbd>£</kbd> is numeric layer, not default layer.

## SUITE_MENU_FUNCTIONALITY 
### GROUP_IPAD_PORTRAIT 
* **TEST_US_BASIC (PASSED):** The keyboard was examined and the next layer for the currency key <kbd>£</kbd> is numeric layer, not default layer.

## SUITE_MENU_FUNCTIONALITY 
### GROUP_IPAD_LANDSCAPE 
* **TEST_US_BASIC (PASSED):** The keyboard was examined and the next layer for the currency key <kbd>£</kbd> is numeric layer, not default layer.
