### ISSUE TITLE
bug(ios): memory leak when rotating device

### ISSUE THREAD

**Issue by sgschantz** [keymanapp/keyman#6547]
**Describe the bug**
While trying to debug system keyboard issues in iOS, each time the device is rotated, a new 'keyman' instance appears in Safari's Develop menu.

**To Reproduce**
1. Run Keyman for iOS extension SWKeyboard from Xcode on an actual iPhone, attaching to Safari
2. Click on the url textedit to bring up the system keyboard
3. choose the Keyman menu from the keyboard picker so that Xcode attaches to the process
4. Open the Develop menu in Safari and see the keyman instance under the iPhone submenu
5. See a keyman instance added each time the phone is rotated

**Expected behavior**
Should only ever see one keyman instance in the Safari debugger while running the Keyman extension

**Screenshots**

![image](https://user-images.githubusercontent.com/89134789/164198624-338f8fb0-05fe-4a03-a2d8-0de8e85196b7.png)

Also note that memory usage steps up as the phone is rotated:

![image](https://user-images.githubusercontent.com/89134789/164198905-87b0b7c7-97c5-49e6-aeb2-082c6f247626.png)

**Comment by jahorton** [comment]
This is highly related to #2300, though I suppose it isn't exactly identical.  A noted aspect is that the old keyboard extension instance effectively crashes; this issue notes a memory leak that results from how that 'crash' is handled.

Fixing _this_ won't outright #2300, but it may help with mitigation of it.
