### ISSUE TITLE
bug(windows): there is a discrepancy where the behavior of soft key is different from that of the actual device when it comes to caps lock

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#6556]
**Describe the bug**

Issue encountered at: https://github.com/keymanapp/keyman/issues/6377#issuecomment-1106239115 on all Windows OSes.

Build for the test: [15.0.234](https://downloads.keyman.com/windows/beta/15.0.234/keyman-15.0.234.exe)
Keyboard for test: [caps lock.zip](https://github.com/keymanapp/keyman/files/8539542/caps.lock.zip)

Reproable on VMs:

> - **TEST_CAPSLOCK-2**: lowercase with virtual key
>   - press and hold 'Shift'
>   - press and release `b`
>   - release `Shift`
> 
>   Expected result:
>   - `pass.` (with other keyboards lowercase `b`)

**Expected behavior**

Both VM should behave in the same way the actual device does when it comes to this test case.

**Comment by rc-swag** [comment]
See [comment](https://github.com/keymanapp/keyman/issues/6377#issuecomment-1109574276) 26 Apr.   With the correct version keyman version, this test was actually passed.
