### ISSUE TITLE
bug(windows): Keyman configuration freezes - user reported and sentry log

### ISSUE THREAD

**Issue by rc-swag** [keymanapp/keyman#6570]
**Describe the bug**
Reported for Community Forum [Here](https://community.software.sil.org/t/keyman-configuration-freezes/6168)
My Keyman configuration suddenly froze with the following error message.

Details for error report for Keyman app:
Application Identifier: kmshell-14.0.290
Error Identifier: 3CEECA79EBD44E6A3F952B966C69035A
The dialogue box displays permanently on the screen without responding to the close button.

The sentry report [here](https://sentry.io/share/issue/49977c3728a8402f993c1b046a148590/#exception)
Shows an invalid argument when running "Initprog.Run" in InitProg.Run 
EVariantInvalidArgError: Exception EVariantInvalidArgError in module kmshell.exe at 0003BE98.
Invalid argument.
**Summary Stack trace**
  kmshell             0x2c43be98   System.Variants.TranslateResult (System.Variants.pas:1)
  kmshell             0x2c43bf4c   System.Variants.VarResultCheck (System.Variants.pas:1)
  kmshell             0x2c4453fc   System.Variants.VarArrayLowBound (System.Variants.pas:1)
  kmshell             0x2c8b795b   KeyboardListXMLRenderer.TKeyboardListXMLRenderer.XMLData (KeyboardListXMLRenderer.pas:120)
  kmshell             0x2c8b1d90   XMLRenderer.TXMLRenderer.GetXMLData (XMLRenderer.pas:134)
  kmshell             0x2c8b23c2   XMLRenderer.TXMLRenderers.RenderToString (XMLRenderer.pas:219)
  kmshell             0x2c968084   UfrmMain.TfrmMain.Do_Content_Render (UfrmMain.pas:306)
  kmshell             0x2c967cdf   UfrmMain.TfrmMain.TntFormCreate (UfrmMain.pas:242)
  kmshell             0x2c646a6a   Vcl.Forms.TCustomForm.DoCreate (Vcl.Forms.pas:1)
  kmshell             0x2c6465ca   Vcl.Forms.TCustomForm.Create (Vcl.Forms.pas:1)
  kmshell             0x2c8c3635   UfrmWebContainer.TfrmWebContainer.Create (UfrmWebContainer.pas:158)
  kmshell             0x2c651cb8   Vcl.Forms.TApplication.CreateForm (Vcl.Forms.pas:1)
  kmshell             0x2c8c3436   UfrmWebContainer.CreateForm (UfrmWebContainer.pas:127)
  kmshell             0x2c97d109   initprog.Main (initprog.pas:165)
  kmshell             0x2c97e524   initprog.RunKMCOM (initprog.pas:519)
  kmshell             0x2c97ded0   initprog.Run (initprog.pas:340)
  kmshell             0x2c992cee   kmshell.kmshell
  KERNEL32.DLL        0x7539fa28   BaseThreadInitThunk
  ntdll               0x772b7a7d   __RtlUserThreadStart
  ntdll               0x772b7a4d   _RtlUserThreadStart

**Keyman for Windows:**
version: 14.0.290 
Windows Version: Unknown.

**Comment by rc-swag** [comment]
Further notes from sentry
The oldest version it appears in is 14.0282
The command line always has the -c option 
`C:\Program Files (x86)\Keyman\Keyman Desktop\kmshell.exe\" -c"`

**Comment by rc-swag** [comment]
> The command line always has the -c option

I'm not so sure about this looking at it after break. I do not think it needs an argument of at -c.

**Comment by mcdurdin** [comment]
> I do not think it needs an argument of at -c.

Note that Configuration dialog can also be opened from the Splash screen.

**Comment by mcdurdin** [comment]
Closing with no repro at this point, no further reports that we saw in Sentry.
