### ISSUE TITLE
bug(windows): AltGr and AltGr+Shift don't output expected character in 15.0.239

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#6576]
**Describe the bug**

<kbd>Alt</kbd> and <kbd>Alt</kbd>+<kbd>Shift</kbd> layers on the latest beta version doesn't output anything, while the latest stable version does produce the expected output.

|  | <kbd>Alt</kbd>+<kbd>1</kbd> | <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>1</kbd> |
| -- | --- | --- |
| Keyman 14.0.290 | + | ᧬ |
| Keyman 15.0.239 | (beep) | (beep) |

**To Reproduce**

1. Install the latest stable version and Khmer Angkor keyboard
2. In Notepad, switch to the keyboard and type <kbd>Alt</kbd>+<kbd>1</kbd> and <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>1</kbd>
3. Notice the outputs shown in the table above
4. Uninstall Keyman and reinstall the latest beta version (restart if required), then install the Khmer Angkor keyboard
5. In Notepad, switch to the keyboard and type <kbd>Alt</kbd>+<kbd>1</kbd> and <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>1</kbd>
6. See error - no output

---

**Keyman for Windows:**
 - OS: Windows 10 Pro 21H2 x64
 - Keyman version: 14.0.290 stable and 15.0.239-beta
 - Target Application: Notepad

---

**Keyboard**
 - Keyboard name: khmer_angkor
 - Keyboard version: 1.2
 - Language name: Khmer

**Additional context**

related bug: https://github.com/keymanapp/keyman/issues/6571

**Comment by rc-swag** [comment]
I have been able to prove that was a regression introduced by  [PR](https://github.com/keymanapp/keyman/pull/6392) #6392
so beta build 229 works and 230 or greater doesn't

**Comment by rc-swag** [comment]
This issue was fixed with PR #6580
