### ISSUE TITLE
bug(android): the spacebar caption doesn't get refresh until after switching to a different keyboard 

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#6603]
**Describe the bug**

While testing this PR https://github.com/keymanapp/keyman/issues/6336, @bharanidharanj found that the spacebar caption doesn't get changed according to the option chosen in the Settings.

It turns out that it would change to the caption option selected in the Settings after switching to a different keyboard using the globe key.

This happens on all tested versions of Android, v5, v8.1, v10 and v11. Please focus on the text on the spacebar of the screenshots in the table below.

| Selected Caption | Before Switching KB via globe key | After Switching KB via globe key |
| --- | --- | --- |
| 1. Default <br/>(Expected: <br/>[Language] + [Keyboard])| <img width="300" alt="image" src="https://user-images.githubusercontent.com/28331388/167796292-b5ea9151-9ad1-4396-a103-18bf06e2f2b5.png"> | <img width="300" alt="image" src="https://user-images.githubusercontent.com/28331388/167796292-b5ea9151-9ad1-4396-a103-18bf06e2f2b5.png"> |
| 2. Language <br/>Expected: Basaa | <img width="300" alt="image" src="https://user-images.githubusercontent.com/28331388/167796751-3686988e-ea5a-4637-ae83-07a05faf48d4.png"> | <img width="300" alt="image" src="https://user-images.githubusercontent.com/28331388/167796888-7eb1cb34-a4fc-4535-9051-c91600a727ff.png"> |
| 3. Keyboard <br/>Expected: <br/>Cameroon QWERTY| <img width="300" alt="image" src="https://user-images.githubusercontent.com/28331388/167796888-7eb1cb34-a4fc-4535-9051-c91600a727ff.png"> | <img width="300" alt="image" src="https://user-images.githubusercontent.com/28331388/167797246-7d976ccf-c27c-497b-96a2-84fa1c473e67.png"> |
| 4. Language + Keyboard <br/>Expected: <br/> Basaa - Cameroon QWERTY | <img width="300" alt="image" src="https://user-images.githubusercontent.com/28331388/167797246-7d976ccf-c27c-497b-96a2-84fa1c473e67.png"> | <img width="300" alt="image" src="https://user-images.githubusercontent.com/28331388/167797814-bd65ab43-781c-409b-9585-6763c7eed74b.png"> |
| 5. Blank <br/>Expected: [nothing] | <img width="300" alt="image" src="https://user-images.githubusercontent.com/28331388/167797814-bd65ab43-781c-409b-9585-6763c7eed74b.png"> | <img width="300" alt="image" src="https://user-images.githubusercontent.com/28331388/167797976-b1dcc568-75ff-445e-a08c-6b535a0a9c0d.png"> |

**To Reproduce**

1. Go to 'Settings'
2. Click on 'Spacebar caption'
3. Choose 'one of the options' and observe before and after clicking on the globe key

**Expected behavior**

The selected option for Spacebar caption should happen instantly, shouldn't it?

---

**Keyman for Android:**
 - Device: Any
 - OS: Any
 - Keyman version: 15.0.245-beta
 - Target application: Keyman

**Comment by darcywong00** [comment]
Fixed by #6620

**Comment by MakaraSok** [comment]
This issue re-emerges in the latest alpha (16.0.56-alpha).

**Comment by darcywong00** [comment]
@bharanidharanj - Can you test this on the current [16.0.69 alpha](https://downloads.keyman.com/android/alpha/16.0.69/keyman-16.0.69.apk) and see if this is still an issue?
In my testing, it seemed the caption was correctly updating after exiting the Settings menu (without having to switch keyboard)
