### ISSUE TITLE
bug(android): 'Cut, Copy, Share and Select all' options are missing after selecting a word in the Text Area

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#6611]
**Describe the bug**
In the Text Area, the Cut, Copy, Share and Select all options are missing after Selecting a word. 

**To Reproduce**
1. Open Keyman Keyboard. 
2. Type any word in the text area. 
3. Double click on the word. 
4. We may notice that the word has been selected and showing only one option "Paste". 
Seems to be an issue. 

**Expected behavior**
The Options layer should contains "Cut, Copy, Paste, Share and Select all" 

**Screenshots**
..in Android 5.0 Version:
<img width="300" src="https://user-images.githubusercontent.com/19683143/168286738-728e6dd7-226e-42dc-802f-a9a40e212e05.PNG"> 

..in Android 10.0 Version:
<img width="300" src="https://user-images.githubusercontent.com/19683143/168286753-e710fa7e-a468-44b2-8d95-2393de21b955.PNG"> 

---

**Keyman for Android:**
 - Device: Android API 21 emulator
 - OS: <Android 5.0 Lollypop -->
 - Keyman version <15.0.246-beta build>
 - Target application: <Keyman>

---

**Keyboard**
 - Keyboard name: English - EuroLatin (SIL)
 - Keyboard version: 1.9.6
 - Language name: English

**Additional context**
Tested the same in Android 11 Version and it is showing all the options.

**Comment by darcywong00** [comment]
On Android 5.0, the device displays the highlighted bar which contains the actions for Cut, Copy, Paste, etc...
![cut copy](https://user-images.githubusercontent.com/7358010/168519991-dfa34cd0-b631-449a-ae80-10715d21bf4d.png)

I've tested on the Android 5.0 emulator and get the same behavior with the default Android keyboard and with Keyman.

**Comment by bharanidharanj** [comment]
> On Android 5.0, the device displays the highlighted bar which contains the actions for Cut, Copy, Paste, etc... ![cut copy](https://user-images.githubusercontent.com/7358010/168519991-dfa34cd0-b631-449a-ae80-10715d21bf4d.png)
> 
> I've tested on the Android 5.0 emulator and get the same behavior with the default Android keyboard and with Keyman.

@darcywong00 Thanks for the Clarification.
