### ISSUE TITLE
bug(web): character on the subkey got output when fast typing

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#6646]
**Describe the bug**

When typing very quickly on iPad, the character on the neighboring keys get output. Try and type the word "you" very quickly and you'll somehow get something totally not what you expect. Please see the screen recording below.

https://user-images.githubusercontent.com/28331388/169770520-aee5f11c-71b2-4684-ad0c-64c38f9e0eff.mov

**Expected behavior**

This issue seems to occur only in iOS. I was not able to repro it on Android running Keyman 15.0.250-beta.

---

**Keyman for iPad:**
 - Device: iPad mini 6
 - OS: iOS 15.5
 - Keyman version: 15.0.249-beta-test-6633 (TestFlight: 0.6633.6275)
 - Target application: Keyman

---

**Keyboard**
 - Keyboard name: EuroLatin (SIL)
 - Keyboard version: 1.9.6
 - Language name: English

**Comment by jahorton** [comment]
I suspect that something may be bit off with the "flick up" longpress shortcut that's effectively eliminated it; that'd make it far easier for subkeys to trigger when not expected.

Probably related:  I noticed that the "roaming touch" (moving key preview mode) is broken whenever it is triggered on a key with subkeys, even if it wasn't the original base key of the "roaming touch."

**Comment by jahorton** [comment]
Very careful examination of the video proves that the subkey menu is being triggered here:

Both images were taken around the 0:04 mark.

![image](https://user-images.githubusercontent.com/25213402/172079926-7bef71c4-3e8b-4a34-84ba-2fae3aa6927e.png)

![image](https://user-images.githubusercontent.com/25213402/172079957-95ecbbbc-c06f-480d-a3de-70f065da4662.png)

**Comment by jahorton** [comment]
@MakaraSok 

One major request I'd like to run for comparison, while we still can - could you please install the latest `stable` version via the App Store and test if it occurs with 14.0?

**Comment by MakaraSok** [comment]
I cannot get it to fail in neither iPad mini 6 nor iPod touch 7th gen.

screenshot from the iPod 
![image](https://user-images.githubusercontent.com/28331388/172280822-22592c0a-4e6c-430b-b8b6-efe909aa1a4a.png)

**Comment by jahorton** [comment]
From https://github.com/keymanapp/keyman/pull/6714#issuecomment-1148105649:

> Worth note:  in 14.0, the subkey quick-display shortcut was broken; longpresses would only result from waiting out the longpress timer.  This was fixed during 15.0.
> - Note https://github.com/keymanapp/keyman/pull/5387/files#r660258571; the 15.0 PR #5387 appears to be when the behavior was fixed.
