### ISSUE TITLE
bug(developer): font defined for the keyboard doesn't get applied else where in the web debug mode

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#6651]
**Describe the bug**

It looks very weird to see different fonts show on the same screen for a given keyboard. In the screenshot below, you can see 1, 2 and 3 are in a default font, while that of the keyboard layout is of the developer defined font (Khmer Mondulkiri).

![image](https://user-images.githubusercontent.com/28331388/169942326-60320b10-5580-4995-95bd-3197bc2ef030.png)

**Expected behavior**

The default font may be used if the developer doesn't define a font for yet keyboard.

---

**Keyman Developer:**
 - OS: Windows 10 Pro 21H2 x64 (19044.1706) 
 - Keyman Developer version: 15.0.221-beta

---

**Keyboard**
 - Keyboard name: Brao (SIL) - `sil_brao`
 - Keyboard version: 1.0
 - Language name: Brao

**Comment by mcdurdin** [comment]
This appears just to be a config issue with sil_brao. Note that the Keyboard/Keyboard Fonts dialog box shows the following in sil_brao:

![image](https://user-images.githubusercontent.com/4498365/171762409-b27cdb25-f56f-4bdc-a9b7-58e2368227f1.png)

When I change it to use Khmer Mondulkiri for the Debugger, Editor Characters field:

![image](https://user-images.githubusercontent.com/4498365/171762553-44fa5ee0-983e-4bba-a7ee-1021d4d23e99.png)

Then I get the expected font in the Web Debugger:

![image](https://user-images.githubusercontent.com/4498365/171762519-620df3d8-6723-4abe-9de2-7075ecdcc4fd.png)
