### ISSUE TITLE
bug(android/engine): Don't vibrate on hardware keys

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#6665]
Follow-on to #6626

The original implementation of haptic feedback has the device vibrating whenever the keyboard generates output, and doesn't differentiate between OSK and hardware keys.

> Minor idea: device rather than keyboard vibrates.
> 
> Also, that makes me ask: does the device vibrate if you type on the hardware keyboard? Because that would be bad!

_Originally posted by @mcdurdin in https://github.com/keymanapp/help.keyman.com/pull/556#pullrequestreview-985704709_

**Comment by jahorton** [comment]
🐝  🐝  🐝
