### ISSUE TITLE
Keyboard Test Host fails to install keyboard

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#668]
Using Keyman Developer 10.0.1040.0, I can connect to the **Keyboard Test Host** from the Android emulator. However, "Install Keyboard into Keyman app" fails to install the keyboard (Khmer Angkor).

The confirmation dialog appears, but investigate if there's a connection issue preventing the keyboard from installing

**Comment by mcdurdin** [comment]
I'm working on resolving this in the debugger. Now working on Android; not yet on iOS. PRs not quite ready yet.
