### ISSUE TITLE
bug(Web): Show On Screen Keyboard is not working in Keyman Web 

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#6685]
**Description**
On Screen Keyboard appears at the right corner of the Keyman Web bar is not working consistently. 

**To Reproduce**
1. Go to 'KeymanWeb.com(beta)' site. 
2. Click on 'Languages' drop down list. 
3. Click on 'Asia' label name. 
4. Scroll down to 'Tamil'
5. Verify that the Tamil language appears on the Keyboard bar. 
6. Click on the Text Area.
7. Verify that the OSK appears at the bottom of the Text Area. 
8. Verify that the Keyboard icon which appears at the top right corner of the Windows is enabled.
9. Click on the Close button on the OSK. 
10. Verify that the OSK disappears on the Screen. 
11. Click once again on the text area. 

Here, I noticed that OSK is missing under the Text Area. 

---
**Expected behavior**
The On Screen Keyboard should appear under the text area, after enabling the Keyboard Icon.

**Screenshots**
<img width="300" src="https://user-images.githubusercontent.com/19683143/170725441-0aeb1bc8-aff6-4c11-8f2d-6b80bf64f7bd.PNG"> 

---

**KeymanWeb:**
 - OS: Windows 10, Mac OS 12.1 Monterey, Windows 11
 - Browser:  Chrome, Firefox
 - KeymanWeb Version: 15.0.252
 - URL:  https://keymanweb.com/#ta,Keyboard_basic_kbdintam
 - 
---

**Additional context**
Only reproducible in Keymanweb.com Site.

**Comment by mcdurdin** [comment]
> Or is there something I'm missing?

I think you are right. But is there something still going wrong?

**Comment by jahorton** [comment]
Ah, and the _other_ part is due to an interesting aspect of `kmwuitoolbar.ts` when compared with the other 3 - it doesn't include calls to `keymanweb['activatingUI']`, which lets KMW know not to clear the active element when interacting with the UI modules.  This prevents the OSK from displaying until the user clicks out of the text area and back again, even _after_ the minification issue is resolved.

**Comment by jahorton** [comment]
Whoops, looks like this didn't get closed when the PR merged.  Closing now.
