### ISSUE TITLE
bug: [iOS] Bottom row cropped

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#6699]
**Describe the bug**
in iOS, bottom row keys are cropped

this was seen in Keyman version 15 beta version

Same issue can be seen in the screenshot under below issue (Keyman 15.0.238 beta)
https://github.com/keymanapp/keyman/issues/6604

It can also be seen in the other images posted in this pull request (Keyman 15.0.252-beta)
https://github.com/keymanapp/keyman/pull/6658 

no evidence of this issue is seen in screenshots under (Keyman 15.0.103 alpha)
https://github.com/keymanapp/keyman/issues/5646

This issue has started between 15.0.103 and 15.0.238

**To Reproduce**
launch Keyman keyboard in iOS

**Expected behavior**
No cropping

**Screenshots**
![IMG_4018](https://user-images.githubusercontent.com/14062593/171506956-a8850e66-322d-473c-958c-efa28cd32d3f.jpeg)
![IMG_4019](https://user-images.githubusercontent.com/14062593/171506959-52b5f038-05d9-4c57-9d36-f9274d6d32a7.jpeg)

**Keyman for iPhone/iPad/Android:**
 - Device: iPhone 13 pro max
 - OS: iOS 15.5
 - Keyman version 15.0.255-beta
 - Target application: Notes, Keyman

**Keyboard**
 - Keyboard name:  Euro SIL (repeatable with any keyboard)
 - Keyboard version: latest
 - Language name: English

**Comment by MayuraVerma** [comment]
Just curious, v15 stable will not be released?
will it v16 stable instead of v15

**Comment by mcdurdin** [comment]
> Just curious, v15 stable will not be released? will it v16 stable instead of v15

We will be releasing 15.0 stable soon. We've had a couple of issues which have delayed release, plus team members who have had family illnesses taking them offline for significant amounts of time. So please bear with us.
