### ISSUE TITLE
bug(linux): Compatibility issues with Open Office on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#6728]
**Describe the bug**

Keyman doesn't output the expected characters in Apache OpenOffice 4.1.12 on Linux 22.04 LTS when using complex script keyboards, i.e. https://keyman.com/keyboards/itrans_devanagari_hindi or https://keyman.com/keyboards/khmer_angkor. Latin characters are output instead.

<img width="1430" alt="image" src="https://user-images.githubusercontent.com/28331388/172542178-e9e15f20-da71-4b12-873c-05c2f15b58d8.png">

**Expected behavior**

The keyboard should output the expected characters of the complex script keyboards.

---

**Keyman for Windows/macOS/Linux:**
 - OS: Ubuntu 22.04 LTS
 - Keyman version: 15.0.243-beta
 - Target Application: openoffice4

**Additional context**

Original post on the community site: https://community.software.sil.org/t/problems-using-a-hindi-keyboard-on-ubuntu/6302/5

**Comment by ermshiperete** [comment]
Could this be a similar problem as in #6193?

**Comment by MakaraSok** [comment]
The two Keyman keyboards work when tweaking the OO Options. From the within the `Options` under `Language Settings`, click on `Languages` and then check `Show UI elements for East Asian writings` and the other one under `Enhanced language support`. 

![image](https://user-images.githubusercontent.com/28331388/172794706-20593430-557b-4847-b339-d6de6a0bf483.png)

Afterwards, The `Default languages for documents` would have `Asian` and `CTL` enabled and Hindi or Khmer can be selected from the dropdown menu of `CTL`.
![image](https://user-images.githubusercontent.com/28331388/172794631-485744e7-da10-4e4a-97e7-2048e32bcba0.png)

Now, try and type in Hindi or Khmer to see the expected characters output.
![image](https://user-images.githubusercontent.com/28331388/172794867-70e59f73-cebe-4a11-a7df-0e9610601453.png)

**Comment by MakaraSok** [comment]
Keyman works and outputs the expected characters in terminal in Xorg and Wayland, but nothing at all in OpenOffice 4.1.12.

https://community.software.sil.org/t/problems-using-a-hindi-keyboard-on-ubuntu/6302/17

**Comment by ermshiperete** [comment]
Closing this issue since it might be fixed by #7079. Feel free to re-open.
