### ISSUE TITLE
feat: Shift key works as Caps-lock on touch keyboards 

### ISSUE THREAD

**Issue by rovasiras** [keymanapp/keyman#6729]
Shift key works as Caps-Lock on Android.
Detected in: EuroLatin,  Old Hungarian and Hungarian basic layouts.
It would be better, if single click would work as Shift, double click would work as Caps-lock, as in other keyboard projects do.

**Comment by mcdurdin** [comment]
Thanks for putting this in. This is coming in 15.0 (due for release very shortly). Existing keyboards will need to be updated but Keyman itself will have full support for Caps Lock. See https://help.keyman.com/developer/language/guide/casing-support
