### ISSUE TITLE
bug(developer): two OSK shown in the Test Keyboard on web

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#6730]
**Describe the bug**

Usually an OSK shown in the box under the text box is shown, but with the latest beta version (15.0.258) there are two.

<img width="1430" alt="image" src="https://user-images.githubusercontent.com/28331388/172574893-5596ac71-e78e-46d9-9b03-97163fc14fdf.png">

**Expected behavior**

The OSK attached to the text box shouldn't have been shown. 

---

**Keyman for Windows/macOS/Linux:**
 - OS: Windows 10 Pro 21H2 x64
 - Keyman version: 15.0.258-beta
 - Target Application: Chrome 102.0.5005.63 (Official Build) (64-bit)

**Comment by mcdurdin** [comment]
Can you check earlier versions to find which version this issue arose in?

**Comment by mcdurdin** [comment]
I have managed to reproduce this once on 15.0.258-beta. But I cannot find a consistent repro. Do you have any ideas?

**Comment by jahorton** [comment]
My initial guess is that someone tried to interact with the page while still in a "flash of unstyled content"-like state.  If the page doesn't stabilize before the first click into the text area, there's a chance that users will get to interact with the standard OSK before it's replaced by the "inlined" version.

So, related questions:
- How quickly did the page seem to load when this occurred?
- How quickly did you try to start interacting with it?

**Comment by MakaraSok** [comment]
The speed of the recoding is by default, 1x. One noticeable pattern is that the double OSK is only seen once when first built and tried. 

https://user-images.githubusercontent.com/28331388/173985274-158d1ff2-9a34-4769-aa75-eab7d40bff94.mov

**Comment by MakaraSok** [comment]
The test above was done on Win11, Keyman Developer 15.0.260-stable.

**Comment by mcdurdin** [comment]
> My initial guess is that someone tried to interact with the page while still in a "flash of unstyled content"-like state. If the page doesn't stabilize before the first click into the text area, there's a chance that users will get to interact with the standard OSK before it's replaced by the "inlined" version.

Yes. There is a race condition here in the initialisation order. The way the page in question uses KeymanWeb (and KeymanWeb itself) has several issues, I think, that are complicating factors:

1. KeymanWeb's cookies remembering which keyboard was active (we don't really want this behaviour here but should leave that to the page to specify, alongside its management of keyboards, models and packages). Is it possible to override this behaviour in KMW?
2. Using attachType=auto (we should attach manually to `ta1` when ready)
3. The page is not using making use of the promise response from `keyman.init` for further steps which are in `window.onload`
4. And following on from 3, putting a lot of behaviour into `window.onload`, including focusing the active control.

You can see, for example, repeatedly reloading the page causes the wrong keyboard to load. I suspect the display of the OSK is related to this also.

One way for us to repro this is probably to introduce server-side delays on each of the scripts loaded and in that way control the init order.

**Comment by jahorton** [comment]
> 1. Is it possible to override this behaviour in KMW?

We do not currently provide this via API.  Of course, we could always have the debug host page nuke it manually - the cookie details are perfectly visible in KMW code.

Also note that if the previous run last used a keyboard not even included on a page's current run, it'll silently ignore that cookie setting.
