### ISSUE TITLE
bug(android): "update pending" icon on tablets is not responsive

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#6731]
**Describe the bug**
Detected while addressing #6698.  Original notes may be found @ https://github.com/keymanapp/keyman/issues/6698#issuecomment-1149501856.

Pretty much what the title says; the batch-update icon displayed on tablets doesn't actually _do_ anything when a user attempts to interact with it.

**To Reproduce**

1. Download an [old version of sil_cameroon_qwerty](https://downloads.keyman.com/keyboards/sil_cameroon_qwerty/6.0.4/sil_cameroon_qwerty.kmp)
2. On the device, set airplane mode on (turns off internet access)
3. On the device, go to settings, and manually set the date to 1 year in the past (e.g. May 2021)
4. Start Keyman for Android
5. From the Keyman Settings, install the local kmp file sil_cameroon_qwerty.kmp (will be an old version 6.0.4)
6. Close Keyman
7. On the device, go to settings and set the date to automatically update from internet
8. On the device, turn off airplane mode (turns on internet access)
9. On the device, go to settings and verify the date is updated
10. Launch Keyman for Android
11. Dismiss "Get Started" and wait for the catalog to update
12. After a while, there should be a notification of a keyboard update being available
13. Verify keyboard update is available; there should be an icon of a cloud with a down arrow at the top right.
14. Click on that button - "Install Updates"
15. ... watch it do nothing.

**Expected behavior**

15. A confirmation dialogue should appear.
16. Accept "Download" on the dialogue
17. Verify resource is updated after background download complete

**Other Notes**
It is still possible to update the resource by going to its specific section in the Installed Languages menu.  It's just not possible for a user to batch-update through that icon.

---

**Keyman for Android:**
 - Device: Galaxy Tab A
 - OS: Android 6.0
 - Keyman version: 16.0.11-alpha-test-6525.
     - Note that there is no real difference in the Android code here from that found in 15.0.258-beta.
 - Target application: Keyman

**Comment by mcdurdin** [comment]
Postponed for now -- we don't have the resources to tackle this one at present.

**Comment by darcywong00** [comment]
I might be able to squeeze this one into 16.0 beta.

Would be able to get the update icon to appear (but not include the blue notification number)

**Comment by darcywong00** [comment]
Fixed in 16.0 beta by #7832
