### ISSUE TITLE
bug(android): default language for keyboard installs even after unselected

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#6732]
**Describe the bug**
Detected while addressing https://github.com/keymanapp/keyman/issues/6698. Original notes may be found @ https://github.com/keymanapp/keyman/issues/6698#issuecomment-1149501856.

When using keyboard search to find a package, it is possible for keyboards to be language tagged as part of the search results.  For multi-lingual keyboards, it is possible for the user to prefer a different language selection, though.

When the package installer displays, it will auto-select the default language... but the user is allowed to deselect it.  However... deselection of that language may be ignored by the app/engine!

**To Reproduce**

While this is likely reproducible with other searches, I will describe the exact search & results that led to the detection of this bug.

1. On the device, enable internet connectivity
2. Touch "Install from keyman.com"
3. In the search bar, type `cameroon`.
4. Select `sil_cameroon_qwerty`.
5. The package installer should then display.
6. Note the language that has been automatically selected, then deselect it.
    - Possibly-important note:  the auto-selected language was "Baka".
    - If there is no auto-selected language... we'll need a new repro, obviously.
7. Select a different language.
    - I selected "Pinyin".
8. Click the "Install" button at the bottom right.
9. Dismiss the "welcome" page that displays after installation.
10. Open the Settings menu, then Installed Languages.
11. Note that despite selecting installation for only one language... the keyboard was installed for two!
    - In the original sequence, there was an installation for both "Baka" and "Pinyin".

**Expected behavior**
`sil_cameroon_qwerty` should not have been installed for the "Baka" language, as its language option was explicitly deselected.

---

**Keyman for Android**:

- Device: Galaxy Tab A
- OS: Android 6.0
- Keyman version: 16.0.11-alpha-test-6525.
    - Note that there is no real difference in the Android code here from that found in 15.0.258-beta.
- Target application: Keyman

**Comment by darcywong00** [comment]
Clarifying steps to repro.

In order for the keyboard search to pre-select "Baka", the keyboard search needs to search for `l:id:bck` (for bck-Latn).

**Comment by darcywong00** [comment]
Aha, BCP 47 case sensitivity bites us again.
Generally, we use `Util/BCP47.languageEquals()` to compare language tags.
But the language picker menu uses a temporary list so `.contains()` doesn't detect that bkc-latn == bkc-Latn.

This definitely is the cause of #6733 as "de-selecting" Baka is actually ends up installing the keyboard for "3" languages:
bkc-latn (Baka)
bkc-Latn (also Baka)
pny-latn (Pinyin)
