### ISSUE TITLE
bug(android): keyboard remains active after deinstallation

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#6733]
**Describe the bug**

Detected while addressing https://github.com/keymanapp/keyman/issues/6698. Original notes may be found @ https://github.com/keymanapp/keyman/issues/6698#issuecomment-1149501856.

When uninstalling keyboards, it is possible for one of the uninstalled keyboards to remain active within the app - even if the keyboard is fully uninstalled for all languages!

**Note**:  this was discovered at the same time as #6732.  In fact, it occurred _during confirmation of that issue_.  There is a chance that the exact sequence for reproduction may matter greatly, despite its length.  Hopefully we can get a less lengthy repro, but... yeah.

**To Reproduce**

While this is likely reproducible with other searches and/or prior states, I will describe the exact search & results that led to the detection of this bug.

**Reproduction, Phase 1**:  Original setup

1. On the device, enable internet connectivity
2. In the Settings menu, go to "Install a keyboard", then touch "Install from keyman.com"
3. In the search bar, type `cameroon`.
4. Select `sil_cameroon_qwerty`.
5. The package installer should then display.
6. Note the language that has been automatically selected, then deselect it.
    - Possibly-important note:  the auto-selected language was "Baka".
    - If there is no auto-selected language... we'll need a new repro, obviously.
7. Select a different language.
    - I selected "Pinyin".
8. Click the "Install" button at the bottom right.
9. Dismiss the "welcome" page that displays after installation.
10. Open the Settings menu, then Installed Languages.
11. Note that despite selecting installation for only one language... the keyboard was installed for two!
    - In the original sequence, there was an installation for both "Baka" and "Pinyin".
    - This is noted as #6732.

It's possible that the sequence above may not be critical.  I suspect that the following details are at least somewhat relevant:

1.  **CRITICAL**: A single keyboard has been installed for two languages.
2. **CRITICAL**: The user _never left the Settings menu_ - even moving forward with the rest of this repro!
    - Note:  after installing a new keyboard, we auto-select it as the currently-active keyboard.
    - The keyboard hasn't been displayed to the user at this stage... and if we didn't immediately uninstall it afterward, we'd expect to see it. (See: the previous bullet point.)
3. One of those language pairings ended up in the "first slot" in the Installed Languages menu.
    - Our usual failsafe for when the active keyboard is uninstalled is to select the default keyboard.
    - ... which may or may not be interpreted as "the keyboard in the first slot."
4. There are at least two distinct keyboards installed.
    - So, one will remain after the next phase.
    - There does need to be at least one installed keyboard left over.
    - And we need it to not match the keyboard we're uninstalling; we plan to uninstall all language pairings for that one.

**Reproduction, Phase 2**:  Deleting the two just-installed keyboard-language pairings.

1. **Without leaving Settings**, return to the base Settings menu, then select Installed Languages.
    - For the originally-detected instance of this bug:
        1.  "Baka" (1 keyboard)
        2. "English" (1 keyboard)
        3. "Pinyin" (1 keyboard) 
            - Slots 1 and 3:  `sil_cameroon_qwerty`.
            - Slot 2:  the default `sil_euro_latin`.
2. Select one of the `sil_cameroon_qwerty` installations.
    - I selected "Baka" first.
3. Select the keyboard from its menu.
4. Use the "Uninstall Keyboard" option and confirm at all related prompts.
6. Return to the Installed Languages menu.
7. Select the _other_ `sil_cameroon_qwerty` installation.
    - Here, only "Pinyin" was left.
8. Select the keyboard from its menu.
9. Use the "Uninstall Keyboard" option and confirm at all related prompts.
10. Return to the base Settings menu, _but do not leave it._
11. "Install a keyboard", then touch "Install from keyman.com"
12. Select the search bar, as if to search for a new package.
13. Watch as the... uninstalled `sil_cameroon_qwerty` keyboard appears!?
    - Even worse, at least on the initial detection - for _**Baka**_, the language that was uninstalled _**first**_!

**Other Notes**:
Not that it's particularly relevant, but this is where I went on to repeat the installation as part of reproing #6732.  Investigating the two simultaneously may be expedient, as each issue (this one and #6732) is quite useful for cyclically reproing the other.

**Expected behavior**
As all language pairings for `sil_cameroon_qwerty` were uninstalled, the keyboard should neither be displayed at step 12.

---

**Keyman for Android**:

- Device: Galaxy Tab A
- OS: Android 6.0
- Keyman version: 16.0.11-alpha-test-6525.
    - Note that there is no real difference in the Android code here from that found in 15.0.258-beta.
- Target application: Keyman

**Comment by jahorton** [comment]
I just had this occur again with a simpler setup:  I simply installed a package, then went back and uninstalled its keyboard without ever having swapped keyboards after the install.

**Comment by darcywong00** [comment]
Well, even after applying a fix for #6732, the system keyboard for Baku still remains after uninstalling sil_cameroon_qwerty for all the installed languages. 

This will need a separate fix
