### ISSUE TITLE
test(windows): Regression Tests for PR6629

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#6764]
# Keyman for Windows Acceptance Test Procedures #

1. These test procedures are to be run before moving from alpha to beta, or beta to stable, or before PRs are merged into stable branches.

2. Results are annotated with results, use `>` at the start of a new line under the checkbox/Test to note the result. 

# User Testing

## Gather Assets for Testing ##
- [ ] Windows 10 (x64) - VM or physical okay
- [ ] Windows 11 (x64) - VM or physical okay
- [ ] Keyboards for Caps Lock test sets - The test keyboard layouts are found in the keyman repo at [`app/windows/src/test/manual-tests/caps-lock-stores`](https://github.com/keymanapp/keyman/tree/master/windows/src/test/manual-tests/caps-lock-stores).
- [ ] Build off of https://github.com/keymanapp/keyman/pull/6629

## Setup Steps ##
1. Uninstall previous versions of Keyman Desktop and Keyman Developer on the system
2. Restart system, install updates
3. Make sure all additional Windows languages are removed
4. Make sure no debug flags are set in HKCU/Software/Keyman/Debug
5. Install the PR6629 build version of Keyman for Windows

---

## SUITE_BASELINE: Keyman for Windows Base Line Tests

- GROUP_WIN10
- GROUP_WIN11

### Test cases

<details>
<summary>click to expand</summary>

- **TEST_INSTALL**: 
  - Install test build keyman-a.b.c.exe
  - Make sure Keyman is started and visible in the Notification area

- **TEST_KEYBOARD_INSTALLATION_REMOTE**: 
  - Start Keyman Configuration
  - Click Download Keyboard, select a keyboard from the download dialog and install it
  - If the package includes a readme file, verify that it appears in the install window.
  - If the package includes a welcome file, verify that it appears after installation.
  - Click OK to close Keyman Configuration
  - Start Notepad
  - Verify that the newly installed keyboard appears in the Keyman menu and can be selected

- **TEST_INSTALL_PKG_DISK**: 
  - Install a package from disk ##
  - Locate a .kmp file on disk and double-click to install it
  - If the package includes a readme file, verify that it appears in the install window.
  - If the package includes a welcome file, verify that it appears after installation.
  - Start Notepad
  - Verify that the keyboard appears in the Keyman menu

- **TEST_KEYBOARD_OUTPUT**: 
  - Start Notepad and select a Keyman keyboard (testing Legacy integration)
  - Verify that various test sequences are output correctly
  - Start Word and select a Keyman keyboard (testing TSF integration)
  - Verify that various test sequences are output correctly

- **TEST_ON_SCREEN_KEYBOARD**:
  - Click Keyman icon in Notification area, select On Screen Keyboard
  - Verify that OSK displays correctly for selected Keyman keyboard
  - Verify that typing characters by clicking on OSK produces expected output

</details>

---

## SUITE_TSF_APP: 
  Type in-app that uses the windows TSF (MS Word, Fieldworks windows search field on the taskbar).

  
  To run these tests the EuroLatin (SIL) Keyboard from [here](https://keyman.com/keyboards/sil_euro_latin).
  
- GROUP_WIN10

### Test cases: double processing

- **TEST_DOUBLE_PROCESSING_SEARCHBAR**:

  1. Start Keyman
  2. Select the EuroLatin Keyboard
  3. Type in to the windows search bar `a` `b` `c` `d` <kbd>Backspace</kbd>
  4. Expected result is `abc`
   
  ![Search_bar](https://user-images.githubusercontent.com/58423624/152917408-785a34be-ad1e-4e06-bcc6-bea2bd86d70d.png)

- **TEST_ DOUBLE_PROCESSING_NOTEPAD**:
  1. Open Notepad
  2. Start Keyman
  2. Select the EuroLatin Keyboard
  3. Type a sequence of letters `a` `b` `c` `d`  
  4. Expected result: `abcd`

---

## SUITE_IMX_KEYBOARDS
Test IMX keyboards still work after core integration. see tests suite on #5936 and also #6187

This is the keyboard to be tested.  [imsample.zip](https://github.com/keymanapp/keyman/files/8203854/imsample.zip)
If an IMTest keyboard is already installed you will need to uninstall it first, restart windows and then install the Imsample keyboard attached to this PR.

I have copied the tests from #5936 and made a few modifications.  
The overall test we are aiming for is that in doing the tests below the keyboard does not cause a keyman or app crash.

- GROUP_WIN10

#### Test cases

<details>
<summary>click to expand</summary>

#### IMSAMPLE_KEYBOARD_INLINE_MENU: 
This keyboard uses the letters `aeom` to allow IMX input. This keyboard is a bit flakey being a demo and not polished.
It also takes some setting up the following registry keys need to be added and set once installed.
The location of the registry keys are at.
`Computer\HKEY_CURRENT_USER\SOFTWARE\Keyman\Keyman Engine\Active Keyboards\imsample`
and are of type REG_DWORD
The keys are `ShowIMWindow` and `ShowIMWindowAlways` they both need to be set to 0.

In this mode IM window is not shown rather the app text is updated with a menu when either `aeom` is pressed.
For example when type `he`  the text will become `h[1ɛ 2ɜ 3ə 4e 5ɘ]` then you type the number `3` the text displayed should now be `hə`

* **TEST_IMSAMPLE_INPUT:**
  - Install Imsample keyboard attached to this PR.
  - Select the keyboard its name is `IMTest`
  - Type some keys that are not the special keys  e.g. `t` `r` `y`
  - - Type the `space` key then `a` then type 1 to get the 1st option 
  - Expected Result: `try æ`
  - continue to the next test

* **TEST_IMSAMPLE_INPUT_CONT:**
... contd from above
  - Type 'm' and type  3 to get `###` option
  - Expected Result: `try æ###`

* **TEST_IMSAMPLE_BACKSPACE:**
Using Notepad or Libreoffice 
  - Type `f`
  - Type `e`
  - The screen should have f[1ɛ 2ɜ 3ə 4e 5ɘ]
  - Now press Backspace. the whole option menu including the square brackets `[` `]` should be deleted.
  - Expected result `f`

#### IMSAMPLE_KEYBOARD_IM_WINDOW: 
This keyboard uses the letters `aeom` to allow IMX input.  This time a IM window should display.
![image](https://user-images.githubusercontent.com/58423624/157192172-2ba2d0e4-8917-49b3-9709-00d7e9014645.png)

The first time you use the keyboard with an application the registry keys will be created and by default set to 1.

If the IM window is not appearing you will need to verify the value of two registry keys.
The location of the registry keys are at.
`Computer\HKEY_CURRENT_USER\SOFTWARE\Keyman\Keyman Engine\Active Keyboards\imsample`
and are of type REG_DWORD
The keys are `ShowIMWindow` and `ShowIMWindowAlways` they both need to be set to 1.

Note for the IM window you need to use the mouse pointer to select the options, you can't type the number.

* **TEST_IMSAMPLE_INPUT_IMW:**

  - Install Imsample keyboard attached to this PR (if not done already)
  - Select the keyboard its name is `IMTest`
  - Type some keys that are not the special keys  e.g. `t` `r` `y` 
  - Type the `space` key then `a` then click the 1st option 
  - Expected Result: `try æ`
  - continue to the next test

* **TEST_IMSAMPLE_INPUT_IMW_CONT:**
... contd from above
  - Type 'm' and select the 3rd `###` option
  - Expected Result: `try æ###`

#### SIMPLIFIED_CHINESE: 
This keyboard will display the IMX window as soon as a string the matches the pinyin for one or more characters are typed.

For all these tests install the Simplified Chinese Keyboard cs-pinyin.cmp found [here](https://keyman.com/keyboards/cs-pinyin)

* **TEST_ SIMPLIFIED_CHINESE_SINGLE**:
    Using Notepad or equivalent.
    - Type `o`  - The IMX window should appear
    - Choose the 4th option
    - Expected result: 喔

* **TEST_ SIMPLIFIED_CHINESE_MULTIPLE**:
    Using Notepad or equivalent.
    - Type `h` `a` `n` `z` `i`  - The IMX window will appear and in the top left the letters `hanzi` will be present
    - Choose the 5th option
    - Expected result: 汉字变换

* **TEST_ SIMPLIFIED_CHINESE_BACKSPACE_1**:
    Using Notepad or equivalent.
    This is to test the backspace occurring mid pinyin sequence before a character is output to the app
    - Type `h` `a` `n` `z` `i` - The IMX window will appear and in the top left the letters `hanzi` will be present
    - Press Backspace twice  - The IMX window should now have the top left letters of `han`.
    - Choose the 5th option
    - Expected result: 汗

* **TEST_ SIMPLIFIED_CHINESE_BACKSPACE_2**:
    Using Notepad or equivalent.
    This is to test the backspace of already output characters.
    - Type `h` `a` `n` `z` `i` - The IMX window will appear and in the top left the letters `hanzi` will be present.
    - Choose the 5th option
    - Expected result: 汉字变换  
    - Press Backspace twice
    - Expected result: 汉字

</details>

**Comment by bharanidharanj** [comment]
## SUITE_INSPECT: Visual Inspection of master/beta branch

* **TEST_CI_MASTER (PASSED):** The latest CI build of master is successful.
* **TEST_CI_BETA (PASSED):** The latest CI build of Beta is successful.

**Comment by bharanidharanj** [comment]
## SUITE_INSPECT: Visual Inspection of master/beta branch

* **TEST_VERIFY_HISTORY (FAILED):** History.md file was missing in the release folder. 

<img width="300" src="https://user-images.githubusercontent.com/19683143/174313790-93064d65-9b60-42b0-a2d0-1e1e1257400c.PNG">

**Comment by bharanidharanj** [comment]
## SUITE_BASELINE: Keyman for Windows Base Line Tests

### GROUP_WIN10: 

* **TEST_INSTALL (PASSED):** Tested in Keyman 16.0.13 alpha-test-6629 build in Windows 10 OS and it is working as expected. 
* **TEST_KEYBOARD_INSTALLATION_REMOTE (PASSED):**  Tested as per the instructions and it is working as expected.
* **TEST_INSTALL_PKG_DISK (PASSED):** Tested as per the instructions and it is working as expected.
* **TEST_KEYBOARD_OUTPUT (PASSED):** Tested as per the instructions and it is working as expected. 
* **TEST_ON_SCREEN_KEYBOARD (PASSED):** Tested as per the instructions and it is working as expected.
* **TEST_WHATS_NEW (FAILED):** History file is missing with this build.

**Comment by mcdurdin** [comment]
I think TEST_VERIFY_HISTORY and TEST_WHATS_NEW are probably not relevant for a PR-specific regression test (we would not expect new content). So I will go ahead and remove those from the spec here.

**Comment by bharanidharanj** [comment]
## SUITE_BASELINE: Keyman for Windows Base Line Tests

### GROUP_WIN11: 

* **TEST_INSTALL (PASSED):** Tested in Keyman 16.0.13 alpha-test-6629 build in Windows 11 OS and it is working fine. 
* **TEST_KEYBOARD_INSTALLATION_REMOTE (PASSED):** Able to install a Keyboard (I have installed Tamil 99) without having any problem. 
* **TEST_INSTALL_PKG_DISK (PASSED):** Able to install a Keyboard using .KMP file from Local disk. 
* **TEST_KEYBOARD_OUTPUT (PASSED):** Tested this as per the instructions and it is working as expected. 
* **TEST_ON_SCREEN_KEYBOARD (PASSED):** Tested the as per the instructions and the OSK keyboards displays the corresponding language in the layout.

**Comment by bharanidharanj** [comment]
## SUITE_TSF_APP: 

### GROUP_WIN10: 

* **TEST_DOUBLE_PROCESSING_SEARCHBAR (PASSED):** Tested in16.0.13 alpha-test-6629 in Windows 10 and it is working as expected in bothe Search bar and in the Notepad App.

**Comment by bharanidharanj** [comment]
## SUITE_IMX_KEYBOARDS: 

### GROUP_WIN10: 

* **TEST_IMSAMPLE_INPUT (PASSED):** Tested this as per the instructions (16.0.13 alpha-test-6629 )in Windows 10 and it is working as expected.
* **TEST_IMSAMPLE_INPUT_CONT (PASSED):** Tested this as per the instructions (16.0.13 alpha-test-6629 )in Windows 10 and it is working as expected.
* **TEST_IMSAMPLE_BACKSPACE (PASSED):** Tested this as per the instructions (16.0.13 alpha-test-6629 )in Windows 10 and it is working as expected.
* **TEST_IMSAMPLE_INPUT_IMW (PASSED):** Tested this as per the instructions (16.0.13 alpha-test-6629 )in Windows 10 and it is working as expected.
* **TEST_IMSAMPLE_INPUT_IMW_CONT (PASSED):** Tested this as per the instructions (16.0.13 alpha-test-6629 )in Windows 10 and it is working as expected.
