### ISSUE TITLE
bug(web): right alt keys don't work on iOS and Android when referred to

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#6792]
**Describe the bug**

Try and install the keyboard below and see how the right alt keys, i.e. ឞ on the default layer and ឝ on the shift layer, don't output anything.

Keyboard project folder with their built package: 
[sil_jarai.zip](https://github.com/keymanapp/keyman/files/8924387/sil_jarai.zip)

**Comment by jahorton** [comment]
This is a keyboard error.  For reference, here's the .kmn from that .zip:

```
c sil_jarai generated from template at 2022-06-13 10:12:07
c with name "Jarai ចារាយ (SIL)"
store(&VERSION) '10.0'
store(&NAME) 'Jarai ចារាយ (SIL)'
store(&COPYRIGHT) '© SIL International'
store(&KEYBOARDVERSION) '1.0'
store(&TARGETS) 'any'
store(&VISUALKEYBOARD) 'sil_jarai.kvks'
store(&LAYOUTFILE) 'sil_jarai.keyman-touch-layout'
store(&BITMAP) 'sil_jarai.ico'

begin Unicode > use(main)

group(main) using keys
+ [SHIFT K_V] > 'េះ'
+ [SHIFT K_O] > 'ៅ'
+ [SHIFT K_COMMA] > 'ុះ'
+ [SHIFT K_COLON] > 'ោះ'
+ [SHIFT K_A] > 'ាំ'
+ [SHIFT K_EQUAL] > '+'
+ [SHIFT K_HYPHEN] > '_'
+ [K_EQUAL] > '='
+ [K_HYPHEN] > '-'
+ [K_0] > '០'
+ [K_9] > '៩'
+ [K_8] > '៨'
+ [K_7] > '៧'
+ [K_6] > '៦'
+ [K_5] > '៥'
+ [K_4] > '៤'
+ [K_3] > '៣'
+ [K_2] > '២'
+ [K_1] > '១'
+ [SHIFT K_0] > ')'
+ [SHIFT K_9] > '('
+ [SHIFT K_5] > '%'
+ [SHIFT K_3] > '"'
+ [SHIFT K_2] > 'ៗ'
+ [K_BKQUOTE] > '«'
+ [SHIFT K_BKQUOTE] > '»'
+ [ALT K_L] > ':'
+ [ALT K_COMMA] > ','
+ [ALT K_PERIOD] > '.'
+ [ALT K_SLASH] > '/'
+ [ALT K_BKSLASH] > '\'
+ [ALT K_RBRKT] > ']'
+ [ALT K_LBRKT] > '['
+ [ALT K_0] > '}'
+ [ALT K_9] > '{'
+ [ALT K_4] > '$'
+ [SHIFT K_4] > '៛'
+ [ALT K_COLON] > '៖'
+ [SHIFT K_1] > '!'
+ [SHIFT K_SLASH] > '?'
+ [SHIFT K_LBRKT] > 'ឿ'
+ [ALT K_K] > 'ឝ'
+ [ALT K_B] > 'ឞ'
+ [SHIFT K_7] > '័'
+ [K_E] > 'េ'
+ [SHIFT K_S] > 'ៃ'
+ [K_A] > 'ា'
+ [K_PERIOD] > '។'
+ [K_SLASH] > '៊'
+ [SHIFT K_QUOTE] > '៉'
+ [SHIFT K_M] > 'ំ'
+ [K_O] > 'ោ'
+ [K_QUOTE] > '់'
+ [ALT K_QUOTE] > 'ៈ'
+ [SHIFT K_E] > 'ែ'
+ [K_COLON] > 'ើ'
+ [SHIFT K_Y] > 'ួ'
+ [SHIFT K_U] > 'ូ'
+ [K_U] > 'ុ'
+ [SHIFT K_H] > 'ះ'
+ [SHIFT K_W] > 'ឺ'
+ [K_W] > 'ឹ'
+ [K_LBRKT] > 'ៀ'
+ [SHIFT K_I] > 'ី'
+ [K_I] > 'ិ'
+ [K_J] > '្'
+ [SHIFT K_D] > 'ឌ'
+ [K_D] > 'ដ'
+ [K_S] > 'ស'
+ [SHIFT K_Q] > 'ឈ'
+ [K_Q] > 'ឆ'
+ [K_H] > 'ហ'
+ [K_V] > 'វ'
+ [SHIFT K_L] > 'ឡ'
+ [K_L] > 'ល'
+ [SHIFT K_G] > 'អ'
+ [K_R] > 'រ'
+ [K_Y] > 'យ'
+ [K_M] > 'ម'
+ [K_P] > 'ផ'
+ [SHIFT K_P] > 'ភ'
+ [SHIFT K_B] > 'ព'
+ [K_B] > 'ប'
+ [SHIFT K_N] > 'ណ'
+ [K_N] > 'ន'
+ [SHIFT K_F] > 'ធ'
+ [K_F] > 'ថ'
+ [K_T] > 'ត'
+ [SHIFT K_T] > 'ទ'
+ [SHIFT K_Z] > 'ឍ'
+ [K_Z] > 'ឋ'
+ [SHIFT K_J] > 'ញ'
+ [SHIFT K_C] > 'ជ'
+ [K_C] > 'ច'
+ [K_G] > 'ង'
+ [SHIFT K_X] > 'ឃ'
+ [SHIFT K_K] > 'គ'
+ [K_X] > 'ខ'
+ [K_K] > 'ក'
```

I do not see a single keyboard rule referring to the `RALT` modifier.  Since the affected keys are using `K_`-based key ids, there must be a rule based on them, combined with `RALT` that produces the desired output.

**Comment by jahorton** [comment]
For comparison, in the `.keyman-touch-layout` file:

```
              {
                "id": "K_B",
                "text": "ឞ",
                "layer": "rightalt"
              },
```

There is this line from the .kmn:

```
+ [ALT K_B] > 'ឞ'
```

But that's using `ALT`, not `RALT`.  I'm pretty sure that makes a difference.  KeymanWeb sees `rightalt` as a chiral modifier, while the compiled version of the keyboard will likely indicate that it's non-chiral - and this causes a major mismatch that results in the keys not operating.

**Comment by jahorton** [comment]
So... if this keyboard is currently in the keyboards repo, unless I'm mistaken this bug report belongs there, not here.

**Comment by mcdurdin** [comment]
> But that's using `ALT`, not `RALT`. That actually makes a huge difference. KeymanWeb sees `rightalt` as a chiral modifier, while the compiled version of the keyboard indicates that it's non-chiral - and this causes a major mismatch that results in the keys not operating.

Hmm. I'm not sure. The `ALT` modifier in the rule is supposed to be non-chiral in nature. If the desktop OSK generates a `[RALT K_A]`, that should match `[ALT K_A]`. I think the same should apply for touch keyboard events.

**Comment by jahorton** [comment]
> Hmm. I'm not sure. The `ALT` modifier in the rule is supposed to be non-chiral in nature. If the desktop OSK generates a `[RALT K_A]`, that should match `[ALT K_A]`. I think the same should apply for touch keyboard events.

For the KeymanWeb OSK, because the keyboard has been denoted as non-chiral, the desktop OSK _**can't**_ generate a `[RALT K_A]`.  It will only generate the non-chiral `[ALT K_A]`, which is why it's not noted here as an issue for desktop platforms.

**Comment by mcdurdin** [comment]
> Keep in mind that this behavior has been in place pretty much since 10.0 as-is.

Well ... it doesn't match the spec. So we have long-lived bad behaviour. Doesn't mean we should continue with it. May mean we need to carefully analyze a fix.

> My position is that the key modifier set in the touch-layout should be expected to match an existing keyboard rule.

My position is that "Right Alt" is matched by the rule "Either Alt". That's what `+ [ALT ...]` is!

**Comment by jahorton** [comment]
> ... May mean we need to carefully analyze a fix.

As we do so, I'd like to point out that even should we "fix" this, for backwards-compatibility's sake, the keyboard should still swap to use of `"alt"` over "`rightalt`" in the touch layout.  I don't think we'd plan to backport this for versions 10.0 - 14.0, while the keyboard itself, when compiled, will state 10.0 compatibility.

**Comment by mcdurdin** [comment]
I'd go the other way and update the keyboard to use right alt throughout.

**Comment by jahorton** [comment]
> I'd go the other way and update the keyboard to use right alt throughout.

That's fair.  The key is consistency.

**Comment by mcdurdin** [comment]
> I don't think we'd plan to backport this for versions 10.0 - 14.0, while the keyboard itself, when compiled, will state 10.0 compatibility.

Yes, given this can be addressed keyboard-side for backward compatibility, I am comfortable with just fixing this going forward.
