### ISSUE TITLE
bug(web): caps lock state needs to be maintained separately for physical and touch layouts at the same time

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#6799]
**Describe the bug**

As of 15.0, the changes I introduced for the Caps Lock layer in KeymanWeb interact with the ` this.stateKeys['K_CAPS']` variable to ensure that key events generated from the `caps` layer are given the right modifier state when doing rule processing.

However, in a brief re-analysis today, I think there is a logical issue and loss of state. We need to ensure that `this.stateKeys['K_CAPS']` is set to the state of the hardware keyboard caps lock key, kept in sync with the hardware keyboard state, except when the user generates a touch event on the caps layer.

The hardware Caps Lock key must not affect the output from the touch keyboard, and changing the caps state on the touch keyboard must not affect the value of `this.stateKeys['K_CAPS']` when pressing keys on the hardware keyboard.

This is also mixed up with `_UpdateVKShift` which was originally designed to make sure the On Screen Keyboard for desktop matched the modifier states of the hardware keyboard (so holding Shift on the hardware keyboard would show the shifted layer on the desktop On Screen Keyboard). This function is now overloaded with touch layout logic as well, and we have multiple state variables for modifiers, so it's really hard to trace:

* `this.stateKeys['K_CAPS']`
* `Lkc.Lstates`
* `Lkc.Lmodifiers`
* And the mysterious link between layer and modifier as shown in `this.getLayerId(keyShiftState)`

Note that the hardware keyboard modifier keys currently affect the visible layer of the touch keyboard, which is probably wrong, particularly for Caps Lock which is not transient -- hardware modifier state should only affect the modifier state of the desktop osk (which is supposed to mirror the state of the hardware keyboard, unlike the touch keyboard).

Yes, there is a hard problem of pressing Caps Lock on the desktop osk, which AFAIK cannot cancel the Caps Lock state of the hardware keyboard on current browsers. Separate problem really but one to consider when detangling this.

---

**KeymanWeb:**
 - KeymanWeb Version: 15.0.260

**Comment by mcdurdin** [comment]
@jahorton Can we discuss this and work through a resolution together? I think we need to fix this for 15.0-stable as well as 16.0-alpha, as there is a current desync for Caps Lock in the stable release, and it's due to this confused state machine.

**Comment by jahorton** [comment]
Please see https://github.com/keymanapp/keyman/pull/6849#issuecomment-1166736861.

Though, I'm not sure my notes there fully hold after some of the PRs that were merged in my absence.  I see that #6351 and #6453 made some odd choices that don't make sense to me on first glance that may be related, for example.

**Comment by jahorton** [comment]
> This is also mixed up with `_UpdateVKShift` which was originally designed to make sure the On Screen Keyboard for desktop matched the modifier states of the hardware keyboard (so holding Shift on the hardware keyboard would show the shifted layer on the desktop On Screen Keyboard). This function is now overloaded with touch layout logic as well, and we have multiple state variables for modifiers, so it's really hard to trace:
> 
>     * `this.stateKeys['K_CAPS']`
> 
>     * `Lkc.Lstates`
> 
>     * `Lkc.Lmodifiers`
> 
>     * And the mysterious link between layer and modifier as shown in `this.getLayerId(keyShiftState)`

Again, there's a chance things have shifted while I was away, but:

- `Lkc.Lstates` - tracks a KeyEvent's state-key states (CAPS, NUM_LOCK, SCROLL.)
    - Will _**always**_ be unchanged from the source keystroke for physical keystrokes.
    - These are (effectively) used to keep `this.stateKeys['K_CAPS']` updated, ensuring that the current engine state matches reality.
- `Lkc.Lmodifiers` - the same, but for modifier keys
- `this.stateKeys['K_CAPS']` - tracks the most recent states that should be used for keystrokes.  This is the source of `Lkc.Lstates` for _OSK-sourced_ keystrokes.

- `this.getLayerId(keyShiftState)` - the heart of that "physical keystroke updates the desktop OSK" bit.  The desktop OSK does use layer names, just like the touch OSK.

> Note that the hardware keyboard modifier keys currently affect the visible layer of the touch keyboard, which is probably wrong [...] -- hardware modifier state should only affect the modifier state of the desktop osk (which is supposed to mirror the state of the hardware keyboard, unlike the touch keyboard).

Okay, so that part's been stuck in your headspace for a while, from the sound of it.  Though I was aware that we aim to keep them separate when used in the Android app, at least.

**Comment by mcdurdin** [comment]
Another question: `set(&layer)` is [documented](https://help.keyman.com/developer/language/reference/layer) as impacting only touch keyboards:

> The `&layer` system variable store can be used to set or test the current layer on the touch keyboard.

But current behaviour has it impacting the desktop OSK as well. This does not seem right to me...
