### ISSUE TITLE
test(Developer): Regression test for PR6860

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#6882]
Acceptance testing of the latest Keyman Developer alpha before going into Beta.

# Keyman Developer Acceptance Test Procedures #

1. These test procedures are to be run before moving from alpha to beta, or beta to stable, or before PRs are merged into stable branches.
2. Copy these checklists of tests into a new issue (for tier transitions) or a comment on the PR.

# User Testing

## Gather Assets for Testing ##
- Windows 10 (x64) - VM or physical okay
- Windows 11 (x64) - VM or physical okay (if prefer for other suites)

## Setup Steps ##
- Uninstall previous versions of Keyman for Windows and Keyman Developer on the system
- Restart system, install updates
- Clean up any broken installation artifacts (ideally, roll back to clean snapshot in VM):
  - `%ProgramFiles(x86)%\Keyman` or `%ProgramFiles%\Keyman`
  - `%CommonProgramFiles(x86)%\Keyman` or `%CommonProgramFiles%\Keyman`
  - `%ProgramData%\Keyman`
  - `%AppData%\Keyman`
  - `%LocalAppData%\Keyman`
  - `HKCU\Software\Keyman`
  - `HKLM\Software\Wow6432Node\Keyman`
  - Manually remove any remaining Keyman input methods from Windows Languages

### GROUP_WIN11 - to be tested on Windows 11 (x64)

- TEST_STARTS: Verify that Keyman Developer starts
- TEST_COMPILES: Open a .kpj project, load keyboards and verify that you can compile them

### SUITE_DEBUGGER: Test new core-based debugger
Setup: open a reasonably complex keyboard project (eg. [Amharic](https://github.com/keymanapp/keyboards/tree/master/release/gff/gff_amharic) and [Cameroon](https://github.com/keymanapp/keyboards/tree/master/release/sil/sil_cameroon_qwerty) keyboards), load the .kmn, and press F7 to compile.

- TEST_DEBUGGER_STARTS: Start debugging by pressing F5. Verify that the debugger starts and you can type with the keyboard in the debug window. Look out for any unexpected behaviour or visual oddities.
- TEST_DEBUGGER_SINGLE_STEP: Press the Single Step button (`>>`) in the Debugger toolbar. Type a key in the debugger window. Use the debugger toolbar (`>`) button to step through the rules and verify that the matched rules are correct. Examine the Debugger State windows (Elements, Call stack, etc) to verify that the content presented at each point makes sense.
- TEST_DEBUGGER_PAUSE: Press the Pause button (`||`) in the Debugger toolbar. Verify that no input is possible in the debugger window.
- TEST_DEBUGGER_CHANGES: Make a change to the source file and verify that the debugger works correctly after recompiling.
- TEST_DEBUGGER_PLATFORM: Create some platform-specific rules with `platform()` statement, and use the Debugger State window 'Platform' to select platform variants, and verify that the debugger selects the appropriate rules in testing.

### SUITE_SERVER: Test new Keyman Developer Server ##

- TEST_SERVER_STARTS: Start Keyman Developer. Verify that Server starts by examining the tool tray area, and launching http://localhost:8008 in your browser.
- TEST_SERVER_STOPS: Start Keyman Developer. Check that Tools/Options/Server/Leave Server running after closing IDE is **off**. Exit Keyman Developer. Verify that Server has shut down by attempting to visit http://localhost:8008 in your browser -- it should fail to load.
- TEST_SERVER_KEEP_ALIVE: Start Keyman Developer. Check that Tools/Options/Server/Leave Server running after closing IDE is **on**. Exit Keyman Developer. Verify that Server has is still running by visiting http://localhost:8008 in your browser.

- TEST_SERVER_KEYBOARD: Make sure that a keyboard debug session works.

  1. In Keyman Developer, load a keyboard project, open a keyboard, and start testing on web.
  2. Open http://localhost:8008 in your browser, and select the keyboard from the Keyboards drop down
  3. Verify that the keyboard is working in the web debug view.

- TEST_SERVER_KEYBOARD_LIVE_CHANGE: Make sure that changes to the keyboard are dynamically updated.

  1. Follow TEST_SERVER_KEYBOARD steps to start debugging the keyboard.
  2. Make a visual change to the on screen keyboard / touch keyboard view in the keyboard and recompile it (<kbd>F7</kbd).
  3. Switch back to the browser and verify that the change is visible in the keyboard.

**Comment by bharanidharanj** [comment]
## SUITE_DEVELOPER_BASELINE: Keyman Developer baseline tests

### GROUP_WIN11: - to be tested on Windows 11 (x64)

* **TEST_STARTS (PASSED):** Tested Keyman Developer 16.0.20.0 in Windows 11 (Virtual Machine) and it is working fine. 
* **TEST_COMPILES (PASSED):** Able to compile a Keyboard using Keyman Developer 16.0.20.0.

**Comment by bharanidharanj** [comment]
## SUITE_DEVELOPER_BASELINE: Keyman Developer baseline tests

## SUITE_DEBUGGER: Test new core-based debugger

* **TEST_DEBUGGER_STARTS (PASSED):** Tested in Keyman Developer 16.0.20.0 in Windows 11 (Virtual Machine) and able to type in the debug window. 
* **TEST_DEBUGGER_SINGLE_STEP (FAILED):** Another (Single_Step) button is not working in the tool bar. 
<img width="300" src="https://user-images.githubusercontent.com/19683143/177142178-42753ee6-b66f-4397-84c0-7fc0f4dc5220.PNG">


* **TEST_DEBUGGER_PAUSE (FAILED):** Able to type in the debugger window even though I enabled the PAUSE button in the tool bar. 
<img width="300" src="https://user-images.githubusercontent.com/19683143/177142194-7fc877c5-1f8a-4753-9007-c6cbf82b40ff.PNG">

**Comment by bharanidharanj** [comment]
## SUITE_DEVELOPER_BASELINE: Keyman Developer baseline tests

### GROUP_WIN10: - to be tested on Windows 10 (x64)

* **TEST_STARTS (PASSED):** Tested in Keyman Developer 16.0.20.0 in Windows 10 OS and it is working fine. 
* **TEST_COMPILES (PASSED):** Able to compile a Keyboard using Keyman Developer.

**Comment by mcdurdin** [comment]
> * **TEST_DEBUGGER_SINGLE_STEP (FAILED):** Another (Step Forward) button is not working in the tool bar.
> 
> * **TEST_DEBUGGER_PAUSE (FAILED):** Able to type in the debugger window even though I enabled the PAUSE button in the tool bar.

The Debugger controls are only relevant for the Debug window. This is the Debug window:

![image](https://user-images.githubusercontent.com/4498365/177222961-1126d3cb-108a-4e9a-9a72-6b2090aee110.png)

* The Step Forward button will only become active when you start a debug action -- by typing a key into the Debug window when in Single Step mode.
* You should find you cannot type into the Debug window when the Pause button is active.

@keymanapp-test-bot retest SUITE_DEBUGGER  TEST_DEBUGGER_SINGLE_STEP TEST_DEBUGGER_PAUSE

**Comment by MakaraSok** [comment]
# Test Results

All tests done on a fresh snapshot of Windows 10 Pro x64 using Keyman Developer `16.0.24` obtained from https://github.com/keymanapp/keyman/pull/6860.

## SUITE_DEBUGGER: Test new core-based debugger

* **TEST_STARTS (PASSED):** The debugger does start and the debugger window does work as expected. One thing I notice is that font size of the characters output and shown in the debugger, they are too small to eye at. 

   <img width="300" src="https://user-images.githubusercontent.com/28331388/177244510-a4d86daa-74fb-4a56-a0ae-f48ac90e28fe.png">


* **TEST_DEBUGGER_SINGLE_STEP (PASSED):** The State, Element and Class stack tabs show relevant info at each step.
* **TEST_DEBUGGER_PAUSE (PASSED):** The debugger window does get disable and nothing can be typed in there.
* **TEST_DEBUGGER_CHANGES (PASSED):** The debugger does work correctly after recompiling with some changes made to the keyboard rules.
* **TEST_DEBUGGER_PLATFORM (PASSED):** The appropriate rule was selected, run and output the expected string.

**Comment by mcdurdin** [comment]
> * **TEST_SERVER_KEEP_ALIVE (FAILED):** When tried to close the Keyman Developer Window, the Keyman Developer IDE goes to hanging state after enabling the "Leave Server running after closing IDE" checkbox.

I think this is not a regression but rather an issue with shutting down Keyman Developer Server -- Keyman Developer IDE then tries to contact the server and fails. So will turn this into a new issue.

SUITE_SERVER
TEST_SERVER_KEEP_ALIVE SKIPPED: See #6897
