### ISSUE TITLE
bug(web): keyboard rules with NCAPS are not matching with touch keyboard events in 15.0.264

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#6910]
**Describe the bug**

On Android or iOS with Keyman stable v15.0.265, typing <kbd>a</kbd><kbd>a</kbd> with the Dega keyboard outputs `aa` instead of the expected â.

When testing it in Keyman Developer, it's working as expected 100% of the time with different variation of Platform options.

But when `Open in browser`, <kbd>a</kbd><kbd>a</kbd> outputs `aa`just like that of when testing on the actual Android/iOS device.

**Expected behavior**

<kbd>a</kbd><kbd>a</kbd> outputs `aa` and all rules should be applied consistently on all platform.

**Screenshots**

Platform variation in Keyman Developer debugger:

https://user-images.githubusercontent.com/28331388/177910907-b82d3b42-02fb-43ae-ae2c-5c0903d889ce.mov

Web from within Keyman Developer:

https://user-images.githubusercontent.com/28331388/177910465-bbdc57ce-1dbe-4f8a-8d94-62f7d9a9fb66.mov

---

**Keyman for iPhone/iPad/Android:**
 - Devices | OSes: iPod touch 7th Gen running iOS 15.5| Galaxy S9+ running Android 10
 - Keyman version: 15.0.265 stable
 - Target application: Keyman

**Keyman Developer:**
 - OS: Windows 10 Pro 21H2 x64
 - Keyman Developer version: 15.0.265 stable

---

**Keyboard**
 - Keyboard name: Dega
 - Keyboard version: 1.0
 - Language name: any of what's available

**Additional context**

**Comment by mcdurdin** [comment]
I have bisected and found the problem starts in 15.0.264. The issue is a regression in one of these:

## 15.0.264 stable 2022-07-01

- fix(ios): eliminates conditional height for banner image (#6857)
- fix(web): clears repeating bksp on keyboard reload ️ (#6863)
- fix(web): better stability during transient OSK load state (#6861)
- fix(developer): readonly groups should never emit output (#6873)
- fix(web): Maintain separate Caps Lock states for touch and physical (#6874)

**Comment by jahorton** [comment]
I can reproduce this using the test pages hosted in this comment: https://github.com/keymanapp/keyman/pull/6874#issuecomment-1170492004.

So, I think it's safe to say we know which PR triggered it.

**Comment by mcdurdin** [comment]
Yes, I just ran the same set of tests.

**Comment by mcdurdin** [comment]
The rules in Dega use `CAPS` and `NCAPS` (dynamically added by the compiler). I think that is why we are no longer matching with the changes in #6874.

But the question is what is the correct fix?

**Comment by mcdurdin** [comment]
Proposal:

https://github.com/keymanapp/keyman/blob/8ba11f608de65810d91a3615e714cec3a2d63ed0/common/web/keyboard-processor/src/text/keyboardProcessor.ts#L387-L389

Add:

```js
else {
  modifier |= Codes.modifierCodes['NO_CAPS'];
}
```

**Comment by LornaSIL** [comment]
When will this update hit my Keyman app on my phone?

**Comment by mcdurdin** [comment]
> When will this update hit my Keyman app on my phone?

It should be available already -- you may need to check your App Store / Play Store updates to install it more quickly.

> Will this PR fix that issue too or do I need to create a new issue?

Yes, it should do. Let me know if it doesn't fix it.

**Comment by LornaSIL** [comment]
It didn't fix it. But when I uninstalled Keyman, then reinstalled the `old_hungarian` and `basic_kbdlvst` keyboards THEN they both work. I checked, and I did have the latest version of Keyman installed before uninstalling, but maybe it was uninstalling the keyboards and reinstalling them that made them work.

**Comment by mcdurdin** [comment]
That's curious -- not sure why that would have happened, because the keyboards shouldn't have needed a reinstall to fix this. Anyway, glad it's working again now for you.
