### ISSUE TITLE
test(android, web): context-only rule effects, set(&layer) from physical keystrokes

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#6953]
Refer to #6949 and its build artifacts for these tests.

# User Testing

TEST_ANDROID_EXTERNAL:  Using an Android device with an external keyboard...

1. Install the KMP within this .zip:  [sil_euro_latin.zip](https://github.com/keymanapp/keyboards/files/9050066/sil_euro_latin.zip)
2. With `sil_euro_latin` active, clear any previously-existing text.
3. Verify that the keyboard is on the 'shift' layer - the key caps should all be capitalized.
4. Using _only the external, hardware keyboard_, type `hello world.`
5. Type the `.` key once more.  Note that no visible text changes should occur; this is not a bug.
6. Type the ` ` (space) key.
7. If the 'shift' layer is not automatically displayed at this time, _**FAIL**_ this test.
    - ONLY if you did BOTH steps 5 and 6.  It will appear to fail if you leave out either step. 

Alternatively, you may use Android Studio's emulator, treating your computer's hardware keyboard as if it were the simulated device's external keyboard.

TEST_ANDROID_OSK:  Using an Android device...

1. Install the KMP within this .zip:  [sil_euro_latin.zip](https://github.com/keymanapp/keyboards/files/9050066/sil_euro_latin.zip)
2. With `sil_euro_latin` active, clear any previously-existing text.
3. Verify that the keyboard is on the 'shift' layer - the key caps should all be capitalized.
4. Using _only the OSK_, type `H`.
5. Verify that the OSK returns to the 'default' layer.
6. Type `ello world.`  (The OSK's layer should remain unshifted.)
7. Type the ` ` (space) key.
8. If the 'shift' layer is not automatically displayed at this time, _**FAIL**_ this test.

TEST_DESKTOP:  in standard desktop Chrome:

1. Release any pressed keyboard keys before swapping to the Obolo Chwerty keyboard.
2. Verify that the OSK is in the 'default' layer when first shown.
3. Press and hold hardware 'shift'.  Verify that the 'shift' layer is now shown.
4. Type hardware `j`.  Verify that a `J` is produced.
5. Release hardware 'shift'.  Verify that the 'default', lowercase layer is now shown.
6. Press the hardware CAPS key.  Verify that it remains on the 'default' layer.
    - Desktop form-factors do not support a 'caps' OSK layer yet.
7. Type the hardware `h` key.  Verify that `SH` is produced.

TEST_MOBILE:  using Chrome's developer mode, emulate a mobile device, then refresh the page.

1. With no pre-existing text in the textbox, swap to the Obolo Chwerty keyboard.
2. Verify that the OSK is in the 'shift' layer when first shown.
3. Type hardware 'j'.  Verify that a `j` is produced - not a `J`.
4. Press and hold hardware 'shift'.  Verify that the 'default' layer remains visible.
5. Type the hardware `h` key.  Verify that `Sh` is produced.
6. Release hardware 'shift', then toggle hardware caps-lock.
7. Type the hardware `h` key again.  Verify that `SH` is produced.

**Comment by bharanidharanj** [comment]
* **TEST_ANDROID_EXTERNAL (PASSED):** Tested this is Android 11 Mobile device with an external keyboard and it is working as expected. 
* **TEST_ANDROID_OSK (PASSED):** Tested this in Android 11 Mobile device with OSK and it is working as expected. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/179487927-7d277eba-4f61-4f22-bc73-75581aec13de.jpg">


* **TEST_DESKTOP (PASSED):** Tested this as per the instructions in  Desktop Chrome browser and it is working as expected. 

   <img width="500" src="https://user-images.githubusercontent.com/19683143/179487966-76a68ab9-25d6-4f42-a7aa-79afc3e4611c.PNG">

* **TEST_MOBILE (PASSED):** Tested this as per the instructions in Chrome emulator mode and it working as expected. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/179487999-b95539d6-e52e-4b24-a4c7-902812636260.PNG">

**Comment by jahorton** [comment]
Thanks a bunch, @bharanidharanj.  Good to know I didn't mess things up too badly with that accidental early merge.
