### ISSUE TITLE
feat(developer): Keyman dev mobile

### ISSUE THREAD

**Issue by TJCgames** [keymanapp/keyman#6958]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

A version of the Keyman Developer platform for android and iOS.

**Describe alternatives you've considered**

None.

---

**Keyman Developer:**
 - OS: <Android, iOS>

---

**Additional context**

I would like to make keyboards when I don't have access to a computer.

**Comment by jahorton** [comment]
We're currently in the process of making the keyboard compiler - a very critical component for this - platform-independent.  Of course, that's _only_ one component; this sort of work takes time, and we're a relatively small development team.  We'll get there one piece at a time, but we cannot currently predict when we'll be able to release such a version of Developer.

This _is_ on our radar, but it's not on the top of our list of priorities.

**Comment by TJCgames** [comment]
ok
