### ISSUE TITLE
[Android] longpress on shift can't access all the layers on Chriality keyboard

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#696]
Found during User testing of Keyman for Android 10.0.373 Beta of the engineering chriality keyboard

In Keyman for Android 10.0.10000051 Alpha, longpress on `shift` could access `*Shift*`, `*LCtrl*`, `*LAlt*`, and `*RAlt*` layers.

Releases after that have 2x the number of shift options, but only default->shift works. All the other ones remain on the default layer.

KMW works fine

**Comment by jahorton** [comment]
Fixed by #713.
