### ISSUE TITLE
bug(developer): no preview of the splash image in the developer

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#6974]
**Describe the bug**

<img width="1131" alt="image" src="https://user-images.githubusercontent.com/28331388/179723107-fb942f9e-443c-482c-a801-1a294b36c536.png">

The splash image chosen for the splash screen when installing the keyboard doesn't show its preview in Keyman Developer. One has to test install the package each time to see how it's shown--which is not quite convenient.

---

**Keyman Developer:**
 - OS: Windows 10 Pro 21H2 x64
 - Keyman Developer version: 15.0.266

**Comment by mcdurdin** [comment]
What format is the splash image?
