### ISSUE TITLE
bug(developer): 'after' (modifier key) label name is missing in Options tab in Debugger Window

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#7059]
**Describe the bug**
In Debugger window, I noticed that the in the Options tab, the 'after' key label name is missing but the related functionality is working fine. 

**To Reproduce**
1. Open an existing keyboard (SIL_IPA) project via Keyman Developer. 
2. Press F5 to open the Debugger Window. 
3. Click the 'Options' tab. 
4. Click on the dropdown list box. 
5. Verify that there two modifier key names 'after' and 'before' appearing the list box. 

Here, I noticed that there is only one key name 'before' appearing in the list box. 

**Expected behavior**
'after' label name should be added in the drop down list box. 

**Screenshots**

<img width="500" src="https://user-images.githubusercontent.com/19683143/183873686-f44508f5-b783-4436-b775-caadcab0f7ff.png">

---

**Keyman Developer:**
 - OS:    Windows 10 Pro x64 
 - Keyman Developer version: 16.0.44-alpha

---

**Keyboard**
 - Keyboard name:    SIL_IPA
 - Keyboard version: 1.8.6
 - Language name:    Undertermind (Und-Latin)

**Comment by mcdurdin** [comment]
Hi @bharanidharanj, does this come out of some test instructions? As far as I can tell, the 'after' text should not be in that box, because it does not appear in sil_ipa.kmn.

**Comment by mcdurdin** [comment]
Ping @bharanidharanj -- see above question

**Comment by mcdurdin** [comment]
Closing this because I do not think it is a problem.
