### ISSUE TITLE
bug(Android): "Error in Keyboard  sil_euro_latin.." message appears after upgrading the Euro Latin Keyboard

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#7063]
**Describe the bug**
After upgrading the Euro Latin Keyboard I noticed that there is an error message pop up on the Keyboard view. 

**To Reproduce**
1. Install 15.0.259 beta build in Android Mobile device. 
2. Open Keyman In-app. 
3. Click the 3 dot button which appears in the top right corner of the Keyman view. 
4. Verify that there is an option 'Install Updates" under Settings option. 
5. Click 'Install Updates' option. 
6. Verify that an 'Keyboard update' message will appear on the Screen. 

Here, I noticed that there is an error message "Error in Keyboard sil_euro_latin..." appearing on the Screen.  Also, selecting the predictions from the banner, I noticed that the selected word appears with some other bg color. 

**Expected behavior**
The sil_euro_latin Keyboard should be working fine after upgrading it. Selecting any predictions from the banner should appear on the text pane. 

**Screenshots**

<img width="300" src="https://user-images.githubusercontent.com/19683143/184160446-61af605d-3ad0-4c41-bb3a-7a3e145251fb.jpg">

---

**Keyman for Android:**
   Device:             Android Mobile Device
 - OS:                 11.0
 - Keyman version:     15.0.29-beta build
 - Target Application: Keyman In-App

---

**Keyboard**
 - Keyboard name:    <EuroLatin(SIL)>
 - Keyboard version: 2.0
 - Language name:    English

**Comment by mcdurdin** [comment]
We'll need some more detail including Keyman version and screenshots I think!

**Comment by bharanidharanj** [comment]
> We'll need some more detail including Keyman version and screenshots I think!

@mcdurdin Sorry. I have updated with my comments. :-)

**Comment by MakaraSok** [comment]
I am unable to reproduce this behavior on Alpha 16.0.49.

@bharanidharanj We can you repro this in the alpha version?

**Comment by darcywong00** [comment]
I could **not** reproduce on my Android device with 15.0.249 beta

**Comment by bharanidharanj** [comment]
Retested with Keyman 15.0.268 Beta build and I was not able to reproduce this issue.

**Comment by bharanidharanj** [comment]
@MakaraSok Retested this issue with Keyman 16.0.49-alpha build in API 26 / Android 8.0 emulator and I was not able to reproduce it. Hence, I am closing the same. Thanks.
