### ISSUE TITLE
bug(Android): Bottom layer of the OSK goes beyond the screen level when the mobile is in lanscape view

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#7064]
**Describe the bug**
After rotating the mobile from Portrait to Landscape View, I noticed that the bottom layer of the Keyboard layout goes beyond the mobile screen view. 

**To Reproduce**
1. Install Keyman 16.0.45-alpha build in the Mobile device.
2. Open the Keyman In-App.
3. Verify that the default EuroLatin Keyboard (OSK) appears on the Screen.
4. Verify that the bottom layer of the Keyboard appears withing the Mobile screen view. 
5. Rotate the Mobile device from Portrait to Landscape mode. 
6. Verify that the bottom layer of the Keyboard appears within the Mobile screen view. 

Here, I noticed that the bottom layer of the Keyboard goes beyond the screen view. 

**Expected behavior**
The OSK layout view should appear within the Mobile screen view. 

**Screenshots**

![OSKView](https://user-images.githubusercontent.com/19683143/184167152-f5cdcef2-3968-48dd-a395-e3baae8138e4.PNG)

---

**Keyman for Android:**
   Device:  Android API 29 emulator
 - OS:   Android 11.0
 - Keyman version:  16.0.45-alpha
 - Target Application: Keyman In-App

---

**Keyboard**
 - Keyboard name:    EuroLatin(SIL)
 - Keyboard version: 2.0
 - Language name:   English

**Comment by mcdurdin** [comment]
We'll need some more detail including Keyman version and screenshots I think!

**Comment by bharanidharanj** [comment]
> **Describe the bug** After rotating the mobile from Portrait to Landscape View, I noticed that the bottom layer of the Keyboard layout goes beyond the mobile screen view.
> 
> **To Reproduce**
> 
>     1. Go to '...'
> 
>     2. Click on '....'
> 
>     3. Scroll down to '....'
> 
>     4. See error
> 
> 
> **Expected behavior**
> 
> **Screenshots**
> 
> **Related issues**
> 
> **Keyman for Windows/macOS/Linux/iPhone/iPad/Android:** Device:
> 
>     * OS:
> 
>     * Keyman version:
> 
>     * Target Application:
> 
> 
> **Keyman Engine for Web:** Device:
> 
>     * OS:
> 
>     * Browser:
> 
>     * KeymanWeb Version:
> 
>     * URL:
> 
> 
> **Keyman Developer:**
> 
>     * OS:
> 
>     * Keyman Developer version:
> 
> 
> **Keyboard**
> 
>     * Keyboard name:
> 
>     * Keyboard version:
> 
>     * Language name:
> 
> 
> **Additional context**



> We'll need some more detail including Keyman version and screenshots I think!

I have updated my comment. Thanks.

**Comment by MakaraSok** [comment]
## Tested with Keyman 16.0.49 - Alpha
Nothing looks strange nor unexpected as indicated above. Let's take a look at this together on Zoom. 

### On Android 10 (API 29)

|   | system keyboard | in-app |
| --- | --- | --- |
| Portrait | <img width="150" alt="image" src="https://user-images.githubusercontent.com/28331388/186312255-01bd2c03-c196-434d-9939-2535cf8a4712.png"> | <img width="150" alt="image" src="https://user-images.githubusercontent.com/28331388/186315438-82f989bb-321e-4bb8-ab67-a2cc2c929b5a.png"> |
| Landscape | <img width="811" alt="image" src="https://user-images.githubusercontent.com/28331388/186312345-aebe2f90-1d07-4f22-84d5-32af2d5ff9d5.png"> | <img width="811" alt="image" src="https://user-images.githubusercontent.com/28331388/186313336-c4e92745-e7f6-45b4-8dce-41970d68e51e.png"> |

---

### On Android 11 (API 30)

|   | system keyboard | in-app |
| --- | --- | --- |
| Portrait | <img width="150" alt="image" src="https://user-images.githubusercontent.com/28331388/186315200-b2ac5f30-f7fd-4035-923c-b3e2742cf1d3.png"> | <img width="150" alt="image" src="https://user-images.githubusercontent.com/28331388/186315002-3e7d1711-8d48-48c9-b686-5b68ef420299.png"> |
| Landscape | <img width="811" alt="image" src="https://user-images.githubusercontent.com/28331388/186313765-e3b623c5-87fd-4aa3-a493-494fd7e82249.png"> | <img width="811" alt="image" src="https://user-images.githubusercontent.com/28331388/186314464-cf60f753-9dde-4ed0-8f23-a5f1c593651a.png"> |

**Comment by darcywong00** [comment]
> Here, I noticed that the bottom layer of the Keyboard goes beyond the screen view.

@bharanidharanj - I'm not sure I understand what you mean by "goes beyond the screen view". From your screenshot, it seems the entire OSK is there (the <kbd>p</kbd> is all there, along with padding on the right). It just looks like the device is rounding corners on the top and bottom - out of our control.

**Comment by bharanidharanj** [comment]
> > Here, I noticed that the bottom layer of the Keyboard goes beyond the screen view.
> 
> @bharanidharanj - I'm not sure I understand what you mean by "goes beyond the screen view". From your screenshot, it seems the entire OSK is there (the p is all there, along with padding on the right). It just looks like the device is rounding corners on the top and bottom - out of our control.

@darcywong00 I thought the Backspace button has been cropped in the right bottom corner of the view when the Keyboard is in the landscape view. (please, see my attached screenshot). As per your comments, this is an expected one. Thanks for your comments.

**Comment by darcywong00** [comment]
OSK is displayed as intended
