### ISSUE TITLE
bug(android): Pressing Backspace key for a while make the cursor stuck on the text pane 

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#7069]
**Describe the bug**
After entering a word in the text pane I tried to delete all the characters by long pressing the Backspace key leads to stuck the cursor on the text pane. 

**To Reproduce**
1. Install Keyman 16.0.45 alpha build. 
2. Open Keyman In-App. 
3. Enter a word in the text pane.
4. Try to delete all the characters in the word by long pressing the Backspace Key. 

Here, I noticed that the cursor on the text pane get stuck and I was not able to delete any one of the character. I have attached the Screenshot as well as the Video file for reference. 

**Expected behavior**
Long pressing with the Backspace key should delete all the characters one by one. 

**Screenshots**

<img width="500" src="https://user-images.githubusercontent.com/19683143/184368802-753dc848-d5d6-4611-a00d-c5be0cce3d1f.PNG">

**Video**

https://user-images.githubusercontent.com/19683143/184367700-2cd4fac0-3387-460c-8eb9-785096d43b83.mp4

**Related issues**
https://github.com/keymanapp/keyman/issues/6544

---

**Keyman for Android:**
   Device:      Android Mobile
 - OS:            Android 11.0 
 - Keyman version:    16.0.45-alpha
 - Target Application: Keyman In-App

---

**Keyboard**
 - Keyboard name:   English - EuroLatin(SIL)
 - Keyboard version: 2.0
 - Language name:   English

**Additional context**
1. I was able to reproduce this issue in API 29 / Android 10 emulator. 
2. I was not able to reproduce this issue in iOS 15.5 / iPhone 13 Pro Max Simulator.

**Comment by MakaraSok** [comment]
Confirm that this issue does occur when testing with the latest alpha (v16.0.49) on Android 10 (API 29) and Android 11 (API 30).

**Comment by rowbory** [comment]
I saw it affect an Android user with version 15.0.268 last week, so it may not be new in 16.x.

**Comment by mcdurdin** [comment]
I believe this is fixed by #7156. Can you confirm @MakaraSok @bharanidharanj?

**Comment by bharanidharanj** [comment]
@mcdurdin  Retested this issue with Keyman 16.0.54-alpha-test-7156 build in both Android emulator and Redmi Note 8 Pro device (Ver 11.0) and I was not able to reproduce it. Seems to be fixed and working fine with the #7156 PR build. Hence, I am closing the same. Thanks.

**Comment by mcdurdin** [comment]
Just a note on process here. While the fix is testing fine with a PR, we don't normally close an issue until the fix is merged to master, and the developer would go ahead and close rellated issues once they do the merge. :grin:

**Comment by bharanidharanj** [comment]
> Just a note on process here. While the fix is testing fine with a PR, we don't normally close an issue until the fix is merged to master, and the developer would go ahead and close rellated issues once they do the merge. 😁

@mcdurdin Okay. Thanks for the Clarification, Marc. :-)
