### ISSUE TITLE
bug(linux): IBUS_CAP_SURROUNDING_TEXT does not reflect app capability due to ibus bug

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#7072]
**Describe the bug**

Keyman Engine for Linux tests for the client capability `IBUS_CAP_SURROUNDING_TEXT`. However, it turns out that this is simply a compile-time `#define` in IBus, and so we are really testing nothing.

In fact, ibus does not surface this capability to the IM. Fixing this requires a patch to ibus.

Relates to:
* #4505
* #1489

---

**Keyman for Windows/macOS/Linux/iPhone/iPad/Android:**
 - OS:                 Ubuntu 22.04

**Comment by mcdurdin** [comment]
See ibus/ibus#2054 for the underlying cause, which was a hack to workaround what appears to be a (bug in Firefox)[https://bugzilla.mozilla.org/show_bug.cgi?id=1506768]. We independently wrote a patch which was an exact reversion of this patch.

As of writing, the Firefox bug has been open for 4 years and is still untriaged.

**Comment by mcdurdin** [comment]
See ibus/ibus#2436 for a patch to ibus.

**Comment by ermshiperete** [comment]
Closing this issue since the upstream ibus repo now has a fix.
