### ISSUE TITLE
bug(web): model association with keyboards uses a case sensitive BCP 47 comparison

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#7075]
**Describe the bug**

If you register a keyboard with a BCP 47 tag of say `bal-latn`, and a model with the same tag, but with case differences, e.g. `bal-Latn`, then the association fails. This comparison should be case-insensitive.

---

**Keyman for Windows/macOS/Linux/iPhone/iPad/Android:**
   Device:             Samsung A90 5G 
 - OS:                 Android 11 
 - Keyman version:     15.0.268

**Comment by darcywong00** [comment]
I think this is somewhere in KMW. I edited the prediction-ui test page to use:

```
        kmw.addKeyboards({id:'balochi_latin',name:'Balochi Latin',languages:{id:'bal-Latn',name:'Balcohi (Latin Script)'},
          filename:('../balochi_latin-1.0.2.js')});

        var pageRef = (window.location.protocol == 'file:')
          ? window.location.href.substr(0, window.location.href.lastIndexOf('/')+1)
          : window.location.href;
   
        var modelStub = {'id': 'upp_ptwl1',
          languages: ['bal-latn'],
          path: (pageRef + "sil.bcc-latn.upp_ptwl1.model.js")
        };

        kmw.modelManager.register(modelStub);

```

I changed the keyboard to **Balochi (Latin Script)** and no suggestions appeared.
When I changed modelStub.languages from `bal-latn` to `bal-Latn`, the test page begins to generate suggestions.
