### ISSUE TITLE
bug(windows): Context is not reset on "Enter/Return" 

### ISSUE THREAD

**Issue by rc-swag** [keymanapp/keyman#7078]
**Describe the bug**
The `context`  for matching rules is not reset when return is pressed. The result is that if the key pressed on the new line plus the characters and the end of the previous line match the output can remove the CR and move the cursor to the previous line. 

**To Reproduce**

1. Installed Ethiopic - (Language Neutral) keyboard
2. Opened Notepad 
3. Typed: <kbd>a</kbd><kbd>s</kbd><kbd>d</kbd><kbd>f</kbd><kbd>Enter</kbd><kbd>a</kbd>
  Received: 
"አስድፍፋ"
  Expected: 
"አስድፍ
አ"

 Windows 15.0.268

**Comment by dyacob** [comment]
I guess "Language Neutral" refers to a SIL Ethiopic keyboards?  There was an older GFF keyboard that used this name, but hasn't been updated in ~5 years, not sure if it is still distributed.  I'll look for issues with GFF keyboards against the latest KM 15 , I had noticed at least one issue but more minor.

**Comment by rc-swag** [comment]
This particular issue is with KM15 but was discovered with the Ethopic keyboard mention. Is have a fix for the code I just need to raise the PR and do further testing. On the community site someone has said they had many issues with keyman 15 and this keyboard that are non existent in version 14. So I don't think there is a problem with the Keyboard. It is just this keyboard must show up bugs with KM15.

**Comment by rc-swag** [comment]
And yes @dyacob you are correct the "Language Neutral" used to reproduce the error was the GFF keyboard still distributed [here](https://keyman.com/keyboards/gff_ethiopic_7)
