### ISSUE TITLE
bug(android): OSK disappears from the bottom of the pane If I change the Keyboard Size into Maximum

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#7085]
**Describe the bug**
After changing the Keyboard Size into Maximum, I noticed that OnScreenKeyboard disappears from the bottom of the pane. 

**To Reproduce**
1. Install Keyman 16.0.48-alpha build in Android Mobile. 
2. Open Keyman In-App.
3. Click the Settings icon from the top right corner of the view. 
4. Click 'Adjust keyboard height' option. 
5. Verify that the Adjust keyboard height page opens. 
6. Drag the keyboard to the Maximum height. 
7. Click the Back button (2 times) to see the Main View. 
8. Here, I noticed that the OSK Keyboard disappears from the View. 

**Expected behavior**
The OSK should appear with the maximum height in the Main View. 

**Screenshots**
Set to an Average Height

   <img width="500" src="https://user-images.githubusercontent.com/19683143/185397030-82d59bfc-9487-4a05-a601-68b78c68a25c.jpg">

Set to Maximum Height
   <img width="500" src="https://user-images.githubusercontent.com/19683143/185397060-164b6561-2e60-4c62-b294-fc005b9d6237.jpg">

---

**Keyman for Android:**
   Device:  Redmi Note 8 Mobile     
 - OS:    Android 11.0
 - Keyman version:   16.0.48-alpha
 - Target Application: Keyman In-App

---

**Keyboard**
 - Keyboard name:   English - EuroLatin (SIL)
 - Keyboard version: 2.0
 - Language name:  English

**Comment by MakaraSok** [comment]
The OSK does appears when set as a system keyboard (see the screenshot below), yet it doesn't shown up at all in-app.

system keyboard:
<img width="806" alt="image" src="https://user-images.githubusercontent.com/28331388/186324492-4195f9d0-df4e-47b4-9da8-77e6da95750b.png">

in-app:
<img width="806" alt="image" src="https://user-images.githubusercontent.com/28331388/186324596-377d6aca-5d45-4ab0-8e23-cdaf462ab1f5.png">

**Comment by darcywong00** [comment]
Adding to what @MakaraSok noted. The in-app keyboard is visible at max landscape height **if** the suggestion banner is disabled...

I don't see javascript errors in the console, so maybe the in-app keyboard is clipping
