### ISSUE TITLE
bug(core): ldml—Cхх compiler issues

### ISSUE THREAD

**Issue by srl295** [keymanapp/keyman#7098]
- use `nullptr` instead of `NULL`
- debug output comments on https://github.com/keymanapp/keyman/pull/7083#pullrequestreview-1079764223
- multichar constants: https://zipcon.net/~swhite/docs/computers/languages/c_multi-char_const.html - redefine as a string.
- zero sized array is not appreciated by windows

**Comment by srl295** [comment]
zero sized array:  use `item entries[]` instead of `item entries[0]` (c99)

**Comment by mcdurdin** [comment]
Ah, not actually LDML compiler ... but C++ compiler issues for Core 😆  I was devastated for a moment because I hadn't even pushed my first commit on the compiler!

**Comment by srl295** [comment]
done with #7116 and #7100
