### ISSUE TITLE
feat(core): ldml vkey support 🙀

### ISSUE THREAD

**Issue by srl295** [keymanapp/keyman#7135]
- validate vkey table
- apply vkey lookup when hardware (non-touch) event
- revisit missing-vkey-as-error #9236 ?

#5015

**Comment by srl295** [comment]
- keyman core doesn't currently emit vkeys
- future feature

**Comment by srl295** [comment]
closed the PR For now, this will need to be a future feature

**Comment by srl295** [comment]
@mcdurdin close this 'now' that vkeys are dropped? Leaving a pointer here in case we need to get the code back.

**Comment by mcdurdin** [comment]
Yes will close.
