### ISSUE TITLE
bug(android): Holding backspace also seems to trigger a longpress on another random key 

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#7155]
From a team review of the Keyman for Android UX (#7161)

It was noted after accepting a suggestion, typing a character, and **holding** the backspace key,
* The backspace sometimes failed to delete and
* the longpress menu of the previous key would appear as long

Fixing the deletion will be addressed on a  separate issue. This one is for the longpress menu. 

**To Reproduce**
Use latest Keyman 16.0 alpha or released 15.0 stable
1. In the Keyman app with the default sil_euro_latin keyboard and lexical model enabled, start typing a word
2. Accept a suggestion
3. Type another letter
4. Hold the backspace key
5. The previous letter is deleted
6. Observe the longpress menu of the previous letter appearing

**Comment by mcdurdin** [comment]
Per @ermshiperete this also seems to happen with a longpress on Globe key. Can we make sure we test fixes against that scenario as well:

* bug: [EB] Long press on globe key (after having started typing) pops up longpress menu of the previous key; releasing then switches to next keyboard
