### ISSUE TITLE
bug(web): Highlighted suggestion freezes after multi-touch on the banner

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#7158]
**Describe the bug**
I noticed that after randomly pressing the predictive texts on the banner freezes the highlighted text at some point. 

**To Reproduce**
1. Install Keyman 16.0.53-alpha 
2. Open Keyman In-App. 
3. Adjust the Keyboard height to the maximum. 
4. Press the Predictive text randomly on the banner. 
5. Change the View from Portrait to Landscape mode. 
6. Adjust the Keyboard height to the maximum. 
7. Press the Predictive text randomly on the banner. 
8. Here, I noticed that the highlighted Predictive text freezes at some point on the banner. 

I have attached the Screenshots as well as the Video file for your reference. 

**Expected behavior**
It should not be stuck at any point and it always highlighted when we press on any predictive text. 

**Screenshots**
..in Portrait view

   <img width="300" src="https://user-images.githubusercontent.com/19683143/187464012-5364a060-e69d-44be-8800-4f19188432ac.jpg">

..in Landscape view

   <img width="500" src="https://user-images.githubusercontent.com/19683143/187464033-125d2672-3450-4ff8-b2f1-3251bff38544.jpg">

---

**Keyman for Android:**
   Device:          Redmi Note 8 Pro
 - OS:               Android 11.0 
 - Keyman version:    16.0.53-alpha
 - Target Application: Keyman In-App

---

**Keyboard**
 - Keyboard name:   English - EuroLatin (SIL)
 - Keyboard version:  2.0
 - Language name:    English

**Comment by darcywong00** [comment]
I don't think the steps about rotating the device or changing the keyboard height are pertinent.

In my attempts to reproduce this on an actual device, maybe it involves multi-touch.
I'm trying to simultaneously 
* left thumb touch a suggestion
* right thumb touch a key 
* release both thumbs before the right thumb triggers a longpress (maybe release the right thumb slightly before left thumb)

**Comment by darcywong00** [comment]
See also 
https://github.com/keymanapp/keyman/pull/7472#issuecomment-1285007685
