### ISSUE TITLE
bug(web): unnecessary flicker on banner while typing

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#7162]
**Describe the bug**

From a team review of the Keyman for Android UX (#7161)

Even if suggestions remain the same, they blink out, then in again on each keystroke. It causes a flicker that is quite distracting while typing two-thumbs, and shouldn't be necessary!

**Expected behavior**

No flicker -- we should not see a blank unless we actually have no suggestions available. Perhaps delay updating the banner until the next suggestion lookup completes?

**Screenshots**

In the following video, I am typing slowly but you can see how the suggestions disappear and reappear with each keystroke, even if they don't change. Particularly noticeable on backspace.

https://user-images.githubusercontent.com/4498365/187516392-8e99c4e1-d4ef-4229-8d9f-c3a6627181c3.mp4

**Related issues**

---

**Keyman for Windows/macOS/Linux/iPhone/iPad/Android:**
 - Device:             Samsung A90 5G 
 - OS:                 Android 12 
 - Keyman version:     15.0.269-stable

**Comment by mcdurdin** [comment]
This seems to me to be adequately addressed in v17.0. @jahorton do you know which PR would have resolved this?

**Comment by jahorton** [comment]
I'd have to go digging and experimenting in order to tell.  I'm not even sure if it was the gesture work (🐵) or the ES-modularization work (🧩) that would have fixed it... though likely the latter.

I did note the link mentioned above for a 🧩 PR, but I can't find an actual comment referring to this one from there.

**Comment by mcdurdin** [comment]
Fixed by #8544 or related PRs.

(Note the "619 hidden items" 😨 on that PR means that the reference to this issue will be somewhere in that conversation history I guess!)

![image](https://github.com/keymanapp/keyman/assets/4498365/451806e9-9252-4b38-b4be-382259537101)
