### ISSUE TITLE
feat(android): separate icon for alpha and beta builds of Keyman

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#7182]
It's possible to have alpha, beta and stable builds of Keyman installed on a phone -- but they all have the same icon. Just a little bit of text at the bottom saying "Alpha" or "Beta" would help a lot. For extra points, include the version number and PR# if it's a test build!

**Comment by darcywong00** [comment]
This probably involves editing the `kMAPro/src/main/res/**/ic_launcher.png` and `ic_launcher_round.png` files

**Comment by darcywong00** [comment]
> For extra points, include the version number and PR# if it's a test build!

That info is now appended to the app name from #7674 so we probably won't need it on the icon.

**Comment by mcdurdin** [comment]
Given the app name now shows Alpha or Beta, we could go ahead and close this -- it's probably sufficient as it is.
