### ISSUE TITLE
bug(iOS): In-app text initially appears smaller than the value in the Text Size setting

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#7185]
**Describe the bug**
The initial text size when typing with the in-app keyboard is smaller than the default Text Size setting.
**To Reproduce**
1. Install Keyman 16.0.54-alpha build in iPhone 13 Pro Max Simulator. 
2. Open Keyman In-App.
3. Type some text on the Text pane. 
4. Notice that the font size is smaler than the default Text Size setting. 
5. Click the 3 dots button. 
6. Click the Text Size button. 
7. Verify that the Text Size dialog appear on the screen. 
8. Click on the slider button without actually moving it and notice the size of the existing text immediately grows in size to match the Text Size setting.

**Expected behavior**
Typing on the Text pane should always match the default Text Size setting. 

**Screenshots**
iPhone 13 Pro Max Simulator:

   <img width="500" src="https://user-images.githubusercontent.com/19683143/187893437-c11cb207-0c6e-48b0-80a6-b6d067724d00.png">

iPad 9th generation Simulator:

  
<img width="500" src="https://user-images.githubusercontent.com/19683143/187894000-f68f7a1f-f270-4771-bbc0-e30a6e93052f.png">

---

**Keyman for iPhone/iPad:**
   Device:   iPhone 13 Pro Max Simulator / iPad 9th generation Simulator  
 - OS:  iOS 15.5          
 - Keyman version:  Keyman 16.0.54 alpha    
 - Target Application: Keyman In-App

---

**Keyboard**
 - Keyboard name:    English - EuroLatin(SIL)
 - Keyboard version: 2.0
 - Language name:    English

**Additional context**
Able to reproduce this issue in iPad Simulator. It would be better to reproduce this issue in iPhone real device.

**Comment by sgschantz** [comment]
Was able to reproduce with simulator, iPhone 13 mini and iOS 15.4
