### ISSUE TITLE
chore(android): Add Toast notifications to KMLog

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#7189]
Ironically, I would suggest adding toasts to LogError and LogException if they are not there already, so the user knows something has gone wrong and can report the error to us (assuming they remember the message at all!)

_Originally posted by @mcdurdin in https://github.com/keymanapp/keyman/pull/7178#discussion_r960186869_

**Comment by darcywong00** [comment]
One note, a lot of the Toast notification strings are localized, whereas our Log messages going ot Sentry need to remain in English.

**Comment by mcdurdin** [comment]
Yeah, I am figuring if we get a low-level error, even reporting it in English is better than silent doom. But that may not be consistently true.

**Comment by darcywong00** [comment]
Will need to investigate how many KMLog.LogExceptions() are already followed with a Toast notification...
