### ISSUE TITLE
bug(core): ldml kmx_plus loading does not validate checksum, version, etc🙀

### ISSUE THREAD

**Issue by srl295** [keymanapp/keyman#7220]
for: #5015 #7136

**Comment by mcdurdin** [comment]
Let's see if we can extract the relevant validation code from the kmx keyboardprocessor into a shared file?

Query: do we make checksum optional for 16.0 onwards? We'd still verify the checksum if non-zero but allow files with a zero field for checksum. Note that this would have ripple effects into other sources which also parse .kmx files -- but we are probably going to need to review those for kmxplus support at some point anyway.

**Comment by mcdurdin** [comment]
process note: we don't normally close the issue until the corresponding PR has merged :)

**Comment by srl295** [comment]
> process note: we don't normally close the issue until the corresponding PR has merged :)

earlier mistake. ready to close now
