### ISSUE TITLE
feat: make checksum optional in .kmx 🙀

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#7222]
Query: do we make checksum optional for 16.0 onwards? We'd still verify the checksum if non-zero but allow files with a zero field for checksum. Note that this would have ripple effects into other sources which also parse .kmx files -- but we are probably going to need to review those for kmxplus support at some point anyway.

_Originally posted by @mcdurdin in https://github.com/keymanapp/keyman/issues/7220#issuecomment-1238708984_

**Comment by ermshiperete** [comment]
What do we gain by having and verifying the checksum? Not requiring it means we don't have to implement checksum handling for ldml, but I guess there was a reason that checksums were added in the past.

**Comment by mcdurdin** [comment]
Checksum was valuable when dodgy media was common -- it stopped people loading a keyboard and wondering why it was going wrong. However, these days, this rarely is an issue. It doesn't help for malicious content and so just adds friction. We still need to check file structural validity even if there is a valid checksum, so I don't think we gain much from having it.

Removing the requirement means that generating and updating files for testing becomes significantly easier (esp. e.g. with hextobin). That's the primary benefit I can see.

**Comment by mcdurdin** [comment]
Throwing this into the epic-ldml bucket, so will merge with feature-ldml.
