### ISSUE TITLE
bug(web): Pin the OSK, KeymanWeb Configuration and the Keyman Web Help options are not working in any Virtual Keyboard

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#7226]
I noticed that by clicking on the 'Pin the OSK..', KeymanWeb Configuration and the Keyman Web Help options in any Virtual Keyboard is not at all working. 

<img width="500" src="https://user-images.githubusercontent.com/19683143/185345866-6d389116-10f2-4ea1-85fa-3390eede2896.png">

Note: I was able to reproduce this in the Stable Release too.

**Comment by mcdurdin** [comment]
This is a long-standing issue. We do need to address it.

**Comment by jahorton** [comment]
Could you please elaborate?

Note that the configuration button and the help button have pretty much been dead for as long as I can remember.  Like, I don't even know what the _right_ behavior for them would be.

If the `pin` doesn't work, I could use more information - it's working perfectly fine for me, both in isolation and on keymanweb.com.  (Windows / Firefox)

As a reminder re: the 'pin' icon:  Dragging the OSK to a new location on the page will activate "pinned" mode automatically, and the OSK should not move from that position unless you deactivate the pin or manually move it elsewhere.

**Comment by mcdurdin** [comment]
> Note that the configuration button and the help button have pretty much been dead for as long as I can remember. Like, I don't even know what the _right_ behavior for them would be.

Well, clearly a problem then!

So clarification desired just on the pin?

**Comment by jahorton** [comment]
> [...] Like, I don't even know what the _right_ behavior for them would be.
> 
> Well, clearly a problem then!
> 
> So clarification desired just on the pin?

For "is this a bug or not", just the pin, yes.

That said, I don't have a clue what our desired solution is to the other two parts.  Like, I can think of a future feature to shunt in under the config icon, but not one for now, let alone previous versions.

**Comment by mcdurdin** [comment]
The non-functional buttons are a bug too -- let's hide them if they don't do anything. (Aside from that, they are a little ugly...)

**Comment by mcdurdin** [comment]
> Just... published events, should a site designer want them.

Are the events documented? If not, we can probably consider them 'experimental' APIs and safely remove them :grin:

**Comment by jahorton** [comment]
They are listed at https://help.keyman.com/developer/engine/web/15.0/reference/events/.

**Comment by jahorton** [comment]
https://help.keyman.com/developer/engine/web/15.0/reference/events/osk.configclick

https://help.keyman.com/developer/engine/web/15.0/reference/events/osk.helpclick

The way the documentation is worded, it sounds as if KMW should be taking an action when these events are raised.  So, it's almost like these events were to allow add-ons/side effects, rather than being the main 'feature' of the buttons.
