### ISSUE TITLE
bug(iOS): the spacebar caption doesn't get refresh until after switching to a different keyboard

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#7228]
**Describe the bug**

The Spacebar Caption doesn't change to the chosen option immediately. It will do so when the globe key is pressed or the keyboard is switched.

**To Reproduce**

1. Go to "Spacebar caption"
2. Choose "Blank"
3. Click "Done" on the top left
 
To make the Caption switches, please on the globe key or switch the keyboard.

**Expected behavior**

After clicking "Done," the Spacebar should have a chosen label.

**Related issues**

https://github.com/keymanapp/keyman/issues/6603

---

**Keyman for Windows/macOS/Linux/iPhone/iPad/Android:**
   Device:              iPad mini 6
 - OS:                  15.6.1
 - Keyman version:      16.0.56-alpha
 - Target Application:  Keyman

**Comment by darcywong00** [comment]
I think ios-host.js will neeed to add the last 2 lines to match Android functionality (:


function setSpacebarText(mode) {
    keyman.options['spacebarText'] = mode;
    keyman.osk.show(true);

    // Refresh KMW OSK
    keyman.correctOSKTextSize();
}

---

## User Testing

* **TEST_SPACEBAR_CAPTION_IOS** - Verifies issue #7228 on iOS is fixed
Note - I'm not familiar with the specific Settings and menus on Keyman for iPhone and iPad. Maybe @sgschantz can tweak steps if needed)
1. Load the PR build of Keyman for iPhone and iPad
2. From Keyman Settings, search for and install another keyboard (e.g. sil_cameroon_qwerty keyboard for the "Basa" language)
3. Verify the default OSK spacebar caption shows **Language + Keyboard** (e.g. Basa - Cameroon QWERTY)
4. Go to Keyman settings --> change Spacebar caption to **Language** --> exit the Settings menu
5. Verify the OSK spacebar caption shows **Language** (e.g. Basa)
6. Go to Keyman settings --> change Spacebar caption to **Keyboard** --> exit the Settings menu
7. Verify the OSK spacebar caption shows **Keyboard** (e.g. Cameroon QWERTY)
8. Go to Keyman settings --> change Spacebar caption to **Language + Keyboard** --> exit the Settings menu
9. Verify the OSK spacebar caption shows **Language + Keyboard** (e.g. Basa - Cameroon QWERTY)
10. Go to Keyman settings --> change Spacebar caption to **Blank** --> exit the Settings menu
11. Verify the OSK spacebar caption shows **Blank** (e.g. no caption)

**Comment by bharanidharanj** [comment]
* **TEST_SPACEBAR_CAPTION_IOS (FAILED):** Tested with Keyman 16.0.69-alpha build in both iPhone 14 Pro (iOS 16.0) and iPad Pro (3 generation) Simulators and it is failed in both the Simulators. 


..in iPhone 14 pro / iOS 16.0
   
   <img width="500" src="https://user-images.githubusercontent.com/19683143/192530695-2107a520-c2d3-4bcd-916c-bf8e5920e4c9.png">


..in iPad Pro (3 generation) / iOS 16.0

<img width="500" src="https://user-images.githubusercontent.com/19683143/192528764-4d851cb2-5f1f-454e-ae9c-25fb3fa6311a.png">
