### ISSUE TITLE
bug(windows): in Word, backspace only deleting half a surrogate pair in Keyman 15

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#7231]
**Describe the bug**

Using any keyboard that produces supplementary plane characters, pressing backspace to delete a non-bmp char in Word only deletes half the surrogate pair a time. In Notepad, this works correctly.

Additionally, <kbd>t</kbd><kbd>space</kbd> <kbd>AltGr</kbd>+<kbd>Left arrow</kbd>, or <kbd>AltGr</kbd>+<kbd>Right</kbd> fails badly too.

I have not yet tried this with 14.0 but the original reporter of the issue notes it is working correctly there.

---

**Keyman for Windows/macOS/Linux/iPhone/iPad/Android:**
 - OS:                 Windows 10 
 - Keyman version:     15.0.269 
 - Target Application: Word 

---

**Keyboard**
 - Keyboard name:    egyptian07 
 - Keyboard version: 

This was provided privately -- I can share privately if needed if you cannot repro with other keyboards.

**Comment by rc-swag** [comment]
Raise an issue to get windows specific unit tests working again since the core location reshuffle and add the unit tests two kmprocessactionstests.cpp to test for the cases this PR fixes.
