### ISSUE TITLE
chore(web): TransformUtils.insertWhitespace seems convoluted

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#7232]
This seems a little convoluted.

* I'm really not sure exactly what we are testing here. It seems like you are looking for `insert.match(/[\u0009...]$/)`? Is it intended to match having a single whitespace character on the end of the text? If so, then the function name is not very clear. If not, then AFAICT the function is not correct.

* `i` modifier should not be necessary on the regex -- there's no case to be insensitive about 🤣.

* Can we use a [character class](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Unicode_Property_Escapes) for the regex match rather than a set of characters? (e.g. `insert.match(/[\p{Z}\r\n]$/u)`. Note Chrome 50+ though (so we could have the shorter regex as a comment if we can't use it for back-compat reasons).

* Finally, can we have a javadoc comment rather than the in-function comment?

_Originally posted by @mcdurdin in https://github.com/keymanapp/keyman/pull/7205#discussion_r965345369_

**Comment by mcdurdin** [comment]
JH [wrote](https://github.com/keymanapp/keyman/pull/7205#discussion_r965418540):

> Keep in mind that I did not edit this function _at all_.  I simply extracted it from its prior home.  From `master`:
> 
> https://github.com/keymanapp/keyman/blob/80d7ce78bedccda20f73982ac74d26da73b5c63c/common/web/lm-worker/src/model-compositor.ts#L19-L33
> 
> This all dates back to #1851, and @eddieantonio was the one responsible for that regex: https://github.com/keymanapp/keyman/pull/1851#discussion_r300022560
> 
> Can't speak to why he didn't use a character class here, but I figure that there was some reason or other.  For what it's worth, following that character class link and drilling down to the actual classes:  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Character_Classes
> 
> I don't see a compatibility chart there.  Now, there are other ways to search for this...
> 
> https://caniuse.com/mdn-javascript_builtins_regexp_property_escapes
> 
> Note the minimum Chrome version listed there - if desktop Chrome didn't support these property escapes before version 64, I doubt that mobile had it implemented at that time.  This, to me, implies a strong chance that using them would break predictive text outright on non-updated Android 5.0 devices, at the least.
> 
> ------
> 
> Where do you see a `$` in the regex string here?  Is it implied with the flags on the pattern?  It's certainly not present in plain-text.
> 
>

**Comment by jahorton** [comment]
Well... we ended up going ahead and addressing it ahead of time anyway.  Took a few iterations to settle on the solution, though.

**Comment by mcdurdin** [comment]
> Well... we ended up going ahead and addressing it ahead of time anyway. 

Can you link the PR that addressed this?
