### ISSUE TITLE
feat(developer): ldml - support UnicodeSets in LDML keyboards 🙀

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#7234]
UnicodeSets -- brain dump from discussion earlier this week

* Parser within compiler
* Appropriate binary form
  * Usage within keyboardprocessor: for now, will be a pure string of characters to choose from. later needs a performant binary format.
  * → UnicodeSet subset for ldml keyboard spec?
  * Allow UnicodeSets up to 1024 chars max for sanity for now. This will need to change because it doesn't cope with inverse sets.
  * Supported patterns
`\uxxxx`
`[abc]`
`[a-z123]`
`[\u1234-\u2468]`

Nopes for now:
* `[\u0001-\u10ffff]` ← binary format issues
* `[^a]` ← binary format issues
* `[]`  ← disallow, non-character

Refs:

* Intl  -> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl
* https://github.com/tc39/ecma402
* https://caniuse.com/?search=intl
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Unicode_Property_Escapes 
* https://github.com/node-unicode/node-unicode-data
* UnicodeSet in rust: https://unicode-org.github.io/icu4x-docs/doc/icu_collections/index.html

**Comment by mcdurdin** [comment]
Will be using ICU components to transform to regex in compilation. Closing as discussion here is ancient history.

**Comment by mcdurdin** [comment]
Turns out that we need to implement a UnicodeSet parser in the compiler. But the discussion here is still out of date.

**Comment by srl295** [comment]
Just to consolidate this:

- linked PR pulls in ICU4C (but patched to not support properties)
- ICU4X TODO issue: https://github.com/unicode-org/icu4x/issues/168 
- Filed upstream ICU ticket https://unicode-org.atlassian.net/browse/ICU-22375 for changes
