### ISSUE TITLE
feat(developer): ldml - support import in .xml 🙀

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#7236]
brain dump from discussion earlier this week

1. Need some additional sample data here (SRL AAC side)
~2. should have an automated process for keeping the 'CLDR bundle' up to date (right now)
https://github.com/keymanapp/keyman/tree/feature-ldml/resources/standards-data/ldml-keyboards/techpreview or from here~
~3. source data is at: https://github.com/unicode-org/cldr/tree/keyboard-preview/keyboards/import. This will be manual action at present. (Make a script to do this [SRL to make issue])~

**Comment by srl295** [comment]
related to #7534 

note that the 'automatic update' above is already done

**Comment by mcdurdin** [comment]
Done in #7534.
