### ISSUE TITLE
Build the master: error

### ISSUE THREAD

**Issue by chandrab699** [keymanapp/keyman#725]
I am getting the below error while building the master. Please help.

```
Build started 4/2/2018 10:30:57 PM.
     1>Project "c:\keyman\windows\src\buildtools\getfilelocks\getfilelocks.sln" on node 1 (Clean target(s)).
     1>ValidateSolutionConfiguration:
         Building solution configuration "Release|Win32".
     1>Project "c:\keyman\windows\src\buildtools\getfilelocks\getfilelocks.sln" (1) is building "c:\keyman\windows\src\buildtools\getfilelocks\getfil
       elocks.vcxproj" (2) on node 1 (Clean target(s)).
     2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Current.targets(108,3): error MSB4019: Th
       e imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Platforms\Win32\Platform.targets" w
       as not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. [c:\keyman\windows\src\buildtool
       s\getfilelocks\getfilelocks.vcxproj]
     2>Done Building Project "c:\keyman\windows\src\buildtools\getfilelocks\getfilelocks.vcxproj" (Clean target(s)) -- FAILED.
     1>Done Building Project "c:\keyman\windows\src\buildtools\getfilelocks\getfilelocks.sln" (Clean target(s)) -- FAILED.

Build FAILED.

       "c:\keyman\windows\src\buildtools\getfilelocks\getfilelocks.sln" (Clean target) (1) ->
       "c:\keyman\windows\src\buildtools\getfilelocks\getfilelocks.vcxproj" (Clean target) (2) ->
         C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Current.targets(108,3): error MSB4019:
       The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Platforms\Win32\Platform.targets"
        was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. [c:\keyman\windows\src\buildto
       ols\getfilelocks\getfilelocks.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.23

** error 1 ** deleting clean

** error 1 ** deleting getfilelocks

** error 1 ** deleting clean

** error 1 ** deleting buildtools

** error 1 ** deleting clean
```

**Comment by chandrab699** [comment]
make build
MAKE Version 5.41  Copyright (c) 1987, 2014 Embarcadero Technologies, Inc.
        make -l          -DTARGET=build ext global buildtools developer engine desktop support
MAKE Version 5.41  Copyright (c) 1987, 2014 Embarcadero Technologies, Inc.
        cd c:\keyman\windows\src\buildtools\devtools
        make -l
MAKE Version 5.41  Copyright (c) 1987, 2014 Embarcadero Technologies, Inc.
        C:\PROGRA~2\EMBARC~1\Studio\19.0\bin\dcc32 -Q -B -E. -NSVcl;Vcl.Imaging;Vcl.Touch;Vcl.Samples;Vcl.Shell;System;Xml;Web;Soap;Winapi;System.Win devtools.dpr
Embarcadero Delphi for Win32 compiler version 32.0
Copyright (c) 1983,2017 Embarcadero Technologies, Inc.
C:\keyman\windows\src\global\delphi\general\RegistryKeys.pas(222) Hint: H1054 Refactor this to use SRegKeyNode naming (no prefix \); fixup references
7687 lines, 0.52 seconds, 2194128 bytes code, 46352 bytes data.
        copy devtools.exe c:\keyman\windows\bin\buildtools
        1 file(s) copied.
        c:\keyman\windows\bin\buildtools\devtools -ti
        cd c:\keyman\windows\src\ext
        make -l          build
MAKE Version 5.41  Copyright (c) 1987, 2014 Embarcadero Technologies, Inc.
        make -l          -DTARGET=build  dcpcrypt embeddedwb jedi mbcolor regexpr scfontcombobox
MAKE Version 5.41  Copyright (c) 1987, 2014 Embarcadero Technologies, Inc.
        cd c:\keyman\windows\src\ext\dcpcrypt
        make -l          build
MAKE Version 5.41  Copyright (c) 1987, 2014 Embarcadero Technologies, Inc.
DCC32 c:\keyman\windows\src\ext\dcpcrypt\DCPdelphi2009.dpk
Embarcadero Delphi for Win32 compiler version 32.0
Copyright (c) 1983,2017 Embarcadero Technologies, Inc.
14127 lines, 0.33 seconds, 210992 bytes code, 74380 bytes data.

exit code =0
        make -l          install
MAKE Version 5.41  Copyright (c) 1987, 2014 Embarcadero Technologies, Inc.
        c:\keyman\windows\bin\buildtools\devtools.exe -ip c:\keyman\windows\lib\DCPdelphi2009.bpl
installpackage c:\keyman\windows\lib\DCPdelphi2009.bpl
        c:\keyman\windows\bin\buildtools\devtools.exe -ai c:\keyman\windows\src\ext\dcpcrypt
addincludepath c:\keyman\windows\src\ext\dcpcrypt
EVariantTypeCastError: Could not convert variant of type (Null) into type (OleStr)

** error 5 ** deleting install

** error 1 ** deleting build

** error 1 ** deleting dcpcrypt

** error 1 ** deleting build

** error 1 ** deleting ext

** error 1 ** deleting build

**Comment by mcdurdin** [comment]
Did you resolve these issues? If not, can you give a bit more detail about your build environment? Which version and edition of Delphi are you using? Are you on Windows 10 or a different version of Windows?
