### ISSUE TITLE
feat(developer): Send to Email in the Web Debugger should have option to open default mail client, and/or copy to clipboard

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#726]
From https://community.software.sil.org/t/keyman-10-beta-feedback/715/23

It would be useful to be able to open an mail in the default mail client, in order to send the connection details, as well as direct SMTP. Another option would be to copy the mail text to the clipboard and paste in whereever.

**Comment by darcywong00** [comment]
This is no longer needed with the Keyman Developer server in #6073
