### ISSUE TITLE
feat(developer): include store() metadata in kmc-generated keyboards 🙀

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#7273]
In order to install a KMXPlus keyboard, it will be important that we have kmx `store` metadata in the keyboard. The following stores may be required or desirable initially:

* [`TSS_KEYBOARDVERSION`, `&KeyboardVersion`](https://help.keyman.com/developer/language/reference/keyboardversion): keyboard version from `<version>` element.
* [`TSS_NAME`, `&Name`](https://help.keyman.com/developer/language/reference/name): the first `<name>` from the `<names>` element.
* [`TSS_TARGETS`, `&Targets`](https://help.keyman.com/developer/language/reference/targets): correlate to `layerMaps` in the source keyboard, `'desktop'` if a hardware map is included, and/or `'mobile tablet'` if touch maps are included; we may want to make this more fine-grained in future.
* `TSS_COMPILEDVERSION`: version of the compiler that generated the keyboard (which may be `>= TSS_VERSION`)

Other stores that should be included but are not required to get it to load include:

* [`&Bitmap`](https://help.keyman.com/developer/language/reference/bitmap) + icon data referenced in `COMP_KEYBOARD`
* [`&CapsOnOnly`, `&CapsAlwaysOff`, `&ShiftFreesCaps`](https://help.keyman.com/developer/language/reference/caps)
* [`&Copyright`](https://help.keyman.com/developer/language/reference/copyright)
* [`&Message`](https://help.keyman.com/developer/language/reference/message)
* `TSS_VKDICTIONARY`: mapping between virtual key codes and key names for touch layouts?
* [`TSS_VERSION`, `&Version`](https://help.keyman.com/developer/language/reference/version): this field is duplicated in `COMP_KEYBOARD.dwFileVersion`, but should be included for consistency with existing kmx files.

**Comment by srl295** [comment]
> bitmap

Synthesize something? Or an ldml extension?

> Caps…

Can this be calculated by inspection?

> Copyright

Do we need this in LDML?

> Message

This could include the author.

**Comment by mcdurdin** [comment]
> > bitmap
> 
> Synthesize something? Or an ldml extension?

I think we do an LDML extension when we want this. Currently only used by Windows and macOS versions of Keyman, but we want to support it elsewhere in future. The extension could specify a .png set (current binary format must be .bmp or .ico but we will de-Windows-ify this a bit further when we do this since it requires a new version of Keyman anyway), or it could specify text which is auto-generated into an icon by the compiler.

> > Caps…
> 
> Can this be calculated by inspection?

At present, no. Shift Frees Caps, Caps On Only, Caps Always On are really around the behaviour of the Caps Lock key and allows users to specify European-layout style behaviours for it.

> > Copyright
> 
> Do we need this in LDML?

Dunno. But many keyboard authors have wanted to have a copyright message in the past. I think it's important. Initially, we could just say `Author: <name>` but we should consider whether a `Copyright (C) <year> <name>` message should be included in the ldml format or a Keyman-specific extension.

> > Message
> 
> This could include the author.

Yep. Or a Keyman extension. However, this one is low priority -- there are better places to put additional messages, such as in keyboard docs.

**Comment by mcdurdin** [comment]
One other potential wrinkle. Currently, Keyman determines if a keyboard has Unicode support on the basis of the `COMP_KEYBOARD.StartGroup[BEGIN_UNICODE]` value. However, KMXPlus keyboards have no StartGroup. We can address this in one of two ways:

1. Add an empty start group (you will have seen that in the binary checksum unit test data) and use that
2. Update all the readers to assume that presence of KMXPlus means Unicode support.

Option 2 is probably the better solution but right now there are readers for Windows, macOS, Linux, plus development tools, so it's more places to touch. We don't have to worry about older versions because they won't load the file anyway due to its high version number in `COMP_KEYBOARD.dwFileVersion`.

**Comment by srl295** [comment]
> > > bitmap
> > Synthesize something? Or an ldml extension?
> I think we do an LDML extension when we want this…png

sounds good. An extension could specify an external file if need be.

> > > Caps…
> > Can this be calculated by inspection?
> At present, no. Shift Frees Caps, Caps On Only, Caps Always On are really around the behaviour of the Caps Lock key and allows users to specify European-layout style behaviours for it.

another extension

> > > Copyright
> > Do we need this in LDML?
> Dunno. But many keyboard authors have wanted to have a copyright message in the past. I think it's important. Initially, we could just say `Author: <name>` but we should consider whether a `Copyright (C) <year> <name>` message should be included in the ldml format or a Keyman-specific extension.

could be an extension, or could be something like a:
  - description (free form extended description)
  - 'rights'/terms/license - copyright or similar. 

> > > Message
> > This could include the author.
> Yep. Or a Keyman extension. However, this one is low priority -- there are better places to put additional messages, such as in keyboard docs.

:+1:

**Comment by srl295** [comment]
> One other potential wrinkle. Currently, Keyman determines if a keyboard has Unicode support on the basis of the `COMP_KEYBOARD.StartGroup[BEGIN_UNICODE]` value. However, KMXPlus keyboards have no StartGroup. We can address this in one of two ways:
> 
> 1. Add an empty start group (you will have seen that in the binary checksum unit test data) and use that

that's https://github.com/keymanapp/keyman/pull/7255/files#diff-ceb318405423a3fb74fd68fbc698c147f3fe273ec4dde5ea75b5adc010e6b1aeR39 ? Not know

> 2. Update all the readers to assume that presence of KMXPlus means Unicode support.
> 
> Option 2 is probably the better solution but right now there are readers for Windows, macOS, Linux, plus development tools, so it's more places to touch. We don't have to worry about older versions because they won't load the file anyway due to its high version number in `COMP_KEYBOARD.dwFileVersion`.

but… don't the readers need to be revved anyway to include the ldml_processor?  Maybe I'm not clear on the data flow, of where this would be read apart from where the ldml_processor code would be.

**Comment by mcdurdin** [comment]
> that's https://github.com/keymanapp/keyman/pull/7255/files#diff-ceb318405423a3fb74fd68fbc698c147f3fe273ec4dde5ea75b5adc010e6b1aeR39 ? Not know

Yep

> but… don't the readers need to be revved anyway to include the ldml_processor? Maybe I'm not clear on the data flow, of where this would be read apart from where the ldml_processor code would be.

Yep. But that's the readers we know about and maintain (there are others out there). We want to be forward-compatible as far as possible. Certainly the presence of a higher version number means, according to the 'spec' (as it exists in my head, anyway), that no assumptions should be made about the file format. But there are specs and then there are implementations. I wish to be as kind as possible to the existing implementations.
