### ISSUE TITLE
chore: mark `dwFileCheckSum` as deprecated in headers 🙀

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#7276]
> I assume kmx_plus should still validate the checksum, iff present?

Maybe? Or we could consider it irrelevant and deprecated and ignore it? I actually think that may be better. That suggests to me I should be adding a `// DEPRECATED in 16.0` comment to the header files.

_Originally posted by @mcdurdin in https://github.com/keymanapp/keyman/issues/7255#issuecomment-1244393034_

also see #7222

**Comment by mcdurdin** [comment]
Resolved to make 16.0 readers ignore dwChecksum.

**Comment by srl295** [comment]
see if i can get this one in

**Comment by srl295** [comment]
Done in #7300
