### ISSUE TITLE
bug: Video link appears under Whats' New topic in iOS whereas the same link is missing in Android 

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#7292]
**Describe the bug**
I noticed that there is a video link appear under What's New topic in iOS and the same link missing Android. 

**To Reproduce**
1. Install Keyman (any version) in iPhone Simulator. 
2. Open Keyman.
3. Click the Info page. 
4. Click What's New link. under About Keyman heading. 
5. Here, we may notice that there is a video link 'Watch a Video' appears on the view. 
6. Install Keyman (any version) in Android Emulator.
7. Open Keyman.
8. Click the Info page. 
9. Click What's New link, under About Keyman heading.
10. Here, I noticed that there no video link that tells the user any new features of the build. 

**Expected behavior**
It would be better to have a video link that tells the user about new features of the Keyman. 

**Screenshots**

..iPhone 13 Pro Max

   <img width="300" src="https://user-images.githubusercontent.com/19683143/190136689-d86f2cd2-2379-4461-9751-c6d5b4b039c5.png">

..Android Version 11.0

   <img width="300" src="https://user-images.githubusercontent.com/19683143/190136709-df841881-4a42-4c76-81bc-28f8a9774592.jpg">

---

**Keyman for iPhone/iPad/Android:**
   Device:            iPhone 13 Pro Simulator, Redmi Note 8 Pro 
 - OS:                iOS 15.0, Android 11.0
 - Keyman version:     English-EuroLatin(SIL)
 - Target Application: Keyman App

---

**Comment by darcywong00** [comment]
The video links were added for the Keyman 14.0 release to highlight some of the new features.

Keyman for Android used to have a similar link in 14.0 at
https://help.keyman.com/products/android/14.0/about/whatsnew

For Keyman for Android 15.0, the content for "whatsnew" was replaced with 15.0 features.

**Comment by darcywong00** [comment]
I note some of the other Keyman products have removed the video link in 15.0

https://help.keyman.com/products/mac/15.0/about/whatsnew
https://help.keyman.com/products/windows/15.0/about/whatsnew

**Comment by mcdurdin** [comment]
If anything, we should be removing the video links from the iOS content. But I think we can close this issue for now as we will be updating with 16.0 content before too long, for all platforms.
