### ISSUE TITLE
refactor(web): move to es modules and appropriate build tools for bundling keymanweb.js

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#7309]
The js module fight seems to have resolved in favour of ES modules. It'll be some time before we can use them in browsers that we support. However, we can use bundling tools like webpack, browserify, or esbuild to transpile them into a bundle.

We should be:

1. Ceasing use of namespaces
2. Replacing all uses of `require()` and other, more hacky, import methods to ESM `import`.
3. Moving from tsc's project prepending tool to use of a bundling tool where needed for deployable artifacts
4. Updating all package.json and tsconfig.json to refer to the appropriate module format.

See also #7328

**Comment by jahorton** [comment]
An important note for handling our predictive-text engine when doing such a migration:  https://esbuild.github.io/content-types/#function-tostring

> This problem most often comes up when people get the source code of a function with .toString() and then try to use it as the body of a [web worker](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API). If you are doing this and you want to use esbuild, you should instead build the source code for the web worker in a separate build step and then insert the web worker source code as a string into the code that creates the web worker. The [define](https://esbuild.github.io/api/#define) feature is one way to insert the string at build time.

**Comment by jahorton** [comment]
Also of note:  https://esbuild.github.io/api/#keep-names

Doesn't seem to allow piece-meal preservation of only some class & function names, but it'll at least prevent esbuild minification from stomping on our API function names.

**Comment by jahorton** [comment]
#8560 has merged!  🎊 

We now fully use ES6-style modules for Web's source and utilize esbuild to bundle it for deployment.  Namespaces are fully "out", we use `import` statements, etc.  (Outside of Karma test-config files, which are still .cjs and for automated-testing only.)

I believe we can consider this goal met now!
