### ISSUE TITLE
bug(android): Language name 'English' has been changed into 'en' in Installed Languages menu after reinstalling sil_euro_latin Keyboard

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#7326]
**Describe the bug**
I noticed that after reinstalling sil_euro_latin keyboard in Keyman app the language name 'English' has been changed into 'en' under Installed Languages menu. 

**To Reproduce**
1. Install Keyman 16.0.66-alpha build. 
2. Open Keyman app.
4. Click Settings / Installed Languages. 
5. Verify that the language name 'English' appears on the pane. 
6. Click the plus sign which appears at the bottom right corner of the view. 
7. Enter 'Khmer Angkor' in the language search bar. 
8. Verify that the Khmer Angkor Keyboard available on the list. 
9. Install Khmer Angkor keyboard. 
10. Verify that the Khmer Angkor keyboard appears in the text pane. 
11. Long press the globe key. 
12. Long press on the  [new]English name in the language picker menu.
13. Click Delete. 
14. Verify that the English Keyboard has been removed from the Language picker menu. 
15. Close the Keyman app. 
16. Launch the Keyman app once again. 
17. Install sil_euro_latin keyboard. 
18. Long press the globe key. 
19. Verify that the [new]English name appears in the language picker menu. 
20. Open Installed Languages menu. 

Here, I noticed that the language name 'English' has been changed to 'en'. 

**Expected behavior**
'English' name should appear under Installed Languages menu after reinstalling the sil_euro_latin keyboard. 

**Screenshots**

   <img width="500" src="https://user-images.githubusercontent.com/19683143/191027082-685143b8-793c-484c-9203-721df24c3c4b.PNG">

---

**Keyman for Android:**
   Device:             API 26 emulator
 - OS:                 Android 8.0
 - Keyman version:     16.0.66-alpha build
 - Target Application: Keyman App

---

**Keyboard**
 - Keyboard name:    EuroLatin (SIL)
 - Keyboard version: 2.0
 - Language name:    English

**Additional context**
I found this issue when I was testing #7325 PR.

**Comment by darcywong00** [comment]
I suspect this regression was introduced in #7239
