### ISSUE TITLE
CODE_BEEP is not supported in stores on KMW

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#733]
When compiling a keyboard that includes `beep` in stores, the compiler raises an error for KeymanWeb targets. However, if you compile with `store(&version) '10.0'` then it compiles, wrongly.

**Comment by jahorton** [comment]
Example keyboard for testing use:  The CamQWERTY keyboard, at least the version we used in our recent workshop presentation.  It's likely in our legacy keyboards repo.
