### ISSUE TITLE
bug(windows): [on behalf of user]  Something causes the left Alt key to be ‘stuck’

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#7337]
**Describe the bug**

> Quite frequently, when I switch between keyboards, something causes the left Alt key to be stuck down. This is at the software level: if I open the on-screen keyboard the left Alt key is purple instead of dark gray. Can anyone suggest what might be causing this? I’ve tried to pay attention to what key I might be hitting by mistake, but I can’t notice a pattern.
>
> This is Windows 11. I’ve disabled every setting I can find to do with sticky keys.
>
> My keyboard-switching shortcuts are Ctrl-Shift-1, Ctrl-Shift-2, etc.

**Expected behavior**

**Screenshots**

**Related issues**

---

**Keyman for Windows/macOS/Linux/iPhone/iPad/Android:**
   Device:             
 - OS:                  Windows 11
 - Keyman version:      15.0.268
 - Target Application:  Excel?

---

**Keyboard**
 - Keyboard name:     user's IPA keyboard?
 - Keyboard version:  ?
 - Language name:     IPA

**Additional context**

PR #7449 - Makes an improvement to by removing one possible cause for the ALT modifier becoming "stuck."
The issue still persists and therefore this issue cannot yet be closed.

**Comment by MakaraSok** [comment]
originally posted at https://community.software.sil.org/t/something-causes-the-left-alt-key-to-be-stuck/6609/8

**Comment by mcdurdin** [comment]
See also https://community.software.sil.org/t/shift-key-sticks-while-using-keyboard-in-paratext-9/6715

Related to #4884, #5190?

**Comment by nilphite** [comment]
I’ve been having exactly the same issue for several weeks, even after updating to the latest version of Keyman. It affects all my Keyman keyboards. Tapping the alt key toggles it off for one character, and then it locks on again. It happens inconsistently; sometimes I can use the keyboards fine for extended periods and then it’ll just lock alt unpredictably. I’m running Windows 11 Developer Preview.

**Comment by rc-swag** [comment]
PR https://github.com/keymanapp/keyman/pull/7449 - Makes an improvement to by removing one possible cause for the ALT modifier becoming "stuck."
The issue still persists and therefore this issue cannot yet be closed.

**Comment by rc-swag** [comment]
Another user finding the same issue.
https://community.software.sil.org/t/typing-a-character-using-keyman-seems-to-activate-a-modifier-key/6819

**Comment by mcdurdin** [comment]
> The issue still persists and therefore this issue cannot yet be closed.

I think we should close this issue, as the one instance where we had an issue with Alt in testing was not reproducible. There may still be an edge case situation from our code, but the significant fixes made by the PR are I think sufficient.

If 'stuck' modifiers occur again, we should start diagnostic from the beginning and try and find a repro.
