### ISSUE TITLE
[Mac] How should we handle chirality with Alt and Control on Mac?

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#734]
Chirality on Mac may need to be handled differently to on Windows - because typically most keyboards treat right and left Option (alt) as the same key, and most Macs do not have a right Control key.

We need to explore how we can make this as transparent as possible to keyboard developers.

**Comment by jahorton** [comment]
This also affects iOS devices, as KMW deals with very similar issues in 'native' mode.

**Comment by SabineSIL** [comment]
see #875

**Comment by mcdurdin** [comment]
This is now scheduled for completion in 17.0. See [discussion document](https://docs.google.com/document/d/1NCRD6BJ_HXtn4rFpoPEpcs1QJOt9nTboZHiC4-uugvs/edit#heading=h.8eiwkiiemmba) for details; tl;dr: keyboards that use only <kbd>RAlt</kbd> or non-chiral <kbd>Alt</kbd> will match on either <kbd>Option</kbd> key.

**Comment by mcdurdin** [comment]
Tracking this in #875.
