### ISSUE TITLE
bug(model): The expected word doesn't show in the banner

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#7362]
**Describe the bug**

With Bunong ឞូន៝ង (SIL) keyboard, type `ន` `ទ` ` ្រ` ` ា​` (នទ្រា) on Android or iOS to see the error where the word itself (នទ្រា) doesn't get shown in the banner even though it does exist in the [wordlist](https://github.com/keymanapp/lexical-models/blob/master/release/sil/sil.cmo.bw/source/wordlist.tsv).

| Android | iOS |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/28331388/192476548-255bf455-18d7-4d69-8424-0afe10676ae9.png)  | ![image](https://user-images.githubusercontent.com/28331388/192476954-078f2e32-b635-44f0-854f-79fea7f00b7c.png) |

**Expected behavior**

នទ្រា should be shown as one of the option on the suggestion banner as it's 100% match what's being typed.

---

**Keyman for Windows/macOS/Linux/iPhone/iPad/Android:**
   Device:              iPhone 14 Pro Max | Galaxy S series
 - OS:                  iOS 16.0 | Android 10.0
 - Keyman version:      16.0.70-alpha | 15.0.270-stable
 - Target Application:  Keyman app

---

**Keyboard**
 - Keyboard name:     sil_bunong
 - Keyboard version:  1.4
 - Language name:     Bunong (Central Mnong)

**Comment by darcywong00** [comment]
@jahorton - here's the applicable frequencies from the wordlist

នទ្រាប់	181
នទ្រាង់	169
នទ្រាញ់	116
នទ្រាវ	14
ក្រាសនទ្រាច	4
នទ្រា	4 (Makara expects this whole word to match)
នទ្រាច	4
នទ្រាវអ្យារ់	2

**Comment by jahorton** [comment]
Ah, so since words _starting_ with the current word are more likely than the word itself, it's not being shown as a suggestion?

**Comment by mcdurdin** [comment]
Yeah, looks like the "accept current typed input" suggestion may be needed if it's a 100% match?

**Comment by jahorton** [comment]
> Yeah, looks like the "accept current typed input" suggestion may be needed if it's a 100% match?

I could see this being a perception thing, though.  It's not 'correcting' at that point; just predicting what _could_ be the rest of the word.

I mean, if I type `ab` in English, I'm not going to be upset if predictive text wants to suggest "about", "ability", "Abigail", "abstract", or "absolute" at a higher priority than just "ab" (the abbreviation for "**ab**dominal muscles"), even though there will be a number of people that somewhat regularly talk about their abs.

Not saying the expectation noted in this issue is outright wrong... but I think it's worth noting that there may be nuance to consider before just charging forward with a quick-fix bandaid.

**Comment by jahorton** [comment]
All of that said, I will say that autocorrection (should we ever enable it) in the case of a 100% match should be outright blocked.

**Comment by mcdurdin** [comment]
> Not saying the expectation noted in this issue is outright wrong... but I think it's worth noting that there may be nuance to consider before just charging forward with a quick-fix bandaid.

For sure. I don't think I would classify this as a bug so much as a design choice. We could go ahead and close this on that basis?

**Comment by darcywong00** [comment]
> For sure. I don't think I would classify this as a bug so much as a design choice. We could go ahead and close this on that basis?

I was reviewing the list of open issues regarding suggestions.  So should this one be closed based on design choice?

**Comment by mcdurdin** [comment]
> So should this one be closed based on design choice?

Yes. Closing by-design
