### ISSUE TITLE
bug(android): Version Conflict happens in APKs page after installing Keyman

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#7364]
**Describe the bug**
I noticed that there is a version conflict happens after installing different versions of Keyman. 

**To Reproduce**
1. Install the pre-release version of (here, it is 16.0.61-alpha) Keyman. 
2. Open Keyman In-App.
3. Click the 'More Info' option from the 'Get Started' menu. 
4. We may notice the pre-release version of Keyman (16.0.61-alpha) at the bottom of the page. 
5. Close Keyman. 
6. Install current release version of (15.0.270) without uninstalling the pre-release version. 
7. Verify that Keyman 15.0.270-beta has been installed in the device. 
8. Open Keyman / More Info page. 
9. Here it is showing 'Keyman 16.0.61-alpha' build.
10. Open File Manager / APK files in the Android Mobile device. 
11. Here, I noticed that 'Keyman 15.0.27.apk' Installed message. 

**Expected behavior**
A warning message should appear with a message 'the Keyman has been already installed' on the screen. 

**Screenshots**

..Info page shows pre-release version

   <img width="300" src="https://user-images.githubusercontent.com/19683143/192501484-357d3c86-c4fc-4f22-b7ff-8fd691c033d3.jpg">

..APKs page shows current-release version

   <img width="300" src="https://user-images.githubusercontent.com/19683143/192501519-a54596b3-b6a3-48a8-b440-2a9376ed5875.jpg">

..APKs page showing both versions are installed..

   <img width="300" src="https://user-images.githubusercontent.com/19683143/192502309-15197218-a9ce-4d16-a0be-581899a11c05.jpg">

---

**Keyman for Android:**
   Device:             Android API 26 emulator, Redmi Note 8 Pro 
 - OS:                 Android 8.0, Android 11
 - Keyman version:     15.0.270, 16.0.70
 - Target Application: Keyman App

---

**Keyboard**
 - Keyboard name:    
 - Keyboard version: 
 - Language name:    

**Additional context**
I am seeing different behavior If I install the stable release (15.0.270) over the pre-release version (16.0.70) build. ie., the APKs page shows both the versions are installed in the device. But, I noticed that (16.0.70) version was installed in the device. I have attached the Screenshot (both versions installed) for your reference. Thanks.

**Comment by mcdurdin** [comment]
The alpha, beta, and stable releases are treated as separate products, which is why they can all be installed simultaneously. I think the appropriate solution here is to have a separate icon for the alpha + beta releases of Keyman, and probably change the App title to "Keyman Alpha" or "Keyman Beta".

**Comment by darcywong00** [comment]
Fixed in 16.0 beta by #7674
