### ISSUE TITLE
bug(windows): Facebook sharing link is missing in the Keyman Configuration dialog / Keep in Touch tab

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#7374]
**Describe the bug**
I noticed that in the Keyman Configuration window, the twitter sharing link appear in the Keep in touch whereas the Facebook link is missing on the same tab. 

**To Reproduce**
1. Install Keyman 15.0.270 current release. 
2. Open the Configuration dialog. 
3. Click the 'Keep in touch' tab. 
4. Here, I noticed that there is not sharing link option for Facebook web site. 

**Expected behavior**
Facebook Sharing link should appear before the Facebook label name. 

**Screenshots**

   <img width="500" src="https://user-images.githubusercontent.com/19683143/192801752-71b4af0c-3117-4c24-90b7-9fa857e44300.PNG">

---

**Keyman for Windows:**
   Device:             Windows Desktop
 - OS:                 Windows 10 x64
 - Keyman version:     15.0.270
 - Target Application: Keyman Desktop Application

---

**Additional context**
I am able to reproduce this issue in Keyman 16.0.70-alpha build.

**Comment by mcdurdin** [comment]
I wonder if this may be because Facebook is blocked on your network?

**Comment by bharanidharanj** [comment]
> I wonder if this may be because Facebook is blocked on your network?

@mcdurdin Oh Okay. Let me check with my Network Admin and will retest then post my comment in this. Thanks.

**Comment by bharanidharanj** [comment]
@mcdurdin Ah..Yes! The Facebook sharing link is visible now after removing some Network Security Software from the system. Thanks!

   <img width="500" src="https://user-images.githubusercontent.com/19683143/193022712-21d44ac3-dbf3-4fd3-a93f-b000443a88bd.png">

**Comment by mcdurdin** [comment]
Good to hear, will go ahead and close this.
