### ISSUE TITLE
feat(core): support ldml transforms 🙀

### ISSUE THREAD

**Issue by srl295** [keymanapp/keyman#7375]
- #5015 
- #7042 

This ticket is for 

Depends on:
- kmx spec updates for UnicodeSet contents
- compiler updates for transforms

-----
### TODO area
- [x] Markers #9119 
- [x] variables in lists
- [x] variables in keys
- [x] map variables

**Comment by srl295** [comment]
@mcdurdin I think this is ready to close, with the final wrapup in #9121 (for those edge cases) and https://github.com/keymanapp/keyman/issues/9707 (tertiary reorder) and of course normalization

**Comment by mcdurdin** [comment]
Note: we don't normally close issues until the corresponding PRs are merged.

**Comment by srl295** [comment]
@mcdurdin Was trying to segment them. But I think I could consider #9688 as closing it.
