### ISSUE TITLE
feat(core): kmx updates for ldml transforms 🙀

### ISSUE THREAD

**Issue by srl295** [keymanapp/keyman#7376]
Updates to #7043 for anything pertaining to transforms / UnicodeSets

For #7375
and #7042

**Comment by mcdurdin** [comment]
Changing this to a 'feat' -- the spec is hosted [in-repo](https://github.com/keymanapp/keyman/blob/feature-ldml/core/src/ldml/C7043_ldml.md) and should be maintained there. (spec issues are hosts for a specification while it is in development)

**Comment by mcdurdin** [comment]
Query: is this the same as #7234?

**Comment by srl295** [comment]
> Query: is this the same as #7234?

Good point thanks

**Comment by srl295** [comment]
@mcdurdin  yes, closing
