### ISSUE TITLE
[Windows] Keyman Crashes when I open it first time after windows start

### ISSUE THREAD

**Issue by RS-SMD** [keymanapp/keyman#739]
Whenever I open keyman first time, this problem occurs.....also it closes other application simultaneously on which you are working....

I found many time keyman crashes when we use google gujarati or any google indic input...

I have paste Technical report below.... aslo have attached screenshot of error message from keyman...

![keyman bug](https://user-images.githubusercontent.com/37132146/38872161-3abd378e-4270-11e8-9171-274cfaec4cdc.JPG)

============================================================
Exception EAccessViolation in keyman.exe: Access violation at address 6D394F03 in module 'GoogleInputTools.ime'. Read of address 00000000

=============================================================

Timestamp=2018-04-17 18:29
Exception=EAccessViolation
Address=6D394F03
Message=Access violation at address 6D394F03 in module 'GoogleInputTools.ime'. Read of address 00000000

:[6D394F03]{GoogleInputTools.ime} Unknown function at ImeSetCompositionString + $7B603
:[2C539BBA]{keyman.exe  } Vcl.Controls.TWinControl.DefaultHandler + $E6
:[2C6040BB]{keyman.exe  } Vcl.Forms.TApplication.ProcessMessage + $F3
:[2C6040FE]{keyman.exe  } Vcl.Forms.TApplication.HandleMessage + $A
:[2C604431]{keyman.exe  } Vcl.Forms.TApplication.Run + $C9
:[2C756155]{keyman.exe  } main.Run (Line 109, "main.pas" + 47) + $7
:[2C40A4E3]{keyman.exe  } System.@StartExe + $3F
:[2C7680B4]{keyman.exe  } keyman.keyman (Line 147, "" + 3) + $0

CONTROLS
========
frmKeymanMenu: TfrmKeymanMenu (ControlActive)
frmVisualKeyboard: TfrmVisualKeyboard " Keyman Desktop - Simple_Guj"
  panContent: TPanel
    panCharMap: TPanel
    panEntryHelper: TPanel
    panKeyboard: TPanel
    status: TStatusBar
    panTop: TPaintPanel
      panTitle: TPaintPanel "Keyman Desktop"
      tbLeft: TToolBar
      tbRight: TToolBar
      tbKeyboards: TToolBar
    panKeyboardUsage: TPanel
    panHint: TPanel
      webHint: TKeymanEmbeddedWB
    panFontHelper: TPanel
      frmOSKFontHelper: TfrmOSKFontHelper
        web: TKeymanEmbeddedWB
frmKeyman7Main: TfrmKeyman7Main "frmKeyman7Main"
frmOSKFontHelper: TfrmOSKFontHelper
  web: TKeymanEmbeddedWB

SYSTEM INFO
===========
Major Version: 10
Minor Version: 10
Build Number:  15063
Platform ID:   2
CSDVersion:    
Drive C:\ QuotaFreeSpace: 35310MB
Drive C:\ TotalSpace:     99599MB
Drive C:\ TotalFreeSpace: 35310MB
Drive D:\ QuotaFreeSpace: 37448MB
Drive D:\ TotalSpace:     159999MB
Drive D:\ TotalFreeSpace: 37448MB
Drive E:\ QuotaFreeSpace: 25793MB
Drive E:\ TotalSpace:     216836MB
Drive E:\ TotalFreeSpace: 25793MB
Memory Load: 28
Memory TotalPhysical: 2047MB
Memory FreePhysical:  2047MB
Memory TotalPageFile: 4095MB
Memory FreePageFile:  4095MB
Memory TotalVirtual:  2047MB
Memory FreeVirtual:   1720MB

**Comment by mcdurdin** [comment]
This appears to be a bug in Google Input Tools as the crash stack indicates. This is outside our control.
