### ISSUE TITLE
bug (oem/fv/ios): FV keyboard not visible on iOS 16

### ISSUE THREAD

**Issue by sgschantz** [keymanapp/keyman#7391]
**Describe the bug**
The FirstVoices app works normally on iOS 15, but after updating to iOS 16, the keyboard is completely blank.

**To Reproduce**
1. Install iOS 16
2. Open Pages
3. Open the keyboard
4. Tap the globe key and select FirstVoices 

**Screenshots**

![image](https://user-images.githubusercontent.com/89134789/193499331-790dd9d3-e726-4f5d-94a1-3de7effa2920.png)

**Related issues**

A similar issue [5831](https://github.com/keymanapp/keyman/issues/5831) appeared with the release of iOS 15.
The behavior was not identical, however, as the keyboard was visible initially and went blank after tapping a key.

**Reproduced with**
 - Device:            iPhone 13 mini
 - OS:                iOS 16.0.2
 - FirstVoices version:     15.0.270
 - Target Application: Pages

**Keyboard**
 - appears to happen with all FV keyboards

**Additional context**
rotating, locking and unlocking, killing and restarting the app have no effect

**First reported by Clarissa Forbes:**

>Hi Keyman team, we have a bug reported from a user, which sounds very much like the iOS 15 bug. I can't reproduce since I don't have an iPhone but here it is:

>>Since the recent iPhone update the Tuscarora keyboard doesn’t work via the FirstVoices keyboard on iPhone. Just a gray screen shows with no keyboard when selecting. I deleted the app and redownloaded it and I'm still experiencing the same issue. I'm using an iPhone 12 on iOS version 16.0 (20A362).

**Comment by sgschantz** [comment]
This issue also occurs for Keyman if Allow Full Access is disabled under Settings > General > Keyboard > Keyboards > Keyman.

Support for the Allow Full Access setting is currently not available in FirstVoices, but when it is added and enabled, the keyboard displays as expected.

**Comment by mcdurdin** [comment]
> This issue also occurs for Keyman if 'Allow Full Access' is disabled under Settings > General > Keyboard > Keyboards > Keyman.

@sgschantz, could you add a [KB article to help.keyman.com](https://github.com/keymanapp/help.keyman.com/tree/master/knowledge-base) about this? And perhaps then a link to the KB article as a [forum topic post](https://community.software.sil.org/c/keyman)? I know this will feel like busy work and you may not have made changes to the help.keyman.com site previously, so if you would like any more detail on how to do this, feel free to ping me!

**Comment by sgschantz** [comment]
Added KB article here: https://github.com/keymanapp/help.keyman.com/pull/627
