### ISSUE TITLE
feat(developer): verify normalization of ldml keyboard xml 🙀

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#7394]
Part of #7042.

Per https://github.com/unicode-org/cldr/pull/2413

**Comment by srl295** [comment]
Waiting on LDML spec to sort this out

**Comment by mcdurdin** [comment]
That is, all strings in the XML should match the declared normalization form. Warning -- imports may need to be excluded from this.

The implementation should use the declared normalization form to normalize all outputs.

**Comment by srl295** [comment]
NFC or NFD are allowed for CLDR

**Comment by mcdurdin** [comment]
This is not about normalization in Core -- we need to do that anyway. This is about making sure that a keyboard .xml file is consistent internally.

**Comment by srl295** [comment]
@mcdurdin this may be moot, now that we "consume all" forms basically?

**Comment by srl295** [comment]
#10317 for normalizing at compile time

**Comment by mcdurdin** [comment]
> @mcdurdin this may be moot, now that we "consume all" forms basically?

It may be helpful to have linter reporting, particularly for consistency in larger repos. e.g. we may want all CLDR keyboards to have NFC sources?
