### ISSUE TITLE
bug(linux): mk-build-deps failed for Debian 11.5

### ISSUE THREAD

**Issue by srl295** [keymanapp/keyman#7398]
**Keyman for Linux:**
 - Device:           VM
 - OS:                 Debian 11.5, x64
 - Keyman version: 04bde69ab6464c1e9a1db742a4fd3f6f3b05c6c6 16.0.72 alpha 2022-09-30

-----

```shell
$ sudo mk-build-deps --install linux/debian/control
…
…
Investigating (0) keyman-build-deps:amd64 < 15.0.270-1 @iU mK Nb Ib >
Broken keyman-build-deps:amd64 Depends on python3-sentry-sdk:amd64 < 0.13.2-1 @ii mK > (>= 1.1)
  Removing keyman-build-deps:amd64 because I can't find python3-sentry-sdk:amd64
Broken keyman-build-deps:amd64 Depends on python3-raven:amd64 < none @un H >
  Removing keyman-build-deps:amd64 because I can't find python3-raven:amd64
  Or group remove for keyman-build-deps:amd64
```

**Comment by srl295** [comment]
version is recent `master` — 04bde69ab6464c1e9a1db742a4fd3f6f3b05c6c6 installed from git.

**Comment by ermshiperete** [comment]
Debian 11.5 Bullseye contains a version of `python3-sentry-sdk` that is too old. The workaround is to install a newer package version from the next Debian version, from packages.sil.org, or via pip. I updated the `README.md` with this information in #7434.
