### ISSUE TITLE
bug(linux): km-config did not work on Debian 11.5

### ISSUE THREAD

**Issue by srl295** [keymanapp/keyman#7400]
**Keyman for Linux:**
 - Device:           VM
 - OS:                 Debian 11.5, x64
 - Keyman version: 04bde69ab6464c1e9a1db742a4fd3f6f3b05c6c6 16.0.72 alpha 2022-09-30

-----

km-config failed to start up with

```
Can not find lang_tags_map.py. Did you run "make"?
```

however, the file WAS inside the .egg file.

Fixed by (!!) setting `zip_safe=False` in the `setup.py` so that it installed a .egg dir instead of a .egg file.  Somehow, this worked.

**Comment by mcdurdin** [comment]
Please include Keyman version info and method of installation for future reference :grin:

**Comment by srl295** [comment]
version is recent `master` — 04bde69ab6464c1e9a1db742a4fd3f6f3b05c6c6 installed from git.

**Comment by ermshiperete** [comment]
Updated `README.md` in #7434.

**Comment by srl295** [comment]
@ermshiperete I'm still hitting on Ubuntu 22.04.1 LTS (happens to be WSL)

```shell
$ make reconf && make fullbuild && sudo make install
$ km-config
Can not find lang_tags_map.py. Did you run "make"?
```


and still 'fixable' with

```diff
diff --git a/linux/keyman-config/setup.py b/linux/keyman-config/setup.py
index c090be9fb..ba5b6f957 100644
--- a/linux/keyman-config/setup.py
+++ b/linux/keyman-config/setup.py
@@ -14,6 +14,8 @@ setup(
              'km-package-uninstall',
              'km-package-list-installed'],
 
+    zip_safe=False,  # SRL: don't install a zip
+
     install_requires=[
         'lxml', 'numpy', 'Pillow', 'requests', 'requests-cache',
         'python-magic', 'qrcode', 'sentry-sdk'
```

do you want a new ticket?

**Comment by srl295** [comment]
@ermshiperete looks like this change didn't make it to feature-ldml yet (which is fine), but this patch does still seem necessary for me otherwise.
