### ISSUE TITLE
bug(developer):  0-th elem needs zero offset 🙀 

### ISSUE THREAD

**Issue by srl295** [keymanapp/keyman#7404]
https://github.com/keymanapp/keyman/blob/feature-ldml/core/src/ldml/C7043_ldml.md#c704323-elemtransform-and-reorder-element-strings says about `elem`

> The first entry in the element string list MUST be the null element string, which has zero length and zero offset.

but on inspection, the first (0th) element string list has a zero length, but repeats the offset of the second (1st) entry.

-----
for #7042 
found during #7234

**Comment by mcdurdin** [comment]
See also https://github.com/keymanapp/keyman/pull/7437/files#diff-95985cb44c34779804524113d19f84c84c0df3809790667a95bd3592e3a9e7cbR307
