### ISSUE TITLE
bug(developer): crash when adding icon

### ISSUE THREAD

**Issue by DavidLRowe** [keymanapp/keyman#7419]
**Describe the bug**
I was looking at:
https://github.com/keymanapp/keyboards/pull/2024/commits/3404ebd7957a7dfb14b3c673c45e5a50c55742bc
The author has added an icon file (.ICO) to the source folder, but hasn't referenced it in the .kmn file. I wanted to update the .kmn file to include the reference to the icon file. When I tried to do that, Developer crashed.
NB: The icon file is a 256x256 pixel .ICO file (rather than the 16x16 pixel format normally used).

**To Reproduce**
- double-click on .kpj file to start Developer
- with the Keyboards tab at the bottom active, click the nisenan.kmn link
- with the Details tab at the left selected, click the Add... button, then select Icon and click OK.

**Expected behavior**
I expected that I'd be offered a chance to select the existing file.

---

**Keyman Developer:**
 - OS: Windows 10 Pro, version 21H2
 - Keyman Developer version: 15.0.268

---

**Keyboard**
see information above

**Additional context**
Details for error report for Keyman app:
  Application Identifier: tike-15.0.268
  Error Identifier: C254DA134E64465BF6991E555B75B1E3

**Comment by mcdurdin** [comment]
Turns out that the file was not an .ico file at all -- it was a .png file with the wrong extension. We'll fix Keyman Developer so it doesn't crash if you do this, but it's important to use the right kind of file :grin:
