### ISSUE TITLE
[Developer] Reduce the number of mobile keyboard modifiers in combo by default

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#744]
When designing a touch-based keyboard layout within Keyman Developer, there are now a *large* number of potential modifiers to select from for a key, which results in a quite overwhelming drop-down list when selecting a key's modifier.

Remembering our "DISCUS" principle for keyboard design, perhaps we could consider hiding most of the complex modifier options by default?  For the general case, it's probably best to only show the most common, recommended combinations and have either a special option or a checkbox somewhere to allow selecting the rarer options.

**Comment by mcdurdin** [comment]
By default, include DEFAULT, SHIFT, RALT, RALT+SHIFT, ALT.

Others should be visible only if they are referenced in the .kmn. User can always add via Code tab if they are desperate :)
