### ISSUE TITLE
[iOS] Mobile app feature request:  Keyboard Search

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#745]
With our large catalogue of existing keyboards, it can be quite cumbersome to manually scroll through such a large list to find what a user is looking for.  (It's definitely no help when doing simulation runs on debug testing, either.)

Something that I'm sure users would find handy - could we include an option in our mobile apps' keyboard download screens to pull up our new keyboard search website?  Said site already knows how to pass keyboards to the app, so integration should be possible.

**Comment by erros84** [comment]
+1 Searching in the app from the "Add New Keyboard" screen would assist the user to find their language. Of course, that opens the can of worms of alternate language names that would need to be indexed and included...

**Comment by darcywong00** [comment]
Splitting Android to separate issue

**Comment by jahorton** [comment]
Initially implemented with #3384.  There's still some polish to do, but it's already well-implemented enough to close out this issue.
