### ISSUE TITLE
bug(web): isChirality() seems to always return false

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#7467]
While creating user-test for #7466, I was unclear why `keyman.isChiral()` would return false for the Chirality keyboard (or for balochi_inpage keyboard which contains a rightalt layer)

I then loaded the KeymanWeb testing/chirality/index.html test page
with the "Chirality Test Keyboard" loaded:
In the Chrome console (F12)
```
keyman.isChiral('Keyboard_chirality')
```
and saw that returned false too.

Shouldn't it be true?

### Configuration
Current master branch

**Comment by jahorton** [comment]
I'm going to need a bit more to go on here.  This isn't reproducing for me.

![image](https://user-images.githubusercontent.com/25213402/197927769-e7257448-d231-4c3f-8406-0e05b949c16b.png)

**Comment by darcywong00** [comment]
I was passing in the keyboard name

![ischiral](https://user-images.githubusercontent.com/7358010/197929702-cdacafb3-1700-42f7-8283-36ef296c5a6f.png)
