### ISSUE TITLE
Bookmarklet crash due to language code issue

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#747]
During a recent live demo of KMW Bookmarklets, we had a Thai keyboard crash.  It is believed that the likely cause is due either to a not-updated BCP-47 code or due to a two-letter code, as pre-10.0 versions of KMW required three-letter codes.

**Comment by darcywong00** [comment]
> KeymanWeb: Invalid call to r.keymanweb.com - invalid language id

**Comment by darcywong00** [comment]
This will be tracked in sillsdev/keyman-keyman.com#204
