### ISSUE TITLE
bug(mac): Keyman triggered itself before manually done so

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#7485]
**Describe the bug**

> * **TEST_DENY_ACCESS:** - User is prompted again when they deny access, restart the machine and run Keyman.
> 
> 1. Remove old version of Keyman **after** first removing its permissions from Security & Privacy > Privacy > Accessibility
> 2. Install the Keyman build for this PR
> 3. Restart the system
> 4. Select Keyman from the System Input Source menu
> 5. Confirm that dialog No. 1 is displayed.
> 6. Click the OK button and confirm that the System Preferences window is displayed with dialog No. 2 in the background
> 7. **Do not** enable accessibility access for Keyman 
> 8. Restart the system.
> 9. Select Keyman from the System Input Source menu
> 10. Confirm that dialog No. 1 is displayed again.
> 11. Click the OK button and confirm that the System Preferences window is now displayed with Keyman unchecked for Accessibility (Dialog No. 2 may or may not be displayed in the background.)

In step 8. quoted from instructions in the second test of https://github.com/keymanapp/keyman/pull/7354 above, after restarting the system, Keyman triggers itself and the privacy alter text gets shown without users' action. With this said, step 9. is kind of unnecessary.

**To Reproduce**

Follow the steps above and try to observe the behavior after restarting at step 8.

**Expected behavior**

Keyman shouldn't trigger itself after denying and restarting the system with Keyman active prior to the restart.

**Screenshots**

N/A

**Related issues**

N/A

---

**Keyman for Windows/macOS/Linux/iPhone/iPad/Android:**
   Device:              MBP
 - OS:                  Big Sur 11.0.1 | Mojave 10.14
 - Keyman version:      16.0.70
 - Target Application:  ?

**Comment by sgschantz** [comment]
@mcdurdin I don't believe we want to do anything different in this case. If someone restarts when Keyman is active (although Privacy settings have not been enabled properly), then it makes sense after restart that the user would be notified to make the Privacy changes. We don't want them to start using Keyman without it functioning properly. I suggest we close this.

**Comment by mcdurdin** [comment]
I agree -- if the user switches to Keyman, and at any point Keyman does not have the necessary permissions to function correctly, Keyman needs to make the user aware of this. Permissions get changed, by users, by OS upgrades, etc. The more self-healing that Keyman can be, the better!
