### ISSUE TITLE
bug(core): Compiling core on Linux outputs a warning

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/keyman#7487]
Compiling core outputs the following warning when building on Linux:

```
core/include/keyman/keyboardprocessor.h:130:1: warning: ‘visibility’ attribute ignored [-Wattributes]
  130 | typedef KMN_API uint8_t (*km_kbp_keyboard_imx_platform)(km_kbp_state*, uint32_t, void*);
      | ^~~~~~~
```

**Comment by mcdurdin** [comment]
I thought `KMN_API` was giving us calling convention as well as import/export/static, but I was wrong. So we should be able to simply delete `KMN_API` from this and it should be fine.
