### ISSUE TITLE
bug(ios): KM for iPad not Using "tablet" Layout

### ISSUE THREAD

**Issue by dyacob** [keymanapp/keyman#7517]
### Describe the bug

There seems to be an issue with Keyman 15 on an iPad whereby it does not use the "tablet" layout, but instead uses the "phone" layout.  I've observed this issue with another keyboard as well, both were fine in KM 13.

The tablet layouts otherwise tests fine in the web browser based testing that is launched from KM Developer.

### Reproduce the bug

1. Install a keyboard that defines _both_ a "phone" and "tablet" touch layout (GFF Amharic 2.3 is one) on an iPad.
2. Note the difference between the layers of the two profiles.
3. When selecting the keyboard on the iPad, the "phone" layout will be used.

### Expected behavior

The "tablet" layer will be used.

### Keyman apps

- [ ] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

15.0.270

### Operating system

iPadOS 15.7 (19H12)

### Device

iPad Mini (5th Generation)

### Target application

Keyman editor app, but any app.

### Browser

N/A

### Keyboard name

gff_amharic

### Keyboard version

2.3

### Language name

Amharic

### Additional context

I've observed the issue in other GFF keyboards.  I last tested on an iPad with KM 13. I haven't tested on other tablets (not available to me).

**Comment by dyacob** [comment]
If it helps as a visual reference, here are the phone and tablet layouts for GFF Amharic 2.3 , taken from the web-based tester:

**Phone:**

![GFF-Amharic-Phone](https://user-images.githubusercontent.com/8098333/197616082-7ecf21b6-168e-4a50-a3e5-e741b47a632b.png)


**Tablet:**

![GFF-Amharic-Tablet](https://user-images.githubusercontent.com/8098333/197616105-691f4d9d-cba7-4638-ab35-5b8467e47f10.png)

**Comment by mcdurdin** [comment]
Relates to:
* #970
* #91

**Comment by mcdurdin** [comment]
This appears to be a manifestation of two bugs:

* kmwembedded.ts: `keymanweb.setDefaultDeviceOptions` tests for `iPad` but then immediately overwrites it, becaus `device.app` received from ios-host.js is `"AppleMobile"`:

https://github.com/keymanapp/keyman/blob/fd5a0c1f0af148d028f3d500d15ca589975bfb13/web/source/kmwembedded.ts#L140-L142

* ios-host.js: by default, device is always set to `'AppleMobile'`, which is supposed to be overridden by `setDeviceType()`, which is supposed to be called by `KeymanWebViewController.swift::setDeviceType()`, but which does not seem to happen, and which would cause a double-`init()` anyway, which is just plain wrong.

https://github.com/keymanapp/keyman/blob/fd5a0c1f0af148d028f3d500d15ca589975bfb13/ios/engine/KMEI/KeymanEngine/resources/Keyman.bundle/Contents/Resources/ios-host.js#L23

https://github.com/keymanapp/keyman/blob/fd5a0c1f0af148d028f3d500d15ca589975bfb13/ios/engine/KMEI/KeymanEngine/resources/Keyman.bundle/Contents/Resources/ios-host.js#L95-L99

https://github.com/keymanapp/keyman/blob/fd5a0c1f0af148d028f3d500d15ca589975bfb13/ios/engine/KMEI/KeymanEngine/Classes/Keyboard/KeymanWebViewController.swift#L257-L269

---

I _think_ the best way to clean this up would be to remove the `setDeviceType()` code path altogether, test for the `iPad` userAgent substring in ios-host.js when initializing `device`, moving that test out of `kmwembedded.ts::setDefaultDeviceOptions()`.

@jahorton, @sgschantz what do you think?

One wrinkle: I am not sure which version of WKWebView started reporting `iPad` in its UA string. I have been testing with iOS 14.4, but will also check soon with iOS 12.4 (installing the older simulator now).

**Comment by mcdurdin** [comment]
Still waiting for the iOS 12.4 Simulator download to finish. Why does development for Apple platforms feel like going back in time 15 years?

**Comment by mcdurdin** [comment]
After Simulator crashed and I restarted it I was able to access the new 12.4 simulator.

On iOS 12.4 on iPad mini 2, the UA string is:

`Mozilla/5.0 (iPad; CPU OS 12_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148`

So my proposed solution should wrok.

**Comment by jahorton** [comment]
Keep in mind that `setDefaultDeviceOptions` is called _during_ KMW init.  The `device` object does exist before that, so it's not like we have to defer until this point to set things straight, but it's worth noting that we'd want to prevent the function's call from overwriting whatever is set there if we do decide to set `tablet` in place before the `init`.

https://github.com/keymanapp/keyman/blob/1bdb2d4364a9f571d0c12a8be41f858eafba5745/web/source/dom/domManager.ts#L1478

My initial thoughts:  just change out line 140 and 141 in kmwembedded.ts.

https://github.com/keymanapp/keyman/blob/fd5a0c1f0af148d028f3d500d15ca589975bfb13/web/source/kmwembedded.ts#L140-L142

If line 141 is squashing line 140, just let (current) 140 be the victor by evaluating it later.

Also, while I'm looking at KMW's `init` function... it doesn't reference that `app` parameter in any way, shape, or form so far as I can see.  It's nice metadata to have for Sentry reports, I suppose, but that's the only discernable use of it that I see.  It's as if someone had good intentions of reworking this via the `setDeviceType()` codepath but never finished.

**Comment by mcdurdin** [comment]
I just wanted to move the `navigator` test out of kmwembedded.ts and into ios-host.js, which it seems like is a better place for it. After all, we really don't want to see that being tested on Android.

**Comment by mcdurdin** [comment]
> My initial thoughts: just change out line 140 and 141 in kmwembedded.ts.

That was my initial thought too. But then I wanted to cleanup the `setDeviceType()` mess and not let it linger, given it has no useful purpose.
