### ISSUE TITLE
feat(developer): ldml: include all LDML data in kmx+ 🙀

### ISSUE THREAD

**Issue by srl295** [keymanapp/keyman#7532]
- KMX+ should include all data in the source
- Principle here: data representation, not prematurely optimizing for keyman build process, other than synthesized vkeys.

Scope:
- layouts
- may include another copy of the keybag also (and displays) due to gestures
- synthesized vkey ids need to match kvks

#7042 🙀

**Comment by srl295** [comment]
should be closed with #7630

**Comment by mcdurdin** [comment]
Closing with #7630
