### ISSUE TITLE
bug (linux): keyboard icon doesn't display in system tray

### ISSUE THREAD

**Issue by rik-shaw** [keymanapp/keyman#7547]
### Describe the bug

In Linux, distros using Gnome (such as Ubuntu) as their desktop environments integrate ibus into their internal keyboard layout solution, so in their panel ("system tray") they do not support using the ibus keyboard icons, instead they show a 2 character text-based short name for the language (or "en1" and "en2" if there are different keyboard layouts for english, for example).

However, other desktop environments that do not refactor ibus but instead use the ibus tray icon directly do show the keyboard icons in the panel ("system tray"). This is much preferred. Unfortunately, Keyman keyboards only show the generic Keyman icon instead of the keyboard icon. This means that the user is not sure from a visual glance what keyboard is active. Screenshots below are using Cinnamon (default DE for Wasta-Linux, for example), but the same behavior exists in other DEs such as XFCE, Mate, etc. Note that ibus-kmfl keyboards do correctly show the keyboard icon in the ibus tray icon.

---
Default ibus icon: ![default ibus tray icon](https://user-images.githubusercontent.com/2560632/198064227-8f160888-8e80-4614-9bc1-727e2a29d580.png)

---

Keyman generic keyboard ibus tray icon: ![keyman ibus icon](https://user-images.githubusercontent.com/2560632/198064276-9e09d4b2-2de6-4d0a-b35d-0529c0f5b53a.png)

---

ibus-kmfl keyboard ibus tray icon: ![ibus-kmfl ibus icon](https://user-images.githubusercontent.com/2560632/198064304-621c3f32-da1a-4021-8a93-7907ef233e4e.png)

---

### Related issues

#1182 seems like it may be related, but this was supposedly fixed some years ago? It is about icon format, there may be something to this.

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [X] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

15.0.271-1+focal1

### Operating system

Ubuntu / Wasta-Linux - Cinnamon DE

### Device

Linux laptop

### Keyboard name

All

**Comment by mcdurdin** [comment]
Thank you for this report. I have initially tagged this to be resolved in 17.0, but bear with us as we will be working through a re-triage of open issues shortly. @ermshiperete will also review this when he returns from vacation.
