### ISSUE TITLE
feat (linux): Add ability to install system-wide keyboards 

### ISSUE THREAD

**Issue by rik-shaw** [keymanapp/keyman#7549]
### Is your feature request related to a problem? Please describe.

Installing Keyman keyboards at the system level (rather than only the user level) would allow Keyman keyboards to be pre-installed in Linux ISOs such as Wasta-Linux. As it currently stands, each user needs to individually download and install Keyman keyboards after installation.

### Describe the solution you'd like

ibus-kmfl keyboards can be installed at the system level of `/usr/share/kfml` and thus bundled as part of an ISO such as Wasta-Linux. Users still need to manually add the keyboard to their user-level, but being installed at the system level ensures that the keyboard is findable in ibus preferences - keyboard selection lists. Additionally, by distributing ibus user preferences (via dconf / gsettings keys), individual user-level inclusion of system-level keyboards can be automated as part of a debian package (wasta-custom-eth, for example, for all Ethiopia Wasta-Linux users), or in general scripting can be done to automate adding / configuring ibus-kmfl keyboards.

Having Keyman support system-level installation would remove a limitation of Keyman that has several Linux supporters still preferring outdated ibus-kmfl keyboards over Keyman keyboards.

### Describe alternatives you've considered

Maybe if Keyman keyboard addition could be bash scripted it would be an acceptable workaround as then all user home directories could be looped through adding the keyboards for each user (the keyboards would need added to the user level `~/.cache/keyman` and added to the `~/.cache/keyman/keyman_cache.sqlite`??)

UPDATE: I did not know of `km-package-install`, `km-package-get`, and `km-package-list-installed`. Of particular note, I see that `km-package-install` can use a `--shared` flag, this may work I will need to test and report back.

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [X] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

15.0.271-1+focal1

### Operating system

Ubuntu / Wasta-Linux - Cinnamon DE

### Device

Linux laptop

**Comment by mcdurdin** [comment]
I think that `km-package-install` may solve this; please let me know how you go on that?

Otherwise, I've tentatively listed this for implementation in 17.0.

**Comment by rik-shaw** [comment]
@mcdurdin yes, `km-package-install` seems to work well, sorry I didn't realize it was there earlier. I will close this issue.
