### ISSUE TITLE
bug: English UI name appears twice in the UI language 'Display in' list box

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#7559]
### Describe the bug

In the Keyman Configuration dialog, I noticed that the English UI name appears twice in the 'Display' drop down list box.

### Reproduce the bug

1. Install Keyman 16.0.89-alpha build. (from keyman status site)
2. Open Keyman Configuration Dialog. 
3. Click English UI name  against the 'Display in' label name. 
4. Here, I noticed that the 'English' UI name appears twice in the drop down list box. 

   <img width="500" src="https://user-images.githubusercontent.com/19683143/198247747-618a0a24-135d-4896-9158-5cade9a3ae0e.png">

### Expected behavior

English UI name should not repeat in the 'Display in' UI drop down list box. 

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [X] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16.0.89-alpha

### Operating system

Windows 10 OS (Native machine)

**Comment by mcdurdin** [comment]
Closing as resolved in #7498 (263b04dce49cda0f05b20b6fdbfe7839e4d2d2f).
