### ISSUE TITLE
bug(mac): Keyman system menu icon has square white background

### ISSUE THREAD

**Issue by sgschantz** [keymanapp/keyman#7609]
The Keyman icon in the system menu has a square white background that causes it to clash with all other sytem menu icons:

<img width="202" alt="Keyman-icon-before" src="https://user-images.githubusercontent.com/89134789/199633790-080fd5e6-b9ca-4181-a783-1c1122b8e284.png">

**Comment by darcywong00** [comment]
Fixed in 16.0 beta by #7610
