### ISSUE TITLE
test(iOS): Regression Test for Keyman 16 - Beta

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#7618]
# Keyman for iPhone and iPad Acceptance Test Procedures #

1. These test procedures are to be run before moving from alpha to beta, or beta to stable, or before PRs are merged into stable branches.
2. Copy these tests into a new issue (for tier transitions) or a comment on the PR.
3. When annotating results, use `>` at the start of a new line under the checkbox to note the result. (For an example, see #3973).

---

# User Testing
## Gather Assets for Testing ##
- [ ] Record device's iOS version
- [ ] Ensure the device is properly configured for testing and is registered with TestFlight.

At this time, Keyman for iOS does not support external keyboard input.

## Setup Steps ##
1.  Uninstall previous version of Keyman on the device (on a simulator, "Erase All Content and Settings..." under Device menu)
2. Install test build IPA (on a simulator, "iOS Simulator Image")
3. Disable internet connectivity of the device
4. Start Keyman and select **Add a keyboard for your language**
5. Verify error message "Could not reach Keyman server!" or "The Internet connection appears to be offline." is displayed
6. Click OK to dismiss.  Close Keyman app
7. On device, enable internet connectivity
8. Start Keyman
9. On initial **Get Started** menu, select "Enable Keyman as system-wide keyboard" and do any necessary system steps to enable Keyman

---

## SUITE_INSPECT: Visual Inspection of master branch
- TEST_BUILD_STATUS: ![Build Status](https://build.palaso.org/app/rest/builds/buildType:(id:Keyman_iOS_Master)/statusIcon) Verify latest CI build of [master](https://build.palaso.org/viewType.html?buildTypeId=Keyman_iOS_Master) is successful
- TEST_VERIFY_HISTORY: Verify [`HISTORY.md`](https://github.com/keymanapp/keyman/tree/beta/HISTORY.md) contains all the current changes
- TEST_VERIFY_UNIT_TESTS: Verify that all unit tests for iOS are currently passing.
    - May be integrated with the first step above once our usual CI processes include the iOS unit tests.

---

## SUITE_MENU_FUNCTIONALITY: Menu Functionality Tests, in-app##
- GROUP_IPHONE_PORTRAIT: portrait mode in iPhone
- GROUP_IPHONE_LANDSCAPE: landscape mode in iPhone
- GROUP_IPAD_PORTRAIT: portrait mode in iPad
- GROUP_IPAD_LANDSCAPE: landscape mode in iPad

### Test Cases
- **TEST_GET_STARTED**: Get Started
  - Verify touching **Add a keyboard for your language** pulls up the **keyboard search**
      - This should also be accessible as **Settings** > **Installed Languages** > **`+`**.
  - Verify touching **Enable Keyman as system-wide keyboard** pulls up Keyman's menu within iOS settings.  (11.0+ devices)
      - If older versions of iOS are supported, ensure that the help page for doing it manually is properly linked.
  - Verify touching **More info** brings up an accurate version and the main table-of-contents help page.
      - This should also be accessible as **Info** from the main menu dropdown (on phones) or as the circled-i button (on tablets).
  - Set **Don't show again** to checked, close and re-open Keyman, and verify **Get Started** menu does not appear

- **TEST_ADD_NEW_KEYBOARD**: Add New Keyboard
This menu is accessed via **Get Started** menu or **Settings** menu
  - On the device, enable internet connectivity
  - Verify a new keyboard can be downloaded and selected, say "US Basic"
  - Return to the text input screen and confirm that it operates correctly.
  - Without changing selected language, confirm that it can be cleanly deleted via the Settings menu.
  - Confirm that another keyboard is correctly selected afterward.

- **TEST_ADD_NEW_KEYBOARD_FROM_FILE**:
  - On the device, go to keyman.com on Safari
  - Search for "US Basic"
  - scroll down to keyboard details and tap to download the keyboard package (i.e. `.kmp` file)
  - open Files app and navigate to Download folder to find "basic_kbdus.kmp" and tap on it to start the installation processes
  - Keyman app should be pulled up
  - follow the screen to finish the keyboard installation
  - verity that the keyboard is correctly installed and working as expected

- **TEST_SWITCH_KEYBOARD**
  - press on the globe key
  - the keyboard menu should be shown
  - press on a keyboard to switch to, say "EuroLatin (SIL)"
  - confirm that "EuroLatin (SIL)" is now selected and ready to be used
  - swich back to "US Basic" and confirm it does as expected

- **TEST_SHARE**: Share
  - Type and verify text can be copied and shared to external app

- **TEST_KEYMAN_BROWSER**: Keyman Browser ###
  - On default page, click on text field and set system keyboard to Keyman
  - Verify can type with Keyman as system keyboard
  - Verify that predictive suggestions are properly applied when selected (using `sil_euro_latin` + English)
  - Close and reopen Keyman app

- **TEST_TEXT_SIZE**: Text Size
  - Verify text can be rescaled from Text Size 9 to 72

- **TEST_CLEAR_TEXT**: Clear Text
  - Verify text can be cleared

- **TEST_INFO**: Info
  - Verify that the Keyman iOS version is displayed; record the version
  - Verify that the Info menu options matches that of the **More Info...** option from the **Get Started** menu option.
  - Verify that the Keyman iOS version matches the version string seen at (Home Screen) > [iOS] Settings > Keyman.

- **TEST_SETTINGS**: Settings
  - Installed Languages ... Add Language
  - Select an installed language ... Add (another) Keyboard
    - Should automatically perform a filtered search based upon that language's BCP-47 code, i.e. for "English" it should be seen as shown in the screenshot below.
    <img width="150" src="https://user-images.githubusercontent.com/28331388/163088289-b467eabb-01a6-468e-81f9-2cfad38584bd.png">

  - Select an installed language ... Dictionary
    - Turn on/off 'Enable Predictions' and validate each
    - Turn on/off 'Enable Corrections' and validate each
  - Validate that when both predictions and corrections are off, banner is not visible
  - Add/Remove dictionaries - validate
  - If multiple dictionaries are available, test swapping between them

- **TEST_EUROLATIN**: `English (Eurolatin)` in-app
  - In portrait orientation, verify that the OSK appears and fills the width the bottom of the screen
  - Verify long-press `q` key works
  - Verify long-press `k` key works
      - Verify that any predictive suggestions generated feel 'reasonable' (based upon 'k', the selected subkey, or one of its neighbors)
  - Verify uppercase layer can be selected via `SHIFT`
  - Verify number layer can be selected via `123`
  - Verify long-press `1` key works
  - Verify long-press `0` key works
  - Verify backspace, space, and enter keys work

Note that EuroLatin2, a highly customized keyboard explicitly designed for mobile, is not found; hence EuroLatin (SIL) is used for testing this instead.

- **TEST_US_BASIC**: English: `US Basic` in-app
  - Verify that the **US Basic** keyboard can be downloaded through Settings > Installed Languages > English > `+`
    - This should automatically bring up search results for **English** keyboards.
    - When the package-installer launches, English should be the one pre-selected language.
  - Install the package for both English and Tagalog by selecting both of them in the installation processes.
  - Set **English: US Basic** as the active in-app keyboard.
  - Verify that predictive text suggestions appear.
  - Set **Tagalog: US Basic** as the active in-app keyboard.
  - Verify that predictive text suggestions do _not_ appear.
  - Verify that long-press `123` key works, presenting options for a currency layer and a symbol layer.
  - Select the currency layer, then press the `£` key.
  - Verify that the keyboard outputs correctly and returns to the default layer.
  - Go to the symbol layer and press the `©` key.
  - Verify that the keyboard outputs correctly and remains on the symbol layer.
  - Revert to the default layer and ensure basic key inputs work.
  - Long-press `e` on the default layer and select a subkey.
  - Verify that the selected key produces the correct output.
  - From the `Settings > Languages > English > US Basic` menu, follow the "Help link" and ensure it displays appropriate help.
    - (Should work both online and offline)
  - From the `Settings > Languages > English > US Basic` menu, scan the QR code with a phone and test that it links to the current version of that keyboard's public download page on keyman.com.
  - Returning to the app, uninstall the **US Basic** keyboard via Settings for Tagalog.
  - Set **English: US Basic** as the active in-app keyboard.
  - Verify that the keyboard appears correctly and ensure basic key inputs work.
    - This is to ensure that uninstalling for one language doesn't adversely affect installations of the same resource for another language.
  - Uninstall the **US Basic** keyboard via Settings for English.

---

## SUITE_SYSTEM_KEYBOARD:
- GROUP_IPHONE_PORTRAIT: portrait mode in iPhone
- GROUP_IPHONE_LANDSCAPE: landscape mode in iPhone
- GROUP_IPAD_PORTRAIT: portrait mode in iPad
- GROUP_IPAD_LANDSCAPE: landscape mode in iPad

Test the following after setting Keyman as a system keyboard.

Test Cases
- **TEST_BASIC_USAGE**: ensure that the keyboards functions as expected on all layers. Please test on multiple keyboards, i.e. EuroLatin (SIL), Cameroon QWERTY keyboard and Khmer Angkor.
- **TEST_LONG_PRESS**: ensure that longpress on all applicable layers are working as intended
- **TEST_GLOBE_KEY**: ensure that a short press on the globe key switch to the next keyboard and a longpress on it open the keyboard menu where you can select a keyboard of your choice

## SUITE_SWITCH_LOCALE
- GROUP_IPHONE_PORTRAIT: portrait mode in iPhone
- GROUP_IPHONE_LANDSCAPE: landscape mode in iPhone
- GROUP_IPAD_PORTRAIT: portrait mode in iPad
- GROUP_IPAD_LANDSCAPE: landscape mode in iPad

### Test Cases
- **TEST_KM_LOCALE** 
  - from System Preferences, switch the UI language to Khmer by adding it in `Language & Region` using `+`
  - drag Khmer to the top of the list to set it as a primary UI language
  - check the dropdown menu to see it in Khmer (there is a known issue on this though, cf. https://github.com/keymanapp/keyman/issues/6527)
  - verify the UI language switch to Khmer
- **TEST_AM_LOCALE**
  - from System Preferences, switch the UI language to Amharic by adding it in `Language & Region` using `+`
  - drag Amharic to the top of the list to set it as a primary UI language
  - check the dropdown menu to see it in Amharic (there is a known issue on this though, cf. https://github.com/keymanapp/keyman/issues/6527)
  - verify the UI language switch to Amharic

---

## [TODO] SUITE_PREDICTIVE_TEXT: Predictive Text

**Comment by bharanidharanj** [comment]
## SUITE_INSPECT: Visual Inspection of master branch

* **TEST_BUILD_STATUS (PASSED):** Verified the latest master branch beta build is successful.
 
   <img width="500" src="https://user-images.githubusercontent.com/19683143/202458888-b47a6cfd-e396-43ff-83d5-c4c21151542f.PNG">

* **TEST_VERIFY_HISTORY (FAILED):** History File need to be updated for iOS. 

   <img width="500" src="https://user-images.githubusercontent.com/19683143/202459082-9d572c19-9989-4227-9e3e-0c4536f52ca0.PNG">

**Comment by mcdurdin** [comment]
> * TEST_VERIFY_HISTORY: Verify [`HISTORY.md`](HISTORY.md) contains all the current changes

This test spec is incorrect -- the link should be to https://github.com/keymanapp/keyman/tree/beta/HISTORY.md

@keymanapp-test-bot retest TEST_VERIFY_HISTORY

**Comment by bharanidharanj** [comment]
* **TEST_VERIFY_HISTORY (PASSED):** Retested this with the updated link and it is opening the correct page. 

   <img width="500" src="https://user-images.githubusercontent.com/19683143/202662491-b773e9d5-1227-41a4-bd1c-637a4a06f9c8.png">

**Comment by bharanidharanj** [comment]
## SUITE_MENU_FUNCTIONALITY: Menu Functionality Tests, in-app##

### GROUP_IPHONE_PORTRAIT: portrait mode in iPhone

* **TEST_GET_STARTED (PASSED):** Tested with Keyman 16.0.106-beta build in iPhone 12 Pro Max Simulator and the Get Started functionality is working as expected. 
* **TEST_ADD_NEW_KEYBOARD (PASSED):** Verified that we are able to install a new keyboard as per the instruction. 
* **TEST_ADD_NEW_KEYBOARD_FROM_FILE (PASSED):** Verified that we able to install a new keyboard from file. (Download folder. )
* **TEST_SWITCH_KEYBOARD (PASSED):** Able to switch between keyboards using the Keyboard picker menu. 
* **TEST_SHARE (PASSED):** Able to share the text with some other applications like Message App.

**Comment by bharanidharanj** [comment]
## SUITE_MENU_FUNCTIONALITY: Menu Functionality Tests, in-app##

### GROUP_IPHONE_PORTRAIT: portrait mode in iPhone

* **TEST_GET_STARTED (PASSED):** Tested with Keyman 16.0.107-beta build in iPhone 12 Pro Max Simulator and the Get Started functionality is working as expected.
* **TEST_ADD_NEW_KEYBOARD (PASSED):** notes
* **TEST_ADD_NEW_KEYBOARD_FROM_FILE (PASSED):** notes
* **TEST_SWITCH_KEYBOARD (PASSED):** notes
* **TEST_SHARE (PASSED):** notes
* **TEST_KEYMAN_BROWSER (PASSED):** notes
* **TEST_TEXT_SIZE (PASSED):** notes
* **TEST_CLEAR_TEXT (PASSED):** notes
* **TEST_INFO (PASSED):** notes
* **TEST_SETTINGS (PASSED):** notes
* **TEST_EUROLATIN (PASSED):** notes
* **TEST_US_BASIC (PASSED):** notes

**Comment by bharanidharanj** [comment]
### GROUP_IPHONE_LANDSCAPE: landscape mode in iPhone

* **TEST_GET_STARTED (PASSED):** Tested with Keyman 16.0.107-beta build in iPhone 12 Pro Max Simulator and the Get Started functionality is working as expected.
* **TEST_ADD_NEW_KEYBOARD (PASSED):** Verified that we are able to install a new keyboard as per the instruction.
* **TEST_ADD_NEW_KEYBOARD_FROM_FILE (PASSED):** Verified that we able to install a new keyboard from file.
* **TEST_SWITCH_KEYBOARD (PASSED):** Able to switch between keyboards using the Keyboard picker menu.
* **TEST_SHARE (PASSED):** Able to share the text with some other applications like Message App.
* **TEST_KEYMAN_BROWSER (PASSED):** Verified that the predictive suggestions are properly applied when selected English - EuroLatin SIL keyboard.
* **TEST_TEXT_SIZE (PASSED):** Verified that I am able to rescale the text size from 9 to 72.
* **TEST_CLEAR_TEXT (PASSED):** Able to clear using Clear Text option.
* **TEST_INFO (PASSED):** Verfied the Keyman Info option from Get Started menu and in the Home Screen.
* **TEST_SETTINGS (PASSED):** Verified the Keyman Settings functionality and it is working as expected.
* **TEST_EUROLATIN (PASSED):** Verified the EuroLatin Keyman and it showing the expected results.
* **TEST_US_BASIC (PASSED):** Verified the English: US Basic as well as the Tagalog: US Basic and both are working as expected.

**Comment by bharanidharanj** [comment]
## SUITE_MENU_FUNCTIONALITY: Menu Functionality Tests, in-app##

### GROUP_IPAD_PORTRAIT: portrait mode in iPad

* **TEST_GET_STARTED (PASSED):** Tested with Keyman 16.0.107-beta build in  iOS 15.0 / iPad Air Simulator and the Get Started functionality is working as expected.
* **TEST_ADD_NEW_KEYBOARD (PASSED):** Verified that we are able to install a new keyboard as per the instruction.
* **TEST_ADD_NEW_KEYBOARD_FROM_FILE (PASSED):** Verified that we able to install a new keyboard from file.
* **TEST_SWITCH_KEYBOARD (PASSED):** Able to switch between keyboards using the Keyboard picker menu.
* **TEST_SHARE (PASSED):** Able to share the text with some other applications like Message App.
* **TEST_KEYMAN_BROWSER (PASSED):** Verified that the predictive suggestions are properly applied when selected English - EuroLatin SIL keyboard.
* **TEST_TEXT_SIZE (PASSED):** Verified that I am able to rescale the text size from 9 to 72.
* **TEST_CLEAR_TEXT (PASSED):** Able to clear using Clear Text option.
* **TEST_INFO (PASSED):** Verified the Keyman Info option from Get Started menu and in the Home Screen.
* **TEST_SETTINGS (PASSED):** Verified the Keyman Settings functionality and it is working as expected.
* **TEST_EUROLATIN (PASSED):** Verified the EuroLatin Keyman and it showing the expected results.
* **TEST_US_BASIC (PASSED):** Verified the English: US Basic as well as the Tagalog: US Basic and both are working as expected.

**Comment by bharanidharanj** [comment]
## SUITE_MENU_FUNCTIONALITY: Menu Functionality Tests, in-app##

### GROUP_IPAD_LANDSCAPE: landscape mode in iPad

* **TEST_GET_STARTED (PASSED):** Tested with Keyman 16.0.107-beta build in iOS 15.0 / iPad Air Simulator and the Get Started functionality is working as expected.
* **TEST_ADD_NEW_KEYBOARD (PASSED):** Verified that we are able to install a new keyboard as per the instruction.
* **TEST_ADD_NEW_KEYBOARD_FROM_FILE (PASSED):** Verified that we able to install a new keyboard from file.
* **TEST_SWITCH_KEYBOARD (PASSED):** Able to switch between keyboards using the Keyboard picker menu.
* **TEST_SHARE (PASSED):** Able to share the text with some other applications like Message App.
* **TEST_KEYMAN_BROWSER (PASSED):** Verified that the predictive suggestions are properly applied when selected English - EuroLatin SIL keyboard.
* **TEST_TEXT_SIZE (PASSED):** Verified that I am able to rescale the text size from 9 to 72.
* **TEST_CLEAR_TEXT (PASSED):** Able to clear using Clear Text option.
* **TEST_INFO (PASSED):** Verified the Keyman Info option from Get Started menu and in the Home Screen.
* **TEST_SETTINGS (PASSED):** Verified the Keyman Settings functionality and it is working as expected.
* **TEST_EUROLATIN (PASSED):** Verified the EuroLatin Keyman and it showing the expected results.
* **TEST_US_BASIC (PASSED):** Verified the English: US Basic as well as the Tagalog: US Basic and both are working as expected.

**Comment by bharanidharanj** [comment]
## SUITE_SYSTEM_KEYBOARD: 

### GROUP_IPHONE_PORTRAIT: portrait mode in iPhone

* **TEST_BASIC_USAGE (PASSED):** Tested this as per the instructions with some of  the keyman keyboards (eg., khmer_angkor, cameroon_qwerty, tamilzha 99 etc.,) and I was able to use it in all layers of the keyboard. 
* **TEST_LONG_PRESS (PASSED):** Verified that long press on all applicable layers are working as expected. 
* **TEST_GLOBE_KEY (FAILED):** Long Pressing a Globe key is not working in iPhone 12 Pro Simulator / iOS 15.0. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/203316226-5d310e9a-7530-4ba9-8e2b-3d7cc9f52f69.png">


### GROUP_IPHONE_LANDSCAPE: landscape mode in iPhone

* **TEST_BASIC_USAGE (PASSED):** Tested this as per the instructions with some of  the keyman keyboards (eg., khmer_angkor, cameroon_qwerty, tamilzha 99 etc.,) and I was able to use it in all layers of the keyboard.
* **TEST_LONG_PRESS (PASSED):** Verified that long press on all applicable layers are working as expected. 
* **TEST_GLOBE_KEY (FAILED):** Long Pressing a Globe key is not working in iPhone 12 Pro Simulator / iOS 15.0. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/203317071-23bdf9fb-f8d3-43f5-b7e7-9a5873a0913a.png">

**Comment by bharanidharanj** [comment]
## SUITE_SWITCH_LOCALE: 

### GROUP_IPHONE_PORTRAIT: portrait mode in iPhone

* **TEST_KM_LOCALE (PASSED):** Verified that the UI language has been changed to Khmer in Keyman App. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/203320240-50f1b8ba-af52-4781-8e6f-0c90b1cde456.png">

* **TEST_AM_LOCALE (PASSED):** Verified that the UI language has been changed to Amharic in Keyman App. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/203320284-e5ce4fbc-a776-414c-b9cb-e53ceaa0ccee.png">

### GROUP_IPHONE_LANDSCAPE: landscape mode in iPhone

* **TEST_KM_LOCALE (PASSED):** Verified that the UI language has been changed to Khmer in Keyman App. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/203320357-b839394b-b5e0-420f-a59b-50cc5837ac5d.png">

* **TEST_AM_LOCALE (PASSED):** Verified that the UI language has been changed to Amharic in Keyman App.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/203320399-9b8525ba-a9de-4773-b858-29d040e6e03a.png">

**Comment by mcdurdin** [comment]
@sgschantz this is a release-blocking issue, I think:

> 🟥 TEST_GLOBE_KEY (https://github.com/keymanapp/keyman/issues/7618#issuecomment-1323624997): Long Pressing a Globe key is not working in iPhone 12 Pro Simulator / iOS 15.0. (https://github.com/keymanapp/keyman/issues/7618#issuecomment-1323624997)

**Comment by jahorton** [comment]
> @sgschantz this is a release-blocking issue, I think:
> 
> > 🟥 TEST_GLOBE_KEY ([#7618 (comment)](https://github.com/keymanapp/keyman/issues/7618#issuecomment-1323624997)): Long Pressing a Globe key is not working in iPhone 12 Pro Simulator / iOS 15.0. ([#7618 (comment)](https://github.com/keymanapp/keyman/issues/7618#issuecomment-1323624997))

I'm not seeing this on my iPhone SE, which is still on iOS 15.5.  Identical behavior for both `stable` and `beta` (16.0.109) versions - the longpress menu displays as usual in the system keyboard.

**Comment by sgschantz** [comment]
The globe key works for me on real devices and on the simulator with beta and older versions. Based on the screenshot, I'm thinking that @bharanidharanj tested this in-app instead of with the system keyboard?

Here's what I saw in the simulator with the beta:

![image](https://user-images.githubusercontent.com/89134789/203484093-4a8e5493-d8c8-42f5-89b6-6058a730880e.png)

**Comment by jahorton** [comment]
> The globe key works for me on real devices and on the simulator with beta and older versions. Based on the screenshot, I'm thinking that @bharanidharanj tested this in-app instead of with the system keyboard?

Right, the test did say "system keyboard", but those _are_ clearly in-app screenshots.  Longpresses don't do anything in-app until released, and even then, it just matches standard tap behavior.

Should probably ask for those two to be retested then.

**Comment by sgschantz** [comment]
@keymanapp-test-bot retest [SUITE_SYSTEM_KEYBOARD] [GROUP_IPHONE_PORTRAIT] [TEST_GLOBE_KEY]

**Comment by sgschantz** [comment]
@keymanapp-test-bot retest [SUITE_SYSTEM_KEYBOARD] [GROUP_IPHONE_LANDSCAPE] [TEST_GLOBE_KEY]

**Comment by bharanidharanj** [comment]
> The globe key works for me on real devices and on the simulator with beta and older versions. Based on the screenshot, I'm thinking that @bharanidharanj tested this in-app instead of with the system keyboard?
> 
> Here's what I saw in the simulator with the beta:
> 
> ![image](https://user-images.githubusercontent.com/89134789/203484093-4a8e5493-d8c8-42f5-89b6-6058a730880e.png)

Oops! Sorry! I will retest it and will post my result. :-)

**Comment by bharanidharanj** [comment]
## SUITE_SYSTEM_KEYBOARD: 

### GROUP_IPHONE_PORTRAIT: portrait mode in iPhone

* **TEST_GLOBE_KEY (PASSED):** Retested this as per Shawn's suggestion and now I am able to see the Keyboard picker menu while long pressing the key in a browser. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/203491033-c8e27832-2a2d-4e32-84e1-a08d1d912845.png">



### GROUP_IPHONE_LANDSCAPE: landscape mode in iPhone

* **TEST_GLOBE_KEY (PASSED):** Retested this as per Shawn's suggestion and now I am able to see the Keyboard picker menu while long pressing the key in a browser. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/203491060-5096d109-076a-47d5-b27e-01d1a40f2a96.png">

**Comment by bharanidharanj** [comment]
## SUITE_SYSTEM_KEYBOARD: 

### GROUP_IPAD_PORTRAIT: portrait mode in iPad

* **TEST_BASIC_USAGE (PASSED):** Tested with Keyman 16.108-beta build in iPad Air (4th generation) / iOS 15.0 Simulator and I was able to use all the layers of the keyboards (khmer_angkor, sil_eurolatin and cameroon qwerty) without having any issues. 
* **TEST_LONG_PRESS (PASSED):** Verified that long press on all applicable layers are working as expected. 
* **TEST_GLOBE_KEY (PASSED):** After changing Keyman as the System wide keyboard, I was able to see the Keyboard picker menu while long pressing the key in a browser.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/203514750-95ab0987-7426-4c6c-a47d-6876e42e94e6.png">


### GROUP_IPAD_LANDSCAPE: landscape mode in iPad

* **TEST_BASIC_USAGE (PASSED):** Verified in all layers of the keyboards (khmer_angkor, sil_eurolatin and cameroon qwerty) without having any issues. 
* **TEST_LONG_PRESS (PASSED):** Verified that long press on all applicable layers are working as expected.
* **TEST_GLOBE_KEY (PASSED):** After changing Keyman as the System wide keyboard, I was able to see the Keyboard picker menu while long pressing the key in a browser.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/203514791-4bd18425-545d-4d6b-9d8c-1e867a613fec.png">

**Comment by bharanidharanj** [comment]
## SUITE_SWITCH_LOCALE: 

### GROUP_IPAD_PORTRAIT: portrait mode in iPad

* **TEST_KM_LOCALE (PASSED):** Verified that the UI language has been changed to Khmer in Keyman App.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/203516363-9b251fd9-a548-4665-a50b-1f867c613df1.png">

* **TEST_AM_LOCALE (PASSED):** Verified that the UI language has been changed to Amharic in Keyman App.

### GROUP_IPAD_LANDSCAPE: landscape mode in iPad

* **TEST_KM_LOCALE (PASSED):** Verified that the UI language has been changed to Khmer in Keyman App.
* **TEST_AM_LOCALE (PASSED):** Verified that the UI language has been changed to Amharic in Keyman App.
   <img width="300" src="https://user-images.githubusercontent.com/19683143/203516420-ba92ec23-dd06-4a79-909c-376559357329.png">

**Comment by bharanidharanj** [comment]
## SUITE_INSPECT: Visual Inspection of master branch

* **TEST_VERIFY_UNIT_TESTS (PASSED):** Tested with Keyman 16.0.108-beta build in all the areas in iPhone and iPad Simulators and all the tests are passed. Thanks.
