### ISSUE TITLE
bug(developer): Key position indicator (in blue colour) highlights in different key after switching from numeric layer to default layer

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#7621]
### Describe the bug

Key position indicator stays in different key after switching from numeric layer to default layer. 

### Reproduce the bug

1. Install Keyman Developer 16.0.96-beta build.
2. Open a Keyboard project. 
3. In touch layout editor, select a key (eg., z), add a subkey , add a subkey text (eg., Z). 
4. Verify that the added text appears on the subkey. 
5. Switch the layer from default to shift layer. 
6. Verify the Key Position indicator (in blue colour) on the selected key. (eg., z)
7. Switch back to default layer. 
8. Verify the Key Position highlighted on the same key. (z)
9. Switch the layer from default to numeric layer. 
10. Here, the Key Position indicator was changed to the number key (eg., 1)
11. Switch back to default layer. 
12. Here, I noticed that the Key Position indicator still highlighted in the same key. And, it did not return to the subkey. (Z)

..from shift layer to default layer

   <img width="500" src="https://user-images.githubusercontent.com/19683143/199978135-1d08a34e-4495-48b7-adb1-c9aba9ab8f01.PNG">

..from numeric layer to default layer

   <img width="500" src="https://user-images.githubusercontent.com/19683143/199978175-651147a9-69f0-408b-b46a-3fad892abb88.PNG">

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [X] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16.0.96-beta

### Operating system

Windows 10 OS

### Device

Desktop

### Target application

Touch Layout in Keyman Devloper

### Keyboard name

Custom Keyboard (Tamil)

### Language name

Tamil

**Comment by mcdurdin** [comment]
This is by design -- the editor tries to stay on the key with the same identifier when you switch layers. When you switch to the numeric layer, there is no <kbd>z</kbd> key, so it moves to the first key on the layer (the <kbd>1</kbd> key). Switching back to the default layer, there is no <kbd>1</kbd> key, so it moves to the first key on that layer (the <kbd>q</kbd> key)
