### ISSUE TITLE
bug(web): `languageMenu.touch*` should be passive

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#7637]
### Describe the bug

The `touch*` events on the language menu call `preventDefault()` but this is probably not necessary, as AFAICT there is no default behaviour that we need to be blocking (the elements are `<div>`s and `<p>`s).

When scrolling is happening, we get a error:

```
languageMenu.ts:448 [Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.
  c @ languageMenu.ts:448
  sentryWrapped @ helpers.ts:87
```

When constructing the menu, we get a cascade of (often thousands of) warnings:

```
trycatch.ts:185 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
  (anonymous) @ trycatch.ts:185
  (anonymous) @ instrument.ts:421
  e.addKeyboard @ languageMenu.ts:489
  k @ languageMenu.ts:365
  e.addLanguages @ languageMenu.ts:315
  e.show @ languageMenu.ts:115
  b.showLanguageMenu @ oskView.ts:989
  e.optionKey @ visualKeyboard.ts:1675
  e.handleClick @ preProcessor.ts:62
  e.raiseKeyEvent @ preProcessor.ts:44
  e.modelKeyClick @ visualKeyboard.ts:980
  (anonymous) @ visualKeyboard.ts:620
  sentryWrapped @ helpers.ts:87
```

More information: https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [X] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16.0.97-beta

### Additional context

I was testing in Chrome with mobile emulation

**Comment by jahorton** [comment]
It's hard to say exactly what the original reason for those `preventDefault()` calls is - these are lines dating back to KMW 2.0, if not before:  https://github.com/keymanapp/keyman/blob/75864966f480c2773980faefe3d35021165d6d53/web/source/kmwosk.js

Starting at:  https://github.com/keymanapp/keyman/blob/75864966f480c2773980faefe3d35021165d6d53/web/source/kmwosk.js#L1368

**Comment by jahorton** [comment]
This comment is probably the best clue we've got:

```
//TODO: Still drags Android background sometimes (not consistently)
```

I did notice the page itself being dragged, rather than the menu, on occasion.  That's _probably_ what's being referenced here... which doesn't sound related to the `preventDefault` calls, but maybe I just need to investigate the full-page drag a bit more.

**Comment by jahorton** [comment]
On _that_ point:  `touchstart` on a language in the list, followed by moving the touchpoint onto the 'index' (the "language bar"?) and _then_ dragging vertically will cause the full page to scroll.

**Comment by jahorton** [comment]
I've noticed that if I disable the `overflow: auto` styling on the `#kmw-menu-scroll-container` (the `m2` element in `LanguageMenu`'s source), the scrolling misbehavior becomes _extremely_ reproducible.
