### ISSUE TITLE
bug(windows): `kmshell -ikl KeyboardID BCP47Tag` is not enabling the keyboard

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#7670]
### Describe the bug

Ref: https://community.software.sil.org/t/how-do-i-deploy-keyman-15-with-custom-keyboards-for-all-users/6845

It seems that the `-ikl` parameter is installing the keyboard for the language for the current user, but not enabling it. This doesn't really make sense.

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [x] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

15.0.272

### Operating system

Windows 10

**Comment by rc-swag** [comment]
Fixed in PR #7856
