### ISSUE TITLE
[Mac] The OSK should hide automatically when Keyman is no longer the active IM.

### ISSUE THREAD

**Issue by tombogle** [keymanapp/keyman#770]

**Comment by mcdurdin** [comment]
Can we detect the switch back to a system keyboard and update the OSK to show the system keycaps?

**Comment by tombogle** [comment]
IDK. Assuming we can, is that really better than just hiding it? As stated the option seems to suggest that it will only remain visible for Keyman keyboards, and I'd be surprised if any users would expect or want it to remain visible when the system keyboard is active. It's more of a necessary evil when you're not that familiar with the keyboard, but it seems you'd want it out of the way otherwise.

**Comment by mcdurdin** [comment]
I was surprised by the number of users who wanted the OSK visible for system keyboards with Keyman Desktop on Windows. Mac users may be a different kettle of mangoes but I think we'll be fine for now until someone complains ;-)
