### ISSUE TITLE
bug(windows): 'ALT' Key 'stuck' after changing keyboards with serialized input enabled

### ISSUE THREAD

**Issue by rc-swag** [keymanapp/keyman#7716]
### Describe the bug

When switching between using the `IPA SIL keyboard` and the `Dadyia keyboard` with `paratext` and `MS Excel` the `ALT` key can become "stuck" always on. 

  

### Reproduce the bug

TODO: I have to look up the key sequence for the Dadyia keyboard

- Have MS Excel open with Keyman running. 
- Select the IPA SIL keyboard type in some letters
- Open Paratext and select the `Dadyia Odd Vowels` keyboard
- Type in TODO add key sequence
- Switch to IPA SIL type 
- Switch back to `Dadyia` and observe that trying to type any in any key causes the application menus to open
- Open the keyman OSK and observe the 'ALT' key is purple  = depressed 

### Expected behavior

The "ALT" key should not stay on "depressed"

### Related issues

Previous issue reported #7337

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [X] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

15.0.270

### Operating system

Windows 10

### Target application

Paratext, MS Office

### Keyboard name

IPA SIL, Dadyia odd vowels

**Comment by mcdurdin** [comment]
I am guessing this is fixed by #7449

**Comment by rc-swag** [comment]
> I am guessing this is fixed by #7449

I am still waiting for confirmation as stated above the previous issue was #7337 which is what the PR #7449 you refer to was addressing. I have asked the current user experiencing the problem to try `16_beta` and repeat the steps to see if it is resolved.

**Comment by MakaraSok** [comment]
Bug reported and diag report sent at https://community.software.sil.org/t/diagnostic-report-from-coleen-starwalt-silx/6920/2.
