### ISSUE TITLE
bug(android/app): More "Install Updates" shenanigans

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#7739]
@bharanidharanj noted the following while attempting to reproduce #6731

On Android 5.0 and 9.0 phone emulators:
1. First install the old version 6.0.4 of sil_cameroon_qwerty for "Akum" language.
2. Go through the other steps from #6731 to trigger the "Install Updates" icon
3. After clicking the cloud icon to update sil_cameroon_qwerty, he saw the keyboard list now had
sil_cameroon_qwerty for Akum (keyboard version 6.0.4)
sil_cameroon_qwerty for Afade (keyboard version 6.0.8)

The keyboard update just installs the first listed language by default (no language picker option during the install)
I verified on the Device File Explorer that only one package sil_cameroon_qwerty exists.

So the issues are:
* Existing keyboard versions aren't getting updated
* The "Install Updates" icon doesn't go away after installing updates. (It does disappear if you cancel the download dialog)

**Comment by mcdurdin** [comment]
* Also, importantly, updating a keyboard should not change the list of installed languages (it should not be adding the first language from the package).

**Comment by darcywong00** [comment]
This issue is fixed by #7740. Will try to tackle #7801 next.
