### ISSUE TITLE
docs(ios): allow full access must remain enabled with ios 16

### ISSUE THREAD

**Issue by sgschantz** [keymanapp/keyman#7763]
The [help page](https://help.keyman.com/products/iphone-and-ipad/current-version/start/installing-system-keyboard) for installing Keyman on ios describes enabling the Allow Full Access setting. It also mentions that it can be disabled after installing a keyboard:

> **On "Allow Full Access"**
> After opening the Keyman system keyboard for the first time in an app, you can turn off the "Allow Full Access" option again.
> You may need to temporarily switch this on again in the future for app updates and for some changes to keyboard preferences.
> It may always be safely deactivated immediately after opening the system keyboard again in an app.
> 

Unfortunately, due to the iOS 16 bug, described in keymanapp/keyman#7391, Allow Full Access must be enbaled for Keyman to function at all. The documentation should be updated in some way to reflect this.

**Comment by sgschantz** [comment]
Thanks!

**Comment by darcywong00** [comment]
Fixed in 16.0 beta by #7791

@sgschantz - can you reply to
https://community.software.sil.org/t/keyboard-fails-to-load-load-correctly-on-iphone-xr-11/6958 ?
