### ISSUE TITLE
feat(linux): Icon for each keyboard

### ISSUE THREAD

**Issue by zenfas** [keymanapp/keyman#7770]
### Is your feature request related to a problem? Please describe.

When I use ibus/fcitx5 in linux, all keyboards from keyman is the same icon, not good for user! Compare to m17n, each keyboard has their own icon

### Describe the solution you'd like

1 keyboard 1 icon

### Describe alternatives you've considered

m17n

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [X] Keyman for Linux
- [X] Keyman for macOS
- [X] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

15.0.269-1

### Operating system

Kubuntu 22.10

### Device

Laptop

### Keyboard name

vietnamese_telex, vietnamese_vni

### Keyboard version

1.05

**Comment by mcdurdin** [comment]
@ermshiperete was this fixed in #7678? (note fcitx not ibus?)

**Comment by ermshiperete** [comment]
> @ermshiperete was this fixed in #7678?

yes, for ibus it's fixed in #7678.

**Comment by zenfas** [comment]
I see fix for ibus only

**Comment by wengxt** [comment]
@zenfas that can be only fixed in fcitx5-keyman downstream
