### ISSUE TITLE
bug(linux): ibus-keyman not buildable with any ibus stable release.

### ISSUE THREAD

**Issue by wengxt** [keymanapp/keyman#7774]
### Describe the bug

ibus-keyman integrate ibus pr to early and make it impossible to be built without patching ibus. This is not a good practice and will be troublesome for distro packager to do the upgrade. (not to mention it's still unknown whether the PR to ibus itself will be accepted or not).

Whether it contains the required change should at least be checked at build time instead of blindly apply it.

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [X] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16.0.107

**Comment by ermshiperete** [comment]
@wengxt It was the intention to make it compilable without the patched ibus version available. Somewhere in the process a change slipped in that made this goal fail. Thanks for noticing!

**Comment by ermshiperete** [comment]
Fixed by #7792
