### ISSUE TITLE
[windows] Locale editor at https://secure.tavultesoft.com/keyman/support/locale/ needs version 10 strings

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#780]

**Comment by MayuraVerma** [comment]
@mcdurdin Please add this locale strings to the site.

**Comment by MayuraVerma** [comment]
Thanks.

**Comment by mcdurdin** [comment]
https://secure.tavultesoft.com/keyman/support/locale/index.php?Version=10.0.1100.0&OnlineProductID=30 now has all strings for version 10.

**Comment by MayuraVerma** [comment]
Please add these new versions in the drop down menu in the below link
https://secure.tavultesoft.com/keyman/support/locale/

We are able to reach to version 10, only with the link you provide.

**Comment by MayuraVerma** [comment]
Also, there are many strings that are not relevant to version 10

SKActivation_OnlineNow
Do you want to activate $(SKShortApplicationTitle) online now with licence number %0:s? If you click No, you can choose from alternate activation methods.

SKActivation_Success
Your licence has been successfully activated.

**Comment by mcdurdin** [comment]
The link given is the one you should use for now. We need to audit the string usage for locale work but that's not going to happen in the next couple of weeks. An overhaul of the i18n of the whole set of Keyman apps is tentatively pencilled in for 11.0, and that would include a stack of work on these issues. For now, we'll have to make do with what we have in the editor -- don't bother translating the strings that you know are irrelevant.
