### ISSUE TITLE
bug(developer): Edits to KMDev Touch Visual Editor don't get saved/compiled until touch code has been opened and edited once.

### ISSUE THREAD

**Issue by MattGyverLee** [keymanapp/keyman#7810]
### Describe the bug

Recently, I copied a test KMDev project to a dozen computers using 16.0.107. Once we opened the correct KMN file, we tried edit the touch layout via the visual editor. We would edit a field, save, compile, and open the browser. The touch changes were NOT showing up. As they fiddled with the project, one here and there started working and updating. We all upgraded to 16.0.110, and the same problem continued on the machines that had the problem. There were no console errors in the browser. 

Eventually, I clicked over to the touch code, and realized that the touch code had not been updated. When I returned to the touch editor, it had reverted. I went back and made the change in the code, saved, compiled and tested, and it worked. After this, I could make any [valid] change in the visual or code editor, and it would update. I did this on the remaining half-dozen machines to unlock them.

To rule out oddities specific to my project, it happened with others. My colleague opened a different keyboard he had created on his machine last year, made changes to the touch, saved, and compiled. The changes were not reflected in the browser. Clicking on the touch code showed that the changes were not retained. We made a minor change in the code, saved, returned to the visual editor, compiled, and all was well from then on.

### Reproduce the bug

Steps to reproduce:
1. Install KM Dev 16.0.107 or 16.0.110.
2. Open a project that hasn't been opened in Keyman 16 (or restore the attached one).
3. Try to make a change to the touch layout in the editor, save, compile, and test. No compile errors.
	-It will not have been updated.
4. Open the touch code and notice that it doesn't contain the change you just made. (It does seem to get reformatted on load.)
5. Make any valid change in the code, return to the visual touch editor. 
6. Compile and test to see that the problem is resolved.
7. Make more changes in the vidual editor and compile and it will work.

### Expected behavior

Expectation:
I expect that changes in either the code or the visual editor will be maintained. 

### Keyman apps

- [X] Keyman Developer
- [X] KeymanWeb

### Keyman version

KMDev 16.0.107-16.0.110

### Operating system

Windows 10 21H1 through Windows 11 22H2

### Device

Windows Laptops

### Target application

Chrome and Edge

### Browser

Chrome and Edge

### Keyboard name

French Model

### Keyboard version

0

### Additional context

Because the touch code resets and "jumps" when opened, I suspect that there is some formatting normalisation happening on opening the code that finally makes it readable/editable by the visual touch editor (but that this reformatting doesn't happen just by using the touch editor. Maybe it's the comversion between quoted and unquoted numbers.

**Comment by MattGyverLee** [comment]
Here's our simplified project for testing.
[french_model.zip](https://github.com/keymanapp/keyman/files/10084757/french_model.zip)

**Comment by mcdurdin** [comment]
Thank you for reporting this. We definitely need to get this fixed in 16.0 before we go to release!

**Comment by MattGyverLee** [comment]
I'm quite curious whether you will be able to reproduce this. The workaround worked on all of the machines, so I don't have a non-working machine to test. Also, I will not have easy access to the users' machines that weren't working after tomorrow.

**Comment by mcdurdin** [comment]
I managed to track the issue down -- it looks like a problem with spaces in filenames. See #7820 for the whole amusing story.

**Comment by MattGyverLee** [comment]
"Here’s the code, maybe it could interest you and the future readers of that article."

Those are prophetic words in that article. 

Reading your report, it makes sense why I never encountered the issue on my machine. My github folder path has no spaces specifically to avoid this type of issue. (I had compiler issues with spaces in the past, maybe around the time you wrote that article.)

I'm still a bit confused why my workaround of switching to code worked. If the touch interface always uses that code to save, how did accessing the code editor once seem to fix the touch editor for the future? This is why I assumed opening the code editor was force-prettifying the code.

**Comment by mcdurdin** [comment]
> I'm still a bit confused why my workaround of switching to code worked. If the touch interface always uses that code to save, how did accessing the code editor once seem to fix the touch editor for the future? This is why I assumed opening the code editor was force-prettifying the code.

Yeah, I am not sure without digging a bit deeper. There are some things about how the two editors share the source that may be a contributing factor.

**Comment by MattGyverLee** [comment]
Ok, when the path fix merges and builds and I could test on my side with the sample project to verify whether it is fully resolved.

**Comment by MattGyverLee** [comment]
I still can't explain how my workaround fixed it before, but I can't get it to fail now in 16.0.118. Good work!
