### ISSUE TITLE
feat(windows): Allow Font Helper to search local fonts for arbitrary strings, not just for characters on a Keyman keyboard

### ISSUE THREAD

**Issue by JapanYoshi** [keymanapp/keyman#7826]
### Is your feature request related to a problem? Please describe.

I'm a Japanese speaker with a lot of Japanese fonts installed, but my image editing programs won't filter by whether or not the fonts support Japanese.

### Describe the solution you'd like

It would be very useful if something like Keyman's Font Helper worked for arbitrary strings, so that I could search local fonts that support the given string, and preview how the string looks. It could be inside Keyman's text editor.

### Describe alternatives you've considered

I'm not sure if external font managers support this feature, or if it shows you all fonts with a fallback font. Nonetheless, I don't know of any programs that will tell you how many percent of all the characters each font supports.

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [X] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

15.0.270

### Operating system

Windows 10

### Device

Windows laptop

**Comment by mcdurdin** [comment]
I wonder if the Character Identifier tool we published a good few years ago will meet your needs? It's still fairly simplistic in terms of whether fonts 'work' or not, but at least provides the ability to type a string of characters to match.

https://blog.keyman.com/2011/07/character-identifier-tool/

**Comment by JapanYoshi** [comment]
It mostly worked for my purpose, but some fonts failed to load in the preview.
