### ISSUE TITLE
feat(windows): options for desktop shortcut during installation

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#7862]
### Is your feature request related to a problem? Please describe.

[oBU] this was posted on the community site:

> I don’t need or want a Keyman shortcut on my desktop. The Keyman icon in systray provides all the functionality I need. Every time I install or upgrade Keyman on my computer, I get another shortcut on my desktop that I wind up deleting.
I probably can’t convince you to completely remove the desktop shortcut, but can you at least make it optional during the installation process? This is an option during installation of many other software packages that I install/upgrade regularly.

### Describe the solution you'd like

An option for users to choose whether or not to have Keyman shortcut created on their desktop after installation

### Related issues

[Link](https://community.software.sil.org/t/make-the-desktop-shortcut-optional-during-installs-and-updates/6985) to this post on the community site

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [X] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

any

### Operating system

any Windows OS

### Device

any

### Target application

n/a

### Keyboard name

n/a

### Keyboard version

n/a

### Language name

n/a

**Comment by rc-swag** [comment]
- [ ]  make change to installation to not install the desktop shortcut #11401 
- [ ] Update any documentation that refers to the Keyman "Desktop Shortcut" to refer to the "Start Menu"
