### ISSUE TITLE
bug(web): pressing layer switch key with selected text would delete the selection

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#7866]
### Describe the bug

From https://community.software.sil.org/t/ios-and-android-undesirable-behaviour-with-selected-text/6986:

> I must say my phone doesn’t respond well to trying to select words, but when it does recognise that’s what I’m trying to do Keyman doesn’t remove the space like on iOS [refer to #7865], but switches to the capitalised layer automatically which is not what I usually want, and then when I tap shift to change layer it deletes the selected text as if I pressed the delete key. Since I was likely to remove it anyway this is more disconcertingly unexpected behaviour than a catastrophe, but I would prefer it if pressing the layer change buttons didn’t remove selected text and also the non-shift layer is more likely to be the one I want. A clever algorithm would maybe try to guess what I want by looking at context before the selection if possible, but I don’t really expect that. The behaviour is quite different on iOS and Android, anyway.
> 
> I would like to find out whether this is very common, whether I can fix my keyboards to cope with it and whether this is something developers are aware of and whether any attention can be given to it.

### Related issues

#7865

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyboard name

NaijaType and sil_euro_latin

**Comment by darcywong00** [comment]
Selected text getting deleted on layer change also happens on sil_cameroon_qwerty for Akum language.

**Comment by darcywong00** [comment]
In `KMManager.insertText()`, it looks like KMEA is told to insert empty String s where the selection used to be (between `textView.getSelectionStart()` and `textView.getSelectionEnd()`...

**Comment by jahorton** [comment]
> and then when I tap shift to change layer it deletes the selected text as if I pressed the delete key.

To me, this is the most important tidbit and lead.  We have a non-output key triggering an output operation - that shouldn't be happening.

> In `KMManager.insertText()`, it looks like KMEA is told to insert empty String s where the selection used to be (between `textView.getSelectionStart()` and `textView.getSelectionEnd()`...

This, on the other hand, is exactly what I'd expect an output key to do.

**Comment by darcywong00** [comment]
> We have a non-output key triggering an output operation - that shouldn't be happening.

OK, does this mean I should look in keyboard-processor?

**Comment by jahorton** [comment]
> > We have a non-output key triggering an output operation - that shouldn't be happening.
> 
> OK, does this mean I should look in keyboard-processor?

There and in `input-processor` - `keyboard-processor` returns `RuleBehavior` objects, while `input-processor` generally is what applies them (thus, is the final trigger for the output operation).

If you can set up a live test and place a breakpoint within `keyboard-processor/src/text/ruleBehavior.ts`'s `finalize()` method right before you press `shift` in the example given, please note and report here what the printed form of `this.transcription` looks like.  If the `transform` property looks like an empty transform that shouldn't change anything, I'd say `input-processor` is more likely where we need the fix.  As I think more on it, I'm thinking this is pretty likely.

**Comment by jahorton** [comment]
After a smidge more investigation... right, context changes are auto-applied against the real element for the regular keystroke.  We might need to abstract that a little bit.

https://github.com/keymanapp/keyman/blob/665c685832e4471943f99b81cd4cc183085a5386/common/web/input-processor/src/text/inputProcessor.ts#L164-L166

We should probably make an extra `Mock` from `outputTarget`, then evaluate on that.  Then, if the resulting transform is _not_ a no-op, we re-apply the transform on the actual `outputTarget` here:

https://github.com/keymanapp/keyman/blob/665c685832e4471943f99b81cd4cc183085a5386/common/web/input-processor/src/text/inputProcessor.ts#L199-L201

(right before the `finalize` call)

That's my current best guess.

**Comment by darcywong00** [comment]
Hmm, I don't quite follow all that, so I'm assigning @jahorton for the input-processor changes.

**Comment by jahorton** [comment]
Been investigating the work done in #6249, as I've bumped up against it during some recent modularization work.

Long story short, I think that PR went "overkill" and missed something kinda simple.

https://github.com/keymanapp/keyman/blob/b3cff7e7d332b0eeeb4335ccc79d5cfaa7ac3094/web/src/engine/main/dom/domOverrides.ts#L22-L37

I'm almost positive that lines 31-37 belong within the if-condition of lines 24-28, inserted at the end.  There's no reason to report text changes when none occur, after all.

That said, this only partially resolves the backspace issue... but I may have a minor idea now.  I'll put that where it belongs.

**Comment by darcywong00** [comment]
Bumping back to 17.0 for @jahorton to look at when modularization refactor is completed.

**Comment by mcdurdin** [comment]
Just verified that this does not happen in KeymanWeb in browser, only in webview (i.e. iOS and Android apps).

**Comment by mcdurdin** [comment]
> but switches to the capitalised layer automatically which is not what I usually want

This part is tracked in #7168.
