### ISSUE TITLE
docs: add flowchart for PR process

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#7871]
Maybe need edits to Wiki on GH [workflow ](https://github.com/keymanapp/keyman/wiki/Pull-Request-and-Commit-workflow-notes); MS would like a flowchart on the workflow.

We can use [mermaid diagrams](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-diagrams)

**Comment by darcywong00** [comment]
Draft of flowchart: https://github.com/keymanapp/keyman/wiki/Pull-Request-and-Commit-workflow-notes#flowchart-of-pr-workflow

**Comment by mcdurdin** [comment]
@MakaraSok we have a flowchart above. Is it sufficient? Reopen this if not 😄
