### ISSUE TITLE
bug(developer): Typing a search in the character map produced an error and developer exited

### ISSUE THREAD

**Issue by sewhite** [keymanapp/keyman#7879]
### Describe the bug

Details for error report for Keyman app:
  Application Identifier: tike-15.0.274
  Error Identifier: 4164B7C919F540AFD4394FC8419060E2

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [X] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

15.0.274

### Operating system

Windows 11 22H2

### Device

Windows laptop

**Comment by mcdurdin** [comment]
Thank you for this report @sewhite -- it really helps to have the user context! Do you happen to know what you were typing into the search box?

**Comment by mcdurdin** [comment]
Call stack:

```
OS Version: Windows 10.0.22621 (755)
Report Version: 104


Application Specific Information:
Exception EInvalidGridOperation in module tike.exe at 00344166.
Grid index out of range.


Thread 0
0   tike.exe                        0x744166            Vcl.Grids.InvalidOp (Vcl.Grids.pas:898)
1   tike.exe                        0x7489d4            Vcl.Grids.TCustomGrid.FocusCell (Vcl.Grids.pas:3318)
2   tike.exe                        0x74bd32            Vcl.Grids.TCustomGrid.SetRow (Vcl.Grids.pas:4913)
3   tike.exe                        0x575b05            Vcl.Controls.TControl.CMMouseWheel (Vcl.Controls.pas:7820)
4   tike.exe                        0x5798e7            Vcl.Controls.TWinControl.WndProc (Vcl.Controls.pas:10278)
5   tike.exe                        0x574a6a            Vcl.Controls.TControl.Perform (Vcl.Controls.pas:7198)
6   tike.exe                        0x573b6a            Vcl.Controls.TControl.MouseWheelHandler (Vcl.Controls.pas:6638)
7   tike.exe                        0x5798e7            Vcl.Controls.TWinControl.WndProc (Vcl.Controls.pas:10278)
8   tike.exe                        0x578eb2            Vcl.Controls.TWinControl.MainWndProc (Vcl.Controls.pas:9977)
9   tike.exe                        0x48bc2d            System.Classes.StdWndProc (System.Classes.pas:17929)
10  USER32.dll                      0x75932412          _InternalCallWinProc
11  USER32.dll                      0x759231d5          UserCallWinProcCheckWow
12  USER32.dll                      0x75921a94          DispatchMessageWorker
13  USER32.dll                      0x759215df          DispatchMessageW
14  tike.exe                        0x685c93            Vcl.Forms.TApplication.ProcessMessage (Vcl.Forms.pas:10747)
15  tike.exe                        0x685cd6            Vcl.Forms.TApplication.HandleMessage (Vcl.Forms.pas:10777)
16  tike.exe                        0x686009            Vcl.Forms.TApplication.Run (Vcl.Forms.pas:10915)
```

**Comment by sewhite** [comment]
I got it to happen again. I typed “dot under” and it crashed Details for error report for Keyman app:  Application Identifier: tike-15.0.274  Error Identifier: 9037949774434AA62242BE430353CE2D   Steve WhiteInternational Language Technology Consultant From: Marc DurdinSent: Thursday, December 8, 2022 6:44 PMTo: keymanapp/keymanCc: Steve White; MentionSubject: Re: [keymanapp/keyman] bug: developer, typing a search in the character map produced an error and developer exited (Issue #7879) Thank you for this report @sewhite -- it really helps to have the user context! Do you happen to know what you were typing into the search box?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by sewhite** [comment]
Second  try. I recorded my screen and saw  the crash. I could type “dot under” and it did not crash, but I did some other random searches, then went back to dot under and it did crash.  Details for error report for Keyman app:  Application Identifier: tike-15.0.274  Error Identifier: 0D5B5C3B02274D236374A42758050CB3 The recording: https://drive.google.com/file/d/1doB4zquJ9hlARHd0C_yvfmpLvAS6fGLG/view?usp=sharing  Steve WhiteInternational Language Technology Consultant From: Marc DurdinSent: Thursday, December 8, 2022 6:44 PMTo: keymanapp/keymanCc: Steve White; MentionSubject: Re: [keymanapp/keyman] bug: developer, typing a search in the character map produced an error and developer exited (Issue #7879) Thank you for this report @sewhite -- it really helps to have the user context! Do you happen to know what you were typing into the search box?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by mcdurdin** [comment]
A set of steps to reproduce:

1. Empty the filter field
2. Select a cell in any row > 1
3. Type a filter such as 'xx' which empties the search results
4. Use the mouse wheel to scroll up

The reason this is happening is that the grid is attempting to select row 0 when we reduce the search results to zero, but our code prevents selection of row 0.
