### ISSUE TITLE
bug(developer): Keyman Developer does not flag virtual keycodes in context string as an error

### ISSUE THREAD

**Issue by sewhite** [keymanapp/keyman#7880]
### Describe the bug

If you use a virtual key code in the context part of a rule, Keyman Developer does not tell you this is an error. But the language guide says virtual key codes can only work in the keystroke part of the rule. A rule with a virtual keycode in the context will not work. 

See this screenshot. The rule will never work, but the Developer compiles it without reporting a problem.

![image](https://user-images.githubusercontent.com/16904461/206270242-d195acda-615c-4c0e-a47b-0f2aa86e9592.png)

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [X] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Operating system

Windows 11 22H2

### Device

Windows laptop

**Comment by sewhite** [comment]
Actually the example is rather non-sensical. What I meant to compose as an example was this:
store(&NAME) 'vk_test'

begin Unicode > use(main)

group(main) using keys
store (consonant) "lmn"
store (sylcons) U+1E37 U+1E43 U+1E47


[K_BKQUOTE] + any(consonant) > index (sylcons, 2 )

**Comment by mcdurdin** [comment]
Coming out of discussions in:
* https://community.software.sil.org/t/virtual-keys-only-work-as-last-item-on-match-side/7001
* https://community.software.sil.org/t/beginner-code-check/7000
