### ISSUE TITLE
feat(web): Make Base Key Visible with Popups (Enhancement)

### ISSUE THREAD

**Issue by dyacob** [keymanapp/keyman#7889]
### Is your feature request related to a problem? Please describe.

On an iPhone, when a keyboard has a popup menu for key selection, the pressed key is masked in white as seen in the screenshot when the `ህ` key is pressed in the GFF Amharic keyboard:

![iPhone-KM-Popup-CSS](https://user-images.githubusercontent.com/8098333/206861807-4e678241-add2-4926-a756-d62e5b4a4afc.jpeg)

### Describe the solution you'd like

I think it is a better user experience to keep the pressed key visible as done with the popups under Android.  Note that the inverted triangle ▾ at the bottom of the keyboard that points to the pressed key is a good approach that could be synched to the iOS popups:

![Android-KM-Popup-CSS](https://user-images.githubusercontent.com/8098333/206861808-ceed8e38-294d-41ca-9f5e-3761e7756a51.jpg)

### Keyman apps

- [ ] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

15.0.273

### Operating system

iOS 16.1.2

### Device

iPhone (probably on iPad also)

### Keyboard name

gff_amharic

### Keyboard version

3.1

### Language name

Amharic

### Additional context

This is a general iOS styling issue, not specific to any one keyboard.

**Comment by jahorton** [comment]
See #9911 - this will land as part of the upcoming gestures feature for 17.0.
