### ISSUE TITLE
bug(web): Add Bottom Border to Popup Keys when Styled

### ISSUE THREAD

**Issue by dyacob** [keymanapp/keyman#7890]
### Is your feature request related to a problem? Please describe.

On an iPhone, keys on a popup menu have a border around styled keys on 3 sides, but not the bottom side.  In the attached screenshot, the bottom area of a popup without the border has been outlined:

![iPhone-KM-Popup-CSS-No-Border](https://user-images.githubusercontent.com/8098333/206862494-59a2e4ad-82a5-4f16-89a8-7d0d0a65e166.jpeg)

### Describe the solution you'd like

An equal border all around.

### Keyman apps

- [ ] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

15.0.273

### Operating system

iOS 16.1.2

### Device

iPhone (probably on iPad also)

### Keyboard name

gff_amharic

### Keyboard version

3.1

### Language name

Amharic

### Additional context

This is a general iOS CSS issue and not specific to a particular keyboard.

**Comment by mcdurdin** [comment]
Is this the same when the keys have default styling?

**Comment by jahorton** [comment]
Interestingly, this only seems to be an issue within the mobile apps; the same code, as used for KeymanWeb's OSK on mobile devices, does not have this problem.  Seems to be something WebView-related somehow.

**Comment by jahorton** [comment]
And @mcdurdin had the deep knowledge & intuition here:  our Web test pages include the `<!DOCTYPE html>` header to ensure standards mode, while the keyboard host-pages within the mobile apps did not.  Apparently "quirks mode" vs "standards mode" was the difference.

**Comment by jahorton** [comment]
This will land as part of the upcoming gestures feature for 17.0; it's already been fixed on that branch.
