### ISSUE TITLE
feat(developer): Add a "Compile" button to the Keyman Developer Toolbar

### ISSUE THREAD

**Issue by dyacob** [keymanapp/keyman#7891]
### Is your feature request related to a problem? Please describe.

I have a usage pattern with KMD where I make a change under "Layout", switch to the "Build" screen, click "Compile Keyboard", read the messages, then go back to "Layout" to make a change and repeat.  This often feels like a like of screen travel that can be reduced.

### Describe the solution you'd like

A "Compile" button in the Keyman Developer toolbar, to the right of the encoding dropdown menu, would be helpful to avoid this back-and-forth screen travel.

### Describe alternatives you've considered

The "F7" key is an alternative, but I tend to forget it's an option.  On my laptop the function keys require that two keys are chorded together which discourages their use.

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [X] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

15.0.274

### Operating system

Windows 11

### Device

Windows Laptop

**Comment by mcdurdin** [comment]
This should be straightforward to implement. Hopefully make it into v17
