### ISSUE TITLE
chore(common): move to release@semver versioning for sentry reporting

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#7895]
Per sentry:

The releases aren't in the SemVer format we are expecting. For example, `release-16.0.117-beta`  isn't something we can parse but if the format had been `release@16.0.117-beta` it would've worked. If you change the formatting for the release, it should work according to your current workflow. For more information on how our releases and SemVer work, click [this link](https://docs.sentry.io/platforms/node/guides/serverless-cloud/configuration/releases/#bind-the-version).

**Comment by darcywong00** [comment]
Is this why Sentry kept reopening issues as regressions?

**Comment by mcdurdin** [comment]
> Is this why Sentry kept reopening issues as regressions?

yep
