### ISSUE TITLE
test(common): Desktop app compatibility tests - Prosemirror

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#7902]
The basic idea is to load the example page for each Text Editor (in this case, Prosemirror), and then test input with latest release version of Keyman apps and a variety of keyboards.

# Gather Assets for Testing
Install the following keyboards and have the test page link ready to load on the respective browser.
* Keyman app - Latest version
* Khmer Angkor keyboard [package](https://keyman.com/go/package/download/khmer_angkor?version=1.3&tier=stable)
* EuroLatin (SIL) keyboard [pagekage](https://keyman.com/go/package/download/sil_euro_latin?version=2.0&tier=stable)
* Galaxie Hebrew (Positional) keyboard [package](https://keyman.com/go/package/download/galaxie_hebrew_positional?version=2.2&tier=stable)
* IPA (SIL) keyboard [package](https://keyman.com/go/package/download/sil_ipa?version=1.8.6&tier=stable)
* Korean KORDA Jamo (SIL) keyboard [package](https://keyman.com/go/package/download/sil_korda_jamo?version=3.0&tier=stable&bcp47=ko)
* Prosemirror test [page](https://prosemirror.net/.): type in the text area to test
<img src="https://user-images.githubusercontent.com/28331388/207572387-83a396ec-1dcc-45a2-975a-1389f31b682c.png" width="400">

We need to test in a variety of Operating Systems and Browsers:
* GROUP_WIN10_CHROME: Windows 10 / Chrome browser
* GROUP_WIN10_FIREFOX: Windows 10 / Firefox browser
* GROUP_MACOS_CHROME: macOS / Chrome browser
* GROUP_MACOS_FIREFOX: macOS / Firefox browser
* GROUP_MACOS_SAFARI: macOS / Safari browser
* GROUP_UBUNTU_CHROME: Ubuntu / Chrome browser 
* GROUP_UBUNTU_FIREFOX: Ubuntu / Firefox browser

# User Testing

Prosemirror have a test on their homepage: https://prosemirror.net/. Load it up on the respective OS and browser to test the followings:
   * TEST_KHMER_ANGKOR: Khmer Angkor
      * Ensure the key combination <kbd>AltGr</kbd> <kbd>B</kbd> produces `ឞ`. Note that on macOS, the function key to use is right `option`.
      * Type the following (US) keys in sequence: <kbd>s</kbd> <kbd>u</kbd> <kbd>j</kbd> <kbd>r</kbd> <kbd>k</kbd>. You should see `ស្រុក`.
   * TEST_SIL_EURO_LATIN: SIL Euro Latin
      * Type <kbd>%</kbd> <kbd>a</kbd>. Ensure the output is `ǎ`
   * TEST_GALAXIE_HEBREW: Galaxie Hebrew or another good SIL RTL keyboard
      * Type <kbd>b</kbd> <kbd>\\</kbd> <kbd>=</kbd> <kbd>r</kbd> <kbd>@</kbd> <kbd>a</kbd> <kbd>v</kbd> <kbd>!</kbd> <kbd>y</kbd> <kbd>t</kbd> to output `בְּרֵאשִׁית`. FAILED if the output is different.
   * TEST_SIL_IPA: sil_ipa
      * Ensure the key sequence <kbd>n</kbd> <kbd>></kbd> produces `ŋ`.
   * TEST_INTERACTION_WITH_TEXT_FORMATTING:
      * when a Keyman keyboard is active and you are able to enable bold by using the keyboard shortcut (i.e. <kbd>Ctrl</kbd> + <kbd>b</kbd>).
      * PASSED if the bold is enabled on the first character and the rest of the text being typed, otherwise FAILED.
      * _Note that on macOS, the keyboard shortcut for Bold is `command`+`b`._
   * TEST_CJK_IMX: Korean KORDA Jamo (SIL)
      * Type <kbd>h</kbd> <kbd>a</kbd> <kbd>n</kbd> `<space>` <kbd>g</kbd> <kbd>e</kbd> <kbd>u</kbd> <kbd>l</kbd> `<space>`. Verify that the result is `한글`.

**Comment by bharanidharanj** [comment]
### GROUP_WIN10_CHROME: Windows 10 / Chrome browser

* **TEST_KHMER_ANGKOR (FAILED):** Tested this in Windows 10 / Chrome browser as per the instructions and here is my observation: 1. I was able to see the expected result in the text area. However, the combination of Ctrl+Alt +B did not show ឞ letter. 

<img width="300" src="https://user-images.githubusercontent.com/19683143/207882517-b1c80599-6f34-4121-9368-0959987d3852.PNG">

* **TEST_SIL_EURO_LATIN (PASSED):** It is working as expected. 

<img width="300" src="https://user-images.githubusercontent.com/19683143/207884552-796d54d3-fea4-46ed-b2c4-52761d04f66a.PNG">


* **TEST_GALAXIE_HEBREW (FAILED):** Installed Galaxie Hebrew Keyboard and typed in the text area as per the instructions. It is showing different output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/207885132-d0a1f625-5e46-4684-92a9-b72686d79067.PNG">

* **TEST_SIL_IPA (PASSED):** It is working as expected. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/207886412-dc242f20-7bc0-40b1-9069-bf2d93943bd2.PNG">


* **TEST_INTERACTION_WITH_TEXT_FORMATTING (PASSED):** Noticed that the bold is enabled on the first character I typed on the text area. Able to enable bold or disable it using the keyboard shortcut keys. (ctrl+b).

   <img width="300" src="https://user-images.githubusercontent.com/19683143/207886471-0a1f7ae7-1327-4acf-a0f5-138669ed22d5.PNG">


* **TEST_CJK_IMX (PASSED):** It is working as expected. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/207886514-4c845b66-08bb-4f42-aa04-5314e65427d4.PNG">

**Comment by bharanidharanj** [comment]
# Test Results

### GROUP_WIN10_FIREFOX: Windows 10 / Firefox browser

* **TEST_KHMER_ANGKOR (FAILED):** Tested this in Windows 10 /  Firefox browser and here is my observation. 1. Typing s u j r k produced the expected result. But, the Key combination Ctrl + Alt + B didn't give the expected output ឞ.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/208080487-8058389a-917d-4235-84b7-1026565c8f34.PNG">

* **TEST_SIL_EURO_LATIN (PASSED):** It is working as expected. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/208080689-7122e8ae-fa3c-411a-8b52-c1d31145388e.PNG">

* **TEST_GALAXIE_HEBREW (PASSED):** It is showing the expected output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/208080767-7ca0528e-fb83-4918-a009-1114f8ba3871.PNG">

* **TEST_SIL_IPA (PASSED):** It produced the expected output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/208080996-fc130d19-58f7-4eab-a160-731e50f89279.PNG">


* **TEST_INTERACTION_WITH_TEXT_FORMATTING (PASSED):** Able to change the font style to bold or without bold using Ctrl + B key combination. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/208083687-610ce597-b520-4461-a272-126bda340aac.PNG">


* **TEST_CJK_IMX (PASSED):** It is showing correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/208083711-7f1205a1-ccbc-446f-a5cb-b55e650af156.PNG">

**Comment by bharanidharanj** [comment]
# Test Results

### GROUP_MACOS_FIREFOX: macOS / Firefox browser

* **TEST_KHMER_ANGKOR (FAILED):** Tested with the latest Keyman 17.0.17-alpha build in macMini 12.6 Monterey OS and here is my observation: Noticed that the combination of Ctrl + Alt + B produced nothing on the text area. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/208098492-7eed35fc-a4a9-420e-81bb-bd724ff3cd7e.png">


* **TEST_SIL_EURO_LATIN (PASSED):** It is showing the expected output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/208098540-44f0dc69-12e6-4a13-b5eb-d3ec2fe21f5d.png">


* **TEST_GALAXIE_HEBREW (PASSED):** It is showing the expected output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/208098562-aa717f57-5064-4db3-9d27-afeb8a0c04f8.png">


* **TEST_SIL_IPA (PASSED):** It is showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/208098610-86daeaf8-82a2-4bf8-888d-b25719ca3182.png">


* **TEST_INTERACTION_WITH_TEXT_FORMATTING (FAILED):** Pressing Ctrl + B did not change the font style into Bold. Seems to be not working as expected. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/208099307-6207d89e-b79e-4bfc-baf9-e75570163319.png">

* **TEST_CJK_IMX (FAILED):** It is showing wrong output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/208098772-2a113369-86c1-406a-b3c0-484f24405a70.png">

**Comment by bharanidharanj** [comment]
# Test Results

### GROUP_MACOS_CHROME: macOS / Chrome browser

* **TEST_KHMER_ANGKOR (FAILED):** Tested this with the latest Keyman 17.0.17-alpha build in macMini 12.6 OS and here is my observation: The combination of Ctrl + Alt + B did not produce the expected output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/208105993-6b781f66-1f41-4db6-bf41-51a61153a9d9.png">

* **TEST_SIL_EURO_LATIN (PASSED):** It is showing the correct output.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/208106029-4bd417ce-c69d-42f7-b4e6-f4cf44cbd947.png">


* **TEST_GALAXIE_HEBREW (PASSED):** It is showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/208106064-f81f7d1c-1cc9-4e97-86ca-58c160eb2243.png">
 
* **TEST_SIL_IPA (PASSED):** It is showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/208106139-54ee862e-76e0-48f3-ad03-32abf92e6a65.png">

* **TEST_INTERACTION_WITH_TEXT_FORMATTING (FAILED):**  Pressing Ctrl+B short cut keys did not change the Font style into Bold. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/208106164-7bbbbab7-3f5e-4ca9-a6b8-b9f1aef531c0.png">


* **TEST_CJK_IMX (FAILED):** It is showing the wrong output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/208106259-14f3509d-f663-480c-bf6d-3c381a928450.png">

**Comment by bharanidharanj** [comment]
# Test Results

### GROUP_MACOS_SAFARI: macOS / Safari browser

* **TEST_KHMER_ANGKOR (FAILED):** Noticed that the combination of Ctrl + Alt + B did not produce the expected output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/208115318-53946b77-30c5-4ff3-a629-865834db3d34.png">


* **TEST_SIL_EURO_LATIN (PASSED):** It is showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/208115548-35907bee-1434-4b65-b753-b7d9a7e4982a.png">


* **TEST_GALAXIE_HEBREW (PASSED):** It is showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/208115570-9a501615-8e2f-4105-8495-c9bf45c451c0.png">


* **TEST_SIL_IPA (PASSED):** It is showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/208115655-6f28e799-46a9-4790-82c3-c5be7ca4422c.png">


* **TEST_INTERACTION_WITH_TEXT_FORMATTING (FAILED):** Pressing Ctrl + B did not change the font style into Bold. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/208115745-8e3c1aeb-6dcb-4a2a-b948-ebccfa12ef74.png">


* **TEST_CJK_IMX (FAILED):** It is showing the wrong output. 
   
   <img width="300" src="https://user-images.githubusercontent.com/19683143/208116487-811b3a29-1bfe-4039-a0fe-80035494daaa.png">

**Comment by bharanidharanj** [comment]
# Test Results

### GROUP_UBUNTU_FIREFOX: Ubuntu / Firefox browser

* **TEST_KHMER_ANGKOR (FAILED):** Tested with Keyman 17.0.19-alpha (package version 17.0.19-1~sil~focal) build in Ubuntu 20.04 Focal Linux OS and here is my observation: 1. Typing s u j r k gives the expected output. 2. However, the key combination of Ctrl + Alt + B did not show anything on the text area. 

  <img width="300" src="https://user-images.githubusercontent.com/19683143/208370472-35b693c5-0810-4faa-9059-1160b734b6d2.PNG">


* **TEST_SIL_EURO_LATIN (PASSED):** It is showing the expected output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/208370512-f7f44749-ce48-4c73-9b86-3ded561d9292.PNG">

* **TEST_GALAXIE_HEBREW (PASSED):** It is showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/208370530-d6013f00-af72-4c79-b0f2-0bca303f644e.PNG">


* **TEST_SIL_IPA (PASSED):** It is showing the expected result. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/208370560-6cd3e01f-f44f-4d3e-9f9b-ea00de86bfad.PNG">


* **TEST_INTERACTION_WITH_TEXT_FORMATTING (PASSED):** Pressing Ctrl + B would enable the Bold Style. And, I was able to type in Bold using the Ctrl+B key combination. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/208370606-4139861e-1aaf-4d01-8aca-67d0c0497524.PNG">


* **TEST_CJK_IMX (PASSED):** It is showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/208370636-e4eed549-633f-4cff-acb4-2d619c8f6acb.PNG">

**Comment by bharanidharanj** [comment]
# Test Results

### GROUP_UBUNTU_CHROME: Ubuntu / Chrome browser 

* **TEST_KHMER_ANGKOR (FAILED):** Tested with Keyman 17.0.19-alpha build in Chromium Web browser in Ubuntu 20.04 Focal Linux OS and here is my observation: 1. Able to see the expected output. However, Pressing Ctrl+Alt+B did not show anything in the Text area. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/208375429-11c950bc-3d5b-4a88-aec5-24715ffdffe6.PNG">


* **TEST_SIL_EURO_LATIN (PASSED):** It is showing correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/208375458-6935904b-4b9f-4c0c-a375-765c6c2c72e6.PNG">


* **TEST_GALAXIE_HEBREW (PASSED):** It is showing the expected output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/208375480-43be028d-a1d3-4585-87a7-ef2b4922ccbd.PNG">


* **TEST_SIL_IPA (PASSED):** It is showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/208375514-250a53b1-440b-4507-bf59-ab7e50811188.PNG">


* **TEST_INTERACTION_WITH_TEXT_FORMATTING (PASSED):** Pressing Ctrl + B would enable the Bold style and I am able to type in the bold style in text area. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/208375545-d1fd768d-c33a-45da-ac06-c4bf11328a4e.PNG">


* **TEST_CJK_IMX (PASSED):** It is showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/208375620-565cbe0e-d95c-41a8-9bb1-8f8344237f42.PNG">

**Comment by MakaraSok** [comment]
The test cases have been amended. Please retest the following.

@keymanapp-test-bot retest GROUP_WIN10_CHROME TEST_KHMER_ANGKOR GROUP_WIN10_FIREFOX TEST_KHMER_ANGKOR GROUP_MACOS_CHROME TEST_KHMER_ANGKOR TEST_INTERACTION_WITH_TEXT_FORMATTING GROUP_MACOS_FIREFOX TEST_KHMER_ANGKOR TEST_INTERACTION_WITH_TEXT_FORMATTING GROUP_MACOS_SAFARI TEST_KHMER_ANGKOR TEST_INTERACTION_WITH_TEXT_FORMATTING GROUP_UBUNTU_CHROME TEST_KHMER_ANGKOR GROUP_UBUNTU_FIREFOX TEST_KHMER_ANGKOR

**Comment by bharanidharanj** [comment]
# Test Results

### GROUP_WIN10_CHROME: Windows 10 / Chrome browser

* **TEST_KHMER_ANGKOR (PASSED):** Retested as per Makara's new instructions and it is showing the correct output. 

<img width="300" src="https://user-images.githubusercontent.com/19683143/208906827-04657fab-ccc3-438f-8d02-5a42e0be7c51.PNG">


### GROUP_WIN10_FIREFOX: Windows 10 / Firefox browser

* **TEST_KHMER_ANGKOR (PASSED):** Retested as per Makara's new instructions and it is showing the correct output.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/208906884-ac5d7fd8-1991-4c18-82b1-a787fc733e03.PNG">

**Comment by bharanidharanj** [comment]
### GROUP_MACOS_FIREFOX: macOS / Firefox browser

* **TEST_KHMER_ANGKOR (PASSED):** Retested this as per Makara's new instructions and it is showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/208913226-0dc752ac-07b9-4755-9a05-c1f2994db48e.png">

* **TEST_INTERACTION_WITH_TEXT_FORMATTING (PASSED):** Retested this as per Makara's new instructions and it is showing the correct output.

<img width="300" src="https://user-images.githubusercontent.com/19683143/208913274-8b093c55-50f0-4280-9988-58e07787559b.png">

**Comment by bharanidharanj** [comment]
### GROUP_MACOS_CHROME: macOS / Chrome browser

* **TEST_KHMER_ANGKOR (PASSED):** Retested this as per Makara's new instructions and it is showing the correct output.

* **TEST_INTERACTION_WITH_TEXT_FORMATTING (PASSED):** Retested this as per Makara's new instructions and it is showing the correct output.

### GROUP_MACOS_SAFARI: macOS / Safari browser

* **TEST_KHMER_ANGKOR (PASSED):** Retested this as per Makara's new instructions and it is showing the correct output.

* **TEST_INTERACTION_WITH_TEXT_FORMATTING (PASSED):** Retested this as per Makara's new instructions and it is showing the correct output.

**Comment by bharanidharanj** [comment]
# Test Results

### GROUP_UBUNTU_CHROME: Ubuntu / Chrome browser 

* **TEST_KHMER_ANGKOR (PASSED):** Retested this as per Makara's new instructions and it is showing the correct output.

### GROUP_UBUNTU_FIREFOX: Ubuntu / Firefox browser

* **TEST_KHMER_ANGKOR (PASSED):** Retested this as per Makara's new instructions and it is showing the correct output.

**Comment by MakaraSok** [comment]
## Verification tests with Keyman 16.0.138 - stable

* GROUP_WIN10_CHROME: [THE SAME RESULTS AS ABOVE] 👍 
![image](https://user-images.githubusercontent.com/28331388/221504337-07619a12-5c2d-4603-8352-71b6828fcdbf.png)

* GROUP_WIN10_FIREFOX: [THE SAME RESULTS AS ABOVE] 👍 
![image](https://user-images.githubusercontent.com/28331388/221504441-b479e2a8-592c-464d-b5d9-c7a657665623.png)

* GROUP_MACOS_CHROME: [THE SAME RESULTS AS ABOVE] 👍 
But discussion may be needed regarding the validity of the Hebrew text. It's text alignment and cursor position.
<img width="960" alt="image" src="https://user-images.githubusercontent.com/28331388/221518984-0f8a7bb0-5b80-4754-b7e8-fdd1969eab78.png">

## TBD

**Comment by MakaraSok** [comment]
@keymanapp-test-bot retest GROUP_UBUNTU_CHROME TEST_KHMER_ANGKOR TEST_SIL_EURO_LATIN TEST_SIL_IPA  TEST_CJK_IMX GROUP_UBUNTU_FIREFOX TEST_KHMER_ANGKOR TEST_SIL_EURO_LATIN

**Comment by bharanidharanj** [comment]
# Test Results

### GROUP_UBUNTU_CHROME: Ubuntu / Chrome browser 

* **TEST_KHMER_ANGKOR (PASSED):** Retested with the latest Keyman 17.0.61-alpha build in Ubuntu 20.04 Focal Linux OS and it is showing the correct output. 

   <img width="100" src="https://user-images.githubusercontent.com/19683143/223464332-357adbc3-eacf-4b89-a30d-19e917d4407a.PNG">

* **TEST_SIL_EURO_LATIN (PASSED):** Retested with the latest Keyman 17.0.61-alpha build in Ubuntu 20.04 Focal Linux OS and it is showing the correct output. 

   <img width="100" src="https://user-images.githubusercontent.com/19683143/223464369-bc443542-033d-4e4f-8575-0023904d0545.PNG">


* **TEST_SIL_IPA (PASSED):** Retested with the latest Keyman 17.0.61-alpha build in Ubuntu 20.04 Focal Linux OS and it is showing the correct output. 

   <img width="100" src="https://user-images.githubusercontent.com/19683143/223464394-17df31fa-27e7-4e24-bcc5-4195e17ba05f.PNG">


* **TEST_CJK_IMX (PASSED):** Retested with the latest Keyman 17.0.61-alpha build in Ubuntu 20.04 Focal Linux OS and it is showing the correct output. 

   <img width="100" src="https://user-images.githubusercontent.com/19683143/223464437-a2127f5d-ae8e-4004-807c-43dc4ea7a610.PNG">



### GROUP_UBUNTU_FIREFOX: Ubuntu / Firefox browser

* **TEST_KHMER_ANGKOR (PASSED):** Retested with the latest Keyman 17.0.61-alpha build in Ubuntu 20.04 Focal Linux OS and it is showing the correct output. Here, I noticed that just typing 'b' would produce ឞ. 

   <img width="100" src="https://user-images.githubusercontent.com/19683143/223464467-5f2ee1e7-7889-4085-b5e7-2fdd9588135e.PNG">


* **TEST_SIL_EURO_LATIN (PASSED):** Retested with the latest Keyman 17.0.61-alpha build in Ubuntu 20.04 Focal Linux OS and it is showing the correct output. 

   <img width="100" src="https://user-images.githubusercontent.com/19683143/223464502-33c0a4e3-a4d8-4819-b3bb-9ff012b5b941.PNG">

**Comment by MakaraSok** [comment]
- [x] Verification test
- [x] Retest
