### ISSUE TITLE
bug(android): Cameroon (Afade) Keyboard appears twice in the Installed Languages menu after upgrading it in Android 5.0

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#7903]
### Describe the bug

While upgrading keyboards, I noticed that the keyboard has been duplicated once again and appears with upgrade icon in the Installed languages menu. 

### Reproduce the bug

1. Install Keyman 17.0.16-alpha build in Android 5.0 emulator. 
2. Set the Date and time to previous year.
3. Turn on Flight mode. 
4. Install 'Cameroon Qwerty' Keyboard (Afade) from local folder. 
5. We may notice that the Afade keyboard was installed successfully. 
6. Close KeymanApp.
7. Set current date and time. 
8. Turn off Flight mode. 
9. Relaunch Keyman App. 
10. Click Settings / Installed languages option. 
11. After a while, we may notice that there is an update icon appears with Afade 6.0.4 name. 
12. Click the Update icon. 
13. Afade: Cameroon QWERTY (would you like to download the latest version of this keyboard?) warning message appears on the screen. 
14. Click the Download button. 
15. We may notice there was a 'Cloud Download KeyboardPackage' file running on the background of the Keyman App. 
16. Wait for a while. Click Settings / Install Languages option. 
17. Here, I noticed that the 'Afade' keyboard appears twice in the Languages menu. 
18. Click the first 'Afade' Keyboard and verify the Information page.  
19. Here, it is showing the upgraded version of Afade keyboard. ie., Afade 6.0.8
20. Open the second 'Afade' Keyboard and verify the Information page. 
21. Here, it is showing the upgraded version of Afade keyboard with update icon. 

Seems to be an issue. 

   <img width="500" src="https://user-images.githubusercontent.com/19683143/207571189-6ed64916-bf68-4ceb-b3ab-647074679bd5.PNG">

### Expected behavior

1. Only one Afade Keyboard appears with the upgraded version number in the Installed Languages menu. 
2. It should not have 'update icon' after  upgradation. 

### Related issues

Linked with similar issue : https://github.com/keymanapp/keyman/pull/7740

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.16-alpha

### Operating system

Android 5.0

### Device

API 21 Android Emulator

### Target application

Keyman In-App

### Keyboard name

Cameroon QWERTY

### Keyboard version

6.0.4

### Language name

Afade

**Comment by darcywong00** [comment]
The fix from #7807 didn't get cherry-picked to master until yesterday in #7885.
@bharanidharanj can you retest with [17.0.17-alpha](https://downloads.keyman.com/android/alpha/17.0.17/keyman-17.0.17.apk) (It failed to upload to Play store due to separate issue)

**Comment by bharanidharanj** [comment]
> The fix from #7807 didn't get cherry-picked to master until yesterday in #7885. @bharanidharanj can you retest with [17.0.17-alpha](https://downloads.keyman.com/android/alpha/17.0.17/keyman-17.0.17.apk) (It failed to upload to Play store due to separate issue)
> 
> The version of Android shouldn't impact the test.

@mcdurdin Sure. I will retest it.

**Comment by bharanidharanj** [comment]
@darcywong00 Retested this issue with Keyman 17.0.17-alpha build in Android 5.0 / API 21 emulator and I was able to reproduce the same.

**Comment by darcywong00** [comment]
OK, this is because sil_cameroon_qwerty keyboard version 6.0.4 uses the language ID `aal-Latn` for Afade
But in keyboard version 6.0.8, the langauge ID is changed to `aal` for Afade.

The Keyman for Android Engine code treats the different language ID's as separate languages - so that's why "Afade" appears twice in the languages menu.

This was already noted in 
https://github.com/keymanapp/keyman/issues/7801#issuecomment-1325801203

**Comment by bharanidharanj** [comment]
> OK, this is because sil_cameroon_qwerty keyboard version 6.0.4 uses the language ID `aal-Latn` for Afade But in keyboard version 6.0.8, the langauge ID is changed to `aal` for Afade.
> 
> The Keyman for Android Engine code treats the different language ID's as separate languages - so that's why "Afade" appears twice in the languages menu.
> 
> This was already noted in [#7801 (comment)](https://github.com/keymanapp/keyman/issues/7801#issuecomment-1325801203)

@darcywong00 Oh Okay. Thanks for the explanation.
