### ISSUE TITLE
chore(android): update advertising id info for play store

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#7913]
Per [build log](https://build.palaso.org/viewLog.html?buildId=355526&buildTypeId=KeymanAndroid_Build):

```
"errors": [
{
  "domain": "global",
  "message": "Your app targets Android 13 (API 33) or above. You must declare the use of advertising ID in Play Console.",
  "reason": "badRequest"
}
],
```

**Comment by darcywong00** [comment]
This is resolved in the Google Play Console --> Policy and Programs --> App content --> Advertising ID -->
Declaring our app does not use advertising ID.

**Comment by darcywong00** [comment]
@mcdurdin to update the advertising ID for FV Android and we'll see if the next nightly 17.0 build successfully publishes.

**Comment by darcywong00** [comment]
17.0.18 alpha successfully built and uploaded to Play Store - so this can be closed
