### ISSUE TITLE
bug(ios): Hebrew vowels not visible with iOS 16

### ISSUE THREAD

**Issue by sgschantz** [keymanapp/keyman#7914]
### Describe the bug

When using the SIL Ancient Hebrew keyboard on an iPhone running iOS 16, the vowel keys are blank. They appear as expected with iOS 15, but this is not enough testing to be certain that it is iOS version related.

Though the keys are blank, they still produce the correct characters when tapped.

![image](https://user-images.githubusercontent.com/89134789/208004563-fea640d1-ac20-4201-9d99-5feeb669ff72.png)

Tested on 
iPhone 13 mini, iOS16.0.2 => blank vowel keys
iPhone 11 Pro, iOS 15.4.1 => vowels are visible on keys

First reported on the SIL community site: https://community.software.sil.org/t/keyboard-fails-to-load-load-correctly-on-iphone-xr-11/6958/3

### Keyman apps

- [ ] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.16-alpha

### Operating system

iOS 16.0.2

### Device

iPhone 13 mini

### Keyboard name

Ancicent Hebrew (SIL)

### Language name

Hebrew

**Comment by DylanCross** [comment]
Thanks for kicking this off Shawn. 

For anyone working on it, I've also seen it on a couple devices, and I'm open to providing feedback, or helping test a fix.

**Comment by ggruen** [comment]
Also occurring on iPadOS 16.1.1 on an "iPad Pro (12.9-inch) (3rd generation)". I'll test on 16.2 and update if it happens to go away there. 
![IMG_5B8080194A82-1](https://user-images.githubusercontent.com/5510793/211924333-a7523189-730c-437f-8d3c-346765a8dd43.jpeg)
I happen to be an iOS/iPadOS/macOS developer with a wife in seminary, so I may dig into this if I get a chance. Don't wait for me though. :)

**Comment by DylanCross** [comment]
@sgschantz Shawn, is someone responsible for this bug, or is it possible to get someone assigned to it? I'd try to help some eventually, but I have no experience with keyman's codebase.

**Comment by mcdurdin** [comment]
See also:
* https://community.software.sil.org/t/hebrew-sil-keyboard-has-some-invisible-characters-on-ios-16-3-1-obu/7273/8
* https://github.com/keymanapp/keyboards/issues/2172

**Comment by sgschantz** [comment]
This is a duplicate of [ #2172](https://github.com/keymanapp/keyboards/issues/2172) so we will continue to track the issue there. The issue appeared due to a change in how the font is rendered by iOS. A way to work around this limitation is to create a new font and package it with the keyboard. This would not be a change to Keyman but a change to the keyboard, so it is more appropriate to track the issue in the keyboard repository. 

@DylanCross please read [ #2172](https://github.com/keymanapp/keyboards/issues/2172) for more information. The solution requires a font designer, and we currently don't have anyone available to work on one but are continuing to discuss internally how we would be able to address this.
