### ISSUE TITLE
test(common): Desktop app compatibility tests - Slatejs

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#7938]
The basic idea is to load the example page for each Text Editor (in this case, Slatejs), and then test input with latest release version of Keyman apps and a variety of keyboards.

# Gather Assets for Testing
Install the following keyboards and have the test page link ready to load on the respective browser.
* Keyman app - Latest version
* Khmer Angkor keyboard [package](https://keyman.com/go/package/download/khmer_angkor?version=1.3&tier=stable)
* EuroLatin (SIL) keyboard [pagekage](https://keyman.com/go/package/download/sil_euro_latin?version=2.0&tier=stable)
* Galaxie Hebrew (Positional) keyboard [package](https://keyman.com/go/package/download/galaxie_hebrew_positional?version=2.2&tier=stable)
* IPA (SIL) keyboard [package](https://keyman.com/go/package/download/sil_ipa?version=1.8.6&tier=stable)
* Korean KORDA Jamo (SIL) keyboard [package](https://keyman.com/go/package/download/sil_korda_jamo?version=3.0&tier=stable&bcp47=ko)
* Slatejs text editor test [page](https://www.slatejs.org/examples/richtext): type in the text area to test
<img src="https://user-images.githubusercontent.com/28331388/208841241-7574473d-7559-4992-a737-fd616d997e6c.png" width="400">

We need to test in a variety of Operating Systems and Browsers:
* GROUP_WIN10_CHROME: Windows 10 / Chrome browser
* GROUP_WIN10_FIREFOX: Windows 10 / Firefox browser
* GROUP_MACOS_CHROME: macOS / Chrome browser
* GROUP_MACOS_FIREFOX: macOS / Firefox browser
* GROUP_MACOS_SAFARI: macOS / Safari browser
* GROUP_UBUNTU_CHROME: Ubuntu / Chrome browser 
* GROUP_UBUNTU_FIREFOX: Ubuntu / Firefox browser

# User Testing
Slatejs has an example page: https://www.slatejs.org/examples/richtext. Load it up on the respective OS and browser to test the followings:
   * TEST_KHMER_ANGKOR: Khmer Angkor
      * Ensure the key combination <kbd>AltGr</kbd> <kbd>B</kbd> produces `ឞ`. Note that on macOS, the function key to use is right `option`.
      * Type the following (US) keys in sequence: <kbd>s</kbd> <kbd>u</kbd> <kbd>j</kbd> <kbd>r</kbd> <kbd>k</kbd>. You should see `ស្រុក`.
   * TEST_SIL_EURO_LATIN: SIL Euro Latin
      * Type <kbd>%</kbd> <kbd>a</kbd>. Ensure the output is `ǎ`
   * TEST_GALAXIE_HEBREW: Galaxie Hebrew or another good SIL RTL keyboard
      * Type <kbd>b</kbd> <kbd>\\</kbd> <kbd>=</kbd> <kbd>r</kbd> <kbd>@</kbd> <kbd>a</kbd> <kbd>v</kbd> <kbd>!</kbd> <kbd>y</kbd> <kbd>t</kbd> to output `בְּרֵאשִׁית`. FAILED if the output is different.
   * TEST_SIL_IPA: sil_ipa
      * Ensure the key sequence <kbd>n</kbd> <kbd>></kbd> produces `ŋ`.
   * TEST_INTERACTION_WITH_TEXT_FORMATTING:
      * when a Keyman keyboard is active and you are able to enable bold by using the keyboard shortcut (i.e. <kbd>Ctrl</kbd> + <kbd>b</kbd>).
      * PASSED if the bold is enabled on the first character and the rest of the text being typed, otherwise FAILED.
      * _Note that on macOS, the keyboard shortcut for Bold is `command`+`b`._
   * TEST_CJK_IMX: Korean KORDA Jamo (SIL)
      * Type <kbd>h</kbd> <kbd>a</kbd> <kbd>n</kbd> `<space>` <kbd>g</kbd> <kbd>e</kbd> <kbd>u</kbd> <kbd>l</kbd> `<space>`. Verify that the result is `한글`.

**Comment by bharanidharanj** [comment]
# Test Results

### GROUP_WIN10_CHROME: Windows 10 / Chrome browser

* **TEST_KHMER_ANGKOR (FAILED):** Tested with Keyman 17.0.20-alpha and typing s u j r k showing the wrong output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/208936397-331a69d4-0fe3-48a4-9313-91a47aa9edec.PNG">

   <img width="300" src="https://user-images.githubusercontent.com/19683143/208936412-ab73964f-6919-4112-a21a-75e95153e93b.PNG">


* **TEST_SIL_EURO_LATIN (PASSED):** It is showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/208936592-8ecaf00c-4dde-4e51-91a4-00a21661c265.PNG">


* **TEST_GALAXIE_HEBREW (PASSED):** It is showing the expected output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/208936634-ec1e1112-6b6a-44ba-b189-558bdcec1eff.PNG">

**Comment by bharanidharanj** [comment]
### GROUP_WIN10_CHROME: Windows 10 / Chrome browser

* **TEST_SIL_IPA (PASSED):** Tested with the latest Keyman 17.0.21-alpha build in Windows 10 OS and it is showing the correct output.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/209074377-69cd6d50-d8cd-4e2c-9f00-78d68b8dab80.PNG">


* **TEST_INTERACTION_WITH_TEXT_FORMATTING (PASSED):** Ctrl + B key combination change the font style into Bold. Seems to be working fine.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/209074413-110b4fb9-a8dc-45e4-9d0e-c7254336f767.PNG">


* **TEST_CJK_IMX (FAILED):** Installed Korean KORDA Jamo (SIL) Keyboard. Typing h a n <space> g e u l produces wrong output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/209074435-0d61ca7a-ba5f-4e6d-857c-82dd52049efa.PNG">

**Comment by bharanidharanj** [comment]
# Test Results

### GROUP_WIN10_FIREFOX: Windows 10 / Firefox browser

* **TEST_KHMER_ANGKOR (PASSED):** Tested with Keyman 17.0.21-alpha and it is showing the correct output. 

   <img width="300" src ="https://user-images.githubusercontent.com/19683143/209093544-07068ad8-43a0-4ea5-a731-5e5d9454f8e5.PNG">

   <img width="300" src="https://user-images.githubusercontent.com/19683143/209093592-acae033d-4fd8-4ff7-ad08-bfcf14cc231c.PNG">


* **TEST_SIL_EURO_LATIN (FAILED):** It is showing the wrong output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/209093696-15cc3538-745b-4ca9-a7f0-e2a7d91731c6.PNG">


* **TEST_GALAXIE_HEBREW (PASSED):** It is showing the expected output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/209094196-a6d51210-3cdc-45ac-abe0-ec64baf30b0b.PNG">


* **TEST_SIL_IPA (FAILED):** It is showing the wrong output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/209094388-8031aba3-8fdb-4176-8f7d-59dd7aa24b6a.PNG">


* **TEST_INTERACTION_WITH_TEXT_FORMATTING (PASSED):** It is showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/209098693-d409a883-7d15-4eb2-82e3-c6b377b2a8fb.PNG">


* **TEST_CJK_IMX (FAILED):** It is showing the wrong output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/209098805-7011a9ad-ca49-496d-84be-51f97f88f368.PNG">

**Comment by bharanidharanj** [comment]
### GROUP_UBUNTU_CHROME: Ubuntu / Chrome browser 

* **TEST_KHMER_ANGKOR (FAILED):** Tested with Keyman 17.0.21-alpha and it is showing the wrong output.

    <img width="300" src="https://user-images.githubusercontent.com/19683143/209134583-1bc29cc5-8024-4f2f-b1a0-e1ec40bc9f23.PNG">


* **TEST_SIL_EURO_LATIN (FAILED):** It is showing the wrong output.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/209132289-155fd29b-ca43-4a56-82d9-8f182f6c5e19.PNG">

* **TEST_GALAXIE_HEBREW (PASSED):** It is showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/209132359-e3f60db7-44e7-409d-b1db-acc4c5d118dd.PNG">

* **TEST_SIL_IPA (PASSED):** It is showing the correct output.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/209134047-bb43f546-467e-469d-8602-4aab2be32031.PNG">


* **TEST_INTERACTION_WITH_TEXT_FORMATTING (PASSED):** It is showing the correct output. 

<img width="300" src="https://user-images.githubusercontent.com/19683143/209134100-128ab156-b22c-4a78-8066-04fb08e88cf4.PNG">


* **TEST_CJK_IMX (PASSED):** It is showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/209132176-7ed03b11-231e-45cf-9a69-87e6727d94ff.PNG">


### GROUP_UBUNTU_FIREFOX: Ubuntu / Firefox browser

* **TEST_KHMER_ANGKOR (FAILED):** It is showing the wrong output.

     <img width="300" src="https://user-images.githubusercontent.com/19683143/209136990-f60370f0-84f6-4ce7-a52c-9b519494dd25.PNG">


* **TEST_SIL_EURO_LATIN (PASSED):** It is showing the expected output. 
   
   <img width="300" src="https://user-images.githubusercontent.com/19683143/209135075-fde505b5-8b12-4119-9500-8d03e0834909.PNG">


* **TEST_GALAXIE_HEBREW (PASSED):** It is showing the correct ouput. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/209135108-9015d38c-c5b1-4d78-9e49-c3aaef8422f0.PNG">


* **TEST_SIL_IPA (PASSED):** It is showing the expected output.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/209135143-9270054e-1221-478d-a0b0-2941505f70ba.PNG">


* **TEST_INTERACTION_WITH_TEXT_FORMATTING (PASSED):** It is showing the expected output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/209135175-34d16441-e899-4bf1-9c24-8a66ad25b50b.PNG">

* **TEST_CJK_IMX (FAILED):** It is showing the wrong output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/209135422-dfbbe3ad-507b-4a07-b863-f33e0353a3f9.PNG">

**Comment by bharanidharanj** [comment]
# Test Results

### GROUP_MACOS_CHROME: macOS / Chrome browser

* **TEST_KHMER_ANGKOR (FAILED):** Tested with Keyman 17.0.21-alpha and it is showing the wrong output.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/209143607-2f6b5cfc-54de-47cc-af0b-f3de9e2c25f6.png">

* **TEST_SIL_EURO_LATIN (PASSED):** It is showing the correct output.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/209143640-fb418d1b-3f22-4b26-90e1-af0cbf5e0639.png">


* **TEST_GALAXIE_HEBREW (PASSED):** It is showing the expected output.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/209143678-fc1fb926-3c04-4e34-b4ac-f9104a1b29ef.png">

* **TEST_SIL_IPA (PASSED):** It is showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/209143710-5ed6897f-cce2-496d-af02-75321a270de3.png">


* **TEST_INTERACTION_WITH_TEXT_FORMATTING (PASSED):** It is showing the expected output. 

<img width="300" src="https://user-images.githubusercontent.com/19683143/209143769-e1fc32cb-ee1d-4089-9fc8-6617bcdeb588.png">


* **TEST_CJK_IMX (FAILED):** It is showing the wrong output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/209143826-4364f7d4-35dc-4486-b11d-e75982f6031b.png">

**Comment by bharanidharanj** [comment]
### GROUP_MACOS_SAFARI: macOS / Safari browser

* **TEST_KHMER_ANGKOR (PASSED):** Tested with Keyman 17.0.21-alpha and it is showing the wrong output.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/209150234-d432de62-9a78-41b0-9b6b-0aedf456430c.png">

   <img width="300" src="https://user-images.githubusercontent.com/19683143/209150260-3873b1ca-91fd-4cab-a79b-129060eaf7c4.png">


* **TEST_SIL_EURO_LATIN (PASSED):** It is showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/209150305-c2d56951-da87-499c-b055-3a5f3b62768d.png">


* **TEST_GALAXIE_HEBREW (PASSED):** It is showing the expected output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/209150338-22ed4e12-e3e4-4159-974d-47fd96a52956.png">


* **TEST_SIL_IPA (PASSED):** It is showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/209150360-083e142e-ca89-4731-9af4-1c2db59979f4.png">


* **TEST_INTERACTION_WITH_TEXT_FORMATTING (PASSED):** It is showing the expected output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/209151102-457ff6b6-387f-44de-9a7e-9ff24b0f62c9.png">


* **TEST_CJK_IMX (FAILED):** It is showing the wrong output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/209151143-e40af860-907a-426f-8e0f-ac02130e4269.png">

**Comment by bharanidharanj** [comment]
# Test Results

### GROUP_MACOS_FIREFOX: macOS / Firefox browser

* **TEST_KHMER_ANGKOR (FAILED):** Tested with Keyman 17.0.21-alpha and it is showing the wrong output.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/209159854-b0322d67-af1c-4bcd-9591-dee7197f950b.png">


* **TEST_SIL_EURO_LATIN (PASSED):** It is showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/209159888-25d6d02e-4283-4bde-bbf0-f34f18be6b5f.png">


* **TEST_GALAXIE_HEBREW (PASSED):** It is showing the expected output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/209159973-4f89c3d7-1c21-4afe-9bf0-ede1585d5aa1.png">


* **TEST_SIL_IPA (PASSED):** It is showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/209160012-a9ac9150-7a88-45ce-98ad-3384251d381d.png">


* **TEST_INTERACTION_WITH_TEXT_FORMATTING (PASSED):** It is showing the expected output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/209160037-fb527782-2399-4ec4-bb91-067a14b52054.png">


* **TEST_CJK_IMX (FAILED):** It is showing the wrong output.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/209160085-bdda483b-f350-4c0c-98fd-406928eebc0a.png">

**Comment by MakaraSok** [comment]
## Verification tests

* GROUP_WIN10_CHROME: [THE SAME RESULTS AS ABOVE] 👍 
![image](https://user-images.githubusercontent.com/28331388/221505945-4d43c3e9-ba09-497a-b736-fd0420949ad9.png)

* GROUP_WIN10_FIREFOX: [SOME RESULTS ARE NOT THE SAME AS ABOVE] 👎 
  * KHMER ANKOR keyboard doesn't output the expected string, hence FAILED, not PASSED. The rest is the same as above.
![image](https://user-images.githubusercontent.com/28331388/221509146-dc0b3d13-a777-4ba2-8bb0-7c52d28bc580.png)

  * Backspacing multiple times cause an error - the sequence led to this is - return > backspace > backspace > backspace (backspaces on the same line doesn't cause this error):
     ![image](https://user-images.githubusercontent.com/28331388/221507195-293e5f54-54f9-4fd5-9f00-574927dfa571.png)

_(Firefox 110.0 (64-bit) on Windows 10 Pro 21H2)_

* GROUP_MACOS_CHROME:  [THE SAME RESULTS AS ABOVE] 👍 
<img width="960" alt="image" src="https://user-images.githubusercontent.com/28331388/221524033-55abc15f-7649-44e3-8ca1-f47b25e7ecef.png">

## TBD

**Comment by MakaraSok** [comment]
@keymanapp-test-bot retest GROUP_WIN10_FIREFOX TEST_KHMER_ANGKOR GROUP_UBUNTU_CHROME TEST_SIL_IPA  TEST_CJK_IMX GROUP_UBUNTU_FIREFOX TEST_SIL_EURO_LATIN TEST_SIL_IPA

**Comment by bharanidharanj** [comment]
### GROUP_WIN10_FIREFOX: Windows 10 / Firefox browser

* **TEST_KHMER_ANGKOR (FAILED):** Retested with the latest Keyman 17.0.61-alpha build in Windows 10 / Firefox browser and here is my observation: 1. Pressing AltGr+B produces ឞ. However, typing s u j r k produces wrong output. 

Output 1:

   <img width="300" src="https://user-images.githubusercontent.com/19683143/223429353-f94f58a2-98b2-4e47-b2cd-be2dfcf3c8ee.PNG">

Output 2:

   <img width="300" src="https://user-images.githubusercontent.com/19683143/223429411-70dfdde7-8052-42a2-ad1c-5a2d520c5615.PNG">

**Comment by bharanidharanj** [comment]
# Test Results

### GROUP_UBUNTU_CHROME: Ubuntu / Chrome browser 

* **TEST_SIL_IPA (PASSED):** Retested with Keyman 17.0.61-alpha build and it is showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/223434336-ea30ab0a-3eba-44fb-8e4a-fb705fe8474d.PNG">


* **TEST_CJK_IMX (FAILED):** Retested this as per the instructions and it is showing the wrong output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/223434383-4a979aef-6483-4571-bd36-bb3aa2cb6e5f.PNG">


### GROUP_UBUNTU_FIREFOX: Ubuntu / Firefox browser

* **TEST_SIL_EURO_LATIN (FAILED):** Retested with Keyman 17.0.61-alpha build and noticed that it is showing the wrong output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/223434435-eb3941ff-9bc7-4d35-a169-fdc69666e439.PNG">

* **TEST_SIL_IPA (PASSED):** Retested and and it is showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/223434478-f22c1ab6-5c26-44f1-8ccc-30ba48ceab3a.PNG">
