### ISSUE TITLE
bug(web): spacebar text sometimes overly small without good reason

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#7940]
### Describe the bug

See repro + screenshot below.

### Reproduce the bug

1. Go to the "Prediction - robust testing" test page in Chrome.
2. Launch developer mode and set it to emulate an iPhone SE.
3. Set the emulation scale to better match the relative size to a physical handheld iPhone SE.

Note how the spacebar text becomes near-unreadably small; something's off with the settings there.

![image](https://user-images.githubusercontent.com/25213402/208859595-119bdfe0-3599-4678-9d0c-4f857852bc5f.png)

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

**Comment by MakaraSok** [comment]
Keyman 16.0.123-beta
Android 10
The spacebar caption is too small to read.
<img width=400 src="https://user-images.githubusercontent.com/28331388/208860952-636bfed6-763b-4302-9c05-62361ab28fb1.png">
