### ISSUE TITLE
chore(common): Request Kannada localization

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#7952]
### Describe the bug

Kannada localization is completed in crowdin.

Please pull it into all apps. I would like to test it.

### Keyman apps

- [x] Keyman for Android
- [x] Keyman for iPhone and iPad
- [x] Keyman for Linux
- [x] Keyman for macOS
- [x] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Language name

Kannada

**Comment by MayuraVerma** [comment]
Please pull this in both v16 n 17

**Comment by darcywong00** [comment]
> Please pull this in both v16 n 17

The PRs are currently in review, so hopefully it will be available in the 16.0-beta and 17.0 alpha builds later this week...
