### ISSUE TITLE
bug(android): No new feautres (?) added under What's New Help topic in Keyman 17.0 alpha build

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#7957]
### Describe the bug

It seems that I did not find any feature list or bug fixes that are added under the What's New Help topic in Keyman 17.0 alpha build. 

### Reproduce the bug

1. Install Keyman 17.0.20-alpha build in Android Mobile. 
2. Launch Keyman App. 
3. Click 'More Info' option from Get Started menu.
4. Verify it opens Keyman for Android 17.0 Help page. 
5. Click 'What's New' link. 
6. Verify it opens the 'What's New' Help page. 
Here, I noticed that no new features (?) or bug fixes has been added under this Help topic. 

FYI, I was able to reproduce this in iOS version too. 

..in Android 5.0 emulator

   <img width="300" src="https://user-images.githubusercontent.com/19683143/210061639-30384de0-a829-4290-8a14-220c18849edf.PNG">

..in iOS 15.0 / iPhone 12 Pro Max Simulator  

   <img width="300" src="https://user-images.githubusercontent.com/19683143/210061722-68635927-c938-406b-a8bf-bc96cf3bd64f.png">

### Expected behavior

It should show some message (about upcoming features (?)) under What's New Help topic. 

### Keyman apps

- [x] Keyman for Android
- [x] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.20-alpha

### Operating system

Android 5.0, iOS 15.0, Android 11.0

### Device

iPhone 12 Pro Max Simulator, APK 21 Emulator, Andorid Mobile device

### Target application

Keyman In

**Comment by darcywong00** [comment]
The whatsnew is blank because we've only just started 17.0 development. We'll likely update the corresponding content when we get close to 17.0 beta (or when a major 17.0 feature gets added)

**Comment by bharanidharanj** [comment]
> The whatsnew is blank because we've only just started 17.0 development. We'll likely update the corresponding content when we get close to 17.0 beta (or when a major 17.0 feature gets added)

@darcywong00 Okay. I just wanted to bring it to your attention, Thanks.
