### ISSUE TITLE
bug(android): Key Preview is missing for English(Runic) Keyboard in Android Tablet 

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#7961]
### Describe the bug

I noticed that long pressing any key in English (Runic) Keyboard did not show up the Key preview while using a Tablet Emulator. (or device). 

### Reproduce the bug

1. Install Keyman 17.0.20 build in an Android 11.0 Tablet.
2. Open Keyman App.
3. Click the Settings button from the top right corner of the Keyman tool bar. 
4. Install English (Runic) Keyboard from the Settings dialog. 
5. In the Keyman App, Set the default English EuroLatin(SIL) keyboard. 
6. Long press any key (for example, long press letter 'A') from the keyboard. 
7. Verify that the Subkey menu appears on the top of the key. 
8. Change the Keyboard to English (Runic) Keyboard. 
9. Long press any key. 
10. Here, I noticed that the Key preview did not appear on the top of the corresponding key. 

Note: The Key preview appears in Android Mobile Emulator (or device). I have attached the Screenshot as well as the Video file for reference. 

..Subkey menu appears in the default keyboard

   <img width="300" src="https://user-images.githubusercontent.com/19683143/210246231-76d894ab-de3f-43d2-b039-bf45e4b009ed.png">

..Key Preview is missing in the English (Runic) Keyboard

   <img width="300" src="https://user-images.githubusercontent.com/19683143/210246245-a9e6e5e7-d19f-48bf-8d08-822e664adce1.png">

..Missing KeyPreivew in Android Tablet 

https://user-images.githubusercontent.com/19683143/210246263-4dec0fb5-3518-4de7-857f-a027bf3eeb7f.mp4

### Expected behavior

The Key preview should appear on the top of the corresponding key in Android Tablet (Emulator or Device). 

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.020 alpha 

### Operating system

Android 11.0

### Device

Android Tablet Emulator (API 30)

### Target application

Keyman In-App

### Keyboard name

English (Runic)

### Keyboard version

1.1

### Language name

Runes

**Comment by darcywong00** [comment]
The source of the keyboad touch layout for sil_euro_latin contains subkeys/popup key options (in the `sk` array)
For example
https://github.com/keymanapp/keyboards/blob/19acf0ff9787bc810c23cf01314722ff5d1fa831/release/sil/sil_euro_latin/source/sil_euro_latin.keyman-touch-layout#L21-L45

The experimental runeboard does not contain popup keys.
https://github.com/keymanapp/keyboards/blob/master/experimental/r/runeboard/source/runeboard.keyman-touch-layout

I believe on tablet layouts, if there's no popup keys, there's intentionally no key previews.
You can see this on sil_euro_latin

https://keymanweb.com/#en,Keyboard_sil_euro_latin in a tablet viewport --> 
Go to symbol layer and longpress underscore <kbd>_</kbd> key

No popup visible
![tablet key](https://user-images.githubusercontent.com/7358010/210307872-acb6c489-ad9a-4de1-ace0-faecdaec1118.png)

**Comment by bharanidharanj** [comment]
@darcywong00 FYI, I was able to see the Key Preview in Android (Ver 11.0) Mobile Emulator. 

..Key Preview in Android Mobile Emulator

   <img width="300" src="https://user-images.githubusercontent.com/19683143/210310091-b21dba64-06c6-407f-9f8c-0a6e46d49294.png">

**Comment by darcywong00** [comment]
That's a phone layout. Your reported issue was tablet formfactor.

**Comment by bharanidharanj** [comment]
> That's a phone layout. Your reported issue was tablet formfactor.

Yes, That's right. I Just wanted to add the  Screenshot to compare the Phone layout vs the tablet layout. Thanks.

**Comment by darcywong00** [comment]
Per A17S4 sprint plan discussion, this is an intentional design for key previews on tablet to **not** display if the base key is the only option (longpress keys available)
