### ISSUE TITLE
chore(common): ldml some tests are failing  🙀

### ISSUE THREAD

**Issue by srl295** [keymanapp/keyman#7967]
```shell
$ cd common/web/types
$ ./build.sh build
$ ./build.sh test
…
failures:

  ldml keyboard xml reader tests
    1) should fail to load files that don't conform to DTD
    2) should fail to load files with an invalid conformsTo
```

looks like these aren't run by CI?

#7042

**Comment by srl295** [comment]
note #7953  for another build.sh issue

**Comment by srl295** [comment]
@mcdurdin which build step should common/web/types be run from? if any?

**Comment by mcdurdin** [comment]
> @mcdurdin which build step should common/web/types be run from? if any?

I think we need to run this as part of the tests for the KeymanWeb build. I am hesitant to do this right now because those scripts are all being refactored by @jahorton, and making changes elsewhere will cause merge pain. Can we make this an issue to address once @jahorton's big 📜 [PR chain](https://github.com/keymanapp/keyman/pull/7474) is merged?

**Comment by srl295** [comment]
- [ ] Make sure @mcdurdin has a ticket for adding this to CI and close this one

**Comment by srl295** [comment]
The tests actually are broken again.. this time it's the kvks round tripper.

**Comment by srl295** [comment]
if only there were a way to automate…

**Comment by jahorton** [comment]
> > @mcdurdin which build step should common/web/types be run from? if any?
> 
> I think we need to run this as part of the tests for the KeymanWeb build. I am hesitant to do this right now because those scripts are all being refactored by @jahorton, and making changes elsewhere will cause merge pain. Can we make this an issue to address once @jahorton's big 📜 [PR chain](https://github.com/keymanapp/keyman/pull/7474) is merged?

My advice is to add this to the `./ci.sh test` script + action added within #7831.

The 📜 chain will be merging shortly, so the file will likely be in place on `master` by the time you see this.

**Comment by mcdurdin** [comment]
Works for me, until we get a separate 'common' test build configuration.
