### ISSUE TITLE
bug(windows): Add/remove Language doesn't work on a keyboard with spaces in filename

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#7968]
### Describe the bug

Install Heidelberg Input Solution package from Keyman Configuration, and then click Add/remove language for any of its keyboards. In this situation, the button doesn't work.

### Expected behavior

The button should open the dialog yeah?

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [X] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16.0.128-beta (tested on 17.0.15-alpha)

### Operating system

Windows

### Keyboard name

The Heidelberg Input Solution package, any keyboards within that package.

**Comment by mcdurdin** [comment]
Yep, I discovered the issue was related to spaces in filenames, not what I originally thought; so still a problem for legacy keyboards but maybe not quite as urgent.

**Comment by rc-swag** [comment]
Tested this against 17.0.49 and it is no longer an issue.
