### ISSUE TITLE
bug(android): Blue Support tab is missing at the bottom of the (Tamil) Help Page.

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#7973]
### Describe the bug

Further continuing with the same Tamil Help page, I noticed that there is a message "use the blue Support tab at the bottom of this page to tell us about this problem" appears under the 'Page not found' heading. But, there is no blue Support tab at the bottom of the page. 

### Reproduce the bug

1. Install Keyman 15.0.274 build from Google Play Store. 
2. Install Tamil Keyboard (ekwtamil99uni). 
3. Open the Tamil Help page. 
4. Click 'Further Resources' link. 
5. Click any one of the Tamil Keyboard layout link. 

Here, I noticed that it opens another page with an error message 'Page not found'. I tried to use the blue Support tab at the bottom of this page to send this problem, but it was missing. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/210387466-ccfed838-195f-4e6c-b53d-761610e9e1be.jpg">

### Expected behavior

There should be a Blue Support tab at the bottom of the page. 

### Related issues

 bug(android): Page not found message appears after clicking on any Tamil Keyboard Layouts #7972

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

15.0.274

### Operating system

Android 11.0

### Device

Redmi Note 8 Pro

### Target application

Keyman App

### Keyboard name

Tamil99

### Keyboard version

2.0.3

### Language name

Tamil

**Comment by darcywong00** [comment]
This sounds similar to help.keyman.com#113 where the blue "Edit page" tab doesn't appear on Android devices.

I'll close this issue and we'll track it on the help.keyman.com issue
