### ISSUE TITLE
test(common): Mobile app compatibility tests - Lexical text editor

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#7977]
The basic idea is to load the example page for each Text Editor (in this case, Lexical), and then test input with latest release version of Keyman apps and a variety of keyboards.

# Gather Assets for Testing
Install the following keyboards and have the test page link ready to load on the respective browser.
* Keyman app - Latest version (please record the version in the test results)
* Khmer Angkor keyboard [package](https://keyman.com/go/package/download/khmer_angkor?version=1.3&tier=stable)
* EuroLatin (SIL) keyboard [pagekage](https://keyman.com/go/package/download/sil_euro_latin?version=2.0&tier=stable)
* Galaxie Hebrew (Positional) keyboard [package](https://keyman.com/go/package/download/galaxie_hebrew_positional?version=2.2&tier=stable)
* IPA (SIL) keyboard [package](https://keyman.com/go/package/download/sil_ipa?version=1.8.6&tier=stable)
* Korean KORDA Jamo (SIL) keyboard [package](https://keyman.com/go/package/download/sil_korda_jamo?version=3.0&tier=stable&bcp47=ko)
* Lexical text editor test [page](https://playground.lexical.dev/): type in the text area to test
<img src="https://user-images.githubusercontent.com/28331388/208840493-e852ac36-ce19-4cd0-a30e-f51fa310d8fd.png" width="400">

We need to test in a variety of Operating Systems and Browsers:
* GROUP_IOS_SAFARI: iOS / Safari browser
* GROUP_IOS_CHROME: iOS / Chrome browser
* GROUP_ANDROID_CHROME: Android / Chrome browser
* GROUP_ANDROID_FIREFOX: Android / Firefox

# User Testing
Lexical text editor has a playground: https://playground.lexical.dev/. Load it up on the respective OS and browser to test the followings:
   * TEST_KHMER_ANGKOR: Khmer Angkor
      * Ensure longpress on <kbd>ស</kbd> and choose <kbd>ឞ</kbd> to produce `ឞ`.
      * Type <kbd>ស</kbd> <kbd>ុ</kbd> <kbd>្រ</kbd> (longpress of <kbd>រ</kbd>) <kbd>ក</kbd> to produce `ស្រុក`.
   * TEST_SIL_EURO_LATIN: SIL Euro Latin
      * Longpress on <kbd>a</kbd> and choose <kbd>ǎ</kbd> to output `ǎ`
   * TEST_GALAXIE_HEBREW: Galaxie Hebrew or another good SIL RTL keyboard
      * Type <kbd>b</kbd> <kbd>\\</kbd> <kbd>=</kbd> <kbd>r</kbd> <kbd>@</kbd> <kbd>a</kbd> <kbd>v</kbd> <kbd>!</kbd> <kbd>y</kbd> <kbd>t</kbd> to output `בְּרֵאשִׁית`. FAILED if the output is different.
   * TEST_SIL_IPA: sil_ipa
      * Ensure the key sequence <kbd>n</kbd> <kbd>></kbd> (long press of <kbd>]</kbd> on `123` layer) produces `ŋ`.

**Comment by bharanidharanj** [comment]
### GROUP_ANDROID_FIREFOX: Android / Firefox

* **TEST_KHMER_ANGKOR (PASSED):** Tested in Lexical text editor with Keyman 17.0.23-alpha build and it is showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/210787932-782fc3a9-7fdc-4e5c-aebd-e640ff826e16.PNG">

* **TEST_SIL_EURO_LATIN (PASSED):** It is showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/210787956-b871ec25-1ff3-4c84-aed5-716d1dbbd5d3.PNG">

* **TEST_GALAXIE_HEBREW (PASSED):** It is showing the expected output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/210787979-8e425aa8-9b92-433e-b8d9-23502ba35fa2.PNG">


* **TEST_SIL_IPA (PASSED):** It is showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/210788007-5308c480-38e1-4581-ae94-ef53a57d9421.PNG">

**Comment by bharanidharanj** [comment]
# Test Results

### GROUP_IOS_SAFARI: iOS / Safari browser

* **TEST_KHMER_ANGKOR (PASSED):** Tested in Lexical text editor and it showing the correct output. 
      
   <img width="300" src="https://user-images.githubusercontent.com/19683143/210804498-27c19a9a-4134-4282-a6be-81ad40bafce5.png">


* **TEST_SIL_EURO_LATIN (PASSED):** It is showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/210803854-6dceca50-0561-4788-9aa8-2422b6028ed4.png">


* **TEST_GALAXIE_HEBREW (FAILED):** It is showing wrong output. It would be better to write some other steps to show the expected output.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/210803876-107b7796-778f-483a-a93d-22bca203caf4.png">

* **TEST_SIL_IPA (PASSED):** It is showing the correct output. 
   
<img width="300" src="https://user-images.githubusercontent.com/19683143/210803893-2902c280-b08a-423b-90cf-927f99d6c248.png">

**Comment by bharanidharanj** [comment]
### GROUP_ANDROID_CHROME: Android / Chrome browser

* **TEST_KHMER_ANGKOR (PASSED):** Tested with Keyman 17.0.23 alpha build in Lexical text editor and it showing the correct output. 

  
   <img width="300" src="https://user-images.githubusercontent.com/19683143/210956141-be92ef02-585f-4f87-bb85-c8eddd03775f.PNG">


* **TEST_SIL_EURO_LATIN (PASSED):** It is showing the correct output. 

 
   <img width="300" src="https://user-images.githubusercontent.com/19683143/210956159-87d4effa-ef49-4c1f-8a3c-f12047cf3180.PNG">


* **TEST_GALAXIE_HEBREW (PASSED):** It is showing the expected output. 

   
   <img width="300" src="https://user-images.githubusercontent.com/19683143/210956166-ad076b98-c57f-4367-a892-7cee2707f34e.PNG">


* **TEST_SIL_IPA (PASSED):** It is showing the correct output. 

 
   <img width="300" src="https://user-images.githubusercontent.com/19683143/210956183-7838dc23-f05a-4102-9dcc-1fbd3790d540.PNG">

**Comment by bharanidharanj** [comment]
# Test Results

### GROUP_IOS_CHROME: iOS / Chrome browser

* **TEST_KHMER_ANGKOR (BLOCKED):** iOS Simulator does not support Chrome browser. 
* **TEST_SIL_EURO_LATIN (BLOCKED):** iOS Simulator does not support Chrome browser. 
* **TEST_GALAXIE_HEBREW (BLOCKED):** iOS Simulator does not support Chrome browser. 
* **TEST_SIL_IPA (BLOCKED):** iOS Simulator does not support Chrome browser.

**Comment by MakaraSok** [comment]
@keymanapp-test-bot retest GROUP_IOS_CHROME TEST_KHMER_ANGKOR TEST_SIL_EURO_LATIN TEST_GALAXIE_HEBREW TEST_SIL_IPA

**Comment by MakaraSok** [comment]
@keymanapp-test-bot retest GROUP_IOS_SAFARI TEST_GALAXIE_HEBREW

@bharanidharanj could you retest this as well?

**Comment by MakaraSok** [comment]
LGTM
