### ISSUE TITLE
test(common): Mobile app compatibility tests - Prosemirror

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#7978]
The basic idea is to load the example page for each Text Editor (in this case, Prosemirror), and then test input with latest release version of Keyman apps and a variety of keyboards.

# Gather Assets for Testing
Install the following keyboards and have the test page link ready to load on the respective browser.
* Keyman app - Latest version (please record the version in the test results)
* Khmer Angkor keyboard [package](https://keyman.com/go/package/download/khmer_angkor?version=1.3&tier=stable)
* EuroLatin (SIL) keyboard [pagekage](https://keyman.com/go/package/download/sil_euro_latin?version=2.0&tier=stable)
* Galaxie Hebrew (Positional) keyboard [package](https://keyman.com/go/package/download/galaxie_hebrew_positional?version=2.2&tier=stable)
* IPA (SIL) keyboard [package](https://keyman.com/go/package/download/sil_ipa?version=1.8.6&tier=stable)
* Prosemirror test [page](https://prosemirror.net/.): type in the text area to test
<img src="https://user-images.githubusercontent.com/28331388/207572387-83a396ec-1dcc-45a2-975a-1389f31b682c.png" width="400">

We need to test in a variety of Operating Systems and Browsers:
* GROUP_IOS_SAFARI: iOS / Safari browser
* GROUP_IOS_CHROME: iOS / Chrome browser
* GROUP_ANDROID_CHROME: Android / Chrome browser
* GROUP_ANDROID_FIREFOX: Android / Firefox

# User Testing

Prosemirror have a test on their homepage: https://prosemirror.net/. Load it up on the respective OS and browser to test the followings:
   * TEST_KHMER_ANGKOR: Khmer Angkor
      * Ensure longpress on <kbd>ស</kbd> and choose <kbd>ឞ</kbd> to produce `ឞ`.
      * Type <kbd>ស</kbd> <kbd>ុ</kbd> <kbd>្រ</kbd> (longpress of <kbd>រ</kbd>) <kbd>ក</kbd> to produce `ស្រុក`.
   * TEST_SIL_EURO_LATIN: SIL Euro Latin
      * Longpress on <kbd>a</kbd> and choose <kbd>ǎ</kbd> to output `ǎ`
   * TEST_GALAXIE_HEBREW: Galaxie Hebrew or another good SIL RTL keyboard
      * Type <kbd>b</kbd> <kbd>\\</kbd> <kbd>=</kbd> <kbd>r</kbd> <kbd>@</kbd> <kbd>a</kbd> <kbd>v</kbd> <kbd>!</kbd> <kbd>y</kbd> <kbd>t</kbd> to output `בְּרֵאשִׁית`. FAILED if the output is different.
   * TEST_SIL_IPA: sil_ipa
      * Ensure the key sequence <kbd>n</kbd> <kbd>></kbd> (long press of <kbd>]</kbd> on `123` layer) produces `ŋ`.

**Comment by bharanidharanj** [comment]
# Test Results

### GROUP_IOS_SAFARI: iOS / Safari browser

* **TEST_KHMER_ANGKOR (PASSED):** Tested with Keyman 17.0.23-alpha build in Prosemirror and it showing the correct output.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/210723798-219056ae-58d5-4b75-b19b-4416bcf5055b.png">



* **TEST_SIL_EURO_LATIN (PASSED):** It is showing the correct output.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/210723825-e6237aca-57ac-47bb-a6d6-b654f20fee84.png">


* **TEST_GALAXIE_HEBREW (FAILED):** It is showing the wrong output. 

   
   <img width="300" src="https://user-images.githubusercontent.com/19683143/210724407-08152c73-b28f-4b77-8c32-ceac3fb22dd0.png">


* **TEST_SIL_IPA (PASSED):** It is showing the expected output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/210723863-5ed4633a-cb80-4df6-b640-36ba2d127b3a.png">

**Comment by bharanidharanj** [comment]
### GROUP_ANDROID_CHROME: Android / Chrome browser

* **TEST_KHMER_ANGKOR (PASSED):** Tested with Keyman 17.0.23-alpha build and it is showing the correct output. 
   
   <img width="300" src="https://user-images.githubusercontent.com/19683143/210760410-9d4bb553-8409-44f0-a12f-8030c95459f1.PNG">


* **TEST_SIL_EURO_LATIN (PASSED):** It is showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/210760432-2d12ff16-270b-4356-9186-a7a41d805b52.PNG">

* **TEST_GALAXIE_HEBREW (PASSED):** It is showing the expected output. 
   <img width="300" src="https://user-images.githubusercontent.com/19683143/210760460-af699afb-c11c-4899-9543-1746fbad5425.PNG">


* **TEST_SIL_IPA (PASSED):** It is showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/210760493-4b295870-f925-43cf-9bcd-9224830dc720.PNG">

**Comment by bharanidharanj** [comment]
### GROUP_ANDROID_FIREFOX: Android / Firefox

* **TEST_KHMER_ANGKOR (PASSED):** Tested in Prosemirror.net site and it is showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/210777667-8dae0ede-3faa-4345-af74-34cedfd1885f.PNG">

* **TEST_SIL_EURO_LATIN (PASSED):** It is showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/210777687-b8d3f8b1-f5c1-4040-bdb0-909c0729e87c.PNG">


* **TEST_GALAXIE_HEBREW (PASSED):** It is showing the expected output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/210777710-a7b57d6b-4463-43e0-9be5-dcae480aaf04.PNG">


* **TEST_SIL_IPA (PASSED):** It is showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/210777733-4d72b674-d52b-435f-9f9a-d53e346b1f39.PNG">

**Comment by bharanidharanj** [comment]
# Test Results

### GROUP_IOS_CHROME: iOS / Chrome browser

* **TEST_KHMER_ANGKOR (BLOCKED):** iOS Simulator does not support Google Chrome. 
* **TEST_SIL_EURO_LATIN (BLOCKED):** iOS Simulator does not support Google Chrome.
* **TEST_GALAXIE_HEBREW (BLOCKED):** iOS Simulator does not support Google Chrome.
* **TEST_SIL_IPA (BLOCKED):** iOS Simulator does not support Google Chrome.

**Comment by jahorton** [comment]
We'll probably have to either drop doing Chrome tests in the simulator or have one of us developers with a physical Apple device run the tests.  Since any browser on iOS is inherently Safari-based due to Apple's requirements, the Safari tests are _probably_ enough re iOS.

The failed test on Safari/iOS in regard to Hebrew is already noteworthy, so that's likely worth looking into.

**Comment by MakaraSok** [comment]
@keymanapp-test-bot retest GROUP_IOS_SAFARI TEST_GALAXIE_HEBREW GROUP_IOS_CHROME TEST_KHMER_ANGKOR TEST_SIL_EURO_LATIN TEST_GALAXIE_HEBREW TEST_SIL_IPA

**Comment by MakaraSok** [comment]
# Test Results
Tested on iPad mini 6 running iOS 16.3.1 

### GROUP_IOS_CHROME: iOS / Chrome browser version 111.0.5563.72

Click to enlarge:
<img width="300" src="https://user-images.githubusercontent.com/28331388/225868875-a33430c9-6b6b-4996-8415-297122a1feee.jpeg">

* **TEST_KHMER_ANGKOR (PASSED):** The expected output is shown.
* **TEST_SIL_EURO_LATIN (PASSED):** The expected output is shown.
* **TEST_GALAXIE_HEBREW (PASSED):** The expected output is shown.
* **TEST_SIL_IPA (PASSED):** The expected output is shown.

**Comment by MakaraSok** [comment]
@bharanidharanj Could you please retest the TEST_GALAXIE_HEBREW above as well?

**Comment by bharanidharanj** [comment]
# Test Results

### GROUP_IOS_SAFARI: iOS / Safari browser

* **TEST_GALAXIE_HEBREW (PASSED):** Tested with Keyman 17.0.72-alpha build in iPhone Simulator (iOS 16.2 / iPhone 14 Pro Max) and it is showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/226596337-bbc4d867-4865-4053-9859-e3327d807af9.png">

**Comment by MakaraSok** [comment]
LGTM
