### ISSUE TITLE
test(common): Mobile app compatibility tests - Slatejs

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#7979]
The basic idea is to load the example page for each Text Editor (in this case, Slatejs), and then test input with latest release version of Keyman apps and a variety of keyboards.

# Gather Assets for Testing
Install the following keyboards and have the test page link ready to load on the respective browser.
* Keyman app - Latest version (please record the version in the test results)
* Khmer Angkor keyboard [package](https://keyman.com/go/package/download/khmer_angkor?version=1.3&tier=stable)
* EuroLatin (SIL) keyboard [pagekage](https://keyman.com/go/package/download/sil_euro_latin?version=2.0&tier=stable)
* Galaxie Hebrew (Positional) keyboard [package](https://keyman.com/go/package/download/galaxie_hebrew_positional?version=2.2&tier=stable)
* IPA (SIL) keyboard [package](https://keyman.com/go/package/download/sil_ipa?version=1.8.6&tier=stable)
* Slatejs text editor test [page](https://www.slatejs.org/examples/richtext): type in the text area to test
<img src="https://user-images.githubusercontent.com/28331388/208841241-7574473d-7559-4992-a737-fd616d997e6c.png" width="400">

We need to test in a variety of Operating Systems and Browsers:
* GROUP_IOS_SAFARI: iOS / Safari browser
* GROUP_IOS_CHROME: iOS / Chrome browser
* GROUP_ANDROID_CHROME: Android / Chrome browser
* GROUP_ANDROID_FIREFOX: Android / Firefox

# User Testing
Slatejs has an example page: https://www.slatejs.org/examples/richtext. Load it up on the respective OS and browser to test the followings:
   * TEST_KHMER_ANGKOR: Khmer Angkor
      * Ensure longpress on <kbd>ស</kbd> and choose <kbd>ឞ</kbd> to produce `ឞ`.
      * Type <kbd>ស</kbd> <kbd>ុ</kbd> <kbd>្រ</kbd> (longpress of <kbd>រ</kbd>) <kbd>ក</kbd> to produce `ស្រុក`.
   * TEST_SIL_EURO_LATIN: SIL Euro Latin
      * Longpress on <kbd>a</kbd> and choose <kbd>ǎ</kbd> to output `ǎ`
   * TEST_GALAXIE_HEBREW: Galaxie Hebrew or another good SIL RTL keyboard
      * Type <kbd>b</kbd> <kbd>\\</kbd> <kbd>=</kbd> <kbd>r</kbd> <kbd>@</kbd> <kbd>a</kbd> <kbd>v</kbd> <kbd>!</kbd> <kbd>y</kbd> <kbd>t</kbd> to output `בְּרֵאשִׁית`. FAILED if the output is different.
   * TEST_SIL_IPA: sil_ipa
      * Ensure the key sequence <kbd>n</kbd> <kbd>></kbd> (long press of <kbd>]</kbd> on `123` layer) produces `ŋ`.

**Comment by bharanidharanj** [comment]
# Test Results

### GROUP_IOS_SAFARI: iOS / Safari browser

* **TEST_KHMER_ANGKOR (FAILED):** Tested with Keyman 17.0.23-alpha build in iOS 15.0 / iPhone 12 Pro Max Simulator and it is showing wrong output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/210547634-c94934ea-6607-4937-9797-23c1c8c60be2.png">


* **TEST_SIL_EURO_LATIN (PASSED):** It is showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/210547649-e897ca4d-e7ef-4881-9bfb-6b84dd983ec3.png">

* **TEST_GALAXIE_HEBREW (FAILED):** It is showing the wrong output. (If I type the letter 'b' it is showing the exact letter 'b' on the screen. It would be better to see right steps to produce the right output)
   <img width="300" src="https://user-images.githubusercontent.com/19683143/210547667-165ac54c-3f59-410a-a679-a75ebc6e3abb.png">


* **TEST_SIL_IPA (PASSED):** It is showing the expected output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/210547693-7f5430ab-148c-4d47-b8ac-fdd2f157fdcb.png">

**Comment by bharanidharanj** [comment]
### GROUP_ANDROID_CHROME: Android / Chrome browser

* **TEST_KHMER_ANGKOR (PASSED):** Tested with the latest Keyman 17.0.23-alpha build in API30 / Android 11 emulator and it showing the expected output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/210573948-6ee99400-99cd-4216-a76d-624c2d57441b.PNG">


* **TEST_SIL_EURO_LATIN (PASSED):** It is showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/210573989-cbbc5780-b702-4c9a-9fb1-7a52e7d78c16.PNG">


* **TEST_GALAXIE_HEBREW (PASSED):** It is showing the expected output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/210574030-0bc066d6-7d90-4a97-bf28-66f8c3732244.PNG">


* **TEST_SIL_IPA (PASSED):** It is showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/210574084-90c10d8e-16f2-4720-a2b8-7d1acd8c5e9b.PNG">

**Comment by bharanidharanj** [comment]
### GROUP_ANDROID_FIREFOX: Android / Firefox

* **TEST_KHMER_ANGKOR (OPEN):** Tested with Keyman 17.0.23-alpha build and it showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/210717272-ca5642d2-0039-45d2-bdf2-37f117a304f1.PNG">

* **TEST_SIL_EURO_LATIN (OPEN):** It is showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/210717305-235d40de-4cac-4b7c-8787-f6ccb66f226f.PNG">

* **TEST_GALAXIE_HEBREW (OPEN):** It is showing the expected output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/210717443-dca54e30-35d7-4aab-9bc3-aa2155bfa747.PNG">

* **TEST_SIL_IPA (OPEN):** It is showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/210717580-57263bb1-173e-48f3-b9e9-4a910321b986.PNG">

**Comment by bharanidharanj** [comment]
# Test Results

### GROUP_IOS_CHROME: iOS / Chrome browser

* **TEST_KHMER_ANGKOR (BLOCKED):** iOS Simulator does not support Chrome browser. Hence, not able to test it in the Simulator. 
* **TEST_SIL_EURO_LATIN (BLOCKED):** iOS Simulator does not support Chrome browser. Hence, not able to test it in the Simulator. 
* **TEST_GALAXIE_HEBREW (BLOCKED):** iOS Simulator does not support Chrome browser. Hence, not able to test it in the Simulator. 
* **TEST_SIL_IPA (BLOCKED):** iOS Simulator does not support Chrome browser. Hence, not able to test it in the Simulator.

**Comment by MakaraSok** [comment]
Verification Tests:
Keyman for iOS version 16.0.137/8.

- GROUP_IOS_SAFARI: iOS / Safari browser - version 15.7.3
  * All test cases, but one doesn't give the same result as reported above. TEST_GALAXIE_HEBREW does NOT FAILED on me. Let's retest TEST_GALAXIE_HEBREW.

![IMG_0CCE76BB18EE-1](https://user-images.githubusercontent.com/28331388/224257399-babb42cf-2793-4e5d-9ec6-bfda8b4ee43d.jpeg)


@keymanapp-test-bot retest GROUP_IOS_SAFARI TEST_GALAXIE_HEBREW

**Comment by MakaraSok** [comment]
# Test Results

### GROUP_IOS_CHROME: iOS / Chrome browser version `110.0.5481.114`

<img width=250 src="https://user-images.githubusercontent.com/28331388/224270209-2846174e-ddee-4248-93b2-19a11d61c077.jpeg">


* **TEST_KHMER_ANGKOR (FAILED):** The output is different from what's expected.
* **TEST_SIL_EURO_LATIN (PASSED):** The output does match what's expected.
* **TEST_GALAXIE_HEBREW (PASSED):** The output does match what's expected.
* **TEST_SIL_IPA (PASSED):** The output does match what's expected.

**Comment by MakaraSok** [comment]
@keymanapp-test-bot retest GROUP_IOS_SAFARI TEST_GALAXIE_HEBREW

**Comment by bharanidharanj** [comment]
# Test Results

### GROUP_IOS_SAFARI: iOS / Safari browser

* **TEST_GALAXIE_HEBREW (BLOCKED):** Got an error message while trying to install the attached Galaxie Hebrew (Positional) .kmp file in the simulator. It's blocked to do further testing in Safari browser. 

   
..iOS 16.0 / iPhone 13 Pro Max Simulator

<img width="300" src="https://user-images.githubusercontent.com/19683143/224673231-870c6700-811f-4207-9576-46933a4d21c0.png">

**Comment by MakaraSok** [comment]
@keymanapp-test-bot retest GROUP_IOS_SAFARI TEST_GALAXIE_HEBREW

With the new instructions to test the Hebrew keyboard we've talked about earlier, could you try and retest this.

For your conveniences, here is a direct quote of it:

>    * TEST_GALAXIE_HEBREW: Galaxie Hebrew mentioned above and here is [how to](https://docs.google.com/spreadsheets/d/e/2PACX-1vS6GnYMo3WB-m7Mj8_4IMzz54MCDNECh01bsuI5epx7LJo28VMSJY8aT9WRbGms6bb_k4DSbNrf7uHZ/pubhtml?gid=0&single=true) type each key.
>       * Type <kbd>b</kbd> <kbd>\\</kbd> <kbd>=</kbd> <kbd>r</kbd> <kbd>@</kbd> <kbd>a</kbd> <kbd>v</kbd> <kbd>!</kbd> <kbd>y</kbd> <kbd>t</kbd> to output `בְּרֵאשִׁית`. FAILED if the output is different.

**Comment by bharanidharanj** [comment]
# Test Results

### GROUP_IOS_SAFARI: iOS / Safari browser

* **TEST_GALAXIE_HEBREW (PASSED):** Tested with the latest Keyman 17.0.78-alpha build in iOS 16.2 / iPhone 14 Pro Max Simulator and here is my observation: 1. Able to install Galaxie Hebrew (Positional) Keyboard without having any problem in the Keyman app. 2. Opened the test page in Safari browser and I was able to type in the Galaxie Hebrew (Positional) keyboard. It is showing the expected output. Seems to be working fine. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/228165971-c34d6f6b-ba42-4b9c-845f-e87a17ec8022.png">

**Comment by MakaraSok** [comment]
- [x] Verification test
- [x] Retest
