### ISSUE TITLE
bug(developer): Touch layout with missing key id's

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#8000]
Your `Núm` and Emoji buttons don't have an `ID` in at least the postmodern_english_uk_natural keyboard. I suspect it's related to that. However, I don't know what the ID should be... I would expect `K_NUMERALS` and `K_SYMBOLS` to be acceptable.

![image](https://user-images.githubusercontent.com/7071907/211358143-4475d300-4abb-425f-8f9f-252c5b236857.png)

_Originally posted by @LornaSIL in https://github.com/keymanapp/lexical-models/issues/180#issuecomment-1375917261_

A user was asking for help why Keyman for Android failed to switch layers on the "emoji" and "Núm" keys. @LornaSIL pointed out the key IDs are blank.

I've marked 1 of the 4 instances here
https://github.com/keymanapp/keyboards/blob/22b4b3ab4eb0b05f3407c21f57c135723495ef58/release/p/postmodern_english_us_natural/source/postmodern_english_us_natural.keyman-touch-layout#L280-L284

Shouldn't Keyman Developer flag this during compilation?

**Comment by PostmodernEnglish** [comment]
Thanks for looking into this. In the past, it seems like these keys worked- either something must have changed, or maybe we erased these fields by mistake. For now, we will take the route LornaSIL suggested.
