### ISSUE TITLE
bug(android): Keyboard Screen Flickering happens If I change the Keyboard Language using Globe Key 

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#8007]
### Describe the bug

I noticed that the screen flickering happens while changing the Keyboard change using globe key. 

### Reproduce the bug

1. Install Keyman 17.0.26-alpha build in a Mobile device.
2. Open Keyman App.
3. Install Khmer Angkor and Tamil Keyboards using Settings / Install Keyboard or Dictionary / Install from keyman.com option.
4. Verify all the Keyboards are installed under Installed languages menu. 
5. Return to main page. 
6. Verify that the default keyboard English -EuroLatin(SIL) is displayed on the page.
7. Short press the globe key and we may noticed that the next keyboard immediately changes. 
8. Now, long press the globe key, Click Khmer or Tamil Keyboard. 
Here, I noticed that there is Screen flickering happens in the Keyboard view. 

I have attached the Video file (Screenflickering.mp4)  for reference. Thanks. 

https://user-images.githubusercontent.com/19683143/211829538-477f932b-5b7b-4283-88e6-e5ad3ab3576b.mp4

### Expected behavior

It would be better if Screen flickering should not happen while changing the keyboard using (long press) globe key. 

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.26-alpha

### Operating system

Android 11.0

### Device

Redmi Note 8 Pro

### Target application

Keyman App

**Comment by darcywong00** [comment]
Defer to A17S18 when I'm back

**Comment by darcywong00** [comment]
Will tackle Android OSK issues with @jahorton in A17S25
