### ISSUE TITLE
refactor(core): Review wasm build scripts

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/keyman#8010]
The wasm.build scripts for Linux, Windows, and Mac (`core/wasm.build.*.in`) greatly differ which seems really odd to me. I'd have thought  that they would differ in the paths and how the executable gets called. They specify different parameters and the entries in the `[binaries]` section are different on Linux and Mac where I'd think they could be the same. This is highly confusing for someone not very familiar with wasm/meson.

It would be good to refactor the wasm.build scripts to be as similar as possible and remove unnecessary lines. (I assume that the parameters that the Linux build specifies are already defined in `wasm.defs.build` and so are not needed)

The same build scripts got copied to `developer/src/kmcmplib/` in the `feature-kmcompx` branch.

**Comment by mcdurdin** [comment]
https://github.com/keymanapp/keyman/pull/8393/files#diff-72f8dac5a826c66c2902a7253b1d3cf84c4d8d2591af3fc4488a78fa02ba55a9 shows config we need and also the cleaned up WASM defs.
