### ISSUE TITLE
bug(windows): Kannada UI name appears twice in the UI language List in Keyman Configuration dialog

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#8075]
### Describe the bug

I noticed that the Kannada language name appears twice in the UI language List. 

### Reproduce the bug

1. Install Keyman 17.0.34-alpha-test-8074 build in Windows OS.
2. Open Keyman Configuration dialog. 
3. Click the 'Display in' list box. 
4. Scroll down and Select 'Kannada' language. 

Here, I noticed that the Kannada language appears twice in the list box. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/214306568-e732676a-a4ce-4288-8b31-73894f3a44e9.PNG">

### Expected behavior

Kannada language name should not be duplicated in the UI list box. 

### Related issues

#7559

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [X] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.34-alpha-test-8074

### Operating system

Windows 11 OS 

### Device

Windows Desktop

**Comment by darcywong00** [comment]
This is reported while testing #8074

**Comment by darcywong00** [comment]
@bharanidharanj - can you retest this with [Keyman for Windows 16.0.138](https://downloads.keyman.com/windows/stable/16.0.138/keyman-16.0.138.exe) and update if this is still an issue?

**Comment by ermshiperete** [comment]
See #8174 for additional details.

**Comment by MayuraVerma** [comment]
![image](https://user-images.githubusercontent.com/14062593/217041232-e31cd1a2-c2fb-493b-a64d-9256a4ff5b5d.png)

kan-Knda-IN, which I had uploaded via pull request before Crowdin.
kn-IN is from Crowdin.

Both can go away, it is better them be replaced by 'kn' just language code.

**Comment by bharanidharanj** [comment]
> @bharanidharanj - can you retest this with [Keyman for Windows 16.0.138](https://downloads.keyman.com/windows/stable/16.0.138/keyman-16.0.138.exe) and update if this is still an issue?

@darcywong00 Sure. I will retest it.

**Comment by bharanidharanj** [comment]
Tested with the attached PR build (16.0.138) and still I am able to see the Kannada language appears twice in the language display list.  

   <img width="300" src="https://user-images.githubusercontent.com/19683143/217227262-7c6a6ee8-8102-4e0c-a3e8-726d633b37fe.PNG">


   Note: English language also appears twice in the list.

**Comment by darcywong00** [comment]
> Note: English language also appears twice in the list.

That's a separate issue because pt-BR is listed as English (with language code "en" too)
https://github.com/keymanapp/keyman/blob/f2f39efb8a3e2147b958926ab2a2903944f3b2fb/windows/src/desktop/kmshell/locale/pt-BR/strings.xml#L625

**Comment by MayuraVerma** [comment]
Version 17.0.51-alpha installation still shows two Kannada language option

However, App is showing one Kannada localization.

Also, if the user chooses a language during installation, same language should be loading with Keyman at launch.

Now, Keyman is defaulting to English after installation.

![image](https://user-images.githubusercontent.com/14062593/219902371-1ba7d3c6-3bd9-4a58-bf15-5b8bbd4c189a.jpeg)
