### ISSUE TITLE
bug(android): Tool tip text still appears in English language instead of Kannada UI language (globe key)

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#8078]
### Describe the bug

I noticed that after changing the UI language into Kannada, the tool tip for globe key is still showing english text instead of kannada text. 

### Reproduce the bug

1. Install Keyman 17.0.34-alpha-test-8074 in Android Mobile / emulator. 
2. Open Keyman App. 
3. Changed the Display language into 'Kannada'. 

Here, I noticed that the tool tip text appears on the globe key are still showing english text. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/214328099-44169e1f-37ea-49de-9508-a912f03926f1.PNG">

### Expected behavior

The tool tip text should appear in kannada language after the kannada UI change.

### Keyman apps

- [x] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.34-alpha-test-8074

### Operating system

Windows 10 OS

### Device

Windows Desktop

**Comment by darcywong00** [comment]
Possible repeat of #7975 - 
I'll check if the build @bharanidharanj used includes the fix from #7976

**Comment by darcywong00** [comment]
The branch `cherrypick/kannada-shawn` in #8074 did not contain the 🍒 picked fix. I've merged master into the branch.

@bharanidharanj - please retest with the Keyman for Android test build from #8074 and see if you can repro the issue.

**Comment by bharanidharanj** [comment]
> The branch `cherrypick/kannada-shawn` in #8074 did not contain the 🍒 picked fix. I've merged master into the branch.
> 
> @bharanidharanj - please retest with the Keyman for Android test build from #8074 and see if you can repro the issue.

Okay, @darcywong00 . I will retest it.

**Comment by bharanidharanj** [comment]
@darcywong00 @mcdurdin Retested with the PR build (#8074 - 17.0.35-alpha-test-8074) in Android 11.0 / API 30 emulator and not I am able to see the tool tip text appears in Kannada after using Kannada UI. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/214502116-a7cfdc34-c693-40cb-a1b9-aacb189090d3.PNG">

**Comment by darcywong00** [comment]
Closed in 17.0.35
