### ISSUE TITLE
chore(windows): Split ssOffline into 3 separate strings

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#8080]
> It seems the Windows string ssOffline is too long (> 1023 bytes), so I had to truncate at 2 of the 3 sentences.

Longer-term, we could fix by having each para a separate string?

_Originally posted by @mcdurdin in https://github.com/keymanapp/keyman/issues/8072#issuecomment-1403081953_

-------------

Should this be resolved by:
1. Splitting the string in crowdin into 3 separate strings?
2. Have the Windows code split the existing string on newlines?

**Comment by darcywong00** [comment]
This is handled on #8072 where @mcdurdin split ssOffline into 3 strings.

**Comment by darcywong00** [comment]
We can leave downloaded strings intact. Unfortunately I think crowdin sees the shorter ssOffline as a change and wiped the existing translations :/ We'll just have to wait for translators to redo them all when we want an update

**Comment by mcdurdin** [comment]
We should be able to fixup the translations ourselves? Either we just plug ssOffline original text back in, or split at the paragraphs. There's no change to the text.

**Comment by darcywong00** [comment]
> We should be able to fixup the translations ourselves? Either we just plug ssOffline original text back in, or split at the paragraphs. There's no change to the text.

Yeah, either is doable as a low-hanging 🥝 task

**Comment by darcywong00** [comment]
And I've manually updated the ssOffline strings in crowdin (for the translations we've previously pulled)
