### ISSUE TITLE
chore(developer): check for common includes in CheckfilenameConsistency.cpp

### ISSUE THREAD

**Issue by SabineSIL** [keymanapp/keyman#8086]
In `developer/src/kmcmplib/src/CheckFilenameConsistency.cpp` (l. 116)

`//TODO: sort out how to find common includes in non-Windows platforms:`

we may need to address this. 

see    https://github.com/keymanapp/keyman/pull/6980#discussion_r1063292099  in feat(developer): cross-platform kmx compiler 🚑 https://github.com/keymanapp/keyman/pull/6980

**Comment by SabineSIL** [comment]
created new PR #8346 for this

**Comment by mcdurdin** [comment]
Process note: we should only close the issue when the PR is merged :smile:
