### ISSUE TITLE
[Android] Feature request: Localize the app

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#809]
We should [localize](https://developer.android.com/training/basics/supporting-devices/languages?authuser=3) the app.

TODO
- [x] Audit and move dialog/notification strings to `/res/values/strings.xml` (account for plurals, #2751)
- [x] Set up translation project on https://crowdin.com/project/keyman to manage translations
- [x] Use CrowdIn translations into separate values-bcp-47 folders (managed by Crowdin CLI v3 in #2895)
- [ ] Configure translated strings into GitHub

One challenge will be for target languages that aren't available in Android system locales

**Comment by darcywong00** [comment]
<a href="https://github.com/ericjding"><img src="https://avatars1.githubusercontent.com/u/10482921?v=4" align="left" width="96" height="96" hspace="10"></img></a> _Originally posted as https://community.software.sil.org/t/keyman-roadmap/822/3_
**[ericjding](https://github.com/ericjding)** says

> It would be a huge help if a localization framework were added to the roadmap for Keyman (esp. for iPhone and Android) so that it could be localized for communities where most people do not read English. In our context, that means simplified Chinese – we could and would happily help with actual localization efforts, but right now there’s no framework for it. As a result, potential users are still non-users if they can’t understand enough English to set up Keyman and download an appropriate minority language keyboard on their smartphones.

**Comment by mcdurdin** [comment]
This needs to be broadened to look at how we can localize across all the Keyman apps. Is there value in sharing localisation data?

Localising language names in the keyboard list should not be part of the app. It should be part of the web service.

**Comment by darcywong00** [comment]
Will configure the Android strings when the other platforms get to i18n in P10S10

**Comment by comradekingu** [comment]
Please don't use Crowdin though, see https://github.com/jitsi/jitsi-meet/issues/5056#issuecomment-612239691
Weblate has no such egregious terms, and is actually libre software :)

**Comment by mcdurdin** [comment]
@comradekingu We're not currently in a position to switch tools at this time. Were you planning to do a translation for Keyman, and is this a blocker for you?

**Comment by comradekingu** [comment]
@mcdurdin It is more that my disdain for Crowdin compells me to. Whatever the circumstances, I find your project additionally is very interesting since I design my own layouts and like users to feel familiar with their surroundings, so I want it to succeed. I'll help fix the source strings, contribute a translation in the languages I know, and call upon the translators I know if you make the switch.

**Comment by mcdurdin** [comment]
Okay, we'll take it under consideration for a future version.

**Comment by mcdurdin** [comment]
Updating CrowdIn will be done periodically through alpha/beta, as a manual task, rather than automatically with every merge to master. Thus, this issue is complete.
