### ISSUE TITLE
bug(iOS): Crash while clicking the Keyman icon in home screen of  iPhone and iPad Simulators 

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#8108]
### Describe the bug

I noticed that after installing the Keyman build from #8071, the keyman crashes while trying to open it. 

### Reproduce the bug

1. Install Keyman 16.0.134 (from #8071) in iPhone 12 Pro Max Simulator.
2. Click the Keyman App icon from home screen. 
Here, I noticed that the keyman app did not open. I just try to open it by clicking again and again on the Keyman App icon. 

Got a crash after clicking the app so many times. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/215054564-e05a6647-f7f1-4760-ae9a-4604e503cd06.png">

Also, attached the Crashtext message (KeymanCrash.txt) for your reference. 

[KeymanCrash.txt](https://github.com/keymanapp/keyman/files/10517455/KeymanCrash.txt)

### Expected behavior

Click on the Keyman App, it should open the Keyman application in iPhone or iPad. 

### Keyman apps

- [ ] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16.0.134

### Operating system

iOS 15.0

### Device

iPhone 12 Pro Max Simulator, iPad Air (4 generation)

### Target application

Keyman App

**Comment by sgschantz** [comment]
I can't reproduce this in the simulator for either Swedish or Czech, but I do get a crash when I attempt to run from TestFlight on  a real device.

**Comment by mcdurdin** [comment]
Tracking this in #8118.
