### ISSUE TITLE
bug(ios): package with >1 matching language id in keyboard.languages crashes on start

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#8118]
### Describe the bug

sil_euro_latin release 2.0.1 [includes Albanian twice](https://github.com/keymanapp/keyboards/pull/2135/files#diff-f18f9f1f702c2facc6aebc1859d0c38a73a43ce6d9d07179fb1e9996518dda90R160) in the list of languages:

```xml
        <Language ID="sq">Albanian</Language>
```

This looks like it was manually edited, because AFAIK, Keyman Developer won't allow language codes to be added more than once?

This causes Keyman Engine on iOS to crash because it isn't expecting the language code to appear more than once:

https://github.com/keymanapp/keyman/blob/1a4512d0eb17e188ab62e4264c283400fb120d29/ios/engine/KMEI/KeymanEngine/Classes/Resource%20Data/InstallableKeyboard.swift#L108-L111

The caller here tries to unwrap the `Optional` return value and crashes:

https://github.com/keymanapp/keyman/blob/1a4512d0eb17e188ab62e4264c283400fb120d29/ios/engine/KMEI/KeymanEngine/Classes/kmp.json/KMPKeyboard.swift#L78-L81

So, a number of issues here:

1. We need to fix sil_euro_latin; see keymanapp/keyboards#2140.
2. The compiler should detect repeated language codes in the .kps; see #8119.
3. We probably don't care in the keyboard install code if we have >1, so change the guard from `==1` to `>=1`
4. The caller must verify that it isn't returned `nil`, and handle failure all the way up the stack (and we should audit for other calls to `InstallableKeyboard.init` that make the same error):

```
* thread #1, queue = 'com.apple.main-thread', stop reason = step in
  * frame #0: 0x0000000110d1e47a KeymanEngine`InstallableKeyboard.init(metadata=0x00006000009b1880, packageID="sil_euro_latin", lgCode="sq") at InstallableKeyboard.swift:104:24
    frame #1: 0x0000000110e19b11 KeymanEngine`KMPKeyboard.installableKeyboards.getter(self=0x00006000009b1880) at KMPKeyboard.swift:79:22
    frame #2: 0x0000000110e1a65c KeymanEngine`KMPKeyboard.isValid.getter(self=0x00006000009b1880) at KMPKeyboard.swift:116:12
    frame #3: 0x0000000110e02551 KeymanEngine`KeyboardKeymanPackage.init(metadata=0x0000600000cb0e70, folder="file:///Users/mcdurdin/Library/Developer/CoreSimulator/Devices/34CB95ED-0A94-4EAD-BCCE-7DAE5DB2C457/data/Containers/Data/Application/B33DD10A-A931-4697-883A-C17C41F89961/Library/Caches/temp/sil_euro_latin.kmp.zip/") at KeyboardKeymanPackage.swift:22:21
    frame #4: 0x0000000110e0214d KeymanEngine`KeyboardKeymanPackage.__allocating_init(metadata:folder:) at KeyboardKeymanPackage.swift:0
    frame #5: 0x0000000110e70006 KeymanEngine`static KeymanPackage.parse(folder="file:///Users/mcdurdin/Library/Developer/CoreSimulator/Devices/34CB95ED-0A94-4EAD-BCCE-7DAE5DB2C457/data/Containers/Data/Application/B33DD10A-A931-4697-883A-C17C41F89961/Library/Caches/temp/sil_euro_latin.kmp.zip/", self=KeymanEngine.KeymanPackage) at KeymanPackage.swift:409:21
    frame #6: 0x0000000110e70fdd KeymanEngine`static KeymanPackage.extract(fileUrl="file:///Users/mcdurdin/Library/Developer/CoreSimulator/Devices/34CB95ED-0A94-4EAD-BCCE-7DAE5DB2C457/data/Containers/Data/Application/B33DD10A-A931-4697-883A-C17C41F89961/Library/Caches/sil_euro_latin.kmp.zip", destination="file:///Users/mcdurdin/Library/Developer/CoreSimulator/Devices/34CB95ED-0A94-4EAD-BCCE-7DAE5DB2C457/data/Containers/Data/Application/B33DD10A-A931-4697-883A-C17C41F89961/Library/Caches/temp/sil_euro_latin.kmp.zip/", self=KeymanEngine.KeymanPackage) at KeymanPackage.swift:459:30
    frame #7: 0x0000000110e556ba KeymanEngine`ResourceFileManager.prepareKMPInstall(url="file:///Users/mcdurdin/Library/Developer/Xcode/DerivedData/keymanios-bufvzwderalsuvatkzcllbtenoas/Build/Products/Debug-iphonesimulator/KeymanEngine.framework/Keyman.bundle/Contents/Resources/sil_euro_latin.kmp", self=(haveRunMigrations = true)) at ResourceFileManager.swift:187:42
    frame #8: 0x0000000110ef31ef KeymanEngine`closure #1 in variable initialization expression of static Defaults.keyboardPackage at Constants.swift:79:44
    frame #9: 0x0000000110ef2f49 KeymanEngine`one-time initialization function for keyboardPackage at Constants.swift:77:62
```

### Keyman apps

- [ ] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

15.0+

### Keyboard name

sil_euro_latin

### Keyboard version

2.0.1

### Language name

Albanian

**Comment by darcywong00** [comment]
fwiw, on Keyman for Android Albanian gets displayed in the language picker twice.
