### ISSUE TITLE
fix(developer): ldml: support >1 layers lists 🙀

### ISSUE THREAD

**Issue by srl295** [keymanapp/keyman#8160]
followon to #7965

right now we support a single `<layers>` element in compile. Should support >1 - ~multiple~ only one hardware layer, but multiple touch layers.

**Comment by srl295** [comment]
LDML now disallows >1 hardware layer so some of this is moot. 

Should handle the case where there's multiple touch layers and only one hardware layer, which is not supported right now.

**Comment by mcdurdin** [comment]
`s/layer/layers/` in places above. Some fun distinguishing between "`<layers>`" and "`<layer>`s".
