### ISSUE TITLE
bug(android): Casing questions on the suggestion banner

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#8164]
Running 16.0.138 stable in the Keyman for Android app, I encountered some scenarios that look curious:
(Not sure if any is related to #7165 

## Scenario 1 - "Hello" suggestion is capitalized

Typing "hell" results in the suggestions: hell, Hello, hella. I'm confused why "hello" is always capitalized. This isn't at a start of a sentence.

![Hello-middle](https://user-images.githubusercontent.com/7358010/216507296-74827ebd-e222-4af4-ab62-d5aca7fef8b7.jpg)

## Scenario 2 - "Hello" moves from middle to left position

From scenario 1, leave the device inactive until the screen lock kicks in. After unlocking the screen, the suggestions refresh to: Hello, hella, helluva

![Hello-left](https://user-images.githubusercontent.com/7358010/216507305-58b0c6b2-17a5-41be-8fd5-dcb170537949.jpg)

~I haven't tested on other platforms to see if this is only on Android~
I built stable-16.0 and tried mobile viewport of web/testing/prediction-mtnt and it shows "Hello" in the middle too

![kmw test page - hello](https://user-images.githubusercontent.com/7358010/216508414-9c81c53b-d185-44de-bfc4-d186160407b9.png)

**Comment by darcywong00** [comment]
OK examining the mtnt.tsv word list, it uses "Hello". (Also "Yep")

https://github.com/keymanapp/lexical-models/blob/master/release/nrc/nrc.en.mtnt/source/mtnt.tsv#L2609

https://github.com/keymanapp/lexical-models/blob/master/release/nrc/nrc.en.mtnt/source/mtnt.tsv#L1618

I thought predictive text lower-cases all the words though?

**Comment by mcdurdin** [comment]
> I thought predictive text lower-cases all the words though?

Upper case suggestions remain upper case (for proper nouns in many langs). Otherwise case matches context.

**Comment by darcywong00** [comment]
> Upper case suggestions remain upper case (for proper nouns in many langs). Otherwise case matches context.

OK, I've updated keymanapp/lexical-models#178 to cleanup the capitalizations there.

Then this issue will remain for tracking down why the Android app resumes and moves suggestions over. (Scenario 2)

**Comment by darcywong00** [comment]
I can repro scenario 2 on Keyman for iPhone and iPad 16.0.138.

Is predictive text doing something different when resuming?

**Comment by darcywong00** [comment]
To triage again in A17S7

**Comment by darcywong00** [comment]
> Then this issue will remain for tracking down why the Android app resumes and moves suggestions over. (Scenario 2)

I added logging and on resuming the Android app, I see `languageProcessor.invalidateContext()` is getting called.

**Comment by darcywong00** [comment]
Bumping back to 17.0 for @jahorton to look at when modularization refactor is completed.

**Comment by jahorton** [comment]
> Is predictive text doing something different when resuming?

Sorry, didn't notice this until now.  The very likely answer is yes, it _is_ doing something different.  You should get very similar results if you change the caret's location and then place it back at the end of the context.

The big distinction I'm noticing here: `hell` - the actual typed text - is being removed as an option when resuming.  It's what's already there, and there's no need to modify anything.  On resuming, it's not like you just typed it; simply "doing nothing" is sufficient to leave it in place.  

When actively typing, we present a 'keep' option if it does indeed match a word in the lexicon.  ("Hell" is a valid English word.)  On context-changes, though... it seems like the "keep" option isn't being generated or returned, for whatever reason.  (Note:  "resuming" is acting like a context-change.)  Thus, that option disappears and the other options slide over.

**Comment by darcywong00** [comment]
Sounds like the suggestions are presented as designed.

Resuming = context-change = not typing anything for the "keep" option.
Can close
