### ISSUE TITLE
bug(iOS): (Random) Inconsistent behavior of keyman sceen view in iPhone Simulator after installing Keyman 17.0.45 alpha build

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#8207]
### Describe the bug

I noticed that the clicking on the home screen button in the iPhone Simulator suddenly changes its view from Landscape to Portrait view. 

### Reproduce the bug

Here, What I did is:

1. Opened iOS 15.0 / iPhone 12 Pro Max Simulator. 
2. Uninstalled previous versions of Keyman build. 
3. Installed Keyman 17.0.45-alpha build.
4. Opened Keyman App. 
5. Installed Tamil Keyboard using Installed Languages menu. 
6. Changed the Simulator view from Portrait to Landscape View. 
7. Then, clicked the Home Screen button from the iPhone Simulator. 

Here, I noticed that the screen view suddenly changed to Portrait View. 

Note: I reinstalled the same keyman build,but this time it is working fine. Seems to be a random one. 

I have attached the Video file for your reference. Thanks. 

https://user-images.githubusercontent.com/19683143/218028185-fdd17692-d588-418a-86ef-73c5587c79d9.mp4

### Expected behavior

By clicking the Home Screen view, the keyman application should close and the Landscape view should remain in the iPhone Simulator. 

### Keyman apps

- [ ] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.45-alpha

### Operating system

iOS 15.0

### Device

iPhone 12 Pro Max Simulator

**Comment by jahorton** [comment]
That's an odd bug, to be sure, but that's Simulator level.  There's literally nothing we could do in our iOS code to trigger that.
