### ISSUE TITLE
test(iOS): Regression Test for Keyman 17 - Alpha

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#8208]
# Keyman for iPhone and iPad Acceptance Test Procedures #

1. These test procedures are to be run before moving from alpha to beta, or beta to stable, or before PRs are merged into stable branches.
2. Copy these tests into a new issue (for tier transitions) or a comment on the PR.
3. When annotating results, use `>` at the start of a new line under the checkbox to note the result. (For an example, see #3973).

---

# User Testing
## Gather Assets for Testing ##
- [ ] Record device's iOS version
- [ ] Ensure the device is properly configured for testing and is registered with TestFlight.

At this time, Keyman for iOS does not support external keyboard input.

## Setup Steps ##
1.  Uninstall previous version of Keyman on the device (on a simulator, "Erase All Content and Settings..." under Device menu)
2. Install test build IPA (on a simulator, "iOS Simulator Image")
3. Disable internet connectivity of the device
4. Start Keyman and select **Add a keyboard for your language**
5. Verify error message "Could not reach Keyman server!" or "The Internet connection appears to be offline." is displayed
6. Click OK to dismiss.  Close Keyman app
7. On device, enable internet connectivity
8. Start Keyman
9. On initial **Get Started** menu, select "Enable Keyman as system-wide keyboard" and do any necessary system steps to enable Keyman

---

## SUITE_INSPECT: Visual Inspection of master branch
- TEST_BUILD_STATUS: ![Build Status](https://build.palaso.org/app/rest/builds/buildType:(id:Keyman_iOS_Master)/statusIcon) Verify latest CI build of [master](https://build.palaso.org/viewType.html?buildTypeId=Keyman_iOS_Master) is successful
- TEST_VERIFY_HISTORY: Verify [`HISTORY.md`](https://github.com/keymanapp/keyman/blob/master/HISTORY.md) contains all the current changes
- TEST_VERIFY_UNIT_TESTS: Verify that all unit tests for iOS are currently passing.
    - May be integrated with the first step above once our usual CI processes include the iOS unit tests.

---

## SUITE_MENU_FUNCTIONALITY: Menu Functionality Tests, in-app##
- GROUP_IPHONE_PORTRAIT: portrait mode in iPhone
- GROUP_IPHONE_LANDSCAPE: landscape mode in iPhone
- GROUP_IPAD_PORTRAIT: portrait mode in iPad
- GROUP_IPAD_LANDSCAPE: landscape mode in iPad

### Test Cases
- **TEST_GET_STARTED**: Get Started
  - Verify touching **Add a keyboard for your language** pulls up the **keyboard search**
      - This should also be accessible as **Settings** > **Installed Languages** > **`+`**.
  - Verify touching **Enable Keyman as system-wide keyboard** pulls up Keyman's menu within iOS settings.  (11.0+ devices)
      - If older versions of iOS are supported, ensure that the help page for doing it manually is properly linked.
  - Verify touching **More info** brings up an accurate version and the main table-of-contents help page.
      - This should also be accessible as **Info** from the main menu dropdown (on phones) or as the circled-i button (on tablets).
  - Set **Don't show again** to checked, close and re-open Keyman, and verify **Get Started** menu does not appear

- **TEST_ADD_NEW_KEYBOARD**: Add New Keyboard
This menu is accessed via **Get Started** menu or **Settings** menu
  - On the device, enable internet connectivity
  - Verify a new keyboard can be downloaded and selected, say "US Basic"
  - Return to the text input screen and confirm that it operates correctly.
  - Without changing selected language, confirm that it can be cleanly deleted via the Settings menu.
  - Confirm that another keyboard is correctly selected afterward.

- **TEST_ADD_NEW_KEYBOARD_FROM_FILE**:
  - On the device, go to keyman.com on Safari
  - Search for "US Basic"
  - scroll down to keyboard details and tap to download the keyboard package (i.e. `.kmp` file)
  - open Files app and navigate to Download folder to find "basic_kbdus.kmp" and tap on it to start the installation processes
  - Keyman app should be pulled up
  - follow the screen to finish the keyboard installation
  - verity that the keyboard is correctly installed and working as expected

- **TEST_SWITCH_KEYBOARD**
  - press on the globe key
  - the keyboard menu should be shown
  - press on a keyboard to switch to, say "EuroLatin (SIL)"
  - confirm that "EuroLatin (SIL)" is now selected and ready to be used
  - swich back to "US Basic" and confirm it does as expected

- **TEST_SHARE**: Share
  - Type and verify text can be copied and shared to external app

- **TEST_KEYMAN_BROWSER**: Keyman Browser ###
  - On default page, click on text field and set system keyboard to Keyman
  - Verify can type with Keyman as system keyboard
  - Verify that predictive suggestions are properly applied when selected (using `sil_euro_latin` + English)
  - Close and reopen Keyman app

- **TEST_TEXT_SIZE**: Text Size
  - Verify text can be rescaled from Text Size 9 to 72

- **TEST_CLEAR_TEXT**: Clear Text
  - Verify text can be cleared

- **TEST_INFO**: Info
  - Verify that the Keyman iOS version is displayed; record the version
  - Verify that the Info menu options matches that of the **More Info...** option from the **Get Started** menu option.
  - Verify that the Keyman iOS version matches the version string seen at (Home Screen) > [iOS] Settings > Keyman.

- **TEST_SETTINGS**: Settings
  - Installed Languages ... Add Language
  - Select an installed language ... Add (another) Keyboard
    - Should automatically perform a filtered search based upon that language's BCP-47 code, i.e. for "English" it should be seen as shown in the screenshot below.
    <img width="150" src="https://user-images.githubusercontent.com/28331388/163088289-b467eabb-01a6-468e-81f9-2cfad38584bd.png">

  - Select an installed language ... Dictionary
    - Turn on/off 'Enable Predictions' and validate each
    - Turn on/off 'Enable Corrections' and validate each
  - Validate that when both predictions and corrections are off, banner is not visible
  - Add/Remove dictionaries - validate
  - If multiple dictionaries are available, test swapping between them

- **TEST_EUROLATIN**: `English (Eurolatin)` in-app
  - In portrait orientation, verify that the OSK appears and fills the width the bottom of the screen
  - Verify long-press `q` key works
  - Verify long-press `k` key works
      - Verify that any predictive suggestions generated feel 'reasonable' (based upon 'k', the selected subkey, or one of its neighbors)
  - Verify uppercase layer can be selected via `SHIFT`
  - Verify number layer can be selected via `123`
  - Verify long-press `1` key works
  - Verify long-press `0` key works
  - Verify backspace, space, and enter keys work

Note that EuroLatin2, a highly customized keyboard explicitly designed for mobile, is not found; hence EuroLatin (SIL) is used for testing this instead.

- **TEST_US_BASIC**: English: `US Basic` in-app
  - Verify that the **US Basic** keyboard can be downloaded through Settings > Installed Languages > English > `+`
    - This should automatically bring up search results for **English** keyboards.
    - When the package-installer launches, English should be the one pre-selected language.
  - Install the package for both English and Tagalog by selecting both of them in the installation processes.
  - Set **English: US Basic** as the active in-app keyboard.
  - Verify that predictive text suggestions appear.
  - Set **Tagalog: US Basic** as the active in-app keyboard.
  - Verify that predictive text suggestions do _not_ appear.
  - Verify that long-press `123` key works, presenting options for a currency layer and a symbol layer.
  - Select the currency layer, then press the `£` key.
  - Verify that the keyboard outputs correctly and returns to the default layer.
  - Go to the symbol layer and press the `©` key.
  - Verify that the keyboard outputs correctly and remains on the symbol layer.
  - Revert to the default layer and ensure basic key inputs work.
  - Long-press `e` on the default layer and select a subkey.
  - Verify that the selected key produces the correct output.
  - From the `Settings > Languages > English > US Basic` menu, follow the "Help link" and ensure it displays appropriate help.
    - (Should work both online and offline)
  - From the `Settings > Languages > English > US Basic` menu, scan the QR code with a phone and test that it links to the current version of that keyboard's public download page on keyman.com.
  - Returning to the app, uninstall the **US Basic** keyboard via Settings for Tagalog.
  - Set **English: US Basic** as the active in-app keyboard.
  - Verify that the keyboard appears correctly and ensure basic key inputs work.
    - This is to ensure that uninstalling for one language doesn't adversely affect installations of the same resource for another language.
  - Uninstall the **US Basic** keyboard via Settings for English.

---

## SUITE_SYSTEM_KEYBOARD:
- GROUP_IPHONE_PORTRAIT: portrait mode in iPhone
- GROUP_IPHONE_LANDSCAPE: landscape mode in iPhone
- GROUP_IPAD_PORTRAIT: portrait mode in iPad
- GROUP_IPAD_LANDSCAPE: landscape mode in iPad

Test the following after setting Keyman as a system keyboard.

Test Cases
- **TEST_BASIC_USAGE**: ensure that the keyboards functions as expected on all layers. Please test on multiple keyboards, i.e. EuroLatin (SIL), Cameroon QWERTY keyboard and Khmer Angkor.
- **TEST_LONG_PRESS**: ensure that longpress on all applicable layers are working as intended
- **TEST_GLOBE_KEY**: ensure that a short press on the globe key switch to the next keyboard and a longpress on it open the keyboard menu where you can select a keyboard of your choice

## SUITE_SWITCH_LOCALE
- GROUP_IPHONE_PORTRAIT: portrait mode in iPhone
- GROUP_IPHONE_LANDSCAPE: landscape mode in iPhone
- GROUP_IPAD_PORTRAIT: portrait mode in iPad
- GROUP_IPAD_LANDSCAPE: landscape mode in iPad

### Test Cases
- **TEST_KM_LOCALE** 
  - from System Preferences, switch the UI language to Khmer by adding it in `Language & Region` using `+`
  - drag Khmer to the top of the list to set it as a primary UI language
  - check the dropdown menu to see it in Khmer
  - verify the UI language switch to Khmer
- **TEST_AM_LOCALE**
  - from System Preferences, switch the UI language to Amharic by adding it in `Language & Region` using `+`
  - drag Amharic to the top of the list to set it as a primary UI language
  - check the dropdown menu to see it in Amharic
  - verify the UI language switch to Amharic

---

## [TODO] SUITE_PREDICTIVE_TEXT: Predictive Text

**Comment by bharanidharanj** [comment]
## SUITE_INSPECT: Visual Inspection of master branch

* **TEST_BUILD_STATUS (PASSED):** Verified the latest CI build of master is successful and I am able to install 17.0.46 build in iPhone and iPad Simulators. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/218124362-b2e67111-ebbd-4d62-b9ed-025bb4a64946.PNG">


* **TEST_VERIFY_HISTORY (PASSED):** Verified the History.md contains all the current changes.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/218124463-3bcef05e-447f-4fb1-b1fc-57728e465c02.PNG">


* **TEST_VERIFY_UNIT_TESTS (PASSED):** Able to install the latest alpha build in iPhone and iPad Simulators without having any issues. Done the basic tests and it is working as fine.

**Comment by bharanidharanj** [comment]
## SUITE_MENU_FUNCTIONALITY: Menu Functionality Tests, in-app##

### GROUP_IPHONE_PORTRAIT: portrait mode in iPhone

* **TEST_GET_STARTED (PASSED):** Tested with the latest Keyman 17.0.47-alpha build in iOS 16.2 / iPhone 14 Pro Max Simulator and the Get Started menu is working as expected.
* **TEST_ADD_NEW_KEYBOARD (PASSED):** Verified that the new keyboard "US Basic" was downloaded and confirmed that it can be cleanly deleted via the Settings menu. Able to select another keyboard without having any issues.
* **TEST_ADD_NEW_KEYBOARD_FROM_FILE (PASSED):** Verified that I was able to install the downloaded keyboard (basic_kbdus.kmp) package from another location.
* **TEST_SWITCH_KEYBOARD (PASSED):** Verified that able to switch keyboards using the globe key is working fine.
* **TEST_SHARE (PASSED):** notes
* **TEST_KEYMAN_BROWSER (PASSED):** Verified that the Keyman can as be used as System keyboard. Also, verified that the predictive suggestion are properly applied when selected (using sil_euro_latin+English) in the Keyman Browser. 
* **TEST_TEXT_SIZE (PASSED):** Verified that the text size can be rescaled from 9 to 72 using Text size functionality. 
* **TEST_CLEAR_TEXT (PASSED):** Verified that the text can be cleared using Clear Text button.

**Comment by bharanidharanj** [comment]
### GROUP_IPHONE_PORTRAIT: portrait mode in iPhone

* **TEST_INFO (PASSED):** Verified that the Info page showing the installed version. Also, verified that the Info menu options matches that of the More Info..option from the Get Started menu option. 
   
   <img width="300" src="https://user-images.githubusercontent.com/19683143/218461240-23aeefa1-ed62-4d70-960e-1b961a2f472b.png">


* **TEST_SETTINGS (PASSED):** Verified that adding another language using Installed Languages Settings is automatically filtered search based upon that language's BCP-47 code. Able to turn on or off the banner using 'Enable Predictions ' and 'Enabled Corrections' option. Able to add or remove dictionaries.

* **TEST_EUROLATIN (PASSED):** In portrait Orientation, the OSK appears and fills the width the bottom of the screen. Long-pressing the alphanumeric key opens the subkey menu. Seems to be working as expected. 

* **TEST_US_BASIC (PASSED):** Installed English: US Basic and Tagalog US Basic Keyboards in the Keyman app. Tested these keyboards as per the instructions and it is working as expected.

**Comment by bharanidharanj** [comment]
## SUITE_MENU_FUNCTIONALITY: Menu Functionality Tests, in-app##

### GROUP_IPHONE_PORTRAIT: portrait mode in iPhone

* **TEST_INFO (PASSED):** notes
* **TEST_SETTINGS (PASSED):** notes
* **TEST_EUROLATIN (PASSED):** notes
* **TEST_US_BASIC (PASSED):** notes

**Comment by bharanidharanj** [comment]
## SUITE_MENU_FUNCTIONALITY: Menu Functionality Tests, in-app##

### GROUP_IPHONE_LANDSCAPE: landscape mode in iPhone

* **TEST_GET_STARTED (PASSED):** Tested with the latest Keyman 17.0.47-alpha build in iOS 16.2 / iPhone 14 Pro Max Simulator and the Get Started menu is working as expected.
* **TEST_ADD_NEW_KEYBOARD (PASSED):** Verified that the new keyboard "US Basic" was downloaded and confirmed that it can be cleanly deleted via the Settings menu. Able to select another keyboard without having any issues.
* **TEST_ADD_NEW_KEYBOARD_FROM_FILE (PASSED):** Verified that I was able to install the downloaded keyboard (basic_kbdus.kmp) package from another location.
* **TEST_SWITCH_KEYBOARD (PASSED):** Verified that able to switch keyboards using the globe key is working fine.
* **TEST_SHARE (PASSED):** Able to copy the text and shared it to external app like Notes App.
* **TEST_KEYMAN_BROWSER (PASSED):** Verified that the Keyman can as be used as System keyboard. Also, verified that the predictive suggestion are properly applied when selected (using sil_euro_latin+English) in the Keyman Browser.
* **TEST_TEXT_SIZE (PASSED):** Verified that the text size can be rescaled from 9 to 72 using Text size functionality.
* **TEST_CLEAR_TEXT (PASSED):** Verified that the text can be cleared using Clear Text button.
* **TEST_INFO (PASSED):** Verified that the Info page showing the installed version. Also, verified that the Info menu options matches that of the More Info..option from the Get Started menu option.
* **TEST_SETTINGS (PASSED):** Verified that adding another language using Installed Languages Settings is automatically filtered search based upon that language's BCP-47 code. Able to turn on or off the banner using 'Enable Predictions ' and 'Enabled Corrections' option. Able to add or remove dictionaries.
* **TEST_EUROLATIN (PASSED):** In portrait Orientation, the OSK appears and fills the width the bottom of the screen. Long-pressing the alphanumeric key opens the subkey menu. Seems to be working as expected.
* **TEST_US_BASIC (PASSED):** Installed English: US Basic and Tagalog US Basic Keyboards in the Keyman app. Tested these keyboards as per the instructions and it is working as expected.

**Comment by bharanidharanj** [comment]
# Test Results

## SUITE_MENU_FUNCTIONALITY: Menu Functionality Tests, in-app##

### GROUP_IPAD_PORTRAIT: portrait mode in iPad

* **TEST_GET_STARTED (PASSED):** Tested with the latest Keyman 17.0.47-alpha build in iOS 16.2 / iPad Air(5th generation) Simulator and the Get Started menu is working as expected.
* **TEST_ADD_NEW_KEYBOARD (PASSED):**  Verified that the new keyboard "US Basic" was downloaded and confirmed that it can be cleanly deleted via the Settings menu. Able to select another keyboard without having any issues.
* **TEST_ADD_NEW_KEYBOARD_FROM_FILE (PASSED):** Verified that I was able to install the downloaded keyboard (basic_kbdus.kmp) package from another location.
* **TEST_SWITCH_KEYBOARD (PASSED):** Verified that able to switch keyboards using the globe key is working fine.
* **TEST_SHARE (PASSED):** Able to copy the text and shared it to external app like Notes App.
* **TEST_KEYMAN_BROWSER (PASSED):** Verified that the Keyman can as be used as System keyboard. Also, verified that the predictive suggestion are properly applied when selected (using sil_euro_latin+English) in the Keyman Browser.
* **TEST_TEXT_SIZE (PASSED):** Verified that the text size can be rescaled from 9 to 72 using Text size functionality.
* **TEST_CLEAR_TEXT (PASSED):** Verified that the text can be cleared using Clear Text button.
* **TEST_INFO (PASSED):** Verified that the Info page showing the installed version. Also, verified that the Info menu options matches that of the More Info..option from the Get Started menu option.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/218669019-0f57a9a7-0b5b-43db-9cd5-516d2ea8f356.png">

* **TEST_SETTINGS (PASSED):** Verified that adding another language using Installed Languages Settings is automatically filtered search based upon that language's BCP-47 code. Able to turn on or off the banner using 'Enable Predictions ' and 'Enabled Corrections' option. Able to add or remove dictionaries.
* **TEST_EUROLATIN (PASSED):** In portrait Orientation, the OSK appears and fills the width the bottom of the screen. Long-pressing the alphanumeric key opens the subkey menu. Seems to be working as expected.
* **TEST_US_BASIC (PASSED):** Installed English: US Basic and Tagalog US Basic Keyboards in the Keyman app. Tested these keyboards as per the instructions and it is working as expected.

**Comment by bharanidharanj** [comment]
## SUITE_MENU_FUNCTIONALITY: Menu Functionality Tests, in-app##

### GROUP_IPAD_LANDSCAPE: landscape mode in iPad

* **TEST_GET_STARTED (PASSED):** Tested with the latest Keyman 17.0.47-alpha build in iOS 16.2 / iPad Air(5th generation) Simulator and the Get Started menu is working as expected.
* **TEST_ADD_NEW_KEYBOARD (PASSED):** Verified that the new keyboard "US Basic" was downloaded and confirmed that it can be cleanly deleted via the Settings menu. Able to select another keyboard without having any issues.
* **TEST_ADD_NEW_KEYBOARD_FROM_FILE (PASSED):** Verified that I was able to install the downloaded keyboard (basic_kbdus.kmp) package from another location.
* **TEST_SWITCH_KEYBOARD (PASSED):** Verified that able to switch keyboards using the globe key is working fine.
* **TEST_SHARE (PASSED):** Able to copy the text and shared it to external app like Notes App.
* **TEST_KEYMAN_BROWSER (PASSED):** Verified that the Keyman can as be used as System keyboard. Also, verified that the predictive suggestion are properly applied when selected (using sil_euro_latin+English) in the Keyman Browser.
* **TEST_TEXT_SIZE (PASSED):** Verified that the text size can be rescaled from 9 to 72 using Text size functionality.
* **TEST_CLEAR_TEXT (PASSED):** Verified that the text can be cleared using Clear Text button.
* **TEST_INFO (PASSED):** Verified that the Info page showing the installed version. Also, verified that the Info menu options matches that of the More Info..option from the Get Started menu option.
* **TEST_SETTINGS (PASSED):** Verified that adding another language using Installed Languages Settings is automatically filtered search based upon that language's BCP-47 code. Able to turn on or off the banner using 'Enable Predictions ' and 'Enabled Corrections' option. Able to add or remove dictionaries.
* **TEST_EUROLATIN (PASSED):** In Landscape Orientation, the OSK appears and fills the width the bottom of the screen. Long-pressing the alphanumeric key opens the subkey menu. Seems to be working as expected.
* **TEST_US_BASIC (FAILED):** Installed English: US Basic and Tagalog US Basic Keyboards in the Keyman app. Tested these keyboards as per the instructions and I noticed that the 123 key was missing in this keyboard. https://github.com/keymanapp/keyman/issues/8220

**Comment by bharanidharanj** [comment]
## SUITE_SWITCH_LOCALE: 

### GROUP_IPAD_PORTRAIT: portrait mode in iPad

* **TEST_KM_LOCALE (PASSED):** Verified that the UI language has been changed to Khmer. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/218744342-0eabcf4f-1487-44a2-9ded-3270e161e230.png">

* **TEST_AM_LOCALE (PASSED):** Verified that the UI language has been changed to Amharic.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/218744394-5659d2af-8243-4ecd-bb37-47884006d8f1.png">


### GROUP_IPAD_LANDSCAPE: landscape mode in iPad

* **TEST_KM_LOCALE (PASSED):** Verified that the UI language has been changed to Khmer. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/218744488-3161ff1f-f708-42f2-8ff1-881d65f6896c.png">


* **TEST_AM_LOCALE (PASSED):** Verified that the UI language has been changed to Khmer. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/218744555-44252f3a-4749-42a5-9920-aa79f0f767cf.png">

**Comment by bharanidharanj** [comment]
## SUITE_SYSTEM_KEYBOARD: 

### GROUP_IPHONE_PORTRAIT: portrait mode in iPhone

* **TEST_BASIC_USAGE (PASSED):** Set Keyman as the system keyboard and verified that the keyboard functions as expected on all layers. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/218759998-40bdffed-e614-4c0b-a80c-b25e9e46ca17.png">

* **TEST_LONG_PRESS (PASSED):** Verified that the long pressing a key on all applicable layers are working as intended.

* **TEST_GLOBE_KEY (PASSED):** Verified that the short pressing the globe key switches to the next keyboard and long pressing globe key opens the keyboard menu and I was able to select a keyboard from that menu.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/218760026-514c38bd-061f-49ff-88a1-539b397da70d.png">


### GROUP_IPHONE_LANDSCAPE: landscape mode in iPhone

* **TEST_BASIC_USAGE (PASSED):** Set Keyman as the system keyboard and verified that the keyboard functions as expected on all layers. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/218760110-60218538-41ff-4bf8-9b0f-9177f0e5482f.png">


* **TEST_LONG_PRESS (PASSED):** Verified that the long pressing a key on all applicable layers are working as intended.


* **TEST_GLOBE_KEY (PASSED):** Verified that the short pressing the globe key switches to the next keyboard and long pressing globe key opens the keyboard menu and I was able to select a keyboard from that menu.


   <img width="300" src="https://user-images.githubusercontent.com/19683143/218760155-edf9a333-a186-4b7f-9acd-3761466beb48.png">

**Comment by bharanidharanj** [comment]
# Test Results

## SUITE_SYSTEM_KEYBOARD: 

### GROUP_IPAD_PORTRAIT: portrait mode in iPad

* **TEST_BASIC_USAGE (PASSED):** Set Keyman as the system keyboard and verified that the keyboard functions as expected on all layers. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/218773529-fd7ad597-cefd-4032-bab4-c00e299d67f4.png">

* **TEST_LONG_PRESS (PASSED):** Verified that the longpressing a key on all applicable layers are working as intended.


* **TEST_GLOBE_KEY (PASSED):** Verified that the short pressing the globe key switches to the next keyboard and longpressing globe key opens the keyboard menu and I was able to select a keyboard from that menu.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/218773610-75f5e990-b019-4aae-8ade-e348b8fcba02.png">


### GROUP_IPAD_LANDSCAPE: landscape mode in iPad

* **TEST_BASIC_USAGE (PASSED):** Set Keyman as the system keyboard and verified that the keyboard functions as expected on all layers. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/218773675-5daecb76-a711-4367-b969-52f85e321c2b.png">

* **TEST_LONG_PRESS (PASSED):** Verified that the longpressing a key on all applicable layers are working as intended.


* **TEST_GLOBE_KEY (PASSED):** Verified that the short pressing the globe key switches to the next keyboard and longpressing globe key opens the keyboard menu and I was able to select a keyboard from that menu.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/218773750-86d61a94-87a5-4588-856a-ef2bc8c2d091.png">
