### ISSUE TITLE
feat: Windows 11 Touch Screen Keyboard Support

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#8214]
### Is your feature request related to a problem? Please describe.

Windows 11 touch screen virtual keyboard is not support for non-latin keyboards.
Even in non-touch screen.

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [X] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.47 aplha

### Operating system

Windows 11

### Device

Windows laptop

**Comment by mcdurdin** [comment]
Can you give some more examples of what you mean, some screenshots? The Windows touch screen keyboard is not extensible by keyboard apps; it's limited to the languages and keyboards that Microsoft have hard-coded into it. (But I am not clear if that is what you are referring to?)

**Comment by MayuraVerma** [comment]
You are right, the laptop with Windows 11 is a touchscreen display.

I didn't realize.
