### ISSUE TITLE
bug(iOS): Text wrap leaves extra space in Khmer Angkor Help page

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#8216]
### Describe the bug

I noticed that the Khmer Angkor Help page shows extra space in the right side of the page. 

### Reproduce the bug

1. Install Keyman 17.0.47-alpha build in iPhone Simulator or iPad Simulator. 
2. Open the Keyman App. 
3. Download and install Khmer Angkor Keyboard. 
4. Click the Keyman Help link.
5. Verify that the Khmer Angkor Keyboard help page opens. 

Here, I noticed that the there is an extra space appears after the text wrap in the help page. 

Note: I am not seeing this problem in Android Mobile. 

..extra space in Khmer Angkor Help page (iPhone Simulator)

   <img width="300" src="https://user-images.githubusercontent.com/19683143/218440607-da6ed199-66bb-4341-bedc-a37f9b619a93.png">

..extra space in Khmer Angkor Help page (iPad Simulator)

   <img width="300" src="https://user-images.githubusercontent.com/19683143/218440656-33f1a83d-e11a-4f87-8255-8ddd3dc5c477.png">

FYI, it is reproducible in Keyman 16.0 beta version too. 

### Expected behavior

The text wrap should not leave more space in the right margin and the help text fully appears on the page. 

..working fine in Android Version

   <img width="300" src="https://user-images.githubusercontent.com/19683143/218440776-5f5d6d2f-3df5-4804-93b9-b4bacdf1ea6a.PNG">

### Keyman apps

- [ ] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16.0, 17.0

### Operating system

iOS 15.0, iOS 16.2

### Device

iPhone 14 Pro Max Simulator

**Comment by MakaraSok** [comment]
@bharanidharanj This is by designed that the body text spans up to 600px. See the html of the page here https://github.com/keymanapp/keyboards/blob/master/release/k/khmer_angkor/source/welcome/welcome.htm. We can however file a feature request to have it shown fully if needed. :)

**Comment by bharanidharanj** [comment]
> @bharanidharanj This is by designed that the body text spans up to 600px. See the html of the page here https://github.com/keymanapp/keyboards/blob/master/release/k/khmer_angkor/source/welcome/welcome.htm. We can however file a feature request to have it shown fully if needed. :)

@MakaraSoak Okay, Thanks.
