### ISSUE TITLE
bug(iOS): 123 key is missing in English-US Basic Keyboard in iPad Simulator

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#8220]
### Describe the bug

While testing with Keyman app in iPad Simulator, I noticed that the English-US Basic keyboard, the '123' key was missing under the Shift key.

### Reproduce the bug

1. Install Keyman 17.0.47-alpha build. 
2. Open Keyman App. 
3. Open Settings / Install Keyboard or Dictionary option. 
4. Install English - US Basic Keyboard. 
5. Set English -US Basic Keyboard using globe key. 

Here, I noticed that the 123 key is missing under the Shift Key in the Keyboard. 

Note: I am not seeing this problem in iPhone Simulator, hence it is showing in the right place. 

..in iPad Simulator

   <img width="300" src="https://user-images.githubusercontent.com/19683143/218709531-0da29f37-ef37-4545-84ed-4ccf7f0303a6.png">

..in iPhone Simulator

   <img width="300" src="https://user-images.githubusercontent.com/19683143/218709642-2cea9613-5e4a-4d0b-a286-9813036a8498.png">

### Expected behavior

123 key should be visible and active under the Shift key in English - US Basic keyboard. 

### Keyman apps

- [ ] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16.0, 17.0

### Operating system

iOS 15.0, iOS 16.2

### Device

iPad Air 5th generation Simulator

**Comment by mcdurdin** [comment]
This is by design, because the digits and punctuation are found on the default and shift layers on the tablet (iPad) layout, so there is no need for a separate layer for those keys.

**Comment by bharanidharanj** [comment]
> This is by design, because the digits and punctuation are found on the default and shift layers on the tablet (iPad) layout, so there is no need for a separate layer for those keys.

@mcdurdin Okay, Thanks for the Clarification.

**Comment by MakaraSok** [comment]
Confirmed that this is by designed. Check the screenshot of the keyboard layouts designed for tablet at https://help.keyman.com/keyboard/basic_kbdus/1.2/basic_kbdus.

**Comment by bharanidharanj** [comment]
> @bharanidharanj Confirmed that this is by designed. Check the screenshot of the keyboard layouts designed for tablet at https://help.keyman.com/keyboard/basic_kbdus/1.2/basic_kbdus.

@MakaraSok Okay.
