### ISSUE TITLE
bug(android/app): OSK didn't resize in Landscape mode

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#8229]
### Describe the bug

I noticed that when I tried to open keyman app in the landscape mode, the virtual keyboard did not change it size. 

### Reproduce the bug

1. Install Keyman 17.0.48-alpha build. 
2. Change the mobile view into landscape. 
3. Open Keyman App. 

Here, I noticed that the On Screen Keyboard did not change its size. Seems to be an issue. 

OSK 1:
   <img width="300" src="https://user-images.githubusercontent.com/19683143/219063953-df46c8c2-052a-4565-ad60-36aa37de058e.jpg">

OSK2:
   <img width="300" src="https://user-images.githubusercontent.com/19683143/219064053-806d5d8c-12ec-4672-87ce-91e5995332bf.jpg">

### Expected behavior

It should resize in to landscape view. 

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.48-alpha

### Operating system

Android 11.0

### Device

Redmi Note 8 Pro

**Comment by darcywong00** [comment]
I can repro with 17.0.48 alpha and 17.0.51 alpha
![landscape](https://user-images.githubusercontent.com/7358010/220000116-fa613e93-0d86-452a-89ab-c4f96b9efca9.jpg)

**Comment by darcywong00** [comment]
Bisect shows the issue appearing between 17.0.16 and 17.0.17 alpha

17.0.17 includes a merge of beta to master from #7885 so I'll start looking there.

**Comment by darcywong00** [comment]
The OSK rotation issue also doesn't seem to affect KMSample1 or system keyboard

**Comment by darcywong00** [comment]
Pretty sure it involves the SDK bump from #7897 cause an emulator of SDK 31 works with the previous commit 1518d1de0c2e54051a5ad02072efd54068917d89 but fails after the #7897 merge. (in-app keyboard)

**Comment by darcywong00** [comment]
#8291 reverted so re-opening this issue for continued investigation
