### ISSUE TITLE
[iOS] "Keyboard Update Error" dialog should only have "OK" button

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#824]
From Support Case 78779

> It said an update was available, but the alert dialog that came up has an unlabeled button! (Keyboard Update Error, “OK” and “—-“). 

![keyboard update error](https://user-images.githubusercontent.com/7358010/39668638-4476d988-50fd-11e8-9c18-050578bdb143.png)

The dialog should be fixed to only have the "OK" button.

### Configuration
Keyboard 11.0.5 alpha
iPhone 7
iOS 11.3
Keyboard ID: grkpoly2
Language ID: grc

**Comment by tombogle** [comment]
There are several places in the code that have this problem. Easy fix (see Swift 4 update): https://stackoverflow.com/questions/24022479/how-would-i-create-a-uialertview-in-swift
