### ISSUE TITLE
bug(windows): When the Windows starts the Old Hungarian layout doesn't work correctly

### ISSUE THREAD

**Issue by soosistvangithub** [keymanapp/keyman#8249]
When I try to use Old Hungarian layout after the Windows loaded (on Windows10 and Windows 11, too), I must to restart the keyman engine. If I don't do it, the Old Hungarian layout works as English layout.
 Could a more convenient solution be made?
More Hungarian users have experienced this.
We use newest engine.

**Comment by mcdurdin** [comment]
Is Keyman setup to 'start with Windows'? Can you please give some precise details on the exact steps you take when Windows starts in order to get Keyman working? If possible, take a video and share it here.

**Comment by soosistvangithub** [comment]
@mcdurdin It's duplicated issue.
