### ISSUE TITLE
bug: Unable to type Malayalam in VS Code with an extension enabled

### ISSUE THREAD

**Issue by zcraber** [keymanapp/keyman#8250]
### Describe the bug

Unable to type Malayalam in VS Code, if the extension [Markdown All in One](https://github.com/yzhang-gh/vscode-markdown) is enabled.

### Reproduce the bug

1. Install [Markdown All in One](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one) extension and enable it.
2. Create a Markdown file and type <kbd>m</kbd><kbd>a</kbd><kbd>l</kbd><kbd>a</kbd><kbd>y</kbd><kbd>a</kbd><kbd>a</kbd><kbd>L</kbd><kbd>a</kbd><kbd>m</kbd>.
3. You'll get ` ംൽയാൾം`

![markdown-vs-code-keyman](https://user-images.githubusercontent.com/61133303/219708522-85a1205d-30f7-4ab8-99b3-0a3ff652694c.gif)

### Expected behavior

`മലയാളം`

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [X] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16.0.138

### Operating system

Windows 10 22H2

### Device

Windows Laptop

### Target application

Visual Studio Code 1.75.1

### Keyboard name

mozhi_malayalam

### Keyboard version

3.2.3

### Language name

Malayalam

**Comment by mcdurdin** [comment]
This looks like a performance issue in the Markdown All-In-One extension causing it to process keystrokes out-of-order. See https://github.com/yzhang-gh/vscode-markdown/issues/855 (try disabling the backspace binding as per [#issuecomment-919232615](https://github.com/yzhang-gh/vscode-markdown/issues/855#issuecomment-919232615)).
