### ISSUE TITLE
chore(web): web/build.sh has `--no-minify` option but also tests `--skip-minify`, and `--debug` may be better

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#8255]
The `--no-minify` option essentially means "build debug version only". Right now, the web/build.sh script builds the debug build and then goes on and builds the release build if `--no-minify` is _not_ specified. It might be better to instead rename this to `--debug` to skip the release build, which would be more consistent with other platforms.

But in any case, `--skip-minify` is just wrong: :grin: 

https://github.com/keymanapp/keyman/blob/c62349d07149aacc94aa89391b03c4cd90605cf1/web/build.sh#L179-L181

https://github.com/keymanapp/keyman/blob/c62349d07149aacc94aa89391b03c4cd90605cf1/web/build.sh#L227-L229

**Comment by mcdurdin** [comment]
Reopening so we can continue to consider `--debug` or similar

**Comment by jahorton** [comment]
The motivating factor behind this issue has been fixed in #8905; we'll go ahead and close it now.
