### ISSUE TITLE
Code is missing Variables for Delphi version 31

### ISSUE THREAD

**Issue by YogiYang** [keymanapp/keyman#829]
In the file: 
The directives are:
{$IFDEF VER310}
  SKey_DelphiLibrary = 'Software\Embarcadero\BDS\18.0\Library\Win32';
  SFile_DelphiEnvironmentProject = '%AppData%\Embarcadero\BDS\18.0\EnvOptions.proj';
{$ELSE}

The variable SKey_DelphiLibrary64 is not getting defined and thus code cannot compile.

**Comment by mcdurdin** [comment]
Can you try with Delphi 10.2.3? We haven't tested with 10.1 for a while.

**Comment by mcdurdin** [comment]
Closing this issue as solution is to use latest Delphi. Older versions are not supported in the build environment.
