### ISSUE TITLE
Compiler Error - DCPDelphi2009.dpk - Fatal: F1030 IMPLICIT_INTEGER_CAST_LOSS

### ISSUE THREAD

**Issue by YogiYang** [keymanapp/keyman#830]
I am getting this error when trying to build as per instructions:

Run make build from the windows/src folder.

**Comment by mcdurdin** [comment]
Can you try with Delphi 10.2.3? We haven't tested with 10.1 for a while.

**Comment by mcdurdin** [comment]
Closing this issue as solution is to use latest Delphi. Older versions are not supported in the build environment.
