### ISSUE TITLE
bug(common): build failure if child script does not implement called action

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#8321]
In the context of #8290...

https://github.com/keymanapp/keyman/blob/456a2902ae6b8bdd1aaef431b58c6d87d9a1eec0/resources/builder.inc.sh#L279-L289

> I take it this is to avoid scripts failing when called as a child script for a non-existent action? I would prefer to solve this slightly differently, as doing it this way we'll get lots of noise with child script help messages I think?
> 
> Happy for this to be opened as an issue for me to resolve.

_Originally posted by @mcdurdin in https://github.com/keymanapp/keyman/pull/8290#discussion_r1117863631_

I implemented the block as seen above to prevent the scenario referenced in the title.  If the following criteria are met:

1. Parent script defines an action (say, `test`)
2. Child script (say, `:child`) _does not_ define that action.
3. `builder_run_child_actions` is called in such a manner that it matches that child+action pairing - say, `test:child`.

... the build will fail, as child script will output its help page due to specification of an invalid action and will return exit code 64 as defined within `_builder_parameter_error`.

An outright-error is reasonable if the call is for _just_ that pairing, but likely not if other children also exist - especially if at least one _does_ define that action.  Say, `test:sibling` corresponds to a valid child + child-action, and the actual command was `builder_run_child_actions test` - not specifying a particular child script.

**Comment by mcdurdin** [comment]
I think I'd like to resolve this by requiring child scripts to define all actions. The reason is, missing actions are important -- we don't want to accidentally skip them in a build. If the build falls over due to a missing action, adding an empty action to the child script along with a comment in the script as to why there is nothing to do in that action at least documents it.
