### ISSUE TITLE
test(common): Desktop app compatibility tests - Xelah HtmlPerfEditor

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#8324]
The basic idea is to load the example page for each Text Editor (in this case, Xelah HtmlPerfEditor), and then test input with latest release version of Keyman apps and a variety of keyboards.

# Gather Assets for Testing
Install the following keyboards and have the test page link ready to load on the respective browser.
* Keyman app - Latest version - please record the version you use :)
* Khmer Angkor keyboard [package](https://keyman.com/go/package/download/khmer_angkor?version=1.3&tier=stable)
* EuroLatin (SIL) keyboard [pagekage](https://keyman.com/go/package/download/sil_euro_latin?version=2.0&tier=stable)
* Galaxie Hebrew (Positional) keyboard [package](https://keyman.com/go/package/download/galaxie_hebrew_positional?version=2.2&tier=stable)
* IPA (SIL) keyboard [package](https://keyman.com/go/package/download/sil_ipa?version=1.8.6&tier=stable)
* Korean KORDA Jamo (SIL) keyboard [package](https://keyman.com/go/package/download/sil_korda_jamo?version=3.0&tier=stable&bcp47=ko)
* Xelah HtmlPerfEditor test [page](https://xelah-type-perf-html.netlify.app/#htmlperfeditor): delete the first line and type in the text area to test
<img src="https://user-images.githubusercontent.com/28331388/221460859-a81f3777-45ae-4d75-b058-e37c26684b9c.png" width="400">

We need to test in a variety of Operating Systems and Browsers:
* GROUP_WIN10_CHROME: Windows 10 / Chrome browser
* GROUP_WIN10_FIREFOX: Windows 10 / Firefox browser
* GROUP_MACOS_CHROME: macOS / Chrome browser
* GROUP_MACOS_FIREFOX: macOS / Firefox browser
* GROUP_MACOS_SAFARI: macOS / Safari browser
* GROUP_UBUNTU_CHROME: Ubuntu / Chrome browser 
* GROUP_UBUNTU_FIREFOX: Ubuntu / Firefox browser

# User Testing

Xelah HtmlPerfEditor has a test on their homepage: https://xelah-type-perf-html.netlify.app/#htmlperfeditor. Load it up on the respective OS and browser to test the followings:
   * TEST_KHMER_ANGKOR: Khmer Angkor
      * Ensure the key combination <kbd>AltGr</kbd> <kbd>B</kbd> produces `ឞ`. Note that on macOS, the function key to use is right `option`.
      * Type the following (US) keys in sequence: <kbd>s</kbd> <kbd>u</kbd> <kbd>j</kbd> <kbd>r</kbd> <kbd>k</kbd>. You should see `ស្រុក`.
   * TEST_SIL_EURO_LATIN: SIL Euro Latin
      * Type <kbd>%</kbd> <kbd>a</kbd>. Ensure the output is `ǎ`
   * TEST_GALAXIE_HEBREW: Galaxie Hebrew or another good SIL RTL keyboard
      * Type <kbd>b</kbd> <kbd>\\</kbd> <kbd>=</kbd> <kbd>r</kbd> <kbd>@</kbd> <kbd>a</kbd> <kbd>v</kbd> <kbd>!</kbd> <kbd>y</kbd> <kbd>t</kbd> to output `בְּרֵאשִׁית`. FAILED if the output is different.
   * TEST_SIL_IPA: sil_ipa
      * Ensure the key sequence <kbd>n</kbd> <kbd>></kbd> produces `ŋ`.
   * TEST_INTERACTION_WITH_TEXT_FORMATTING:
      * when a Keyman keyboard is active and you are able to enable bold by using the keyboard shortcut (i.e. <kbd>Ctrl</kbd> + <kbd>b</kbd>).
      * PASSED if the bold is enabled on the first character and the rest of the text being typed, otherwise FAILED.
      * _Note that on macOS, the keyboard shortcut for Bold is `command`+`b`._
   * TEST_CJK_IMX: Korean KORDA Jamo (SIL)
      * Type <kbd>h</kbd> <kbd>a</kbd> <kbd>n</kbd> `<space>` <kbd>g</kbd> <kbd>e</kbd> <kbd>u</kbd> <kbd>l</kbd> `<space>`. Verify that the result is `한글`.

**Comment by bharanidharanj** [comment]
### GROUP_UBUNTU_FIREFOX: Ubuntu / Firefox browser

* **TEST_KHMER_ANGKOR (PASSED):** Verified that it is showing the expected output. 

Key Combination1:
    <img width="300" src="https://user-images.githubusercontent.com/19683143/222181987-e653e8e3-6503-41fd-8799-16b13c18519a.PNG">

Key Combination2:
   <img width="300" src="https://user-images.githubusercontent.com/19683143/222181913-dde9d9ab-e80a-4194-9a34-e454a604620d.PNG">


* **TEST_SIL_EURO_LATIN (PASSED):** Verified that it is showing the expected output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/222182103-997c44eb-2b29-4748-aca3-a5df232f3ef2.PNG">

* **TEST_GALAXIE_HEBREW (PASSED):** Verified that it is showing the expected output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/222182153-5c965a7f-1555-4037-b21f-acf83f7075c8.PNG">


* **TEST_SIL_IPA (PASSED):** Verified that it is showing the expected output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/222182186-9e5617ed-6668-40e8-b4e4-e9761438200b.PNG">



* **TEST_INTERACTION_WITH_TEXT_FORMATTING (FAILED):** I noticed that after pressing Ctrl+b shotcut keys, the text did not affect the font style. ie., it always seems to be appear in bold style.  Seems to be an issue. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/222182240-f415f939-3590-41f3-901e-a9e93161089c.PNG">


* **TEST_CJK_IMX (PASSED):** Verified that it is showing the expected output. 

  <img width="300" src="https://user-images.githubusercontent.com/19683143/222182302-8d2b4189-2bdb-4704-aac7-67ef66368dfd.PNG">

**Comment by bharanidharanj** [comment]
### GROUP_WIN10_CHROME: Windows 10 / Chrome browser

* **TEST_KHMER_ANGKOR (PASSED):** Verified that it is showing the expected output.

Output 1:

   <img width="300" src="https://user-images.githubusercontent.com/19683143/223078750-5b9530f8-e931-419d-84ad-891f637d3be3.PNG">


Output 2:

   <img width="300" src="https://user-images.githubusercontent.com/19683143/223078766-a1182aeb-8237-43d7-9dea-6c83ec333348.PNG">


* **TEST_SIL_EURO_LATIN (PASSED):** Verified that it is showing the expected output.s
   
   <img width="300" src="https://user-images.githubusercontent.com/19683143/223078975-f29808cf-2c98-405a-ace2-eebe38ce02e7.PNG">


* **TEST_GALAXIE_HEBREW (PASSED):** Verified that it is showing the expected output.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/223079001-4996755f-87dd-4f49-b528-a852de6e8ea0.PNG">

* **TEST_SIL_IPA (PASSED):** Verified that it is showing the expected output.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/223079189-6378d537-c12b-4737-bc74-a2cd735789c3.PNG">

* **TEST_INTERACTION_WITH_TEXT_FORMATTING (PASSED):** Verified that it is showing the expected output.
   
   <img width="300" src="https://user-images.githubusercontent.com/19683143/223079231-4ecad6b6-4a3a-422e-8fa6-ade51ba2907b.PNG">


* **TEST_CJK_IMX (PASSED):** Verified that it is showing the expected output.

    <img width="300" src="https://user-images.githubusercontent.com/19683143/223079289-738db93b-a173-4bb0-9f12-7b2df5ac4422.PNG">

**Comment by bharanidharanj** [comment]
### GROUP_WIN10_FIREFOX: Windows 10 / Firefox browser

* **TEST_KHMER_ANGKOR (PASSED):** Verified that it is showing the expected output.

Output 1:

   <img width="300" src="https://user-images.githubusercontent.com/19683143/223088316-19bdcb1f-cf09-4298-8eed-3eb0a7d179dd.PNG">


Output 2:

   <img width="300" src="https://user-images.githubusercontent.com/19683143/223088354-71ded47f-43b8-4350-811a-cc0ed9d4df10.PNG">

* **TEST_SIL_EURO_LATIN (PASSED):** Verified that it is showing the expected output.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/223088374-75142818-e4f3-4e01-8221-ea9a85a6d1f4.PNG">

* **TEST_GALAXIE_HEBREW (PASSED):** Verified that it is showing the expected output.
   
   <img width="300" src="https://user-images.githubusercontent.com/19683143/223088405-e3485839-7d6d-41e7-ad3a-91438113a87b.PNG">


* **TEST_SIL_IPA (PASSED):** Verified that it is showing the expected output.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/223088436-354b26e2-808f-41ea-b387-a36d943420ea.PNG">


* **TEST_INTERACTION_WITH_TEXT_FORMATTING (FAILED):** I noticed that after pressing Ctrl+b shotcut keys, the Bookmarks menu opens in the left instead of showing the font style into normal.  Seems to be an issue.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/223088460-4c19750f-aac1-4c88-932f-ba19cfa5eccf.PNG">


* **TEST_CJK_IMX (PASSED):** Verified that it is showing the expected output.
   
   <img width="300" src="https://user-images.githubusercontent.com/19683143/223088483-03184d13-75d3-4424-b4a0-4453e0ed97e6.PNG">

**Comment by bharanidharanj** [comment]
### GROUP_MACOS_CHROME: macOS / Chrome browser

* **TEST_KHMER_ANGKOR (PASSED):** Tested with Keyman 17.0.61-alpha build in macMini Ventura OS and here is my observation: 1. Verified that it is showing the expected output.

Output 1:

   <img width="300" src="https://user-images.githubusercontent.com/19683143/223102358-93113dcb-b0f1-456c-95a4-6d9422b79a63.png">

Output 2:

   <img width="300" src="https://user-images.githubusercontent.com/19683143/223102377-4d329520-5305-482b-a816-f8ac9902e648.png">


* **TEST_SIL_EURO_LATIN (PASSED):** Verified that it is showing the expected output.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/223102392-bf160728-7570-4404-b086-4ce068bf1014.png">

* **TEST_GALAXIE_HEBREW (PASSED):** notes

   <img width="300" src="https://user-images.githubusercontent.com/19683143/223102422-b7f45a9e-996c-4859-b428-974b6fbc3739.png">


* **TEST_SIL_IPA (PASSED):** Verified that it is showing the expected output.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/223102444-aaed81e7-057e-4cb1-bcb9-2bd562e89b9b.png">


* **TEST_INTERACTION_WITH_TEXT_FORMATTING (PASSED):** Pressing Command+b keys shows the Font style changes from bold to normal or normal to bold style. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/223102475-56b7b6a2-dbe6-4851-b1e2-813274fb3985.png">


* **TEST_CJK_IMX (FAILED):** Noticed that after entering space it is showing the square boxes. Seems to be an issue. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/223102586-20833821-5de6-4a27-bdcd-02addcf8b82d.png">

**Comment by bharanidharanj** [comment]
### GROUP_MACOS_FIREFOX: macOS / Firefox browser

* **TEST_KHMER_ANGKOR (PASSED):** Verified that it is showing the expected output.

Output 1:

   <img width="300" src="https://user-images.githubusercontent.com/19683143/223120717-f6c5132d-86a9-49e3-81d7-2113e403e0b3.png">

Output 2:

   <img width="300" src="https://user-images.githubusercontent.com/19683143/223120741-a16be688-37e8-4f71-89bd-8f6885d21ad6.png">


* **TEST_SIL_EURO_LATIN (PASSED):** Verified that it is showing the expected output.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/223120485-b347303e-13de-4031-9212-3d88c881eed3.png">

* **TEST_GALAXIE_HEBREW (FAILED):** Noticed that it is showing the wrong output. 
  
   <img width="300" src="https://user-images.githubusercontent.com/19683143/223121499-099734e5-da21-4be7-b109-d0afa4985605.png">

* **TEST_SIL_IPA (PASSED):** Verified that it is showing the expected output.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/223120588-6c53efe7-356a-4802-8dc8-c04068061267.png">

* **TEST_INTERACTION_WITH_TEXT_FORMATTING (FAILED):** Pressing Command+b keys opens Bookmarks menu in Firefox browser. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/223120600-e9b5fcc3-ddc4-4e09-af9b-b0f761fcce66.png">

* **TEST_CJK_IMX (FAILED):** Noticed that it is showing the wrong output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/223120634-a3b7e680-ad1f-438a-a999-5e3e77f859df.png">

**Comment by bharanidharanj** [comment]
### GROUP_MACOS_SAFARI: macOS / Safari browser

* **TEST_KHMER_ANGKOR (PASSED):**  Verified that it is showing the expected output.

Output 1:
   
   <img width="300" src="https://user-images.githubusercontent.com/19683143/223130231-71d00ff2-749c-4eea-ad83-e51bc9868bf2.png">


Output 2: 
   
   <img width="300" src="https://user-images.githubusercontent.com/19683143/223130251-2f025ac7-8ea8-46d1-9f9c-3d1696434a91.png">


* **TEST_SIL_EURO_LATIN (PASSED):**  Verified that it is showing the expected output.
   
   <img width="300" src="https://user-images.githubusercontent.com/19683143/223130317-2c9a7098-f9f2-4fbc-9a6c-381235767814.png">


* **TEST_GALAXIE_HEBREW (PASSED):**  Verified that it is showing the expected output.
   <img width="300" src="https://user-images.githubusercontent.com/19683143/223130347-691b0fec-d880-4b52-aeba-c0dd0e42caa2.png">


* **TEST_SIL_IPA (PASSED):**  Verified that it is showing the expected output.
   <img width="300" src="https://user-images.githubusercontent.com/19683143/223130368-6a1371d2-34be-4c25-9934-e6236dfd9612.png">


* **TEST_INTERACTION_WITH_TEXT_FORMATTING (FAILED):** Pressing Command+b keys did not do anything on the screen. Seems to be not working. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/223130680-7a82e69a-95a7-4817-8c7a-547cc91ede74.png">


* **TEST_CJK_IMX (FAILED):** Noticed that it is showing the wrong output.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/223130719-4fcfc1bf-d1d7-459e-b449-cd9d5a2a3c90.png">

**Comment by MakaraSok** [comment]
# Test Results

* GROUP_WIN10_CHROME: Windows 10 / Chrome browser

	Chrome Version 112.0.5615.138 (Official Build) (64-bit) on Windows 10 Pro 21H2 with Keyman for Windows Version 17.0.90-alpha.

	<img width=300 src="https://user-images.githubusercontent.com/28331388/233261901-04aee38e-7c10-483e-9266-0793e1b8d9b8.png">

    * TEST_KHMER_ANGKOR (PASSED): shown as expected
    * TEST_SIL_EURO_LATIN (PASSED): shown as expected
    * TEST_GALAXIE_HEBREW (PASSED): shown as expected
    * TEST_SIL_IPA (PASSED): shown as expected
    * TEST_INTERACTION_WITH_TEXT_FORMATTING (PASSED): behaved as expected
    * TEST_CJK_IMX (PASSED): shown as expected

* GROUP_WIN10_FIREFOX: Windows 10 / Firefox browser

	Firefox Version 112.0.1 (64-bit) on Windows 10 Pro 21H2 with Keyman for Windows Version 17.0.90-alpha.

	<img width=300 src="https://user-images.githubusercontent.com/28331388/233264822-d8e69b09-3e27-4de4-a002-97228bb333be.png">

    * TEST_KHMER_ANGKOR (PASSED): shown as expected
    * TEST_SIL_EURO_LATIN (PASSED): shown as expected
    * TEST_GALAXIE_HEBREW (PASSED): shown as expected
    * TEST_SIL_IPA (PASSED): shown as expected
    * TEST_INTERACTION_WITH_TEXT_FORMATTING (FAILED): not behaved as expected. Each formatting shortcut triggers Firefox’s command, i.e. Ctrl+B - Bookmark, Ctrl+I - Page Info and Ctrl+U - Source code
    * TEST_CJK_IMX (PASSED): shown as expected

* GROUP_MACOS_CHROME: macOS / Chrome browser

	Google Chrome Version 112.0.5615.121 (Official Build) (x86_64) on macOS Ventura 13.3.1 with Keyman for macOS Version 17.0.90-alpha.

	<img width=300 alt="image" src="https://user-images.githubusercontent.com/28331388/233297889-7d34bd44-b0a8-425b-9492-24ce762bb80e.png">

    * TEST_KHMER_ANGKOR (PASSED): shown as expected
    * TEST_SIL_EURO_LATIN (PASSED): shown as expected
    * TEST_GALAXIE_HEBREW (PASSED): shown as expected
    * TEST_SIL_IPA (PASSED): shown as expected
    * TEST_INTERACTION_WITH_TEXT_FORMATTING (PASSED): behaved as expected
    * TEST_CJK_IMX (FAILED): not shown as expected

* GROUP_MACOS_FIREFOX: macOS / Firefox browser

	Firefox Browser Version 112.0.1 (64-bit) on macOS Ventura 13.3.1 with Keyman for macOS Version 17.0.90-alpha.

	<img width=300 alt="image" src="https://user-images.githubusercontent.com/28331388/233295907-63eb942c-f8cc-4a9d-880a-bac8517fd271.png">

    * TEST_KHMER_ANGKOR (PASSED): shown as expected
    * TEST_SIL_EURO_LATIN (PASSED): shown as expected
    * TEST_GALAXIE_HEBREW (PASSED): shown as expected
    * TEST_SIL_IPA (PASSED): shown as expected
    * TEST_INTERACTION_WITH_TEXT_FORMATTING (FAILED): not behaved as expected. The shortcuts triggered Firefox’s command instead of text formatting.
    * TEST_CJK_IMX (PASSED): shown as expected

* GROUP_MACOS_SAFARI: macOS / Safari browser

	Safari on macOS Ventura 13.3.1 with Keyman for macOS Version 17.0.90-alpha.

	<img width=300 alt="image" src="https://user-images.githubusercontent.com/28331388/233294029-c6ac72c9-9a0f-4045-952e-f60663eaad07.png">

    * TEST_KHMER_ANGKOR (PASSED): shown as expected
    * TEST_SIL_EURO_LATIN (PASSED): shown as expected
    * TEST_GALAXIE_HEBREW (PASSED): shown as expected
    * TEST_SIL_IPA (PASSED): shown as expected
    * TEST_INTERACTION_WITH_TEXT_FORMATTING (FAILED): not behaved as expected. The shortcuts triggered Safari’s command instead of text formatting.
    * TEST_CJK_IMX (FAILED): not shown as expected

* GROUP_UBUNTU_CHROME: Ubuntu / Chrome browser

	Chromium Web Browser Version 112.0.5615.49 (Official Build) snap (64-bit) on Ubuntu 20.04.6 LTS (64-bit) with Keyman for Linux Version 17.0.90-alpha (package version 17.0.90-1~sil1~focal).

	<img width=300 src="https://user-images.githubusercontent.com/28331388/233290596-213d56d2-d43e-4cd5-a806-ccb20166278e.png">

    * TEST_KHMER_ANGKOR (FAILED): not shown as expected
    * TEST_SIL_EURO_LATIN (FAILED): not shown as expected
    * TEST_GALAXIE_HEBREW (PASSED): shown as expected
    * TEST_SIL_IPA (FAILED): not shown as expected
    * TEST_INTERACTION_WITH_TEXT_FORMATTING (PASSED): behaved as expected
    * TEST_CJK_IMX (FAILED): not shown as expected

* GROUP_UBUNTU_FIREFOX: Ubuntu / Firefox browser

	Firefox Browser Version 112.0.1 (64-bit) on Ubuntu 20.04.6 LTS (64-bit) with Keyman for Linux Version 17.0.90-alpha (package version 17.0.90-1~sil1~focal).

	<img width=300 src="https://user-images.githubusercontent.com/28331388/233291754-5eb09001-8aef-4757-8d41-0465a187348c.png">

    * TEST_KHMER_ANGKOR (FAILED): not shown as expected
    * TEST_SIL_EURO_LATIN (FAILED): not shown as expected
    * TEST_GALAXIE_HEBREW (PASSED): shown as expected
    * TEST_SIL_IPA (FAILED): not shown as expected
    * TEST_INTERACTION_WITH_TEXT_FORMATTING (PASSED): behaved as expected
    * TEST_CJK_IMX (FAILED): not shown as expected

**Comment by MakaraSok** [comment]
- [x] verification test
- [x] no retest requested
