### ISSUE TITLE
bug(ios): the version numbers of Keyman in the App Store and in Keyman app itself are not consistent 

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#8343]
### Describe the bug

The version numbers of Keyman in the App Store (at the time of writing this report) is `16.0.138`, but after installing Keyman, within the app itself the version number shown is `16.0.137`.

| In App Store | In Keyman App - About page |
| --- | --- |
| <img width="300" src="https://user-images.githubusercontent.com/28331388/222063201-bc319c63-f02a-490a-8501-d8806bcb43e6.jpg"> | <img width="300" src="https://user-images.githubusercontent.com/28331388/222062962-e6c01549-6ec4-4f76-9393-0147e1caba97.jpeg"> |

### Keyman apps

- [ ] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

?

### Operating system

iOS 16.3.1

### Device

iPad mini 6

### Target application

Keyman for iOS 

### Browser

n/a

### Keyboard name

n/a

### Keyboard version

n/a

### Language name

n/a

### Additional context

The same behavior is seen in Keyman for iOS running on iPod touch.

**Comment by darcywong00** [comment]
I think this was just an artifact of the stable-16.0 release process.
Both 16.0.137 and 16.0.138 were published close to each other, so the Apple Store rejected the 138 build.

I believe both apps are identical, and this will get sorted when 16.0.139 gets published.

**Comment by darcywong00** [comment]
@MakaraSok - can you repro with 16.0.139?

**Comment by MakaraSok** [comment]
@darcywong00 The version numbers look identical now for 16.0.139. Tested with iPadOS 16.4.1 (a) with Keyman of the aforementioned version number.

![893E0AAB-5340-4068-B8C8-A130A7FC9D86_1_201_a](https://user-images.githubusercontent.com/28331388/235605086-673475aa-4518-45e4-9ac7-6934b7a1316b.jpeg)

**Comment by darcywong00** [comment]
Version numbers match, so closing issue.
