### ISSUE TITLE
[Web] moveToElement does not accept element ID strings any more

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#836]
This issue was found in the Keyman Developer Web Debugger.

Chrome Version 64.0.3282.140 (Official Build) (64-bit)
Keyman Developer Version 10.0.1000.0

Uncaught TypeError: e.focus is not a function
    at DOMManager.moveToElement (kmwdom.ts:1330)
    at KeymanBase.moveToElement (kmwbase.ts:483)
    at olympus.phnompenh.keyman.com/:123

**Comment by MakaraSok** [comment]
@jahorton Could you confirm whether or not this issue is fixed in the latest version of Keyman Developer?

**Comment by jahorton** [comment]
As it hasn't been happening since the initial report and the team's been using Developer and the debugger frequently, we'll go ahead and close this until we get additional confirmation.
