### ISSUE TITLE
refactor(common): Refactor build-help.sh as helper functions for all platforms

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#8363]
Are you intending to convert this to a builder script in the future as well? It's a little awkward to have a script in a sub-folder calling a higher-level one.

_Originally posted by @mcdurdin in https://github.com/keymanapp/keyman/pull/7407#discussion_r1122690568_

This refactors the build-help.sh scripts in all the platforms to apply the builder pattern. (And possibly move down to the app folders)

**Comment by darcywong00** [comment]
From A17S8 planning meeting, we may intially try this on Android (rather than wait on all products e.g Windows/developer to migrate to builders)

So would the builder actions be: ?

### clean
rm the output htm folder

### configure
??

### build
pandoc from markdown to htm

@mcdurdin - is migrating resources/build/help-keyman-com.sh a separate endavour?

**Comment by darcywong00** [comment]
via Slack, @mcdurdin gave more direction. Instead of builder patterns, 

> It should probably be organised as helper functions in a .inc.sh script given the outputs are in the platform folders.

**Comment by darcywong00** [comment]
Linux will be tricky. I note its build-help.sh script uses different tooling: `help2man` and `help2md`

**Comment by mcdurdin** [comment]
> Linux will be tricky. I note its build-help.sh script uses different tooling: `help2man` and `help2md`

Can we talk about consolidation with @ermshiperete?

**Comment by ermshiperete** [comment]
`help2man` and `help2md` serve slightly different purposes than what this issue is about. This issue talks about converting .md to HTML. The two Linux tools take the output of the python scripts (e.g. `km-config --help`) to create a man page, or a .md file (which can then be converted to HTML by the script this issue talks about).

**Comment by mcdurdin** [comment]
OK, that's good -- the linux scripts will do the conversion to .md first, and then can call the build-help.inc.sh functions to do the conversion to html.
