### ISSUE TITLE
chore(common): Make `--debug` a globally inheritable option for builder

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#8373]
True. `--debug` is an option that we want to be passing through to dependency builds. I need to do some work on that particular feature -- I'll make a sub-PR of this one.

I actually think we should never spec `--debug` in `builder_describe` but it should always be available, and _always_ be passed to child scripts and dependency scripts. (If the script doesn't use it, it doesn't hurt!)

Note: `-d` is shorthand for `--debug`.

`--debug` may be the only option we do that with for now, but there may be others in the future?

_Originally posted by @mcdurdin in https://github.com/keymanapp/keyman/pull/8371#discussion_r1125981899_

**Comment by darcywong00** [comment]
Just checking
Will web/build.sh need to see the global --debug option before describing outputs?
Specifically, Keyman Engine for Android could be expecting either:
* build/app/embed/release/keyman.js 
* build/app/embed/debug/keyman.js  

https://github.com/keymanapp/keyman/blob/19b21e3bf6e5d2a589af06730fdbe1a62a550c6f/web/build.sh#L51-L66

**Comment by mcdurdin** [comment]
Yes, we should think about this for web/build.sh. 'debug' builds for web are essentially non-minified builds -- the release builds are generated from the debug builds.
