### ISSUE TITLE
chore(core): meson deprecated features

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#8399]
```
NOTICE: Future-deprecated features used:
 * 0.56.0: {'meson.source_root'}
```

**Comment by mcdurdin** [comment]
We are still on 0.53 for Linux at this stage so cannot deal with this currently.

**Comment by mcdurdin** [comment]
@ermshiperete, are we on meson 1.0 for Linux builds now?

**Comment by ermshiperete** [comment]
yes, we can use meson 1.0. We run package builds for older Ubuntu versions on our own infrastructure where we added a meson 1.0 package. Current Debian and Ubundu versions come with meson > 1.0, so it's no problem there either.
