### ISSUE TITLE
Running Make Build removes all Paths in my Delphi IDE

### ISSUE THREAD

**Issue by YogiYang** [keymanapp/keyman#841]
Hello,
When Running Make Build it removes all paths from my Delphi IDE.

What mistake I may be making please guide?

I am using Delphi Berlin 10.1.

**Comment by mcdurdin** [comment]
The Keyman build environment restricts the paths to a known set in order to avoid conflict with other packages. You may find it most appropriate to build in a VM dedicated to Keyman, for Keyman's Delphi projects.

**Comment by YogiYang** [comment]
Thanks for the info.

But I feel this should be very clearly stated somewhere so that we know well in advance before we try out the code here!

**Comment by mcdurdin** [comment]
To do: add warning in build environment documentation about this
