### ISSUE TITLE
feat(common): ldml add some extra vkey mappings 🙀 

### ISSUE THREAD

**Issue by srl295** [keymanapp/keyman#8413]
```
ERROR 300009: Virtual key 'BKQUOTE' is not found in the CLDR VKey Enum table.
ERROR 300009: Virtual key 'MINUS' is not found in the CLDR VKey Enum table.
ERROR 300009: Virtual key 'LBRKT' is not found in the CLDR VKey Enum table.
ERROR 300009: Virtual key 'LBRKT' is not found in the CLDR VKey Enum table.
ERROR 300009: Virtual key 'RBRKT' is not found in the CLDR VKey Enum table.
ERROR 300009: Virtual key 'COLON' is not found in the CLDR VKey Enum table.
ERROR 300009: Virtual key 'BKQUOTE' is not found in the CLDR VKey Enum table.
ERROR 300009: Virtual key 'EXCLAMATION' is not found in the CLDR VKey Enum table.
```

and

```xml
		<vkey from="BKQUOTE" to="QUOTE" /> <!-- i.e., OEM_3 >>> OEM_7 -->
		<vkey from="SLASH" to="EXCLAMATION" /> <!-- i.e., OEM_2 >>> OEM_8 -->
```

these names are mentioned in the spec and test files. Add them as aliases.

**Comment by srl295** [comment]
blocks consuming the fr-azerty keyboard from ldml

**Comment by mcdurdin** [comment]
COLON and EXCLAMATION are names that are specific to the French keyboard, from what I recall:

PLUS, COMMA, MINUS and PERIOD are defined in winuser.h:

```
#define VK_OEM_PLUS       0xBB   // '+' any country
#define VK_OEM_COMMA      0xBC   // ',' any country
#define VK_OEM_MINUS      0xBD   // '-' any country
#define VK_OEM_PERIOD     0xBE   // '.' any country
```

"any country" is a bit of an interesting choice of words.

Also, see:

```
#define VK_OEM_1          0xBA   // ';:' for US
#define VK_OEM_2          0xBF   // '/?' for US
#define VK_OEM_3          0xC0   // '`~' for US
#define VK_OEM_4          0xDB  //  '[{' for US
#define VK_OEM_5          0xDC  //  '\|' for US
#define VK_OEM_6          0xDD  //  ']}' for US
#define VK_OEM_7          0xDE  //  ''"' for US
#define VK_OEM_8          0xDF

#define VK_OEM_102        0xE2  //  "<>" or "\|" on RT 102-key kbd.
```

So these are mostly 'up for grabs' -- VK_OEM_8 == EXCLAMATION on French but not necessarily elsewhere.

A good design would probably lean towards avoiding definition of virtual keys for any character-generating key in the future -- virtual key identifiers would be reserved for keys that have no character output. Then hotkeys (or shortcut keys) that use character keys would always be defined as `[modifer(s)+] Unichar`, and other hotkeys are `[modifiers(s)+] VK`. This resolves the whole "define a VK for every character" conundrum, but does force app developers into a world of pain wrt an ever expanding set of hotkey definitions -- at the very least, one defn per script. (A decent fallback for apps is to use QWERTY defns for non-Latin scripts when no hotkey defns for that script have been defined.)

It's worth noting that Windows does already do this with `WM_SYSCHAR`, but that only handles plain Alt+char, and not Ctrl or Shift or combinations thereof.

And of course some pseudo-control-character keys like Tab, Enter, Backspace, Esc may still need some special sauce.

**Comment by srl295** [comment]
actually there is vkey `GRAVE` in virtual-key-constants.ts which maps to `K_BKQUOTE`

**Comment by srl295** [comment]
same with LBRACKET and RBRACKET

**Comment by srl295** [comment]
It sounds like MINUS, COLON, COMMA, EXCLAMATION will perhaps remain platform specific extensions of some sort?
