### ISSUE TITLE
bug(developer): Tabs hard to distinguish in Keyman Developer

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#845]
I’m working on a keyboard and I just wanted to tell you that it is hard to distinguish between the second and third tab below to know which one is active. Could you please give more visual cues to make it clear. In this case the 3rd is active, but sometimes I think the 2nd is.

![image](https://user-images.githubusercontent.com/4498365/39790353-c0970358-535f-11e8-809d-b285b10d6461.png)

**Comment by markpenny** [comment]
And while you're working on this, please note that it is just as difficult to work out which vertical TAB is active. Some more highlighting or colour would be much appreciated!
![image](https://user-images.githubusercontent.com/12962708/56082283-b638d900-5e34-11e9-8826-38024f2bb3b4.png)

**Comment by mcdurdin** [comment]
See also: #228, #3224.

**Comment by mcdurdin** [comment]
See also https://community.software.sil.org/t/coloured-active-tab-in-developer/4148
