### ISSUE TITLE
bug(linux) : Failed message appear in the Terminal window while closing Keyman Configuration dialog

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#8454]
### Describe the bug

I noticed that clicking the on the Close button in the Keyman Configuration dialog, shows an error message in the Terminal window. 

### Reproduce the bug

1. In Ubuntu 22.04, install Keyman 17.0.68 alpha build. 
2. Open the Terminal window. 
3. Run km-config
4. We may notice that the Keyman Configuration dialog opens. 
5. Click the Close (x) icon which appears at the top right corner of the dialog. 
6. We may noticed that the Configuration dialog closes and the nothing outputs behind the terminal window. 
7. Run km-config
8. In the Keyman Configuration dialog, Click the Close button which appears at the bottom right of the dialog. 
9. Here, I noticed that there is an error message appears on the terminal window. 

..Click the Close icon 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/225644097-e6b5ead8-4de9-458c-977e-91a815418db3.PNG">

..Click the Close button

   <img width="300" src="https://user-images.githubusercontent.com/19683143/225644140-68649a1a-c82b-4f5b-922e-bbdf5617e534.PNG">

### Expected behavior

The error message should not appear after clicking the Close button. 

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [X] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.68-alpha

### Operating system

Ubuntu 22.04 Jammy Jelly Fish Linux OS

**Comment by ermshiperete** [comment]
Good find, @bharanidharanj. I always ignored that message, but it's a real problem.

**Comment by bharanidharanj** [comment]
> Good find, @bharanidharanj. I always ignored that message, but it's a real problem.

Thank you, @ermshiperete .
