### ISSUE TITLE
test(common): Mobile app compatibility tests - Xelah HtmlPerfEditor

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#8460]
The basic idea is to load the app (or test page), and then test input with latest release version of Keyman apps and a variety of keyboards.

## Gather Assets for Testing
Install the following keyboards and have the test page link ready to load on the respective browser.
* Keyman app - Latest version (please record the version in the test results)
* Khmer Angkor keyboard [package](https://keyman.com/go/package/download/khmer_angkor?version=1.3&tier=stable)
* EuroLatin (SIL) keyboard [pagekage](https://keyman.com/go/package/download/sil_euro_latin?version=2.0&tier=stable)
* Galaxie Hebrew (Positional) keyboard [package](https://keyman.com/keyboards/galaxie_greek_hebrew_positional)
* IPA (SIL) keyboard [package](https://keyman.com/go/package/download/sil_ipa?version=1.8.6&tier=stable)
* Xelah HtmlPerfEditor test [page](https://xelah-type-perf-html.netlify.app/#htmlperfeditor): delete the first line and type in the text area to test
<img src="https://user-images.githubusercontent.com/28331388/221460859-a81f3777-45ae-4d75-b058-e37c26684b9c.png" width="400">

## User Testing
The app may need to be tested in multiple environments. Each environment can be defined as a group here. For example, if you wanted to test a web app, you may have the following groups:
* GROUP_IOS_SAFARI: iOS / Safari browser
* GROUP_IOS_CHROME: iOS / Chrome browser
* GROUP_ANDROID_CHROME: Android / Chrome browser
* GROUP_ANDROID_FIREFOX: Android / Firefox

Load "the app or 'test page' being tested" on the respective OS (and browser) to test the followings:
   * TEST_KHMER_ANGKOR: Khmer Angkor
      * Ensure longpress on <kbd>ស</kbd> and choose <kbd>ឞ</kbd> to produce `ឞ`.
      * Type <kbd>ស</kbd> <kbd>ុ</kbd> <kbd>្រ</kbd> (longpress of <kbd>រ</kbd>) <kbd>ក</kbd> to produce `ស្រុក`.
   * TEST_SIL_EURO_LATIN: SIL Euro Latin
      * Longpress on <kbd>a</kbd> and choose <kbd>ǎ</kbd> to output `ǎ`
   * TEST_GALAXIE_HEBREW: Galaxie Hebrew mentioned above and here is [how to](https://docs.google.com/spreadsheets/d/e/2PACX-1vS6GnYMo3WB-m7Mj8_4IMzz54MCDNECh01bsuI5epx7LJo28VMSJY8aT9WRbGms6bb_k4DSbNrf7uHZ/pubhtml?gid=0&single=true) type each key.
      * Type <kbd>b</kbd> <kbd>\\</kbd> <kbd>=</kbd> <kbd>r</kbd> <kbd>@</kbd> <kbd>a</kbd> <kbd>v</kbd> <kbd>!</kbd> <kbd>y</kbd> <kbd>t</kbd> to output `בְּרֵאשִׁית`. FAILED if the output is different.
   * TEST_SIL_IPA: sil_ipa
      * Ensure the key sequence <kbd>n</kbd> <kbd>></kbd> (long press of <kbd>]</kbd> on `123` layer) produces `ŋ`.
   * TEST_INTERACTION_WITH_TEXT_FORMATTING: 
      * (n/a for the time being)
   * TEST_CJK_IMX: 
      * (n/a for the time being)

**Comment by bharanidharanj** [comment]
### GROUP_IOS_SAFARI: iOS / Safari browser

* **TEST_KHMER_ANGKOR (PASSED):** Tested with the  latest Keyman 17.0.72-alpha build in iOS 16.2 /  iPhone 14 Pro Max Simulator and it is showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/226564369-856fc178-7239-4251-909f-7d70de194675.png">

* **TEST_SIL_EURO_LATIN (PASSED):** Tested with the latest Keyman build and it is showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/226564410-7b74d3b7-6a35-411f-8415-beae11ce7ee8.png">


* **TEST_GALAXIE_HEBREW (PASSED):** Tested with the latest Keyman build and it is showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/226564427-9da39e42-3c4a-4683-b360-711d9d716f8c.png">

* **TEST_SIL_IPA (PASSED):** Tested with the latest Keyman build and it is showing the correct output.

    <img width="300" src="https://user-images.githubusercontent.com/19683143/226564475-73abd0b0-7036-406d-aee5-54c52a284416.png">

* **TEST_INTERACTION_WITH_TEXT_FORMATTING (SKIPPED):** As per the instructions, this test is not applicable for time being. Hence, I skipped the test. 
* **TEST_CJK_IMX (SKIPPED):** As per the instructions, this test is not applicable for time being. Hence, I skipped the test.

**Comment by bharanidharanj** [comment]
### GROUP_IOS_CHROME: iOS / Chrome browser

* **TEST_KHMER_ANGKOR (SKIPPED):** Not able to install Chrome browser in iPhone Simulator, but the chrome browser is working in real iOS device.  It seems that the results that appear in the Safari browser will give the same result in Chrome browser. Hence, I skipped the test in Chrome browser. Thanks. 
* **TEST_SIL_EURO_LATIN (SKIPPED):** I skipped this test since the Safari browser and chrome browser would produce the same result. (Please, find my previous results that I have tested in Safari browser)
* **TEST_GALAXIE_HEBREW (SKIPPED):** I skipped this test since the Safari browser and chrome browser would produce the same result. (Please, find my previous results that I have tested in Safari browser)
* **TEST_SIL_IPA (SKIPPED):** I skipped this test since the Safari browser and chrome browser would produce the same result. (Please, find my previous results that I have tested in Safari browser)
* **TEST_INTERACTION_WITH_TEXT_FORMATTING (SKIPPED):** As per the instructions, this test is not applicable for time being. Hence, I skipped the test.
* **TEST_CJK_IMX (SKIPPED):** As per the instructions, this test is not applicable for time being. Hence, I skipped the test.

**Comment by bharanidharanj** [comment]
### GROUP_ANDROID_CHROME: Android / Chrome browser

* **TEST_KHMER_ANGKOR (PASSED):** Tested with the latest Keyman 17.0.72-alpha build in my Android Mobile device (Ver 11.0) and it is showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/226581964-31213b70-4c97-4be3-bcf2-9663fbfb7583.jpg">

* **TEST_SIL_EURO_LATIN (PASSED):** Tested with the latest Keyman 17.0.72-alpha build in my Android Mobile device (Ver 11.0) and it is showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/226582006-120c8453-5d9e-47ac-8ef1-ff68142aaaf2.jpg">

* **TEST_GALAXIE_HEBREW (PASSED):** Tested with the latest Keyman 17.0.72-alpha build in my Android Mobile device (Ver 11.0) and it is showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/226582114-497a5e89-427d-42f7-a2c2-fd3f9e410ab5.jpg">


* **TEST_SIL_IPA (PASSED):** Tested with the latest Keyman 17.0.72-alpha build in my Android Mobile device (Ver 11.0) and it is showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/226582150-17fba2fd-cdbb-4ce8-9046-9601004d9a2e.jpg">

* **TEST_INTERACTION_WITH_TEXT_FORMATTING (SKIPPED):** As per the instructions, this test is not applicable for time being. Hence, I skipped the test.
* **TEST_CJK_IMX (SKIPPED):** As per the instructions, this test is not applicable for time being. Hence, I skipped the test.

**Comment by bharanidharanj** [comment]
# Test Results

### GROUP_ANDROID_FIREFOX: Android / Firefox

* **TEST_KHMER_ANGKOR (OPEN):**  Tested with the latest Keyman 17.0.72-alpha build in my Android Mobile device (Ver 11.0) and it is showing the correct output.
   
   <img width="300" src="https://user-images.githubusercontent.com/19683143/226585322-b2e45481-e4d5-440f-98b5-a5aaeea23363.jpg">


* **TEST_SIL_EURO_LATIN (OPEN):**  Tested with the latest Keyman 17.0.72-alpha build in my Android Mobile device (Ver 11.0) and it is showing the correct output.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/226585363-0e62d727-a109-4743-9584-3e62f6031f07.jpg">


* **TEST_GALAXIE_HEBREW (OPEN):**  Tested with the latest Keyman 17.0.72-alpha build in my Android Mobile device (Ver 11.0) and it is showing the correct output.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/226585400-ef571225-5718-4489-b8cb-c825cf53650b.jpg">


* **TEST_SIL_IPA (OPEN):**  Tested with the latest Keyman 17.0.72-alpha build in my Android Mobile device (Ver 11.0) and it is showing the correct output.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/226585444-6b4b80d7-c88f-41d4-96bc-bfe63c055f45.jpg">


* **TEST_INTERACTION_WITH_TEXT_FORMATTING (OPEN):** As per the instructions, this test is not applicable for time being. Hence, I skipped the test.

* **TEST_CJK_IMX (OPEN):** As per the instructions, this test is not applicable for time being. Hence, I skipped the test.

**Comment by MakaraSok** [comment]
### GROUP_IOS_CHROME: iOS / Chrome browser

Tested with the  latest Keyman 17.0.86-alpha build in iOS 16.4.1 /  iPad mini 6 and it is showing the correct output. 

<img width="300" src="https://user-images.githubusercontent.com/28331388/231630073-46f10cc4-3f9c-4c4b-bc89-eab53b9db724.jpeg">

* **TEST_KHMER_ANGKOR (PASSED):** 
* **TEST_SIL_EURO_LATIN (PASSED):** 
* **TEST_GALAXIE_HEBREW (PASSED):** 
* **TEST_SIL_IPA (PASSED):**

**Comment by MakaraSok** [comment]
- [x] verification test
- [x] no retest requested
