### ISSUE TITLE
feat(core): integrate ICU4C into the build for ldml 🙀

### ISSUE THREAD

**Issue by srl295** [keymanapp/keyman#8495]
- download tarball and use (ala Node.js)
- static link, and static link libstdc++ (no DLLs on win)
- no data
- common / icu-uc only 

For tests, make io available?

Unblocks:
- #7234
- #8435

**Comment by srl295** [comment]
now this is very interesting => https://mesonbuild.com/Wrapdb-projects.html

**Comment by mcdurdin** [comment]
Does #8441 fix this?

**Comment by srl295** [comment]
It's in the build there but not in the core lib proper. So maybe close it and open a followon?

**Comment by mcdurdin** [comment]
We'll track completion of this in #8441 then. No need to open a followon.

**Comment by srl295** [comment]
SGTM
