### ISSUE TITLE
refactor(linux): avoid using tests from Core in Linux source

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#8504]
Right now, we have a deep cross-module dependency from Linux to on test fixtures in Core. I am trying to cleanup these fixtures in #8503, but this breaks the Linux build -- because we no longer store any .kmx in the repo.

```
  ――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――
  Can't find kmx files in /build/linux/ibus-keyman/tests/../../../core/tests/unit/kmx
  ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
```

Deep dependencies are fragile because there is no expectation that other modules depend on the test fixtures, and so changes cause ripple effects, and also make it difficult to maintain the tests.

Two parts to the solution for this:

1. Move the .kmn fixtures to common and building them there as a separate build step, otherwise copy the fixtures to the Linux build
2. Update Linux build to build the fixtures also.

See also:
* #8499

**Comment by ermshiperete** [comment]
Depends on #8527

**Comment by mcdurdin** [comment]
Note: .kmx are required for kmcmplib so we should not need to include kmc in the Debian packaging. If we do want kmc to be available as a Debian package (yes please!), it should be its own package.
