### ISSUE TITLE
bug(developer): kmc should not validate as well as compile ldml keyboard

### ISSUE THREAD

**Issue by srl295** [keymanapp/keyman#8512]
```console
HINT 100008: Locale 'pt-BR-t-k0-abnt2' is not minimal or correctly formatted and should be 'pt-t-k0-abnt2'
HINT 100008: Locale 'pt-BR-t-k0-abnt2' is not minimal or correctly formatted and should be 'pt-t-k0-abnt2'
```

“There now, I've said it twice.”

I think we could dedup compiler messages that are exactly identical. At least before output to the screen. Note that part of the cause is that the same validation is done twice, such as in keys and in layr.

**Comment by mcdurdin** [comment]
Given command:
```
mcdurdin@THARK MINGW64 /c/Projects/keyman/app/developer/src/kmc $ node --inspect-brk . build /c/Projects/keyman/app/resources/standards-data/ldml-keyboards/techpreview/3.0/pt-BR-k0-abnt2.xml 
```

First instance stack:
```
compile				@	loca.ts:44
compile				@	compiler.ts:147
validate			@	compiler.ts:120
buildLdmlKeyboardToMemory	@	BuildLdmlKeyboard.ts:58
build				@	BuildLdmlKeyboard.ts:16
build				@	build.ts:39
(anonymous)			@	build.ts:21
```

Second instance stack:
```
compile				@	loca.ts:44
compile				@	compiler.ts:147
buildLdmlKeyboardToMemory	@	BuildLdmlKeyboard.ts:61
build				@	BuildLdmlKeyboard.ts:16
build				@	build.ts:39
(anonymous)			@	build.ts:21
```

This suggests that many parts of the compiler are actually running twice -- first in validate, and then in compile. That sounds worse than merely emitting the same hint twice :grin:

**Comment by srl295** [comment]
> This suggests that many parts of the compiler are actually running twice -- first in validate, and then in compile. That sounds worse than merely emitting the same hint twice 

`Compiler.validate()` validates by compiling again and throwing the result away.  It's useful in loadSectionFixture in some sense because it checks ALL sections not just the one under test.


```js
  /**
   * Validates that the LDML keyboard source file and lints. Actually just
   * compiles the keyboard and returns `true` if everything is good...
   * @param     source
   * @returns   true if the file validates
   */
  public validate(source: LDMLKeyboardXMLSourceFile): boolean {
    return !!this.compile(source);
  }
```


1. Maybe what we should do is just not call `validate` again from `buildLdmlKeyboard.ts`? Just remove the call to `validate`?  Then leave the API for if you want to ONLY validate and not compile?

```js
  if (!k.validate(source)) {
    return [null, null, null];
  }
  let kmx = k.compile(source);
  if (!kmx) {
    return [null, null, null];
  }
```


2. Otherwise, could add an API trail that has a validate-only path.

The duplication does come sometimes from when two sections give the same error. In that case I've tried to have only one section give the same error.
