### ISSUE TITLE
chore(linux): stray ibus-engine-keyman left running post CI builds

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#8517]
ps aux gives:

```
bob       970553  0.0  0.0 258316   624 ?        Sl   Feb21   0:00 /var/lib/TeamCity/agent/work/99b311828f4ee7c/keyman/linux/build/x86_64/release/tests/../src/ibus-engine-keyman
bob      2660136  0.0  0.9 310128 40100 ?        Sl   Feb10   6:46 /var/lib/TeamCity/agent/work/99b311828f4ee7c/keyman/linux/build/x86_64/release/tests/../src/ibus-engine-keyman
bob      2689737  0.0  0.0 258244   624 ?        Sl   Feb10   0:00 /var/lib/TeamCity/agent/work/99b311828f4ee7c/keyman/linux/build/x86_64/release/tests/../src/ibus-engine-keyman
```

We can of course just kill these three, and it may be due to an old issue given their start date, but wanted to track it just in case.

**Comment by ermshiperete** [comment]
I'm not sure how it could happen that those processes are left running, but #8536 tries to improve robustness.

**Comment by mcdurdin** [comment]
I think it could happen if the build is cancelled for another reason -- and cleanup doesn't happen. So it may be that additional robustness still won't help in that case.
