### ISSUE TITLE
bug(core): slash/backslash path issues in copying files

### ISSUE THREAD

**Issue by srl295** [keymanapp/keyman#8524]
found on PR #8513 

`tests\unit\ldml\keyboards\meson.build:77:2: ERROR: Command "C:\WINDOWS\system32\cmd.exe /c copy C:/BuildAgent/work/99b311828f4ee7c/keyman/core/../resources/standards-data/ldml-keyboards/techpreview/3.0/ja-Latn.xml C:\BuildAgent\work\99b311828f4ee7c\keyman\core\build\x86\release\tests\unit\ldml\keyboards\ja-Latn.xml" failed with status 1.`

these meson-generated paths worked under linux and windows, but failed on Windows (`cmd.exe /c copy` was not happy about mixing slash and backslash).

**Comment by mcdurdin** [comment]
We should use `configure_file` to copy files; see https://github.com/keymanapp/keyman/pull/8503/files#diff-e7c8f9f12fc2df83cbac68d10a7389dcf3457856498c5d1eebaf02989fbbd917R150-R154 for example:

```meson
  kbd_kmn = configure_file(
    configuration: cfg,
    input: join_paths('template', 'keyboard.kmn.in'),
    output: kbd_basename + '.kmn'
  )
```
