### ISSUE TITLE
bug(windows): Close button appears outside of Add/remove language dialog after changing the UI into Deutsch(German)/Kannada/French languages

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#8525]
### Describe the bug

I noticed that when the UI is changed to German, by clicking the Add/remove language button, the close button appears outside of the Add/remove language window. 

### Reproduce the bug

1. Install Windows 17.0.77-alpha build. 
2. Open Keyman Configuration dialog. 
3. Install any Keyboard. (eg., Khmer Angkor)
4. Change the UI language into Deutsch (German). 
5. In the Keyboard Layouts tab, Click Add/remove language button. 

Here, I noticed that the 'Close' button appears outside of the Add/remove language dialog. 

Note: I am seeing the same behavior when I change the UI language into Kannada or French or Myanmar. 

..German UI
 <img width="300" src="https://user-images.githubusercontent.com/19683143/227967878-b0c5f433-067d-44ef-a21e-a5294595dc94.PNG">

..Kannada UI

   <img width="300" src="https://user-images.githubusercontent.com/19683143/227971855-33da436d-ffaf-4d69-8003-74d5c11be491.PNG">

..French UI

   <img width="300" src="https://user-images.githubusercontent.com/19683143/227971894-ca9460a8-7098-4321-af6d-a722695dbd51.PNG">

..Myanmar UI

   <img width="300" src="https://user-images.githubusercontent.com/19683143/227971954-2ac0eddd-a5d6-429b-88d4-70c1bc3eedc4.PNG">

### Expected behavior

Close button should appear inside the Add/remove language dialog, even the UI is changed to Deutsch (German).  

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [X] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.077-alpha

### Operating system

Window 10 OS

**Comment by rc-swag** [comment]
I can replicate this. 
Some further notes for the investigation. If you hit cancel instead of pressing the install button again, although the keyboard layout tab is not updated with the Galaxie keyboard. If you exit Keyman Configuration and come back in, the keyboard is actually installed but with no language.  Other keyboards would have installed but used systems default language instead.

**Comment by bharanidharanj** [comment]
> I can replicate this. Some further notes for the investigation. If you hit cancel instead of pressing the install button again, although the keyboard layout tab is not updated with the Galaxie keyboard. If you exit Keyman Configuration and come back in, the keyboard is actually installed but with no language. Other keyboards would have installed but used systems default language instead.

Yes, @rc-swag I was able to reproduce the issue, that you have mentioned (ie., the keyboard is installed but with no language). Shall I post this as a separate issue?

**Comment by rc-swag** [comment]
>Yes, @rc-swag I was able to reproduce the issue, that you have mentioned (ie., the keyboard is installed but with no language). Shall I post this as a separate issue?


I posted this into the wrong bug it was meant for #8368. No need for a new issue as it was just more information to help me solve the bug the issue as it is a result of the install not completing as expected.

**Comment by bharanidharanj** [comment]
Okay, Thanks..Ross!
