### ISSUE TITLE
bug: builder script consistency re 'configure' actions

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#8542]
### Describe the bug

After a while once starting to utilize Android's reworked build script, I finally realized that Web updates were not propagating through unless I ran the `configure` action.  It had been my understanding up until this point that `configure` was only to be used for external dependencies, while `build` would chain for any internal dependencies (as `web` is for `android`).  

Note that all of the Web scripts have been written based on my understanding - `build` actions trigger in-repo dependencies' builds.  The dependency-check system is already preventing unnecessary rebuilds there.

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

**Comment by mcdurdin** [comment]
Yes. Any dependency listed will by default be called if necessary for all actions except `clean`. Thus, anything that depends on that (e.g. copying a build artifact) should do that in the `build` step.

This change needs to happen in the Android scripts @darcywong00. Not sure if there are other places with the same issue.

**Comment by darcywong00** [comment]
So to clarify, these KMEA steps get moved from the configure action to the beginning of build action?

https://github.com/keymanapp/keyman/blob/6df63eddc50a825042a44ff59ca5a1318686d75e/android/KMEA/build.sh#L75-L87

**Comment by mcdurdin** [comment]
> So to clarify

Yes, that all looks right.
