### ISSUE TITLE
bug(android): Default Keyboard is not working after setting it as a System wide keyboard 

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#8548]
### Describe the bug

I was able to use the keyman keyboard as the system keyboard in Chrome browser. But, after that, the same keyboard is not at all working in the Keyman In-app. 

### Reproduce the bug

1. Install the latest Keyman 17.0.80-alpha build in an Android Mobile / emulator. 
2. Set the sil_eurolatin keyboard as the system wide and default keyboard. 
3. Type some texts in the Keyman In-app. We may able to see the typed text in the text area. 
4. Close the application. 
5. Open Chrome browser. 
6. Click the Search field in the chrome browser. 
7. Verify that the Keyman Keyboard (sil_eurolatin) appears on the screen. 
8. Type some texts using the system keyboard. 
9. Close the browser. 
10. Open Keyman In-App. 
11. Type some text. 
Here, I noticed that the text did not appear on the text area. Seems to be an issue. 

I have attached the Video (keyboardnotworking.mp4)  file for reference. 

https://user-images.githubusercontent.com/19683143/228816487-3cd436c3-afd9-47ee-9b2c-a04cd12daa1c.mp4

### Expected behavior

The Keyman Keyboard should be working in the Keyman In-App after revert  from the chrome browser. 

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.80-alpha

### Operating system

Android 11.0

### Device

Redmi Note 8 Pro, API 31 emulator

**Comment by darcywong00** [comment]
Hmm, I cannot repro with 17.0.87 alpha

**Comment by bharanidharanj** [comment]
@darcywong00 Retested this with Keyman 17.0.87 build in my android mobile Version 11.0 and I am able to reproduce this issue.
