### ISSUE TITLE
bug(android): Inconsistent behavior of Keyboard after adjusting the OSK height for the current orientation (portrait or landscape)

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#8550]
### Describe the bug

I noticed the misbehavior of the default keyboard after changing the OSK height for the current orientation. (portrait or landscape)

### Reproduce the bug

1. Install Keyman 17.0.80-alpha build in an Android device / emulator. 
2. Open Keyman App. 
3. Install Khmer Angkor and Sil_Cameroon_QWERTY keyboards. 
4. Change the current orientation from Portrait to Landscape. 
5. Click the Settings option. 
6. Click Adjust keyboard height. 
7. Set with Maximum height. 
8. Change the keyboard to Sil_Cameroon_QWERTY.
9. Again, Change the keyboard to SIL_Eurolatin keyboard. 
10. Now, change the current orientation from Landscape to Portrait mode. 

Here, I noticed that the default keyboard appears partially on the screen. 

I have attached the Screenshot as well as the Video file for reference. 

..Partial appearance of the Keyboard

   <img width="300" src="https://user-images.githubusercontent.com/19683143/228852560-90697f40-1994-43bd-be00-ac965d64b6fb.jpg">

..Inconsistent behavior of the Keyboard

https://user-images.githubusercontent.com/19683143/228853265-87d59316-fbf2-4ad4-bb03-52736f0904cf.mp4

### Expected behavior

Changing the OSK Orientation should not affect the Keyboard View. 

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.80-alpha

### Operating system

Android 11.0, 12.0

### Device

Redmi Note 8 Pro, API 31 emulator

**Comment by darcywong00** [comment]
I could not repro with Keyman 17.0.87 alpha. @bharanidharanj - can you retest?

**Comment by bharanidharanj** [comment]
> I could not repro with Keyman 17.0.87 alpha. @bharanidharanj - can you retest?

@darcywong00 I was able to reproduce this issue. Here, What I did is:
1. Installed the latest Keyman 17.0.87-alpha build. 
2. Downloaded and Installed Khmer Angkor, Sil_Cameroon_Qwerty Keyboards in the Keyman In-App. 
3. Change the Orientation from Portrait to Landscape.
4. Adjust the Keyboard height to Maximum size. 
5. Change the Keyboard to Khmer Angkor or Sil_Cameroon_Qwerty Keyboard. 
6. Revert to English-EuroLatin keyboard. 
7. Close the Keyman Application. 
8. Change the Orientation from Landscape to Portrait. 
9. Open Keyman In-App. 

Here, the Keyboard partially in the Keyman application.

**Comment by darcywong00** [comment]
@bharanidharanj - I still cannot repro this (currently on 17.0.92 alpha).

When I do the last 2 steps:
>8. Change the Orientation from Landscape to Portrait.
>9. Open Keyman In-App.

I see the OSK briefly show a partial keyboard but quickly refreshes to show the full OSK.

**Comment by bharanidharanj** [comment]
> @bharanidharanj - I still cannot repro this (currently on 17.0.92 alpha).
> 
> When I do the last 2 steps:
> 
> > 8. Change the Orientation from Landscape to Portrait.
> > 9. Open Keyman In-App.
> 
> I see the OSK briefly show a partial keyboard but quickly refreshes to show the full OSK.

@darcywong00 For me, the OSK did not change its behavior (ie., partial appearance) even though, I stayed in the same screen. But, If I restarted the application, the keyboard revert to its original size.

**Comment by darcywong00** [comment]
@bharanidharanj - I still haven't been able to get a repro in my testing.

Do you know if you can reproduce the issue if you don't change the keyboard height? (skip steps 5-7).

**Comment by darcywong00** [comment]
OK, now I can get a consistent repro (doesn't involve adjusting keyboard height).

1. With the device in landscape, launch Keyman for Android (leave "Get Started" on startup enabled)
2. From the navigation bar, press the back button "<"
3. Rotate device to portrait
4. From the launcher, launch Keyman for Android (note the splash screen appears)
5. Observe reported issue where only the left half of the OSK and suggestion banner is visible.

**Comment by darcywong00** [comment]
Investigating if this might be why
https://developer.android.com/guide/topics/resources/runtime-changes#allow-activity
