### ISSUE TITLE
bug(android): "Undo" suggestion is not working Keyman 17.0.80 alpha build

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#8556]
### Describe the bug

I noticed that after pressing the backspace key, the broken suggestion did not appear on the suggestion banner. 

### Reproduce the bug

1. Install Keyman 17.0.80-alpha build. 
2. Open Keyman In-App.
3. Type P r o b
4. Select Problem from the banner. 
5. Press Backspace 

Here, I noticed that the broken suggestion 'Prob' was missing in the suggestion banner. Seems to be an issue. 

I have attached the Screenshot as well as the Video file for reference. 

..broken suggestion Prob is missing

   <img width="300" src="https://user-images.githubusercontent.com/19683143/229106457-3d2994f2-b5eb-4206-bbad-496a949b6699.jpg">

..broken suggestion is missing

https://user-images.githubusercontent.com/19683143/229106512-d5ad20d2-1b36-43f7-a2ed-b07de64e3ea9.mp4

### Expected behavior

The broken suggestion 'Prob' should appear on the suggestion banner. 

### Related issues

https://github.com/keymanapp/keyman/issues/7167

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.80-alpha

### Operating system

Android 11.0, 12.0

### Device

Redmi Note 8 Pro, API 31 emulator

**Comment by darcywong00** [comment]
@jahorton - does predictive text allow for that level of "undoing" a suggestion?

**Comment by jahorton** [comment]
The input sequence he describes should put the predictive-text system into a state that allows reversion, which presents a suggestion that restores the original text from before the suggestion was applied.  (One backspace after applying the suggestion.)

**Comment by jahorton** [comment]
Ah, since I forgot to document it here:  this smells like an issue with the context-resetting mechanism.  If I manually try to place the caret where it already is, the "prob" suggestion will drop - even on iOS - as that performs a context reset.

So, if Android is _already_ doing a context reset behind the scenes that it shouldn't be, that could easily cause this problem.

**Comment by darcywong00** [comment]
> So, if Android is already doing a context reset behind the scenes that it shouldn't be, that could easily cause this problem.

Ack, it seems Android is calling resetContext() on every keystroke :disappointed: . Investigating...

**Comment by mcdurdin** [comment]
Resetting context would also break deadkeys from an earlier keystroke (if there is an intermediate keystroke). Do we have any regression test that would validate this? We should add one, if there isn't one already.

**Comment by darcywong00** [comment]
aha, the bug was introduced during the consolidation in #8438 where `KMManager.SystemKeyboardShouldIgnoreSelectionChange` gets set, but never `KMManager.InAppKeyboardShouldIgnoreSelectionChange`. This was causing resetContext to trigger on every change.

I didn't find a regression test, but kbd_basicfr has a deadkey on <kbd>^</kbd> with vowels for an easy test.

**Comment by mcdurdin** [comment]
> I didn't find a regression test, but kbd_basicfr has a deadkey on ^ with vowels for an easy test.

Is this sufficient to trigger the bug? Or do you need a keyboard which has an intermediate keystroke (which would be the one which triggers the resetContext call)?

**Comment by jahorton** [comment]
> > I didn't find a regression test, but kbd_basicfr has a deadkey on ^ with vowels for an easy test.
> 
> Is this sufficient to trigger the bug? Or do you need a keyboard which has an intermediate keystroke (which would be the one which triggers the resetContext call)?

That keyboard requires deadkey-first, so it should make an adequate test.

https://keymanweb.com/#fr,Keyboard_basic_kbdfr

The `^` on the US-layout `[` key affects the following keystroke, not the previous.  So, `^` + `a` => `â`... with just `^` displaying nothing.

**Comment by mcdurdin** [comment]
If that keyboard triggers the bug, fine. But I can imagine scenarios where the reset could happen between matching context and emitting output, in which case you'd need a keyboard that has an intermediate step, e.g.:

```
+ 'a' > dk(1)
+ 'b' > 'X'
dk(1) 'X' + 'c' > 'PASS'
```
