### ISSUE TITLE
bug(iOS): Paste, Select, Select All popup menu appears automatically If I click multiple times in the text area

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#8564]
### Describe the bug

I noticed that after installing Keyman application in the iPhone (Simulator), I clicked multiple times on the text input screen showed Paste, Select and Select all options popup menu on the screen. 

### Reproduce the bug

1. Install Keyman 17.0.82-alpha build in iPhone device / Simulator. 
2. Open the Keyman In-App.
3. Double click on the text area. 
4. Click one more time on the text area would show Paste, Select and Select all option popup menu on Screen. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/230400442-3626e8a6-cf30-45b3-8703-7897c0ce1527.png">

### Expected behavior

Clicking multiple times on the text area should not display the "Paste, Select, Select all" popup menu in the text input screen. 

### Keyman apps

- [ ] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.82-alpha

### Operating system

iOS 15.0, iOS 16.4

### Device

iPhone 14 Pro Max Simulator

**Comment by mcdurdin** [comment]
This is a standard iOS behaviour, so closing as by-design 😄
