### ISSUE TITLE
bug(web): different output with lao_phonetic keyboard

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#8568]
### Describe the bug

The [lao_phonetic keyboard, v1.1.2](https://keyman.com/keyboards/lao_phonetic) can sometimes generate different output on web vs Windows (Core) -- this seems to be most visible when backspacing.

This could possibly be caused by one or more of the following:

1. differences in the compiler
2. deadkey handling
3. backspace handling

At this point, I am just documenting the difference!

### Reproduce the bug

1. Type `phaa saa laaw ko` then press <kbd>bksp</kbd>, <kbd>bksp</kbd>
2. On Windows, you'll see the following output: ພາສາລາວ
3. In the Developer debugger, you can also see the deadkeys: ພາ￼ສາ￼ລາວ￼ (all `dk(1)`)
4. However, on web, you'll see this: ພາສາລາົວ (with 0ebb inserted prior to final 0ea7 ວ).

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [X] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16.0.139

### Operating system

Web

### Browser

any?

### Keyboard name

lao_phonetic

### Keyboard version

1.1.2

### Language name

Lao

**Comment by ermshiperete** [comment]
A shorter repro is to type `laaw ko` then press `bksp`, `bksp`.

Expected output: ລາວ
Actual output: ລາົວ

**Comment by jahorton** [comment]
This bumps up against https://github.com/keymanapp/legacy-issues/issues/3309.  Investigation led me to discover this fun little culprit:

https://github.com/keymanapp/keyman/blob/b4843b25abbc967a11413a043f6bc1242f35b320/common/web/keyboard-processor/src/text/keyboardProcessor.ts#L526-L536

So... the reason this is happening is quite obvious.  (The first BKSP keystroke instantly nukes KMW's deadkeys, whereas Keyman for Windows preserves them.)  But... the direct culprit is a fix to an issue from early, early KMW.  Should we be safe to reverse it (removing the check above) at this time?  

The original issue text, with better formatting:

> Deadkeys are stored with position w.r.t. each element, and should be removed when (a) they are matched in a rule or (b) text including that position is deleted, either by selecting and deleting or overwriting the text.  The first condition has been implemented for (hopefully) all browsers and input element types, but deadkey cleanup following backspace needs to be implemented.

This does remind me of some of the KMW 10 deadkey work - making sure deadkeys were properly tracked, etc, while they hadn't been before in certain scenarios.  So... we probably _can_ drop the deadkey-clear?

**Comment by mcdurdin** [comment]
I think we can drop the deadkey-clear, so long as we add some unit tests to verify that KeymanWeb's behaviour matches Core's behaviour with respect to deadkeys and backspace.
