### ISSUE TITLE
bug(developer): rtl gets unchecked for lexical-models

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#8595]
>  Thanks @DavidLRowe , I'm a tad surprised because I was very sure that I had checked that box ... and I believe we have uncovered a bug!   My Keyman Developer version is 16.0.139, these steps bring out a bug where "Is Right-to-left" will become _unchecked_ : 

1. Open a lexical model .kps file.
2. Go to the "Lexical Models" section/tab.
3. Check "Is Right-to-left"
4. Go to the "Source" section/tab (do nothing).
5. Return to "Lexical Models" , "Is Right-to-left" is now _unchecked!_

"Is Right-to-left" remains checked if you go back and forth to any of the other tabs.  I'll open a bug report for KMD.

I'll make a new commit with "Is Right-to-left" checked, I guess it will be fine so long as the "Source" section is not visited.

_Originally posted by @dyacob in https://github.com/keymanapp/lexical-models/issues/196#issuecomment-1506217855_

**Comment by mcdurdin** [comment]
I've just tried to reproduce this, and haven't succeeded. Can you give me some more details on where this is going wrong? (I tested with 17.0.88-alpha, but nothing in the lexical model editor has changed since 16.0)

**Comment by dyacob** [comment]
Thanks for opening this @darcywong00 , it was on my todo list but kept slipping my attention :-)

It reproduces easily on my end, I can make a short video if it helps.  One thing I note is that you do have to start with the `.kps` file and then go to the Lexical Models section.  If you start with the `.kpj` , then open the `.ts` file, there is another `Right-to-left script` checkbox, but it does _not_ have the issue.

**Comment by mcdurdin** [comment]
Good catch thank you @dyacob -- I was opening the .model.ts... will try again!

**Comment by mcdurdin** [comment]
Okay, reproduced in package editor. Will work on a fix.
