### ISSUE TITLE
feat(linux): Add column for area where keyboards are installed.

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/keyman#8631]
(From https://github.com/keymanapp/keyman/issues/8619#issuecomment-1513325138)

Add another column that shows the area where a keyboard is installed: user/shared/system. Maybe only show or fill the column if we have keyboards from more than one area.

Currently it is confusing if you have the same keyboard multiple times:

![image](https://user-images.githubusercontent.com/181336/233096626-cfc0d7c4-6287-45a4-8781-f9e7ba1d063c.png)

**Comment by mcdurdin** [comment]
We may want to address this with the unified configuration dialog styling coming later?
