### ISSUE TITLE
bug(android): Keyboard is not working after changing the Display Language

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#8639]
### Describe the bug

I noticed that after changing the UI language, the Keyboard is not at all working in the Keyman In-App

### Reproduce the bug

1. Install Keyman 17.0.90-alpha  build Android Mobile / emulator.
2. Open Keyman In-App.
3. Type a word (eg., Testing) in the text input screen. 
4. We may notice that the typed word appears on the screen. 
5. Change the Display Language into Amharic. 
6. Revert to Home Screen. 
7. Type a word (eg., testing) in the text input screen. 

Here, I noticed that the text is not appearing on the screen. Even, changing the UI into English does not help. 

Seems to be an issue. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/233362084-7812c700-da13-47cd-b436-94839e3b7081.PNG">

..

### Expected behavior

Keyboard should work after changing the display language. 

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

18.0.90-alpha

### Operating system

Android 5.0, 9.0, 12.0

### Device

API 21, 28 and 31  Android Emulator

**Comment by darcywong00** [comment]
Regression introduced in #8494 72c6ad17d4d5a93a36a5ba8d00935f8cd993dcfe

When resuming, `InAppKeyboard` and `SystemKeyboard` have already been initialized, so `keyboard` remains null and exits...

I believe fixing this will also fix #8548

**Comment by darcywong00** [comment]
In my testing, this seems to affect only INAPP keyboard. System keyboard still works after changing the Display Language
