### ISSUE TITLE
[Windows] Keyman keyboards not functioning in Cortana search

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#866]
Kannada keyboard installed in keyman doesn't type in "Cortona" Search window. Instead the default Kannada keyboard layout of Windows 10 is operating.

![image](https://user-images.githubusercontent.com/14062593/39960933-9b42a082-55f1-11e8-8f62-13e3838fbf49.png)

**Comment by darcywong00** [comment]
This Microsoft [bulletin](https://support.microsoft.com/en-us/help/4026948/windows-10-cortanas-regions-and-languages) gives a list of regions & languages that Cortana can be set to. I believe it's tied to the currently selected default language in Windows 10.

> Cortana is available in these regions for these languages:
> * Australia: English
> * Brazil: Portuguese
> * Canada: English/French
> * China: Chinese (Simplified)
> * France: French
> * Germany: German
> * India: English
> * Italy: Italian
> * Japan: Japanese
> * Mexico: Spanish
> * Spain: Spanish
> * United Kingdom: English
> * United States: English

**Comment by MayuraVerma** [comment]
The reference you have provide is speech support.

We can type Kannada in Cortana search box. We should be able to search documents system-wide, internet search, app store by typing in that box.

when Keyman Kannada keyboard layout is active, search box uses system default Kannada layout. 

It looks like the search box recognizes the language, but fails to load to Keyman layout, instead uses Windows default layout.

![screen shot 2018-05-18 at 8 29 04 pm](https://user-images.githubusercontent.com/14062593/40263584-32aa064e-5ada-11e8-8752-5a25183398ab.png)
![screen shot 2018-05-18 at 8 29 12 pm](https://user-images.githubusercontent.com/14062593/40263585-32bdabea-5ada-11e8-9c62-1d244d0f9fe0.png)
![screen shot 2018-05-18 at 8 29 22 pm](https://user-images.githubusercontent.com/14062593/40263586-32d157ee-5ada-11e8-8bee-c2573dc92f1e.png)

![screen shot 2018-05-18 at 8 20 19 pm](https://user-images.githubusercontent.com/14062593/40263501-f95b22e8-5ad8-11e8-8d00-419610d3b0dc.png)

**Comment by mcdurdin** [comment]
This is related to a set of issues around 3rd party keyboard support in Windows Modern UI. As such, we'll revisit with Keyman 11; there may now be solutions but 3rd party keyboards (specifically, TSF TIPs) were not fully supported with Modern UI previously.

**Comment by MayuraVerma** [comment]
Thanks

**Comment by MayuraVerma** [comment]
This is similar issue seen in Cortana search window.
Browser: Chrome

The comment window in SIL community forum doesn’t pickup the keyman layout. Instead it picks the windows system default keyboard layout of the language selected in keyman layout.

**Comment by mcdurdin** [comment]
@MayuraVerma I'm not seeing the same behaviour in Chrome that you are. I am able to type into the comment window without problem with a Keyman keyboard. Can you provide some more detail - Keyman keyboard you are using, Chrome version, Windows version, x64 vs x86. Also consider attaching a diagnostic report?

**Comment by mcdurdin** [comment]
This was resolved in 11.0 with the Modern UI compatibility update
