### ISSUE TITLE
feat(developer): package compiler should warn if a .kmx targets mobile but there is no corresponding .js

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#8672]
### Is your feature request related to a problem? Please describe.

See for example keymanapp/keyboards#2193

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [X] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0

**Comment by dyacob** [comment]
Thanks!  Perhaps generalize this to have the package compiler warn if any required resources are missing for the target platforms.
