### ISSUE TITLE
chore: move `set -eu` into build-utils.sh

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#8693]
Currently, all our build scripts have a tedious prolog. I want to minimize that and maximize script safety by moving the `set -eu` line into build-utils.sh. There are a number of scripts that fail when I do this, though, including:

* /resources/build/history/history-utils.sh:
  ```
  /Users/mcdurdin/buildAgent/work/99b311828f4ee7c/keyman/resources/build/history/history-utils.sh: line 11: DEBUG: unbound variable
  ```

* /mac/build.sh:
  ```
  ./build.sh: line 113: KME4M_BUILD_PATH: unbound variable
  ```

* /linux/scripts/dist.sh:
  ```
  ./scripts/dist.sh: line 20: $1: unbound variable
  ```

I originally had this change bundled into #8692 but will make it a separate task to avoid a cascade of issues.

**Comment by darcywong00** [comment]
How do we handle actions we expect only to run on CI when certain environment variables are set?

**Comment by mcdurdin** [comment]
> How do we handle actions we expect only to run on CI when certain environment variables are set?

The way we normally do this is by using `-z ${var+x}` syntax -- which tests if variable is set.

```bash
if [[ ! -z "${var+x}" ]]; then
  do_action
fi
```

**Comment by darcywong00** [comment]
But for dev environment, those variables would be unset. Would the script then error?

**Comment by mcdurdin** [comment]
No, that's why we use `-z ${var+x}`. That works even if the variable is not set. See https://stackoverflow.com/a/13864829/1836776
