### ISSUE TITLE
bug(android): Backspace key get stuck in the text input screen while trying to delete the repeated letter (eg., l) 

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#8709]
### Describe the bug

I noticed that backspace key is not working after entering the same letter (eg., l) for n number of times in the text input screen. 

### Reproduce the bug

1. Install the latest Keyman 17.0.98-alpha build. 
2. Open Keyman In-App.
3. Type the letter "L" continuously (eg., lllllllllllllllllllllllllllllllllllllllllllll) using OSK.
4. Press 'Backspace' key to delete all the letters one by one. 

Here, I noticed that the Backspace key stuck and did not work. Seems to be an issue. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/236210774-b0dc3f73-b17a-43a7-8998-9a00e2a6241f.PNG">

### Expected behavior

Pressing BackSpace key should delete the letter one by one

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.98-alpha

### Operating system

Android 5.0, 9.0, 12.0

### Device

API 21, 28 and 31  Android Emulator, Redmi Note 8 Pro

**Comment by bharanidharanj** [comment]
> Hi @bharanidharanj, is this reproducible on 16.0?

@mcdurdin Retested with 16.0.139 Stable build and I was not able to reproduce it.

**Comment by darcywong00** [comment]
Closing until some consistent repro
