### ISSUE TITLE
[android] Monitoring Instrumentation exception

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#871]
From a Firebase crash [report](https://console.firebase.google.com/u/1/project/kmapro-ee779/crashlytics/app/android:com.tavultesoft.kmapro/issues/5afdc25311e9fa0aa5e0c673):

![monitoring exception](https://user-images.githubusercontent.com/7358010/40210860-9c0f6cbe-5a71-11e8-8838-8b02f34b94c4.jpg)

### Configuration ###
Keyman Android 10.0.393 Beta
Android 5.0.1
Huawei P8 Lite

To investigate.
Any connection to android-testing [issue](https://github.com/googlesamples/android-testing/issues/89)?

### Workaround ###
From [SO](https://stackoverflow.com/questions/47854705/google-fabric-uiautomation-not-connected) and it says this seems to only affect Google test devices
> It seems that this crash is related to UI testing in your app...

Remove `testInstrumentationRunner` in  defaultConfig from build.gradle
```
defaultConfig {
   ...
   testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
}
```

and **androidTestCompile, testCompile** in dependencies
```
dependencies {
androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', 
{
    exclude group: 'com.android.support', module: 'support-annotations'
})
testCompile 'junit:junit:4.12'
...
```

**Comment by darcywong00** [comment]
atm, this might be difficult to repro

**Comment by mcdurdin** [comment]
Moving to future

**Comment by darcywong00** [comment]
Firebase migrated all issues to Crashlytics, but unfortunately, this [issue](https://console.firebase.google.com/u/0/project/kmapro-ee779/crashlytics/app/android:com.tavultesoft.kmapro/issues/5afdc25311e9fa0aa5e0c673) is outside the 90-day window.

CND
