### ISSUE TITLE
bug(iOS): 'Keyman as system-wide keyboard' feature is always be in enabled state even though I reinstalled the Keyman app

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#8714]
### Describe the bug

I noticed that once we enabled "Keyman as system-wide keyboard.." feature in the keyman app, this feature is always be in enabled state even though we installed a new version keyman application. 

### Reproduce the bug

1. Install Keyman 16.0.139 build.
2. Open Keyman In-App.
3. Enable Keyman as the system-wide keyboard using Settings dialog. 
4. Close the Application. 
5. Uninstall Keyman app. 
6. Install Keyman 17.0.100-alpha build.
7. Open Keyman In-App. 

Here, I noticed that "Setup Keyman as system-wide keyboard.." option is still in enabled state. Seems to be an issue. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/236445205-58c6373f-92e2-44d6-8a3d-8724e0ae2bfc.png">

### Expected behavior

This feature "Setup keyman as system-wide keyboard" should be disabled during the uninstallation process of keyman. 

### Keyman apps

- [ ] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16.0, 17.0

### Operating system

iOS 16.2

### Device

iPhone 14 Pro Max Simulator

**Comment by mcdurdin** [comment]
This is an iOS setting and not something we can control -- if the user adds Keyman as a system keyboard in Settings, we can't remove it from Keyman.

Will close as wontfix because we cantfix :grin:
