### ISSUE TITLE
bug(windows): Got an error message while trying to install Khmer Angkor keyboard in Keyman 16.0.139 stable build (Random)

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#8734]
### Describe the bug

After installing a sil_ipa.kmp package file, I tried to download and install Khmer Angkor keyboard using Keyman Configuration dialog and noticed that an error message appeared during the installation. 

### Reproduce the bug

Here, What I did is:
1. Installed Keyman 16.0.139 Stable build in Windows 11 OS. 
2. Opened Keyman Configuration dialog. 
3. I already have sil_ipa.kmp file in the folder. So, I double clicked on the .kmp file and installed it. 
4. I was able to see the installed IPA (SIL) keyboard in the Keyman Configuration / Keyboard Layouts view. 
5. Then, I clicked the 'Download keyboard' button from the Configuration dialog. 
6. Tried to download and install the Khmer Angkor keyboard using Keyboard Search dialog. 

Got the following error message during the downloading process..

<img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/2b5909e5-8ca8-4f24-9dd8-ecc1c654dd01">

Note:  I uninstalled Keyman 16.0 then reinstalled it in the system. After that, I was not able to reproduce this issue. Seems to be a random one. 

### Expected behavior

It should install Khmer Angkor keyboard after installing the sil_ipa.kmp file from a folder. 

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [X] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16.0.139 stable build

### Operating system

Windows 11 OS (VM0

**Comment by rc-swag** [comment]
The message is saying there was an error contacting the server. It was a temporary network error either on the download side or could have been a firewall issue. The network problem was resolved which is why you didn't see the error again.
