### ISSUE TITLE
feat(android/app): Feature Request: customize long-press delay time

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#877]
User request from [community-site](https://community.software.sil.org/t/keyman-10-beta-feedback/715/43)

> Is there a way to customize the long-press delay time for Android and iOS? That would be very helpful. It currently defaults to about 1000 milliseconds.

**Comment by mcdurdin** [comment]
Query: @jahorton what is the delay time for iOS?

**Comment by darcywong00** [comment]
From A18S8 sprint plan meeting, @jahorton notes
> For the UX controls, do with auto-correct preference (same patterns)

**Comment by darcywong00** [comment]
UX: slider (6 steps?) of maybe 0.1 ms increments
Follow the pattern for auto-corrections

**Comment by darcywong00** [comment]
![adjust longpress delay](https://github.com/user-attachments/assets/0f976bf3-f035-432b-b536-c6fca70fa82c)

A prototype of the menu.
* Default to 1000 ms
* Range from 500ms to 1500 ms (in 250ms increments)

**Comment by jahorton** [comment]
> ![adjust longpress delay](https://private-user-images.githubusercontent.com/7358010/357274438-0f976bf3-f035-432b-b536-c6fca70fa82c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MjM5NzAsIm5iZiI6MTcyMzUyMzY3MCwicGF0aCI6Ii83MzU4MDEwLzM1NzI3NDQzOC0wZjk3NmJmMy1mMDM1LTQzMmItYjUzNi1jNmZjYTcwZmE4MmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTNUMDQzNDMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODBiMjk1NTlhOTdkMDUyZTZlNjcwZjhmZTFhY2M0ODJkNTlmOTg2OTZlMTVjOWQxOTg1NzJlODIxNjZhYmFjMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._Aj2MRtfTOIk2bBHM9znVjy5xyKE54c84KW8WRJzdYE)
> 
> A prototype of the menu.
> 
>     * Default to 1000 ms
> 
>     * Range from 500ms to 1500 ms (in 250ms increments)

Current time = 500 ms.  I'd do 100 ms increments from 200 ms to 1000ms or 2000ms.  The latter does feel extreme, but it probably would help people with accessibility needs.

**Comment by darcywong00** [comment]
atm, now trying to see if this is the KeymanWeb parameter to specify the long-press duration
```typescript
keyman.osk.vkbd.gestureParams.longpress.waitLength
```

**Comment by jahorton** [comment]
> From A18S8 sprint plan meeting, @jahorton notes
> 
> > For the UX controls, do with auto-correct preference (same patterns)

Migrating this to #12203, since current work on this issue is not addressing the quoted node.
