### ISSUE TITLE
bug(windows):  Non Roman Characters appears in the Notepad  <Untitled- file name> field If I use Keyman Keyboard in Windows 11 OS

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#8809]
### Describe the bug

I noticed that after switching into keyman keyboard, If I typed a letter in the body of the Notepad app, it immediately appear in the <untitled - name>field. 

### Reproduce the bug

1. Install Keyman 17.0.106-alpha build in Windows 11 OS. 
2. Open Keyman Configuration dialog. 
3. Download and install Khmer Angkor keyboard. 
4. Open Notepad application. 
5. Switch to Khmer Angkor keyboard. 
6. Type 'xEjmr' from the keyboard. 
7. Verify that  ់ខ្មែរ់ appears in the body of the notepad. 

Here, I noticed that the same Khmer text appears in the Untitled-Notepad field. 

Note: I am not seeing the behavior in Windows 10 OS. 

..in Windows 11 OS

<img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/a9b5be2c-4de3-4689-ba38-0aead66c8bb6">

..in Windows 10 OS

<img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/35c2a027-d91a-4fe3-bfe5-b1bca4a35852">

### Expected behavior

Typing with any keyboards (non-roman) in the body of the Notepad app, should not affect the <Untitled-file name>.

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [X] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.106-alpha

### Operating system

Windows 11 OS (VM)

### Target application

Notepad app

### Keyboard name

khmer_angkor, kannada basic

**Comment by mcdurdin** [comment]
I believe this behaviour is by design in the Notepad app; not a Keyman issue -- you'll see the same behaviour with a Windows keyboard.
