### ISSUE TITLE
bug(windows): Keyman Unable to Enter Text in MS Word Dialogs

### ISSUE THREAD

**Issue by dyacob** [keymanapp/keyman#8841]
### Describe the bug

This problem has popped up a few times in the past and I think has been related to Windows or Word and Keyman has had to work around it.  When a Word dialog appears, text cannot be typed into a dialog field with a keyman keyboard.  Nothing happens at all when keys are hit (even for keys not mapped by the keyboard).  I notice this primarily with Word's"Phonetic Guide" which I use the most, but also when using "Find"  (Ctrl+F).

Keyman will work as expected _if_ there is already text in the dialog field. The problem occurs when the fields are initially empty.

### Reproduce the bug

1. With Word open and Keyman keyboard active, activate "Find".
2. Type into the search field, nothing will happen.
3. Switch to the default keyboard, type into the field.
4. Switch back to Keyman, you can now type into the field.

This should be repeatable with other dialogs and keyboads.

### Expected behavior

Text can be typed just as it is in the Word document body.

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [X] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16.0.139

### Operating system

Windows 11 Pro (22621.1702)

### Device

Laptop

### Target application

2019 MSO (Version 2304 Build 16.0.16327.20200) 64-bit

### Keyboard name

gff_amharic, gff_geez

### Keyboard version

latest

### Language name

Windows and Word are set for English

**Comment by mcdurdin** [comment]
@rc-swag can you investigate?

**Comment by rc-swag** [comment]
I can't replicate it, unfortunately. 
I tried on Win 10 and  Windows 11.
My Version Word: Microsoft® Word for Microsoft 365 MSO (Version 2304 Build 16.0.16327.20200) 64-bit 
I did both did `Ctrl-F` to find and tested the "Phonetic Guide" through the font menu Icon.

The next step would be to get a log file from @dyacob and see if I can see what is going on.  I have sent a direct message via the forum to request a log file.

**Comment by dyacob** [comment]
@rc-swag , after being an issue for me for the full of May, I am now unable to reproduce the problem this morning. Which is good but also frustrating.  I don't know what has changed since I made the bug report.  I guess the conditions that triggered it have to be just right.  

I'll keep an eye on it, I suspect it will resurface in the next week or two.  You may close the bug report and I can reopen it when/if the issue returns and will attach the log file then.

thanks!

**Comment by rc-swag** [comment]
Closing but will reopen if occurs again
