### ISSUE TITLE
feat: Show Developer Defined Hint Symbol When Longpress is not Present

### ISSUE THREAD

**Issue by dyacob** [keymanapp/keyman#8855]
### Is your feature request related to a problem? Please describe.

The "Hint" symbol is displayed only when a longpress key is defined for the key.  The "hint" notion is useful in other use cases, for example when tapping the key will change layers.  For example, the GFF Blin keyboard uses a hint character on the 2nd order modifier key to alert the user that this is the key to touch to reveal additional, less frequently used, modifier keys (which in turn is achieved by a layer change vs a longpress).  I would like to apply this hint mechanism on other keyboards.

So I think of the keyboard designer has decided a "hint" is helpful for whatever reason, and entered text in the "Hint" field, it should be displayed.  This does not interfere with the default hint used to indicate longpress options.

### Describe the solution you'd like

If the keyboard developer has entered text into the "Hint" field, display it always.

### Keyman apps

- [X] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16.0.139

### Operating system

Android and iOS.

### Device

Any mobile or tablet device.

### Keyboard name

Any, but gff_blin is an example

### Keyboard version

1.5.x

### Language name

Blin

**Comment by mcdurdin** [comment]
This has already been implemented in the Keyman Developer Touch Layout Editor and will become visible in Keyman 17.0. See #6936 for details.

**Comment by mcdurdin** [comment]
And see #5079 for the upcoming work on the touch layout views in web,android,ios.
