### ISSUE TITLE
bug(iOS): Crash while trying to open FirstVoices App in the iPhone / iPad Simulators

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#8861]
### Describe the bug

I am getting crash while trying to open the installed FirstVoices application in both iPhone and iPad Simulators. 

### Reproduce the bug

1. Install FirstVoices 17.0.111-alpha build in iPhone device (?) or Simulator.
2. Click on the FirstVoices icon.
3. Crash message appear after clicking the FirstVoices application. 

I have attached the Screenshots for your reference. 

..Crash in iPhone 14 Pro Max Simulator

<img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/27571c08-1c29-4042-97d9-d19351b198e9">

..Crash in iPad (10th generation) Simulator

<img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/1a93719e-e6bc-4daf-b558-f992155b6aaf">

### Expected behavior

By clicking the FirstVoices icon from the Display, the application should open without showing any error message. 

### Keyman apps

- [ ] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.111-alpha

### Operating system

iOS 15.0, iOS 16.4

### Device

iPhone 14 Pro Max Simulator, iPad (10 generation) Simulator

### Target application

FirstVoices App

**Comment by mcdurdin** [comment]
@bharanidharanj please make sure you paste the text from the error report in as well as the image, thanks!

**Comment by bharanidharanj** [comment]
> @bharanidharanj please make sure you paste the text from the error report in as well as the image, thanks!

@mcdurdin Sure, I will do it.

**Comment by bharanidharanj** [comment]
I have attached here with the FirstVoices iPhone Text Error message for your reference. 

[FirstVoicesiPhoneError.txt](https://github.com/keymanapp/keyman/files/11597188/FirstVoicesiPhoneError.txt)

**Comment by jahorton** [comment]
The error readout suggests that an expected framework - Zip.framework - is missing.  I see that it's also missing from oem/firstvoices/ios/Cartfile.  Granted, it's been missing from that Cartfile for a _while_, so that _shouldn't_ affect anything... but maybe it does now, somehow?
