### ISSUE TITLE
bug(linux): Arch Linux distribution

### ISSUE THREAD

**Issue by nikita-moor** [keymanapp/keyman#8880]
### Describe the bug

A. Compilation error "../include/keyman/keyboardprocessor.h.in does not exist"
B. Absent MIME file.

### Problem A

1. Install hotdoc (the problem does not arise if hotdoc is not detected)
2. Download Linux release [keyman-16.0.139.tar.gz](https://downloads.keyman.com/linux/stable/16.0.139/keyman-16.0.139.tar.gz)
3. Extract
4. `cd keyman/core`
5. `./build.sh configure`
6. Error: "doc/meson.build:18:2: ERROR: File ../include/keyman/keyboardprocessor.h.in does not exist."

### Problem B

File [keyman.sharedmimeinfo](https://github.com/keymanapp/keyman/blob/master/linux/debian/keyman.sharedmimeinfo) is not included into Linux releases.

### Expected behavior

A. I need to comment out this line, then compilation completes with success:

https://github.com/keymanapp/keyman/blob/733363a69def1e00c18c4c935805038f83b0f0b1/core/meson.build#L36

B. Could you, please, include  [linux/debian/keyman.sharedmimeinfo](https://github.com/keymanapp/keyman/blob/master/linux/debian/keyman.sharedmimeinfo) into the release (https://downloads.keyman.com/linux/)?

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [X] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16.0.139

### Operating system

Manjaro Linux x86_64, X1, KDE Plasma 5.27.4

### Device

Desktop GB-BXi5-5200

### Additional context

I'm a maintainer of the [Arch Linux package](https://aur.archlinux.org/packages/keyman), and I will be grateful if you check the building process: [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=keyman).

**Comment by ermshiperete** [comment]
Problem A will be fixed by #8912.

**Comment by ermshiperete** [comment]
For stable 16.0 #8929 will fix it.

**Comment by ermshiperete** [comment]
Problem B will be fixed by #8917 (for alpha builds).
