### ISSUE TITLE
chore(developer): Support cp1252 for real legacy keyboards in kmcmplib

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#8884]
Also, don't forget: Hint to add: k004_ansi.kmn: Hint: 10A6 Keyman Developer has detected that the file has ANSI encoding. Consider converting this file to UTF-8

**Comment by srl295** [comment]
If I understand the requirements you want to be able to take in files in cp1252 and compile them.

cp1252 to utf-8 only requires an 8-bit transform (not all of them do!) and it's even available at https://www.unicode.org/Public/MAPPINGS/VENDORS/MICSFT/WINDOWS/CP1252.TXT 

actually, 1252 is supported by whatwg https://encoding.spec.whatwg.org/#windows-1252  so you could probably do the conversion at the nodejs level if needed https://nodejs.org/api/buffer.html#buffers-and-character-encodings  — but tiat's actually iso-8859-1 and not 'real' cp1252

in any event, the ICU built for unicodeset could have conversion in it and perform the conversion.  Or just build something out of the mapping table.
