### ISSUE TITLE
bug(core): support GCC 13 compilation

### ISSUE THREAD

**Issue by nikita-moor** [keymanapp/keyman#8920]
### Describe the bug

The v16.0.139 code compiles correctly with GCC 12, but using GCC 13 the `core` fails with a message ([full log](https://dpaste.com/77XLBL3V5)):

> ../../common/include/km_types.h:22:9: error: ‘uint32_t’ does not name a type

It can be solved adding library to [core/include/keyman/keyboardprocessor_bits.h](https://github.com/keymanapp/keyman/blob/master/core/include/keyman/keyboardprocessor_bits.h):

```c
#include <stdint.h>
```

Not `<stdint>` because this header is used in both C and C++ code.

Related to Arch Linux distribution, but might be useful to others.

P.S. Probably, a [bug in GCC](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=107134).

### Keyman version

16.0.139

### Operating system

Arch Linux

**Comment by mcdurdin** [comment]
@ermshiperete are you happy to take a look at this one?

**Comment by ermshiperete** [comment]
Thanks, @nikita-moor! This will be fixed with #8932.

This is not a problem on the `master` branch (Keyman 17) where things already compile successfully with GCC 13.

**Comment by ermshiperete** [comment]
See also [Debian bug #1037707](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1037707)
