### ISSUE TITLE
bug(android): Suggest words with Capitalization turns into lower case letters after closing the Get Started dialog

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#8947]
### Describe the bug

I noticed that after closing the Get Started dialog, the suggest words with capitalization turns into lower case letters in the suggestion banner. 

### Reproduce the bug

1. Install Keyman 17.0.118-alpha build.
2. Open Keyman In-App. 
3. We may notice that the Get Started dialog opens along with Keyman application. 
4. We may also notice that the suggest word with capitalization appears on the banner. (beforeclosing ..dialog)
5. Close the Get Started dialog . 

Here, I noticed that the suggest words with capitalization turns to lower-case letters. (afterclosing..dialog)

Seems to be an issue. 

I have attached the Screenshots for reference. 

..before closing Get Started dialog

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/33740aae-110d-4201-8c07-36c4b6d97cce">

..after closing Get Started dialog

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/0572791c-b0c6-4f43-9175-634065453780">

### Expected behavior

The suggest word with capitalization should be appear the same in the suggestion banner after closing the Get Started dialog. 

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.118-alpha build

### Operating system

Android 5.0, 9.0, 12.0

### Device

API 21, 28 and 31  Android Emulator, Redmi Note 8 Pro

**Comment by jahorton** [comment]
Interestingly, this behavior appears to have become inverted since its original posting: I'm seeing the keyboard and suggestions behind "Get Started" in lowercase, but shifting to uppercase when exiting the menu - when appropriate, of course.
