### ISSUE TITLE
Platform tests still have inconsistencies

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#896]
https://help.keyman.com/developer/language/reference/platform says that `platform('hardware')` should match on Keyman Desktop. However, it doesn't -- only `windows`, `desktop` and `native`.

Check also Keyman for macOS.

This works on KeymanWeb.

**Comment by erros84** [comment]
Hi all, I was just realizing this...and it's wreaking havoc in my quest for cross-compatibility.
While you are at it, there is more weirdness related to platforms (Developer 10).
![image](https://user-images.githubusercontent.com/986339/40714250-08459534-63fa-11e8-97c9-8e9d4d70d798.png)

When a keyboard is used on Android/Chrome Android Emulator, it switches to "hardware", but also to desktop.  This leaves us with an "Android Desktop". 
Here's the keyboard I used to test:

https://github.com/silcam/Cameroon-Keyboard/tree/BrokenRules/src/km/Platform%20Test

**Comment by mcdurdin** [comment]
@erros84 that's a great help, thank you. This is scheduled for resolution next sprint (P3S5).

**Comment by erros84** [comment]
How feasible would it be to selectively "fake" these values in Devoloper's Debug? This would allow us to create a unit test that reaches beyond Developer/Native/Windows, as well as testing a platform-specific rule flow without diving into Chrome.

**Comment by mcdurdin** [comment]
> How feasible would it be to selectively "fake" these values in Devoloper's Debug? 

This is a really good idea. It would be difficult to achieve now for version 10, but after some refactoring that's planned for version 11, then it should drop in relatively easily. So I've created issue #958 for this suggestion.

**Comment by mcdurdin** [comment]
A few notes on the spreadsheet:

1. I've added the spreadsheet to the PR that will be attached to this issue, and annotated with the target program (e.g. Keyman for Android, KeymanWeb, Keyman Desktop). Added missing tests and version numbers.

2. Web OSK, with no emulation of a mobile device, is treated the same as hardware by Keyman. There is no distinction, by design, because it's intended to work identically to the hardware. So we don't need to test against that. Same with Keyman Desktop OSK.

3. I'm not too concerned with Browser detection because it's a crazy moving target anyway... and not recommended. So won't be attempting to address that before 10.0 release.

4. KeymanWeb running in mobile device emulation mode in Chrome is challenging, particularly when using hardware keystrokes. (I think the iPhone X should be recognised as a phone, not a tablet, even in the emulator.) It's a bit of a special case. Again, I won't attempt to address this before 10.0 release.

More to come...

**Comment by mcdurdin** [comment]
Updated spreadsheet, all supported platforms:

![image](https://user-images.githubusercontent.com/4498365/41089161-5b50216e-6a6b-11e8-90d9-ed1c4ec5a8b4.png)

![image](https://user-images.githubusercontent.com/4498365/41089388-e719eb62-6a6b-11e8-90e9-0f7f34d7f042.png)

[Platform Results.xlsx](https://github.com/keymanapp/keyman/files/2079700/Platform.Results.xlsx)

**Comment by mcdurdin** [comment]
This gives a set of work items:

- [ ] Keyman Engine for Windows: Add support for `hardware` platform test
- [ ] Keyman Engine for macOS: Report `macosx` not `ios`
- [ ] Keyman Engine for Web: Test for Edge (low priority)
- [ ] Keyman Engine for Web: Report `macosx` not `undefined` on macOS, all browsers
- [ ] Keyman Engine for Web: Report `linux` not `undefined` on Linux, all browsers
- [ ] Keyman Engine for Web: Test for Safari (low priority)
- [ ] Keyman Engine for Web: Report `tablet` or `phone` not `desktop` when using hardware keyboard in Chrome emulator
- [ ] Keyman Engine for Web: Treat iPhone X as `phone`, not `tablet`
- [ ] Keyman Engine for Android: Report `tablet` or `phone` when using hardware keyboard
- [ ] Keyman Engine for Android: Report `undefined` for browser when using hardware keyboard

(errata note: Android Tablet KeymanWeb Chrome Hardware should report 'unsupported')

**Comment by mcdurdin** [comment]
I've reworked the platform test keyboard and spreadsheet extensively to clarify the tests.

With the keyboard now, activate it and press just the `a` key. The keyboard will spit out a sequence of words that are intended to be pasted into the FullResult column in the spreadsheet. The spreadsheet then automatically parses the result and highlights failing tests. You can also use keys `e`-`p` on the top row of the keyboard to do individual tests.

At this stage, I have not attempted to automate the tests completely, although they certainly could be automated on some platforms. Doing so would be worthwhile, but it's a big job.

**Comment by mcdurdin** [comment]
All platform inconsistencies have been addressed except for (a) mac, fix in progress [#967] and an issue with iPhone X [#970]. Given these are tracked separately now, will go ahead and close this issue.

**Comment by erros84** [comment]
I love what you've done with the platformtest kmn and all the updates.

Should clicking on "a" in Keyman Web OSK (Chrome, using no emulation) fire as "hardware" or "touch"? Getting "hardware" seems odd to me, but I can imagine a possible use case where it might be simplest.
My original test listed this as a possible problem area. Maybe you could add this line back to the table.

![image](https://user-images.githubusercontent.com/986339/41511837-50237b64-726e-11e8-9312-8d167202bf25.png)

**Comment by mcdurdin** [comment]
@erros84 Clicking on the virtual keyboard -- not the touch keyboard -- generates a 'hardware' event because it is identical to pressing a keyboard on the hardware keyboard. Think of it as a soft representation of the hardware keyboard; the presentation and behaviour is identical.

**Comment by erros84** [comment]
Ok, I thought it might be intentional.

**Comment by mcdurdin** [comment]
> How feasible would it be to selectively "fake" these values in Devoloper's Debug? This would allow us to create a unit test that reaches beyond Developer/Native/Windows, as well as testing a platform-specific rule flow without diving into Chrome.

Added in 15.0, see #5640.
