### ISSUE TITLE
bug(mac): Inconsistent behavior of the OSK after enabling 'Always show on-screen keyboard' option

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#8965]
### Describe the bug

 I noticed that after enabling 'Always show on-screen keyboard' option, the keyboard which is unchecked from the Keyboard Configuration dialog, is still enabled in the Keyman menu list and the OSK appears on the Screen.

### Reproduce the bug

1. Install 17.0.120-alpha build. 
2. Open Keyman Configuration dialog. 
3. Install any keyboard. (eg., Amharic keyboard)
4. Click the Options tab. 
5. Enable 'Always show on-screen keyboard' option. 
6. Click the Keyboards tab. 
7. Uncheck 'Amharic' Keyboard checkbox. 
8. Switch to default keyboard. 
9. Revert to Keyman Keyboard .

Here, I noticed that the Amharic keyboard is still enabled in the Keyboard menu list. And the OSK still appears on the screen. Seems to be an issue. 

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/7daaefd5-eb51-46e0-932f-ecb29b884668">

### Expected behavior

After disabling the Keyboard in Keyboards view, the disabled keyboard should not appear in the keyboard menu list. 

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [X] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.120-alpha build

### Operating system

macOS 13.4 Ventura

**Comment by sgschantz** [comment]
I was able to reproduce with 18 beta. It appears that having the OSK open for a keyboard when attempting to deactive it in the Configuration window prevents it from being removed from the keyboard menu.
