### ISSUE TITLE
feat(linux): mcompile - part 1: adapt LoadKeyboard to be cross-platform

### ISSUE THREAD

**Issue by SabineSIL** [keymanapp/keyman#8975]
Mcompile uses 4 basic steps to perform a conversion from a given kmx-file to another kmx-file:

- LoadKeyboard
- DoConvert-read 2 keyboards and store mapping
- DoConvert-translate to translate the keyboard
- SaveKeyboard

This issue is to enable/ adapt the first part of mcompile for Linux: the loading of the keyboard.

This function needs to be adapted to work on Linux and cross-platform. 

see #3345

**Comment by darcywong00** [comment]
@ermshiperete not available till after the team planning meetings

**Comment by mcdurdin** [comment]
> @ermshiperete not available till after the team planning meetings

This is @SabineSIL's work though :grin:

**Comment by darcywong00** [comment]
ah, I wasn't checking the assignee. reverting milestone

**Comment by SabineSIL** [comment]
closed because this issue is addressed in PR doconvert-read https://github.com/keymanapp/keyman/pull/9384
