### ISSUE TITLE
[Web] Rotation and screen size factors may need adjustment

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#90]
There appears to be some inconsistencies in how the OSK is constructed with respect to the emulator in Chrome. This should be reviewed.

-	Review use of .kmw-portrait/.kmw-landscape classes
-	Scaling for keyboard per devices in the test window (this code may need cleanup yet):

          tavultesoft.keymanweb.getOskHeight = function() {
            if(tavultesoft.keymanweb.util.device.formFactor == 'phone') {
              if(tavultesoft.keymanweb.util.portraitView()) {
                var height = 428;
              } else {
                var height = 220;
              }
              height=height/2; //tavultesoft.keymanweb.util.getViewportScale();
          
            } else {
              if(tavultesoft.keymanweb.util.portraitView()) {
                var height = 264;
              } else {
                var height = 350;
              }
              height=height/tavultesoft.keymanweb.util.getViewportScale();
            }
            return height;
          };

-	Review the key sizes, etc, against all common keyboards before we go live with this.

**Comment by jahorton** [comment]
This seems to be a non-issue at this point; we'll review this before releasing 11.0 to make sure its device emulation offerings all provide reasonable OSK layouts.  If everything looks good, we'll close it upon that confirmation.

**Comment by jahorton** [comment]
As best as I can tell, I am unable to replicate the original issue, especially for iOS.  (Android's OSK does seem a bit small on larger tablet device settings, though that's likely due to the emulation's zoom level.)  I'm going ahead and closing this issue for now.
