### ISSUE TITLE
bug(macOS): Multiple Keyman icons has been created with no version number on the desktop

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#9004]
### Describe the bug

I noticed that multiple keyman icons has been created whenever I installed a new build from keyman.com.

### Reproduce the bug

1. Install Keyman 17.0.119 build in macOS. 
2. I noticed that a Keyman icon has been created on the desktop. (no version numbe displayed)
3. Uninstall the Keyman build. 
4. Install Keyman 17.0.120 build.
5. Another keyman icon has been created on the desktop with no version number.
6. Uninstall the build. 
7. Install Keyman 17.0.122 build. 
8. Here, another keyman icon has been created on the desktop with no version number. 

I have attached the screenshot for reference. 

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/1cc50a1f-937e-48e9-be62-5bb2982e7458">

### Expected behavior

Keyman icon should show up the version number on the desktop.

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [X] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.122-alpha

### Operating system

macOS 13.4 Ventura

**Comment by mcdurdin** [comment]
These icons are disk images -- the Keyman installer -- which can be dragged to the Trash to 'eject' them. It would be nice if the installer offered to unmount and move the image to the trash, but that's a future feature rather than a bug, so closing this for now.
