### ISSUE TITLE
bug(windows): Keyboard Documentation link is not working in the Keyboard Help page

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#9018]
### Describe the bug

I noticed that If I click the keyboard documentation link it does not open the correct page. 

### Reproduce the bug

1. Install Keyman 17.0.123-alpha build. 
2. Open Keyman Configuration dialog. 
3. Download and Install Khmer Angkor keyboard. 
4. Open Khmer Angkor keyboard in Keyboard Layouts view. 
5. Click the Help button. 
6. Click the blue link button under Keyboard Documentations heading. 

Here, I noticed that there is a black window opens with a warning message on the screen. Seems to be an issue. 

I have attached the Screenshot for reference. 

..Black window appears on the screen

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/7d194425-3d1c-4300-9e95-6d40fbbacaf7">

Note:
1. I was able to reproduce it in Keyman 16.0.139 stable build. 
2. Reproducible in Linux build. 

### Expected behavior

By clicking the blue link button, it should open the relevant keyboard documentation page. 

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [X] Keyman for Linux
- [ ] Keyman for macOS
- [X] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

**Comment by rc-swag** [comment]
Related issue #9044 

I can see that URL to external file (pdf, or html) work fine. It is the links the locally stored files that fail.
