### ISSUE TITLE
bug(web): 404 error message appears while trying to open Sample test pages (minified and unminified)

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#9023]
### Describe the bug

I noticed that while trying to open minified and unminified pages, the web links given in the 'acceptance test for web' are not working. 

### Reproduce the bug

1. Enter [web/samples/minified.html](https://build.palaso.org/repository/download/Keymanweb_TestPullRequests/TBD:id/samples/minified.html) link on any browser. 
2. I noticed that '404 ' error message appears on the web page. 
3. Enter [Unminified Test Page](https://build.palaso.org/repository/download/Keymanweb_TestPullRequests/TBD:id/testing/unminified.html)  on any browser. 
4. I noticed that '404' error message appears on the web page. 

I have attached the Screenshot for reference. 

..minified page

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/21859a0e-97b4-41b9-a3c5-f061fa24decb">

..unminified page

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/62cdcd8d-4fe1-4921-a04a-aafeecfdd2d6">

Not able to do further testing with (keyman for) web. 

### Expected behavior

By clicking on the web links (minified and unminfied), the relevant page should open.

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [X] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Operating system

Windows 10 OS, Windows 11 OS (VM)

### Browser

Firefox, Chrome, Safari

**Comment by jahorton** [comment]
With the successful merge of #8560, I've also updated the acceptance-test links and such; when the CI-build ID is inserted properly, the links will now direct to the correct location.
