### ISSUE TITLE
bug(android): Inconsistent behavior of Get Started dialog checkbox

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#9028]
### Describe the bug

I noticed that after enabling the system wide keyboard, the check box near 'Show 'Get Started' on startup' was disappeared. 

### Reproduce the bug

1. Install Keyman 17.0.124-alpha build. 
2. Open Keyman In-App. 
3. We may notice that the check box of Get Started dialog has been enabled. 
4. Enable 'Enable Keyman as system-wide keyboard' option. 
5. Enable 'Set Keyman as default keyboard' option. 

Here, I noticed that the check box of Get Started dialog disappeared. Seems to be an issue. 

Note: 1. This happens only when the keyman app opens for the first time. 

I have attached the Screenshots as well as the video file for reference. 

..before enabling the system wide keyboard

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/5b7bd765-6923-42c1-91a4-4b5021129799">

..after enabling the system wide keyboard

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/4d9ec2b2-d83d-4514-bf98-6777491cdb75">

..Inconsistent behavior of Get Started dialog checkbox

   https://github.com/keymanapp/keyman/assets/19683143/e3f53d0a-b24b-409c-aa8a-09e311949e74

### Expected behavior

Enabling system wide keyboard option should not remove the check box near the 'Show 'get Started' on startup option.

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.124-alpha

### Operating system

Android 5.0, 9.0, 12.0

### Device

Redmi Note 8 Pro, API 31 emulator

**Comment by darcywong00** [comment]
This is intended behavior as implemented in #7587 because the user has finished the required steps of setting Keyman as a system keyboard

> if the user completes steps 2-3
>
> * Enable Keyman as a system-wide keyboard
> * Set Keyman as default keyboard
> the checkbox will automatically get unchecked and gets saved as a user preference
