### ISSUE TITLE
test(common/web): feature-branch regression testing - ES modules (🧩), embedded / alt uses

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#9039]
# Keyman for Web Acceptance Test Procedures #

For this test run, please refer to the builds posted on https://github.com/keymanapp/keyman/pull/8560#issuecomment-1492750092.

**NOTE**: nearly all of these are new, as far as regression testing is concerned.  We should probably consider adding them as proper regression tests in some manner.

# User Testing

## SUITE_DEVELOPER:  Use of KMW in the Developer test-host page

Note that Developer itself must run on Windows for the first one or two steps, while the test-host page may be loaded on a different device for the steps that follow based upon the specified target GROUP.

* GROUP_WINDOWS_CHROME
* GROUP_WINDOWS_FIREFOX
* GROUP_ANDROID_PHONE
* GROUP_IOS_TABLET

### Keyboard test-host page

- TEST_SERVER_KEYBOARD: (_pre-existing_, modified from SUITE_SERVER) Make sure that a keyboard debug session works.

  1. In Keyman Developer on a Windows machine, load a keyboard project, open a keyboard, and start testing on web.
  2. Open the entry above `http://localhost:8008` in your browser on the GROUP-specified test device, and select the keyboard from the Keyboards drop down.
  3. Verify that the keyboard is working in the web debug view.

## SUITE_MOBILE_APPS

* GROUP_ANDROID_TABLET
* GROUP_IOS_PHONE

- TEST_LAYER_SWAP_WITH_SELECTION:  Ensure that pressing a layer-swap key does not affect text-selection in any way.
  1. Load the Keyman app and select the default ("EuroLatin (SIL)") keyboard. 
  2. Type `testing testing 1 2 3`.
  3. Select `testing 1`.
  4. Press the SHIFT key.
  5. Verify that the selection remains selected and that no changes occurred.  The text before, inside, and after the selection should all remain unaltered.

- TEST_START_OF_SENTENCE:  Ensure that start-of-sentence behavior works properly.
  1. Load the Keyman app and select the default ("EuroLatin (SIL)") keyboard.
  2. Type `Test`.
  3. Verify that the keyboard is in its default (lowercased) layer.
  4. Type `.`
  5. Verify that the keyboard remains in its default layer.
  6. Type a single space (` `). 
  7. Verify that the keyboard automatically shifts to the SHIFT (uppercased) layer.
  8. Type `T`.
  9. Verify that the keyboard returns to the default layer.
  10. Move the caret to before the recently-typed `T`.
  11. Verify that the keyboard automatically shifts to the SHIFT layer.
  12. Move the caret to before the `s` in `Test`.
  13. Verify that the keyboard returns to the default layer.

**Comment by bharanidharanj** [comment]
## SUITE_DEVELOPER: Use of KMW in the Developer test-host page

### GROUP_WINDOWS_CHROME: 

* **TEST_SERVER_KEYBOARD (PASSED):** Tested with Keyman Developer 17.0.119-alpha-test-8560 in Windows 10 OS and here is my observation: 1. Opened gff_amharic project. 2. Opened the Keyboard in the local browser (http://localhost:8008) and selected gff_amharic keyboard from the dropdown list. Verified that the keyboard is working in the web debug view. 

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/9f9d5742-e01e-41e5-b2eb-eebf6eccc8d0">


* **TEST_SERVER_CAMEROON_AZERTY (FAILED):** 1. Opened sil_cameroon_azerty project in Keyman developer. 2. Opened it in the local browser. 3. Selected the sil_cameroon_azerty keyboard from the dropdown list. Verified that the keyboard is working in the web debug view. 3. Noticed that the output text does not appear in 'rounded' font. 

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/3e4212f8-54ce-4d7a-a3b7-2bc1fdc7d439">



### GROUP_WINDOWS_FIREFOX: 

* **TEST_SERVER_KEYBOARD (PASSED):** Tested with Keyman Developer 17.0.119-alpha-test-8560 in Windows 10 OS and here is my observation: 1. Opened gff_amharic project. 2. Opened the Keyboard in the local browser (http://localhost:8008) and selected gff_amharic keyboard from the dropdown list. Verified that the keyboard is working in the web debug view. 

    <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/e2bb3dd7-b0f5-44c5-a757-e18d9bb9f206">


* **TEST_SERVER_CAMEROON_AZERTY (FAILED):** 1. Opened sil_cameroon_azerty project in Keyman developer. 2. Opened it in the local browser. 3. Selected the sil_cameroon_azerty keyboard from the dropdown list. Verified that the keyboard is working in the web debug view. 3. Noticed that the output text does not appear in 'rounded' font. 
  
   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/cb66bff3-2d41-41c9-b601-eef83aab9d60">

**Comment by jahorton** [comment]
I was struggling to figure out a good way to refer to that font... apparently "rounded" didn't do it well.  What term might have worked better?  Perhaps the test spec should include a reference picture or two instead?

(Those font-related fails should be passes.  But... it's best we resolve a good way to clearly define this for the future.)

**Comment by jahorton** [comment]
Re: Developer... interesting.  I thought I remembered getting it to work correctly in Developer, but maybe not.  I went investigating... and the issue is that Developer isn't sending the right font information, which seems odd.

![image](https://github.com/keymanapp/keyman/assets/25213402/b438f2ef-7fe6-40cf-bb4a-cf0e1fa14537)

To focus on the part for this keyboard:
```js
kmw.KRS({
  "KN": "sil_cameroon_azerty",
  "KI": "Keyboard_sil_cameroon_azerty",
  "KL": "sil_cameroon_azerty",
  "KLC": "en",
  "KR": "Europe",
  "KRC": "eu",
  "KFont": {
    "family": "Consolas"
  },
  "KOskFont": {
    "family": "Andika Afr"
  },
  "KF": "sil_cameroon_azerty.js"
}/*8be90626184d7fd712b88fb69d7e5330662aec6dd75fa5fa46023976e7b0612b*/);
})();
```

Compare this to the actual package settings:

![image](https://github.com/keymanapp/keyman/assets/25213402/eeb430db-1508-4f4d-a65d-d89d838ab3ae)

Also of note: the data from above is my personal attempt to repro.  The OSK font isn't showing up correctly, unlike in your screenshots.  Either way, the same font is being used for in-page text, which is certainly not what I expected.

**Comment by jahorton** [comment]
"Intended, but not happy about it" were the words I got from him.  So... guess I'll need to drop that test.  I'll echo that "not happy about it" in regard to the tests not working out.

**Comment by mcdurdin** [comment]
> Also of note: the data from above is my personal attempt to repro. The OSK font isn't showing up correctly, unlike in your screenshots. Either way, the same font is being used for in-page text, which is certainly not what I expected.

Yeah, because remember you are not testing the package -- you are testing just the keyboard in isolation. KeymanWeb does not support loading packages, so we pass font settings in to the debugger from Keyman Developer's Keyboard/Fonts menu.

**Comment by bharanidharanj** [comment]
## SUITE_DEVELOPER: Use of KMW in the Developer test-host page

### GROUP_ANDROID_PHONE: 

* **TEST_SERVER_KEYBOARD (PASSED):** Tested with Keyman Developer 17.0.119-alpha-test-8560 in Windows 10 OS and here is my observation: 1. Opened gff_amharic project. 2. Opened the Keyboard in the local browser (http://localhost:8008/) and selected gff_amharic keyboard from the dropdown list. Verified that the keyboard is working in the web debug view.

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/165ffc96-3c34-47b3-86dc-e5bd9616d8c4">



### GROUP_IOS_TABLET: 

* **TEST_SERVER_KEYBOARD (PASSED):** Tested with Keyman Developer 17.0.119-alpha-test-8560 in Windows 10 OS and here is my observation: 1. Opened gff_amharic project. 2. Opened the Keyboard in the local browser (http://localhost:8008/) and selected gff_amharic keyboard from the dropdown list. Verified that the keyboard is working in the web debug view.

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/cea84745-5fb7-4214-b687-d2bb26b3c176">

**Comment by bharanidharanj** [comment]
## SUITE_MOBILE_APPS: 

### GROUP_ANDROID_TABLET: 

* **TEST_LAYER_SWAP_WITH_SELECTION (PASSED):** Tested with the Keyman Developer 17.0.119-alpha-test-8560 in Android 12 / Nexus 7 API 31 emulator and here is my observation:  1. Verified that the selection remains selected and that no changes occurred. Seems to be working fine. 

<img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/7081c824-9cb4-461c-801c-da8b6cbb6e7c">


* **TEST_START_OF_SENTENCE (PASSED):** Verified that the keyboard remains in its default layer after typing period (.). 2. Verified that the keyboard automatically shifts to the SHIFT (uppercased) layer after typing single space. 3. Verified that the keyboard returns to the default layer after typing T. 4. Verified that the keyboard automatically shifts to the SHIFT layer after moving the caret to before the letter T. 5. Verified that the keyboard returns to the default layer after moving the caret to before the letter s. Seems to be working fine. 

..SHIFT layer after typing single space

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/a19c6c5b-ecdc-450b-9ced-c8baf547389d">


....default layer shows after moving the caret to letter s

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/4789fbe7-3bc8-494d-9146-325c8ac4fae2">

**Comment by bharanidharanj** [comment]
## SUITE_MOBILE_APPS: 

### GROUP_IOS_PHONE: 

* **TEST_LAYER_SWAP_WITH_SELECTION (PASSED):**  Tested with the Keyman Developer 17.0.119-alpha-test-8560 in iOS 16.4 / iPhone 14 Pro Max simulator and here is my observation: 1. Verified that the selection remains selected and that no changes occurred. Seems to be working fine.

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/38a8190d-7d63-481e-bef3-39828de5fb89">


* **TEST_START_OF_SENTENCE (PASSED):** Verified that the keyboard remains in its default layer after typing period (.). 2. Verified that the keyboard automatically shifts to the SHIFT (uppercased) layer after typing single space. 3. Verified that the keyboard returns to the default layer after typing T. 4. Verified that the keyboard automatically shifts to the SHIFT layer after moving the caret to before the letter T. 5. Verified that the keyboard returns to the default layer after moving the caret to before the letter s. Seems to be working fine.

..SHIFT layer after moving the caret before T

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/2b6f9920-4f71-488f-991b-7aba17966119">


....default layer shows after moving the caret to letter s
   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/1aa68276-7a05-44b9-9d85-5b9a91a3e701">

**Comment by jahorton** [comment]
#8560 has merged!  🎊 

As this was a testing issue for that branch, we can retire this issue now.
