### ISSUE TITLE
bug(windows): links to pdf in welcome.htm give an error

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#9044]
Hi @mcdurdin, I did try adding a link from the welcome.htm , however clinking on the link from the Keyman installer screen that displays the welcome.htm , or from the Keyman Configuration "Help" button gives me this screenshot where it is unable to display the PDF file.  It seems to think the filetype is "chrome-extension".  Then browsing the Microsoft store it finds nothing, so it seems not to recognize the .pdf file extension.

![LinkFromKeymanWelcome](https://github.com/keymanapp/keyboards/assets/8098333/4abe2a8f-8ce1-4c15-9c71-821fc0a1bf48)

_Originally posted by @dyacob in https://github.com/keymanapp/keyboards/issues/2254#issuecomment-1595577455_

**Comment by mcdurdin** [comment]
@rc-swag I wonder if this is best addressed by always opening .pdf in a separate process (detect the link in the welcome.htm viewer and do a ShellExecute on the .pdf?)

**Comment by rc-swag** [comment]
Related issue #9018
