### ISSUE TITLE
chore(developer): tracking issue for additional kmw-compiler issues 🗜

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#9090]
## General issues

- [x] #9230
- [x] #9233
- [x] #9239
- [x] We need to verify that output of .js and .kmp for all keyboards in repo are (functionally) identical to kmcomp. (Check .kmx at the same time I think)
- [x] #9249
- [x] #9240
- [x] #9250
- [x] #9253
- [x] #9272
- [x] We need to check that hints and warnings generated are congruent with those produced by kmcomp -- there may be places where the new code does a better job (see e.g. #9108)
- [ ] #9266
- [ ] #9324
- [ ] #9325

## Tweaks to compiler messages

- [x] #9296
- [x] #9297
- [x] #9298
- [x] #9299
- [x] #9300

## kmcmplib issues identified

- [x] #9132
- [x] #9133
- [x] #9134

## general issues

- [x] #9205
- [x] #9208
- [x] #9209

## build.sh release/a/ahom_star

- [x] #9198

## build.sh release/a/aksarabali_panlex

- [x] #9097
- [x] #9098
- [x] #9156
- [x] #9160
- [x] #9100
- [ ] #9099

## build.sh release/a/anii

- [x] #9101
- [x] #9102
- [x] #9157

## build.sh release/a/armenian_mnemonic

- [x] #9103
- [x] #9185

## build.sh release/a/ausephon

- [x] #9104

## build.sh release/b/balochi_inpage

- [x] #9159
- [x] #9161
- [x] #9180

## build.sh release/b/bangla_munir

- [x] #9105
- [x] #9184

## build.sh release/b/btl_kenya

- [x] #9106

## build.sh release/basic/basic_kbdarmph

- [x] #9107

## build.sh release/basic/basic_kbdbr

- [x] #9177

## build.sh release/basic/basic_kbdinasa

- [x] #9178

## build.sh release/el/el_harari_latin

- [x] #9108

## build.sh release/fv/fv_gitsenimx

- [x] #9124

## build release/gff/gff_amh_7/extra/old-source/gff_amh_7.kpj

Note, this package would never normally be built, only built because it was found through a `find *.kpj`, but it was helpful to capture a legacy edge case.

- [x] #9148
- [x] #9150

## build.sh release/gff/gff_amharic

- [x] #9125
- [x] #9140
- [x] #9204

## build.sh release/k/korean_rr

- [x] #9181

## build.sh release/n/nailangs

- [x] #9203

## build.sh release/packages/gff_amh_powerpack_7

- [x] #9145
- [x] #9146
- [x] #9152
- [x] #9147
- [x] #9274

## build.sh release/rac/rac_marwari

- [x] #9207

## build.sh release/rac/rac_uyghur

- [x] #9109

## build.sh release/sil/sil_akha_act

- [x] #9183

## build.sh release/sil/sil_nko

- [x] #9182

## build.sh release/t/tohono_oodham

- [x] #9111
- [x] #9110

## build.sh release/v/vietnamese_telex

- [x] #9112
- [x] #9154
- [ ] #9113

**Comment by DavidLRowe** [comment]
"Warn if a .kps includes source files, .kmn, .keyman-touch-layout, .kvks, .kps at least."
Other files to check for (based on what I've seen) .ico and (believe it or not) .kmp! I seem to recall someone including HISTORY.md, README.md etc. as well.

**Comment by mcdurdin** [comment]
I think I can see legitimate reasons to include LICENSE.md, HISTORY.md, and README.md; some authors may wish to include the full license text in their package and history also. Even .ico may be okay -- it could be referenced from welcome.htm. But including .kmp is curious (recursion should make this impossible though?)

**Comment by mcdurdin** [comment]
Going ahead and closing this issue -- remaining open issues are new functionality or related to warnings about BCP47 tags, which are not going to block us.
