### ISSUE TITLE
bug(iOS): Page Not Found message appears If I try to download FirstVoices build from Keyman Status Site

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#9094]
### Describe the bug

I noticed that after clicking the FirstVoices download link it leads to 404 error page.

### Reproduce the bug

1. Open 'https://status.keyman.com/' site. 
2. Click the 'FirstVoices' build from iOS platform. 

Here, I noticed that by clicking on the download link it is showing 'Page Not Found' error (404) message. 

I have attached the screenshot for reference. 

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/d0cd88c3-754a-4449-b02b-10d130ebe295">

### Expected behavior

By clicking the FirstVoices link should download the corresponding build on the system. 

### Keyman apps

- [ ] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.129-alpha

**Comment by jahorton** [comment]
I believe we currently have its build component disabled.  Is that right, @mcdurdin?  If so, I believe there's an external issue or two awaiting resolution before we reactivate it.

**Comment by mcdurdin** [comment]
Yes, this is due to the FV certificate having expired, waiting for FPCC to renew. (@madebybridget any progress here?)

**Comment by sgschantz** [comment]
FirstVoices builds are available as expected.
