### ISSUE TITLE
[Android] globe button in system keyboard broken

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#913]
Android app globe button is not switching the keyboards in system level. Instead it is changing the keyboards within the keyman layouts. 

Once the user selects keyman layout, he/she can't select any other keyboard layout besides the keyman layout.

**Comment by darcywong00** [comment]
The globe button is only intended to install or select another Keyman keyboard/language.

The Android menu for changing the system keyboard depends on your device's vendor and Android version.

For example, on my Android 7.1.1 (Nougat) device, I would go to:
Settings --> Languages & Input --> Virtual keyboard

**Comment by darcywong00** [comment]
My apologies. On further testing, there seems to be an issue getting the globe button functioning in the system keyboard.

I suspect it's a side effect of #848 and will investigate more this sprint

**Comment by MayuraVerma** [comment]
All the third party keyboards are switching system wide keyboards in the device I am testing.

I am not a android user to confirm or comment on other devices.

Here is android documentation, I am sure you are aware of this.
https://developer.android.com/guide/topics/text/creating-input-method

**Comment by erros84** [comment]
I thought it was a requirement that Android keyboards give you the ability to jump to the next input method, even if not Keyman. 

As Keyman does not (yet) have technologies that facilitate the kind of entry we expect for vehicular languages (swype/autocomplete/etc), It is reasonable to pair a KM keyboard for a minority language with a Swype/Google keyboard for French or English.

I would love to see a button in the Globe popup that opens the system IME chooser.  Some manufacturers make the chooser painfully hard to find.

**Comment by darcywong00** [comment]
@erros84 I'll move your suggestion to a new issue (for future development). Thanks!
