### ISSUE TITLE
bug(core): tag all KMXPlus file-based structs with alignment 🙀 

### ISSUE THREAD

**Issue by srl295** [keymanapp/keyman#9139]
ref: https://github.com/keymanapp/keyman/pull/9134#issuecomment-1614029004

* We should tag any KMXPlus file-based structs with alignment

also see #9138

**Comment by srl295** [comment]
do we want two issues?

first one is pretty small, nearer term

**Comment by mcdurdin** [comment]
> do we want two issues?

Perhaps split when we implement first one.

**Comment by srl295** [comment]
I can even reopen the one originally filed for it
