### ISSUE TITLE
bug(web): Keyboard keys are not properly aligned for some device models in local browser window

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#9163]
### Describe the bug

I noticed that after opening gff_amharic keyboard in a local browser window by selecting iPhone or iPad device models, the keys are not properly aligned in the keyboard pad. 

### Reproduce the bug

1. Install Keyman Developer 17.0.132-alpha build
2. Open gff_amharic project in Keyman Developer.
3. Click Build tab. 
4. Select 'http://localhost:8008' web link. 
5. Click Open in browser button. 
6. Select 'gff_amharic' keyboard  from the keyboard list. 
7. Select ' iPhone 5S' phone device from Device list. 

Here, I noticed that the keyboard is not appearing properly

..iPhone 5S

 <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/a67a7000-545e-4ca1-ad29-e6cc7ca05468">  
 

..Pixel5

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/9288e661-e6a3-4525-b106-022554fc990c">

..iPad Mini

  <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/9ab01e51-b293-4b63-bcbd-b39e70f82130">

  
..Nexus 9

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/74b73869-74db-4a2c-82c1-c97caccf8656">

### Expected behavior

By selecting iPhone or iPad device models, the keys should appear properly on the Keyboard pad. (in gff_amharic keyboard)

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [X] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.132-alpha

### Operating system

Windows 10 OS, Windows 11 OS (VM)

### Device

iPhone, iPad 

### Keyboard name

gff_amharic

### Language name

Amharic

**Comment by mcdurdin** [comment]
@jahorton this looks like it might be a regression in KMW?

**Comment by jahorton** [comment]
It looks like the CSS stylesheets aren't being applied properly on the Developer test-host page - neither the standard OSK stylesheet nor the keyboard's custom one.  We confirmed that I had it working at one point late in the ES-module feature branch, but maybe it broke again somehow?

Either way, this works fine in standalone KMW using the main backing feature:

![image](https://github.com/keymanapp/keyman/assets/25213402/07142d00-4d92-4c32-91ca-7ca20154e860)

So it shouldn't be Web-side.

(Note that #9175 was needed to actually get the image above.)

**Comment by jahorton** [comment]
The last Developer version I had installed - from during the ES module work - loads the keyboard onto the test page correctly as well.

**Comment by jahorton** [comment]
I am not getting a repro on this (on my machine) for 17.0.133-alpha.

![image](https://github.com/keymanapp/keyman/assets/25213402/74d58043-cfbc-4c43-83ee-021360a8b616)

...

**Comment by bharanidharanj** [comment]
@jahorton Retested with the latest Keyman 17.0.139-alpha build in both Windows 10 and 11 OS and here is my observation: 1. I noticed that I was able to reproduce this issue only in Windows 11 OS. It is working fine with Windows 10 OS.  I have attached the Screenshot for reference. 

..in Windows 10 OS

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/366945ae-049f-4c1b-b9bd-ef149040d7a4">


..in Windows 11 OS

<img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/4d691738-55d8-4c25-90ca-dc9cc731d3d5">

**Comment by bharanidharanj** [comment]
@jahorton Retested with the latest Keyman Developer 17.0.147-alpha build in Windows 11 OS (VM)  and here is my observation: 1. I was not able to reproduce this issue with the recent build. 2. It is showing the correct keyboard. 3. Seems to fixed and working fine with the recent build. Thanks!

..iPhone

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/e6f295e2-71b3-4bb8-a0a2-790a4e459a97">

..iPadMini

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/88ab155b-a44e-4a78-b016-7f6ba6646ae2">

..Nexus

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/18a44a02-c485-4252-a4f0-5718a749a74c">
