### ISSUE TITLE
bug(web): Sentry error reports are not being properly matched against the source

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#9176]
Looks like some of the changes from the ES module work have led to a significant reduction in detail in the quality of our Sentry error reports.

Example report:
https://keyman.sentry.io/share/issue/0500abcd12734ba18d7399b764c57a02/

![image](https://github.com/keymanapp/keyman/assets/25213402/4d7bf911-b6c7-4316-b4ad-8ed2d2744e47)

**Comment by mcdurdin** [comment]
Missing sourcemaps (or perhaps just keymanweb-webview.js filename not matching appropriate sourcemap data?)
