### ISSUE TITLE
[Windows] Keyboards with BCP-47 language tags in package metadata are not installing on Windows 7

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#919]
Version 10.0.1098
Windows 7 enterprise service pack 1

Keyboard shows its installed but it is not available in language bar.

When I close the keyman desktop and reopen or even open the configuration. I get error
![image](https://user-images.githubusercontent.com/14062593/40728669-42ae47a2-63f0-11e8-8897-91952e6d0a4b.png)

I keep getting the error.

I have uninstalled the application twice and reinstalled.
I have removed the keyboard package and reinstalled.

Still no luck.

**Comment by MayuraVerma** [comment]
Same keyboard installs in windows 10 and iPhone without any trouble.

The keyboard doesn't install in Windows 7.

**Comment by mcdurdin** [comment]
Can you let me know which keyboard this is? If it is a custom keyboard, I need to know the language codes associated with the keyboard. Or, if you can share the .kmp file in this issue, then I can test it more easily.

**Comment by mcdurdin** [comment]
Okay, I managed to reproduce this issue. Attaching a test keyboard.

[bcp47test.zip](https://github.com/keymanapp/keyman/files/2071021/bcp47test.zip)

**Comment by mcdurdin** [comment]
Possibly related: when installing sil_ipa, no language association is added.

**Comment by MayuraVerma** [comment]
@mcdurdin please check your DM in SIL forum.

**Comment by mcdurdin** [comment]
This should be fixed in build 1103, which will land tonight.

**Comment by MayuraVerma** [comment]
@mcdurdin Now, the keyboard is successfully installed in Windows 7.

However. It is not picking up the correct language.
It is defaulting to "English". User can manually change the language from English to the language of Keyboard. But this is not preferred.

Please review.

**Comment by mcdurdin** [comment]
Okay, I've tested that here and I understand the problem. On Windows 7, we should never attempt to install with a script subtag. I am working on that; for other platforms the script subtag may be required so don't remove it from the tag.

**Comment by MayuraVerma** [comment]
Could also please test for include region tag

**Comment by mcdurdin** [comment]
There's no need to strip the region subtag -- it's accepted by Windows. You should only include a region subtag if you need to differentiate a keyboard that is for other regions with the same language.

**Comment by MayuraVerma** [comment]
With version 10.0.1105, Keyman is able to install version 10 keyboards in Windows 7, correctly.

Also, I found a different issue related to this. Please review 
https://github.com/keymanapp/keyman/issues/975
