### ISSUE TITLE
bug(android): Keyboard position does not fit properly in the screen after changing to Landscape Orientation in Android 12.0 OS

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#9191]
### Describe the bug

I noticed that after changing the orientation to landscape mode the keyboard position changes and it does not fit properly in the keyboard frame.

### Reproduce the bug

1. Install Keyman 17.0.133-alpha build. 
2. Open Keyman In-App. 
3. We may notice that the Get Started dialog opens along with keyman application. 
4. Change the Orientation from Portrait to Landscape. 
5. Close the Get Started dialog. 

Here, I noticed that the Keyboard does not fit in its position. 

Note: It is only reproducible in Android 12.0 OS. 

I have attached the Screenshot as well as the Video file for reference. 

..in Android 12.0 Mobile

   
![android12mobile](https://github.com/keymanapp/keyman/assets/19683143/19194193-b7d1-4e4c-a4cf-15b750a7f314)

..in Android 12.0 Nexus 7 Tab

  
![NexusAndroid](https://github.com/keymanapp/keyman/assets/19683143/14dc7f0f-28b9-4470-a526-73f38669e81f)

..Android 12.0 Mobile Video

https://github.com/keymanapp/keyman/assets/19683143/9dc16e68-6125-4943-960d-9a576608cdd6

..Android 12.0 Nexus Video

https://github.com/keymanapp/keyman/assets/19683143/c8c11169-f623-405b-97c8-1d3e4ef46810

### Expected behavior

After changing the orientation to landscape the keyboard position should fit into the screen. 

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.133-alpha

### Operating system

Android 12.0

### Device

Android Mobile (Emulator), Nexus 7 (Emulator)

**Comment by darcywong00** [comment]
Addressing Android OSK in A17S25
