### ISSUE TITLE
[developer] KMW Deadkeys that work on KM9 keyboard fail when compiled as KM10

### ISSUE THREAD

**Issue by erros84** [keymanapp/keyman#920]
I have a Keyboard (https://github.com/silcam/Cameroon-Keyboard/blob/BrokenRules/src/km/cameroon_qwerty/source/cameroon_qwerty.kmn) that was written for KM9 ( ﻿store(&VERSION) '9.0' ) .

When I change it to ﻿store(&VERSION) '10.0', I gain the better handling of RALT and CAPS in KMW10 (which is AMAZING, btw!), but I lose deadkeys in KMW with a hardware keyboard. (Debugger/Keyman Native work fine) 

As far as I can tell, it is related to this change: (https://github.com/keymanapp/keyman/commit/19a570a7d3ea30c684d03d7fad944c7440e12c55#diff-880fb835e18dcfeb02a3ed891f7a5c97R686) 

Here's my debugging info:

Keyman 9.0, Deadkey works (because 1-1=0): 
![km9 working deadkey](https://user-images.githubusercontent.com/986339/40744063-570a402e-644b-11e8-8f00-d9df8f3e4c7f.png)

Keyman 10.0 Deadkey fails (because 1-1<>1): "kmwcallback.ts:768 Unmatched contextual index() statement detected in rule with index 1!"
![km10 broken deadkey](https://user-images.githubusercontent.com/986339/40744113-8642bc54-644b-11e8-964c-b8dc44992451.png)

It is obvious that the resulting index of `this._AnyIndices` has changed, and the code is missing the desired value, but I can't find where the variable that becomes PN is defined. My best guess is that the fault is in the KMW10 compiler, but not in the KMW9 compiler.

Steps to reproduce:
Install KM Dev 10, versions 1093-1098.
Compile the cameroon_qwerty.kmn keyboard and open in Chrome test on web.
Type the combination `;e`, which should give `ə`.
It should work here.
Change the header to store(&VERSION) '10.0'
Recompile and retest `;e`. It will fail to produce the desired output and give the error: "kmwcallback.ts:768 Unmatched contextual index() statement detected in rule with index 1!"

 I hope this is the last blocker bug before I'm ready to submit my keyboard to the Repo.

Another keyboard is affected by the same bug, but isn't compatible with KM9 (RALT, CAPS), so I can't test it in the same way.
https://github.com/silcam/Cameroon-Keyboard/blob/BrokenRules/src/km/cameroon_azerty/source/cameroon_azerty.kmn

**Comment by erros84** [comment]
Is this affecting anyone else?

**Comment by mcdurdin** [comment]
That's a great writeup, thank you. Will investigate.

**Comment by mcdurdin** [comment]
Minimal repro
```
c To repro, on KMW, press <;a> which works. then press <;e> which doesn't
store(&VERSION) '10.0'
store(&NAME) 'Secondary group any mismatch #920'
store(&TARGETS) 'any'

begin Unicode > use(main)

group(main) using keys

+ [K_E] > U+0065
+ [K_COLON] > dk(semicolon)

store(a-key) 'a'
store(a-out) U+1D44 
dk(semicolon) + any(a-key) > index(a-out, 2)

match > use(deadkeys)   

group(deadkeys)

store(e-key)  'e' 
store(e-out)  U+0259
dk(semicolon) any(e-key) > index(e-out, 2)
```
