### ISSUE TITLE
bug(linux): Keyman Keyboard icon does not appear in the system tray

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#9263]
### Describe the bug

I noticed that the keyboard icon is missing on the system tray even though I installed some keyboards using keyman configuration. 

### Reproduce the bug

1. Install Keyman 17.038-alpha build
2. Open Keyman Configuration dialog. 
3. Download and Install some languages like Khmer Angkor, Amharic, Vietnamese Telex etc.,
4. Restart the system. 
5. Start Keyman Keyboard. 
6. Click the Keyman icon from the system tray. 
7. From the Keyboard list, select a keyboard. for example, select Khmer Angkor keyboard. 

Here, I noticed that the Khmer Angkor keyboard icon does not appear in the system tray. 

Note: The Keyboard icon appears correctly in Windows build and Wasta 20.04 Linux build. 

I have attached the Screenshots for reference. 

..Keyboard icon appears in Windows OS builds

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/0c3e89a7-d5d5-4fb9-bbd0-05f9a48f5407">

..Keyboard icon appears in Wasta builds

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/93bcc039-de91-4d00-8514-93b7f3dd5d1a">

..Keyboard icon is missing in the system tray in other Linux versions (Ubuntu Focal, Jammy and Lunar)

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/c6ee9c9e-7dbd-4560-8281-a4c23dde342f">

### Expected behavior

Keyman Keyboard icon should appear in the system tray

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [X] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0138-alpha

### Operating system

Ubuntu 20.04 Focal, Ubuntu 22.04 Jammy and Ubuntu 23.04 Lunar Linux OS

**Comment by ermshiperete** [comment]
This is by design: Ubuntu decided to show the language abbreviation instead of an icon. There's nothing we can do.
