### ISSUE TITLE
question(developer): how do we handle non-minimal tags using kmc on keyboards repo 🗜

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#9266]
On the hint vs warning conundrum: currently, kmcomp _warns_ for package builds, and keyboard_info metadata verification, on non-minimal tags. However, for reasons, it doesn't respect the Warnings-As-Errors flag in the project for package and keyboard_info warnings, so the keyboards repo build succeeds despite that. But kmc is consistent in its treatment of warnings, so the build does fail on non-minimal tags.

The kmcomp build has around 2500 instances of the warning!

Hence I was looking at the options:

1. reducing this to a hint in order to have a passing build.
2. turn off warnings-as-errors for all keyboards that have this issue, or even for the entire build.
3. fixup all the tags.
4. eliminate the warning altogether because it's not really fitting its purpose at present.

The only really viable option I can see is (1) at present, with the option to turn it back up to a warning in the future when we finally get to revisiting our BCP 47 tag treatment across all platforms.

Relates to #9099.

**Comment by srl295** [comment]
1 (warning to a hint) may be best for now.
