### ISSUE TITLE
[Windows] Unexpected hotkey behavior

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#927]
@sdysart reports having this **intermittent** issue 

In Keyman Configuration, he had assigned a Hotkey for "Open Keyboard Menu" with a custom hotkey:
"Shift + M".

We think we understand Desktop overrides "Shift" with "Ctrl + Alt" because the panel statuses the hotkey:

"Ctrl + Alt + M"
![image](https://user-images.githubusercontent.com/7358010/40773647-b2e4e24e-64ed-11e8-8b78-f3e5aaef8819.png)

On rare occasion (he's noticed when using Thunderbird email client), he'll try to type `M` and the Keyman Keyboard menu appears instead.

`Ctrl + Alt + M` reliably bring up the Keyboard menu.

This is very sporadic, so we'll have to report more details if/when it comes up again.

### Configuration ###
Windows 10
Keyman Desktop 10.0.1096
Thunderbird 52.8
Keyboard using default English (US)

**Comment by mcdurdin** [comment]
Probably resolved (Shift+M is not a permissible hotkey). The sporadic issue is most likely resolved by serialised input fix.

**Comment by darcywong00** [comment]
I'm re-opening because @sdyart and another user are seeing this with Keyman 13.0.115.0 stable.

On a fresh install (with the sil_ipa keyboard), the default hotkeys are:
|      |     | 
| ---- | --- |
| Switch Keyman Desktop Off  |    Shift+Alt+O |
| Show On Screen Keyboard Pane  |    Shift+Alt+K |

## Expected Behavior
When Keyman is running and the default Windows US keyboard selected:
* Shift-O should output upper-case "O"
* Shift-K should output upper-case "K"

## Actual Behavior
* Shift-O turns Desktop off
* Shift-K brings on the OSK
(neither O or K are output)


When he tries to reassign "Show On Screen Keyboard Pane" --> Custom
Holding either left shift or right Shift is reporting "Ctrl+Alt" ...

For a workaround, they're disabling these two hotkeys.

**Comment by mcdurdin** [comment]
Not currently reproducible; also this relates only to the dialog -- see #3852 for alternative report.
