### ISSUE TITLE
chore(developer): using json modules triggers ExperimentalWarning in kmc 🗜

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#9272]
Coming out of #9253. When we launch kmc now, nodejs emits the following warning to stderr:

```
(node:19668) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
```

This is unfortunate because it will be annoying cmdline noise for kmc. While we can avoid this for Keyman Developer's kmc.cmd by using `--no-warnings`, this is not ideal, and won't work for the npm packaged version -- is there a way we can do this for npm as well?

**Comment by mcdurdin** [comment]
Thoughts @srl295 and @jahorton ?

**Comment by mcdurdin** [comment]
Noting that we can use the shebang for kmc.ts to avoid this on *nix, but not on Windows:

```
#!/usr/bin/env -S node --no-warnings
```

**Comment by jahorton** [comment]
One possibility, if we're fine being node-only: https://www.stefanjudis.com/snippets/how-to-import-json-files-in-es-modules-node-js/#option-2%3A-leverage-the-commonjs-%60require%60-function-to-load-json-files

`require` statements for JSON files are long-supported, so we can reconstruct a Node `require` statement and dodge things that way.

Something else of interest I bumped into:
- https://github.com/tc39/proposal-import-attributes#synopsis
- https://twitter.com/robpalmer2/status/1639014193369354240

It appears that `with` is winning out over `assert` for this style of syntax.  Not sure if that'll have an effect on the warning or not.

**Comment by mcdurdin** [comment]
> One possibility, if we're fine being node-only

A design req for kmc is for it to _not_ depend on Node.

> It appears that `with` is winning out over `assert` for this style of syntax. Not sure if that'll have an effect on the warning or not.

AFAIK, the `with` syntax is not implemented in Node 18 / tsc yet, and in any case it doesn't have an impact on the warning per the [Node source](https://github.com/nodejs/node/blob/7196946d7f59652c19dec278186165806b1e28ad/lib/internal/modules/esm/translators.js#L263).

**Comment by jahorton** [comment]
Yeah... kinda what I figured.  😞

**Comment by srl295** [comment]
Well. Make a configure step that converts the json into a .ts file..?

I expect the syntax to sort out eventually.

**Comment by mcdurdin** [comment]
> Well. Make a configure step that converts the json into a .ts file..?

I hate your suggestion and am going to implement it forthwith. Thank you!
