### ISSUE TITLE
[Mac] Crash in KMConfigurationWindowController.m line 389 on MACOSX 10.7.5

### ISSUE THREAD

**Issue by tombogle** [keymanapp/keyman#928]
Error: objc[274]: garbage collection is OFF objc[274]: cannot form weak reference to instance (0x7fd60d1229b0) of class KMConfigurationWindowController

Call stack:

Crashed: com.apple.main-threadSIGILL 0x00007fff8e721768 Raw Text
--
0 | libobjc.A.dylib | _objc_trap + 4
1 | libobjc.A.dylib | _objc_fatal + 193
2 | libobjc.A.dylib | weak_register_no_lock + 344
3 | libobjc.A.dylib | objc_storeWeak + 360
4 | Keyman | KMConfigurationWindowController.m line 389-[KMConfigurationWindowController startTimer]
5 | Keyman | KMConfigurationWindowController.m line 60-[KMConfigurationWindowController windowDidLoad]
6 | AppKit | -[NSWindowController _windowDidLoad] + 566
7 | AppKit | -[NSWindowController window] + 109
8 | Keyman | KMInputMethodAppDelegate.m line 858-[KMInputMethodAppDelegate configWindow]
9 | Keyman | KMPackage.m line 29-[KMPackage makeWindowControllers]
10 | AppKit | -[NSDocumentController openUntitledDocumentAndDisplay:error:] + 448
11 | AppKit | -[NSDocumentController(NSInternal) _openUntitled] + 112
12 | AppKit | -[NSApplication _doOpenUntitled] + 273
13 | AppKit | -[NSApplication(NSAppleEventHandling) _handleCoreEvent:withReplyEvent:] + 330
14 | CoreFoundation | -[NSObject performSelector:withObject:withObject:] + 65
15 | Foundation | __-[NSAppleEventManager setEventHandler:andSelector:forEventClass:andEventID:]_block_invoke_1 + 101
16 | Foundation | -[NSAppleEventManager dispatchRawAppleEvent:withRawReply:handlerRefCon:] + 283
17 | Foundation | _NSAppleEventManagerGenericHandler + 105
18 | AE | aeDispatchAppleEvent(AEDesc const*, AEDesc*, unsigned int, unsigned char*) + 200
19 | AE | _ZL25dispatchEventAndSendReplyPK6AEDescPS_ + 38
20 | AE | aeProcessAppleEvent + 250
21 | HIToolbox | AEProcessAppleEvent + 102
22 | AppKit | _DPSNextEvent + 1247
23 | AppKit | -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 135
24 | AppKit | -[NSApplication run] + 470
25 | Keyman | main.m line 21main

Explanation: This version of the operating system did not allow weak references to instances of NSViewController. See https://developer.apple.com/library/content/releasenotes/ObjectiveC/RN-TransitioningToARC/Introduction/Introduction.html

**Comment by tombogle** [comment]
I don't have an installed Parallels VM with 10.7.5. Looks like the license for 10.7 is $19.99 (here: https://www.apple.com/shop/product/D6106Z/A/os-x-lion). Not sure if it's worth buying to try to test this.

**Comment by mcdurdin** [comment]
According to http://gs.statcounter.com/macos-version-market-share/desktop/worldwide, 10.7 has only 1% market share. I suggest we don't attempt to spend any further time on this.

**Comment by tombogle** [comment]
Old OS - low priority - won't fix.
