### ISSUE TITLE
mac issue: Libreoffice

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#931]
Libreoffice Version: 6.0.3.2
Build ID: 8f48d515416608e3a835360314dac7e47fd0b821
CPU threads: 4; OS: Mac OS X 10.13.5; UI render: default; 
Locale: en-US (en_US.UTF-8); Calc: group
Keyman: version 10.0.43

Expected: Context: U+0CAA Output: U+0CCA
Actual: Context: U+0CAA Output: U+0CAA U+0CCA (context is repeated. ERROR)

![image](https://user-images.githubusercontent.com/14062593/40815807-a1a9ebe8-650e-11e8-83ce-6b23cb867e93.png)

Keyman functioning fine in Pages.

**Comment by MayuraVerma** [comment]
@tombogle Please check your DM in SIL forum.

**Comment by MayuraVerma** [comment]
@mcdurdin This is bug in mac and serious compatibility issue in libreoffice, possibly in other applications.
Please do not tag is as future. Please try to resolve it with version 10.0.

**Comment by tombogle** [comment]
Tested and found no issues with LibreOffice Vanilla

**Comment by MayuraVerma** [comment]
@tombogle This is still same issue. I have tested on two mac's I am find the same error.
