### ISSUE TITLE
feat(android): Investigate use of downloadable fonts

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#932]
[Reference](https://developer.android.com/guide/topics/ui/look-and-feel/downloadable-fonts)

> Android 8.0 (API level 26) and Android Support Library 26 introduce support for APIs to request fonts from a provider application instead of bundling files into the APK or letting the APK download fonts. The feature is available on devices running Android API versions 14 and higher through the Support Library 26.

Since our minimum API is 15, we should investigate to see if this will allow us to download fonts to use in the system keyboard.

At the minimum, we could remove asset/ fonts

**Comment by darcywong00** [comment]
Alternative method is [Fonts in XML](https://developer.android.com/guide/topics/ui/look-and-feel/fonts-in-xml) which is available for Android 4.1 (API level 16) and higher, using the Support Library 26.

**Comment by darcywong00** [comment]
Maybe less relevant now that 14.0 strictly installs keyboard packages where it already includes fonts

**Comment by mcdurdin** [comment]
I think this is no longer relevant.
