### ISSUE TITLE
feat(mac): Functionality to control behaviour of RAlt rules

### ISSUE THREAD

**Issue by andjc** [keymanapp/keyman#933]
Keyman 10  on macOS will use the RALT rules allowing a single set of rules across desktop platforms.

This has an unintended side effect in KM10: The Right Option key will produce output matching the rules for the RALT key sequences defined in the kmn file. While the Left Option key generates characters from the underlying system keyboard. This is potentially confusing on Latin script keyboards.

There are a few possible workarounds, depending on whether the Keyman app will choose a canonical approach, or whether the user or keyboard developer is given some control over this.

There are three possible scenarios :

1. existing KM10 RALT rules are used by right option key, and left option key remains as is accessing the underlying keyboard. (this is probably most confusing for the user)
2. RALT rules are mapped to both left and right Options buttons in macOS
3. RALT rules use Right Option key, and output of Left Option key suppressed or nulled out

I would suggest a two-pronged approach; 
- allow the keyboard developer to specify the default behaviour in the kmn file. 
- and if macOS app supports options in the future (similar to what is possible on Windows), allow the kbd developer to expose this behaviour as an option for the end user to change the default specified by the keyboard developer.

It is possible to take a user-centric approach and have all choices made by the user, but I'd advocate for the kbd developer choosing the appropriate behaviour keyboards.

Feel free to ignore ;)

**Comment by mcdurdin** [comment]
Thank you for the detailed writeup @andjc. I've scheduled this for investigation in the future as we are close to the end of the beta cycle for 10.0, but I agree this is confusing and needs to be improved.
