### ISSUE TITLE
[Windows] Language Association is sometimes wrong

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#936]
Sometimes Keyman gets confused about what language to associate a keyboard with. For example Kmhmu:
![image](https://user-images.githubusercontent.com/7071907/40732013-f99fd85c-63f7-11e8-9894-555c9a214b50.png)
If I delete Greek through Region and Language Settings (Windows 10)
Then it switches to Arabic:
![image](https://user-images.githubusercontent.com/7071907/40732135-43c5bfc8-63f8-11e8-950c-442af1b14cc4.png)

Delete Arabic and it switches to Yi:
![image](https://user-images.githubusercontent.com/7071907/40732256-872dd1f6-63f8-11e8-867e-b4b158f34b07.png)

The keyboard seems to work fine.
I just upgraded to Keyman Desktop v 10.0.1098.0 but it was doing this before with 10.0.1092.0 (I think).

I haven't been too worried since I'm installing and uninstalling so many keyboards for testing, but I don't know if others have seen this.

Moved from keymanapp/keyboards#312

**Comment by LornaSIL** [comment]
Here's another instance:
![image](https://user-images.githubusercontent.com/7071907/40942475-f2a7ffc8-6813-11e8-887b-3cb585ab4046.png)

Using KeymanDesktop 10.0.1098.0

**Comment by LornaSIL** [comment]
After uninstalling the Hieroglyphics keyboard I get this:
![image](https://user-images.githubusercontent.com/7071907/40942645-7e13f15c-6814-11e8-9523-aa5f080fc280.png)

**Comment by mcdurdin** [comment]
I believe this was fixed with the release of 10.0. Current work relating to #3512 should resolve any outstanding problems that may be related.
