### ISSUE TITLE
bug(developer): sil_cameroon_qwerty keyboard appears to be a normal keyboard when I switch to some device models in localhost

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#9362]
### Describe the bug

I noticed that the normal keyboard appears in some device models when I set 'sil_cameroon_qwerty' keyboard in a localhost browser. 

### Reproduce the bug

1. Install Keyman Developer 17.0.18-alpha build in Windows 11 OS. 
2. Open Sil_Cameroon_Qwerty.kpj project. 
3. Click the Build tab. 
4. Click 'Test Keyboard on web' button. 
5. Click 'http://localhost:8008' web link address from the web address pane. 
6. Click 'Open in browser' button. 
We may notice that the 'localhost:8008' page open in a browser. 
7. Select 'sil_cameroon_qwerty' Keyboard from the Keyboard dropdown list. 
8. Select 'iPhone 5S' device from Device dropdown list. 

Here, I noticed that the keyboard is appear to be normal keyboard. I am seeing the same issue when I switch to some other device models like Pixel 5, iPad Mini and Nexus 9 etc., 

Note: I was not able to reproduce this issue in Windows 10 OS. 

I have attached the Screenshots for reference. 

..Windows 10 OS

..iPadMini

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/2b7732dd-9fba-43a8-8453-e23f9ef5d427">

..Nexus9

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/0d324970-b47f-4bc2-826d-c8288b924ac7">

..Pixel5

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/4549b73b-8fdf-45b4-a8d8-692b12a4226f">

..Windows 11 OS

..iPadMini

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/ccf5a74f-230e-4624-8f71-7d2bde40f613">

..iPhone 5

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/da3a9624-9d22-40d5-879c-14e8523a0814">

..Pixel 5

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/4f5392b5-41d1-4c25-beb9-38371947f3a1">

..Nexus 9

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/dfd10232-1d20-40e3-88ef-16ca0bc0bff3">

### Expected behavior

Setting sil_cameroon_qwerty keyboard along with device models like iPhone, Nexus 9 etc., should show the right cameroon qwerty keyboard on the page. 

### Related issues

#9163

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [X] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.148-alpha

### Operating system

Windows 11 OS (VM)

### Browser

localhost:8008

### Keyboard name

sil_cameroon_qwerty

**Comment by MattGyverLee** [comment]
Interesting. Things look fine in 16.0.141 and I haven't installed 17 yet to see this. I'm assuming that this is a compile issue and there's nothing I need to do on my end.

**Comment by MattGyverLee** [comment]
I can't reproduce this in 17.0.198. I'm not sure what fixed it in 17.0.147 (https://github.com/keymanapp/keyman/issues/9163) for @jahorton, but it looks like it's resolved for Cam Qwerty as well.

**Comment by mcdurdin** [comment]
@bharanidharanj can you reproduce this issue in latest Keyman Developer 17 alpha?

**Comment by bharanidharanj** [comment]
> @bharanidharanj can you reproduce this issue in latest Keyman Developer 17 alpha?

@mcdurdin Retested with the latest Keyman 17.0.203-alpha build on Windows 11 OS and I can reproduce this issue.

**Comment by MattGyverLee** [comment]
> @mcdurdin Retested with the latest Keyman 17.0.203-alpha build on Windows 11 OS and I can reproduce this issue.

I still can't reproduce the issue in 17.0.203 on Windows 11. I've tried. Is it a server cache issue on @bharanidharanj 's Win11 machine from an old build?

**Comment by mcdurdin** [comment]
We will look at this today together on @bharanidharanj's computer.

**Comment by mcdurdin** [comment]
Yes, server cache issue. Need to investigate why the cached content was corrupted.

**Comment by mcdurdin** [comment]
Looks like it was just an old version 6.0.6 of sil_cameroon_qwerty. Rebuild after server cache clear resolved (see also #9848 for server cache issue)
