### ISSUE TITLE
Heroku Application Error trying to sign up for iOS beta

### ISSUE THREAD

**Issue by punchcutter** [keymanapp/keyman#937]
I want to try the iOS beta so I went to https://keyman-ios-beta.herokuapp.com/ and all I get is 
```
Application error
An error occurred in the application and your page could not be served. 
If you are the application owner, check your logs for details.
```

**Comment by mcdurdin** [comment]
Okay, we've resolved this problem; it was due to Apple updating their privacy policy and we needed to login to the site and accept the changes...  https://github.com/fastlane/fastlane/issues/12577

Thank you for the report.
