### ISSUE TITLE
bug(web): Suggestion word 'Characteristics' appear partially in the suggestion bar

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#9371]
### Describe the bug

I noticed that the suggestion word 'Characteristics' does not appear fully in the suggestion bar. 

### Reproduce the bug

1. Install Keyman 17.0.149-alpha build. 
2. Open Keyman In-App. 
3. Type 'Chara' using English -EuroLatin(SIL) Keyboard. 

Here, I noticed that the last two letters are missing from the suggestion word 'Characteristics' in the suggestion banner. 

Note: I am not seeing this issue in Nexus 7 Tab Simulator. 

I have attached the Screenshot for reference. 

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/323c4245-169b-4f3e-b16b-30e1a1c40033">
   
   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/4ac269e3-0743-4339-90b7-92d6af266b38">

### Expected behavior

The suggestion word 'Characteristics' should be full visible in the suggestion banner. 

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.149-alpha 

### Operating system

Android 5.0, 9.0, 12.0

### Device

Redmi Note 8 Pro, API 31 emulator

**Comment by jahorton** [comment]
This is what #7934 seeks to address.  It's a limitation of the existing design and subpar UI.

**Comment by darcywong00** [comment]
I believe the suggestions are just truncated. I think you should be able to drag the suggestion left/right to see the rest of the word.

**Comment by jahorton** [comment]
Relates to #7934.
