### ISSUE TITLE
[Developer] Debugger can't handle Shift>Alt>[Letter]

### ISSUE THREAD

**Issue by MattGyverLee** [keymanapp/keyman#939]
KMDev10.1101.0

The Debugger doesn't ever read [NCAPS SHIFT RALT K_E],  [SHIFT RALT K_E]  or Shift+RAlt+anything the first time. I have to type [SHIFT RALT K_E] + [K_E] (continuing to hold Shift/RALT, but hitting the E key twice.) Debugging seems to step through the correct steps, but the text doesn't appear until the second keypress.

[SHIFT RALT K_E] (or similar) works every time in KM Native/Web; so this is just the debugger. I don't know when this behavior started. 

Tested with KM10 and KM9 Keyboards.

**Comment by mcdurdin** [comment]
This will be resolved with the refactor of Keyman Engine for Windows key processing in Keyman 11.

**Comment by tombogle** [comment]
I just noticed this when creating a test keyboard with the rule:
+ [SHIFT RALT K_C] > 'Shift/Ralt+C '
In the debugger, the output is:
hift/Ralt+C
No matter what I put as the output, the first character gets suppressed.

**Comment by mcdurdin** [comment]
Resolved with new debugger core in work relating to #5013.
