### ISSUE TITLE
docs(windows): Update with Windows 11 resources

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#9391]
> You'll probably regret making these changes, because now I think we need to put some effort in to refresh for Win11 as well. If not in this PR, certainly before 17.0-stable.

_Originally posted by @mcdurdin in https://github.com/keymanapp/keyman/pull/9381#pullrequestreview-1558124050_

* make-taskbar-icon-visible.md
> Obviously we need updates for Win11 also!

* text_services_framework.md
> This whole document probably needs a rewrite...

**Comment by rc-swag** [comment]
> * text_services_framework.md
> 
> > This whole document probably needs a rewrite...

@mcdurdin  can you give me a few notes on how you want this re-written, does it need more or less info? I have added a few applications that I know use it.

**Comment by mcdurdin** [comment]
It's probably too technical for most users? Not really sure what I want to do with it at present. As more and more apps support it, the distinction becomes less meaningful. It's not terrible apart from one grammatical weirdness but I am just not sure if it is helpful to users. What do you think?

**Comment by rc-swag** [comment]
> I am just not sure if it is helpful to users.

Ok, now I see the main issue. I agree it is more just a statement. I guess it would answer a F.A.Q. Why does such an application not enter the input after I move focus?  However, it would not be a Frequently asked question but rather a rarely asked question.
I say drop it?

**Comment by mcdurdin** [comment]
Yep, I think we move the content to a technical note on help.keyman.com and out of the core keyman for windows docs.
