### ISSUE TITLE
bug(android): Keyboard error message appear on the screen after installing Keyman 17.0.150 build in Android Lollipop OS

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#9401]
### Describe the bug

I noticed that after installing Keyman 17.0.150 alpha build in Android Lollipop OS, it is showing keyboard error message on the screen. 

### Reproduce the bug

1. Install Keyman 17.0.150-alpha build.
2. Open Keyman-InApp. 

Here, I noticed that an error message flashes on the screen. Seems to be an issue. 

Note: This error message always appear on the scree whenever a new keyboard is installed. 

..Error in default keyboard after opening keyman In-App

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/be08d437-642e-4e3c-b157-286669df2e95">

..After installing a keyboard
   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/d16be535-fb8f-4d73-800f-daee35f19f00">

### Expected behavior

The default keyboard should appear without showing any error message. 

### Related issues

#7613

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.15-alpha

### Operating system

Android 5.1 Lollipop OS

### Device

API 22 Android Simulator

**Comment by jahorton** [comment]
Ah, and... Lollipop is Android 5.0, so this is probably the same thing as #9409.  I just made the connection after spinning up that issue.  Easy enough fix, though.
