### ISSUE TITLE
feat(developer): ldml scancodes 🙀 

### ISSUE THREAD

**Issue by srl295** [keymanapp/keyman#9403]
Background: see [CLDR-16604](https://unicode-org.atlassian.net/browse/CLDR-16604) and https://github.com/unicode-org/cldr/pull/2929 and https://github.com/unicode-org/cldr/pull/3276

- The proposal is for the CLDR repo to not allow embedded scanCodes in a keyboard file even though the spec will support it 
- kmc should do likewise
- also we should have unit tests that sanity check that the _stock_ CLDR scancodes match the keyman expectations. (won't change between cldr drops)

**Comment by mcdurdin** [comment]
warn or error? I think it's a bad idea for kmc to not accept valid ldml .xml files, isn't it?

**Comment by srl295** [comment]
> warn or error? I think it's a bad idea for kmc to not accept valid ldml .xml files, isn't it?

For kmc i think these should be errs (both the kmc and the unit test).  We wouldn't expect such a keyboard to work properly in keyman.

**Comment by mcdurdin** [comment]
It bothers me that we are building the spec in such a way that keyboards generated under it cease to be cross-platform (because if Keyman can't work it then other platforms will also be in the same boat). It seems like a backwards step to me and leads inevitably to -windows -mac -linux -... variants of keyboards, and then even worse, possibly to -windows-102, -windows-101 variants etc. Which benefits nobody.

**Comment by srl295** [comment]
> It bothers me that we are building the spec in such a way that keyboards generated under it cease to be cross-platform (because if Keyman can't work it then other platforms will also be in the same boat). It seems like a backwards step to me and leads inevitably to -windows -mac -linux -... variants of keyboards, and then even worse, possibly to -windows-102, -windows-101 variants etc. Which benefits nobody.

help me out here… how are they not cross-platform?

**Comment by srl295** [comment]
My reading is that Keyman, like CLDR's repo, would only support keyboards defined in terms of a few standard layouts.  If you had a [triple keyboard](https://www.youtube.com/watch?v=AEkzWP6lTBo) with 306 keys on it, you would need to wait until that layout was added to the standard list.  You could use the triple keyboard (or something else) but you would not be able to define keys not part of us/iso/abnt2/jis.

But yet, platforms are allowed to have customized layouts in their own implementations.

**Comment by mcdurdin** [comment]
OK, so what you are saying is, the spec allows for esoteric scan code layouts which we won't support in Keyman. I guess I can live with that.

**Comment by mcdurdin** [comment]
Although I wonder what the benefit is!

**Comment by srl295** [comment]
> OK, so what you are saying is, the spec allows for esoteric scan code layouts which we won't support in Keyman. I guess I can live with that.

That seemed to be the request, for OS specific purposes.

**Comment by mcdurdin** [comment]
> for OS specific purposes

And _that's_ what I was talking about. Why does it need to be in the spec for a single implementation's needs? It belongs as separated metadata.

**Comment by srl295** [comment]
the standard layout belongs in the spec. I could see having a way to override that as being reasonable for the spec. But maybe we can discuss after or in adhoc.  Maybe discuss this on the other PR?
