### ISSUE TITLE
bug(linux): Warning message appear in the terminal window while installing a keyboard

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#9411]
### Describe the bug

I noticed that a warning message appear in the terminal window during keyboard installation using Keyman Configuration dialog. 

### Reproduce the bug

1. Open Terminal window. 
2. Type km-config

I noticed that 'libEGL warning: DRI2: failed to authenticate' message appear in appear in Ubuntu 22.04 Linux OS.  And 'Running unit tests, not reporting to Sentry' message appear in Ubuntu 20.04 Focal and Wasta Linux OS. 

3. Download and install any keyboard. 

Here, I noticed that the warning message appeared again on the terminal window. 

I have attached the Screenshots for reference. 

..Ubuntu 22.04 Linux OS

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/34bd477d-6144-4230-b2b0-2aa2c0f20a2e">

..Ubuntu 20.04 Linux OS

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/9e65633b-adf6-4252-8e6a-c6fb44650a1f">

### Expected behavior

It would be better that no warning message should appear in the terminal window during the keyboard installation.

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [X] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.152-alpha 

### Operating system

Ubuntu 22.04, Ubuntu 20.04 Linux OS

**Comment by ermshiperete** [comment]
See also #8916

**Comment by ermshiperete** [comment]
There's no easy way to suppress the output. However, this happens only in some environments (could reproduce in a VM running Ubuntu 22.04), and is only visible if the user starts `km-config` from the terminal. Most users will start km-config through gnome-shell which doesn't show the console output.
