### ISSUE TITLE
bug(windows): 'no hotkey'  link is missing for a keyboard which has more than one language (eg., EuroLatin(SIL))

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#9412]
### Describe the bug

I noticed that after installing more than one language for a specific keyboard like EuroLatin(SIl), the 'no hotkey' link is missing in the active Keyboard blue bar. 

### Reproduce the bug

1. Install Keyman 17.0.152-alpha build. 
2. Open Keyman Configuration dialog.
3. Download and install 'EuroLatin(SIL)' keyboard. 

We may notice that 'no hotkey' link appear in the keyboard bar. 

4. Download and install 'French-EuroLatin(SIL)' keyboard. 

Here, I noticed that 'no hotkey' link is missing from the EuroLatin(SIL) keyboard bar. However, clicking on the Keyboard bar, shows the 'no hot key' link appear inside the pane. 

I have attached the Screenshots for reference. 

..no hotkey missing in the keyboard bar

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/fa58935a-e886-4153-9e59-32f2d5a8ec2b">

..no hotkeys are hidden and appear inside the keyboard pane

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/b10fc195-10b6-41bb-927c-a05efe8f2aa8">

### Expected behavior

'no hotkey' link should appear in the keyboard  bar. 

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [X] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.152-alpha

### Operating system

Windows 10 OS, Windows 11 OS (VM)

**Comment by mcdurdin** [comment]
This is by design -- if you install more than one language for a keyboard, each language can have a separate hotkey. I agree that it is somewhat subtle but given installing more than one language for the keyboard is advanced usage anyway, I think we can live with it.
