### ISSUE TITLE
feat: Consider long-press default key (i.e. when user long-presses but doesn't swipe) as dev-configurable 🐵

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#9416]
gestures/longpress

From a UI perspective, it would be nice to have a longpress that is automatically selected rather than having to move up off the base key to select a key. The default should be highlighted in the longpress menu when the menu appears. I think any macro movement after that would then return to traditional longpress behaviour.

The keyboard designer needs to be able to select the default longpress key, or to have no default. (The fallback behaviour for existing keyboards should probably be no default?)

Requires:

- [x] #9430
- [ ] Update to gestures module in KeymanWeb to handle this case.

@jahorton do you think it is possible to include this in gestures-17.0?

This comes out of a design discussion in 16.0, missed getting an issue assigned at the time.

Note from #8519:

* Default will be selectable by keyboard designer -- _not_ necessarily the first, and may be _none_.
* Where there is a default will be indicated by highlighting it in the longpress -- the normal selection highlight.
* Given that cancel is _not_ the preferred default action for a longpress, the user can cancel the longpress default by sliding outside the 'acceptance' area -- e.g. south of the key cap, which would then unhighlight the default and indicate visually that no output would occur when they release their finger.

**Comment by jahorton** [comment]
Yeah, sure.  I'd love to have that included.  I loved when that "unintended feature" was active.  (Where we auto-selected the first subkey)

**Comment by darcywong00** [comment]
I think #9496 addresses the KeymanWeb portion of this.

**Comment by jahorton** [comment]
#9496 + #9698 ensure that this will be handled, both before and after the gesture-engine rework.  I'm going ahead and closing it now.
