### ISSUE TITLE
[Windows] Excel 2016 deletes a whole cluster on backspace

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#944]
Excel 2016 (other versions not tested) deletes a whole cluster when backspace is pressed, rather than just the final character. This is out of sync with how all other Microsoft Office apps delete characters and breaks Keyman's context manipulation. Unfortunately not all clusters are treated in the same way.

See also https://community.software.sil.org/t/first-character-joined-by-ligature-tie-disappears-in-excel/930

**Comment by metrey** [comment]
Yes, here is the video to show how it happens: https://youtu.be/s5adzP6m3ks

**Comment by MakaraSok** [comment]
> Yes, here is the video to show how it happens: https://youtu.be/s5adzP6m3ks

The issue with Khmer Angkor keyboard here is that the autocorrect was trigger when mistyping is detected. The word shown in the clip may be typed as ប ណ ្ ត ុះ ប ណ ្ ត ា ល, and it is supposed to be auto-corrected as ប ណ ្ ដ ុះ ប ណ ្ ដ ា ល, but in the replacement process the known issue (as reported here) gets in the way and wreck havoc.

**Comment by mcdurdin** [comment]
I have touched base with Microsoft again on this issue. Awaiting response from them.

**Comment by mcdurdin** [comment]
Query: does AAUI help us? https://docs.microsoft.com/en-us/windows/desktop/WinAuto/event-constants

**Comment by mcdurdin** [comment]
https://community.software.sil.org/t/sanskrit-veda-devanagiri-keyboard/5061/6

**Comment by mcdurdin** [comment]
Good news: I have tested today with Excel `Version 2107 (Build 14228.20204 Click-to-Run)` (About dialog shows `Microsoft 365 MSO (16.0.14228.20200)`) and this backspacing behaviour is resolved in this version.

For confirmation, I tried again with Excel `2016 (16.0.5188.1000) MSO (16.0.5188.1000)` and can verify that it was definitely a problem in this version.

**Comment by MakaraSok** [comment]
Tried just now and it doesn't get fixed for me neither on the `Excel Version 2107 (Build 14228.20204 Click-to-Run)` nor the latest version  `Version 2107 (Build 14228.20226 Click-to-Run)`. 

The about dialog shows a different version from yours though, `Microsoft Excel 2016 MSO (16.0.14228.20216) 32-bit`.

**Comment by mcdurdin** [comment]
Yes, this appears to be fixed in Microsoft Excel 365 and (I presume) Excel 2019 -- but not fixed in Microsoft Excel 2016. Microsoft were unsure exactly when the fix went in. The Office versioning strategy is difficult to follow now, but if you are on a fully updated Office 365 or Excel 2019, you should have the fix. (The build numbers do not appear to be particularly relevant?)
