### ISSUE TITLE
bug(developer): enter key does not add a new line in the debugger

### ISSUE THREAD

**Issue by sewhite** [keymanapp/keyman#9444]
### Describe the bug

When testing a keyboard, the enter key  does not start a new line in the output.
The debugger says I pressed 000d, but the cursor is not on a new line.

![image](https://github.com/keymanapp/keyman/assets/16904461/0357328b-638f-472c-a574-6d7ccd8abd10)

### Reproduce the bug

1. Create keyboard layout that does not modify the Enter key
2. Compile and go to test (keyboard > test keyboard
3. Type some text
4. press Enter

### Expected behavior

The enter key would start  a new line in the output. 

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [X] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16.0.141

### Operating system

Windows 11 22H2

### Device

Windows laptop

**Comment by mcdurdin** [comment]
Thank you for this report; we will look at resolving it soon
