### ISSUE TITLE
bug(windows): 'Share Keyboard' and 'Help' buttons are missing If I install a keyboard via Keyman Developer 

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#9449]
### Describe the bug

I noticed that there is a change in number of buttons available in an installed keyboard after installing it from a Keyman Developer or directly installed it from the Keyman Configuration dialog. 

### Reproduce the bug

1. Install Keyman 17.0.158-alpha build 
2. Install Keyman Developer17.0.158-alpha
3. Open a Keyboard project (.kpj) using Keyman Developer. (eg., gff_amharic)
4. Click the Build tab. 
5. In the 'Windows, macOS and Linux Target' pane, Click the Install button. 

We may notice that Amharic keyboard is installed in the Keyman Configuration dialog. 

6. Open Keyboards Layouts tab in Keyman Configuration dialog. 

Here, I there are 3 buttons 1. Add/remove language 2. Disable and 3. Uninstall are available in this view. 

7. Click the Download Keyboard button in the Configuration dialog. 
8. Download and Install Amharic keyboard. 
9. Open Keyboard layout view. 

Here, I noticed that there are 2 more options 1. Share keyboard and 2. Help buttons are available in the layout view.  Also, some information are missing in the right side of the pane. 

..Amharic Keyboard installed via Keyman Developer 17.0.158

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/06f48fc7-ba30-4055-895a-de1471f70aa0">

..Amharic Keyboard installed via Keyman 17.0.158 

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/d0c4e932-3119-40dd-9fdd-44509588af74">

### Expected behavior

Installing a Keyman Keyboard via Keyman Developer should always shows the same number of buttons in the Keyboard Layout view. 

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [X] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.158-alpha

**Comment by mcdurdin** [comment]
This is by design. 

This pathway is intended for development and testing only: in the example you are giving, you are installing a .kmx file which is the raw keyboard file without any metadata, such as the documentation or the package, so there is no information for the help or the keyboard share.
