### ISSUE TITLE
[Windows] "Get Started" is incomplete

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#945]
Found during a dry run of user-testing Keyman Desktop 10.0.1101.0

The links to "Get Started" don't seem to be fully functional

From the Configuration panel -> Getting Started
![image](https://user-images.githubusercontent.com/7358010/40963334-67008ade-68d2-11e8-98d8-99d80a28e395.png)

From the Desktop --> Help... menu
![image](https://user-images.githubusercontent.com/7358010/40963391-967cf798-68d2-11e8-86e2-5c1282da0cbe.png)

 "Get Started" dismisses the panel

**Comment by mcdurdin** [comment]
The tutorial was removed for v10. So will remove the links.
