### ISSUE TITLE
bug(core): ldml backspace not quite right 🙀 

### ISSUE THREAD

**Issue by srl295** [keymanapp/keyman#9450]
- backspace transforms aren't working yet #7375 
per review: 
- https://github.com/keymanapp/keyman/pull/9405/files#r1289569219 ldml processor should work more like kmx processor

**Comment by srl295** [comment]
https://github.com/keymanapp/keyman/issues/9073 maybe relevant? @rc-swag  @mcdurdin

**Comment by mcdurdin** [comment]
#9073 shouldn't impact the ldml keyboard processor because those interactions should be happening at the Engine level, I think. At least at this stage.

**Comment by srl295** [comment]
see also #8827
