### ISSUE TITLE
bug(android): Keyman abruptly closes after choosing a keyboard from the keyboard picker menu

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#9456]
### Describe the bug

I noticed that after choosing any keyboard from the keyboard picker menu, keyman app abruptly closes. This happens after selecting keyman as the system wide keyboard. 

### Reproduce the bug

1. Install Keyman 17.0.158-alpha build.
2. Open Keyman In-App.
3. Set Keyman as the system-wide keyboard and default keyboard. 
4. Click 'Install Keyboard or Dictionary' option from the Settings menu. 
5. Click 'Install from keyman.com' option. 
6. Click the Search bar to enter a keyboard name. 

We may notice that the default keyman keyboard flashes on the page. 

7. Click once again on the Search bar. 
8. Long press the 'globe key' from the keyman keyboard. 
9. Click 'Gboard' or English EuroLatin(SIL) keyboard from the Keyboards picker menu. 

Here, I noticed that the keyman app suddenly closes from the screen. Seems to be an issue. 

I have attached the video file for reference. 

..Keyman App abruptly closes

https://github.com/keymanapp/keyman/assets/19683143/6b5d8fe8-9cab-4737-8efb-4ece367d8225

### Expected behavior

After clicking any keyboard it should open the corresponding keyboard on the screen. 

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.158-alpha

### Operating system

Android 5.0, 9.0, 12.0

### Device

Redmi Note 8 Pro, API 31 emulator

**Comment by darcywong00** [comment]
I can repro on the latest 16.0 stable

Some additional notes:
1. The transition from the keyboard search page to keyboard picker menu is where the keyboard search page "closes". If I back out of the keyboard picker menu, the Keyman app is still in the task bar
2. Using the keyboard picker (if available on the nav bar) doesn't close the keyboard search page

**Comment by darcywong00** [comment]
Will need to defer this a few sprints

**Comment by darcywong00** [comment]
Fixed by #10806
