### ISSUE TITLE
[Developer] Can't Fill from Layout if using a matching Keyman Desktop hotkey.

### ISSUE THREAD

**Issue by MattGyverLee** [keymanapp/keyman#946]
Keyman Dev (10.0.1101 and before) cannot fill the OSK from layout if certain "Keyman reserved" combinations are used in the keyboard and configured as hotkeys in Keyman Desktop: [SHIFT RALT K_M], [SHIFT RALT K_O], etc.

![image](https://user-images.githubusercontent.com/986339/40966548-b3fbb3ec-68a8-11e8-9a05-8f2a68de14f4.png)

The importer semi-helpfully gets stuck on the problem command (see above), but may be left in a broken state with some modifier keys pressed. Of course, removing the Keyman Desktop Hotkey (or the Layout code) avoids the  problem.

**Comment by mcdurdin** [comment]
This will be resolved with the refactor of Keyman Engine for Windows key processing in Keyman 11.

**Comment by mcdurdin** [comment]
This has been sufficiently resolved with #2360 -- it doesn't deal with the case of virtual keys with left or ambiguous chirality but these are not generally encouraged now -- RAlt and RAlt+Shift being the only encouraged options.
