### ISSUE TITLE
bug: (developer)

### ISSUE THREAD

**Issue by sewhite** [keymanapp/keyman#9460]
### Describe the bug

The virtual key sequence [NCAPS SHIFT K_PERIOD] does not work as expected. 

If  I want to put a letter on the period key, I am not able to get the lower case letter when CAPS Lock is on and Shift is pressed.
Sample code:

```
+ [NCAPS K_PERIOD] > U+0077
+ [NCAPS SHIFT K_PERIOD] > U+0057
+ [CAPS K_PERIOD] > U+0057
+ [NCAPS SHIFT K_PERIOD] > U+0077   <-- doesn't work, I get >
+ [NCAPS K_COLON] > U+0077
+ [CAPS K_COLON]  > U+0057
+ [NCAPS SHIFT K_COLON] > U+0057
+ [CAPS SHIFT K_COLON] > U+0077    <-- does work, I get lower case w
```

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16.0.141

### Operating system

Windows 11 22H2

### Device

Windows laptop

### Target application

testing keyboard in Developer

**Comment by sewhite** [comment]
oops. I see what I did wrong. You can close this.

**Comment by mcdurdin** [comment]
For reference for future readers, this rule was duplicated:

```
+ [NCAPS SHIFT K_PERIOD] > U+0057
...
+ [NCAPS SHIFT K_PERIOD] > U+0077   <-- doesn't work, I get >
```
