### ISSUE TITLE
feat(core): warn on unassigned codepoints when loading keyboard 🙀 

### ISSUE THREAD

**Issue by srl295** [keymanapp/keyman#9464]
- on web, use /u regex
- otherwise, use ICU codepoint age

Will show warning that codepoints aren't handled by your platform.

**Comment by mcdurdin** [comment]
Core should silently accept any legal (even if unassigned) codepoint. Because there is no UI that can be shown to the user, and because there is no real pathway for resolution for the user either. It could be a log message for diagnostics.
