### ISSUE TITLE
bug(windows): Some text appear behind the Configuration button in the 'About' dialog after changing the UI into Kannada

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#9481]
### Describe the bug

I noticed that after changing the UI into Kannada, some kannada text appear behind the Configuration button in the About dialog. 

### Reproduce the bug

1. Install Keyman 17.0.161-alpha build. 
2. Open Keyman Configuration dialog. 
3. Change the UI into Kannada. 
4. Open the About dialog. 

Here, I noticed that the some kannada text appear behind the Configuration button. 

Note: I am seeing the same issue when I use 'Waha' UI language. 

I have attached the Screenshots for reference. 

..using Kannada UI

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/0830b7ae-2aae-4162-a1f2-2b6f37e0a59e">

..using Waha UI

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/36f9e80a-7965-4522-9af9-d9c26488e138">

### Expected behavior

No extra text appear behind the Configuration button in the About dialog. 

### Related issues

#9436

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [X] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.161-alpha

### Operating system

Windows 10 OS, Windows 11 OS (VM)

**Comment by rc-swag** [comment]
I can fix this but I noticed Keyman and been translated for Kanda.
@darcywong00  Do we translate trademark names like "Keyman". 
Another question do we have the ability in crowdin to limit the number of characters they have for a given translation field? For example the "Exit" button string

**Comment by mcdurdin** [comment]
> @darcywong00 Do we translate trademark names like "Keyman"

No, that should stay as 'Keyman', 'Windows' as 'Windows' etc.
