### ISSUE TITLE
feat(web): custom spacebar labeling

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#949]
Hello,

Please watch this video.
https://drive.google.com/open?id=1YEyUBMEH49zLUXACn-cTUDEnAIm8WWo7

In iOS, stock and custom keyboards, display the keyboard name or language (decided by developer) followed by name of the key "space" or equivalent "space" in that language which is again decided by developer.

But Keyman is space bar title is hardcoded to "language(script)-region and name of the keyboard" 

1. Please add feature to label space bar by developer in the native language.
2. When the keyboard be switched to keyman, it should display a custom test (name of keyboard/language) which is decided by the developer based on the space constraint. Followed by title of the space bar in the native language.

**Comment by mcdurdin** [comment]
Some mitigations:

1. If the language name and keyboard name are identical, then we currently don't duplicate them (this may be sufficient for some keyboards) 
2. Update the language name in the package file keyboard section to exclude the script.

Changes we'll implement:

1. KeymanWeb: Add an API option to set display name for a given keyboard which overrides the default pattern. This can be used by Keyman Engine for Web consumers or apps that use Keyman Engine for Android or Keyman Engine for iOS:

```js
keyboardStub.displayName = 'foo';
```

2. KeymanWeb: We'll add an API to control the default display pattern: 
    * "languageKeyboard"
    * just "keyboard"
    * just "language"
    * "blank"

```js
keyman.options.spacebarText = 'keyboard';
keyman.osk.show(true); // refresh the spacebar
```

3. Keyman Engine for Android: Add an API to control default space bar pattern

4. Keyman Engine for iOS: Add an API to control default space bar pattern

5. Keyman for Android and Keyman for iPhone and iPad: add an option to select the space bar text mode, and default to just "keyboard":
    * "language - keyboard" (We'll set the pattern to "language - keyboard" rather than "language (keyboard)" - this reduces the number of parentheses so this will be easier to read.)
    * just "keyboard"
    * just "language"
    * nothing

6. We'll add a recommendation to avoid adding the script in parentheses in the package language details.

7. Keyman Developer: will not insert the script when generating package language details.

**Comment by MayuraVerma** [comment]
iOS, android do not have the feature to display custom label for spacebar.
Is it in works or not in scope?

**Comment by mcdurdin** [comment]
See https://help.keyman.com/products/android/15.0/basic/config/#toc-spacebar-caption for what is supported in 15.0.

**Comment by mcdurdin** [comment]
This is now complete for 15.0.
