### ISSUE TITLE
bug(android): Special character '<' rendering problem with IPA (SIL) keyboard 

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#9499]
### Describe the bug

I noticed that the special character "<" is missing in the long press option while using IPA (SIL) keyboard. 

### Reproduce the bug

1. Install Keyman 17.0.162-alpha build. 
2. Open Keyman In-App.
3. Download and Install IPA (SIL) Keyboard. 
4. Switch to IPA (SIL) keyboard in the Keyman App. 
5. Click the Number (123) key. 
6. Long Press "]" key. 
7. From the Longpress options, Select "<" special character. 

Here, I noticed that the "<" symbol does not appear on the screen. Other two special characters (>>, }) appear correctly. Seems to be an issue. 

I have attached the Screenshot as well as the Video file for reference. 

.. special character is missing

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/9bddbb60-267b-44b8-87ae-d1b931c81794">

https://github.com/keymanapp/keyman/assets/19683143/a0e17149-2848-4f5c-99f8-de748791bac9

### Expected behavior

Clicking the "<" special character on the longpress option should be correctly and rendered and appear on the text screen. 

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.162-alpha

### Operating system

Android 5.0, 9.0, 12.0

### Device

Android 12.0 /  API 31 emulator, Redmi Note 8 Pro

### Keyboard name

IPA (SIL)

### Keyboard version

1.8.6

### Language name

und-Latn

**Comment by jahorton** [comment]
I just tried this out in a few other configurations - the bug seems to be Android-specific.

Both `stable` and `alpha` of Keyman for iOS output the `<` just fine, as does the current alpha build of KMW when tested with remote device emulation in Chrome.

**Comment by darcywong00** [comment]
The keyboard source numeric layer has
```json
{
  "text": "<",
  "id": "K_COMMA",
  "layer": "shift"
},
```

In the Android emulator from the numeric layer, I halted after selecting the subkey and saw
```
keyId -> "numeric-K_COMMA+shift"
```
@jahorton - is that correct? Or should the keyID be `numeric-K_COMMA+numeric-shift`?

**Comment by jahorton** [comment]
Ah, it's one of _those_.  I didn't realize that - it's probably related to being a subkey using a specific layer modifier.  I'd have to double-check to see exactly what it should be, but that's a very notable lead.

**Comment by jahorton** [comment]
After the double-check, it seems that the ID is correct:  `numeric-K_COMMA+shift`.
