### ISSUE TITLE
[mac] feature request: package keyboard with keyman

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#951]
Hello,

Is there a way to package kmp file be packaged with keyman in mac?

If not, could you please add this feature.

**Comment by mcdurdin** [comment]
Agreed. Bundling is a useful feature for all platforms. Probably will never happen for iOS but for all other platforms we are still looking at doing this.

**Comment by SabineSIL** [comment]
see  #5318

**Comment by mcdurdin** [comment]
Closing as dup of #5318
