### ISSUE TITLE
bug(developer): Validation error encountered during the compilation of a package file

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#9512]
### Describe the bug

I observed an error message that appeared following the compilation of a keyboard package.

### Reproduce the bug

1. Install Keyman Developer 17.0.167-alpha build.
2. Open any existing Keyboard project. (eg., Khmer_Angkor) via Keyman Developer.
3. Click the 'Packaging' tab. 
4. Open the Keyboard package. 
5. Press the F7 key to  compile a keyboard.

Here, I notice that there is an 'Validation error' message appears in the message window. Seems to be an issue. 

I have attached the Screenshot for reference. 

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/23c1b694-eccc-4177-9165-9bd25aba4254">

### Expected behavior

After pressing the F7 key, compilation should be successful and the green message should appear in the message window. 

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [X] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.167-alpha

### Operating system

Windows 10 OS, Windows 11 OS (VM)

**Comment by mcdurdin** [comment]
@bharanidharanj  I think this may have been resolved by 17.0.183-alpha?

**Comment by bharanidharanj** [comment]
@mcdurdin  Retested with the latest Keyman developer 17.0.184-alpha build in Windows 11 OS (VM) and here is my observation: 1. I am able to reproduce this issue with some existing projects (eg.,khmer_angkor) with the above-mentioned steps. 

  
   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/15099701-aa09-476f-8acd-cb0df720aeb5">



Note: I tried with some other existing projects like malar_malayalam, sil_euro_latin and gff_amharic  and I did not see the above error message. Strange.

**Comment by bharanidharanj** [comment]
@mcdurdin Retested the same issue in Windows 10 OS (Native Machine) and I was not able to reproduce it. Seems to be working fine on Windows Native machine.  

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/ee6c7818-cde5-454a-afdb-cc5ee3772e88">

Note: This issue is only reproducible on the Windows 11 OS (Virtual Machine). There might be some other factors cause this error message. However, I will keep an eye on this issue. 

Otherwise, it is working fine with the native machine. As per Marc's suggestion, I am closing the issue. Thanks.

**Comment by mcdurdin** [comment]
Perhaps try it with a brand new project as well? Or adding some extra data into the Keyboards tab
