### ISSUE TITLE
bug(android): Changing the keyboard height in landscape view has an impact on the keyboard's height when in portrait view

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#9521]
### Describe the bug

I observed that resetting the keyboard height in landscape view results in changes to the keyboard height in portrait mode.

### Reproduce the bug

1. Install Keyman 17.0.167-alpha build.
2. Open Keyman In-App.
3. Adjust the Keyboard height to the maximum in Portrait view.
4. Change the orientation to a landscape view. 
5. Adjust the Keyboard height to the maximum. (in landscape)

We may notice that now the Keyboard appears with maximum height in both the Landscape and Portrait view. 

6. In Landscape view, Reset the Keyboard height to default. 
7. Change the orientation to Portrait view. 

Here, I noticed that the Keyboard height also changed to default. Seems to be an issue. 

I have attached the Video file for reference. 

https://github.com/keymanapp/keyman/assets/19683143/666cd10e-b540-4853-b711-ddfb7110618e

### Expected behavior

Resetting to the default height in landscape mode should have no impact on the keyboard height in portrait mode.

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.167-alpha

### Operating system

Android 5.0, 9.0, 12.0

### Device

Android 12.0 /  API 31 emulator, Redmi Note 8 Pro

**Comment by darcywong00** [comment]
As current implemented, the <kbd>RESET TO DEFAULTS</kbd> button does clear the preference for both portrait and landscape orientation, 

https://github.com/keymanapp/keyman/blob/d7a3e8a2304492b3514b838f31759318e4d6ae6e/android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/AdjustKeyboardHeightActivity.java#L76-L87

as also noted in the [Adjust Keyboard Height](https://help.keyman.com/products/android/16.0/basic/config/adjust-keyboard-height) documentation.
> Press the button to reset the OSK height to the default values.

**Comment by darcywong00** [comment]
The "Reset to Defaults" button is clearing both portrait and landscape heights as intended.
