### ISSUE TITLE
[Mac] Fatal Exception: NSInvalidArgumentException in initWithString

### ISSUE THREAD

**Issue by tombogle** [keymanapp/keyman#954]
Looking at the call stack (below), this occured when the user clicked the remove button to delete a keyboard in the Configuration window. Looking at the code, it appears the only way this could happen is if the KMP file to remove went missing before Keyman could delete it. I was able to reproduce the crash on a test machine by manually deleting it while Keyman was waiting for me to confirm the deletion. Seems like a possible scenario for a real user, but not too likely.

Call stack (from Fabric/Crashlytics):

Fatal Exception: NSInvalidArgumentException*** -[NSPlaceholderString initWithString:]: nil argument Raw Text
--
0 | CoreFoundation | (Missing)
1 | libobjc.A.dylib | (Missing)
2 | CoreFoundation | (Missing)
3 | Foundation | (Missing)
4 | Foundation | (Missing)
5 | Keyman | KMInputMethodAppDelegate.m line 440-[KMInputMethodAppDelegate packageFolderFromPath:]
6 | Keyman | KMConfigurationWindowController.m line 125-[KMConfigurationWindowController packageFolderFromPath:]
7 | Keyman | KMConfigurationWindowController.m line 531-[KMConfigurationWindowController deleteFileAtIndex:]
8 | Keyman | KMConfigurationWindowController.m line 505-[KMConfigurationWindowController alertDidEnd:returnCode:contextInfo:]

Machine details:
MacBook Pro Retina, 15", Late 2016 DEVICE; OS Version: 10.12.6 (16G1314)

**Comment by tombogle** [comment]
The code could pretty easily be made more airtight to avoid a crash and just do nothing. But, depending on the real scenario, we couldn't guarantee that just doing nothing would be the right answer. Discussed this with Marc and agreed to wait on it unless/until we get additional reports.

**Comment by SabineSIL** [comment]
We decided to close this since it is a minor issue
