### ISSUE TITLE
feat: Add Backspace Rules for Variation Sequences

### ISSUE THREAD

**Issue by dyacob** [keymanapp/keyman#9558]
### Is your feature request related to a problem? Please describe.

When the cursor is to the right of a variation selector (VS), and a Backspace key is hit, the VS is deleted but not the base character it modifies.  Thus two backspace keystrokes are needed, this is likely confusing for users who are not familiar with how character encoding works.

### Describe the solution you'd like

When the Backspace is hit and deletes a VS, the base character should be deleted along with it.  Thus the full character disappears onscreen.

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [X] Keyman for macOS
- [X] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

 16.0.141

### Operating system

Windows 11, macOS 13.5.2

### Device

Window Laptop, MacBook

### Target application

Microsoft Word

### Keyboard name

gff_geez_emufi

### Keyboard version

1.0

### Language name

Ge'ez

### Additional context

Variation selectors are in the address range:  FE00 - FE0F ,  E0100 - E01EF .

An example with the new GFF Ge'ez Manuscript Keyboard (gff_geez_emufi) is to type:  `::`  with the Ge'ez Manuscript Zemen font selected, and a rubricated Ethiopic full stop will appear.   Hit Backspace / Delete and you will notice the symbol change to the base symbol (።) .  In this example, the invisible symbol U+FE00 has been deleted only.

**Comment by mcdurdin** [comment]
For now, the best way to solve this is to add rules in your keyboard to delete the variation selectors alongside the characters. We try not to add 'magic' to the Keyman Engine itself and leave the decisions on what should be deleted to the keyboard developer. For example:

```
any(something) U+FE00 + [K_BKSP] > nul
```

Or to arbitrarily delete any 1 variation selector together something:

```
store(variation-selector) U+FE00..U+FE0F U+E0100..U+E01EF
any(something) any(variation-selector) + [K_BKSP] > nul
```

**Comment by dyacob** [comment]
Thanks for this @mcdurdin , I incorporated backspace rules in the latest update to the gff_geez_emufi keyboard following your example.
