### ISSUE TITLE
[Windows] Text Editor optional

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#956]
Hello,

Please make text editor in Keyman version of windows be optional or perhaps completely remove it.

Background:
This causes confusion in users. Most Indic languages used ASCII based keyboard, font and editor.
Having a text editor with a keyboard application will encourage users to revert back to same habit of creating documents in the text editors provided with the keyboard. And would complain the text editor included is not as powerful as the other keyboard packages.

There is no need for a text editor in the windows application.

Please remove it or at least enable developers to turn it off in the package.

**Comment by mcdurdin** [comment]
The text editor is still widely used, and is particularly useful for resolving system-specific issues. While it is less important than it used to be, I'm not prepared to remove it at this time.

If you do your own fork of Keyman, then you can certainly turn it off. The feature cannot be removed by installing a package into Keyman Dekstop.
