### ISSUE TITLE
bug(linux): Upon clicking the Vedic link button in Focal Linux, an error is shown in the terminal

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#9567]
### Describe the bug

I observed that when I clicked the Vedic link button, an error message appeared in the terminal window.

### Reproduce the bug

1. Install Keyman 17.0.173-alpha build in Ubuntu 20.04 Focal Linux OS.
2. Open the terminal window.
3. Type 'km-config', then press Enter key.
4. In the Keyman Configuration dialog, Click the 'Download Keyboard' button. 
5. Enter 'Vedic Sanskrit..' in the Keyboard Search bar. 
6. Click the Install Keyboard button.
7. Click the "https"//sankritdocuments.org/..." website link button. 

Here, I noticed that there is an error message displayed on the terminal window. However, the help page is open as expected. 

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/1243124d-77be-486b-8c55-044d40904bc7">

### Expected behavior

 By clicking the Vedic link button should open the help page without showing any error message.

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [X] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.173-alpha

### Operating system

Ubuntu 20.04 Focal Linux OS

**Comment by bharanidharanj** [comment]
Reproducible in Ubuntu 22.04 Jammy and Lunar 23.04 Linux OS. 

..in Ubuntu 22.04 Jammy Linux OS

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/55573075-4f4b-4726-aa70-0c1410b1a8ab">

..in Ubuntu 23.04 Lunar Linux OS

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/3fbaa681-de60-41f5-ad84-04d19df53e57">

**Comment by ermshiperete** [comment]
I suspect this output is from Firefox. To verify:

@bharanidharanj Please start Firefox from the terminal (by executing `firefox`), then navigate to https://sanskritdocuments.org/learning_tools/sanskritvedic.html and paste the output from the terminal. Thanks!

**Comment by bharanidharanj** [comment]
@ermshiperete As per your suggestion, I opened Firefox (with the above-mentioned) link from the terminal. I am getting some error messages in the terminal window. I have attached the screenshot for your reference. Thanks. 

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/aabf90b9-b73c-4faa-b186-de6b93bbcbde">

**Comment by ermshiperete** [comment]
The output we're seeing is from Firefox, so there is not much we can do here (we could suppress the messages, but that might hide real problems).
