### ISSUE TITLE
docs: Clarify example for `builder_describe_internal_dependency` in `build-utils.md`

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/keyman#9581]
It seems to me that the example for [builder_describe_internal_dependency](https://github.com/keymanapp/keyman/blob/master/resources/build/build-utils.md#example) in `build-utils.md` and `builder.inc.sh` is wrong.

Shouldn't this be the following?

```bash
builder_describe_internal_dependency \
  build:mac build:mac-x86_64 \
  build:mac build:mac-arm64
```

**Comment by ermshiperete** [comment]
[`core/build.sh`](https://github.com/keymanapp/keyman/blob/ae490135fc3df96d93c5f25e29a0c69b40838707/core/build.sh#L98) shows that the documentation is in deed wrong.

**Comment by mcdurdin** [comment]
🤦🏼 my bad
