### ISSUE TITLE
KMEA 16.0.141 is missing a class.

### ISSUE THREAD

**Issue by MattGyverLee** [keymanapp/keyman#9587]
When building a release version of my app with KMEA 16.0.141, it ran R8 and needed a new class, which i can't find. Was that intentional?

![image](https://github.com/keymanapp/keyman/assets/986339/e98182dc-476a-420f-a4b0-1ae4269a07aa)

https://github.com/keymanapp/keyman/blob/31fd6ea42afef1dddd7d883fc31c5086fe9ae9b2/android/KMEA/app/build.gradle#L71C22-L71C60

**Comment by darcywong00** [comment]
That should be an optional dependency used in the Keyman for Android app to generate a QR code for downloading a keyboard. 
We build FirstVoices for Android with the same engine and it doesn't include the QR code dependency.
https://github.com/keymanapp/keyman/blob/31fd6ea42afef1dddd7d883fc31c5086fe9ae9b2/oem/firstvoices/android/app/build.gradle#L119-L126

Are you updating from Keyman Engine for Android 15.0 to 16.0?

**Comment by MattGyverLee** [comment]
No, from 16.0.139 (my last release) to 16.0.141. I only get the error when I try to build a release package. I've never seen R8 errors before, but they seem to be deeper checks related to minify.

**Comment by MattGyverLee** [comment]
I'm originally based on KMSample2, but I try to upgrade Gradle, dependencies, and my target SDK at each release.

**Comment by darcywong00** [comment]
I haven't really dealt with R8.

from SO
https://stackoverflow.com/questions/70037537/proguard-missing-classes-detected-while-running-r8-after-adding-package-names-in

maybe you can try adding `-dontwarn net.glxn.qrgen.android.QRCode` to proguard-rules.pro

Our FirstVoices project doesn't have anything in proguard-rules.pro though.  :man_shrugging:

**Comment by MattGyverLee** [comment]
Ah, it's a Gradle 8 thing.

**Comment by MattGyverLee** [comment]
No luck...
![image](https://github.com/keymanapp/keyman/assets/986339/49272ebb-05c7-49e9-ac66-8457acda022a)

**Comment by MattGyverLee** [comment]
I guess we were too specific. ```-dontwarn net.glxn.qrgen.android.**``` doesn't show a debug error.  Trying to build now.

**Comment by MattGyverLee** [comment]
That got me past the error. Thanks. I guess Gradle 8 adds some complication for optional dependencies.

**Comment by darcywong00** [comment]
Yeah, Gradle 8 will be an adventure for when we start Keyman 18 next year...

**Comment by MattGyverLee** [comment]
It would be helpful to know what versions of Gradle KMEA is tested with. Should I have stuck with the versions from FirstVoices\KmSample2?

**Comment by darcywong00** [comment]
> It would be helpful to know what versions of Gradle KMEA is tested with. Should I have stuck with the versions from FirstVoices\KmSample2?

I think we're still using Gradle plugin 7.4
https://developer.android.com/build/releases/gradle-plugin
