### ISSUE TITLE
bug: KM Dev shouldn't both sum duplicate words AND fail to compile.

### ISSUE THREAD

**Issue by MattGyverLee** [keymanapp/keyman#9589]
### Describe the bug

I see from https://github.com/keymanapp/keyman/pull/3338 that the compiler handily offers to sum the values of the duplicate words and this shows in the compile debug.
![image](https://github.com/keymanapp/keyman/assets/986339/9cae7ccd-be7d-4616-bb0a-fc3ad627a493)

If this magic is happening underneath, why are duplicate words a fatal error that stops the compile? The compiler presumably dutifully adds the numbers and then exits the compile because a duplicate was found.

If I delete the duplicate word, the compile completes.

### Reproduce the bug

1. Leave a duplicate word in the  wordlist. 
2. Compile.
3. Rejoice that KM fixed your error and summed the matching words. 
4. Be confused that the compile still failed when this was the only error and it was handled gracefully.

### Expected behavior

Expectation:
Either sum or fail on a duplicate word. Don't do both. 
KM Developer 16.0.141

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [X] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16.0.141

### Operating system

Win 11 22H2

### Device

Lenovo Yoga C930

### Language name

Mengisa

**Comment by MattGyverLee** [comment]
The first time I compiled and got this error, I was still able to test the model in the browser. So it may have actually worked, but should be reporting "completed with warnings" instead of failed.

**Comment by darcywong00** [comment]
Can you check the Keyman Developer project settings to see if the checkbox for "Treat warnings as errors" is set?
We generally prefer that to be set on submissions to the lexical-model / keyboard repos.

**Comment by MattGyverLee** [comment]
I've never seen that checkbox before, but indeed it was checked. Unchecking it temporarily allowed the model to compile. 
The behavior now makes sense from a program perspective (and you can probably close this issue), but it raises two questions in my mind:
1. Could the debugger let me know?
   "You have chosen 'treat warnings as errors' for this project. Due to one or more warnings (or errors), compile has failed." 
3. Is it "really" still a warning if it's been handled or is it more of a notification?

**Comment by mcdurdin** [comment]
It should really be a hint rather than a warning. Hints don't block the build, and it's information that may be helpful (particularly when dealing with normalizing the content).

Warnings should be reserved for things that may cause trouble. The reason this was a warning was the early builds of the compiler didn't merge duplicates, it just got excited about them.

**Comment by mcdurdin** [comment]
Closing this, tracking the warning change in #9597.

**Comment by mcdurdin** [comment]
> 1. Could the debugger let me know?
>    "You have chosen 'treat warnings as errors' for this project. Due to one or more warnings (or errors), compile has failed."

Not a bad idea, the compiler could be more friendly here. An INFO message about warnings failing the build would help. Do you want to open a feature request?

**Comment by MattGyverLee** [comment]
> > 1. Could the debugger let me know?
> >    "You have chosen 'treat warnings as errors' for this project. Due to one or more warnings (or errors), compile has failed."
> 
> Not a bad idea, the compiler could be more friendly here. An INFO message about warnings failing the build would help. Do you want to open a feature request?

Because of #9597, duplicate words won't fail in the future. That answers my question. I don't know what other cases would create a warning. I also don't know how much of KMDev code is going to be kept in the new compiler, so you can decide whether it's worth pursuing.
