### ISSUE TITLE
[Developer] Issues with "hbo" language tag

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#959]
Testing Configuration:
Keyman Desktop 10.0.1101.0
Keyman Developer 10.0.1103.0

I'm seeing several issues associating a keyboard with the language tag `hbo` for Ancient Hebrew.

From Developer Package editor, I can assign the BCP 47 tag `hbo` for "Ancient Hebrew".

When I try to install that .kmp package in Desktop though, Configuration shows it falling back to a default "EN".

If I then try to Add/edit the language, the **Add Language to Keyboard** dialog does the following:
* searching for `hbo` yields no results
* searching for `ancient` yields no results
* searching for `hebr` yields "Hebrew" and "Yiddish"
* searching for `hbo-hebr` finally yields "Ancient Hebrew (Hebrew)

**Comment by mcdurdin** [comment]
Interesting. Looking at alltags.txt, this shows `hbo-Hebr = hbo-Hebr-IL`. It doesn't show a standalone `hbo` tag. The alltags.txt data is not well documented (https://github.com/silnrsi/sldr/blob/master/doc/alltags.md is what we have) so it seems I'm missing something in the model. We may be able to improve this by treating the absence of `hbo` as meaning that `hbo-Hebr` should be the default.

**Comment by mcdurdin** [comment]
Note also that the language search only currently searches names for languages known to Windows. For all others, you have to use a language code. That's why you need to do `hbo-Hebr`.

I am a little puzzled as to why we have to do search for hbo-hebr in the Add Languages dialog but that the script isn't added automatically by Keyman Developer. That seems incorrect.

**Comment by mcdurdin** [comment]
Okay, figured out my puzzlement. If there is no `suppress-script` property for a given language tag (e.g. `hbo`) then Keyman Configuration will require a script in the Add Language dialog. However, that doesn't tell us what the script should be. Suggestions:

1. Keyman Developer could probably be a little more stringent on the script subtag when no `suppress-script` property is present for a given language tag.
2. Keyman Developer should assume that, given a record `hbo-Hebr = hbo-Hebr-IL`, or `juc-Jurc` in alltags.txt, that the default script is as given. The developer can always override the default but it avoids the confusion.
