### ISSUE TITLE
bug(linux): Font License, Font documentation links are not working in Ubuntu 22.04 and Lunar 23.04 Linux OS

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#9600]
Here, what I did is:
1. Installed Syriac/Aramaic keyboard using Keyman Configuration dialog. 
2. Clicked 'Syriac/Aramaic' Keyboard from the Keyboard Layouts view. 
3. Clicked 'Help' button. 
4. In the syriac_aramaic keyboard package help page, Click the Aramaic (Hebrew Layout) blue link button. 
5. Click the 'Font license' blue link button. 
I noticed that it is opening an 'Access denied' page. 
6. Click the 'Font documentation' blue link button. 
It is showing the same 'Access denied' page. 

I have attached the Screenshot for reference. 

   <img width="300" src="https://github.com/keymanapp/help.keyman.com/assets/19683143/b0fc1df0-5eaf-409e-b33a-9cb9906f3962">

Note: In Ubuntu 20.04, Wasta 20.04 Linux, it is working fine. ie., the help page opens without showing any error message.

**Comment by ermshiperete** [comment]
I think the right thing to do is to only open external links with the browser. Internal links to html pages we can open in the webview browser which we use to display the help, and links to other file types we can open with the system's default app.
