### ISSUE TITLE
[Mac] Keyman crash with click on OSK, shift button

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#962]
Hello,
Keyman is crashing when we click on shift button in OSK.
Keyman version 47.
Please review.

**Comment by tombogle** [comment]
Easy to reproduce

**Comment by tombogle** [comment]
Just got the crash report from Crashlytics from my reproducing the issue. Turns out it looks like it's a specific repeatable instance of #894

**Comment by tombogle** [comment]
Actually, it looks like maybe it's something I broke trying to fix #894...

**Comment by tombogle** [comment]
A version build based on the code as it was on June 2 consistently works. It I switch to a version of the code from June 4, it also works. But if I then switch to the current version and build it, it fails consistently. And then if I switch back to the June 4 codebase and re-build, it also fails. The main significant change between June 2 and 4th was to change from using Carthage to Cocoapods to get Fabric/Crashlytics. The very next change after my temporary June 4 branch, which was done later on June 4, was to attempt to fix #894 using thread synchronization. So some combination of that change and the Crashlytics stuff is at the heart of this bug. I'm pretty sure that the determining factor as to whether my June 4 branch works or fails has to do with the presence or absence of some build artifacts, most likely Crashlytics/Fabric stuff.

**Comment by tombogle** [comment]
Using the current (beta) codebase, I commented out the 3 places where I added @synchronized directives in KeyView.m, and now this crash goes away. So this "fix" obviously isn't correct. It's possible (even likely) that it makes what would otherwise be a timing-related crash into a reliably reproducible crash.
