### ISSUE TITLE
bug(android): Keyboard Transition occurs after clicking any keyboard from keyboard picker menu

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#9622]
### Describe the bug

I observed that the keyboard transition takes place following the selection of any keyboard from the keyboard picker menu.

### Reproduce the bug

1. Install Keyman 17.0.179-alpha build. 
2. Open Keyman In-App.
3. Long press the globe key. 
4. Click 'English - EuroLatin (SIL)' keyboard. 

Here, I noticed that the keyboard transition occurs immediately within the keyman keyboard. 

I have attached the video file for reference. 

https://github.com/keymanapp/keyman/assets/19683143/054b9f9f-50d3-40af-a8be-63d6bdc0fab0

### Expected behavior

Clicking on a keyboard from the keyboard picker menu should not affect the keyman keyboard.

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.179-alpha

### Operating system

Android 5.0, 9.0, 12.0

### Device

Redmi Note 8 Pro, API 31 emulator

### Keyboard name

EuroLatin (SIL) Keyboard

### Keyboard version

1.2

### Language name

English

**Comment by darcywong00** [comment]
This is a lot like #8534 . 
@jahorton and I will spelunk on the Android keyboard transitions in A17S26

**Comment by jahorton** [comment]
To be a bit more explicit, based on what I see in the video, the OSK temporarily goes to a desktop form-factor default when only `sil_euro_latin` is installed and it's reselected from the language picker.
