### ISSUE TITLE
bug(ios): The application crashes when you tap the "Enable Keyman as the system-wide keyboard" option in the Get Started dialog on iOS 17.0

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#9632]
### Describe the bug

After clicking "Set Keyman as the default keyboard" option, the Keyman application unexpectedly shuts down.

### Reproduce the bug

1. Install Keyman 17.0.181-alpha build on the iPhone 15 Pro Max (iOS 17.0) simulator. 
2. Open Keyman In-App. 
3. Click the 'Set up Keyman as system-wide keyboard' option from the Get Started menu. 

Here, I noticed that the application abruptly closed. I tried the same steps a few more times and I was getting an error message after the application crashed. 

I have attached the Screenshots as well as the error text file (KeymanError_ios17.txt)  for reference. 

..Error message after the crash

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/ad1e6359-e490-42f6-9d22-709d750a54b4">

[KeymanError_ios17.txt](https://github.com/keymanapp/keyman/files/12738471/KeymanError_ios17.txt)

### Expected behavior

After clicking the 'Set up Keyman as system-wide keyboard' option it should open the Keyboard settings menu. 

### Keyman apps

- [ ] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.181-alpha

### Operating system

ios 17.0

### Device

iPhone 15 Pro Max Simulator

**Comment by sgschantz** [comment]
Unable to reproduce. Does this happen only on the simulator, or can you also do this when running from TestFlight?

**Comment by sgschantz** [comment]
@bharanidharanj still cannot reproduce this one; can you do so with the latest alpha or on a real device?
Are there any other details you can provide to help me reproduce it?

**Comment by bharanidharanj** [comment]
@sgschantz Retested this issue with the latest Keyman 17.0.234-alpha build in iOS 17 / iPhone 15 Pro Max Simulator and I was not able to reproduce it. Tried to reproduce it in the real iPhone 13 device and it seems be working fine. ie., No error message appeared on the screen. Seems to be working fine with the recent build. It would be better to close this issue. Thanks.
