### ISSUE TITLE
chore(web): build scripts are calling child scripts directly, meaning we lose deps and build state

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#9670]
e.g. bulk_rendering should be a child build of web/src/tools, but is called directly, so loses the environment (and ends up building things multiple times):

```
[web/src/tools] child build, parameters: <build --builder-child --deps>
[web/src/tools] ## build:bulk_rendering starting...
[web/src/tools/testing/bulk_rendering] build.sh parameters: <>
[web/src/tools/testing/bulk_rendering] ## build starting...
```

The pattern to look for is `build.sh parameters: <>` which indicates that a build.sh is being called directly rather than as a dependency or child script. I see:

* sourcemap-path-remapper
* bulk_rendering
* recorder
* test/manual/embed/android-harness

Note that the three tools above are called _twice_ at present because of this.

**Comment by jahorton** [comment]
I've just put together #9743 toward addressing the biggest issues pointed out here.  Doesn't solve everything, but it should mitigate the issue significantly.
