### ISSUE TITLE
bug(ios): build fails to build kmsample1

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#9674]
Building 17.0.185-alpha on my local machine with `./build.sh --sim-artifact --debug --force-deps`:

```log
...
[ios/keyman] Expected output: 'ios/build/Build/Products/Release-iphoneos/Keyman.xcarchive'.
[ios/keyman] ## build completed successfully, but output does not exist
[ios/samples/KMSample1] child build, parameters: <build --builder-child --force-deps --sim-artifact --debug>
[ios/samples/KMSample1] ## build starting...
cp: /Users/mcdurdin/Documents/Projects/keyman/app/ios/build/Build/Products/Release/KeymanEngine.xcframework: No such file or directory
[ios/samples/KMSample1] ## build failed
[ios] ## build:sample1 failed with exit code 1
```

**Comment by sgschantz** [comment]
@mcdurdin Local build executed succesfully for me. I guess it's possible that this was fixed by some of the library changes at the end of last year. Or do you think there is a step I am missing to reproduce? I didn't time it, but it was  a very slow build.

**Comment by mcdurdin** [comment]
I think it's quite likely this has been fixed. Does it relate to forum topic https://community.software.sil.org/t/ios-kmsample-dependencies-issues/8440?

**Comment by jahorton** [comment]
Attempting to build it today, with the latest from beta, on my old Mac dev-laptop:

![Screen Shot 2024-02-26 at 8 14 14 AM](https://github.com/keymanapp/keyman/assets/25213402/82bd1895-dc80-4f1e-81ec-11e8efc382d9)

This was when running `$KEYMAN_ROOT/ios/build.sh --debug`, (`cwd` == `$KEYMAN_ROOT/ios`, actual command `./build.sh --debug`).

**Comment by mcdurdin** [comment]
This is no longer an issue with reworked sample build scripts.
