### ISSUE TITLE
bug(common): ldml-keyboardtest3.schema.json is not strictly conformant

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#9683]
per `ajv -s ldml-keyboardtest3.schema.json -o ldml-keyboardtest3.schema.js` ([ref](https://ajv.js.org/standalone.html)):

```
[common/web/types] Compiling schema ldml-keyboardtest3.schema.json
strict mode: missing type "object" for keyword "required" at "#/properties/keyboardTest3" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "#/properties/keyboardTest3" (strictTypes)
strict mode: missing type "object" for keyword "properties" at "#/properties/keyboardTest3" (strictTypes)
```

**Comment by srl295** [comment]
okay, I'm not quite sure what's trying to happen here.  What's the second file being used? The packaged version of the schema?

If you are trying to validate the generated .json data against the schema, it doesn't, because as in the comment in compiler.ts:

```js
      // TODO-LDML: The unboxed data doesn't match the schema anymore. Skipping validation, for now.

      // try {
      //   if (!reader.validate(source)) {
      //     return null;
      //   }
      // } catch(e) {
      //   this.callbacks.reportMessage(CompilerMessages.Error_InvalidFile({errorText: e.toString()}));
      //   return null;
      // }
```

If you're trying to validate the schema itself, ajv says:

```shell
$ npx --package=ajv-cli -- ajv compile -s resources/standards-data/ldml-keyboards/techpreview/ldml-keyboard3.schema.json
schema resources/standards-data/ldml-keyboards/techpreview/ldml-keyboard3.schema.json is valid
```

**Comment by mcdurdin** [comment]
This is the ldml-keyboardtest3 schema, not ldml-keyboard3.

Background: this is precompiling the schema to a .js. These errors were raised by ajv 8.12.0.

**Comment by srl295** [comment]
Ok makes more sense

**Comment by mcdurdin** [comment]
This needs to be resolved in CLDR, should I open a ticket there?

**Comment by srl295** [comment]
Yes

**Comment by mcdurdin** [comment]
https://unicode-org.atlassian.net/browse/CLDR-17157
