### ISSUE TITLE
bug(mac): Unable to switch keyboards with macOS Sonoma 14.0

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#9684]
### Describe the bug

I encountered difficulty switching between keyboards within the Keyman menu.

### Reproduce the bug

1. Install Keyman 17.0.185 alpha build in macOS Sonoma 14.0.
2. Download and install two keyboards like 'KhmerAngkor' and 'Telugu Basic' using the Keyman Configuration dialog. 
3. Open the Keyman menu from the taskbar. 
4. Verify that there are two keyboards 'KhmerAngkor' and the 'Telugu Basic' Keyboard appears from the Keyboards list. The Khmer Angkor keyboard is selected by default. 
5. Switch to the 'Telugu Basic' keyboard by clicking on the 'Telugu Basic' name. 

Here, I noticed that the keyboard does not switch to 'Telugu Basic'. Seems to be an issue. 

Note: I was able to reproduce it in Keyman 16.0141 Stable build. 

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/5b665164-c674-4d10-aa24-7708e7ef10c9">

### Expected behavior

Switching between any two keyboards should be working fine using Keyman menu list. 

### Related issues

#8599

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [X] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16.0.141 Stable build, 17.0.185-alpha build

### Operating system

macOS 14 Sonoma

**Comment by mcdurdin** [comment]
See also https://community.software.sil.org/t/unselectable-on-macos-sonoma/8036

**Comment by sgschantz** [comment]
I think that we will change the dynamically-generated keyboards submenu to work around Sonoma.

According to Apple's [release notes](https://developer.apple.com/documentation/macos-release-notes/appkit-release-notes-for-macos-14#Menus):
> In macOS 14, menus have been reimplemented from the ground up to fully use AppKit.

**Comment by mcdurdin** [comment]
Good find! Sounds like a sensible plan.
