### ISSUE TITLE
bug(developer): The "Download and Install Keyman" option in the menu list within the localhost:8008 browser window is unresponsive or not functioning

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#9702]
### Describe the bug

I observed that when I click the "Download and Install Keyman" option from the menu list, it does not trigger any action on the screen.

### Reproduce the bug

1. Install Keyman Developer 17.0.186-alpha build.
2. Open a web keyboard in a localhost:8008 browser using Keyman Developer.
3. Click the top left icon (list menu) from the browser. 
4. Click the 'Download and install Keyman' option. 

I noticed that after clicking the 'Download and install Keyman' option, it does not trigger any action on the screen. 

I have attached the Screenshot for reference. 

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/f1300630-4666-4f54-959c-cc2a929fe7b3">

### Expected behavior

Selecting the 'download and install Keyman' option should trigger the opening of the Keyman download and installation window.

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [X] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.186-alpha

### Operating system

Windows 10 OS, Windows 11 OS (VM)

**Comment by mcdurdin** [comment]
```
Uncaught TypeError: Cannot read properties of undefined (reading 'OS')
    at menuDropdown.onclick (packages.js:14:31)
    at HTMLButtonElement.<anonymous> (test.js:94:14)
    at HTMLButtonElement.sentryWrapped (bundle.min.js:2:45453)
```

**Comment by mcdurdin** [comment]
This is due to a change in the KeymanWeb internals -- `keyman.util.device.OS` is no longer available, instead moving to `keyman.config.hostDevice.OS`. @jahorton is this appropriate?
