### ISSUE TITLE
bug(developer): The web keyboard is not displayed in the keyboard menu list when accessed through the Keyman Developer server menu

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#9704]
### Describe the bug

I observed that when I opened a web keyboard using the 'open http://localhost:8008 in the browser' option from the Keyman Developer server menu, it did not show up in the local browser's keyboard menu list.

### Reproduce the bug

1. Install Keyman Developer 17.0.186-alpha build. 
2. Open a Keyboard project (eg., itrans_devanagiri_hindi.kpj)  in the Keyman Developer. 
3. Click the 'Keyman Developer Server' tray icon from the taskbar. 
4. Click 'open http://localhost:8008 in the browser' option from the Keyman Developer server menu.

We may notice that the local browser window opens. 

5. Click the Keyboard menu list. 

Here, I noticed that the selected web keyboard did not show up in the keyboard menu list. Seems to be an issue. 

I have attached the screenshots for reference. 

..opened a keyboard project

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/70c490be-368c-4861-984c-5202507b85dd">

..web keyboard did show up in the keyboard menu list

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/03cb17ba-0465-4459-a4fb-eed171d43374">

### Expected behavior

The web keyboard should be present in the keyboard menu list when accessed through keyman developer server menu.

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [X] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.186-alpha

### Operating system

Windows 10 OS, Windows 11 OS (VM)

### Browser

Firefox 118.0.1 (64-bit)

**Comment by mcdurdin** [comment]
Did you click `Test Keyboard` in the Keyboard Editor? That is required in order for the keyboard to be made available to Keyman Developer Server.

**Comment by mcdurdin** [comment]
@bharanidharanj awaiting your feedback on this :grin:

**Comment by bharanidharanj** [comment]
@mcdurdin  Oops! Yes, Marc. After clicking the 'Test keyboard on web' button from the Keyboard Editor, I tried the same step. ie., Clicking 'open http://localhost:8008/ in the browser' option from the Keyman Developer server menu. Now, I am able to see the new keyboard in the Keyman drop-down list. Thanks for the Clarification. :-).

**Comment by bharanidharanj** [comment]
@mcdurdin It would be better to close this issue. Thanks!

**Comment by mcdurdin** [comment]
Thanks!
