### ISSUE TITLE
bug(developer): Validation error message appear on the console window after compilation of a keyboard in the Package Editor 

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#9732]
### Describe the bug

I noticed that after the keyboard compilation, an error message appear on the console. 

### Reproduce the bug

1. Install Keyman Developer 17.0.185-alpha  (from keyman.com site)
2. Open any Keyboard project. (eg., khmer_angkor)
3. Click the Keyboards tab. 
4. Run Compile Keyboard. 
We may notice the 'Compiled successfully..' message appear in the console. 
5. Click the Packaging tab.
6. Run Compile Keyboard. 

Here, I noticed that an error message "Validation error" appears in the console. Seems to be an issue. 

I have attached the Screenshot for reference. 

..Validation error message

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/bda14df4-5e37-4285-9ea7-f00fc7b64139">

### Expected behavior

'Compiled Successfully' message should appear after the compilation in Package editor

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [X] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.185-alpha

### Operating system

Windows 10 OS (Native machine)

**Comment by mcdurdin** [comment]
I believe this is fixed as of 17.0.196-alpha. Can you retest with that version please?

**Comment by mcdurdin** [comment]
@bharanidharanj -- 
I believe this is fixed as of 17.0.196-alpha. Can you retest with that version please?

**Comment by bharanidharanj** [comment]
@mcdurdin Retested with Keyman Developer 17.0.196-alpha build on Windows 11 OS (VM) and I was not able to reproduce it. Seems to be fixed and working fine with the recent build. Thanks. 

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/40b999e4-91ab-46eb-bcd7-1788924f28ff">

**Comment by mcdurdin** [comment]
Thanks!
