### ISSUE TITLE
chore(linux): Rename `libkmnkbp` to `libkeymancore`

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/keyman#9733]
As a follow-up of #9721 and #9722 we should rename the library to `libkeymancore` and also bump the version number. This also requires changes in the `debian` directory.

- new binary will be `libkeymancore.so.1.0`
- package names will be `libkeymancore` and `libkeymancore-dev`

_Edit: Updated library name following our discussion in standup meeting. `libkeymancore` is less cryptic than `libkmncore`._

**Comment by mcdurdin** [comment]
See also notes in https://github.com/keymanapp/keyman/pull/9723#issuecomment-1755512073

**Comment by ermshiperete** [comment]
`core/meson.build` specifies `lib_version` which has to be updated.

Also noticed that `libkmnkbp(.a)` is also used on the other platforms.
