### ISSUE TITLE
[Window] bug/feature request: language keyboard from OS

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#975]
I am not sure if this is bug or feature request.

When a Keyman keyboard is installed in a PC (Windows 7/8/10). 
Lets say Kannada language. 
System will installed Windows default Kannada keyboard, in addition to Keyman Kannada keyboard.

Installing two Kannada keyboards can be confusing to users. They will be required to remove this keyboard from "Region/language" settings. This can be avoided.

This was happening in Version 9.0.

Maybe its overlooked bug. 
Or limitation in Windows system, if so please program Keyman to remove the additional keyboards during installation of Keyman package.

**Comment by mcdurdin** [comment]
We have some code that attempts to address this, not always successfully; it's a little weird because it seems the system keyboard is automatically added by Windows, asynchronously. This is a little documented part of the Windows API. We will continue to work to smooth this.

**Comment by MayuraVerma** [comment]
This is in Windows 10 under "regions and language".
It is impossible for user to know, which is Keyman keyboard and which is system keyboard. 
![image](https://user-images.githubusercontent.com/14062593/41333488-9f2854ac-6ea7-11e8-8c93-da9a68d11d66.png)

Windows 7, displays the name of the keyboard under settings.

**Comment by MayuraVerma** [comment]
I have reported this as a separate issue
https://github.com/keymanapp/keyman/issues/983
