### ISSUE TITLE
bug(developer): language `rsk` is given a blank name in compiled .keyboard_info

### ISSUE THREAD

**Issue by LornaSIL** [keymanapp/keyman#9762]
This keyboard is for the `rsk` language and I believe it has the appropriate information in keyboard_info and .kps. However, the home page does not indicate that there is any language supported:

https://keyman.com/keyboards/rusyn

I've tested the keyboard on Android and it is working and indicates the correct language.

**Comment by mcdurdin** [comment]
This is fixed with 17.0.196-alpha, so I hope that we can just wait for the 17.0 alpha to land and use the data from that.

**Comment by mcdurdin** [comment]
Resolved in 17.0-alpha as noted above.
