### ISSUE TITLE
bug(linux): Unable to access the  keyman configuration window through the command line (km-config) in Wasta 20.04 Linux OS

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#9773]
### Describe the bug

I observed that when executing the "km-config" command in the terminal, it generates an error message.

### Reproduce the bug

1. Install Keyman 17.0.191-alpha build in Wasta 20.04 Linux OS.
2. Open the Terminal window.
3. Run the km-config command.

I observed an error message appearing on the terminal following the execution of the command.

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/8cbe4e3f-7b60-4eaf-8077-eefb8423dfdb">

### Expected behavior

After running 'km-config' command in the terminal, the keyman configuration dialog should opens. 

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [X] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.191-alpha

### Operating system

Ubuntu Wasta 20.04 Linux OS

**Comment by ermshiperete** [comment]
This will also happen on Ubuntu 20.04 Focal. The reason is that those are using Python 3.8 which doesn't have the method `platform.freedesktop_os_release()` that we recently started to call.
