### ISSUE TITLE
[web] osk.updateLayer has legacy code regarding building layer names that should be eliminated

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#978]
`osk.updateLayer()` builds up a special layer name based on the `nextLayer` (`id`) parameter and the current layer name, but only for non-recognised layer names. This is slightly bizarre given our model now of defining each layer completely. It comes from older code which was based on the desktop Ctrl/Shift/Alt model.

This pattern is certainly obsolete for touch devices. For desktop devices, there may still be some reliance on it. This needs to be tested further.

web/source/testing/test-updateLayer provides a sample keyboard that shows the problem. Switching from `symbols` layer to `shift` layer by pressing the [Shift] key fails down to the default layer, because `updateLayer()` is looking for a layer named `shift-symbols`, constructed from the new layer name followed by the current layer name.

**Comment by jahorton** [comment]
KeymanWeb `desktop` mode still uses this code pathway; putting the OSK into the 'shift' layer and then clicking 'ctrl' relies upon `updateLayer()` to combine the two.

For now, it should be simple enough to do a quick form-factor check first so that mobile doesn't run into issues with this.
