### ISSUE TITLE
chore(common): pull URL out of common/web/types 🐵

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#9788]
Hmm, @srl295 I think we should pull `URL` usage out of this module and have a helper instead. It's apparently used in 4 places altogether in unit tests and kmc:

* kmc buildTestData/index.ts
* kmc BuildLdmlKeyboard.ts
* unit test: reader-callback-test.ts
* unit test helpers/index.ts

Propose the following:

```
static get defaultImportsURL() {
  return ['../import/', import.meta.url];
}
```

And in usage:

```
    readerOptions: {
      importsPath: fileURLToPath(new URL(...LDMLKeyboardXMLSourceFileReader.defaultImportsURL))
    }
```

[...]

Be good to address it before this change lands in master though, just for cleanliness.

_Originally posted by @mcdurdin in https://github.com/keymanapp/keyman/pull/9664#discussion_r1360020505_

**Comment by srl295** [comment]
OK i missed the comment in the PR. 

I think this is just moving the import of `url` from the common lib down into the caller.

**Comment by mcdurdin** [comment]
> I think this is just moving the import of `url` from the common lib down into the caller.

yes
