### ISSUE TITLE
bug(linux): Encountered an error message in the terminal window upon selecting the "Share Online" link

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#9806]
### Describe the bug

I noticed that after clicking the share online link button an error message appeared in the terminal window.

### Reproduce the bug

1. Install Keyman 17.0.193-alpha build. 
2. Open Keyman Configuration dialog. 
3. Download and Install any keyboard. (eg., khmer_angkor)
4. Select the Keyboard then click the 'About' button. 
5. From the Keyboard dialog, Click 'share online' link button. 

Here, I noticed that there is an error message (?) appear in the terminal window. Seems to be an issue. 

Note: It is reproducible in Ubuntu 20.04 Focal and Ubuntu 23.10 Mantic OS. 

..error message in Ubuntu 20.04 Focal Linux 

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/60e04296-c8b7-40ed-879d-45d67f9158e2">

..error message in Ubuntu 23.10 Mantic OS

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/0ca6f9c3-d61c-4b01-bcbb-ae7c7502682b">

### Related issues

Selecting the "Share Online" link should not result in any error messages appearing in the terminal window.

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [X] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.193-alpha

### Operating system

Ubuntu 20.04 Focal and Ubuntu 23.10 Lunar Linux OS

**Comment by ermshiperete** [comment]
This is caused by Firefox being installed as snap package and there's nothing we can do about that. However, since users normally start km-config from the launcher instead of the terminal they won't see these messages.
