### ISSUE TITLE
bug(core): test -t option not working?

### ISSUE THREAD

**Issue by srl295** [keymanapp/keyman#9816]
How is this supposed to work?

```shell
$ core/build.sh -d test:mac-x86_64 -t 'abc'
[core] core/build.sh: invalid parameter: -t
…
Options: 
  --test opt_tests,-t    test[s] to run (space separated)

$ core/build.sh -d -t abc test:mac-x86_64 
[core] core/build.sh: invalid parameter: -t

$ core/build.sh -d --test abc test:mac-x86_64 
/Users/srl295/src/keymanapp/keyman/resources/builder.inc.sh: line 1340: declare: `opt_tests,-t=abc': not a valid identifier

$ core/build.sh -d --test=abc test:mac-x86_64 
[core] core/build.sh: invalid parameter: --test=abc
```

**Comment by mcdurdin** [comment]
Hmm, looks like the definition in build.sh may be wrong, should be `--test,-t=opt_tests  test[s] to run (space separated)`

**Comment by mcdurdin** [comment]
Also looks like the parameter is never used in the build. You could use `./build.sh test -- --test=abc` as that _does_ look like it is passed through. (`--` is separator for "extra params":

https://github.com/keymanapp/keyman/blob/549a8e009e0ea51abe90ff27a72267c669f58fde/core/build.sh#L176

https://github.com/keymanapp/keyman/blob/2fa8a09672eb7ccedb0e1c91121d08b8a345c504/core/commands.inc.sh#L91-L95
