### ISSUE TITLE
bug(developer): After installing the Keyman Developer 17.0.197 build, the Keyman Server is not in an operational state on Windows 10 OS

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#9848]
### Describe the bug

Following the installation of the Keyman Developer 17.0.197 build on a Windows 10 OS, the Keyman Server is not functioning as expected.

### Reproduce the bug

1. Install Keyman Developer 17.0.197-alpha build on Windows 10 OS.
2. Open a Keyman Project (eg., Khmer_Angkor.kpj) using Keyman Developer. 
3. Compile the Keyboard. 
4. Click the Build tab. 
5. Click the 'Test Keyboard on Web' button. 

Here, I noticed that a confirm message 'Keyman Developer Server does not appear to be running. Try and start Keyman Developer Server now?" with the Yes, No, and Cancel buttons. 

6. Click the 'Yes' button to show another confirmation message 'Keyman Developer Server has not yet started successfully, Keep waiting?" with the OK and Cancel buttons. 

Clicking the OK button repeats the same message on the screen. 

I noticed that the Keyman Server icon is not displayed in the taskbar. Seems that the Keyman Developer Server is not running with the application. 

I have attached the Screenshots for reference. 

..Confirm message 1 

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/7b4efc2a-571e-4130-a1cd-ff2e774b9593">

..Confirm message 2

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/4eeeb7aa-1850-4930-a93b-ff46dafa5e26">

### Expected behavior

Selecting the "Yes" button will initiate the Keyman Server, and the local web address links should then become visible in the web address pane.

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [X] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.197-alpha

### Operating system

Windows 10 OS (Native machine)

**Comment by bharanidharanj** [comment]
@mcdurdin Retested with the latest Keyman Developer 17.0.201-alpha build on Windows 10 OS (Native Machine) and here is my observation: 1. I was able to see the Web address link on the 'Test keyboard on web' field. 2. I got an error message after opened the link in any browser. 3. FYI, I have disabled Firewall and proxy settings. But, still, I noticed that the Keyman Developer server icon was missing in the taskbar. 4. I was able to reproduce this issue with the recent build too. 

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/5bdca4b5-7564-4122-895f-22dea7a41f25">

**Comment by mcdurdin** [comment]
@bharanidharanj thank you for this report. I have tried to reproduce this here on my computer but it seems to be working okay. Can you try clicking on the `http://localhost:8008` or `http://127.0.0.1:8008` links and see if it works with those?

**Comment by bharanidharanj** [comment]
@mcdurdin I retested with the latest Keyman Developer 17.0.203-alpha build on Windows 10 OS (Native Machine) and here is my observation: 1. Tried with the above-mentioned web address links and noticed that it throws an error message. 2. Noticed that the Keyman Developer Server icon is still missing in the taskbar. 3. Getting a warning message, whenever I tried to click the 'Start debugging' option. Clicking the OK button doesn't do anything on the screen. If I tried to start debugging, again the same window opens. Seems to be an issue. Or Did I miss out on anything in the Configure window?


..webaddress1

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/e82681a2-65f0-460b-99c2-cd5a64c3f286">


..webaddress2

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/2729a87b-ca78-4a8b-b57f-79148ad3f053">


..debugerror

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/90d84c42-c9d5-4d59-b5d7-4ddf47111097">

**Comment by mcdurdin** [comment]
OK, I'm not sure what is going on. Perhaps we can rubber-ducky tomorrow after Standup?

**Comment by mcdurdin** [comment]
Cache corruption, need to investigate what was corrupted and why

**Comment by mcdurdin** [comment]
cache.json, lock.json, and pid.json were all filled with nul bytes (9168, 5, and 5 bytes respectively). Unclear what is happening. Resilient response is to wipe them + cache folder if corruption detected (but a log to sentry would be helpful)

**Comment by mcdurdin** [comment]
[server-folder.zip](https://github.com/keymanapp/keyman/files/13247389/server-folder.zip)
