### ISSUE TITLE
[Linux] Arch Linux package

### ISSUE THREAD

**Issue by nikita-moor** [keymanapp/keyman#985]
In order to simplify packaging, could you:

1. Include only linux-related files in linux-release — KFML source code is 1.1 Mb against 160.9 Mb of Keyman's sources.
2. Compile all 3 sub-projects in one pass. The way proposed in `build.sh` is not applicable for Arch Linux — one cannot install binaries directly into `/usr/`. So, every package is build in a temporary directory and such files as `kmfl.h` and `libkmfl.so` are not in their final locations. Currently, I need to support 3 separate packages.

**Comment by glasseyes** [comment]
1. The release versions will be the standard tarballs not the whole keyman source for all platforms

2. build.sh installs to /tmp/kmfl (or whatever you set INSTALLDIR to). It is a script for the continuous build server, or to /usr/local for local testing.
kmflcomp, libkmfl and ibus-kmfl were separate on https://sf.net/projects/kmfl and still are. The 3 source packages are separate on Debian.
afaict kmflcomp is separate because it is only useful to keyboard developers rather than the average user
ibus-kmfl is separate because there can be other implementations for other input systems (possibly fcitx in the future, scim in the past)

HTH

**Comment by mcdurdin** [comment]
Note also that the final deployment model is likely to change as kmflcomp will be removed with the full release of Keyman for Linux 11.0, when Keyman for Linux consumes .kmx files created with Keyman Developer (kmcomp on Linux/WINE).

**Comment by glasseyes** [comment]
I hope kmflcomp will be replaced by a cross platform version rather than depending on wine if it'll be possible to implement it with the new api engine.

also I'd expect libkmfl to be replaced by the cross platform api engine

**Comment by mcdurdin** [comment]
kmcomp is not scheduled for rewrite in 11.0, but probably in 12.0. It has a number of Windows dependencies and will take some effort. Yes, libkmfl will be replaced by the cross platform api engine. It's not 100% clear at this stage whether we'll keep the same project name or not -- no reason not to, if it simplifies things.

**Comment by nikita-moor** [comment]
The new `km-config` application uses the old "WebKit1" API deprecated since 2014.

https://github.com/keymanapp/keyman/blob/3f474c64feb842cfadfd5c253516624056359adc/linux/keyman-config/keyman_config/welcome.py#L11

It cannot be used in Arch Linux because of [security vulnerabilities](https://www.archlinux.org/todo/phasing-out-webkitgtk2/). Could this part of the code be rewritten using "WebKit2"?

**Comment by nikita-moor** [comment]
Would be nice to move all directories to a separate config file. Example:

https://github.com/keymanapp/keyman/blob/3f474c64feb842cfadfd5c253516624056359adc/linux/keyman-config/keyman_config/install_kmp.py#L95-L106

Though, in my opinion, keyboards should be installed into a user's home directory.

**Comment by glasseyes** [comment]
> The new `km-config` application uses the old "WebKit1" API [deprecated since 2014](https://blogs.gnome.org/mcatanzaro/2016/02/01/on-webkit-security-updates/).
> 
> [keyman/linux/keyman-config/keyman_config/welcome.py](https://github.com/keymanapp/keyman/blob/3f474c64feb842cfadfd5c253516624056359adc/linux/keyman-config/keyman_config/welcome.py#L11)
> 
> Line 11 in [3f474c6](/keymanapp/keyman/commit/3f474c64feb842cfadfd5c253516624056359adc)
>  gi.require_version('WebKit', '3.0') 
> 
> Supporting an old port of this big library would be a laborious task (and [is not welcome](https://www.archlinux.org/todo/phasing-out-webkitgtk2/) in Arch Linux). What is the reasoning to use it for new development?

Please open a new issue for this and we'll have that discussion there.

**Comment by glasseyes** [comment]
> In order to simplify packaging, it would be nice to move all directories to a separate config file.

I'm sorry. I don't understand what you mean by this.

> New `km-config` and accompanying tools are greedy to such data. Example:
> 
> [keyman/linux/keyman-config/keyman_config/install_kmp.py](https://github.com/keymanapp/keyman/blob/3f474c64feb842cfadfd5c253516624056359adc/linux/keyman-config/keyman_config/install_kmp.py#L95-L106)
> 
> Lines 95 to 106 in [3f474c6](/keymanapp/keyman/commit/3f474c64feb842cfadfd5c253516624056359adc)
>  if not os.access('/usr/local/share/keyman', os.X_OK | os.W_OK): # Check for write access of keyman dir 
>  	logging.error("You do not have permissions to install the keyboard files. You need to be a member of the keyman group. `sudo adduser <username> keyman`") 
>  	exit(3) 
>  kbdir = os.path.join('/usr/local/share/keyman', kbid) 
>  if not os.access('/usr/local/share/doc/keyman', os.X_OK | os.W_OK): # Check for write access of keyman doc dir 
>  	logging.error("You do not have permissions to install the documentation. You need to be a member of the keyman group. `sudo adduser <username> keyman`") 
>  	exit(3) 
>  kbdocdir = os.path.join('/usr/local/share/doc/keyman', kbid) 
>  if not os.access('/usr/local/share/fonts/keyman', os.X_OK | os.W_OK): # Check for write access of keyman fonts 
>  	logging.error("You do not have permissions to install the font files. You need to be a member of the keyman group. `sudo adduser <username> keyman`") 
>  	exit(3) 
>  kbfontdir = os.path.join('/usr/local/share/fonts/keyman', kbid) 
> 
> Though, in my opinion, keyboards should be installed into the user's home directory.

see #1177

**Comment by nikita-moor** [comment]
> > In order to simplify packaging, it would be nice to move all directories to a separate config file.

> I'm sorry. I don't understand what you mean by this.
> see #1177

I meant to move definition of the paths to a separate file. Something like that:

```py
# config.py
installdir = dict(
  keyman = '/usr/local/share/keyman',
  doc = '/usr/local/share/doc/keyman',
  fonts = '/usr/local/share/fonts/keyman'
)
```
```py
# install_kmp.py
import config
...
kbdir = os.path.join(config.installdir['keyman'], kbid) 
```

So I could easily adapt it to the filesystem hierarchy standards of the target OS. For example, replace `/usr/local/share/` with `/usr/share/`. Also, it's not clear to the date do we need to migrate user's files from `~/.kmfl` to `/usr/local/share/keyman` or `~/.local/share/keyman`, so some flexibility would be appreciated.

**Comment by glasseyes** [comment]
> > > In order to simplify packaging, it would be nice to move all directories to a separate config file.
> 
> > I'm sorry. I don't understand what you mean by this.
> > see #1177
> 
> I meant to move definition of the paths to a separate file. Something like that:
> 
> ```python
> # config.py
> installdir = dict(
>   keyman = '/usr/local/share/keyman',
>   doc = '/usr/local/share/doc/keyman',
>   fonts = '/usr/local/share/fonts/keyman'
> )
> ```
> 
> ```python
> # install_kmp.py
> import config
> ...
> kbdir = os.path.join(config.installdir['keyman'], kbid) 
> ```

Thanks for the explanation.

> So I could easily adapt it to the filesystem hierarchy standards of the target OS. For example, replace `/usr/local/share/` with `/usr/share/`. 

`/usr/local/share` is the FHS standard for where to install local shared data. `/usr/share` is where you can install keyboards installed by the OS in a package e.g. Arch, Debian.

The locations of where ibus-kmfl are hardcoded for where it looks for keyboards so you will need to patch ibus-kmfl for it to know about keyboards anywhere other than in `/usr/share`, `/usr/local/share`, `~/.kmfl`, `~/.local/share`

> Also, it's not clear to the date do we need to migrate user's files from `~/.kmfl` to `/usr/local/share/keyman` or `~/.local/share/keyman`, so some flexibility would be appreciated.

The current plan is for ibus-kmfl to support both the existing keyboards that users have and the compiled kmx keyboards. So there won't be any need for a migration. It will still detect keyboards in `~/.kmfl`

**Comment by glasseyes** [comment]
Nikita, is there more to this or is it ok for me to close this issue?

**Comment by nikita-moor** [comment]
I was waiting for the 11th release, but now do not expect any problems. So, close.

**Comment by nikita-moor** [comment]
I know linux version is still alpha and under active development, but consider, please, explaining following questions on release:

* **On-screen keyboard.** I see several commits mentioning OSK (such as #1337) and a separate repository [onboard-keyman](https://github.com/keymanapp/onboard-keyman). Could I recommend our users installing optional package `Onboard` extending main functionality?

From my former conversation with Onboard community, the development of this application was stopped in favour of [OnboardOSK](https://launchpad.net/onboardosk):

> Onboard not being compatible with newer Technologies like Wayland and GNOME3, a rewrite of Onboard was started under the name of OnboardOSK more than one year ago.

However, neither OnboardOSK is developing. So, are you goining to get your patchs into the upstream or support own fork?

* **IBus & language codes.** Here #1183 you mention a patch for ibus. Could I see it and was it accepted by ibus developers?
