### ISSUE TITLE
feat(web): Make popups and keytips children of .kmw-keyboard to streamline CSS selection

### ISSUE THREAD

**Issue by MattGyverLee** [keymanapp/keyman#9864]
### Is your feature request related to a problem? Please describe.

Today, I'm playing with CSS selectors for popups in α17. I've wanted my vowel popups to be colored like my static vowel keys, and I hear from @mcdurdin that we have some new popup styling options in 17.

![image](https://github.com/keymanapp/keyman/assets/986339/9dd4eac4-793c-4c8d-a371-37bc3eaec6bb)

```
.android .kmw-keyboard-sil_cameroon_qwerty .kmw-key[id$='K_A']:not(.kmw-key-touched),
.android #kmw-popup-keys .kmw-key[id*='U_2C6D']:not(.kmw-key-touched) {background-image: radial-gradient(transparent, #00000030), linear-gradient(#7f7f7f55, #beab40dd);}
```
I got it working in mobile preview (haven't tested it on real phones), but I did run into one inconsistency related to selectors.

I usually include the keyboard name in my CSS selector to avoid leakage and give my rules a higher specification priority:
```
.android .kmw-keyboard-sil_cameroon_qwerty .kmw-key[id$='K_A']:not(.kmw-key-touched)
```
but if I add `.kmw-keyboard-sil_cameroon_qwerty` to my popup, it doesn't work. 
```
/* works */
.android #kmw-popup-keys .kmw-key[id*='U_2C6D']:not(.kmw-key-touched) {background-image: radial-gradient(transparent, #00000030), linear-gradient(#7f7f7f55, #beab40dd);}
/* does not work */
.android .kmw-keyboard-sil_cameroon_qwerty #kmw-popup-keys .kmw-key[id*='U_2C6D']:not(.kmw-key-touched) {background-image: radial-gradient(transparent, #00000030), linear-gradient(#7f7f7f55, #beab40dd);}
```

This is because popups are children of `#kmw-popup-keys` which is itself a sibling and not  a child of `.kmw-keyboard-sil_cameroon_qwerty`.  Popups and keytips are both siblings of the keyboard `div`.

![image](https://github.com/keymanapp/keyman/assets/986339/70fb51ed-b23b-4034-bb32-ece850129234)

### Describe the solution you'd like

Since there are now several siblings of  `.kmw-keyboard-sil_cameroon_qwerty` that are specific to the selected keyboard, maybe we need a new `div` wrapper around them that can be the new `.kmw-keyboard-sil_cameroon_qwerty`.

### Describe alternatives you've considered

Add a customized class to the siblings, like: `.kmw-popups-sil_cameroon_qwerty` or  `.kmw-keytips-sil_cameroon_qwerty`, but this seems less ideal.

### Keyman apps

- [X] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.198

### Operating system

Windows 11

### Keyboard name

sil_cameroon_qwerty

**Comment by mcdurdin** [comment]
@jahorton this sounds sensible -- but perhaps needs to be part of the whole retheming project? Or are there small tweaks we can make now to address this sufficiently for @MattGyverLee's needs?

**Comment by MattGyverLee** [comment]
No rush. I have my workaround. I just wanted to get this in there for consideration for when you do make changes.

**Comment by mcdurdin** [comment]
The big problem with workarounds is that each workaround makes it harder
for us to fix the issues in subsequent versions without breaking keyboard
rendering for existing keyboards!

**Comment by jahorton** [comment]
> @jahorton this sounds sensible -- but perhaps needs to be part of the whole retheming project? Or are there small tweaks we can make now to address this sufficiently for @MattGyverLee's needs?

I could give it a try.  It's something I've been noticing for a _while_ and wondering about.

**Comment by jahorton** [comment]
This will land as part of the upcoming gestures feature for 17.0; it's already been fixed on that branch.

**Comment by MattGyverLee** [comment]
> whole retheming projec

@mcdurdin Is there a meta-issue for the retheming project you reference? I've had some good luck with CSS variables that could make this as easy as choosing a set of colors.

**Comment by mcdurdin** [comment]
> Is there a meta-issue for the retheming project you reference?

Not at this point. It's on the roadmap but not at the point where we've started opening issues relating to it.
