### ISSUE TITLE
bug(windows): RTL switches to LTR when punctuation key entered  

### ISSUE THREAD

**Issue by rc-swag** [keymanapp/keyman#9874]
### Describe the bug

Raised in the Community forum [here](https://community.software.sil.org/t/rtl-switches-to-ltr-with-punctuation/8061).
When typing with an RTL such as Yiddish or `Urdu Phonetic` when a punctuation key is entered, for example, a double quote `"`.
The double quote is placed on the far right of the current line, and the cursor is also moved to this position. As soon as another non-punctuation key is pressed, both the double quote and the cursor are moved to the far left, that is to the correct position. However, if an `Return` key is pressed the double quote will stay in the incorrect insertion point on the right. 

This is observed in Notepad and LibreOffice on Windows 10.  However, it works fine in Word, WordPad, and Firefox. This suggests it is a problem only in not TSF apps. 

Update:
I just discovered even `space` is initially inserted on the right until the next key press then the `space` plus the next character and cursor return to the left. While it works out ok it is distracting to the user.

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [X] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.197

### Operating system

Windows 10

### Keyboard name

Yiddish Pasekh, Urdu Phonetic

### Keyboard version

1.9,1.21

### Language name

RTL (hebrew), Urdu

**Comment by mcdurdin** [comment]
This seems like it relates to display rather than input?

**Comment by rc-swag** [comment]
> This seems like it relates to display rather than input?

Display or the editor itself? A <kbd>"</kbd> followed by <kbd>Return</kbd> will result in the double quote remaining on the right. If it is an issue with the editor. Then we would either have to raise a bug with them OR. Do something hacky like sending a dummy character (for RTL languages for certain code points) and deleting it so the editor fixed itself

**Comment by rc-swag** [comment]
The display problem is that the text area or paragraph section is set as LTR instead of RTL. 
By correcting the setting in `Notepad` , `LibreOffice` and `Word` the punctuation behaves correctly.
It is also worth checking the correct language is registered for the keyboard in the Keyman Configuration.
I have put more detail on how to change this setting in the original forum [post](https://community.software.sil.org/t/rtl-switches-to-ltr-with-punctuation/8061/5).
