### ISSUE TITLE
bug(linux): Installed Keyman package shows `-local` tag

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/keyman#9878]
Running `km-config --version` with Keyman packages installed incorrectly shows

```
km-config version 17.0.198-alpha-local (package version 17.0.198-1+jammy1)
```

The correct version number would be `17.0.198-alpha-test`.

**Comment by mcdurdin** [comment]
If this is for an alpha release build, it should be just `17.0.198-alpha`. 

* `-test` is only used for PR test branch builds, and should also have a PR appended:

  ```
  #   VERSION_TAG:      Tier + Pull Request + Location of build [-alpha|-beta][-test[-1234]][-local]
  ```
