### ISSUE TITLE
bug: CI cannot handle use of new commands in .kps from v17.0

### ISSUE THREAD

**Issue by LornaSIL** [keymanapp/keyman#9884]
### Describe the bug

I attempted to use the new "welcome", "examples" and "related" fields in a PR:
https://github.com/keymanapp/keyboards/pull/2436/commits/145554ab6995bd1794d4290b271c434a690c844b

CI gave me this message:
```
source/gondi_gunjala.kps:11: element WelcomeFile: Schemas validity error : Element 'WelcomeFile': This element is not expected.
source/gondi_gunjala.kps:153: element Examples: Schemas validity error : Element 'Examples': This element is not expected.
source/gondi_gunjala.kps:156: element RelatedPackages: Schemas validity error : Element 'RelatedPackages': This element is not expected.
source/gondi_gunjala.kps fails to validate
Failed to validate source/gondi_gunjala.kps
```

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Additional context

The keyboard built in Developer, but the problem occurred on the CI.

**Comment by mcdurdin** [comment]
Yes, CI is still running 16.0, until we merge the staging branch in. I hope to do that soon, once I have completed final verification of the outputs of the 17.0 compiler. I've done the verification of each component a couple of times, but now that all the bits and pieces are in place, for peace of mind I just want to run through it again.

That's assuming you are comfortable with running the alpha version of the compiler on the keyboard repository!

So I'll go ahead and close this as it is an expected outcome right now.
