### ISSUE TITLE
bug(ios): After deactivating the predictions feature, an empty suggestion banner becomes visible with the default keyboard

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#9894]
### Describe the bug

I've observed that, despite my deactivation of the prediction feature, an empty suggestion banner remains visible when I use the EuroLatin(SIL) keyboard.

### Reproduce the bug

1. Install Keyman 17.0.201-alpha build. 
2. Open Keyman In-App.
3. Verify that the Suggestion banner appears with the suggestions along with the default keyboard. 
4. Open the Settings menu. 
5. Click Installed Languages / English (EuroLatin (SIL))option. 
6. Switch off the 'Enable predictions' feature. 
7. Revert to the Main window. 
Here, I noticed that an empty suggestion banner still appears with the default OSK. Seems to be an issue. 

I have attached the Screenshots for reference. 

..Disable predictions radio button

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/1fe00b56-16a6-4948-93c5-834c44186ce0">

..an empty suggestion banner still visible

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/7690e14d-c908-43f9-8924-20467454e5c4">

### Expected behavior

Disabling the predictions feature should eliminate the suggestion banner from the default EuroLatin(SIL) keyboard.

### Keyman apps

- [ ] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.201-alpha

### Operating system

iOS 16.6

### Device

iPhone 13

**Comment by sgschantz** [comment]
Reproduced on a real device, iPhone Xs Max with iOS 17.2.1 and Keyman 17.0.201-alpha.

Closing: not reproducible with 17.0.233-alpha.
