### ISSUE TITLE
[mac iOS] pages, keynotes: context Error

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#991]
in mac and iOS

keyman is failing in pages and keynotes

key stroke -> k, f, l 
output ಕ್ಲ (U+0c95 U+0ccd U+0cb2)
followed by key stoke -> A 
expected output -> ಾ (U+0cbe) in addition to the existing text, so on screen output must be  ಕ್ಲಾ  (U+0c95 U+0ccd U+0cb2 U+0cbe)
Here is the context is U+0cb2. With the presence of U+0cb2, key "A" outputs  ಾ (U+0cbe) 

But trouble is pages and keynotes in mac and iOS treats the ಕ್ಲ as one cluster.

So, the output in the screen is ಲಾ (U+0cb2 U+0cbe), This output is ERROR.

This is a serious bug. Please check.

**Comment by MayuraVerma** [comment]
FYI: This was working fine in earlier versions of both mac and ios.

**Comment by mcdurdin** [comment]
Thank you for the report. Can you provide a minimal keyboard layout that reproduces the problem and attach it to this issue? That will make it much easier for us to test the problem. It may be also useful to create two versions of the keyboard: one that works with Kannada script and one with Latin script, to see if the problem is related to the script or not.

**Comment by MayuraVerma** [comment]
@mcdurdin Mark, it is related to script. This problem is showing up in version 47, it was working fine in 44 and earlier.
It is related to treating pages and keynotes as legacy application.
I can confirm the same and let you know by evening.
I will post a better report by evening.

**Comment by tombogle** [comment]
Probably the answer is to revert that change and not treat those apps as legacy. That would mean that you'd be back to the problem of not being able to choose a font (or other formatting) and then start typing. You'd have to have at least one character typed select it, and then apply the font/formatting. Perhaps there is some other way to fix that, but it sounds like the current "fix" is actually worse than the original problem we were trying to solve.
