### ISSUE TITLE
[android] exceptions switching to certain keyboards

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#992]
I'm getting intermittent weirdness switching to certain keyboards.
Screenshot below is from [sil_bwe_karen]. In the keyboard catalog, it's listed under "Karen, Bwe".

Is there some KMW issue with BCP 47 tags involving script tags?

Using Keyman Android 10.0.401 beta
Android 7.1 Nougat

![screenshot_20180616-141116](https://user-images.githubusercontent.com/7358010/41496700-64d912c0-7170-11e8-93e8-4e2ce561a362.png)

Once this happens, it seems to trigger switching to every currently installed keyboard . even the default EuroLatin2.  The keyboards seem to still type in the app.

**Comment by darcywong00** [comment]
When the Android app attempts to download **sil_bwe_karen**

https://api.keyman.com/cloud/3.0/languages/bwe/sil_bwe_karen?version=10.0.0.0&device=androidphone

returns an empty language object
```
{
	"options": {
		"context": "language",
		"dateFormat": "standard",
		"device": "androidphone",
		"keyboardBaseUri": "https://s.keyman.com/keyboard/",
		"fontBaseUri": "https://s.keyman.com/font/deploy/",
		"keyboardid": "sil_bwe_karen",
		"languageid": "bwe",
		"keyboardVersion": "current"
	},
	"language": []
}
```

**Comment by mcdurdin** [comment]
The Android app should be looking up https://api.keyman.com/cloud/3.0/languages/bwe-Latn/sil_bwe_karen?version=10.0.0.0&device=androidphone&languageidtype=bcp47

Which returns

```
{
	"options": {
		"context": "language",
		"dateFormat": "standard",
		"device": "androidphone",
		"keyboardBaseUri": "https:\/\/s.keyman.com\/keyboard\/",
		"fontBaseUri": "https:\/\/s.keyman.com\/font\/deploy\/",
		"languageid": "bwe-Latn",
		"keyboardVersion": "current"
	},
	"language": {
		"name": "Karen, Bwe",
		"id": "bwe-Latn",
		"keyboards": [{
			"id": "sil_bwe_karen",
			"name": "Bwe Karen (SIL)",
			"filename": "sil_bwe_karen\/1.0\/sil_bwe_karen-1.0.js",
			"lastModified": "2018-06-15",
			"version": "1.0",
			"fileSize": 13552
		}]
	}
}
```

**Comment by darcywong00** [comment]
hmm, that's something for us to chase down. 

In the debugger, I'm seeing language ID `bwe` instead of `bwe-Latn` in the Keyboard downloader activity...

**Comment by mcdurdin** [comment]
I've put this into the plan for this sprint because I think this needs to be fixed before 10.0 stable release.

**Comment by darcywong00** [comment]
#1012 added the filter to the language tag query. 

But I'm still seeing symptoms on my physical device (Android 7.1).
Fresh install, hit the globe button

![en_european2](https://user-images.githubusercontent.com/7358010/41588478-131df144-73dc-11e8-8136-ca9bb7cfbf70.png)

console log shows kmw_console_error
```
kmw_console_error, Bundle[{keyboardVersion=1.6, cm_lineNumber=328, keyboardID=european2, firebase_event_origin(_o)=app, firebase_error_length(_el)=140, firebase_error_value(_ev)=cm_message, firebase_error(_err)=4, cm_sourceID=file:///data/user/0/com.tavultesoft.kmapro.debug/app_data/keyman.js, keyboardName=EuroLatin2 Keyboard, keyboardType=INAPP, packageID=cloud}]
06-19 16:18:10.687 29804-29856/com.tavultesoft.kmapro.debug V/FA: Connection attempt already in pro
```

I can then add `sil_bwe_karen` and `arabic_izza` keyboards. But switching to keyboards gives similar console errors.

**Comment by darcywong00** [comment]
console error for `sil_bwe_karen`
```
kmw_console_error, Bundle[{keyboardVersion=1.0, cm_lineNumber=328, keyboardID=sil_bwe_karen, firebase_event_origin(_o)=app, firebase_error_length(_el)=140, firebase_error_value(_ev)=cm_message, firebase_error(_err)=4, cm_sourceID=file:///data/user/0/com.tavultesoft.kmapro.debug/app_data/keyman.js, keyboardName=Bwe Karen (SIL), keyboardType=INAPP, packageID=cloud}]
06-19 16:20:32.823 29804-30173/com.tavultesoft.kmapro.debug D/FA: Logging event (FE):
```

I wonder if the KMW namespacing `bwe-Latn_sil_bwe_karen` is having issues with the hyphen separator...

**Comment by darcywong00** [comment]
From the debugger, the console error message from KMW is
`Ignored attempt to cancel a touchcancel event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.`
line 328
