### ISSUE TITLE
[Windows] Windows 7, shift and CAPS lock state reversed

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#993]
In Windows 7, shift and CAPS lock state is reversed.
Please check.

**Comment by mcdurdin** [comment]
We need a test keyboard to reproduce an issue; can you give some examples of what you mean? Also which version of Keyman are you using?

**Comment by MayuraVerma** [comment]
@mcdurdin Mark, I had shared it with you on DM.

Shift state keys are outputting the CAPS state keys intended output and vice versa in Windows 7.
Windows 10 is working fine.

I am using Keyman version 10.0.1108.0

**Comment by mcdurdin** [comment]
Can you provide a minimal example keyboard which demonstrates the problem so that anyone who needs to work on this issue can do so? I don't want to share your keyboard on this issue.

**Comment by MayuraVerma** [comment]
@mcdurdin After a restart, its not happening anymore.

Should we still chase this?

**Comment by mcdurdin** [comment]
Okay let’s leave it. My guess: one of the shift keys had its down state “stuck”. This would explain the reversal. I have seen this in rare circumstances usually with interactions with another app. Pressing and releasing each of the modifier keys works around the problem. But rare.
