### ISSUE TITLE
bug(android): An inconsistency arises in the Android emulator when testing it with an external Bluetooth keyboard

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#9974]
### Describe the bug

Certain shortcut keys from the external (bluetooth) keyboard do not function as anticipated when evaluating Keyman app on Android emulators.

### Reproduce the bug

1. Install Keyman 17.0 alpha build in an Android emulator. (eg., API 21 / Andorid 5.0)
2. Open Keyman In-App. 
3. Connect the external Bluetooth keyboard to Windows 10 OS. 
4. Press the Tab key from the bluetooth keyboard. 
5. Noticed that it does not toggle to the next field. 
6. Press Ctrl + Tab keys from the keyboard. 
7. Noticed that it opens some other keyboards instead of opening the keyboard picker menu. 

I have attached the Screenshot for reference. 

..Tab key is not working

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/9f338a8c-334a-435e-be78-9f6f01ef67f5">

..keyboard picker menu is not opening after pressing Ctrl+Tab keys

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/6e3103e5-f178-4395-b8f0-d395bcfb1092">

### Expected behavior

Pressing Tab key should toggles to the next field. Also, pressing Ctrl+Tab key from the external bluetooth keyboard should open the Keyboard Picker menu. 

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16.0.142 stable, 17.0.205-alpha

### Operating system

Android 5.0, 9.0, 12.0

### Device

API 21, 28 and 31  Android Emulators from Android Studio

**Comment by darcywong00** [comment]
I think we should only test the interaction of the bluetooth keyboard with a physical device, and not the emulator.
There's other keys (even on a physical keyboard) that don't get to the emulator.

If you find <kbd>ctrl</kbd>+<kbd>tab</kbd> doesn't work on a physical device, then you can re-open this.
