### ISSUE TITLE
bug(android): The Android emulator exhibits incorrect results when tested with an external AZERTY keyboard

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#9975]
### Describe the bug

Typing some special keys from an external azerty keyboard doesn't produce the expected result in an Android emulator

### Reproduce the bug

1. Install Keyman 17.0.205- alpha build in an Android emulator. (eg., API21 / Android 5 OS)
2. Connect an external azerty keyboard. 
3. Open Keyman In-App.
4. Download and Install French Basic keyboard. 
5. Type on the 102 nd key. 
6. It shows the Asterisk (*) letter on the text input screen. 
7. Type Shift + 102 nd key from the external azerty keyboard. 
8. It shows µ on the screen. 

Seems to be an issue. 

I have attached the Screenshot for reference. 

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/5a40f372-1e10-43fe-8175-49259a7754d0">

### Expected behavior

Typing 102 nd key should output < symbol on the screen. Typing Shift + 102 nd key should output > symbol. 

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16.0.142 stable, 17.0.205-alpha

### Operating system

Android 5.0, 9.0, 12.0

### Device

API 21, 28 and 31  Android Emulators from Android Studio

**Comment by MattGyverLee** [comment]
Interesting. Is this a Bluetooth or wired keyboard? I've seen some weird Bluetooth AZERTYs.

Those are the output for [NCAPS K_BKSLASH]. What do you get for [NCAPS K_BKSLASH]?  Maybe they're swapped somewhere.

**Comment by darcywong00** [comment]
I'll take a look next week when I'm back at my desk with an AZERTY keyboard to repro

**Comment by mcdurdin** [comment]
Again, let's only test hardware keyboards with a physical device, not emulator -- the emulator adds extra layer of complexity with the host OS.
