### ISSUE TITLE
bug(android): The keyboard disappeared after changing the orientation of the on-screen keyboard from Portrait to Landscape in Android 13 

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#9978]
### Describe the bug

I observed that adjusting the height of the on-screen keyboard caused it to vanish in the Keyman In-App. This issue is specific to the most recent Android 13 version.

### Reproduce the bug

1. Install Keyman 17.0.208-alpha build.
2. Open Keyman In-App.
3. Open the Settings menu. 
4. Open Adjust keyboard height menu.
5. Set the height to the maximum size. 
6. Revert to Keyman Home screen. 
7. Change the Orientation from Portrait to Landscape. 

Here, I noticed that the On-Screen Keyboard disappeared from the keyman home screen. Rotating to Portrait Orientation does not show up OSK in the home screen. 

..Set to Maximum height

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/ebf1215a-a76d-4286-b2c3-6c47f2dad962">

..OSK is missing after the rotation (P-to-L)

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/0201107a-91aa-4a38-9b06-9c5e0e1c8e6a">

..OSK is still missing after the change to the default position (L-to-P)

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/602cd389-956b-4460-9fd7-5b61538ec0ee">

### Expected behavior

The Keyboard should be visible after changing the orientation from Portrait-to-Landscape.

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.208-alpha

### Operating system

Android 13

### Device

Samsung Galaxy A23 5G Mobile

### Keyboard name

English - EuroLatin (SIL) Keyboard

### Keyboard version

2.0.4

### Language name

English

**Comment by darcywong00** [comment]
I can repro with the in-app keyboard. Doesn't seem to occur with system keyboard.
